// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    "id": "SP15-011",
    "name": "Biolumina Night Grid",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, cyberpunk-grime, violent-neon, blackout-chaos, watermark, text, logo",
    "style": {
      "aesthetic": "Community biopunk night district where engineered organisms provide light, data, and care services.",
      "form_and_line": "Bio-reactor terraces, vascular conduit arcs, and pod-like neighborhood hubs.",
      "color_palette": "Fluorescent cyan, chlorophyll green, and deep midnight indigo.",
      "lighting_setup": "Pulsed bioluminescent emissions with damp ground reflections and moon spill.",
      "material_texture": "Gel membranes, porous bioceramics, wet stone, and mycelial conduits.",
      "render_quality": "Atmospheric concept art with crisp biotech legibility and safe-path readability.",
      "spatial_distortion": "Layered vertical district depth linked by glowing metabolic corridors.",
      "atmosphere": "Nurturing experimentation, civic trust, and living-system intelligence.",
      "key_features": "Gene-lit avenues, communal wetlabs, symbiotic canopy nodes, and bio-signal kiosks.",
      "creative_brief": "A biopunk neighborhood where public biotech replaces brittle utilities and creates a visibly living urban metabolism."
    }
  },
  {
    "id": "SP15-018",
    "name": "Gene Garden Borough",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, body-horror-gore, dystopian-abuse, militarized-lab, watermark, text, logo",
    "style": {
      "aesthetic": "Biopunk neighborhood where genomic craft and public ecology co-evolve.",
      "form_and_line": "Organically branching labs, tendon-like bridges, and modular grow pods.",
      "color_palette": "Chlorophyll green, sterile white, and bio-lilac accents.",
      "lighting_setup": "Diffused lab daylight with pulsing specimen chamber glow.",
      "material_texture": "Wet biogel membranes, matte ceramic bioreactors, and mycelial composite walls.",
      "render_quality": "Advanced concept art with clean scientific readability and emotional warmth.",
      "spatial_distortion": "Interlaced district perspective linking street clinics to elevated biofarms.",
      "atmosphere": "Experimental care, ethical tension, and hopeful adaptation.",
      "key_features": "Community gene clinic, edible tissue greenhouses, open-source wetlab kiosks.",
      "creative_brief": "A biopunk borough where biotechnology is treated as public infrastructure instead of private power."
    }
  },
  {
    "id": "SP15-103",
    "name": "Mycelial Transit Spine",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, cyberpunk-grime, violent-neon, watermark, text, logo, rust",
    "style": {
      "aesthetic": "Public transit corridor grown from mycelial structures and bioceramic ribs.",
      "form_and_line": "Spine-like tunnels, branching nodes, and soft archways.",
      "color_palette": "Mushroom cream, moss green, and dusk violet.",
      "lighting_setup": "Subsurface glow and soft bioluminescent pulses.",
      "material_texture": "Fungal felt, porous ceramic, and damp stone.",
      "render_quality": "Clean biotech concept with organic legibility.",
      "spatial_distortion": "Long corridor depth with branching cellular ribs.",
      "atmosphere": "Adaptive infrastructure, calm motion, and living-system trust.",
      "key_features": "Mycelial rails, transit pods, and nutrient maintenance nodes.",
      "creative_brief": "A biopunk transit spine where the city moves through a living fungal backbone."
    }
  },
  {
    "id": "SP15-104",
    "name": "Symbiont Market Canopy",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, dystopian, harsh-neon, watermark, text, logo, grime",
    "style": {
      "aesthetic": "Open-air market sheltered by symbiotic canopy organisms.",
      "form_and_line": "Tented bio-canopies, hanging pods, and curved vendor aisles.",
      "color_palette": "Leaf green, coral pink, and pearl white.",
      "lighting_setup": "Dappled canopy light with gentle bioglow accents.",
      "material_texture": "Living fabric, translucent membranes, and woven fiber.",
      "render_quality": "Bright civic biotech scene with highly readable stalls.",
      "spatial_distortion": "Sweeping market aisle under layered living roofs.",
      "atmosphere": "Exchange, nourishment, and mutual dependence.",
      "key_features": "Symbiotic stalls, nutrient kiosks, and canopy vent petals.",
      "creative_brief": "A biopunk marketplace where commerce is sheltered by cooperative living architecture."
    }
  },
  {
    "id": "SP15-105",
    "name": "Genome Garden Forum",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, sterile, cyberpunk, watermark, text, logo, flat-light",
    "style": {
      "aesthetic": "Public forum embedded inside a genomic garden landscape.",
      "form_and_line": "Spiral forum seats, petal-like lab alcoves, and DNA trellis curves.",
      "color_palette": "Chlorophyll green, rose amber, and clean white.",
      "lighting_setup": "Bright diffused daylight with reflective leaf scatter.",
      "material_texture": "Living trellises, polished bio-glass, and soft soil beds.",
      "render_quality": "Elegant civic biotech concept art.",
      "spatial_distortion": "Amphitheater depth framed by botanical layers.",
      "atmosphere": "Debate, cultivation, and intelligent stewardship.",
      "key_features": "Genome benches, pollen displays, and bio-learning panels.",
      "creative_brief": "A biopunk forum where public discourse grows inside a carefully tended living garden of knowledge."
    }
  },
  {
    "id": "SP15-106",
    "name": "Nerve Loom Clinic",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, horror, harsh-metal, watermark, text, logo, slime-gross",
    "style": {
      "aesthetic": "Community clinic weaving neural repair through tactile living systems.",
      "form_and_line": "Loom frames, soft treatment alcoves, and filament pathways.",
      "color_palette": "Soft cyan, eucalyptus green, and porcelain.",
      "lighting_setup": "Clean clinical glow softened by living tissue luminescence.",
      "material_texture": "Biofabric threads, gel pads, and matte ceramic.",
      "render_quality": "Gentle biotech interior with humane readability.",
      "spatial_distortion": "Loom-centered floor plan with radial patient bays.",
      "atmosphere": "Care, repair, and embodied trust.",
      "key_features": "Nerve looms, bioscan petals, and restorative membranes.",
      "creative_brief": "A biopunk clinic where healing is woven rather than assembled."
    }
  },
  {
    "id": "SP15-107",
    "name": "Coral Laboratory Promenade",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, cyberpunk, storm-chaos, watermark, text, logo, over-dark",
    "style": {
      "aesthetic": "Seaside promenade adjoining coral research labs and tidewalks.",
      "form_and_line": "Reef terraces, promenade rails, and rounded lab domes.",
      "color_palette": "Coral red, aqua, and pearl gray.",
      "lighting_setup": "Sea shimmer and bright coastal diffusion.",
      "material_texture": "Calcium-like structures, glassy bio-panels, and wet stone.",
      "render_quality": "Coastal biotech concept art with graceful clarity.",
      "spatial_distortion": "Promenade vanishing point crossing reef terraces.",
      "atmosphere": "Exploration, stewardship, and aquatic curiosity.",
      "key_features": "Coral benches, tide instruments, and reef observation pods.",
      "creative_brief": "A biopunk shoreline where marine research and public leisure share the same living promenade."
    }
  },
  {
    "id": "SP15-108",
    "name": "Biofoundry Commons",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, aggressive-industrial, cyberpunk, watermark, text, logo, grime",
    "style": {
      "aesthetic": "Shared fabrication commons where living materials are grown in public.",
      "form_and_line": "Worktables, organoid trays, and soft factory arches.",
      "color_palette": "Warm white, moss, and amber biolight.",
      "lighting_setup": "Workshop daylight and internal growth lamps.",
      "material_texture": "Bio-foam, smooth glass, and plant-fiber mesh.",
      "render_quality": "Productive civic biotech with clear process readability.",
      "spatial_distortion": "Open plan with radial fabrication bays.",
      "atmosphere": "Collaboration, invention, and ecological pragmatism.",
      "key_features": "Growth trays, living molds, and shared maker stations.",
      "creative_brief": "A biopunk commons where citizens co-grow materials for their city."
    }
  },
  {
    "id": "SP15-109",
    "name": "Living Bridge District",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, militaristic, neon-gloom, watermark, text, logo, decay",
    "style": {
      "aesthetic": "City district linked by living bridges that heal and adapt over time.",
      "form_and_line": "Spanning bio-arches, ribbed walkways, and root anchors.",
      "color_palette": "Sap green, cloud white, and soft amber.",
      "lighting_setup": "Sky daylight filtered through translucent living spans.",
      "material_texture": "Root fiber, bio-resin, and woven membrane.",
      "render_quality": "Infrastructure concept with lush organic engineering.",
      "spatial_distortion": "Bridge grid crossing layered urban terraces.",
      "atmosphere": "Connection, resilience, and responsive infrastructure.",
      "key_features": "Living spans, root anchors, and adaptive footpaths.",
      "creative_brief": "A biopunk district where the bridges are alive and the city’s circulation is grown rather than built."
    }
  },
  {
    "id": "SP15-110",
    "name": "Spore Signal Plaza",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, horror, grimdark, watermark, text, logo, over-saturation",
    "style": {
      "aesthetic": "Civic plaza using spore networks as signal, memory, and public interface.",
      "form_and_line": "Central plaza rings, spore towers, and branching signal petals.",
      "color_palette": "Mushroom beige, moss green, and twilight blue.",
      "lighting_setup": "Gentle bioluminescent signal pulses and reflected plaza light.",
      "material_texture": "Fungal surfaces, wet stone, and translucent growth membranes.",
      "render_quality": "Symbolic biotech cityscape with legible circulation.",
      "spatial_distortion": "Plaza-centered circular layout with branching signal arms.",
      "atmosphere": "Communication, adaptation, and communal intelligence.",
      "key_features": "Spore beacons, memory spores, and public signal blooms.",
      "creative_brief": "A biopunk plaza where spores carry the city’s messages like living civic infrastructure."
    }
  },
  {
    "id": "SP15-111",
    "name": "Tissue Archive Pavilion",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, horror, gore, watermark, text, logo, messy-clutter",
    "style": {
      "aesthetic": "Memory archive grown from preserved tissue patterns and soft shell structures.",
      "form_and_line": "Pavilion ribs, archive drawers, and layered specimen shelves.",
      "color_palette": "Pearl, muted coral, and quiet jade.",
      "lighting_setup": "Museum diffusion with internal biological glow.",
      "material_texture": "Bio-glass, preserved membranes, and smooth ceramic.",
      "render_quality": "Museum-grade biotech concept with fragile elegance.",
      "spatial_distortion": "Pavilion shell focused on a central specimen spine.",
      "atmosphere": "Preservation, contemplation, and scientific tenderness.",
      "key_features": "Tissue drawers, bio-index panels, and preservation domes.",
      "creative_brief": "A biopunk archive that treats living tissue as both record and artifact."
    }
  },
  {
    "id": "SP15-112",
    "name": "Chloroplast Housing Stack",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, dystopian, dystopic, watermark, text, logo, cold-grit",
    "style": {
      "aesthetic": "Residential stack where chloroplast systems power light and air.",
      "form_and_line": "Terrace stacks, leaf panels, and sun-capture fins.",
      "color_palette": "Verdant green, cream, and honey amber.",
      "lighting_setup": "Sunlit facades with diffuse interior glow.",
      "material_texture": "Leaf-film, timber composites, and matte bioceramic.",
      "render_quality": "Warm housing concept with strong environmental readability.",
      "spatial_distortion": "Vertical terraced stack rising like a living garden tower.",
      "atmosphere": "Domestic comfort, ecological intelligence, and bright stability.",
      "key_features": "Chloroplast panels, air gardens, and terrace nurseries.",
      "creative_brief": "A biopunk home stack where the building behaves like a giant productive leaf."
    }
  },
  {
    "id": "SP15-113",
    "name": "Stemcell Harbor",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, hospital-gore, cyberpunk, watermark, text, logo, grime",
    "style": {
      "aesthetic": "Harbor district devoted to regenerative stemcell care and logistics.",
      "form_and_line": "Dock curves, treatment pods, and fluid container towers.",
      "color_palette": "Seafoam, pearl white, and muted aqua.",
      "lighting_setup": "Harbor daylight with soft water bounce.",
      "material_texture": "Wet bio-panels, translucent tubes, and ceramic docks.",
      "render_quality": "Clean maritime biotech concept with calm precision.",
      "spatial_distortion": "Dock perspective leading to regenerative intake pods.",
      "atmosphere": "Recovery, exchange, and compassionate infrastructure.",
      "key_features": "Stemcell clinics, tide docks, and restorative capsules.",
      "creative_brief": "A biopunk harbor where the port itself participates in healing and renewal."
    }
  },
  {
    "id": "SP15-114",
    "name": "Organ Garden Observatory",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, gore, horror, neon, watermark, text, logo",
    "style": {
      "aesthetic": "Observatory embedded in an organ garden of living sensory structures.",
      "form_and_line": "Dome observatory, organic petals, and ribbed growth platforms.",
      "color_palette": "Soft rose, algae green, and pale ivory.",
      "lighting_setup": "Celestial moonlight mixed with internal bioglow.",
      "material_texture": "Living membranes, polished lens glass, and soft organic ribs.",
      "render_quality": "Surreal but readable biotech concept art.",
      "spatial_distortion": "Dome-centered observatory with layered organ gardens.",
      "atmosphere": "Awe, measurement, and organic wonder.",
      "key_features": "Organ blooms, sensor domes, and growth benches.",
      "creative_brief": "A biopunk observatory where cultivated living organs study the sky."
    }
  },
  {
    "id": "SP15-115",
    "name": "Bioglass Rain Atrium",
    "category": "3. Corepunk — Biopunk",
    "negativePrompt": "photoreal, dark-industrial, cyberpunk, watermark, text, logo, muddy",
    "style": {
      "aesthetic": "Rain-harvesting atrium with bioglass surfaces and living channels.",
      "form_and_line": "Tall atrium shaft, catch basins, and vine-laced downspouts.",
      "color_palette": "Clear aqua, moss, and sunlit white.",
      "lighting_setup": "Rain-diffused skylight and reflective wet surfaces.",
      "material_texture": "Bioglass, living fiber, and smooth stone.",
      "render_quality": "Bright infrastructure illustration with environmental clarity.",
      "spatial_distortion": "Atrium verticality with layered water flow.",
      "atmosphere": "Renewal, abundance, and climate adaptation.",
      "key_features": "Rain catchers, bioglass walls, and water nerve channels.",
      "creative_brief": "A biopunk rain atrium where water collection is expressed as elegant living architecture."
    }
  }
] as unknown as StyleRuntimePreset[];
