// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP15-107',
    name: 'Vaporpunk',
    category: '7. Media, Vapor & Glitch Punks',
    negativePrompt:
      'a mandatory mall, arcade, CRT, or empty commercial interior, heavy glitch effects, pastel haze that erases the focal subject, an unrequested coast, ocean, palm silhouette, sunset horizon, or scenic window view',
    style: {
      aesthetic:
        'Use pastel retro-consumer futurism: checker or tiled planes, contained pastel gradients, chrome-trimmed curves, soft cathode halos, and shallow reflections on existing surfaces create synthetic nostalgia without adding a new landscape or view.',
      subject_treatment:
        'Preserve the requested subject, action, setting, and framing; let selected existing planes, edges, or reflections carry tile geometry and softened retro color. Do not add a window, coastline, ocean, palms, or sunset scene to communicate Vaporpunk.',
      color_and_tone:
        'Blend lavender, pale cyan, pink, cream, and washed teal in localized planes or reflections, with chrome or dark purple used sparingly for structure; retain the requested focal contrast and palette.',
      lighting_and_shadow:
        'Preserve the requested light source, direction, and time of day; use gradients as surface color and keep any cathode-like halo local rather than bathing the scene in sunset light.',
      texture_and_material:
        'Combine smooth tile, chrome trim, glassy reflections, and softly faded print; keep surfaces calm and avoid adding digital glitch artifacts.',
      camera_and_composition:
        'Use receding tile divisions or gentle reflective bands to lead toward the subject; preserve the requested setting and keep the background subordinate.',
      atmosphere_and_mood:
        'Suggest dreamy consumer-retro nostalgia through restrained color and surface rhythm; do not introduce a coast, horizon, sunset view, or commercial interior.',
      rendering_and_quality:
        'Keep large shapes soft-edged but defined, with concise highlights and enough contrast for a readable thumbnail.',
    },
    ui: {
      kind: 'full_style',
      derivedFrom: ['SP15-107'],
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP15-108',
    name: 'Cassette Futurism',
    category: '7. Media, Vapor & Glitch Punks',
    negativePrompt:
      'a required cassette deck or weather station, modern glossy touch-screen minimalism, dense controls that collapse into noise',
    style: {
      aesthetic:
        'Build a tactile late-analog design language from chunky rounded rectangles, cassette-window shapes, paired reels, slider rows, and cable loops, with the geometry applied selectively to forms rather than requiring a cassette as the subject.',
      subject_treatment:
        'Preserve the requested subject and action; give unspecified equipment, clothing panels, or environmental edges molded analog contours, smoked windows, and a few mechanical controls without adding a full control console.',
      color_and_tone:
        'Favor warm cream, amber, graphite, and restrained teal or blue-green indicators; keep the large masses warm and quiet, with small colored signals providing contrast.',
      lighting_and_shadow:
        'Use broad panel highlights, soft amber lamp glow, and dark window recesses to reveal molded depth; keep reflections graphic and localized instead of glossy product photography.',
      texture_and_material:
        'Contrast matte molded plastic, brushed metal edges, translucent smoked inserts, and visible tape-like ribbons; use wear at corners and controls, not a blanket vintage filter.',
      camera_and_composition:
        'Organize the focal form through nested rounded frames and linked ribbons or cable curves; preserve depth and action, and avoid arranging every image as a centered device catalog shot.',
      atmosphere_and_mood:
        "Suggest an intimate, repairable analog future: practical, lived-in, and quietly optimistic, with the source subject's own emotional tone intact.",
      rendering_and_quality:
        'Use clean illustrated surfaces, readable control silhouettes, and restrained grain; separate large panel geometry from tiny buttons at thumbnail scale.',
    },
    ui: {
      kind: 'full_style',
      derivedFrom: ['SP15-108'],
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP15-109',
    name: 'Broadcastpunk',
    category: '7. Media, Vapor & Glitch Punks',
    negativePrompt:
      'a mandatory television studio, monitor wall, or scene-wide screen frame, digital pixel breakup as the dominant effect, scanlines across all forms, unrequested screen labels, readable UI text, or picture-in-picture framing',
    style: {
      aesthetic:
        'Make analog transmission and pirate television tangible through phosphor linework, antenna-like arcs, coaxial routes, broadcast color bars, and occasional red tally marks applied to existing forms; do not frame the scene inside a screen or add television hardware unless requested.',
      subject_treatment:
        'Preserve the requested subject, action, setting, and framing; apply signal marks within the existing composition and never display the entire scene as television content.',
      color_and_tone:
        'Use graphite, warm black, phosphor green, cyan, cream, and a controlled red signal accent on existing surfaces; keep the focal subject brighter and clearer than surrounding signal marks.',
      lighting_and_shadow:
        'Preserve the requested base illumination; keep any phosphor-like glow small and confined to signal marks rather than darkening the scene or adding illuminated hardware.',
      texture_and_material:
        'Use scanline-like strokes and analog noise as localized graphic marks on existing forms; do not add glass screens, metal bezels, or cable objects when they are not part of the requested scene.',
      camera_and_composition:
        'Preserve the requested composition; use one or two signal arcs or short scanline zones within existing surfaces, never a frame around the full scene or duplicate images.',
      atmosphere_and_mood:
        'Suggest unauthorized transmission, community media, or fragile connection without requiring a station, crowd, or political message.',
      rendering_and_quality:
        "Keep frame edges and signal marks distinct, limit scanlines to visible signal zones, and preserve the focal subject's silhouette.",
    },
    ui: {
      kind: 'full_style',
      derivedFrom: ['SP15-109'],
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP15-110',
    name: 'Glitchpunk',
    category: '7. Media, Vapor & Glitch Punks',
    negativePrompt:
      'global image tearing or unreadable pixel noise, analog scanlines and monitor frames dominating the image, glitch marks that alter identity or anatomy',
    style: {
      aesthetic:
        "Break a clean digital image locally with displaced RGB contours, compression blocks, clipped pixel clusters, and interrupted interface-like fragments, keeping most of the subject's structure stable.",
      subject_treatment:
        'Preserve the requested subject, identity, and action; offset only selected edges, reflections, or secondary details so corruption reads as a deliberate digital disturbance rather than anatomy damage.',
      color_and_tone:
        'Use a stable base palette with brief cyan, magenta, or red channel slips; keep the main value grouping coherent and avoid converting every region into neon.',
      lighting_and_shadow:
        'Maintain the underlying light logic and use channel offsets as graphic edge events; do not let glitch marks act as an all-over lighting effect.',
      texture_and_material:
        'Contrast clean rendered regions with sparse pixel stair-steps, compression smears, and raster breaks; avoid analog dust, film grain, and physical paper textures.',
      camera_and_composition:
        'Preserve the requested camera and silhouette; use a few short horizontal or stepped disruptions, with negative space around the focal form.',
      atmosphere_and_mood:
        'Create unstable, rebellious digital energy without implying a specific device, game interface, or cyberpunk city.',
      rendering_and_quality:
        'Keep corruption sharply localized and the core subject readable at thumbnail scale; preserve facial, limb, and object continuity.',
    },
    ui: {
      kind: 'full_style',
      derivedFrom: ['SP15-110'],
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP15-224',
    name: 'Filmpunk',
    displayName: 'Filmpunk',
    styleAnchors: ['Filmpunk', 'celluloid projection culture punk', 'projector beams'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'celluloid projection culture punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Filmpunk: a culture built around physical celluloid, with projection booths, film strips hung like laundry, splicing benches and beams of light through dust.',
      subject_treatment:
        "Keep the prompt's subject and setting; surround it with reels, hanging film strips, projectors and projected beams of light.",
      color_and_tone:
        'Warm amber projector light, deep cinema reds and blacks with sepia celluloid tones.',
      lighting_and_shadow: 'A single bright projector beam cutting through dusty darkness.',
      texture_and_material:
        'Celluloid strips, metal reels, brass projectors, velvet seats, floating dust.',
      camera_and_composition:
        'Dark rooms crossed by beams, with film strips looping through the frame.',
      atmosphere_and_mood: 'Romantic, flickering and nostalgic, dreams made of light and plastic.',
      rendering_and_quality:
        'Warm cinematic illustration with light beams and fine dust particles.',
      creative_brief:
        "Filmpunk: a culture built around physical celluloid, with projection booths, film strips hung like laundry, splicing benches and beams of light through dust. Carry it through projector beams, hanging film strips, splicing benches, floating dust. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'projector beams; hanging film strips; splicing benches; floating dust',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-225',
    name: 'Camcorderpunk',
    displayName: 'Camcorderpunk',
    styleAnchors: ['Camcorderpunk', 'home video camcorder punk', 'shaky handheld framing'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'home video camcorder punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Camcorderpunk: the world through a 1990s home camcorder, with shaky handheld framing, soft video blur, blown highlights, tape tracking lines and family-event chaos.',
      subject_treatment:
        "Keep the prompt's subject and setting; show it as handheld home video footage, shaky, softly blurred and badly exposed.",
      color_and_tone:
        'Oversaturated warm video colors, blown whites and muddy shadows with slight color bleed.',
      lighting_and_shadow: 'Harsh on-camera light or blown window light, flat and unflattering.',
      texture_and_material:
        'Video noise, tracking lines, soft focus, chromatic bleed and interlace texture.',
      camera_and_composition:
        'Tilted handheld framing, awkward zooms and subjects half out of frame.',
      atmosphere_and_mood: 'Chaotic, intimate and funny, memories nobody meant to make beautiful.',
      rendering_and_quality:
        'Authentic low-resolution video rendering with noise, bleed and tracking lines.',
      creative_brief:
        "Camcorderpunk: the world through a 1990s home camcorder, with shaky handheld framing, soft video blur, blown highlights, tape tracking lines and family-event chaos. Carry it through shaky handheld framing, tracking lines, blown highlights, color bleed. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'shaky handheld framing; tracking lines; blown highlights; color bleed',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-226',
    name: 'Dialuppunk',
    displayName: 'Dialuppunk',
    styleAnchors: ['Dialuppunk', 'early internet dial-up punk', 'beige towers'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'early internet dial-up punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Dialuppunk: the early home internet, with beige tower computers, glowing modem lights, tangled phone cords, clunky 3D avatars and bedrooms lit by a single monitor.',
      subject_treatment:
        "Keep the prompt's subject and setting; surround it with beige computers, modems, phone cords and early low-poly virtual worlds.",
      color_and_tone:
        'Beige plastic, CRT blue glow and dark bedrooms with bright primary low-poly colors.',
      lighting_and_shadow: 'Faces lit only by a blue monitor glow and small green modem lights.',
      texture_and_material:
        'Beige plastic, coiled phone cords, keyboard grime, low-poly shapes and dithering.',
      camera_and_composition: 'Cramped bedroom desks at night and chunky early virtual spaces.',
      atmosphere_and_mood:
        'Lonely, curious and exciting, the first time the whole world connected.',
      rendering_and_quality:
        'Nostalgic illustration mixing warm room detail with dithered low-poly worlds.',
      creative_brief:
        "Dialuppunk: the early home internet, with beige tower computers, glowing modem lights, tangled phone cords, clunky 3D avatars and bedrooms lit by a single monitor. Carry it through beige towers, modem lights, tangled cords, low-poly avatars. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'beige towers; modem lights; tangled cords; low-poly avatars',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-227',
    name: 'Teletextpunk',
    displayName: 'Teletextpunk',
    styleAnchors: ['Teletextpunk', 'chunky mosaic broadcast page punk', 'coarse mosaic cells'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'chunky mosaic broadcast page punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Teletextpunk: everything built from chunky blocky mosaic graphics of old broadcast pages, with eight flat colors, stepped edges and black backgrounds.',
      subject_treatment:
        "Keep the prompt's subject and setting; reduce it to coarse block mosaic shapes of eight flat colors on black, without letters.",
      color_and_tone:
        'Pure black backgrounds with saturated red, green, yellow, blue, magenta, cyan and white blocks.',
      lighting_and_shadow: 'Flat screen glow with no shading, only solid mosaic cells.',
      texture_and_material:
        'Coarse rectangular mosaic cells, stepped diagonals and slight screen glow.',
      camera_and_composition: 'Flat centered page-like compositions made entirely of large blocks.',
      atmosphere_and_mood: 'Charming, crude and futuristic, a past idea of the digital future.',
      rendering_and_quality: 'Strict coarse mosaic rendering with solid cells and glowing edges.',
      creative_brief:
        "Teletextpunk: everything built from chunky blocky mosaic graphics of old broadcast pages, with eight flat colors, stepped edges and black backgrounds. Carry it through coarse mosaic cells, eight flat colors, black background, stepped edges. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'coarse mosaic cells; eight flat colors; black background; stepped edges',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-228',
    name: 'Y2Kpunk',
    displayName: 'Y2Kpunk',
    styleAnchors: ['Y2Kpunk', 'millennium chrome future punk', 'liquid chrome'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'millennium chrome future punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Y2Kpunk: the millennium future, with liquid chrome blobs, translucent candy-colored plastics, inflatable furniture, bubble shapes and glossy techno optimism.',
      subject_treatment:
        "Keep the prompt's subject and setting; restyle it with liquid chrome, translucent candy plastic and bubbly inflatable shapes.",
      color_and_tone:
        'Iridescent silver, icy blue, candy pink and lime with translucent tints and bright white.',
      lighting_and_shadow:
        'Glossy studio light with bright specular reflections on chrome and plastic.',
      texture_and_material:
        'Liquid chrome, translucent colored plastic, inflatable vinyl and holographic sheen.',
      camera_and_composition:
        'Glossy centered hero shots and wide-angle distortion with bubbly shapes.',
      atmosphere_and_mood: 'Optimistic, shiny and hyper, the future as a glossy toy.',
      rendering_and_quality:
        'High-gloss CGI-like rendering with clean reflections and bubbly forms.',
      creative_brief:
        "Y2Kpunk: the millennium future, with liquid chrome blobs, translucent candy-colored plastics, inflatable furniture, bubble shapes and glossy techno optimism. Carry it through liquid chrome, translucent plastic, inflatable furniture, bubble shapes. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'liquid chrome; translucent plastic; inflatable furniture; bubble shapes',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-229',
    name: 'Idolpunk',
    displayName: 'Idolpunk',
    styleAnchors: ['Idolpunk', 'manufactured pop idol media punk', 'holographic stages'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'manufactured pop idol media punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Idolpunk: an original pop-idol machine, with holographic stages, glowing fan lightsticks, sparkling costumes and a factory-like media world behind the glamour.',
      subject_treatment:
        "Keep the prompt's subject and setting; turn it into a glittering idol performance with holographic stages, lightsticks and a media machine behind it.",
      color_and_tone:
        'Candy pastels and sparkling whites with seas of colored lightsticks in darkness.',
      lighting_and_shadow: 'Blazing stage spotlights and glowing crowds against dark arenas.',
      texture_and_material:
        'Sequins, glitter, holographic foil, stage smoke and glossy plastic sticks.',
      camera_and_composition: 'Performers centered on huge stages with oceans of fan lights below.',
      atmosphere_and_mood: 'Dazzling and slightly uneasy, joy manufactured at industrial scale.',
      rendering_and_quality: 'Glossy sparkling illustration with bright stage light and glitter.',
      creative_brief:
        "Idolpunk: an original pop-idol machine, with holographic stages, glowing fan lightsticks, sparkling costumes and a factory-like media world behind the glamour. Carry it through holographic stages, seas of lightsticks, sequin costumes, media machine. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'holographic stages; seas of lightsticks; sequin costumes; media machine',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-230',
    name: 'Faxpunk',
    displayName: 'Faxpunk',
    styleAnchors: ['Faxpunk', 'thermal fax paper punk', 'curling thermal paper'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'thermal fax paper punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Faxpunk: a world transmitted by fax, with curling thermal paper, streaky grey scan lines, crushed contrast and endless paper spilling from machines.',
      subject_treatment:
        "Keep the prompt's subject and setting; render it as a streaky fax transmission on curling thermal paper, spilling from a machine.",
      color_and_tone: 'Faded grey and black on warm thermal paper white, with fading brown edges.',
      lighting_and_shadow:
        'Harsh office fluorescent light with crushed fax contrast in the image itself.',
      texture_and_material:
        'Curling thermal paper, streaky horizontal scan lines, toner speckle and grain.',
      camera_and_composition:
        'Images emerging line by line from machines, paper piling on office floors.',
      atmosphere_and_mood: 'Urgent and bureaucratic, messages from far away arriving slowly.',
      rendering_and_quality: 'Low-fidelity fax rendering with streaks, speckle and crushed tones.',
      creative_brief:
        "Faxpunk: a world transmitted by fax, with curling thermal paper, streaky grey scan lines, crushed contrast and endless paper spilling from machines. Carry it through curling thermal paper, scan streaks, crushed contrast, spilling paper. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'curling thermal paper; scan streaks; crushed contrast; spilling paper',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-231',
    name: 'Microfichepunk',
    displayName: 'Microfichepunk',
    styleAnchors: ['Microfichepunk', 'microfiche archive punk', 'glowing reader screens'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'microfiche archive punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Microfichepunk: forgotten archives read through glowing microfiche machines, with tiny film cards, magnified grainy photographs and endless cabinets of drawers.',
      subject_treatment:
        "Keep the prompt's subject and setting; show it as a grainy magnified photograph glowing on a microfiche reader in a dim archive.",
      color_and_tone:
        'Negative-like greys, ghostly whites and sickly green reader glow in dark archive rooms.',
      lighting_and_shadow: 'The reader screen as the main light, lighting faces and dusty drawers.',
      texture_and_material:
        'Grainy magnified film, scratches, steel cabinets, dusty drawers and cards.',
      camera_and_composition: 'Close views of glowing screens and long rows of archive cabinets.',
      atmosphere_and_mood: 'Obsessive and eerie, secrets hidden in tiny squares of film.',
      rendering_and_quality: 'Grainy low-key rendering with scratched magnified film texture.',
      creative_brief:
        "Microfichepunk: forgotten archives read through glowing microfiche machines, with tiny film cards, magnified grainy photographs and endless cabinets of drawers. Carry it through glowing reader screens, magnified grain, archive drawers, film scratches. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'glowing reader screens; magnified grain; archive drawers; film scratches',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-232',
    name: 'Jukeboxpunk',
    displayName: 'Jukeboxpunk',
    styleAnchors: ['Jukeboxpunk', 'jukebox diner culture punk', 'glowing jukeboxes'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'jukebox diner culture punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Jukeboxpunk: mid-century diner culture centered on glowing jukeboxes, with bubble tubes, chrome grilles, neon arches, checkered floors and milkshake counters.',
      subject_treatment:
        "Keep the prompt's subject and setting; place it in a glowing diner world with jukeboxes, chrome, neon and checkered floors.",
      color_and_tone:
        'Cherry red, mint, cream and chrome with warm neon orange and bubble-tube rainbows.',
      lighting_and_shadow: 'Glowing jukebox light and neon reflections on chrome and vinyl booths.',
      texture_and_material:
        'Chrome, bubble tubes, red vinyl booths, checkered tile and glossy formica.',
      camera_and_composition:
        'Warm diner interiors with a jukebox glowing at the center of attention.',
      atmosphere_and_mood: 'Sweet, rebellious and nostalgic, rock and roll on a Saturday night.',
      rendering_and_quality: 'Glossy illustration with bright chrome reflections and neon glow.',
      creative_brief:
        "Jukeboxpunk: mid-century diner culture centered on glowing jukeboxes, with bubble tubes, chrome grilles, neon arches, checkered floors and milkshake counters. Carry it through glowing jukeboxes, bubble tubes, chrome grilles, checkered floors. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'glowing jukeboxes; bubble tubes; chrome grilles; checkered floors',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-233',
    name: 'Hologrampunk',
    displayName: 'Hologrampunk',
    styleAnchors: ['Hologrampunk', 'cheap hologram foil punk', 'rainbow diffraction'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'cheap hologram foil punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Hologrampunk: a world covered in cheap holographic foil and lenticular prints, with rainbow diffraction shifts, shimmering stickers and images that change as you move.',
      subject_treatment:
        "Keep the prompt's subject and setting; render its surfaces as shimmering holographic foil and lenticular prints with rainbow shifts.",
      color_and_tone:
        'Rainbow diffraction over silver foil with shifting cyan, magenta and gold bands.',
      lighting_and_shadow: 'Sharp point light creating rainbow flares and shifting bands on foil.',
      texture_and_material:
        'Holographic foil, lenticular ridges, diffraction patterns and glossy laminate.',
      camera_and_composition:
        'Close views of shimmering surfaces with images appearing to shift angle.',
      atmosphere_and_mood: 'Dazzling, cheap and magical, a trick of light you want to keep.',
      rendering_and_quality:
        'Crisp iridescent rendering with diffraction rainbows and fine ridges.',
      creative_brief:
        "Hologrampunk: a world covered in cheap holographic foil and lenticular prints, with rainbow diffraction shifts, shimmering stickers and images that change as you move. Carry it through rainbow diffraction, lenticular ridges, silver foil, shifting images. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'rainbow diffraction; lenticular ridges; silver foil; shifting images',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-234',
    name: 'Photoboothpunk',
    displayName: 'Photoboothpunk',
    styleAnchors: ['Photoboothpunk', 'photo booth strip culture punk', 'four-frame strips'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'photo booth strip culture punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Photoboothpunk: life told through coin photo booths, with four-frame vertical strips, harsh flash, pulled curtains and faces caught mid-laugh or mid-secret.',
      subject_treatment:
        "Keep the prompt's subject and setting; show it as a four-frame photo booth strip, the same framing repeated with a changing moment in each frame.",
      color_and_tone:
        'Silvery black and white or faded chemical color with bright flash-lit skin and dark booth backdrops.',
      lighting_and_shadow: 'Harsh frontal flash with flat faces and a hard dark falloff behind.',
      texture_and_material:
        'Glossy chemical print paper, slight developer stains, booth curtain fabric and rounded frame corners.',
      camera_and_composition:
        'Four stacked square frames from the same fixed close camera, each a different beat.',
      atmosphere_and_mood:
        'Spontaneous, intimate and mischievous, a tiny private theatre behind a curtain.',
      rendering_and_quality:
        'Authentic photo booth print rendering with flash glare, grain and slight chemical unevenness.',
      creative_brief:
        "Photoboothpunk: life told through coin photo booths, with four-frame vertical strips, harsh flash, pulled curtains and faces caught mid-laugh or mid-secret. Carry it through four-frame strips, harsh flash, fixed close camera, changing moments. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'four-frame strips; harsh flash; fixed close camera; changing moments',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-235',
    name: 'Carouselpunk',
    displayName: 'Carouselpunk',
    styleAnchors: ['Carouselpunk', 'slide projector memory punk', 'projected slides'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'slide projector memory punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Carouselpunk: family memories projected from rotating slide carousels, with dust-filled beams, warm color slides, clicking changes and living rooms turned into cinemas.',
      subject_treatment:
        "Keep the prompt's subject and setting; show it as a warm color slide projected onto a wall or sheet in a dark living room.",
      color_and_tone:
        'Warm saturated slide colors, faded magenta shifts and brown-dark living rooms.',
      lighting_and_shadow:
        'A single projector beam through dust and the glow of the projected image.',
      texture_and_material:
        'Slide film grain, dust in the beam, hanging bedsheets, wallpaper and carpet.',
      camera_and_composition:
        'Dark rooms with a glowing projected image and silhouettes of viewers.',
      atmosphere_and_mood: 'Warm, nostalgic and bittersweet, memories glowing on a wall.',
      rendering_and_quality: 'Warm grainy illustration with a luminous projected image and dust.',
      creative_brief:
        "Carouselpunk: family memories projected from rotating slide carousels, with dust-filled beams, warm color slides, clicking changes and living rooms turned into cinemas. Carry it through projected slides, dust beams, dark living rooms, viewer silhouettes. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'projected slides; dust beams; dark living rooms; viewer silhouettes',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-236',
    name: 'Screensaverpunk',
    displayName: 'Screensaverpunk',
    styleAnchors: ['Screensaverpunk', 'idle-screen screensaver punk', 'pipe mazes'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'idle-screen screensaver punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Screensaverpunk: the dreaming world of idle old computers, with endless pipe mazes, flying starfields, bouncing shapes and 3D forms drifting in black space.',
      subject_treatment:
        "Keep the prompt's subject and setting; render it as an early 3D screensaver scene with shiny primitive shapes drifting in black space.",
      color_and_tone:
        'Black backgrounds with shiny primary colored 3D primitives and white starfields.',
      lighting_and_shadow: 'Simple early 3D shading with bright hard specular highlights.',
      texture_and_material:
        'Glossy low-poly pipes, chrome spheres, smooth gradients and starfield dots.',
      camera_and_composition:
        'Endless looping motion through black space with shapes filling the frame.',
      atmosphere_and_mood: 'Hypnotic, lonely and dreamy, machines dreaming while nobody watches.',
      rendering_and_quality: 'Early 3D rendering with simple shading and glossy highlights.',
      creative_brief:
        "Screensaverpunk: the dreaming world of idle old computers, with endless pipe mazes, flying starfields, bouncing shapes and 3D forms drifting in black space. Carry it through pipe mazes, starfields, bouncing shapes, black space. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'pipe mazes; starfields; bouncing shapes; black space',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-237',
    name: 'Vinylpunk',
    displayName: 'Vinylpunk',
    styleAnchors: ['Vinylpunk', 'record culture vinyl punk', 'spinning grooves'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'record culture vinyl punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Vinylpunk: a culture built around vinyl records, with record-store crates, glossy black grooves, turntables, needle drops and walls of album sleeves.',
      subject_treatment:
        "Keep the prompt's subject and setting; surround it with vinyl records, turntables, crates and spinning grooves.",
      color_and_tone: 'Glossy black vinyl, warm wood and sleeve colors with warm lamp amber.',
      lighting_and_shadow: 'Warm lamps catching rainbow sheen in the grooves of spinning records.',
      texture_and_material:
        'Glossy grooves, cardboard sleeves, wooden crates, turntable metal and dust.',
      camera_and_composition: 'Close views of needles on grooves and crowded record shops.',
      atmosphere_and_mood: 'Warm, devoted and analog, music you can hold in your hands.',
      rendering_and_quality:
        'Warm detailed illustration with glossy groove highlights and soft dust.',
      creative_brief:
        "Vinylpunk: a culture built around vinyl records, with record-store crates, glossy black grooves, turntables, needle drops and walls of album sleeves. Carry it through spinning grooves, record crates, needle drops, groove sheen. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'spinning grooves; record crates; needle drops; groove sheen',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-238',
    name: 'Pinballpunk',
    displayName: 'Pinballpunk',
    styleAnchors: ['Pinballpunk', 'pinball machine world punk', 'flippers and bumpers'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'pinball machine world punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Pinballpunk: whole worlds built as pinball playfields, with flippers, bumpers, ramps, chrome balls and flashing lights under glass.',
      subject_treatment:
        "Keep the prompt's subject and setting; turn it into a pinball playfield world of ramps, bumpers, flippers and a racing chrome ball.",
      color_and_tone:
        'Bright primary playfield colors with chrome, flashing lamp oranges and deep backglass blacks.',
      lighting_and_shadow: 'Flashing bulbs and reflections under glass, bright chrome highlights.',
      texture_and_material:
        'Painted playfield wood, chrome ramps, rubber bumpers, glass and steel balls.',
      camera_and_composition: 'High angled views down the table with a chrome ball mid-flight.',
      atmosphere_and_mood: 'Frantic, flashing and playful, a whole world of chaos under glass.',
      rendering_and_quality:
        'Crisp glossy illustration with flashing lights and chrome reflections.',
      creative_brief:
        "Pinballpunk: whole worlds built as pinball playfields, with flippers, bumpers, ramps, chrome balls and flashing lights under glass. Carry it through flippers and bumpers, chrome ball, ramps under glass, flashing lamps. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'flippers and bumpers; chrome ball; ramps under glass; flashing lamps',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP15-239',
    name: 'Karaokepunk',
    displayName: 'Karaokepunk',
    styleAnchors: ['Karaokepunk', 'karaoke box culture punk', 'glitter microphones'],
    category: '7. Media, Vapor & Glitch Punks',
    domain: 'karaoke box culture punk',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, real brand or company logo, readable interface text or numerals, real celebrity likeness, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Karaokepunk: late-night karaoke rooms and bars, with glitter microphones, disco lights, tambourines, velvet sofas and friends singing with total commitment.',
      subject_treatment:
        "Keep the prompt's subject and setting; turn it into a late-night karaoke scene with microphones, disco lights and dramatic singers.",
      color_and_tone:
        'Hot pink, purple and blue disco light with glitter gold and velvet deep tones.',
      lighting_and_shadow: 'Spinning disco light spots and screen glow in small dark rooms.',
      texture_and_material:
        'Glitter microphones, velvet sofas, tambourines, drinks and mirrored balls.',
      camera_and_composition: 'Close dramatic singing poses with friends crowded around.',
      atmosphere_and_mood: 'Silly, heartfelt and loud, everyone is a star for three minutes.',
      rendering_and_quality: 'Colorful glowing illustration with disco light spots and glitter.',
      creative_brief:
        "Karaokepunk: late-night karaoke rooms and bars, with glitter microphones, disco lights, tambourines, velvet sofas and friends singing with total commitment. Carry it through glitter microphones, disco lights, velvet rooms, dramatic singers. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
      key_features: 'glitter microphones; disco lights; velvet rooms; dramatic singers',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
] as unknown as StyleRuntimePreset[];
