// Generated by scripts/generate-style-thumbnail-projections.ts.
// Add/remove style card thumbnails, then run `bun run styles:thumbnails`.

const STYLE_THUMBNAIL_PACK_LOADERS: Record<string, () => Promise<Record<string, string>>> = {
  pack_01: () =>
    import('./thumbnail_group_01').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_01'] ?? {}),
  pack_02: () =>
    import('./thumbnail_group_01').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_02'] ?? {}),
  pack_03: () =>
    import('./thumbnail_group_02').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_03'] ?? {}),
  pack_04: () =>
    import('./thumbnail_group_02').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_04'] ?? {}),
  pack_05: () =>
    import('./thumbnail_group_03').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_05'] ?? {}),
  pack_06: () =>
    import('./thumbnail_group_03').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_06'] ?? {}),
  pack_07: () =>
    import('./thumbnail_group_04').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_07'] ?? {}),
  pack_08: () =>
    import('./thumbnail_group_04').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_08'] ?? {}),
  pack_09: () =>
    import('./thumbnail_group_05').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_09'] ?? {}),
  pack_10: () =>
    import('./thumbnail_group_05').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_10'] ?? {}),
  pack_11: () =>
    import('./thumbnail_group_06').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_11'] ?? {}),
  pack_12: () =>
    import('./thumbnail_group_06').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_12'] ?? {}),
  pack_13: () =>
    import('./thumbnail_group_07').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_13'] ?? {}),
  pack_14: () =>
    import('./thumbnail_group_07').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_14'] ?? {}),
  pack_15: () =>
    import('./thumbnail_group_08').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_15'] ?? {}),
  pack_17: () =>
    import('./thumbnail_group_08').then((module) => module.STYLE_THUMBNAIL_PACKS['pack_17'] ?? {}),
};

export function loadGeneratedStyleThumbnailPack(packId: string) {
  return STYLE_THUMBNAIL_PACK_LOADERS[packId]?.() ?? Promise.resolve({});
}
