type BriefPack = { id: string };
type BriefPreset = { id: string; name: string; category?: string };

type SubjectPlan = {
  category: RegExp;
  subjects: readonly string[];
  framing: readonly string[];
};

type PackPlan = {
  categories: readonly SubjectPlan[];
  details: readonly string[];
};

const gameDetails = [
  'a small pickup or clue sits near the edge of the scene',
  'one short trail of light points toward the next route',
  'a distant landmark anchors the open play space',
  'one foreground shape gives the action a clear starting point',
  'a single secondary silhouette hints at scale',
  'a small patch of reflected color links foreground and distance',
  'the route through the scene stays visually open',
  'a restrained environmental cue supports the action without becoming another subject',
] as const;

const animeDetails = [
  'let an existing contour carry the visual rhythm',
  'keep one existing detail clear enough to anchor scale',
  'use the requested subject itself as the point of focus',
  'leave open space around the focal form without adding decoration',
  'balance detail with a quiet patch of background',
  'let the stated light separate form from setting',
  'keep secondary elements subordinate when the sample includes them',
  'make the main movement or structure readable in one clear arc',
] as const;

const mythDetails = [
  'one celestial shape anchors the distant background',
  'a single natural element echoes the central symbol',
  'one clear reflection connects the figure to the landscape',
  'a few small lights mark a path without forming letters',
  'a quiet band of open space balances the detailed forms',
  'a single animal silhouette gives the scene scale',
  'one repeated geometric mark ties the scene together',
  'a specific place grounds the scene instead of a generic fantasy collage',
] as const;

const punkDetails = [
  'one visible repair seam joins two different materials',
  'a short run of colored tape marks a practical fix',
  'one salvaged part remains distinct from the newer frame',
  'a few hand-painted blocks add color without readable slogans',
  'one rough cable or cord leads the eye toward the subject',
  'a small cluster of reused parts shows how the object was rebuilt',
  'one bright patch contrasts with worn surfaces',
  'the surrounding clutter stays low enough to keep the subject clear',
] as const;

const darkDetails = [
  'one warm light breaks the cool surrounding shadow',
  'a thin line of mist separates the near and far planes',
  'one small architectural detail gives the place a human scale',
  'a single pale accent draws attention to the focal action',
  'the silhouette stays distinct against the darkest area',
  'one distant opening suggests a route beyond the scene',
  'a few controlled marks carry the atmosphere without extra props',
  'surrounding forms frame the subject without making a card border',
] as const;

const gameFraming = [
  'separate the playable silhouette from the background',
  'let one strong diagonal carry the action',
  'keep foreground, play space and distance easy to read',
  'leave a quiet patch beside the main focal shape',
  'make the key action legible at small card size',
  'use a clear side-on staging with uncluttered edges',
  'balance one bright focal point against broad dark masses',
  'show the whole important silhouette without cropping its defining parts',
] as const;

const animeFraming = [
  'give the requested subject a clean silhouette and room to read',
  'keep its defining structure clear at card size',
  'place the focal form against a simple, distinct background shape',
  'use a controlled diagonal while keeping the focal subject readable',
  'balance detailed surfaces with open negative space',
  'show the complete subject with the setting kept secondary',
  'keep the focal form distinct from surrounding motion',
  'frame the moment using only existing readable details',
] as const;

const mythFraming = [
  'make the central symbol readable without adding lettering',
  'keep the human and celestial forms distinct',
  'use a clear focal silhouette against open sky',
  'balance intricate detail with broad, quiet shapes',
  'show the relationship between the figure and the landscape',
  'let one symbolic form anchor the composition',
  'keep the scene specific and avoid a generic fantasy collage',
  'leave breathing room around the principal figure or emblem',
] as const;

const punkFraming = [
  'make the improvised construction legible at a glance',
  'separate the main silhouette from the layered surface marks',
  'use one sharp accent amid otherwise controlled shapes',
  'show how the reclaimed parts fit together',
  'keep the focal object or figure clear of decorative clutter',
  'balance rough edges with a strong overall silhouette',
  'let the material contrast carry the visual emphasis',
  'reserve open space around the main subject',
] as const;

const darkFraming = [
  'make the main creature or figure readable against the architecture',
  'let a single light source guide the eye through the scene',
  'balance dense shadow with a clear focal silhouette',
  'show the scale of the setting without burying the subject',
  'use a strong vertical rhythm in the surrounding forms',
  'keep the central action readable amid the dark detail',
  'leave a quiet area beside the most intricate forms',
  'avoid a crowded montage of unrelated props',
] as const;

const gamePlans: readonly SubjectPlan[] = [
  {
    category: /neon urban|night ops/i,
    subjects: [
      'a helmeted courier with a folded map',
      'a lone rail inspector carrying a signal lamp',
      'a compact night train with lit windows',
      'a rooftop runner holding a blank data slate',
      'a street medic guiding a small service drone',
      'a delivery rider beside a battered electric bike',
      'a watchful alley cat beneath a fire escape',
      'a maintenance bot with one bright sensor eye',
      'a night-shift cook closing a tiny food stall',
      'a masked violinist crossing a transit concourse',
    ],
    framing: gameFraming,
  },
  {
    category: /arcane temples|mythic realms/i,
    subjects: [
      'an apprentice astronomer carrying a brass instrument',
      'a stone lion guardian with a cracked halo',
      'a blind archivist holding a closed ledger',
      'a small fox spirit with a single floating charm',
      'a temple bell ringer on a high balcony',
      'a masked challenger facing a many-eyed guardian',
      'a blue moth spirit with broad patterned wings',
      'a pilgrim carrying a plain walking staff',
      'a clockwork oracle with an unlit crystal core',
      'a pair of monks studying a blank star chart',
    ],
    framing: mythFraming,
  },
  {
    category: /sci-fi frontiers|mech zones/i,
    subjects: [
      'a tracked survey carrier with a tall sensor mast',
      'a compact rescue mech with an open cargo cradle',
      'a desert pilot beside a grounded two-leg machine',
      'a small convoy of mining crawlers',
      'an orbital mechanic in a tethered work suit',
      'a cargo walker carrying a bridge section',
      'a scout rover with its sampling arm extended',
      'a sand-worn command vehicle with blank status lights',
      'a pair of maintenance drones around a damaged landing strut',
      'a remote pilot watching a tiny rover feed',
    ],
    framing: gameFraming,
  },
  {
    category: /sieges|warfronts|last stands/i,
    subjects: [
      'a bridge engineer carrying a rolled plan',
      'a shield bearer protecting a field medic',
      'a signal keeper beside a damaged beacon',
      'a small crew hauling a field cannon',
      'a tired scout returning through a gate',
      'a stone rampart with a torn banner',
      'a rescue wagon entering a quiet village square',
      'a watchtower keeper calling across the wall',
      'a supply cart stuck beside a collapsed barricade',
      'two sentries guarding an empty causeway',
    ],
    framing: gameFraming,
  },
  {
    category: /speed|sport|competitive arenas/i,
    subjects: [
      'a sprinter leaving the starting blocks',
      'a cyclist leaning into a velodrome turn',
      'a goalkeeper reaching across the goal mouth',
      'a skateboarder setting up for a clean landing',
      'a swimmer turning at the end of a lane',
      'a rally car rounding a dusty hairpin',
      'a fencer advancing with the blade held safely forward',
      'a climber reaching for the next hold',
      'a basketball player rising toward the hoop',
      'a speed skater crossing the finish line',
    ],
    framing: gameFraming,
  },
  {
    category: /wilderness hunts|harsh frontiers/i,
    subjects: [
      'a field tracker studying prints in soft snow',
      'a park ranger carrying a folded stretcher',
      'a red fox moving along a rocky ledge',
      'a small canoe with one bundled traveler',
      'a mountain goat standing on a narrow shelf',
      'a weather station keeper checking a windsock',
      'a rescue dog following a trail between trees',
      'a lone botanist collecting a fallen seed pod',
      'a pack animal carrying supplies across scrubland',
      'a ranger guiding a young deer away from a road',
    ],
    framing: gameFraming,
  },
  {
    category: /heists|horror|underworld runs/i,
    subjects: [
      'a cautious locksmith carrying a small work light',
      'an adult courier with an unmarked satchel',
      'a night guard listening beside a closed service door',
      'a pale moth drifting through an empty hotel',
      'a salvage diver holding a blank brass key',
      'a quiet detective examining a scuffed tile',
      'a small shadow creature peeking around a stairwell',
      'a pair of thieves sharing one dim flashlight',
      'an elevator operator staring at an unlit floor panel',
      'a ghostly conductor waiting beside a silent train',
    ],
    framing: darkFraming,
  },
  {
    category: /puzzle chambers|adventure setpieces/i,
    subjects: [
      'an explorer holding a small mirror',
      'a clockwork door with one missing gear',
      'a stone staircase folding back on itself',
      'a tiny boat beneath a vast indoor arch',
      'a lantern bearer facing a room of suspended bridges',
      'a pair of travelers comparing blank stone tiles',
      'a mechanical owl resting on a narrow ledge',
      'a pressure plate surrounded by carved circles',
      'a rope bridge ending at a floating platform',
      'a traveler studying a shadow cast by three pillars',
    ],
    framing: gameFraming,
  },
];

const animePlans: readonly SubjectPlan[] = [
  {
    category: /core anime/i,
    subjects: [
      'an original young cartographer with a wind-tossed scarf',
      'an adult station musician carrying a cello case',
      'a student mechanic with rolled sleeves and a tool pouch',
      'a quiet courier carrying a paper parcel',
      'a young astronomer with a hand-built telescope',
      'an adult café cook balancing a tray',
      'a pair of siblings sharing an umbrella',
      'a determined fencer holding a practice foil',
      'a shy stage actor waiting in the wings',
      'a village runner carrying a message tube',
      'an original masked pilot beside a compact training craft',
      'a young botanist holding a pressed leaf',
      'a traveling puppeteer with a folded marionette stage',
      'an adult sound engineer wearing large headphones',
      'a curious diver examining a tiny shell',
      'a mountain guide beside a bright trail marker',
    ],
    framing: animeFraming,
  },
  {
    category: /slice of life, school and music/i,
    subjects: [
      'a student drummer carrying a practice pad',
      'a pianist closing a music book with blank pages',
      'two friends sharing one pair of headphones',
      'a student tending a classroom windowsill plant',
      'an adult music teacher packing a small keyboard',
      'a school club repairing a paper lantern',
      'a singer waiting beside a rehearsal-room door',
      'a student carrying a stack of art folders',
    ],
    framing: animeFraming,
  },
  {
    category: /shojo|magical girl|visionary classics/i,
    subjects: [
      'an articulated desk fan on a clean repair bench',
      'an adult technician checking a braided cable junction',
      'a blue dragonfly hovering above pond reeds',
      'a small glass greenhouse beside a city sidewalk',
      'an adult dancer practicing a turn on an empty stage',
      'a wooden bench beneath a flowering tree',
      'a city courier wearing a plain navy jacket',
      'a striped cat perched on a bright kitchen chair',
      'a sealed red envelope on a pale table',
      'two adult friends greeting each other at a station',
      'a rust-colored fox crossing a grassy path',
      'a narrow arched stairwell with a blue handrail',
      'an adult signing hello to a friend across a café table',
      'one blue scarf unfolding into a wind-borne ribbon in three clear stages',
      'a single amber warning lamp on a quiet control console',
      'a copper kettle resting on an outdoor cooking stove',
      'a compact model airplane on a workshop stand',
      'an original adult guard wearing lightweight segmented armor',
      'a ferry bridge with round instruments and open sky beyond',
      'a stone gate beside a modern city park path',
      'an orange tabby asleep beside a rainy window',
      'an adult musician tuning a dark electric bass',
      'a yellow bicycle leaned against a school entrance',
      'a folded paper flower under a desk lamp',
      'an adult tailor pinning the hem of a blue coat',
      'two contrasting wooden stools beside a small table',
      'an adult actor adjusting a plain stage curtain',
      'a student carrying a stack of blank art folders',
      'a sunset reflected in the window of an ordinary bus',
      'a pale blue raincoat hanging by an open doorway',
      'two adults walking beside a river after dusk',
      'a café worker folding a clean white apron',
      'a tray of herbs in a contemporary greenhouse',
      'an older painter standing beside an unfinished portrait canvas',
      'a hand-sewn canvas tote with bright geometric patches',
      'a charcoal pencil and paper sketch on a studio desk',
      'a red fox pausing on a snowy footbridge',
      'a translucent blue umbrella on a plain chair',
      'an adult hiker resting at a windy ridge marker',
      'a folded green umbrella beside a rain-darkened pavement',
    ],
    framing: animeFraming,
  },
  {
    category: /slice of life|moe/i,
    subjects: [
      'a warm loaf in a paper bag on a kitchen bench',
      'two friends sharing a bicycle repair kit',
      'a small watering can beside new garden seedlings',
      'a sunlit bookstore shelf with a leaning stack of novels',
      'a sleepy cat curled inside a soft blue scarf',
      'three bandmates packing instruments after practice',
      'three small bread rolls rising on a baking tray',
      'a paper cup resting on an empty commuter train seat',
      'a half-built cardboard model on a kitchen table',
      'a quiet student carrying a sketchbook under one arm',
      'a stovetop soup pot beside a portable radio',
      'an adult florist trimming a single stem',
      'two colorful backpack charms on a plain coat hook',
      'an open blank notebook beside a shaded desk lamp',
      'a laundry basket near a newly painted apartment door',
      'a café regular warming their hands around a mug',
      "a blue jacket with its loose hem pinned on a tailor's form",
      'a young dog walker paused at a crossing',
      'a thermos and folded picnic cloth beneath a park tree',
      'an older neighbor teaching a child to mend a button',
      'a pair of garden gloves drying on a wooden fence',
      'a night-shift baker arranging cooling rolls on a tray',
      'a blank postcard beside a rainy train window',
      'a painted ceramic tile drying on a studio shelf',
      'a quiet music student tuning a secondhand violin',
      'a bicycle courier returning a borrowed umbrella',
      'a few seashells sorted on a kitchen table',
      'a sleepy rabbit inside an open travel basket',
      'an adult librarian repairing a torn book cover',
      'a plate of uneven homemade pancakes by a sunny window',
    ],
    framing: animeFraming,
  },
  {
    category: /anime style spectrum/i,
    subjects: [
      'a young athlete stretching beside a practice bag',
      'an adult night courier with a reflective jacket',
      'a student inventor testing a paper glider',
      'a quiet forest guide holding a folded trail map',
      'a determined young pilot beside a simple training suit',
      'a street dancer in mid-turn on a rooftop',
      'an adult stage singer listening for the opening cue',
      'a young swordswoman holding a wooden practice blade',
      'a friendly river spirit with a face made of ripples',
      'a young science-club member carrying a model planet',
      'a pair of friends on a long-distance rail journey',
      'an original fantasy traveler with a repaired cloak',
      'a small maintenance robot bringing one flower indoors',
      'a young detective examining a broken pocket watch',
      'an adult chef setting out a neatly folded cloth',
      'a student swimmer pausing beneath a high dive board',
      'a bicycle racer passing beneath a string of flags',
      'a young musician tuning a bright red guitar',
      'a forest ranger meeting a large gentle bird',
      'an original masked hero standing beside a blank signboard',
      'a quiet archivist lifting a curtain of dust from an old shelf',
      'a sky sailor checking a loose rope knot',
      'a young photographer lowering a compact camera',
      'an adult mechanic listening to a small engine',
      'a mountain climber checking a bright safety carabiner',
      'a puppet performer carrying a folded stage screen',
      'a young journalist holding a recorder with its display dark',
      'a quiet baker carrying a tray through morning rain',
      'a pair of siblings steering a small model airship',
      'a deep-sea researcher beside a round observation window',
      'a masked fencer with a plain practice foil',
      'a child gardener presenting a giant sunflower seed',
      'an adult paramedic guiding a compact rescue robot',
      'a young archivist carrying a box of blank film reels',
      'a street drummer holding one pair of bright wooden sticks',
      'a shy dragon keeper beside a curled hatchling',
      'a train conductor holding a brass pocket watch',
      'a night photographer beneath a row of paper lanterns',
      'a young mechanic holding a cracked ceramic gear',
      'a traveling botanist with a pressed-leaf portfolio',
      'a small lighthouse robot projecting a narrow beam',
      'an adult cartographer unfolding a weathered coast map',
      'a student carrying a hand-built radio with a loose aerial',
      'a young skater holding a repaired board under one arm',
    ],
    framing: animeFraming,
  },
];

const mythPlans: readonly SubjectPlan[] = [
  {
    category: /mythic — symbolism|mythic - symbolism/i,
    subjects: [
      'a young astronomer holding a blank circular star chart',
      'a winged traveler carrying a balance scale',
      'a small river spirit coiling around a smooth stone',
      'a shepherd watching a bright new star',
      'a pair of siblings carrying two differently shaped lanterns',
      'a masked storyteller before a simple moon disk',
      'a crowned bird standing between two open gates',
      'a quiet figure holding a thread that reaches the horizon',
      'a deer with a constellation reflected in its antlers',
      'a lone guardian holding a seed above dark soil',
      'a sunlit hand releasing a flock of tiny paper birds',
      'a traveler crossing a circle of standing stones',
      'a small boat beneath an enormous crescent moon',
      'a child pointing toward a new constellation',
      'a pair of ravens perched beside a closed book',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — ritual noir|mythic - ritual noir/i,
    subjects: [
      'a masked timekeeper holding a small hourglass',
      'a night watch procession with three covered lanterns',
      'a quiet cantor standing beside a dark water basin',
      'a witness in a long coat carrying a closed ledger',
      'a shadowed guide holding one unlit candle',
      'a pair of attendants bearing a folded ceremonial cloth',
      'a hooded astronomer observing a lunar eclipse',
      'a lone mourner placing a single branch on stone',
      'a quiet figure listening beside a closed temple door',
      'a bell keeper with one gloved hand raised',
      'a small procession crossing a bridge at midnight',
      'a watcher holding a feather above a black pool',
      'an archivist reading a blank vellum sheet by lamplight',
      'a traveler leaving a simple token at a threshold',
      'a silent guide standing beneath an open stone arch',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — pantheons|mythic - pantheons/i,
    subjects: [
      'a cloud shepherd beside a calm thunder spirit',
      'a small hearth guardian tending a coal',
      'a winged messenger with a closed scroll tube',
      'a river deity lifting a bridge from the water',
      'a mountain giant carrying a pine tree like a staff',
      'a young hero guiding a frightened mule',
      'a many-armed smith shaping a plain horseshoe',
      'a shy serpent spirit warming itself in sunlight',
      'a harvest keeper carrying one sheaf of grain',
      'a moon guardian watching over a sleeping village',
      'a pair of rival wind spirits meeting above a pass',
      'a wise owl perched on a worn stone marker',
      'a traveler asking directions from a small shrine spirit',
      'a sea guardian holding a lantern above the waves',
      'a messenger crossing a field between distant temples',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — cosmology|mythic - cosmology/i,
    subjects: [
      'a tiny moon passing between two immense planets',
      'an astronomer tracing a blank constellation wheel',
      'a comet spirit carrying a tail of pale flowers',
      'a solar boat crossing a dark celestial sea',
      'a ringed world reflected in a mountain lake',
      'a figure holding an eclipse disc before the sun',
      'a cluster of stars gathering above a lone observatory',
      'a silver heron flying between moonlit clouds',
      'a celestial seed opening into a spiral of light',
      'two small moons approaching a quiet horizon',
      'a night watch keeper turning a brass sky globe',
      'a constellation shaped like a running animal',
      'a long-tailed star above a sleeping settlement',
      'a cloud giant whose outline resembles a mountain range',
      'a traveler following a pale band of stars across a plateau',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — greek epics|mythic - greek epics/i,
    subjects: [
      'a young sailor repairing one oar on a quiet shore',
      'a bronze-armored messenger beneath a coastal cliff',
      'a patient weaver working beside a sunlit doorway',
      'a small winged horse drinking from a stream',
      'a watchful owl perched above an olive grove',
      'a lone runner carrying news toward a hilltop city',
      'a sea captain steering past a chain of islands',
      'a wandering singer carrying a simple lyre',
      'a shepherd meeting a small mountain spirit',
      'a bronze shield resting beside a travel cloak',
      'a pair of travelers leaving a stone harbor',
      'a young archer watching the wind move through reeds',
      'a fisher guiding a narrow boat through a channel',
      'a quiet guardian beside a weathered marble gate',
      'a messenger crossing a sunlit courtyard',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — african cosmologies|mythic - african cosmologies/i,
    subjects: [
      'a night-sky storyteller pointing toward a bright star group',
      'a moon watcher beside a hand-built observatory',
      'a traveler following a river beneath a broad constellation',
      'a young drummer listening for an answer from the hills',
      'a guardian bird circling above a quiet settlement',
      'a weaver carrying a patterned cloth beneath the stars',
      'an elder and child watching a lunar halo',
      'a small water spirit emerging beside river reeds',
      'a star keeper climbing a ridge with a covered lamp',
      'a family gathered outdoors beneath a changing sky',
      'a messenger crossing grassland with a sealed letter',
      'a baobab silhouette beneath a new moon',
      'a crocodile spirit gliding through a still channel',
      'a careful astronomer aligning a simple sighting rod',
      'a cloud of fireflies tracing a path to the horizon',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — japanese yokai|mythic - japanese yokai/i,
    subjects: [
      'a lantern spirit with a curious, gentle face',
      'a small fox-like messenger carrying a leaf',
      'a river guardian whose sleeves flow like water',
      'a paper-winged night spirit perched on a gate',
      'a long-necked shadow yokai peering around a corner',
      'a quiet mountain kami beside a cedar branch',
      'a traveling umbrella spirit crossing a wet path',
      'a tiny household spirit hiding beneath a stair',
      'a moon hare watching from a tiled roof',
      'a fox-mask dancer pausing between steps',
      'a sleepy tanuki spirit resting near a stream',
      'a wind spirit tangled in a few maple leaves',
      'a pale river dragon winding between stones',
      'a small shrine keeper sweeping fallen blossoms',
      'a bell-shaped forest spirit glowing under dark trees',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — norse sagas|mythic - norse sagas/i,
    subjects: [
      'a weathered navigator reading the wind above the fjord',
      'a shield maker testing a newly bound rim',
      'a raven spirit perched on a carved mast',
      'a small longship turning between ice floes',
      'a quiet seer holding a plain wooden staff',
      'a frost giant carrying a fallen pine',
      'a young fisher hauling a net onto black sand',
      'a broad-shouldered traveler leading a shaggy pony',
      'a wolf spirit watching from a snowy ridge',
      'a skald tuning a small travel harp',
      'a mountain keeper tending a beacon fire',
      'a pair of siblings crossing a frozen stream',
      'a ring of standing stones beneath the northern lights',
      'an old boat builder shaping a curved prow',
      'a bright constellation above a timber hall',
    ],
    framing: mythFraming,
  },
  {
    category: /mythic — mesoamerican suns|mythic - mesoamerican suns/i,
    subjects: [
      'a sun watcher aligning a plain stone sighting marker',
      'a feathered serpent spirit above a quiet canal',
      'a young runner carrying a bright cloth between terraces',
      'a solar disc rising behind a stepped observatory',
      'a small jaguar spirit resting beneath a ceiba tree',
      'a community astronomer tracing the shadow of a pillar',
      'a pair of ballplayers meeting at the edge of an empty court',
      'a hummingbird spirit hovering above red flowers',
      'a traveler carrying water toward a highland settlement',
      'a carved stone marker beneath a ring of clouds',
      'a sun guardian crossing a broad mountain pass',
      'an artisan shaping a small clay whistle',
      'a bright star reflected in a ceremonial pool',
      'a young farmer watching dawn from a terrace',
      'a distant pyramid silhouette under a copper sky',
    ],
    framing: mythFraming,
  },
];

const punkPlans: readonly SubjectPlan[] = [
  {
    category: /classic industrial punks/i,
    subjects: [
      'an adult machinist repairing a hand-built radio',
      'a courier wearing a patched work jacket',
      'a bicycle builder testing a welded cargo frame',
      'a pair of workers carrying a salvaged fan motor',
      'a street musician playing a metal-bodied instrument',
      'a maker fitting a new handle to a worn tool',
      'a mechanic riding a rebuilt single-speed bike',
      'a foundry worker carrying a small work lamp',
    ],
    framing: punkFraming,
  },
  {
    category: /neon, net|signal punks/i,
    subjects: [
      'a signal runner wearing a jacket threaded with tiny lights',
      'an adult technician holding a compact antenna',
      'a rooftop coder with a blank portable screen',
      'a courier carrying a bundle of fiber cable',
      'a small relay drone repaired with mismatched panels',
      'a street DJ turning a patched mixer knob',
      'a night mechanic beside a home-built e-bike',
      'a quiet radio operator beneath a rooftop dish',
    ],
    framing: punkFraming,
  },
  {
    category: /eco, repair|climate punks/i,
    subjects: [
      'a repair collective member carrying a wooden tool box',
      'an adult gardener with a bucket of seedlings',
      'a bicycle mechanic fitting a reused wheel',
      'a rooftop beekeeper checking an empty frame',
      'a community builder carrying a salvaged door panel',
      'a young botanist with a bundle of native grasses',
      'a river monitor holding a blank field slate',
      'a group of neighbors assembling a shade canopy',
    ],
    framing: punkFraming,
  },
  {
    category: /bio, myco|body punks/i,
    subjects: [
      'a field biologist carrying a clear sample slide',
      'an adult gardener examining a cluster of blue mushrooms',
      'a careful medic fitting a lightweight prosthetic glove',
      'a mycelium grower checking a broad culture bed',
      'a dancer wearing a costume of soft translucent layers',
      'a small fungal spirit with a cap like a folded leaf',
      'a researcher carrying an unmarked seed capsule',
      'a body artist painting a temporary geometric arm pattern',
    ],
    framing: punkFraming,
  },
  {
    category: /ocean, ice|terrain punks/i,
    subjects: [
      'a cold-water diver carrying a patched oxygen line',
      'a shoreline ranger in a repaired weather coat',
      'a small research skiff with mismatched panels',
      'an ice climber checking a rope anchor',
      'a fisher repairing a net beside a dry dock',
      'a seaweed farmer carrying a woven basket',
      'a rescue swimmer guiding a tired seal toward open water',
      'a geologist studying a band of exposed rock',
    ],
    framing: punkFraming,
  },
  {
    category: /street, riot|diy punks/i,
    subjects: [
      'a street muralist carrying a broad brush',
      'an adult skateboarder with a patched canvas bag',
      'a community organizer holding a blank poster board',
      'a sound-system builder tightening a speaker stand',
      'a young dancer in a self-mended jacket',
      'a bicycle messenger beside a painted helmet',
      'a pair of volunteers stacking folding chairs',
      'a street tailor repairing a torn sleeve',
    ],
    framing: punkFraming,
  },
  {
    category: /media, vapor|glitch punks/i,
    subjects: [
      'a video artist adjusting a stack of old monitors',
      'a radio host wearing mismatched studio headphones',
      'a visual performer beside a homemade light grid',
      'a cassette archivist winding a clear tape reel',
      'a small pixel-shaped spirit emerging from scanlines',
      'a projectionist carrying a blank film canister',
      'an adult sound designer turning a patched synthesizer dial',
      'a young maker repairing a handheld game screen',
    ],
    framing: punkFraming,
  },
  {
    category: /occult, myth|gothic punks/i,
    subjects: [
      'an adult night librarian holding a closed book',
      'a street magician with a plain black umbrella',
      'a gentle crow spirit perched on a bent street sign',
      'a candle maker carrying an unlit taper',
      'a masked accordion player beside a quiet archway',
      'a local historian tracing a map with one gloved finger',
      'a small moth creature sheltering under a coat',
      'a repairer wearing a hand-stitched cloak',
    ],
    framing: punkFraming,
  },
  {
    category: /space, atomic|ray punks/i,
    subjects: [
      'a starship mechanic carrying a patched pressure hood',
      'a small moon buggy with hand-painted panels',
      'an adult orbital gardener tending a sealed seed tray',
      'a ray-gun inventor testing a harmless light beam',
      'a pilot beside a compact one-seat exploration craft',
      'a radio operator with a home-built headset',
      'a lunar surveyor planting a plain reflective marker',
      'a community welder repairing a small satellite dish',
    ],
    framing: punkFraming,
  },
  {
    category: /primitive, stone|salvage punks/i,
    subjects: [
      'a stone carver shaping a simple hand tool',
      'a salvager carrying a repaired wooden sled',
      'an adult potter shaping a low clay tile',
      'a rope maker gathering strong plant fibers',
      'a young builder stacking reused stone blocks',
      'a field guide holding a flint scraper',
      'a weaver repairing a broad grass mat',
      'a quiet traveler with a patched hide pack',
    ],
    framing: punkFraming,
  },
];

const retroAnimePlans: readonly SubjectPlan[] = [
  {
    category: /70s|80s|retro anime/i,
    subjects: [
      'a young test pilot beside a rounded training craft',
      'a school runner holding a paper relay sash',
      'an adult space mechanic with a large tool belt',
      'a quiet swordswoman carrying a wrapped practice blade',
      'a city detective with a long coat and simple notebook',
      'a small forest spirit watching a railway signal',
      'a singer stepping into a warm spotlight',
      'a pair of friends leaning over an arcade cabinet',
      'an original mecha pilot standing beside an open cockpit',
      'a young mountain climber clipping onto a rope',
      'a stage magician holding a blank playing card',
      'a traveling cook steering a tiny food cart',
      'a swimmer leaving the pool after practice',
      'a night courier crossing a roof under moonlight',
      'a small robot carrying a folded umbrella',
      'an adult racing mechanic checking a wheel hub',
      'a fantasy archer watching clouds gather over a ridge',
      'a young musician tuning a red electric guitar',
      'a quiet archivist dusting a row of old books',
      'a bicycle racer leaning into a velodrome curve',
      'a village guardian with a plain wooden staff',
      'a young astronomer at a hand-built telescope',
      'a pair of hikers crossing a bridge above the clouds',
      'a student carrying a sketchbook through a station',
      'an adult radio host testing a polished studio microphone',
      'a young mechanic studying a diagram of a compact engine',
      'a mountain rescue guide carrying a coiled rope',
      'a pair of siblings watching a small robot race',
      'a night ferry pilot beside a row of round instrument dials',
      'a school fencer carrying a wrapped practice blade',
      'a quiet wildlife keeper beside a rescued crane',
    ],
    framing: animeFraming,
  },
  {
    category: /90s golden era/i,
    subjects: [
      'a young explorer with a worn shoulder pack',
      'an adult detective examining a bent key',
      'a quiet pilot beside a compact aircraft',
      'a group of friends carrying a broken radio',
      'a swordswoman helping a traveler onto a bridge',
      'a small robot holding a paper flower',
      'a street drummer pausing between rhythms',
      'a young athlete tying a loose shoe lace',
      'an original sea captain reading the weather',
      'a mechanic opening the hood of a small race car',
      'a mountain spirit watching a village road',
      'a student carrying a stack of blank notebooks',
      'an adult stage actor waiting behind a curtain',
      'a night cyclist passing a row of shop lights',
      'a young archer at the edge of a forest',
      'a pair of siblings watching an airship pass',
      'a traveler holding a map with no writing',
      'a quiet singer turning toward the audience',
      'a small dog running alongside a school bicycle',
      'a forest guide sheltering a rescued bird',
    ],
    framing: animeFraming,
  },
  {
    category: /2000s classics/i,
    subjects: [
      'an adult courier wearing a bright weatherproof jacket',
      'a young science student carrying a model glider',
      'a pair of musicians testing a small portable speaker',
      'a forest ranger beside a compact utility bike',
      'a student athlete holding a relay baton',
      'an original pilot checking a simplified cockpit display',
      'a night baker closing a neighborhood shop',
      'a traveler carrying a digital camera with no visible brand',
      'a small service robot and its human repairer',
      'a young climber with a coiled safety rope',
      'an adult gardener carrying a tray of seedlings',
      'a drummer waiting beneath a backstage work light',
      'a young detective comparing two blank photographs',
      'a bicycle racer lifting a bike onto a stand',
      'an original fantasy traveler holding a softly glowing stone',
      'a student carrying a folded umbrella through wind',
      'a quiet librarian returning a stack of books',
      'a small racing drone resting on a workbench',
      'a pair of friends looking across a city from a bridge',
      'a young sailor watching a distant storm line',
    ],
    framing: animeFraming,
  },
  {
    category: /studio masterpieces/i,
    subjects: [
      'a young traveler sharing food with a small animal companion',
      'a cloud shadow crossing a green field beside a modern road',
      'a yellow commuter train rounding a low platform',
      'a curved wooden boat rib resting on a workbench',
      'a child chasing a paper pinwheel along a path',
      'a bakery door opening onto a bright street at dawn',
      'a broad tree beside a quiet apartment courtyard',
      'a pair of siblings carrying a box of moving supplies',
      'a paper-winged glider resting on a classroom table',
      'a handmade wooden flute on folded blue cloth',
      'a large gray bird walking through tall roadside grass',
      'a student watching steam rise from a blue cup',
      'a young diver following sunlight through clear water',
      'a folded coastal map spread beside a brass compass',
      'a bicycle repairer showing a child how a bell works',
      'a courier helping a neighbor carry a basket',
      'a blue lighthouse door above a quiet stone stair',
      'a wind-bent pine on a mountain overlook',
      'a broad fallen leaf sheltering a small field mouse',
      'a commuter asleep beside a bright train window',
      'a paper boat floating along a shallow garden path',
      'a tiny brass spring beside a disassembled alarm clock',
      'a warm bread roll set near a curious stray cat',
      'a roadside shelter with a bicycle leaned against it',
      'a folded transit map on the open deck of a ferry',
      'fireflies above a wooden porch after rainfall',
      "a small bird figurine taking shape in a sculptor's hands",
      'seedling trays under a sudden summer shower',
      'a young violinist practicing beneath an open stairwell',
      'two friends carrying a repaired terracotta roof tile',
    ],
    framing: animeFraming,
  },
  {
    category: /sports|competition|performance/i,
    subjects: [
      'a track runner leaning into the final curve',
      'a gymnast holding a balanced beam pose',
      'a fencer testing distance before a clean lunge',
      'a swimmer reaching the wall at the end of a lap',
      'a basketball player tracking a high pass',
      'a cyclist climbing a steep open road',
      'a tennis player preparing a serve beneath clear sky',
      'a skateboarder rolling down a smooth quarter-pipe',
      'a baseball outfielder reaching toward a high catch',
      'a volleyball player jumping beside the net',
      'a figure skater completing a controlled turn',
      'a climber reaching across a bright training wall',
      'a martial artist completing a careful practice form',
      'a rower pulling through a quiet stretch of water',
      'a relay runner receiving the baton',
      'a diver holding a clean line above the pool',
      'a football player turning with the ball at their feet',
      'a sprinter accelerating from a crouched start',
      'a kayaker rounding a marked buoy',
      'a dancer finishing a wide traveling leap',
      'a skier carving across a groomed slope',
      'a boxer training against a hanging bag',
      'a horse and rider clearing a low practice jump',
      'a racing mechanic signaling a safe pit exit',
      'a handball player preparing a controlled jump shot',
      'a synchronized swimmer holding a mirrored pose',
      'a table tennis player watching a bright ball cross the table',
      'a kayaker carrying a paddle toward a marked start',
      'a long jumper measuring a quiet run-up',
      'a wheelchair racer approaching a broad track bend',
    ],
    framing: animeFraming,
  },
  {
    category: /samurai|medieval/i,
    subjects: [
      'a traveling swordswoman carrying a sheathed blade',
      'a young page holding a repaired kite shield',
      'a quiet archer beside a low stone wall',
      'an adult blacksmith checking the edge of a plain tool',
      'a mounted courier crossing a shallow stream',
      'a watch keeper holding a lantern by the gate',
      'a wandering musician carrying a small travel lute',
      'a castle gardener carrying a bundle of cut branches',
    ],
    framing: animeFraming,
  },
  {
    category: /horror/i,
    subjects: [
      'a student carrying a lantern with a dim blue flame',
      'an adult night guard hearing a sound above the ceiling',
      'a small shadow creature peeking from behind a curtain',
      'a young detective standing beside an empty coat rack',
      'a pale moth landing on a closed classroom book',
      'a lonely station operator beside an unlit control panel',
      'a traveler looking back toward a second set of footprints',
      'a quiet child holding a flashlight below chin level',
    ],
    framing: darkFraming,
  },
];

const darkFantasyPlans: readonly SubjectPlan[] = [
  {
    category: /dark fantasy|gothic courts/i,
    subjects: [
      'a weary court messenger carrying a sealed plain envelope',
      'a pale wolf guardian beneath a broken arch',
      'a masked duchess standing beside an empty throne',
      'a traveling knight lowering a battered shield',
      'a crow-headed archivist holding one unmarked page',
      'a young grave keeper with a simple lantern',
      'a moth-winged creature resting above an old gate',
      'a quiet court musician beside a cracked window',
      'a giant stag spirit watching a ruined road',
      'a pair of siblings crossing a bridge of bone-white stone',
      'a one-eyed sentinel turning toward a distant bell',
      'a veiled healer carrying a bundle of herbs',
      'a pale raven beside a tower with no banners',
      'a traveler leading a tired mule through a dark pass',
      'a queen in plain mourning clothes beside a rain-streaked window',
      'a small fox spirit beneath a thorn tree',
      'a knight removing a helmet at the edge of a battlefield',
      'a ruined chapel overgrown with black ivy',
      'an empty throne room with one candle still burning',
      'a stone bridge suspended over a deep ravine',
      'a quiet village beneath the shadow of a vast fortress',
      'a blind bell keeper carrying a ring of iron keys',
      'a pale swan spirit circling a drowned courtyard',
      'a weary stable hand beside a horse with a silver mane',
      'a masked judge seated beneath a leafless tree',
      'a young scribe holding a lantern over an unfinished map',
      'a wolfhound guarding an abandoned chapel step',
      'a quiet pilgrim carrying a cracked hand mirror',
      'a court gardener tending a single thorned rose',
      'a stone-faced sentinel with a small bird on one shoulder',
    ],
    framing: darkFraming,
  },
  {
    category: /dungeon zine|risograph prints/i,
    subjects: [
      'a small party sharing a lantern at a fork in the passage',
      'a mapmaker drawing a blank route through a maze',
      'a mushroom creature guarding a narrow stair',
      'a lone torch bearer beside a sealed stone door',
      'a rope bridge crossing a square dungeon shaft',
      'a tiny camp beside a dry fountain',
      'a chest-sized mimic disguised as a cracked stone block',
      'a cave explorer checking a simple compass',
      'a set of winding stairs seen from above',
      'a heavy gate with a single bright keyhole',
      'a pair of travelers facing a sleeping cave lizard',
      'a tiny explorer lowering a bucket into a dry well',
      'a stone golem holding a lantern in one open palm',
      'a folded map pinned beneath a chipped dungeon tile',
    ],
    framing: punkFraming,
  },
  {
    category: /ink, tarot|bestiary plates/i,
    subjects: [
      'a crowned moth spirit with broad patterned wings',
      'a two-headed heron standing on a single reed',
      'a quiet oracle holding a plain mirror',
      'a horned forest guardian with a wreath of bare branches',
      'a serpent coiled around a closed unmarked book',
      'a small lantern-bearer beneath a black sun',
      'a skeletal fish swimming through an open ring of water',
      'a pair of ravens sharing one bright feather',
      'a winged deer standing between two dark trees',
      'a masked dancer holding a long white ribbon',
      'a horned owl perched on a crescent branch',
      'a sea creature with a lighthouse-shaped shell',
      'a quiet judge balancing one stone in each hand',
      'a many-tailed fox spirit facing a full moon',
      'a thorn-backed lion resting with eyes closed',
      'a tall skeleton botanist holding one flower',
      'a small dragon emerging from a cut-paper cave',
      'a black swan crossing an empty pool',
      'a twin-tailed serpent circling a plain silver key',
      'a veiled astronomer beneath a ring of moths',
      'a stag skull sprouting a crown of pale branches',
      'a quiet ferryman holding two unlit candles',
      'a moon-faced owl perched above a blank scroll',
      'a small fox spirit carrying a broken sundial',
    ],
    framing: mythFraming,
  },
  {
    category: /rune-tech|apocalyptic warfronts/i,
    subjects: [
      'a field engineer carrying a blank metal tablet',
      'a rune-carved rescue mech with one damaged leg',
      'a courier beside a small hovering supply drone',
      'a signal keeper tending an unlettered beacon',
      'a blackened airship passing over a broken bridge',
      'a young mechanic holding a fractured power cell',
      'a watchtower surrounded by strange glowing roots',
      'a masked scout guiding a line of evacuees',
      'a stone gate fitted with salvaged cables and lights',
      'a small armored vehicle with a cracked windscreen',
      'a radio operator under a damaged rooftop dish',
      'a towering guardian with a bright rune-shaped core',
      'an empty road crossing a field of fallen antennae',
      'a team of repairers lifting a broken wind vane',
    ],
    framing: darkFraming,
  },
  {
    category: /grimdark game systems|tabletop/i,
    subjects: [
      'a painted scout miniature beside a low stone barricade',
      'a compact squad of original armored figures',
      'a weathered campaign map with blank markers',
      'a tiny siege engine beside a painted infantry line',
      'a lone command figure holding a plain standard',
      'a small monster miniature emerging from a cave tile',
      'a modular battlefield built from dark terrain pieces',
      'a set of unmarked objective tokens beside a ruined tower',
      'a heavy creature miniature standing on a cracked base',
      'a narrow bridge tile between two cliff sections',
      'a small group of figures gathered around a blank mission map',
    ],
    framing: gameFraming,
  },
];

const PRESET_ORDER_BY_CATEGORY: Readonly<Record<string, readonly string[]>> = {
  'pack_12|1. Neon Urban & Night Ops': [
    'SP12-001',
    'SP12-014',
    'SP12-025',
    'SP12-032',
    'SP12-043',
    'SP12-048',
    'SP12-056',
    'SP12-062',
    'SP12-071',
    'SP12-078',
  ],
  'pack_12|6. Wilderness Hunts & Harsh Frontiers': [
    'SP12-002',
    'SP12-010',
    'SP12-022',
    'SP12-027',
    'SP12-029',
    'SP12-034',
    'SP12-040',
    'SP12-041',
    'SP12-067',
    'SP12-073',
  ],
  'pack_12|3. Sci-Fi Frontiers & Mech Zones': [
    'SP12-003',
    'SP12-005',
    'SP12-011',
    'SP12-018',
    'SP12-023',
    'SP12-033',
    'SP12-042',
    'SP12-045',
    'SP12-046',
    'SP12-068',
  ],
  'pack_12|8. Puzzle Chambers & Adventure Setpieces': [
    'SP12-004',
    'SP12-012',
    'SP12-036',
    'SP12-037',
    'SP12-051',
    'SP12-058',
    'SP12-072',
    'SP12-074',
    'SP12-077',
    'SP12-080',
  ],
  'pack_12|2. Arcane Temples & Mythic Realms': [
    'SP12-006',
    'SP12-013',
    'SP12-015',
    'SP12-020',
    'SP12-028',
    'SP12-044',
    'SP12-053',
    'SP12-055',
    'SP12-061',
    'SP12-070',
  ],
  'pack_12|4. Sieges, Warfronts & Last Stands': [
    'SP12-007',
    'SP12-009',
    'SP12-026',
    'SP12-035',
    'SP12-038',
    'SP12-052',
    'SP12-060',
    'SP12-064',
    'SP12-076',
    'SP12-079',
  ],
  'pack_12|5. Speed, Sport & Competitive Arenas': [
    'SP12-008',
    'SP12-017',
    'SP12-021',
    'SP12-031',
    'SP12-039',
    'SP12-047',
    'SP12-059',
    'SP12-063',
    'SP12-065',
    'SP12-075',
  ],
  'pack_12|7. Heists, Horror & Underworld Runs': [
    'SP12-016',
    'SP12-019',
    'SP12-024',
    'SP12-030',
    'SP12-049',
    'SP12-050',
    'SP12-054',
    'SP12-057',
    'SP12-066',
    'SP12-069',
  ],
  'pack_13|3. Shojo, Magical Girl & Visionary Classics': [
    'SP05-013',
    'SP05-019',
    'SP05-020',
    'SP05-041',
    'SP05-042',
    'SP05-043',
    'SP05-044',
    'SP05-045',
    'SP05-046',
    'SP05-047',
    'SP05-048',
    'SP05-049',
    'SP05-050',
    'SP05-162',
    'SP05-168',
    'SP05-171',
    'SP05-172',
    'SP05-176',
    'SP05-177',
    'SP05-178',
    'SP05-181',
    'SP05-182',
    'SP05-183',
    'SP05-184',
    'SP05-185',
    'SP05-186',
    'SP05-187',
    'SP05-188',
    'SP05-189',
    'SP05-190',
    'SP05-191',
    'SP05-192',
    'SP05-193',
    'SP05-194',
    'SP05-195',
    'SP05-196',
    'SP05-197',
    'SP05-198',
    'SP05-199',
    'SP05-200',
  ],
  'pack_13|4. Slice Of Life & Moe': [
    'SP05-081',
    'SP05-082',
    'SP05-083',
    'SP05-084',
    'SP05-085',
    'SP05-086',
    'SP05-087',
    'SP05-088',
    'SP05-089',
    'SP05-090',
    'SP05-201',
    'SP05-202',
    'SP05-203',
    'SP05-204',
    'SP05-205',
    'SP05-206',
    'SP05-207',
    'SP05-208',
    'SP05-209',
    'SP05-210',
    'SP05-211',
    'SP05-212',
    'SP05-213',
    'SP05-214',
    'SP05-215',
    'SP05-216',
    'SP05-217',
    'SP05-218',
    'SP05-219',
    'SP05-220',
  ],
  'pack_13|5. Anime Style Spectrum': [
    'SP05-101',
    'SP05-102',
    'SP05-103',
    'SP05-104',
    'SP05-105',
    'SP05-106',
    'SP05-107',
    'SP05-108',
    'SP05-109',
    'SP05-110',
    'SP05-111',
    'SP05-112',
    'SP05-113',
    'SP05-114',
    'SP05-115',
    'SP05-116',
    'SP05-117',
    'SP05-118',
    'SP05-119',
    'SP05-120',
    'SP05-321',
    'SP05-322',
    'SP05-323',
    'SP05-324',
    'SP05-325',
    'SP05-326',
    'SP05-327',
    'SP05-328',
    'SP05-329',
    'SP05-330',
    'SP05-331',
    'SP05-332',
    'SP05-333',
    'SP05-334',
    'SP05-335',
    'SP05-336',
    'SP05-337',
    'SP05-338',
    'SP05-339',
    'SP05-340',
    'SP05-341',
    'SP05-342',
  ],
  'pack_13|1. Core Anime': [
    'SP13-001',
    'SP13-002',
    'SP13-004',
    'SP13-006',
    'SP13-007',
    'SP13-008',
    'SP13-009',
    'SP13-010',
    'SP13-011',
    'SP13-012',
    'SP13-014',
    'SP13-016',
    'SP13-017',
    'SP13-019',
    'SP13-020',
  ],
  'pack_13|2. Slice Of Life, School And Music': [
    'SP13-003',
    'SP13-005',
    'SP13-013',
    'SP13-015',
    'SP13-018',
  ],
  'pack_14|1. Mythic — Symbolism': [
    'SP14-001',
    'SP14-005',
    'SP14-011',
    'SP14-095',
    'SP14-096',
    'SP14-097',
    'SP14-098',
    'SP14-099',
    'SP14-100',
    'SP14-101',
    'SP14-102',
    'SP14-103',
    'SP14-104',
    'SP14-105',
    'SP14-106',
  ],
  'pack_14|2. Mythic — Ritual Noir': [
    'SP14-002',
    'SP14-003',
    'SP14-006',
    'SP14-007',
    'SP14-010',
    'SP14-107',
    'SP14-108',
    'SP14-109',
    'SP14-110',
    'SP14-111',
    'SP14-112',
    'SP14-113',
    'SP14-114',
    'SP14-115',
    'SP14-116',
  ],
  'pack_14|3. Mythic — Pantheons & Legends': [
    'SP14-004',
    'SP14-008',
    'SP14-009',
    'SP14-012',
    'SP14-014',
    'SP14-015',
    'SP14-016',
    'SP14-017',
    'SP14-117',
    'SP14-118',
    'SP14-119',
    'SP14-120',
    'SP14-121',
    'SP14-122',
    'SP14-123',
  ],
  'pack_14|4. Mythic — Cosmology & Omens': [
    'SP14-013',
    'SP14-081',
    'SP14-082',
    'SP14-083',
    'SP14-084',
    'SP14-085',
    'SP14-086',
    'SP14-087',
    'SP14-088',
    'SP14-089',
    'SP14-090',
    'SP14-091',
    'SP14-092',
    'SP14-093',
    'SP14-094',
  ],
  'pack_14|5. Mythic — Greek Epics': [
    'SP14-018',
    'SP14-019',
    'SP14-020',
    'SP14-045',
    'SP14-046',
    'SP14-047',
    'SP14-048',
    'SP14-049',
    'SP14-050',
    'SP14-051',
    'SP14-052',
    'SP14-053',
    'SP14-054',
    'SP14-055',
    'SP14-056',
  ],
  'pack_14|6. Mythic — African Cosmologies': [
    'SP14-021',
    'SP14-022',
    'SP14-023',
    'SP14-057',
    'SP14-058',
    'SP14-059',
    'SP14-060',
    'SP14-061',
    'SP14-062',
    'SP14-063',
    'SP14-064',
    'SP14-065',
    'SP14-066',
    'SP14-067',
    'SP14-068',
  ],
  'pack_14|7. Mythic — Japanese Yokai & Kami': [
    'SP14-024',
    'SP14-025',
    'SP14-026',
    'SP14-033',
    'SP14-034',
    'SP14-035',
    'SP14-036',
    'SP14-037',
    'SP14-038',
    'SP14-039',
    'SP14-040',
    'SP14-041',
    'SP14-042',
    'SP14-043',
    'SP14-044',
  ],
  'pack_14|8. Mythic — Norse Sagas': [
    'SP14-027',
    'SP14-028',
    'SP14-029',
    'SP14-069',
    'SP14-070',
    'SP14-071',
    'SP14-072',
    'SP14-073',
    'SP14-074',
    'SP14-075',
    'SP14-076',
    'SP14-077',
    'SP14-078',
    'SP14-079',
    'SP14-080',
  ],
  'pack_14|9. Mythic — Mesoamerican Suns': ['SP14-030', 'SP14-031', 'SP14-032'],
  'pack_15|1. Classic Industrial Punks': [
    'SP15-001',
    'SP15-002',
    'SP15-003',
    'SP15-004',
    'SP15-005',
    'SP15-006',
    'SP15-007',
    'SP15-008',
  ],
  'pack_15|2. Neon, Net & Signal Punks': [
    'SP15-009',
    'SP15-010',
    'SP15-011',
    'SP15-012',
    'SP15-013',
    'SP15-014',
    'SP15-015',
    'SP15-016',
  ],
  'pack_15|3. Eco, Repair & Climate Punks': [
    'SP15-017',
    'SP15-018',
    'SP15-019',
    'SP15-020',
    'SP15-021',
    'SP15-022',
    'SP15-023',
    'SP15-024',
  ],
  'pack_15|4. Bio, Myco & Body Punks': [
    'SP15-025',
    'SP15-026',
    'SP15-027',
    'SP15-028',
    'SP15-029',
    'SP15-030',
    'SP15-031',
    'SP15-032',
  ],
  'pack_15|5. Ocean, Ice & Terrain Punks': [
    'SP15-033',
    'SP15-034',
    'SP15-035',
    'SP15-036',
    'SP15-037',
    'SP15-038',
    'SP15-039',
    'SP15-040',
  ],
  'pack_15|6. Street, Riot & DIY Punks': [
    'SP15-041',
    'SP15-042',
    'SP15-043',
    'SP15-044',
    'SP15-045',
    'SP15-046',
    'SP15-047',
    'SP15-048',
  ],
  'pack_15|7. Media, Vapor & Glitch Punks': [
    'SP15-049',
    'SP15-050',
    'SP15-051',
    'SP15-052',
    'SP15-053',
    'SP15-054',
    'SP15-055',
    'SP15-056',
  ],
  'pack_15|8. Occult, Myth & Gothic Punks': [
    'SP15-057',
    'SP15-058',
    'SP15-059',
    'SP15-060',
    'SP15-061',
    'SP15-062',
    'SP15-063',
    'SP15-064',
  ],
  'pack_15|9. Space, Atomic & Ray Punks': [
    'SP15-065',
    'SP15-066',
    'SP15-067',
    'SP15-068',
    'SP15-069',
    'SP15-070',
    'SP15-071',
    'SP15-072',
  ],
  'pack_15|10. Primitive, Stone & Salvage Punks': [
    'SP15-073',
    'SP15-074',
    'SP15-075',
    'SP15-076',
    'SP15-077',
    'SP15-078',
    'SP15-079',
    'SP15-080',
  ],
  'pack_16|1. 70s & 80s Retro Anime': [
    'SP05-001',
    'SP05-002',
    'SP05-003',
    'SP05-004',
    'SP05-005',
    'SP05-006',
    'SP05-007',
    'SP05-008',
    'SP05-009',
    'SP05-010',
    'SP05-301',
    'SP05-302',
    'SP05-303',
    'SP05-304',
    'SP05-305',
    'SP05-306',
    'SP05-307',
    'SP05-308',
    'SP05-309',
    'SP05-310',
    'SP05-311',
    'SP05-312',
    'SP05-313',
    'SP05-314',
    'SP05-315',
    'SP05-316',
    'SP05-317',
    'SP05-318',
    'SP05-319',
    'SP05-320',
    'SP16-001',
  ],
  'pack_16|2. 90s Golden Era': [
    'SP05-011',
    'SP05-012',
    'SP05-014',
    'SP05-015',
    'SP05-016',
    'SP05-017',
    'SP05-018',
    'SP05-161',
    'SP05-163',
    'SP05-164',
    'SP05-165',
    'SP05-166',
    'SP05-167',
    'SP05-169',
    'SP05-170',
    'SP05-173',
    'SP05-174',
    'SP05-175',
    'SP05-179',
    'SP05-180',
  ],
  'pack_16|3. 2000s Classics': [
    'SP05-024',
    'SP05-026',
    'SP05-027',
    'SP05-030',
    'SP05-141',
    'SP05-145',
    'SP05-146',
    'SP05-147',
    'SP05-149',
    'SP05-150',
    'SP05-151',
    'SP05-152',
    'SP05-153',
    'SP05-154',
    'SP05-155',
    'SP05-156',
    'SP05-157',
    'SP05-158',
    'SP05-159',
    'SP05-160',
  ],
  'pack_16|4. Studio Masterpieces': [
    'SP05-071',
    'SP05-072',
    'SP05-073',
    'SP05-074',
    'SP05-075',
    'SP05-076',
    'SP05-077',
    'SP05-078',
    'SP05-079',
    'SP05-080',
    'SP05-281',
    'SP05-282',
    'SP05-283',
    'SP05-284',
    'SP05-285',
    'SP05-286',
    'SP05-287',
    'SP05-288',
    'SP05-289',
    'SP05-290',
    'SP05-291',
    'SP05-292',
    'SP05-293',
    'SP05-294',
    'SP05-295',
    'SP05-296',
    'SP05-297',
    'SP05-298',
    'SP05-299',
    'SP05-300',
  ],
  'pack_16|5. Sports, Competition & Performance': [
    'SP05-343',
    'SP05-344',
    'SP05-345',
    'SP05-346',
    'SP05-347',
    'SP05-348',
    'SP05-349',
    'SP05-350',
    'SP05-351',
    'SP05-352',
    'SP05-353',
    'SP05-354',
    'SP05-355',
    'SP05-356',
    'SP05-357',
    'SP05-358',
    'SP05-359',
    'SP05-360',
    'SP05-361',
    'SP05-362',
    'SP05-363',
    'SP05-364',
    'SP05-365',
    'SP05-366',
    'SP05-367',
    'SP05-368',
    'SP05-369',
    'SP05-370',
    'SP05-371',
    'SP05-372',
  ],
  'pack_16|6. Samurai & Medieval': ['SP13-026', 'SP13-027', 'SP13-028', 'SP13-029', 'SP13-030'],
  'pack_16|7. Horror': ['SP13-031', 'SP13-032', 'SP13-033', 'SP13-034', 'SP13-035'],
  'pack_17|1. Dark Fantasy & Gothic Courts': [
    'SP17-001',
    'SP17-002',
    'SP17-003',
    'SP17-004',
    'SP17-005',
    'SP17-006',
    'SP17-007',
    'SP17-008',
    'SP17-009',
    'SP17-010',
    'SP17-011',
    'SP17-012',
    'SP17-045',
    'SP17-046',
    'SP17-047',
    'SP17-048',
    'SP17-049',
    'SP17-050',
    'SP17-051',
    'SP17-052',
    'SP17-073',
  ],
  'pack_17|2. Dungeon Zine & Risograph Prints': [
    'SP17-013',
    'SP17-014',
    'SP17-015',
    'SP17-016',
    'SP17-017',
    'SP17-018',
    'SP17-059',
    'SP17-060',
    'SP17-061',
    'SP17-062',
    'SP17-063',
  ],
  'pack_17|4. Rune-Tech & Apocalyptic Warfronts': [
    'SP17-019',
    'SP17-020',
    'SP17-021',
    'SP17-022',
    'SP17-023',
    'SP17-024',
    'SP17-025',
    'SP17-026',
    'SP17-027',
    'SP17-028',
    'SP17-029',
    'SP17-030',
    'SP17-031',
    'SP17-032',
  ],
  'pack_17|3. Ink, Tarot & Bestiary Plates': [
    'SP17-033',
    'SP17-034',
    'SP17-035',
    'SP17-036',
    'SP17-037',
    'SP17-038',
    'SP17-039',
    'SP17-040',
    'SP17-041',
    'SP17-042',
    'SP17-043',
    'SP17-044',
    'SP17-053',
    'SP17-054',
    'SP17-055',
    'SP17-056',
    'SP17-057',
    'SP17-058',
  ],
  'pack_17|5. Grimdark Game Systems & Tabletop': [
    'SP17-064',
    'SP17-065',
    'SP17-066',
    'SP17-067',
    'SP17-068',
    'SP17-069',
    'SP17-070',
    'SP17-071',
    'SP17-072',
  ],
};

const PACKS: Readonly<Record<string, PackPlan>> = {
  pack_12: { categories: gamePlans, details: gameDetails },
  pack_13: { categories: animePlans, details: animeDetails },
  pack_14: { categories: mythPlans, details: mythDetails },
  pack_15: { categories: punkPlans, details: punkDetails },
  pack_16: { categories: retroAnimePlans, details: animeDetails },
  pack_17: { categories: darkFantasyPlans, details: darkDetails },
};

function stableOrdinal(id: string, category: string): number {
  const match = /^SP(\d+)-(\d+)$/i.exec(id);
  if (match) return Number(match[1]) * 1000 + Number(match[2]);

  let hash = 2166136261;
  for (const char of `${id}|${category}`) {
    hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  }
  return hash >>> 0;
}

function categoryOffset(category: string, combinations: number): number {
  let hash = 2166136261;
  for (const char of category) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return (hash >>> 0) % combinations;
}

/** Returns a varied subject brief for legacy preview cards in packs 12–17. */
export function legacyBriefPacks12to17(pack: BriefPack, preset: BriefPreset): string | null {
  const packPlan = PACKS[pack.id];
  if (!packPlan) return null;

  const category = preset.category ?? '';
  const plan = packPlan.categories.find((candidate) => candidate.category.test(category));
  if (!plan) return null;

  const presetOrder = PRESET_ORDER_BY_CATEGORY[`${pack.id}|${category}`];
  const categoryRank = presetOrder?.indexOf(preset.id) ?? -1;
  const subjectIndex =
    categoryRank >= 0
      ? categoryRank % plan.subjects.length
      : stableOrdinal(preset.id, category) % plan.subjects.length;
  const pools = [plan.framing, packPlan.details];
  const combinationCount = pools.reduce((count, pool) => count * pool.length, 1);
  let ordinal =
    (stableOrdinal(preset.id, category) + categoryOffset(category, combinationCount)) %
    combinationCount;
  const choose = (values: readonly string[]) => {
    const value = values[ordinal % values.length]!;
    ordinal = Math.floor(ordinal / values.length);
    return value;
  };

  return `Create a representative card image of ${plan.subjects[subjectIndex]}; ${choose(plan.framing)}; ${choose(packPlan.details)}.`;
}
