// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP05-001',
    name: 'Retro Pioneer Hero',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Early television anime with large-eye era cues, simple shapes, brave retro energy, limited shadow tones, and earnest storytelling charm',
      form_and_line:
        'Rounded iconic form language, thick confident contouring, simplified in-between-friendly geometry, hand-inked cel cadence',
      color_palette:
        'Sun-warmed primaries, milk-soft skin midtones, subdued sky blues, faded analog broadcast chroma',
      lighting_setup:
        'Broadcast-era key-fill simplicity, stepped cel shadow bands, restrained rim accents, low dynamic-range highlights',
      material_texture:
        'Acetate cel edge shimmer, painted matte backgrounds, mild registration jitter, analog scan grain',
      render_quality:
        'Late-70s to early-80s TV anime fidelity with clean silhouette priority and era-authentic compositing softness',
      spatial_distortion:
        'Child-safe proportion push, focal emphasis for bravery beats, limited-perspective staging for readability',
      atmosphere: 'Nostalgic, optimistic, daring, spirited',
      key_features:
        'Earnest iconic silhouette language, warm cel-era optimism, emblematic posing rhythm, hand-painted scenic restraint',
      creative_brief:
        'Early TV-anime optimism should read immediately through bold contour clarity, emotionally direct posing, and warm analog cel color logic. Keep compositions clean, uplifting, and iconic, with craftsmanship rooted in hand-painted backgrounds and pre-digital broadcast constraints.',
    },
  },
  {
    id: 'SP05-311',
    name: 'Rusted Eco Hope Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Aventura ecológica postcolapso de espíritu luminoso, donde ruina tecnológica y rebrote natural conviven con esperanza activa.',
      form_and_line:
        'Contorno cel robusto con acting atlético, siluetas de salto y escalada, y gesto corporal optimista de exploración.',
      color_palette:
        'Turquesas oceánicos, óxidos rojizos, verdes de rebrote y blancos solares de cielo abierto.',
      lighting_setup:
        'Sol marítimo frontal de alto contraste, sombras cel cortas y rim ventoso para reforzar impulso acrobático.',
      material_texture:
        'Chapa oxidada, concreto salinizado, roca costera y vegetación resiliente sobre infraestructura antigua.',
      render_quality:
        'Acabado premium retro-aventura con lectura clara de movimiento, geografía insular y pulso ambiental optimista.',
      spatial_distortion:
        'Perspectiva amplia de acantilado e isla con verticalidad juguetona para enfatizar agilidad del protagonista.',
      atmosphere: 'Esperanzadora, energética, marina, aventurera.',
      key_features:
        'Óxido luminoso, rebrote ecológico, energía corporal, cielo abierto y lectura optimista de mundo dañado.',
      creative_brief:
        'Define una gramática reusable de aventura ecológica resiliente para cualquier prompt o imagen de entrada: óxido, aire abierto y esperanza activa sin imponer islas, costas, saltos juveniles ni infraestructura específica.',
    },
  },
  {
    id: 'SP05-003',
    name: 'Jazzy Rogue Heist Rhythm Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Picardía retro-jazz elegante, humor seco, glamour nocturno abstracto y tensión de engaño sofisticado.',
      form_and_line:
        'Trazo cel vintage afilado, gestualidad pícara y coreografía de timing musical sin acción fija.',
      color_palette:
        'Carbón nocturno, ámbar de farola, turquesa tenue y acentos crema de cartel antiguo.',
      lighting_setup:
        'Noir suave con contraluz recortado, reflejo húmedo y key focal en gesto de engaño.',
      material_texture:
        'Superficie mojada, tela textil elegante, cromado reflectante y grano telecine de caper setentero.',
      render_quality:
        'Acabado broadcast 80s de alto carácter, lectura clara de astucia, ritmo y puesta en escena.',
      spatial_distortion:
        'Perspectiva oblicua con encuadres de fuga, contrapicado de estilo y compresión de escape.',
      atmosphere: 'Jazzy, juguetona, traviesa, sofisticada.',
      key_features:
        'Silueta estilizada, ritmo de montaje heist, luces recortadas y acting de doble intención.',
      creative_brief:
        'Diseña una gramática reusable de jazzy-rogue-heist-rhythm para cualquier sujeto, priorizando elegancia táctica, ironía visual y swing nocturno sin imponer robos, calles, callejones, gabardinas, vitrinas ni dúos investigadores.',
    },
  },
  {
    id: 'SP05-004',
    name: 'Melancholy Astral Opera Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Ópera astral romántica, heroicidad melancólica, nobleza crepuscular y escala monumental.',
      form_and_line:
        'Línea cel clásica de figura elevada, drapeado amplio, acting contenido de añoranza y nobleza.',
      color_palette:
        'Índigos profundos, oro envejecido, rojo vino ceremonial y grises siderales desaturados.',
      lighting_setup:
        'Claroscuro estelar con key lateral dramática, halos de vacío y rim tenue sobre capa en movimiento.',
      material_texture:
        'Metal envejecido, terciopelo ceremonial, vidrio oscuro y grano analógico elegante.',
      render_quality:
        'Producción retro premium con lectura épica-lírica y composición de gran aliento visual.',
      spatial_distortion:
        'Grandes vacíos y ejes largos para enfatizar soledad heroica y destino itinerante.',
      atmosphere: 'Melancólica, heroica, anhelante, grandiosa.',
      key_features:
        'Drapeado icónico, silueta noble, escala axial y horizonte abstracto como contrapeso emocional.',
      creative_brief:
        'Construye una gramática reusable de melancholy-astral-opera para cualquier sujeto, equilibrando majestuosidad operática, soledad noble y escala crepuscular sin imponer corsarios, naves, uniformes, puentes, ventanales ni horizontes estelares literales.',
    },
  },
  {
    id: 'SP05-008',
    name: 'Neon Procedural Irony Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Procedural retro con filo cómico, elegancia precisa y tensión nocturna de deducción.',
      form_and_line: 'Trazo cel preciso, acting seco y blocking táctico con ritmo irónico.',
      color_palette: 'Cobalto nocturno, neón rosa-controlado, ámbar contenido y grafito frío.',
      lighting_setup:
        'Contraste de vidrio y sombra, reflejos húmedos y key dirigida para lectura de indicio visual.',
      material_texture:
        'Tejido elegante, metal vintage abstracto, vidrio lluvioso y grano cinematográfico pulcro.',
      render_quality:
        'Acabado broadcast 80s con equilibrio entre carisma procedural y ritmo de resolución.',
      spatial_distortion:
        'Profundidad oblicua con encuadres de vigilancia, giro táctico y resolución rápida.',
      atmosphere: 'Elegante, afilada, irónica, magnética.',
      key_features:
        'Siluetas elegantes, neón de expediente abstracto, acción compacta y humor procedural seco.',
      creative_brief:
        'Diseña una gramática reusable de neon-procedural-irony para cualquier sujeto, combinando sofisticación táctica, deducción visual y timing irónico sin imponer policías, detectives, calles, armas, trajes, ventanas ni persecuciones.',
    },
  },
  {
    id: 'SP05-009',
    name: 'Hyper-Dense Cyber-Retro Infrastructure Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Infraestructura cyber-retro hiperdensa, fricción social, velocidad mecánica y saturación sistémica.',
      form_and_line:
        'Línea detallista y nerviosa, estructura protagonista y dinámica de desplazamiento a máxima inercia.',
      color_palette:
        'Violeta eléctrico, verde neón, concreto gris-azul y rojos de señal disruptiva.',
      lighting_setup:
        'Brillo de señal superpuesto, flare industrial y sombras recortadas por capas elevadas.',
      material_texture:
        'Superficies calientes, chapa abstracta, señalética luminosa y suciedad tecnológica acumulada.',
      render_quality:
        'Acabado retro de alta complejidad visual con lectura clara de caos estructurado.',
      spatial_distortion:
        'Capas infraestructurales superpuestas para sensación de presión sistémica constante.',
      atmosphere: 'Eléctrica, rebelde, convulsa, adrenalínica.',
      key_features:
        'Horizonte saturado de ingeniería, movilidad agresiva, densidad señalética y pulso de revuelta.',
      creative_brief:
        'Construye una gramática reusable de hyper-dense-cyber-retro-infrastructure para cualquier sujeto, priorizando densidad arquitectónica, energía social y movimiento continuo sin imponer ciudad literal, calles, torres, vías, pasarelas ni cartelería concreta.',
    },
  },
  {
    id: 'SP05-010',
    name: 'Round Adventure Slapstick Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Aventura cómica de formas redondas, inocencia física, slapstick amable y energía itinerante.',
      form_and_line:
        'Trazo cel elástico y expresivo, timing de gag corporal y silueta cartoon de lectura instantánea.',
      color_palette:
        'Amarillos soleados, verdes vivos, naranjas suaves y azules limpios de viaje clásico.',
      lighting_setup:
        'Iluminación abierta de aventura diurna, sombra simple y acentos brillantes de humor físico.',
      material_texture: 'Polvo caricaturesco, tela simple, piedra ligera y grano retro optimista.',
      render_quality:
        'Acabado broadcast cálido con énfasis en claridad cómica y ternura de movimiento.',
      spatial_distortion:
        'Espacio expansivo y flexible para carrera, salto y choque cómico sin perder legibilidad.',
      atmosphere: 'Aventurera, alegre, juguetona, entrañable.',
      key_features:
        'Proporción redondeada, energía de troupe, beat de broma visual y choque amistoso.',
      creative_brief:
        'Define una gramática reusable de round-adventure-slapstick para cualquier sujeto, enfocada en elasticidad expresiva, optimismo narrativo y ritmo de gag físico sin imponer artes marciales, viajes, troupe, combate ni mundo expansivo literal.',
    },
  },
  {
    id: 'SP05-301',
    name: 'Analog Space Opera Command Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Ópera espacial clásica, con liturgia de mando analógico, solemnidad colectiva y supervivencia civilizatoria.',
      form_and_line:
        'Contorno grueso de ingeniería, siluetas jerarquizadas y acting decidido de mando clásico setentero.',
      color_palette:
        'Azules interestelares profundos, rojos de alerta analógica, grises metálicos y ámbares cálidos de interfaz.',
      lighting_setup:
        'Iluminación de alarma táctica con pools rojos intermitentes, key de interfaz y sombra cel de alta urgencia.',
      material_texture:
        'Paneles analógicos, metal pintado, fósforo de monitor y grano de telecine vintage.',
      render_quality:
        'Acabado premium retro-broadcast con lectura táctica clara y dramatismo emocional coral.',
      spatial_distortion:
        'Perspectiva forzada y escala cósmica monumental para enfatizar fragilidad humana frente al vacío.',
      atmosphere: 'Noble, urgente, cósmica, sacrificial.',
      key_features:
        'Paneles analógicos, jerarquía compositiva, alerta solemne, escala interestelar sugerida y heroísmo coral.',
      creative_brief:
        'Construye una gramática reusable de mando espacial analógico para cualquier prompt o imagen de entrada: tensión, ceremonia técnica y escala épica sin imponer puentes de nave, consolas, cascos ni tripulaciones.',
    },
  },
  {
    id: 'SP05-302',
    name: 'Melancholic Space Corsair Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Romanticismo corsario crepuscular, con ética disidente, elegancia fúnebre y soledad heroica.',
      form_and_line:
        'Silueta de capa dominante, línea heroica elongada y contornos limpios de icono outlaw de alto contraste.',
      color_palette:
        'Negros terciopelo, azules de abismo estelar, rojos vino de emblema y blancos fríos de insignia.',
      lighting_setup:
        'Contraluz estelar dramático con rim fuerte sobre capa y rostro, sombras planas de fuerte identidad gráfica.',
      material_texture:
        'Tejido pesado en movimiento, superficies de casco oscurecidas y señalética pirata de acabado clásico.',
      render_quality:
        'Terminación premium retro-operática con foco en presencia de figura única y aura de leyenda errante.',
      spatial_distortion:
        'Contraste de primerísimo monumental contra vacío astral negativo para acentuar aislamiento soberano.',
      atmosphere: 'Romántica, solitaria, rebelde, cósmica.',
      key_features:
        'Silueta imperial, vacío compositivo, viento estelar abstracto, emblemas oscuros y código moral insumiso.',
      creative_brief:
        'Crea una gramática reusable de leyenda corsaria melancólica para cualquier prompt o imagen de entrada: elegancia fúnebre, vacío y disidencia sin imponer capas, calaveras, capitanes ni naves.',
    },
  },
  {
    id: 'SP05-303',
    name: 'Celestial Journey Melancholy Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Balada cósmica de tránsito existencial, con nostalgia elegíaca, maravilla iniciática y horizonte infinito.',
      form_and_line:
        'Línea clásica de tránsito contemplativo, acting meditado y ritmo visual de trayecto largo.',
      color_palette:
        'Azules de noche profunda, dorados antiguos, blancos de nieve estelar y sepias de recuerdo.',
      lighting_setup: 'Faroles lechosos, calidez compartimentada y contraluz sobre vacío estelar.',
      material_texture:
        'Metal envejecido, vapor suave, madera antigua y película granulada de época.',
      render_quality:
        'Acabado premium retro-poético con legibilidad narrativa de tránsito y emoción de despedida continua.',
      spatial_distortion:
        'Perspectiva longitudinal, con profundidad astral que extiende sensación de viaje eterno.',
      atmosphere: 'Melancólica, maravillada, sideral, meditativa.',
      key_features:
        'Horizonte infinito, umbrales de viaje, equipaje simbólico abstracto, escala cósmica íntima y soledad luminosa.',
      creative_brief:
        'Diseña una gramática reusable de peregrinaje metafísico para cualquier prompt o imagen de entrada: viaje, despedida y escala cósmica íntima sin imponer trenes, estaciones, vías ni equipaje literal.',
    },
  },
  {
    id: 'SP05-304',
    name: 'Baroque Insurgent Melodrama Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Tragedia barroca insurgente, con glamour cortesano quebrado, sentimentalismo político y alto voltaje ornamental.',
      form_and_line:
        'Línea ornamental y estilizada, posturas de retrato ceremonial y gestualidad trágica de alta teatralidad histórica.',
      color_palette:
        'Marfiles empolvados, azules reales, rojos de rosa heráldica y dorados envejecidos.',
      lighting_setup:
        'Luz lateral ceremonial con sombras planas nobles, halos suaves sobre ornamento y contraste de protocolo.',
      material_texture:
        'Brocado ceremonial, encaje rígido, piedra pulida y pátina ornamental al borde del derrumbe.',
      render_quality:
        'Acabado premium retro-histórico con lectura de emblema visual y tensión dramática de destino.',
      spatial_distortion:
        'Composición profunda con eje de retrato frontal y presión histórica abstracta en segundo plano.',
      atmosphere: 'Regia, trágica, histórica, apasionada.',
      key_features:
        'Ornamento floral, protocolo visual, retrato trágico, sensualidad pictórica y sensación de fractura histórica.',
      creative_brief:
        'Define una gramática reusable de melodrama barroco insurgente para cualquier prompt o imagen de entrada: protocolo, ornamento y tensión política sin imponer uniformes, palacios, escalinatas ni aristocracia literal.',
    },
  },
  {
    id: 'SP05-305',
    name: 'Neon Sci-Fi Slapstick Rom-Com Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Sitcom sci-fi ochentera de caos afectivo, color fluorescente, slapstick corporal y fricción sentimental episódica.',
      form_and_line:
        'Contorno grueso caricaturesco, acting facial exagerado y timing visual de gag físico instantáneo.',
      color_palette:
        'Neones rosas y turquesa, amarillos eléctricos, azules nocturnos saturados y acentos pastel de sitcom.',
      lighting_setup:
        'Luz frontal televisiva con neón filtrado, contraste bajo y acentos de gag instantáneo.',
      material_texture:
        'Superficie doméstica plana, señalética fluorescente, utilería sci-fi ligera y grano retro de emisión.',
      render_quality:
        'Acabado premium retro-pop con claridad de broma, ritmo de caos y legibilidad de ensemble romántico.',
      spatial_distortion:
        'Espacio elástico de comedia con deformaciones leves para golpes visuales y persecuciones domésticas.',
      atmosphere: 'Hiperactiva, coqueta, neón, traviesa.',
      key_features:
        'Color fluorescente, timing corto, expresiones exageradas, gadgets absurdos sugeridos y fricción romántica caricaturesca.',
      creative_brief:
        'Construye una gramática reusable de rom-com sci-fi histriónica para cualquier prompt o imagen de entrada: neón, slapstick y caos afectivo sin imponer aliens, apartamentos, persecuciones ni iconografía oni.',
    },
  },
  {
    id: 'SP05-306',
    name: 'Adult Domestic Warmth Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Comedia romántica adulta de convivencia lenta, erosión cotidiana y ternura de segunda oportunidad.',
      form_and_line:
        'Línea suave de convivencia, actuación sutil de proximidad y composición íntima con humor de fricción diaria.',
      color_palette:
        'Ámbares de atardecer, marrones de madera vivida, verdes apagados y rojos discretos de intimidad.',
      lighting_setup:
        'Luz dorada de fin de tarde con sombras planas tranquilas y contraste bajo que favorece ternura acumulativa.',
      material_texture:
        'Superficies gastadas, telas colgadas, muebles usados y grano cálido de serie televisiva clásica.',
      render_quality:
        'Acabado premium retro-doméstico con énfasis en microdrama emocional y timing cómico cotidiano.',
      spatial_distortion:
        'Corredores estrechos y espacios conectados que intensifican roce emocional continuo.',
      atmosphere: 'Cálida, nostálgica, doméstica, paciente.',
      key_features:
        'Clutter habitable, luz de atardecer, microgesto afectivo, desgaste entrañable y humor cotidiano suave.',
      creative_brief:
        'Crea una gramática reusable de intimidad doméstica adulta para cualquier prompt o imagen de entrada: rutina, calidez y tiempo vivido sin imponer pensiones, balcones, vecinos ni romance explícito.',
    },
  },
  {
    id: 'SP05-307',
    name: 'Summer Sports Melodrama Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Melodrama deportivo de verano tardío, con rivalidad, duelo íntimo y crecimiento nostálgico.',
      form_and_line:
        'Línea atlética limpia, gesto contenido y composición que alterna acción física y pausa emocional.',
      color_palette:
        'Verdes soleados, naranjas de atardecer, blancos limpios y azules deslavados de verano tardío.',
      lighting_setup:
        'Sol bajo cálido con contraluces amplios y sombras planas que sostienen melancolía ligera.',
      material_texture:
        'Polvo seco, cuero cálido, tela funcional y grano fílmico de recuerdo deportivo.',
      render_quality:
        'Acabado retro-atlético premium con lectura táctica de esfuerzo y subtexto romántico en respiraciones largas.',
      spatial_distortion:
        'Perspectiva abierta con compresión selectiva en momentos de mirada y decisión sentimental.',
      atmosphere: 'Nostálgica, cálida, atlética, melancólica.',
      key_features:
        'Luz estival, presión competitiva, pausa antes del esfuerzo, deseo contenido y crescendo emocional.',
      creative_brief:
        'Diseña una gramática reusable de deporte sentimental juvenil para cualquier prompt o imagen de entrada: verano, competencia y maduración sin imponer baseball, diamantes, marcadores, dugouts ni adolescentes.',
    },
  },
  {
    id: 'SP05-308',
    name: 'Eighties Neon Precision Noir Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Noir ochentero seductor, con cinismo brillante, comedia insolente y peligro preciso.',
      form_and_line:
        'Contorno firme, acting de pose confiada y encuadres dinámicos de tensión vertical.',
      color_palette:
        'Azules nocturnos de cristal, morados neón, grises acero y acentos rojos de peligro instantáneo.',
      lighting_setup:
        'Neón alto reflejado en cristal, key cortante y sombras planas de thriller televisivo.',
      material_texture:
        'Vidrio nocturno, superficie brillante, tailoring texturado y metal pulido estilizado.',
      render_quality:
        'Acabado premium retro-noir con lectura clara de acción, punchline visual y elegancia precisa.',
      spatial_distortion: 'Profundidad vertical exagerada y lente de acción para ritmo de amenaza.',
      atmosphere: 'Suave, neón, irónica, peligrosa.',
      key_features:
        'Neón nocturno, verticalidad abstracta, moda 80s sugerida, ironía visual y contraste entre humor y amenaza.',
      creative_brief:
        'Construye una gramática reusable de noir ochentero de precisión para cualquier prompt o imagen de entrada: neón, cinismo y precisión tensa sin imponer skylines, armas, detectives ni violencia literal.',
    },
  },
  {
    id: 'SP05-309',
    name: 'Explosive Space Glam Action Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Space-action glam hiperpop, con elegancia táctica, croma explosivo y caos coreografiado.',
      form_and_line:
        'Siluetas fashion dinámicas, contorno cel contundente y lenguaje de pose dual coordinada en clave de impacto.',
      color_palette:
        'Blancos clínicos de corredor, rosas explosivos, cianes láser y acentos amarillos de advertencia pop.',
      lighting_setup:
        'Luz interior brillante de sci-fi retro con flashes de energía y sombras planas para legibilidad de acción veloz.',
      material_texture:
        'Corredor sci-fi pulido, textil técnico brillante, residuos de disparo láser y grano analógico televisivo.',
      render_quality:
        'Acabado premium retro-glam con claridad de dúo protagonista y balance entre espectacularidad y control.',
      spatial_distortion:
        'Corredores de fuga y combate con perspectiva lineal acelerada para subrayar velocidad y destrucción elegante.',
      atmosphere: 'Flashy, traviesa, pop, explosiva.',
      key_features:
        'Moda sci-fi abstracta, láseres de color, sincronía táctica sugerida, croma explosivo y composición de caos limpio.',
      creative_brief:
        'Diseña una gramática reusable de acción glam espacial para cualquier prompt o imagen de entrada: moda, energía táctica y color explosivo sin imponer dúos, pasillos, misiones ni protagonistas concretos.',
    },
  },
  {
    id: 'SP05-310',
    name: 'Competent Space Pulp Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Pulp espacial profesionalista, con ética de oficio, aventura resolutiva y optimismo técnico ochentero.',
      form_and_line:
        'Contorno robusto de diseño técnico, acting competente y staging funcional orientado a resolución práctica.',
      color_palette:
        'Naranjas operativos, azules técnicos, grises industriales y blancos de señal funcional.',
      lighting_setup:
        'Iluminación de mantenimiento con key frontal claro, sombras planas técnicas y acentos de baliza.',
      material_texture:
        'Metal usado, paneles de servicio, tejido técnico y desgaste mecánico de uso intensivo.',
      render_quality:
        'Acabado premium retro-pulp con foco en claridad procedimental, jerarquía funcional y acción resolutiva.',
      spatial_distortion:
        'Gran volumen operativo con líneas guía y flujo direccional para enfatizar competencia técnica.',
      atmosphere: 'Pulp, aventurera, competente, luminosa.',
      key_features:
        'Color-identidad fuerte, claridad procedimental, hardware funcional sugerido, oficio competente y aventura directa.',
      creative_brief:
        'Crea una gramática reusable de pulp espacial competente para cualquier prompt o imagen de entrada: oficio, claridad técnica y heroísmo práctico sin imponer trajes, hangares, tripulaciones ni rescates.',
    },
  },
  {
    id: 'SP05-312',
    name: 'Elegant Eighties Heist Glam Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Heist glam nocturno de alta elegancia, con sofisticación ochentera, precisión coreográfica y tensión de infiltración.',
      form_and_line:
        'Línea estilizada de figura felina, poses de infiltración milimétrica y coreografía silenciosa táctica.',
      color_palette: 'Rojos icónicos, negros cerrados, dorados de lujo y blancos de spotlight.',
      lighting_setup:
        'Conos de luz de seguridad, sombras planas marcadas y brillos reflectivos para tensión furtiva.',
      material_texture:
        'Piedra pulida, vidrio reflectivo, cuero técnico y grano analógico de serie nocturna retro.',
      render_quality:
        'Acabado premium de thriller elegante con legibilidad de movimiento furtivo y glamour controlado.',
      spatial_distortion:
        'Espacio abstracto con perspectiva profunda y capas de vigilancia que tensionan el vector de salida.',
      atmosphere: 'Astuta, elegante, nocturna, glamurosa.',
      key_features:
        'Rojo acento, lujo reflejado, ballet criminal abstracto, siluetas elegantes y precisión estratégica.',
      creative_brief:
        'Construye una gramática reusable de heist glam para cualquier prompt o imagen de entrada: elegancia, reflejos y tensión furtiva sin imponer tríos, ladronas, museos, vitrinas ni leotardos.',
    },
  },
  {
    id: 'SP05-313',
    name: 'Zodiac Cosmic Heroism Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Épica zodiacal juvenil, con fraternidad heroica, brillo ritual y dramatismo cósmico declarativo.',
      form_and_line:
        'Contornos brillantes, anatomía heroica elongada y poses de impacto frontal con energía ritual sagrada.',
      color_palette:
        'Azules celestes, dorados astrales, blancos marmóreos y rojos de voluntad combativa.',
      lighting_setup:
        'Flares de constelación sobre clave dura de cel, sombras planas dramáticas y rim luminoso en bordes ornamentales.',
      material_texture:
        'Brillo ceremonial pulido, piedra mítica abstracta, partículas de impacto y grano analógico retro.',
      render_quality:
        'Acabado premium retro-shonen con lectura instantánea de equipo, poder astral y escalada de intensidad.',
      spatial_distortion:
        'Perspectiva monumental ascendente para amplificar sacrificio, impacto y destino estelar.',
      atmosphere: 'Mítica, vehemente, celeste, sacrificial.',
      key_features:
        'Iconografía estelar, brillo ritual, estelas cósmicas, pose declarativa y emoción combativa juvenil.',
      creative_brief:
        'Diseña una gramática reusable de heroísmo zodiacal para cualquier prompt o imagen de entrada: cosmos, brillo y juramento visual sin imponer armaduras, templos, escalinatas ni combates literales.',
    },
  },
  {
    id: 'SP05-317',
    name: 'Arcade Techno-Rebellion Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Retrofuturo rebelde de OVA ochentera, con neón sintético, velocidad gráfica y paranoia de sistema encubierto.',
      form_and_line:
        'Trazado afilado de señalética, diagonales cinéticas y silueta rebelde como eje de identidad visual.',
      color_palette: 'Cianes y magentas arcade, violetas sintéticos de twilight y negros húmedos.',
      lighting_setup:
        'Derrame de neón nocturno, parpadeo de cartelería abstracta y contraste cel duro con backfill de sodio.',
      material_texture:
        'Brillo de lluvia sobre superficie oscura, borde de bloom CRT y grano analógico de video-era.',
      render_quality:
        'Acabado premium OVA retro-tech con claridad de velocidad y atmósfera de inquietud sistémica.',
      spatial_distortion:
        'Perspectiva de avance forzado con compresión profunda para enfatizar fuga y revelación.',
      atmosphere: 'Elegante, rebelde, nocturna, revelatoria.',
      key_features:
        'Overlays de arcade, neón sintético, velocidad lateral, vigilancia abstracta y revelación de verdad oculta.',
      creative_brief:
        'Diseña una gramática reusable de techno-rebeldía ochentera para cualquier prompt o imagen de entrada: arcade, velocidad y paranoia sin imponer motos, carreteras, skylines ni riders.',
    },
  },
  {
    id: 'SP05-320',
    name: 'Charismatic Space Rogue Pulp Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Pulp espacial canalla de carisma seductor, humor insolente y peligro cool en clave noir retrofuturista.',
      form_and_line:
        'Silueta rogue confiada, postura relajada de tensión y contorno cel limpio con staging pulp de viñeta dinámica.',
      color_palette: 'Rojo dominante, púrpuras interestelares, ámbar ahumado y azules acero.',
      lighting_setup:
        'Iluminación lounge-noir, bordes de energía, charcos de luz baja y rim estelar cosmopolita.',
      material_texture:
        'Brillo de vestuario retro, humo difuso de ambiente, superficies sci-fi cepilladas y grano compositivo analógico.',
      render_quality:
        'Acabado premium pulp-80s con legibilidad total del protagonista y atmósfera de peligro juguetón.',
      spatial_distortion:
        'Encuadre centrado en carisma con profundidad comprimida y dinámica one-vs-many de alta confianza.',
      atmosphere: 'Desfachatada, cósmica, juguetona, peligrosa.',
      key_features:
        'Rojo acento, silueta relajada, amenaza elegante, ironía visual y lujo retrofuturista sugerido.',
      creative_brief:
        'Construye una gramática reusable de rogue pulp espacial para cualquier prompt o imagen de entrada: seducción, ironía y amenaza elegante sin imponer chaquetas, láseres, clubes ni anti-héroes concretos.',
    },
  },
  {
    id: 'SP05-315',
    name: 'Angular Institutional Tragedy Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Tragedia política áspera, donde juventud, geometría coercitiva e institución opresiva chocan.',
      form_and_line:
        'Contorno angular severo, siluetas rígidas y actuación contenida de trauma bajo presión institucional.',
      color_palette:
        'Grises industriales, azules fríos de interfaz, rojos de alerta táctica y blancos desaturados.',
      lighting_setup:
        'Luz dura de control institucional, sombras cel planas tajantes y destellos de interfaz en rostros tensos.',
      material_texture:
        'Aleación pesada, vidrio fracturable, paneles tácticos y ruido analógico de señal en crisis.',
      render_quality:
        'Acabado premium retro-institucional con lectura estratégica clara y peso emocional de decisión irreversible.',
      spatial_distortion:
        'Profundidad comprimida y escala opresiva para reforzar claustrofobia política.',
      atmosphere: 'Tensa, institucional, trágica, cortante.',
      key_features:
        'Geometría angular, luz de conflicto, códigos abstractos de poder, crisis psicológica y masa opresiva.',
      creative_brief:
        'Diseña una gramática reusable de tragedia institucional angular para cualquier prompt o imagen de entrada: aristas, trauma y poder opresivo sin imponer colonias, cabinas, pilotos, facciones ni máquinas concretas.',
    },
  },
  {
    id: 'SP05-002',
    name: 'Vintage Mechanical Grandeur Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Heavy chrome grandeur, heroic massing, bold retro machinery logic, rivet detailing, and triumphant analog scale.',
      form_and_line:
        'Chunky silhouette blocking, rivet-conscious contouring, mechanical panel breaks, and impact-line emphasis.',
      color_palette:
        'Saturated super-robot primaries with steel neutrals, hot warning reds, and heroic contrast blocks',
      lighting_setup:
        'Hard directional key with dramatic cel shadow wedges, metallic rim splits, and backlight flare.',
      material_texture:
        'Painted steel plate cues, cel-highlighted chrome edges, analog matte background treatment, scanline-era grain',
      render_quality:
        'Classic broadcast frame quality with strong mechanical readability and era-faithful cel compositing.',
      spatial_distortion:
        'Extreme low-angle heroic framing, launch-vector perspective exaggeration, and scale-first composition logic.',
      atmosphere: 'Action-heavy, triumphant, intense, explosive',
      key_features:
        'Monumental massing grammar, riveted panel articulation, launch-vector perspective drama, and metallic cel highlight choreography.',
      creative_brief:
        'Preserve vintage mechanical grandeur through heavy silhouette logic, high-contrast cel shading, riveted articulation, and emotionally maximal hero framing. Transfer this logic to any subject or input image without requiring robots, vehicles, launch bays, pilots, or machinery as literal content.',
    },
  },
  {
    id: 'SP05-005',
    name: 'Grounded Tactical Machinery Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Maquinaria táctica terrenal, doctrina funcional, fatiga de campaña y sobriedad operacional.',
      form_and_line:
        'Línea técnica robusta, panelado legible y acting de tensión logística continua.',
      color_palette:
        'Olivas apagados, tierra polvorienta, acero mate y rojos mínimos de señal de riesgo.',
      lighting_setup:
        'Luz dura de campo abierto, sombras secas de blindaje y reflejos discretos en metal funcional.',
      material_texture:
        'Superficie rayada, barro compactado, lona técnica y grano viejo de crónica operacional.',
      render_quality:
        'Acabado retro de precisión mecánica con claridad documental de hardware y cadena funcional.',
      spatial_distortion:
        'Profundidad por capas tácticas con bloqueos, cobertura abstracta y avance pesado.',
      atmosphere: 'Seria, devastada, áspera, resiliente.',
      key_features:
        'Masa funcional, mapa táctico implícito, desgaste prolongado y peso logístico visible.',
      creative_brief:
        'Define una gramática reusable de grounded-tactical-machinery para cualquier sujeto, priorizando funcionalidad mecánica, disciplina táctica y peso logístico sin imponer mechas, vehículos, frentes de guerra, escuadras, mapas ni campo de batalla.',
    },
  },
  {
    id: 'SP05-006',
    name: 'Pop Transformable Aerial Spectacle Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Espectáculo pop transformable de alto brillo, teatralidad aérea y emoción de clímax performático.',
      form_and_line:
        'Trazo cel dinámico con coreografía de ascenso y transición performance-heroísmo.',
      color_palette:
        'Magentas de show, cian eléctrico, blanco perlado y acentos metálicos cromados.',
      lighting_setup:
        'Spotlights glam combinados con flare técnico, rim brillante y gradiente futurista.',
      material_texture:
        'Lentejuela textil, pintura técnica brillante, panel translúcido y grano cálido broadcast.',
      render_quality:
        'Acabado retro premium de espectáculo híbrido con legibilidad simultánea de ícono pop y tecnología.',
      spatial_distortion:
        'Espacio elevado y ascendente conectado por encuadres de transformación y vuelo gráfico.',
      atmosphere: 'Radiante, emotiva, espectacular, eufórica.',
      key_features:
        'Silueta pop distintiva, transformación técnica, iluminación de show y gestualidad de clímax.',
      creative_brief:
        'Diseña una gramática reusable de pop-transformable-aerial-spectacle para cualquier sujeto, equilibrando brillo escénico, ingeniería heroica y emoción de directo sin imponer idols, mechas, escenarios, conciertos, cockpits, aeronaves ni combate.',
    },
  },
  {
    id: 'SP05-314',
    name: 'Monumental Formation Sacrifice Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Drama de entrenamiento y sacrificio extremo, con vulnerabilidad emotiva, escala cósmica y determinación formativa.',
      form_and_line:
        'Línea cel de alto contraste, close-ups emocionales intensos y siluetas monumentales frente a fragilidad humana.',
      color_palette:
        'Azules nocturnos de base, blancos técnicos, rojos de alarma y naranjas de impulso terminal.',
      lighting_setup:
        'Luz industrial con destellos de energía, sombras planas rígidas y backlight de cuenta regresiva emocional.',
      material_texture:
        'Masa técnica pesada, paneles funcionales, superficies de esfuerzo y grano televisivo ochentero.',
      render_quality:
        'Acabado premium retro-dramático con énfasis en escala, cuerpo vulnerable y crescendo emocional de partida.',
      spatial_distortion:
        'Perspectiva vertical extrema que magnifica madurez forzada y salto irreversible.',
      atmosphere: 'Sincera, grandiosa, llorosa, heroica.',
      key_features:
        'Escala colosal, lágrimas de determinación, infraestructura abstracta, salto irreversible y emoción formativa.',
      creative_brief:
        'Crea una gramática reusable de heroísmo formativo monumental para cualquier prompt o imagen de entrada: entrenamiento, sacrificio y escala cósmica sin imponer academias, plataformas, motores, pilotos ni lanzamientos.',
    },
  },
  {
    id: 'SP05-316',
    name: 'Biomorphic Mist Ritual Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Fantasía biomórfica de extrañeza onírica, con tecnología ritual, niebla viva y siluetas quiméricas.',
      form_and_line:
        'Siluetas quiméricas con línea orgánico-metálica, poses heroicas y contorno clásico de cel.',
      color_palette:
        'Verdes brumosos, violetas de crepúsculo arcano, metales opacos y acentos lumínicos etéreos.',
      lighting_setup:
        'Niebla luminosa como fuente principal, key suave de contracampo y sombras planas que conservan legibilidad retro.',
      material_texture:
        'Quitina metálica, membranas translúcidas, materia húmeda fantástica y ruido fílmico analógico.',
      render_quality:
        'Acabado premium retro-fantasy con claridad de diseño híbrido y atmósfera de tensión irreal sostenida.',
      spatial_distortion:
        'Profundidad brumosa con distorsión ligera de escala para reforzar mundo no terrestre.',
      atmosphere: 'Extraña, brumosa, heroica, ultraterrena.',
      key_features:
        'Niebla viva, siluetas quiméricas, biología mecánica, brillo ritual y relieve fantástico abstracto.',
      creative_brief:
        'Construye una gramática reusable de fantasía biomórfica para cualquier prompt o imagen de entrada: niebla, quimera y tecnología ritual sin imponer insectos, espadas, guerras ni mechas.',
    },
  },
  {
    id: 'SP05-318',
    name: 'Psychedelic Demonic Horror Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Horror demónico setentero de violencia expresionista, con transformación corporal cruda y tragedia sin filtro.',
      form_and_line:
        'Deformación anatómica agresiva, trazo quebrado de metamorfosis y energía de tinta frenética.',
      color_palette:
        'Rojos hemáticos ácidos, amarillos tóxicos, violetas infernales y blancos de pánico estroboscópico.',
      lighting_setup:
        'Estallidos de contraste, subluces de horror y sombras cel inestables con artefacto de señal analógica.',
      material_texture:
        'Pintura cel rugosa, sangrado croma de TV antigua y fondos deteriorados de pincel duro.',
      render_quality:
        'Acabado premium de shock-retro deliberadamente abrasivo, con legibilidad emocional asentada en confrontación visual.',
      spatial_distortion:
        'Warping de body horror y encuadre desorientado impulsado por dolor de transformación.',
      atmosphere: 'Pánico, psicodelia, tragedia, primalidad.',
      key_features:
        'Agonía metamórfica, simbolismo apocalíptico, brutalidad cromática, grano de broadcast antiguo e impacto visceral.',
      creative_brief:
        'Construye una gramática reusable de horror demónico expresionista para cualquier prompt o imagen de entrada: transformación, crudeza y tragedia cromática sin imponer demonios literales ni escenas de violencia concreta.',
    },
  },
  {
    id: 'SP05-007',
    name: 'Wasteland Impact Legend Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Épica de supervivencia brutal, impacto físico extremo, ferocidad ritual y dureza post-colapso.',
      form_and_line:
        'Línea gruesa y cortante, anatomía hipertensa y puesta de golpe frontal con lectura brutal inmediata.',
      color_palette:
        'Ocres abrasados, negros pesados, rojos secos y acentos hueso de paisaje devastado.',
      lighting_setup:
        'Sol alto implacable y sombras densas, con destellos duros sobre sudor, metal y cuero gastado.',
      material_texture:
        'Cuero curtido, polvo volcánico, cicatriz visible y grano áspero de cinta analógica violenta.',
      render_quality:
        'Acabado retro de alto contraste corporal, privilegiando contundencia, daño y resiliencia.',
      spatial_distortion:
        'Horizonte árido abstracto con encuadres de colisión directa y escala de choque primitivo.',
      atmosphere: 'Brutal, icónica, tensa, visceral.',
      key_features:
        'Siluetas masivas, gesto de supervivencia, dureza wasteland y coreografía de impacto sin ornamento.',
      creative_brief:
        'Construye una gramática reusable de wasteland-impact-legend para cualquier sujeto, enfocada en peso físico, dureza material y catarsis de choque sin imponer desiertos, duelos, guerreros, cuero, cicatrices ni combate literal.',
    },
  },
  {
    id: 'SP05-319',
    name: 'Strategic Pop Duality Style',
    category: '11. 70s & 80s Retro Anime',
    negativePrompt:
      'realistic, 3d render, photo, live action, western comic, ugly, bad anatomy, low quality, jpeg artifacts, watermark, text, signature',
    style: {
      aesthetic:
        'Ópera pop de dualidad estratégica y espectáculo emocional, donde tensión técnica y melodrama cromático coexisten.',
      form_and_line:
        'Doble registro de línea, rigidez operacional y fluidez performativa de espectáculo.',
      color_palette:
        'Grises tácticos, rojos de alerta, azules estelares y pasteles pop de contrapeso emocional.',
      lighting_setup:
        'Haze técnico combinado con spot escénico, glow de interfaz y contraluces cósmicos de gran dramatismo.',
      material_texture:
        'Placas pintadas, marcas operativas, superficies de show y shimmer de borde cel analógico.',
      render_quality:
        'Acabado premium retro-futuro con balance nítido entre lectura táctica y catarsis pop escénica.',
      spatial_distortion:
        'Escala macro contrapuesta a encuadre íntimo performativo para tensión entre estrategia y canción.',
      atmosphere: 'Romántica, estratégica, pop, sideral.',
      key_features:
        'Contraste táctico-pop, escala operática, color pop, melodrama estratégico y diseño técnico sentimental.',
      creative_brief:
        'Diseña una gramática reusable de pop estratégico dual para cualquier prompt o imagen de entrada: estrategia, espectáculo y romance gráfico sin imponer carrier decks, idols, ciudades nave, mechas ni operaciones militares.',
    },
  },
] as unknown as StyleRuntimePreset[];
