// Generated from assets/recipes/character-lab/character-lab-option-atlas.manifest.json.
// Do not hand-edit frame coordinates.
export const CHARACTER_LAB_OPTION_ICON_ATLAS_URL = new URL(
  '../assets/recipes/character-lab/character-lab-option-atlas.png',
  import.meta.url,
).href;
export const CHARACTER_LAB_OPTION_ICON_ATLAS_CELL_SIZE = 128;
export const CHARACTER_LAB_OPTION_ICON_ATLAS_WIDTH = 2048;
export const CHARACTER_LAB_OPTION_ICON_ATLAS_HEIGHT = 1536;
export const CHARACTER_LAB_OPTION_ICON_FRAMES = {
  'option:expression:neutral': {
    x: 0,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:happy': {
    x: 128,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:sad': {
    x: 256,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:angry': {
    x: 384,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:surprised': {
    x: 512,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:determined': {
    x: 640,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:annoyed': {
    x: 768,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:confident': {
    x: 896,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:scared': {
    x: 1024,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:sarcastic': {
    x: 1152,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:shy-timid': {
    x: 1280,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:smug': {
    x: 1408,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:exhausted': {
    x: 1536,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:joyful': {
    x: 1664,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:worried': {
    x: 1792,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:expression:flirty': {
    x: 1920,
    y: 0,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:1-1': {
    x: 0,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:21-9': {
    x: 128,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:16-9': {
    x: 256,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:4-3': {
    x: 384,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:3-2': {
    x: 512,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:9-16': {
    x: 640,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:3-4': {
    x: 768,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:2-3': {
    x: 896,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:5-4': {
    x: 1024,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:aspect-ratio:4-5': {
    x: 1152,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:preserve-original': {
    x: 1280,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:anime-manga': {
    x: 1408,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:90s-anime-cel-shaded': {
    x: 1536,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:modern-anime-digital': {
    x: 1664,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:studio-ghibli-inspired': {
    x: 1792,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:horror-manga-junji-ito': {
    x: 1920,
    y: 128,
    w: 128,
    h: 128,
  },
  'option:style:action-manga-akira-toriyama': {
    x: 0,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:seinen-manga-takehiko-inoue': {
    x: 128,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:70s-retro-mecha-action-anime': {
    x: 256,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:cartoon-toon': {
    x: 384,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:american-comic-book': {
    x: 512,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:vintage-comic-1960s': {
    x: 640,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:graphic-novel-noir': {
    x: 768,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:chibi': {
    x: 896,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:vector-art': {
    x: 1024,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:flat-design': {
    x: 1152,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:psychedelic-art': {
    x: 1280,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:pixel-art-16-bit': {
    x: 1408,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:pixel-art-32-bit': {
    x: 1536,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:voxel-art': {
    x: 1664,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:glitch-art': {
    x: 1792,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:synthwave-retrowave': {
    x: 1920,
    y: 256,
    w: 128,
    h: 128,
  },
  'option:style:retro-2d-rpg-snes': {
    x: 0,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:ps1-n64-era-3d': {
    x: 128,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:ps2-era-3d': {
    x: 256,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:cel-shaded-3d-wind-waker': {
    x: 384,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:souls-like-dark-fantasy': {
    x: 512,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:modern-aaa-realism': {
    x: 640,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:fighting-game-style': {
    x: 768,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:mobile-game-style': {
    x: 896,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:visual-novel-style': {
    x: 1024,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:3d-render-modern': {
    x: 1152,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:3d-render-retro-ps1': {
    x: 1280,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:low-poly-3d': {
    x: 1408,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:claymation-style': {
    x: 1536,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:concept-art-sketch': {
    x: 1664,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:concept-art-polished': {
    x: 1792,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:matte-painting': {
    x: 1920,
    y: 384,
    w: 128,
    h: 128,
  },
  'option:style:watercolor-painting': {
    x: 0,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:oil-painting': {
    x: 128,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:charcoal-sketch': {
    x: 256,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:ukiyo-e-woodblock': {
    x: 384,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:stained-glass': {
    x: 512,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:art-nouveau': {
    x: 640,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:art-deco': {
    x: 768,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:surrealism-dali-esque': {
    x: 896,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:style:technical-drawing-blueprint': {
    x: 1024,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:preserve-original': {
    x: 1152,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:fantasy-knight-armor': {
    x: 1280,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:wizard-robes': {
    x: 1408,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:rogue-s-leather-tunic': {
    x: 1536,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:elven-silks': {
    x: 1664,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:barbarian-furs': {
    x: 1792,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:druid-s-ceremonial-robes': {
    x: 1920,
    y: 512,
    w: 128,
    h: 128,
  },
  'option:clothing:bard-s-colorful-attire': {
    x: 0,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:necromancer-s-dark-cloak': {
    x: 128,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:dwarven-smithing-apron': {
    x: 256,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:warlock-s-shadow-weave-robes': {
    x: 384,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:paladin-s-holy-plate-armor': {
    x: 512,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:vampire-noble-attire': {
    x: 640,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:nomad-desert-wraps': {
    x: 768,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:plague-doctor-outfit': {
    x: 896,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:king-s-royal-garb': {
    x: 1024,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:jester-s-motley': {
    x: 1152,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:celestial-sage-robes': {
    x: 1280,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:fae-touched-silken-garb': {
    x: 1408,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:orcish-warchief-plate': {
    x: 1536,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:sci-fi-power-armor': {
    x: 1664,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:galactic-explorer-jumpsuit': {
    x: 1792,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:cyberpunk-gear': {
    x: 1920,
    y: 640,
    w: 128,
    h: 128,
  },
  'option:clothing:steampunk-attire': {
    x: 0,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:cyberpunk-netrunner-suit': {
    x: 128,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:post-apocalyptic-heavy-armor': {
    x: 256,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:space-pirate-gear': {
    x: 384,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:starship-captain-uniform': {
    x: 512,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:android-shell-exposed-circuits': {
    x: 640,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:void-walker-s-suit': {
    x: 768,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:biomechanical-suit': {
    x: 896,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:solar-punk-artisan-wear': {
    x: 1024,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:retro-futuristic-spaceman-suit': {
    x: 1152,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:samurai-armor': {
    x: 1280,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:kimono': {
    x: 1408,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:victorian-era-ball-gown': {
    x: 1536,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:viking-raider-leathers': {
    x: 1664,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:egyptian-pharaoh-regalia': {
    x: 1792,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:roaring-20s-flapper-dress': {
    x: 1920,
    y: 768,
    w: 128,
    h: 128,
  },
  'option:clothing:1950s-greaser-leather-jacket-jeans': {
    x: 0,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:1980s-new-wave-fashion': {
    x: 128,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:modern-casual-wear': {
    x: 256,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:streetwear-oversized-hoodie-cargo-pants-chunky-sneakers': {
    x: 384,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:skater-punk-outfit': {
    x: 512,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:techwear-functional-futuristic': {
    x: 640,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:hypebeast-outfit-designer-brands-rare-sneakers': {
    x: 768,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:graffiti-artist-wear-paint-splattered-clothes-beanie': {
    x: 896,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:drill-rapper-tracksuit-balaclava-designer-bag': {
    x: 1024,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:lo-fi-beats-listener-oversized-sweater-beanie-round-glasses': {
    x: 1152,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:dark-academia-tweed-blazer-turtleneck-trousers': {
    x: 1280,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:light-academia-linen-shirt-light-colored-sweater-chinos': {
    x: 1408,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:preppy-ivy-league-style-polo-shirt-khaki-shorts-boat-shoes': {
    x: 1536,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:librarian-chic-cardigan-button-up-shirt-glasses': {
    x: 1664,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:art-student-paint-splattered-overalls-quirky-earrings-tote-bag': {
    x: 1792,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:chaotic-academia-mismatched-patterns-worn-out-sweaters-disheveled-look': {
    x: 1920,
    y: 896,
    w: 128,
    h: 128,
  },
  'option:clothing:goth-black-clothing-leather-silver-jewelry': {
    x: 0,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:pastel-goth-pastel-colors-with-goth-elements': {
    x: 128,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:punk-rocker-ripped-jeans-band-t-shirt-studded-jacket': {
    x: 256,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:metalhead-black-band-shirt-denim-vest-leather-pants': {
    x: 384,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:e-girl-e-boy-outfit-striped-shirt-chains-beanie': {
    x: 512,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:hipster-attire-beanie-flannel': {
    x: 640,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:scene-kid-2000s-revival-coontails-bright-colors-skinny-jeans': {
    x: 768,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:health-goth-monochromatic-athletic-wear-futuristic-look': {
    x: 896,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:witchcore-long-black-dress-occult-symbols-layered-shawls': {
    x: 1024,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:cottagecore-outfit-flowy-dress-knitted-cardigan-rustic': {
    x: 1152,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:minimalist-chic-neutral-colors-clean-lines-simple-silhouette': {
    x: 1280,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:y2k-revival-fashion-low-rise-jeans-crop-top-colorful-accessories': {
    x: 1408,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:bohemian-boho-chic-flowing-fabrics-earthy-tones-fringe': {
    x: 1536,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:gamer-streamer-casual-comfortable-hoodie-headphones-merch': {
    x: 1664,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:tech-bro-uniform-branded-fleece-vest-button-down-sneakers': {
    x: 1792,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:vsco-girl-oversized-t-shirt-shell-necklace-scrunchies': {
    x: 1920,
    y: 1024,
    w: 128,
    h: 128,
  },
  'option:clothing:normcore-unbranded-basics-simple-jeans-plain-sneakers': {
    x: 0,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:baddie-aesthetic-bodycon-dress-perfect-makeup-high-heels': {
    x: 128,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:plant-mom-dad-linen-shirt-practical-pants-surrounded-by-plants': {
    x: 256,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:dark-cottagecore-goblincore-earthy-tones-mushroom-motifs-slightly-worn-l': {
    x: 384,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:clowncore-rainbow-patterns-oversized-collars-playful-accessories': {
    x: 512,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:fairycore-faecore-ethereal-dresses-flower-crowns-delicate-wings': {
    x: 640,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:athleisure-wear': {
    x: 768,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:gorpcore-hiker-chic-technical-jacket-cargo-shorts-hiking-boots': {
    x: 896,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:surfer-style-board-shorts-tank-top-flip-flops': {
    x: 1024,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:yoga-instructor-yoga-pants-sports-bra-serene-expression': {
    x: 1152,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:cyclist-gear-lycra-shorts-cycling-jersey-helmet': {
    x: 1280,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:business-casual-attire': {
    x: 1408,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:formal-suit-tuxedo': {
    x: 1536,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:modern-business-suit-slim-fit-no-tie': {
    x: 1664,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:creative-professional-stylish-blazer-dark-jeans-designer-sneakers': {
    x: 1792,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:startup-founder-branded-hoodie-expensive-sneakers-confident-stance': {
    x: 1920,
    y: 1152,
    w: 128,
    h: 128,
  },
  'option:clothing:barista-uniform-apron-t-shirt-comfortable-shoes': {
    x: 0,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:summer-beachwear': {
    x: 128,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:winter-wear-puffer-jacket': {
    x: 256,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:vintage-aviator-jacket': {
    x: 384,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:festival-goer-fringe-face-glitter-denim-shorts': {
    x: 512,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:tourist-outfit-hawaiian-shirt-shorts-camera-around-neck': {
    x: 640,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:pajamas-loungewear-cozy-sweatpants-and-a-soft-shirt': {
    x: 768,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:noir-detective-trenchcoat': {
    x: 896,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:superhero-spandex-suit': {
    x: 1024,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:royal-gown': {
    x: 1152,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:gothic-victorian-attire': {
    x: 1280,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:gothic-lolita-dress': {
    x: 1408,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:post-apocalyptic-scavenger': {
    x: 1536,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:wasteland-raider-leathers': {
    x: 1664,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:tribal-hunter-garb': {
    x: 1792,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:circus-ringleader-costume': {
    x: 1920,
    y: 1280,
    w: 128,
    h: 128,
  },
  'option:clothing:mad-scientist-lab-coat': {
    x: 0,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:preserve-original': {
    x: 128,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:thinner': {
    x: 256,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:very-thin': {
    x: 384,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:skeletal-emaciated': {
    x: 512,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:heavier': {
    x: 640,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:obese': {
    x: 768,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:morbidly-obese': {
    x: 896,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:athletically-fit': {
    x: 1024,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:lean-muscle': {
    x: 1152,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:stocky-burly': {
    x: 1280,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:exaggerated-muscles': {
    x: 1408,
    y: 1408,
    w: 128,
    h: 128,
  },
  'option:body-type:hyper-muscular': {
    x: 1536,
    y: 1408,
    w: 128,
    h: 128,
  },
} as const;
const CHARACTER_LAB_OPTION_ICON_METADATA = {
  'option:expression:neutral': {
    field: 'expression',
    label: 'Neutral',
    detail: '',
  },
  'option:expression:happy': {
    field: 'expression',
    label: 'Happy',
    detail: '',
  },
  'option:expression:sad': {
    field: 'expression',
    label: 'Sad',
    detail: '',
  },
  'option:expression:angry': {
    field: 'expression',
    label: 'Angry',
    detail: '',
  },
  'option:expression:surprised': {
    field: 'expression',
    label: 'Surprised',
    detail: '',
  },
  'option:expression:determined': {
    field: 'expression',
    label: 'Determined',
    detail: '',
  },
  'option:expression:annoyed': {
    field: 'expression',
    label: 'Annoyed',
    detail: '',
  },
  'option:expression:confident': {
    field: 'expression',
    label: 'Confident',
    detail: '',
  },
  'option:expression:scared': {
    field: 'expression',
    label: 'Scared',
    detail: '',
  },
  'option:expression:sarcastic': {
    field: 'expression',
    label: 'Sarcastic',
    detail: '',
  },
  'option:expression:shy-timid': {
    field: 'expression',
    label: 'Shy / Timid',
    detail: '',
  },
  'option:expression:smug': {
    field: 'expression',
    label: 'Smug',
    detail: '',
  },
  'option:expression:exhausted': {
    field: 'expression',
    label: 'Exhausted',
    detail: '',
  },
  'option:expression:joyful': {
    field: 'expression',
    label: 'Joyful',
    detail: '',
  },
  'option:expression:worried': {
    field: 'expression',
    label: 'Worried',
    detail: '',
  },
  'option:expression:flirty': {
    field: 'expression',
    label: 'Flirty',
    detail: '',
  },
  'option:aspect-ratio:1-1': {
    field: 'aspect-ratio',
    label: '1:1',
    detail: 'Square',
  },
  'option:aspect-ratio:21-9': {
    field: 'aspect-ratio',
    label: '21:9',
    detail: 'Landscape',
  },
  'option:aspect-ratio:16-9': {
    field: 'aspect-ratio',
    label: '16:9',
    detail: 'Landscape',
  },
  'option:aspect-ratio:4-3': {
    field: 'aspect-ratio',
    label: '4:3',
    detail: 'Landscape',
  },
  'option:aspect-ratio:3-2': {
    field: 'aspect-ratio',
    label: '3:2',
    detail: 'Landscape',
  },
  'option:aspect-ratio:9-16': {
    field: 'aspect-ratio',
    label: '9:16',
    detail: 'Portrait',
  },
  'option:aspect-ratio:3-4': {
    field: 'aspect-ratio',
    label: '3:4',
    detail: 'Portrait',
  },
  'option:aspect-ratio:2-3': {
    field: 'aspect-ratio',
    label: '2:3',
    detail: 'Portrait',
  },
  'option:aspect-ratio:5-4': {
    field: 'aspect-ratio',
    label: '5:4',
    detail: 'Flexible',
  },
  'option:aspect-ratio:4-5': {
    field: 'aspect-ratio',
    label: '4:5',
    detail: 'Flexible',
  },
  'option:style:preserve-original': {
    field: 'style',
    label: 'Preserve Original',
    detail: "Keep the source image's style.",
  },
  'option:style:anime-manga': {
    field: 'style',
    label: 'Anime / Manga',
    detail: 'Classic Japanese animation style.',
  },
  'option:style:90s-anime-cel-shaded': {
    field: 'style',
    label: '90s Anime (Cel-shaded)',
    detail: 'Hand-drawn look, hard shadows.',
  },
  'option:style:modern-anime-digital': {
    field: 'style',
    label: 'Modern Anime (Digital)',
    detail: 'Sharp, clean, complex lighting.',
  },
  'option:style:studio-ghibli-inspired': {
    field: 'style',
    label: 'Studio Ghibli Inspired',
    detail: 'Whimsical, soft, painterly.',
  },
  'option:style:horror-manga-junji-ito': {
    field: 'style',
    label: 'Horror Manga (Junji Ito)',
    detail: 'High-contrast, detailed, unsettling.',
  },
  'option:style:action-manga-akira-toriyama': {
    field: 'style',
    label: 'Action Manga (Akira Toriyama)',
    detail: 'Blocky, dynamic figures, action.',
  },
  'option:style:seinen-manga-takehiko-inoue': {
    field: 'style',
    label: 'Seinen Manga (Takehiko Inoue)',
    detail: 'Realistic anatomy, expressive ink.',
  },
  'option:style:70s-retro-mecha-action-anime': {
    field: 'style',
    label: '70s Retro Mecha/Action Anime',
    detail: 'Vintage, bold designs, film grain.',
  },
  'option:style:cartoon-toon': {
    field: 'style',
    label: 'Cartoon / Toon',
    detail: 'Simplified shapes, bold outlines.',
  },
  'option:style:american-comic-book': {
    field: 'style',
    label: 'American Comic Book',
    detail: 'Dynamic poses, strong inks.',
  },
  'option:style:vintage-comic-1960s': {
    field: 'style',
    label: 'Vintage Comic (1960s)',
    detail: 'Ben-Day dots, limited colors.',
  },
  'option:style:graphic-novel-noir': {
    field: 'style',
    label: 'Graphic Novel / Noir',
    detail: 'High-contrast, gritty, cinematic.',
  },
  'option:style:chibi': {
    field: 'style',
    label: 'Chibi',
    detail: 'Cute, oversized heads, simplified bodies.',
  },
  'option:style:vector-art': {
    field: 'style',
    label: 'Vector Art',
    detail: 'Clean lines, flat colors, geometric.',
  },
  'option:style:flat-design': {
    field: 'style',
    label: 'Flat Design',
    detail: 'Minimalist, clean, simple shapes.',
  },
  'option:style:psychedelic-art': {
    field: 'style',
    label: 'Psychedelic Art',
    detail: 'Distorted visuals, vibrant colors, surreal.',
  },
  'option:style:pixel-art-16-bit': {
    field: 'style',
    label: 'Pixel Art (16-bit)',
    detail: 'Retro console style, limited palette.',
  },
  'option:style:pixel-art-32-bit': {
    field: 'style',
    label: 'Pixel Art (32-bit)',
    detail: 'Detailed pixel work, richer palette.',
  },
  'option:style:voxel-art': {
    field: 'style',
    label: 'Voxel Art',
    detail: '3D pixel art, blocky look.',
  },
  'option:style:glitch-art': {
    field: 'style',
    label: 'Glitch Art',
    detail: 'Digital distortion, corrupted feel.',
  },
  'option:style:synthwave-retrowave': {
    field: 'style',
    label: 'Synthwave / Retrowave',
    detail: 'Neon grids, 80s futuristic vibe.',
  },
  'option:style:retro-2d-rpg-snes': {
    field: 'style',
    label: 'Retro 2D RPG (SNES)',
    detail: '16-bit fantasy sprites.',
  },
  'option:style:ps1-n64-era-3d': {
    field: 'style',
    label: 'PS1 / N64 Era 3D',
    detail: 'Low-poly models, warped textures.',
  },
  'option:style:ps2-era-3d': {
    field: 'style',
    label: 'PS2 Era 3D',
    detail: 'More complex retro 3D models.',
  },
  'option:style:cel-shaded-3d-wind-waker': {
    field: 'style',
    label: 'Cel-shaded 3D (Wind Waker)',
    detail: 'Cartoonish hand-drawn 3D.',
  },
  'option:style:souls-like-dark-fantasy': {
    field: 'style',
    label: 'Souls-like (Dark Fantasy)',
    detail: 'Gritty, atmospheric, realistic.',
  },
  'option:style:modern-aaa-realism': {
    field: 'style',
    label: 'Modern AAA Realism',
    detail: 'Photorealistic, complex models.',
  },
  'option:style:fighting-game-style': {
    field: 'style',
    label: 'Fighting Game Style',
    detail: 'Stylized, muscular characters.',
  },
  'option:style:mobile-game-style': {
    field: 'style',
    label: 'Mobile Game Style',
    detail: 'Bright, simple, and clean.',
  },
  'option:style:visual-novel-style': {
    field: 'style',
    label: 'Visual Novel Style',
    detail: 'High-quality 2D character art.',
  },
  'option:style:3d-render-modern': {
    field: 'style',
    label: '3D Render (Modern)',
    detail: 'Clean, high-fidelity 3D models.',
  },
  'option:style:3d-render-retro-ps1': {
    field: 'style',
    label: '3D Render (Retro PS1)',
    detail: 'Low-poly models, no smoothing.',
  },
  'option:style:low-poly-3d': {
    field: 'style',
    label: 'Low Poly 3D',
    detail: 'Stylized, minimal polygons.',
  },
  'option:style:claymation-style': {
    field: 'style',
    label: 'Claymation Style',
    detail: 'Handcrafted clay look.',
  },
  'option:style:concept-art-sketch': {
    field: 'style',
    label: 'Concept Art (Sketch)',
    detail: 'Rough, energetic lines.',
  },
  'option:style:concept-art-polished': {
    field: 'style',
    label: 'Concept Art (Polished)',
    detail: 'Clean, detailed, production-ready.',
  },
  'option:style:matte-painting': {
    field: 'style',
    label: 'Matte Painting',
    detail: 'Photorealistic, epic landscapes.',
  },
  'option:style:watercolor-painting': {
    field: 'style',
    label: 'Watercolor Painting',
    detail: 'Soft, transparent colors.',
  },
  'option:style:oil-painting': {
    field: 'style',
    label: 'Oil Painting',
    detail: 'Rich, opaque, thick brushwork.',
  },
  'option:style:charcoal-sketch': {
    field: 'style',
    label: 'Charcoal Sketch',
    detail: 'B&W, smudged, focus on light/shadow.',
  },
  'option:style:ukiyo-e-woodblock': {
    field: 'style',
    label: 'Ukiyo-e Woodblock',
    detail: 'Japanese print, bold outlines.',
  },
  'option:style:stained-glass': {
    field: 'style',
    label: 'Stained Glass',
    detail: 'Bold black lines, vibrant colors.',
  },
  'option:style:art-nouveau': {
    field: 'style',
    label: 'Art Nouveau',
    detail: 'Elegant, flowing lines, decorative.',
  },
  'option:style:art-deco': {
    field: 'style',
    label: 'Art Deco',
    detail: 'Geometric shapes, strong lines, opulent.',
  },
  'option:style:surrealism-dali-esque': {
    field: 'style',
    label: 'Surrealism (Dali-esque)',
    detail: 'Dreamlike, bizarre, illogical scenes.',
  },
  'option:style:technical-drawing-blueprint': {
    field: 'style',
    label: 'Technical Drawing / Blueprint',
    detail: 'Precise lines, schematic look.',
  },
  'option:clothing:preserve-original': {
    field: 'clothing',
    label: 'Preserve Original',
    detail: '',
  },
  'option:clothing:fantasy-knight-armor': {
    field: 'clothing',
    label: 'Fantasy Knight Armor',
    detail: '',
  },
  'option:clothing:wizard-robes': {
    field: 'clothing',
    label: 'Wizard Robes',
    detail: '',
  },
  'option:clothing:rogue-s-leather-tunic': {
    field: 'clothing',
    label: "Rogue's Leather Tunic",
    detail: '',
  },
  'option:clothing:elven-silks': {
    field: 'clothing',
    label: 'Elven Silks',
    detail: '',
  },
  'option:clothing:barbarian-furs': {
    field: 'clothing',
    label: 'Barbarian Furs',
    detail: '',
  },
  'option:clothing:druid-s-ceremonial-robes': {
    field: 'clothing',
    label: "Druid's Ceremonial Robes",
    detail: '',
  },
  'option:clothing:bard-s-colorful-attire': {
    field: 'clothing',
    label: "Bard's Colorful Attire",
    detail: '',
  },
  'option:clothing:necromancer-s-dark-cloak': {
    field: 'clothing',
    label: "Necromancer's Dark Cloak",
    detail: '',
  },
  'option:clothing:dwarven-smithing-apron': {
    field: 'clothing',
    label: 'Dwarven Smithing Apron',
    detail: '',
  },
  'option:clothing:warlock-s-shadow-weave-robes': {
    field: 'clothing',
    label: "Warlock's Shadow Weave Robes",
    detail: '',
  },
  'option:clothing:paladin-s-holy-plate-armor': {
    field: 'clothing',
    label: "Paladin's Holy Plate Armor",
    detail: '',
  },
  'option:clothing:vampire-noble-attire': {
    field: 'clothing',
    label: 'Vampire Noble Attire',
    detail: '',
  },
  'option:clothing:nomad-desert-wraps': {
    field: 'clothing',
    label: 'Nomad Desert Wraps',
    detail: '',
  },
  'option:clothing:plague-doctor-outfit': {
    field: 'clothing',
    label: 'Plague Doctor Outfit',
    detail: '',
  },
  'option:clothing:king-s-royal-garb': {
    field: 'clothing',
    label: "King's Royal Garb",
    detail: '',
  },
  'option:clothing:jester-s-motley': {
    field: 'clothing',
    label: "Jester's Motley",
    detail: '',
  },
  'option:clothing:celestial-sage-robes': {
    field: 'clothing',
    label: 'Celestial Sage Robes',
    detail: '',
  },
  'option:clothing:fae-touched-silken-garb': {
    field: 'clothing',
    label: 'Fae-touched Silken Garb',
    detail: '',
  },
  'option:clothing:orcish-warchief-plate': {
    field: 'clothing',
    label: 'Orcish Warchief Plate',
    detail: '',
  },
  'option:clothing:sci-fi-power-armor': {
    field: 'clothing',
    label: 'Sci-Fi Power Armor',
    detail: '',
  },
  'option:clothing:galactic-explorer-jumpsuit': {
    field: 'clothing',
    label: 'Galactic Explorer Jumpsuit',
    detail: '',
  },
  'option:clothing:cyberpunk-gear': {
    field: 'clothing',
    label: 'Cyberpunk Gear',
    detail: '',
  },
  'option:clothing:steampunk-attire': {
    field: 'clothing',
    label: 'Steampunk Attire',
    detail: '',
  },
  'option:clothing:cyberpunk-netrunner-suit': {
    field: 'clothing',
    label: 'Cyberpunk Netrunner Suit',
    detail: '',
  },
  'option:clothing:post-apocalyptic-heavy-armor': {
    field: 'clothing',
    label: 'Post-Apocalyptic Heavy Armor',
    detail: '',
  },
  'option:clothing:space-pirate-gear': {
    field: 'clothing',
    label: 'Space Pirate Gear',
    detail: '',
  },
  'option:clothing:starship-captain-uniform': {
    field: 'clothing',
    label: 'Starship Captain Uniform',
    detail: '',
  },
  'option:clothing:android-shell-exposed-circuits': {
    field: 'clothing',
    label: 'Android Shell (Exposed circuits)',
    detail: '',
  },
  'option:clothing:void-walker-s-suit': {
    field: 'clothing',
    label: "Void-walker's Suit",
    detail: '',
  },
  'option:clothing:biomechanical-suit': {
    field: 'clothing',
    label: 'Biomechanical Suit',
    detail: '',
  },
  'option:clothing:solar-punk-artisan-wear': {
    field: 'clothing',
    label: 'Solar-punk Artisan Wear',
    detail: '',
  },
  'option:clothing:retro-futuristic-spaceman-suit': {
    field: 'clothing',
    label: 'Retro-futuristic Spaceman Suit',
    detail: '',
  },
  'option:clothing:samurai-armor': {
    field: 'clothing',
    label: 'Samurai Armor',
    detail: '',
  },
  'option:clothing:kimono': {
    field: 'clothing',
    label: 'Kimono',
    detail: '',
  },
  'option:clothing:victorian-era-ball-gown': {
    field: 'clothing',
    label: 'Victorian Era Ball Gown',
    detail: '',
  },
  'option:clothing:viking-raider-leathers': {
    field: 'clothing',
    label: 'Viking Raider Leathers',
    detail: '',
  },
  'option:clothing:egyptian-pharaoh-regalia': {
    field: 'clothing',
    label: 'Egyptian Pharaoh Regalia',
    detail: '',
  },
  'option:clothing:roaring-20s-flapper-dress': {
    field: 'clothing',
    label: 'Roaring 20s Flapper Dress',
    detail: '',
  },
  'option:clothing:1950s-greaser-leather-jacket-jeans': {
    field: 'clothing',
    label: '1950s Greaser (Leather jacket, jeans)',
    detail: '',
  },
  'option:clothing:1980s-new-wave-fashion': {
    field: 'clothing',
    label: '1980s New Wave Fashion',
    detail: '',
  },
  'option:clothing:modern-casual-wear': {
    field: 'clothing',
    label: 'Modern Casual Wear',
    detail: '',
  },
  'option:clothing:streetwear-oversized-hoodie-cargo-pants-chunky-sneakers': {
    field: 'clothing',
    label: 'Streetwear (Oversized hoodie, cargo pants, chunky sneakers)',
    detail: '',
  },
  'option:clothing:skater-punk-outfit': {
    field: 'clothing',
    label: 'Skater Punk Outfit',
    detail: '',
  },
  'option:clothing:techwear-functional-futuristic': {
    field: 'clothing',
    label: 'Techwear (Functional, futuristic)',
    detail: '',
  },
  'option:clothing:hypebeast-outfit-designer-brands-rare-sneakers': {
    field: 'clothing',
    label: 'Hypebeast Outfit (Designer brands, rare sneakers)',
    detail: '',
  },
  'option:clothing:graffiti-artist-wear-paint-splattered-clothes-beanie': {
    field: 'clothing',
    label: 'Graffiti Artist Wear (Paint-splattered clothes, beanie)',
    detail: '',
  },
  'option:clothing:drill-rapper-tracksuit-balaclava-designer-bag': {
    field: 'clothing',
    label: 'Drill Rapper (Tracksuit, balaclava, designer bag)',
    detail: '',
  },
  'option:clothing:lo-fi-beats-listener-oversized-sweater-beanie-round-glasses': {
    field: 'clothing',
    label: 'Lo-Fi Beats Listener (Oversized sweater, beanie, round glasses)',
    detail: '',
  },
  'option:clothing:dark-academia-tweed-blazer-turtleneck-trousers': {
    field: 'clothing',
    label: 'Dark Academia (Tweed blazer, turtleneck, trousers)',
    detail: '',
  },
  'option:clothing:light-academia-linen-shirt-light-colored-sweater-chinos': {
    field: 'clothing',
    label: 'Light Academia (Linen shirt, light-colored sweater, chinos)',
    detail: '',
  },
  'option:clothing:preppy-ivy-league-style-polo-shirt-khaki-shorts-boat-shoes': {
    field: 'clothing',
    label: 'Preppy Ivy League Style (Polo shirt, khaki shorts, boat shoes)',
    detail: '',
  },
  'option:clothing:librarian-chic-cardigan-button-up-shirt-glasses': {
    field: 'clothing',
    label: 'Librarian Chic (Cardigan, button-up shirt, glasses)',
    detail: '',
  },
  'option:clothing:art-student-paint-splattered-overalls-quirky-earrings-tote-bag': {
    field: 'clothing',
    label: 'Art Student (Paint-splattered overalls, quirky earrings, tote bag)',
    detail: '',
  },
  'option:clothing:chaotic-academia-mismatched-patterns-worn-out-sweaters-disheveled-look': {
    field: 'clothing',
    label: 'Chaotic Academia (Mismatched patterns, worn-out sweaters, disheveled look)',
    detail: '',
  },
  'option:clothing:goth-black-clothing-leather-silver-jewelry': {
    field: 'clothing',
    label: 'Goth (Black clothing, leather, silver jewelry)',
    detail: '',
  },
  'option:clothing:pastel-goth-pastel-colors-with-goth-elements': {
    field: 'clothing',
    label: 'Pastel Goth (Pastel colors with goth elements)',
    detail: '',
  },
  'option:clothing:punk-rocker-ripped-jeans-band-t-shirt-studded-jacket': {
    field: 'clothing',
    label: 'Punk Rocker (Ripped jeans, band t-shirt, studded jacket)',
    detail: '',
  },
  'option:clothing:metalhead-black-band-shirt-denim-vest-leather-pants': {
    field: 'clothing',
    label: 'Metalhead (Black band shirt, denim vest, leather pants)',
    detail: '',
  },
  'option:clothing:e-girl-e-boy-outfit-striped-shirt-chains-beanie': {
    field: 'clothing',
    label: 'E-girl / E-boy Outfit (Striped shirt, chains, beanie)',
    detail: '',
  },
  'option:clothing:hipster-attire-beanie-flannel': {
    field: 'clothing',
    label: 'Hipster Attire (Beanie, flannel)',
    detail: '',
  },
  'option:clothing:scene-kid-2000s-revival-coontails-bright-colors-skinny-jeans': {
    field: 'clothing',
    label: 'Scene Kid (2000s revival',
    detail: 'Coontails, bright colors, skinny jeans)',
  },
  'option:clothing:health-goth-monochromatic-athletic-wear-futuristic-look': {
    field: 'clothing',
    label: 'Health Goth (Monochromatic athletic wear, futuristic look)',
    detail: '',
  },
  'option:clothing:witchcore-long-black-dress-occult-symbols-layered-shawls': {
    field: 'clothing',
    label: 'Witchcore (Long black dress, occult symbols, layered shawls)',
    detail: '',
  },
  'option:clothing:cottagecore-outfit-flowy-dress-knitted-cardigan-rustic': {
    field: 'clothing',
    label: 'Cottagecore Outfit (Flowy dress, knitted cardigan, rustic)',
    detail: '',
  },
  'option:clothing:minimalist-chic-neutral-colors-clean-lines-simple-silhouette': {
    field: 'clothing',
    label: 'Minimalist Chic (Neutral colors, clean lines, simple silhouette)',
    detail: '',
  },
  'option:clothing:y2k-revival-fashion-low-rise-jeans-crop-top-colorful-accessories': {
    field: 'clothing',
    label: 'Y2K Revival Fashion (Low-rise jeans, crop top, colorful accessories)',
    detail: '',
  },
  'option:clothing:bohemian-boho-chic-flowing-fabrics-earthy-tones-fringe': {
    field: 'clothing',
    label: 'Bohemian / Boho-Chic (Flowing fabrics, earthy tones, fringe)',
    detail: '',
  },
  'option:clothing:gamer-streamer-casual-comfortable-hoodie-headphones-merch': {
    field: 'clothing',
    label: 'Gamer / Streamer Casual (Comfortable hoodie, headphones, merch)',
    detail: '',
  },
  'option:clothing:tech-bro-uniform-branded-fleece-vest-button-down-sneakers': {
    field: 'clothing',
    label: 'Tech Bro Uniform (Branded fleece vest, button-down, sneakers)',
    detail: '',
  },
  'option:clothing:vsco-girl-oversized-t-shirt-shell-necklace-scrunchies': {
    field: 'clothing',
    label: 'VSCO Girl (Oversized t-shirt, shell necklace, scrunchies)',
    detail: '',
  },
  'option:clothing:normcore-unbranded-basics-simple-jeans-plain-sneakers': {
    field: 'clothing',
    label: 'Normcore (Unbranded basics, simple jeans, plain sneakers)',
    detail: '',
  },
  'option:clothing:baddie-aesthetic-bodycon-dress-perfect-makeup-high-heels': {
    field: 'clothing',
    label: 'Baddie Aesthetic (Bodycon dress, perfect makeup, high heels)',
    detail: '',
  },
  'option:clothing:plant-mom-dad-linen-shirt-practical-pants-surrounded-by-plants': {
    field: 'clothing',
    label: 'Plant Mom/Dad (Linen shirt, practical pants, surrounded by plants)',
    detail: '',
  },
  'option:clothing:dark-cottagecore-goblincore-earthy-tones-mushroom-motifs-slightly-worn-l': {
    field: 'clothing',
    label: 'Dark Cottagecore / Goblincore (Earthy tones, mushroom motifs, slightly worn look)',
    detail: '',
  },
  'option:clothing:clowncore-rainbow-patterns-oversized-collars-playful-accessories': {
    field: 'clothing',
    label: 'Clowncore (Rainbow patterns, oversized collars, playful accessories)',
    detail: '',
  },
  'option:clothing:fairycore-faecore-ethereal-dresses-flower-crowns-delicate-wings': {
    field: 'clothing',
    label: 'Fairycore / Faecore (Ethereal dresses, flower crowns, delicate wings)',
    detail: '',
  },
  'option:clothing:athleisure-wear': {
    field: 'clothing',
    label: 'Athleisure Wear',
    detail: '',
  },
  'option:clothing:gorpcore-hiker-chic-technical-jacket-cargo-shorts-hiking-boots': {
    field: 'clothing',
    label: 'Gorpcore / Hiker-chic (Technical jacket, cargo shorts, hiking boots)',
    detail: '',
  },
  'option:clothing:surfer-style-board-shorts-tank-top-flip-flops': {
    field: 'clothing',
    label: 'Surfer Style (Board shorts, tank top, flip-flops)',
    detail: '',
  },
  'option:clothing:yoga-instructor-yoga-pants-sports-bra-serene-expression': {
    field: 'clothing',
    label: 'Yoga Instructor (Yoga pants, sports bra, serene expression)',
    detail: '',
  },
  'option:clothing:cyclist-gear-lycra-shorts-cycling-jersey-helmet': {
    field: 'clothing',
    label: 'Cyclist Gear (Lycra shorts, cycling jersey, helmet)',
    detail: '',
  },
  'option:clothing:business-casual-attire': {
    field: 'clothing',
    label: 'Business Casual Attire',
    detail: '',
  },
  'option:clothing:formal-suit-tuxedo': {
    field: 'clothing',
    label: 'Formal Suit / Tuxedo',
    detail: '',
  },
  'option:clothing:modern-business-suit-slim-fit-no-tie': {
    field: 'clothing',
    label: 'Modern Business Suit (Slim fit, no tie)',
    detail: '',
  },
  'option:clothing:creative-professional-stylish-blazer-dark-jeans-designer-sneakers': {
    field: 'clothing',
    label: 'Creative Professional (Stylish blazer, dark jeans, designer sneakers)',
    detail: '',
  },
  'option:clothing:startup-founder-branded-hoodie-expensive-sneakers-confident-stance': {
    field: 'clothing',
    label: 'Startup Founder (Branded hoodie, expensive sneakers, confident stance)',
    detail: '',
  },
  'option:clothing:barista-uniform-apron-t-shirt-comfortable-shoes': {
    field: 'clothing',
    label: 'Barista Uniform (Apron, t-shirt, comfortable shoes)',
    detail: '',
  },
  'option:clothing:summer-beachwear': {
    field: 'clothing',
    label: 'Summer Beachwear',
    detail: '',
  },
  'option:clothing:winter-wear-puffer-jacket': {
    field: 'clothing',
    label: 'Winter Wear (Puffer jacket)',
    detail: '',
  },
  'option:clothing:vintage-aviator-jacket': {
    field: 'clothing',
    label: 'Vintage Aviator Jacket',
    detail: '',
  },
  'option:clothing:festival-goer-fringe-face-glitter-denim-shorts': {
    field: 'clothing',
    label: 'Festival Goer (Fringe, face glitter, denim shorts)',
    detail: '',
  },
  'option:clothing:tourist-outfit-hawaiian-shirt-shorts-camera-around-neck': {
    field: 'clothing',
    label: 'Tourist Outfit (Hawaiian shirt, shorts, camera around neck)',
    detail: '',
  },
  'option:clothing:pajamas-loungewear-cozy-sweatpants-and-a-soft-shirt': {
    field: 'clothing',
    label: 'Pajamas / Loungewear (Cozy sweatpants and a soft shirt)',
    detail: '',
  },
  'option:clothing:noir-detective-trenchcoat': {
    field: 'clothing',
    label: 'Noir Detective Trenchcoat',
    detail: '',
  },
  'option:clothing:superhero-spandex-suit': {
    field: 'clothing',
    label: 'Superhero Spandex Suit',
    detail: '',
  },
  'option:clothing:royal-gown': {
    field: 'clothing',
    label: 'Royal Gown',
    detail: '',
  },
  'option:clothing:gothic-victorian-attire': {
    field: 'clothing',
    label: 'Gothic Victorian Attire',
    detail: '',
  },
  'option:clothing:gothic-lolita-dress': {
    field: 'clothing',
    label: 'Gothic Lolita Dress',
    detail: '',
  },
  'option:clothing:post-apocalyptic-scavenger': {
    field: 'clothing',
    label: 'Post-Apocalyptic Scavenger',
    detail: '',
  },
  'option:clothing:wasteland-raider-leathers': {
    field: 'clothing',
    label: 'Wasteland Raider Leathers',
    detail: '',
  },
  'option:clothing:tribal-hunter-garb': {
    field: 'clothing',
    label: 'Tribal Hunter Garb',
    detail: '',
  },
  'option:clothing:circus-ringleader-costume': {
    field: 'clothing',
    label: 'Circus Ringleader Costume',
    detail: '',
  },
  'option:clothing:mad-scientist-lab-coat': {
    field: 'clothing',
    label: 'Mad Scientist Lab Coat',
    detail: '',
  },
  'option:body-type:preserve-original': {
    field: 'body-type',
    label: 'Preserve Original',
    detail: '',
  },
  'option:body-type:thinner': {
    field: 'body-type',
    label: 'Thinner',
    detail: '',
  },
  'option:body-type:very-thin': {
    field: 'body-type',
    label: 'Very Thin',
    detail: '',
  },
  'option:body-type:skeletal-emaciated': {
    field: 'body-type',
    label: 'Skeletal / Emaciated',
    detail: '',
  },
  'option:body-type:heavier': {
    field: 'body-type',
    label: 'Heavier',
    detail: '',
  },
  'option:body-type:obese': {
    field: 'body-type',
    label: 'Obese',
    detail: '',
  },
  'option:body-type:morbidly-obese': {
    field: 'body-type',
    label: 'Morbidly Obese',
    detail: '',
  },
  'option:body-type:athletically-fit': {
    field: 'body-type',
    label: 'Athletically Fit',
    detail: '',
  },
  'option:body-type:lean-muscle': {
    field: 'body-type',
    label: 'Lean Muscle',
    detail: '',
  },
  'option:body-type:stocky-burly': {
    field: 'body-type',
    label: 'Stocky / Burly',
    detail: '',
  },
  'option:body-type:exaggerated-muscles': {
    field: 'body-type',
    label: 'Exaggerated Muscles',
    detail: '',
  },
  'option:body-type:hyper-muscular': {
    field: 'body-type',
    label: 'Hyper-Muscular',
    detail: '',
  },
} as const;
