// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP23-053',
    name: 'Opaque Plane and Raster Accents',
    category: '12. Hybrid Visual Studies',
    negativePrompt:
      'unrequested symbols, luminous effects or added content, all-over pixelation, raster noise or color shifts, unrequested lettering or added graphic elements',
    style: {
      aesthetic:
        'Combine broad opaque color planes and confident ink contours with small, controlled raster accents. Keep the main forms broad and quiet while clusters clarify selected existing details.',
      subject_treatment:
        'Preserve the requested subject, identity, function, count, pose, action and proportions. Use raster accents only to distinguish details that already exist; add no content or symbols.',
      color_and_tone:
        'Retain the requested palette and color relationships. Reuse existing colors in compact accents without forcing neon, glow or additional hues.',
      lighting_and_shadow:
        'Follow the requested light and shadow pattern. Keep accents subordinate to existing value groups and avoid adding luminous effects or new light sources.',
      texture_and_material:
        'Keep broad areas opaque and matte with clean contours. Restrict raster clusters to selected details rather than pixelating the full image or replacing depicted materials.',
      camera_and_composition:
        'Preserve the requested viewpoint, crop, scale and spatial relationships. This rendering method does not alter the requested composition or add graphic elements.',
      atmosphere_and_mood:
        'Preserve the requested setting and mood. Ink, opaque planes and small raster accents change the rendering only, not the scene or narrative.',
      rendering_and_quality:
        'Establish broad planes and legible contours first. Add only a few aligned raster clusters where they improve separation; avoid noise, all-over pixelation and competing styles.',
    },
    ui: {
      kind: 'full_style',
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP23-054',
    name: 'Directional Hatch Raster',
    category: '12. Hybrid Visual Studies',
    negativePrompt:
      'undirected raster noise or random dithering, unrequested print aging, coarse resolution or palette restriction, unrequested lettering or added graphic elements',
    style: {
      aesthetic:
        'Model volume with directional hatching, then quantize each stroke into a consistent raster rhythm. Preserve clean open areas and keep the direction of every cluster tied to form.',
      subject_treatment:
        'Preserve requested identity, function, count, pose, action and proportions. Let hatch direction follow existing forms without reshaping them or adding detail.',
      color_and_tone:
        'Retain the requested palette and value relationships. Keep light areas clear and use existing colors or values for rasterized strokes without imposing a monochrome palette.',
      lighting_and_shadow:
        'Follow the requested lighting. Vary hatch direction and density to describe existing volume and shadows without creating a new light source or contrast pattern.',
      texture_and_material:
        'Keep raster edges coherent while preserving the material distinctions already shown. Avoid artificial print wear, coarse resolution or undirected pixel noise.',
      camera_and_composition:
        'Preserve the requested viewpoint, crop, scale and spatial relationships. Rasterizing strokes does not change perspective or the requested arrangement.',
      atmosphere_and_mood:
        'Preserve the requested setting and mood. Directional hatching and quantization affect mark-making only; they do not add a period or narrative.',
      rendering_and_quality:
        'Keep stroke direction visible at the final viewing size, with clean gaps and deliberate clusters. Avoid random dithering, uniform hatch bands and detail loss from coarse pixels.',
    },
    ui: {
      kind: 'full_style',
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP23-055',
    name: 'Directional Raster Interlock',
    category: '12. Hybrid Visual Studies',
    negativePrompt:
      'unrequested patterns or changes to depicted material, random dithering, noisy clusters or chaotic overlap, unrequested lettering or added graphic elements',
    style: {
      aesthetic:
        'Arrange directional mark groups that follow existing form, then use compact raster clusters to define selected edges and color changes. Keep the image integrated, not fragmented.',
      subject_treatment:
        'Preserve requested identity, count, pose, action, proportions and scene. Mark direction follows existing shapes without introducing patterns or changing the represented material.',
      color_and_tone:
        'Retain the requested palette and tonal relationships. Use raster clusters to clarify transitions between existing colors without forcing a woven palette or adding hues.',
      lighting_and_shadow:
        'Follow the requested lighting. Let directional marks support the existing value structure and avoid replacing it with an arbitrary repeated pattern.',
      texture_and_material:
        'Keep marks directional and restrained; preserve the materials already depicted. Do not turn the full image into a textile surface or apply uniform grain.',
      camera_and_composition:
        'Preserve the requested viewpoint, crop and arrangement. Quantized edges follow existing forms without adding elements or changing the requested composition.',
      atmosphere_and_mood:
        'Preserve the requested mood and setting. The combination of directional marks and raster clusters changes the rendering only, not the subject or story.',
      rendering_and_quality:
        'Keep the primary mark direction clear and raster groupings consistent. Avoid noisy dithering, chaotic overlaps or pattern density that competes with form.',
    },
    ui: {
      kind: 'full_style',
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP23-056',
    name: 'Selective Pigment Surface Modifier',
    category: '12. Hybrid Visual Studies',
    negativePrompt:
      'surface texture outside the explicitly authorized material target, changes to the base silhouette, linework, palette or shadow structure, unrequested wear, damage or graphic content',
    style: {
      aesthetic:
        'Optional fine pigment opacity and subtle porosity on one explicitly authorized existing surface target. This modifier affects surface treatment only.',
      subject_treatment:
        'Preserve the base image silhouette, identity, count, proportions, pose, action and linework. Do not reshape or redraw content to make room for surface texture.',
      color_and_tone:
        'Preserve the base image palette and value relationships. Change no color unless separately authorized for the selected target.',
      lighting_and_shadow:
        'Preserve the base image lighting and shadow shapes. Surface porosity must not introduce a light, shadow or contrast change.',
      texture_and_material:
        'Apply fine opaque-grain cues only to the explicitly authorized existing material target. Keep contours clear and do not add damage, wear or texture beyond that target.',
      camera_and_composition:
        'Preserve the base image viewpoint, crop, scale and placement exactly. This modifier does not alter composition or add elements.',
      atmosphere_and_mood:
        'Preserve the base image setting and mood. Surface treatment adds no period, narrative or scene.',
      rendering_and_quality:
        'Keep any added grain fine and subordinate. Leave the underlying silhouette, line and shadow structure unchanged so the modifier can be removed without altering the image geometry.',
    },
    ui: {
      kind: 'modifier',
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP23-057',
    name: 'Faceted Opaque Color Planes',
    category: '12. Hybrid Visual Studies',
    negativePrompt:
      'unrequested geometry or material changes, uniform metallic edging, excess facets or forced hues, unrequested ornament, lettering or added graphic elements',
    style: {
      aesthetic:
        'Describe existing forms with simple faceted color planes, opaque fills and selective narrow edge accents. Keep facets aligned to the original geometry rather than reshaping the subject.',
      subject_treatment:
        'Preserve the requested identity, function, count, pose, action, proportions and geometry. Use plane boundaries to clarify form without adding ornaments or changing what it is made of.',
      color_and_tone:
        'Retain the requested palette and color relationships. Organize existing colors into opaque fields and use restrained edge accents drawn from that palette.',
      lighting_and_shadow:
        'Follow the requested light direction and contrast. Faceted values should support existing form and shadows without adding metallic shine or a new light source.',
      texture_and_material:
        'Preserve represented materials. Use clean color fields and selective edge accents as drawing choices, not as a demand to convert surfaces into a different physical material.',
      camera_and_composition:
        'Preserve the requested viewpoint, crop, scale and spatial relationships. Faceting follows current perspective and does not create new geometry or graphic elements.',
      atmosphere_and_mood:
        'Preserve the requested setting and mood. Faceted color treatment changes visual construction, not the scene, period or narrative.',
      rendering_and_quality:
        'Keep plane scale and edge accents consistent across the image. Avoid uniform metallic outlines, excessive facets or changes to the original silhouette.',
    },
    ui: {
      kind: 'full_style',
      visualEvaluation: 'pending',
    },
  },
  {
    id: 'SP23-058',
    name: 'Shallow Relief and Fine Marks',
    category: '12. Hybrid Visual Studies',
    negativePrompt:
      'unrequested changes to geometry or depicted material, excessive relief, noisy pigment or mark-like lettering, unrequested symbols or lettering that create new content',
    style: {
      aesthetic:
        'Suggest shallow modeled depth with restrained highlights and shadows, then add fine drawing marks and dry-pigment accents to existing forms. Keep the relief cue subtle and integrated.',
      subject_treatment:
        'Preserve the requested identity, function, count, pose, action, proportions and geometry. Relief shading follows existing forms; drawn accents add no writing, symbols or new content.',
      color_and_tone:
        'Retain the requested palette and color relationships. Use restrained opaque accents within those colors without imposing a fixed pigment or material color.',
      lighting_and_shadow:
        'Follow the requested light direction. Use shallow value changes to clarify existing form without inventing relief, new shadows or a new light source.',
      texture_and_material:
        'Preserve the materials already depicted. Keep dry-pigment marks fine and local to existing surfaces rather than turning the full image into a new material.',
      camera_and_composition:
        'Preserve the requested viewpoint, crop, scale and spatial relationships. Relief cues only affect rendering; they do not add elements or alter the requested arrangement.',
      atmosphere_and_mood:
        'Preserve the requested scene and mood. Low-relief modeling and fine marks change image treatment only; they do not add a setting, period or narrative.',
      rendering_and_quality:
        'Keep the relief restrained, drawing marks legible and pigment accents selective. Avoid raised edges that distort the silhouette or marks that resemble lettering.',
    },
    ui: {
      kind: 'full_style',
      visualEvaluation: 'pending',
    },
  },
] as unknown as StyleRuntimePreset[];
