// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP06-101',
    name: 'JRPG Pixel Diorama Grammar',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, flat 2D tile map, motion blur, inconsistent proportions, changing costume, background scene, literal town requirement, npc crowd requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Pixel diorama: flat pixel-art sprites and pixel textures placed inside a real 3D miniature set, lit with modern bloom and tilt-shift depth of field.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a high tilted camera over a miniature 3D diorama in which characters stay flat pixel sprites, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Warm storybook palette with saturated pixel textures, glowing warm point lights and cool ambient shadows.',
      lighting_and_shadow:
        'Real-time point lights, soft bloom around lamps and fires, sprites casting soft 3D shadows onto the set.',
      texture_and_material:
        'Chunky pixel textures on 3D blocks, flat billboarded character sprites, particle dust and water shimmer.',
      camera_and_composition:
        'High oblique camera over a floating chunk of the world, strong tilt-shift blur at the top and bottom of frame.',
      atmosphere_and_mood:
        'Nostalgic and wondrous, a remembered childhood game rebuilt as a toy set.',
      rendering_and_quality:
        'Crisp pixel sprites against depth-blurred 3D surroundings; no pixel scaling blur on the sprites.',
      key_features:
        'pixel sprites in 3D diorama; tilt-shift blur; bloom point lights; pixel textures on blocks; floating world chunk',
      creative_brief:
        "Pixel diorama: flat pixel-art sprites and pixel textures placed inside a real 3D miniature set, lit with modern bloom and tilt-shift depth of field. Carry it through pixel sprites in 3D diorama, tilt-shift blur, bloom point lights, pixel textures on blocks, floating world chunk. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-102',
    name: 'Roguelike Tile Glyph System',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, letters as creatures, perspective scene, soft shading, motion blur, inconsistent proportions, changing costume, background scene, literal dungeon requirement, monster requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Roguelike tile set: each subject reduced to one square pictographic tile with a stark silhouette in two or three colors on black.',
      subject_treatment:
        'Keep the prompt subject recognizable; present it as one tile or a sheet of matching tiles on a black grid, and build a dungeon map only when the prompt asks for one.',
      color_and_tone:
        'Black ground with two or three flat colors per tile; bone white, rust red, moss green or cold blue as tile accents.',
      lighting_and_shadow:
        'No modeled light; value comes from silhouette cutouts and one inner highlight shape.',
      texture_and_material:
        'Hard-edged 32 pixel tiles, one-pixel inner detail lines, no gradients, a faint grid between tiles.',
      camera_and_composition:
        'Orthographic tiles in an even grid with equal padding; each silhouette centered and readable at tiny size.',
      atmosphere_and_mood: 'Stark and tactical, danger read in a single glance.',
      rendering_and_quality:
        'Consistent tile size, line weight and palette across the whole set; no text glyphs.',
      key_features:
        'square pictograph tiles; black ground; two or three colors; even grid; stark silhouettes',
      creative_brief:
        "Roguelike tile set: each subject reduced to one square pictographic tile with a stark silhouette in two or three colors on black. Carry it through square pictograph tiles, black ground, two or three colors, even grid, stark silhouettes. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-103',
    name: 'Side-Scroll Parallax Gloom',
    displayName: 'Side-Scroll Parallax Gloom',
    styleAnchors: ['Side-Scroll Parallax Gloom', 'Metroidvania Parallax Gloom'],
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, perspective camera, flat single-layer backdrop, motion blur, inconsistent proportions, changing costume, literal cavern requirement, platform requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Side-scrolling exploration art: a dark near-black gameplay plane in front of four to six parallax layers that fade into colored fog.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a flat side-on view built from layered parallax planes, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Foreground near black, midground rich teal or violet, background washed into pale fog; one warm accent for the focal light.',
      lighting_and_shadow:
        'Backlit silhouettes with thin rim light, god-rays through gaps, glowing flora and embers as small light sources.',
      texture_and_material:
        'Painted or pixel textures that lose contrast with each layer, crisp foreground edges, drifting particles.',
      camera_and_composition:
        'Strict side view; the walkable silhouette runs across the lower third, depth stacked in horizontal bands.',
      atmosphere_and_mood: 'Lonely and curious, a vast place explored one room at a time.',
      rendering_and_quality:
        'Clear value separation between planes so the foreground path always reads.',
      key_features:
        'strict side view; stacked parallax layers; near-black foreground; fog-washed background; rim-lit silhouettes',
      creative_brief:
        "Side-scrolling exploration art: a dark near-black gameplay plane in front of four to six parallax layers that fade into colored fog. Carry it through strict side view, stacked parallax layers, near-black foreground, fog-washed background, rim-lit silhouettes. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-104',
    name: 'Cyberpunk Diegetic HUD Glow',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, readable interface copy, weapon requirement, generic cyborg woman face, watermark, text, literal city scene, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Diegetic sci-fi HUD: translucent holographic panels, brackets and arcs projected into the world around the subject, glowing cyan and magenta.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a layer of in-world holographic interface around and over the subject, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Dark scene grade with cyan primary and magenta or amber secondary glows; interface additive and luminous.',
      lighting_and_shadow:
        'Holograms cast soft colored light on nearby surfaces; the rest of the scene stays low-key.',
      texture_and_material:
        'Thin vector lines, segmented arcs, hexagon grids, faint scanlines and slight chromatic fringing on the projections.',
      camera_and_composition:
        'Keep the requested view; brackets frame the focal point, panels sit on an asymmetric grid with safe margins.',
      atmosphere_and_mood: 'Focused and tense, information wrapped around the moment.',
      rendering_and_quality:
        'Crisp luminous lines with no legible glyphs; interface never hides the subject.',
      key_features:
        'holographic brackets; segmented arcs; hexagon grid; scanlines; cyan and magenta glow',
      creative_brief:
        "Diegetic sci-fi HUD: translucent holographic panels, brackets and arcs projected into the world around the subject, glowing cyan and magenta. Carry it through holographic brackets, segmented arcs, hexagon grid, scanlines, cyan and magenta glow. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-105',
    name: 'Retro Fighting Game Select Screen',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, known fighting-game characters, readable character name, watermark, text, human-only portrait, arena requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        '90s arcade fighter select screen: a grid of bold hand-painted pixel portraits of original fighters with diagonal energy slashes and a versus split.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a fighter-select layout of portrait tiles, a highlighted selection and diagonal versus panels, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Saturated gradient backgrounds per fighter, hot red, electric blue, acid green, gold selection glow.',
      lighting_and_shadow:
        'Dramatic portrait light from below or the side with hard pixel highlights on muscles and armor.',
      texture_and_material:
        'Painterly pixel portraits with dense clusters, crisp tile borders, speed-line slashes and glow edges.',
      camera_and_composition:
        'Tiled grid of tight portraits or a diagonal split with two large figures facing off; strong symmetry.',
      atmosphere_and_mood: 'Competitive and loud, the charge before the first round.',
      rendering_and_quality:
        'Consistent portrait crop and pixel density; blank name plates, no numbers or timers.',
      key_features:
        'portrait tile grid; diagonal versus split; painterly pixel portraits; gradient backgrounds; selection glow',
      creative_brief:
        "90s arcade fighter select screen: a grid of bold hand-painted pixel portraits of original fighters with diagonal energy slashes and a versus split. Carry it through portrait tile grid, diagonal versus split, painterly pixel portraits, gradient backgrounds, selection glow. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-106',
    name: 'Isometric Strategy Tile Language',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, perspective camera, army requirement, full map scene, motion blur, inconsistent proportions, changing costume, background scene, literal terrain requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Isometric strategy tiles: each subject built on a 2:1 diamond tile with beveled edges, as a clean atlas-ready game asset.',
      subject_treatment:
        'Keep the prompt subject and its design; present it as a standalone game asset on a plain field, and build a gameplay scene or interface only when the prompt asks for one.',
      color_and_tone:
        'Clear readable greens, sand and slate with slightly saturated team-color accents; side faces one step darker.',
      lighting_and_shadow:
        'Fixed top-left sun on every tile; short consistent shadows falling inside the tile footprint.',
      texture_and_material:
        'Simple painted textures, beveled tile edges, a visible soil or rock cross-section on the tile sides.',
      camera_and_composition:
        'True 2:1 isometric projection, no vanishing point, tiles centered on a plain light background with equal spacing.',
      atmosphere_and_mood: 'Orderly and inviting, a board game ready to be played.',
      rendering_and_quality:
        'Crisp edges and consistent tile size and light across the set; no perspective drift.',
      key_features:
        '2:1 diamond tiles; beveled edges; cross-section tile sides; fixed top-left sun; plain background',
      creative_brief:
        "Isometric strategy tiles: each subject built on a 2:1 diamond tile with beveled edges, as a clean atlas-ready game asset. Carry it through 2:1 diamond tiles, beveled edges, cross-section tile sides, fixed top-left sun, plain background. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-107',
    name: 'MOBA Splash Rendering',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, known champion likeness, literal battle crowd, watermark, text, literal battle scene, weapon requirement, human champion requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Hero splash art: a painterly 3D-looking champion with exaggerated heroic proportions exploding out of a diagonal composition in ability-colored effects.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a diagonal heroic splash composition built around one champion-like focal figure, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Saturated complementary palette: warm hero lighting against cool environment, each ability given one signature glow color.',
      lighting_and_shadow:
        'Strong key from the ability effect, bright rim light, deep shaped shadows that sculpt big forms.',
      texture_and_material:
        'Soft painted gradients over sculpted forms, crisp hard-surface armor edges, swirling particle and energy trails.',
      camera_and_composition:
        'Low to mid heroic angle on a strong diagonal; big-medium-small shape hierarchy, background simplified into effects.',
      atmosphere_and_mood: 'Triumphant and kinetic, a hero at the peak of power.',
      rendering_and_quality:
        'Polished painterly finish with clean silhouette; effects never hide the face or pose.',
      key_features:
        'diagonal splash; exaggerated heroic proportions; ability-color rim light; particle trails; sculpted painted forms',
      creative_brief:
        "Hero splash art: a painterly 3D-looking champion with exaggerated heroic proportions exploding out of a diagonal composition in ability-colored effects. Carry it through diagonal splash, exaggerated heroic proportions, ability-color rim light, particle trails, sculpted painted forms. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-108',
    name: 'Visual Novel Neon Backdrop Wash',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, dialogue box, people in frame by default, readable signage, watermark, text, literal classroom requirement, student requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Visual-novel backdrop: a clean anime-painted location with no characters, graded in neon night color and staged for a character to stand in later.',
      subject_treatment:
        'Keep the prompt setting and camera; paint it as an empty story backdrop, and add characters only when the prompt names them.',
      color_and_tone:
        'Deep indigo base with magenta and cyan neon washes, warm practical lights as small accents.',
      lighting_and_shadow:
        'Soft neon spill on surfaces, gentle bloom around signs and windows, smooth gradient shadows.',
      texture_and_material:
        'Clean anime background painting, crisp architectural lines, soft gradient skies and glossy reflective floors.',
      camera_and_composition:
        'Eye-level, near-symmetrical framing with an open central area where a character could stand; lower quarter kept calm.',
      atmosphere_and_mood: 'Wistful and quiet, a place waiting for its scene.',
      rendering_and_quality:
        'Polished, uncluttered backdrop with blank signs; no people, dialogue boxes or words.',
      key_features:
        'empty anime backdrop; neon magenta and cyan wash; bloom; open central stage; blank signs',
      creative_brief:
        "Visual-novel backdrop: a clean anime-painted location with no characters, graded in neon night color and staged for a character to stand in later. Carry it through empty anime backdrop, neon magenta and cyan wash, bloom, open central stage, blank signs. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-109',
    name: 'Eroded Grandeur Dark Fantasy',
    displayName: 'Eroded Grandeur Dark Fantasy',
    styleAnchors: ['Eroded Grandeur Dark Fantasy', 'Soulslike Tarnished Atmosphere'],
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, bright saturated fantasy, known boss likeness, watermark, text, literal citadel requirement, boss requirement, armor requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Dark fantasy art direction of eroded grandeur: colossal ruined architecture, worn stone and dim gold, with a tiny figure against oppressive scale.',
      subject_treatment:
        'Keep the prompt subject, action, setting and camera; this art direction sets palette, light, shape language and finish, and adds no interface elements.',
      color_and_tone:
        'Desaturated ash grey, bone and ochre with one dim gold or ember accent; low overall saturation.',
      lighting_and_shadow:
        'Overcast diffuse light, pale god-rays through ruins, deep atmospheric perspective and faint ember glows.',
      texture_and_material:
        'Pitted, eroded stone, rusted and tarnished metal, torn banners, moss and ash drifts.',
      camera_and_composition:
        'Keep the requested view; when unspecified, a low patient frame with huge negative space above a small figure.',
      atmosphere_and_mood: 'Melancholic and oppressive, the ruin of a vanished age.',
      rendering_and_quality:
        'Painterly realism with restrained detail and heavy atmosphere; no glossy fantasy color.',
      key_features:
        'colossal ruins; tiny figure; desaturated ash palette; pale god-rays; eroded stone and tarnish',
      creative_brief:
        "Dark fantasy art direction of eroded grandeur: colossal ruined architecture, worn stone and dim gold, with a tiny figure against oppressive scale. Carry it through colossal ruins, tiny figure, desaturated ash palette, pale god-rays, eroded stone and tarnish. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-110',
    name: 'Chibi Platformer Sprite Bounce',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, platform level scene, motion blur, inconsistent proportions, changing costume, background scene, human character requirement, platform requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Chibi platformer sprite: a two-to-three-heads-tall pixel character drawn with squash and stretch, shown as a small sprite sheet of key poses.',
      subject_treatment:
        'Keep the prompt subject and its design; present it as a standalone game asset on a plain field, and build a gameplay scene or interface only when the prompt asks for one.',
      color_and_tone:
        'Bright saturated palette with three-step ramps and a darker hue-shifted outline color per material.',
      lighting_and_shadow:
        'Simple top-left light, one highlight cluster per form and a small oval shadow under each pose.',
      texture_and_material:
        'Clean 32 to 48 pixel sprites, selective outlines, squash on landing and stretch on jumps.',
      camera_and_composition:
        'Orthographic side view, poses in a tidy row on a plain white or pale field, consistent scale and pivot.',
      atmosphere_and_mood: 'Bouncy and cheerful, instantly lovable at small size.',
      rendering_and_quality:
        'Pixel-perfect clusters with consistent proportions across poses; no background scene.',
      key_features:
        'chibi proportions; squash and stretch; sprite-sheet row; hue-shifted outlines; plain field',
      creative_brief:
        "Chibi platformer sprite: a two-to-three-heads-tall pixel character drawn with squash and stretch, shown as a small sprite sheet of key poses. Carry it through chibi proportions, squash and stretch, sprite-sheet row, hue-shifted outlines, plain field. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-111',
    name: 'Battle Royale Compression Colorway',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, known battle royale skins, realistic military gear, weapon requirement, watermark, text, literal arena requirement, storm wall requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Stylized competitive-shooter art direction: chunky readable forms, bright saturated PBR-lite materials and color coding that separates everything at distance.',
      subject_treatment:
        'Keep the prompt subject, action, setting and camera; this art direction sets palette, light, shape language and finish, and adds no interface elements.',
      color_and_tone:
        'Sunny saturated palette against an encroaching violet storm gradient; rarity tints in white, green, blue, purple and gold.',
      lighting_and_shadow:
        'Bright sun with soft ambient fill, strong rim light that separates silhouettes from terrain.',
      texture_and_material:
        'Simplified hand-painted textures on chunky shapes, soft plastic-like sheen, clean stylized foliage clumps.',
      camera_and_composition:
        'Keep the requested view; favor wide readability with the subject isolated against simple terrain.',
      atmosphere_and_mood: 'Energetic and playful, with pressure building at the horizon.',
      rendering_and_quality:
        'Clean, bright, low-noise rendering; silhouettes readable at a distance.',
      key_features:
        'chunky stylized forms; rarity color tints; violet storm gradient; strong rim light; clean foliage clumps',
      creative_brief:
        "Stylized competitive-shooter art direction: chunky readable forms, bright saturated PBR-lite materials and color coding that separates everything at distance. Carry it through chunky stylized forms, rarity color tints, violet storm gradient, strong rim light, clean foliage clumps. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-112',
    name: 'Sci-Fi Arsenal Icon Kit',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, gun requirement, soldier requirement, labels on items, motion blur, inconsistent proportions, changing costume, cluttered background, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Sci-fi equipment icon kit: hard-surface items rendered at three-quarter view as matching inventory icons with emissive accent strips.',
      subject_treatment:
        'Keep the prompt subject and its design; present it as a standalone game asset on a plain field, and build a gameplay scene or interface only when the prompt asks for one.',
      color_and_tone:
        'Gunmetal, white ceramic and black rubber with one emissive accent color shared by the whole set.',
      lighting_and_shadow:
        'Studio key from top-left, cool rim light on the right, subtle glow from emissive strips.',
      texture_and_material:
        'Panel lines, beveled edges, brushed metal, matte polymer and small warning-stripe details without text.',
      camera_and_composition:
        'Each item at the same three-quarter angle, centered with equal padding in a grid on a dark gradient field.',
      atmosphere_and_mood: 'Precise and collectible, gear laid out before a mission.',
      rendering_and_quality:
        'Crisp silhouettes, consistent scale and light across the kit; no labels or numbers.',
      key_features:
        'three-quarter icon angle; emissive accent strips; panel lines and bevels; dark gradient field; equal grid padding',
      creative_brief:
        "Sci-fi equipment icon kit: hard-surface items rendered at three-quarter view as matching inventory icons with emissive accent strips. Carry it through three-quarter icon angle, emissive accent strips, panel lines and bevels, dark gradient field, equal grid padding. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-113',
    name: 'Fantasy MMO Parchment Interface',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, readable map labels, castle requirement, legible script, watermark, text, literal world map requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Fantasy MMO parchment interface: aged parchment and leather panels with carved wood or metal borders, wax seals and icon slots.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a parchment interface panel in which the subject appears as an inked illustration, icon or map, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Warm parchment beige, burnt umber ink, oxblood wax and tarnished brass trim, with small jewel-tone icon accents.',
      lighting_and_shadow:
        'Soft even light with slight vignette; embossed borders and seals cast short shadows.',
      texture_and_material:
        'Stained fibrous parchment, tooled leather, carved border ornaments, cracked wax seals, inked lines.',
      camera_and_composition:
        'Frontal panel layout with ornate frame, one illustrated zone and rows of empty slots or nodes.',
      atmosphere_and_mood: 'Adventurous and scholarly, a guildhall record of the journey.',
      rendering_and_quality:
        'Clean interface hierarchy; any writing is illegible squiggle, never words or numbers.',
      key_features:
        'parchment panel; carved ornate border; wax seal; icon slots; inked illustration',
      creative_brief:
        "Fantasy MMO parchment interface: aged parchment and leather panels with carved wood or metal borders, wax seals and icon slots. Carry it through parchment panel, carved ornate border, wax seal, icon slots, inked illustration. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-114',
    name: 'Anime Gacha Foil Frame',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, readable stats, generic anime schoolgirl, revealing outfit, watermark, text, character requirement, weapon requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Gacha character card: a vertical collectible card with an ornate iridescent foil frame around a clean anime-painted character illustration.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a vertical collectible-card frame with a foil border and rarity gems around the subject, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Bright clean anime color in the art window, rainbow holographic foil and gold filigree on the frame.',
      lighting_and_shadow:
        'Glamorous key light on the character, sparkle and lens-flare bursts, foil catching rainbow reflections.',
      texture_and_material:
        'Holographic foil shimmer, embossed gold filigree, faceted rarity gems, particle bursts and petals in the art.',
      camera_and_composition:
        'Vertical card; the character breaks slightly out of the art window, ornate border hierarchy, star gems at top.',
      atmosphere_and_mood: 'Dazzling and precious, the thrill of a rare pull.',
      rendering_and_quality:
        'Polished anime finish with crisp foil edges; no stats, numbers or name banner.',
      key_features:
        'vertical card; iridescent foil frame; rarity gems; clean anime paint; figure breaking the frame',
      creative_brief:
        "Gacha character card: a vertical collectible card with an ornate iridescent foil frame around a clean anime-painted character illustration. Carry it through vertical card, iridescent foil frame, rarity gems, clean anime paint, figure breaking the frame. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-115',
    name: 'Survival Horror Save-Room Lighting',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, gore, monster requirement, typewriter save icon, watermark, text, literal room requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Survival-horror safe room: a pre-rendered-looking interior lit by one warm lamp pool inside cold darkness, seen from a fixed high camera.',
      subject_treatment:
        'Keep the prompt subject, action, setting and camera; this art direction sets palette, light, shape language and finish, and adds no interface elements.',
      color_and_tone:
        'Sickly green-grey and brown in the dark, one warm amber pool of light; crushed but not empty shadows.',
      lighting_and_shadow:
        'Single small warm source, steep falloff, deep shadows in corners, faint cold light from a doorway.',
      texture_and_material:
        'Peeling paint, stained tiles, worn wood and damp plaster, soft film grain over a slightly soft pre-rendered finish.',
      camera_and_composition:
        'Keep the requested view; when unspecified, a fixed high-corner angle with slightly awkward perspective and empty space.',
      atmosphere_and_mood: 'Briefly safe yet uneasy, a held breath before going back out.',
      rendering_and_quality:
        'Soft pre-rendered look with fine grain; no monsters or gore unless the prompt asks.',
      key_features:
        'single warm lamp pool; fixed high-corner camera; green-grey darkness; damp worn surfaces; fine grain',
      creative_brief:
        "Survival-horror safe room: a pre-rendered-looking interior lit by one warm lamp pool inside cold darkness, seen from a fixed high camera. Carry it through single warm lamp pool, fixed high-corner camera, green-grey darkness, damp worn surfaces, fine grain. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-116',
    name: 'Stealth Game Shadow Readability',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, weapon requirement, guard requirement, muddy midtones, watermark, text, literal rooftop requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Stealth art direction: the world divided into readable lit and unlit zones, cool blue shadow where you hide and warm pools where you are seen.',
      subject_treatment:
        'Keep the prompt subject, action, setting and camera; this art direction sets palette, light, shape language and finish, and adds no interface elements.',
      color_and_tone:
        'Deep blue-violet shadows, warm sodium or lantern pools, very little midtone between them.',
      lighting_and_shadow:
        'Hard-edged light pools with clear boundaries, moonlight as cool fill, strong occluder shadows.',
      texture_and_material:
        'Rough stone, tiled roofs, wooden shutters and cloth, details visible in light and lost in shadow.',
      camera_and_composition:
        'Keep the requested view; when unspecified, an oblique high angle that shows the hiding path and the light to avoid.',
      atmosphere_and_mood: 'Silent and tense, patience measured in footsteps.',
      rendering_and_quality: 'Clean value design where shadow and light zones read at a glance.',
      key_features:
        'lit and unlit zones; hard-edged light pools; cool blue shadows; warm lantern light; visible hiding path',
      creative_brief:
        "Stealth art direction: the world divided into readable lit and unlit zones, cool blue shadow where you hide and warm pools where you are seen. Carry it through lit and unlit zones, hard-edged light pools, cool blue shadows, warm lantern light, visible hiding path. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-117',
    name: 'Arcade Racing Velocity Neon',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, car brand badge, readable signage, licensed car likeness, watermark, text, car requirement, race track requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Arcade racing art direction: glossy vehicles and streaking neon light trails pulled toward a vanishing point at exaggerated speed.',
      subject_treatment:
        'Keep the prompt subject, action, setting and camera; this art direction sets palette, light, shape language and finish, and adds no interface elements.',
      color_and_tone:
        'Saturated magenta, cyan and orange light trails against deep blue dusk or night; glossy reflections everywhere.',
      lighting_and_shadow:
        'Neon and headlight streaks, bloom on every light source, bright specular sweeps across curved bodies.',
      texture_and_material:
        'Mirror-glossy paint, wet-look reflective road, motion-streaked scenery and sparks.',
      camera_and_composition:
        'Keep the requested view; favor a low wide angle with strong vanishing-point pull and diagonal lanes.',
      atmosphere_and_mood: 'Euphoric and fast, speed felt as color.',
      rendering_and_quality:
        'Sharp subject against radial motion streaks; no brand badges or signage text.',
      key_features:
        'neon light trails; low wide angle; vanishing-point pull; glossy reflections; radial motion streaks',
      creative_brief:
        "Arcade racing art direction: glossy vehicles and streaking neon light trails pulled toward a vanishing point at exaggerated speed. Carry it through neon light trails, low wide angle, vanishing-point pull, glossy reflections, radial motion streaks. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
  {
    id: 'SP06-118',
    name: 'RPG Pixel Inventory Icon System',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, item counts, painterly icons, mixed icon scales, motion blur, inconsistent proportions, changing costume, background scene, weapon requirement, potion requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'RPG pixel inventory icons: small 32 by 32 pixel item icons with a one-pixel dark outline, top-left light and a matched slot frame.',
      subject_treatment:
        'Keep the prompt subject and its design; present it as a standalone game asset on a plain field, and build a gameplay scene or interface only when the prompt asks for one.',
      color_and_tone:
        'Three-to-four-step hue-shifted ramps per material, warm highlights and cool shadows, one saturated accent per item.',
      lighting_and_shadow:
        'Consistent top-left light across every icon, one bright specular pixel on metal and glass.',
      texture_and_material:
        'Clean pixel clusters for leather, iron, glass, wood and cloth; no noise, no dithering chatter.',
      camera_and_composition:
        'Each item centered in an identical square slot with equal padding, arranged as a neat grid.',
      atmosphere_and_mood: 'Satisfying and collectible, loot sorted with care.',
      rendering_and_quality:
        'Pixel-perfect edges and uniform scale and outline weight across the set; no numbers.',
      key_features:
        '32x32 pixel icons; one-pixel outline; hue-shifted ramps; top-left light; matched square slots',
      creative_brief:
        "RPG pixel inventory icons: small 32 by 32 pixel item icons with a one-pixel dark outline, top-left light and a matched slot frame. Carry it through 32x32 pixel icons, one-pixel outline, hue-shifted ramps, top-left light, matched square slots. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-119',
    name: 'Cozy Sim Seasonal Palette',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, harsh contrast, gritty textures, known farming game likeness, motion blur, inconsistent proportions, changing costume, farm requirement, crop requirement, animal requirement, watermark, text, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Cozy life-sim art direction: soft pixel or painted forms with rounded shapes, gentle outlines and warm seasonal palettes.',
      subject_treatment:
        'Keep the prompt subject, action, setting and camera; this art direction sets palette, light, shape language and finish, and adds no interface elements.',
      color_and_tone:
        'One season per image: spring pastels, summer greens, autumn ambers or winter blues, always warm-leaning and low contrast.',
      lighting_and_shadow:
        'Soft sunny light, short soft shadows, warm window glow in evening scenes.',
      texture_and_material:
        'Rounded wood, soft foliage clumps, knitted and woven textures, small scattered details like flowers and leaves.',
      camera_and_composition:
        'Keep the requested view; tidy spacing, cozy negative space and small useful objects arranged invitingly.',
      atmosphere_and_mood: 'Gentle and comforting, daily routine as a small pleasure.',
      rendering_and_quality:
        'Clean soft outlines and a controlled seasonal palette; nothing harsh or gritty.',
      key_features:
        'seasonal palette; rounded forms; soft outlines; warm light; cozy negative space',
      creative_brief:
        "Cozy life-sim art direction: soft pixel or painted forms with rounded shapes, gentle outlines and warm seasonal palettes. Carry it through seasonal palette, rounded forms, soft outlines, warm light, cozy negative space. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
    layout: {
      preferredFrameCount: 8,
      frameGrid: '4x2',
      transparentBackground: true,
    },
  },
  {
    id: 'SP06-120',
    name: 'Boss Encounter Key Art Tension',
    category: '7. Game Art Directions & UI',
    negativePrompt:
      'copied game characters, known game HUD layout, readable interface text, numbers and stat values, publisher or studio logo, boss health bar, title lettering, gore, watermark, text, monster requirement, combat scene, weapon requirement, wrong medium, generic AI gloss, muddy noise, uncontrolled texture chatter, readable text, signature, low resolution, readable UI text, logo clutter, generic screenshot, unplayable visual clutter, readable labels, logo, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic:
        'Boss encounter key art: a colossal threat towering over a tiny challenger, cinematic painterly rendering built on extreme scale contrast.',
      subject_treatment:
        'Keep the prompt subject and action recognizable; this preset owns a low-angle key-art composition built on extreme scale contrast between threat and challenger, with blank panels and icon shapes instead of any readable text, numbers or logos.',
      color_and_tone:
        'Dark smoky base with one ominous color for the boss (ember red, poison green or cold violet) and a small warm light on the hero.',
      lighting_and_shadow:
        'Strong backlight and rim light on the colossus, silhouetted challenger, smoke and ash catching light.',
      texture_and_material:
        'Rough painted detail on the boss, drifting ash, embers and dust, simplified foreground ground plane.',
      camera_and_composition:
        'Low angle from behind the small challenger, boss filling the upper two thirds, diagonal tension lines.',
      atmosphere_and_mood: 'Ominous and awe-struck, the moment before an impossible fight.',
      rendering_and_quality:
        'Cinematic painterly finish, clear silhouettes at both scales; no health bars or titles.',
      key_features:
        'extreme scale contrast; low angle from behind the hero; boss rim light; drifting ash; one ominous color',
      creative_brief:
        "Boss encounter key art: a colossal threat towering over a tiny challenger, cinematic painterly rendering built on extreme scale contrast. Carry it through extreme scale contrast, low angle from behind the hero, boss rim light, drifting ash, one ominous color. Use it as a reusable look on any subject, keeping the prompt's own subject, action, setting and mood.",
    },
  },
] as unknown as StyleRuntimePreset[];
