// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP10-046',
    name: 'Paisley Pattern',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, solid color, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Paisley: curved teardrop botehs with intricate inner filling.',
      subject_treatment:
        "Apply this motif printed or woven onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: repeating teardrop botehs filled with florals and dots.",
      color_and_tone:
        'Rust, indigo, gold and cream, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Printed or woven fabric with fine detail, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Bohemian, ornate, warm and flowing, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'teardrop botehs; intricate filling',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Paisley Pattern as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-047',
    name: 'Damask Pattern',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, modern, messy, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Damask: reversible woven floral motifs in tone-on-tone sheen.',
      subject_treatment:
        "Apply this motif printed or woven onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: large symmetrical floral damask motifs shown by matte and satin contrast.",
      color_and_tone:
        'Tone-on-tone crimson, ivory or black, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Woven jacquard with satin sheen, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood: 'Regal, formal, rich and quiet, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'tone-on-tone damask; satin/matte contrast',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Damask Pattern as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-049',
    name: 'Houndstooth',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, floral, organic, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Houndstooth: broken check of four-pointed jagged shapes.',
      subject_treatment:
        "Apply this motif woven into the fabric of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: crisp houndstooth broken checks.",
      color_and_tone:
        'Black and white or brown and cream, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material: 'Woven wool twill, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Classic, sharp, tailored and graphic, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'houndstooth broken check',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Houndstooth as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-050',
    name: 'Tartan (Plaid)',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, curved lines, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Tartan: intersecting colored stripes forming a woven plaid sett.',
      subject_treatment:
        "Apply this motif woven into the fabric of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: a tartan sett of crossing stripes with twill diagonals.",
      color_and_tone:
        'Deep green, navy, red and yellow lines, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material: 'Woven wool twill, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Rugged, clan-proud, warm and bold, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'tartan sett; twill diagonals',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Tartan (Plaid) as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-051',
    name: 'Polka Dot',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, square, line, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Polka dot: evenly spaced round dots on a contrasting ground.',
      subject_treatment:
        "Apply this motif printed or woven onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: evenly spaced round dots.",
      color_and_tone:
        'White on red, black on white or navy, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Printed fabric or painted surface, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Playful, retro, cheerful and bold, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'even round dots',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Polka Dot as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-052',
    name: 'Camouflage',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, military insignia, bright, neon, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Camouflage: disruptive organic blotch pattern for concealment.',
      subject_treatment:
        "Apply this motif printed or woven onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: organic camouflage blotches in 3-4 tones.",
      color_and_tone:
        'Woodland greens, desert tans or urban greys, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Printed ripstop or paint, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Military, rugged, hidden and practical, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'camouflage blotches',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Camouflage as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-053',
    name: 'Tie Dye',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, sharp lines, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Tie-dye: radial or spiral dye bursts with soft bleeding edges.',
      subject_treatment:
        "Apply this motif dyed into the fabric of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: spiral or radial dye bursts with soft edges.",
      color_and_tone:
        'Saturated rainbow or indigo, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Dyed cotton with bleed, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Joyful, free, hippie and bright, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'tie-dye spirals; bleeding edges',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Tie Dye as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-057',
    name: 'Knitted Texture',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, smooth, flat, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Knitted texture: visible knit stitches, cables and ribbing forming the surface.',
      subject_treatment:
        "Apply this motif built from knit stitches on the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: visible knit stitches and cables as a surface texture.",
      color_and_tone:
        'Wool colors, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Knit stitches with fuzz, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood: 'Cozy, handmade, warm and soft, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'knit stitches; cables',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Knitted Texture as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-058',
    name: 'Denim Texture',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, silk, smooth, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Denim texture: indigo twill with diagonal weave and fading.',
      subject_treatment:
        "Apply this motif woven into the fabric of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: indigo twill with diagonal weave and whiskered fading.",
      color_and_tone:
        'Indigo blues, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Twill weave with fading, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Casual, rugged, American and worn, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'indigo twill; diagonal weave',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Denim Texture as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-065',
    name: 'Basket Weave',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, solid, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Basket weave: over-under interlaced strips like woven rattan.',
      subject_treatment:
        "Apply this motif woven as the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: over-under interlaced strips.",
      color_and_tone:
        'Natural rattan, straw and tan, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Woven strips with gaps, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Handmade, natural, rustic and airy, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'over-under interlaced strips',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Basket Weave as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-066',
    name: 'Honeycomb',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, square, circle, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Honeycomb pattern: tessellated hexagon cells as a surface motif.',
      subject_treatment:
        "Apply this motif printed or woven onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: tessellated hexagon cells.",
      color_and_tone:
        'Gold, amber or monochrome, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Hexagonal cells with raised edges, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Orderly, organic, natural and precise, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'hexagon tessellation',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Honeycomb as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-070',
    name: 'Azulejo Tile',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, modern, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Azulejo: glazed blue-and-white painted tiles with ornate repeats.',
      subject_treatment:
        "Apply this motif as glazed tiles on the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: blue-and-white glazed tile repeats with ornate borders.",
      color_and_tone:
        'Cobalt blue on white glaze, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Glazed ceramic tiles with grout, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Mediterranean, fresh, ornate and bright, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'blue-white glazed tiles; ornate repeats',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Azulejo Tile as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-075',
    name: 'Cross Stitch',
    category: '5. Textile & Ornamental Patterns',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, smooth, drawn, generic wallpaper overlay, pattern pasted flat, literal card scene, style-card boilerplate, muddy noise, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Cross stitch: X-shaped stitches forming pixel-like motifs on even-weave fabric.',
      subject_treatment:
        "Apply this motif built from cross stitches on the fabric of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: X-stitch motifs on an even-weave grid.",
      color_and_tone:
        'Embroidery floss colors, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'X stitches on aida cloth, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Homely, handmade, charming and patient, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      key_features: 'X stitches; even-weave grid',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Cross Stitch as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
    },
  },
  {
    id: 'SP10-116',
    name: 'Toile de Jouy',
    displayName: 'Toile de Jouy',
    styleAnchors: ['Toile de Jouy', 'toile scenic print', 'engraved vignettes'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'toile scenic print',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Toile de Jouy: single-color engraved pastoral scenes repeated on cream cloth.',
      subject_treatment:
        "Apply this motif printed or woven onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: repeated single-color engraved vignettes.",
      color_and_tone:
        'Red, blue or black on cream, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material: 'Printed cotton, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Romantic, antique, pastoral and refined, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Toile de Jouy as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'engraved vignettes; single color on cream',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP10-117',
    name: 'Ikat Blur',
    displayName: 'Ikat Blur',
    styleAnchors: ['Ikat Blur', 'ikat resist-dyed weave', 'blurred-edge ikat motifs'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'ikat resist-dyed weave',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Ikat: resist-dyed yarns woven into blurred-edge geometric motifs.',
      subject_treatment:
        "Apply this motif dyed into the yarn before weaving of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: blurred-edge diamond and hook motifs.",
      color_and_tone:
        'Indigo, madder red, ochre and cream, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Woven threads with feathered edges, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Handcrafted, rich, earthy and vibrant, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Ikat Blur as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'blurred-edge ikat motifs',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP10-118',
    name: 'Batik Wax Resist',
    displayName: 'Batik Wax Resist',
    styleAnchors: ['Batik Wax Resist', 'batik wax resist dye', 'wax-resist motifs'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'batik wax resist dye',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Batik: wax-resist dyed cloth with crackled lines and layered colors.',
      subject_treatment:
        "Apply this motif dyed into the cloth of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: wax-resist motifs with fine crackle lines.",
      color_and_tone:
        'Indigo, brown and cream, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Dyed cotton with crackle, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Earthy, handcrafted, intricate and warm, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Batik Wax Resist as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'wax-resist motifs; crackle lines',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP10-119',
    name: 'Shibori Indigo',
    displayName: 'Shibori Indigo',
    styleAnchors: ['Shibori Indigo', 'shibori indigo dye', 'indigo shibori resist'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'shibori indigo dye',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Shibori: indigo shaped-resist dyeing with folded, bound and stitched patterns.',
      subject_treatment:
        "Apply this motif dyed into the cloth of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: soft indigo resist patterns from folding and binding.",
      color_and_tone:
        'Indigo and white, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material: 'Dyed cotton or silk, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood: 'Calm, handmade, fluid and deep, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Shibori Indigo as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'indigo shibori resist',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP10-120',
    name: 'Argyle',
    displayName: 'Argyle',
    styleAnchors: ['Argyle', 'argyle diamond knit', 'argyle diamonds'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'argyle diamond knit',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Argyle: overlapping diamonds with thin diagonal crossing lines.',
      subject_treatment:
        "Apply this motif knitted into the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: diamonds with thin crossing diagonals.",
      color_and_tone:
        'Navy, burgundy, green and cream, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material: 'Knit wool, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Preppy, classic, cozy and playful, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Argyle as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'argyle diamonds; crossing lines',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP10-121',
    name: 'Kilim Geometric',
    displayName: 'Kilim Geometric',
    styleAnchors: ['Kilim Geometric', 'kilim flatweave', 'kilim stepped diamonds'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'kilim flatweave',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Kilim: flat-woven geometric diamonds, hooks and stepped motifs.',
      subject_treatment:
        "Apply this motif flat-woven as the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: stepped diamonds and hook motifs.",
      color_and_tone:
        'Madder red, indigo, saffron, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Flatweave wool with slits, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Nomadic, bold, warm and ancient, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Kilim Geometric as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'kilim stepped diamonds; flatweave',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
  {
    id: 'SP10-122',
    name: 'Celtic Knotwork',
    displayName: 'Celtic Knotwork',
    styleAnchors: ['Celtic Knotwork', 'celtic interlace knotwork', 'over-under interlace'],
    category: '5. Textile & Ornamental Patterns',
    domain: 'celtic interlace knotwork',
    negativePrompt:
      'readable text, logo, real artist signature, copying a specific famous artwork, muddy noisy texture, pattern covering the whole scene instead of the target, watermark, text, readable labels, UI overlay, franchise likeness, real person likeness, prompt literal card reuse, noisy compression artifacts',
    style: {
      aesthetic: 'Celtic knotwork: continuous interlaced bands weaving over and under.',
      subject_treatment:
        "Apply this motif carved, embroidered or painted onto the surface of the target named in the prompt (garment, object, upholstery, wall); if none is named, use it on the main subject's clothing or surface. Keep shape, pose and setting: continuous over-under interlace bands.",
      color_and_tone:
        'Gold, green and deep red, on the patterned surface while the rest of the scene keeps its palette.',
      lighting_and_shadow:
        'Natural light that follows the surface, so the pattern bends with folds and curves.',
      texture_and_material:
        'Carved, embroidered or painted, with the pattern scaled correctly to the target.',
      camera_and_composition:
        'Keep the prompt framing; show enough of the patterned surface for the motif to read at card size.',
      atmosphere_and_mood:
        'Ancient, mystic, intricate and flowing, carried by the pattern and its colors.',
      rendering_and_quality:
        'Crisp, correctly repeating pattern that wraps believably around form, without smeared or random motifs.',
      creative_brief:
        "Apply this as a reusable style router after prompt X: prompt X supplies subject, action, setting, tone, and intensity, while this preset supplies Celtic Knotwork as medium, palette, mark language, composition logic, material behavior, and finish. Preserve the user's subject instead of forcing this preset's sample-card subject, fixed character, fixed prop, readable text, or a repeated thumbnail formula.",
      key_features: 'over-under interlace; continuous bands',
    },
    ui: {
      previewStatus: 'pending',
    },
  },
] as unknown as StyleRuntimePreset[];
