// Display-only labels. Source category keys, hashes, thumbnails and saved IDs stay unchanged.
const CATEGORY_DISPLAY_NAMES: Readonly<Record<string, string>> = {
  'pack_01::1. Portrait And Studio': 'Portrait & studio',
  'pack_01::2. Lighting Techniques': 'Light studies',
  'pack_01::3. Film And Analog Process': 'Film response',
  'pack_01::4. Documentary And Street': 'Documentary & camera',
  'pack_01::5. Commercial And Product': 'Commercial imaging',
  'pack_01::6. Nature And Wildlife': 'Nature imaging',
  'pack_01::7. Technical And Specialist Imaging': 'Technical capture',
  'pack_02::1. Film Genres': 'Cinema languages',
  'pack_02::2. TV And Broadcast': 'Broadcast formats',
  'pack_02::3. Animation Styles': 'Animation craft',
  'pack_02::4. Photography Eras': 'Historic photo processes',
  'pack_02::5. Lighting And Atmosphere': 'Cinematic lighting',
  'pack_02::6. Caricature And Cartoon Styles': 'Cartoon & caricature',
  'pack_02::7. Sensor And Technical Imaging': 'Sensor looks',
  'pack_02::8. Hand-Drawn And DIY Media': 'DIY drawing surfaces',
  'pack_03::1. Render Engines': 'CGI rendering',
  'pack_03::2. Materials': 'CGI material response',
  'pack_03::3. Lighting And Atmosphere': 'CGI light',
  'pack_03::4. 3D Styles': 'Stylized 3D',
  'pack_03::5. Hard Surface And Product CGI': 'Hard-surface production',
  'pack_03::6. Organic Character And Bio CGI': 'Organic CGI',
  'pack_03::7. Environment And Worldbuilding': 'Environment directions',
  'pack_03::8. Sensor And Technical Shaders': 'Technical shaders',
  'pack_04::1. Comic Book Styles': 'Comics',
  "pack_04::2. Children's Illustration": 'Storybook illustration',
  'pack_04::3. Editorial And Poster': 'Editorial & posters',
  'pack_04::4. Concept Art': 'Concept development',
  'pack_04::5. Ink And Print': 'Ink & print',
  'pack_04::6. Technical And Reference Sheets': 'Reference layouts',
  'pack_05::1. Modern Shonen & Action': 'Action drawing',
  'pack_05::2. Mecha & Cyberpunk': 'Mechanical anime',
  'pack_05::3. Isekai & High Fantasy': 'Fantasy anime',
  'pack_05::4. Dark Fantasy & Seinen': 'Dark anime',
  'pack_05::5. Action Motion Setpieces': 'Action staging',
  'pack_06::1. Traditional Painting': 'Painting',
  'pack_06::2. Drawing & Sketching': 'Drawing',
  'pack_06::3. Printmaking': 'Printmaking',
  'pack_06::4. Digital Art': 'Digital media',
  'pack_06::5. Mixed Media': 'Mixed media',
  'pack_06::6. Retro Game Visual Systems': 'Pixel constraints',
  'pack_06::7. Game Art Directions & UI': 'Game art & interfaces',
  'pack_07::1. Interior Design Systems': 'Interior systems',
  'pack_07::2. Architectural Movements And Vernaculars': 'Architectural systems',
  'pack_07::3. Civic Infrastructure And Specialty Spaces': 'Specialty spaces',
  'pack_07::4. Landscape And Garden Systems': 'Garden systems',
  'pack_07::5. Fantasy And Mythic Architecture': 'Imagined architecture',
  'pack_07::6. Toy Craft And Miniature Architecture': 'Miniature construction',
  'pack_07::7. Megastructure And Impossible Space': 'Impossible space',
  'pack_08::1. Contemporary Fashion': 'Contemporary clothing',
  'pack_08::2. Subcultures': 'Subcultural clothing',
  'pack_08::3. Historical & Fantasy': 'Historical clothing',
  'pack_08::4. Fantasy Sci-Fi Costume': 'Speculative costume',
  'pack_08::5. Fabric & Texture Focus': 'Fabric studies',
  'pack_09::1. Natural Materials': 'Natural surfaces',
  'pack_09::2. Man-Made Materials': 'Manufactured surfaces',
  'pack_09::3. Weathering And Decay': 'Wear & weathering',
  'pack_09::4. Tactile Surfaces': 'Tactile response',
  'pack_09::5. Elemental And FX': 'Elemental effects',
  'pack_10::1. Geometric Abstraction': 'Geometric abstraction',
  'pack_10::2. Fluid & Organic': 'Fluid abstraction',
  'pack_10::3. Digital Glitch & Noise': 'Digital artifacts',
  'pack_10::4. Surrealism & Dream': 'Surreal systems',
  'pack_10::5. Textile & Ornamental Patterns': 'Pattern systems',
  'pack_10::6. Material Surface Textures': 'Surface transformations',
  'pack_10::7. Diagram And Data Systems': 'Diagram languages',
  'pack_10::8. Point, Mosaic And Glass Systems': 'Unit-based illustration',
  'pack_10::9. Print And Light Finishes': 'Print & light finish',
  'pack_11::1. Toys And Crafts': 'Craft & miniatures',
  'pack_11::2. Artistic Mediums': 'Specialist illustration',
  'pack_11::3. Aesthetics': 'Digital aesthetics',
  'pack_11::4. Food And Drink': 'Food imagery',
  'pack_11::5. Micro Macro': 'Scale & microscopy',
  'pack_11::6. Sensor And Technical Imaging': 'Technical imaging',
  'pack_11::7. Diagram And Technical Drawing': 'Blueprint drawing',
  'pack_12::1. Neon Urban & Night Ops': 'Urban game capture',
  'pack_12::2. Arcane Temples & Mythic Realms': 'Mythic game capture',
  'pack_12::3. Sci-Fi Frontiers & Mech Zones': 'Sci-fi game capture',
  'pack_12::4. Sieges, Warfronts & Last Stands': 'Tactical game capture',
  'pack_12::5. Speed, Sport & Competitive Arenas': 'Speed & arena capture',
  'pack_12::6. Wilderness Hunts & Harsh Frontiers': 'Frontier game capture',
  'pack_12::7. Heists, Horror & Underworld Runs': 'Stealth & horror capture',
  'pack_12::8. Puzzle Chambers & Adventure Setpieces': 'Adventure game capture',
  'pack_13::1. Core Anime': 'Cel fundamentals',
  'pack_13::2. Slice Of Life, School And Music': 'Everyday anime',
  'pack_13::3. Shojo, Magical Girl & Visionary Classics': 'Expressive anime',
  'pack_13::4. Slice Of Life & Moe': 'Quiet character animation',
  'pack_13::5. Anime Style Spectrum': 'Anime rendering spectrum',
  'pack_14::Greek Mythology — Epic Noir': 'Greek Mythology — Epic Noir',
  'pack_14::Japanese Mythology — Kami & Yokai': 'Japanese Mythology — Kami & Yokai',
  'pack_14::Norse Mythology — Sagas': 'Norse Mythology — Sagas',
  'pack_14::Mande Oral Epic': 'Mande Oral Epic',
  'pack_14::Yoruba Mythology — Orisha': 'Yoruba Mythology — Orisha',
  'pack_14::Akan Mythology — Anansi': 'Akan Mythology — Anansi',
  'pack_14::Egyptian Mythology': 'Egyptian Mythology',
  'pack_14::Maya Mythology': 'Maya Mythology',
  'pack_14::Mexica Mythology': 'Mexica Mythology',
  'pack_15::1. Classic Industrial Punks': 'Industrial futures',
  'pack_15::2. Neon, Net & Signal Punks': 'Signal futures',
  'pack_15::3. Eco, Repair & Climate Punks': 'Repair futures',
  'pack_15::4. Bio, Myco & Body Punks': 'Biological futures',
  'pack_15::5. Ocean, Ice & Terrain Punks': 'Terrain futures',
  'pack_15::6. Street, Riot & DIY Punks': 'DIY futures',
  'pack_15::7. Media, Vapor & Glitch Punks': 'Media futures',
  'pack_15::8. Occult, Myth & Gothic Punks': 'Occult futures',
  'pack_15::9. Space, Atomic & Ray Punks': 'Atomic & orbital futures',
  'pack_15::10. Primitive, Stone & Salvage Punks': 'Primitive & salvage futures',
  'pack_16::1. 70s & 80s Retro Anime': 'Retro cel craft',
  'pack_16::2. 90s Golden Era': 'Nineties cel craft',
  'pack_16::3. 2000s Classics': 'Early digital anime',
  'pack_16::4. Studio Masterpieces': 'Authored animation',
  'pack_16::5. Sports, Competition & Performance': 'Performance drawing',
  'pack_16::6. Samurai & Medieval': 'Period action',
  'pack_16::7. Horror': 'Horror animation',
  'pack_17::1. Dark Fantasy & Gothic Courts': 'Matte dark fantasy',
  'pack_17::2. Dungeon Zine & Risograph Prints': 'Zine reproduction',
  'pack_17::3. Ink, Tarot & Bestiary Plates': 'Ink & plate formats',
  'pack_17::4. Rune-Tech & Apocalyptic Warfronts': 'Techno-fantasy design',
  'pack_17::5. Grimdark Game Systems & Tabletop': 'Game & tabletop formats',
  'pack_17::6. Dungeon Zine Assemblage & Stampwork': 'Dungeon zine assemblage',
  'pack_17::7. Pulp Fantasy Painting': 'Pulp fantasy painting',
  'pack_17::8. Medieval Fantasy Drawing Media': 'Fantasy drawing media',
  'pack_17::9. Gothic & Dungeon Art Directions': 'Gothic & dungeon art',
  'pack_17::10. Graphic & Feudal Art Directions': 'Graphic & feudal art',
  'pack_12::9. Gothic & Dungeon Gameplay': 'Gothic & dungeon gameplay',
  'pack_12::10. Graphic & Feudal Gameplay': 'Graphic & feudal gameplay',
  'pack_12::11. Psychological & Tactical Gameplay': 'Psychological & tactical gameplay',
  'pack_24::1. Psychological Horror Aesthetics': 'Psychological horror',
  'pack_24::2. Tactical & Solitary Frontiers': 'Tactical & solitary frontiers',
  'pack_19::1. Ink Structures': 'Ink Structures',
  'pack_20::1. Print Registers': 'Print Registers',
  'pack_21::1. Paper & Pigment': 'Paper & Pigment',
  'pack_22::1. Workshop Painting': 'Workshop Painting',
  'pack_22::2. Epic Digital Painting': 'Epic Digital Painting',
  'pack_22::3. Strange Ink & Paint': 'Strange Ink & Paint',
  'pack_22::4. Storybook & Animation': 'Storybook & Animation',
  'pack_22::5. Character & Readable Forms': 'Character & Readable Forms',
  'pack_22::6. Anime Illustration': 'Anime Illustration',
  'pack_22::7. Manga Ink & Impact': 'Manga Ink & Impact',
  'pack_22::8. Technical Illustration': 'Technical Illustration',
  'pack_22::9. Comic & Cartoon Illustration': 'Comic & Cartoon Illustration',
  'pack_22::10. Printmaking & Reproduction': 'Printmaking & Reproduction',
  'pack_22::11. Ornament & Symbolic Illustration': 'Ornament & Symbolic Illustration',
  'pack_22::12. Crafted Materials & Miniatures': 'Crafted Materials & Miniatures',
  'pack_22::13. Vintage Collectible Illustration': 'Vintage Collectible Illustration',
  'pack_22::14. Symbolic Graphic Illustration': 'Symbolic Graphic Illustration',
  'pack_22::15. Digital Rendering Methods': 'Digital Rendering Methods',
  'pack_23::1. Manuscript Visual Systems': 'Manuscript Visual Systems',
  'pack_23::2. Print & Engraving': 'Print & Engraving',
  'pack_23::3. Medieval Material Studies': 'Medieval Material Studies',
  'pack_23::4. Regional Manuscript Traditions': 'Regional Manuscript Traditions',
  'pack_23::5. Revival & Storybook Illustration': 'Revival & Storybook Illustration',
  'pack_23::6. Classic RPG Visual Studies': 'Classic RPG Visual Studies',
  'pack_23::7. Indexed Raster Language': 'Indexed Raster Language',
  'pack_23::8. Retro 3D Visual Studies': 'Retro 3D Visual Studies',
  'pack_23::9. Painted RPG & Tactics': 'Painted RPG & Tactics',
  'pack_23::10. Tabletop Illustration Studies': 'Tabletop Illustration Studies',
  'pack_23::11. Modern Visual Techniques': 'Modern Visual Techniques',
  'pack_23::12. Hybrid Visual Studies': 'Hybrid Visual Studies',
};

export function getStyleCategoryDisplayName(packId: string, sourceCategory: string) {
  return CATEGORY_DISPLAY_NAMES[`${packId}::${sourceCategory}`] ?? sourceCategory;
}
