// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StylePresetDef } from '../../styles/types';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP08-077',
    name: 'Stone Statue',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'flesh',
    style: {
      aesthetic: 'Living statue, museum-come-alive fantasy, petrified-elegance awe',
      form_and_line:
        'Chisel marks, contrapposto-stance, sculpted-drapery fold, classical-proportion silhouette, pedestal-base stillness',
      color_palette:
        'Grey Marble, Carrara-white, Pentelic-cream, veined-grey, Parian-snow, weathered-ivory, shadow-grey recess',
      lighting_setup:
        'Museum, gallery-spot precision, overhead-directional drama, pedestal-up shadow, marble-subsurface scatter',
      material_texture:
        'Stone, fine-grain marble, crystalline-sparkle, chisel-tool mark, weathered-surface, polished-high, dust-settled crevice',
      render_quality: 'Classic, cold, Bernini-marble realism, gallery-plinth gravitas',
      spatial_distortion: 'Rigid',
      atmosphere:
        'Timeless, still, museum-after-hours magic, sculptural-permanence awe, stone-silence eternity',
      key_features: 'Marble, veining, chisel marks, contrapposto, pedestal',
    },
  },
  {
    id: 'SP08-052',
    name: 'Denim on Denim',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'silk, suit',
    style: {
      aesthetic: 'Canadian Tuxedo, denim-on-denim confidence, Americana-workwear cool',
      form_and_line:
        'Stitching, trucker-jacket box, straight-leg column, western-yoke line, contrast-thread geometry',
      color_palette:
        'Indigo Blue, raw-indigo, faded-wash blue, ecru weft, copper-orange stitching, stonewashed sky',
      lighting_setup: 'Studio, softbox-even, denim-texture side-light, garage-daylight',
      material_texture:
        'Denim weave, selvedge twill, contrast-thread chainstitch, copper rivets, buffalo-horn buttons, leather patch',
      render_quality: 'Textured, casual, heritage-workwear authenticity, Americana-denim fidelity',
      spatial_distortion: 'None',
      atmosphere: 'Cool, blue, blue-collar pride, weekend-ease, American-classic confidence',
      key_features:
        'Orange stitching, selvedge ID, copper rivets, leather patch, double-denim coordination',
    },
  },
  {
    id: 'SP08-051',
    name: 'Latex/PVC',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'matte, cotton',
    style: {
      aesthetic: 'Fetish fashion, high-gloss domination, latex-subculture statement',
      form_and_line:
        'Tight highlights, second-skin compression, corset-waist curve, opera-glove length, catsuit continuity',
      color_palette:
        'Black shiny, blood-red, midnight purple, liquid-mercury, rubber-white, patent-bordeaux',
      lighting_setup:
        'High contrast reflection, rim-light gloss, studio-strip catchlights, wet-look sheen',
      material_texture:
        'Glossy latex, polished PVC, wet-look spandex, patent leather, chlorinated rubber, slick sealant finish',
      render_quality: 'Shiny, edgy, high-polish fetish aesthetic, studio-reflection perfection',
      spatial_distortion: 'None',
      atmosphere: 'Intense, sleek, power-dressing charge, mirror-shine confidence, club-kid edge',
      key_features: 'Reflections, crease-free tension, zip front, corset lacing, high-shine polish',
    },
  },
  {
    id: 'SP08-053',
    name: 'Fur Coat',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'smooth',
    style: {
      aesthetic: 'Luxury fur, old-Hollywood opulence, cold-climate extravagance',
      form_and_line:
        'Soft edges, voluminous-sleeve bulk, shawl-collar wrap, floor-length column, muff-hand enclosure',
      color_palette:
        'Brown/White, sable, silver-fox, chinchilla grey, mink-champagne, arctic-white',
      lighting_setup:
        'Soft, diffused-glamour light, fur-halo rim, vanity-mirror warmth, evening-interior amber',
      material_texture:
        'Fur strands, mink guard hairs, fox underwool, chinchilla density, sable tips, shearling curl, silken guard',
      render_quality: 'Expensive, soft, fur-atelier luxury, tactile-lavish perfection',
      spatial_distortion: 'None',
      atmosphere: 'Rich, warm, fireside-comfort, champagne-evening ease, first-class decadence',
      key_features: 'Fluff, guard-hair sheen, dense underwool, dramatic collar, full-length sweep',
    },
  },
  {
    id: 'SP08-056',
    name: 'Silk & Satin',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'rough, matte',
    style: {
      aesthetic: 'Slip dress, boudoir-elegance minimalism, liquid-light sensuality',
      form_and_line:
        'Fluid drape, bias-cut column, cowl-neck waterfall, spaghetti-strap line, floor-grazing hem',
      color_palette: 'Champagne, Red, oyster, rose-quartz, midnight-navy, ivory, blush, emerald',
      lighting_setup:
        'Soft sheen, candlelight ripple, vanity-bulb warmth, afternoon-window silk glow',
      material_texture:
        'Smooth silk charmeuse, liquid satin, crepe de chine, sand-washed silk, hammered satin, silk georgette',
      render_quality: 'Elegant, soft, boudoir-editorial luxury, light-caught-on-fabric poetry',
      spatial_distortion: 'None',
      atmosphere:
        'Sensual, expensive, bedroom-secret intimacy, champagne-bubble delicacy, silk-against-skin luxury',
      key_features:
        'Drape folds, bias-cut cling, cowl neck, spaghetti straps, liquid-sheen movement',
    },
  },
  {
    id: 'SP08-059',
    name: 'Transparent Plastic',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'opaque',
    style: {
      aesthetic: 'Raincoat, weather-ready futurism, urban-downpour chic',
      form_and_line:
        'Highlights, trans-seasonal trench, A-line volume, drawstring-waist cinch, hood-frame arc',
      color_palette:
        'Clear, tint, optic-clear, smoked-grey, amber-tint, cyan, translucent-white, rose',
      lighting_setup:
        'Reflective, wet-surface glare, rain-streak catchlights, streetlamp-refraction, overcast-diffusion',
      material_texture:
        'Clear vinyl, TPU film, heat-sealed seams, nylon webbing, rubberized zipper, transparent PVC',
      render_quality: 'Waterproof, modern, wet-weather editorial, transparent-tech sophistication',
      spatial_distortion: 'See-through',
      atmosphere: 'Wet, tech, urban-rain serenity, downpour-preparedness, future-commute cool',
      key_features:
        'Transparency, heat-sealed seams, layered visibility, rain droplets, reflective trim',
    },
  },
  {
    id: 'SP08-073',
    name: 'Body Paint',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'clothes',
    style: {
      aesthetic: 'Painted clothes, trompe-l-oeil illusion, skin-as-canvas transformation',
      form_and_line:
        'Brush strokes on skin, painted-lapel line, faux-button stroke, body-contour follow, wet-paint flow',
      color_palette:
        'Vibrant, primary-bold, acrylic-bright, UV-reactive, metallic-body, matte-flat, dayglo',
      lighting_setup:
        'Studio, diffused-even light, ring-flash catch, body-paint evenness, exhibition-gallery spot',
      material_texture:
        'Matte paint, body-paint film, glycerin-sheen, airbrush-gradient, brush-stroke relief, skin-oil through paint',
      render_quality: 'Artistic, illusion, living-canvas spectacle, body-art mastery',
      spatial_distortion: 'None',
      atmosphere:
        'Creative, naked, painted-vulnerability confidence, art-gallery hush, body-ceremony ritual',
      key_features:
        'Paint, brush strokes, trompe-l-oeil effect, painted seams, skin-texture beneath',
    },
  },
  {
    id: 'SP08-057',
    name: 'Tweed Suit',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'smooth, shiny',
    style: {
      aesthetic: 'Professor suit, donnish-academia charm, country-estate weekend',
      form_and_line:
        'Herringbone pattern, structured-shoulder drape, notch-lapel angle, three-roll-two button stance, trouser-break hem',
      color_palette: 'Brown, Green, loden, chestnut, olive-herringbone, barley-corn, moss',
      lighting_setup: 'Flat, study-lamp pool, rainy-window grey, library-wingback warmth',
      material_texture:
        'Rough wool, herringbone tweed, Donegal fleck, shetland wool, horn buttons, bemberg lining',
      render_quality: 'Classic, textured, Savile Row heritage, country-house authenticity',
      spatial_distortion: 'None',
      atmosphere:
        'Smart, old school, leather-armchair comfort, pipe-smoke contemplation, donnish eccentricity',
      key_features: 'Herringbone, elbow patches, ticket pocket, knitted tie, brogues',
    },
  },
  {
    id: 'SP08-072',
    name: 'Tattoo Skin',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'clean skin',
    style: {
      aesthetic: 'Full body suit tattoo, living-canvas autobiography, ink-and-skin devotion',
      form_and_line:
        'Ink lines, bodysuit-coverage contour, sleeve-to-chest flow, back-piece canvas, Japanese-traditional background',
      color_palette:
        'Blue/Black ink, tebori-indigo, iron-black, old-school red, yellow, green accent, skin-tone canvas',
      lighting_setup:
        'Skin, studio-softbox evenness, rim-light muscle definition, tattoo-parlor fluorescent, healed-ink saturation',
      material_texture:
        'Skin, healed-ink surface, needle-point texture, raised-line keloid, skin-sheen, stippled-shading dotwork',
      render_quality: 'Artistic, permanent, irezumi-master precision, living-canvas dedication',
      spatial_distortion: 'None',
      atmosphere:
        'Edgy, committed, ink-commitment gravity, bodysuit-ritual patience, living-art pride',
      key_features:
        'Ink, full-coverage bodysuit, Japanese background, sleeve-to-chest connection, healed-settle depth',
    },
  },
  {
    id: 'SP08-062',
    name: 'Leather Armor',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'metal, cloth',
    style: {
      aesthetic: 'Fantasy rogue, shadow-guild anonymity, dungeon-crawler practicality',
      form_and_line:
        'Straps, studs, asymmetrical-harness geometry, pauldron-shoulder square, bracer-forearm wrap, hooded-cowl depth',
      color_palette: 'Brown, Black, oxblood, oiled-chestnut, shadow-black, bronze-stud, smoke',
      lighting_setup:
        'Subsurface scatter, torchlit-corridor amber, dungeon-shadow depth, candle-flicker rim, moonlight-through-bars',
      material_texture:
        'Worn leather, oil-tanned hide, distressed leather, brass studs, iron buckles, suede lining, tooled-leather panel',
      render_quality: 'Tough, flexible, D&D-manual realism, stealth-gear authenticity',
      spatial_distortion: 'None',
      atmosphere:
        'Adventure, tough, shadow-alley tension, lockpick silence, midnight-escape adrenaline',
      key_features: 'Buckles, hood, hidden pouches, throwing-knife bandolier, soft-soled boots',
    },
  },
  {
    id: 'SP08-074',
    name: 'Bandage/Mummy',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'skin',
    style: {
      aesthetic: 'Wrapped in bandages, tomb-risen horror, ancient-curse concealment',
      form_and_line:
        'Wrapping lines, body-enveloping spiral, mummiform-silhouette, crossing-bandage grid, trailing-wrap end',
      color_palette:
        'White, Dirty, aged-linen, dried-blood brown, desert-dust tan, tomb-shadow grey, ancient-yellow',
      lighting_setup:
        'Flat, tomb-interior dimness, torch-flicker amber, sarcophagus-shadow mystery, excavation-site daylight',
      material_texture:
        'Cloth strips, linen bandage, gauze-weave texture, frayed-edge loose wrap, stiffened-gauze, overlapping-layer bulk',
      render_quality: 'Spooky, hurt, Universal-monster atmosphere, curse-of-the-pharaoh dread',
      spatial_distortion: 'None',
      atmosphere:
        'Horror, hidden, sarcophagus-confinement dread, ancient-awakening tension, wrapped-identity mystery',
      key_features:
        'Wraps, layered bandages, trailing ends, gap-showing skin, wrapped-face silhouette',
    },
  },
  {
    id: 'SP08-079',
    name: 'Invisibility Cloak',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'visible',
    style: {
      aesthetic: 'Partially invisible, refraction-mirage wonder, stealth-magic concealment',
      form_and_line:
        'Distortion edge, partially-missing contour, refractive-bend silhouette, glass-lens warp, suspended-garment shape',
      color_palette:
        'Background, environment-match, refractive-rainbow fringe, glass-blue edge, transparency-neutral, reveal-flesh',
      lighting_setup:
        'Refraction, lens-warp caustics, glass-bend highlights, environmental-pass light, chromatic-shift edge',
      material_texture:
        'Glass-like, lens-distortion surface, heat-shimmer wave, refractive-prism, liquid-crystal, adaptive-camo',
      render_quality: 'Magic, stealth, optical-illusion wonder, wizard-cloak mystery',
      spatial_distortion: 'Missing parts',
      atmosphere:
        'Hidden, magic, disappearing-presence wonder, see-but-not-see mystique, veil-between-worlds poetry',
      key_features:
        'Distortion, bend-light edge, partial reveal, environment-through-body, glass-warp seam',
    },
  },
  {
    id: 'SP08-064',
    name: 'Burlap/Rags',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'silk, clean',
    style: {
      aesthetic: 'Peasant clothes, medieval-field humility, honest-labor simplicity',
      form_and_line:
        'Loose weave, tunic-length drape, rope-belt cinch, hood-cowl silhouette, gathered-neckline ease',
      color_palette: 'Brown, Grey, undyed-flax, mud, oatmeal, ash, weathered-hemp',
      lighting_setup: 'Flat, overcast-field light, cottage-window dimness, hearth-fire amber',
      material_texture:
        'Rough fiber, burlap jute, coarse hemp, hand-woven linen, homespun wool, frayed-edge cotton, rope cord',
      render_quality: 'Poor, scratchy, honest-poverty texture, feudal-era authenticity',
      spatial_distortion: 'Holes',
      atmosphere:
        'Sad, poverty, humble-endurance dignity, harvest-field weariness, simple-life resilience',
      key_features: 'Fraying, rope belt, rough patches, raw hem, homespun texture',
    },
  },
  {
    id: 'SP08-061',
    name: 'Lace',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'solid',
    style: {
      aesthetic: 'Wedding dress detail, heirloom-textile romance, cathedral-veil delicacy',
      form_and_line:
        'Intricate web, Alencon-pattern spread, scalloped-edge hem, illusion-neckline line, chapel-train sweep',
      color_palette: 'White, Black, ivory, candlelight, champagne, jet, nude-illusion',
      lighting_setup:
        'Backlit, window-light diffusion, veil-glow translucency, chapel-candle warmth, morning-light ethereality',
      material_texture:
        'Holes, thread, Chantilly lace, Alencon needlepoint, guipure relief, tulle ground, silk organza appliqué, re-embroidered motifs',
      render_quality: 'Delicate, detailed, lacemaker-artisan precision, bridal-couture heritage',
      spatial_distortion: 'None',
      atmosphere:
        'Romantic, fragile, heirloom-promise tenderness, veil-lift anticipation, cathedral-hush beauty',
      key_features:
        'Pattern, floral motif, scalloped edge, illusion neckline, hand-embroidered detail',
    },
  },
  {
    id: 'SP08-054',
    name: 'Chainmail',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'cloth',
    style: {
      aesthetic: 'Armor mesh, medieval-smithy craft, interlocked-defense beauty',
      form_and_line:
        'Tiny rings, butted-ring grid, riveted-flat drape, hauberk-length column, coif-hood circumference',
      color_palette:
        'Silver, steel-grey, polished-iron, oiled-black, bronze-ring, galvanized-sheen',
      lighting_setup:
        'Sparkle, forge-fire warmth, ring-reflection glint, torch-lit corridor, overcast-daylight evenness',
      material_texture:
        'Metal rings, riveted steel links, butted-iron rings, oiled-mail, brass-trim rings, leather-backing strap',
      render_quality: 'Detailed, heavy, forge-craft authenticity, ring-by-ring precision',
      spatial_distortion: 'None',
      atmosphere:
        'Protective, historic, castle-garrison readiness, crusade-road weariness, anvil-song pride',
      key_features: 'Mesh pattern, ring grid, coif hood, riveted links, mail curtain',
    },
  },
  {
    id: 'SP08-055',
    name: 'Knitted Wool',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'smooth',
    style: {
      aesthetic: 'Chunky sweater, hygge-comfort warmth, Nordic-cabin coziness',
      form_and_line:
        'Cable knit pattern, oversized-sweater volume, drop-shoulder ease, ribbed-cuff taper, turtleneck cylinder',
      color_palette: 'Cream, Grey, oatmeal, charcoal, forest, mustard, rust, undyed-wool ivory',
      lighting_setup:
        'Soft, window-light overcast, fireplace-warm amber, candle-flicker glow, afternoon-knit session',
      material_texture:
        'Wool yarn, merino twist, alpaca halo, cashmere fuzz, Shetland wool, lambswool loft, cable-knit relief',
      render_quality: 'Cozy, warm, cabin-retreat comfort, Aran-island authenticity',
      spatial_distortion: 'None',
      atmosphere:
        'Comfortable, winter, fireside-contentment, cocoa-and-wool warmth, snowed-in serenity',
      key_features: 'Knit loops, cable braid, ribbed hem, wooden buttons, rolled neck',
    },
  },
  {
    id: 'SP08-060',
    name: 'Velvet',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'shiny, hard',
    style: {
      aesthetic: 'Evening jacket, after-dark luxury, candlelit-sophistication',
      form_and_line:
        'Soft highlights, shawl-collar wrap, smoking-jacket taper, jacquard-relief silhouette, silk-faced lapel roll',
      color_palette: 'Deep Blue, Burgundy, midnight, amethyst, forest, oxblood, cognac',
      lighting_setup:
        'Soft edge glow, candle-halo warmth, chandelier-dimmer ambiance, piano-bar amber',
      material_texture:
        'Plush velvet pile, crushed velvet, silk-velvet devoré, jacquard weave, satin-faced lapel, grosgrain trim',
      render_quality: 'Rich, soft, smoking-room luxury, velvet-pile depth',
      spatial_distortion: 'None',
      atmosphere:
        'Luxury, night, after-hours refinement, aged-whiskey warmth, private-club exclusivity',
      key_features: 'Soft sheen, pile-direction gleam, satin lapel, jacquard pattern, frog closure',
    },
  },
  {
    id: 'SP08-065',
    name: 'Neon Light Suit',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'dark',
    style: {
      aesthetic:
        'Tron light-grid bodysuit, identity-disc glow, digital frontier, Grid-terminal icon',
      form_and_line:
        'Glowing lines, hex-circuit geometry, body-con compression, disc-mount backplate, luminescent-stripe contour',
      color_palette:
        'Black + Cyan, grid-blue, identity-disc white, amber-iso, CLU-orange, deep-circuit black',
      lighting_setup:
        'Self-illuminated, emissive-glow bloom, dark-grid contrast, disc-edge rim light, neon-floor reflection',
      material_texture:
        'Light, electroluminescent panel, matte neoprene, polycarbonate disc, luminous-flex circuit, silicone grip',
      render_quality: 'Sci-fi, digital, Flynn-lives luminescence, light-cycle precision',
      spatial_distortion: 'None',
      atmosphere:
        'Future, tech, Grid-frontier freedom, data-stream electricity, user-vs-program drama',
      key_features: 'Glow, identity disc, circuit-line grid, illuminated piping, dark-helmet visor',
    },
  },
  {
    id: 'SP08-066',
    name: 'Origami Paper',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'fabric',
    style: {
      aesthetic: 'Paper dress, washi-sculpture fragility, geometric-origami couture',
      form_and_line:
        'Sharp folds, mountain-valley crease, triangular-panel construction, accordion-pleat compression, angular-bodice geometry',
      color_palette:
        'White paper, rice-paper cream, kraft-brown, washi-natural, metallic-gold foil, indigo-dyed edge',
      lighting_setup:
        'Hard shadows, raking-side light, graphic-crease contrast, gallery-spot precision, shadow-cast drama',
      material_texture:
        'Paper grain, washi fiber, mulberry texture, crisp-kraft, embossed pattern, delicate-tear edge',
      render_quality: 'Artistic, fragile, Issey-Miyake-pleat poetry, paper-sculpture wonder',
      spatial_distortion: 'Rigid',
      atmosphere:
        'Creative, stiff, museum-gallery hush, delicate-construction tension, ephemeral-material poetry',
      key_features: 'Folds, crisp crease lines, paper edges, origami geometry, tear-away reveal',
    },
  },
  {
    id: 'SP08-068',
    name: 'Smoke Dress',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'solid',
    style: {
      aesthetic: 'Dress made of smoke, evanescent-form poetry, vapor-sculpture impossibility',
      form_and_line:
        'Swirling, billow-plume volume, tendril-curl silhouette, dissipating-edge softness, columnar-rising column',
      color_palette:
        'Grey, White, charcoal-wisp, pearl-haze, silver-smoke, blue-grey, ethereal-mist',
      lighting_setup:
        'Volumetric, god-ray penetration, smoke-halo backlight, theatrical-haze ambiance, laser-shaft definition',
      material_texture:
        'Gas, particulate-suspension wisp, layered-veil translucency, turbulent-curl, still-stratum band, wisp-edge diffusion',
      render_quality: 'Ethereal, impossible, volumetric-light poetry, ghost-presence majesty',
      spatial_distortion: 'Dissolving',
      atmosphere:
        'Ghostly, magic, fading-presence melancholy, incense-ritual mystery, phantasm-elegance',
      key_features:
        'No edges, wisp boundary, volume-without-surface, light-through-form, tendril dissolution',
    },
  },
  {
    id: 'SP08-071',
    name: 'Porcelain Doll',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'skin',
    style: {
      aesthetic: 'Living doll, uncanny-valley porcelain, toy-cabinet nightmare',
      form_and_line:
        'Cracks (optional), ball-joint articulation, bisque-head proportion, glass-eye stare, hinged-limb segmentation',
      color_palette:
        'Pale White, Pink, bisque, rose-blush, glass-blue iris, crackle-gold, doll-flesh cream',
      lighting_setup:
        'Glossy, display-cabinet spot, porcelain-reflection highlights, window-ledge daylight, toy-room dimness',
      material_texture:
        'Ceramic bisque, high-fire glaze, glass eyes, mohair wig, kid-leather body, painted-blush, crackle-kintsugi',
      render_quality: 'Creepy, perfect, dollmaker-artisan precision, cabinet-photograph stillness',
      spatial_distortion: 'Joints',
      atmosphere:
        'Uncanny, stiff, toy-room-after-dark unease, porcelain-fragility tension, glass-stare mystery',
      key_features: 'Shiny skin, glass eyes, ball joints, painted cheeks, mohair wig',
    },
  },
  {
    id: 'SP08-076',
    name: 'Slime/Goo',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'dry',
    style: {
      aesthetic: 'Covered in slime, toxic-spill horror, ectoplasmic-goo body',
      form_and_line:
        'Drips, gravity-pull tendrils, sagging-weight deformation, viscosity-drape silhouette, drip-trail elongation',
      color_palette:
        'Neon Green, toxic-slime, chartreuse, radioactive-amber, bioluminescent-blue, nuclear-waste, sickly-yellow',
      lighting_setup:
        'Glossy, wet-look specular, blacklight-UV fluorescence, under-shelf neon, lab-emergency flicker',
      material_texture:
        'Viscous, methylcellulose slime, gel-thickness body, stringy-elastic drip, gelatinous-surface, bubble-suspension',
      render_quality: 'Gross, sci-fi, Ghostbusters-ectoplasm goo, lab-accident horror',
      spatial_distortion: 'Melting',
      atmosphere: 'Weird, sticky, containment-breach disgust, slime-pit dread, oozing-drip tension',
      key_features:
        'Drips, stringy tendrils, bubble suspension, wet-gloss surface, gravity-sag form',
    },
  },
  {
    id: 'SP08-078',
    name: 'Hologram',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'solid',
    style: {
      aesthetic:
        'Star Wars monochrome sci-fi hologram, help-me-Obi-Wan shimmer, rebel-transmission urgency',
      form_and_line:
        'Scanlines, horizontal-interlaced banding, ghost-flicker edge, translucent-body silhouette, projection-cone taper',
      color_palette:
        'Blue monochrome, R2-D2-cyan, hologram-azure, transmission-static white, fade-to-transparent edge, flicker-blue',
      lighting_setup:
        'Self-lit, emissive-blue glow, projection-cone light, dark-room contrast, flicker-instability pulse',
      material_texture:
        'Light interference, scanline-grid pattern, signal-degradation static, transparency-fade, projection-grain, chromatic-fringe',
      render_quality: 'Sci-fi, glitchy, stolen-plans urgency, long-time-ago transmission',
      spatial_distortion: 'Transparent',
      atmosphere:
        'Tech, message, desperate-plea intimacy, rebel-hope transmission, galaxy-far-away nostalgia',
      key_features:
        'Scanlines, blue monochrome, flicker instability, transparent body, projection base',
    },
  },
  {
    id: 'SP08-080',
    name: 'Shadow Form',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'light',
    style: {
      aesthetic: 'Made of shadow, void-walker mystery, darkness-incarnate form',
      form_and_line:
        'Blurry, undefined-edge silhouette, smoke-like boundary, absence-contour, negative-space shape',
      color_palette: 'Black, void, abyss, pitch, ink, unlit, dark-matter',
      lighting_setup:
        'None, light-absence void, negative-fill darkness, silhouette-against-light, rim-light-only edge',
      material_texture:
        'Darkness, light-absorbent void, shadow-cast density, absence-of-matter, velvety-black, depth-without-surface',
      render_quality: 'Scary, void, light-swallowing menace, heart-of-darkness poetry',
      spatial_distortion: 'Silhouette',
      atmosphere:
        'Evil, mystery, primeval-darkness dread, unnamed-fear stillness, shadow-realm silence',
      key_features:
        'No details, featureless void, light-absorbing depth, negative shape, silhouette-only form',
    },
  },
  {
    id: 'SP08-058',
    name: 'Sequins',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'matte',
    style: {
      aesthetic: 'Disco dress, mirror-ball fantasy, floor-filler magnetism',
      form_and_line:
        'Sparkles, sequin-grid drrape, bodycon column, keyhole-back cutout, fringe-hem shake',
      color_palette: 'Silver, Gold, rose-gold, holographic, champagne, disco-ball prism, copper',
      lighting_setup:
        'Glittering, disco-ball fragment light, dancefloor-spot sparkle, colored-gel shimmer, strobe-pulse refraction',
      material_texture:
        'Small discs, holographic sequins, bugle-bead fringe, mirror-tile paillettes, crystal mesh, metallic thread',
      render_quality: 'Flashy, bright, dancefloor-electric energy, mirror-ball perfection',
      spatial_distortion: 'None',
      atmosphere:
        "Party, attention, all-eyes-on-you magnetism, floor-filler confidence, New-Year's-Eve electricity",
      key_features: 'Sparkle, sequin grid, holographic shift, fringe movement, mirror-tile gleam',
    },
  },
  {
    id: 'SP08-063',
    name: 'Feathers',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'fur, hair',
    style: {
      aesthetic: 'Showgirl costume, Folies-Bergere extravagance, stage-spectacle plumage',
      form_and_line:
        'Soft barbs, feather-fan spread, headdress-arc corona, tail-train sweep, wing-cape silhouette',
      color_palette:
        'Bright, Peacock, fuchsia, emerald-green, sapphire, gold, flamingo-pink, iridescent-oil',
      lighting_setup:
        'Soft, stage-spotlight drama, feather-edge translucency, backstage-bulb warmth, curtain-call glow',
      material_texture:
        'Ostrich feather, marabou fluff, peacock eye, coque plume, pheasant barb, downy base, dyed hackle',
      render_quality: 'Exotic, soft, cabaret-spectacle grandeur, Moulin-Rouge opulence',
      spatial_distortion: 'None',
      atmosphere:
        'Grand, bird, stage-curtain anticipation, plumage-pride majesty, feathered-flight fantasy',
      key_features: 'Quills, feather fan, headdress, marabou trim, iridescent barb',
    },
  },
  {
    id: 'SP08-067',
    name: 'Bubble Wrap',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'fabric',
    style: {
      aesthetic: 'Plastic fashion, pop-art materialism, bubble-texture absurdity',
      form_and_line:
        'Circles, bubble-sphere cluster volume, inflatable-cushion silhouette, rounded-bodice geometry, air-filled dimension',
      color_palette:
        'Clear plastic, optic-clear, tinted-rose, sky-blue, translucent-mint, iridescent-oil, milky-white',
      lighting_setup:
        'Highlights, point-reflection catchlights, studio-softbox pop, plastic-sheen bounce, gallery-overhead',
      material_texture:
        'Plastic bubbles, polyethylene film, air-cushion texture, poppable-dome surface, crinkle-film, heat-sealed seam',
      render_quality: 'Weird, pop art, Warhol-factory irreverence, inflated-sculpture playfulness',
      spatial_distortion: 'Bulky',
      atmosphere:
        'Fun, strange, childlike-wonder whimsy, packaging-material poetry, pop-culture satire',
      key_features:
        'Bubbles, air-filled domes, crinkle texture, heat-sealed grid, translucent layers',
    },
  },
  {
    id: 'SP08-070',
    name: 'Fire Dress',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'cold',
    style: {
      aesthetic:
        'Hunger Games ceremonial flame couture, Capitol excess, girl-on-fire moment, tribute-parade spectacle',
      form_and_line:
        'Flames, flicker-tongue silhouette, cape-sweep conflagration, rising-heat verticality, ember-trail train',
      color_palette:
        'Orange, Yellow, crimson-core, gold-white heat, sapphire-blue base, ember-red edge, coal-black ground',
      lighting_setup:
        'Self-illuminated, flame-glow bloom, incandescent-body light, smoke-haze diffraction, ember-spark scatter',
      material_texture:
        'Fire, flame-sheet fabric, synthetic-ember fiber, smoke-veil char, heat-shimmer distortion, LED-programmable textile',
      render_quality: 'Dangerous, hot, Cinna-design spectacle, Capitol-television perfection',
      spatial_distortion: 'Burning',
      atmosphere:
        'Powerful, magic, arena-entrance electricity, revolutionary-symbol awe, controlled-combustion beauty',
      key_features: 'Flames, cape ignition, ember trail, heat shimmer, synthetic flame effect',
    },
  },
  {
    id: 'SP08-075',
    name: 'Gold Leaf',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'dull',
    style: {
      aesthetic: 'Covered in gold, gilded-divinity fantasy, living-statue opulence',
      form_and_line:
        'Flakes, body-conforming foil, gilded-contour highlight, seamless-metallic shell, layered-leaf overlap',
      color_palette:
        'Metallic Gold, 24k-yellow, rose-gold, white-gold, champagne-foil, burnished-bronze, copper-patina',
      lighting_setup:
        'Reflection, rim-light gold-bounce, warm-specular highlights, gallery-spot gleam, candlelight-warmth reflection',
      material_texture:
        "Metal foil, gold leaf, composition-gold sheet, gilder's-clay base, burnished-surface, mica-flake, gold-dust",
      render_quality: 'Expensive, statue, Klimt-gold luxuriance, gilded-age opulence',
      spatial_distortion: 'None',
      atmosphere:
        'Divine, rich, alchemical-wonder awe, temple-treasure sanctity, immortal-beauty stillness',
      key_features: 'Gold skin, leafing seams, burnished reflection, flake edges, gilded contour',
    },
  },
  {
    id: 'SP08-069',
    name: 'Water Dress',
    category: '4. Fabric & Texture Focus',
    negativePrompt: 'dry',
    style: {
      aesthetic: 'Dress made of water, liquid-sculpture illusion, elemental-body transformation',
      form_and_line:
        'Splashes, cascade-fall drape, droplet-spray volume, surface-tension curve, sheet-flow silhouette, rippling-hem line',
      color_palette:
        'Clear Blue, aquamarine, crystal-clear, deep-ocean, turquoise, glacier-blue, refractive-white',
      lighting_setup:
        'Refraction, caustic-light dapple, underwater-beam shafts, rim-light sparkle, pool-reflection bounce',
      material_texture:
        'Liquid, surface-tension skin, splash-droplet dispersion, flow-sheet film, waterfall-veil, meniscus-edge curvature',
      render_quality: 'Magical, fluid, hydro-sculpture wonder, elemental-transformation poetry',
      spatial_distortion: 'Flowing',
      atmosphere:
        'Pure, fantasy, ocean-spirit serenity, water-nymph magic, dissolving-identity mystique',
      key_features:
        'Droplets, splash arrest, surface tension, liquid-sheet transparency, flow lines',
    },
  },
] as unknown as StylePresetDef[];
