// Generated by scripts/generate-style-runtime-data.ts.
// Edit Style Preset Manifests, then run `bun run styles:runtime`.
import type { StyleRuntimePreset } from '../../styles/runtimeTypes';

export const GENERATED_STYLE_PRESETS = [
  {
    id: 'SP08-040',
    name: 'Space Suit (Retro)',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'modern sleek',
    style: {
      aesthetic: 'Apollo-era retro space suit, one-small-step romance, Cape-Canaveral optimism',
      form_and_line:
        'Bulky suit, pressurized-ring segmentation, hose-connector geometry, glove-gasket bulk, backpack-box volume',
      color_palette:
        'White, silver, American-flag accent, visor-gold, beta-cloth cream, mission-patch color',
      lighting_setup:
        'Harsh vacuum-like key light, unfiltered-solar glare, helmet-interior bounce, gold-visor reflection',
      material_texture:
        'Beta cloth, gold-film visor, rubber gaskets, aluminum connectors, nylon webbing, Velcro patches',
      render_quality: 'Historic, tech, NASA-archive authenticity, vacuum-silence clarity',
      spatial_distortion: 'None',
      atmosphere:
        'Heroic, exploration, mission-control suspense, giant-leap awe, archival optimism',
      key_features: 'Bubble helmet, gold visor, mission patch, umbilical hoses, moon boots',
      creative_brief:
        'Translate the input into retro EVA suit language: beta cloth, bubble helmet, gold visor, rubber gaskets, umbilical hoses, aluminum rings and mission-patch color. Keep Apollo optimism and vacuum clarity without requiring a lunar surface, astronaut hero pose or NASA archive reenactment.',
    },
  },
  {
    id: 'SP08-015',
    name: 'Cosplay Anime',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'realistic clothes, dull',
    style: {
      aesthetic:
        'High quality cosplay construction, character-faithful transformation, anime-costume spectacle',
      form_and_line:
        'Silhouette-matched precision, exaggerated anime proportions, prop-scale geometry',
      color_palette:
        'Bright synthetic colors, candy-neon saturation, cell-shaded contrast, vibrant cel hues',
      lighting_setup:
        'Studio craft lighting, three-point rig, colored gel accents, anime-style rim',
      material_texture:
        'Heat-resistant wig fiber, EVA foam armor with Worbla overlay, thermoplastic detailing, holographic spandex',
      render_quality: 'Fan art, detailed, fun, craftsmanship pride, competition-grade finish',
      spatial_distortion: 'Big props',
      atmosphere:
        'Playful, character, fake, joyful transformation, fandom devotion, handmade spectacle',
      key_features: 'Wig texture, styled fiber sheen, armor seam lines, prop replica detail',
      creative_brief:
        'Convert the input into cosplay craft language: styled synthetic fiber, EVA/Worbla armor seams, thermoplastic props, holographic spandex and silhouette-matched anime exaggeration. Preserve character-faithful cues without forcing a convention hall, named character, replica pose or photo booth scene.',
    },
  },
  {
    id: 'SP08-013',
    name: 'Ethereal Fantasy',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'heavy, dark, solid',
    style: {
      aesthetic: 'Elven or fairy couture, Rivendell ethereality, woodland-realm grace',
      form_and_line:
        'Flowing, windblown, gossamer waterfall silhouette, bishop-sleeve billow, empire-line rise',
      color_palette:
        'White, Silver, Pale Blue, moonstone, starlight silver, celadon mist, pearl essence',
      lighting_setup: 'Glowing, backlight, god-ray shafts, moonbeam dapple, faerie-light sparkle',
      material_texture:
        'Silk chiffon, gossamer organza, liquid satin charmeuse, silver lamé thread, dew-beaded tulle',
      render_quality:
        'Lord of the Rings epic fantasy, magical, elven grace, Middle-earth majesty, artisan-fantasy caliber',
      spatial_distortion: 'Floating fabric',
      atmosphere:
        'Magical, soft, dreamlike, ancient enchantment, starlit serenity, undying-lands longing',
      key_features:
        'Translucency, flowing sleeves, circlet or brooch cues, silver-thread constellation detail',
      creative_brief:
        'Apply elven ethereality to the input through gossamer translucency, moonstone thread, floating sleeves and a palette of pearl, celadon and pale blue. Keep circlet or brooch cues when useful, but avoid locking the image to a forest realm, harp-lit figure or fixed fantasy gown scene.',
    },
  },
  {
    id: 'SP08-009',
    name: 'Steampunk Inventor',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'modern, plastic, digital',
    style: {
      aesthetic:
        'Victorian sci-fi costume, Jules Verne expedition cues, clockwork inventor regalia',
      form_and_line:
        'Gears, goggles, corsets, pocket-watch chains, top-hat elongation, bustle-back volume',
      color_palette:
        'Bronze, Brown Leather, Copper, brass patina, burnished mahogany, verdigris green',
      lighting_setup: 'Sepia tone, steam-softened gaslight warmth, amber glow, brass reflection',
      material_texture:
        'Full-grain leather, engraved brass, Harris tweed, clockwork gears, riveted copper, pocket-watch crystal',
      render_quality:
        'Detailed, costume, fantasy, cogs-and-corsets craftsmanship, retro-futurist opulence',
      spatial_distortion: 'Mechanical limbs (optional)',
      atmosphere:
        'Adventurous, retro, inventive, clockwork wonder, airship-era ambition, tea-and-tinker curiosity',
      key_features: 'Brass accessories, aviator goggles, gear-motif jewelry, leather tool belt',
      creative_brief:
        'Translate any input into steampunk costume engineering: brass constellations, tinted goggles, leather tool-belt logic, corset or waistcoat structure, clockwork ornament and sepia gaslight. Keep mechanical-limb hints optional and useful, but do not force an aviator, workshop, hangar or adventure scene.',
    },
  },
  {
    id: 'SP08-006',
    name: 'Cyberpunk Techwear',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'vintage, natural, soft',
    style: {
      aesthetic:
        'Cyberpunk technical utility, stealth modular operator cues, rain-slicked futurewear',
      form_and_line:
        'Straps, buckles, pockets, articulated knee darts, webbing harness geometry, asymmetrical zip lines',
      color_palette:
        'Matte Black, Dark Grey, charcoal shadow, stealth anthracite, muted olive-black',
      lighting_setup:
        'Neon edge spill, wet-surface reflections, sodium-vapor amber, holographic accent light',
      material_texture:
        'Waterproof technical fabric, Gore-Tex Pro, Dyneema composite, laser-cut nylon, bonded seam tape',
      render_quality:
        'Acronym technical utility, dystopian, functional, Errolson Hugh silence, shadow-ops precision',
      spatial_distortion: 'Optional masked or hooded identity cues',
      atmosphere:
        'Dark, prepared, cool, anticipatory stillness, modular survival, surveillance-era restraint',
      key_features: 'Utility focus, MOLLE webbing, magnetic fidlock closures, articulated hood',
      creative_brief:
        'Mechanize the input through cyberpunk techwear: bonded seams, Dyneema panels, harness geometry, magnetic closures, hooded or masked cues and neon edge reflections. It may imply stealth operations, but must not require a city alley, mercenary scene, weapon, surveillance camera or fixed character role. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
  {
    id: 'SP08-079',
    name: 'Invisibility Cloak',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'visible',
    style: {
      aesthetic: 'Partially invisible, refraction-mirage wonder, stealth-magic concealment',
      form_and_line:
        'Distortion edge, partially-missing contour, refractive-bend silhouette, glass-lens warp, suspended-garment shape',
      color_palette:
        'Background-match, refractive-rainbow fringe, glass-blue edge, transparency-neutral, partial-reveal tones',
      lighting_setup:
        'Refraction, lens-warp caustics, glass-bend highlights, environmental-pass light, chromatic-shift edge',
      material_texture:
        'Glass-like, lens-distortion surface, heat-shimmer wave, refractive-prism, liquid-crystal, adaptive-camo',
      render_quality: 'Magic, stealth, optical-illusion wonder, wizard-cloak mystery',
      spatial_distortion: 'Missing parts',
      atmosphere:
        'Hidden, magic, disappearing-presence wonder, see-but-not-see mystique, veil-between-worlds poetry',
      key_features:
        'Distortion, bend-light edge, partial reveal, environment-through-body, glass-warp seam',
      creative_brief:
        'Apply invisibility-cloak optics to the input: refractive edge distortion, background-matching transparency, glass-blue seams, chromatic fringe and adaptive-camo shimmer. Preserve the disappearing-presence effect without forcing a body, hand reveal, wizard cloak scene or specific environment.',
    },
  },
  {
    id: 'SP08-065',
    name: 'Neon Light Suit',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'dark',
    style: {
      aesthetic:
        'Tron light-grid bodysuit, identity-disc glow, digital frontier, Grid-terminal icon',
      form_and_line:
        'Glowing lines, hex-circuit geometry, body-con compression, disc-mount backplate, luminescent-stripe contour',
      color_palette:
        'Black + Cyan, grid-blue, identity-disc white, amber-iso, CLU-orange, deep-circuit black',
      lighting_setup:
        'Self-illuminated, emissive-glow bloom, dark-grid contrast, disc-edge rim light',
      material_texture:
        'Light, electroluminescent panel, matte neoprene, polycarbonate disc, luminous-flex circuit, silicone grip',
      render_quality: 'Sci-fi, digital, Flynn-lives luminescence, light-cycle precision',
      spatial_distortion: 'None',
      atmosphere:
        'Future, tech, Grid-frontier freedom, data-stream electricity, programmatic drama',
      key_features: 'Glow, identity disc, circuit-line grid, illuminated piping, dark-helmet visor',
      creative_brief:
        'Convert the input into neon grid suiting: cyan circuit lines, matte neoprene, electroluminescent panels, identity-disc glow and black-cyan contrast. Keep Tron-like digital frontier energy while avoiding a required body, arena, light-cycle action or floor-grid scene.',
    },
  },
  {
    id: 'SP08-078',
    name: 'Hologram',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'solid',
    style: {
      aesthetic:
        'Monochrome sci-fi hologram, rebel-transmission shimmer, long-distance signal urgency',
      form_and_line:
        'Scanlines, horizontal-interlaced banding, ghost-flicker edge, translucent-body silhouette, projection-cone taper',
      color_palette:
        'Blue monochrome, R2-D2-cyan, hologram-azure, transmission-static white, fade-to-transparent edge, flicker-blue',
      lighting_setup:
        'Self-lit, emissive-blue glow, projection-cone light, dark-room contrast, flicker-instability pulse',
      material_texture:
        'Light interference, scanline-grid pattern, signal-degradation static, transparency-fade, projection-grain, chromatic-fringe',
      render_quality: 'Sci-fi, glitchy, stolen-plans urgency, long-time-ago transmission',
      spatial_distortion: 'Transparent',
      atmosphere:
        'Tech, message, desperate-plea intimacy, rebel-hope transmission, distant-signal nostalgia',
      key_features:
        'Scanlines, blue monochrome, flicker instability, transparent body, projection base',
      creative_brief:
        'Render the input as unstable holographic transmission: blue monochrome, scanlines, projection grain, transparency fade, chromatic fringe and flicker-loss at the edges. It can imply a message or figure, but must not require Star Wars staging, a projection base, dark room or pleading character. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
  {
    id: 'SP08-080',
    name: 'Shadow Form',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'light',
    style: {
      aesthetic: 'Made of shadow, void-walker mystery, darkness-incarnate form',
      form_and_line:
        'Blurry, undefined-edge silhouette, smoke-like boundary, absence-contour, negative-space shape',
      color_palette: 'Black, void, abyss, pitch, ink, unlit, dark-matter',
      lighting_setup:
        'None, light-absence void, negative-fill darkness, silhouette-against-light, rim-light-only edge',
      material_texture:
        'Darkness, light-absorbent void, shadow-cast density, absence-of-matter, velvety-black, depth-without-surface',
      render_quality: 'Scary, void, light-swallowing menace, heart-of-darkness poetry',
      spatial_distortion: 'Silhouette',
      atmosphere: 'Mystery, primeval-darkness dread, unnamed-fear stillness, shadow-realm silence',
      key_features:
        'No details, featureless void, light-absorbing depth, negative shape, silhouette-only form',
      creative_brief:
        'Transform the input into shadow-form materiality: light-absorbing void, velvety black depth, rim-only edge, undefined silhouette and absence as surface. Keep menace optional and atmospheric; do not require a humanoid figure, evil character, realm scene or literal standing pose.',
    },
  },
  {
    id: 'SP08-044',
    name: 'Wizard Robes',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'pants, modern',
    style: {
      aesthetic: 'Classic mage regalia, arcane scholar mystique, spellcraft textile language',
      form_and_line:
        'Flowing robes, bell-sleeve drape, hooded-cowl depth, floor-length column, pointed-hat apex',
      color_palette:
        'Deep Blue, Stars, burgundy, amethyst, midnight, silver-thread constellations, emerald',
      lighting_setup:
        'Magic glow, spell-light rim, candle-flicker ambiance, crystal-orb luminescence, staff-gem radiance',
      material_texture:
        'Velvet, silver-thread embroidery, astrological silk, crystal beads, aged leather, moonstone inlay',
      render_quality: 'Magical, wise, illuminated-manuscript wonder, arcane-academia gravitas',
      spatial_distortion: 'None',
      atmosphere:
        'Mysterious, powerful, forbidden-knowledge awe, incantation tension, arcane focus',
      key_features: 'Staff, pointed hat, spellbook, crystal pendant, rune-embroidered robe',
      creative_brief:
        'Give the input wizard-robe grammar: velvet depth, bell sleeves, hooded cowl, rune embroidery, moonstone inlay, spell-light rim and silver constellations. Staff, hat or spellbook cues may appear when useful, but the preset should not require a tower, library, sanctum or spellcasting scene. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
  {
    id: 'SP08-048',
    name: 'Zombie Survivor',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'clean',
    style: {
      aesthetic:
        'Walking Dead post-outbreak survivor wear, bite-mark paranoia, terminus-road desperation',
      form_and_line:
        'Dirty layers, scavenged-onion bulk, duct-tape reinforcement, wrapped-forearm binding, boot-cut pragmatism',
      color_palette: 'Grey, Blood stain, mud-brown, rust, faded-olive, dried-crimson, ash-grey',
      lighting_setup:
        'Gritty overcast grey, dust-haze shadow, emergency-orange rim, dirty practical light',
      material_texture:
        'Blood-crusted fabric, dirt-embedded denim, duct-tape patches, torn flannel, sweat-soaked cotton, leather holster wear',
      render_quality: 'Horror, survival, walker-apocalypse realism, exhaustion-verité',
      spatial_distortion: 'Wounds',
      atmosphere:
        'Scared, tough, constant-vigilance exhaustion, survival-instinct clarity, herd-approach dread',
      key_features:
        'Backpack, fingerless gloves, duct-tape patches, bite-protection layers, relic accessory cues',
      creative_brief:
        'Turn the input into post-outbreak survival wear: duct-taped denim, torn flannel, leather wear, mud, dried crimson stains, bite-protection wraps and exhausted layering. It may imply zombie danger, but should not require a weapon, sheriff hat, forest, abandoned building or survivor portrait. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
  {
    id: 'SP08-043',
    name: 'Space Opera Royal',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'simple, earth',
    style: {
      aesthetic: 'Padme Amidala operatic space-court couture, Naboo regality, senatorial authority',
      form_and_line:
        'Elaborate headpiece, issei-crown halo, gown-train sweep, corset-waist architecture, bell-sleeve drama',
      color_palette:
        'Red, Gold, Alien, crimson, electrum, pearl, plasma-pink, Naboo-teal, midnight-velvet',
      lighting_setup: 'Dramatic ceremonial glow, stained-glass fantasy light, diplomatic backlight',
      material_texture:
        'Exotic fabric, iridescent organza, feather-trim, beaded net, liquid-metal threads, luminescent silk',
      render_quality: 'Regal, alien, galactic-court opulence, Coruscant-high-fashion',
      spatial_distortion: 'Strange hair',
      atmosphere:
        'Serious, political, galactic-court gravity, doomed-romance elegance, diplomatic tension',
      key_features:
        'Face-paint cues, issei headpiece, ceremonial gown architecture, feathered cape',
      creative_brief:
        'Turn the input into galactic-court couture: issei halo geometry, alien headpiece logic, liquid-metal thread, feather trim, ceremonial face-paint cues and diplomatic crimson-gold gravity. Keep Padme/Naboo regality as style anchor without requiring a throne room, senate chamber, twin suns or specific royal figure.',
    },
  },
  {
    id: 'SP08-045',
    name: 'Superhero Spandex',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'loose clothes',
    style: {
      aesthetic: 'Comic book hero, four-color idealism, panel-breaking dynamism',
      form_and_line:
        'Muscle-sculpt silhouette, cape-sweep drama, boot-cut taper, emblem-centered geometry',
      color_palette: 'Primary Colors, flag-blue, signal-red, gold-yellow, ink-black, optic-white',
      lighting_setup: 'Rim light, heroic edge-highlight, two-source dramatic, comic-ink contrast',
      material_texture:
        'Matte spandex, dimensional-print muscle shading, vinyl cape, rubber sole, metallic accents',
      render_quality: 'Heroic, bold, splash-page energy, Kirby-esque power',
      spatial_distortion: 'Muscles',
      atmosphere:
        'Strong, brave, truth-and-justice clarity, splash-page dynamism, unwavering resolve',
      key_features: 'Logo on chest, cape, utility belt, domino mask, heroic boots',
      creative_brief:
        'Recast the input in superhero costume language: matte spandex, emblem-first chest geometry, cape sweep, utility belt, heroic boots and four-color ink contrast. Preserve aspirational anatomy cues when useful, but do not force a human hero, action pose, city rescue or fixed comic panel. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
  {
    id: 'SP08-050',
    name: 'Alien Fashion',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'human clothes',
    style: {
      aesthetic:
        'Fifth Element bold alien runway costuming, Jean-Paul Gaultier sci-fi, interstellar-couture rebellion',
      form_and_line:
        'Strange cutouts, geometric-negative-space, body-harness wrapping, asymmetrical neckline, tab-constructed sleeves',
      color_palette:
        'Orange, Plastic, optic-white, safety-yellow, chrome, rubber-black, sky-blue, metallic-mint',
      lighting_setup:
        'Bright sci-fi editorial glow, chrome-reflection bounce, sterile overhead, neon-advertisement spill',
      material_texture:
        'Orange rubber, clear plastic, chrome vinyl, white elastic webbing, molded neoprene, holographic PVC',
      render_quality: 'Weird, futuristic, Gaultier-costume genius, space-opera runway spectacle',
      spatial_distortion: 'None',
      atmosphere:
        'Alien, fashion, zero-g couture attitude, cosmic glamour, rebellious artificiality',
      key_features: 'Straps, body harness, cutout geometry, contrast stitching, utility ring',
      creative_brief:
        'Make the input feel designed by non-human couture logic: orange rubber, clear plastic, chrome vinyl, body-harness wrapping, strange cutouts, tab-built sleeves and utility rings. Keep the Gaultier/Fifth Element rebellion without requiring a space terminal, alien body, lab or runway.',
    },
  },
  {
    id: 'SP08-042',
    name: 'Post-Apocalyptic Scavenger',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'clean, new',
    style: {
      aesthetic:
        'Mad Max wasteland survivor gear, guzzoline grit, Fury Road desperation, chrome-sprayed myth',
      form_and_line:
        'Rags, armor, scavenged-layer chaos, shoulder-pad bulk, wrapped-limb binding, improvised asymmetry',
      color_palette:
        'Dust, Brown, Rust, sun-bleached tan, oxidized copper, blood-rust, war-boy white, desert-ochre',
      lighting_setup:
        'Desert sun, heat-shimmer distortion, dust-storm diffusion, engine-fire orange, post-blast haze',
      material_texture:
        'Dirty canvas, torn leather, salvaged tire rubber, rusty chain, car-part armor, gauze wraps, weathered denim',
      render_quality: 'Survival, gritty, post-apocalypse vérité, guzzoline-desperation rawness',
      spatial_distortion: 'None',
      atmosphere:
        'Desperate, tough, resource-scarcity tension, wasteland-wind solitude, witness-me ferocity',
      key_features: 'Goggles, shoulder pad, bandolier, gas-mask, improvised armor cues',
      creative_brief:
        'Render the input as scavenged survival couture: dirty canvas, tire rubber, rusty chain, car-part armor, gauze wraps, oxidized metal and dust-choked layering. Keep Mad Max resource-scarcity ferocity without requiring a wasteland chase, weapon, survivor portrait or specific desert scene.',
    },
  },
  {
    id: 'SP08-047',
    name: 'Vampire Lord',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'modern, messy',
    style: {
      aesthetic: 'Dracula style, Carpathian aristocracy, immortal-danger elegance',
      form_and_line:
        'High collar, cape-volume sweep, tailcoat-waist taper, cravat-neck precision, ring-adorned fingers',
      color_palette: 'Black, Red lining, blood-crimson, ivory, silver, deep burgundy, moon-white',
      lighting_setup:
        'Moonlight silver rim, candelabra flicker, fog-diffused ambiance, stained-glass dimness',
      material_texture:
        'Velvet, silk satin lining, brocade vest, starched wing collar, onyx ring, opera cape wool',
      render_quality: 'Gothic, scary, Stoker-novel atmosphere, Hammer-horror elegance',
      spatial_distortion: 'None',
      atmosphere:
        'Evil, elegant, ancient-hunger menace, moonlit-seduction danger, aristocratic dread',
      key_features: 'Opera cape, high collar, medallion, signet ring, crimson lining',
      creative_brief:
        "Style the input as vampire aristocratic costume: black velvet cape, crimson silk lining, high collar, cravat precision, onyx signet and moonlit silver edge. Keep immortal menace and old-world elegance without requiring a castle, specific face, widow's peak or literal Dracula portrait.",
    },
  },
  {
    id: 'SP08-046',
    name: 'Mech Pilot Suit',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'casual',
    style: {
      aesthetic:
        'Evangelion sleek biomech pilot suit, NERV interface, sync-ratio shine, plug-depth tension',
      form_and_line:
        'Panel lines, entry-plug contour, form-fitting compression, shoulder-interface cutout, neck-seal band',
      color_palette:
        'Glossy White/Red, EVA-purple, NERV orange, Unit-01 violet, caution-yellow, matte-black',
      lighting_setup:
        'LCL-amber immersion glow, display-screen backlight, entry-plug bioluminescence, sync-alert rim',
      material_texture:
        'Latex, plastic, neoprene compression, interface gel, carbon-fiber panel, memory-foam inner',
      render_quality: 'Anime, sci-fi, cel-shaded precision, mecha-pilot intimacy',
      spatial_distortion: 'None',
      atmosphere: 'Ready, tech, sync-ratio tension, AT-field silence, impact-alert urgency',
      key_features: 'Interface headset, A10 nerve clips, plug-suit panel lines, LCL fluid sheen',
      creative_brief:
        'Apply mecha-pilot interface design to the input: glossy plug-suit panel lines, compression seams, neck seals, A10 nerve-clip cues, LCL amber sheen and biomech synchronization signals. If a character is present, the style may make them feel linked to a giant machine; if not, leave clear mecha interface traces without requiring cockpit, hangar, launch tube or battle.',
    },
  },
  {
    id: 'SP08-041',
    name: 'Cybernetic Implant',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'fully human',
    style: {
      aesthetic: 'Cyborg fashion, transhuman evolution, chrome-and-flesh fusion',
      form_and_line:
        'Metal seams on skin, implant-ridge lines, carbon-fiber contour, prosthetic-limb silhouette',
      color_palette:
        'Skin + Chrome, titanium, graphite, bio-luminescent blue, carbon-black, circuit-gold',
      lighting_setup:
        'Studio, ring-light reflection, cold-lab overhead, LED-indicator glow, surgical-key sharpness',
      material_texture:
        'Brushed titanium, carbon-fiber weave, medical silicone, polycarbonate, bio-gel interface, anodized aluminum',
      render_quality: 'Sci-fi, body mod, Ghost-in-the-Shell precision, augment-realism clarity',
      spatial_distortion: 'Optional visible augmentation',
      atmosphere:
        'Transhuman, cool, augmentation-identity tension, clinical-aesthetic chill, future-body wonder',
      key_features:
        'Metal parts, seam-line integration, exposed circuitry, bionic eye, neural port',
      creative_brief:
        'Mechanize the input through cybernetic augmentation: titanium seams, carbon-fiber contour, medical silicone, bionic eye cues, neural ports and bio-luminescent circuit glow. Preserve transhuman body-mod tension while allowing non-human subjects to gain implant logic instead of forcing a portrait, lab scene or full robot arm. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
  {
    id: 'SP08-049',
    name: 'Mermaid Tail',
    category: '4. Fantasy Sci-Fi Costume',
    negativePrompt: 'legs',
    style: {
      aesthetic: 'Fantasy mermaid, deep-ocean enchantment, shipwreck-siren allure',
      form_and_line:
        'Scales, fishtail-flare silhouette, fin-ridge undulation, bandeau-top line, hair-float weightlessness',
      color_palette:
        'Iridescent Green, teal, abalone, moonlight-pearl, aquamarine, bioluminescent-blue, coral-pink',
      lighting_setup:
        'Underwater, caustic-light dapple, surface-sunbeam shafts, bioluminescent glow, reef-filtered turquoise',
      material_texture:
        'Iridescent scales, wet-look silicone, pearlescent finish, seaweed hair, shell texture, liquid organza',
      render_quality: 'Magical, mythical, lagoon-dream ethereality, siren-song enchantment',
      spatial_distortion: 'Fish tail',
      atmosphere: 'Beautiful, wet, deep-ocean mystery, coral-reef serenity, moon-tide magic',
      key_features:
        'Tail or fin cues, scale texture, pearlescent shell detail, liquid organza flow',
      creative_brief:
        'Give the input mermaid-costume transformation: iridescent scales, fin ridges, pearlescent shell detail, wet-look silicone, liquid organza and caustic turquoise light. It may convert a figure into a tail silhouette, but should not require shipwrecks, coral reef, underwater hair or a siren scene. Apply this fashion/costume grammar over any input: preserve textile behavior, silhouette logic, trims, material cues, and styling attitude while avoiding a required body, portrait, runway, room, prop, role, or fixed character scene.',
    },
  },
] as unknown as StyleRuntimePreset[];
