import type { Create, Spec } from '../tools/apply';
import { CRAFT_AVOID as AVOID, craft } from './_craft';

// Toys & crafts: each preset is one construction method. Brand names are replaced by generic
// descriptions; collectible proportion changes are stated in the preset that uses them.
const spec: Spec = {
  pack: 'pack_11',
  category: '1. Toys And Crafts',
  updates: {
    'SP11-001': {
      name: 'Interlocking Brick Build',
      dna: craft(
        'Interlocking brick build: the subject assembled from studded plastic building bricks.',
        'built from studded interlocking plastic bricks with visible studs, stepped curves and right-angle blocks.',
        'Primary brick colors: red, yellow, blue, grey, black.',
        'Bright studio light with plastic highlights.',
        'Glossy ABS bricks with studs and seams.',
        'Playful, constructive, nostalgic and bright.',
        'studded bricks; stepped curves; plastic gloss',
      ),
      avoid: AVOID,
      briefs: [
        'Tabletop photograph of a black-and-dark-red interlocking-brick dragon coiled around a crumbling grey brick watchtower, wings made of stepped plate pieces, translucent orange bricks for fire in its throat, studs catching the studio light. No logos or text.',
        'Interlocking-brick diorama of a torchlit dungeon crypt: a skeleton knight rising from a brick sarcophagus, translucent green bricks for ghost light, loose spare bricks scattered at the edge of the baseplate. No logos or text.',
        'Close macro photograph of a brick-built galleon listing in a sea of stacked blue and white bricks, torn sail made of flat tiles, a kraken tentacle built from curved slopes wrapping the mast. No logos or text.',
      ],
    },
    'SP11-002': {
      name: 'Big-Head Vinyl Collectible',
      dna: craft(
        'Big-head vinyl collectible: stylized figure with oversized square head, small body and blank black eyes.',
        'a vinyl figure with a huge head, tiny body and simplified features — a deliberate proportion change.',
        'Flat matte vinyl colors.',
        'Soft studio light.',
        'Matte vinyl with seam lines.',
        'Cute, collectible, simple and playful.',
        'oversized head; small body; blank eyes; matte vinyl',
      ),
      avoid: AVOID,
      briefs: [
        'Studio photograph of a big-head vinyl collectible of an original plague doctor: huge square head with a long beak mask, blank round black eyes, tiny body in a black coat, holding a lantern, standing on a shelf. No logos or text.',
        'Big-head vinyl collectible of an original undead queen with a cracked crown, grey-green matte skin, blank black eyes and a tiny body in a torn violet gown, photographed beside a plain unprinted window box. No logos or text.',
        'Row of three big-head vinyl collectibles on a desk: an original armored orc warlord, a hooded rogue and a horned demon cleric, all with oversized heads, tiny bodies and blank black eyes, factory seam lines visible. No logos or text.',
      ],
    },
    'SP11-003': {
      name: 'Modeling Dough Clay',
      dna: craft(
        'Modeling dough: soft bright dough rolled and pinched with fingerprints and cracks.',
        'hand-rolled soft modeling dough with fingerprints, pinched edges and small drying cracks.',
        'Bright dough colors.',
        'Soft diffuse light.',
        'Soft dough with fingerprints and cracks.',
        'Playful, childlike, soft and handmade.',
        'soft dough; fingerprints; drying cracks',
      ),
      avoid: AVOID,
      briefs: [
        'Tabletop photograph of a soft modeling-dough dragon with fingerprints pressed into its purple belly, pinched yellow wings, small drying cracks and a lopsided grin, perched on a dough treasure pile. No logos or text.',
        'Modeling-dough haunted graveyard on a kitchen table: lumpy grey tombstones, a green dough ghost with thumb-pressed eyes, a crooked orange pumpkin, crumbs and cutter tools around it. No logos or text.',
        "Close photograph of a modeling-dough knight losing a duel to a dough snail, the knight's helmet squashed flat, colors partly smeared together where small hands mixed them. No logos or text.",
      ],
    },
    'SP11-004': {
      dna: craft(
        'Papercraft low poly: folded paper model with flat faceted panels and glue tabs.',
        'folded paper facets with crisp creases and visible glue tabs.',
        'Printed flat paper colors.',
        'Soft side light showing facets.',
        'Paper facets, creases and tabs.',
        'Crafted, geometric, charming and light.',
        'folded paper facets; glue tabs',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a low-poly papercraft wolf howling on a desk under a lamp, grey faceted panels with sharp valley folds, glue tabs peeking from its belly, a cutting mat and scalpel beside it. No text or logo.',
        'Low-poly papercraft skull lantern made of black and bone-white faceted card, a tealight glowing through its hollow eye sockets, visible creases and slightly lifting glue tabs. No text or logo.',
        'Low-poly papercraft stag with enormous faceted antlers standing in a forest of folded paper pine trees, soft window light raking across every facet. No text or logo.',
      ],
    },
    'SP11-005': {
      dna: craft(
        'Amigurumi crochet: small crocheted stuffed figures with single-crochet stitches and safety eyes.',
        'crocheted in tight spiral stitches, stuffed, with safety eyes and sewn-on parts.',
        'Soft yarn colors.',
        'Soft natural light.',
        'Crochet stitches and yarn fuzz.',
        'Cute, cozy, handmade and gentle.',
        'crochet stitches; safety eyes; stuffed',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a crocheted amigurumi dragon in moss-green yarn with safety eyes, tiny felt wings sewn on slightly crooked, sitting inside a chipped teacup on a wooden table. No text or logo.',
        'Amigurumi crocheted lich in black and bone-colored yarn with a tiny stitched crown and yellow safety eyes, holding a crocheted skull staff, yarn fuzz glowing in soft side light. No text or logo.',
        'Family of crocheted amigurumi mushrooms with sleepy stitched faces around a crocheted toadstool house, visible spiral stitch rows and stuffing slightly showing at one seam. No text or logo.',
      ],
    },
    'SP11-016': {
      dna: craft(
        'Plushie: soft stuffed toy with fleece or minky fabric, seams and embroidered features.',
        'sewn from soft minky fabric panels, stuffed, with embroidered eyes and visible seams.',
        'Soft pastel or bright fabric.',
        'Soft light.',
        'Minky fleece, seams and embroidery.',
        'Cuddly, comforting, sweet and soft.',
        'minky fabric; seams; embroidered eyes',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a plush dragon in charcoal minky fabric with embroidered sleepy eyes and floppy felt wings, one seam slightly puckered, lying on a rumpled quilt in morning light. No text or logo.',
        'Soft plush grim reaper toy with a hooded black minky robe, an embroidered friendly skull face and a felt scythe, sitting on a bookshelf next to an unlit candle. No text or logo.',
        'Plush kraken in deep purple velboa with eight stuffed tentacles, embroidered curious eyes and satin suckers, sprawled over the edge of a bed. No text or logo.',
      ],
    },
    'SP11-017': {
      dna: craft(
        '90s action figure: hard plastic figure with visible joints, sculpted muscles and painted details.',
        'molded plastic with swivel joints at shoulders, hips and knees, sculpted detail and simple paint.',
        'Bold toy colors.',
        'Studio light with plastic sheen.',
        'Molded plastic, joints and paint apps.',
        'Heroic, nostalgic, toyetic and bold.',
        'swivel joints; sculpted plastic; paint apps',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a 90s-style action figure of an original barbarian warlord with sculpted muscles, visible swivel joints at shoulders and knees, simple paint apps, raising a molded axe on a rock-diorama base. No logos or text.',
        '90s-style action figure of an original skeleton king on a molded bone-throne playset, glow-in-the-dark green plastic eyes, visible hip and neck joints, slight paint rub on the crown. No logos or text.',
        'Two 90s-style action figures mid-battle on a bedroom carpet: an original lizard-man warrior and a knight with a spring-loaded sword, joints visible, lit like an old toy catalog photo. No logos or text.',
      ],
    },
    'SP11-018': {
      dna: craft(
        'Balloon art: the subject twisted from long modeling balloons.',
        'twisted from inflated modeling balloons with visible twists and knots.',
        'Glossy balloon colors.',
        'Bright light with glossy highlights.',
        'Latex balloons with twists.',
        'Playful, festive, silly and bright.',
        'twisted balloons; glossy latex',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a twisted balloon-art dragon in glossy green and orange modeling balloons, wings made of looped twists, knotted tail, on a party table with light glinting off the latex. No text or logo.',
        'Balloon-art knight riding a balloon horse, silver and black twisted balloons for armor, a long red balloon lance, one balloon slightly deflated and wrinkled. No text or logo.',
        'Giant balloon-art spider in black and purple long balloons hanging over a haunted party doorway, legs made of bent twisted balloons, glossy highlights. No text or logo.',
      ],
    },
    'SP11-020': {
      dna: craft(
        'Wooden toy: turned and carved wood toy with rounded shapes and simple paint.',
        'turned and carved wood parts, dowels and pegs, with simple painted details.',
        'Natural wood with primary paint.',
        'Warm soft light.',
        'Wood grain, dowels and paint.',
        'Wholesome, classic, warm and simple.',
        'turned wood; dowels; simple paint',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a turned-wood pull-along dragon toy with painted red wheels, dowel legs, simple black painted eyes and a wooden-bead tail, on a worn floorboard. No text or logo.',
        'Set of turned-wood peg figures: round-headed knights with painted helmets and tiny carved shields guarding a castle of stacked painted wooden blocks. No text or logo.',
        'Hand-carved wooden wolf toy with visible knife facets, oiled beech grain and a single carved red tongue, beside wood shavings and a whittling knife. No text or logo.',
      ],
    },
    'SP11-021': {
      dna: craft(
        'Sticker art: die-cut vinyl sticker with thick white border and glossy print.',
        'printed as a die-cut vinyl sticker with a thick white border.',
        'Bold flat colors with white border.',
        'Glossy light on vinyl.',
        'Glossy vinyl and white border.',
        'Playful, bold, graphic and collectible.',
        'die-cut sticker; white border; glossy',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a glossy die-cut vinyl sticker of a grumpy black dragon clutching a steaming mug, thick white border, stuck slightly crooked on a scratched wooden desk. No text or logo.',
        'Sheet of glossy die-cut vinyl stickers of dark fantasy creatures: a skull moth, a cursed crown, a one-eyed bat and a cute lich, each with a thick white border, one sticker half peeled. No text or logo.',
        'Weathered vinyl sticker of a howling wolf stuck on a battered metal lunchbox, white border scuffed, gloss cracking and a corner lifting. No text or logo.',
      ],
    },
    'SP11-022': {
      dna: craft(
        'Clay stop-motion comedy: plasticine characters with big grins and fingerprinted surfaces on a miniature set.',
        'plasticine puppets with wide mouths, bulging eyes and fingerprints on a miniature set.',
        'Saturated plasticine colors.',
        'Warm miniature-set lighting.',
        'Plasticine with fingerprints.',
        'Comic, warm, silly and handmade.',
        'plasticine puppets; wide grins; fingerprints',
      ),
      avoid: AVOID,
      briefs: [
        'Stop-motion still of an original plasticine knight with a wide nervous grin and bulging eyes facing a tiny fire-breathing plasticine dragon on a miniature castle set, fingerprints visible on both. No logos or text.',
        'Plasticine witch with a huge toothy grin stirring a bubbling cauldron of green clay blobs in a cramped miniature cottage set, fingerprints and tool marks on everything. No logos or text.',
        'Plasticine feast scene: a round-faced king with a startled grin as a plasticine roast pig sits up on the banquet table, clay candles, warm miniature-set light. No logos or text.',
      ],
    },
    'SP11-023': {
      dna: craft(
        'Tin toy: lithographed tin-plate toy with wind-up key and tabs.',
        'lithographed tin plate folded with tabs, with a wind-up key.',
        'Bright printed lithograph colors.',
        'Studio light on metal.',
        'Tin plate, tabs and printed detail.',
        'Vintage, charming, mechanical and nostalgic.',
        'lithographed tin; tabs; wind-up key',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a wind-up tin toy dragon with lithographed red and gold scales, folded tin tabs at the seams, a large brass wind-up key in its side, rust spots at the edges. No text or logo.',
        'Tin toy jousting knight on a wheeled tin horse, lithographed armor pattern, bent tab joints and a wind-up key, slightly dented from years of play. No text or logo.',
        'Tin toy castle carousel with lithographed horses and knights circling under a striped tin roof, wind-up key underneath, soft reflections on the metal. No text or logo.',
      ],
    },
    'SP11-024': {
      dna: craft(
        'Diorama box: a miniature scene built inside an open box with layered depth.',
        'built as a miniature scene inside a shadow box with layered cut-outs and props.',
        'Warm crafted colors.',
        'Soft light from above.',
        'Paper, wood and miniature props.',
        'Intimate, charming, crafted and deep.',
        'shadow box; layered miniature scene',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a shadow-box diorama: a dragon sleeping on a hoard of tiny gold coins inside an old wooden box, layered cut-paper cave walls, a miniature knight peeking from the edge. No text or logo.',
        "Shadow-box diorama of a witch's cottage interior at night, layered card walls, miniature bottles and a tiny cauldron, warm light from a hidden bulb. No text or logo.",
        'Deep shadow-box diorama of a sunken ship on the sea floor, layered cut-paper waves, miniature fish on wires and a skeleton captain at the wheel. No text or logo.',
      ],
    },
    'SP11-025': {
      dna: craft(
        'Button-eye doll: stitched cloth doll with button eyes and yarn hair.',
        'sewn cloth doll with button eyes, yarn hair and visible stitches.',
        'Muted fabric colors.',
        'Soft window light.',
        'Cloth, buttons and stitches.',
        'Eerie, handmade, sweet and uncanny.',
        'button eyes; stitched cloth; yarn hair',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a stitched cloth doll of an original witch with mismatched black button eyes, grey yarn hair and a patched black dress, sitting on a dusty windowsill at dusk. No text or logo.',
        'Button-eyed cloth doll knight with a felt helmet and a stitched cross on its tunic, one button eye hanging by a thread, lying in an old toy chest. No text or logo.',
        'Stitched cloth doll of an original little ghost bride with pale linen skin, black button eyes and a torn lace veil, seated in a wicker chair in a dim attic. No text or logo.',
      ],
    },
    'SP11-027': {
      dna: craft(
        'Craft mosaic tile: small ceramic craft tiles glued onto a form.',
        'covered in small hand-cut ceramic tiles with grout.',
        'Bright glazed tile colors.',
        'Soft light.',
        'Glazed tiles and grout.',
        'Crafty, cheerful, handmade and bright.',
        'craft mosaic tiles; grout',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a garden dragon sculpture covered in hand-cut glazed ceramic tiles in greens and turquoise, grey grout lines, sitting among ferns. No text or logo.',
        "Craft mosaic knight's helmet covered in broken china fragments with blue floral patterns and white grout, mounted on a garden wall. No text or logo.",
        'Craft mosaic owl birdbath with small bright glazed tiles, uneven grout and a few missing tiles, water in the basin reflecting the sky. No text or logo.',
      ],
    },
    'SP11-029': {
      dna: craft(
        'Embroidery: the subject stitched in thread on fabric in a hoop.',
        'embroidered with satin, stem and French-knot stitches on linen in a hoop.',
        'Thread colors on linen.',
        'Soft light.',
        'Satin stitches, knots and linen weave.',
        'Delicate, handmade, patient and cozy.',
        'embroidery stitches; hoop; linen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an embroidery hoop with a stitched black dragon coiled around a castle tower, satin-stitch scales, stem-stitch outlines and French-knot stars on natural linen. No text or logo.',
        "Embroidered death's-head moth in muted gold and black threads on dark linen, satin-stitched wings, loose threads and a needle resting in the hoop. No text or logo.",
        'Embroidery hoop of a knight kneeling in a thorny rose garden, long-and-short stitch shading on the roses, a few unfinished areas with pencil lines still showing. No text or logo.',
      ],
    },
    'SP11-030': {
      dna: craft(
        'Sand art: colored sand layered in a glass bottle into patterns and scenes.',
        'layered colored sand forming the subject inside a glass bottle or frame.',
        'Layered colored sands.',
        'Backlit glass.',
        'Sand grains and glass.',
        'Patient, fragile, colorful and calm.',
        'layered colored sand; glass',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a glass bottle filled with layered colored sand forming a desert dragon flying over dunes, sharp strata lines, backlit by a window. No text or logo.',
        'Sand-art bottle showing a dark castle at sunset in layers of red, orange, purple and black sand, a few grains spilled on the table. No text or logo.',
        'Framed sand-art picture of a ship in a storm, layered blue and grey sand between glass panes, some layers shifted as if the frame was tilted. No text or logo.',
      ],
    },
    'SP11-031': {
      dna: craft(
        'Ice carving: the subject carved from clear ice with chisel marks.',
        'carved from a clear ice block with chisel marks and frosty edges.',
        'Clear ice with blue tints.',
        'Colored backlight through ice.',
        'Clear ice, chisel marks and frost.',
        'Cold, elegant, fleeting and luminous.',
        'carved clear ice; chisel marks',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an ice-carved dragon at a winter festival, wings clear and thin, chisel marks and frosty edges, lit blue from below at night. No text or logo.',
        'Ice-carved knight holding a sword, clear ice with trapped bubbles, melting drips at the base, lit by warm torchlight. No text or logo.',
        'Ice-carved throne in a frozen hall, chisel marks on the armrests, frost on the seat, cold blue light passing through it. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Paper Theater Puppets',
      domain: 'toy paper theater',
      tags: ['paper-theater', 'puppets', 'craft'],
      dna: craft(
        'Paper theater: flat printed cardboard figures on sticks in a miniature stage with layered wings.',
        'flat printed cardboard cut-outs on sticks set in a toy stage with layered scenery.',
        'Victorian printed colors.',
        'Warm footlight glow.',
        'Printed card, cut edges and sticks.',
        'Theatrical, nostalgic, charming and quaint.',
        'flat card cut-outs; toy stage; layered wings',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a toy paper theater staging a knight fighting a dragon with flat printed cardboard cut-outs on sticks, layered painted wings of a castle, warm footlight glow. No text or logo.',
        'Toy paper theater scene of a witch in a moonlit forest, flat printed card trees in three layers, a cut-out owl on a wire, candle-like footlights. No text or logo.',
        'Toy paper theater of a ship in a storm, cut-card waves on sliding strips, a flat printed sea serpent rising behind the hull, a hand holding a stick at the edge. No text or logo.',
      ],
    },
    {
      name: 'Resin Garage Kit',
      domain: 'hand-painted resin kit',
      tags: ['resin-kit', 'model', 'craft'],
      dna: craft(
        'Resin garage kit: hand-painted resin model on a sculpted base with fine brushwork.',
        'a cast resin model assembled and hand-painted with washes and drybrush on a sculpted base.',
        'Hand-painted model colors with washes.',
        'Studio light.',
        'Resin with brushwork, washes and base.',
        'Crafted, detailed, collectible and dramatic.',
        'hand-painted resin; washes; sculpted base',
      ),
      avoid: AVOID,
      briefs: [
        'Studio photograph of a hand-painted resin model of an original dragon knight on a sculpted rocky base, washes pooling in the armor recesses, drybrushed highlights on the edges. No text or logo.',
        'Hand-painted resin garage kit of an original swamp witch on a mossy base, glazed green skin, tiny painted eyes, a hobby paint brush and palette beside it. No text or logo.',
        'Unfinished resin garage kit of a sea monster: half primed grey, half painted in teal and bone, mold lines still visible on the tentacles, on a hobby desk. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
