import type { Spec } from '../tools/apply';
import { ga, keep } from './_authors';

// Video game pass, puzzle chambers and adventure setpieces: each preset names its game, studio
// and year and states the real render technique and camera. Briefs that restaged a signature
// hero, prop or boss (the portal gun and cube, the cat suit and tortoise king, the fez, the
// squirrel card, the bug-eyed escapee) are replaced with original ones.
const spec: Spec = {
  pack: 'pack_12',
  category: '8. Puzzle Chambers & Adventure Setpieces',
  updates: Object.fromEntries([
    ga('SP12-004', 'Skies of Arcadia 2000 - Overworks Sky Pirates', {
      look: 'Overworks Skies of Arcadia (2000) look: bright Dreamcast JRPG of sky pirates, wooden airships over an endless cloud sea, floating islands, cheerful anime characters and huge sky beasts.',
      subject:
        'render people as cheerful low-poly anime sky pirates with goggles, sashes and big boots.',
      color: 'Sky blue, sunny gold, cloud white and warm ship wood.',
      light: 'Bright open-sky sunshine with soft Dreamcast gradients.',
      texture: 'Early-2000s low-poly models with clean bright textures.',
      camera: 'Third-person deck view over the cloud sea.',
      mood: 'sunny swashbuckling adventure',
      render: 'Authentic Dreamcast JRPG screen.',
      key: 'Skies of Arcadia airships; cloud sea; sky pirates',
      avoid: ['a sky pirate boy with an eyepatch strap and twin cutlasses'],
    }),
    ga('SP12-012', 'Stardew Valley 2016 - ConcernedApe Pixel Farm Town', {
      look: 'ConcernedApe Stardew Valley (2016) look: cozy top-down pixel farm town with warm saturated sprites, wooden interiors, seasonal festivals, crops and friendly villagers.',
      subject: 'render people as small cozy pixel villagers with round heads and simple faces.',
      color: 'Warm wood amber, harvest orange, crop green and cozy lamp yellow.',
      light: 'Warm lamplight and flat pixel daylight.',
      texture: 'Soft detailed pixel art tiles and sprites.',
      camera: 'Top-down three-quarter pixel view.',
      mood: 'cozy communal warmth',
      render: 'Authentic cozy pixel farm game screen.',
      key: 'Stardew pixel town; cozy tavern; harvest festival',
    }),
    ga('SP12-036', 'Portal 2 2011 - Valve Aperture Test Chamber', {
      look: 'Valve Portal 2 (2011) look: first-person physics puzzle chambers, clean white modular panels, grey walls, robotic arms rearranging the room, laser emitters, light bridges and dry humor.',
      subject:
        'render people as test subjects in plain white jumpsuits and long-fall boots, seen from first person.',
      color: 'Clinical white, panel grey, laser red and light-bridge blue.',
      light: 'Clean even fluorescent light with glowing beams.',
      texture: 'Matte white panels, brushed metal and glass.',
      camera: 'First-person view in a test chamber.',
      mood: 'dry clinical wit',
      render: 'Authentic Source engine puzzle screen.',
      key: 'Portal 2 test chamber; white panels; robotic arms; lasers',
      avoid: [
        'a grey cube with a pink heart',
        'orange and blue portal ovals',
        'a hanging robotic AI with a yellow eye',
        'a white handheld device with a black claw tip',
      ],
      briefs: [
        'Standing in a clean modular test chamber in first person, an original subject in a white jumpsuit balances on a floating panel as a giant robotic arm lowers a potted fern into the path of a laser. No readable text or logo.',
        keep('SP12-036')[1],
        keep('SP12-036')[2],
      ],
    }),
    ga('SP12-037', 'Super Mario 3D World 2013 - Nintendo EAD Toy Platformer', {
      look: 'Nintendo EAD Tokyo Super Mario 3D World (2013) look: bright toy-box 3D platformer, candy-colored floating blocks, glossy plastic surfaces, clean shadows and cheerful diorama levels.',
      subject:
        'render people as tiny round glossy toy-like figures with big eyes and chunky shoes.',
      color: 'Candy red, sky blue, grass green and sunny yellow.',
      light: 'Bright soft daylight with clean drop shadows.',
      texture: 'Glossy plastic toy surfaces.',
      camera: 'Three-quarter overhead platformer camera.',
      mood: 'bouncy cheerful play',
      render: 'Authentic Wii U toy platformer screen.',
      key: 'Mario 3D World toy blocks; glossy plastic; diorama levels',
      avoid: [
        'a mustached plumber in red and blue',
        'a cat suit with a bell',
        'a spiked turtle king',
        'question-mark blocks',
        'flagpoles and green pipes',
      ],
      briefs: [
        'Leaping across a toy-like floating island of candy-colored blocks, an original tiny hero in a frog raincoat bounces onto a giant grumpy cactus boss whose flowers pop off with every hit. No readable text or logo.',
        'In a bright toy-box platformer, a small hero triumphantly reaches the goal gate, and the ribbon is being held out by a very proud caterpillar. No readable text or logo.',
        keep('SP12-037')[2],
      ],
    }),
    ga('SP12-051', 'Slay the Spire 2019 - Mega Crit Card Climb', {
      look: 'Mega Crit Slay the Spire (2019) look: 2D roguelike deckbuilder with hand-drawn cartoon heroes and monsters, card hands at the bottom and glowing intent icons above enemies.',
      subject:
        'render every subject as flat hand-drawn cartoon heroes, monsters and illustrated cards.',
      color: 'Candle gold, card parchment and dungeon teal.',
      light: 'Flat painted light and glowing card effects.',
      texture: 'Hand-drawn 2D art and card frames.',
      camera: 'Side-on card battle layout.',
      mood: 'strategic climbing tension',
      render: 'Authentic deckbuilder battle screen.',
      key: 'Slay the Spire cards; intent icons; hand-drawn foes',
      avoid: ['existing Slay the Spire heroes'],
    }),
    ga('SP12-058', 'Fez 2012 - Polytron Rotating Pixel World', {
      look: 'Polytron Fez (2012) look: 2D pixel platformer in a 3D world that rotates in quarter turns, bright pastel voxels, secret glyphs and serene exploration.',
      subject: 'render people as tiny pastel pixel sprites in a rotating voxel world.',
      color: 'Bright pastel greens, sky blue and warm stone.',
      light: 'Soft pixel daylight or starry night.',
      texture: 'Crisp pixel voxels.',
      camera: 'Flat side view of a rotating world.',
      mood: 'serene curious puzzling',
      render: 'Authentic pixel puzzle-platformer screen.',
      key: 'Fez rotating world; pastel pixels; glyphs',
      avoid: ['a small white creature in a red fez'],
      briefs: [
        'Rotating a blocky pixel world in a single turn, an original tiny explorer in a knitted beanie reveals a hidden door as the whole echo cavern pivots around her in bright pastel colors. No readable text or logo.',
        keep('SP12-058')[1],
        keep('SP12-058')[2],
      ],
    }),
    ga('SP12-072', 'Dakar Desert Rally 2022 - Big Moon Dune Run', {
      look: 'Big Moon Entertainment Dakar Desert Rally (2022) look: realistic off-road rally across vast dunes, rally trucks and bikes airborne, sand plumes and dawn haze.',
      subject: 'render vehicles as dusty rally trucks and bikes flying over dunes.',
      color: 'Dune gold, dawn pink and dust.',
      light: 'Low dawn light with sand haze.',
      texture: 'Realistic sand spray and dirty paint.',
      camera: 'Chase camera during jumps.',
      mood: 'brutal endurance thrill',
      render: 'Authentic off-road rally screen.',
      key: 'Dakar rally dunes; sand plumes; trucks airborne',
    }),
    ga('SP12-074', 'Inscryption 2021 - Daniel Mullins Cabin Cards', {
      look: 'Daniel Mullins Games Inscryption (2021) look: first-person card game in a dark wooden cabin, a looming dealer in shadow, carved creature cards, candles and grainy unsettling horror.',
      subject: 'render every subject as carved woodcut creature cards and shadowy figures.',
      color: 'Candle amber, dark wood and blood red.',
      light: 'Single candle glow in darkness.',
      texture: 'Grainy film, wood and old paper.',
      camera: 'First-person view across the table.',
      mood: 'eerie unsettling dread',
      render: 'Authentic horror card game screen.',
      key: 'Inscryption cabin; looming dealer; creature cards',
      avoid: ['a looming dealer with glowing eyes and masks', 'squirrel cards'],
      briefs: [
        'Seated at a candlelit table in a dark cabin, an original player places a moth card as the looming dealer across the table reveals a hand of carved bone creatures. No readable text or logo.',
        keep('SP12-074')[1],
        keep('SP12-074')[2],
      ],
    }),
    ga('SP12-077', "Oddworld Abe's Oddysee 1997 - Oddworld Inhabitants Pre-Rendered", {
      look: "Oddworld Inhabitants Abe's Oddysee (1997) look: side-view cinematic platformer with lush pre-rendered backgrounds, grotesque industrial factories, alien wilderness and dark satire.",
      subject: 'render people as small pre-rendered alien workers with odd anatomy.',
      color: 'Industrial rust, smog orange and alien green.',
      light: 'Pre-rendered moody factory light.',
      texture: 'Pre-rendered CGI backgrounds.',
      camera: 'Side-view cinematic screen.',
      mood: 'grim satirical escape',
      render: 'Authentic PS1 pre-rendered platformer screen.',
      key: 'Oddworld pre-rendered; factory escape; satire',
      avoid: ['a thin green alien with sewn lips', 'existing Oddworld species'],
      briefs: [
        'Sneaking across a side-view industrial quarry, an original lanky moth-winged worker leads a line of fellow escapees past a sleeping guard creature as the smokestacks glow. No readable text or logo.',
        keep('SP12-077')[1],
        keep('SP12-077')[2],
      ],
    }),
    ga('SP12-080', "Demon's Souls 2009 - FromSoftware Boletarian Keep", {
      look: "FromSoftware Demon's Souls (2009) look: grim third-person action in fog-choked ruined castles, dull grey-green palettes, fog gates, towering armored demons and lonely nexus light.",
      subject: 'render people as lone weathered warriors in dented plate and mail.',
      color: 'Grey-green fog, cold stone and rust.',
      light: 'Dull fog light with soul glow.',
      texture: 'Worn stone and dented armor.',
      camera: 'Third-person lock-on duel view.',
      mood: 'grim oppressive dread',
      render: 'Authentic PS3 dark fantasy screen.',
      key: "Demon's Souls fog gates; ruined keep; grey-green",
    }),
    ga('SP12-169', 'Lara Croft GO 2015 - Square Enix Montreal Diorama Puzzles', {
      look: 'Square Enix Montreal Lara Croft GO (2015) look: turn-based puzzle dioramas in stylized low-poly ruins, node paths, pushable blocks, glowing plates and soft color gradients.',
      subject: 'render people as small stylized low-poly explorers on node paths.',
      color: 'Soft jade, sand and dusk gradients.',
      light: 'Soft gradient ambient light.',
      texture: 'Clean low-poly shapes.',
      camera: 'High diorama view.',
      mood: 'calm clever exploration',
      render: 'Authentic diorama puzzle screen.',
      key: 'Lara Croft GO dioramas; nodes; blocks',
    }),
    ga('SP12-170', 'Simon the Sorcerer 1993 - Adventure Soft Painted Adventure', {
      look: 'Adventure Soft Simon the Sorcerer (1993) look: VGA point-and-click adventure with lush painted backgrounds, cluttered wizard rooms, cheeky cartoon characters and verb inventory.',
      subject: 'render people as cheeky cartoon adventure characters in pointed hats and robes.',
      color: 'Rich VGA purples, greens and warm browns.',
      light: 'Warm candle and window light.',
      texture: 'Painted VGA pixel art.',
      camera: 'Side-view adventure room.',
      mood: 'cheeky magical mischief',
      render: 'Authentic VGA adventure screen.',
      key: 'Simon the Sorcerer painted VGA; wizard rooms',
      avoid: ['a boy wizard in a purple robe and hat'],
      briefs: [
        'Standing in a painted wizard workshop full of bubbling flasks, an original young apprentice holds a rubber duck tied to a fishing line as a stuffed crocodile winks from the ceiling. No readable text or logo.',
        keep('SP12-170')[1],
        keep('SP12-170')[2],
      ],
    }),
    ga('SP12-171', 'Super Monkey Ball 2001 - Amusement Vision Tilt Stage', {
      look: 'Amusement Vision Super Monkey Ball (2001) look: bright tilting stages floating in the sky or space, a character sealed in a clear ball, bananas and goal gates.',
      subject: 'render people as small figures sealed inside clear rolling balls.',
      color: 'Bright checker colors and starry skies.',
      light: 'Bright arcade light.',
      texture: 'Glossy clean surfaces.',
      camera: 'Behind-the-ball tilt view.',
      mood: 'tense playful balance',
      render: 'Authentic arcade tilt-maze screen.',
      key: 'Monkey Ball tilt stages; ball; floating mazes',
      avoid: ['a monkey in a ball'],
    }),
    ga('SP12-172', 'Machinarium 2009 - Amanita Hand-Drawn Robots', {
      look: 'Amanita Design Machinarium (2009) look: hand-drawn rusty robot city, whimsical mechanical characters, sepia greens and point-and-click puzzles.',
      subject: 'render people as whimsical hand-drawn rusty robots.',
      color: 'Sepia green, rust and warm grey.',
      light: 'Soft hazy light.',
      texture: 'Hand-drawn pencil and watercolor.',
      camera: 'Side-view scene.',
      mood: 'wistful mechanical whimsy',
      render: 'Authentic hand-drawn adventure screen.',
      key: 'Machinarium rusty robots; hand-drawn; sepia',
      avoid: ['a small robot with a stretching body and bowler hat'],
    }),
    ga('SP12-173', 'Monument Valley 2014 - ustwo Impossible Geometry', {
      look: 'ustwo games Monument Valley (2014) look: isometric impossible architecture that rotates, pastel minimalist palettes, tiny figures and Escher-like paths.',
      subject: 'render people as tiny minimalist figures on impossible paths.',
      color: 'Pastel coral, mint and lilac.',
      light: 'Soft flat gradient light.',
      texture: 'Clean flat shapes.',
      camera: 'Isometric diorama view.',
      mood: 'serene puzzling wonder',
      render: 'Authentic isometric puzzle screen.',
      key: 'Monument Valley impossible geometry; pastel; isometric',
      avoid: ['a small princess in a white cone hat'],
    }),
    ga('SP12-174', 'The Room 2012 - Fireproof Puzzle Box', {
      look: 'Fireproof Games The Room (2012) look: first-person close-up puzzle boxes of dark wood and brass, hidden drawers, eyepiece reveals and occult glow.',
      subject: 'render every subject as intricate mechanical boxes and devices seen up close.',
      color: 'Dark wood, brass and occult blue.',
      light: 'Single warm lamp with glow.',
      texture: 'Polished wood, brass and leather.',
      camera: 'First-person close-up view.',
      mood: 'curious occult tension',
      render: 'Authentic mobile puzzle screen.',
      key: 'The Room puzzle box; brass; hidden drawers',
    }),
    ga('SP12-175', 'Rayman Legends 2013 - Ubisoft Montpellier UbiArt', {
      look: 'Ubisoft Montpellier Rayman Legends (2013) look: UbiArt hand-painted 2D platforming, lush storybook worlds, rubbery cartoon characters and speedy set-piece chases.',
      subject: 'render people as rubbery hand-painted cartoon characters.',
      color: 'Lush storybook greens and warm golds.',
      light: 'Painterly glow.',
      texture: 'Hand-painted 2D art.',
      camera: 'Side-scrolling chase view.',
      mood: 'zany breathless chase',
      render: 'Authentic hand-painted platformer screen.',
      key: 'Rayman UbiArt; hand-painted chase; storybook',
      avoid: ['a limbless hero with floating hands'],
    }),
    ga('SP12-176', 'Indiana Jones Great Circle 2024 - MachineGames Pulp Adventure', {
      look: 'MachineGames Indiana Jones and the Great Circle (2024) look: pulp 1930s adventure, jungle chasms, rope bridges, whips and ruins in rich cinematic light.',
      subject: 'render people as 1930s explorers in khaki and leather.',
      color: 'Jungle green, khaki and sunlit gold.',
      light: 'Cinematic dappled jungle light.',
      texture: 'Realistic rope, wood and stone.',
      camera: 'First-person action view.',
      mood: 'pulpy daring thrill',
      render: 'Authentic modern adventure screen.',
      key: 'Great Circle pulp; rope bridges; ruins',
      avoid: ['a fedora-wearing archaeologist with a whip'],
    }),
    ga('SP12-177', 'Return to Monkey Island 2022 - Terrible Toybox Paper Cutout', {
      look: 'Terrible Toybox Return to Monkey Island (2022) look: paper-cutout storybook art with angular shapes, flat textures, pirate islands and comic adventure staging.',
      subject: 'render people as angular paper-cutout cartoon pirates.',
      color: 'Tropical teal, sand and sunset orange.',
      light: 'Flat storybook light.',
      texture: 'Paper-cutout flat textures.',
      camera: 'Side-view adventure scene.',
      mood: 'wry piratical comedy',
      render: 'Authentic storybook adventure screen.',
      key: 'Return to Monkey Island paper cutout; pirates',
      avoid: ['a blond wannabe pirate', 'a ghost pirate captain'],
    }),
    ga('SP12-178', 'Shadowmatic 2015 - Triada Shadow Puzzles', {
      look: 'Triada Studio Shadowmatic (2015) look: rotating abstract objects under a lamp to cast recognizable shadows on a wall, moody rooms and surreal reveals.',
      subject: 'render every subject as abstract object clusters and the shadows they cast.',
      color: 'Moody sepia, wall cream and deep shadow.',
      light: 'Single lamp casting hard shadows.',
      texture: 'Clean matte objects.',
      camera: 'Front view of a lit wall.',
      mood: 'quiet surreal discovery',
      render: 'Authentic shadow puzzle screen.',
      key: 'Shadowmatic shadows; lamp; abstract objects',
    }),
  ]),
};

export default spec;
