import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Old-school and indie tabletop illustrators: each preset names the artist whose ink, layout and
// zine grammar it rebuilds, from seventies role-playing books to the OSR and indie zine scene.
// Cards stage original monsters and adventurers, never published book art or licensed characters.
const T = ['osr-illustrator', 'dungeon-zine'];
const ink = 'Black ink on cheap paper with photocopy grain and slight bleed.';

const spec: Spec = {
  pack: 'pack_17',
  category: '12. OSR Dungeon Zine Illustrators',
  newCategory: { id: 'osr-dungeon-zine-illustrators' },
  updates: {},
  creates: [
    cr('David Trampier - Clean Line Old-School Ink', 'tabletop illustration', [...T, 'trampier'], {
      look: 'David Trampier old-school role-playing ink: clean confident line work, bold spotted blacks, moody dungeon interiors, grotesque idols and understated mysterious menace.',
      subject:
        'draw the subject in clean confident ink line with bold spotted blacks in moody dungeon settings.',
      color: 'Black ink on white with deep spotted blacks.',
      light: 'Torchlit darkness expressed in solid blacks.',
      texture: ink,
      camera: 'Classic book-plate framing.',
      mood: 'quiet mysterious menace',
      render: 'Classic old-school role-playing ink plate.',
      key: 'Trampier clean line; spotted blacks; dungeon idols',
      avoid: ['a giant horned idol with gem eyes being robbed by thieves'],
      briefs: [
        'In clean confident ink with bold spotted blacks, two nervous tax collectors lower a lantern into a flooded crypt where a squat toad-faced idol sits on a throne of skulls, its shadow falling across the black water. No readable text or logo.',
        'A lone adventurer stands at a fork in a corridor, both passages swallowed by solid ink. Her torch shows scratches on the floor leading left. No readable text or logo.',
        'A chest sits in a small stone room drawn in crisp outline. Its lid is open, and a single thin tentacle rests on the rim. No readable text or logo.',
      ],
    }),
    cr('Erol Otus - Psychedelic Weird Dungeon Art', 'tabletop illustration', [...T, 'otus'], {
      look: 'Erol Otus weird fantasy art: psychedelic bizarre creatures, cosmic strangeness, bold saturated color or wobbly ink, alien anatomy and seventies underground comix energy.',
      subject:
        'draw creatures and people with bizarre alien anatomy in wobbly ink or saturated psychedelic color.',
      color: 'Saturated purple, acid green and orange.',
      light: 'Flat psychedelic color light.',
      texture: 'Wobbly ink with saturated flat color.',
      camera: 'Bizarre crowded composition.',
      mood: 'cosmic weird strangeness',
      render: 'Psychedelic weird fantasy illustration.',
      key: 'Otus weird creatures; psychedelic color; alien anatomy',
      briefs: [
        'In wobbly ink and saturated acid green and purple, a bizarre many-eyed tentacled librarian creature floats above a dungeon study, handing strange glowing books to a startled dwarf with a lantern. No readable text or logo.',
        'A cosmic worm with a human-like smile coils around a crystal pillar in an orange void. Tiny adventurers flee along its body. No readable text or logo.',
        'A pool of purple slime reflects a moon that is not in the sky. Something with too many fingers reaches out of it. No readable text or logo.',
      ],
    }),
    cr('Russ Nicholson - Scratchy Grotesque Ink', 'tabletop illustration', [...T, 'nicholson'], {
      look: 'Russ Nicholson fighting fantasy ink: scratchy dense line work, grotesque detailed monsters, cross-hatched murk, warty skin and eccentric British gamebook character.',
      subject:
        'draw the subject as grotesque detailed ink creatures and characters in scratchy cross-hatched murk.',
      color: 'Black ink with grey hatched tone.',
      light: 'Murky hatched shadow.',
      texture: 'Scratchy dense ink hatching.',
      camera: 'Gamebook illustration framing.',
      mood: 'grotesque eccentric humor',
      render: 'Scratchy gamebook ink illustration.',
      key: 'Nicholson scratchy ink; grotesque monsters; hatching',
      briefs: [
        'In scratchy cross-hatched ink, a warty goblin innkeeper polishes a tankard behind a crooked bar while a line of grotesque detailed monster customers waits, one politely holding its own head under its arm. No readable text or logo.',
        'A swamp witch stirs a pot of eels on a rickety porch. Her pet toad wears spectacles. No readable text or logo.',
        'A crooked signpost in a haunted forest points in three directions at once. Each arrow is a bony finger. No readable text or logo.',
      ],
    }),
    cr('Jim Holloway - Humorous Adventurer Ink', 'tabletop illustration', [...T, 'holloway'], {
      look: 'Jim Holloway role-playing illustration: humorous expressive adventurers in comic mishaps, clean lively ink, clear storytelling and eighties tabletop charm.',
      subject: 'draw people as expressive humorous adventurers in lively clean ink comic mishaps.',
      color: 'Clean black ink with occasional flat tone.',
      light: 'Clear flat illustration light.',
      texture: ink,
      camera: 'Clear storytelling vignette.',
      mood: 'lighthearted adventuring humor',
      render: 'Lively humorous tabletop ink illustration.',
      key: 'Holloway humorous adventurers; lively ink; mishaps',
      briefs: [
        'In lively clean ink, a party of adventurers opens a treasure chest only to find a very angry wizard having a bath inside it, soap bubbles and all, while the thief tries to back away quietly. No readable text or logo.',
        'A knight in full armor struggles to climb a rope ladder while his squire eats his lunch below. Expressions are pure comedy. No readable text or logo.',
        'A dragon’s hoard is labeled with tiny price tags in a dungeon shop. The dragon wears a cardigan. No readable text or logo.',
      ],
    }),
    cr(
      'Dave Sutherland - Early Dungeon Module Ink',
      'tabletop illustration',
      [...T, 'sutherland'],
      {
        look: 'Dave Sutherland early role-playing module look: crude earnest ink drawings, stiff heroic figures, simple dungeon architecture and seventies amateur-professional charm.',
        subject:
          'draw the subject in crude earnest seventies ink with stiff heroic figures and simple architecture.',
        color: 'Black ink on off-white.',
        light: 'Flat simple ink light.',
        texture: ink,
        camera: 'Straightforward frontal composition.',
        mood: 'earnest early adventure',
        render: 'Early seventies dungeon module ink drawing.',
        key: 'Sutherland crude earnest ink; stiff heroes; simple dungeons',
        briefs: [
          'In crude earnest seventies ink, four stiff heroic adventurers stand in a line facing a simple stone doorway guarded by a lumpy ogre holding a club, all drawn with a charming amateur-professional touch. No readable text or logo.',
          'A simple dungeon room contains a well and a stiff skeleton guard. The torches are drawn as small triangles. No readable text or logo.',
          'A wizard with a pointed hat raises a staff at a lumpy dragon in a cave. Both look slightly surprised. No readable text or logo.',
        ],
      },
    ),
    cr('Bill Willingham - Bold Comic Dungeon Ink', 'tabletop illustration', [...T, 'willingham'], {
      look: 'Bill Willingham role-playing ink: bold comic-book line work, dynamic poses, heavy blacks, confident anatomy and eighties module cover energy.',
      subject: 'draw people in bold comic-book ink with dynamic poses and heavy blacks.',
      color: 'Black ink with bold spot blacks.',
      light: 'Dramatic comic contrast.',
      texture: ink,
      camera: 'Dynamic comic panel framing.',
      mood: 'bold dynamic adventure',
      render: 'Bold comic-style tabletop ink.',
      key: 'Willingham bold comic ink; dynamic poses; heavy blacks',
      briefs: [
        'In bold comic-book ink with heavy blacks, a lanky swamp ranger leaps between floating logs as a giant crocodile surges from the dark water, her cloak whipping in a dynamic diagonal. No readable text or logo.',
        'A dwarf and an elf stand back to back in a crumbling tomb as mummies close in. Their shadows stretch across the wall. No readable text or logo.',
        'A shattered door hangs from one hinge in a dungeon corridor. Something just went through it very fast. No readable text or logo.',
      ],
    }),
    cr('Jeff Dee - Energetic Cartoon Adventure Ink', 'tabletop illustration', [...T, 'jeff-dee'], {
      look: 'Jeff Dee role-playing illustration: energetic cartoon-inflected ink, expressive monsters, lively action and bright playful eighties module energy.',
      subject:
        'draw the subject in energetic cartoon-inflected ink with expressive monsters and lively action.',
      color: 'Black ink with occasional bright flat color.',
      light: 'Flat lively illustration light.',
      texture: ink,
      camera: 'Energetic action vignette.',
      mood: 'playful energetic adventure',
      render: 'Energetic cartoon tabletop ink.',
      key: 'Jeff Dee energetic ink; expressive monsters; lively',
      briefs: [
        'In energetic cartoon-inflected ink, a startled cleric ducks as an expressive gelatinous cube wobbles past carrying a lost boot, a set of keys and a very surprised goblin inside it. No readable text or logo.',
        'A band of kobolds chases an adventurer across a rope bridge. One kobold has brought a frying pan. No readable text or logo.',
        'A beholder-like floating eye creature peeks nervously around a pillar. It is holding a tiny white flag. No readable text or logo.',
      ],
    }),
    cr(
      'Tony DiTerlizzi - Planar Whimsical Ink Watercolor',
      'tabletop illustration',
      [...T, 'diterlizzi'],
      {
        look: 'Tony DiTerlizzi planar fantasy art: whimsical elongated characters, curling Art Nouveau lines, sepia ink with muted watercolor and strange bohemian city dwellers.',
        subject:
          'draw people as whimsical elongated characters with curling Art Nouveau lines in sepia ink and watercolor.',
        color: 'Sepia ink with muted rust and teal washes.',
        light: 'Soft muted watercolor light.',
        texture: 'Sepia ink line with soft washes.',
        camera: 'Character portrait vignette.',
        mood: 'whimsical bohemian strangeness',
        render: 'Sepia ink and watercolor planar illustration.',
        key: 'DiTerlizzi elongated whimsy; sepia; Art Nouveau curls',
        avoid: ['Planescape characters', 'Spiderwick characters'],
        briefs: [
          'In sepia ink and muted watercolor, an elongated whimsical doorkeeper with curling Art Nouveau horns guards a city of doors floating in mist, a key ring as tall as she is hanging from her hip. No readable text or logo.',
          'A thin bohemian merchant sells bottled dreams from a creaking cart in a misty sepia alley. His long mustache curls into perfect spirals. No readable text or logo.',
          'A curling iron doorway stands alone in a sepia fog. Behind it, a different sky is visible. No readable text or logo.',
        ],
      },
    ),
    cr('Jason Sholtis - Weird Humorous OSR Line', 'tabletop illustration', [...T, 'sholtis'], {
      look: 'Jason Sholtis OSR illustration: weird humorous line art, bizarre goofy monsters, deadpan adventurers and underground mythic-underworld strangeness in crisp black ink.',
      subject:
        'draw the subject as weird goofy monsters and deadpan adventurers in crisp black ink.',
      color: 'Crisp black ink on white.',
      light: 'Flat clear line light.',
      texture: ink,
      camera: 'Weird deadpan vignette.',
      mood: 'weird deadpan humor',
      render: 'Weird humorous OSR ink illustration.',
      key: 'Sholtis weird goofy monsters; deadpan; crisp ink',
      briefs: [
        'In crisp black ink, a deadpan adventurer holds out a sandwich to a bizarre goofy monster made of three stacked mushrooms with legs, which stares back with no expression in a mythic underworld cave. No readable text or logo.',
        'A dungeon hallway is lined with doors that each have a face. One door is yawning. No readable text or logo.',
        'A skeleton sits at a desk filling in forms in a crypt office. A lantern flickers overhead. No readable text or logo.',
      ],
    }),
    cr('Stefan Poag - Retro Bold Weird Fantasy Ink', 'tabletop illustration', [...T, 'poag'], {
      look: 'Stefan Poag weird fantasy art: retro bold ink with thick outlines, strange monsters, pulpy cosmic weirdness and seventies-inspired OSR cover energy.',
      subject: 'draw the subject in retro bold thick-outlined ink with pulpy cosmic weirdness.',
      color: 'Bold black ink with flat retro color.',
      light: 'Flat retro print light.',
      texture: ink,
      camera: 'Bold iconic composition.',
      mood: 'pulpy cosmic weirdness',
      render: 'Retro bold weird fantasy ink.',
      key: 'Poag retro bold ink; thick outlines; cosmic weird',
      briefs: [
        'In retro bold thick-outlined ink, a lumpy cosmic toad wizard floats above a ruined tower, its many eyes glowing as tiny adventurers raise spears from the crumbling battlements. No readable text or logo.',
        'A strange brain-shaped moon rises in thick outline over a swamp village of stilt huts. The villagers bow politely toward it from their porches. No readable text or logo.',
        'A thick-outlined crystal skull glows on a stone pedestal in a forgotten temple. Fat worms coil lazily around its base. No readable text or logo.',
      ],
    }),
    cr(
      'Evey Lockhart - Wobbly Charming OSR Monsters',
      'tabletop illustration',
      [...T, 'lockhart'],
      {
        look: 'Evey Lockhart OSR art: wobbly charming ink line, whimsical creepy monsters, cozy-weird dungeon inhabitants and handmade zine warmth.',
        subject: 'draw the subject in wobbly charming ink as whimsical creepy dungeon inhabitants.',
        color: 'Black ink with occasional soft wash.',
        light: 'Flat handmade zine light.',
        texture: ink,
        camera: 'Cozy-weird vignette.',
        mood: 'cozy creepy whimsy',
        render: 'Charming wobbly OSR zine ink.',
        key: 'Lockhart wobbly ink; cozy-weird monsters; zine',
        briefs: [
          'In wobbly charming ink, a family of whimsical creepy mushroom goblins sets a dinner table inside a hollow skull, lighting candles and serving moss soup to a lost adventurer who looks deeply unsure. No readable text or logo.',
          'A shy ghost knits a scarf for a skeleton in a cozy crypt. The fire crackles in a bone fireplace. No readable text or logo.',
          'A tiny door in the side of a giant toadstool is open. A teacup sits on the doorstep. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Luka Rejec - Ultraviolet Grasslands Weird Color',
      'tabletop illustration',
      [...T, 'rejec'],
      {
        look: 'Luka Rejec psychedelic OSR art: bright weird color, sprawling alien steppes, strange caravans, loose sketchy linework and ultraviolet sci-fantasy vistas.',
        subject:
          'draw the subject in loose sketchy line with bright weird ultraviolet color across sprawling alien steppes.',
        color: 'Bright ultraviolet, magenta and acid yellow.',
        light: 'Glowing psychedelic sky light.',
        texture: 'Loose sketchy line with digital color.',
        camera: 'Sprawling vista composition.',
        mood: 'psychedelic wandering wonder',
        render: 'Bright psychedelic OSR illustration.',
        key: 'Rejec ultraviolet steppes; weird caravans; sketchy',
        briefs: [
          'Across a sprawling ultraviolet steppe under a magenta sky, a strange caravan of long-legged beasts carries a floating tea house while tiny travelers in bright robes wave at a crystal tower on the horizon. No readable text or logo.',
          'A giant stone head lies half-buried in acid-yellow grass on an endless steppe. A band of nomads has pitched camp inside its open mouth. No readable text or logo.',
          'A lone signal fire burns on a violet hill at dusk. Three moons watch from the sky. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Kelvin Green - Comedic Grotesque OSR Ink',
      'tabletop illustration',
      [...T, 'kelvin-green'],
      {
        look: 'Kelvin Green OSR art: comedic grotesque ink, bulbous ugly monsters and disgusting details, slapstick violence and gleeful British underground humor.',
        subject:
          'draw the subject as bulbous comedic grotesque ink characters with gleeful disgusting detail.',
        color: 'Black ink with grubby tone.',
        light: 'Flat grubby ink light.',
        texture: ink,
        camera: 'Slapstick vignette.',
        mood: 'gleeful grotesque comedy',
        render: 'Comedic grotesque OSR ink illustration.',
        key: 'Kelvin Green grotesque comedy; bulbous monsters',
        briefs: [
          'In comedic grotesque ink, a bulbous warty troll dentist cheerfully examines the enormous rotten teeth of a sobbing ogre while a line of equally ugly patients waits in a damp dungeon clinic. No readable text or logo.',
          'Stepping into something truly unpleasant in a sewer tunnel, a proud adventurer freezes mid-stride. A fat rat on a pipe laughs at him. No readable text or logo.',
          'A bloated slime creature wears a monocle and reads a newspaper in a dungeon. It is dripping everywhere. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Jez Gordon - Clean Graphic Map Illustration',
      'tabletop illustration',
      [...T, 'jez-gordon'],
      {
        look: 'Jez Gordon OSR design and illustration: clean graphic line, isometric dungeon maps with charming detail, limited color and crisp modern zine layout.',
        subject: 'draw the subject as a clean graphic isometric map vignette with limited color.',
        color: 'Limited two-color palette with black line.',
        light: 'Flat graphic light.',
        texture: 'Crisp clean line and flat color.',
        camera: 'Isometric map view.',
        mood: 'crisp inviting exploration',
        render: 'Clean graphic isometric dungeon illustration.',
        key: 'Jez Gordon isometric maps; clean graphic line',
        briefs: [
          'In clean graphic line and a limited orange-and-black palette, an isometric map shows a crooked tower with a flooded basement, a hidden stair, a sleeping cat on the roof and a ladder leading into a well. No readable text or logo.',
          'An isometric map of a village shows a smithy, an inn and a suspicious hole in the square. No readable text or logo.',
          'A small isometric cave map shows three chambers and one locked door. A skeleton rests in the corner. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Scrap Princess - Chaotic Scribble Horror Art',
      'tabletop illustration',
      [...T, 'scrap-princess'],
      {
        look: 'Scrap Princess OSR art: chaotic raw scribbled line, frantic body horror, splattered ink, collage fragments and punk outsider intensity.',
        subject:
          'draw the subject in chaotic raw scribbled line with splattered ink and body-horror intensity.',
        color: 'Black ink with splatter and sickly accents.',
        light: 'Harsh raw contrast.',
        texture: 'Frantic scribble, ink splatter and collage scraps.',
        camera: 'Frantic crowded composition.',
        mood: 'feverish outsider horror',
        render: 'Raw scribbled OSR horror art.',
        key: 'Scrap Princess scribble; splatter; body horror',
        briefs: [
          'In chaotic raw scribbled line and splattered ink, a frantic many-limbed saint made of broken furniture crawls out of a chapel wall while tiny scratchy adventurers scatter, collage scraps of old maps glued around it. No readable text or logo.',
          'A scribbled face emerges from a swamp of ink splatters. Its eyes are two torn buttons. No readable text or logo.',
          'A frantic scribble of wings and teeth fills a small torn page. One corner is burnt. No readable text or logo.',
        ],
      },
    ),
    cr('Johan Nohr - Mork Borg Doom Metal Layout', 'tabletop illustration', [...T, 'nohr'], {
      look: 'Johan Nohr Mörk Borg layout: acid yellow, black and hot pink doom metal design, brutal distressed type as shapes, skulls, harsh halftone and apocalyptic art-punk energy.',
      subject:
        'render the subject as a brutal doom-metal page of harsh halftone in acid yellow, black and hot pink.',
      color: 'Acid yellow, black and hot pink only.',
      light: 'Harsh flat print contrast.',
      texture: 'Distressed halftone and grunge print.',
      camera: 'Aggressive page layout composition.',
      mood: 'apocalyptic art-punk aggression',
      render: 'Brutal doom metal zine page design.',
      key: 'Mörk Borg acid yellow; doom metal; halftone',
      avoid: ['the real Mörk Borg logo'],
      briefs: [
        'On an acid-yellow page slashed with black and hot pink, a harsh halftone portrait of a crowned plague rat king screams over a burning town, distressed shapes clawing across the layout like broken type with no readable words. No readable text or logo.',
        'A hot pink skull glows in a black void above a yellow landscape of dead trees. Halftone dots crumble at its edges. No readable text or logo.',
        'A black page holds a single yellow crow and a dripping pink moon. The paper is torn at the bottom. No readable text or logo.',
      ],
    }),
    cr('Peter Mullen - Funnel Cosmic Horror Ink', 'tabletop illustration', [...T, 'mullen'], {
      look: 'Peter Mullen Dungeon Crawl Classics art: dense cosmic horror ink, elaborate crowded monsters, sword-and-sorcery pulp, heavy black textures and occasional vivid color.',
      subject: 'draw the subject in dense crowded cosmic horror ink with heavy black textures.',
      color: 'Dense black ink with occasional vivid color.',
      light: 'Cosmic ominous glow.',
      texture: 'Dense detailed ink textures.',
      camera: 'Crowded pulp composition.',
      mood: 'dense pulp cosmic horror',
      render: 'Dense cosmic horror ink illustration.',
      key: 'Mullen dense ink; cosmic horror; pulp swords',
      avoid: ['the Dungeon Crawl Classics logo'],
      briefs: [
        'In dense crowded ink, a mob of terrified villagers armed with farm tools and one chicken advance into a star-lit ruin where an elaborate cosmic horror of eyes and tentacles coils around a crumbling obelisk. No readable text or logo.',
        'A sword-and-sorcery barbarian grandmother swings a frying pan at a serpent god. Stars swirl around them. No readable text or logo.',
        'An obelisk carved with a hundred eyes stands alone in a black desert under strange stars. Only one of the eyes is open. No readable text or logo.',
      ],
    }),
    cr('Doug Kovacs - Expressive Funnel Dungeon Crowd', 'tabletop illustration', [...T, 'kovacs'], {
      look: 'Doug Kovacs Dungeon Crawl Classics art: expressive loose ink crowds of peasant adventurers, dungeon mayhem, sketchy energy and chaotic funnel humor.',
      subject:
        'draw people as expressive loose-ink crowds of peasant adventurers in chaotic dungeon mayhem.',
      color: 'Black ink with sketchy tone.',
      light: 'Flat sketchy ink light.',
      texture: ink,
      camera: 'Chaotic crowd composition.',
      mood: 'chaotic peasant mayhem',
      render: 'Expressive loose dungeon crowd ink.',
      key: 'Kovacs peasant crowds; loose ink; dungeon mayhem',
      briefs: [
        'In loose expressive ink, a crowd of peasant adventurers, a turnip farmer, a gravedigger, a baker and a goat herder, stampede out of a dungeon chased by a single angry squeaking rat. No readable text or logo.',
        'A dozen peasants try to push a giant boulder off a trapdoor at once. Everyone is pushing the wrong way. No readable text or logo.',
        'A pile of discarded pitchforks and hats lies at a dungeon entrance. A goat is chewing on one. No readable text or logo.',
      ],
    }),
    cr('Alex Mayo - Surreal Dreamlike OSR Illustration', 'tabletop illustration', [...T, 'mayo'], {
      look: 'Alex Mayo OSR illustration: surreal dreamlike line, strange hybrid creatures, soft limited color and eerie playful weirdness in indie role-playing zines.',
      subject: 'draw the subject as surreal dreamlike hybrid creatures in soft limited color.',
      color: 'Soft limited teal, peach and grey.',
      light: 'Soft dreamy light.',
      texture: 'Clean line with soft flat color.',
      camera: 'Surreal vignette.',
      mood: 'eerie playful dream',
      render: 'Surreal dreamlike OSR illustration.',
      key: 'Alex Mayo surreal hybrids; dreamlike; soft color',
      briefs: [
        'In soft teal and peach, a surreal hybrid creature with a lighthouse for a head and moth wings for arms guides a small boat of sleeping adventurers across a sea of floating keys. No readable text or logo.',
        'A tree grows upside down from a cloud, dropping fruit into a waiting basket held by a fox. No readable text or logo.',
        'A door stands in a field with a staircase going down into the grass. A snail climbs the doorframe. No readable text or logo.',
      ],
    }),
    cr(
      'Kevin Siembieda - Palladium Dense Hatched Ink',
      'tabletop illustration',
      [...T, 'siembieda'],
      {
        look: 'Kevin Siembieda Palladium Books ink: dense cross-hatched detail, muscular armored warriors, mega-weapons and monsters, eighties comic-influenced black-and-white rulebook art.',
        subject:
          'draw people as muscular armored warriors in dense cross-hatched black-and-white ink.',
        color: 'Black ink with dense hatched greys.',
        light: 'Dramatic hatched contrast.',
        texture: 'Dense cross-hatching.',
        camera: 'Rulebook illustration framing.',
        mood: 'rugged heroic intensity',
        render: 'Dense eighties rulebook ink illustration.',
        key: 'Siembieda dense hatching; armored warriors; rulebook',
        avoid: ['Rifts or Palladium characters'],
        briefs: [
          'In dense cross-hatched ink, a muscular armored post-apocalyptic mail carrier with an enormous mega-cannon strapped to her back delivers a single tiny envelope to a nervous goblin at a ruined gas station. No readable text or logo.',
          'A hulking armored robot knight stands guard at a crumbling wasteland shrine. Every plate of its armor is densely cross-hatched. No readable text or logo.',
          'A giant glowing energy sword rests against a ruined concrete wall in the wasteland. Tiny vines have grown over its hilt. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
