import type { Create, Dna, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';

// Sensor and technical imaging: each preset is one real instrument's output. The prompt subject keeps
// its geometry and pose; only the appearance becomes what that sensor records. Mechanics were checked
// against existing sensor presets (thermal, ironbow, night vision, lidar, SAR, sonar, MRI slice,
// ultrasound, Hubble, UV, Schlieren, camera trap, weather radar) so these add new instruments.
const AVOID = [...STYLE_AVOID, 'readable UI text', 'fake HUD clutter', 'medical gore'];

const words = (t: string) => t.split(/\s+/).filter(Boolean).length;
const pad = (t: string, min: number, tail: string) =>
  words(t) < min ? `${t.replace(/\.$/, '')}, ${tail}` : t;

function sensor(
  aesthetic: string,
  records: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  key: string,
): Dna {
  return {
    aesthetic,
    subject_treatment: `Keep the prompt subject's geometry, pose and setting; replace only its appearance with what this instrument records: ${records}`,
    color_and_tone: pad(color, 9, 'exactly as the instrument maps its signal.'),
    lighting_and_shadow: pad(light, 9, 'because the image shows signal, not ordinary light.'),
    texture_and_material: pad(texture, 9, 'as real instrument artifacts rather than decoration.'),
    camera_and_composition: pad(camera, 9, 'matching how this instrument actually frames data.'),
    atmosphere_and_mood: pad(mood, 8, 'coming from seeing what eyes cannot.'),
    rendering_and_quality:
      'Believable instrument output with correct signal logic, artifacts and resolution for that sensor.',
    key_features: key,
  };
}

const spec: Spec = {
  pack: 'pack_11',
  category: '6. Sensor And Technical Imaging',
  updates: {
    'SP11-034': {
      name: 'Dual-Energy Baggage X-Ray',
      dna: sensor(
        'Security baggage X-ray: dual-energy scan where organic materials read orange, metals blue and mixed materials green.',
        'a flat top-down transmission scan: dense metal in dark blue-black, organics in orange, mixed materials in green, overlapping objects adding density.',
        'Orange, green and blue-black on a pale background.',
        'No light; brightness is material density.',
        'Overlapping translucent layers with crisp metal edges and slight scan noise.',
        'Top-down scan of a case or container with contents packed together.',
        'Clinical, suspicious, revealing and tense.',
        'dual-energy colors; orange organics; blue metal; overlapping contents',
      ),
      avoid: AVOID,
      briefs: [
        'Dual-energy baggage X-ray of an old leather chest packed with a coiled chain, a dagger in dark blue, a skull and candles in orange, potion bottles in green and a small dragon egg glowing dense at the center, overlapping contents. No readable text.',
        'Baggage X-ray of a knight travel trunk: folded armor plates in blue-black, a helmet, a lute, bread and a wrapped sword, all overlapping in orange and green. No readable text.',
        'Baggage X-ray of a witch satchel: a cat curled asleep in orange, glass vials in green, iron keys and a pair of shears in dark blue. No readable text.',
      ],
    },
    'SP11-035': {
      name: 'White-Hot Thermal Imager',
      dna: sensor(
        'White-hot thermal imager: greyscale heat image where warm bodies glow white through smoke and darkness, hottest spots flagged red.',
        'shown as heat: warm bodies bright white, cool surfaces dark grey, the hottest points tinted red, smoke and darkness ignored.',
        'Greyscale white-hot with a single red hot-spot overlay.',
        'Heat glows; no visible light or shadows.',
        'Soft thermal blur, low resolution and slight sensor noise.',
        'Handheld imager view with a centered crosshair.',
        'Urgent, tactical, eerie and tense.',
        'white-hot greyscale; red hottest spots; smoke transparency',
      ),
      avoid: AVOID,
      briefs: [
        'White-hot thermal image through thick smoke in a burning castle hall: a knight carrying a child glows white, the fireplace and fallen beams flagged in red, cold stone walls dark grey, centered crosshair. No readable text.',
        'Thermal imager view of a dark forest at night revealing a hulking warm beast hiding behind trees, its breath glowing, a hunter barely warm at the edge. No readable text.',
        'White-hot thermal view of a crypt where a coffin lid is warm from something inside, the candle flagged red, cold skeletons black. No readable text.',
      ],
    },
  },
  creates: [
    {
      name: 'Neutron Radiography',
      domain: 'neutron imaging',
      tags: ['neutron', 'radiography', 'sensor'],
      dna: sensor(
        'Neutron radiography: an X-ray-like image with reversed logic, where metal turns see-through and organic or wet materials show dark.',
        'a greyscale transmission image in which metal casings fade to pale ghosts and wood, wax, water, leather and bone read dark and sharp.',
        'Greyscale with inverted material contrast.',
        'No light; density to hydrogen-rich materials.',
        'Fine grain and soft edges on metal.',
        'Frontal transmission view of a sealed object.',
        'Revealing, mysterious, scientific and quiet.',
        'metal transparent; organics dark; sealed contents',
      ),
      avoid: AVOID,
      briefs: [
        'Neutron radiograph of a sealed iron reliquary: the iron case almost transparent, revealing inside a dark mummified hand holding a wax-sealed scroll and a leather pouch, greyscale with fine grain. No readable text.',
        'Neutron radiograph of a steel knight helmet on a stand: the steel shell almost vanished into a pale ghost, while the leather padding, straps, sweat-soaked lining and a hidden folded letter show dark and sharp, fine greyscale grain. No readable text.',
        'Neutron image of a locked iron treasure chest: the iron frame faint and ghostly, water-swollen books, a wax candle and a coiled snake inside rendered dark and crisp, soft grain across the plate. No readable text.',
      ],
    },
    {
      name: 'Terahertz Package Scan',
      domain: 'terahertz imaging',
      tags: ['terahertz', 'scan', 'sensor'],
      dna: sensor(
        'Terahertz scan: a soft, blurry, low-resolution image that sees through paper, cloth and plastic but not metal or water.',
        'a soft false-color intensity map where cloth, paper and wood fade away and metal and wet objects show as bright solid shapes.',
        'Blue-to-yellow false-color intensity.',
        'No light; intensity is reflected terahertz signal.',
        'Blurry pixels, speckle and soft edges.',
        'Frontal scan of a person or package.',
        'Clinical, eerie, intrusive and quiet.',
        'sees through cloth; bright metal; soft blur',
      ),
      avoid: AVOID,
      briefs: [
        'Terahertz scan of a hooded pilgrim standing still: the robe nearly invisible, a hidden dagger, a chain of keys and a flask showing as bright yellow shapes, soft blue false-color blur. No readable text.',
        'Terahertz scan of a sealed wax-stamped envelope held up to the scanner, the paper nearly invisible, a silver signet ring and a tiny key inside glowing as bright yellow shapes in soft blue false color. No readable text.',
        'Terahertz scan of a wooden marionette case, the wood fading away to reveal bright metal hinges, a coiled spring and a hidden thin blade tucked behind the puppet, blurry speckled false color. No readable text.',
      ],
    },
    {
      name: 'Event Camera Sparse Pixels',
      domain: 'neuromorphic event sensor',
      tags: ['event-camera', 'motion', 'sensor'],
      dna: sensor(
        'Event camera: only changing pixels appear, as scattered colored dots along moving edges on a black or grey field.',
        'reduced to scattered brightness-change events along moving edges: red for darker, blue or green for brighter, still areas empty.',
        'Red and blue events on black or mid grey.',
        'No light; only change is recorded.',
        'Sparse dots, motion trails and noise speckles.',
        'Fixed sensor view of a moving scene.',
        'Ghostly, kinetic, abstract and technical.',
        'sparse events; moving edges only; red and blue dots',
      ),
      avoid: AVOID,
      briefs: [
        'Event camera frame of a swordsman spinning a blade: only the moving edges appear as red and blue dots on black, the sword arc a dense trail, the still background empty. No readable text.',
        'Event camera frame of hundreds of bats bursting from a cave mouth at dusk, each flapping wing edge a flicker of red and blue dots, the still rock face completely empty on mid grey. No readable text.',
        'Event camera frame of a galloping horse and armored rider, legs and cloak traced by dense red and blue dots, dust kicked up as scattered speckle, the static road invisible. No readable text.',
      ],
    },
    {
      name: 'Audio Spectrogram Imaging',
      domain: 'sound spectrogram',
      tags: ['spectrogram', 'sound', 'sensor'],
      dna: sensor(
        'Audio spectrogram: time runs left to right and frequency bottom to top, with sound energy as glowing color.',
        'drawn as sound energy in a spectrogram: harmonics as stacked lines, noise as clouds, silence dark.',
        'Magma or viridis color ramps on black.',
        'No light; brightness is sound energy.',
        'Harmonic stripes, noise clouds and pixel blocks.',
        'Wide horizontal time-frequency plot with no axis labels.',
        'Hidden, eerie, musical and precise.',
        'harmonic stripes; time-frequency; energy colors',
      ),
      avoid: AVOID,
      briefs: [
        'Audio spectrogram where the harmonics of a bell toll and a scream form the silhouette of a screaming skull, bright magma colors on black, noise clouds around it. No axis labels or readable text.',
        'Audio spectrogram of a dragon roar: a low rumble band at the bottom and rising harmonic curves that spread upward like wings, bright magma colors fading to purple noise on black. No axis labels or readable text.',
        'Audio spectrogram of a monastery choir: evenly stacked glowing harmonics rising and falling like the arches and spires of a cathedral, viridis colors on black, reverb tails as soft haze. No axis labels or readable text.',
      ],
    },
    {
      name: 'Infrared Reflectography',
      domain: 'art conservation imaging',
      tags: ['reflectography', 'conservation', 'sensor'],
      dna: sensor(
        'Infrared reflectography: a grey image of a painting that shows the hidden underdrawing and changed mind beneath the paint.',
        'the visible paint fades to grey, revealing the artist underdrawing: sketch lines, grid squares and corrections.',
        'Neutral greys with dark carbon lines.',
        'Even flat lighting.',
        'Faded paint, sketch lines and craquelure.',
        'Frontal view of a painting panel.',
        'Secretive, scholarly, quiet and revealing.',
        'underdrawing; corrections; grey paint layer',
      ),
      avoid: AVOID,
      briefs: [
        'Infrared reflectogram of an old painting of a saint and a dragon: the paint faded to grey, revealing sketched underdrawing lines, a squared grid and a second hidden dragon head the painter covered, fine craquelure. No readable text.',
        "Infrared reflectogram of an old portrait of a noblewoman: the paint faded to soft grey, revealing a skull sketched in carbon lines beneath her face, the painter's grid and a changed hand position. No readable text.",
        'Infrared reflectogram of a pastoral landscape painting revealing a sketched fortress and gallows hidden under the painted meadow, grey paint layer and craquelure. No readable text.',
      ],
    },
    {
      name: 'Multispectral Palimpsest Imaging',
      domain: 'manuscript recovery imaging',
      tags: ['palimpsest', 'multispectral', 'sensor'],
      dna: sensor(
        'Multispectral palimpsest: false-color processed manuscript where scraped-off earlier writing and drawings show in red over the later text.',
        'shown as a recovered layer on parchment: the hidden older image in red or magenta, later marks in grey.',
        'Pale grey parchment with recovered red.',
        'Even flat lighting.',
        'Parchment fibers, erased ink and holes.',
        'Flat page view.',
        'Scholarly, secret, ancient and haunting.',
        'recovered red layer; grey later text; parchment',
      ),
      avoid: AVOID,
      briefs: [
        'Multispectral palimpsest image of a parchment page where an erased drawing of a dragon devouring a sun reappears in red beneath grey blocks of later script shown as unreadable marks, worm holes and fibers. No readable text.',
        'Multispectral palimpsest page where a scraped-away drawing of a walled city and its gates returns in magenta beneath grey unreadable blocks of later script, holes and stitched tears in the parchment. No readable text.',
        'Multispectral palimpsest parchment revealing a faint erased portrait of a crowned queen in red, her eyes crossing through grey later marks, worn edges and fibers. No readable text.',
      ],
    },
    {
      name: 'Acoustic Camera Overlay',
      domain: 'sound source localization',
      tags: ['acoustic-camera', 'overlay', 'sensor'],
      dna: sensor(
        'Acoustic camera: an ordinary photo overlaid with colored sound hotspots showing where noise comes from.',
        'a normal photo with translucent sound-intensity blobs over the loud sources, red at the center fading to blue.',
        'Normal photo with red to blue overlay.',
        'Ordinary light plus overlay.',
        'Soft overlay blobs.',
        'Fixed camera view.',
        'Technical, revealing, strange and diagnostic.',
        'sound hotspots; photo overlay',
      ),
      avoid: AVOID,
      briefs: [
        'Acoustic camera image of a dark castle hall with a colored sound hotspot glowing red at a sealed wall where scratching comes from behind the stones, the rest quiet blue. No readable text.',
        'Acoustic camera image of a blacksmith forge: a normal photo with red-hot sound hotspots on the hammer and anvil, softer orange around the bellows, quiet blue elsewhere. No readable text.',
        'Acoustic camera view of an empty candlelit corridor where a red sound hotspot hangs in mid-air at head height where weeping is heard, nothing visible beneath it. No readable text.',
      ],
    },
    {
      name: 'MR Tractography',
      domain: 'diffusion MRI fiber tracking',
      tags: ['tractography', 'mri', 'sensor'],
      dna: sensor(
        'Tractography: bundles of fiber pathways color-coded by direction, glowing like silk threads.',
        'traced as bundles of streamlines color-coded by direction: red left-right, green front-back, blue up-down.',
        'Red, green and blue streamlines on black.',
        'Glow of streamlines.',
        'Fine silk-like strands.',
        'Isolated 3D subject on black.',
        'Intricate, beautiful, clinical and luminous.',
        'direction-coded streamlines; fiber bundles',
      ),
      avoid: AVOID,
      briefs: [
        'MR tractography rendering where fiber streamlines trace the body and wings of a sleeping dragon, color-coded red, green and blue on black, like glowing silk. No readable text.',
        'MR tractography of a crowned human head in profile, fiber streamlines through the brain glowing red, green and blue, and the crown outlined faintly as a ghostly shell on black. No readable text.',
        'Tractography-style rendering of a war horse in motion, muscle fiber streamlines along its neck and legs color-coded by direction, glowing like silk on black. No readable text.',
      ],
    },
    {
      name: 'EBSD Crystal Map',
      domain: 'crystal orientation mapping',
      tags: ['ebsd', 'microscopy', 'sensor'],
      dna: sensor(
        'EBSD map: metal grains shown as a mosaic of flat colored patches by crystal orientation.',
        'broken into grains colored by crystal orientation: flat rainbow patches with sharp grain boundaries.',
        'Pastel rainbow orientation colors.',
        'No light.',
        'Grain boundaries and flat patches.',
        'Flat map view.',
        'Precise, scientific, colorful and strange.',
        'grain mosaic; orientation colors',
      ),
      avoid: AVOID,
      briefs: [
        'EBSD crystal orientation map of a sword blade cross-section, grains shown as a rainbow mosaic of flat patches, the forge-folded layers visible as bands. No readable text.',
        'EBSD crystal orientation map of a cross-section of an old gold crown, grains as a mosaic of flat rainbow patches, jewel settings as black holes and sharp grain boundaries. No readable text.',
        'EBSD map of a polished iron meteorite slice with large interlocking crystal bands in pastel orientation colors, a dark fracture running through. No readable text.',
      ],
    },
    {
      name: 'Atomic Force Microscope Topography',
      domain: 'nanoscale surface topography',
      tags: ['afm', 'nanoscale', 'sensor'],
      dna: sensor(
        'AFM topography: a nanoscale surface shown as a 3D height map with a gold-brown color ramp.',
        'rendered as a height map: hills and pits from nanoscale scanning, with scan lines.',
        'Gold-brown height ramp.',
        'Virtual side light on height map.',
        'Scan lines and artifacts.',
        'Oblique 3D height view.',
        'Precise, alien, tiny and strange.',
        'height map; scan lines; gold ramp',
      ),
      avoid: AVOID,
      briefs: [
        'Atomic force microscope topography of a nanoscale surface where molecules form a castle on a hill, gold-brown height ramp, oblique 3D view, scan lines. No readable text.',
        'Atomic force microscope topography of a DNA strand coiling across a surface like a serpent, gold-brown height ramp, oblique 3D view, faint scan-line streaks. No readable text.',
        'Atomic force microscope height map of a crystal surface with stepped terraces like a ruined amphitheater, gold-brown height ramp, oblique 3D view and faint horizontal scan artifacts. No readable text.',
      ],
    },
    {
      name: 'Fluoroscopy',
      domain: 'live X-ray video',
      tags: ['fluoroscopy', 'x-ray', 'sensor'],
      dna: sensor(
        'Fluoroscopy: live X-ray video frame, grainy greyscale with dark bones and a circular field.',
        'shown as a grainy live X-ray frame: bones and dense objects dark, soft tissue faint, motion blur.',
        'Greyscale inverted.',
        'No light.',
        'Grain and blur.',
        'Circular field.',
        'Clinical, live, eerie and intimate.',
        'circular field; grainy live X-ray',
      ),
      avoid: AVOID,
      briefs: [
        'Fluoroscopy frame of an armored hand gripping a sword hilt, bones dark inside the faint metal gauntlet, grainy circular field with motion blur. No readable text.',
        'Fluoroscopy frame of a cat mid-leap, spine and legs dark and crisp, fur a faint haze, grainy circular field with motion blur. No readable text.',
        'Fluoroscopy frame of a swallowed iron key inside a faint stomach outline, the key dark and sharp, ribs and spine soft grey, grainy circular field with slight motion blur. No readable text.',
      ],
    },
    {
      name: 'Water Vapor Satellite Imagery',
      domain: 'meteorological satellite',
      tags: ['water-vapor', 'satellite', 'sensor'],
      dna: sensor(
        'Water vapor satellite image: swirling moisture in the upper atmosphere shown in grey or blue-orange false color.',
        'seen from orbit as water vapor: moist swirls bright, dry slots dark, jet streams and storms.',
        'Grey or blue-orange false color.',
        'No light.',
        'Swirls, filaments and coastlines.',
        'Top-down satellite view.',
        'Vast, turbulent, moody and planetary.',
        'vapor swirls; dry slots; storms',
      ),
      avoid: AVOID,
      briefs: [
        'Water vapor satellite image of a vast storm swirl shaped like a dragon coiling over a continent, moist bright swirls and dark dry slots, coastlines faint. No readable text.',
        'Water vapor satellite image of a hurricane with a clear eye and spiral bands, bright moist swirls against dark dry slots, blue-orange false color, faint coastlines. No readable text.',
        'Water vapor satellite image of jet stream ribbons wrapping around a continent like serpents, bright moisture filaments and dark dry air. No readable text.',
      ],
    },
    {
      name: 'Mass Spectrometry Imaging',
      domain: 'molecular distribution map',
      tags: ['mass-spec', 'imaging', 'sensor'],
      dna: sensor(
        'Mass spectrometry imaging: pixelated maps of where molecules sit in a tissue slice, hot colors on black.',
        'mapped as molecular distribution: pixelated hot-colored patches on black.',
        'Hot colormap on black.',
        'No light.',
        'Pixelated maps.',
        'Flat slice.',
        'Scientific, abstract, precise and hidden.',
        'pixelated molecule map; hot colors',
      ),
      avoid: AVOID,
      briefs: [
        'Mass spectrometry image of a plant slice where a molecule is distributed in the shape of a crowned serpent, pixelated hot colors on black. No readable text.',
        'Mass spectrometry image of a mushroom slice with molecules mapped in pixelated hot colors, gills glowing yellow and the cap edge red on black. No readable text.',
        'Mass spectrometry map of a leaf where one molecule gathers along the veins in hot orange pixels, forming a tree shape on black. No readable text.',
      ],
    },
    {
      name: 'Streak Camera Image',
      domain: 'ultrafast streak imaging',
      tags: ['streak-camera', 'ultrafast', 'sensor'],
      dna: sensor(
        'Streak camera: one line of space smeared across time into a glowing streak pattern.',
        'turned into streaks: a single line of space stretched over time.',
        'Glowing green or false color on black.',
        'Streak glow.',
        'Smeared streaks.',
        'Horizontal streak.',
        'Fast, abstract, scientific and eerie.',
        'space-time streak',
      ),
      avoid: AVOID,
      briefs: [
        'Streak camera image of a lightning strike hitting a castle tower, the strike smeared into a glowing green time streak on black. No readable text.',
        'Streak camera image of an explosion in a castle powder room, a single slit of the blast smeared into fanning green time streaks on black, bright at the start and fading. No readable text.',
        'Streak camera image of a laser pulse passing through a crystal, a thin bright streak splitting into colored lines on black. No readable text.',
      ],
    },
    {
      name: 'Endoscopy Capsule View',
      domain: 'capsule camera',
      tags: ['endoscopy', 'capsule', 'sensor'],
      dna: sensor(
        'Capsule endoscopy: a fisheye camera view with ring light inside a wet tunnel, pink and glossy.',
        'seen from a tiny capsule camera: fisheye tunnel, ring light, wet glossy walls.',
        'Pinks and reds with glossy highlights.',
        'Ring light.',
        'Wet glossy walls.',
        'Fisheye tunnel.',
        'Claustrophobic, intimate, strange and alien.',
        'fisheye; ring light; wet tunnel',
      ),
      avoid: AVOID,
      briefs: [
        'Capsule endoscopy fisheye view inside a wet stone tunnel beneath a castle, ring light glinting on glossy walls, a tiny lost ring lying ahead. No readable text.',
        'Capsule endoscopy fisheye view down the throat of a sleeping dragon, ring light glinting on glossy red walls and ridged cartilage, a faint ember glow deep ahead. No readable text.',
        'Endoscopy capsule view inside an old copper pipe, green corrosion and water drops on the walls, ring light and fisheye distortion. No readable text.',
      ],
    },
    {
      name: 'Radio Telescope Intensity Map',
      domain: 'radio astronomy',
      tags: ['radio-telescope', 'astronomy', 'sensor'],
      dna: sensor(
        'Radio telescope map: blurry false-color radio emission with lobes and jets.',
        'mapped as radio emission: blobs, lobes, jets and contour lines.',
        'False-color on black.',
        'No light.',
        'Blurry emission and contours.',
        'Sky map.',
        'Cosmic, mysterious, scientific and vast.',
        'radio lobes; jets; contours',
      ),
      avoid: AVOID,
      briefs: [
        'Radio telescope map of a galaxy whose radio lobes form the wings of a dragon, false-color emission and contour lines on black. No readable text.',
        'Radio telescope map of a pulsar and its wind nebula shaped like a lighthouse beam, false-color emission and contour lines on black. No readable text.',
        'Radio telescope map of a nebula whose false-color emission blobs form a hooded figure bowing its head, soft contour lines, a bright point like a lantern in its hands. No readable text.',
      ],
    },
    {
      name: 'Solar H-Alpha Telescope',
      domain: 'solar telescope',
      tags: ['h-alpha', 'sun', 'sensor'],
      dna: sensor(
        'H-alpha solar telescope: the sun in deep red-orange with prominences and filaments.',
        'shown in H-alpha: red-orange disk, prominences, filaments and granular texture.',
        'Red-orange on black.',
        'Solar glow.',
        'Granulation and filaments.',
        'Sun disk or limb.',
        'Fiery, vast, cosmic and dramatic.',
        'prominences; filaments; red disk',
      ),
      avoid: AVOID,
      briefs: [
        'H-alpha solar telescope image of the sun limb with a huge prominence shaped like a rearing dragon, deep red-orange granulation, filaments on the disk. No readable text.',
        'H-alpha solar telescope close-up of a large sunspot with dark umbra and fibrous penumbra like an eye, red-orange granulation around it. No readable text.',
        'H-alpha full solar disk with dark filaments snaking across it and bright plage areas, prominences on the limb like flames, black background. No readable text.',
      ],
    },
    {
      name: 'All-Sky Meteor Camera',
      domain: 'fisheye night sky camera',
      tags: ['all-sky', 'meteor', 'sensor'],
      dna: sensor(
        'All-sky camera: a circular fisheye night sky with meteor streaks, horizon ring and trees.',
        'seen from an all-sky camera: circular fisheye, horizon at the rim, meteors and stars.',
        'Dark blue night with white streaks.',
        'Starlight.',
        'Noise, star trails.',
        'Circular fisheye.',
        'Vast, quiet, cosmic and watchful.',
        'circular fisheye; meteor streaks',
      ),
      avoid: AVOID,
      briefs: [
        'All-sky meteor camera frame: circular fisheye night sky ringed by dark pine silhouettes and a castle tower at the rim, a bright fireball streaking across the center, noisy stars. No readable text.',
        'All-sky camera frame of green and violet aurora curtains filling the fisheye circle, pine silhouettes and a stone watchtower around the rim, noisy stars. No readable text.',
        'All-sky camera long exposure of a meteor shower, dozens of white streaks radiating from one point, circular horizon of mountains and a small chapel. No readable text.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
