import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Horror cinema of the 1980s: each preset names its film and director and rebuilds that film's
// production look (practical effects, lighting, lensing, color). Cards stage original moments.
const T = ['horror-80s', 'horror-cinema'];
const film80 =
  'Eighties 35mm film grain, diffusion glow on highlights and rich saturated print color.';

const spec: Spec = {
  pack: 'pack_27',
  category: '2. Horror Cinema 80s',
  newCategory: { id: 'horror-cinema-80s' },
  updates: {},
  creates: [
    cr('The Shining 1980 - Symmetrical Hotel Dread', 'eighties horror cinema', [...T, 'shining'], {
      look: 'Stanley Kubrick The Shining (1980) look: one-point perspective symmetry, gliding steadicam through vast empty hotel corridors, patterned carpets and cold overlit rooms.',
      subject:
        'stage the subject in perfectly symmetrical one-point perspective corridors and vast empty rooms.',
      color: 'Hotel red, mustard, mint green and cold white overlight.',
      light: 'Flat cold overlighting with no hiding shadows.',
      texture: film80,
      camera: 'Perfect one-point perspective symmetry and low gliding steadicam.',
      mood: 'cold isolating dread',
      render: 'Precise symmetrical eighties horror film frame.',
      key: 'Kubrick symmetry; one-point perspective; patterned carpet; steadicam',
      avoid: [
        'twin girls in blue dresses',
        'a hexagon patterned carpet',
        'a man breaking through a door with an axe',
      ],
      briefs: [
        'In perfect one-point perspective, a hotel night auditor pushes a laundry cart down an endless symmetrical corridor of identical doors while, far at the vanishing point, one door stands open and glowing. Only the cart’s squeaking wheel breaks the silence. No readable text or logo.',
        'In a vast cold ballroom lit like an operating theater, a lone bartender polishes glasses for a party that ended fifty years ago. Every chair is still perfectly aligned. No readable text or logo.',
        'At the end of a snowy hedge maze seen from above, a single red mitten lies in perfect symmetry at the exact center. Fresh snow is slowly covering it. No readable text or logo.',
      ],
    }),
    cr(
      'The Thing 1982 - Arctic Practical Effects Paranoia',
      'eighties horror cinema',
      [...T, 'the-thing'],
      {
        look: 'John Carpenter The Thing (1982) look: blue-lit Antarctic station, blizzard darkness, flare-lit paranoia, frost-crusted beards and grotesque practical creature effects.',
        subject: 'stage the subject in a blue-lit icy research station with flare light and frost.',
        color: 'Icy blue, flare red and dark snow shadow.',
        light: 'Cold blue night light and red handheld flares.',
        texture: film80,
        camera: 'Anamorphic tense group framing and snowy wides.',
        mood: 'freezing paranoid tension',
        render: 'Tense anamorphic eighties Antarctic horror frame.',
        key: 'The Thing arctic blue; flares; paranoia; practical effects',
        avoid: ['a dog splitting open into tentacles'],
        briefs: [
          'In a blue-lit Antarctic research station during a blizzard, six frost-bearded scientists hold red flares and stare at each other around a table where a chessboard has rearranged itself. Nobody admits touching it. No readable text or logo.',
          'A lone cook trudges through a whiteout toward the station’s glowing kennel, a red flare sputtering in his glove. Something inside has stopped barking. No readable text or logo.',
          'A frozen sled lies overturned in the snow outside a dark station under a sky full of cold stars. One set of footprints leads away and then ends. No readable text or logo.',
        ],
      },
    ),
    cr('Evil Dead 1981 - Shaky-Cam Cabin Frenzy', 'eighties horror cinema', [...T, 'evil-dead'], {
      look: 'Sam Raimi The Evil Dead (1981) look: rushing low shaky-cam through fog-bound woods, cramped cabin, dutch angles, crash zooms and frantic low-budget energy.',
      subject: 'stage the subject in a cramped woodland cabin with rushing low camera energy.',
      color: 'Murky forest green, cabin brown and lurid highlights.',
      light: 'Swinging lamp light and misty moonlight.',
      texture: 'Grainy low-budget 16mm blown to 35mm.',
      camera: 'Rushing low POV through woods, dutch angles and crash zooms.',
      mood: 'frantic manic terror',
      render: 'Frantic low-budget eighties cabin horror frame.',
      key: 'Raimi shaky cam; cabin in woods; dutch angles; frenzy',
      avoid: ['a chainsaw hand', 'a flesh-bound book with a face'],
      briefs: [
        'Rushing low through foggy woods at impossible speed, the camera closes in on a cabin porch where a startled birdwatcher drops his binoculars. A swinging lamp inside tilts every shadow sideways. No readable text or logo.',
        'Inside a cramped cabin, a dentist barricades the trapdoor with a piano while the floorboards bulge. The dutch-angled room seems to lean in with him. No readable text or logo.',
        'A cellar door rattles on its hinges in a moonlit cabin as a tape recorder spins by itself on the table. The whole room is slightly crooked. No readable text or logo.',
      ],
    }),
    cr(
      'A Nightmare on Elm Street 1984 - Dream Boiler Room',
      'eighties horror cinema',
      [...T, 'elm-street'],
      {
        look: 'Wes Craven A Nightmare on Elm Street (1984) look: suburban bedrooms melting into steaming boiler rooms, dream logic transitions, red and green lighting and practical surreal effects.',
        subject:
          'stage the subject where cozy suburban rooms melt into steaming industrial dream spaces.',
        color: 'Boiler-room red and green with suburban pastel.',
        light: 'Red and green industrial light and steam.',
        texture: film80,
        camera: 'Dream transitions from bedrooms into boiler rooms.',
        mood: 'surreal dream dread',
        render: 'Surreal eighties dream horror frame.',
        key: 'Elm Street dream boiler room; red and green; melting rooms',
        avoid: ['a burned man in a striped sweater with a bladed glove'],
        briefs: [
          'A night-shift nurse falls asleep on her floral bedspread and the wallpaper stretches like rubber into a steaming red and green boiler room full of hissing pipes. Her slippers are still on her feet. No readable text or logo.',
          'A bathtub fills with warm water in a pastel bathroom, and beneath the surface a staircase descends into a glowing boiler room. Bubbles rise from very far below. No readable text or logo.',
          'A single fedora hangs on a boiler room pipe in hissing steam and red light. Water drips steadily from its brim. No readable text or logo.',
        ],
      },
    ),
    cr('Hellraiser 1987 - Blue Chains Sacrament', 'eighties horror cinema', [...T, 'hellraiser'], {
      look: 'Clive Barker Hellraiser (1987) look: shadowy London house, blue otherworldly light, rattling hooks and chains, leather and gothic pain-as-ritual imagery.',
      subject:
        'stage the subject in shadowy rooms flooded with cold blue light and rattling chains.',
      color: 'Cold blue light, black leather and dim candle gold.',
      light: 'Otherworldly blue beams through dust.',
      texture: film80,
      camera: 'Gothic compositions with hanging chains.',
      mood: 'ritual gothic menace',
      render: 'Gothic eighties British horror frame.',
      key: 'Hellraiser blue light; chains and hooks; gothic ritual',
      avoid: ['a pale figure with nails in the head', 'a golden puzzle box'],
      briefs: [
        'In a shadowy London attic, an antique dealer opens a lacquered jewelry box and cold blue light pours out while chains quietly rattle down from the rafters. Dust hangs in the beams. No readable text or logo.',
        'A dripping ceiling in a gothic townhouse glows blue as a woman in a black dress lights candles beneath it. The floorboards pulse slowly. No readable text or logo.',
        'Rows of empty hooks sway gently in a dusty attic flooded with cold blue light. Somewhere below, a church bell is tolling for no one at all. No readable text or logo.',
      ],
    }),
    cr('Poltergeist 1982 - TV Static Suburb', 'eighties horror cinema', [...T, 'poltergeist'], {
      look: 'Tobe Hooper Poltergeist (1982) look: warm Spielbergian suburbia, glowing television static, swirling light vortexes, flying toys and cozy family homes turning uncanny.',
      subject:
        'stage the subject in warm suburban homes lit by glowing television static and swirling light.',
      color: 'Warm suburban tones with glowing static blue-white.',
      light: 'Glowing TV static light and swirling white vortex glow.',
      texture: film80,
      camera: 'Cozy family interiors with uncanny light events.',
      mood: 'uncanny suburban wonder',
      render: 'Warm eighties supernatural suburban frame.',
      key: 'Poltergeist TV static; suburban glow; light vortex',
      avoid: ['a clown doll under a bed', 'a girl touching a television screen'],
      briefs: [
        'In a cozy suburban living room at 3 a.m., a retired couple in pajamas watch their television glow with pure static while every houseplant slowly turns its leaves toward the screen. The kettle begins to float. No readable text or logo.',
        'Kitchen chairs stack themselves into a perfect tower while a mother goes to fetch milk. She has been gone only ten seconds. No readable text or logo.',
        'A glowing swirl of white light fills an empty closet door in a dark bedroom. Toys drift slowly toward it. No readable text or logo.',
      ],
    }),
    cr(
      'Videodrome 1983 - Cronenberg Body Television',
      'eighties body horror cinema',
      [...T, 'videodrome'],
      {
        look: 'David Cronenberg Videodrome (1983) look: grimy cathode-ray media, breathing television sets, organic technology, cold Toronto apartments and body-horror practical effects.',
        subject:
          'stage the subject with organic breathing technology and grimy cathode-ray screens.',
        color: 'Cold grey, flesh pink and CRT blue.',
        light: 'Cold apartment light and glowing CRT screens.',
        texture: film80,
        camera: 'Cold clinical framing of organic machines.',
        mood: 'clinical body dread',
        render: 'Clinical eighties body horror frame.',
        key: 'Cronenberg organic tech; breathing TV; body horror',
        briefs: [
          'In a cold grey apartment, a television set breathes slowly on its stand, the screen bulging outward like skin as a sleepless late-night programmer leans closer. A videotape pulses on the table. No readable text or logo.',
          'A VCR drips warm fluid onto a shag carpet while its owner calmly reads the manual. The tape inside has started to hum. No readable text or logo.',
          'An old CRT television glows alone in an empty studio, its screen showing a fleshy pattern. The cables on the floor twitch. No readable text or logo.',
        ],
      },
    ),
    cr(
      'An American Werewolf in London 1981 - Moonlit Moor Transformation',
      'eighties horror cinema',
      [...T, 'american-werewolf'],
      {
        look: 'John Landis An American Werewolf in London (1981) look: foggy Yorkshire moors, cozy pubs, full moons, darkly comic tone and practical transformation effects under bright light.',
        subject:
          'stage the subject in foggy moors and cozy pubs under full moons with dark comedy.',
        color: 'Foggy moor grey, pub amber and moon silver.',
        light: 'Full moonlight and warm pub glow.',
        texture: film80,
        camera: 'Moor wides and brightly lit transformation close-ups.',
        mood: 'darkly comic dread',
        render: 'Darkly comic eighties horror frame.',
        key: 'Moors and pubs; full moon; comic dread; transformation',
        briefs: [
          'In a cozy moorland pub under a full moon, two backpacking accountants order hot soup while every regular silently turns to stare at them and the darts player misses the board. The fog outside presses against the glass. No readable text or logo.',
          'A businessman wakes up naked in a zoo enclosure among very confused wolves. The morning visitors have started to arrive. No readable text or logo.',
          'A full moon rises over a foggy moor as a single signpost creaks in the wind. A lone howl drifts across the heather. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Fly 1986 - Telepod Laboratory Metamorphosis',
      'eighties body horror cinema',
      [...T, 'the-fly'],
      {
        look: 'David Cronenberg The Fly (1986) look: cluttered warehouse laboratory, sleek telepods, tragic romance, warm lamp light and gradual body metamorphosis.',
        subject:
          'stage the subject in a cluttered warehouse lab with sleek pod machines and tragic metamorphosis.',
        color: 'Warm warehouse amber and sterile pod steel.',
        light: 'Warm lamp light and clinical pod glow.',
        texture: film80,
        camera: 'Intimate lab compositions.',
        mood: 'tragic metamorphic unease',
        render: 'Intimate eighties body horror frame.',
        key: 'Telepods; warehouse lab; tragic metamorphosis',
        briefs: [
          'In a cluttered warehouse laboratory, a baker steps out of a sleek glowing pod after testing it with a loaf of bread, and the bread in her hand now has a tiny pair of wings. She laughs nervously. No readable text or logo.',
          'A scientist’s bathroom cabinet is lined with jars of his own shed fingernails. He labels each one neatly. No readable text or logo.',
          'Two steaming pods glow side by side in a dark warehouse. A single housefly circles the lamp above them. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Re-Animator 1985 - Glowing Green Serum',
      'eighties horror comedy cinema',
      [...T, 're-animator'],
      {
        look: 'Stuart Gordon Re-Animator (1985) look: medical school basements, glowing neon green serum, splatter comedy and garish eighties lighting.',
        subject: 'stage the subject in basement labs lit by glowing neon green serum.',
        color: 'Neon green serum, morgue grey and garish red.',
        light: 'Glowing green chemical light.',
        texture: film80,
        camera: 'Garish lab and morgue compositions.',
        mood: 'garish macabre comedy',
        render: 'Garish eighties splatter comedy frame.',
        key: 'Glowing green serum; morgue labs; macabre comedy',
        briefs: [
          'In a medical school basement lit by vials of glowing neon green serum, a nervous student revives a houseplant that immediately starts lunging at him. His professor takes careful notes. No readable text or logo.',
          'A morgue drawer slides open by itself while a janitor mops the floor. Green light seeps out of it. No readable text or logo.',
          'A single syringe of glowing green fluid rests on a steel tray. The tray is trembling. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Possession 1981 - Żuławski Hysteria Berlin',
      'eighties art horror cinema',
      [...T, 'possession'],
      {
        look: 'Andrzej Żuławski Possession (1981) look: cold divided Berlin apartments, restless handheld camera, blue-grey palette and raw hysterical emotion.',
        subject:
          'stage the subject in cold blue-grey Berlin apartments with restless handheld intensity.',
        color: 'Cold blue-grey and pale skin.',
        light: 'Flat cold daylight.',
        texture: film80,
        camera: 'Restless circling handheld camera.',
        mood: 'raw hysterical dread',
        render: 'Raw eighties art horror frame.',
        key: 'Żuławski blue-grey; Berlin; restless camera; hysteria',
        briefs: [
          'In a cold blue-grey Berlin apartment beside the Wall, a translator circles her kitchen with a bag of groceries spilling while the camera spins restlessly around her. The milk carton leaks across the tiles. No readable text or logo.',
          'A man sits on a bare mattress in an empty flat staring at a locked door. Something behind it breathes slowly. No readable text or logo.',
          'An empty subway corridor in cold grey light echoes with dropped groceries. A single egg rolls toward the camera. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Opera 1987 - Argento Theater Terror',
      'eighties Italian horror cinema',
      [...T, 'opera-87'],
      {
        look: 'Dario Argento Opera (1987) look: grand opera house, swooping raven point-of-view camera, candlelit backstage, baroque staging and elegant terror.',
        subject:
          'stage the subject in a grand opera house with swooping camera and candlelit backstage.',
        color: 'Opera red velvet, gold and deep shadow.',
        light: 'Candlelit backstage and stage spotlights.',
        texture: film80,
        camera: 'Swooping bird’s-eye camera through the auditorium.',
        mood: 'elegant operatic terror',
        render: 'Baroque eighties Italian horror frame.',
        key: 'Argento opera house; swooping ravens; candlelight',
        briefs: [
          'Swooping like a bird through a grand opera house, the camera dives past gilded balconies toward an understudy singing alone on stage. A flock of ravens roosts silently in the rafters above. No readable text or logo.',
          'Backstage by candlelight, a costume maker sews a gown while someone breathes behind the rack. The needle stops mid-stitch. No readable text or logo.',
          'An empty red velvet box seat glows under a single spotlight. The opera glasses on the chair are still warm. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Lost Boys 1987 - Neon Boardwalk Vampires',
      'eighties horror cinema',
      [...T, 'lost-boys'],
      {
        look: 'Joel Schumacher The Lost Boys (1987) look: neon seaside boardwalk, bonfires on the beach, leather jackets, carnival lights and stylish MTV vampire glamour.',
        subject:
          'stage the subject on neon boardwalks and bonfire beaches with stylish eighties glamour.',
        color: 'Neon pink, carnival gold and night blue.',
        light: 'Neon and carnival lights with bonfire glow.',
        texture: film80,
        camera: 'Stylish MTV-era compositions and slow motion.',
        mood: 'stylish neon menace',
        render: 'Stylish eighties vampire frame.',
        key: 'Lost Boys neon boardwalk; bonfires; eighties glamour',
        avoid: ['a gang of leather-jacketed vampire bikers'],
        briefs: [
          'On a neon-lit seaside boardwalk, a middle-aged comic book store owner eyes a group of pale carnival workers who never seem to blink under the ferris wheel lights. The tide is coming in fast. No readable text or logo.',
          'A beach bonfire burns while its dancers cast no shadows on the sand. The saxophone player keeps playing. No readable text or logo.',
          'A carousel spins alone at midnight on an empty neon boardwalk. Its music box plays slightly too slow. No readable text or logo.',
        ],
      },
    ),
    cr('Near Dark 1987 - Dusty Western Vampires', 'eighties horror cinema', [...T, 'near-dark'], {
      look: 'Kathryn Bigelow Near Dark (1987) look: dusty Oklahoma highways, blue dusk, blackened motel windows, harsh daylight burns and neo-western vampire road movie.',
      subject: 'stage the subject on dusty highways and dark motels at blue dusk.',
      color: 'Blue dusk, dust brown and neon motel red.',
      light: 'Blue twilight and harsh morning sun.',
      texture: film80,
      camera: 'Wide western highway compositions.',
      mood: 'dusty nocturnal menace',
      render: 'Neo-western eighties horror frame.',
      key: 'Near Dark dusty highways; blue dusk; motels',
      briefs: [
        'At blue dusk on an empty Oklahoma highway, a waitress waves goodbye to a family in a battered RV whose windows are all painted black. The sun is setting just in time. No readable text or logo.',
        'A roadside bar glows red at night as a pale drifter orders nothing and watches the door. The jukebox changes songs by itself. No readable text or logo.',
        'A motel room door hangs open with sunlight pouring in on a scorched carpet. Dust swirls in the beam. No readable text or logo.',
      ],
    }),
    cr(
      'Return of the Living Dead 1985 - Punk Zombie Night',
      'eighties horror comedy cinema',
      [...T, 'return-living-dead'],
      {
        look: 'Dan O’Bannon The Return of the Living Dead (1985) look: punk rock cemeteries, medical warehouse, rain-soaked night, chemical gas, neon punks and gleeful zombie comedy.',
        subject:
          'stage the subject in punk rock cemeteries and warehouses on rainy chemical nights.',
        color: 'Neon punk colors, toxic yellow and rain grey.',
        light: 'Rainy night and toxic gas glow.',
        texture: film80,
        camera: 'Punk comedy compositions in graveyards.',
        mood: 'gleeful punk mayhem',
        render: 'Punk eighties zombie comedy frame.',
        key: 'Punk graveyard; toxic gas; rainy night; zombie comedy',
        briefs: [
          'In a rain-soaked cemetery at night, punks with neon mohawks dance on gravestones as a yellow chemical cloud rolls in and the ground starts to crack beneath their boots. Nobody stops dancing. No readable text or logo.',
          'A medical supply warehouse worker opens a dented barrel and yellow gas hisses out. His boss is on the phone. No readable text or logo.',
          'A gravestone tips over in the rain, revealing a muddy hand holding a cassette tape. The tape is still playing. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Tetsuo the Iron Man 1989 - Metal Fetish Cyberpunk',
      'eighties Japanese cyberpunk cinema',
      [...T, 'tetsuo'],
      {
        look: 'Shinya Tsukamoto Tetsuo: The Iron Man (1989) look: frantic black-and-white 16mm, stop-motion metal growth, industrial Tokyo and grinding cyberpunk body horror.',
        subject:
          'stage the subject in frantic black-and-white industrial Tokyo with metal growing from bodies.',
        color: 'High-contrast black and white only.',
        light: 'Harsh industrial light.',
        texture: 'Grainy 16mm black and white and stop-motion metal.',
        camera: 'Frantic stop-motion and speeding handheld.',
        mood: 'frantic industrial frenzy',
        render: 'Frantic black-and-white cyberpunk frame.',
        key: 'Tetsuo metal growth; frantic 16mm; industrial Tokyo',
        briefs: [
          'In frantic black-and-white 16mm, a salaryman stares at his shaving mirror as tiny screws and wires sprout from his cheek, the bathroom walls covered in industrial pipes. The electric razor buzzes on its own. No readable text or logo.',
          'Scrap metal crawls across a Tokyo street in stop-motion toward a sleeping commuter. The streetlights flicker in rhythm. No readable text or logo.',
          'A single metal bolt spins upright on a grimy factory floor under harsh black-and-white light. It hums louder with every turn as the pipes around it tremble. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Society 1989 - Glossy Suburban Shunting',
      'eighties satirical horror cinema',
      [...T, 'society'],
      {
        look: 'Brian Yuzna Society (1989) look: glossy Beverly Hills wealth, pastel mansions, bright satire turning into surreal melting practical effects.',
        subject: 'stage the subject in glossy pastel wealth that turns surreal and melting.',
        color: 'Glossy pastel pink, pool blue and gold.',
        light: 'Bright glossy wealthy light.',
        texture: film80,
        camera: 'Glossy satirical compositions.',
        mood: 'glossy surreal satire',
        render: 'Glossy eighties satirical horror frame.',
        key: 'Society glossy wealth; pastel mansions; surreal melting',
        briefs: [
          'At a glossy pastel mansion pool party, the wealthy guests’ smiles stretch a little too wide as they lean closer and closer to the new tennis coach. Their champagne glasses begin to melt. No readable text or logo.',
          'A debutante’s portrait on the wall slowly melts into the frame while guests applaud. The butler keeps pouring. No readable text or logo.',
          'An empty pink sun lounger sits by a glowing pool at dusk. The water ripples without wind. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Prince of Darkness 1987 - Canister Church Dread',
      'eighties horror cinema',
      [...T, 'prince-darkness'],
      {
        look: 'John Carpenter Prince of Darkness (1987) look: abandoned downtown church, swirling green liquid in a glass canister, scientists and priests under siege and grainy dream transmissions.',
        subject: 'stage the subject in an abandoned church lit by a glowing swirling canister.',
        color: 'Sickly green glow and church stone grey.',
        light: 'Green canister glow and candles.',
        texture: film80,
        camera: 'Anamorphic siege compositions.',
        mood: 'cosmic besieged dread',
        render: 'Anamorphic eighties cosmic horror frame.',
        key: 'Carpenter church; glowing canister; cosmic dread',
        briefs: [
          'In an abandoned downtown church, a team of graduate physicists in cardigans stands around a glass canister of swirling green liquid while homeless onlookers outside stand perfectly still in rows. The candles lean toward the glass. No readable text or logo.',
          'A priest reads ancient text by flashlight while insects gather on the windows. Their number keeps growing. No readable text or logo.',
          'A grainy video frame shows a church doorway with a shadow standing in it. The timestamp is tomorrow. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Gremlins 1984 - Holiday Creature Chaos',
      'eighties horror comedy cinema',
      [...T, 'gremlins'],
      {
        look: 'Joe Dante Gremlins (1984) look: snowy small-town Christmas, cozy Americana, practical creature puppets, and holiday chaos turning mischievous and scary.',
        subject:
          'stage the subject in cozy snowy Christmas Americana overrun by mischievous small creatures.',
        color: 'Christmas red, snow white and warm lights.',
        light: 'Warm holiday lights and snowy night glow.',
        texture: film80,
        camera: 'Cozy town wides and chaotic interiors.',
        mood: 'mischievous holiday chaos',
        render: 'Cozy eighties creature comedy frame.',
        key: 'Snowy Christmas Americana; creature chaos; holiday lights',
        avoid: ['a furry big-eared creature with brown and white fur', 'reptilian gremlins'],
        briefs: [
          'In a snowy small town decorated for Christmas, a crowd of tiny mischievous creatures of original design steals every string of lights from the main street while a baffled mailman watches holding a fruitcake. No readable text or logo.',
          'A department store Santa discovers small creatures nesting in his sack. They are wearing his reindeer antlers. No readable text or logo.',
          'A single snow globe cracks on a windowsill as tiny footprints lead away through the frost. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Sweet Home 1989 - Japanese Fresco Haunting',
      'eighties Japanese horror cinema',
      [...T, 'sweet-home-89'],
      {
        look: 'Kiyoshi Kurosawa Sweet Home (1989) look: abandoned Japanese mansion, cursed fresco paintings, crumbling rooms and practical special effects by Dick Smith.',
        subject: 'stage the subject in a crumbling Japanese mansion with cursed fresco walls.',
        color: 'Dusty mansion browns, fresco ochre and shadow.',
        light: 'Dusty shafts of daylight and flashlights.',
        texture: film80,
        camera: 'Explorer compositions through crumbling rooms.',
        mood: 'creeping cursed dread',
        render: 'Eerie eighties Japanese haunted house frame.',
        key: 'Sweet Home frescoes; crumbling mansion; cursed paintings',
        briefs: [
          'A small documentary crew explores a crumbling Japanese mansion and finds a huge cursed fresco whose painted figures have faces that match the crew exactly. The cameraman keeps filming. No readable text or logo.',
          'A flashlight beam crosses a dusty hallway revealing a baby carriage and a fresh pair of footprints. The dust has not settled. No readable text or logo.',
          'A cracked fresco of a mother and child glows faintly in a dark mansion room. Plaster keeps falling from it. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
