import type { Spec } from '../tools/apply';
import { MATERIAL_AVOID as AVOID, material } from './_material';

const spec: Spec = {
  pack: 'pack_09',
  category: '1. Natural Materials',
  updates: {
    'SP09-001': {
      dna: material(
        'Raw oak wood: unfinished quarter-sawn oak with open grain, ray flecks and dry, matte fibers.',
        'the target becomes carved or built from raw oak, with grain following its form and tool marks at edges.',
        'Pale honey to mid brown with darker grain lines.',
        'Warm side light raking across the open grain.',
        'Open-pore oak grain, medullary ray flecks, splits and adze marks.',
        'Solid, honest, warm and old.',
        'raw open oak grain; ray flecks; tool marks; matte dry fibers',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a life-size warhorse carved entirely from raw oak, grain flowing along its muscles and adze marks on the mane, standing in a misty meadow. No text or logo.',
        "Photograph of a knight's full armor made of raw unfinished oak planks and pegs, worn by an adult man in a forest clearing. No text or logo.",
        'Photograph of a raw oak spiral staircase rising through an empty stone tower, grain lines flowing up each step. No text or logo.',
      ],
    },
    'SP09-002': {
      dna: material(
        'Polished mahogany: deep red-brown hardwood with a mirror-like French polish and flowing figure.',
        'the target is made of polished mahogany with a deep lacquered finish and figure that follows its curves.',
        'Deep red-brown to near-black with amber highlights.',
        'Warm lamp light producing glossy reflections.',
        'French-polished mahogany with ribbon figure, deep gloss and inlay lines.',
        'Rich, formal, warm and antique.',
        'polished mahogany gloss; ribbon figure; amber highlights; deep red-brown',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a full-size dragon skeleton made of polished mahogany with brass joints displayed in a candlelit hall. No text or logo.',
        'Photograph of a polished mahogany suit of armor with inlaid lines standing in a library corner. No text or logo.',
        'Photograph of a slender racing rowboat built from mirror-polished mahogany gliding across a black lake at dawn, the flowing flame figure of the grain visible through deep French polish, mist and the reflection of pines on the hull. No text or logo.',
      ],
    },
    'SP09-003': {
      dna: material(
        'Birch bark: papery white bark with dark horizontal lenticels, curling peels and chalky texture.',
        'the target is wrapped or built from birch bark sheets with peeling curls and dark lenticel dashes.',
        'Chalk white, cream and charcoal marks with peach inner bark.',
        'Soft cool daylight.',
        'Papery peeling bark layers with black lenticels and curls.',
        'Northern, quiet, delicate and wild.',
        'papery white bark; dark lenticels; curling peels; peach inner layer',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a tall hooded figure whose cloak is layers of peeling birch bark standing in a snowy forest. No text or logo.',
        'Photograph of a violin made from curled sheets of birch bark resting on green moss in a forest clearing, dark horizontal lenticels running across its body, peeling papery edges and chalky white texture in soft overcast light. No text or logo.',
        'Photograph of a small wayside chapel clad entirely in overlapping birch bark sheets at dusk, curled peels lifting at the corners, dark lenticel stripes and a single candle glowing through the open door. No text or logo.',
      ],
    },
    'SP09-004': {
      dna: material(
        'Polished granite: speckled crystalline stone polished to a hard reflective surface.',
        'the target is carved from granite and polished, with mineral speckles visible across its surfaces.',
        'Grey, black and pink speckle or black granite with mica sparkle.',
        'Crisp light producing sharp reflections.',
        'Polished granite with feldspar, quartz and mica grains.',
        'Hard, permanent, cold and monumental.',
        'polished speckled granite; mica sparkle; hard reflections; crystalline grain',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a colossal polished black granite bull standing in a rain-soaked plaza, reflections sliding on its flanks. No text or logo.',
        'Photograph of a grand piano carved from polished pink granite in an empty concert hall, speckled feldspar crystals under a mirror-hard finish, stage lights reflecting in the lid and a single chair beside it. No text or logo.',
        'Photograph of a throne cut from polished grey granite standing on a windswept sea cliff, black mica speckles catching the storm light, rain beading on the reflective seat and waves exploding far below. No text or logo.',
      ],
    },
    'SP09-005': {
      dna: material(
        'Rough sandstone: layered sedimentary stone with granular surface and warm bands.',
        'the target is carved from rough sandstone with visible bedding layers and eroded edges.',
        'Ochre, rust, cream and red banding.',
        'Low warm sun that emphasizes grain.',
        'Granular sandstone with bedding layers and wind erosion.',
        'Ancient, eroded, warm and desert-like.',
        'rough granular sandstone; bedding bands; wind erosion; warm ochre',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a giant sandstone statue of a kneeling knight half-eroded by wind, bands of red and ochre across the armor. No text or logo.',
        'Photograph of a steam locomotive carved from rough red sandstone standing on rusted rails in a desert, bands of ochre and cream running along the boiler, wind-rounded edges and sand drifting against the wheels. No text or logo.',
        'Photograph of a tall harp carved from rough layered sandstone in a quiet cloister courtyard, granular surface and warm strata running through the frame, crumbled grit at its foot and afternoon sun raking the texture. No text or logo.',
      ],
    },
    'SP09-006': {
      dna: material(
        'Carrara marble: white marble with soft grey veining, polished or finely carved.',
        'the target is carved from white Carrara marble with grey veins following its form.',
        'Warm white with soft grey veining.',
        'Soft diffused light showing subsurface glow.',
        'Fine crystalline marble with translucent edges and polished or chiselled finish.',
        'Classical, serene, pure and timeless.',
        'white Carrara marble; grey veining; translucent glow; carved detail',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a veiled mourner carved from Carrara marble, the veil translucent at the edges, in a ruined chapel. No text or logo.',
        'Photograph of a dragon carved from white Carrara marble coiled down a grand staircase, soft grey veins flowing along its scales, polished claws and finely rasped wings, cool window light from the landing above. No text or logo.',
        'Photograph of a life-size bicycle carved from Carrara marble leaning against an old stone wall in a narrow street, thin grey veins across the spokes, delicate chisel work on the chain and a real sparrow on the seat. No text or logo.',
      ],
    },
    'SP09-007': {
      dna: material(
        'Split slate: dark layered stone that cleaves into thin sheets with sharp, stepped edges.',
        'the target is built from split slate sheets or carved slate showing layered cleavage.',
        'Blue-grey, charcoal and green-grey with rust stains.',
        'Overcast light showing the stepped layers.',
        'Cleaved slate sheets with sharp edges and rough riven faces.',
        'Austere, cold, rugged and old.',
        'split slate sheets; stepped cleavage; riven faces; blue-grey',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a slate-plated dragon made of overlapping split slate sheets perched on a quarry ledge. No text or logo.',
        'Photograph of an adult knight in armor made of riven slate scales standing in the rain beside a quarry, each dark plate cleaved into thin stepped layers, wet sheen on the edges and grey mist behind. No text or logo.',
        'Photograph of a rowing boat shingled in overlapping split slate tiles drifting on a still grey loch, sharp stepped edges on each tile, rainwater pooling in the hull and hills fading into cloud. No text or logo.',
      ],
    },
    'SP09-008': {
      dna: material(
        'Mossy rock: weathered stone covered in cushions of green moss and lichen.',
        'the target turns into weathered stone covered with thick moss cushions and lichen patches.',
        'Vivid moss green, lichen yellow and grey stone.',
        'Soft, damp forest light.',
        'Velvety moss cushions, crusty lichen and damp stone.',
        'Ancient, quiet, overgrown and living.',
        'moss cushions; lichen patches; damp weathered stone; forest green',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a sleeping giant made of mossy rock, moss cushions on its shoulders, in a misty glen. No text or logo.',
        "Photograph of a knight's helmet turned to weathered stone lying on a forest floor, cushions of bright green moss filling the visor slits, grey and orange lichen crusting the crest and ferns curling around it. No text or logo.",
        'Photograph of an old stone telephone kiosk deep in a rainforest, thick cushions of moss on its roof, lichen patterns on the stone panels and a beam of green light falling through the canopy. No text or logo.',
      ],
    },
    'SP09-009': {
      dna: material(
        'River stones: smooth, rounded pebbles fitted together like a mosaic.',
        'the target is assembled from smooth rounded river stones fitted tightly together.',
        'Grey, ochre, slate and white pebbles.',
        'Soft light, with some stones wet and glossy.',
        'Water-polished stones with rounded edges.',
        'Calm, patient, natural and grounded.',
        'fitted rounded pebbles; water-polished; wet gloss; mosaic packing',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a life-size bear built from smooth fitted river stones standing in a shallow clear stream, each rounded pebble in grey, ochre and rust fitted like a mosaic, water rippling around its legs and dappled forest light. No text or logo.',
        'Photograph of a long cloak made of fitted river pebbles draped over a standing figure on a windy shingle beach, the stones smooth and wet near the hem, grey sea and low clouds behind. No text or logo.',
        'Photograph of an armchair assembled from smooth river stones in a sunlit whitewashed room, every pebble rounded and fitted tight, a wool blanket over one arm and a cat asleep on the seat. No text or logo.',
      ],
    },
    'SP09-010': {
      dna: material(
        'Obsidian: black volcanic glass with conchoidal fractures, razor edges and glassy sheen.',
        'the target is knapped from obsidian, with shell-like fracture scars and sharp edges.',
        'Glossy black with smoky brown and rainbow sheen.',
        'Hard rim light showing the glassy edges.',
        'Volcanic glass with conchoidal ripples and translucent edges.',
        'Dangerous, sleek, dark and primordial.',
        'black volcanic glass; conchoidal fractures; razor edges; rainbow sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a crown knapped from black obsidian resting on a deep red velvet cushion, conchoidal ripple fractures across every point, razor-thin translucent edges glowing faintly brown in a candle beam. No text or logo.',
        'Photograph of an adult woman in armor of knapped obsidian plates with rainbow sheen on a lava field. No text or logo.',
        'Photograph of a wolf sculpture knapped from black obsidian standing on a snowy ridge at sunset, glassy conchoidal fractures along its fur, razor edges catching pink light and snow crystals on its back. No text or logo.',
      ],
    },
    'SP09-011': {
      dna: material(
        'Wolf fur: dense grey-brown guard hairs over a soft underfur, with directional flow.',
        'the target is covered in dense wolf-like fur with directional flow following its form.',
        'Grey, silver, tan and black tipped fur.',
        'Backlight halo on the fur edges.',
        'Guard hairs and soft underfur with natural direction.',
        'Wild, warm, primal and alert.',
        'dense grey fur; guard hairs; directional flow; backlit halo',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a tall grandfather clock covered in dense grey-brown wolf fur standing in a snowbound log cabin, guard hairs flowing downward over the case, soft underfur at the edges and firelight on the brass dial. No text or logo.',
        "Photograph of a knight's cape and helmet crest made of wolf fur on a frozen battlefield. No text or logo.",
        'Photograph of a deep armchair upholstered in silver wolf fur beside a crackling hearth, directional flow of the guard hairs over the arms, soft underfur showing where it parts and a cup of tea on the table. No text or logo.',
      ],
    },
    'SP09-012': {
      dna: material(
        'Snake scales: overlapping keeled or smooth scales with iridescent sheen and patterned bands.',
        'the target is covered in overlapping snake scales with patterned bands following its form.',
        'Olive, emerald, black and gold banding with iridescence.',
        'Raking light that shows each scale edge.',
        'Overlapping keeled scales with glossy iridescent sheen.',
        'Sleek, dangerous, hypnotic and exotic.',
        'overlapping snake scales; patterned bands; iridescent sheen; scale edges',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a violin covered in overlapping emerald-and-gold snake scales lying on black cloth, each keeled scale catching an iridescent sheen, a banded pattern running along the neck and the bow beside it. No text or logo.',
        'Photograph of an adult woman in a gown of iridescent snake scales in a desert ruin. No text or logo.',
        'Photograph of a horse-drawn carriage covered in iridescent snake scales waiting on a rainy cobbled street at night, scales shifting from green to violet under the gas lamps, the coachman in a dark cloak. No text or logo.',
      ],
    },
    'SP09-013': {
      dna: material(
        'Bird feathers: overlapping contour feathers with barbs, shafts and iridescent sheen.',
        'the target is covered in overlapping feathers laid in rows like plumage.',
        'Brown, cream, black and iridescent blue-green.',
        'Soft backlight showing feather barbs.',
        'Overlapping feathers with visible barbs and shafts.',
        'Light, graceful, alive and soft.',
        'overlapping feathers; barbs and shafts; plumage rows; iridescent sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an armored helmet covered in overlapping glossy raven feathers resting on a broken shield on a battlefield at dusk, barbs and shafts sharp, blue-violet iridescence on the crest feathers. No text or logo.',
        'Photograph of a sweeping staircase banister covered in soft barred owl feathers in an old manor, the feathers overlapping downward like a wing, dusty afternoon light across their edges. No text or logo.',
        'Photograph of a small rowboat covered in overlapping white swan feathers floating on a still pond at dawn, the feathers lifting slightly in the breeze and reflected perfectly in the water. No text or logo.',
      ],
    },
    'SP09-014': {
      dna: material(
        'Coral reef: branching and brain corals growing over the target in bright calcareous forms.',
        'the target is overgrown or formed from living coral structures, branching and brain coral.',
        'Coral pink, orange, purple, cream and turquoise.',
        'Underwater-like caustic light.',
        'Calcareous coral with polyps, ridges and porous texture.',
        'Vibrant, alive, oceanic and intricate.',
        'branching and brain coral; polyps; porous calcareous texture; caustic light',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a sunken diving bell overgrown with pink and orange branching coral on the sea bed, brain coral swelling over its portholes, parrotfish grazing the rim and blue light filtering from above. No text or logo.',
        'Photograph of a chandelier grown from branching pink and orange coral hanging in a dark sunken ballroom, fish swimming between the arms, brain coral on the ceiling rose and shafts of blue sea light. No text or logo.',
        'Photograph of a throne formed from brain coral and branching staghorn coral in a sea cave, bright calcareous colors, sea anemones in the armrests and a moray eel peering from the base. No text or logo.',
      ],
    },
    'SP09-015': {
      dna: material(
        'Honeycomb wax: hexagonal beeswax comb with golden translucent cells and honey drips.',
        'the target is built from hexagonal honeycomb with some cells filled and dripping.',
        'Amber, gold and pale yellow wax.',
        'Backlight making wax cells glow.',
        'Hexagonal wax cells, honey drips and waxy sheen.',
        'Warm, sweet, organic and industrious.',
        'hexagonal wax cells; honey drips; glowing amber; waxy sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a crown made of golden beeswax honeycomb resting on a stone altar, hexagonal cells glowing translucent in a sunbeam, honey dripping slowly down the points and a few bees crawling over it. No text or logo.',
        "Photograph of a beekeeper's smoker and veiled hat grown over with golden hexagonal honeycomb wax on a garden bench, cells glowing amber in the late sun, honey pooling on the wood and bees crawling over the brim. No text or logo.",
        'Photograph of a honeycomb-wax lantern hanging in a dark barn, a candle inside making every hexagonal cell glow amber, honey drips on the beam below and dust floating in the light. No text or logo.',
      ],
    },
    'SP09-016': {
      dna: material(
        'Glacier ice: dense blue ice with trapped bubbles, fracture planes and melt-smoothed surfaces.',
        'the target is made of glacier ice with blue depths and trapped bubbles.',
        'Deep cyan-blue with white frosted edges.',
        'Backlight showing blue translucency.',
        'Dense ice with bubbles, fractures and melt ridges.',
        'Cold, ancient, pure and silent.',
        'deep blue glacier ice; trapped bubbles; fracture planes; translucent depth',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a life-size bison carved from dense blue glacier ice standing on a frozen plain, trapped bubbles and fracture planes inside its hump, melt-smoothed horns and low pink sunlight passing through. No text or logo.',
        'Photograph of a grand piano carved from dense blue glacier ice in a dark stone hall, trapped bubbles and fracture planes glowing in a single spotlight, meltwater dripping from the keys onto the floor. No text or logo.',
        'Photograph of a great cathedral door carved from glacier ice in a snowstorm, deep blue fracture planes and trapped air bubbles inside, melt-smoothed edges around carved saints and warm light behind it. No text or logo.',
      ],
    },
    'SP09-044': {
      dna: material(
        'Sea sponge: porous organic sponge with irregular holes and soft tan fibers.',
        'the target is made of porous natural sea sponge with irregular holes.',
        'Tan, sand, ochre and pale yellow.',
        'Soft side light showing pores.',
        'Porous spongy fibers with irregular holes.',
        'Soft, strange, organic and absorbent.',
        'porous sea sponge; irregular holes; soft tan fibers',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an old diving helmet grown from porous tan sea sponge sitting on a wet beach at dusk, irregular holes of every size, soft fibers at the rims and small crabs sheltering in the openings. No text or logo.',
        'Photograph of an armchair made entirely of porous tan sea sponge in a white-walled room, irregular holes and soft fiber texture across the seat and arms, window light casting soft shadows into the pores. No text or logo.',
        'Photograph of a bust of a queen made of sea sponge on a marble plinth in a museum, irregular pores forming her crown and hair, soft tan fibers catching a gallery spotlight. No text or logo.',
      ],
    },
    'SP09-055': {
      dna: material(
        'Crystal and gemstone: faceted translucent crystal with internal refractions and color zones.',
        'the target is carved from gem crystal with facets and inner refractions.',
        'Amethyst purple, emerald, sapphire or clear quartz.',
        'Point lights producing refraction and fire.',
        'Faceted crystal with inclusions and internal reflections.',
        'Precious, magical, cold and brilliant.',
        'faceted gem crystal; internal refraction; inclusions; spectral fire',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a dragon skull made of faceted amethyst crystal resting in a candlelit cave, internal refractions throwing violet light onto the rock, color zones deepening toward the horns and clear points at the teeth. No text or logo.',
        'Photograph of a hummingbird carved from faceted blue sapphire crystal perched on a real flower stem, internal refractions and color zoning through its wings, a spotlight scattering blue sparks on the petals. No text or logo.',
        'Photograph of a rocking horse carved from clear quartz crystal in a sunlit nursery, rainbow refractions spilling across the floorboards, cloudy inclusions in the body and faceted edges on the mane. No text or logo.',
      ],
    },
    'SP09-063': {
      dna: material(
        'Cobweb: dense dusty spider silk draped in layers over the target.',
        'the target is draped in thick layers of dusty cobweb strands and sheets.',
        'Grey-white strands with dust and dark gaps.',
        'Backlight catching the strands.',
        'Silk strands, sagging sheets and dust.',
        'Abandoned, eerie, still and forgotten.',
        'dusty cobweb layers; backlit strands; sagging sheets',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an old printing press in an abandoned workshop draped in thick dusty cobwebs, silk strands sagging between the rollers and levers, grey dust on every surface and a shaft of window light. No text or logo.',
        'Photograph of a grand piano in an abandoned ballroom shrouded under thick layers of dusty cobweb, silk strands hanging from the lid like curtains, a beam of moonlight showing the dust drifting. No text or logo.',
        'Photograph of a tiered wedding cake shrouded in grey cobwebs on a long banquet table in a derelict manor, spiders in the silk, dust on the candelabras and faded ribbons. No text or logo.',
      ],
    },
    'SP09-066': {
      dna: material(
        'Beach sand: fine packed sand sculpted into the target, with grain texture and crumbling edges.',
        'the target is sculpted from packed beach sand with crumbling edges and fine grain.',
        'Warm beige, golden and wet darker sand.',
        'Low sun raking the grains.',
        'Packed fine sand grains with crumbling edges and shell fragments.',
        'Fleeting, playful, warm and fragile.',
        'packed sand sculpture; crumbling edges; fine grains; wet and dry tones',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a huge sleeping dragon sculpted from fine packed beach sand, scales carved with a knife, grains visible in close light, crumbling edges at the tail and the incoming tide about to reach it at sunset. No text or logo.',
        'Photograph of a sand-sculpted sea turtle crawling toward the waves on a wide beach, fine grain texture on its shell plates, the flippers beginning to crumble in the wind and real footprints around it. No text or logo.',
        'Photograph of a sand-sculpted cathedral facade on a beach at sunset, pointed arches and a rose window carved from packed sand, fine grains glowing orange and one tower slumping as it dries. No text or logo.',
      ],
    },
    'SP09-068': {
      dna: material(
        'Cooled lava rock: porous black-red basalt scoria with vesicles and ropy flow texture.',
        'the target is made of cooled lava rock with vesicles and ropy flow texture.',
        'Charcoal black, rust red and ash grey.',
        'Hard side light revealing pores.',
        'Vesicular basalt, scoria and ropy pahoehoe flow.',
        'Harsh, volcanic, primal and rough.',
        'porous lava rock; vesicles; ropy flow; charcoal and rust',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a golem built from porous black-red lava rock kneeling on a black sand beach, vesicles and ropy flow texture across its shoulders, steam rising from cracks and surf breaking behind. No text or logo.',
        'Photograph of a throne of ropy cooled lava rock inside a volcanic cave, pahoehoe folds forming the armrests, porous red scoria on the back and faint orange glow from a fissure behind it. No text or logo.',
        'Photograph of a teapot made of porous black lava rock on a rough wooden table, vesicles across its belly, a ropy flow ridge along the spout and steam curling from the lid. No text or logo.',
      ],
    },
    'SP09-079': {
      dna: material(
        'Mother of pearl: iridescent nacre with shimmering color shifts and layered sheen.',
        'the target is inlaid or carved from mother-of-pearl nacre with color-shifting sheen.',
        'Pearl white with pink, blue and green iridescence.',
        'Soft light producing shifting iridescence.',
        'Layered nacre with shimmer and inlay seams.',
        'Precious, delicate, oceanic and luminous.',
        'iridescent nacre; color-shifting sheen; inlay seams',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an old music box sheathed in mother of pearl open on a dark pebble shore at twilight, iridescent nacre shifting from pink to green to silver, layered plates catching the last light. No text or logo.',
        'Photograph of a violin inlaid entirely with mother of pearl on a black silk cloth, shimmering nacre plates shifting color along the curves, layered sheen on the scroll under a soft lamp. No text or logo.',
        'Photograph of a ceremonial carriage covered in nacre inlay standing in a moonlit palace courtyard, iridescent panels shimmering blue and pink, horses waiting in the shadow of the arch. No text or logo.',
      ],
    },
    'SP09-080': {
      dna: material(
        'Dragon scale: large armored overlapping scales with ridges, metallic sheen and battle scratches.',
        'the target is covered in large overlapping dragon scales with ridges and metallic sheen.',
        'Bronze, crimson, emerald or obsidian with metallic highlights.',
        'Hard raking light showing ridges.',
        'Thick overlapping scales with ridges, scratches and metallic sheen.',
        'Powerful, armored, mythic and fierce.',
        'large overlapping dragon scales; ridges; metallic sheen; battle scratches',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a round shield covered in large overlapping crimson dragon scales leaning against a burnt tree, ridged edges, metallic sheen and deep battle scratches across the scales, smoke drifting over the field. No text or logo.',
        'Photograph of an adult woman in a dragon-scale coat with metallic bronze sheen in a storm. No text or logo.',
        'Photograph of a heavy door covered in bronze-green dragon scales set in a castle wall, ridged overlapping plates, metallic sheen and old claw scratches, a torch burning in an iron bracket beside it. No text or logo.',
      ],
    },
  },
};

export default spec;
