import type { Create, Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Material surface textures (pack_10) are decorative surface patterns — the visible figure, grain
// or finish pattern — as opposed to pack_09's physical material behavior.
const AVOID = [...MATERIAL_AVOID, 'plain untextured surface'];
const s = (a: string, b: string, c: string, l: string, t: string, m: string, k: string) =>
  material(
    a,
    `${b} The decorative surface pattern is the point: make its figure, veining or motif the first read.`,
    c,
    l,
    t,
    m,
    `${k}; decorative surface pattern`,
  );

const spec: Spec = {
  pack: 'pack_10',
  category: '6. Material Surface Textures',
  updates: {
    'SP10-048': {
      dna: s(
        'Terrazzo: polished composite with scattered stone and glass chips in a cement matrix.',
        'the surface shows scattered colored chips set in a smooth matrix.',
        'Cream matrix with terracotta, green and black chips.',
        'Soft even light on polished surface.',
        'Polished chips flush in matrix.',
        'Playful, modern, crafted and bright.',
        'scattered chips; polished matrix',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a café counter and bar stools finished in polished terrazzo, scattered terracotta, green and white stone chips in a cream cement matrix, espresso cups catching the morning light. No text or logo.',
        'Photograph of a large terrazzo egg on a museum plinth, polished speckled surface with chips of marble, glass and brass scattered through grey cement, a soft spotlight reflection. No text or logo.',
        'Photograph of a public drinking fountain cast in polished terrazzo in a park, blue and white glass chips in the matrix and water arcing into the basin. No text or logo.',
      ],
    },
    'SP10-054': {
      dna: s(
        'Marble veining texture: dramatic flowing veins across polished stone.',
        "bold flowing veins sweep across the target's surfaces.",
        'White, black or green marble with gold or grey veins.',
        'Polished reflections.',
        'Flowing veins and polish.',
        'Luxurious, dramatic, cool and grand.',
        'dramatic flowing veins',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a black marble panther sculpture with dramatic gold veins sweeping along its body, polished to a mirror finish in a dark gallery. No text or logo.',
        'Photograph of a green marble bathtub in an old spa with dramatic white veins flowing across its curves, steam rising and brass taps. No text or logo.',
        'Photograph of a veined pink marble staircase curving through a grand hotel lobby, flowing grey veins running across every polished step. No text or logo.',
      ],
    },
    'SP10-055': {
      dna: s(
        'Wood grain texture: bold flowing grain lines and knots across the surface.',
        'strong grain lines flow around knots over the surfaces.',
        'Warm wood tones with dark grain.',
        'Warm side light.',
        'Flowing grain and knots.',
        'Warm, organic, handcrafted and natural.',
        'flowing grain lines; knots',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a carved wooden owl whose bold grain lines flow around its eyes like feathers, a dark knot forming one pupil, oiled walnut glowing in window light. No text or logo.',
        'Photograph of a wooden canoe paddle and hull with bold flowing grain lines and knots, freshly oiled on a lakeside dock at sunset. No text or logo.',
        'Photograph of a wooden toy chest with bold swirling grain on its lid, knots like eyes and warm honey tones in a nursery. No text or logo.',
      ],
    },
    'SP10-056': {
      dna: s(
        'Carbon fiber weave: glossy twill pattern of black fibers.',
        'a glossy 2x2 twill carbon weave covers the surfaces.',
        'Black and graphite with gloss.',
        'Strip light across the weave.',
        'Twill weave under clear coat.',
        'High-tech, sleek, sporty and modern.',
        'twill carbon weave; glossy',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a racing bicycle frame in glossy carbon-fiber twill under strip lights, the black woven pattern shifting as the tubes curve. No text or logo.',
        'Photograph of a carbon-fiber twill briefcase on a marble desk, the glossy woven pattern catching a single desk lamp. No text or logo.',
        'Photograph of a carbon-fiber twill cello standing in a dark studio, glossy black weave following its curves under soft light. No text or logo.',
      ],
    },
    'SP10-059': {
      dna: s(
        'Leather texture: pebbled or embossed leather grain with stitching.',
        'embossed leather grain and saddle stitching cover the surfaces.',
        'Cognac, black, oxblood.',
        'Soft side light.',
        'Grain, stitching and edge paint.',
        'Crafted, warm, rugged and classic.',
        'leather grain; saddle stitching',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a vintage camera case in pebbled black leather with saddle stitching on a travel desk, embossed grain and worn corners. No text or logo.',
        'Photograph of a tooled leather saddle on a fence rail, embossed floral patterns and stitching along the skirt, warm ranch light. No text or logo.',
        'Photograph of a leather-covered traveling trunk with brass corners on a train platform, pebbled grain and neat stitching. No text or logo.',
      ],
    },
    'SP10-060': {
      dna: s(
        'Glitter texture: dense sparkling glitter coating.',
        'dense multicolor glitter coats the surfaces.',
        'Gold, silver or rainbow glitter.',
        'Point lights for sparkle.',
        'Glitter flakes.',
        'Festive, playful, sparkly and kitsch.',
        'dense glitter sparkle',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a skull coated in dense gold glitter on black velvet, every contour sparkling under a spotlight, loose glitter scattered on the cloth. No text or logo.',
        'Photograph of a disco-roller skate coated in dense silver glitter on a rink floor, sparkles scattering under colored lights. No text or logo.',
        'Photograph of a violet glitter-coated trumpet on a stage stool, dense sparkling coating catching the spotlight. No text or logo.',
      ],
    },
    'SP10-061': {
      dna: s(
        'Rust texture: decorative rust blooms and streaks as surface pattern.',
        'orange rust blooms and streaks pattern the surface.',
        'Orange and brown on grey.',
        'Warm light.',
        'Rust blooms and streaks.',
        'Aged, industrial, raw and warm.',
        'rust blooms and streaks',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a garden gate patterned with decorative rust blooms and orange streaks running down from each scroll, the pattern deliberate and even. No text or logo.',
        'Photograph of a steel park bench patterned with decorative rust blooms and streaks, autumn leaves on the seat. No text or logo.',
        'Photograph of a large bell with decorative rust blooms and streaks as a surface pattern hanging in a tower. No text or logo.',
      ],
    },
    'SP10-062': {
      dna: s(
        'Holographic foil: rainbow diffraction foil that shifts color with angle.',
        'holographic diffraction foil covers the surfaces with shifting rainbows.',
        'Rainbow diffraction over silver.',
        'Point lights for diffraction.',
        'Foil with diffraction pattern.',
        'Futuristic, playful, shiny and pop.',
        'holographic diffraction foil',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a racing suit wrapped in holographic foil in a pit lane, rainbow diffraction shifting from magenta to green as the rider turns. No text or logo.',
        'Photograph of a whale-shaped balloon covered in holographic foil floating over a festival, rainbow diffraction rippling across its skin. No text or logo.',
        'Photograph of a holographic foil gift box on a white table, rainbow diffraction shifting across every face. No text or logo.',
      ],
    },
    'SP10-063': {
      dna: s(
        'Chainmail texture: ring pattern as a decorative surface.',
        'fine interlocking ring pattern covers the surfaces.',
        'Steel, silver, bronze.',
        'Sparkling light on rings.',
        'Interlocking rings.',
        'Armored, ancient, elegant and heavy.',
        'interlocking ring pattern',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a swan sculpture with a chainmail ring-pattern surface on a lake shore, tiny interlocking rings shimmering like feathers. No text or logo.',
        'Photograph of a teapot with a chainmail ring-pattern surface on a kitchen table, the rings catching window light, steam rising. No text or logo.',
        'Photograph of a carnival mask with a chainmail ring-pattern surface on a velvet stand, fine rings forming the brows and nose. No text or logo.',
      ],
    },
    'SP10-064': {
      dna: s(
        'Snake skin texture: scale pattern with bold markings as decorative surface.',
        'patterned snake scales cover the surfaces with bold markings.',
        'Python browns or emerald.',
        'Soft sheen.',
        'Overlapping scales and markings.',
        'Exotic, sleek, dangerous and luxe.',
        'snake scale markings',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a pair of cowboy boots in python-patterned skin on a porch, bold scale markings and a soft sheen. No text or logo.',
        'Photograph of a snakeskin-patterned armchair in a jazz lounge, bold diamond markings across the curved back. No text or logo.',
        'Photograph of an electric guitar finished in snakeskin pattern leaning on an amplifier in a smoky club, bold black and gold diamond markings wrapping the body, scales catching the red stage light. No text or logo.',
      ],
    },
    'SP10-071': {
      dna: s(
        'Kintsugi: broken ceramic repaired with gold-filled seams.',
        'the surfaces show cracks repaired with bright gold seams.',
        'Ceramic base with gold seams.',
        'Soft light catching gold.',
        'Gold-lacquer seams across cracks.',
        'Resilient, poetic, precious and calm.',
        'gold-repaired cracks',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a broken tea bowl repaired with kintsugi gold seams on a tatami mat, the gold-filled cracks branching like rivers. No text or logo.',
        'Photograph of a ceramic fox mask repaired with kintsugi gold seams, cracks running across its snout and eyes. No text or logo.',
        'Photograph of a cracked porcelain skull repaired with branching gold kintsugi seams resting on dark wood beside a candle, the gold lines catching the flame across the brow and jaw. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Raku Crackle Glaze',
      domain: 'raku crackle glaze',
      tags: ['raku', 'crackle', 'surface'],
      dna: s(
        'Raku glaze: crackled white glaze with smoky black craze lines and metallic flashes.',
        'crackled glaze with smoky black lines and copper flashes covers the surfaces.',
        'White crackle with black lines and copper flashes.',
        'Soft light.',
        'Crazed glaze and smoky carbon.',
        'Earthy, fiery, random and beautiful.',
        'raku crackle; smoky lines; copper flash',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a raku-glazed vase with crackled white glaze, smoky black craze lines and copper metallic flashes, on a rough stone plinth. No text or logo.',
        'Photograph of a horse head sculpture fired in raku on a gallery pedestal, the white glaze split by a dense web of smoky black crackle, iridescent copper blushes pooling in the nostrils and mane. No text or logo.',
        'Photograph of a raku-fired owl perched on a moss-covered garden wall at dusk, heavy carbon smoke staining its lower half black, crackled pale glaze on the chest and a coppery sheen on the wings. No text or logo.',
      ],
    },
    {
      name: 'Damascus Steel',
      domain: 'damascus pattern-welded steel',
      tags: ['damascus', 'steel', 'surface'],
      dna: s(
        'Damascus steel: flowing layered wave patterns in etched steel.',
        'flowing etched Damascus layers pattern the metal surfaces.',
        'Dark and light grey steel waves.',
        'Raking light.',
        'Etched layered wave pattern.',
        'Crafted, deadly, elegant and ancient.',
        'Damascus wave pattern',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a Damascus-steel chef's knife on a cutting board, flowing etched wave patterns along the blade beside herbs. No text or logo.",
        'Photograph of a Damascus-steel pocket watch case with flowing layered waves, open on a velvet cloth. No text or logo.',
        'Photograph of a pair of Damascus-steel wedding rings resting on a mossy river stone, flowing etched layers swirling in grey and silver around each band, water droplets beading nearby. No text or logo.',
      ],
    },
    {
      name: 'Burl Wood Figure',
      domain: 'burl wood figure',
      tags: ['burl', 'wood', 'surface'],
      dna: s(
        'Burl wood: swirling chaotic grain with eyes and clusters.',
        'swirling burl figure with tiny eyes covers the surfaces.',
        'Amber, honey and dark swirls.',
        'Warm glossy light.',
        'Chaotic swirls and eyes.',
        'Rich, organic, warm and rare.',
        'swirling burl figure; eyes',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a bowl turned from burl wood with swirling chaotic grain, clusters of eyes and a glossy oil finish on a workbench. No text or logo.',
        'Photograph of a burl-wood dashboard in a vintage car, swirling grain and eye clusters under glossy lacquer. No text or logo.',
        'Photograph of a burl-wood guitar body with swirling figure and dark eye clusters under a glossy finish. No text or logo.',
      ],
    },
    {
      name: 'Mokume-gane',
      domain: 'mokume-gane layered metal',
      tags: ['mokume-gane', 'metal', 'surface'],
      dna: s(
        'Mokume-gane: layered mixed metals forming wood-grain-like patterns.',
        'wood-grain patterns of layered copper, silver and gold cover the surfaces.',
        'Copper, silver and gold bands.',
        'Soft metallic light.',
        'Layered metal grain.',
        'Refined, crafted, precious and warm.',
        'layered metal grain',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a mokume-gane pendant with copper, silver and gold layers forming wood-grain patterns, resting on slate. No text or logo.',
        'Photograph of a mokume-gane ring on velvet, layered mixed metals swirling like wood grain in pink and grey. No text or logo.',
        'Photograph of a mokume-gane sword guard with layered copper and silver grain patterns on dark cloth. No text or logo.',
      ],
    },
    {
      name: 'Tadelakt Plaster',
      domain: 'tadelakt polished plaster',
      tags: ['tadelakt', 'plaster', 'surface'],
      dna: s(
        'Tadelakt: burnished lime plaster with soft sheen and subtle cloudy variation.',
        'soft burnished plaster with cloudy tone variation covers the surfaces.',
        'Terracotta, sand, sage.',
        'Soft warm light.',
        'Burnished plaster sheen.',
        'Calm, earthy, warm and soft.',
        'burnished plaster; cloudy sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a bathroom with walls and a sunken tub in terracotta tadelakt plaster, burnished soft sheen and cloudy variation in warm light. No text or logo.',
        'Photograph of a tadelakt plaster sink and niche in pale sand color, soft burnished sheen and subtle cloudy variation. No text or logo.',
        'Photograph of a curved tadelakt bench in a courtyard, burnished lime plaster in ochre with soft cloudy variation. No text or logo.',
      ],
    },
    {
      name: 'Cloisonné Enamel',
      domain: 'cloisonne enamel',
      tags: ['cloisonne', 'enamel', 'surface'],
      dna: s(
        'Cloisonné: glossy colored enamel fields separated by fine gold wire cells.',
        'glossy enamel fields in gold wire cells cover the surfaces.',
        'Turquoise, cobalt, coral, gold.',
        'Glossy light.',
        'Enamel and gold wire.',
        'Ornate, precious, bright and refined.',
        'enamel in gold wire cells',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a cloisonné koi fish vase with turquoise and coral enamel fields separated by fine gold wire cells, glossy under soft light. No text or logo.',
        'Photograph of a cloisonné egg on a gold stand, glossy enamel fields in cobalt and white separated by gold wire. No text or logo.',
        'Photograph of a cloisonné incense burner with glossy green and red enamel cells and fine gold wire outlines. No text or logo.',
      ],
    },
    {
      name: 'Guilloché Engraving',
      domain: 'guilloche engine turning',
      tags: ['guilloche', 'engraving', 'surface'],
      dna: s(
        'Guilloché: machine-engraved repeating wave and sunburst patterns under enamel.',
        'fine engine-turned wave and sunburst patterns cover the surfaces.',
        'Silver or gold with translucent enamel.',
        'Light rippling in grooves.',
        'Engine-turned grooves.',
        'Precise, luxurious, hypnotic and refined.',
        'engine-turned grooves; sunburst',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a pocket watch dial with guilloché sunburst grooves under translucent blue enamel, catching the light. No text or logo.',
        'Photograph of a guilloché-engraved compact mirror with repeating wave patterns under pink enamel on a vanity. No text or logo.',
        'Photograph of a fountain pen with a guilloché-engraved barrel lying on an old leather desk blotter, machine-cut waves glowing beneath translucent green enamel in lamp light. No text or logo.',
      ],
    },
    {
      name: 'Urushi Lacquer',
      domain: 'urushi lacquer finish',
      tags: ['urushi', 'lacquer', 'surface'],
      dna: s(
        'Urushi lacquer: deep glossy lacquer in black and vermilion with maki-e gold sprinkles.',
        'deep glossy lacquer with gold sprinkle motifs covers the surfaces.',
        'Black and vermilion with gold.',
        'Deep glossy reflections.',
        'Layered lacquer and gold dust.',
        'Refined, deep, precious and calm.',
        'deep lacquer; maki-e gold',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a black urushi-lacquered samurai helmet with gold maki-e cranes, deep glossy surface reflecting a paper lantern. No text or logo.',
        'Photograph of a vermilion urushi-lacquered writing box open on a low table, gold maki-e maple leaves drifting across the lid, the deep glossy surface reflecting a paper window. No text or logo.',
        'Photograph of a black urushi-lacquered tiered food box on a tatami mat, fine gold sprinkles scattered like stars, glossy reflections of a garden in its surface. No text or logo.',
      ],
    },
    {
      name: 'Hammered Metal',
      domain: 'hammered metal texture',
      tags: ['hammered', 'metal', 'surface'],
      dna: s(
        'Hammered metal: dimpled facets from hand hammering catching light.',
        'hand-hammered dimples facet the metal surfaces.',
        'Copper, brass or pewter.',
        'Point lights sparkling on dimples.',
        'Hammered facets.',
        'Handmade, warm, rustic and crafted.',
        'hammered dimples',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a hammered-copper kettle on an old iron stove, hundreds of dimpled facets glinting orange and pink in the flame light, steam curling from the spout into a dim kitchen. No text or logo.',
        'Photograph of a hammered-brass farmhouse sink under a window of herbs, dimpled hand-hammered facets scattering the morning light, water droplets on the rim. No text or logo.',
        'Photograph of a hammered-pewter goblet on a long oak tavern table, dimpled facets glowing softly in candlelight, a spilled drop of red wine beside the base. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
