import type { Spec } from '../tools/apply';
import { ga } from './_authors';

// Video game pass, wilderness hunts and harsh frontiers: each preset names its game, studio and
// year and states the real render technique and camera. Briefs stay; they already invent their
// own prey, beasts and places.
const spec: Spec = {
  pack: 'pack_12',
  category: '6. Wilderness Hunts & Harsh Frontiers',
  updates: Object.fromEntries([
    ga('SP12-002', 'Avatar Frontiers of Pandora 2023 - Massive Bioluminescent Jungle', {
      look: 'Massive Entertainment Avatar: Frontiers of Pandora (2023) look: first-person hunting in a towering alien rainforest, bioluminescent plants, floating flora, six-legged fauna and lush Snowdrop engine detail.',
      subject:
        'render people as hunters seen from first person with a bow, among giant alien plants.',
      color: 'Lush jungle green, bioluminescent cyan, violet and warm sunbeams.',
      light: 'Dappled canopy sunlight by day and glowing bioluminescence at night.',
      texture: 'Dense photoreal alien foliage, wet bark and translucent glowing plants.',
      camera: 'First-person view with a drawn bow in frame.',
      mood: 'lush alien wonder',
      render: 'Authentic modern first-person open-world screen.',
      key: 'Frontiers of Pandora jungle; bioluminescence; first-person bow',
      avoid: ['tall blue-skinned aliens with tails'],
    }),
    ga('SP12-010', 'Dark Souls 2011 - FromSoftware Grim Bonfire', {
      look: 'FromSoftware Dark Souls (2011) look: third-person dark fantasy of decayed kingdoms, muted desaturated palettes, heavy worn armor, towering demon bosses and lonely bonfires.',
      subject:
        'render people as heavy worn knights and hollowed wanderers in battered armor and rags.',
      color: 'Desaturated ash grey, ember orange, rust and deep shadow.',
      light: 'Dim gloomy light with molten glows and bonfire warmth.',
      texture: 'Worn armor, rough stone, ash and embers.',
      camera: 'Third-person lock-on view facing a huge boss.',
      mood: 'bleak perilous endurance',
      render: 'Authentic early-2010s dark fantasy action screen.',
      key: 'Dark Souls decay; demon bosses; bonfires; worn armor',
      avoid: ['a knight in a bucket helm with a sun emblem'],
    }),
    ga('SP12-022', 'The Long Dark 2017 - Hinterland Painterly Wilderness', {
      look: 'Hinterland Studio The Long Dark (2017) look: first-person survival in a painterly Canadian winter wilderness, flat brushstroke textures, soft gradients, cabins, wolves and aurora nights.',
      subject:
        'render people as bundled survivors seen from first person in painterly winter light.',
      color: 'Painterly snow blue, pine green, sunset peach and cabin amber.',
      light: 'Soft painterly gradients with low winter sun.',
      texture: 'Flat brushstroke textures and soft shapes.',
      camera: 'First-person view across snowfields.',
      mood: 'quiet lonely survival',
      render: 'Authentic painterly survival screen.',
      key: 'The Long Dark painterly snow; cabins; wolves',
    }),
    ga('SP12-027', 'Deep Rock Galactic 2020 - Ghost Ship Low-Poly Caves', {
      look: 'Ghost Ship Games Deep Rock Galactic (2020) look: first-person co-op mining in dark procedural caves, stylized low-poly rock, glowing minerals, flares and alien bug swarms.',
      subject:
        'render people as stout bearded space miners in chunky gear, seen from first person.',
      color: 'Cave darkness, flare orange and mineral cyan.',
      light: 'Headlamps and thrown flares in darkness.',
      texture: 'Faceted low-poly rock and glowing crystals.',
      camera: 'First-person view in a cavern.',
      mood: 'rowdy cave camaraderie',
      render: 'Authentic co-op cave shooter screen.',
      key: 'Deep Rock low-poly caves; flares; mining crew',
      avoid: ['existing Deep Rock dwarves and their salute'],
    }),
    ga('SP12-029', 'Subnautica 2018 - Unknown Worlds Alien Reef', {
      look: 'Unknown Worlds Subnautica (2018) look: first-person underwater survival on an alien ocean planet, luminous coral, leviathans, small submarines and handheld scanners.',
      subject: 'render people as divers seen from first person with scanners and small subs.',
      color: 'Alien turquoise, coral magenta and abyss blue.',
      light: 'Filtered sun shafts and glowing reef.',
      texture: 'Stylized alien coral and water haze.',
      camera: 'First-person dive view.',
      mood: 'awe edged with fear',
      render: 'Authentic underwater survival screen.',
      key: 'Subnautica reef; leviathans; first-person dive',
      avoid: ['existing leviathan designs'],
    }),
    ga('SP12-034', 'Sniper Ghost Warrior Contracts 2019 - CI Games Long Shot', {
      look: 'CI Games Sniper Ghost Warrior Contracts (2019) look: realistic first-person sniping over mountain canyons, scope with ranging marks, wind haze and distant convoys.',
      subject:
        'render people as distant realistic figures seen through a scope or a prone marksman.',
      color: 'Canyon ochre, dusty green and sky haze.',
      light: 'Hot daylight with heat haze.',
      texture: 'Realistic rock, dust and gear.',
      camera: 'First-person prone scope view.',
      mood: 'patient lethal focus',
      render: 'Authentic tactical sniper screen.',
      key: 'Sniper contracts; scope view; canyon haze',
    }),
    ga('SP12-040', 'Monster Hunter World 2018 - Capcom Ecosystem Hunt', {
      look: 'Capcom Monster Hunter: World (2018) look: third-person hunting of huge living monsters across rich ecosystems, oversized weapons, layered armor made from monster parts and dramatic weather.',
      subject: 'render people as hunters in layered monster-part armor with oversized weapons.',
      color: 'Storm blue, electric yellow and natural earth.',
      light: 'Stormy light with lightning bursts.',
      texture: 'Detailed scales, fur and forged armor.',
      camera: 'Third-person view mid-attack.',
      mood: 'thrilling colossal hunt',
      render: 'Authentic modern hunting action screen.',
      key: 'Monster Hunter giant monsters; big weapons; ecosystems',
      avoid: ['existing Monster Hunter monsters', 'a cat companion in armor'],
    }),
    ga('SP12-041', 'Firewatch 2016 - Campo Santo Olly Moss Palette', {
      look: 'Campo Santo Firewatch (2016) look: first-person Wyoming wilderness in Olly Moss poster palettes, flat painterly forests, fire lookouts, sunsets and layered ridges.',
      subject: 'render people as simple painterly figures seen from first person.',
      color: 'Sunset orange, coral pink and teal ridges.',
      light: 'Warm poster-like sunset gradients.',
      texture: 'Flat painterly shapes and soft gradients.',
      camera: 'First-person view from a lookout.',
      mood: 'wistful lonely warmth',
      render: 'Authentic painterly first-person screen.',
      key: 'Firewatch Olly Moss palette; lookout; ridges',
    }),
    ga('SP12-067', 'Total War Three Kingdoms 2019 - Creative Assembly Epic Battle', {
      look: 'Creative Assembly Total War: Three Kingdoms (2019) look: massive real-time battles of thousands of soldiers in ancient Chinese armies, banners, lacquered armor, marshes and fortresses.',
      subject: 'render people as thousands of small soldiers in lacquered armor with banners.',
      color: 'Bronze marsh gold, banner red and mist grey.',
      light: 'Dawn mist light over armies.',
      texture: 'Detailed lacquered armor and reeds.',
      camera: 'High battle camera over armies.',
      mood: 'epic martial grandeur',
      render: 'Authentic grand battle strategy screen.',
      key: 'Total War massed armies; banners; marsh siege',
    }),
    ga('SP12-073', 'Shadow of the Colossus 2018 - Bluepoint Colossus Climb', {
      look: 'Bluepoint Games Shadow of the Colossus (2018) look: tiny riders climbing fur and stone of moving colossi, vast empty lands, soft bloom and melancholic grandeur.',
      subject: 'render people as tiny figures clinging to colossal furred creatures.',
      color: 'Soft green, stone grey and sun haze.',
      light: 'Soft bloom and hazy sunlight.',
      texture: 'Detailed fur, moss and ancient stone.',
      camera: 'Wide low view of a colossus.',
      mood: 'melancholic grand struggle',
      render: 'Authentic modern remake adventure screen.',
      key: 'Colossus climb; tiny rider; vast land',
      avoid: ['existing colossi', 'a black horse with a young swordsman'],
    }),
    ga('SP12-149', 'Far Cry Primal 2016 - Ubisoft Stone Age Hunt', {
      look: 'Ubisoft Far Cry Primal (2016) look: first-person Stone Age hunting in lush Mesolithic valleys, bows and spears, megafauna, bone ornaments and fire.',
      subject: 'render people as Stone Age hunters in furs and bone ornaments.',
      color: 'Forest green, fur brown and fire amber.',
      light: 'Dappled forest light.',
      texture: 'Realistic fur, bone and foliage.',
      camera: 'First-person bow view.',
      mood: 'primal tense stalking',
      render: 'Authentic open-world hunting screen.',
      key: 'Far Cry Primal hunt; Stone Age; bow',
    }),
    ga('SP12-150', 'Never Alone 2014 - Upper One Arctic Folktale', {
      look: 'Upper One Games Never Alone (2014) look: side-view Arctic folktale platformer inspired by Iñupiaq art, scrimshaw-like spirit shapes, blizzards and ice.',
      subject: 'render people as small bundled Arctic travelers in fur parkas.',
      color: 'Blizzard white, ice blue and spirit glow.',
      light: 'Blizzard haze and spirit light.',
      texture: 'Stylized snow and scrimshaw spirit lines.',
      camera: 'Side-view platformer.',
      mood: 'bitter folkloric endurance',
      render: 'Authentic folktale platformer screen.',
      key: 'Never Alone Arctic; spirit shapes; blizzard',
    }),
    ga('SP12-151', 'Afrika 2008 - Rhino Studios Safari Photography', {
      look: 'Rhino Studios Afrika (2008) look: realistic safari photography with a camera viewfinder over the African savanna, herds at golden hour, jeeps and river crossings.',
      subject: 'render every subject as wildlife framed through a camera viewfinder.',
      color: 'Savanna gold, sunset orange and river blue.',
      light: 'Golden hour savanna light.',
      texture: 'Realistic grass and animal detail.',
      camera: 'Viewfinder framing from a jeep.',
      mood: 'patient wild wonder',
      render: 'Authentic safari photography screen.',
      key: 'Afrika viewfinder; savanna; herds',
    }),
    ga('SP12-152', 'Spirit of the North 2019 - Infuse Nordic Aurora', {
      look: 'Infuse Studio Spirit of the North (2019) look: stylized low-detail Nordic landscapes, green auroras, snowy rivers, spirit guardians and quiet wordless travel.',
      subject: 'render people and animals as soft stylized figures in snowy landscapes.',
      color: 'Aurora green, snow white and night blue.',
      light: 'Aurora glow and soft moonlight.',
      texture: 'Soft stylized snow and ice.',
      camera: 'Third-person wide travel view.',
      mood: 'serene northern mystery',
      render: 'Authentic stylized adventure screen.',
      key: 'Spirit of the North aurora; Nordic snow',
    }),
    ga('SP12-153', 'Red Dead Redemption 2010 - Rockstar San Diego Frontier', {
      look: 'Rockstar San Diego Red Dead Redemption (2010) look: dusty frontier west, canyon rims, mesas, covered wagons, horseback riders and golden-hour haze.',
      subject: 'render people as dusty frontier riders in hats and dusters.',
      color: 'Canyon red, dust gold and sage.',
      light: 'Golden-hour haze.',
      texture: 'Dusty terrain and worn leather.',
      camera: 'Third-person riding view.',
      mood: 'lonesome frontier grit',
      render: 'Authentic Xbox 360 western screen.',
      key: 'Red Dead 2010 frontier; canyons; riders',
      avoid: ['a scarred cowboy in a tan hat'],
    }),
    ga('SP12-154', 'Silt 2022 - Spiral Circus Monochrome Abyss', {
      look: 'Spiral Circus Silt (2022) look: monochrome underwater puzzle adventure drawn in Mr Mead ink art, surreal abyssal creatures, diving suits and sunken ruins.',
      subject: 'render people as small monochrome divers in heavy suits.',
      color: 'Monochrome black, white and grey.',
      light: 'Ink shafts of light in darkness.',
      texture: 'Dense ink drawing and grain.',
      camera: 'Side-view abyssal view.',
      mood: 'surreal abyssal dread',
      render: 'Authentic monochrome ink adventure screen.',
      key: 'Silt monochrome ink; abyss; diving suit',
    }),
    ga('SP12-155', 'Uncharted 4 2016 - Naughty Dog Expedition', {
      look: "Naughty Dog Uncharted 4: A Thief's End (2016) look: cinematic third-person adventure, rope bridges, cliffs, lush detail, dramatic set pieces and warm realistic light.",
      subject: 'render people as rugged realistic explorers in field gear.',
      color: 'Lava orange, rock grey and jungle green.',
      light: 'Cinematic warm light and lava glow.',
      texture: 'Realistic rock, rope and gear.',
      camera: 'Third-person cinematic view.',
      mood: 'daring adventure thrill',
      render: 'Authentic cinematic adventure screen.',
      key: 'Uncharted 4 set pieces; rope bridges; cinematic',
      avoid: ['a treasure hunter in a henley shirt with a holster'],
    }),
    ga('SP12-156', 'Black Book 2021 - Morteshka Slavic Folk Swamp', {
      look: 'Morteshka Black Book (2021) look: dark Slavic folklore adventure, misty swamps, wooden villages, witches, demons and hand-painted folk art details.',
      subject: 'render people as nineteenth-century Russian villagers and folk spirits.',
      color: 'Swamp green, lantern amber and folk red.',
      light: 'Misty swamp light and lanterns.',
      texture: 'Painted folk art details and wet wood.',
      camera: 'Low canoe view into mist.',
      mood: 'eerie folkloric mystery',
      render: 'Authentic folk adventure screen.',
      key: 'Black Book Slavic folklore; swamp; witches',
    }),
    ga('SP12-157', 'Valheim 2021 - Iron Gate Low-Poly Viking', {
      look: 'Iron Gate Valheim (2021) look: pixelated low-resolution textures with modern volumetric lighting, Viking survival camps, palisades, crafting benches and misty forests.',
      subject: 'render people as low-poly Viking survivors in furs and helmets.',
      color: 'Misty forest green, fire amber and dusk blue.',
      light: 'Volumetric fog and campfire glow.',
      texture: 'Low-resolution pixelated textures.',
      camera: 'Third-person survival view.',
      mood: 'rugged Viking survival',
      render: 'Authentic low-poly survival screen.',
      key: 'Valheim pixel textures; volumetric fog; palisades',
    }),
    ga('SP12-158', 'Xenoblade Chronicles 2 2017 - Monolith Soft Titans', {
      look: 'Monolith Soft Xenoblade Chronicles 2 (2017) look: anime JRPG where people live on giant Titan beasts crossing a cloud sea, vast vistas and colorful anime characters.',
      subject: 'render people as colorful anime adventurers riding giant titans.',
      color: 'Cloud sea white, sky blue and titan green.',
      light: 'Bright open-sky anime light.',
      texture: 'Anime cel with detailed vistas.',
      camera: 'Wide third-person vista.',
      mood: 'vast hopeful journey',
      render: 'Authentic anime JRPG screen.',
      key: 'Xenoblade titans; cloud sea; vast vistas',
      avoid: ['existing Xenoblade characters'],
    }),
  ]),
};

export default spec;
