import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID as AVOID, style } from './_style';

// Aesthetics: named cultural looks (-punk, -core, internet eras). Each preset states the few
// concrete signals that make the look recognizable instead of a mood list. Grimdark drops
// franchise-specific armor and props; representation limits (pixel, 3D emoji) stay explicit.
const spec: Spec = {
  pack: 'pack_11',
  category: '3. Aesthetics',
  updates: {
    'SP11-009': {
      dna: style(
        'Glossy 3D emoji: the subject as a chunky, rounded, candy-glossy icon with a simple expressive face.',
        'simplified into soft inflated volumes with rounded edges, oversized eyes and one clear expression, like a platform emoji rendered in 3D.',
        'Bright saturated candy colors with soft gradients.',
        'Soft top light with big glossy highlights and a gentle contact shadow.',
        'Smooth glossy plastic or gummy material with no fine texture.',
        'Centered single icon on a plain soft gradient background.',
        'Cheerful, readable, cute and instant.',
        'Clean 3D icon render with smooth subdivided surfaces.',
        'inflated rounded forms; glossy highlights; simple face; icon framing',
      ),
      avoid: AVOID,
      briefs: [
        'Glossy 3D emoji of a grumpy little dragon hugging a pile of gold coins, inflated rounded shapes, big glossy highlights, simple frowning face, centered on a soft violet gradient. No text or logo.',
        'Glossy 3D emoji of a friendly skull wearing a tiny crown and winking, candy-white and gold, soft contact shadow, on a plain teal gradient. No text or logo.',
        'Glossy 3D emoji of a haunted castle with a sleepy face in its gate, round towers like gumdrops, purple roofs, on a soft night-blue gradient. No text or logo.',
      ],
    },
    'SP11-010': {
      dna: style(
        'Indexed pixel art: the subject drawn under strict old-console limits, hard square pixels and a tiny fixed palette.',
        'redrawn on a low-resolution grid with hard pixel edges, a limited indexed palette, hand-placed dithering and clear silhouettes.',
        'A fixed palette of about 16 colors, no gradients beyond dithering.',
        'Light shown by palette steps and dither, with one clear light direction.',
        'Crisp square pixels with no anti-aliasing and no blur.',
        'Game-scene framing at native low resolution scaled up with nearest-neighbor.',
        'Nostalgic, precise, crafted and playful.',
        'Hand-placed pixel art with clean clusters and no stray pixels.',
        'hard pixels; indexed palette; dithering; strong silhouettes',
      ),
      avoid: [...AVOID, 'blurry upscaled pixels', 'HUD text'],
      briefs: [
        'Indexed 16-color pixel art of a knight standing before a dragon in a torchlit cave, hard square pixels, hand-placed dithering in the smoke, strong silhouettes, nearest-neighbor upscale. No text or logo.',
        'Pixel art of a witch cottage in a swamp at night, 16-color palette, dithered fog, a single lit window, fireflies as single pixels. No text or logo.',
        'Pixel art of a skeleton merchant in a dungeon shop with potions on shelves, limited palette, clean clusters, no anti-aliasing. No text or logo.',
      ],
    },
    'SP11-011': {
      dna: style(
        'Chrome horizon synthwave: glowing grid floors, a striped sunset sun, chrome edges and magenta-cyan night haze.',
        'placed on a glowing perspective grid under a striped setting sun, edges rimmed in chrome and neon, silhouettes simplified.',
        'Magenta, cyan, violet and hot orange with deep indigo night.',
        'Neon rim light, glowing grid lines and sunset backlight.',
        'Chrome reflections, scanline haze and airbrushed gradients.',
        'Low wide shot toward the horizon with the grid receding.',
        'Nostalgic, cool, electric and dreamy.',
        'Polished retro airbrush and neon render.',
        'perspective grid; striped sun; chrome rim; magenta-cyan haze',
      ),
      avoid: AVOID,
      briefs: [
        'Synthwave chrome horizon: a lone armored knight on a chrome horse riding across a glowing magenta perspective grid toward a huge striped setting sun, cyan rim light, scanline haze. No text or logo.',
        'Giant chrome dragon skull half buried in a glowing magenta grid desert, a striped sunset sun framed between its horns, wireframe mountains behind, airbrushed violet sky with scanline haze. No text or logo.',
        'Chrome wizard tower rising from a glowing grid sea at dusk, cyan neon trim along its spiral stair, magenta lightning striking its tip, palm silhouettes on a distant island. No text or logo.',
      ],
    },
    'SP11-012': {
      dna: style(
        'Solarpunk: hopeful green-tech communities where plants, solar glass and handmade repair live together.',
        'set in a lived-in green city: terraces of gardens, solar canopies, wind sails, stained-glass panels and people working together.',
        'Sunny greens, warm whites, sky blue and copper.',
        'Bright warm daylight filtered through leaves and glass.',
        'Living plants, bamboo, glass, copper and weathered wood.',
        'Wide inhabited view with foreground gardens and deep city layers.',
        'Hopeful, communal, fresh and calm.',
        'Clean detailed illustration or painting.',
        'rooftop gardens; solar canopies; wind sails; communal life',
      ),
      avoid: AVOID,
      briefs: [
        'Solarpunk medieval town rebuilt: a stone castle wrapped in terrace gardens, solar-glass stained windows, wind sails on the towers, villagers repairing a water wheel, warm morning light. No text or logo.',
        'Solarpunk covered market bridge over a clear river, copper arches wrapped in grapevines, solar canopies overhead, people trading bread and seedlings from bicycle carts, children dangling feet over the water. No text or logo.',
        'Solarpunk seed monastery on a green hill, glass domes full of rare plants, monks in patched linen tending terraced water gardens, wind sails turning on the bell tower at sunrise. No text or logo.',
      ],
    },
    'SP11-013': {
      dna: style(
        'Dieselpunk: 1930s-40s heavy industry retrofuturism, huge riveted machines, smoke and searchlights.',
        'set in a world of riveted steel, diesel engines, zeppelins and war-era propaganda-poster weight.',
        'Oily blacks, gunmetal, rust, olive and sodium amber.',
        'Searchlights and furnace glow through smoke.',
        'Riveted steel, grease, soot and heavy canvas.',
        'Low monumental angle with massive machines.',
        'Oppressive, grim, mighty and industrial.',
        'Painterly concept art with heavy forms.',
        'rivets; diesel smoke; searchlights; zeppelins; monumental machines',
      ),
      avoid: [...AVOID, 'real war insignia'],
      briefs: [
        'Dieselpunk siege: a riveted walking fortress with smokestacks crushing through a medieval forest toward a castle, searchlights cutting the smoke, zeppelins overhead. No text or logo.',
        'Dieselpunk knight in riveted gunmetal armor with a diesel engine backpack coughing black smoke, gripping a chain-driven war hammer in a furnace-lit hangar, mechanics in greasy overalls watching. No text or logo.',
        'Dieselpunk airship dock above a smog-choked fortress city at night, riveted black hulls moored to iron towers, sodium lamps, searchlights sweeping the clouds, a propaganda-style heroic statue without any lettering. No text or logo.',
      ],
    },
    'SP11-014': {
      dna: style(
        'Cottagecore: soft pastoral life, wildflower gardens, handmade bread, linen and warm cottage light.',
        'set in a slow rural life of cottage gardens, baking, sewing, foraging and animals.',
        'Soft creams, sage, dusty rose and butter yellow.',
        'Golden afternoon light through windows.',
        'Linen, wicker, wood, flowers and bread crust.',
        'Cozy interior or garden framing with foreground flowers.',
        'Gentle, warm, nostalgic and peaceful.',
        'Soft painterly or photographic finish.',
        'cottage garden; linen; baking; wildflowers; golden light',
      ),
      avoid: AVOID,
      briefs: [
        'Cottagecore witch in a linen apron baking bread in a stone cottage kitchen, dried herbs hanging, a black cat on the sill, golden afternoon light through a small window. No text or logo.',
        'Cottagecore young woman in a linen dress and straw hat foraging chanterelles at the edge of an old forest with her white goat, wicker basket of wildflowers and mushrooms, warm golden meadow light. No text or logo.',
        'Cottagecore tea picnic under a blossoming apple tree, lace cloth, scones and jam, a small moss-green dragon curled around the wicker basket warming the teapot with its breath. No text or logo.',
      ],
    },
    'SP11-015': {
      dna: style(
        'Dark academia: candlelit old universities, tweed, leather books, marble busts and scholarly obsession.',
        'set in old stone colleges and libraries, with students in tweed and wool, candles, inkwells and marble.',
        'Brown, oxblood, forest green, cream and candle gold.',
        'Candlelight and grey window light.',
        'Leather, tweed, parchment, marble and dark wood.',
        'Intimate interior framing with deep shadows.',
        'Melancholic, intellectual, secretive and romantic.',
        'Moody painterly or film-photo finish.',
        'tweed; candlelit library; marble busts; ink and parchment',
      ),
      avoid: AVOID,
      briefs: [
        'Dark academia alchemy seminar at midnight: students in tweed and wool gathered around a candlelit oak table with a skull, astrolabe and bubbling flask, marble busts watching, rain on gothic windows. No readable text or logo.',
        'Dark academia student in a wool sweater asleep at an oak desk in a vaulted library, candle nearly burned out, ink spilled across a star chart, a raven watching from a marble bust, blue dawn in the tall windows. No readable text or logo.',
        'Dark academia secret society meeting in the crypt beneath an old college, students in black robes over tweed holding candles around a stone table with an old skull and a sealed letter, faces half in shadow. No readable text or logo.',
      ],
    },
    'SP11-036': {
      name: 'Vaporwave Mall Haze',
      dna: style(
        'Vaporwave mall haze: empty 90s shopping malls, marble statues, palms, pastel gradients and low-res digital nostalgia.',
        'placed in an empty dreamlike mall or lobby with fountains, palms, marble busts and glossy tiles, a little too clean and quiet.',
        'Pastel pink, teal, lavender and chrome.',
        'Soft even fluorescent light with gradient skies.',
        'Glossy tiles, marble, chrome and low-res image grain.',
        'Symmetrical frontal framing with empty space.',
        'Dreamy, ironic, lonely and nostalgic.',
        'Glossy digital collage finish with mild pixel grain.',
        'empty mall; marble bust; palms; pastel gradients; low-res grain',
      ),
      avoid: AVOID,
      briefs: [
        'Vaporwave empty mall atrium at closing time: a marble statue of a knight beside an indoor fountain, palms in planters, pastel pink and teal gradients, glossy checker tiles, faint low-res grain. No readable text or logo.',
        'Vaporwave hotel lobby after midnight, a sleeping chrome dragon curled around a marble column, an empty grand piano, palms in pink planters, lavender haze and a glossy checker floor reflecting everything. No readable text or logo.',
        'Vaporwave twin escalators rising out of an empty food court into a pastel gradient sky, a lone hooded figure riding up, marble busts on both sides, soft fluorescent glow and low-res grain. No readable text or logo.',
      ],
    },
    'SP11-037': {
      dna: style(
        'Steampunk: Victorian brass-and-steam invention, gears, gauges, goggles and airships.',
        'fitted with brass gears, pressure gauges, copper pipes and steam vents, dressed in Victorian clothing.',
        'Brass, copper, mahogany, cream and soot.',
        'Warm gaslight and steam glow.',
        'Polished brass, riveted copper, leather and steam.',
        'Detailed mid shot with machinery around the subject.',
        'Inventive, adventurous, ornate and romantic.',
        'Detailed illustration or painting.',
        'brass gears; gauges; steam; goggles; airships',
      ),
      avoid: AVOID,
      briefs: [
        'Steampunk clockwork octopus of brass and copper crawling across a Victorian workshop bench, steam venting from its joints, pressure gauges on its head and an inventor in goggles adjusting a gear, warm gaslight. No text or logo.',
        'Steampunk airship pirates in goggles and leather coats swinging on ropes to board a brass zeppelin above sunset clouds, cannon smoke, gears and propellers turning, copper hull glowing warm. No text or logo.',
        'Steampunk jousting knight in brass-trimmed plate riding a clockwork horse with pistons for legs, a steam-powered lance venting white clouds, a crowd of top hats in a Victorian tournament ground. No text or logo.',
      ],
    },
    'SP11-038': {
      dna: style(
        'Biopunk: living technology grown from flesh, veins and tissue in wet labs and organic cities.',
        'fused with grown organic machinery: veins, tendons, membranes, growth vats and pulsing tubes.',
        'Flesh pinks, bile yellow, sick green and dark red.',
        'Wet lab light and bioluminescent glow.',
        'Wet skin, membrane, cartilage and glass vats.',
        'Close, claustrophobic framing.',
        'Unsettling, visceral, strange and feverish.',
        'Detailed painterly render with wet surfaces.',
        'grown machinery; veins; membranes; vats; bioluminescence',
      ),
      avoid: [...AVOID, 'gore'],
      briefs: [
        'Biopunk cathedral grown from living tissue: ribbed vaults of cartilage, glowing veins in the walls, a monk tending a pulsing vat that holds a sleeping whale calf, wet lab light. No text or logo.',
        'Biopunk war horse grown with chitin armor plates and glowing vein-cables along its neck, ridden by a masked rider in a membrane cloak across a foggy wetland at dusk. No text or logo.',
        'Biopunk night market in a medieval alley, stalls selling grown hearts and eyes floating in glass jars, lamps made of bioluminescent jellyfish, a hooded buyer bargaining with a vendor whose arm is grafted tissue. No text or logo.',
      ],
    },
    'SP11-039': {
      dna: style(
        'Gothic horror: crumbling castles, crypts, candlelit aristocrats and vertical menace.',
        'framed by tall vertical shadows and pointed-arch shapes, figures made pale and elegant, surfaces aged and decaying, with the threat kept just out of sight.',
        'Black, blood red, bone white and candle gold.',
        'Candlelight and moonlight with deep shadow.',
        'Stone, velvet, cobwebs and tarnished silver.',
        'Tall vertical framing with looming architecture.',
        'Dread, romantic, decadent and haunted.',
        'Dark painterly finish.',
        'pointed arches; crypt; candelabra; pale aristocrat; moonlight',
      ),
      avoid: AVOID,
      briefs: [
        'Gothic horror: a pale countess in black velvet descending a spiral stone staircase with a candelabra, portraits with scratched-out faces on the walls, moonlight through a broken rose window. No text or logo.',
        'Gothic horror crypt lit by a single guttering candle: the stone effigy of a bishop on his tomb begins to open its eyes, dust falling from its face, a young priest backing away with a silver cross. No text or logo.',
        'Gothic horror castle on a black crag in a thunderstorm, lightning revealing bats around the towers, one high window glowing red, a lone carriage climbing the switchback road below. No text or logo.',
      ],
    },
    'SP11-040': {
      dna: style(
        'Kawaii pastel: super-cute mascot style with round shapes, blushing cheeks and soft pastel colors.',
        'redrawn as a round mascot with big shiny eyes, tiny mouth, blush marks and soft thick outlines.',
        'Pastel pink, mint, baby blue and lavender.',
        'Soft flat light with small sparkles.',
        'Smooth flat color with soft outlines.',
        'Centered mascot with sparkles and small props.',
        'Adorable, sweet, cheerful and soft.',
        'Clean vector-like illustration.',
        'round mascot; blush marks; big eyes; pastel palette; sparkles',
      ),
      avoid: AVOID,
      briefs: [
        'Kawaii pastel grim reaper mascot with big shiny eyes and blush marks, holding a tiny scythe with a heart, sitting on a pastel cloud with sparkles. No text or logo.',
        'Kawaii baby penguin hatching from a pastel speckled egg, yawning with big sleepy eyes and blush marks, tiny flippers, an eggshell hat on its head, mint and pink sparkles. No text or logo.',
        'Kawaii haunted house with a smiling face in its door, round smiling ghosts floating out of the windows, candy-colored bats and a lollipop moon, pastel lavender sky. No text or logo.',
      ],
    },
    'SP11-041': {
      dna: style(
        'Grimdark war fantasy: endless war, cathedral-sized fortresses, filthy armored soldiers and religious fanaticism.',
        'set in a world of permanent war: massive ornate armor worn down by mud and blood, relic-covered banners, skull-carved fortresses.',
        'Mud brown, rust, bone, grim gold and ash grey.',
        'Smoky battlefield light, fire and cold overcast.',
        'Battered plate, torn cloth, bone, soot and stone.',
        'Monumental framing with tiny figures against huge structures.',
        'Bleak, grim, oppressive and fanatical.',
        'Gritty painterly concept art.',
        'battered ornate armor; skull fortress; relic banners; endless war',
      ),
      avoid: [...AVOID, 'franchise armor designs', 'franchise insignia'],
      briefs: [
        'Grimdark siege: exhausted soldiers in battered ornate plate trudging through mud toward a cathedral fortress carved with skulls, tattered relic banners, fires on the horizon, cold overcast light. No text or logo.',
        'Grimdark war priest in battered armor trimmed with bone reading last rites from a chained book over a muddy trench of exhausted soldiers, smoking censer, rain and distant fire. No text or logo.',
        'Grimdark battlefield at dawn: broken siege towers, a toppled giant statue of a saint half sunk in mud, crows over the fallen, a lone standard-bearer still holding a tattered relic banner. No text or logo.',
      ],
    },
    'SP11-042': {
      dna: style(
        'Frutiger Aero: mid-2000s glossy optimism with water, bubbles, green fields, blue skies and glassy UI shine.',
        'placed in a glossy clean world of blue sky, green grass, water droplets, bubbles and aqua glass reflections.',
        'Aqua blue, grass green, white and glossy silver.',
        'Bright clean daylight with lens flares and glass shine.',
        'Glass, water droplets, bubbles and glossy plastic.',
        'Clean airy framing with lots of sky.',
        'Optimistic, fresh, clean and nostalgic.',
        'Glossy 2000s digital render.',
        'aqua glass; bubbles; blue sky; green hills; glossy shine',
      ),
      avoid: AVOID,
      briefs: [
        'Frutiger Aero fantasy: a glossy glass island floating over a green hill under a bright blue sky, water droplets and bubbles drifting, a friendly aqua whale swimming through the air, lens flare. No text or logo.',
        'Frutiger Aero goldfish swimming inside a giant floating water bubble above a bright green meadow, glossy reflections, smaller bubbles drifting, clean blue sky with soft lens flare. No text or logo.',
        'Frutiger Aero penguin made of glossy aqua glass standing on a sunny ice floe, water droplets on its body, bubbles rising around it, bright clean sky and glassy shine. No text or logo.',
      ],
    },
    'SP11-043': {
      dna: style(
        'Postmodern pattern clash: Memphis-style squiggles, terrazzo, checkerboards and bold primary shapes colliding.',
        'rebuilt from bold geometric blocks and patterned surfaces: squiggles, dots, terrazzo, zigzags and checkerboards.',
        'Primary colors with pink, mint and black.',
        'Flat light and hard shadows.',
        'Flat patterned surfaces and laminate.',
        'Playful staged framing with objects on pedestals.',
        'Playful, loud, witty and irreverent.',
        'Crisp graphic render.',
        'squiggles; terrazzo; checkerboard; primary shapes; pedestals',
      ),
      avoid: AVOID,
      briefs: [
        'Postmodern pattern clash: a flamingo made of Memphis-style geometric blocks, checkerboard wings, squiggle neck, terrazzo legs, standing on a pink pedestal with hard shadows. No text or logo.',
        'Memphis-style crocodile built from zigzag, dot and squiggle blocks guarding a terrazzo treasure chest on a mint pedestal, primary yellow teeth, hard black shadows on a pink floor. No text or logo.',
        'Postmodern pattern-clash lighthouse with checkerboard stripes, cylinder balconies in primary colors, squiggle waves and a terrazzo rock, a tiny sailboat passing. No text or logo.',
      ],
    },
    'SP11-045': {
      name: 'Psychedelic Optical Recursion',
      dna: style(
        'Psychedelic recursion: melting patterns, paisley whorls and repeating concentric forms in vibrating colors.',
        'dissolved into nested repeating forms, melting contours and paisley swirls that echo outward from the subject.',
        'Vibrating complementary colors: orange, magenta, green and violet.',
        'Glow comes from color vibration, not light.',
        'Smooth flowing paint and concentric lines.',
        'Centered, radiating composition.',
        'Trippy, hypnotic, ecstatic and strange.',
        'Clean psychedelic illustration.',
        'nested repeats; melting contours; paisley; vibrating colors',
      ),
      avoid: AVOID,
      briefs: [
        'Psychedelic optical recursion of a wizard whose beard melts into endless paisley swirls, concentric echoes of his face radiating outward, vibrating orange, magenta and green. No text or logo.',
        'Psychedelic tiger eye repeating inward in endless nested rings, stripes melting into paisley, vibrating orange and violet, a tiny figure silhouette reflected in the pupil. No text or logo.',
        'Psychedelic forest of giant mushrooms whose caps melt into waves of color, a robed wanderer walking a path that echoes outward in concentric ripples, vibrating green and magenta. No text or logo.',
      ],
    },
    'SP11-066': {
      dna: style(
        'Holographic flake: the subject covered in iridescent glitter flakes that scatter rainbow sparkles.',
        'coated with tiny iridescent flakes and glitter that shift color across the surface.',
        'Rainbow iridescence over silver, violet and pink.',
        'Bright point lights creating sparkle and flare.',
        'Glitter flakes, holographic foil and gloss.',
        'Close hero framing to show sparkle.',
        'Festive, dazzling, glamorous and playful.',
        'Macro sparkle render.',
        'iridescent flakes; rainbow sparkle; holographic foil',
      ),
      avoid: AVOID,
      briefs: [
        'Holographic glitter high-heeled shoe covered in tiny iridescent flakes that scatter rainbow sparkles across black velvet, point lights creating starburst flares on the heel and toe, macro close-up. No text or logo.',
        'Holographic glitter crown resting on a deep violet velvet cushion in a dark throne room, iridescent flakes throwing rainbow sparkles across the stone walls. No text or logo.',
        'Holographic glitter witch hat floating above a black cauldron, iridescent flakes shifting from silver to pink to green, tiny star sparkles and flare, dark background. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Goblincore',
      domain: 'forest floor treasure aesthetic',
      tags: ['goblincore', 'nature', 'aesthetic'],
      dna: style(
        'Goblincore: loving the ugly and overlooked parts of nature, mushrooms, moss, frogs, snails, bones and shiny found treasures.',
        'set on a damp forest floor among moss, mushrooms, snails, frogs, beetles, old bones and collected shiny trinkets.',
        'Moss green, mud brown, mushroom cream and beetle iridescence.',
        'Damp soft light under trees.',
        'Moss, mud, mushroom gills, snail shells and tarnished trinkets.',
        'Low ground-level framing close to the forest floor.',
        'Earthy, cozy, strange and playful.',
        'Detailed illustration or macro photo feel.',
        'moss; mushrooms; frogs; snails; bones; found treasures',
      ),
      avoid: AVOID,
      briefs: [
        'Goblincore: a small goblin sitting on a mossy log sorting a treasure pile of beetle shells, rusty keys and a cracked ring, mushrooms and snails around, damp soft forest light, low ground-level view. No text or logo.',
        'Goblincore frog king wearing an acorn-cap crown on a red toadstool throne, subjects of snails and beetles before him, a hoard of bottle caps and bent spoons behind, dewy moss floor. No text or logo.',
        'Goblincore treasure nook inside a hollow tree: small animal bones, moss, mushrooms, a cracked pocket watch and a jar of shiny pebbles arranged lovingly on a shelf fungus, damp green light. No text or logo.',
      ],
    },
    {
      name: 'Dungeon Synth Cassette Art',
      domain: 'lo-fi medieval fantasy cover aesthetic',
      tags: ['dungeon-synth', 'medieval', 'aesthetic'],
      dna: style(
        'Dungeon synth cover art: murky lo-fi fantasy painting reproduced like a photocopied cassette insert, with small lonely figures, heavy mist and faded ink.',
        'painted as a murky amateur oil or gouache, shrunk small within a wide, mist-filled space, then reproduced in faded photocopy with grain and crushed blacks.',
        'Muted greys, deep blues, forest greens and one faded accent.',
        'Dim mist and moonlight.',
        'Old painting reproduced with copier grain and faded print.',
        'Square-ish cover framing with a lonely distant subject.',
        'Melancholic, mysterious, lonely and ancient.',
        'Lo-fi reproduced painting.',
        'misty castle; lone wanderer; murky paint; copier grain',
      ),
      avoid: AVOID,
      briefs: [
        'Dungeon synth cover art: a lone cloaked wanderer on a misty hill facing a distant ruined tower under a pale moon, murky old painting reproduced with copier grain and faded blues. No readable text or logo.',
        'Dungeon synth cover art of a ruined wizard tower rising above a black pine forest, one window lit, crows circling, murky painting with faded greens and copier grain. No readable text or logo.',
        'Dungeon synth cover art of an ancient king asleep on a stone throne in a mist-filled hall, sword across his knees, candles long cold, faded blue-grey paint with photocopy speckle. No readable text or logo.',
      ],
    },
    {
      name: 'Southern Gothic',
      domain: 'decaying rural gothic aesthetic',
      tags: ['southern-gothic', 'decay', 'aesthetic'],
      dna: style(
        'Southern Gothic: decaying rural mansions, swamps, Spanish moss, humid heat and quiet grotesque secrets.',
        'set among overgrown old houses, cypress swamps, moss-hung oaks, rusty porches and old churches.',
        'Faded whites, moss green, rust and humid gold.',
        'Hazy humid light and dusk.',
        'Peeling paint, moss, rust and damp wood.',
        'Still, wide framing with a lonely figure.',
        'Uneasy, humid, secretive and melancholy.',
        'Painterly or film-photo finish.',
        'Spanish moss; swamp; peeling mansion; humid haze',
      ),
      avoid: AVOID,
      briefs: [
        'Southern Gothic: a woman in a faded white dress standing on the rotting porch of a peeling mansion as a swamp creeps up the steps, Spanish moss on the oaks, humid gold dusk haze. No text or logo.',
        'Southern Gothic white wooden church half sunk in a cypress swamp, a lantern burning in the bell tower, Spanish moss and still black water reflecting it at dusk. No text or logo.',
        'Southern Gothic river baptism at dusk, a gaunt preacher waist-deep in brown water, a congregation in white on the bank, a snake gliding past, humid gold haze through the oaks. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
