import type { Create, Dna, Spec } from '../tools/apply';
import { STYLE_AVOID as AVOID } from './_style';

// Unit-based construction: each preset names its unit, its joint (grout, lead, gap, glue) and how
// light behaves on it. Presets must not share one generic "mosaic" template.
const words = (t: string) => t.split(/\s+/).filter(Boolean).length;
const pad = (t: string, min: number, tail: string) =>
  words(t) < min ? `${t.replace(/\.$/, '')}, ${tail}` : t;

function units(
  aesthetic: string,
  unit: string,
  joint: string,
  light: string,
  color: string,
  mood: string,
  key: string,
): Dna {
  return {
    aesthetic,
    subject_treatment: `Rebuild the prompt's subject and setting entirely from discrete units so it stays recognizable at a glance — unit: ${unit}; joints: ${joint}.`,
    color_and_tone: pad(
      color,
      9,
      'with each unit holding one color so the image is built by juxtaposition.',
    ),
    lighting_and_shadow: pad(light, 9, 'as the physical behavior of this unit.'),
    texture_and_material: `${unit}, set with ${joint}, at a unit size that keeps the subject readable.`,
    camera_and_composition:
      'Keep the prompt framing; unit size and direction follow the subject contours so forms read clearly.',
    atmosphere_and_mood: pad(mood, 8, 'coming from the handcrafted construction.'),
    rendering_and_quality:
      'Crisp, consistent units and joints across the whole image, with no smeared or random fill.',
    key_features: key,
  };
}

const spec: Spec = {
  pack: 'pack_10',
  category: '8. Point, Mosaic And Glass Systems',
  updates: {
    'SP10-072': {
      name: 'Optical Dot Pointillism',
      dna: units(
        'Pointillism: the image built from small dots of pure color that mix optically.',
        'small round dots of pure unmixed paint',
        'visible canvas between dots',
        'Light comes from bright dot juxtaposition, no blending.',
        'Complementary pure colors placed side by side.',
        'Luminous, calm, patient and vibrant.',
        'pure color dots; optical mixing',
      ),
      avoid: AVOID,
      briefs: [
        "Bathers rest by a river at a summer sunset, water, grass and parasols built entirely from small dots of pure color that only blend from a distance. No readable text or logo.",
        "A fishing harbor at dawn fills with boats and gulls made of pure color dots, violet shadows and yellow light mixing on the water. No readable text or logo.",
        "A formal garden of clipped hedges and a fountain shimmers in midday light, every leaf and gravel path built from tiny separate dots. No readable text or logo.",
      ],
    },
    'SP10-073': {
      dna: units(
        'Stone tile mosaic: cut stone and ceramic tesserae laid in flowing rows.',
        'square and cut stone or ceramic tesserae',
        'grey grout lines',
        'Matte stone with slight surface unevenness.',
        'Earthy stone colors with bright accents.',
        'Ancient, durable, patient and crafted.',
        'cut tesserae; flowing rows; grout',
      ),
      avoid: AVOID,
      briefs: [
        "An octopus coils around an ancient amphora in cut stone and ceramic tesserae, each row following the curl of a tentacle. No readable text or logo.",
        "A charioteer races four horses across a floor of ochre, rust and white tesserae laid in curving rows along the flying manes. No readable text or logo.",
        "A sea serpent dives between waves in blue and green tesserae whose flowing rows suggest the whole floor is moving. No readable text or logo.",
      ],
    },
    'SP10-074': {
      dna: units(
        'Stained glass: colored glass pieces joined by dark lead came, glowing with transmitted light.',
        'colored glass pieces',
        'dark lead came lines',
        'Transmitted light glowing through the glass.',
        'Jewel reds, blues, greens and gold.',
        'Sacred, luminous, grand and still.',
        'colored glass; lead came; transmitted glow',
      ),
      avoid: AVOID,
      briefs: [
        "In a chapel window a saint confronts a coiled serpent in ruby and cobalt pieces joined by dark lead came, glowing with morning light. No readable text or logo.",
        "A firebird rises from flames in amber, scarlet and gold glass set in dark lead, backlit by a sunset that sets the whole wall burning. No readable text or logo.",
        "In a cottage window an owl perches on a crescent branch in violet and pale green glass, lead lines tracing each feather. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Divisionist Color Dots',
      domain: 'divisionist brushwork',
      tags: ['divisionism', 'dots', 'unit-art'],
      dna: units(
        'Divisionism: short directional dashes and dots of separated color.',
        'short directional dashes of pure color',
        'small gaps',
        'Vibrating light from separated colors.',
        'Sunlit complementary pairs.',
        'Radiant, energetic, luminous and warm.',
        'directional color dashes',
      ),
      avoid: AVOID,
      briefs: [
        "A farmer's daughter walks through a sunflower field built from short directional dashes of separated yellow, orange and blue. No readable text or logo.",
        "A mountain village at sunset glows in short dashes of separated rose, violet and gold, the rooftops vibrating against the sky. No readable text or logo.",
        "A racing horse and jockey blur forward in short color dashes, separated greens and reds following the direction of the gallop. No readable text or logo.",
      ],
    },
    {
      name: 'Byzantine Gold Tessera',
      domain: 'Byzantine gold mosaic',
      tags: ['byzantine', 'gold-mosaic', 'unit-art'],
      dna: units(
        'Byzantine mosaic: glass and gold-leaf tesserae set at angles to shimmer.',
        'glass and gold-leaf tesserae set at slight angles',
        'dark mortar gaps',
        'Shimmering gold catching light unevenly.',
        'Gold ground with deep blues and reds.',
        'Sacred, radiant, formal and eternal.',
        'gold-leaf tesserae; angled shimmer',
      ),
      avoid: AVOID,
      briefs: [
        "A crowned empress holds a chalice on a shimmering gold ground, glass and gold-leaf tesserae set at angles so she flickers as you move. No readable text or logo.",
        "Two peacocks drink from a fountain in jewel-green and blue glass tesserae against a field of glinting gold. No readable text or logo.",
        "A ship crosses a stylized sea under a gold sky, the tesserae tilted so the waves flash as the viewer walks past. No readable text or logo.",
      ],
    },
    {
      name: 'Roman Floor Mosaic',
      domain: 'Roman floor mosaic',
      tags: ['roman', 'floor-mosaic', 'unit-art'],
      dna: units(
        'Roman floor mosaic: small limestone tesserae in earthy tones with guilloche borders.',
        'small limestone and marble tesserae',
        'worn grout',
        'Matte worn stone.',
        'Terracotta, ochre, black and white.',
        'Ancient, grounded, archaeological and warm.',
        'limestone tesserae; guilloche border',
      ),
      avoid: AVOID,
      briefs: [
        "A gladiator faces a lion in an arena of small limestone tesserae in earthy ochre, rust and grey, framed by a braided border. No readable text or logo.",
        "Octopus, dolphins, eels and fish swirl across a pale floor of small earthy tesserae inside a black and white wave border. No readable text or logo.",
        "A boar hunt with riders and dogs spreads across an old floor of earthy tesserae, one corner lost to a crack in the ground. No readable text or logo.",
      ],
    },
    {
      name: 'Micro-Mosaic',
      domain: 'micro-mosaic',
      tags: ['micro-mosaic', 'fine', 'unit-art'],
      dna: units(
        'Micro-mosaic: tiny glass rods cut into minute tesserae, painterly and fine.',
        'minute glass smalti cut from rods',
        'nearly invisible joints',
        'Soft glassy sheen.',
        'Rich painterly colors.',
        'Precious, delicate, refined and patient.',
        'minute smalti; painterly fine',
      ),
      avoid: AVOID,
      briefs: [
        "A brooch holds a portrait of a woman in a bonnet made of minute glass tesserae, the painterly shading visible only under a loupe. No readable text or logo.",
        "A tiny box lid shows a goldfinch on a thistle, glass rods cut into tesserae so fine the feathers look brushed. No readable text or logo.",
        "A small panel holds a lake landscape with boats and cypresses, microscopic glass tesserae giving the sky a painterly glow. No readable text or logo.",
      ],
    },
    {
      name: 'Pique-Assiette Mosaic',
      domain: 'broken china mosaic',
      tags: ['pique-assiette', 'broken-china', 'unit-art'],
      dna: units(
        'Pique-assiette: broken china plates and cups reassembled into mosaic.',
        'broken china shards with floral patterns',
        'white grout',
        'Glossy glaze highlights.',
        'Blue-and-white and floral china.',
        'Whimsical, thrifty, colorful and homely.',
        'broken china shards; patterned pieces',
      ),
      avoid: AVOID,
      briefs: [
        "A leaping koi covers a garden wall in blue-and-white shards of old plates and cups, fragments of floral pattern forming its scales. No readable text or logo.",
        "A garden bench is covered in shards of floral teacups, handles and rims forming the armrests in a riot of color. No readable text or logo.",
        "An owl perches on a birdbath made of broken dinner plates, pattern fragments forming its feathers and a saucer rim for each eye. No readable text or logo.",
      ],
    },
    {
      name: 'Pebble Mosaic',
      domain: 'pebble mosaic',
      tags: ['pebble', 'mosaic', 'unit-art'],
      dna: units(
        'Pebble mosaic: smooth river pebbles set on edge in patterns.',
        'smooth river pebbles set on edge',
        'packed mortar',
        'Wet sheen on pebbles.',
        'Black, white, grey and ochre pebbles.',
        'Earthy, patient, rhythmic and calm.',
        'pebbles on edge; flowing patterns',
      ),
      avoid: AVOID,
      briefs: [
        "A courtyard floor coils into a sea serpent of black and white river stones set on edge, the pattern gleaming after rain. No readable text or logo.",
        "A sailing ship crosses a harbor path in smooth grey and white stones set on edge, wet footprints walking over the waves. No readable text or logo.",
        "A radiant sun spreads across a garden terrace in rings of ochre and white stones set on edge, a cat asleep at its center. No readable text or logo.",
      ],
    },
    {
      name: 'Sea Glass Mosaic',
      domain: 'sea glass mosaic',
      tags: ['sea-glass', 'mosaic', 'unit-art'],
      dna: units(
        'Sea glass: frosted rounded glass fragments assembled against light.',
        'frosted, rounded sea-glass fragments',
        'clear resin',
        'Soft backlit glow.',
        'Aqua, green, brown and white glass.',
        'Coastal, soft, calm and nostalgic.',
        'frosted sea glass; backlit',
      ),
      avoid: AVOID,
      briefs: [
        "A sea serpent glows aqua and green in a bathroom window made of frosted rounded beach glass set against the light. No readable text or logo.",
        "A mermaid combs her hair in frosted blue, white and amber fragments backlit in a seaside window. No readable text or logo.",
        "A lighthouse on a cliff at sunset glows amber and teal in frosted fragments hanging in a fishing shack window. No readable text or logo.",
      ],
    },
    {
      name: 'Button Mosaic',
      domain: 'button mosaic',
      tags: ['buttons', 'mosaic', 'unit-art'],
      dna: units(
        'Button mosaic: hundreds of sewing buttons forming the image.',
        'assorted sewing buttons with holes',
        'fabric or board gaps',
        'Glossy button highlights.',
        'Assorted button colors.',
        'Playful, homely, crafty and charming.',
        'assorted buttons; visible holes',
      ),
      avoid: AVOID,
      briefs: [
        "A galloping horse is made of hundreds of sewing buttons in browns and creams, wood, shell and brass glued side by side. No readable text or logo.",
        "A peacock spreads a tail of hundreds of blue, green and gold buttons, shiny and matte ones mixed like real plumage. No readable text or logo.",
        "A pocket watch face is built from silver and black buttons on velvet, the largest buttons marking the hours. No readable text or logo.",
      ],
    },
    {
      name: 'Fuse Bead Pixel Art',
      domain: 'fuse bead pixel art',
      tags: ['fuse-beads', 'pixel', 'unit-art'],
      dna: units(
        'Fuse beads: melted plastic tube beads on a pegboard grid.',
        'fused plastic tube beads with center holes',
        'grid adjacency',
        'Soft plastic sheen.',
        'Bright plastic colors.',
        'Playful, retro, crafty and nostalgic.',
        'fused tube beads; center holes',
      ),
      avoid: AVOID,
      briefs: [
        "A spaceship made of melted plastic beads is lifted off a white pegboard by a proud adult hobbyist, every bead hole visible. No readable text or logo.",
        "A strawberry cake slice made of pink and red beads, melted slightly unevenly, lies on a kitchen table beside a real fork. No readable text or logo.",
        "A frog on a lily pad is fused from green and pink beads with open holes, a tray of loose beads spilled beside it. No readable text or logo.",
      ],
    },
    {
      name: 'Rhinestone Mosaic',
      domain: 'rhinestone mosaic',
      tags: ['rhinestone', 'sparkle', 'unit-art'],
      dna: units(
        'Rhinestone mosaic: faceted crystals set edge to edge.',
        'faceted crystal rhinestones',
        'tight glue setting',
        'Sparkling facet flashes.',
        'Crystal colors.',
        'Glamorous, sparkling, kitsch and bright.',
        'faceted rhinestones; sparkle',
      ),
      avoid: AVOID,
      briefs: [
        "A crowned skull glitters under a spotlight, faceted crystals set edge to edge across black velvet. No readable text or logo.",
        "A flamingo sparkles on a stage backdrop in pink and gold crystals set edge to edge, scattering light across the curtain. No readable text or logo.",
        "A moth glitters in the dark on a clutch bag, grey and amber crystals set edge to edge along its wings. No readable text or logo.",
      ],
    },
    {
      name: 'Opus Sectile Inlay',
      domain: 'opus sectile stone inlay',
      tags: ['opus-sectile', 'inlay', 'unit-art'],
      dna: units(
        'Opus sectile: large cut stone shapes fitted into a picture.',
        'large cut marble and stone shapes',
        'hairline joints',
        'Polished stone reflections.',
        'Colored marbles and porphyry.',
        'Grand, ancient, precise and noble.',
        'cut stone shapes; hairline joints',
      ),
      avoid: AVOID,
      briefs: [
        "A lion attacks a stag in large shaped pieces of colored marble fitted together without grout, a relic from a palace floor. No readable text or logo.",
        "A sailing boat crosses a stylized sea made of large cut pieces of blue, white and grey marble fitted into one picture. No readable text or logo.",
        "A tiger stalks among reeds in large cut stones of ochre and green fitted so tightly the joins disappear. No readable text or logo.",
      ],
    },
    {
      name: 'Pietra Dura',
      domain: 'pietra dura hardstone inlay',
      tags: ['pietra-dura', 'inlay', 'unit-art'],
      dna: units(
        'Pietra dura: polished hardstones inlaid seamlessly into black marble.',
        'polished semi-precious hardstones',
        'invisible seamless joints',
        'High polish.',
        'Lapis, malachite, coral on black marble.',
        'Precious, refined, elegant and rich.',
        'hardstone inlay on black marble',
      ),
      avoid: AVOID,
      briefs: [
        "A tabletop of black marble is inlaid with a firebird in lapis and coral, the polished hardstones fitted seamlessly under soft light. No readable text or logo.",
        "A box lid shows a parrot on a branch in malachite, carnelian and lapis set seamlessly into black marble. No readable text or logo.",
        "A panel of flowers and a dragonfly glows in polished hardstones inlaid into black marble without a visible seam. No readable text or logo.",
      ],
    },
    {
      name: 'Marquetry Wood Inlay',
      domain: 'wood marquetry',
      tags: ['marquetry', 'wood', 'unit-art'],
      dna: units(
        'Marquetry: veneers of different woods cut and fitted into pictures.',
        'wood veneer pieces of different species',
        'tight fitted seams',
        'Satin varnish sheen.',
        'Wood tones from pale maple to dark ebony.',
        'Crafted, warm, refined and patient.',
        'wood veneers; fitted seams',
      ),
      avoid: AVOID,
      briefs: [
        "A hunter rides past a forest lodge in contrasting veneers of maple, walnut and ebony cut and fitted together on a cabinet door. No readable text or logo.",
        "A sailing ship in a storm is fitted from dark walnut sea and pale sycamore sails across the lid of a writing desk. No readable text or logo.",
        "An owl sits on a branch in contrasting veneers, finely cut feathers and a figured-wood moon behind it. No readable text or logo.",
      ],
    },
    {
      name: 'Tiffany Lampshade Glass',
      domain: 'tiffany-style lamp glass',
      tags: ['tiffany-glass', 'lamp', 'unit-art'],
      dna: units(
        'Tiffany-style lamp glass: opalescent glass pieces with copper-foil seams glowing warmly.',
        'opalescent streaky glass pieces',
        'copper-foil soldered seams',
        'Warm glow from within.',
        'Amber, green and dragonfly blues.',
        'Warm, ornate, cozy and luminous.',
        'opalescent glass; copper-foil seams; warm glow',
      ),
      avoid: AVOID,
      briefs: [
        "Wisteria blossoms glow in opalescent glass on a lampshade in a dim study, copper-foil seams warming the whole room. No readable text or logo.",
        "A heron stands among irises in an opalescent window panel, copper-foil seams glowing in the afternoon light. No readable text or logo.",
        "Moths and wisteria glow on a lampshade by a bed, warm light passing through milky opalescent pieces. No readable text or logo.",
      ],
    },
    {
      name: 'Grisaille Leaded Glass',
      domain: 'grisaille painted glass',
      tags: ['grisaille', 'glass', 'unit-art'],
      dna: units(
        'Grisaille glass: clear and grey painted glass with fine lead lines and delicate shading.',
        'clear glass panes painted in grey grisaille',
        'thin lead lines',
        'Soft silvery transmitted light.',
        'Silver-grey with pale yellow stain accents.',
        'Austere, delicate, sacred and quiet.',
        'grey painted glass; thin lead',
      ),
      avoid: AVOID,
      briefs: [
        "A praying monk appears in silvery grey painted glass with delicate shading and yellow stain accents, fine lead lines crossing his robe. No readable text or logo.",
        "In a garden room a grape trellis climbs across clear panes painted in soft grey enamel, only the ripe clusters touched with yellow. No readable text or logo.",
        "A stag stands in a forest of silvery grey glass, fine lead lines and delicate shading lit from behind at dusk. No readable text or logo.",
      ],
    },
    {
      name: 'Fused Glass Slab',
      domain: 'fused glass',
      tags: ['fused-glass', 'glass', 'unit-art'],
      dna: units(
        'Fused glass: glass pieces kiln-fused into one slab with rounded edges and bubbles.',
        'kiln-fused glass pieces',
        'melted, rounded seams',
        'Backlit glow with bubbles.',
        'Saturated glass colors.',
        'Modern, glowing, crafted and fluid.',
        'kiln-fused glass; rounded seams; bubbles',
      ),
      avoid: AVOID,
      briefs: [
        "Backlit in a studio window, a rising firebird melted into one slab shows rounded seams and trapped bubbles glowing like embers. No readable text or logo.",
        "A bowl of melted glass shows a coral reef with rounded edges and trapped bubbles on a sunny kitchen table. No readable text or logo.",
        "A blue jellyfish floats in a slab of kiln-melted glass, rounded seams and tiny bubbles glowing in a window. No readable text or logo.",
      ],
    },
    {
      name: 'Paper Quilling Coils',
      domain: 'paper quilling',
      tags: ['quilling', 'paper', 'unit-art'],
      dna: units(
        'Quilling: rolled paper strip coils shaped and glued edge-on.',
        'rolled paper strip coils',
        'glued edge-on contact',
        'Soft shadows between coils.',
        'Paper colors.',
        'Delicate, crafty, intricate and charming.',
        'rolled paper coils; edge-on',
      ),
      avoid: AVOID,
      briefs: [
        "A dragon made of rolled paper strips glued edge-on curls around a candle, red and gold coils forming every scale. No readable text or logo.",
        "A peacock spreads a coiled tail of teal and gold rolled strips glued edge-on to a pale board. No readable text or logo.",
        "A hot-air balloon drifts over rolling hills, its envelope built from tight striped coils of red and cream paper. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
