import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, beasts, guardians and chimeras: culture-rooted visual languages for gate guardians,
// composite creatures and sacred animals. Ten originals stay; thirteen new looks add Chinese,
// Korean, Persian, Assyrian, South Indian, Russian, Scythian, Armenian and Caucasian, Edo, Etruscan, Pictish,
// Mughal and Tibetan traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} beast and guardian art`,
  tags: [tag, culture.toLowerCase().replace(/\s+/g, '-'), 'mythic-beasts', 'portable-style-study'],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Beasts, Guardians & Chimeras',
  updates: {},
  creates: [
    s(
      'Qilin Silk Rank Badge',
      'qilin-badge',
      'Chinese',
      'Qilin silk rank badge: Chinese court embroidery squares where a scaled, hoofed qilin prances among five-colored clouds, rocks and wave stripes, stitched in couched gold thread and satin floss.',
      'stitch the subject as a scaled, hoofed guardian beast prancing on clouds above striped waves.',
      'Midnight blue silk, couched gold, coral red, jade green and cloud white.',
      'Silk sheen and gold thread glint rather than cast shadow, even and rich.',
      'Satin stitch floss, couched gold thread, seed knots and silk ground grain.',
      'Square badge composition with the beast centered above wave stripes and a sun disc in one corner.',
      'auspicious noble calm',
      'Dense precise embroidery with every scale and cloud outlined in gold thread.',
      'qilin beast; five-colored clouds; wave stripes; couched gold thread',
      [
        'Prancing across a square of midnight silk, a scaled beast with deer hooves and a flaming mane steps so lightly on the clouds that the stitched waves below stay perfectly still. No readable text or logo.',
        'Stitched into a court square, a stern guardian beast has turned to stare at the embroidered sun, which appears to be sweating gold thread under the pressure. No readable text or logo.',
        'In one corner of a silk square, a single cloud has come unstitched, and a tiny gold hoof dangles from it into the plain blue silk. No readable text or logo.',
      ],
    ),
    s(
      'Dancheong Eave Guardians',
      'dancheong-guardians',
      'Korean',
      'Dancheong eave guardians: Korean palace and temple painting on carved wooden eaves and brackets, with lotus, cloud and flame bands framing haetae, dragons and phoenix heads in mineral green and red.',
      'paint the subject as a guardian carved and painted into the colorful bracket work under a palace roof.',
      'Malachite green, cinnabar red, azurite blue, ochre yellow and white outlines.',
      'Soft shade under deep eaves with painted colors glowing out of the dimness.',
      'Carved wood brackets, mineral paint layers, crisp white outlines and weathered lacquer.',
      'Low view upward into stacked brackets and eaves, beast heads emerging from the pattern.',
      'protective ornate vigilance',
      'Crisp symmetrical decorative painting with repeated banded motifs.',
      'haetae guardian; bracket work; lotus and cloud bands; mineral green and red',
      [
        'Emerging from the painted brackets under a palace roof, a flame-maned lion dog bares its teeth at an approaching storm while dragons coil through the green and red cloud bands around it. No readable text or logo.',
        'Under a temple roof, a painted guardian beast has been staring down the same courtyard for five hundred years and has finally spotted a monk sneaking an extra dumpling. No readable text or logo.',
        'High under an empty palace roof at dusk, the painted lotus bands glow faintly, and one carved beast head has quietly closed its eyes. No readable text or logo.',
      ],
    ),
    s(
      'Simurgh Manuscript Painting',
      'simurgh-manuscript',
      'Persian',
      'Simurgh manuscript painting: Persian illuminated manuscript painting of the great healing bird with a peacock tail sweeping over jewel-colored rocks, gold skies and flowering trees.',
      'paint the subject in a jewel-bright manuscript scene beneath a vast bird with streaming peacock plumes.',
      'Lapis blue, gold sky, rose, emerald, lilac rocks and vermilion.',
      'Shadowless even light with gold backgrounds that shine on their own.',
      'Opaque watercolor, burnished gold, fine brush line and illuminated borders.',
      'High vertical page with stacked space, the great bird curving across the upper sky.',
      'marvelous protective wonder',
      'Exquisite miniature detail with rhythmic plumes and patterned rocks.',
      'great healing bird; peacock plumes; lilac rocks; gold sky',
      [
        'Sweeping down from a mountain nest across a burnished gold sky, an immense bird with a river of peacock plumes lifts an abandoned adult prince from the lilac rocks. No readable text or logo.',
        'Drifting from the tail of a giant healing bird, a single plume lands in a busy market, and every merchant stops arguing to stare at it. No readable text or logo.',
        'On a jewel-colored mountain at dawn, an enormous empty nest sits among flowering trees, and one feather still glows gold. No readable text or logo.',
      ],
    ),
    s(
      'Lamassu Gate Relief',
      'lamassu-relief',
      'Assyrian',
      'Lamassu gate relief: Assyrian palace gateway colossi, human-headed winged bulls carved in gypsum with curled beards, feathered wings and five legs seen from front and side.',
      'carve the subject as a colossal winged guardian relief flanking a palace gate.',
      'Pale gypsum, sand, faded red and black pigment traces.',
      'Raking desert light cutting deep shadows into carved feathers and curls.',
      'Carved alabaster, chisel marks, crisp curled beards and worn edges.',
      'Low monumental view past the guardian toward a tiny figure in the gateway.',
      'immovable sovereign guard',
      'Sharp monumental relief carving with deep rhythmic detail.',
      'winged bull guardian; curled beard; feathered wings; palace gateway',
      [
        'Standing between two colossal winged bulls with carved beards, a tired adult messenger raises a clay tablet at dusk while the stone guardians seem to lean in to read it first. No readable text or logo.',
        'Carved with five legs so it looks right from every angle, a winged palace guardian has finally started walking and nobody knows which leg to watch. No readable text or logo.',
        'In a ruined palace doorway, one winged stone bull still stands in raking dawn light, with sand drifted to the height of its knees. No readable text or logo.',
      ],
    ),
    s(
      'Yali Temple Pillar',
      'yali-pillar',
      'South Indian',
      'Yali temple pillar: South Indian temple halls with rearing leonine yali carved from single granite columns, elephant trunks, bulging eyes and riders, receding in long pillared corridors.',
      'carve the subject into a rearing granite pillar creature in a long temple corridor.',
      'Warm grey granite, oiled black stone, marigold orange and lamp gold.',
      'Oil lamp glow along a dark corridor catching the curves of carved muscle.',
      'Polished granite, deep undercut carving, oil sheen and worn edges.',
      'Long corridor perspective of repeating pillars, one creature rearing close to the lens.',
      'fierce sacred vitality',
      'Deeply undercut sculptural carving with rhythmic repetition, kept consistent across the whole image.',
      'rearing leonine beast; granite pillar; elephant trunk; pillared corridor',
      [
        'Rearing out of carved granite with a stone ball rolling loose in its jaws, a lion-bodied beast with an elephant trunk towers over a pilgrim carrying a brass lamp down the long corridor. No readable text or logo.',
        'In a thousand-column hall, every carved beast rears in the same direction except one, which has turned to look at the visitors. No readable text or logo.',
        'At the end of a dark granite corridor, a single oil lamp lights one stone claw, and marigold petals lie at its feet. No readable text or logo.',
      ],
    ),
    s(
      'Izba Window Sirin Carving',
      'izba-sirin',
      'Russian folk',
      'Izba window sirin carving: Russian carved and painted wooden window frames on log houses, with lacy fretwork, lions, sirin bird-maidens and sun rosettes in faded blue, white and green.',
      'carve the subject into the painted fretwork frame of a wooden village window.',
      'Faded sky blue, chalk white, moss green, weathered log brown and snow.',
      'Low winter sun raking across carved fretwork, casting lacy shadows on logs.',
      'Carved pine fretwork, flaking paint, cracked logs and frosted glass.',
      'Frontal window frame filling the image with carved figures around the glass.',
      'wistful folk enchantment',
      'Crisp woodcraft detail with symmetrical ornament, kept consistent across the whole image.',
      'carved window frame; bird-maiden; fretwork lions; sun rosettes',
      [
        'Perched above a frosted village pane, a bird-maiden with a crowned human face spreads fretwork wings between two grinning lions as smoke curls from the chimney into a pale winter sky. No readable text or logo.',
        'On a log house frame, two wooden lions have been painted by different neighbors and now disagree completely about what lions look like. No readable text or logo.',
        'In a snowbound village at dusk, one lamp glows behind frosted glass, and the wooden bird-maiden above it throws a long lacy shadow. No readable text or logo.',
      ],
    ),
    s(
      'Scythian Animal-Style Gold',
      'scythian-gold',
      'Scythian steppe',
      'Scythian animal-style gold: steppe nomad gold plaques of stags with curled antlers, twisting griffins and felines turned back on themselves, beast bodies folded into tight ornamental loops.',
      'hammer the subject into a gold plaque, the body folded and twisted into a tight looping animal shape.',
      'Burnished gold, dark patina, garnet red and steppe grass tones.',
      'Warm glint on raised gold forms against black velvet darkness.',
      'Repousse gold, granulation, inlaid stones and hammer marks.',
      'Tight single-object composition with the creature twisted to fill its outline.',
      'fierce nomadic grace',
      'Sculptural goldsmith detail with bold simplified animal forms.',
      'curled stag; twisting griffin; folded beast body; repousse gold',
      [
        'Folded into a single gleaming plaque, a stag with antlers curling into bird heads gallops forever while a griffin twists over its back to seize it, all hammered from one sheet of metal. No readable text or logo.',
        'Hammered into a belt buckle, a panther has curled so tightly around itself that it seems to be chasing its own tail with great dignity. No readable text or logo.',
        'On black velvet in a dim room, one small stag lies folded into a perfect circle, its garnet eye catching the only light. No readable text or logo.',
      ],
    ),
    s(
      'Caucasian Dragon Carpet',
      'dragon-carpet',
      'Armenian and Caucasian',
      'Caucasian dragon carpet: Armenian and Caucasian knotted pile carpets where stylized dragons become angular S-shaped emblems locked in a diagonal lattice with palmettes, stars and hooked borders.',
      'weave the subject as an angular stylized beast emblem locked into a knotted carpet lattice.',
      'Madder red, indigo, ivory, saffron yellow and walnut brown.',
      'Soft window light grazing the pile so knots and worn patches show.',
      'Hand-knotted wool pile, abrashed dye bands, worn fringe and pixel-like knot steps.',
      'Top-down carpet field with repeating lattice cells and a hooked border.',
      'ancient guardian pattern',
      'Crisp geometric weaving with stepped knot edges, kept consistent across the whole image.',
      'angular dragon emblems; diagonal lattice; palmettes; hooked border',
      [
        'Stepped into the knots of a madder red carpet, angular dragons with hooked jaws coil through a diagonal lattice of palmettes as a real dragon asleep on the carpet tries to match their pose. No readable text or logo.',
        'In a knotted carpet, one stylized dragon has been woven slightly wrong, and every other dragon in the lattice is turning to look at it. No readable text or logo.',
        'Across the worn middle of an old carpet, the dragons have faded almost to the warp threads, and a single cat sleeps in the brightest cell. No readable text or logo.',
      ],
    ),
    s(
      'Edo Court Leopard Bronze',
      'edo-leopard',
      'Edo Benin',
      'Edo court leopard bronze: lost-wax brass leopards of the Benin court with spotted bodies made of punched rings, alert heads, and ornamented guardian figures on dark palace grounds.',
      'cast the subject as a spotted brass guardian figure with punched ring markings.',
      'Warm brass, dark patina, red coral beads and clay red.',
      'Low palace lamp light gleaming along cast brass curves.',
      'Lost-wax brass, punched ring spots, chased lines and patina.',
      'Frontal alert stance filling the frame against a plain dark ground.',
      'regal watchful power',
      'Refined cast-metal sculpture with crisp surface pattern, kept consistent across the whole image.',
      'spotted brass leopard; punched rings; coral beads; alert stance',
      [
        'Standing guard at a palace doorway, a pair of spotted brass big cats with punched ring coats and coral bead collars lift their heads as a royal procession passes in lamplight. No readable text or logo.',
        'Cast in brass with hundreds of punched spots, a royal big cat sits perfectly still for its portrait while a real house cat investigates its tail. No readable text or logo.',
        'In a dim palace hall, a single brass big cat stands on a clay altar, and lamplight moves across its spots like breath. No readable text or logo.',
      ],
    ),
    s(
      'Etruscan Bronze Chimera',
      'etruscan-chimera',
      'Etruscan',
      'Etruscan bronze chimera: ancient Italic cast bronze of the three-headed fire beast, lion body, goat head rising from its back and serpent tail, snarling with wounded tension.',
      'cast the subject as a snarling dark bronze creature with ancient green patina.',
      'Dark bronze, verdigris green, earth red and dusty ochre.',
      'Museum spot and dusk light raking over tense cast musculature.',
      'Cast bronze, chased mane locks, green patina and pitted surface.',
      'Low three-quarter view of the creature crouching, tension in every limb.',
      'wounded defiant menace',
      'Powerful sculptural bronze with crisp stylized mane, kept consistent across the whole image.',
      'three-headed beast; lion body; goat head; serpent tail',
      [
        'Crouched on a rocky hillside at dusk, a snarling beast with a lion body, a goat head on its back and a serpent for a tail braces against a spear that has already struck. No readable text or logo.',
        'A three-headed beast argues with itself, the lion wanting to fight, the goat wanting to graze and the serpent tail simply wanting to sleep. No readable text or logo.',
        'In an empty museum hall at closing time, a green metal tail curls out from behind a column, its serpent head watching the door. No readable text or logo.',
      ],
    ),
    s(
      'Pictish Symbol Stone Beast',
      'pictish-beast',
      'Pictish',
      'Pictish symbol stone beast: carved standing stones of early Scotland with the mysterious long-snouted Pictish beast, crescents, V-rods, serpents and interlace cut into grey rock.',
      'incise the subject into a weathered standing stone with mysterious symbols around it.',
      'Lichen grey, moss green, peat brown and cold sky white.',
      'Overcast highland light with low raking sun showing incised lines.',
      'Incised stone lines, lichen patches, rain weathering and moss.',
      'Tall standing stone in a moorland, carved figure centered on its face.',
      'ancient enigmatic stillness',
      'Clean incised line carving with smooth spiral curves.',
      'long-snouted beast; crescent and rod; incised standing stone; moorland',
      [
        'Cut into a lichen-covered monolith on a windswept moor, a long-snouted creature with scrolling feet curls above a crescent and rod as rain clouds drag across the hills. No readable text or logo.',
        'Carved into an ancient monolith, a mysterious creature has puzzled scholars for centuries and seems to enjoy it very much. No readable text or logo.',
        'On a foggy moor, a lone monolith rises from the heather, and the carved creature on it is wet with rain. No readable text or logo.',
      ],
    ),
    s(
      'Mughal Composite Beast Painting',
      'mughal-composite',
      'Mughal and Deccani',
      'Mughal composite beast painting: Indian court album paintings where an elephant, horse or camel is built entirely from interlocking smaller figures, animals, spirits and people.',
      'paint the subject as a single large animal built from many interlocking smaller creatures and figures.',
      'Soft buff, gold, pale green, rose and ink outlines.',
      'Even gentle album light on a plain ground.',
      'Opaque watercolor, fine brush line, burnished paper and gold rules.',
      'Single striding composite animal centered on a plain page with a gold border.',
      'playful inventive marvel',
      'Exquisite fine-line miniature with every inner figure legible.',
      'composite animal; interlocking creatures; plain page; fine line',
      [
        'Striding across a plain buff page, a great elephant is built entirely from interlocking tigers, fish, dancers, spirits and birds, and an adult rider on top is also made of tiny animals. No readable text or logo.',
        'Built from forty smaller animals, a camel has a problem because the rabbit forming its knee wants to leave. No readable text or logo.',
        'On an otherwise empty album page, one small bird rests alone where the horse made of animals was supposed to begin. No readable text or logo.',
      ],
    ),
    s(
      'Snow Lion Thangka Banner',
      'snow-lion',
      'Tibetan',
      'Snow lion thangka banner: Tibetan painted scrolls and banners of white snow lions with turquoise manes and tails, leaping among mountain peaks, clouds and jewel flames.',
      'paint the subject as a leaping white lion with a turquoise mane among snow peaks and clouds.',
      'Snow white, turquoise, deep lapis, gold and coral red.',
      'Clear high-altitude light with gold outlines shining, kept consistent across the whole image.',
      'Mineral pigment on cotton, gold line, silk brocade border.',
      'Dynamic leaping pose across a mountain scroll with brocade frame.',
      'joyful fearless energy',
      'Precise painted scroll with flowing curling manes, kept consistent across the whole image.',
      'white lion; turquoise mane; snow peaks; jewel flames',
      [
        'Bounding between icy peaks with its turquoise mane streaming, a white beast leaps across the clouds holding a jewel flame as prayer flags snap in the high wind below. No readable text or logo.',
        'Two white beasts with turquoise manes play with a single jewel like kittens with a ball, completely forgetting they are meant to look fierce. No readable text or logo.',
        'High on a quiet mountain pass, fresh paw prints cross the fresh powder and vanish into a turquoise cloud. No readable text or logo.',
      ],
    ),
  ],
};

export default spec;
