import type { Create, Spec } from '../tools/apply';
import { ANIME_AVOID as AVOID, anime } from './_anime';

// Slice of life, school and music (part B): more light-and-mood looks. Venues in the briefs are
// only tests of the look; the DNA carries light, palette and line.
const spec: Spec = {
  pack: 'pack_13',
  category: '2. Slice Of Life, School And Music',
  updates: {},
  creates: [
    {
      name: 'Seaside Summer Haze Anime',
      domain: 'summer seaside anime',
      tags: ['summer', 'seaside', 'anime'],
      dna: anime(
        'Seaside summer haze anime: saturated blue skies, towering cumulus clouds, heat shimmer and bright white light.',
        'clean simple lines, sun-squinting faces, sweat beads, hair and shirts moving in sea wind.',
        'Saturated cobalt sky, white clouds, sea teal and sun-bleached colors.',
        'Harsh midday sun with heat haze and deep short shadows.',
        'Cel with painted clouds and shimmer.',
        'Wide horizon frames with big sky.',
        'Free, lazy, nostalgic and bright.',
        'cumulus towers; heat haze; cobalt sky; sea wind',
      ),
      avoid: AVOID,
      briefs: [
        'Seaside summer anime frame of a young fisher girl and a sea-serpent hatchling sharing a melting ice pop on a harbor wall, towering cumulus over a cobalt sea, heat haze shimmering on the stones, bright white sun. No readable text or logo.',
        'Summer haze anime frame of a boy pushing a bicycle up a coastal hill road, cicada-loud stillness, sweat on his neck, the sea blazing below and a lighthouse in the distance. No readable text or logo.',
        'Summer anime frame of friends lying on a wooden pier with feet in the water, clouds reflected on the flat sea, a paper boat drifting toward a small island shrine. No readable text or logo.',
      ],
    },
    {
      name: 'Dawn Practice Mist Anime',
      domain: 'early morning practice anime',
      tags: ['dawn', 'practice', 'anime'],
      dna: anime(
        'Dawn practice anime: cold blue early mornings, mist on fields, breath and determined solitary training.',
        'focused determined faces, repeated practice poses, mist drawn in soft layers.',
        'Cold blue-grey with the first pale gold on the horizon.',
        'Pre-dawn blue light turning gold.',
        'Cel with soft mist layers.',
        'Wide lonely frames with small figures.',
        'Determined, lonely, quiet and hopeful.',
        'mist layers; pre-dawn blue; solitary practice',
      ),
      avoid: AVOID,
      briefs: [
        'Dawn practice anime frame of a young squire swinging a wooden sword alone in a misty training yard before sunrise, breath clouds, dew on the practice dummies, the first gold light touching the castle towers. No readable text or logo.',
        'Dawn anime frame of a runner on a foggy riverside path, only her silhouette and breath visible, a heron lifting off the water. No readable text or logo.',
        'Dawn anime frame of an archer loosing arrows at a target in a misty field, quiver half empty, sky turning pale gold. No readable text or logo.',
      ],
    },
    {
      name: 'Rooftop Wind Anime',
      domain: 'wind and sky anime',
      tags: ['wind', 'sky', 'anime'],
      dna: anime(
        'Rooftop wind anime: sky-dominated frames with strong wind, flapping clothes and hair, and sweeping clouds.',
        'dynamic windblown hair and cloth, open body poses, speed of clouds drawn with long strokes.',
        'Bright sky blue and white with small warm accents.',
        'Clear daylight with fast cloud shadows.',
        'Cel with painted streaking clouds.',
        'Low angles with most of the frame sky.',
        'Free, restless, open and youthful.',
        'windblown cloth; big sky; streaking clouds',
      ),
      avoid: AVOID,
      briefs: [
        'Rooftop wind anime frame of a young tower guard leaning into a strong wind on castle battlements, cloak and hair streaming, a paper kite torn loose and flying away, huge clouds racing across a bright sky. No readable text or logo.',
        'Anime frame of two friends on a school rooftop holding their skirts and jackets against gusts, laughing, fence rattling. No readable text or logo.',
        'Rooftop wind anime frame of a young witch standing on a windmill roof as her hat flies off, seeds and autumn leaves swirling past, the sails turning and the sky racing with clouds. No readable text or logo.',
      ],
    },
    {
      name: 'Late Train Window Anime',
      domain: 'night train melancholy anime',
      tags: ['train', 'night', 'anime'],
      dna: anime(
        'Late train anime: night commuter frames with window reflections, passing lights and tired quiet passengers.',
        'still tired poses, reflections layered over faces, streaked passing lights.',
        'Deep blue night, fluorescent green-white and warm passing lights.',
        'Train interior light and passing streetlights.',
        'Cel with reflective glass layers.',
        'Seat-level frames through windows.',
        'Melancholic, tired, reflective and quiet.',
        'window reflections; streaked lights; tired passengers',
      ),
      avoid: AVOID,
      briefs: [
        'Late train anime frame of a weary young knight in dented armor dozing against a train window at night, her reflection layered over the passing lights of a dark countryside, a small dragon asleep in her lap. No readable text or logo.',
        'Late train anime frame of a nearly empty carriage at midnight, fluorescent light humming, a single passenger in a traveling cloak watching her own reflection over the dark fields, rain streaking the glass. No readable text or logo.',
        'Late train anime frame of two strangers on a night train sharing one pair of earphones without speaking, passing station lights sliding across their faces, both almost smiling. No readable text or logo.',
      ],
    },
    {
      name: 'Soft Focus Letter Anime',
      domain: 'soft focus romantic anime',
      tags: ['soft-focus', 'romance', 'anime'],
      dna: anime(
        'Soft focus anime: dreamy frames with shallow depth, glowing bokeh and gentle blur, like remembered moments.',
        'sharp focus on one small detail (hands, a letter, eyes) with everything else melting into bokeh.',
        'Soft creams, rose and pale gold.',
        'Backlit glow with bokeh circles.',
        'Cel with blur and glow layers.',
        'Very shallow depth close-ups.',
        'Tender, nostalgic, dreamy and intimate.',
        'bokeh; shallow focus; glowing backlight',
      ),
      avoid: AVOID,
      briefs: [
        'Soft focus anime close-up of a young woman holding a sealed letter with a wax dragon seal, her fingers in sharp focus while her face and the candlelit room melt into warm bokeh. No readable text or logo.',
        'Soft focus anime close-up of two hands exchanging a single white flower at a garden gate, the flower sharp, the faces and lantern-lit garden melting into rose and gold bokeh. No readable text or logo.',
        'Soft focus anime extreme close-up of an eye reflecting a string of warm fairy lights and a distant figure, lashes sharp, everything else dissolving into glowing circles. No readable text or logo.',
      ],
    },
    {
      name: 'Club Room Clutter Comedy',
      domain: 'cluttered comedy anime',
      tags: ['comedy', 'clutter', 'anime'],
      dna: anime(
        'Club room clutter comedy: dense, busy frames packed with props, posters and chaotic group reactions.',
        'dense background detail, chibi reactions, comedic sweat drops and exaggerated poses.',
        'Busy colorful props with warm light.',
        'Flat warm light.',
        'Cel with dense line detail.',
        'Wide busy frames.',
        'Chaotic, silly, cozy and lively.',
        'dense clutter; chibi reactions; group chaos',
      ),
      avoid: AVOID,
      briefs: [
        'Club room clutter comedy anime frame of a monster-research club room packed with jars, taxidermy, maps and a sleeping baby griffin, five members reacting in chibi panic as a potion bubbles over. No readable text or logo.',
        'Club room clutter comedy anime frame after a failed cake experiment: frosting on the ceiling, a scorched oven, flour everywhere and four members frozen in chibi shock as the club president walks in. No readable text or logo.',
        'Club room clutter anime frame of a band rehearsal in a tiny room crammed with amps, costumes and snack boxes, a drummer tangled in cables, a bassist asleep on a pile of coats. No readable text or logo.',
      ],
    },
    {
      name: 'Library Sunbeam Quiet Anime',
      domain: 'quiet library light anime',
      tags: ['library', 'sunbeam', 'anime'],
      dna: anime(
        'Library sunbeam anime: hushed frames with shafts of sun, floating dust and quiet readers.',
        'quiet relaxed poses, turning pages, soft lines.',
        'Warm wood, cream and dusty gold.',
        'Shafts of sun through high windows.',
        'Cel with painted light shafts and dust.',
        'Tall frames with shelves and beams.',
        'Quiet, peaceful, studious and warm.',
        'sun shafts; dust motes; quiet readers',
      ),
      avoid: AVOID,
      briefs: [
        'Library sunbeam anime frame of a young scribe reading on a rolling ladder in an ancient library, a shaft of sun falling across her page, dust motes glowing, a small owl dozing on the shelf. No readable text or logo.',
        'Library sunbeam anime frame of a student asleep on an open atlas at a long oak table, a sunbeam slowly crossing her hair, dust drifting, tall shelves fading into warm shadow. No readable text or logo.',
        'Library sunbeam anime frame of a fat orange librarian cat asleep on a tall stack of old books in a pool of sun, a young clerk tiptoeing past with a cart. No readable text or logo.',
      ],
    },
    {
      name: 'Choir Harmony Light Anime',
      domain: 'choir anime',
      tags: ['choir', 'music', 'anime'],
      dna: anime(
        'Choir harmony anime: rows of singers bathed in soft light, open mouths, uplifted faces and warm glow.',
        'uplifted faces, open mouths, rows of figures, soft lines.',
        'Warm cream and gold with soft blue.',
        'Soft glow from above.',
        'Cel with glow.',
        'Rows of singers.',
        'Uplifting, warm, together and moving.',
        'rows; uplifted faces; soft glow',
      ),
      avoid: AVOID,
      briefs: [
        'Choir harmony anime frame of a village choir singing in a stone chapel at midwinter, rows of uplifted faces lit gold by candles and a soft beam from the high window, breath visible, a small child in front holding the highest note. No readable text or logo.',
        'Choir anime frame of a small choir singing on a grassy hilltop at sunset, robes and hair lifting in the wind, open mouths and closed eyes, the valley and a castle glowing below. No readable text or logo.',
        'Choir anime frame of a choir of translucent spirits singing in a moonlit ruined abbey, soft blue glow on their faces, one living girl standing among them singing too. No readable text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
