import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval fantasy drawing media: traditional dry and wet drawing materials used for dark
// fantasy subjects. Five originals get card briefs; fifteen new studies add three-chalk drawing,
// carved gesso line, goldpoint, lampblack brush, vine charcoal, white heightening on blue paper,
// burnished graphite, oil-stick gesture, bistre wash, carbon pencil blacks, India-ink drybrush,
// crowquill line, mixed chalk on grey paper, pencil with tea-stain wash and fine ballpoint.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'drawing-media', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'digital smoothness', 'readable text', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original characters';

const spec: Spec = {
  pack: 'pack_17',
  category: '8. Medieval Fantasy Drawing Media',
  updates: {
    'SP17-079': { briefs: [
      'Accumulated in delicate metallic strokes on a rose-toned ground, a sleeping unicorn lies curled among thorns while a hunter\'s hand reaches in from the edge of the page. No readable text or logo.',
      'Traced in fine grey metallic line, a court wizard tries to sit still for his portrait while his beard keeps creeping toward the candle. No readable text or logo.',
      'Drawn in faint grey strokes on toned paper, a portrait of a queen is finished except for one eye, which is looking elsewhere. No readable text or logo.',
    ] },
    'SP17-080': { briefs: [
      'Glowing through pale wax channels in a dark ink wash, a fire salamander coils around a blacksmith\'s anvil as sparks resist the wash like stars. No readable text or logo.',
      'Resisting the ink in bright pale lines, a wax-drawn ghost at a banquet keeps showing through every course the servants try to cover it with. No readable text or logo.',
      'Left pale where the wax resisted, a single path winds through a forest of dark ink, and the path ends at a pale shape the size of a person. No readable text or logo.',
    ] },
    'SP17-081': { briefs: [
      'Rising in broad pale strokes from a deep black ground, a spectral stag with a crown of candles walks through a winter forest where only its light exists. No readable text or logo.',
      'Drawn in rubbed pale strokes on a dark page, a ghost tries to frighten a sleeping dog that simply rolls over for a belly rub. No readable text or logo.',
      'Emerging in broken pale marks from a black sheet, a staircase climbs into the dark, and the top step has been left completely undrawn. No readable text or logo.',
    ] },
    'SP17-082': { briefs: [
      'Pressed in velvety compressed marks, a stone giant carries a broken bridge on its back through a valley, its rubbed planes shifting between crisp line and soft pigment. No readable text or logo.',
      'Drawn with firm velvety strokes, a very serious dwarf sits for his portrait while holding a cat that refuses to face the artist. No readable text or logo.',
      'In rubbed velvety planes, a hooded figure stands in a field, and the contour line around it stops on one side as if it walked out of the drawing. No readable text or logo.',
    ] },
    'SP17-083': { briefs: [
      'Layered in directional strokes and burnished highlights, a phoenix bursts from the ashes of a ruined chapel with every feather built from broken pigment coverage. No readable text or logo.',
      'Drawn with gritty layered pencil, a goblin tailor measures a troll for a suit and needs a ladder to reach the shoulders. No readable text or logo.',
      'Burnished to a waxy shine in one small spot, a dark forest is drawn in rough strokes, and the only bright point is a lit window with a figure in it. No readable text or logo.',
    ] },
  },
  creates: [
    study('Trois Crayons Drawing', 'black, red and white chalk drawing', 'three-chalk', {
      aesthetic: 'Trois crayons drawing: figure drawings in three chalks, black for shadow, red for flesh and white for highlights, on warm toned paper with lively hatching.',
      subject_treatment: `${keep}; model the subject with black shadows, red warmth and white highlights on toned paper.`,
      color_and_tone: 'Black, sanguine red and white chalk on buff paper.',
      lighting_and_shadow: "Soft modeled light built from three chalks, kept consistent across the whole image.",
      texture_and_material: "Chalk grain, hatching and toned paper tooth, kept consistent across the whole image.",
      camera_and_composition: "Figure study with breathing space, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with intimate old-master grace.',
      rendering_and_quality: "Refined lively chalk drawing, kept consistent across the whole image.",
      key_features: 'three chalks; toned paper; hatching; figure study',
    }, [], [
      'Modeled in black, red and white chalk, a sleeping elf queen rests her cheek on the flank of an enormous wolf, both drawn with warm lively hatching on buff paper. No readable text or logo.',
      'Drawn in three chalks, a court jester practices a very dignified bow that ends with him tipping over sideways. No readable text or logo.',
      'On warm toned paper, a portrait of a young page is modeled in three chalks, and only the eyes have been left in plain black. No readable text or logo.',
    ]),
    study('Carved Gesso Line Drawing', 'drawing incised in gesso', 'gesso-line', {
      aesthetic: 'Carved gesso line drawing: drawings incised into smooth white gesso with a stylus, crisp grooves filled with dark wash and soft raised edges catching the light.',
      subject_treatment: `${keep}; incise the subject as crisp grooves in smooth white gesso.`,
      color_and_tone: 'Chalky white gesso with dark umber line fill.',
      lighting_and_shadow: "Raking light across carved grooves, kept consistent across the whole image.",
      texture_and_material: "Incised lines, smooth gesso and small chips, kept consistent across the whole image.",
      camera_and_composition: "Flat panel viewed with slight raking light, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with quiet carved permanence.',
      rendering_and_quality: "Crisp controlled incision, kept consistent across the whole image.",
      key_features: 'incised grooves; white gesso; dark fill; raking light',
    }, [], [
      'Cut into a smooth white panel, a sea serpent winds around a lighthouse in crisp dark grooves that catch the raking light like wet ink. No readable text or logo.',
      'Incised into chalky white, a knight\'s portrait has one groove carved too deep, giving him a very surprised eyebrow. No readable text or logo.',
      "Framed by clean incised grooves in a white panel, a doorway has a small chip in the surface right where its handle should be. No readable text or logo.",
    ]),
    study('Goldpoint Stylus Drawing', 'drawing with a gold stylus', 'goldpoint', {
      aesthetic: 'Goldpoint stylus drawing: extremely fine warm golden-grey lines drawn with a gold stylus on prepared ground, delicate, precious and faintly shimmering.',
      subject_treatment: `${keep}; draw the subject in extremely fine shimmering golden-grey line.`,
      color_and_tone: "Faint warm gold-grey lines on ivory ground, kept consistent across the whole image.",
      lighting_and_shadow: "Delicate hatching with a soft shimmer, kept consistent across the whole image.",
      texture_and_material: "Prepared ground, hairline strokes and metallic sheen, kept consistent across the whole image.",
      camera_and_composition: "Small precious drawing with generous space, kept consistent across the whole image.",
      atmosphere_and_mood: "Keep the requested mood with hushed reverence, kept consistent across the whole image.",
      rendering_and_quality: "Hairline precision, no heavy darks, kept consistent across the whole image.",
      key_features: 'gold stylus line; hairline strokes; shimmer; ivory ground',
    }, [], [
      'Drawn in hairline strokes that shimmer faintly, a sleeping dragon curls around a single egg, the whole creature so delicate it seems woven of light. No readable text or logo.',
      'In faint shimmering line, a tiny mouse wearing a crown sits for a portrait with great solemnity on a velvet cushion. No readable text or logo.',
      'Traced in delicate warm line, an empty chair sits by a window, and faint marks on the seat suggest someone has just stood up. No readable text or logo.',
    ]),
    study('Lampblack Brush Study', 'soot ink brush drawing', 'lampblack', {
      aesthetic: 'Lampblack brush study: rich soot-black brush drawing with velvety deep blacks, dry-brush edges and grey water washes, bold and quick.',
      subject_treatment: `${keep}; brush the subject with bold velvety black strokes and grey washes.`,
      color_and_tone: 'Deep velvety black and water greys on white.',
      lighting_and_shadow: "Strong black masses and white paper light, kept consistent across the whole image.",
      texture_and_material: "Dry-brush edges, soot pigment and paper texture, kept consistent across the whole image.",
      camera_and_composition: "Bold central subject with open space, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with stark decisive power.',
      rendering_and_quality: "Confident quick brushwork, kept consistent across the whole image.",
      key_features: 'velvety black; dry-brush edges; grey washes; quick strokes',
    }, [], [
      'Brushed in velvety soot black, a raven king spreads his wings over a snowbound fortress, each feather a single confident stroke. No readable text or logo.',
      'In quick black strokes, a cat has knocked over the ink pot and walked across the drawing, leaving perfect paw prints through the hero. No readable text or logo.',
      'In a few strokes of deep black, a tall hooded figure stands at the edge of a lake of pale grey wash. No readable text or logo.',
    ]),
    study('Vine Charcoal Fantasy Sketch', 'soft vine charcoal drawing', 'vine-charcoal', {
      aesthetic: 'Vine charcoal fantasy sketch: soft grey vine-charcoal drawing with light searching lines, smudged tones and easy erasure, airy and atmospheric.',
      subject_treatment: `${keep}; sketch the subject lightly with searching charcoal lines and smudged tone.`,
      color_and_tone: "Soft greys on white paper, kept consistent across the whole image.",
      lighting_and_shadow: "Smudged tonal shading and erased lights, kept consistent across the whole image.",
      texture_and_material: "Powdery charcoal, finger smudges and eraser marks, kept consistent across the whole image.",
      camera_and_composition: "Loose sketch with visible construction lines, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with airy exploratory calm.',
      rendering_and_quality: "Light searching sketch, not heavy, kept consistent across the whole image.",
      key_features: 'vine charcoal; searching lines; smudges; erased lights',
    }, [], [
      'Sketched in soft smudged grey, a giant knight of mist wades through a lake while the faint first lines of a castle appear behind him. No readable text or logo.',
      'In light searching lines, an artist has drawn a griffin three times, and each version looks more annoyed at being redrawn. No readable text or logo.',
      'In soft charcoal, a woman stands at a window, and an erased figure beside her is still faintly visible. No readable text or logo.',
    ]),
    study('Blue-Paper White Heightening', 'white highlights on blue paper', 'blue-paper', {
      aesthetic: 'Blue-paper white heightening: drawings on blue paper using dark ink or chalk for shadows and opaque white for highlights, the paper serving as the midtone.',
      subject_treatment: `${keep}; model the subject with dark shadows and white highlights on blue paper.`,
      color_and_tone: 'Blue paper midtone, dark ink shadows and white highlights.',
      lighting_and_shadow: "Crisp white highlights with blue midtones, kept consistent across the whole image.",
      texture_and_material: "Blue laid paper, white gouache and ink, kept consistent across the whole image.",
      camera_and_composition: "Study sheet with a central figure, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with cool moonlit elegance.',
      rendering_and_quality: "Clear three-value drawing, kept consistent across the whole image.",
      key_features: 'blue paper; white highlights; dark shadows; midtone paper',
    }, [], [
      'Heightened in white on blue paper, a ghost ship glides through a night sea while moonlight catches its torn sails and the crest of each wave. No readable text or logo.',
      "Shining so brightly in white highlights that a sparrow uses it as a mirror, a stern knight's helmet is drawn with dark ink shadows on a cool midtone sheet. No readable text or logo.",
      'On a sheet of blue paper, a lantern is highlighted in white on a table, and the chair beside it is drawn only in shadow. No readable text or logo.',
    ]),
    study('Burnished Graphite Sheen', 'polished shiny graphite drawing', 'burnished-graphite', {
      aesthetic: 'Burnished graphite sheen: dense graphite drawing polished until the darks shine like metal, with crisp paper-white highlights and silvery reflections.',
      subject_treatment: `${keep}; render the subject in dense burnished graphite that shines like metal.`,
      color_and_tone: "Silvery grey to glossy black on white, kept consistent across the whole image.",
      lighting_and_shadow: "Metallic sheen on dark graphite areas, kept consistent across the whole image.",
      texture_and_material: "Polished graphite, smooth blends and crisp edges, kept consistent across the whole image.",
      camera_and_composition: "Strong central subject with white space, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with cool polished intensity.',
      rendering_and_quality: "Highly finished graphite with sheen, kept consistent across the whole image.",
      key_features: 'burnished graphite; metallic sheen; crisp highlights; dense darks',
    }, [], [
      'Polished until its armor shines like real metal, a graphite paladin kneels beside a fallen horse whose mane is drawn in soft silvery strands. No readable text or logo.',
      "Admiring its own reflection in a stolen spoon, a vain raven gleams in polished dark pencil that shines like metal. No readable text or logo.",
      'Drawn in shining dark graphite, a mirror hangs in an empty hall and reflects a candle that is not in the room. No readable text or logo.',
    ]),
    study('Oil-Stick Gestural Drawing', 'bold oil stick drawing', 'oil-stick', {
      aesthetic: 'Oil-stick gestural drawing: bold greasy oil-stick lines and smears, energetic gestures, thick waxy marks in black and a few colors on raw paper.',
      subject_treatment: `${keep}; draw the subject with bold greasy gestures and thick waxy lines.`,
      color_and_tone: 'Black with rust, ochre and one bright color.',
      lighting_and_shadow: "Implied by stroke weight and smears, kept consistent across the whole image.",
      texture_and_material: "Greasy waxy lines, smears and raw paper, kept consistent across the whole image.",
      camera_and_composition: "Big gestural figure filling the sheet, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with raw primal energy.',
      rendering_and_quality: "Loose powerful gesture, not tidy, kept consistent across the whole image.",
      key_features: 'oil stick; greasy gesture; smears; raw paper',
    }, [], [
      'Scrawled in thick greasy black and rust, a horned beast rears up and fills the whole sheet, its legs one explosive gesture of waxy lines. No readable text or logo.',
      "In bold smeared strokes, a warrior tries to draw his sword dramatically and has gotten it stuck in the scabbard. No readable text or logo.",
      'Smeared in heavy waxy black, a figure stands in a doorway, and a single stroke of red marks where its eyes should be. No readable text or logo.',
    ]),
    study('Bistre Wash and Line', 'brown soot ink pen and wash', 'bistre', {
      aesthetic: 'Bistre wash and line: warm brown soot-ink pen drawing with transparent brown washes, quick landscapes and figures in the manner of old travel sketches.',
      subject_treatment: `${keep}; draw the subject in warm brown pen line with transparent brown washes.`,
      color_and_tone: 'Warm browns from pale to deep on cream paper.',
      lighting_and_shadow: "Transparent wash shadows with paper lights, kept consistent across the whole image.",
      texture_and_material: "Pen line, wash pooling and laid paper, kept consistent across the whole image.",
      camera_and_composition: "Quick landscape or figure sketch, kept consistent across the whole image.",
      atmosphere_and_mood: "Keep the requested mood with wandering observation, kept consistent across the whole image.",
      rendering_and_quality: "Fresh quick sketch with confident wash, kept consistent across the whole image.",
      key_features: 'brown ink; transparent wash; pen line; travel sketch',
    }, [], [
      'Sketched in warm brown line and wash, a giant\'s ruined castle crowns a hill while a tiny traveler sits sketching it from the road below. No readable text or logo.',
      'In quick brown pen and wash, a traveler sketches a bridge while a troll under it poses as helpfully as it can. No readable text or logo.',
      'In pale brown wash, a road leads to a village, and one house has been left completely unpainted. No readable text or logo.',
    ]),
    study('Carbon Pencil Velvet Blacks', 'rich carbon pencil drawing', 'carbon-pencil', {
      aesthetic: 'Carbon pencil velvet blacks: matte carbon pencil drawing with velvety deep blacks, fine controlled hatching and no graphite shine.',
      subject_treatment: `${keep}; render the subject with matte velvety blacks and fine hatching.`,
      color_and_tone: "Matte black to soft grey on white, kept consistent across the whole image.",
      lighting_and_shadow: "Deep matte shadows with controlled gradations, kept consistent across the whole image.",
      texture_and_material: 'Carbon pencil grain, fine hatching and paper tooth.',
      camera_and_composition: "Dramatic close subject, kept consistent across the whole image.",
      atmosphere_and_mood: "Keep the requested mood with grave intensity, kept consistent across the whole image.",
      rendering_and_quality: "Precise velvety finish with no shine, kept consistent across the whole image.",
      key_features: 'matte carbon blacks; fine hatching; no shine; velvety',
    }, [], [
      'Rising out of velvety matte black, a hooded executioner-priest holds up a lantern whose light reveals only his gloved hands and the edge of a bell. No readable text or logo.',
      "Trying to fix his hair in a mirror that stubbornly shows nothing, a vampire is drawn in fine matte hatching with velvety deep shadows. No readable text or logo.",
      'In deep matte blacks, a well is drawn from above, and something pale is visible at the very bottom. No readable text or logo.',
    ]),
    study('India Ink Drybrush Fantasy', 'dry brush black ink illustration', 'india-drybrush', {
      aesthetic: 'India ink drybrush fantasy: black ink dragged with a nearly dry brush to create rough broken textures on fur, stone and smoke, bold and gritty.',
      subject_treatment: `${keep}; render the subject with rough broken drybrush textures in black ink.`,
      color_and_tone: "Black ink on white paper, kept consistent across the whole image.",
      lighting_and_shadow: "Broken texture and solid black shadows, kept consistent across the whole image.",
      texture_and_material: "Dragged dry brush, split bristles and grit, kept consistent across the whole image.",
      camera_and_composition: "Bold figure with textured surroundings, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with gritty savage energy.',
      rendering_and_quality: "Crisp black with rough texture, kept consistent across the whole image.",
      key_features: 'dry brush; broken texture; black ink; gritty',
    }, [], [
      'Dragged in rough broken black, a wolf-headed warrior stalks through a smoky ruin, his fur and the rising smoke made of the same split-bristle strokes. No readable text or logo.',
      'In gritty drybrush, a barbarian tries to look fierce while a tiny bird sits on his head grooming itself. No readable text or logo.',
      'In rough broken black strokes, a stone wall has a doorway where the brush texture simply stops. No readable text or logo.',
    ]),
    study('Crowquill Fine Line Fantasy', 'very fine nib pen drawing', 'crowquill', {
      aesthetic: 'Crowquill fine line fantasy: extremely fine flexible-nib pen drawing with delicate swelling lines and intricate hatching, detailed and elegant.',
      subject_treatment: `${keep}; draw the subject with intricate delicate lines from a very fine flexible nib.`,
      color_and_tone: "Black ink on bright white paper, kept consistent across the whole image.",
      lighting_and_shadow: "Fine hatching and cross-hatching, kept consistent across the whole image.",
      texture_and_material: "Hairline nib strokes and swelling lines, kept consistent across the whole image.",
      camera_and_composition: "Detailed centered subject with ornament, kept consistent across the whole image.",
      atmosphere_and_mood: "Keep the requested mood with meticulous wonder, kept consistent across the whole image.",
      rendering_and_quality: "Intricate precise linework, kept consistent across the whole image.",
      key_features: 'fine nib; swelling lines; intricate hatching; elegant detail',
    }, [], [
      'Drawn in swelling hairline strokes, a moth queen spreads wings patterned with a hundred tiny eyes over a sleeping city of spires. No readable text or logo.',
      'In delicate nib lines, a fussy gnome has drawn a perfect border around his garden and is very upset about a single weed. No readable text or logo.',
      'In fine intricate lines, a staircase spirals into the page, and each step is drawn in more detail than the last. No readable text or logo.',
    ]),
    study('Mixed Chalk on Grey Paper', 'colored chalks on mid-grey paper', 'grey-chalk', {
      aesthetic: 'Mixed chalk on grey paper: colored chalks and pastels on mid-grey paper, warm and cool accents, white highlights and dark contours over the neutral ground.',
      subject_treatment: `${keep}; render the subject in colored chalks with warm and cool accents on grey paper.`,
      color_and_tone: 'Grey paper with warm ochres, cool blues and white.',
      lighting_and_shadow: "Soft chalk modeling with bright highlights, kept consistent across the whole image.",
      texture_and_material: "Chalk grain, smudges and grey paper tooth, kept consistent across the whole image.",
      camera_and_composition: "Figure or head study on grey, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with muted painterly warmth.',
      rendering_and_quality: "Soft confident chalk study, kept consistent across the whole image.",
      key_features: 'grey paper; colored chalks; warm and cool; white highlights',
    }, [], [
      'Drawn in warm and cool chalks on grey paper, an elderly sorceress holds a small flame in her palms that lights her wrinkled face in ochre and blue. No readable text or logo.',
      'On grey paper, a knight\'s horse has been drawn with far more care and color than the knight, who is only a rough grey outline. No readable text or logo.',
      'On mid-grey paper, a head study of a young man is finished in chalk, and faint marks show a second head drawn behind his. No readable text or logo.',
    ]),
    study('Pencil and Tea-Stain Wash', 'graphite with tea-stained washes', 'tea-stain', {
      aesthetic: 'Pencil and tea-stain wash: graphite drawings washed with brewed tea for warm uneven stains, rings and blooms that age the page.',
      subject_treatment: `${keep}; draw the subject in pencil with warm uneven tea-stain washes.`,
      color_and_tone: "Graphite greys with warm amber tea stains, kept consistent across the whole image.",
      lighting_and_shadow: "Pencil shading with stained tone, kept consistent across the whole image.",
      texture_and_material: "Tea rings, blooms, buckled paper and pencil, kept consistent across the whole image.",
      camera_and_composition: "Sketchbook page with stains around the subject, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with aged cozy mystery.',
      rendering_and_quality: "Delicate pencil with organic stains, kept consistent across the whole image.",
      key_features: 'tea stains; pencil; blooms and rings; aged page',
    }, [], [
      'Drawn in soft pencil and washed with amber tea, a map-making owl sits in a tower among scrolls, a tea ring framing the full moon in the window. No readable text or logo.',
      "Pretending the spill was always part of the picture, a wizard's familiar sits beside the overturned teacup that has stained half of the sketch. No readable text or logo.",
      'On a tea-stained page, a pencil drawing of a door has a dark ring right on the handle, as if something wet was pressed there. No readable text or logo.',
    ]),
    study('Fine Ballpoint Crosshatch Study', 'precise ballpoint pen drawing', 'ballpoint-study', {
      aesthetic: 'Fine ballpoint crosshatch study: careful blue or black ballpoint drawing built from patient crosshatching, subtle pressure and soft tonal buildup.',
      subject_treatment: `${keep}; build the subject in patient ballpoint crosshatching with soft tonal buildup.`,
      color_and_tone: "Blue or black ballpoint on white paper, kept consistent across the whole image.",
      lighting_and_shadow: "Layered hatching creating smooth tones, kept consistent across the whole image.",
      texture_and_material: 'Ballpoint strokes, ink blobs and slight paper indent.',
      camera_and_composition: "Detailed study in a sketchbook, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with patient obsessive calm.',
      rendering_and_quality: "Precise controlled ballpoint rendering, kept consistent across the whole image.",
      key_features: 'ballpoint crosshatch; tonal buildup; ink blobs; sketchbook',
    }, [], [
      'Built from thousands of patient blue ballpoint hatches, a skeletal horse and its armored rider stand in a snowstorm drawn entirely by pressure and restraint. No readable text or logo.',
      'In careful ballpoint, a heroic portrait of a goblin is so detailed that every one of his nose hairs is visible, much to his pride. No readable text or logo.',
      'In patient blue hatching, a window at night is drawn from inside, and the hatching outside the glass forms a face. No readable text or logo.',
    ]),
  ],
};

export default spec;
