import type { Create, Dna, Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Weathering is a surface treatment with an explicit intensity. The target keeps its structure;
// collapse, ruins or abandonment scenes are not added unless the prompt asks for them.
const AVOID = [...MATERIAL_AVOID, 'structural collapse', 'unrequested ruins or abandonment scene'];
const w = (a: string, b: string, c: string, l: string, t: string, m: string, k: string): Dna =>
  material(
    a,
    `${b} Default intensity is moderate; follow the prompt if it asks for light or heavy wear.`,
    c,
    l,
    t,
    m,
    `${k}; surface-level damage; structure intact`,
    'surfaces of the target named in the prompt',
  );

const spec: Spec = {
  pack: 'pack_09',
  category: '3. Weathering And Decay',
  updates: {
    'SP09-018': {
      dna: w(
        'Rusty iron: iron or steel surfaces oxidized into orange-brown rust with flaking scale and streaks.',
        'rust blooms from edges, bolts and seams, with flaking scale and run-off streaks.',
        'Orange, umber and dark brown rust over grey steel.',
        'Low warm light that shows flaking relief.',
        'Oxide scale, pitting, flakes and streaks.',
        'Neglected, industrial, harsh and timeworn.',
        'orange rust blooms; flaking scale; run-off streaks; pitting',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's full armor rusted orange-brown with flaking scale and streaks, still standing proud on a stand. No text or logo.",
        'Photograph of a rusted iron dragon sculpture in a field of poppies. No text or logo.',
        'Photograph of a rusty iron birdcage with a live canary. No text or logo.',
      ],
    },
    'SP09-025': {
      dna: w(
        'Cracked porcelain: glazed ceramic surfaces crazed with hairline cracks and a few chips.',
        'fine crazing across the glaze with a few deeper cracks and chipped edges, the object still whole.',
        'Glazed white, celadon or blue-and-white with dark crack lines.',
        'Soft light with glaze highlights.',
        'Crazed glaze network, chips and exposed bisque.',
        'Fragile, precious, aged and delicate.',
        'crazed glaze network; hairline cracks; chipped edges',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a porcelain knight's helmet crazed with hairline cracks on a velvet cushion. No text or logo.",
        'Photograph of a cracked blue-and-white porcelain dragon on a shelf. No text or logo.',
        'Photograph of a crazed celadon porcelain horse. No text or logo.',
      ],
    },
    'SP09-030': {
      dna: w(
        'Burlap decay: coarse sackcloth surfaces frayed, stained and patched.',
        "the target's fabric surfaces fray at seams and edges, with stains and rough patches.",
        'Sack brown with darker stains and pale frayed threads.',
        'Dim natural light.',
        'Coarse weave, loose threads, stains and patches.',
        'Poor, worn, rustic and humble.',
        'frayed burlap; stains; patched weave',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a scarecrow knight whose burlap tabard is frayed and stained in a windy field. No text or logo.',
        'Photograph of a frayed burlap throne cover in a stone hall. No text or logo.',
        'Photograph of a frayed burlap doll on a windowsill. No text or logo.',
      ],
    },
    'SP09-033': {
      dna: w(
        'Peeling paint: layered paint coats curling, cracking and flaking off to reveal older colors beneath.',
        'paint layers curl and flake from the target, revealing older coats and bare material.',
        'Layered pastel and faded colors over bare wood or metal.',
        'Soft raking light on curling flakes.',
        'Curling paint flakes, cracked layers and exposed substrate.',
        'Nostalgic, faded, neglected and layered.',
        'curling paint flakes; layered old colors; exposed substrate',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a carousel horse with peeling layered paint revealing older colors beneath. No text or logo.',
        'Photograph of a knight statue with peeling blue paint over bronze. No text or logo.',
        'Photograph of a rowboat with peeling paint on a beach. No text or logo.',
      ],
    },
    'SP09-034': {
      dna: w(
        'Mold and mildew: fuzzy spotted mold colonies spreading over damp surfaces.',
        "patchy mold colonies and mildew spots spread over the target's damp surfaces.",
        'Black, grey-green and white mold spots.',
        'Dim damp light.',
        'Fuzzy mold colonies, spots and damp stains.',
        'Unsettling, damp, neglected and organic.',
        'fuzzy mold colonies; mildew spots; damp stains',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a velvet throne spotted with grey-green mold in a damp crypt. No text or logo.',
        'Photograph of a mildewed wedding portrait frame. No text or logo.',
        'Photograph of a moldy loaf-shaped crown. No text or logo.',
      ],
    },
    'SP09-035': {
      dna: w(
        'Charred wood (shou sugi ban): wood surfaces deliberately charred into black alligator-skin char.',
        'the wooden surfaces are charred into black crackled alligator texture, brushed to reveal grain on edges.',
        'Deep charcoal black with silvery sheen and brown grain.',
        'Low side light on the crackled char.',
        'Crackled char, silvery sheen and exposed grain.',
        'Dark, elegant, protective and primal.',
        'alligator char crackle; silvery sheen; brushed grain',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a horse sculpture made of charred shou-sugi-ban wood in snow. No text or logo.',
        'Photograph of a charred-wood knight statue. No text or logo.',
        'Photograph of a charred wooden throne in a white room. No text or logo.',
      ],
    },
    'SP09-036': {
      dna: w(
        'Water damage: tide lines, swelling, staining and bloom where water soaked the target.',
        'tide-line stains, swelling, warping and mineral bloom where water soaked the surfaces.',
        'Brown tide lines, grey bloom and darkened wet zones.',
        'Soft window light.',
        'Warped swollen surfaces, tide lines and bloom.',
        'Melancholic, neglected, damp and quiet.',
        'tide-line stains; swelling; mineral bloom',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a grand piano with tide-line stains and swelling after a flood, in an otherwise tidy room. No text or logo.',
        'Photograph of a water-damaged painted icon. No text or logo.',
        'Photograph of a water-stained wooden rocking horse. No text or logo.',
      ],
    },
    'SP09-037': {
      dna: w(
        'Scratched metal: bright scratches and scuffs cutting through a metal finish.',
        'bright scratches, scuffs and nicks cut through the metal surface along worn areas.',
        'Metal grey with bright silver scratch lines.',
        'Hard light catching scratch lines.',
        'Scratches, scuffs, nicks and dulled patches.',
        'Used, battle-worn, tough and honest.',
        'bright scratch lines; scuffs and nicks; dulled wear',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's helmet with bright battle scratches under hard light. No text or logo.",
        'Photograph of a scratched metal violin. No text or logo.',
        'Photograph of a scratched steel horse sculpture. No text or logo.',
      ],
    },
    'SP09-038': {
      dna: w(
        'Dusty surface: a soft layer of settled dust dulling the target, thicker on top surfaces.',
        'a fine layer of settled dust dulls the target, thicker on upward faces, with finger swipes.',
        'Grey-beige dust over the object color.',
        'Shafts of light revealing floating motes.',
        'Fine dust layer, finger swipes and motes.',
        'Forgotten, quiet, still and timeless.',
        'settled dust layer; thicker on top faces; finger swipes',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a crown on a cushion under a fine layer of settled dust with a finger swipe. No text or logo.',
        'Photograph of a dusty harp in a shaft of light. No text or logo.',
        'Photograph of a dusty suit of armor. No text or logo.',
      ],
    },
    'SP09-040': {
      dna: w(
        'Oil stains: dark glossy oil and grease stains soaking into the target.',
        'dark glossy oil and grease stains soak into the surfaces with iridescent edges.',
        'Black-brown stains with iridescent sheen.',
        'Hard light for glossy spots.',
        'Oil stains, grease smears and iridescent film.',
        'Mechanical, gritty, working and dirty.',
        'oil stains; grease smears; iridescent film',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a white wedding dress stained with dark oil splotches on a mannequin. No text or logo.',
        "Photograph of an oil-stained knight's tabard. No text or logo.",
        'Photograph of an oil-stained marble statue. No text or logo.',
      ],
    },
    'SP09-041': {
      dna: w(
        'Sandpaper abrasion: surfaces covered in grit or scuffed by sanding into a matte scratched finish.',
        'the surface is gritty or sanded matte with swirl marks and exposed layers.',
        'Muted, dusty tones with pale sanding marks.',
        'Soft light showing matte grit.',
        'Abrasive grit, sanding swirls and dust.',
        'Rough, workshop-worn and matte.',
        'abrasive grit; sanding swirls; matte scuffed finish',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a sanded wooden knight statue with swirl marks and dust. No text or logo.',
        'Photograph of a grit-covered dragon egg. No text or logo.',
        'Photograph of a sanded guitar body. No text or logo.',
      ],
    },
    'SP09-064': {
      dna: w(
        'Cracked mud: dried mud coating the target and splitting into polygon cracks.',
        'dried mud coats the target and splits into polygon cracks, curling at edges.',
        'Clay brown and ochre with dark crack lines.',
        'Harsh sun with crisp shadows in cracks.',
        'Dried mud plates, polygon cracks and curls.',
        'Parched, rough, earthy and harsh.',
        'dried mud polygon cracks; curled edges; parched clay',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a knight coated in dried cracked mud standing on a battlefield. No text or logo.',
        'Photograph of a mud-caked horse statue. No text or logo.',
        'Photograph of a mud-cracked throne. No text or logo.',
      ],
    },
    'SP09-065': {
      dna: w(
        'Tar coating: thick black tar coating the target, glossy, dripping and sticky.',
        'thick black tar coats the target with glossy drips and stringy strands.',
        'Glossy black with brown translucency at thin edges.',
        'Hard light for glossy highlights.',
        'Viscous tar, drips, strands and bubbles.',
        'Heavy, sticky, ominous and industrial.',
        'glossy black tar; drips and strands; viscous coating',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a swan statue dripping with black tar on a white plinth. No text or logo.',
        'Photograph of a tar-coated knight. No text or logo.',
        'Photograph of a tar-dipped crown. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Salt Crust',
      domain: 'salt crust efflorescence',
      tags: ['salt', 'crust', 'weathering'],
      dna: w(
        'Salt crust: white crystalline salt deposits crusting over the target, as if dried by sea spray.',
        'white salt crystals crust on edges and recesses with efflorescence blooms.',
        'White salt over darker base colors.',
        'Bright coastal light sparkling on crystals.',
        'Crystalline salt crust, blooms and granules.',
        'Coastal, dry, bleached and ancient.',
        'white salt crystal crust; efflorescence blooms',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an anchor-bearing sea knight statue crusted with white salt crystals on a shore. No text or logo.',
        'Photograph of a salt-crusted violin. No text or logo.',
        'Photograph of a salt-crusted rowboat on a dry lake. No text or logo.',
      ],
    },
    {
      name: 'Sun-Bleached Fade',
      domain: 'sun-bleached fading',
      tags: ['sun-bleached', 'fade', 'weathering'],
      dna: w(
        'Sun-bleached fade: colors washed out by years of sun, pale on exposed faces and richer in shadowed folds.',
        'exposed faces fade to pale washed tones while protected folds keep deeper color.',
        'Pastel-faded versions of the original colors.',
        'Harsh overhead sun.',
        'Chalky faded pigment and dried surfaces.',
        'Nostalgic, dry, quiet and timeworn.',
        'sun-faded exposed faces; deeper colors in folds; chalky pigment',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a sun-bleached carousel horse with pastel-faded paint in a desert. No text or logo.',
        'Photograph of a sun-faded red velvet throne on a beach. No text or logo.',
        "Photograph of a sun-bleached knight's tabard on armor. No text or logo.",
      ],
    },
    {
      name: 'Soot Staining',
      domain: 'soot and smoke staining',
      tags: ['soot', 'smoke-stain', 'weathering'],
      dna: w(
        'Soot staining: black smoke deposits blackening the target from below, as after a fire, without burning it away.',
        'black soot stains rise from lower edges and gather in crevices, surfaces intact.',
        'Black soot gradients over original colors.',
        'Dim light with smoky warmth.',
        'Soft soot deposits, smudges and fingerprints.',
        'Ominous, grim, aftermath and heavy.',
        'soot gradients from below; smudges; intact surfaces',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a white marble angel blackened with soot from below in a chapel. No text or logo.',
        'Photograph of a soot-stained wedding cake. No text or logo.',
        "Photograph of a soot-stained knight's helmet. No text or logo.",
      ],
    },
    {
      name: 'Woodworm Rot',
      domain: 'woodworm and dry rot',
      tags: ['woodworm', 'rot', 'weathering'],
      dna: w(
        'Woodworm rot: wood riddled with tiny boreholes and soft dry-rot cracking.',
        'the wooden target is riddled with small boreholes and cubic dry-rot cracks.',
        'Grey-brown wood with dark holes and pale dust.',
        'Soft side light showing holes.',
        'Boreholes, frass dust and cubic rot cracks.',
        'Decrepit, old, fragile and eerie.',
        'woodworm boreholes; cubic dry rot; frass dust',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a carved wooden saint riddled with woodworm holes in a chapel. No text or logo.',
        'Photograph of a woodworm-eaten chess set. No text or logo.',
        'Photograph of a woodworm-riddled rocking chair. No text or logo.',
      ],
    },
    {
      name: 'Acid Etching',
      domain: 'acid-etched surfaces',
      tags: ['acid', 'etching', 'weathering'],
      dna: w(
        'Acid etching: surfaces eaten by acid into pitted, frosted and bubbled zones with bright residue edges.',
        'acid pits, frosted zones and bubbled corrosion eat into the surfaces in splash patterns.',
        'Frosted pale zones and yellow-green residue.',
        'Cold light on pitted surfaces.',
        'Pitted, frosted and bubbled corrosion.',
        'Toxic, alarming, chemical and harsh.',
        'acid pits; frosted zones; splash patterns; residue edges',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a silver knight's shield eaten by acid in splash-shaped pitted zones. No text or logo.",
        'Photograph of an acid-etched glass crown. No text or logo.',
        'Photograph of an acid-etched bronze horse. No text or logo.',
      ],
    },
    {
      name: 'Lichen Crust',
      domain: 'lichen crust growth',
      tags: ['lichen', 'crust', 'weathering'],
      dna: w(
        'Lichen crust: flat crusty lichen rosettes in orange, yellow and grey growing over the target.',
        'flat lichen rosettes and crusts spread over exposed surfaces in circular patches.',
        'Orange, chartreuse and grey-green lichen.',
        'Soft overcast light.',
        'Crusty lichen rosettes and powdery patches.',
        'Ancient, slow, quiet and alive.',
        'lichen rosettes; circular crust patches; orange and chartreuse',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a stone knight effigy dotted with orange and chartreuse lichen rosettes. No text or logo.',
        'Photograph of a lichen-crusted telephone. No text or logo.',
        'Photograph of a lichen-covered bell. No text or logo.',
      ],
    },
    {
      name: 'Ash Fall Coating',
      domain: 'volcanic ash coating',
      tags: ['ash', 'coating', 'weathering'],
      dna: w(
        'Ash fall coating: fine grey volcanic ash settled over the target, softening edges.',
        'fine grey ash settles on every upward face, softening edges and filling crevices.',
        'Monochrome grey ash over faint original colors.',
        'Diffuse hazy light.',
        'Fine powdery ash drifts and settled layers.',
        'Silent, eerie, suspended and bleak.',
        'grey ash drifts; softened edges; monochrome',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a banquet table fully set, everything coated in fine grey volcanic ash. No text or logo.',
        'Photograph of an ash-coated knight on horseback. No text or logo.',
        'Photograph of an ash-covered harp. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
