import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Horror cinema of the 1970s: each preset names its film and director and rebuilds that film's
// production look (stock, lighting, lensing, effects). Cards stage original horror moments.
const T = ['horror-70s', 'horror-cinema'];
const film70 =
  'Seventies 35mm film grain, soft halation, slight gate weave and warm faded print color.';

const spec: Spec = {
  pack: 'pack_27',
  category: '1. Horror Cinema 70s',
  newCategory: { id: 'horror-cinema-70s' },
  updates: {},
  creates: [
    cr(
      'Suspiria 1977 - Technicolor Stained-Glass Terror',
      'seventies horror cinema',
      [...T, 'suspiria'],
      {
        look: 'Dario Argento Suspiria (1977) look: dye-transfer Technicolor saturation, rooms flooded with pure red, blue and green gel light, art nouveau stained glass and operatic baroque terror.',
        subject:
          'stage the subject as a figure lost in rooms flooded with saturated primary gel light and ornate art nouveau patterns.',
        color: 'Pure saturated red, cobalt blue and emerald green gel light with deep black.',
        light: 'Hard colored gel lighting that paints whole rooms a single primary color.',
        texture: 'Dye-transfer Technicolor print richness, fine grain and glossy blacks.',
        camera: 'Symmetrical baroque interiors, stained glass and slow gliding dolly moves.',
        mood: 'operatic nightmarish terror',
        render: 'Hyper-saturated seventies Italian horror film frame.',
        key: 'Argento Technicolor; red and blue gels; art nouveau glass; baroque terror',
        avoid: ['a ballet academy logo', 'existing film characters'],
        briefs: [
          'Flooded with pure red gel light, a night-shift piano tuner walks down an art nouveau corridor of stained-glass peacocks while every window turns cobalt blue one by one behind her. No readable text or logo.',
          'In a baroque dance hall painted entirely emerald green by the lights, an elderly caretaker waltzes alone with a mop while the shadows on the wall dance a different step. No readable text or logo.',
          'A single stained-glass door glows red and blue at the end of a black hallway while a razor-thin line of green light slips underneath it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Texas Chain Saw Massacre 1974 - Sunbaked 16mm Dread',
      'seventies horror cinema',
      [...T, 'chainsaw'],
      {
        look: 'Tobe Hooper The Texas Chain Saw Massacre (1974) look: grainy blown-up 16mm, harsh Texas sun, sweaty documentary camerawork, bone-filled farmhouse clutter and sweltering rural dread.',
        subject:
          'stage the subject in harsh sunlight and sweaty handheld documentary framing amid rural clutter.',
        color: 'Bleached yellow sun, dusty ochre, sickly green and sweat-shine skin.',
        light: 'Merciless midday sun and hot overexposed windows.',
        texture: 'Coarse blown-up 16mm grain, dust and scratches.',
        camera: 'Handheld documentary framing, low angles and sudden close-ups.',
        mood: 'sweltering rural dread',
        render: 'Grainy documentary-style seventies horror frame.',
        key: 'Hooper 16mm grain; harsh sun; rural clutter; documentary dread',
        avoid: ['a masked man with a chainsaw in a leather apron', 'existing film characters'],
        briefs: [
          'Under a merciless noon sun, a traveling encyclopedia salesman knocks on the door of a sagging farmhouse whose porch is decorated with hundreds of dangling chicken bones, grainy 16mm sweat on his collar. No readable text or logo.',
          'Inside a sweltering farmhouse kitchen cluttered with jars of strange things, a family dinner table waits with one extra empty chair facing the door, harsh light blazing through the window. No readable text or logo.',
          'A dusty gas station sign creaks in the hot wind beside a single abandoned sneaker on the road, the heat shimmer warping the empty horizon. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Halloween 1978 - Suburban Steadicam Stalk',
      'seventies horror cinema',
      [...T, 'halloween-78'],
      {
        look: 'John Carpenter Halloween (1978) look: autumn suburban streets, anamorphic widescreen, patient Panavision steadicam point of view, deep blue night and minimal chilling stillness.',
        subject:
          'stage the subject in quiet suburban autumn streets watched from a patient distant point of view.',
        color: 'Deep night blue, pumpkin orange and autumn leaf brown.',
        light: 'Blue moonlit night with warm porch lights.',
        texture: film70,
        camera:
          'Anamorphic widescreen with patient point-of-view tracking and deep foreground shadows.',
        mood: 'patient suburban stalking dread',
        render: 'Minimal widescreen seventies slasher frame.',
        key: 'Carpenter anamorphic; suburban autumn; POV stalk; blue night',
        avoid: ['a pale white mask with a dark boiler suit', 'existing film characters'],
        briefs: [
          'Seen from behind a hedge in anamorphic widescreen, a babysitter in her thirties carries grocery bags up a leaf-covered suburban path while a jack-o’-lantern on the porch grins with its candle suddenly blown out. No readable text or logo.',
          'A laundry line of white sheets flaps in a blue moonlit backyard, and one sheet stays perfectly still in the wind. No readable text or logo.',
          'A child’s tricycle sits alone at the end of a silent suburban street under a single porch light, dead leaves swirling around its wheels. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Exorcist 1973 - Clinical Bedroom Dread',
      'seventies horror cinema',
      [...T, 'exorcist'],
      {
        look: 'William Friedkin The Exorcist (1973) look: cold documentary realism, freezing breath indoors, clinical hospital scenes, Georgetown streetlight fog and a single glowing window.',
        subject:
          'stage the subject with cold documentary realism in freezing rooms and misty streetlights.',
        color: 'Cold blue-grey, clinical white and sodium streetlight amber.',
        light: 'Cold window light, visible breath and one warm streetlamp in fog.',
        texture: film70,
        camera: 'Documentary-style framing and low foggy street views.',
        mood: 'cold clinical dread',
        render: 'Realist seventies supernatural drama frame.',
        key: 'Friedkin realism; freezing breath; streetlight fog; clinical cold',
        avoid: [
          'a priest in a hat under a streetlamp holding a briefcase',
          'existing film characters',
        ],
        briefs: [
          'In a freezing bedroom where everyone’s breath hangs white in the air, a tired pediatric doctor checks a patient’s pulse while the frost on the window slowly spells out a crooked spiral. No readable text or logo.',
          'A plumber in a heavy coat stands at the bottom of a steep foggy stairway at night, a single upstairs window glowing above him. No readable text or logo.',
          'A hospital corridor hums under cold fluorescent light as a gurney slowly rolls by itself toward the elevator doors. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Wicker Man 1973 - Folk Horror Maypole Daylight',
      'seventies folk horror cinema',
      [...T, 'wicker-man'],
      {
        look: 'Robin Hardy The Wicker Man (1973) look: bright pagan daylight on a Scottish island, maypoles, animal masks, flower crowns, folk songs and cheerful sinister community.',
        subject:
          'stage the subject among cheerful villagers in animal masks and flower crowns under bright daylight.',
        color: 'Bright spring green, flower yellow, sea blue and pagan red.',
        light: 'Bright cheerful island daylight with no shadows of menace.',
        texture: film70,
        camera: 'Wide community festival shots and odd smiling close-ups.',
        mood: 'cheerful sinister folk ritual',
        render: 'Bright seventies folk horror film frame.',
        key: 'Wicker Man daylight; animal masks; maypoles; sinister cheer',
        avoid: ['a giant burning wicker figure', 'existing film characters'],
        briefs: [
          'In bright island sunshine, smiling villagers in hare and stag masks dance around a ribboned maypole while a visiting insurance clerk in a grey suit clutches his clipboard and slowly realizes the ribbons are tied to his ankles. No readable text or logo.',
          'An island schoolteacher leads a cheerful harvest procession carrying a giant bread loaf shaped like a sleeping man. No readable text or logo.',
          'A flower crown rests on an empty chair at the head of a long sunlit banquet table set for a guest who has not arrived. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Don’t Look Now 1973 - Venice Red Coat Grief',
      'seventies psychological horror cinema',
      [...T, 'dont-look-now'],
      {
        look: 'Nicolas Roeg Don’t Look Now (1973) look: wintry Venice canals, fragmented editing, grief-laden muted palette with a single recurring red, and eerie glimpses around corners.',
        subject:
          'stage the subject in misty Venetian alleys with a single recurring red accent glimpsed at a distance.',
        color: 'Muted canal grey and ochre with one small saturated red.',
        light: 'Pale wintry mist and dim lamplight on water.',
        texture: film70,
        camera: 'Fragmented glimpses down alleys and across canals.',
        mood: 'grieving uncanny premonition',
        render: 'Muted seventies psychological horror frame.',
        key: 'Roeg Venice; single red; fragmented glimpses; grief',
        avoid: ['a small figure in a red hooded coat', 'existing film characters'],
        briefs: [
          'In a misty winter canal city, a widowed architect restoring a church mosaic glimpses a single red umbrella vanishing around the corner of a narrow alley across the water. No readable text or logo.',
          'Two elderly sisters sit in a canal-side café staring at a tourist as if they know exactly how her evening will end. No readable text or logo.',
          'A red glove floats slowly down a grey canal under a misty stone bridge while church bells ring somewhere unseen. No readable text or logo.',
        ],
      },
    ),
    cr('Carrie 1976 - Split-Diopter Prom Nightmare', 'seventies horror cinema', [...T, 'carrie'], {
      look: 'Brian De Palma Carrie (1976) look: split-diopter shots with two planes in focus, dreamy soft-focus romance turning into red-lit fury, slow motion and seventies high school gloss.',
      subject:
        'stage the subject with a split-diopter frame keeping a near face and a distant event both sharp.',
      color: 'Soft pastel romance turning into saturated red.',
      light: 'Dreamy glowing soft focus then harsh red light.',
      texture: film70,
      camera: 'Split-diopter compositions and slow-motion dread.',
      mood: 'dreamy dread turning to fury',
      render: 'Stylized seventies De Palma horror frame.',
      key: 'De Palma split diopter; soft-focus to red; slow motion',
      avoid: ['a prom queen drenched in blood on stage', 'existing film characters'],
      briefs: [
        'In a split-diopter frame, a shy cafeteria cook’s face stays sharp in the foreground while far behind her, equally sharp, the whole staff party slowly turns to stare as every light in the hall glows red. No readable text or logo.',
        'Soft-focus dancers sway at a retirement party while a bucket balances on a ceiling beam above them. No readable text or logo.',
        'A single glittering crown lies on a stage floor under a harsh red spotlight in slow motion. No readable text or logo.',
      ],
    }),
    cr('Dawn of the Dead 1978 - Mall Zombie Satire', 'seventies zombie cinema', [...T, 'dawn-78'], {
      look: 'George A. Romero Dawn of the Dead (1978) look: bright shopping mall fluorescents, blue-grey zombie makeup, consumer satire, muzak calm and late-seventies color film.',
      subject: 'stage the subject in bright shopping mall satire with blue-grey shambling crowds.',
      color: 'Bright mall fluorescents, consumer primary colors and blue-grey skin.',
      light: 'Flat bright fluorescent mall lighting.',
      texture: film70,
      camera: 'Wide mall concourse shots and satirical tableaux.',
      mood: 'satirical consumer horror',
      render: 'Bright late-seventies zombie satire frame.',
      key: 'Romero mall; blue-grey zombies; consumer satire',
      briefs: [
        'Under cheerful mall fluorescents, a crowd of blue-grey shambling shoppers rides the escalator in slow circles while a security guard eats a hot pretzel on the balcony, trying not to be noticed. No readable text or logo.',
        'Blue-grey figures press their faces against a department store window full of mannequins in wedding dresses. No readable text or logo.',
        'Under humming mall fluorescents, an empty shopping cart rolls slowly across a silent concourse past a fountain full of floating shopping bags and one lost high-heeled shoe. No readable text or logo.',
      ],
    }),
    cr(
      'House 1977 - Obayashi Psychedelic Collage Horror',
      'seventies Japanese horror cinema',
      [...T, 'hausu'],
      {
        look: 'Nobuhiko Obayashi House (Hausu, 1977) look: psychedelic collage effects, painted backdrops, matte composites, candy colors, cartoon inserts and absurd playful horror.',
        subject:
          'stage the subject in absurd playful horror with painted backdrops and collage effects.',
        color: 'Candy pink, sunset orange, lime and painted sky blue.',
        light: 'Artificial painted-set light and glowing composite effects.',
        texture: 'Matte composites, painted backdrops and optical effects.',
        camera: 'Theatrical painted-set compositions with collage inserts.',
        mood: 'absurd candy-colored horror',
        render: 'Psychedelic seventies Japanese horror frame.',
        key: 'Hausu collage; painted backdrops; candy colors; absurd horror',
        briefs: [
          'In a mansion with a painted sunset backdrop, a grand piano starts eating the sheet music while a startled music teacher’s floating head, composited like a cutout, watches from the chandelier in candy-pink light. No readable text or logo.',
          'A white cat sits on a painted staircase as the whole house tilts like a stage set in sunset orange. No readable text or logo.',
          'A single glowing lime watermelon floats over a painted pond at dusk while cutout fireflies blink on and off like cheap stage lights around it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Eraserhead 1977 - Industrial Monochrome Dream',
      'seventies surreal cinema',
      [...T, 'eraserhead'],
      {
        look: 'David Lynch Eraserhead (1977) look: grainy high-contrast black and white, industrial wastelands, hissing radiators, cramped apartments and surreal dream logic.',
        subject: 'stage the subject in cramped industrial black-and-white dream spaces.',
        color: 'High-contrast black and white only.',
        light: 'Harsh pools of light in deep black.',
        texture: 'Grainy black-and-white film and industrial grime.',
        camera: 'Static uneasy compositions in cramped rooms.',
        mood: 'surreal industrial unease',
        render: 'Surreal black-and-white art horror frame.',
        key: 'Lynch monochrome; industrial wasteland; surreal dream',
        avoid: ['a man with towering upright hair holding a swaddled creature'],
        briefs: [
          'In a cramped black-and-white apartment, a nervous clerk sits on his bed staring at a radiator from which a tiny theater stage slowly glows, steam hissing in the dark. No readable text or logo.',
          'A woman in a factory yard carries a potted dead tree through puddles under harsh lamplight. No readable text or logo.',
          'A single pencil sharpener hums on a table in a pool of harsh light surrounded by darkness. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Alien 1979 - Biomechanical Corridor Dread',
      'seventies science fiction horror cinema',
      [...T, 'alien-79'],
      {
        look: 'Ridley Scott Alien (1979) look: used-future industrial spaceship corridors, steam, strobing warning lights, blue haze and slow claustrophobic dread.',
        subject:
          'stage the subject in claustrophobic industrial spaceship corridors full of steam and strobing light.',
        color: 'Cold blue haze, warning amber and industrial grime.',
        light: 'Strobing emergency lights, steam haze and flashlight beams.',
        texture: film70,
        camera: 'Claustrophobic corridor compositions and slow tracking.',
        mood: 'slow claustrophobic dread',
        render: 'Atmospheric seventies sci-fi horror frame.',
        key: 'Alien used future; steam corridors; strobe lights; claustrophobia',
        avoid: ['a black eyeless creature with an elongated skull', 'Giger biomechanical alien'],
        briefs: [
          'Through steam and strobing amber lights, a ship’s cook in a stained jumpsuit crawls along a cramped maintenance duct holding a flashlight while something drips from the ceiling ahead. No readable text or logo.',
          'In a steam-filled storage bay aboard a mining ship, a cat’s eyes glow in the dark as the crew’s flashlight beams sweep past without noticing it. No readable text or logo.',
          'In a silent industrial chamber full of blue haze, a single empty sleep pod glows with its lid open and a thin trail of frost leading toward the door. No readable text or logo.',
        ],
      },
    ),
    cr('The Omen 1976 - Gothic Diplomatic Doom', 'seventies horror cinema', [...T, 'omen'], {
      look: 'Richard Donner The Omen (1976) look: elegant diplomatic wealth, rain-soaked English estates, ominous ravens and rottweilers, gothic churches and slow inevitable doom.',
      subject:
        'stage the subject in elegant wealthy settings shadowed by ominous animals and gothic churches.',
      color: 'Rich dark mahogany, rain grey and church stone.',
      light: 'Grey rainy daylight and candlelit churches.',
      texture: film70,
      camera: 'Elegant compositions with ominous animals watching.',
      mood: 'elegant inevitable doom',
      render: 'Elegant seventies occult thriller frame.',
      key: 'Omen elegance; ravens and hounds; gothic doom',
      avoid: ['a child with 666 birthmark'],
      briefs: [
        'At an elegant embassy garden party in the rain, a diplomat’s wife raises her champagne glass as a row of black ravens lands silently along the hedge behind her, every one facing her. No readable text or logo.',
        'In a rainy English churchyard, a black dog sits perfectly still watching a priest hurry past with his umbrella, its eyes never leaving him. No readable text or logo.',
        'In a cold stone crypt lit by one candle, a single silver dagger rests on a velvet cushion beside an open, very old leather-bound book. No readable text or logo.',
      ],
    }),
    cr(
      'Picnic at Hanging Rock 1975 - Hazy Pastoral Unease',
      'seventies mystery cinema',
      [...T, 'hanging-rock'],
      {
        look: 'Peter Weir Picnic at Hanging Rock (1975) look: dreamy gauzy haze, Edwardian white dresses, sunlit Australian bush, ancient rock formations and uncanny stillness.',
        subject:
          'stage the subject in gauzy sunlit haze near ancient rocks with uncanny stillness.',
        color: 'Hazy gold, white lace and eucalyptus green.',
        light: 'Soft diffused sunlight through gauze.',
        texture: 'Soft gauzy filtration and fine film grain.',
        camera: 'Dreamy still compositions near rock formations.',
        mood: 'dreamy uncanny stillness',
        render: 'Hazy seventies mystery film frame.',
        key: 'Weir gauzy haze; white dresses; ancient rock; stillness',
        briefs: [
          'In gauzy golden haze, a group of women in white Edwardian dresses climbs an ancient rock formation while one pauses to look back as all the pocket watches in the picnic basket stop at noon. No readable text or logo.',
          'A governess naps under a gum tree as a lizard watches her from a warm rock. No readable text or logo.',
          'On a sunlit boulder in hazy golden light, a white lace glove lies beside a cracked pocket watch whose hands have stopped exactly at twelve. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Messiah of Evil 1973 - Pop-Art Coastal Nightmare',
      'seventies cult horror cinema',
      [...T, 'messiah-of-evil'],
      {
        look: 'Messiah of Evil (1973) look: pop-art murals, eerie empty California beach towns, blood moon light, dreamlike stillness and art-house cult horror.',
        subject: 'stage the subject in eerie empty beach towns and pop-art mural rooms.',
        color: 'Pop-art mural colors with blood moon red.',
        light: 'Eerie moonlight and stark gallery light.',
        texture: film70,
        camera: 'Dreamlike still wide compositions.',
        mood: 'dreamlike cult nightmare',
        render: 'Stylish seventies cult horror frame.',
        key: 'Messiah of Evil pop murals; empty beach town; blood moon',
        briefs: [
          'In an empty seaside art gallery covered floor to ceiling in pop-art murals of crowds, a painter notices that the painted people have all turned to look at her under a blood-red moon. No readable text or logo.',
          'A supermarket in a beach town is silent except for townsfolk staring into the meat freezer. No readable text or logo.',
          'In an empty beach-town movie theater glowing blue, the whole audience sits perfectly still facing the blank screen while one seat in the middle slowly creaks. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Lucio Fulci 1979 - Tropical Rot Horror',
      'seventies Italian zombie cinema',
      [...T, 'fulci'],
      {
        look: 'Lucio Fulci Zombi 2 (1979) look: tropical island decay, crumbling conquistador graves, extreme close-ups of eyes, rotting makeup and humid Italian exploitation color.',
        subject: 'stage the subject in humid tropical decay with extreme close-ups of eyes.',
        color: 'Humid green, rot brown and sun-bleached white.',
        light: 'Harsh tropical sun and murky shade.',
        texture: film70,
        camera: 'Extreme eye close-ups and crash zooms.',
        mood: 'humid rotting dread',
        render: 'Humid seventies Italian zombie frame.',
        key: 'Fulci tropical rot; eye close-ups; crash zooms',
        briefs: [
          'On a humid tropical island, a marine biologist lifts her dive mask to find a crumbling conquistador grave has opened in the sand, an extreme close-up catching the terror in her eye. No readable text or logo.',
          'In a humid tropical mission hut, a tired doctor treats a line of feverish patients while the drums in the jungle outside grow louder with every hour. No readable text or logo.',
          'In shallow turquoise water off a crumbling island pier, a rusted diving helmet sits on the sand while curious tropical fish swim in and out of it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Blood on Satan’s Claw 1971 - Rural Folk Occult',
      'seventies folk horror cinema',
      [...T, 'satans-claw'],
      {
        look: 'Piers Haggard The Blood on Satan’s Claw (1971) look: seventeenth-century English countryside, muddy fields, pagan rituals in ruined churches and folk horror naturalism.',
        subject: 'stage the subject in muddy rural fields and ruined churches with folk ritual.',
        color: 'Earthy mud brown, grey sky and pale linen.',
        light: 'Overcast rural daylight and ritual firelight.',
        texture: film70,
        camera: 'Low wide fields and intimate ritual close-ups.',
        mood: 'creeping rural corruption',
        render: 'Earthy seventies folk horror frame.',
        key: 'Folk horror fields; ruined church rituals; earthy palette',
        briefs: [
          'A ploughman turns up a strange carved skull in a muddy furrow under a grey sky while villagers in linen smocks gather at the hedge, whispering. No readable text or logo.',
          'Villagers hold a secret ritual in a ruined church lit by bonfire as a stern judge watches from the woods. No readable text or logo.',
          'On an ancient field boundary stone under a grey sky, a strange patch of dark fur has started to grow, and the grass around it has all turned white. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Salem’s Lot 1979 - TV Vampire Window Scratch',
      'seventies TV horror',
      [...T, 'salems-lot'],
      {
        look: 'Tobe Hooper Salem’s Lot (1979) TV miniseries look: small-town Americana, foggy night windows, floating pale figures and soft television film color.',
        subject:
          'stage the subject in small-town nights with pale figures floating outside foggy windows.',
        color: 'Foggy blue night and warm lamp interiors.',
        light: 'Fog-diffused moonlight and warm bedroom lamps.',
        texture: 'Soft television film color and fog.',
        camera: 'Window framing from inside warm rooms.',
        mood: 'eerie small-town dread',
        render: 'Soft seventies TV horror frame.',
        key: 'Salem’s Lot floating figures; foggy windows; small town',
        avoid: ['a bald blue-skinned vampire with fangs'],
        briefs: [
          'Through a foggy bedroom window in a sleepy small town, a pale smiling neighbor in pajamas floats outside and gently scratches at the glass while the homeowner freezes in his lamplit room. No readable text or logo.',
          'A small-town antique shop glows at night while a crate is delivered by men who never speak. No readable text or logo.',
          'On a foggy small-town porch under a single yellow bulb, an empty rocking chair sways slowly back and forth as if someone has just stood up. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Black Christmas 1974 - Sorority Holiday Dread',
      'seventies horror cinema',
      [...T, 'black-christmas'],
      {
        look: 'Bob Clark Black Christmas (1974) look: cozy snowy holiday house, colored Christmas lights, attic point-of-view shots and unsettling phone calls.',
        subject: 'stage the subject in a cozy snowy holiday house watched from the attic.',
        color: 'Warm Christmas colors, snow white and attic shadow.',
        light: 'Colored Christmas lights and warm lamps.',
        texture: film70,
        camera: 'Attic point-of-view and cozy interior shots.',
        mood: 'cozy holiday dread',
        render: 'Cozy seventies holiday horror frame.',
        key: 'Black Christmas holiday lights; attic POV; snow',
        briefs: [
          'In a cozy snowy boarding house glowing with colored Christmas lights, a group of nurses wrap presents while, seen from the attic hatch above, one ornament on the tree slowly turns to reflect the watcher. No readable text or logo.',
          'On a snowy boarding-house porch, carolers in knitted scarves sing cheerfully while the phone inside the dark hallway rings and rings without anyone answering. No readable text or logo.',
          'A rocking horse sits in a dusty attic lit by a single strand of Christmas lights. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Tourist Trap 1979 - Mannequin Roadside Terror',
      'seventies cult horror cinema',
      [...T, 'tourist-trap'],
      {
        look: 'Tourist Trap (1979) look: dusty roadside wax museum, uncanny mannequins with gaping mouths, telekinetic chaos and sunbleached cult horror.',
        subject: 'stage the subject among uncanny roadside mannequins with gaping mouths.',
        color: 'Sunbleached dust, faded pastel and waxy skin tones.',
        light: 'Dusty daylight shafts and dim museum light.',
        texture: film70,
        camera: 'Uncanny mannequin close-ups and dusty wides.',
        mood: 'uncanny roadside terror',
        render: 'Dusty seventies cult horror frame.',
        key: 'Roadside mannequins; gaping mouths; dusty museum',
        briefs: [
          'In a dusty roadside wax museum, a lost family of tourists stares at a mannequin of a grinning gas station attendant whose mouth slowly falls open while every other figure turns its head. No readable text or logo.',
          'A mannequin sits at a dusty piano in an abandoned diner, fingers poised above the keys. No readable text or logo.',
          'On a sunbleached motel bedspread in a dusty roadside room, a single wax hand lies beside a room key, its fingers slightly curled as if it just let go. No readable text or logo.',
        ],
      },
    ),
    cr('Jaws 1975 - Sunlit Ocean Dread', 'seventies thriller cinema', [...T, 'jaws'], {
      look: 'Steven Spielberg Jaws (1975) look: bright summer beach resort, water-level camera, underwater point of view, sunny panic and unseen menace beneath.',
      subject:
        'stage the subject in bright summer water seen from water level with unseen menace below.',
      color: 'Summer blue sea, sand beige and beach umbrella stripes.',
      light: 'Bright summer sun glittering on water.',
      texture: film70,
      camera: 'Water-level shots and underwater point of view.',
      mood: 'sunny ocean dread',
      render: 'Bright seventies summer thriller frame.',
      key: 'Spielberg water-level; underwater POV; sunny beach dread',
      avoid: ['a great white shark', 'a fishing boat named after a woman'],
      briefs: [
        'From just above the waterline on a crowded summer beach, a lifeguard in her sixties lowers her binoculars as every swimmer suddenly stops splashing at the same moment and the sea goes perfectly calm. No readable text or logo.',
        'Seen from deep underwater, a pair of legs kicks on an inflatable swan in bright sunlight above. No readable text or logo.',
        'At noon on a perfectly calm blue sea, a single yellow barrel bobs near an empty rowboat while seagulls circle in total silence above it. No readable text or logo.',
      ],
    }),
  ],
};

export default spec;
