import type { Spec } from '../tools/apply';
import { au } from './_authors';

// Slice of life and moe, author pass: each preset names its series, studio or mangaka and the
// concrete marks of that look. Existing briefs stay; they are original adult scenes.
const tv =
  'Contemporary digital television cel with clean outlines, soft gradient highlights and detailed painted backgrounds.';
const manga4 =
  'Clean simple four-panel manga line with light screentone and plenty of white space around figures.';

const spec: Spec = {
  pack: 'pack_13',
  category: '4. Slice Of Life & Moe',
  updates: Object.fromEntries([
    au('SP05-202', 'Tamako Market Kyoto Animation - Market-Festival Community Softness', {
      look: 'Kyoto Animation Tamako Market look (2013) by Naoko Yamada with Yukiko Horiguchi designs: soft rounded faces, warm shopping-street community, mochi shops and gentle festival days.',
      subject:
        'draw people with Horiguchi designs, soft round faces, simple bangs, small hands and cozy shopkeeper aprons.',
      color: 'Warm peach, mochi cream, shop-awning red and soft sky blue.',
      light: 'Soft warm afternoon light along a covered shopping street.',
      texture: tv,
      camera: 'Community street compositions and small tender close-ups.',
      mood: 'soft communal warmth',
      render: 'Gentle Kyoto Animation frame with shopping-street coziness.',
      key: 'Tamako Market softness; shopping street; Horiguchi designs; festivals',
    }),
    au('SP05-208', 'Do It Yourself!! EGG FIRM - Beginner-Made DIY Glow', {
      look: 'EGG FIRM Do It Yourself!! look (2022): pastel watercolor textures, handmade DIY projects, gentle club camaraderie and soft glowing afternoons.',
      subject:
        'draw people with soft pastel designs, overalls, tool belts and proud clumsy gestures.',
      color: 'Pastel watercolor mint, lemon, peach and sawdust tan.',
      light: 'Soft glowing afternoon light in a cluttered workshop.',
      texture: 'Soft cel with watercolor-textured backgrounds and visible paper grain.',
      camera: 'Workbench compositions with half-built projects.',
      mood: 'proud handmade joy',
      render: 'Soft pastel watercolor television frame.',
      key: 'DIY pastel watercolor; workshops; handmade projects; camaraderie',
    }),
    au('SP05-086', 'Yuru Camp C-Station - Cold-Warm Restorative Comfort', {
      look: 'C-Station Laid-Back Camp anime look (2018): cold clear winter landscapes around Mount Fuji, warm tents and campfires, cozy blankets and relaxed solo camping.',
      subject:
        'draw people with soft rounded designs, puffy winter jackets, knit hats and relaxed contented faces.',
      color: 'Winter blue sky, lake teal, campfire orange and cozy wool tones.',
      light: 'Crisp clear winter daylight and warm campfire glow at dusk.',
      texture: tv,
      camera: 'Scenic lakeside camp wides and cozy close-ups on hot food.',
      mood: 'cold-warm restorative comfort',
      render: 'Cozy scenic C-Station frame with winter camping calm.',
      key: 'Yuru Camp scenery; campfires; winter jackets; restorative calm',
    }),
    au('SP05-207', 'Shirobako P.A. Works - Deadline-Cheer Workflow Density', {
      look: 'P.A. Works Shirobako look (2014): busy anime studio workplaces, cluttered desks, production meetings, dense ensemble casts and cheerful deadline stress.',
      subject:
        'draw people with P.A. Works designs, office casual clothes, lanyards and determined tired expressions.',
      color: 'Office fluorescent white, desk clutter colors and warm late-night lamps.',
      light: 'Fluorescent office light and late-night desk lamps.',
      texture: tv,
      camera: 'Dense office ensemble compositions and meeting-room shots.',
      mood: 'cheerful deadline hustle',
      render: 'Detailed P.A. Works workplace frame.',
      key: 'Shirobako studio; cluttered desks; ensemble; deadlines',
    }),
    au('SP05-211', 'Super Cub Studio Kai - Utilitarian Quiet-Freedom Minimalism', {
      look: 'Studio Kai Super Cub look (2021): muted near-grey world that blooms into color with freedom, quiet solitary motorbike rides and precise mechanical detail.',
      subject:
        'draw people with quiet simple designs, plain clothes, helmets and careful practical gestures.',
      color: 'Muted grey that shifts into soft color when the rider feels free.',
      light: 'Soft natural daylight on quiet roads and garages.',
      texture: tv,
      camera: 'Quiet road compositions and mechanical close-ups.',
      mood: 'quiet utilitarian freedom',
      render: 'Understated Studio Kai frame with minimal restraint.',
      key: 'Super Cub muted palette; motorbike freedom; quiet solitude',
    }),
    au('SP05-215', 'Slow Loop Connect - Looped-Routine Healing Pastel', {
      look: 'Connect Slow Loop look (2022): pastel seaside fishing days, gentle family healing, soft rounded designs and calm routines.',
      subject: 'draw people with soft rounded designs, fishing hats and casual seaside clothes.',
      color: 'Pastel sea blue, sand beige and soft coral.',
      light: 'Soft seaside daylight and gentle sunsets.',
      texture: tv,
      camera: 'Riverside and seaside fishing compositions.',
      mood: 'gentle healing routine',
      render: 'Pastel healing slice-of-life frame.',
      key: 'Slow Loop pastel fishing; seaside; healing routine',
    }),
    au('SP05-216', 'Afro - Bundled Warmth Pocket', {
      look: 'Afro Laid-Back Camp manga art: simple clean line with round faces, detailed camping gear, winter scenery and warm cozy humor.',
      subject:
        'draw people with Afro designs, round faces, bundled winter layers and detailed camp gear.',
      color: 'Black ink with light tone, and soft winter color on covers.',
      light: 'Crisp winter light and warm stove glow.',
      texture: 'Clean simple manga line, light tone and detailed gear drawing.',
      camera: 'Cozy tent and stove compositions.',
      mood: 'bundled cozy warmth',
      render: 'Clean cozy camping manga illustration.',
      key: 'Afro clean line; camping gear; bundled warmth; winter',
    }),
    au('SP05-217', 'Eizouken Science SARU - Rough-Ideation Motion Overlay', {
      look: 'Science SARU Keep Your Hands Off Eizouken! look (2020) by Masaaki Yuasa: rough pencil sketch imagination overlays, concept-art worlds bursting from notebooks and lively animation passion.',
      subject:
        'draw people with Sumito Owara-derived designs, expressive faces and casual clothes, with rough sketch fantasies around them.',
      color: 'Flat everyday colors with rough watercolor imagination overlays.',
      light: 'Everyday light that shifts into imaginative sketch worlds.',
      texture: 'Rough pencil sketch lines layered over clean cel.',
      camera: 'Imagination transitions from desks into sketch worlds.',
      mood: 'giddy creative imagination',
      render: 'Energetic Science SARU frame with rough sketch overlays.',
      key: 'Eizouken sketch overlays; imagination; concept art; passion',
    }),
    au('SP05-082', 'Keiichi Arawi - Deadpan-Explosion Absurd Timing', {
      look: 'Keiichi Arawi Nichijou manga look: very simple clean rounded designs, flat pastel color, deadpan stillness exploding into absurd over-the-top gags.',
      subject:
        'draw people with Arawi simplicity, round faces, dot eyes and plain clothes, deadpan until chaos erupts.',
      color: 'Flat pastel blues, pinks and creams.',
      light: 'Flat even light with sudden explosion flashes.',
      texture: 'Very clean simple line and flat color.',
      camera: 'Deadpan still framing suddenly exploding into chaos.',
      mood: 'deadpan absurd chaos',
      render: 'Clean absurdist gag manga illustration.',
      key: 'Keiichi Arawi simplicity; deadpan; absurd explosions; pastel',
    }),
    au('SP05-083', 'Kagami Yoshimizu - Low-Stakes Banter Flatness', {
      look: 'Kagami Yoshimizu Lucky Star art: flat cute four-panel designs, big simple eyes, pastel color and low-stakes otaku chatter.',
      subject:
        'draw people with Yoshimizu designs, big simple eyes, small mouths and casual clothes.',
      color: 'Flat pastel pink, blue and lilac.',
      light: 'Flat even light.',
      texture: manga4,
      camera: 'Four-panel chatter compositions.',
      mood: 'low-stakes chatty comfort',
      render: 'Flat cute four-panel illustration.',
      key: 'Kagami Yoshimizu flat cute; four-panel; chatter',
    }),
    au('SP05-084', 'Noizi Ito - Ordinary-Cosmic Whimsy Pivot', {
      look: 'Noizi Ito illustration look as in her light novel art: crisp clean designs, bright energetic eyes, school settings flipping into cosmic whimsy.',
      subject: 'draw people with Noizi Ito designs, bright big eyes, ribbons and energetic poses.',
      color: 'Bright school colors with cosmic violet accents.',
      light: 'Clean bright illustration light with cosmic glow.',
      texture: 'Crisp digital illustration line and soft cel shading.',
      camera: 'Energetic illustration compositions.',
      mood: 'ordinary cosmic whimsy',
      render: 'Crisp light-novel illustration.',
      key: 'Noizi Ito designs; bright eyes; cosmic whimsy',
    }),
    au('SP05-085', 'Bocchi the Rock! CloverWorks - Anxiety-Glitch Catharsis Comedy', {
      look: 'CloverWorks Bocchi the Rock! look (2022): wild mixed-media anxiety gags, style switches into clay, photos and pixel art, and cathartic live-house rock.',
      subject:
        'draw people with soft cute designs, tracksuits and band gear, dissolving into wild style switches when anxious.',
      color: 'Soft pink, live-house blue and sudden glitch colors.',
      light: 'Live-house stage lights and comedic glitch flashes.',
      texture: 'Clean cel mixed with clay, photo and pixel-art gag inserts.',
      camera: 'Anxiety close-ups and live performance wides.',
      mood: 'anxious cathartic comedy',
      render: 'Inventive CloverWorks frame with mixed-media gags.',
      key: 'Bocchi mixed media; anxiety gags; live houses; catharsis',
      avoid: ['a pink-haired guitarist in a pink tracksuit', 'existing franchise characters'],
    }),
    au('SP05-087', 'Non Non Biyori Silver Link - Pastoral Breathing-Room Stillness', {
      look: 'Silver Link Non Non Biyori look (2013): lush painted rural Japan, long still shots of fields and cicadas, tiny figures and gentle countryside life.',
      subject: 'draw people with soft cute designs, simple country clothes and relaxed poses.',
      color: 'Lush green fields, blue sky and warm earth tones.',
      light: 'Warm rural sunlight and soft summer haze.',
      texture: 'Lush detailed painted countryside backgrounds with soft cel.',
      camera: 'Long still shots of landscapes with tiny figures.',
      mood: 'pastoral breathing-room stillness',
      render: 'Lush pastoral Silver Link frame.',
      key: 'Non Non Biyori countryside; long still shots; lush fields',
    }),
    au('SP05-090', 'Itaru Hinoue Key - Memory-Washed Melodrama Softness', {
      look: 'Itaru Hinoue Key visual novel art as in Clannad and Kanon: very large soft eyes, small faces, pastel memory-washed light and tearful melodrama.',
      subject:
        'draw people with Hinoue designs, huge soft eyes, small noses, long hair and simple clothes.',
      color: 'Soft pastel wash, sakura pink and pale gold.',
      light: 'Memory-washed soft glowing light.',
      texture: 'Soft digital illustration with pastel gradients.',
      camera: 'Tearful close-ups and wistful town views.',
      mood: 'memory-washed tender melodrama',
      render: 'Soft visual-novel illustration look.',
      key: 'Itaru Hinoue huge eyes; pastel washes; Key melodrama',
    }),
    au('SP05-201', 'Hyouka Kyoto Animation - Tea-Light Observational Mystery', {
      look: 'Kyoto Animation Hyouka look (2012): detailed school club rooms, curious flower-petal imagination sequences, warm tea light and quiet observational mysteries.',
      subject:
        'draw people with KyoAni designs, expressive curious eyes, school uniforms and precise small gestures.',
      color: 'Warm tea amber, old book brown and soft classroom light.',
      light: 'Warm afternoon light and imaginative flower-petal glows.',
      texture: tv,
      camera: 'Club-room compositions and imaginative petal sequences.',
      mood: 'curious observational calm',
      render: 'Refined Kyoto Animation mystery frame.',
      key: 'Hyouka curiosity; club rooms; flower-petal imagination; mysteries',
    }),
    au('SP05-203', 'A Place Further Than the Universe Madhouse - Horizon-Forward Youth Momentum', {
      look: 'Madhouse A Place Further Than the Universe look (2018): vivid journey to Antarctica, icebergs and auroras, bright expressive faces and horizon-forward momentum.',
      subject:
        'draw people with bright expressive designs, expedition parkas and determined faces.',
      color: 'Iceberg blue, aurora green, snow white and expedition orange.',
      light: 'Bright polar sunlight and aurora glow.',
      texture: tv,
      camera: 'Vast polar horizons and ship-deck compositions.',
      mood: 'bright horizon-forward momentum',
      render: 'Vivid Madhouse journey frame.',
      key: 'Antarctic journey; icebergs; auroras; momentum',
    }),
    au('SP05-204', 'Kozue Amano Aria - Reflective Breeze Healing Reverie', {
      look: 'Kozue Amano Aria look: Neo-Venezia canals on terraformed Mars, gondoliers, sunlit water reflections, breezy calm and healing wonder.',
      subject:
        'draw people with Amano designs, gentle faces, gondolier uniforms and relaxed poses.',
      color: 'Canal blue, terracotta, white and sunlit gold.',
      light: 'Sparkling canal reflections and breezy sunlight.',
      texture: tv,
      camera: 'Canal and gondola compositions.',
      mood: 'reflective healing reverie',
      render: 'Breezy healing canal frame.',
      key: 'Aria Neo-Venezia; canals; gondoliers; healing',
    }),
    au('SP05-205', 'Satsuki Yoshino - Breezy Brush-Reinvention Summer', {
      look: 'Satsuki Yoshino Barakamon look: sunny island life, bold calligraphy brush energy, rustic villages and breezy summer comedy.',
      subject: 'draw people with Yoshino designs, casual island clothes and expressive faces.',
      color: 'Island green, sea blue, ink black and sun white.',
      light: 'Bright island sunlight.',
      texture: 'Clean line with bold ink brush accents.',
      camera: 'Island village compositions.',
      mood: 'breezy summer reinvention',
      render: 'Sunny island comedy illustration.',
      key: 'Barakamon island; calligraphy brush; summer',
    }),
    au('SP05-206', 'Yumi Unita - Everyday-Care Gesture Intimacy', {
      look: 'Yumi Unita Usagi Drop look: soft watercolor-like gentle illustration, everyday caregiving, tender small gestures and warm homes.',
      subject:
        'draw people with Unita designs, soft faces, simple home clothes and caring gestures.',
      color: 'Soft watercolor pastels and warm home tones.',
      light: 'Soft warm home light.',
      texture: 'Soft watercolor-like washes and gentle lines.',
      camera: 'Intimate home compositions.',
      mood: 'tender everyday care',
      render: 'Gentle watercolor slice-of-life illustration.',
      key: 'Yumi Unita watercolor; caregiving; tender gestures',
    }),
    au('SP05-209', 'Koi Gochiusa - Sugar-Cotton Hospitality Miniature', {
      look: 'Koi Is the Order a Rabbit? look: sugar-cotton cafe town of half-timbered houses, fluffy rabbits, frilly cafe uniforms and pastel sweetness.',
      subject:
        'draw people with Koi designs, big gentle eyes, fluffy hair and frilly cafe uniforms.',
      color: 'Sugar pastel pink, cream, lavender and mint.',
      light: 'Soft sweet cafe light.',
      texture: tv,
      camera: 'Cafe and European town compositions.',
      mood: 'sugary cozy hospitality',
      render: 'Sweet pastel cafe frame.',
      key: 'Gochiusa pastel cafe; half-timbered town; rabbits',
    }),
    au('SP05-210', 'Ume Aoki - Sunshine-Scribble Soft Geometry', {
      look: 'Ume Aoki Hidamari Sketch look: round simple faces, art school dorm life, playful geometric scribble backgrounds and sunny pastel color.',
      subject: 'draw people with Aoki designs, round faces, big eyes and art school clothes.',
      color: 'Sunny pastels, lemon, sky blue and pink.',
      light: 'Bright sunny light.',
      texture: 'Soft line with scribbled geometric backgrounds.',
      camera: 'Playful geometric compositions.',
      mood: 'sunny scribbled cheer',
      render: 'Playful pastel illustration.',
      key: 'Ume Aoki round faces; scribble geometry; art dorm',
    }),
    au('SP05-212', 'Komi Can’t Communicate OLM - Immaculate Social-Jitter Comedy', {
      look: 'OLM Komi Can’t Communicate look (2021): immaculate elegant designs, chalkboard gag cards, soft pastel comedy and social anxiety humor.',
      subject:
        'draw people with elegant designs, long straight hair, calm faces and nervous body language.',
      color: 'Soft pastels and chalkboard green.',
      light: 'Soft school light.',
      texture: tv,
      camera: 'Comedy cut-ins and elegant still compositions.',
      mood: 'jittery social comedy',
      render: 'Polished pastel comedy frame.',
      key: 'Komi elegance; social jitters; chalkboard gags',
      avoid: ['a long black-haired girl with a notebook', 'existing franchise characters'],
    }),
    au('SP05-213', 'Karino Takatsu - Shift-Comedy Choreography Warmth', {
      look: 'Karino Takatsu Working!! look: bright family restaurant comedy, four-panel roots, uniforms and choreographed shift chaos.',
      subject: 'draw people with Takatsu designs, restaurant uniforms and expressive comic faces.',
      color: 'Bright restaurant warm tones.',
      light: 'Bright restaurant light.',
      texture: manga4,
      camera: 'Choreographed shift comedy compositions.',
      mood: 'warm shift comedy',
      render: 'Bright workplace comedy illustration.',
      key: 'Working!! restaurant; shift comedy; uniforms',
    }),
    au('SP05-214', 'Tanaka-kun Silver Link - Breeze-Drift Beautiful Inertia', {
      look: 'Silver Link Tanaka-kun Is Always Listless look (2016): soft breezy pastel, lethargic comedy, sunlit windows and beautiful laziness.',
      subject: 'draw people with soft designs, sleepy half-lidded eyes and relaxed slouched poses.',
      color: 'Soft breezy pastel green and sky blue.',
      light: 'Sunlit breezy windows.',
      texture: tv,
      camera: 'Lethargic still compositions.',
      mood: 'breezy beautiful inertia',
      render: 'Soft breezy comedy frame.',
      key: 'Tanaka-kun lethargy; breezy pastels; laziness',
    }),
    au('SP05-218', 'Yama no Susume 8bit - Incremental-Ascent Confidence Light', {
      look: 'Eight Bit Encouragement of Climb look (2013): mountain hiking, scenic summits, sunrise light and small steps of confidence.',
      subject: 'draw people with soft cute designs, hiking gear and determined faces.',
      color: 'Mountain green, sunrise gold and sky blue.',
      light: 'Summit sunrise light.',
      texture: tv,
      camera: 'Scenic trail and summit compositions.',
      mood: 'incremental ascending confidence',
      render: 'Scenic hiking television frame.',
      key: 'Yama no Susume hiking; summits; sunrise',
    }),
    au('SP05-219', 'Daily Lives of High School Boys Sunrise - Mundane Absurdist Theater', {
      look: 'Sunrise Daily Lives of High School Boys look (2012): mundane absurdist comedy, deadpan dramatic staging of trivial moments, realistic plain designs.',
      subject: 'draw people with plain realistic designs and deadpan dramatic poses.',
      color: 'Plain everyday school colors.',
      light: 'Dramatic lighting on mundane moments.',
      texture: tv,
      camera: 'Overly dramatic staging of trivial moments.',
      mood: 'mundane absurdist theater',
      render: 'Deadpan comedy television frame.',
      key: 'Mundane absurdity; dramatic staging; deadpan',
    }),
    au('SP05-220', 'Totan Kobako - Observational Watercolor Drift', {
      look: 'Totan Kobako Sketchbook look: gentle observational sketching, watercolor wash, stray cats, quiet afternoons and small discoveries.',
      subject: 'draw people with soft gentle designs, sketchbooks and quiet observing poses.',
      color: 'Soft watercolor pastels.',
      light: 'Quiet afternoon light.',
      texture: 'Watercolor washes and gentle pencil lines.',
      camera: 'Quiet observation compositions.',
      mood: 'gentle observational drift',
      render: 'Soft watercolor sketchbook illustration.',
      key: 'Sketchbook watercolor; stray cats; observation',
    }),
    au('SP05-088', 'Coolkyousinnjya - Domestic-Fantasy Scale Chaos', {
      look: 'Coolkyousinnjya Miss Kobayashi’s Dragon Maid manga look: simple rounded designs, dragons in maid outfits, domestic comedy and huge-scale fantasy chaos.',
      subject:
        'draw people with Coolkyousinnjya designs, simple round faces, horns and tails on dragons, and casual office clothes.',
      color: 'Bright domestic pastels and dragon colors.',
      light: 'Bright apartment light.',
      texture: 'Simple clean manga line with flat color.',
      camera: 'Domestic scenes exploding into giant-scale chaos.',
      mood: 'domestic fantasy chaos',
      render: 'Simple cheerful comedy manga illustration.',
      key: 'Dragon Maid domestic; dragons; scale chaos',
      avoid: ['a red-haired dragon maid with horns and a tail', 'existing franchise characters'],
    }),
    au('SP05-089', 'Kiyohiko Azuma - Soft-Surreal Deadpan Drift', {
      look: 'Kiyohiko Azuma Azumanga Daioh and Yotsuba&! look: clean soft line, simple faces, deadpan surreal humor and gentle everyday wonder.',
      subject: 'draw people with Azuma designs, simple faces, dot eyes and casual clothes.',
      color: 'Soft pastels and clean white.',
      light: 'Soft everyday light.',
      texture: manga4,
      camera: 'Deadpan still compositions.',
      mood: 'soft surreal deadpan',
      render: 'Clean gentle comedy manga illustration.',
      key: 'Kiyohiko Azuma clean line; deadpan; everyday wonder',
    }),
  ]),
};

export default spec;
