import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, heroes and epics: culture-rooted visual languages for epic journeys, duels and
// legendary deeds. Fourteen originals stay; eight new looks add Persian, Odia, Kyrgyz, Sicilian,
// Ethiopian, Chinese, Filipino and Mongolian storytelling traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} epic hero art`,
  tags: [tag, culture.toLowerCase().replace(/\s+/g, '-'), 'mythic-heroes', 'portable-style-study'],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Heroes & Epics',
  updates: {},
  creates: [
    s(
      'Qajar Coffeehouse Epic Canvas',
      'coffeehouse-epic',
      'Persian',
      'Qajar coffeehouse epic canvas: large Persian storyteller canvases painted for coffeehouse recitals, crowded with champions in tiger-skin armor, white demons, duels and many episodes of one epic on a single cloth.',
      'paint the subject as a champion in a crowded storyteller canvas where several episodes happen at once.',
      'Earth red, ochre, olive green, deep blue, bone white and soot black.',
      'Flat even light with bold dark outlines and little modeling.',
      'Oil on unprimed cotton, cracked paint, creases from rolling and smoke-darkened varnish.',
      'Wide canvas packed with episodes, the champion painted largest at the center.',
      'rousing heroic storytelling',
      'Bold naive-heroic painting with dense narrative crowds, kept consistent across the whole image.',
      'champion in tiger skin; many episodes at once; white demon; crowded canvas',
      [
        'Painted across a smoke-darkened canvas, a champion in tiger-skin armor wrestles a white demon at the center while the same champion also slays a dragon, crosses a desert and weeps over a lost son in the corners. No readable text or logo.',
        'On a crowded storyteller canvas, the same horse appears in seven different episodes and looks more tired in each one. No readable text or logo.',
        "Rolled half open on a coffeehouse bench after closing, a painted cloth shows only a hero's raised mace and a single lamp still lit. No readable text or logo.",
      ],
    ),
    s(
      'Pattachitra Epic Scroll',
      'pattachitra-epic',
      'Odia',
      'Pattachitra epic scroll: Odisha cloth paintings with bold ornamental borders, stylized almond-eyed heroes, dense floral fields and epic battles and journeys on chalk-primed cloth.',
      'paint the subject with almond eyes and ornamented profile inside dense floral borders on primed cloth.',
      'Conch white, lamp black, red ochre, yellow, indigo and leaf green.',
      'Flat shadowless color with crisp black line, kept consistent across the whole image.',
      'Chalk and tamarind-primed cloth, natural pigment, fine brush line and lacquered finish.',
      'Framed panel with ornate multiple borders and figures in profile across a patterned field.',
      'devotional heroic splendor',
      'Precise decorative line painting with every surface ornamented.',
      'almond-eyed profile heroes; ornamental borders; floral field; primed cloth',
      [
        'Framed by triple floral borders, an archer prince in profile draws his bow against a ten-headed giant while an army of monkeys builds a stone bridge across a patterned sea. No readable text or logo.',
        'Inside a dense floral border, a mighty monkey hero carries an entire mountain because he could not remember which healing herb he was sent to fetch. No readable text or logo.',
        'On a painted cloth panel, a single golden deer grazes in an ornamented forest, and one footprint at the edge suggests someone is following it. No readable text or logo.',
      ],
    ),
    s(
      'Kyrgyz Epic Felt Hanging',
      'kyrgyz-felt',
      'Kyrgyz',
      'Kyrgyz epic felt hanging: nomad felt hangings with inlaid ram-horn spirals and appliqued riders, eagles and battle scenes from the great steppe epic, stitched in bold contrasting colors.',
      'build the subject from inlaid felt shapes with bold outlines of cord and ram-horn spirals around it.',
      'Madder red, indigo, saffron yellow, undyed cream and black.',
      'Soft yurt light falling across thick felt with gentle raised edges.',
      'Pressed wool felt, inlaid shapes, twisted cord outlines and hand stitching.',
      'Frontal hanging with a central scene inside spiral borders.',
      'proud nomadic epic',
      'Bold simplified felt forms with crisp contrast, kept consistent across the whole image.',
      'felt riders; ram-horn spirals; eagle; cord outlines',
      [
        'Inlaid in red and indigo felt, an epic hero on a black stallion charges across the steppe with a golden eagle on his arm as forty companions follow in a single spiral line. No readable text or logo.',
        'Stitched into a nomad felt hanging, a golden eagle has been given so many ram-horn spirals for feathers that it seems to be flying in every direction at once. No readable text or logo.',
        'Inside a quiet yurt, a felt hanging shows a lone rider on the horizon, and the lamp flickers across the raised cord outlines. No readable text or logo.',
      ],
    ),
    s(
      'Sicilian Cart Paladin Panel',
      'sicilian-cart',
      'Sicilian',
      'Sicilian cart paladin panel: painted panels from Sicilian donkey carts showing armored paladins, jousts and battles against rival knights and sea giants in glossy saturated colors with carved gilt frames.',
      'paint the subject as a glossy armored champion on a carved and painted cart panel.',
      'Cart yellow, vermilion, cobalt, emerald green and silver armor.',
      'Bright Mediterranean sun giving glossy highlights on enamel paint.',
      'Glossy enamel paint on wood, carved frames, gilded scrolls and wheel spokes.',
      'Rectangular panel with a crowded battle scene inside carved scroll frames.',
      'boisterous chivalric pride',
      'Vivid folk painting with bold outlines and polished shine.',
      'armored paladins; joust; carved scroll frame; glossy cart paint',
      [
        'Painted on the side of a festival cart, an armored paladin with a plumed helmet splits an enemy shield in a dazzling joust while the carved wheel spokes blaze in yellow and red. No readable text or logo.',
        'On a painted cart panel, two armored knights are frozen mid-duel while the donkey pulling the cart looks deeply unimpressed. No readable text or logo.',
        'Parked in a sunlit square, an empty painted cart shows a single fallen sword on its panel as church bells ring. No readable text or logo.',
      ],
    ),
    s(
      'Ethiopian Legend Strip Painting',
      'ethiopian-strip',
      'Ethiopian',
      'Ethiopian legend strip painting: Ethiopian popular paintings telling a legend across rows of small panels, large-eyed figures in profile and frontal views, bright flat color on canvas.',
      'paint the subject with large almond eyes in a row of bright flat story panels on canvas.',
      'Saffron yellow, green, red, sky blue and white.',
      'Flat bright light with no cast shadow, kept consistent across the whole image.',
      'Tempera or oil on canvas, bold outlines and crisp panel dividers.',
      'Grid of story panels read in rows, the hero reappearing in each.',
      'noble legendary wonder',
      'Clear flat narrative painting with expressive eyes, kept consistent across the whole image.',
      'story panels in rows; large almond eyes; bright flat color; legendary journey',
      [
        'Across four rows of bright panels, a legendary queen travels with a caravan of camels to a distant court, meets its wise ruler and returns home carrying a secret gift. No readable text or logo.',
        'In one small story panel, a gifted queen tests a famous wise ruler with a riddle, and his face shows he has no idea. No readable text or logo.',
        'In the last panel of a story canvas, a lone traveler sits beside a fire under a star, and the caravan has gone ahead. No readable text or logo.',
      ],
    ),
    s(
      'Nianhua Door Warrior Print',
      'door-warrior',
      'Chinese',
      'Nianhua door warrior print: Chinese New Year woodblock prints of paired guardian generals in armor, hand-colored with bold outlines, pasted on doors to protect the household.',
      'print the subject as a fierce armored guardian general in a bold hand-colored woodblock.',
      'Vermilion, peach pink, emerald, yellow, black outline and paper white.',
      'Flat woodblock color with no cast light, kept consistent across the whole image.',
      'Woodblock line, stenciled hand color, paper grain and slight misregistration.',
      'Tall frontal figure filling a door panel, mirrored by its pair.',
      'festive fierce protection',
      'Bold decorative woodblock with strong symmetry, kept consistent across the whole image.',
      'paired armored generals; door panels; hand-colored woodblock; festive colors',
      [
        'Pasted on a pair of old wooden doors, two armored guardian generals with fierce eyebrows and flag-spined armor raise their maces at a sneaking spirit on the doorstep. No readable text or logo.',
        'On two freshly pasted doors, the guardian generals face each other and seem to be arguing about who gets the better door. No readable text or logo.',
        'On a snowy alley doorway, a faded guardian print peels at one corner, and fresh firecracker paper lies below. No readable text or logo.',
      ],
    ),
    s(
      'Filipino Komiks Epic Hero',
      'filipino-komiks',
      'Filipino',
      'Filipino komiks epic hero: classic Filipino komiks art of island epics, heroes and enchanted beings in lush ink linework, dramatic poses, jungle backgrounds and newsprint color.',
      'draw the subject as a heroic figure in lush komiks ink with dramatic pose and jungle backdrop.',
      'Newsprint cream, flat halftone color, jungle green and sunset orange.',
      'Dramatic ink shadow and strong sunlight contrast, kept consistent across the whole image.',
      'Brush ink linework, crosshatching, halftone color and pulp paper.',
      'Dynamic heroic angle in a panel with jungle or sea behind.',
      'vivid adventurous heroism',
      'Masterful ink illustration with dynamic anatomy, kept consistent across the whole image.',
      'island epic hero; lush ink lines; jungle backdrop; newsprint color',
      [
        'Leaping from a jungle cliff in lush ink lines, a legendary hero swings his golden blade against a giant crocodile guarding a river of enchanted gold as monsoon clouds boil. No readable text or logo.',
        'In a dramatic comic panel, a legendary hero is ready for battle but his loyal rooster companion has already won it. No readable text or logo.',
        'On a quiet beach in ink, one sword stands in the sand as the tide comes in. No readable text or logo.',
      ],
    ),
    s(
      'Mongolian Zurag Panorama',
      'mongol-zurag',
      'Mongolian',
      'Mongolian zurag panorama: Mongol zurag painting with tiny detailed figures spread across vast steppe panoramas, gers, horses and many episodes of an epic hero happening at once.',
      'paint the subject as a tiny detailed figure within a vast steppe panorama of many simultaneous episodes.',
      'Steppe green, sky blue, ochre, red and white gers.',
      'Clear even steppe light with little shadow, kept consistent across the whole image.',
      'Mineral pigment on cotton, fine brush, tiny detailed figures.',
      "Bird's-eye panorama with many tiny scenes across rolling hills.",
      'vast epic scope',
      'Meticulous miniature detail across a wide landscape, kept consistent across the whole image.',
      'steppe panorama; tiny figures; gers and horses; many episodes',
      [
        'Across a vast painted steppe, a tiny epic hero on a chestnut horse battles a many-headed monster in one valley while in the next valley his people celebrate his return. No readable text or logo.',
        'In a steppe panorama with a hundred tiny scenes, one exhausted hero is still chasing a runaway camel that has wandered into three other episodes. No readable text or logo.',
        'On a wide painted steppe at dawn, a single ger smokes quietly, and a tiny rider appears on the far hill. No readable text or logo.',
      ],
    ),
  ],
};

export default spec;
