import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Tactical and solitary frontier art directions: the two referenced directions keep their DNA and
// get original briefs; eighteen new directions with original names each pair one lonely frontier
// (ice, desert, orbit, deep cave, storm rig...) with a distinct painting or drawing method.
const FRONTIER_AVOID = ['gore', 'real military insignia', 'real brand or company logo'];
const dir = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'art-direction', 'frontier'],
  dna: dna(fields),
  avoid: [...avoid, ...FRONTIER_AVOID, ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_24',
  category: '2. Tactical & Solitary Frontiers',
  updates: {
    'SP24-005': {
      briefs: [
        'A lone scout crouches in monsoon mud behind a fallen tree, rain and fronds slashed in dry black brush strokes and her rifle silhouette the only crisp line. No readable text or logo.',
        'A mechanic in fatigues repairs a jeep engine in a jungle clearing, the machine drawn in confident ink while the foliage dissolves into translucent wash. No readable text or logo.',
        'Two figures shake hands on a rope bridge above a gorge, their silhouettes brushed in heavy ink as mist swallows both ends of the bridge. No readable text or logo.',
      ],
    },
    'SP24-006': {
      briefs: [
        'A courier bent under a towering backpack crosses a black volcanic plain toward a tiny relay tower, rain veiling the mountains behind him. No readable text or logo.',
        'A cable bridge of thin metal spans a green ravine where waterfalls pour into mist, one small figure halfway across. No readable text or logo.',
        'A lone traveler rests beside a small shelter on a mossy ridge while a strange rainbow arcs the wrong way across the grey sky. No readable text or logo.',
      ],
    },
  },
  creates: [
    dir('Arctic Weather-Station Solitude', 'polar outpost solitude', 'arctic-station', {
      aesthetic: 'Arctic weather-station solitude: a tiny research hut and instrument masts on endless white ice, painted in cold gouache with one warm window glowing.',
      subject_treatment: "Place the prompt's subject at or near a lonely polar outpost, keeping it clear against vast white ice and pale sky.",
      color_and_tone: 'Icy blues and whites, pale lilac shadows and a single warm amber window glow.',
      lighting_and_shadow: 'Low polar sun or long twilight, soft blue shadows stretching across the snow.',
      texture_and_material: 'Matte gouache snow, wind-carved drifts, frosted masts and weathered hut panels.',
      camera_and_composition: 'Very wide frames with a tiny outpost against a huge empty horizon.',
      atmosphere_and_mood: 'Quiet, cold and devoted, one person keeping watch at the edge of the world.',
      rendering_and_quality: 'Clean matte gouache painting with crisp shapes and soft snow gradients.',
      key_features: 'tiny polar outpost; endless ice; warm window glow; long blue shadows',
    }, ['tropical scenery'], [
      'A meteorologist steps out of a tiny hut to read the instruments while the aurora pours green light over a thousand miles of ice. No readable text or logo.',
      'A polar bear sits politely outside a weather station door as if waiting to be let in for the night shift. No readable text or logo.',
      'One warm window glows in a research hut buried to its roof in snow, a single thread of smoke rising straight up. No readable text or logo.',
    ]),
    dir('Desert Long-Haul Courier', 'lone desert haulage', 'desert-courier', {
      aesthetic: 'Desert long-haul courier: a single battered truck or walker crossing enormous dune seas, painted in heat-shimmer ochres with dust trailing for miles.',
      subject_treatment: "Put the prompt's subject on a long lonely desert haul, keeping it clear against dunes, dust and shimmering heat.",
      color_and_tone: 'Burnt ochre, sand gold and bleached blue sky with violet distant ridges.',
      lighting_and_shadow: 'Harsh overhead sun, short black shadows and shimmering heat haze on the horizon.',
      texture_and_material: 'Wind-rippled sand, sun-bleached metal, dust plumes and cracked leather.',
      camera_and_composition: 'Wide low horizons with the courier small and dust trails leading the eye.',
      atmosphere_and_mood: 'Determined, parched and solitary, the delivery must arrive.',
      rendering_and_quality: 'Sunbaked painterly realism with heat shimmer and fine dust.',
      key_features: 'lone desert haul; heat shimmer; dust plumes; bleached sky',
    }, ['lush greenery'], [
      'A battered truck hauls a single grand piano across a sea of dunes, its driver asleep at the wheel while the truck steers itself. No readable text or logo.',
      'A courier on foot drags a sled of water barrels past the skeleton of an ancient whale half buried in the sand. No readable text or logo.',
      'At noon a lone driver stops to share his shade with a desert fox under the belly of his truck. No readable text or logo.',
    ]),
    dir('Orbital Lone Maintenance', 'solo orbital repair work', 'orbital-maintenance', {
      aesthetic: 'Orbital lone maintenance: a single technician tethered to a vast silent structure in orbit, rendered in crisp technical illustration with the planet turning below.',
      subject_treatment: "Place the prompt's subject on or near an orbital structure, keeping it clear against black space and the curve of a planet.",
      color_and_tone: 'Stark white suits, black space, blue planet glow and small orange warning lights.',
      lighting_and_shadow: 'Unfiltered sunlight with razor shadows and soft planet bounce from below.',
      texture_and_material: 'Scuffed suit fabric, insulation foil, tether cables, bolts and solar panels.',
      camera_and_composition: 'The technician small on a huge structure, planet curve filling part of the frame.',
      atmosphere_and_mood: 'Silent, focused and precarious, one bolt at a time above the world.',
      rendering_and_quality: 'Crisp technical illustration with precise hardware and clean light.',
      key_features: 'tethered lone technician; vast orbital structure; planet curve; razor sunlight',
    }, ['atmospheric haze in space'], [
      'A technician tightens a single bolt on a solar array a mile long while the whole night side of the planet sparkles below her boots. No readable text or logo.',
      'A spacewalker drops a wrench and watches it drift slowly toward the moon, sighing inside the helmet. No readable text or logo.',
      'Alone on the hull of a station, a mechanic pauses to watch a sunrise race across the planet in eight seconds. No readable text or logo.',
    ]),
    dir('Whiteout Mountain Rescue', 'alpine rescue in whiteout', 'whiteout-rescue', {
      aesthetic: 'Whiteout mountain rescue: rescuers roped together on a storm-blasted ridge, painted in near-white charcoal and chalk where snow and sky merge.',
      subject_treatment: "Put the prompt's subject into an alpine whiteout, keeping it readable as a dark shape inside swirling snow.",
      color_and_tone: 'Near-white greys, charcoal silhouettes and a single red jacket or flare.',
      lighting_and_shadow: 'Flat diffused whiteout light with almost no shadows and a glowing flare.',
      texture_and_material: 'Charcoal smudges, chalk snow, frozen rope, ice-crusted clothing and wind streaks.',
      camera_and_composition: 'Figures roped in a line along a diagonal ridge, horizon lost in white.',
      atmosphere_and_mood: 'Urgent, brave and disoriented, holding the rope in nothing.',
      rendering_and_quality: 'Expressive charcoal and chalk drawing with strong wind direction.',
      key_features: 'whiteout blending snow and sky; roped rescuers; red accent; wind streaks',
    }, ['clear blue sky', 'summer'], [
      'A rescue team roped together follows a single red flare through a whiteout so complete that the ridge seems to float. No readable text or logo.',
      'A rescue dog leads four climbers down a mountain in the blizzard, the only one who seems to know the way. No readable text or logo.',
      'A lost climber sits wrapped in a red emergency blanket, a faint headlamp beam appearing in the white beside her. No readable text or logo.',
    ]),
    dir('Fire-Lookout Tower Vigil', 'wildfire lookout solitude', 'fire-lookout', {
      aesthetic: 'Fire-lookout tower vigil: a lone watcher in a glass cabin atop a tower above endless forest, painted in warm gouache with smoke columns on the horizon.',
      subject_treatment: "Place the prompt's subject in or around a forest lookout tower, keeping it clear above a sea of treetops.",
      color_and_tone: 'Deep forest greens, amber sunset, violet smoke and warm cabin light.',
      lighting_and_shadow: 'Golden low sun, long tree shadows and a smoky glow on the horizon.',
      texture_and_material: 'Weathered timber, cabin glass, pine needles and soft smoke plumes.',
      camera_and_composition: 'Tower rising above forest, horizon high with distant smoke columns.',
      atmosphere_and_mood: 'Watchful, peaceful and uneasy, beauty with danger far away.',
      rendering_and_quality: 'Warm painterly gouache with soft atmospheric depth and haze.',
      key_features: 'lookout tower above forest; distant smoke columns; glass cabin; long sunset',
    }, ['close flames engulfing', 'gore'], [
      'A lookout spots a thin smoke column on the horizon while a thunderstorm walks across the forest toward her tower. No readable text or logo.',
      'A retired ranger plays chess alone in the glass cabin of a fire tower, a hawk perched on the railing as his opponent. No readable text or logo.',
      'At dawn the forest below a lookout tower is buried in fog, only the tops of the tallest pines showing like islands. No readable text or logo.',
    ]),
    dir('Deep-Cave Survey Lamp', 'lone cave surveying', 'cave-survey', {
      aesthetic: 'Deep-cave survey lamp: a lone surveyor mapping enormous underground chambers by helmet lamp, painted in dense ink wash where light barely reaches.',
      subject_treatment: "Place the prompt's subject deep underground in a small headlamp pool, keeping it clear inside immense darkness.",
      color_and_tone: 'Near-black ink wash, warm headlamp yellow and faint mineral glints.',
      lighting_and_shadow: 'Single headlamp beam, small pools of light and total darkness beyond.',
      texture_and_material: 'Wet limestone, flowstone, rope, mud-caked coveralls and dripping water.',
      camera_and_composition: 'Tiny lit figure within vast dark chambers, scale shown by the beam.',
      atmosphere_and_mood: 'Awestruck, careful and lonely, the first light in a place that never saw any.',
      rendering_and_quality: 'Dense ink-wash painting with precise small warm highlights.',
      key_features: 'single headlamp beam; immense cave darkness; wet stone; tiny surveyor',
    }, ['daylight', 'crowded tourists'], [
      'A surveyor\'s headlamp sweeps across an underground lake so still it looks like a second cave hanging upside down. No readable text or logo.',
      'A caver squeezes through a narrow passage and her lamp reveals a chamber full of giant crystals taller than houses. No readable text or logo.',
      'At the end of a rope, a lone surveyor measures a stalagmite that has been growing drop by drop for a hundred thousand years. No readable text or logo.',
    ]),
    dir('Submarine Night Watch', 'red-lit submarine watch', 'submarine-watch', {
      aesthetic: 'Submarine night watch: a single sailor on watch in a cramped red-lit control room, painted in tight chiaroscuro with gauges glowing in the gloom.',
      subject_treatment: "Place the prompt's subject inside a cramped red-lit vessel interior, keeping it clear among pipes and glowing gauges.",
      color_and_tone: 'Deep red night lighting, black shadows and faint green instrument glow.',
      lighting_and_shadow: 'Red lamps and instrument glow, heavy chiaroscuro with faces half lit.',
      texture_and_material: 'Painted steel, valves, cables, condensation and worn wool sweaters.',
      camera_and_composition: 'Tight claustrophobic framing with pipes and equipment crowding the edges.',
      atmosphere_and_mood: 'Tense, quiet and focused, listening to the dark sea.',
      rendering_and_quality: 'Moody chiaroscuro painting with crisp glowing instrument highlights.',
      key_features: 'red night lighting; cramped control room; glowing gauges; lone watcher',
    }, ['daylight', 'spacious rooms'], [
      'A sonar operator on night watch presses her headphones closer as a slow song comes from something far below the hull. No readable text or logo.',
      'A cook on night watch fries a single egg in a cramped galley bathed in red light, the whole crew asleep behind him. No readable text or logo.',
      'A lone officer stares at a round dial whose needle has slowly started to move on its own. No readable text or logo.',
    ]),
    dir('Tundra Trapper Cabin', 'lone northern cabin life', 'tundra-cabin', {
      aesthetic: 'Tundra trapper cabin: a single log cabin on endless snowy tundra, painted in muted oil with smoke rising and snowshoe tracks leading away.',
      subject_treatment: "Place the prompt's subject around a remote snowy cabin, keeping it clear in the muted winter landscape.",
      color_and_tone: 'Muted whites, slate blues, dark spruce and warm brown log walls.',
      lighting_and_shadow: 'Low winter light, soft blue shadows and a warm glow from the cabin window.',
      texture_and_material: 'Rough logs, snow drifts, furs, frosted windows and woodsmoke.',
      camera_and_composition: 'Small cabin in a wide snowy expanse, tracks leading the eye.',
      atmosphere_and_mood: 'Self-reliant, quiet and cold, a life measured in firewood.',
      rendering_and_quality: 'Muted oil painting with soft snow and textured brushwork.',
      key_features: 'lone log cabin; snowy tundra; snowshoe tracks; woodsmoke',
    }, ['summer'], [
      'A trapper returns to his cabin at dusk and finds a family of foxes asleep on his porch in a perfect ring. No readable text or logo.',
      'Snowshoe tracks lead from a lonely cabin to a frozen lake where a woman fishes through a hole under the northern lights. No readable text or logo.',
      'A single cabin sits in endless white, its chimney smoke drifting sideways in a wind that has blown for three days. No readable text or logo.',
    ]),
    dir('Salt-Flat Signal Post', 'lone salt flat outpost', 'salt-flat', {
      aesthetic: 'Salt-flat signal post: a lonely antenna and caravan on mirror-flat white salt, painted in minimal pale tones where sky and ground reflect each other.',
      subject_treatment: "Place the prompt's subject on a vast mirror-like salt flat, keeping it clear with its reflection beneath.",
      color_and_tone: 'Brilliant white salt, pale sky blue and pink dawn tones mirrored below.',
      lighting_and_shadow: 'Soft wide sky light with perfect reflections and faint shadows.',
      texture_and_material: 'Cracked hexagonal salt crust, thin water sheen, weathered metal antenna.',
      camera_and_composition: 'Horizon in the center, subject and reflection mirrored top and bottom.',
      atmosphere_and_mood: 'Minimal, surreal and lonely, a signal sent into emptiness.',
      rendering_and_quality: 'Clean minimal painting with precise mirror reflections and calm.',
      key_features: 'mirror salt flat; lone antenna; perfect reflection; hexagonal crust',
    }, ['crowds', 'dense forest'], [
      'A radio operator sits in a folding chair on a flooded salt flat, her antenna and its reflection making one long silver needle. No readable text or logo.',
      'A caravan parks on endless white salt at dawn and its owner walks out onto the mirror to hang laundry on the antenna. No readable text or logo.',
      'A single blinking beacon on a salt flat reflects perfectly into the ground, as if it were signaling to itself. No readable text or logo.',
    ]),
    dir('Storm-Rig Night Shift', 'offshore rig in storm', 'storm-rig', {
      aesthetic: 'Storm-rig night shift: an offshore platform battered by black waves at night, painted in heavy wet oils with sodium floodlights and flying spray.',
      subject_treatment: "Place the prompt's subject on a storm-lashed offshore platform, keeping it clear under floodlights and spray.",
      color_and_tone: 'Black water, steel grey, sodium orange floodlights and white spray.',
      lighting_and_shadow: 'Harsh floodlights cutting through rain and spray, deep darkness beyond.',
      texture_and_material: 'Wet steel grating, rust, safety orange gear, flying spray and rain.',
      camera_and_composition: 'Low angles on the rig with towering waves and dramatic diagonals.',
      atmosphere_and_mood: 'Relentless, dangerous and defiant, the night shift continues regardless.',
      rendering_and_quality: 'Heavy wet oil painting with bold light and spray effects.',
      key_features: 'offshore rig; towering night waves; sodium floodlights; flying spray',
    }, ['calm sea', 'daylight'], [
      'A rig worker in orange oilskins grips a railing as a wave taller than the platform rises out of the dark behind her. No readable text or logo.',
      'Inside a steamy canteen on a storm-battered rig, workers play cards while the coffee slides slowly across the table. No readable text or logo.',
      'A lone crane operator watches the floodlit sea from his cab, a whale surfacing briefly in the storm below. No readable text or logo.',
    ]),
    dir('Cold Checkpoint Night', 'remote border post at night', 'cold-checkpoint', {
      aesthetic: 'Cold checkpoint night: a small barrier post on an empty frozen road, painted in graphic ink and flat color with one lamp and long shadows.',
      subject_treatment: "Place the prompt's subject at a remote nighttime road barrier, keeping it clear under a single lamp.",
      color_and_tone: 'Ink black, cold blue snow and a single pool of sickly yellow lamplight.',
      lighting_and_shadow: 'One lamp, long hard shadows and the dark forest beyond the barrier.',
      texture_and_material: 'Striped barrier pole, frosted booth window, snowy road and heavy coats.',
      camera_and_composition: 'Road vanishing into darkness, barrier and booth small in the lamplight.',
      atmosphere_and_mood: 'Tense, bored and suspicious, waiting all night for headlights.',
      rendering_and_quality: 'Graphic ink illustration with flat color and crisp shadows.',
      key_features: 'remote barrier post; single lamp; frozen road; long shadows',
    }, ['national flags', 'readable signs'], [
      'A guard in a heavy coat raises the barrier for a lone cyclist carrying a Christmas tree across the frozen border at midnight. No readable text or logo.',
      'Two guards on opposite sides of a barrier share a thermos across the pole because nobody has driven by in four days. No readable text or logo.',
      'Headlights appear far down a black frozen road and the checkpoint lamp flickers as they approach. No readable text or logo.',
    ]),
    dir('Rooftop Surveillance Night', 'urban night recon', 'rooftop-surveillance', {
      aesthetic: 'Rooftop surveillance night: a lone observer watching a rain-slick city from rooftops, painted in noir gouache with neon reflections and deep silhouettes.',
      subject_treatment: "Place the prompt's subject on a nighttime rooftop above a city, keeping it clear as a strong silhouette.",
      color_and_tone: 'Inky blues and blacks with neon magenta and teal reflections on wet surfaces.',
      lighting_and_shadow: 'City glow from below, rim light on the silhouette and deep rooftop shadow.',
      texture_and_material: 'Wet roof tar, rain, water tanks, antennas and binocular glass.',
      camera_and_composition: 'Figure on a roof edge with the city spread below, strong diagonals.',
      atmosphere_and_mood: 'Patient, watchful and alone, the city never notices.',
      rendering_and_quality: 'Noir gouache painting with crisp silhouettes and glowing reflections.',
      key_features: 'rooftop silhouette; rain-slick city below; neon reflections; binoculars',
    }, ['daylight', 'readable signs'], [
      'An observer on a rooftop watches the same lit window across the street for the third night, and tonight the window watches back. No readable text or logo.',
      'A surveillance agent eats noodles on a wet rooftop while a pigeon shares her ledge and her binoculars. No readable text or logo.',
      'Rain streams off the brim of a lone watcher\'s hat as she looks down at a parade of umbrellas in the neon street. No readable text or logo.',
    ]),
    dir('Surveyor Expedition Plates', 'lone survey expedition art', 'survey-plates', {
      aesthetic: 'Surveyor expedition plates: a lone surveyor mapping wild frontier land, rendered like hand-colored expedition plates with fine line and pale washes.',
      subject_treatment: "Show the prompt's subject as part of a lonely surveying expedition scene, keeping it clear in fine line and pale wash.",
      color_and_tone: 'Pale watercolor washes over sepia line on cream paper, restrained earth tones.',
      lighting_and_shadow: 'Soft even light with fine hatching for shadow in the landscape.',
      texture_and_material: 'Fine engraved-style lines, pale washes, tripod instruments and canvas tents.',
      camera_and_composition: 'Wide landscape views with the surveyor small beside instruments.',
      atmosphere_and_mood: 'Curious, patient and solitary, measuring a world no one has mapped.',
      rendering_and_quality: 'Hand-colored plate illustration with delicate line and wash.',
      key_features: 'hand-colored plates; lone surveyor; tripod instruments; pale washes',
    }, ['photographic realism'], [
      "Setting up her theodolite on a cliff above a valley, a mapmaker spots a herd of unknown beasts grazing among giant ferns below. No readable text or logo.",
      'A lone mapmaker measures the height of a waterfall with a rope while a curious bear watches from the far bank. No readable text or logo.',
      "At the edge of a salt lake at dusk, one lantern and a tripod stand beside a canvas tent under a sky of pale stars. No readable text or logo.",
    ]),
    dir('Flooded-City Salvage Rower', 'lone salvage in drowned city', 'flooded-salvage', {
      aesthetic: 'Flooded-city salvage rower: a lone rower gliding between drowned towers, painted in soft green-grey watercolor with reflections and floating debris.',
      subject_treatment: "Place the prompt's subject in a drowned city, keeping it clear on still water among half-submerged buildings.",
      color_and_tone: 'Soft green-grey water, faded building colors and pale overcast sky.',
      lighting_and_shadow: 'Soft overcast light with long reflections and gentle shadows under arches.',
      texture_and_material: 'Still water, drifting debris, mossy facades, rusted signs without letters and wooden boats.',
      camera_and_composition: 'Low water-level views with buildings towering and reflections mirroring them.',
      atmosphere_and_mood: 'Melancholic, quiet and resourceful, living among the drowned.',
      rendering_and_quality: 'Soft watercolor painting with careful reflections and wet edges.',
      key_features: 'drowned towers; lone rower; still reflections; floating debris',
    }, ['readable signs', 'bright sunny tourism'], [
      'A salvager rows through the third floor of a drowned department store, mannequins standing waist-deep in the water around her. No readable text or logo.',
      'A lone rower ties her boat to a traffic light poking out of a flooded avenue and eats lunch on top of it. No readable text or logo.',
      "Down the aisle of a drowned cathedral a single boat glides over perfectly still water that mirrors every stained window. No readable text or logo.",
    ]),
    dir('Polar Sledge Haul', 'manhauling across ice', 'sledge-haul', {
      aesthetic: 'Polar sledge haul: a lone figure dragging a heavy sledge across endless pressure ice, rendered in stark black-and-white woodcut style with bold carved snow.',
      subject_treatment: "Put the prompt's subject into a solitary polar haul, keeping it clear as a bold shape against carved snow.",
      color_and_tone: 'Stark black and white with rare pale blue accents in the ice.',
      lighting_and_shadow: 'Harsh low sun rendered as carved white channels and solid black shadows.',
      texture_and_material: 'Carved relief lines, pressure ridges, frost-covered harness and wooden sledge.',
      camera_and_composition: 'Low horizon with the hauler leaning into a diagonal against the wind.',
      atmosphere_and_mood: 'Grueling, heroic and alone, every single step hard earned.',
      rendering_and_quality: 'Bold woodcut-style rendering with strong carved lines and contrast.',
      key_features: 'lone sledge hauler; pressure ice; woodcut contrast; diagonal struggle',
    }, ['color photography'], [
      'A lone explorer drags a sledge up a pressure ridge as tall as a house, her shadow stretching a hundred meters behind her. No readable text or logo.',
      'A hauler stops to share his last biscuit with a curious seal poking its head through a hole in the ice. No readable text or logo.',
      'An empty sledge sits on endless ice beside a single set of footprints that simply stop. No readable text or logo.',
    ]),
    dir('Volcano Observatory Vigil', 'lone volcano monitoring', 'volcano-observatory', {
      aesthetic: 'Volcano observatory vigil: a small monitoring station on the rim of an active volcano, painted in glowing oils with lava light and ash clouds.',
      subject_treatment: "Place the prompt's subject at a volcano observation post, keeping it clear against glowing lava light and ash.",
      color_and_tone: 'Glowing lava orange, ash grey, black rock and night sky violet.',
      lighting_and_shadow: 'Lava glow from below, silhouettes rimmed in orange and ash-dimmed stars.',
      texture_and_material: 'Black volcanic rock, heat-cracked instruments, ash layers and protective suits.',
      camera_and_composition: 'Station on a rim edge with the crater glow filling the lower frame.',
      atmosphere_and_mood: 'Awestruck, dangerous and devoted, watching the earth breathe.',
      rendering_and_quality: 'Glowing oil painting with rich warm light and smoky depth.',
      key_features: 'crater rim station; lava glow; ash clouds; rimmed silhouettes',
    }, ['gore', 'daylight blue sky'], [
      "Sipping coffee on the crater rim, a scientist watches the lava lake below glow like a sunset turned upside down. No readable text or logo.",
      'A tiny observatory hut sits on the edge of a crater as the ash cloud above it flickers with lightning. No readable text or logo.',
      'A scientist lowers a sensor on a long cable toward the lava, the cable glowing red where it nears the surface. No readable text or logo.',
    ]),
    dir('Lighthouse Relief Keeper', 'isolated lighthouse keeping', 'lighthouse-keeper', {
      aesthetic: 'Lighthouse relief keeper: a lone keeper on a wave-battered rock lighthouse, painted in maritime oils with rotating beam and heavy seas.',
      subject_treatment: "Place the prompt's subject on or near a lonely rock lighthouse, keeping it clear in the sweep of the beam.",
      color_and_tone: 'Slate grey seas, white foam, warm lamp gold and stormy indigo sky.',
      lighting_and_shadow: 'Rotating beam slicing the dark, lamp glow from windows and stormy rim light.',
      texture_and_material: 'Wet granite, brass lens, whitewashed tower walls and oilskin coats.',
      camera_and_composition: 'Tower on a rock with waves exploding around its base, beam across the sky.',
      atmosphere_and_mood: 'Steadfast, lonely and romantic, keeping the light alive.',
      rendering_and_quality: 'Classic maritime oil painting with dramatic spray and glow.',
      key_features: 'rock lighthouse; sweeping beam; exploding waves; lone keeper',
    }, ['calm tropical beach'], [
      'A keeper polishes the giant lens by hand while a storm hurls waves over the gallery rail outside. No readable text or logo.',
      'The relief boat arrives after two months and the keeper waves from the rock holding a cake he baked for the crew. No readable text or logo.',
      "Sweeping across a night sea, the great beam briefly catches a ship that is not on any chart. No readable text or logo.",
    ]),
    dir('Nomad Radio Caravan', 'lone steppe radio caravan', 'nomad-radio', {
      aesthetic: 'Nomad radio caravan: a lone traveler with a camel or horse carrying radio gear across a vast steppe, rendered in flat gouache with wide skies and tiny figures.',
      subject_treatment: "Place the prompt's subject on a vast steppe journey, keeping it clear as a small figure under a huge sky.",
      color_and_tone: 'Golden grass, dusty ochre, deep blue sky and white clouds.',
      lighting_and_shadow: 'Clear afternoon light with long soft shadows across the grass.',
      texture_and_material: 'Flat gouache grass, felt saddlebags, wooden antenna poles and dust.',
      camera_and_composition: 'Very low horizon with sky taking most of the frame.',
      atmosphere_and_mood: 'Free, solitary and wide open, a voice crossing empty land.',
      rendering_and_quality: 'Flat graphic gouache painting with crisp shapes and clean color.',
      key_features: 'vast steppe; tiny traveler; radio antenna; enormous sky',
    }, ['city skyline'], [
      "Raising a tall antenna beside her horse on an endless steppe, a traveler listens to a voice singing from somewhere across the grass. No readable text or logo.",
      'A radio caravan of three camels crosses the steppe while a lone eagle follows the antenna like it is a friend. No readable text or logo.',
      'At dusk a traveler sits by a tiny fire with a crackling radio, the only light for a hundred miles. No readable text or logo.',
    ]),
  ],
};

export default spec;
