import type { Spec } from '../tools/apply';
import { au } from './_authors';

// Shojo, magical girl and visionary classics, author pass: each preset names its mangaka or studio
// adaptation and the concrete marks of that hand. Existing briefs stay; they are original.
const manga =
  'Delicate shojo manga pen line with screentone gradients, sparkle tones, floral accents and clean white paper.';
const mangaRender =
  'Refined shojo manga illustration with hand-drawn romantic detail and expressive emotional close-ups.';
const tv =
  'Contemporary digital television cel with clean outlines, soft gradient highlights and detailed painted backgrounds.';
const cel90 =
  'Late analog hand-painted cel over painted backgrounds, with soft film grain and gentle cel edge softness.';

const spec: Spec = {
  pack: 'pack_13',
  category: '3. Shojo, Magical Girl & Visionary Classics',
  updates: Object.fromEntries([
    au('SP05-013', 'Mohiro Kitoh - Psychological Biomech Drama', {
      look: 'Mohiro Kitoh manga look as in Bokurano and Narutaru: simple plain faces and thin clean lines set against enormous eerie biomechanical giants, cold detachment and psychological dread.',
      subject:
        'draw people with Kitoh simplicity, plain small faces, thin bodies and ordinary clothes, dwarfed by vast strange machines.',
      color: 'Pale overcast greys, cold white and a single dull red in black-and-white manga tone.',
      light: 'Flat pale overcast light that makes the giants look uncanny and indifferent.',
      texture: 'Thin clean pen lines, sparse screentone and huge empty sky spaces.',
      camera: 'Tiny figures beneath colossal silent machines in wide empty cityscapes.',
      mood: 'cold psychological dread',
      render: 'Unsettling minimal manga illustration with colossal biomechanical scale.',
      key: 'Mohiro Kitoh plain faces; colossal biomech giants; cold dread; empty skies',
    }),
    au('SP05-162', 'Sailor Moon - Moonlit Ribbon Justice', {
      look: 'Toei Sailor Moon anime look (1992) with Kazuko Tadano designs: long-legged nineties magical girls, sparkling transformation ribbons, moonlit Tokyo rooftops and pastel glittering cel.',
      subject:
        'draw people with Tadano nineties designs, long slender legs, big shining eyes and sailor-collar or ribboned costumes.',
      color: 'Pastel pink, moon gold, navy night and sparkling white.',
      light: 'Moonlight halos, sparkle bursts and transformation glows.',
      texture: cel90,
      camera: 'Transformation spins and heroic rooftop poses under the moon.',
      mood: 'sparkling moonlit justice',
      render: 'Glittering early-1990s Toei magical girl frame with moonlit sparkle.',
      key: 'Sailor Moon nineties cel; Tadano designs; ribbons; moonlit rooftops',
      avoid: ['blonde twin buns with a crescent moon tiara', 'existing franchise characters'],
    }),
    au('SP05-168', 'Neon Genesis Evangelion - Red Alert Psychological Collapse', {
      look: 'Gainax Neon Genesis Evangelion TV look (1995): Yoshiyuki Sadamoto designs, long static shots, red emergency lighting, power lines and psychological collapse into stark abstract frames.',
      subject:
        'draw people with Sadamoto designs, slim bodies, big anxious eyes and plain clothes or plugsuit-like suits.',
      color: 'Emergency red, sunset orange, purple and cold grey.',
      light: 'Red emergency light and harsh sunset silhouettes.',
      texture: cel90,
      camera: 'Long static shots, power lines and stark silhouettes.',
      mood: 'anxious psychological collapse',
      render: 'Iconic mid-1990s Gainax frame with psychological stillness.',
      key: 'Evangelion red alerts; Sadamoto designs; long static shots; power lines',
      avoid: ['a purple and green horned biomech', 'existing franchise characters'],
    }),
    au('SP05-171', 'Slayers - Arcane Chaos Roadtrip', {
      look: 'J.C.Staff Slayers look (1995) with Rui Araizumi designs: bright nineties fantasy comedy, huge explosive spells, super-deformed gags and colorful roadside inns.',
      subject:
        'draw people with Araizumi designs, big eyes, wild hair, capes, shoulder pads and fantasy adventurer gear.',
      color: 'Bright red, spell gold, sky blue and forest green.',
      light: 'Explosive spell light and cheerful fantasy daylight.',
      texture: cel90,
      camera: 'Explosive comedic wides and super-deformed reaction shots.',
      mood: 'chaotic arcane comedy',
      render: 'Lively mid-1990s fantasy comedy television frame.',
      key: 'Slayers explosions; Araizumi designs; SD gags; nineties fantasy',
      avoid: [
        'a red-haired sorceress with shoulder spikes and a dragon slave spell',
        'existing franchise characters',
      ],
    }),
    au('SP05-172', 'The Vision of Escaflowne Film - Tarot Mecha Fantasy', {
      look: 'BONES and Sunrise Escaflowne film look (2000): darker painterly fantasy, engraved armored guymelefs, tarot symbolism and moody candlelit medieval sky kingdoms.',
      subject:
        'draw people with sharper film designs, long faces, long hair and medieval armor or robes.',
      color: 'Deep crimson, brass, midnight blue and candle gold.',
      light: 'Candlelit interiors and moody dusk skies.',
      texture: 'Painterly film cel with engraved mechanical detail.',
      camera: 'Moody cathedral compositions and soaring sky battles.',
      mood: 'dark tarot destiny',
      render: 'Painterly 2000 feature frame with engraved mecha fantasy.',
      key: 'Escaflowne film; engraved guymelefs; tarot symbolism; candlelight',
      avoid: ['a white dragon-shaped mech with a sword', 'existing franchise characters'],
    }),
    au('SP05-176', 'CLAMP Rayearth - Jewel Armor Quest', {
      look: 'CLAMP Magic Knight Rayearth manga art: elegant elongated figures, huge luminous eyes, ornate jeweled armor, flowing hair and decorative fantasy framing.',
      subject:
        'draw people with CLAMP proportions, very long limbs, huge luminous eyes, flowing hair and ornate jeweled armor.',
      color: 'Ruby, sapphire, emerald and gold with soft pastel washes.',
      light: 'Gem light and soft decorative glows.',
      texture: manga,
      camera: 'Elegant vertical compositions and ornate framing.',
      mood: 'ornate heroic quest',
      render: mangaRender,
      key: 'CLAMP elongation; jeweled armor; luminous eyes; ornate framing',
    }),
    au('SP05-177', 'Martian Successor Nadesico - Cheerful Bridge-Deck Mecha', {
      look: 'Xebec Martian Successor Nadesico look (1996) with Keiji Goto designs: cheerful parody space opera, colorful bridge crews, super robot homage and nineties comedy.',
      subject:
        'draw people with Goto designs, big bright eyes, colorful hair and crisp starship uniforms.',
      color: 'Bright bridge white, mecha pink, navy space and yellow.',
      light: 'Bright bridge lighting and explosion flashes.',
      texture: cel90,
      camera: 'Crowded bridge compositions and mecha battle wides.',
      mood: 'cheerful parody spirit',
      render: 'Bright mid-1990s space comedy television frame.',
      key: 'Nadesico bridge crew; Keiji Goto designs; parody mecha; nineties comedy',
    }),
    au('SP05-178', 'Yuzo Takada - Mythic Tokyo Purge', {
      look: 'Yuzo Takada Blue Seed look: nineties Japanese mythology horror-action in Tokyo, plant-like monsters, shrine maidens and soft rounded Takada character designs.',
      subject:
        'draw people with Takada designs, round faces, big eyes, work uniforms and shrine clothes.',
      color: 'Monster green, blood-red accents, Tokyo grey and shrine white.',
      light: 'Eerie green monster glow and city night lights.',
      texture: cel90,
      camera: 'Monster reveals in Tokyo streets and shrine interiors.',
      mood: 'mythic urban horror',
      render: 'Mid-1990s horror-action television frame.',
      key: 'Yuzo Takada designs; Japanese myth; plant monsters; Tokyo',
    }),
    au('SP05-019', 'Yoshitoshi ABe - Wired Existential Glitch', {
      look: 'Yoshitoshi ABe illustration look as in his art books: soft thin pencil-like lines, washed-out pastel color, power lines and quiet melancholy figures dissolving into digital noise.',
      subject:
        'draw people with ABe designs, small quiet faces, short hair and plain clothes, rendered with soft thin lines.',
      color: 'Washed-out pastel, power-line grey, faint pink and digital cyan.',
      light: 'Pale dusk light with glitch artifacts.',
      texture: 'Soft pencil-like lines, watercolor washes and digital noise.',
      camera: 'Lonely figures under power lines and empty skies.',
      mood: 'quiet existential drift',
      render: 'Soft melancholy digital illustration with glitch artifacts.',
      key: 'Yoshitoshi ABe soft line; power lines; pastel melancholy; glitch',
    }),
    au('SP05-020', 'Kazuki Takahashi - Dream Card Enchanter', {
      look: 'Kazuki Takahashi manga look: sharp angular faces, spiky dramatic hair, intense card duels and colossal original monsters summoned from glowing cards.',
      subject:
        'draw people with Takahashi designs, angular jaws, intense eyes, spiky hair and dramatic coats.',
      color: 'Dramatic purple, gold, black and glowing card light.',
      light: 'Glowing card light and dramatic backlit summons.',
      texture: 'Sharp inked lines, screentone and dramatic effect lines.',
      camera: 'Low dramatic angles with giant summoned creatures.',
      mood: 'dramatic summoning intensity',
      render: 'Dramatic card-battle manga illustration.',
      key: 'Kazuki Takahashi angles; spiky hair; card summons; giant monsters',
      avoid: [
        'existing card-game monsters',
        'millennium puzzle pendant',
        'existing franchise characters',
      ],
    }),
    au('SP05-183', 'Kimi ni Todoke - Shy Hallway Bloom', {
      look: 'Karuho Shiina Kimi ni Todoke manga look: gentle sparkling shojo, soft flower-filled backgrounds, blushing shy faces and delicate lines.',
      subject:
        'draw people with Shiina designs, soft faces, long straight hair, big gentle eyes and simple clothes.',
      color: 'Soft pinks, sakura white and gentle pastel blue.',
      light: 'Soft glowing light with sparkles.',
      texture: manga,
      camera: 'Gentle close-ups and hallway compositions.',
      mood: 'shy blooming warmth',
      render: mangaRender,
      key: 'Karuho Shiina softness; blushing faces; flower backgrounds; sparkles',
    }),
    au('SP05-190', 'Ao Haru Ride - Clean Uniform Reunion Ache', {
      look: 'Io Sakisaka Ao Haru Ride manga look: clean crisp lines, powder-blue melancholy, handsome understated faces and bittersweet reunions.',
      subject:
        'draw people with Sakisaka designs, clean faces, neat hair and simple uniforms or casual clothes.',
      color: 'Powder blue, soft grey and gentle white.',
      light: 'Soft dusk light with gentle glow.',
      texture: manga,
      camera: 'Quiet reunion compositions and close-ups.',
      mood: 'bittersweet reunion ache',
      render: mangaRender,
      key: 'Io Sakisaka clean line; powder blue; bittersweet reunions',
    }),
    au('SP05-181', 'Fruits Basket - Zodiac Warmth and Grief', {
      look: 'Natsuki Takaya Fruits Basket manga look: gentle rounded faces with big eyes, soft sad smiles, zodiac animal motifs and warm grief.',
      subject:
        'draw people with Takaya designs, round faces, big expressive eyes and simple cozy clothes.',
      color: 'Warm peach, soft green, gentle brown and pastel.',
      light: 'Soft warm household light.',
      texture: manga,
      camera: 'Warm family compositions and tearful close-ups.',
      mood: 'warm tender grief',
      render: mangaRender,
      key: 'Natsuki Takaya warmth; zodiac motifs; soft sad smiles',
      avoid: [
        'a girl with long brown hair and a pink hat among zodiac boys',
        'existing franchise characters',
      ],
    }),
    au('SP05-182', 'Nana - Black-Lace Apartment Heartbreak', {
      look: 'Ai Yazawa Nana manga look: fashion-illustration elegance, long slender bodies, punk and Vivienne-style fashion, smoky apartments and heartbreak.',
      subject:
        'draw people with Yazawa designs, tall slender bodies, long legs, heavy eyeliner and fashionable punk outfits.',
      color: 'Black ink with grey tone and occasional crimson.',
      light: 'Smoky apartment light and night city glow.',
      texture: manga,
      camera: 'Fashion-editorial compositions and emotional close-ups.',
      mood: 'aching punk heartbreak',
      render: mangaRender,
      key: 'Ai Yazawa fashion elegance; punk; smoky apartments; heartbreak',
      avoid: [
        'a punk singer with a spiked choker and black lipstick named character',
        'existing franchise characters',
      ],
    }),
    au('SP05-184', 'Ouran High School Host Club - Rose-Cloud Flirt Theater', {
      look: 'Bisco Hatori Ouran manga look: sparkling bishonen, rose clouds, elegant academy salons and exaggerated comedic reactions.',
      subject: 'draw people with Hatori designs, elegant faces, sparkling eyes and tailored suits.',
      color: 'Rose pink, gold, white and pastel.',
      light: 'Sparkling glow and rose light.',
      texture: manga,
      camera: 'Posed salon compositions and comedy panels.',
      mood: 'flirty comedic theater',
      render: mangaRender,
      key: 'Bisco Hatori sparkle; rose clouds; bishonen; comedy',
    }),
    au('SP05-185', 'Paradise Kiss - Runway Heartbreak Chic', {
      look: 'Ai Yazawa Paradise Kiss look: high fashion shojo, runway glamour, hand-made gowns, stylish designers and chic heartbreak.',
      subject: 'draw people with Yazawa designs, tall models, long legs and elaborate fashion.',
      color: 'Black, white, gold and runway pastels.',
      light: 'Runway spotlights and glamorous glow.',
      texture: manga,
      camera: 'Fashion runway compositions and close-ups.',
      mood: 'chic runway heartbreak',
      render: mangaRender,
      key: 'Paradise Kiss fashion; runway glamour; tall models; chic',
    }),
    au('SP05-186', 'Lovely Complex - Height-Gap Comedy Romance', {
      look: 'Aya Nakahara Lovely Complex look: Osaka comedy romance, exaggerated reactions, height-gap gags and bright energetic shojo.',
      subject: 'draw people with Nakahara designs, expressive comic faces and casual clothes.',
      color: 'Bright warm pastels and comedy colors.',
      light: 'Bright cheerful light.',
      texture: manga,
      camera: 'Comedic reaction panels and height-gap compositions.',
      mood: 'rowdy comic romance',
      render: mangaRender,
      key: 'Lovely Complex comedy; height gags; energetic shojo',
    }),
    au('SP05-187', 'Skip Beat! - Revenge Idol Stardom Spark', {
      look: 'Yoshiki Nakamura Skip Beat! look: showbusiness shojo, dramatic acting transformations, dark grudge spirits comedy and glamorous idols.',
      subject:
        'draw people with Nakamura designs, expressive faces, stylish clothes and dramatic acting poses.',
      color: 'Glamour gold, dark grudge purple and pastel.',
      light: 'Spotlights and ominous comic auras.',
      texture: manga,
      camera: 'Dramatic acting compositions and comedy panels.',
      mood: 'fierce showbiz spark',
      render: mangaRender,
      key: 'Skip Beat showbiz; acting transformations; grudge comedy',
    }),
    au('SP05-188', 'Boys Over Flowers - Elite Campus Melodrama', {
      look: 'Yoko Kamio Boys Over Flowers look: nineties elite academy melodrama, curly-haired arrogant heirs, fashionable rich kids and fiery underdog romance.',
      subject:
        'draw people with Kamio designs, tall stylish figures, curly hair and luxury fashion.',
      color: 'Luxury gold, rose red and cream.',
      light: 'Glamorous gala light.',
      texture: manga,
      camera: 'Dramatic melodrama compositions.',
      mood: 'fiery elite melodrama',
      render: mangaRender,
      key: 'Yoko Kamio melodrama; elite academy; curly heirs; underdog',
    }),
    au('SP05-189', 'Orange - Sunset Regret Letter Drama', {
      look: 'Ichigo Takano Orange manga look: soft gentle lines, sunset orange light, letters from the future and bittersweet regret.',
      subject: 'draw people with Takano designs, gentle faces, simple clothes and quiet emotion.',
      color: 'Sunset orange, soft pink and dusk blue.',
      light: 'Warm sunset glow.',
      texture: manga,
      camera: 'Quiet sunset compositions.',
      mood: 'gentle regretful longing',
      render: mangaRender,
      key: 'Ichigo Takano soft line; sunset orange; regret; letters',
    }),
    au('SP05-191', 'Say I Love You - Night-Walk Intimacy', {
      look: 'Kanae Hazuki Say I Love You look: quiet intimate shojo romance, soft grey tones, night walks and tender closeness.',
      subject: 'draw people with Hazuki designs, soft faces, long hair and casual clothes.',
      color: 'Soft grey, night blue and warm lamp light.',
      light: 'Streetlamp glow at night.',
      texture: manga,
      camera: 'Intimate two-shots at night.',
      mood: 'quiet intimate tenderness',
      render: mangaRender,
      key: 'Kanae Hazuki intimacy; night walks; soft grey',
    }),
    au('SP05-192', 'Maid Sama! - Secret Uniform Double Life', {
      look: 'Hiro Fujiwara Maid Sama! look: comedic double-life romance, maid cafe frills, bold confident heroines and teasing rivals.',
      subject:
        'draw people with Fujiwara designs, confident faces, maid cafe outfits and uniforms.',
      color: 'Frilly pink, black and white and cafe pastels.',
      light: 'Bright cafe light.',
      texture: manga,
      camera: 'Comic double-life reveals.',
      mood: 'teasing comic romance',
      render: mangaRender,
      key: 'Maid Sama frills; double life; teasing romance',
    }),
    au('SP05-194', 'Rose of Versailles - Court Portrait Revolution', {
      look: 'Riyoko Ikeda Rose of Versailles manga art: baroque shojo, long-lashed sparkling eyes, voluminous golden hair, lavish court gowns and revolution.',
      subject:
        'draw people with Ikeda designs, sparkling star eyes, long lashes, voluminous hair and baroque clothing.',
      color: 'Rose, gold, royal blue and cream.',
      light: 'Sparkling glow and dramatic backlight.',
      texture: manga,
      camera: 'Baroque portrait compositions and revolutionary drama.',
      mood: 'passionate baroque drama',
      render: mangaRender,
      key: 'Riyoko Ikeda baroque; sparkling eyes; court gowns; revolution',
      avoid: [
        'a blonde commander in a white military uniform with epaulettes',
        'existing franchise characters',
      ],
    }),
    au('SP05-195', 'Neighborhood Story - Harajuku Handmade Romance', {
      look: 'Ai Yazawa Neighborhood Story look: nineties Harajuku handmade fashion, art school energy, colorful accessories and youthful romance.',
      subject: 'draw people with Yazawa designs, slender figures and handmade eclectic fashion.',
      color: 'Colorful handmade pastels and bright accents.',
      light: 'Bright Harajuku daylight.',
      texture: manga,
      camera: 'Fashion street compositions.',
      mood: 'playful handmade romance',
      render: mangaRender,
      key: 'Neighborhood Story Harajuku; handmade fashion; art school',
    }),
    au('SP05-196', 'Honey and Clover - Art-School Spring Ache', {
      look: 'Chica Umino Honey and Clover look: loose airy lines, art school life, spring breezes, bittersweet unrequited love and whimsical interludes.',
      subject:
        'draw people with Umino designs, loose lanky figures, messy hair and art-school clothes.',
      color: 'Soft spring pastels and clover green.',
      light: 'Airy spring light.',
      texture: manga,
      camera: 'Airy art-school compositions.',
      mood: 'bittersweet spring ache',
      render: mangaRender,
      key: 'Chica Umino airy line; art school; spring; unrequited love',
    }),
    au('SP05-197', 'Kamisama Kiss - Shrine Romance and Fox Familiar', {
      look: 'Julietta Suzuki Kamisama Kiss look: shrine romance, fox spirit familiars, flowing kimono, sakura and playful yokai.',
      subject: 'draw people with Suzuki designs, big eyes, flowing hair and kimono.',
      color: 'Sakura pink, shrine red and soft gold.',
      light: 'Soft shrine light with foxfire glows.',
      texture: manga,
      camera: 'Shrine compositions with spirits.',
      mood: 'playful shrine romance',
      render: mangaRender,
      key: 'Julietta Suzuki shrines; fox familiars; kimono; yokai',
      avoid: ['a silver-haired fox spirit with a purple kimono', 'existing franchise characters'],
    }),
    au('SP05-198', 'Princess Jellyfish - Jelly-Color Otaku Makeover', {
      look: 'Akiko Higashimura Princess Jellyfish look: otaku women comedy, jellyfish dresses, crude comic faces and dazzling makeovers.',
      subject:
        'draw people with Higashimura designs, crude comic faces, frumpy clothes and dazzling transformations.',
      color: 'Jelly translucent pastels and aquarium blue.',
      light: 'Aquarium glow and makeover sparkle.',
      texture: manga,
      camera: 'Comic reactions and makeover reveals.',
      mood: 'giddy otaku makeover',
      render: mangaRender,
      key: 'Higashimura comedy; jellyfish dresses; makeovers',
    }),
    au('SP05-200', 'Sukitte Ii na yo - Rainy Umbrella Confession', {
      look: 'Kanae Hazuki Sukitte Ii na yo anime look (Zexcs 2012): muted grey rainy romance, soft realistic designs and quiet confessions.',
      subject: 'draw people with soft designs, gentle faces, school or casual clothes.',
      color: 'Rainy grey, soft blue and warm skin.',
      light: 'Soft rainy daylight.',
      texture: tv,
      camera: 'Umbrella two-shots in rain.',
      mood: 'quiet rainy confession',
      render: 'Quiet rainy romance television frame.',
      key: 'Rainy romance; umbrellas; muted grey; confessions',
    }),
    au('SP05-193', 'Snow White with the Red Hair - Herbal Courtship Fantasy', {
      look: 'Sorata Akizuki Snow White with the Red Hair look: gentle court fantasy, vivid red hair, herbalist gardens and courteous romance.',
      subject: 'draw people with Akizuki designs, gentle faces, vivid red hair and court clothes.',
      color: 'Vivid red, herb green and cream.',
      light: 'Soft garden light.',
      texture: manga,
      camera: 'Herb garden compositions.',
      mood: 'gentle courteous romance',
      render: mangaRender,
      key: 'Akizuki court fantasy; red hair; herb gardens',
      avoid: ['a red-haired herbalist girl in an apron', 'existing franchise characters'],
    }),
    au('SP05-199', 'Yona of the Dawn Pierrot - Crimson Princess Resolve', {
      look: 'Studio Pierrot Yona of the Dawn anime look (2014): Korean-inspired fantasy kingdoms, vivid crimson hair, loyal dragon warriors and sweeping journeys.',
      subject:
        'draw people with modern shojo designs, vivid red hair, travel clothes and warriors.',
      color: 'Crimson, earth brown, sky blue and gold.',
      light: 'Warm dawn light and campfire glow.',
      texture: tv,
      camera: 'Sweeping journey wides and campfire scenes.',
      mood: 'resolute crimson journey',
      render: 'Polished Pierrot fantasy television frame.',
      key: 'Yona anime crimson hair; fantasy kingdoms; loyal warriors',
      avoid: ['a red-haired princess with a hairpin and bow', 'existing franchise characters'],
    }),
    au('SP05-047', 'Kazune Kawahara - Airy First-Love Tenderness', {
      look: 'Kazune Kawahara My Love Story look: sweet airy first-love comedy, huge gentle giant guys, tiny blushing partners and warm light.',
      subject:
        'draw people with Kawahara designs, contrasting body sizes, blushing faces and simple clothes.',
      color: 'Airy pastels, blossom pink and warm sky.',
      light: 'Soft warm spring light.',
      texture: manga,
      camera: 'Sweet two-shots under blossoms.',
      mood: 'airy first-love tenderness',
      render: mangaRender,
      key: 'Kazune Kawahara sweetness; gentle giants; blushing; blossoms',
    }),
    au('SP05-041', 'Keiko Takemiya - Ornate Palace Shojo', {
      look: 'Keiko Takemiya classic seventies shojo look: ornate European palaces, flowing hair, flowers, elaborate costumes and lyrical melodrama.',
      subject:
        'draw people with Takemiya designs, delicate faces, flowing hair and ornate period gowns.',
      color: 'Ornate gold, rose, ivory and palace blue.',
      light: 'Soft palace light and dramatic glow.',
      texture: manga,
      camera: 'Ornate palace compositions.',
      mood: 'lyrical ornate grandeur',
      render: mangaRender,
      key: 'Keiko Takemiya ornate; seventies shojo; palaces; flowing hair',
    }),
    au('SP05-042', 'Chiho Saito - Theatrical Duel Symbolism', {
      look: 'Chiho Saito manga look as in Revolutionary Girl Utena and Bride of Deimos: elegant elongated figures, roses, princely duelists and theatrical symbolism.',
      subject:
        'draw people with Saito designs, long elegant limbs, sharp lashes and princely uniforms.',
      color: 'Rose, black, white and gold.',
      light: 'Theatrical spotlight and petal glows.',
      texture: manga,
      camera: 'Symmetrical duel compositions.',
      mood: 'theatrical symbolic duel',
      render: mangaRender,
      key: 'Chiho Saito elegance; roses; princely duels; symbolism',
    }),
    au('SP05-043', 'Flying Witch J.C.Staff - Soft Healing Ensemble', {
      look: 'J.C.Staff Flying Witch look (2016): gentle rural witch life, soft pastel countryside, herb gardens and relaxed healing slice of life.',
      subject: 'draw people with soft gentle designs, relaxed faces and casual country clothes.',
      color: 'Soft green, sky blue and warm cream.',
      light: 'Gentle spring sunlight.',
      texture: tv,
      camera: 'Relaxed garden and countryside compositions.',
      mood: 'gentle healing calm',
      render: 'Soft relaxed slice-of-life television frame.',
      key: 'Flying Witch gentleness; herb gardens; rural calm',
    }),
    au('SP05-044', 'Moyoco Anno - Punk Romance Drama', {
      look: 'Moyoco Anno manga look as in Happy Mania and Sakuran: bold graphic fashion lines, sharp sexy josei heroines, punk energy and heartbreak.',
      subject: 'draw people with Anno designs, sharp eyes, bold lips and fashionable edgy clothes.',
      color: 'Black ink with bold fashion accents.',
      light: 'Nightlife light and rainy gloom.',
      texture: 'Bold graphic fashion lines and tone.',
      camera: 'Fashion-forward compositions.',
      mood: 'edgy punk romance',
      render: 'Bold graphic josei manga illustration.',
      key: 'Moyoco Anno bold line; josei; punk fashion; heartbreak',
    }),
    au('SP05-045', 'Kaguya-sama A-1 - Rose-Petal Comedy Club', {
      look: 'A-1 Pictures Kaguya-sama: Love Is War look (2019): theatrical mind-game comedy, dramatic narration staging, rose petals, dutch angles and gag reactions.',
      subject:
        'draw people with Aka Akasaka-derived designs, elegant faces, sharp eyes and school uniforms.',
      color: 'Dramatic red, rose pink and cool blue.',
      light: 'Dramatic spotlights and comic flashes.',
      texture: tv,
      camera: 'Theatrical dutch angles and gag cuts.',
      mood: 'theatrical comic scheming',
      render: 'Theatrical A-1 comedy frame.',
      key: 'Kaguya-sama theatrics; mind games; roses; gag reactions',
    }),
    au('SP05-046', 'Maquia P.A. Works - Luminous Letter Drama', {
      look: 'P.A. Works Maquia look (2018) by Mari Okada: luminous fantasy drama, woven cloth of memory, glowing light, tender farewells and painterly beauty.',
      subject:
        'draw people with Yuriko Ishii-derived designs, delicate faces and flowing fantasy clothes.',
      color: 'Luminous white, soft gold and pale blue.',
      light: 'Luminous glowing light and soft dusk.',
      texture: tv,
      camera: 'Emotional close-ups and luminous wides.',
      mood: 'luminous tender farewell',
      render: 'Luminous painterly P.A. Works feature frame.',
      key: 'Maquia luminosity; woven memories; farewells',
    }),
    au('SP05-050', 'A Sign of Affection Ajia-do - Cozy Sign-Language Romance', {
      look: 'Ajia-do A Sign of Affection look (2024) from suu Morishita: soft pastel romance, sign language hands, snowy cafes and gentle closeness.',
      subject: 'draw people with soft designs, expressive hands and cozy winter clothes.',
      color: 'Soft pastel pink, snow white and cafe warmth.',
      light: 'Soft cafe light and snowy glow.',
      texture: tv,
      camera: 'Close-ups on signing hands and gentle faces.',
      mood: 'cozy tender romance',
      render: 'Soft pastel romance television frame.',
      key: 'A Sign of Affection; signing hands; pastel romance; snow',
    }),
    au('SP05-048', 'Mizuho Kusanagi - Crimson Hair Quest Romance', {
      look: 'Mizuho Kusanagi Yona of the Dawn manga art: vivid crimson flowing hair, fierce resolve, beautiful warriors and dramatic fantasy panels.',
      subject: 'draw people with Kusanagi designs, flowing hair, fierce eyes and fantasy robes.',
      color: 'Crimson, ink black and gold accents.',
      light: 'Dramatic fire and dawn light.',
      texture: manga,
      camera: 'Dramatic cliff and battle compositions.',
      mood: 'fierce romantic resolve',
      render: mangaRender,
      key: 'Mizuho Kusanagi crimson hair; fierce resolve; fantasy',
    }),
    au('SP05-049', 'Kaori Yuki - Velvet Gothic Academy', {
      look: 'Kaori Yuki gothic manga look as in Angel Sanctuary and Godchild: ornate gothic fashion, angels and demons, lace, crosses and decadent melancholy.',
      subject:
        'draw people with Yuki designs, slender elegant bodies, ornate gothic fashion and dramatic hair.',
      color: 'Black ink with gothic tone and crimson accents.',
      light: 'Moonlit gothic light.',
      texture: 'Ornate fine line with lace and gothic ornament.',
      camera: 'Dramatic gothic compositions.',
      mood: 'decadent gothic melancholy',
      render: 'Ornate gothic manga illustration.',
      key: 'Kaori Yuki gothic; angels and demons; lace; decadence',
    }),
  ]),
};

export default spec;
