import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas revival and storybook illustration: nineteenth- and early twentieth-century
// illustration that looked back to the middle ages and to folk tales. Four originals get card
// briefs; sixteen new studies add jewel-detail painting, toy books, contraption drawings, Celtic
// revival plates, fairy painting, gilt deco plates, Slavic folktale frames, troll watercolors,
// decadent black line, revival illumination, troubadour painting, tapestry cartoons, gift-book
// plates, wood-engraved vignettes, nursery friezes and chapbook woodcuts. Names are descriptors,
// never artist names.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'storybook-revival', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'readable captions or lettering', 'existing fairy-tale film character designs', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original characters';

const spec: Spec = {
  pack: 'pack_23',
  category: '5. Revival & Storybook Illustration',
  updates: {
    'SP23-022': { briefs: [
      'Stepping through a shallow ford, a pale stag carries a whole sleeping forest in its antlers, owls and vines and tiny houses, drawn in assertive black masses and fine line against open paper. No readable text or logo.',
      'In dense black and white line, a huntswoman aims at a rabbit who is aiming a tiny crossbow right back at her. No readable text or logo.',
      'Among dark masses of leaves drawn in fine line, a garden gate stands half open, and beyond it the paper is left completely, unnervingly white. No readable text or logo.',
    ] },
    'SP23-023': { briefs: [
      'Riding a polar bear across a frozen sea under a sky of falling stars, a girl in a long patterned cloak searches for the palace east of the sun, drawn in elegant silhouettes and delicate highlights. No readable text or logo.',
      'Helping a long-eared winged stoat off a harbor ledge, a traveler discovers the creature has brought its entire extended family, all equally elegant and demanding. No readable text or logo.',
      'On a tall ornamental plate, a princess sleeps in a tower of briars while a thin silhouette of someone climbs the thorns toward her window. No readable text or logo.',
    ] },
    'SP23-024': { briefs: [
      'Poling a skiff through a flooded meadow at dusk, a boatman is followed by the gnarled roots of the willows, which have pulled themselves out of the bank and are wading after him. No readable text or logo.',
      'In sinuous pen lines and pale washes, a grumpy gnome is stuck head-first in a rabbit hole while the rabbit sits comfortably on his backside nibbling a dandelion leaf. No readable text or logo.',
      'Under a twisted oak drawn in nervous branching lines, a small girl stands very still while every root and knot in the bark has a face turned toward her. No readable text or logo.',
    ] },
    'SP23-025': { briefs: [
      "Kneeling at a small stone bridge, an old drover offers an apple slice to a pebble-shelled dormouse, and the whole bridge turns out to be the dormouse's enormous sleeping mother. No readable text or logo.",
      'In calm matte washes, a very tired troll sits on a milestone and soaks his feet in a river while a heron cleans his toenails. No readable text or logo.',
      'In muted folk washes, a lantern hangs by a field path at night, and beside it stands a scarecrow that was definitely in a different field this morning. No readable text or logo.',
    ] },
  },
  creates: [
    study('Pre-Raphaelite Jewel Detail', 'jewel-bright revival painting', 'jewel-detail', {
      aesthetic: 'Pre-Raphaelite jewel detail: mid-nineteenth-century revival painting with brilliant jewel colors on white ground, every leaf and flower painted sharp, long-haired figures in medieval dress.',
      subject_treatment: `${keep}; paint the subject with intense botanical detail and medieval costume in sharp focus everywhere.`,
      color_and_tone: 'Brilliant emerald, ruby, sapphire and copper hair on luminous white ground.',
      lighting_and_shadow: 'Clear daylight with little shadow, detail everywhere in focus.',
      texture_and_material: 'Fine glazed oil, crisp leaves, velvet and embroidered hems.',
      camera_and_composition: "Close vertical figure composition filled with plants, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with intense lyrical longing.',
      rendering_and_quality: "Hyper-sharp detail with jewel-like saturated color, kept consistent across the whole image.",
      key_features: 'jewel colors; sharp botanical detail; medieval dress; flowing hair',
    }, [], [
      'Floating down a river among sharp-painted flowers, a lady of the lake holds up a sword to a knight who has just realized he forgot how to swim. No readable text or logo.',
      'In jewel-bright detail, a copper-haired queen sits in a garden of lilies holding a hedgehog, which she believes is the most beautiful creature in the kingdom. No readable text or logo.',
      'Amid perfectly painted roses, a woman in green velvet looks into a well, and the reflection in the water is wearing a crown she does not have. No readable text or logo.',
    ]),
    study('Toy-Book Flat Color', 'victorian color toy book', 'toy-book', {
      aesthetic: 'Toy-book flat color: Victorian children\'s picture books printed from wood blocks in flat bold colors, strong outlines, decorative interiors and nursery-rhyme staging.',
      subject_treatment: `${keep}; stage the subject as a flat bold nursery scene with patterned interiors.`,
      color_and_tone: 'Flat brick red, deep blue, mustard and cream.',
      lighting_and_shadow: "Flat color areas with minimal black shading, kept consistent across the whole image.",
      texture_and_material: 'Wood-engraved black keylines, flat printed color, patterned wallpapers.',
      camera_and_composition: 'Stage-like interior or garden, figures in a row.',
      atmosphere_and_mood: 'Keep the requested mood with cheerful decorative order.',
      rendering_and_quality: "Bold clean flat printing with strong outlines, kept consistent across the whole image.",
      key_features: 'flat bold color; black keylines; patterned interiors; nursery staging',
    }, [], [
      'In a patterned Victorian parlor, three bears have come home to find a fox asleep in the baby\'s cradle, and the fox is wearing the baby\'s bonnet. No readable text or logo.',
      'In flat brick red and blue, a cat plays a fiddle while a cow tries to jump over a moon that has been hung too low on a string. No readable text or logo.',
      'In a bold toy-book nursery, the children are asleep and every doll on the shelf has turned its head to face the door. No readable text or logo.',
    ]),
    study('Contraption Ink Drawing', 'absurd machine line drawing', 'contraption', {
      aesthetic: 'Contraption ink drawing: Edwardian humorous line drawings of absurdly complicated machines built from string, pulleys, planks and kettles, operated by very serious gentlemen.',
      subject_treatment: `${keep}; involve the subject in a ridiculously elaborate machine of ropes, pulleys and planks.`,
      color_and_tone: 'Black ink with soft grey wash or pale tint.',
      lighting_and_shadow: "Light hatching and soft wash shadows, kept consistent across the whole image.",
      texture_and_material: 'Fine pen line, knotted string, planks and patched fabric.',
      camera_and_composition: 'Wide view showing the entire contraption and its operators.',
      atmosphere_and_mood: 'Keep the requested mood with deadpan absurd ingenuity.',
      rendering_and_quality: "Clear readable mechanism with careful comic detail, kept consistent across the whole image.",
      key_features: 'absurd machine; pulleys and strings; serious operators; fine pen line',
    }, [], [
      'Using a machine of ropes, pulleys, a bellows and eleven serious gentlemen, a small team attempts to wake a sleeping dragon by tickling its nose with a single feather. No readable text or logo.',
      "Built entirely to butter one slice of toast, a machine of planks, kettles, string and three pulleys whirs away while a very patient cat waits at the end of it. No readable text or logo.",
      'In a dim attic, an unmanned contraption of strings and pulleys is still running on its own, slowly winding a rope that disappears into a trunk. No readable text or logo.',
    ]),
    study('Celtic Revival Twilight Plate', 'celtic revival book illustration', 'celtic-revival', {
      aesthetic: 'Celtic revival twilight plate: early twentieth-century illustration of Irish legend, intricate jewel-like patterning, elongated pale figures, peacock blues and shadowy twilight.',
      subject_treatment: `${keep}; render the subject as elongated pale figures wrapped in intricate jewel-patterned clothing.`,
      color_and_tone: 'Peacock blue, deep violet, emerald and pale gold with inky blacks.',
      lighting_and_shadow: 'Dim twilight glow with pale faces lit from within.',
      texture_and_material: 'Dense decorative patterning like stained glass and beadwork.',
      camera_and_composition: 'Tall figures filling a vertical plate among patterned shapes.',
      atmosphere_and_mood: 'Keep the requested mood with eerie haunted romanticism.',
      rendering_and_quality: "Obsessively detailed patterns with clear pale figures, kept consistent across the whole image.",
      key_features: 'jewel patterning; elongated pale figures; peacock blue; twilight glow',
    }, [], [
      'Rising out of a twilight lake, a pale sea king wrapped in jeweled seaweed patterns offers a crown of shells to a fisherman who is too terrified to take it. No readable text or logo.',
      'In peacock-blue patterned robes, a solemn fairy queen tries to hold court while a goat eats the hem of her beaded cloak. No readable text or logo.',
      'At twilight, a pale bride in a patterned veil stands at a crossroads, and her long veil trails into the ground like roots. No readable text or logo.',
    ]),
    study('Victorian Fairy Painting', 'minute victorian fairy scenes', 'fairy-painting', {
      aesthetic: 'Victorian fairy painting: obsessively detailed paintings of tiny winged folk in grass and flowers, crowded scenes of fairy courts, feasts and quarrels at mouse scale.',
      subject_treatment: `${keep}; shrink the subject to fairy scale among giant grass blades, mushrooms and petals.`,
      color_and_tone: "Twilight greens, moonlit silver, glowing fairy gold, kept consistent across the whole image.",
      lighting_and_shadow: "Soft moonlight and small magical glows, kept consistent across the whole image.",
      texture_and_material: 'Fine oil detail, dewdrops, gauzy wings and petals.',
      camera_and_composition: "Low ground-level view crowded with tiny figures, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with uncanny miniature enchantment.',
      rendering_and_quality: "Crowded meticulous detail with readable focal figures, kept consistent across the whole image.",
      key_features: 'tiny winged folk; giant grass; crowded court; moonlit glow',
    }, [], [
      'Deep in moonlit grass, an entire fairy army rides into battle on field mice against a single enormous and very confused garden snail. No readable text or logo.',
      'Among giant clover leaves, a fairy court holds a trial for a bumblebee accused of eating the queen\'s flower, and the bee has hired a beetle lawyer. No readable text or logo.',
      'Under a mushroom in the moonlight, a crowd of tiny fairies gathers silently around a human baby shoe that has been left in the grass. No readable text or logo.',
    ]),
    study('Gilt Deco Fairy Plate', 'luxurious stenciled deco fairy plate', 'deco-fairy', {
      aesthetic: 'Gilt deco fairy plate: luxurious 1910s gift-book plates with stenciled jewel colors, gold outlines, exotic palaces and fantastic creatures in stylized deco elegance.',
      subject_treatment: `${keep}; render the subject in elegant stylized shapes outlined in gold with stenciled color.`,
      color_and_tone: 'Deep turquoise, saffron, rose and black with gold outlines.',
      lighting_and_shadow: "Flat stylized with gentle glow, kept consistent across the whole image.",
      texture_and_material: 'Stenciled pigment, gold ink lines and soft paper.',
      camera_and_composition: 'Elegant centered figure framed by stylized palace forms.',
      atmosphere_and_mood: 'Keep the requested mood with opulent dreamy luxury.',
      rendering_and_quality: "Crisp elegant shapes with rich flat color, kept consistent across the whole image.",
      key_features: 'gold outlines; stenciled jewel color; stylized palaces; deco elegance',
    }, [], [
      'Before a turquoise palace outlined in gold, a sultana of the sea rides a giant seahorse through the night sky, her veil turning into a comet tail. No readable text or logo.',
      'In gold-outlined saffron and rose, a very elegant peacock has refused to leave the royal throne, and the court has decided to simply work around it. No readable text or logo.',
      'Framed by stylized golden arches, a moon-pale dancer spins alone in an empty hall, and her shadow on the floor is dancing a different dance. No readable text or logo.',
    ]),
    study('Slavic Folktale Ornament Frame', 'russian folktale book illustration', 'folktale-frame', {
      aesthetic: 'Slavic folktale ornament frame: early twentieth-century folk-tale illustration with firm ink outlines, flat watercolor, birch-bark and embroidered borders framing each scene.',
      subject_treatment: `${keep}; frame the subject with ornamental folk borders of birch, flowers and carved wood.`,
      color_and_tone: 'Rich red, forest green, gold and snow white flat washes.',
      lighting_and_shadow: "Flat with light wash shading, kept consistent across the whole image.",
      texture_and_material: 'Firm ink outline, flat watercolor, embroidered and carved motifs.',
      camera_and_composition: 'Scene inside a decorative border frame with corner motifs.',
      atmosphere_and_mood: 'Keep the requested mood with folk-tale wonder and menace.',
      rendering_and_quality: 'Clear outline and flat color with rich ornament.',
      key_features: 'ornamental folk border; ink outline; flat watercolor; birch and flowers',
    }, [], [
      'Inside an ornamental folk border, a witch\'s hut on giant chicken legs chases a girl through a snowy birch forest, its door flapping open like a mouth. No readable text or logo.',
      'Framed by carved wooden flowers, a firebird has landed in a tsar\'s garden and is eating the golden apples one by one while the guards sleep. No readable text or logo.',
      'Within a birch-bark border, a gaunt immortal sorcerer counts gold in a dark castle, while behind him a small needle glints inside an egg. No readable text or logo.',
    ]),
    study('Mossy Troll Forest Watercolor', 'nordic troll forest illustration', 'troll-forest', {
      aesthetic: 'Mossy troll forest watercolor: Nordic folk-tale illustration with huge moss-covered trolls in misty pine forests, muted earthy watercolor and tiny human figures.',
      subject_treatment: `${keep}; place huge mossy troll-like forms in a misty pine forest with tiny figures for scale.`,
      color_and_tone: 'Moss green, bark brown, fog grey and pale birch white.',
      lighting_and_shadow: "Soft diffuse forest light and mist, kept consistent across the whole image.",
      texture_and_material: 'Muted watercolor washes, pencil lines and mossy textures.',
      camera_and_composition: 'Towering forms among pines with small travelers below.',
      atmosphere_and_mood: 'Keep the requested mood with ancient quiet wilderness.',
      rendering_and_quality: "Soft atmospheric wash with clear scale contrast, kept consistent across the whole image.",
      key_features: 'moss-covered giants; misty pines; tiny travelers; muted watercolor',
    }, [], [
      'In a misty pine forest, a troll so old and mossy that trees grow on his shoulders lifts his head as a tiny princess walks fearlessly toward him. No readable text or logo.',
      'Three enormous trolls share one eye between them and are arguing about whose turn it is, while a small boy hides behind a mossy rock. No readable text or logo.',
      'Deep in foggy woods, a traveler sits down to rest on a mossy boulder, not noticing the boulder has two slowly opening eyes. No readable text or logo.',
    ]),
    study('Decadent Black-Line Illustration', 'fin-de-siècle black ink illustration', 'black-line', {
      aesthetic: 'Decadent black-line illustration: fin-de-siècle pen drawing of pure black masses and fine hairlines, sinuous figures, peacock patterns and elegant sinister wit.',
      subject_treatment: `${keep}; render the subject in stark black shapes and hairline detail with sinuous elegance.`,
      color_and_tone: "Pure black ink and white paper only, kept consistent across the whole image.",
      lighting_and_shadow: "No gradation; black and white masses only, kept consistent across the whole image.",
      texture_and_material: 'Solid black fills, hairlines, dotted patterns and white space.',
      camera_and_composition: 'Tall asymmetric composition with vast black or white areas.',
      atmosphere_and_mood: 'Keep the requested mood with sly decadent menace.',
      rendering_and_quality: "Precise elegant line with dramatic black masses, kept consistent across the whole image.",
      key_features: 'pure black masses; hairlines; peacock patterns; sinuous figures',
    }, ['gray tones'], [
      'In a swirl of peacock feathers and pure black, a sinister queen admires herself in a mirror while her reflection quietly holds a knife behind its back. No readable text or logo.',
      'Drawn in hairlines and black masses, a very elegant cat in a long gown has invited four mice to dinner and is smiling far too much. No readable text or logo.',
      'Against a vast white page, a single black figure in a long cloak walks away, and its trailing shadow is full of tiny hairline eyes. No readable text or logo.',
    ]),
    study('Victorian Revival Illumination', 'nineteenth-century neo-gothic illumination', 'revival-illumination', {
      aesthetic: 'Victorian revival illumination: nineteenth-century chromolithographed imitations of medieval illumination, too perfect and too bright, with crisp gold, geometric borders and saturated color.',
      subject_treatment: `${keep}; frame the subject in immaculate neo-gothic borders printed in saturated color.`,
      color_and_tone: 'Saturated crimson, ultramarine, emerald and bright printed gold.',
      lighting_and_shadow: "Flat with slight printed modeling, kept consistent across the whole image.",
      texture_and_material: "Chromolithograph ink, printed gold and smooth paper, kept consistent across the whole image.",
      camera_and_composition: "Central panel with elaborate symmetric borders, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with earnest Victorian grandeur.',
      rendering_and_quality: "Crisp mechanical perfection of revival ornament, kept consistent across the whole image.",
      key_features: 'neo-gothic border; saturated chromolithograph; printed gold; symmetry',
    }, ['readable script'], [
      'Inside a perfectly symmetric neo-gothic border, a Victorian gentleman in full armor poses heroically beside a steam locomotive he has named after his horse. No readable text or logo.',
      'In saturated printed crimson and gold, a revival illumination shows a very round medieval cat, drawn by someone who has read about cats but never seen one. No readable text or logo.',
      'Framed in immaculate gothic tracery, a small oval shows a candlelit nursery where a Victorian child watches the painted border slowly growing into the room. No readable text or logo.',
    ]),
    study('Troubadour Romance Painting', 'romantic medieval genre painting', 'troubadour', {
      aesthetic: 'Troubadour romance painting: early nineteenth-century French painting of intimate medieval anecdotes, polished surfaces, gothic interiors and sentimental costumed moments.',
      subject_treatment: `${keep}; stage the subject as an intimate sentimental moment in a polished gothic interior.`,
      color_and_tone: 'Warm browns, deep reds and cool light through gothic windows.',
      lighting_and_shadow: "Soft window light with polished glowing surfaces, kept consistent across the whole image.",
      texture_and_material: 'Smooth porcelain-like oil finish, velvet and carved wood.',
      camera_and_composition: 'Small cabinet-scale interior with figures near a window.',
      atmosphere_and_mood: 'Keep the requested mood with tender romantic nostalgia.',
      rendering_and_quality: "Polished smooth finish with careful costume detail, kept consistent across the whole image.",
      key_features: 'gothic interior; window light; polished finish; sentimental anecdote',
    }, [], [
      'In a polished gothic chamber, a queen and a troubadour share a secret song by the window while the old king\'s parrot memorizes every word. No readable text or logo.',
      'By soft window light, a knight shows his lady the tiny dragon he has captured, which fits perfectly inside a teacup. No readable text or logo.',
      'In a quiet gothic interior, a young woman reads a letter by the window, and behind the tapestry on the wall a pair of shoes is visible. No readable text or logo.',
    ]),
    study('Tapestry Cartoon Drawing', 'full-size design drawing for weaving', 'tapestry-cartoon', {
      aesthetic: 'Tapestry cartoon drawing: large arts-and-crafts design drawings for tapestry and stained glass, chalk and wash figures in medieval dress, flat decorative foliage and squared-up grids.',
      subject_treatment: `${keep}; draw the subject as a large flat decorative design with faint squaring grid.`,
      color_and_tone: 'Muted chalk tones, sepia wash and touches of color notation.',
      lighting_and_shadow: "Flat with light chalk modeling, kept consistent across the whole image.",
      texture_and_material: 'Chalk, wash, visible grid lines and joined paper sheets.',
      camera_and_composition: "Large frontal composition with dense foliage background, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with calm craftsman ideals.',
      rendering_and_quality: "Clear design drawing with visible working marks, kept consistent across the whole image.",
      key_features: 'squaring grid; chalk and wash; flat foliage; medieval dress',
    }, ['readable color notes'], [
      'On a large chalk cartoon with a faint grid, a procession of knights rides through a forest of flat leaves toward a holy cup floating in the trees. No readable text or logo.',
      'In a squared-up design drawing, a pair of angels hold up a banner that the designer has left blank, and one angel is visibly bored. No readable text or logo.',
      'On joined sheets of chalk drawing, a woman in a flowing gown stands among flat foliage, and one area of the grid is left undrawn in the shape of a hand. No readable text or logo.',
    ]),
    study('Golden Age Gift-Book Plate', 'tipped-in color plate illustration', 'gift-book', {
      aesthetic: 'Golden age gift-book plate: tipped-in color plates from lavish 1900s illustrated books, soft muted watercolor over fine ink, cream margins and tissue-guard atmosphere.',
      subject_treatment: `${keep}; paint the subject as a single full-page plate with soft muted color over ink.`,
      color_and_tone: 'Muted sepia, olive, dusty rose and soft sky blue.',
      lighting_and_shadow: "Soft diffuse light with gentle washes, kept consistent across the whole image.",
      texture_and_material: 'Fine ink, soft watercolor, cream paper and plate mount.',
      camera_and_composition: 'Single plate mounted on a cream page with margin.',
      atmosphere_and_mood: 'Keep the requested mood with nostalgic enchanted calm.',
      rendering_and_quality: "Delicate refined plate with muted harmony, kept consistent across the whole image.",
      key_features: 'tipped-in plate; muted watercolor; fine ink; cream margins',
    }, ['readable captions'], [
      'On a tipped-in color plate, a mermaid princess trades her voice to a sea witch who keeps it in a small glowing jar among hundreds of others. No readable text or logo.',
      'In muted watercolor on a cream plate, an emperor proudly parades through a crowd, and a single small child in the crowd is the only one laughing and pointing. No readable text or logo.',
      'On a soft gift-book plate, a girl in a red cloak walks through a birch wood, and every trunk has a gray wolf standing directly behind it. No readable text or logo.',
    ]),
    study('Wood-Engraved Revival Vignette', 'victorian wood-engraved vignette', 'engraved-vignette', {
      aesthetic: 'Wood-engraved revival vignette: small Victorian end-grain wood engravings of country life, animals and legends with fine tonal lines fading into white paper.',
      subject_treatment: `${keep}; engrave the subject as a small vignette fading softly at its edges.`,
      color_and_tone: 'Black ink tones from deep black to fine silver grey.',
      lighting_and_shadow: 'Tonal engraving with fine white lines for light.',
      texture_and_material: 'End-grain engraving, fine tint lines and soft white edges.',
      camera_and_composition: 'Small vignette with no border, fading into the page.',
      atmosphere_and_mood: 'Keep the requested mood with quiet rustic observation.',
      rendering_and_quality: "Precise tonal engraving with gentle fade, kept consistent across the whole image.",
      key_features: 'end-grain engraving; fading vignette edge; fine tint lines; rustic detail',
    }, [], [
      'In a small fading vignette, a farmer ploughs his field while a giant green man made of hedgerow watches him from the edge of the woods. No readable text or logo.',
      'Engraved in fine silver lines, a hedgehog in a waistcoat tries to borrow an umbrella from a very unwilling crow. No readable text or logo.',
      'In a tiny wood engraving that fades into white, a churchyard yew tree stands in the fog with a lantern hung on it by no one. No readable text or logo.',
    ]),
    study('Nursery Frieze Procession', 'edwardian nursery wall frieze', 'nursery-frieze', {
      aesthetic: 'Nursery frieze procession: long Edwardian nursery wallpaper friezes with repeating processions of animals, soldiers and storybook characters in soft flat color.',
      subject_treatment: `${keep}; arrange the subject into a long repeating procession along a horizontal band.`,
      color_and_tone: 'Soft flat pastels, cream ground and gentle outlines.',
      lighting_and_shadow: "Flat with no shadow, kept consistent across the whole image.",
      texture_and_material: 'Printed wallpaper paper, soft outlines and repeat seams.',
      camera_and_composition: "Long horizontal band with evenly spaced figures, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with gentle childhood rhythm.',
      rendering_and_quality: "Clean repeating design with charming figures, kept consistent across the whole image.",
      key_features: 'horizontal procession; repeating figures; soft pastels; wallpaper',
    }, [], [
      'Along a pastel nursery frieze, a parade of wooden soldiers marches in perfect order, except for one soldier who has joined the ducks marching the other way. No readable text or logo.',
      'In a long wallpaper band, elephants march trunk to tail around the room, and the last elephant is holding the tail of the first one. No readable text or logo.',
      'On an old nursery frieze of repeating lambs, one lamb in the repeat is facing the wrong way and looking straight into the room. No readable text or logo.',
    ]),
    study('Chapbook Woodcut Tale', 'cheap popular chapbook print', 'chapbook', {
      aesthetic: 'Chapbook woodcut tale: crude cheap woodcuts from pocket-sized popular story pamphlets sold by peddlers, reused blocks, heavy ink and bold simple figures.',
      subject_treatment: `${keep}; cut the subject in crude bold woodcut shapes with naive proportions.`,
      color_and_tone: "Heavy black ink on rough grey-brown paper, kept consistent across the whole image.",
      lighting_and_shadow: "Crude hatching and solid black areas, kept consistent across the whole image.",
      texture_and_material: 'Worn cracked blocks, uneven inking and cheap paper.',
      camera_and_composition: "Small framed picture with one clear action, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with rowdy popular storytelling.',
      rendering_and_quality: "Crude charm with worn block cracks, kept consistent across the whole image.",
      key_features: 'crude woodcut; worn block cracks; cheap paper; naive figures',
    }, [], [
      'In a crude cracked woodcut, a giant-killer with a tiny sword stands on the chest of a huge giant who is, frankly, just having a nap. No readable text or logo.',
      'Printed from a worn block, a famous highwayman holds up a coach and discovers the only passenger is an extremely angry goose. No readable text or logo.',
      'On rough cheap paper, a crude woodcut shows a house at night with every window black except one, where a pale round face is pressed to the glass. No readable text or logo.',
    ]),
  ],
};

export default spec;
