import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Manga covers: volume, magazine and edition traditions named after their publishers, eras and
// artists. Cards invent original manga with exact titles.
const T = ['manga-cover'];
const P = { requestedText: true } as const;

const spec: Spec = {
  pack: 'pack_26',
  category: '3. Manga Covers',
  newCategory: { id: 'manga-covers' },
  updates: {},
  creates: [
    cr('Weekly Shonen Jump Tankobon Cover', 'manga volume cover', [...T, 'jump'], {
      ...P,
      look: 'Weekly Shonen Jump tankobon cover look: one bold hero bursting from a clean white background, dynamic foreshortened pose, bright flat color, a strong title logo band and volume number block.',
      subject:
        'show the subject as one dynamic hero bursting toward the viewer on a clean white cover.',
      color: 'Bright primary colors on clean white with a bold colored logo band.',
      light: 'Clean bright cover illustration light with crisp cel shading.',
      texture: 'Crisp digital manga color on glossy cover stock.',
      camera: 'Foreshortened hero pose filling the cover with a logo band at the top.',
      mood: 'bold shonen energy',
      render: 'Polished shonen volume cover illustration.',
      key: 'Jump tankobon; bursting hero; white background; logo band',
      avoid: ['existing shonen heroes'],
      briefs: [
        'A spiky-haired retired firefighter bursts toward the viewer with a flaming garden hose, foreshortened fist first, on a clean white volume cover of the invented shonen series "HOSE HERO" volume 12, title band set exact.',
        'A grinning grandmother swordswoman in a tracksuit leaps off the white cover with a baguette blade, invented series "BREAD BLADE" volume 3 with its bold logo band.',
        'A lone battered backpack flies across a clean white cover trailing sparks, invented adventure series "THE LONG ROAD" volume 27 with a bright red title band.',
      ],
    }),
    cr('Ribon Nineties Shojo Magazine Cover', 'shojo magazine cover', [...T, 'ribon'], {
      ...P,
      look: 'Nineties shojo magazine cover look as on Ribon and Nakayoshi: sparkling big-eyed heroines, pastel flowers, ribbons, hearts, cute stickers and busy decorative cover lines.',
      subject:
        'show the subject as sparkling big-eyed shojo characters framed by flowers, ribbons and hearts.',
      color: 'Candy pastel pink, mint, lavender and sparkle white.',
      light: 'Soft sparkling glow with star highlights.',
      texture: 'Glossy magazine print with sparkle screentone.',
      camera: 'Cheerful centered composition with decorative frames.',
      mood: 'sparkling sweet romance',
      render: 'Glossy nineties shojo magazine cover.',
      key: 'Ribon shojo cover; sparkles; ribbons; pastel flowers',
      briefs: [
        'Two sparkling big-eyed pastry chefs in their thirties hold a giant strawberry cake framed by ribbons, hearts and flowers on the cover of an invented nineties shojo magazine titled "SWEET RIBBON", cover lines set exact.',
        'A shy lighthouse keeper with enormous starry eyes blushes among pastel seashells on the invented magazine "PASTEL TIDE" with a cute sticker badge.',
        'A single pink ribbon curls around a sparkling moon on the cover of the invented magazine "HOSHI NO RIBBON" with glittering hearts all around.',
      ],
    }),
    cr('Garo Alternative Magazine Cover', 'alternative manga magazine cover', [...T, 'garo'], {
      ...P,
      look: 'Garo magazine cover look from Japanese alternative manga of the sixties and seventies: raw ink drawings, surreal everyday scenes, rough hand lettering and underground printing.',
      subject: 'draw the subject in raw expressive ink as a surreal everyday scene.',
      color: 'Limited muted print colors with black ink.',
      light: 'Flat printed light.',
      texture: 'Raw ink and rough underground printing.',
      camera: 'Single surreal ink scene with hand-lettered title.',
      mood: 'raw underground surrealism',
      render: 'Raw alternative manga magazine cover.',
      key: 'Garo raw ink; surreal everyday; underground print',
      briefs: [
        'A salaryman with a fish bowl for a head sits in a public bath while tiny ink boats sail around his knees, raw ink cover of an invented alternative magazine issue titled "ねじれ" hand-lettered exactly.',
        'A crooked tenement building grows legs and walks off at dusk, rough ink cover of the invented anthology "歩く家" with scratchy lettering.',
        'A single empty umbrella stands upright in a flooded rice field, alternative cover titled "雨男" in raw brush letters.',
      ],
    }),
    cr(
      'Hitoshi Ashinano - Watercolor Seinen Volume Cover',
      'seinen volume cover',
      [...T, 'ashinano'],
      {
        ...P,
        look: 'Hitoshi Ashinano Yokohama Kaidashi Kikou cover look: soft watercolor, quiet post-apocalyptic countryside, gentle figures, summer light and serene melancholy.',
        subject: 'paint the subject in soft watercolor within a quiet sunlit countryside.',
        color: 'Soft watercolor greens, sky blue and warm summer light.',
        light: 'Gentle summer sunlight and soft shadows.',
        texture: 'Watercolor washes and fine pencil line.',
        camera: 'Quiet landscape cover with small figures.',
        mood: 'serene quiet melancholy',
        render: 'Soft watercolor seinen volume cover.',
        key: 'Ashinano watercolor; quiet countryside; serenity',
        briefs: [
          'A woman runs a tiny roadside café beside a flooded highway where streetlamps poke out of the calm water, soft watercolor cover of the invented seinen volume "EVENING COFFEE AT THE END" with its title set exact.',
          'A lone cyclist rides past a giant overgrown statue in summer fields, quiet watercolor cover of the invented series "SLOW ROADS" volume 4.',
          'A single cup of coffee steams on a wooden railing above a still flooded valley, gentle cover titled "QUIET WATER" in small letters.',
        ],
      },
    ),
    cr('Kashihon Sixties Rental Manga Cover', 'rental manga cover', [...T, 'kashihon'], {
      ...P,
      look: 'Kashihon rental manga cover look from late-fifties and sixties Japan: dramatic gekiga illustrations, pulp thriller energy, bold painted color and hand-lettered titles on cheap hardcovers.',
      subject: 'paint the subject as dramatic pulp gekiga action on a cheap hardcover.',
      color: 'Bold pulp reds, blues and yellows, slightly faded.',
      light: 'Dramatic pulp lighting.',
      texture: 'Worn cheap hardcover with faded paint.',
      camera: 'Dramatic pulp scene with hand-lettered title.',
      mood: 'pulp dramatic thrill',
      render: 'Faded sixties rental manga cover.',
      key: 'Kashihon pulp; gekiga drama; faded hardcover',
      briefs: [
        'A trench-coated detective leaps from a moving streetcar with a pistol as a neon sign explodes behind him, faded pulp cover of an invented rental gekiga titled "夜の弾丸" with hand-lettered title set exact.',
        'A wandering swordsman stands in a snowstorm outside a lantern-lit inn, invented rental manga "雪の流れ者" on a worn hardcover.',
        'A single smoking pistol lies on a rain-wet street under a faded neon glow, pulp cover titled "最後の夜".',
      ],
    }),
    cr('Kadokawa Light Novel Cover', 'light novel cover', [...T, 'light-novel'], {
      ...P,
      look: 'Kadokawa light novel cover look: glossy anime illustration of a heroine or duo, detailed fantasy or school setting, soft bloom lighting and a long descriptive title block.',
      subject: 'illustrate the subject as a glossy anime cover character in a detailed setting.',
      color: 'Glossy saturated anime colors with soft bloom.',
      light: 'Soft bloom and sparkling highlights.',
      texture: 'Polished digital anime illustration.',
      camera: 'Character-forward cover with detailed background.',
      mood: 'bright escapist fantasy',
      render: 'Glossy light novel cover illustration.',
      key: 'Light novel gloss; heroine duo; long title block',
      briefs: [
        'A tired accountant reincarnated as a dragon’s bookkeeper sits on a treasure pile with glowing ledgers, glossy light novel cover with the long invented title "I WAS SUMMONED TO BALANCE A DRAGON’S TAXES" set exact.',
        'An elf baker and a demon customer share a glowing cream bun in a cozy shop, invented light novel "MY BAKERY IS OPEN TO DEMONS ON TUESDAYS" volume 2.',
        'A single glowing summoning circle burns on the floor of an empty office, invented light novel titled "OVERTIME IN ANOTHER WORLD".',
      ],
    }),
    cr(
      'Posuka Demizu - Painterly Picture-Book Manga Cover',
      'manga cover illustration',
      [...T, 'posuka-demizu'],
      {
        ...P,
        look: 'Posuka Demizu cover look: lush painterly color, whimsical storybook details, eerie beautiful forests and dense decorative illustration.',
        subject:
          'paint the subject in lush painterly storybook style surrounded by whimsical detail.',
        color: 'Lush jewel greens, deep reds and golden light.',
        light: 'Magical dappled painterly light.',
        texture: 'Lush digital painting with decorative detail.',
        camera: 'Dense whimsical storybook cover composition.',
        mood: 'eerie whimsical wonder',
        render: 'Lush painterly manga cover.',
        key: 'Posuka Demizu lush paint; storybook detail; eerie forests',
        briefs: [
          'An old clockmaker stands in a forest where every tree trunk is a grandfather clock and owls perch on the pendulums, lush painterly cover of the invented manga "THE CLOCKWOOD" with its title set exact.',
          'A gardener feeds a flower that has grown teeth in a lush greenhouse, invented manga "BLOOM" volume 5.',
          'A single glowing key hangs from a thorny branch in an eerie painted forest, cover titled "THE LOCKED WOOD".',
        ],
      },
    ),
    cr('Paru Itagaki - Sketchy Ink Volume Cover', 'manga volume cover', [...T, 'itagaki'], {
      ...P,
      look: 'Paru Itagaki cover look: sketchy expressive ink, anthropomorphic animals with human drama, loose paint and moody minimal color.',
      subject: 'draw the subject with sketchy expressive ink lines and moody minimal color.',
      color: 'Moody minimal color with ink black.',
      light: 'Moody soft light.',
      texture: 'Sketchy ink and loose paint.',
      camera: 'Close expressive character cover.',
      mood: 'moody expressive drama',
      render: 'Sketchy expressive manga cover.',
      key: 'Paru Itagaki sketchy ink; animal drama; moody',
      avoid: ['a grey wolf in a school uniform'],
      briefs: [
        'A nervous rabbit night-shift nurse clutches a clipboard as a tall owl doctor looms behind her, sketchy ink cover of the invented manga "NIGHT WARD" volume 1 with its title set exact.',
        'A lonely badger jazz pianist plays in a smoky bar, sketchy cover of the invented series "BLUE BADGER".',
        'On a sketchy ink floor scattered with torn petals and pawprints, a single crumpled love letter waits under a moody lamp, manga cover titled "PAWPRINTS" with its title set exact.',
      ],
    }),
    cr(
      'Seventies Shonen Magazine Pop Cover',
      'manga magazine cover',
      [...T, 'seventies-magazine'],
      {
        ...P,
        look: 'Seventies weekly manga magazine cover look: pop-art collage, bold graphic color blocks, photo and illustration mixed, radical design energy.',
        subject: 'collage the subject with pop-art color blocks and mixed photo and illustration.',
        color: 'Bold pop red, yellow and blue.',
        light: 'Flat pop light.',
        texture: 'Print collage and halftone.',
        camera: 'Radical graphic collage layout.',
        mood: 'radical pop energy',
        render: 'Seventies pop magazine cover.',
        key: 'Seventies magazine pop; collage; bold blocks',
        briefs: [
          'A giant photographed eye stares through a pop-art collage of boxers, rockets and baseball players on bold color blocks, seventies manga magazine cover titled "週刊ポップ" with cover lines set exact.',
          'A comic-book boxer punches through a photographed city skyline, radical cover of the invented magazine "少年ロケット".',
          'A single pop-art rocket rises through bold yellow and red color blocks past a photographed crowd of cheering fans, seventies magazine cover titled "未来" with cover lines set exact.',
        ],
      },
    ),
    cr('Doujinshi Convention Booklet Cover', 'fan booklet cover', [...T, 'doujinshi'], {
      ...P,
      look: 'Doujinshi convention booklet cover look: independent self-published comic covers, heartfelt fan illustration, spot colors, special paper and handmade print charm.',
      subject:
        'illustrate the subject as an independent booklet cover with spot colors and handmade charm.',
      color: 'Two or three spot colors on special paper.',
      light: 'Soft flat illustration light.',
      texture: 'Offset print on textured or pearl paper.',
      camera: 'Intimate cover illustration with small title.',
      mood: 'heartfelt indie charm',
      render: 'Handmade independent booklet cover.',
      key: 'Doujinshi spot colors; special paper; indie charm',
      briefs: [
        'Two original robot gardeners share a watering can under cherry blossoms in teal and pink spot inks on pearl paper, independent booklet cover titled "ROBOT GARDEN DIARY" with its title set exact.',
        'A sleepy dragon curls around a teapot on an indie booklet cover titled "TEA TIME DRAGON" in two spot colors.',
        'On textured cream paper printed in two spot inks, a single paper crane sits beside a tiny sleeping cat, independent booklet cover titled "PAPER WINGS" set exact.',
      ],
    }),
    cr('Kanzenban Deluxe Foil Cover', 'deluxe manga edition cover', [...T, 'kanzenban'], {
      ...P,
      look: 'Kanzenban deluxe manga edition cover look: minimal premium design, metallic foil, restrained new illustration, matte textured stock and elegant small typography.',
      subject:
        'present the subject as a restrained premium illustration with metallic foil accents.',
      color: 'Matte neutral stock with metallic gold or silver foil.',
      light: 'Soft premium light catching foil.',
      texture: 'Matte textured stock with foil stamping.',
      camera: 'Minimal centered premium composition.',
      mood: 'premium collector elegance',
      render: 'Minimal premium deluxe edition cover.',
      key: 'Kanzenban foil; matte stock; minimal premium',
      briefs: [
        'A single silver-foil sword rests across a matte midnight blue cover beside a small restrained portrait of an old swordswoman, deluxe edition of the invented manga "BLADE OF WINTER" with its title set exact.',
        'A gold-foil moon rises over a matte black cover in a deluxe edition titled "MOON RIVER" volume 1.',
        'A small silver foil feather drifts across matte ivory stock above a faint embossed moon, deluxe manga edition cover titled "FEATHER" set exact in elegant small type.',
      ],
    }),
    cr('Manga Artbook Gashu Cover', 'manga artbook cover', [...T, 'gashu'], {
      ...P,
      look: 'Manga artbook gashu cover look: large luxurious full-bleed illustration, painterly color, ornate character showcase and premium print.',
      subject: 'showcase the subject as a luxurious full-bleed painted illustration.',
      color: 'Rich luxurious painted color.',
      light: 'Luminous painterly light.',
      texture: 'Premium printed painting with fine detail.',
      camera: 'Full-bleed showcase composition.',
      mood: 'luxurious showcase wonder',
      render: 'Luxurious full-bleed artbook cover.',
      key: 'Gashu full-bleed; luxurious paint; showcase',
      briefs: [
        'A dozen original characters from an invented fantasy saga crowd a luminous full-bleed painting of a floating market at sunset, artbook cover titled "SKY MARKET ART WORKS" with its title set exact.',
        'An elegant witch reclines on a giant moth in a luxurious painted artbook cover titled "MOTHLIGHT".',
        'A single painted brush floats in a luminous sunset sky trailing ribbons of every color it has ever used, luxurious artbook cover titled "COLORS" set exact.',
      ],
    }),
    cr('Yonkoma Collection Cover', 'four-panel manga cover', [...T, 'yonkoma'], {
      ...P,
      look: 'Yonkoma four-panel manga collection cover look: cute simple chibi characters, flat pastel backgrounds, playful cover gags and rounded title lettering.',
      subject: 'draw the subject as cute simple chibi characters in a playful cover gag.',
      color: 'Flat pastel colors.',
      light: 'Flat cute light.',
      texture: 'Clean simple line and flat fills.',
      camera: 'Playful centered cover gag.',
      mood: 'playful cute comedy',
      render: 'Cute yonkoma collection cover.',
      key: 'Yonkoma chibi; pastel flats; cover gag',
      briefs: [
        'Three chibi office workers hide under one desk from a tiny angry printer on a pastel mint cover, four-panel collection titled "PRINTER PANIC" with rounded title set exact.',
        'A chibi cat café owner is buried under sleeping cats on a pastel pink yonkoma cover titled "CAT CAFE CHAOS".',
        'A single chibi rice ball with tiny arms waves hello from a pastel yellow cover while a chibi crow eyes it hungrily, yonkoma collection titled "RICE BALL DAYS" set exact.',
      ],
    }),
    cr('Eighties Horror Pocket Manga Cover', 'horror manga cover', [...T, 'horror-pocket'], {
      ...P,
      look: 'Eighties horror pocket manga cover look: lurid painted monsters, screaming faces, dripping titles, black backgrounds and cheap sensational printing.',
      subject: 'paint the subject as a lurid horror scene with screaming faces.',
      color: 'Lurid green, blood red and black.',
      light: 'Lurid monster lighting.',
      texture: 'Cheap glossy pocket print.',
      camera: 'Sensational close-up horror cover.',
      mood: 'lurid cheap scare',
      render: 'Lurid eighties horror pocket cover.',
      key: 'Horror pocket manga; lurid paint; dripping title',
      briefs: [
        'A schoolteacher screams as her own reflection crawls out of a bathroom mirror in lurid green paint on a black background, horror pocket manga cover titled "鏡の女" with dripping title set exact.',
        'A giant bloodshot eyeball rolls down a dark school corridor toward a terrified janitor on a lurid green and black cover titled "目玉廊下" with dripping letters set exact.',
        'A single dripping porcelain doll hangs by one arm from a rusty hook on a pitch black cover, horror pocket manga titled "人形" with a lurid red title.',
      ],
    }),
    cr('Webtoon Vertical Cover Thumbnail', 'webtoon cover', [...T, 'webtoon'], {
      ...P,
      look: 'Korean webtoon cover thumbnail look: tall vertical format, glossy full-color digital painting, dramatic character close-ups and bold stylized title logos.',
      subject: 'paint the subject as a glossy dramatic character close-up in tall vertical format.',
      color: 'Glossy saturated color with dramatic lighting.',
      light: 'Dramatic glossy highlights.',
      texture: 'Polished digital painting.',
      camera: 'Tall vertical close-up composition.',
      mood: 'dramatic glossy intrigue',
      render: 'Glossy webtoon cover thumbnail.',
      key: 'Webtoon vertical; glossy paint; dramatic close-up',
      briefs: [
        'A villainous duchess reborn as her own maid smirks over a teacup in a tall vertical glossy portrait, webtoon cover titled "THE MAID WHO WAS DUCHESS" with its stylized logo set exact.',
        'A tired hunter with glowing eyes stands in a flooded subway on a glossy webtoon cover titled "RANK ZERO".',
        'A single glowing sword stands buried in shattered marble in a tall vertical frame, dramatic webtoon cover titled "RETURN" with its stylized logo set exact.',
      ],
    }),
    cr('Josei Magazine Minimal Cover', 'josei magazine cover', [...T, 'josei'], {
      ...P,
      look: 'Josei manga magazine cover look as on Feel Young: fashionable minimal illustration of adult women, calm color fields, stylish composition and elegant cover lines.',
      subject: 'illustrate the subject as a fashionable adult woman in a calm minimal composition.',
      color: 'Calm muted color fields with one accent.',
      light: 'Soft calm light.',
      texture: 'Clean fashionable line and flat color.',
      camera: 'Stylish minimal cover composition.',
      mood: 'calm grown-up style',
      render: 'Fashionable minimal josei cover.',
      key: 'Josei minimal; fashionable women; calm color',
      briefs: [
        'A woman in her thirties reads on a balcony with a cat on her shoulder against a calm sage field, fashionable josei magazine cover titled "FEEL CALM" with cover lines set exact.',
        'A stylish architect sips coffee under a minimal red umbrella on a josei cover titled "AFTER WORK".',
        'A single pair of heels rests beside a potted plant on a muted cover titled "SUNDAY".',
      ],
    }),
    cr('Sports Manga Volume Cover', 'sports manga cover', [...T, 'sports-manga'], {
      ...P,
      look: 'Sports manga volume cover look: dynamic athletes mid-action, sweat and speed lines, team colors and bold energetic title design.',
      subject: 'show the subject as a dynamic athlete mid-action with sweat and speed lines.',
      color: 'Bold team colors and bright highlights.',
      light: 'Bright stadium light.',
      texture: 'Crisp manga color with speed lines.',
      camera: 'Dynamic mid-action cover composition.',
      mood: 'intense competitive drive',
      render: 'Dynamic sports manga cover.',
      key: 'Sports manga; mid-action; speed lines; team colors',
      briefs: [
        'A sixty-year-old ping pong player smashes a ball so hard the table cracks, sweat and speed lines flying, sports manga cover titled "SMASH GRANDPA" volume 8 with its title set exact.',
        'A goalkeeper made entirely of sweat and determination dives across a sports cover titled "LAST SAVE".',
        'A single cracked volleyball rests on a gleaming court under blazing stadium lights, speed lines radiating from it, sports manga cover titled "SPIKE" set exact.',
      ],
    }),
    cr('Osamu Tezuka Complete Works Cover', 'retro manga series cover', [...T, 'tezuka-zenshu'], {
      ...P,
      look: 'Osamu Tezuka Manga Complete Works cover look: clean retro series design, a single classic rounded cartoon illustration on a flat color field and consistent series framing.',
      subject: 'draw the subject as a classic rounded retro cartoon on a flat color field.',
      color: 'Flat retro color fields with clean white frame.',
      light: 'Flat retro print light.',
      texture: 'Clean retro print and line.',
      camera: 'Consistent series framing with centered illustration.',
      mood: 'classic retro charm',
      render: 'Retro series manga cover.',
      key: 'Tezuka zenshu; retro series frame; rounded cartoon',
      avoid: ['a boy robot with rocket boots', 'a white lion cub'],
      briefs: [
        'A rounded retro cartoon robot mailman salutes on a flat orange field inside a clean white series frame, complete-works cover of the invented classic "POSTBOT" volume 14 with its title set exact.',
        'A cartoon doctor with a big round nose rides a flying ambulance on a flat blue field, retro cover titled "SKY CLINIC".',
        'A single smiling cartoon star with little legs waves from a flat yellow field inside a clean white series frame, retro complete-works cover titled "STARLIGHT" set exact.',
      ],
    }),
    cr('Nineties Young Magazine Seinen Cover', 'seinen magazine cover', [...T, 'young-magazine'], {
      ...P,
      look: 'Nineties seinen magazine cover look: gritty urban illustration, photo backgrounds, delinquents and motorcycles, bold cover lines and street attitude.',
      subject: 'illustrate the subject with gritty urban attitude over photo backgrounds.',
      color: 'Gritty urban colors with bold red cover lines.',
      light: 'Night street light.',
      texture: 'Illustration over photo backgrounds.',
      camera: 'Street-attitude cover composition.',
      mood: 'gritty street attitude',
      render: 'Gritty nineties seinen magazine cover.',
      key: 'Seinen street attitude; photo backgrounds; bold cover lines',
      briefs: [
        'A delinquent florist in a long coat leans on a battered scooter full of roses against a photographed night street, seinen magazine cover titled "ヤング花屋" with cover lines set exact.',
        'A tough taxi driver glares from a rainy photo backdrop on the cover of an invented magazine "夜のドライバー".',
        'A single battered motorcycle helmet sits on a rain-wet photographed curb under a flickering streetlight, seinen magazine cover titled "走り屋" with bold cover lines.',
      ],
    }),
    cr('CoroCoro Kids Comic Cover', 'kids manga magazine cover', [...T, 'corocoro'], {
      ...P,
      look: 'CoroCoro Comic kids magazine cover look: loud crowded cover of cheering cartoon characters, bursts, explosions, bright primary colors and giveaway badges.',
      subject: 'show the subject as loud cheering cartoon characters in a crowded burst layout.',
      color: 'Loud primary red, yellow and blue.',
      light: 'Bright loud cartoon light.',
      texture: 'Glossy crowded magazine print.',
      camera: 'Crowded burst layout with badges.',
      mood: 'loud gleeful excitement',
      render: 'Loud crowded kids comic magazine cover.',
      key: 'CoroCoro loud cover; bursts; badges; primary colors',
      briefs: [
        'A gang of original cartoon beetles, a robot tortoise and a yo-yo champion grandmother cheer inside explosive bursts on a crowded kids comic cover titled "ワクワクコミック" with giveaway badges set exact.',
        'A cartoon rocket-powered hamster zooms across a loud cover full of starbursts and cheering sidekicks, kids comic magazine titled "ロケットハム" with giveaway badges set exact.',
        'A single spinning battle top glows inside a giant yellow starburst while cartoon kids gasp around it, loud kids magazine cover titled "コマ王" set exact.',
      ],
    }),
    cr(
      'Space Opera Seventies Manga Cover',
      'retro sci-fi manga cover',
      [...T, 'retro-scifi-manga'],
      {
        ...P,
        look: 'Seventies space opera manga cover look: dense mechanical detail, starfields, tall elegant heroines and melancholy retro-future ships.',
        subject: 'illustrate the subject among starfields and detailed retro-future machinery.',
        color: 'Deep space navy, gold and pale starlight.',
        light: 'Starlight and instrument glow.',
        texture: 'Dense line and airbrushed space.',
        camera: 'Starfield cover composition.',
        mood: 'melancholy cosmic adventure',
        render: 'Retro space opera manga cover.',
        key: 'Seventies space opera; starfields; retro-future ships',
        briefs: [
          'A tall elegant starship cook in a long coat gazes out of a round porthole at a dying red star while a battered freighter drifts past, seventies space opera cover titled "宇宙食堂" with its title set exact.',
          'A lonely radio operator floats in a starfield among glowing gauges on a cover titled "星の無線".',
          'A single old riveted spaceship drifts silently across a dense starfield past a pale ringed planet, retro seventies space opera cover titled "漂流" set exact.',
        ],
      },
    ),
    cr('Cooking Manga Volume Cover', 'food manga cover', [...T, 'food-manga'], {
      ...P,
      look: 'Cooking manga volume cover look: glistening appetizing dishes, proud chefs, steam and sparkles, and a warm delicious color palette.',
      subject: 'show the subject with glistening appetizing food, steam and sparkles.',
      color: 'Warm appetizing browns, reds and golden highlights.',
      light: 'Warm glistening highlights on food.',
      texture: 'Glossy food rendering and steam.',
      camera: 'Food-forward cover composition with chef.',
      mood: 'warm delicious pride',
      render: 'Appetizing cooking manga cover.',
      key: 'Cooking manga; glistening dishes; steam; proud chefs',
      briefs: [
        'A proud grandmother ramen chef presents a glistening bowl so perfect that tiny golden dragons rise from the steam, cooking manga cover titled "DRAGON BROTH" volume 6 with its title set exact.',
        'A nervous young baker holds up a glowing golden croissant as sparkles and steam rise around her flour-covered face, cooking manga cover titled "FLAKE" set exact.',
        'A single steaming dumpling sparkles on a blue porcelain plate while a tiny golden aura rises from its pleats, cooking manga cover titled "ONE DUMPLING" set exact.',
      ],
    }),
  ],
};

export default spec;
