import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, creation, world trees and cosmos: culture-rooted visual languages for world eggs,
// cosmic maps, first beings and the order of heaven and earth. Eight originals stay; thirteen new
// looks add Telugu, Chinese, Japanese, Finnish, Dogon, Lithuanian, Jain, Hungarian, Balinese,
// Korean, Peruvian, Ukrainian and Inuit traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} cosmological art`,
  tags: [tag, culture.toLowerCase().replace(/\s+/g, '-'), 'mythic-cosmos', 'portable-style-study'],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Creation, World Trees & Cosmos',
  updates: {},
  creates: [
    s(
      'Kalamkari Cosmic Textile',
      'kalamkari',
      'Telugu',
      'Kalamkari cosmic textile: hand-drawn and vegetable-dyed temple cloths from Andhra with pen-drawn gods, serpents and churning seas in narrative bands on madder red and black line.',
      'draw the subject with a bamboo pen in fluid black line and fill it with vegetable dyes on cotton.',
      'Madder red, indigo, myrobalan yellow, iron black and unbleached cotton cream.',
      'Flat dyed color with no cast light, kept consistent across the whole image.',
      'Vegetable dye on cotton, pen-drawn black line, soft dye bleed and cloth weave.',
      'Horizontal narrative bands with a large central scene and ornamental border.',
      'epic cosmic devotion',
      'Fluid confident hand-drawn line with dense dyed fill.',
      'pen-drawn line; vegetable dyes; narrative bands; serpent and sea',
      [
        'Pulling on a colossal serpent wrapped around a mountain, gods on one side and giants on the other churn a sea of milk until a moon, a white elephant and a goddess rise from the foam. No readable text or logo.',
        'At the end of a very long tug-of-war over a cosmic sea, both teams collapse exhausted while the serpent rope looks mildly relieved. No readable text or logo.',
        'In the middle of a dyed cloth, a sea of milk lies perfectly still, and a single pot of nectar floats on it. No readable text or logo.',
      ],
    ),
    s(
      'Dunhuang Celestial Cave Mural',
      'dunhuang',
      'Chinese',
      'Dunhuang celestial cave mural: Silk Road cave temple murals with flying celestials trailing scarves through heavenly skies, lotus ceilings, oxidized pigments and flaking plaster.',
      'paint the subject as a celestial being flying with long trailing scarves across a cave ceiling.',
      'Malachite green, lapis blue, oxidized dark red, earth ochre and plaster white.',
      'Dim cave light with pigment glowing softly from the walls.',
      'Mineral pigment on plaster, flaking layers, oxidized skin tones and cracks.',
      'Upward view across a cave ceiling with flowing figures circling a lotus center.',
      'weightless heavenly grace',
      'Flowing mural painting with long rhythmic ribbon lines.',
      'flying celestials; trailing scarves; lotus ceiling; flaking plaster',
      [
        'Circling a painted lotus at the top of a cave ceiling, flying musicians trail scarves so long that they become the rivers, clouds and mountain paths of an entire heaven. No readable text or logo.',
        'Across a cave ceiling, one flying celestial has lost her scarf and is chasing it through the entire heavenly procession. No readable text or logo.',
        'In a dark cave temple, a single beam of lamplight reveals one faded flying figure, and the plaster around her is flaking like petals. No readable text or logo.',
      ],
    ),
    s(
      'Nihonga Mineral Creation',
      'nihonga-creation',
      'Japanese',
      'Nihonga mineral creation: modern Japanese painting in crushed mineral pigments and gold leaf, showing the first gods stirring the primordial sea with a jeweled spear from a floating bridge.',
      'paint the subject in crushed mineral pigment with soft gold leaf and shimmering granular color.',
      'Azurite blue, malachite green, gold leaf, shell white and ink grey.',
      'Soft glowing light with gold leaf catching and shimmering.',
      'Crushed mineral pigment, hide glue, gold leaf squares and silk grain.',
      'Wide calm composition with figures small above a vast shimmering sea.',
      'quiet primordial awe',
      'Refined luminous painting with granular pigment shimmer, kept consistent across the whole image.',
      'mineral pigment; gold leaf; primordial sea; floating bridge',
      [
        'Standing on a floating bridge of cloud, two first gods stir the dark primordial sea with a jeweled spear, and drops falling from its tip harden into the very first island. No readable text or logo.',
        'After stirring the first island out of the sea, two creator gods realize they have made it slightly crooked. No readable text or logo.',
        'Above a still shimmering sea, a single drop of brine falls from nowhere and catches the gold light. No readable text or logo.',
      ],
    ),
    s(
      'Ryijy Rug Kalevala Weave',
      'ryijy-kalevala',
      'Finnish',
      'Ryijy rug Kalevala weave: Finnish long-pile ryijy rugs with shaggy wool knots in bold shapes showing the epic creation of the world from the eggs of a duck resting on the knee of the air spirit.',
      'weave the subject in long shaggy wool pile with bold simple shapes and blended color knots.',
      'Deep indigo, rowan red, birch white, moss green and gold.',
      'Soft northern daylight across thick shaggy pile, kept consistent across the whole image.',
      'Long wool pile, knotted rows, soft blended color and fringe.',
      'Frontal wall rug with bold central composition and simple border.',
      'mythic northern calm',
      'Bold textile design with soft shaggy edges, kept consistent across the whole image.',
      'long wool pile; bold shapes; duck eggs; air spirit',
      [
        "Floating in a shaggy indigo sea, the spirit of the air raises her knee from the waves as a duck's cracked eggs become the sky, the earth, the sun and the stars. No readable text or logo.",
        'Woven in long wool pile, a small duck looks at the whole universe that just hatched from its eggs with deep concern. No readable text or logo.',
        'On a shaggy wool rug, one tiny golden egg sits alone in a sea of deep blue knots. No readable text or logo.',
      ],
    ),
    s(
      'Dogon Granary Door',
      'dogon-door',
      'Dogon',
      'Dogon granary door: carved wooden granary doors from Mali with rows of ancestor figures, twin spirits, lizards and zigzag water lines cut into weathered planks with iron staples.',
      'carve the subject as a row of simplified figures on weathered planks joined by iron staples.',
      'Weathered grey-brown wood, dust ochre, iron dark and cliff red.',
      'Strong Sahel sun raking across carved relief, kept consistent across the whole image.',
      'Weathered hardwood planks, iron staples, adze marks and cracks.',
      'Frontal door with repeated rows of carved figures and a lock bar.',
      'ancestral cosmic order',
      'Simplified rhythmic carving with worn surface, kept consistent across the whole image.',
      'rows of ancestors; twin spirits; iron staples; granary door',
      [
        'Carved in weathered rows across an old granary door, the first ancestral twins descend from the sky on an ark full of seeds, animals and the knowledge of smithing. No readable text or logo.',
        'On a carved door, twelve identical ancestors stand in rows, except the one at the end who is clearly late. No readable text or logo.',
        'On a cliff village at noon, a small carved door hangs open, and the granary behind it is full of light. No readable text or logo.',
      ],
    ),
    s(
      'Straw Sodas Cosmos Mobile',
      'straw-sodas',
      'Lithuanian',
      'Straw sodas cosmos mobile: Lithuanian and Baltic hanging straw gardens of geometric polyhedra, suspended from ceilings to model the order of the world, glowing gold and turning slowly.',
      'build the subject from geometric straw polyhedra suspended on threads, turning slowly in warm light.',
      'Straw gold, warm shadow brown, linen white and candle amber.',
      'Warm window and candle light with delicate shadows cast by straw.',
      'Hollow straw tubes, threaded joins, fragile geometry and soft shadows.',
      'Centered hanging structure seen slightly from below against a pale ceiling.',
      'fragile sacred harmony',
      'Precise delicate geometry with soft glow, kept consistent across the whole image.',
      'straw polyhedra; hanging threads; nested structures; soft shadows',
      [
        'Hanging from the beam of a farmhouse, a vast straw cosmos of nested polyhedra turns slowly, each small structure holding a tiny sun, moon and planet also woven from straw. No readable text or logo.',
        'Beneath a hanging straw universe in a farmhouse kitchen, a curious cat has already begun to rearrange the planets with one careful paw. No readable text or logo.',
        'In a quiet room, the shadow of a hanging straw structure spreads across the wall like a starry map. No readable text or logo.',
      ],
    ),
    s(
      'Jain Cosmic Man Diagram',
      'jain-cosmic',
      'Jain',
      'Jain cosmic man diagram: Jain cosmological paintings showing the universe as a vast human figure, layered with heavens, a central human world of rings and hells below, in precise color on cloth or paper.',
      'paint the subject as a vast human-shaped universe with layered worlds inside its body.',
      'Vermilion, gold, deep blue, green and cream, kept consistent across the whole image.',
      'Flat even light with no cast shadow, kept consistent across the whole image.',
      'Opaque watercolor on cloth, fine line and gold.',
      'Frontal vertical figure filling the frame with stacked worlds.',
      'vast ordered cosmos',
      'Precise schematic painting with ornamental detail, kept consistent across the whole image.',
      'cosmic human figure; layered heavens; concentric continents; hells below',
      [
        'Standing with hands on hips, a vast human figure contains the whole universe, rows of palaces in the chest, a ring of island continents at the waist and seven dark worlds in the legs. No readable text or logo.',
        'Inside a vast cosmic figure, one tiny traveler has lost their way between the heavens and asks a celestial for directions. No readable text or logo.',
        'At the center of a vast cosmic figure, a single small island floats in a ring of blue seas. No readable text or logo.',
      ],
    ),
    s(
      'Matyó World Tree Embroidery',
      'matyo-tree',
      'Hungarian',
      'Matyó world tree embroidery: Hungarian folk embroidery with dense satin-stitched roses, tulips and peonies branching from a single tree of life in saturated red, blue, green and yellow on black or white cloth.',
      'stitch the subject as a dense flowering tree of life in bold satin-stitch floss.',
      'Crimson, cobalt, emerald, sunflower yellow and black cloth.',
      'Soft sheen on silky floss with no strong shadow.',
      'Satin-stitch floss, dense petals, cloth grain and visible stitches.',
      'Symmetrical tree rising from a pot or roots filling the frame.',
      'joyous abundant life',
      'Dense decorative embroidery with bold flat color, kept consistent across the whole image.',
      'tree of life; satin-stitch roses; tulips and peonies; bold color',
      [
        'Rising from a single root in a black cloth sky, a vast flowering tree of life holds the sun in its upper branches, the living world in its middle and the underworld among its tangled roots. No readable text or logo.',
        'On a crowded embroidered tree, one tiny bird has found the only empty space and is very proud of it. No readable text or logo.',
        'On a plain white cloth, a single embroidered rose blooms alone, its thread still attached to the needle. No readable text or logo.',
      ],
    ),
    s(
      'Kamasan Astrological Calendar',
      'kamasan-calendar',
      'Balinese',
      'Kamasan astrological calendar: Balinese Kamasan painting on cloth, a grid of divine figures, planets, beasts and constellations drawn in stylized wayang profile with muted earth colors.',
      'paint the subject in stylized profile within a grid of cosmic figures on bark or cloth.',
      'Earth red, ochre, indigo, pale sage and black outline.',
      'Flat shadowless color with fine outlines, kept consistent across the whole image.',
      'Natural pigment on cotton, fine black line and aged cloth.',
      'Grid of small panels, each a cosmic figure or constellation.',
      'ordered celestial wonder',
      'Meticulous flat traditional painting, kept consistent across the whole image.',
      'calendar grid; stylized profiles; constellations; earth colors',
      [
        'Arranged across a painted cloth calendar, every constellation has become a figure, a turtle carrying the earth, a scorpion, a boat of stars and a demon swallowing the moon. No readable text or logo.',
        'On a cosmic calendar, the figure governing tomorrow looks extremely unlucky, and everyone in the neighboring squares is avoiding eye contact. No readable text or logo.',
        'In one small square of a painted calendar, a single star sits on a quiet boat, drifting through the dark. No readable text or logo.',
      ],
    ),
    s(
      'Ten Longevity Screen',
      'longevity-screen',
      'Korean',
      'Ten longevity screen: Korean court folding screens of the ten symbols of long life, sun, clouds, mountains, water, pines, cranes, deer, turtles, fungus and bamboo in lush blue-green mineral color.',
      'paint the subject among the ten long-life symbols on a blue-green court screen.',
      'Azurite blue, malachite green, cinnabar sun, white cranes and gold.',
      'Even decorative light with glowing color, kept consistent across the whole image.',
      'Mineral pigment on silk, folding screen panels, fine outlines.',
      'Wide panorama across panels with mountains, sea and sun.',
      'serene eternal harmony',
      'Lush ornamental landscape painting, kept consistent across the whole image.',
      'long-life symbols; blue-green mountains; cranes and deer; red sun',
      [
        'Across ten folding panels, cranes wheel above blue-green peaks, deer drink from a waterfall, turtles breathe mist, and a red sun and white moon share one eternal sky. No readable text or logo.',
        'Among the ten symbols of long life, a very old turtle and a very young deer argue about which of them will last longer. No readable text or logo.',
        'On one quiet panel of a court screen, a single pine leans over the water, and a crane lands on its branch. No readable text or logo.',
      ],
    ),
    s(
      'Andean Retablo Cosmos',
      'andean-retablo',
      'Peruvian',
      'Andean retablo cosmos: Peruvian Ayacucho retablo boxes with painted doors opening onto layered tiers of tiny plaster figures, heaven above, earth in the middle and underworld below.',
      'model the subject as tiny painted plaster figures in stacked tiers inside a painted wooden box.',
      'Bright pink, lime, sky blue, sun yellow and white plaster.',
      'Warm front light into shallow box tiers, kept consistent across the whole image.',
      'Painted wood, plaster and potato-paste figures, floral painted doors.',
      'Open box frontal with doors swung wide and tiers stacked.',
      'festive layered cosmos',
      'Crisp handmade miniature diorama, kept consistent across the whole image.',
      'painted box; tiered scenes; tiny figures; floral doors',
      [
        'Behind flower-painted doors, a tiny box contains the whole cosmos, condors and the sun in the top tier, a village feast in the middle and horned mountain spirits dancing in the underworld below. No readable text or logo.',
        'In a painted box, the tiny figures on the earthly tier are having such a loud party that heaven above has leaned down to complain. No readable text or logo.',
        'Half open on a market stall, a small painted box shows only its upper tier, a condor carrying the sun. No readable text or logo.',
      ],
    ),
    s(
      'Pysanka World Egg',
      'pysanka',
      'Ukrainian',
      'Pysanka world egg: Ukrainian wax-resist decorated eggs with fine geometric bands, stars, wheat, suns and endless lines, dyed in layers from yellow to red to black.',
      'decorate the subject with wax-resist bands, stars and endless lines as if drawn on an egg surface.',
      'Sun yellow, poppy red, deep black, orange and white.',
      'Soft sheen on curved shell with candle-warm highlight.',
      'Wax-resist line, dye layers, shell surface, faint wax residue.',
      'Centered egg form or curved surface filling frame with wrapping pattern.',
      'protective cosmic order',
      'Precise curved-surface patterning with crisp lines, kept consistent across the whole image.',
      'wax-resist lines; star bands; endless line; layered dyes',
      [
        'Glowing on a dark table, a vast decorated egg holds the whole world, a black sky of eight-pointed stars on its crown, a band of wheat and suns at its equator and waves along its base. No readable text or logo.',
        'After decorating a perfect world egg, the artist discovers one tiny line that does not connect, and the whole cosmos seems worried about it. No readable text or logo.',
        'On a windowsill at dawn, a single egg decorated with one endless line catches the first sun. No readable text or logo.',
      ],
    ),
    s(
      'Arctic Stonecut Print',
      'arctic-stonecut',
      'Inuit',
      'Arctic stonecut print: contemporary Inuit stonecut and stencil prints with bold flat shapes of sea spirits, birds, transformations and hunters on white paper with generous space.',
      'print the subject as bold flat stonecut shapes with simple stenciled color on white paper.',
      'Black, deep blue, ochre, rust red and paper white.',
      'Flat print with no cast light, kept consistent across the whole image.',
      'Stonecut ink, stencil color, soft paper edges and sparse layout.',
      'Balanced central figure surrounded by open white space.',
      'mythic arctic clarity',
      'Bold graphic printmaking with confident shapes, kept consistent across the whole image.',
      'bold flat shapes; sea spirits; transformation; white space',
      [
        "Floating in open white space, a sea spirit's long hair spreads into the shapes of seals, whales and walruses as they swim out into the arctic sea for the first time. No readable text or logo.",
        'In a bold stonecut print, an owl halfway through turning into a person has forgotten which half should blink. No readable text or logo.',
        'On a mostly white print, a single black raven flies above a thin blue line of sea. No readable text or logo.',
      ],
    ),
  ],
};

export default spec;
