import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, tricksters and shape-shifters: culture-rooted visual languages for clever
// tricksters, fox spirits, shape-shifters and pranksters. Eight originals stay; fourteen new
// looks add Japanese, Chinese, Korean, medieval European, Roman, Polynesian, Scottish, French,
// Oaxacan, German, Ottoman and Yoruba traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} trickster art`,
  tags: [
    tag,
    culture.toLowerCase().replace(/\s+/g, '-'),
    'mythic-tricksters',
    'portable-style-study',
  ],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Tricksters & Shape-Shifters',
  updates: {},
  creates: [
    s(
      'Kitsune Rain Wedding Print',
      'kitsune-wedding',
      'Japanese',
      'Kitsune rain wedding print: woodblock prints of fox wedding processions during sun-showers, lantern-carrying foxes in kimono crossing fields under rain and sunlight.',
      'show the subject in a fox wedding procession during a sunlit rain shower.',
      'Soft gold sunlight, rain grey and vermilion accents.',
      'Sunlight through slanting rain, kept consistent across the whole image.',
      'Woodblock grain, rain lines and bokashi gradients, kept consistent across the whole image.',
      'Procession crossing a field or bridge, kept consistent across the whole image.',
      'enchanted mischievous wonder',
      'Refined woodblock print, kept consistent across the whole image.',
      'fox wedding; sun-shower; lanterns; procession',
      [
        'Crossing a rice field during a sun-shower, a procession of foxes in wedding kimono carries glowing lanterns as a rainbow arches over their veiled bride. No readable text or logo.',
        'At a fox wedding in the rain, one young fox guest keeps forgetting to hide his tail under his borrowed human disguise. No readable text or logo.',
        'In a sunlit rain over an empty field, a single line of small paw prints leads to a lantern still burning in the grass. No readable text or logo.',
      ],
    ),
    s(
      'Stone Monkey Cloud Ink Painting',
      'stone-monkey',
      'Chinese',
      'Stone monkey cloud ink painting: vigorous Chinese ink-and-color painting of a stone-born monkey king somersaulting on clouds with his staff, in splashy brushwork.',
      'paint the subject with vigorous splashy ink and color, riding or leaping on clouds.',
      'Ink black with gold, red and cloud white.',
      'Luminous cloud highlights, kept consistent across the whole image.',
      'Splashed ink, dry brush and rice paper, kept consistent across the whole image.',
      'Dynamic diagonal across cloud banks, kept consistent across the whole image.',
      'exuberant mischievous power',
      'Energetic ink painting, kept consistent across the whole image.',
      'monkey king; cloud somersault; golden staff; splashed ink',
      [
        'Somersaulting across a sea of clouds with a staff that stretches to the horizon, a stone-born monkey king laughs as heavenly soldiers tumble in his wake. No readable text or logo.',
        'Having eaten all the peaches of immortality, a monkey king is trying to hide the stones up his sleeve as the palace gardeners arrive. No readable text or logo.',
        'At the end of the sky, five great mountain pillars rise from the clouds, and a tiny mark has been scrawled on the middle one. No readable text or logo.',
      ],
    ),
    s(
      'Huli Jing Silk Painting',
      'huli-jing',
      'Chinese',
      'Huli jing silk painting: delicate Chinese silk painting of fox spirits transforming between elegant ladies and nine-tailed foxes in moonlit gardens.',
      'paint the subject on silk mid-transformation between fox and human form.',
      'Pale silk, moon silver, soft rose and ink.',
      'Soft moonlight on silk, kept consistent across the whole image.',
      'Aged silk, fine brushwork and light color, kept consistent across the whole image.',
      'Garden scene with moon gate, kept consistent across the whole image.',
      'elegant uncanny allure',
      'Delicate refined silk painting, kept consistent across the whole image.',
      'fox spirit; transformation; moon gate; silk',
      [
        "Stepping through a moon gate in a silver garden, an elegant lady's shadow on the wall reveals nine sweeping fox tails behind her silk robes. No readable text or logo.",
        'In a moonlit garden, a fox spirit disguised as a noble lady has been caught by a dog and is trying very hard to look dignified. No readable text or logo.',
        'On an aged silk painting, a lady sits by a pond, and her reflection in the water is a fox. No readable text or logo.',
      ],
    ),
    s(
      'Tanuki Belly-Drum Woodblock',
      'tanuki',
      'Japanese',
      'Tanuki belly-drum woodblock: comic Japanese woodblock prints of shape-shifting raccoon dogs drumming their bellies, disguised as kettles, monks and lanterns.',
      'print the subject as a comic shape-shifting raccoon-dog scene in woodblock color.',
      'Earthy browns, moon gold and soft green, kept consistent across the whole image.',
      'Flat woodblock color with moonlight, kept consistent across the whole image.',
      'Woodblock lines, paper grain and bokashi, kept consistent across the whole image.',
      'Moonlit temple garden composition, kept consistent across the whole image.',
      'playful folk comedy',
      'Charming comic woodblock, kept consistent across the whole image.',
      'raccoon dogs; belly drums; disguises; moonlight',
      [
        'Under a full moon at a mountain temple, a band of raccoon dogs drums on their round bellies as one of them transforms into a teakettle mid-song. No readable text or logo.',
        'Disguised as a very convincing tea kettle, a raccoon dog is put on the fire and starts sprouting legs in a panic. No readable text or logo.',
        'At a moonlit temple, the monk counts his lanterns and finds one more than he owns, and it has a furry tail. No readable text or logo.',
      ],
    ),
    s(
      'Kumiho Moonlit Minhwa',
      'kumiho',
      'Korean',
      'Kumiho moonlit minhwa: Korean folk painting of the nine-tailed fox under a full moon, flat bold color, pine trees and mountains, eerie and charming at once.',
      'paint the subject as a nine-tailed fox in bold Korean folk painting under the moon.',
      'Indigo night, white fox, pine green and red.',
      'Flat color with moon glow, kept consistent across the whole image.',
      'Hanji paper, bold outlines and folk washes, kept consistent across the whole image.',
      'Fox on a mountain ridge under a large moon.',
      'eerie folk enchantment',
      'Bold charming folk painting, kept consistent across the whole image.',
      'nine-tailed fox; full moon; pine; folk painting',
      [
        'On a mountain ridge beneath an enormous moon, a white nine-tailed fox rolls a glowing bead between its paws as its tails fan out like a crown of moonlight. No readable text or logo.',
        'A nine-tailed fox trying to become human has mastered everything except hiding the ninth tail, which keeps popping out. No readable text or logo.',
        'On a moonlit path, nine small footprints lead into the pines, then a single pair of human footprints walks out. No readable text or logo.',
      ],
    ),
    s(
      'Reynard Fable Engraving',
      'reynard',
      'Medieval European',
      'Reynard fable engraving: medieval and early modern engravings of the cunning fox Reynard outwitting the lion king and the wolf in courtly animal satire.',
      'engrave the subject as a courtly animal fable with fine cross-hatching.',
      'Black ink on cream paper, kept consistent across the whole image.',
      'Fine hatched shadows, kept consistent across the whole image.',
      'Copper-engraved line and cross-hatching, kept consistent across the whole image.',
      'Courtly scene of dressed animals, kept consistent across the whole image.',
      'sly courtly satire',
      'Detailed witty engraving, kept consistent across the whole image.',
      'cunning fox; animal court; engraving; satire',
      [
        "Dressed as a pilgrim before the lion king's court, a cunning fox points dramatically at a wolf who is clearly being framed for stealing the royal hens. No readable text or logo.",
        'In an engraved fable, a fox preaching to a flock of geese from a pulpit keeps licking his lips mid-sermon. No readable text or logo.',
        "In an engraved courtroom of animals, the fox's seat is empty, and a trail of feathers leads to the window. No readable text or logo.",
      ],
    ),
    s(
      'Pompeian Mercury Fresco',
      'pompeian',
      'Roman',
      'Pompeian Mercury fresco: Roman wall painting in Pompeian red with the winged messenger trickster, painted architecture, garlands and faded plaster.',
      'paint the subject as a lively figure on a Pompeian red fresco wall.',
      'Pompeian red, ochre, black and faded blue, kept consistent across the whole image.',
      'Flat fresco light, kept consistent across the whole image.',
      'Fresco plaster, cracks and faded pigment, kept consistent across the whole image.',
      'Figure in a painted architectural panel, kept consistent across the whole image.',
      'witty classical playfulness',
      'Faded elegant fresco, kept consistent across the whole image.',
      'Pompeian red; winged sandals; painted architecture; fresco',
      [
        'Darting across a Pompeian red wall in winged sandals, the messenger god steals a lyre from a sleeping god of light while painted doves scatter. No readable text or logo.',
        'On a faded villa fresco, the messenger god has stolen a herd of cattle and made them all walk backward to hide his tracks. No readable text or logo.',
        'On a cracked red fresco, the painted winged sandals stand on a pedestal, and the figure who wore them is gone. No readable text or logo.',
      ],
    ),
    s(
      'Tapa Cloth Legend Pattern',
      'tapa',
      'Polynesian',
      'Tapa cloth legend pattern: Pacific bark cloth with painted and stamped brown and black geometric patterns framing the legend of the demigod who fished up islands.',
      'render the subject within brown and black geometric bark-cloth patterns.',
      'Earth brown, black and natural bark cream, kept consistent across the whole image.',
      'Flat printed cloth, kept consistent across the whole image.',
      'Beaten bark cloth, stamped patterns and fibers, kept consistent across the whole image.',
      'Central legend panel in geometric frames, kept consistent across the whole image.',
      'bold oceanic legend',
      'Crisp patterned bark cloth, kept consistent across the whole image.',
      'bark cloth; geometric patterns; brown and black; legend',
      [
        'Framed in brown and black bark-cloth patterns, a demigod hauls a whole island out of the sea with a magic fishhook as his brothers row the canoe in terror. No readable text or logo.',
        'On a patterned bark cloth, a demigod lassos the sun to slow it down, and the sun looks deeply annoyed. No readable text or logo.',
        'On a finished bark cloth, the pattern repeats perfectly around an empty space shaped like a hook. No readable text or logo.',
      ],
    ),
    s(
      'Orkney Selkie Watercolor',
      'selkie',
      'Scottish',
      'Orkney selkie watercolor: soft northern watercolor of seal-folk shedding their skins on moonlit rocks, grey seas, mist and lamplit crofts.',
      'paint the subject as a seal-folk transformation on misty rocks in soft watercolor.',
      'Sea grey, moon silver and warm croft light.',
      'Moonlight through sea mist, kept consistent across the whole image.',
      'Soft washes, granulation and paper texture, kept consistent across the whole image.',
      'Rocky shore with sea and croft, kept consistent across the whole image.',
      'wistful sea enchantment',
      'Soft atmospheric watercolor, kept consistent across the whole image.',
      'seal skins; moonlit rocks; sea mist; croft',
      [
        'On a moonlit skerry, seal-folk step out of their silver skins to dance, while one sealskin lies forgotten close to a lamplit croft window. No readable text or logo.',
        "A fisherman has hidden a selkie's sealskin in his attic, and a very large seal is now waiting at his door every morning. No readable text or logo.",
        'On a misty shore at dawn, a folded sealskin lies on the rocks, and a line of human footprints leads into the sea. No readable text or logo.',
      ],
    ),
    s(
      'Loup-Garou Chapbook Woodcut',
      'loup-garou',
      'French',
      'Loup-garou chapbook woodcut: rough French chapbook woodcuts of werewolves and shape-shifters in villages and forests, crude bold carving and cheap paper.',
      'cut the subject as a crude bold chapbook woodcut of a shape-shifter.',
      'Black ink on grey-brown paper, kept consistent across the whole image.',
      'Crude carved contrast, kept consistent across the whole image.',
      'Worn woodblock, cracks and cheap paper, kept consistent across the whole image.',
      'Village or forest scene in a frame, kept consistent across the whole image.',
      'rustic folk dread',
      'Crude charming woodcut, kept consistent across the whole image.',
      'werewolf; chapbook; crude carving; village',
      [
        "Carved in crude bold lines, a wolf-man in a peasant's coat stalks the edge of a village as the moon rises over the church and a lantern bobs in the lane. No readable text or logo.",
        'In a chapbook woodcut, a werewolf trying to sneak through the village has been spotted by an old woman who scolds him with a broom. No readable text or logo.',
        'In a rough woodcut of a forest clearing, a pile of neatly folded clothes sits beside a line of paw prints. No readable text or logo.',
      ],
    ),
    s(
      'Oaxacan Alebrije Carving',
      'alebrije',
      'Oaxacan',
      'Oaxacan alebrije carving: vividly painted carved wooden fantasy creatures with intricate dotted patterns, combining animals into impossible spirit guides.',
      'carve and paint the subject as a vivid patterned fantasy creature.',
      'Neon pink, turquoise, yellow and black dots, kept consistent across the whole image.',
      'Bright daylight on painted wood, kept consistent across the whole image.',
      'Carved copal wood and intricate painted patterns, kept consistent across the whole image.',
      'Single creature on a plain ground, kept consistent across the whole image.',
      'joyful fantastic spirit',
      'Vivid detailed painted carving, kept consistent across the whole image.',
      'painted creature; dotted patterns; hybrid animal; wood',
      [
        'Leaping from a workshop shelf into the night, a painted wooden jaguar with eagle wings and a lizard tail carries a sleeping woodcarver across the stars. No readable text or logo.',
        "In a carver's workshop, a painted fantasy creature with too many legs has tripped over all of them at once. No readable text or logo.",
        'On a table of painted creatures, one alebrije is still unpainted wood, and its carved eyes are open. No readable text or logo.',
      ],
    ),
    s(
      'Eulenspiegel Owl-and-Mirror Etching',
      'eulenspiegel',
      'German',
      'Eulenspiegel owl-and-mirror etching: early German etchings of the jester prankster with his owl and mirror, crowded market towns and comic chaos.',
      'etch the subject as a prankster scene in a crowded old German town.',
      'Brown ink with light hand tint, kept consistent across the whole image.',
      'Etched line shading, kept consistent across the whole image.',
      'Etched line, crosshatching and aged paper, kept consistent across the whole image.',
      'Market square scene, kept consistent across the whole image.',
      'cheeky urban mischief',
      'Lively detailed etching, kept consistent across the whole image.',
      'jester prankster; owl and mirror; market square; etching',
      [
        'Walking a tightrope over a crowded market square, a jester with an owl on one shoulder and a mirror in his hand has convinced the whole town to give him their left shoes. No readable text or logo.',
        'In a crowded etching, a prankster has taught a donkey to read an empty book, and the town council is deeply impressed. No readable text or logo.',
        'In an old etched town at night, an owl sits on the fountain holding a small mirror that reflects no moon. No readable text or logo.',
      ],
    ),
    s(
      'Nasreddin Ottoman Miniature',
      'nasreddin',
      'Ottoman',
      'Nasreddin Ottoman miniature: Ottoman court miniature style of the wise fool on his donkey, flat bright colors, patterned carpets and bustling bazaars.',
      'paint the subject as a flat bright Ottoman miniature scene of a wise fool.',
      'Bright red, green, gold and blue, kept consistent across the whole image.',
      'Flat even light, kept consistent across the whole image.',
      'Fine pigment, gold and patterned surfaces, kept consistent across the whole image.',
      'Bazaar scene with high horizon, kept consistent across the whole image.',
      'gentle witty wisdom',
      'Clear charming miniature, kept consistent across the whole image.',
      'wise fool; donkey; bazaar; Ottoman miniature',
      [
        'Riding backward on his donkey through a bustling bazaar, a wise fool explains to the crowd that he is simply keeping an eye on everyone following him. No readable text or logo.',
        'In a bright miniature, a wise fool searches for a lost ring under a street lamp because the light is better there than in his house. No readable text or logo.',
        "In a bazaar miniature, a donkey waits patiently outside a closed door, and its rider's shadow is on the roof. No readable text or logo.",
      ],
    ),
    s(
      'Ijapa Tortoise Market Mural',
      'ijapa',
      'Yoruba',
      'Ijapa tortoise market mural: Nigerian painted market and school murals of the clever tortoise from Yoruba folktales, bold flat color and lively crowds.',
      'paint the subject as a bold flat-color mural of a folktale scene.',
      'Bright flat primaries and earth tones, kept consistent across the whole image.',
      'Flat bright daylight, kept consistent across the whole image.',
      'Painted plaster wall and weathering, kept consistent across the whole image.',
      'Wide mural with crowds, kept consistent across the whole image.',
      'cheeky folk wisdom',
      'Bold lively mural painting, kept consistent across the whole image.',
      'clever tortoise; market mural; bold color; folktale',
      [
        'Painted across a market wall, the clever tortoise rides on the back of a bird to the sky feast, having convinced everyone his name is All-of-You. No readable text or logo.',
        'On a bright mural, the tortoise tries to sneak away from the market with a whole pot of stew balanced on his shell. No readable text or logo.',
        "On a faded market mural, the painted tortoise's shell has a new crack that was not there yesterday. No readable text or logo.",
      ],
    ),
  ],
};

export default spec;
