import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Classic film noir and westerns, 1939-1971: each preset names its film and director and rebuilds
// that film's photography (stock, lighting, lenses, landscape). Cards stage original moments,
// never the film's own characters, props or scenes. Pack_02 keeps the generic noir and western.
const T = ['noir-western', 'classic-cinema'];
const noirBw =
  'Forties black-and-white nitrate grain with deep inky blacks and silvery highlights.';
const westColor = 'Mid-century Technicolor or Eastmancolor grain with warm earth tones.';

const spec: Spec = {
  pack: 'pack_27',
  category: '10. Classic Noir & Western',
  newCategory: { id: 'classic-noir-western' },
  updates: {},
  creates: [
    cr(
      'The Maltese Falcon 1941 - Huston Office Noir',
      'forties film noir',
      [...T, 'maltese-falcon'],
      {
        look: 'John Huston The Maltese Falcon (1941) look: San Francisco private-eye offices, venetian blind shadows, low ceilings, fedoras, cigarette smoke and tight dialogue-driven noir framing.',
        subject:
          'stage the subject in cramped private-eye offices with venetian blind shadows and smoke.',
        color: 'Inky black, grey and silvery highlights.',
        light: 'Hard key light cut by venetian blind stripes.',
        texture: noirBw,
        camera: 'Low angles showing ceilings and tight two-shots.',
        mood: 'cynical smoky intrigue',
        render: 'Authentic early-forties Warner noir frame.',
        key: 'Maltese Falcon office; blind shadows; fedoras; low ceilings',
        avoid: ['a black bird statuette'],
        briefs: [
          'In a cramped private-eye office striped by venetian blind shadows, a retired librarian in a veiled hat slides a mysterious library book across the desk while cigarette smoke curls under the low ceiling. No readable text or logo.',
          'A hotel corridor at night holds a nervous man in a bowler hat listening at a keyhole. The elevator light glows behind him. No readable text or logo.',
          'A package wrapped in newspaper sits on an empty office desk at dawn. The blinds cut it into stripes. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Double Indemnity 1944 - Wilder Venetian Dust Noir',
      'forties film noir',
      [...T, 'double-indemnity'],
      {
        look: 'Billy Wilder Double Indemnity (1944) look: dusty sunlit Los Angeles bungalows with shafts through blinds, insurance offices, supermarket aisles, flashback narration and fatalistic noir.',
        subject: 'stage the subject in dusty sunlit California interiors cut by blind shadows.',
        color: 'Dusty greys and bright sunlit whites.',
        light: 'Shafts of dusty sunlight through blinds.',
        texture: noirBw,
        camera: 'Classic Hollywood noir coverage with deep shadows.',
        mood: 'fatalistic sunlit noir',
        render: 'Authentic forties Paramount noir frame.',
        key: 'Double Indemnity dusty sunlight; blinds; insurance offices',
        briefs: [
          'In a dusty sunlit Los Angeles living room, an insurance salesman in a double-breasted suit hesitates with his pen above a policy while dust floats in a shaft of light through the blinds. No readable text or logo.',
          'Two strangers pretend not to know each other in a supermarket aisle of canned peaches. Their eyes never meet. No readable text or logo.',
          'An office at night holds a dictaphone, a burning cigarette and an empty chair. The recording is still running. No readable text or logo.',
        ],
      },
    ),
    cr('Laura 1944 - Preminger Portrait Mystery', 'forties film noir', [...T, 'laura-44'], {
      look: 'Otto Preminger Laura (1944) look: elegant Manhattan apartments, a haunting painted portrait above a fireplace, gliding camera, rain and sophisticated obsession.',
      subject:
        'stage the subject in elegant apartments beneath a haunting painted portrait, with gliding camera.',
      color: 'Elegant silver greys and velvet black.',
      light: 'Soft lamp pools and rainy window light.',
      texture: noirBw,
      camera: 'Gliding elegant camera moves.',
      mood: 'haunted elegant obsession',
      render: 'Authentic forties Fox noir frame.',
      key: 'Laura portrait; elegant apartment; gliding camera',
      briefs: [
        'In an elegant rainy Manhattan apartment, a weary detective falls asleep in an armchair beneath a glowing painted portrait of a woman, and the portrait seems to be watching the rain. No readable text or logo.',
        'A dinner party of sophisticated guests toasts under a chandelier. One chair at the head of the table is empty. No readable text or logo.',
        'A mantel clock hides a small secret compartment in an elegant Manhattan parlor. Its tiny brass door is slightly open, and the rain taps on the window. No readable text or logo.',
      ],
    }),
    cr(
      'Out of the Past 1947 - Tourneur Nocturnal Fatalism',
      'forties film noir',
      [...T, 'out-of-the-past'],
      {
        look: 'Jacques Tourneur Out of the Past (1947) look: Nicholas Musuraca low-key cinematography, moonlit Mexican beaches, trench coats, rain-slick cars and fatalistic romance.',
        subject:
          'stage the subject in low-key nocturnal scenes with trench coats and moonlit exteriors.',
        color: 'Deep velvet black with moonlit silver.',
        light: 'Low-key moonlight and cigarette glow.',
        texture: noirBw,
        camera: 'Low-key nocturnal framing with deep shadow.',
        mood: 'doomed fatalistic romance',
        render: 'Authentic forties RKO noir frame.',
        key: 'Out of the Past low-key; moonlit beaches; trench coats',
        briefs: [
          'On a moonlit Mexican beach at night, a gas station owner in a trench coat waits beside fishing nets as a woman in white walks out of the dark cantina lights toward him. No readable text or logo.',
          'Two figures sit in a parked car in the rain, their faces lit only by cigarette glow. The wipers are off. No readable text or logo.',
          'A lakeside cabin at night has its door open and a fishing rod leaning against it. The radio is still playing. No readable text or logo.',
        ],
      },
    ),
    cr('The Third Man 1949 - Reed Tilted Vienna', 'forties film noir', [...T, 'third-man'], {
      look: 'Carol Reed The Third Man (1949) look: bombed-out postwar Vienna, dutch-tilted angles, wet cobblestones, huge shadows on walls, sewers, a Ferris wheel and zither music.',
      subject:
        'stage the subject in bombed postwar city ruins shot with dutch tilts and huge wall shadows.',
      color: 'Wet cobblestone silver and deep black.',
      light: 'Harsh street lamps throwing giant shadows.',
      texture: noirBw,
      camera: 'Dutch-tilted angles throughout.',
      mood: 'tilted postwar intrigue',
      render: 'Authentic late-forties British noir frame.',
      key: 'Third Man dutch tilts; ruined Vienna; giant shadows',
      avoid: ['a man in a doorway revealed by a window light with a cat at his feet'],
      briefs: [
        'Shot at a steep dutch tilt on wet cobblestones in bombed-out Vienna, a balloon seller in a long coat walks alone as his enormous shadow climbs across a ruined wall behind him. No readable text or logo.',
        'In a vast echoing sewer tunnel, torch beams bounce off rushing water. Footsteps come from every direction. No readable text or logo.',
        'An empty Ferris wheel car creaks at the top of its arc over a ruined city. The city below is silent. No readable text or logo.',
      ],
    }),
    cr(
      'Sunset Boulevard 1950 - Wilder Decaying Hollywood',
      'fifties film noir',
      [...T, 'sunset-boulevard'],
      {
        look: 'Billy Wilder Sunset Boulevard (1950) look: decaying Hollywood mansion, dusty pipe organ, empty swimming pool, projector beams through cigarette smoke and faded silent-film glamour.',
        subject:
          'stage the subject in decaying mansions of faded glamour with projector beams and dust.',
        color: 'Faded glamour greys and silver.',
        light: 'Projector beams through smoke.',
        texture: noirBw,
        camera: 'Grand theatrical framing in cavernous rooms.',
        mood: 'faded grotesque glamour',
        render: 'Authentic 1950 Paramount noir frame.',
        key: 'Sunset Boulevard mansion; projector beams; faded glamour',
        briefs: [
          'In a cavernous decaying mansion, a forgotten silent-film stuntman in a velvet robe watches his old movies alone as a projector beam cuts through the cigarette smoke above a dusty pipe organ. No readable text or logo.',
          'An empty swimming pool full of leaves reflects a lonely mansion. A rat swims in the last puddle. No readable text or logo.',
          'A staircase in a huge mansion is lined with framed photographs of the same face. Every one is signed. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Night of the Hunter 1955 - Laughton Expressionist Fable',
      'fifties film noir',
      [...T, 'night-of-the-hunter'],
      {
        look: 'Charles Laughton The Night of the Hunter (1955) look: expressionist fairy-tale noir, silhouettes on river banks, stylized starry skies, animals in the foreground and nightmarish Southern Gothic.',
        subject: 'stage the subject in expressionist silhouettes along a starry fairy-tale river.',
        color: 'Deep velvet black and stylized starlight.',
        light: 'Stylized expressionist moonlight and silhouettes.',
        texture: noirBw,
        camera: 'Painterly tableaux with foreground animals.',
        mood: 'nightmarish fairy-tale dread',
        render: 'Authentic fifties expressionist noir frame.',
        key: 'Night of the Hunter silhouettes; starry river; fairy tale',
        avoid: ['a preacher with LOVE and HATE tattooed knuckles'],
        briefs: [
          'Drifting down a starry river at night in a small skiff, two children sleep under a patched quilt while a frog and a spider’s web stand huge and silver in the foreground on the bank. No readable text or logo.',
          'A figure on horseback is silhouetted against a stylized night horizon. A barn window glows below. No readable text or logo.',
          'A grandmother sits on a porch with a rifle across her lap, singing to the dark. A lantern flickers. No readable text or logo.',
        ],
      },
    ),
    cr('Kiss Me Deadly 1955 - Aldrich Atomic Noir', 'fifties film noir', [...T, 'kiss-me-deadly'], {
      look: 'Robert Aldrich Kiss Me Deadly (1955) look: brutal atomic-age noir, Los Angeles night roads, sports cars, extreme angles, staircases and a glowing mysterious box.',
      subject:
        'stage the subject in brutal atomic noir night roads and stairwells at extreme angles.',
      color: 'Hard black and white with a burning white glow.',
      light: 'Headlights at night and blinding white glow.',
      texture: noirBw,
      camera: 'Extreme high and low angles.',
      mood: 'brutal atomic dread',
      render: 'Authentic fifties atomic noir frame.',
      key: 'Kiss Me Deadly extreme angles; night roads; glowing box',
      briefs: [
        'A barefoot hitchhiker in a trench coat runs down the center of a dark highway at night straight into the headlights of a sports car while the credits of the night roll silently in the empty sky. No readable text or logo.',
        'A steep Bunker Hill staircase at night seen from far below holds a man climbing slowly. A cat blocks the top step. No readable text or logo.',
        'A small leather case on a table leaks a line of blinding white light through its seam. Nobody dares touch it. No readable text or logo.',
      ],
    }),
    cr(
      'Sweet Smell of Success 1957 - Mackendrick Neon Broadway',
      'fifties film noir',
      [...T, 'sweet-smell'],
      {
        look: 'Alexander Mackendrick Sweet Smell of Success (1957) look: James Wong Howe night photography of Times Square neon, smoky nightclubs, wide-angle close-ups and venomous columnist power.',
        subject:
          'stage the subject in neon Times Square nights and smoky nightclubs with wide-angle faces.',
        color: 'Sparkling neon black and white.',
        light: 'Times Square neon and nightclub key light.',
        texture: noirBw,
        camera: 'Wide-angle close-ups and deep-focus nightclub tables.',
        mood: 'venomous glittering ambition',
        render: 'Authentic fifties New York noir frame.',
        key: 'Sweet Smell neon Broadway; nightclubs; wide-angle',
        briefs: [
          'In a smoky nightclub booth, a powerful gossip columnist in horn-rimmed glasses tears a matchbook into pieces while a desperate press agent leans in, neon Times Square glittering in the window. No readable text or logo.',
          'A news truck throws bundles of papers onto a wet street at four in the morning. A man watches from a phone booth. No readable text or logo.',
          'A jazz quintet plays to an empty club after closing. One chair holds a forgotten hat. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Touch of Evil 1958 - Welles Border Town Long Take',
      'fifties film noir',
      [...T, 'touch-of-evil'],
      {
        look: 'Orson Welles Touch of Evil (1958) look: seedy Mexican border town at night, extreme wide-angle low angles, long crane takes, neon, oil derricks and baroque corruption.',
        subject:
          'stage the subject in seedy border-town nights with extreme wide-angle low angles.',
        color: 'Neon-sparked black and white.',
        light: 'Neon signs and harsh street lamps.',
        texture: noirBw,
        camera: 'Extreme wide-angle low angles and long crane moves.',
        mood: 'baroque corrupted menace',
        render: 'Authentic late-fifties Welles noir frame.',
        key: 'Touch of Evil border town; wide-angle; long takes',
        briefs: [
          'In a seedy border town at night, seen from an extreme low wide angle, a tired customs officer in rumpled uniform eats a taco beside an oil derrick while a car bomb ticks in the next street. No readable text or logo.',
          'A motel in the desert at night is run by a jittery night clerk. Every room is empty but one. No readable text or logo.',
          'An old pianola plays in a smoky brothel parlor. A deck of tarot cards is spread on the table. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Stagecoach 1939 - Ford Monument Valley Journey',
      'classic western cinema',
      [...T, 'stagecoach'],
      {
        look: 'John Ford Stagecoach (1939) look: black-and-white Monument Valley buttes, a lone stagecoach crossing vast plains, low-ceilinged way stations and ensemble frontier drama.',
        subject:
          'stage the subject crossing vast black-and-white Monument Valley plains or cramped way stations.',
        color: 'Silver buttes and dusty black-and-white sky.',
        light: 'Hard desert sun and dim lamplit interiors.',
        texture: noirBw,
        camera: 'Vast wide shots of tiny figures under buttes.',
        mood: 'rugged ensemble journey',
        render: 'Authentic 1939 Ford western frame.',
        key: 'Stagecoach Monument Valley; buttes; way stations',
        briefs: [
          'Beneath towering black-and-white buttes, a lone stagecoach crosses the vast plain carrying a nervous whiskey salesman, a pregnant schoolteacher and a card sharp who is losing to her at poker. No readable text or logo.',
          'Travelers crowd a low-ceilinged adobe way station for dinner. The ceiling is so low the lamps nearly touch their hats. No readable text or logo.',
          'Dust rises over a distant ridge as a coach waits at a river crossing. The horses stamp nervously. No readable text or logo.',
        ],
      },
    ),
    cr('High Noon 1952 - Zinnemann Clock Tension', 'classic western cinema', [...T, 'high-noon'], {
      look: 'Fred Zinnemann High Noon (1952) look: stark bright black-and-white town, clocks ticking toward noon, empty streets, sweating faces and real-time moral tension.',
      subject:
        'stage the subject in stark sunlit black-and-white western streets as the clock nears noon.',
      color: 'Stark sunlit whites and hard black shadow.',
      light: 'Flat harsh noon sun.',
      texture: noirBw,
      camera: 'Real-time cutting between clocks and faces.',
      mood: 'tense lonely resolve',
      render: 'Authentic early-fifties western frame.',
      key: 'High Noon clocks; empty street; real-time tension',
      avoid: ['a marshal with a star badge'],
      briefs: [
        'On a stark empty western street at 11:58, a lone schoolteacher walks with her satchel past shuttered windows while every townsperson watches from behind the curtains. A clock ticks in the saloon. No readable text or logo.',
        'A train station platform waits in blazing sun. Three men sit on a bench watching the tracks. No readable text or logo.',
        'A pendulum clock hangs on a whitewashed wall in an empty frontier office. Its minute hand trembles just before noon while dust drifts in the sunbeam. No readable text or logo.',
      ],
    }),
    cr(
      'Johnny Guitar 1954 - Ray Trucolor Melodrama',
      'classic western cinema',
      [...T, 'johnny-guitar'],
      {
        look: 'Nicholas Ray Johnny Guitar (1954) look: lurid Trucolor saloon melodrama, a saloon carved into red rock, women in black and white dueling, operatic color and gender-bent western.',
        subject:
          'stage the subject in lurid Trucolor saloons carved into red rock with operatic staging.',
        color: 'Lurid Trucolor red rock, black and white costume.',
        light: 'Theatrical stage light in a rock-hewn saloon.',
        texture: westColor,
        camera: 'Operatic staging and bold color blocking.',
        mood: 'operatic lurid melodrama',
        render: 'Authentic fifties Trucolor western frame.',
        key: 'Johnny Guitar Trucolor; red-rock saloon; operatic',
        briefs: [
          'In a lurid Trucolor saloon carved into a red rock cliff, a woman in a crisp white gown plays the piano with her back to a posse in black who have come to arrest her. No readable text or logo.',
          'A waterfall hides the entrance to an outlaw cave behind a red rock wall. A horse drinks at its pool. No readable text or logo.',
          'An empty roulette wheel spins in a deserted saloon. The dealer has left his green visor on the table. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Searchers 1956 - Ford VistaVision Doorways',
      'classic western cinema',
      [...T, 'searchers'],
      {
        look: 'John Ford The Searchers (1956) look: VistaVision Technicolor Monument Valley, figures framed through dark doorways against blazing red buttes, snowfields and restless obsession.',
        subject:
          'stage the subject framed through dark doorways against blazing red Monument Valley buttes.',
        color: 'Blazing red buttes, sky blue and dark doorway frames.',
        light: 'Harsh desert sunlight from a dark interior.',
        texture: westColor,
        camera: 'VistaVision wide landscapes through doorway frames.',
        mood: 'restless epic longing',
        render: 'Authentic fifties VistaVision western frame.',
        key: 'Searchers doorway frame; red buttes; VistaVision',
        briefs: [
          'Framed by a dark cabin doorway, a weathered cartographer walks away into a blazing red Monument Valley afternoon carrying a rolled map, his family watching from the shadow inside. No readable text or logo.',
          'Two riders cross a pale snowfield beneath towering red buttes at dawn. Their tired horses leave the only tracks for miles, and their breath steams. No readable text or logo.',
          'A cabin door swings slowly shut on an empty desert. The wind carries dust across the threshold. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Rio Bravo 1959 - Hawks Jailhouse Camaraderie',
      'classic western cinema',
      [...T, 'rio-bravo'],
      {
        look: 'Howard Hawks Rio Bravo (1959) look: warm Technicolor small-town jailhouse, lamplit interiors, easy camaraderie, songs by the fire and patient siege tension.',
        subject: 'stage the subject in warm lamplit Technicolor jailhouse and hotel interiors.',
        color: 'Warm lamplight amber and dusty street brown.',
        light: 'Warm lamps and soft window light.',
        texture: westColor,
        camera: 'Classic Hawks eye-level ensemble framing.',
        mood: 'warm stubborn camaraderie',
        render: 'Authentic late-fifties Technicolor western frame.',
        key: 'Rio Bravo jailhouse; lamplit camaraderie; siege',
        briefs: [
          'In a warm lamplit jailhouse, a limping old deputy brews coffee on the stove while a young gunhand strums a guitar and a stubborn prisoner hums along from his cell. No readable text or logo.',
          'A hotel owner stacks flower pots on a windowsill above the street. Something glints on a rooftop across the way. No readable text or logo.',
          'A wagon loaded with crates of dynamite waits in a sunny frontier barn. A speckled chicken has settled comfortably on the top crate to lay an egg. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Good the Bad and the Ugly 1966 - Leone Extreme Close-Up',
      'sixties spaghetti western',
      [...T, 'good-bad-ugly'],
      {
        look: 'Sergio Leone The Good, the Bad and the Ugly (1966) look: Techniscope widescreen with extreme close-ups of eyes next to vast desert, sweat, stubble, circular cemetery standoffs and Morricone tension.',
        subject:
          'stage the subject in extreme close-ups of eyes set against vast widescreen desert.',
        color: 'Sun-baked ochre, dust and sky blue.',
        light: 'Blazing desert sun and sweat highlights.',
        texture: westColor,
        camera: 'Extreme close-ups cut against vast wide shots.',
        mood: 'sweaty operatic standoff',
        render: 'Authentic sixties Leone Techniscope frame.',
        key: 'Leone extreme close-ups; widescreen desert; standoffs',
        avoid: ['a poncho-wearing gunslinger with a cigarillo'],
        briefs: [
          'In an extreme widescreen close-up, the sweating eyes of three rival pie bakers fill the frame as they stand in a circular desert cemetery, each clutching a pie tin, waiting for the church bell. No readable text or logo.',
          'A tiny figure crosses a vast shimmering desert pulling a stubborn mule. The sun is merciless. No readable text or logo.',
          'A pocket watch opens with a chime in the dust. Its lid holds a faded photograph. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Once Upon a Time in the West 1968 - Leone Railroad Opera',
      'sixties spaghetti western',
      [...T, 'once-upon-west'],
      {
        look: 'Sergio Leone Once Upon a Time in the West (1968) look: operatic railroad western, long silent waits at stations, dusters, harmonicas, Monument Valley vistas and grand crane reveals.',
        subject:
          'stage the subject in long silent operatic waits at dusty railroad stations and vast vistas.',
        color: 'Dust gold, duster tan and sky blue.',
        light: 'Blazing sun and dusty station shadows.',
        texture: westColor,
        camera: 'Long slow takes and grand crane reveals.',
        mood: 'slow operatic grandeur',
        render: 'Authentic late-sixties Leone frame.',
        key: 'Once Upon a Time railroad; long waits; crane reveals',
        avoid: ['three men in long dusters waiting at a station', 'a man playing a harmonica'],
        briefs: [
          'At a lonely desert railroad station, a stationmaster’s widow in a lace dress waits on the platform as a fly buzzes around her and water drips steadily onto her hat from a leaking tank. No readable text or logo.',
          'A crane shot rises over a half-built railroad town to reveal an endless line of workers laying track. A train whistle echoes. No readable text or logo.',
          'An empty farmhouse table is set for a wedding feast in the desert. The door creaks in the wind. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Wild Bunch 1969 - Peckinpah Slow-Motion Twilight',
      'late sixties western cinema',
      [...T, 'wild-bunch'],
      {
        look: 'Sam Peckinpah The Wild Bunch (1969) look: dusty Mexican border towns, aging outlaws in a changing West, dusty Panavision, rapid cutting and slow-motion chaos.',
        subject: 'stage the subject in dusty sun-bleached border towns with slow-motion intensity.',
        color: 'Dust brown, sun white and faded denim.',
        light: 'Harsh sun and dust haze.',
        texture: westColor,
        camera: 'Rapid cutting mixed with slow motion.',
        mood: 'dusty twilight elegy',
        render: 'Authentic late-sixties Peckinpah frame.',
        key: 'Wild Bunch slow motion; aging outlaws; dusty border',
        briefs: [
          'In slow motion on a dusty border-town street, four aging outlaws in sweat-stained shirts walk side by side toward a fiesta while children run beside them waving paper streamers. No readable text or logo.',
          'Scorpions fight in a box surrounded by laughing children in the sun. An old man watches without smiling. No readable text or logo.',
          'An automobile, the first anyone has seen, sits in a dusty plaza. A horse stares at it. No readable text or logo.',
        ],
      },
    ),
    cr('El Topo 1970 - Jodorowsky Surreal Desert', 'seventies surreal western', [...T, 'el-topo'], {
      look: 'Alejandro Jodorowsky El Topo (1970) look: surreal acid western, white desert, symbolic tableaux, black-clad riders, umbrellas in the sun, pools of blood and mystical allegory.',
      subject: 'stage the subject in surreal symbolic tableaux across a white desert.',
      color: 'Bleached white desert, black costume and red accents.',
      light: 'Harsh white desert sun.',
      texture: westColor,
      camera: 'Frontal symbolic tableaux.',
      mood: 'surreal mystical allegory',
      render: 'Authentic seventies acid western frame.',
      key: 'El Topo surreal desert; symbolic tableaux; black riders',
      avoid: ['a black-clad rider with a naked child and an umbrella'],
      briefs: [
        'In a blinding white desert, a monk in a black hat balances a teacup on his head while a line of identical riders in black crosses the horizon under a single parasol. No readable text or logo.',
        'Four masters live in four strange homes in the desert. One lives inside a cage of rabbits. No readable text or logo.',
        'A single red rose grows from a skull in the white sand. A bee circles it. No readable text or logo.',
      ],
    }),
    cr(
      'McCabe & Mrs Miller 1971 - Altman Fogged Frontier',
      'seventies revisionist western',
      [...T, 'mccabe-miller'],
      {
        look: 'Robert Altman McCabe & Mrs. Miller (1971) look: Vilmos Zsigmond flashed-film fog, muddy Pacific Northwest mining town, snow and rain, candlelit saloons and overlapping murmured dialogue.',
        subject: 'stage the subject in foggy muddy frontier towns lit by candles and snow light.',
        color: 'Fogged amber, mud brown and snow grey.',
        light: 'Soft fogged candlelight and snow light.',
        texture: 'Flashed-negative seventies grain with milky fog and soft highlights.',
        camera: 'Slow zooms through foggy crowded rooms.',
        mood: 'melancholy fogged frontier',
        render: 'Authentic seventies revisionist western frame.',
        key: 'McCabe fog; muddy town; candlelit saloon; snow',
        briefs: [
          'In a foggy, candlelit frontier saloon being built around its customers, a fur-coated gambler shuffles cards while carpenters hammer the roof above and snow drifts in through the gaps. No readable text or logo.',
          'A muddy main street is half-built with raw planks under a light snowfall. A church steeple rises unfinished. No readable text or logo.',
          'An opium lamp glows in a steamy bathhouse at dusk. A pocket watch lies open on the bench. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
