import type { Create, Dna, Spec } from '../tools/apply';
import { STYLE_AVOID as AVOID } from './_style';

// Unit-based construction: each preset names its unit, its joint (grout, lead, gap, glue) and how
// light behaves on it. Presets must not share one generic "mosaic" template.
const words = (t: string) => t.split(/\s+/).filter(Boolean).length;
const pad = (t: string, min: number, tail: string) =>
  words(t) < min ? `${t.replace(/\.$/, '')}, ${tail}` : t;

function units(
  aesthetic: string,
  unit: string,
  joint: string,
  light: string,
  color: string,
  mood: string,
  key: string,
): Dna {
  return {
    aesthetic,
    subject_treatment: `Rebuild the prompt's subject and setting entirely from discrete units so it stays recognizable at card size — unit: ${unit}; joints: ${joint}.`,
    color_and_tone: pad(
      color,
      9,
      'with each unit holding one color so the image is built by juxtaposition.',
    ),
    lighting_and_shadow: pad(light, 9, 'as the physical behavior of this unit.'),
    texture_and_material: `${unit}, set with ${joint}, at a unit size that keeps the subject readable.`,
    camera_and_composition:
      'Keep the prompt framing; unit size and direction follow the subject contours so forms read clearly.',
    atmosphere_and_mood: pad(mood, 8, 'coming from the handcrafted construction.'),
    rendering_and_quality:
      'Crisp, consistent units and joints across the whole image, with no smeared or random fill.',
    key_features: key,
  };
}

const spec: Spec = {
  pack: 'pack_10',
  category: '8. Point, Mosaic And Glass Systems',
  updates: {
    'SP10-072': {
      name: 'Pointillism',
      dna: units(
        'Pointillism: the image built from small dots of pure color that mix optically.',
        'small round dots of pure unmixed paint',
        'visible canvas between dots',
        'Light comes from bright dot juxtaposition, no blending.',
        'Complementary pure colors placed side by side.',
        'Luminous, calm, patient and vibrant.',
        'pure color dots; optical mixing',
      ),
      avoid: AVOID,
      briefs: [
        'Pointillist painting of knights resting by a river at sunset, built from pure color dots. No text or logo.',
        'Pointillist dragon over a harbor. No text or logo.',
        'Pointillist castle garden. No text or logo.',
      ],
    },
    'SP10-073': {
      dna: units(
        'Stone tile mosaic: cut stone and ceramic tesserae laid in flowing rows.',
        'square and cut stone or ceramic tesserae',
        'grey grout lines',
        'Matte stone with slight surface unevenness.',
        'Earthy stone colors with bright accents.',
        'Ancient, durable, patient and crafted.',
        'cut tesserae; flowing rows; grout',
      ),
      avoid: AVOID,
      briefs: [
        'Stone tile mosaic of a dragon coiled around a tower, tesserae following its curves. No text or logo.',
        'Mosaic knight on horseback. No text or logo.',
        'Mosaic sea serpent. No text or logo.',
      ],
    },
    'SP10-074': {
      dna: units(
        'Stained glass: colored glass pieces joined by dark lead came, glowing with transmitted light.',
        'colored glass pieces',
        'dark lead came lines',
        'Transmitted light glowing through the glass.',
        'Jewel reds, blues, greens and gold.',
        'Sacred, luminous, grand and still.',
        'colored glass; lead came; transmitted glow',
      ),
      avoid: AVOID,
      briefs: [
        'Stained glass window of a knight slaying a serpent, glowing with transmitted light. No text or logo.',
        'Stained glass dragon. No text or logo.',
        'Stained glass owl. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Divisionist Color Dots',
      domain: 'divisionist brushwork',
      tags: ['divisionism', 'dots', 'unit-art'],
      dna: units(
        'Divisionism: short directional dashes and dots of separated color.',
        'short directional dashes of pure color',
        'small gaps',
        'Vibrating light from separated colors.',
        'Sunlit complementary pairs.',
        'Radiant, energetic, luminous and warm.',
        'directional color dashes',
      ),
      avoid: AVOID,
      briefs: [
        'Divisionist painting of a knight in a sunflower field built from directional color dashes. No text or logo.',
        'Divisionist castle. No text or logo.',
        'Divisionist dragon. No text or logo.',
      ],
    },
    {
      name: 'Byzantine Gold Tessera',
      domain: 'Byzantine gold mosaic',
      tags: ['byzantine', 'gold-mosaic', 'unit-art'],
      dna: units(
        'Byzantine mosaic: glass and gold-leaf tesserae set at angles to shimmer.',
        'glass and gold-leaf tesserae set at slight angles',
        'dark mortar gaps',
        'Shimmering gold catching light unevenly.',
        'Gold ground with deep blues and reds.',
        'Sacred, radiant, formal and eternal.',
        'gold-leaf tesserae; angled shimmer',
      ),
      avoid: AVOID,
      briefs: [
        'Byzantine gold mosaic of a crowned knight saint on a shimmering gold ground. No text or logo.',
        'Byzantine dragon. No text or logo.',
        'Byzantine peacock. No text or logo.',
      ],
    },
    {
      name: 'Roman Floor Mosaic',
      domain: 'Roman floor mosaic',
      tags: ['roman', 'floor-mosaic', 'unit-art'],
      dna: units(
        'Roman floor mosaic: small limestone tesserae in earthy tones with guilloche borders.',
        'small limestone and marble tesserae',
        'worn grout',
        'Matte worn stone.',
        'Terracotta, ochre, black and white.',
        'Ancient, grounded, archaeological and warm.',
        'limestone tesserae; guilloche border',
      ),
      avoid: AVOID,
      briefs: [
        'Roman floor mosaic of a gladiator fighting a dragon, framed by a guilloche border. No text or logo.',
        'Roman mosaic sea creatures. No text or logo.',
        'Roman mosaic hunting scene. No text or logo.',
      ],
    },
    {
      name: 'Micro-Mosaic',
      domain: 'micro-mosaic',
      tags: ['micro-mosaic', 'fine', 'unit-art'],
      dna: units(
        'Micro-mosaic: tiny glass rods cut into minute tesserae, painterly and fine.',
        'minute glass smalti cut from rods',
        'nearly invisible joints',
        'Soft glassy sheen.',
        'Rich painterly colors.',
        'Precious, delicate, refined and patient.',
        'minute smalti; painterly fine',
      ),
      avoid: AVOID,
      briefs: [
        "Micro-mosaic brooch of a knight's portrait made of minute glass tesserae. No text or logo.",
        'Micro-mosaic dragon. No text or logo.',
        'Micro-mosaic castle landscape. No text or logo.',
      ],
    },
    {
      name: 'Pique-Assiette Mosaic',
      domain: 'broken china mosaic',
      tags: ['pique-assiette', 'broken-china', 'unit-art'],
      dna: units(
        'Pique-assiette: broken china plates and cups reassembled into mosaic.',
        'broken china shards with floral patterns',
        'white grout',
        'Glossy glaze highlights.',
        'Blue-and-white and floral china.',
        'Whimsical, thrifty, colorful and homely.',
        'broken china shards; patterned pieces',
      ),
      avoid: AVOID,
      briefs: [
        'Broken-china mosaic of a dragon made of blue-and-white shards. No text or logo.',
        'Broken-china knight. No text or logo.',
        'Broken-china owl. No text or logo.',
      ],
    },
    {
      name: 'Pebble Mosaic',
      domain: 'pebble mosaic',
      tags: ['pebble', 'mosaic', 'unit-art'],
      dna: units(
        'Pebble mosaic: smooth river pebbles set on edge in patterns.',
        'smooth river pebbles set on edge',
        'packed mortar',
        'Wet sheen on pebbles.',
        'Black, white, grey and ochre pebbles.',
        'Earthy, patient, rhythmic and calm.',
        'pebbles on edge; flowing patterns',
      ),
      avoid: AVOID,
      briefs: [
        'Pebble mosaic courtyard of a spiraling dragon in black and white pebbles. No text or logo.',
        'Pebble mosaic knight. No text or logo.',
        'Pebble mosaic sun. No text or logo.',
      ],
    },
    {
      name: 'Sea Glass Mosaic',
      domain: 'sea glass mosaic',
      tags: ['sea-glass', 'mosaic', 'unit-art'],
      dna: units(
        'Sea glass: frosted rounded glass fragments assembled against light.',
        'frosted, rounded sea-glass fragments',
        'clear resin',
        'Soft backlit glow.',
        'Aqua, green, brown and white glass.',
        'Coastal, soft, calm and nostalgic.',
        'frosted sea glass; backlit',
      ),
      avoid: AVOID,
      briefs: [
        'Sea glass mosaic window of a sea serpent glowing aqua and green. No text or logo.',
        'Sea glass knight. No text or logo.',
        'Sea glass lighthouse. No text or logo.',
      ],
    },
    {
      name: 'Button Mosaic',
      domain: 'button mosaic',
      tags: ['buttons', 'mosaic', 'unit-art'],
      dna: units(
        'Button mosaic: hundreds of sewing buttons forming the image.',
        'assorted sewing buttons with holes',
        'fabric or board gaps',
        'Glossy button highlights.',
        'Assorted button colors.',
        'Playful, homely, crafty and charming.',
        'assorted buttons; visible holes',
      ),
      avoid: AVOID,
      briefs: [
        'Button mosaic of a knight on horseback made of hundreds of buttons. No text or logo.',
        'Button mosaic dragon. No text or logo.',
        'Button mosaic crown. No text or logo.',
      ],
    },
    {
      name: 'Fuse Bead Pixel Art',
      domain: 'fuse bead pixel art',
      tags: ['fuse-beads', 'pixel', 'unit-art'],
      dna: units(
        'Fuse beads: melted plastic tube beads on a pegboard grid.',
        'fused plastic tube beads with center holes',
        'grid adjacency',
        'Soft plastic sheen.',
        'Bright plastic colors.',
        'Playful, retro, crafty and nostalgic.',
        'fused tube beads; center holes',
      ),
      avoid: AVOID,
      briefs: [
        'Fuse-bead pixel art of a dragon with visible melted bead holes. No text or logo.',
        'Fuse-bead knight. No text or logo.',
        'Fuse-bead castle. No text or logo.',
      ],
    },
    {
      name: 'Rhinestone Mosaic',
      domain: 'rhinestone mosaic',
      tags: ['rhinestone', 'sparkle', 'unit-art'],
      dna: units(
        'Rhinestone mosaic: faceted crystals set edge to edge.',
        'faceted crystal rhinestones',
        'tight glue setting',
        'Sparkling facet flashes.',
        'Crystal colors.',
        'Glamorous, sparkling, kitsch and bright.',
        'faceted rhinestones; sparkle',
      ),
      avoid: AVOID,
      briefs: [
        'Rhinestone mosaic of a skull wearing a crown, sparkling. No text or logo.',
        'Rhinestone dragon. No text or logo.',
        'Rhinestone moth. No text or logo.',
      ],
    },
    {
      name: 'Opus Sectile Inlay',
      domain: 'opus sectile stone inlay',
      tags: ['opus-sectile', 'inlay', 'unit-art'],
      dna: units(
        'Opus sectile: large cut stone shapes fitted into a picture.',
        'large cut marble and stone shapes',
        'hairline joints',
        'Polished stone reflections.',
        'Colored marbles and porphyry.',
        'Grand, ancient, precise and noble.',
        'cut stone shapes; hairline joints',
      ),
      avoid: AVOID,
      briefs: [
        'Opus sectile panel of a lion attacking a stag in cut colored marble. No text or logo.',
        'Opus sectile knight. No text or logo.',
        'Opus sectile dragon. No text or logo.',
      ],
    },
    {
      name: 'Pietra Dura',
      domain: 'pietra dura hardstone inlay',
      tags: ['pietra-dura', 'inlay', 'unit-art'],
      dna: units(
        'Pietra dura: polished hardstones inlaid seamlessly into black marble.',
        'polished semi-precious hardstones',
        'invisible seamless joints',
        'High polish.',
        'Lapis, malachite, coral on black marble.',
        'Precious, refined, elegant and rich.',
        'hardstone inlay on black marble',
      ),
      avoid: AVOID,
      briefs: [
        'Pietra dura tabletop inlaid with a phoenix in lapis and coral on black marble. No text or logo.',
        'Pietra dura knight shield. No text or logo.',
        'Pietra dura flowers and dragonfly. No text or logo.',
      ],
    },
    {
      name: 'Marquetry Wood Inlay',
      domain: 'wood marquetry',
      tags: ['marquetry', 'wood', 'unit-art'],
      dna: units(
        'Marquetry: veneers of different woods cut and fitted into pictures.',
        'wood veneer pieces of different species',
        'tight fitted seams',
        'Satin varnish sheen.',
        'Wood tones from pale maple to dark ebony.',
        'Crafted, warm, refined and patient.',
        'wood veneers; fitted seams',
      ),
      avoid: AVOID,
      briefs: [
        'Marquetry panel of a knight riding past a castle in contrasting wood veneers. No text or logo.',
        'Marquetry dragon. No text or logo.',
        'Marquetry owl. No text or logo.',
      ],
    },
    {
      name: 'Tiffany Lampshade Glass',
      domain: 'tiffany-style lamp glass',
      tags: ['tiffany-glass', 'lamp', 'unit-art'],
      dna: units(
        'Tiffany-style lamp glass: opalescent glass pieces with copper-foil seams glowing warmly.',
        'opalescent streaky glass pieces',
        'copper-foil soldered seams',
        'Warm glow from within.',
        'Amber, green and dragonfly blues.',
        'Warm, ornate, cozy and luminous.',
        'opalescent glass; copper-foil seams; warm glow',
      ),
      avoid: AVOID,
      briefs: [
        'Tiffany-style lampshade glowing with a dragon wrapped around it in opalescent glass. No text or logo.',
        'Tiffany-style knight panel. No text or logo.',
        'Tiffany-style wisteria and moths. No text or logo.',
      ],
    },
    {
      name: 'Grisaille Leaded Glass',
      domain: 'grisaille painted glass',
      tags: ['grisaille', 'glass', 'unit-art'],
      dna: units(
        'Grisaille glass: clear and grey painted glass with fine lead lines and delicate shading.',
        'clear glass panes painted in grey grisaille',
        'thin lead lines',
        'Soft silvery transmitted light.',
        'Silver-grey with pale yellow stain accents.',
        'Austere, delicate, sacred and quiet.',
        'grey painted glass; thin lead',
      ),
      avoid: AVOID,
      briefs: [
        'Grisaille leaded window of a praying knight in silvery grey with yellow stain accents. No text or logo.',
        'Grisaille dragon. No text or logo.',
        'Grisaille vine window. No text or logo.',
      ],
    },
    {
      name: 'Fused Glass Slab',
      domain: 'fused glass',
      tags: ['fused-glass', 'glass', 'unit-art'],
      dna: units(
        'Fused glass: glass pieces kiln-fused into one slab with rounded edges and bubbles.',
        'kiln-fused glass pieces',
        'melted, rounded seams',
        'Backlit glow with bubbles.',
        'Saturated glass colors.',
        'Modern, glowing, crafted and fluid.',
        'kiln-fused glass; rounded seams; bubbles',
      ),
      avoid: AVOID,
      briefs: [
        'Fused glass panel of a phoenix with melted rounded seams and trapped bubbles, backlit. No text or logo.',
        'Fused glass knight. No text or logo.',
        'Fused glass jellyfish. No text or logo.',
      ],
    },
    {
      name: 'Paper Quilling Coils',
      domain: 'paper quilling',
      tags: ['quilling', 'paper', 'unit-art'],
      dna: units(
        'Quilling: rolled paper strip coils shaped and glued edge-on.',
        'rolled paper strip coils',
        'glued edge-on contact',
        'Soft shadows between coils.',
        'Paper colors.',
        'Delicate, crafty, intricate and charming.',
        'rolled paper coils; edge-on',
      ),
      avoid: AVOID,
      briefs: [
        'Paper quilling of a dragon made of rolled paper coils glued edge-on. No text or logo.',
        'Quilled knight. No text or logo.',
        'Quilled castle. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
