import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas material studies: the made objects of the middle ages as rendering materials.
// Five originals get card briefs; fifteen new studies add millefleur tapestry, gold couched
// embroidery, carved ivory, brass rubbings, inlaid floor tiles, pilgrim badges, repoussé gilt,
// oak misericords, gold-ground tempera, carved capitals, walrus-ivory game pieces, weathered
// gargoyles, tooled leather, bronze aquamaniles and painted wooden caskets.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'medieval-material', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'readable inscriptions', 'plastic or modern materials', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original figures';

const spec: Spec = {
  pack: 'pack_23',
  category: '3. Medieval Material Studies',
  updates: {
    'SP23-013': { briefs: [
      'Rising out of a woven sea of stepped blue and green planes, a leviathan lifts a whole fishing fleet on its back, every wave and fin built from bounded interlaced color fields. No readable text or logo.',
      "Up on a ladder picking apples, a gardener has not noticed that the goat below is eating the ladder, the whole scene built from interlaced color planes with slightly stepped edges. No readable text or logo.",
      'In interlaced planes of dusk violet and ochre, a solitary tower stands in a field and its single window is woven from a color that appears nowhere else. No readable text or logo.',
    ] },
    'SP23-014': { briefs: [
      'Stitched in continuous thread-like contours, a great wolf pads through a stitched snowstorm, and where the stitches thin out the bare linen shows through like breath in the cold. No readable text or logo.',
      "Gathering rosemary by a stone wall, an herbalist has not noticed a very small hedgehog carrying away her entire basket one sprig at a time, all in thread-like wool contours. No readable text or logo.",
      'In parallel stitch fills, a figure stands at a garden wall looking over it, and on the other side the stitches simply stop, leaving empty cloth. No readable text or logo.',
    ] },
    'SP23-015': { briefs: [
      'Painted in matte mineral pigments, a giant stands knee-deep in a river and lets a whole caravan cross over his outstretched arm like a bridge. No readable text or logo.',
      'In dry chalky fresco tones, a beekeeper offers a cup of water to a traveler, and the bees have formed a tiny second cup in the air beside it. No readable text or logo.',
      "Walking toward a distant hill in a long line, a procession of figures in faded reds and ochres keeps its eyes forward, except the last figure, who has turned around to look at us. No readable text or logo.",
    ] },
    'SP23-016': { briefs: [
      'On a broad curved shield of opaque enamel compartments, a blue dragon coils around a red sun, each scale a separate vitreous cell divided by bright gilt walls. No readable text or logo.',
      'Enameled in turquoise and white compartments on a small reliquary box, a proud rooster stands on top of a sleeping fox as if he personally defeated it. No readable text or logo.',
      'On an enamel plaque of deep blue cells, a single pale hand reaches out of a gilt cloud toward a small closed box. No readable text or logo.',
    ] },
    'SP23-017': { briefs: [
      'Through a tall leaded window of ruby and cobalt panes, a knight fights a many-headed serpent, the evening sun lighting each pane from behind so the serpent seems to move. No readable text or logo.',
      "Holding up a tiny lantern, a watchman painted inside a glass lantern guards an even tinier watchman who holds an even tinier lantern, every pane divided by dark lead lines. No readable text or logo.",
      "At night in an empty chapel, every glass pane of the window is dark except one small yellow pane where a painted face is still watching the pews. No readable text or logo.",
    ] },
  },
  creates: [
    study('Millefleur Tapestry', 'thousand-flower woven tapestry', 'millefleur', {
      aesthetic: 'Millefleur tapestry: woven wool and silk hangings with figures and animals floating on a dark ground densely scattered with hundreds of tiny flowering plants.',
      subject_treatment: `${keep}; float the subject on a dense dark ground of tiny woven flowers.`,
      color_and_tone: 'Deep blue-green or red ground with bright woven flowers and figures.',
      lighting_and_shadow: 'Flat woven color with hatched shading in wool.',
      texture_and_material: 'Visible weave, wool and silk sheen, hatched color steps.',
      camera_and_composition: 'Figures floating without horizon on the flowered field.',
      atmosphere_and_mood: 'Keep the requested mood with enchanted courtly stillness.',
      rendering_and_quality: 'Dense even flower scatter with clear woven figures.',
      key_features: 'thousand tiny flowers; dark woven ground; floating figures; wool texture',
    }, [], [
      'Floating on a dark field of a thousand woven flowers, a unicorn rests inside a small fence and looks at the viewer as if it knows it is being hunted. No readable text or logo.',
      "Playing a portable organ in a field of tiny woven flowers, a lady is accompanied by a lion and a rabbit who sing along badly and at completely different pitches. No readable text or logo.",
      'Among hundreds of woven flowers, one patch of the tapestry has unraveled into bare threads in the exact shape of a missing person. No readable text or logo.',
    ]),
    study('Gold Couched Embroidery', 'precious gold thread embroidery', 'couched-gold', {
      aesthetic: 'Gold couched embroidery: medieval luxury needlework with gold threads laid in patterns and couched down, silk split-stitch faces and jeweled seed-pearl borders.',
      subject_treatment: `${keep}; embroider the subject in silk split stitch against a shimmering couched gold ground.`,
      color_and_tone: 'Shimmering gold ground with silk blues, reds and greens.',
      lighting_and_shadow: 'Gold threads catch light differently as their direction changes.',
      texture_and_material: 'Couched gold threads, split-stitch silk and seed pearls.',
      camera_and_composition: 'Figures in arcaded panels on a vestment or hanging.',
      atmosphere_and_mood: 'Keep the requested mood with glittering sacred luxury.',
      rendering_and_quality: "Fine needlework detail with visible thread direction, kept consistent across the whole image.",
      key_features: 'couched gold ground; split-stitch silk; seed pearls; thread sheen',
    }, [], [
      'Embroidered in silk on a shimmering gold ground, a sea serpent rises beneath a tiny ship, its scales laid in gold thread that changes direction with every coil. No readable text or logo.',
      "Proudly showing off his new crown, an embroidered king has clearly been given one far too large by the needleworker, his silk face sliding under the rim against the shimmering ground. No readable text or logo.",
      "With the needle still pulling her last thread, a silk figure is sewing herself into the shimmering cloth, half of her already flat and stitched into the gold ground. No readable text or logo.",
    ]),
    study('Carved Ivory Relief', 'small carved ivory plaques', 'ivory-relief', {
      aesthetic: 'Carved ivory relief: small gothic ivory plaques and diptychs carved in deep relief, swaying figures under pointed arches, creamy surfaces with hints of old gilding.',
      subject_treatment: `${keep}; carve the subject as swaying relief figures in warm ivory.`,
      color_and_tone: 'Warm cream and honey ivory with faint traces of gold and paint.',
      lighting_and_shadow: 'Soft raking light and deep shadows in the carved recesses.',
      texture_and_material: 'Smooth polished ivory, fine grain lines and hairline cracks.',
      camera_and_composition: "Framed relief panels under small pointed arches, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with intimate precious devotion.',
      rendering_and_quality: "Delicate carving with believable ivory translucency, kept consistent across the whole image.",
      key_features: 'deep relief; swaying figures; pointed arches; warm polished ivory',
    }, [], [
      "Storming a castle defended by ladies who are throwing roses, a troop of knights is clearly losing, the whole battle cut deep into a small creamy ivory panel. No readable text or logo.",
      'In a creamy ivory relief under little pointed arches, a lover kneels to offer a ring to a lady who is clearly more interested in his falcon. No readable text or logo.',
      'On an ivory diptych, the left panel shows a woman looking at a mirror and the right panel shows the mirror looking back at her. No readable text or logo.',
    ]),
    study('Brass Rubbing Effigy', 'rubbed memorial brass image', 'brass-rubbing', {
      aesthetic: 'Brass rubbing effigy: waxy rubbings taken from engraved memorial brasses, life-size flat figures in armor or gowns rendered in gold or black wax on dark paper.',
      subject_treatment: `${keep}; show the subject as a flat engraved effigy captured by wax rubbing.`,
      color_and_tone: 'Gold or black wax on black or cream paper.',
      lighting_and_shadow: "No lighting, only rubbed line and tone, kept consistent across the whole image.",
      texture_and_material: 'Waxy crayon grain, raised line edges and paper texture.',
      camera_and_composition: 'Full-length frontal effigy lying flat, feet on a small animal.',
      atmosphere_and_mood: 'Keep the requested mood with quiet memorial calm.',
      rendering_and_quality: "Clean engraved outlines with even waxy grain, kept consistent across the whole image.",
      key_features: 'wax rubbing grain; flat effigy; engraved outlines; dark paper',
    }, ['readable epitaphs'], [
      'Rubbed in gold wax on black paper, a full-length knight lies with his feet resting on a sleeping lion that has one eye slightly open. No readable text or logo.',
      'In a black wax rubbing, a merchant\'s effigy lies calmly with his feet on a small dog, while the dog is chewing the edge of his robe. No readable text or logo.',
      'On gold-rubbed black paper, a lady\'s effigy lies with her hands together, and the rubbing shows faint fingerprints of someone pushing up from underneath. No readable text or logo.',
    ]),
    study('Inlaid Floor Tile', 'two-color inlaid clay tiles', 'inlaid-tile', {
      aesthetic: 'Inlaid floor tile: medieval two-color clay tiles, red earthenware inlaid with pale yellow slip designs of beasts, heraldry and foliage, worn smooth by feet.',
      subject_treatment: `${keep}; inlay the subject in pale slip on red clay tiles in a repeating floor.`,
      color_and_tone: 'Brick red clay with cream or yellow slip and a thin glaze.',
      lighting_and_shadow: "Glossy glaze highlights and worn matte patches, kept consistent across the whole image.",
      texture_and_material: 'Worn glaze, chipped corners, grout lines and slip inlay.',
      camera_and_composition: 'Top-down view of a tile or a floor of tiles.',
      atmosphere_and_mood: 'Keep the requested mood with worn centuries of footsteps.',
      rendering_and_quality: "Clear two-color design with believable wear, kept consistent across the whole image.",
      key_features: 'red clay; yellow slip inlay; worn glaze; repeating tiles',
    }, [], [
      'On a worn red clay floor, the inlaid yellow griffin on one tile is breaking free and stepping onto the tile next to it. No readable text or logo.',
      'Across a floor of two-color tiles, every tile shows a proud lion except one, which shows a small cat that is sure it belongs there. No readable text or logo.',
      'Seen from above, a tiled floor of inlaid beasts has been worn smooth except for one path of footprints leading to a tile that shows a closed trapdoor. No readable text or logo.',
    ]),
    study('Pilgrim Badge Pewter', 'cast lead-tin souvenir badges', 'pilgrim-badge', {
      aesthetic: 'Pilgrim badge pewter: small cheap lead-tin openwork badges cast in stone molds, souvenirs of shrines with tiny figures, ships and symbols, dull grey and slightly bent.',
      subject_treatment: `${keep}; cast the subject as a tiny openwork pewter badge with a pin.`,
      color_and_tone: "Dull grey pewter with dark oxidation, kept consistent across the whole image.",
      lighting_and_shadow: "Soft metallic highlights on raised parts, kept consistent across the whole image.",
      texture_and_material: 'Rough cast metal, openwork gaps, bent pins and mold seams.',
      camera_and_composition: "Single badge on dark cloth or earth, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with humble traveler devotion.',
      rendering_and_quality: "Crude charming casting with believable wear, kept consistent across the whole image.",
      key_features: 'openwork pewter; tiny figures; bent pin; dull oxidation',
    }, ['readable inscriptions'], [
      'On dark river mud, a tiny pewter badge of a ship full of pilgrims has been found, and the little cast sailors seem to be rowing it toward the water. No readable text or logo.',
      'A cheap pewter souvenir badge shows a heroic saint slaying a monster, but the casting went wrong and the monster came out much cuter. No readable text or logo.',
      'On black cloth, a bent pewter badge of a small openwork door has been pinned upside down, and something inside the door is looking out. No readable text or logo.',
    ]),
    study('Repoussé Gilt Metal', 'hammered gilded relief metal', 'repousse', {
      aesthetic: 'Repoussé gilt metal: thin sheets of copper or silver hammered from behind into relief, then gilded and set with cabochon stones, as on reliquaries and book covers.',
      subject_treatment: `${keep}; hammer the subject into raised gilded relief with stones set around it.`,
      color_and_tone: 'Warm gilded copper, silver and rich cabochon reds and blues.',
      lighting_and_shadow: 'Bright metallic highlights on raised forms, dark recesses.',
      texture_and_material: 'Hammer marks, punched grounds, gilding wear and polished stones.',
      camera_and_composition: "Frontal relief panel filling the card, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with heavy precious splendor.',
      rendering_and_quality: "Convincing hammered relief with jeweled accents, kept consistent across the whole image.",
      key_features: 'hammered relief; gilded metal; cabochon stones; punched ground',
    }, [], [
      'Hammered out of gilded copper, a lion with cabochon ruby eyes roars from a reliquary lid while tiny hammered villagers hide behind the jewels. No readable text or logo.',
      'On a gilt metal book cover, a very round hammered bishop has clearly been hit too many times by the craftsman\'s hammer and looks dizzy. No readable text or logo.',
      'Set among cabochon stones, a repoussé face in gilded silver has its eyes closed, except when light from a candle falls on it, when one eye appears open. No readable text or logo.',
    ]),
    study('Carved Oak Misericord', 'humorous choir seat carving', 'misericord', {
      aesthetic: 'Carved oak misericord: small hidden carvings under choir seats, dark polished oak showing humorous everyday scenes, fights, beasts and fools framed by leafy supporters.',
      subject_treatment: `${keep}; carve the subject in dark oak as a small humorous relief with leafy side roundels.`,
      color_and_tone: 'Dark honey and black oak with polished highlights.',
      lighting_and_shadow: "Warm low light raking across the carving, kept consistent across the whole image.",
      texture_and_material: 'Wood grain, chisel marks, polished edges and dust in recesses.',
      camera_and_composition: 'Central carved scene with two leafy roundels at the sides.',
      atmosphere_and_mood: 'Keep the requested mood with hidden medieval humor.',
      rendering_and_quality: "Clear carved relief with believable old wood, kept consistent across the whole image.",
      key_features: 'dark oak; hidden humor; leafy roundels; chisel marks',
    }, [], [
      "Chasing her husband around the kitchen with a ladle, a furious wife does not see the dog stealing the dinner, the scene hidden in dark oak under a choir seat. No readable text or logo.",
      'On a polished misericord, a fox preaches to a row of geese from a pulpit, and one goose in the back is quietly sharpening a knife. No readable text or logo.',
      'In a dark oak carving hidden beneath a seat, a small grinning face peers out between leaves as if it has been waiting centuries for someone to look. No readable text or logo.',
    ]),
    study('Gold-Ground Tempera Panel', 'egg tempera on gold panel', 'gold-tempera', {
      aesthetic: 'Gold-ground tempera panel: egg tempera painted on wooden panels with tooled gold backgrounds, fine hatched modeling, green underpaint in flesh and punched halos.',
      subject_treatment: `${keep}; paint the subject in fine hatched tempera against a tooled gold ground.`,
      color_and_tone: 'Gold ground with lapis, vermilion and green-toned flesh.',
      lighting_and_shadow: "Soft hatched modeling, gold glowing behind, kept consistent across the whole image.",
      texture_and_material: 'Egg tempera hatching, punched gold patterns and craquelure.',
      camera_and_composition: 'Figures on shallow ground under a pointed panel top.',
      atmosphere_and_mood: 'Keep the requested mood with serene luminous stillness.',
      rendering_and_quality: "Delicate hatched tempera with punched gold detail, kept consistent across the whole image.",
      key_features: 'tooled gold ground; hatched tempera; punched halos; wooden panel',
    }, [], [
      "Reading calmly in the desert, a hermit does not notice that the lion behind him has fallen asleep on his feet, the painted panel punched with gold stars around them. No readable text or logo.",
      "Wearing a punched halo, a solemn ox seems very aware of its own importance and poses accordingly against a glowing background of tooled gold. No readable text or logo.",
      'In fine hatched tempera on gold, a woman stands in a doorway looking out, and the gold behind her has been scratched away in the shape of a second figure. No readable text or logo.',
    ]),
    study('Carved Stone Capital', 'romanesque figured capitals', 'stone-capital', {
      aesthetic: 'Carved stone capital: romanesque column capitals carved with crowded beasts, acrobats, demons and foliage that wrap around the stone block, worn and lichen-stained.',
      subject_treatment: `${keep}; carve the subject wrapping around a column capital among beasts and foliage.`,
      color_and_tone: 'Warm limestone with grey weathering and faint old paint.',
      lighting_and_shadow: 'Strong light from above, deep shadows under the carving.',
      texture_and_material: "Chiseled stone, weathered edges, lichen and dust, kept consistent across the whole image.",
      camera_and_composition: 'Close view of one capital atop a column in a cloister.',
      atmosphere_and_mood: 'Keep the requested mood with strange ancient vitality.',
      rendering_and_quality: "Crowded vigorous carving with believable weathering, kept consistent across the whole image.",
      key_features: 'column capital; wrapped beasts; chiseled foliage; lichen stone',
    }, [], [
      'Wrapped around a stone column capital, two lions share a single head at the corner, and both bodies are trying to walk in opposite directions. No readable text or logo.',
      'On a worn capital, a carved acrobat balances upside down holding up the whole roof with his feet and looking very tired about it. No readable text or logo.',
      "Covering its eyes with both hands among the stone leaves of a cloister column, a small carved demon seems to have seen something even it could not bear. No readable text or logo.",
    ]),
    study('Walrus-Ivory Game Piece', 'carved medieval chess figures', 'ivory-chessman', {
      aesthetic: 'Walrus-ivory game piece: squat carved chess figures with bulging eyes, worried faces, shields and swords, carved from walrus tusk with a stained creamy finish.',
      subject_treatment: `${keep}; carve the subject as a squat bug-eyed game piece in stained ivory.`,
      color_and_tone: 'Creamy ivory with brown staining and faint red traces.',
      lighting_and_shadow: 'Soft side light with small cast shadows on a board.',
      texture_and_material: 'Carved tusk grain, cracks, worn edges and incised patterns.',
      camera_and_composition: 'One or a few pieces standing on a board close up.',
      atmosphere_and_mood: 'Keep the requested mood with grumpy tabletop character.',
      rendering_and_quality: "Convincing carved ivory with expressive faces, kept consistent across the whole image.",
      key_features: 'squat figures; bulging eyes; stained ivory; incised patterns',
    }, [], [
      'On an old game board, a squat ivory warrior bites the top of his shield in rage because his side has only three pieces left. No readable text or logo.',
      'A worried ivory queen with bulging eyes holds her cheek in her hand, looking at a very small ivory mouse that has appeared on the board. No readable text or logo.',
      'Standing alone on an empty board in a dark hall, a single ivory king waits, and the shadows of many other pieces surround him. No readable text or logo.',
    ]),
    study('Weathered Gargoyle Stone', 'grotesque rooftop stone carving', 'gargoyle', {
      aesthetic: 'Weathered gargoyle stone: grotesque carved waterspouts and chimeras on gothic rooftops, open-mouthed beasts stained black by rain, moss in every crevice.',
      subject_treatment: `${keep}; carve the subject as a weathered grotesque perched on a gothic roof ledge.`,
      color_and_tone: 'Grey limestone streaked black with rain and green moss.',
      lighting_and_shadow: 'Overcast sky or stormy dusk light with deep shadows.',
      texture_and_material: 'Eroded stone, rain streaks, moss, pigeon feathers and cracks.',
      camera_and_composition: 'Close view of the grotesque with rooftops or city below.',
      atmosphere_and_mood: 'Keep the requested mood with brooding watchful menace.',
      rendering_and_quality: "Convincing weathered stone with rain detail, kept consistent across the whole image.",
      key_features: 'grotesque carving; rain-stained stone; moss; rooftop height',
    }, [], [
      'Perched high on a cathedral roof in a storm, a weathered stone gargoyle spews rainwater onto the street and its carved eyes are following a single figure below. No readable text or logo.',
      'On a rooftop ledge, a gargoyle with its mouth wide open has a family of pigeons living inside its throat and looks deeply offended. No readable text or logo.',
      'At dusk above the city, one of a row of stone grotesques has turned its head in a different direction than yesterday. No readable text or logo.',
    ]),
    study('Tooled Leather Binding', 'blind-tooled leather book cover', 'tooled-leather', {
      aesthetic: 'Tooled leather binding: medieval book covers in brown calf blind-tooled with small stamps of beasts, rosettes and lattices, brass bosses and clasps.',
      subject_treatment: `${keep}; press the subject into leather as repeated stamped tools and a central panel.`,
      color_and_tone: 'Warm brown and dark tan leather with tarnished brass.',
      lighting_and_shadow: "Raking light reveals the pressed impressions, kept consistent across the whole image.",
      texture_and_material: 'Blind-tooled stamps, scuffed leather, brass bosses and clasps.',
      camera_and_composition: 'Top-down view of a book cover filling the card.',
      atmosphere_and_mood: 'Keep the requested mood with old library mystery.',
      rendering_and_quality: "Crisp stamped impressions with believable wear, kept consistent across the whole image.",
      key_features: 'blind-tooled stamps; brown calf; brass bosses; raking light',
    }, ['readable title'], [
      'On a brown leather book cover, a stamped dragon repeats across the lattice pattern, and in one square the dragon has escaped, leaving an empty pressed outline. No readable text or logo.',
      "Among rows of stamped lions on a brown calf cover, one stamped cat has been pressed in by a mischievous binder and sits proudly in the middle of the pattern. No readable text or logo.",
      'On an old leather cover with brass clasps, a pressed pattern of eyes has one eye that shows scuff marks as if it has been blinking. No readable text or logo.',
    ]),
    study('Cast Bronze Aquamanile', 'animal-shaped bronze water vessel', 'aquamanile', {
      aesthetic: 'Cast bronze aquamanile: medieval water vessels cast in bronze as lions, horses, knights and dragons, with spouts in their mouths and handles on their backs.',
      subject_treatment: `${keep}; cast the subject as a bronze pouring vessel with a spout and handle.`,
      color_and_tone: 'Warm bronze with green patina and polished highlights.',
      lighting_and_shadow: "Museum spotlight with soft reflections on bronze, kept consistent across the whole image.",
      texture_and_material: 'Cast bronze, incised fur patterns, patina and wear.',
      camera_and_composition: "Single vessel on a plinth, three-quarter view, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with proud whimsical craft.',
      rendering_and_quality: "Convincing cast metal with charming stylization, kept consistent across the whole image.",
      key_features: 'animal vessel; spout mouth; back handle; bronze patina',
    }, [], [
      'A bronze lion vessel with a spout in its roaring mouth is pouring water onto the hands of a tiny bronze knight who rides on its back as the handle. No readable text or logo.',
      'On a plinth, a bronze horse aquamanile has clearly been cast with a surprised expression, as if someone just poured water into its head. No readable text or logo.',
      'In a dark museum case, a bronze beast-shaped vessel has a thin trickle of water running from its spout although no one has filled it in centuries. No readable text or logo.',
    ]),
    study('Painted Wooden Casket', 'small painted wooden chest', 'painted-casket', {
      aesthetic: 'Painted wooden casket: small medieval chests painted with courtly love scenes, heraldry and animals in tempera, with iron hinges and worn gilded edges.',
      subject_treatment: `${keep}; paint the subject on the panels and lid of a small wooden casket.`,
      color_and_tone: 'Faded red, green and gold tempera on wood.',
      lighting_and_shadow: 'Warm soft light on the box and its iron fittings.',
      texture_and_material: 'Worn tempera, wood grain, iron hinges and flaking gilt.',
      camera_and_composition: 'Three-quarter view of the casket with lid slightly open.',
      atmosphere_and_mood: 'Keep the requested mood with secret treasured keepsakes.',
      rendering_and_quality: "Delicate painted scenes with believable wear, kept consistent across the whole image.",
      key_features: 'painted panels; iron hinges; courtly scenes; flaking gilt',
    }, [], [
      'On a small painted casket, a lover climbs a ladder to a castle window on one panel, and on the next panel he is running away from her furious father. No readable text or logo.',
      'The lid of a painted wooden chest shows a goose dressed as a lady, courted by a very hopeful fox in a feathered hat. No readable text or logo.',
      "From the dark inside of a slightly open wooden chest, painted fingers curl over the painted edge of the lid, as if the courtly lovers on its panels want to climb out. No readable text or logo.",
    ]),
  ],
};

export default spec;
