import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID, style } from './_style';

// Fluid & Organic: the fluid process is how the image is made. It does not add smoke, liquid or
// bubbles as props to a scene unless the prompt asks for them.
const AVOID = [...STYLE_AVOID, 'adding literal liquid or smoke props to the scene'];

const spec: Spec = {
  pack: 'pack_10',
  category: '2. Fluid & Organic',
  updates: {
    'SP10-011': {
      dna: style(
        'Alcohol ink: vivid translucent inks spreading and pushing each other into cells with dark edge rings.',
        'the subject is painted in flowing alcohol ink whose pooled edges define its contours.',
        'Saturated translucent teal, magenta, gold and violet.',
        'Glowing translucency on white yupo.',
        'Ink cells, dark edge rings and metallic veins.',
        'Flowing organic fields shaping the subject.',
        'Vivid, fluid, spontaneous and luminous.',
        'Wet translucent finish.',
        'alcohol ink cells; dark edge rings; metallic veins',
      ),
      avoid: AVOID,
      briefs: [
        "A serpent coils through the page as flowing teal and gold cells shove against each other, each one ringed in a dark edge. No readable text or logo.",
        "A jellyfish drifts in deep water where translucent magenta and violet pigments push into each other and form bubbling cells. No readable text or logo.",
        "A cliffside village melts downhill into the sea as turquoise and gold pools meet in dark rings along every street. No readable text or logo.",
      ],
    },
    'SP10-012': {
      dna: style(
        'Smoke photography style: the subject drawn as thin wisps of backlit smoke on black.',
        "the subject's outline is traced by curling smoke filaments on black.",
        'White or tinted smoke on pure black.',
        'Hard side backlight raking through the smoke against pure black, so only the thin wisps catch light and everything else falls away.',
        'Thin curling smoke filaments.',
        'Subject centered against black.',
        'Ethereal, delicate, mysterious and fleeting.',
        'Crisp high-contrast studio photograph with sharp wisp edges, deep clean blacks and no stray haze or grain.',
        'smoke filaments tracing form; black ground',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "A horse and rider gallop out of pure black, traced entirely by thin curling wisps of backlit white vapor, the mane dissolving behind them. No readable text or logo.",
        "A heron lifts off in wings drawn by thin backlit wisps curling on black, its long neck a single graceful thread. No readable text or logo.",
        "A woman's profile forms from fine backlit wisps on black, her hair breaking into delicate curls that drift off the frame. No readable text or logo.",
      ],
    },
    'SP10-013': {
      dna: style(
        'Oil slick: iridescent thin-film color swirls forming the subject.',
        'the subject is formed from swirling rainbow thin-film color on dark ground.',
        'Iridescent rainbow over black.',
        'Soft sheen with interference colors.',
        'Thin-film swirls and marbling.',
        'Swirling field shaping the subject.',
        'Hypnotic, toxic, beautiful and fluid.',
        'Glossy finish.',
        'iridescent thin-film swirls; dark ground',
      ),
      avoid: AVOID,
      briefs: [
        "A serpent coils across black water in iridescent thin-film swirls, magenta, gold and teal bands following its scales. No readable text or logo.",
        "A dancer's spinning skirt becomes iridescent film on black, rainbow bands whirling outward from her waist. No readable text or logo.",
        "A moth rests on a black puddle, its wings patterned by purple and green interference bands. No readable text or logo.",
      ],
    },
    'SP10-014': {
      dna: style(
        'Macro bubble: the subject seen inside or reflected on a giant soap-bubble surface.',
        'the subject is reflected and wrapped on the curved surface of a huge bubble with thin-film swirls.',
        'Iridescent swirls with dark background.',
        'Soft backlight and a few small reflected highlights on the bubble film, the curved surface bending the light behind it.',
        'Thin-film surface with swirling interference.',
        'Spherical framing.',
        'Dreamy, fragile, cosmic and delicate.',
        'Crisp macro photograph with shallow depth, true thin-film interference color and clean dark background.',
        'giant bubble surface; iridescent swirls; spherical framing',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "A fortress on a hill is reflected and warped across the surface of a giant iridescent bubble about to pop. No readable text or logo.",
        "A grandfather's delighted face bends and stretches on the curved skin of a giant bubble, rainbow film sliding across his nose. No readable text or logo.",
        "A whole city skyline floats inside a giant bubble, curved reflections and swirling interference colors around a thin black spot. No readable text or logo.",
      ],
    },
    'SP10-015': {
      dna: style(
        'Mycelium network: the subject built from branching white fungal threads and nodes.',
        'the subject is woven from branching mycelial threads and glowing nodes.',
        'White threads on dark soil or glowing blue-green.',
        'Soft glow at nodes.',
        'Fine branching hyphae and nodes.',
        'Network fill across the frame.',
        'Organic, interconnected, eerie and alive.',
        'Fine detailed finish.',
        'branching hyphae; glowing nodes; network',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "A stag stands on dark soil, its body and antlers woven from glowing white fungal threads that keep growing into the ground. No readable text or logo.",
        "A human skull on forest soil is built from branching white threads and nodes, fine filaments spreading from its eye sockets. No readable text or logo.",
        "A tree's roots, trunk and canopy are glowing white threads and nodes, connected underground to every mushroom around it. No readable text or logo.",
      ],
    },
    'SP10-016': {
      dna: style(
        'Ferrofluid: black magnetic liquid spiking into sharp cones.',
        'the subject is sculpted from glossy black ferrofluid spikes.',
        'Glossy black with reflected highlights.',
        'Hard studio light raking across the spikes so each cone carries a bright specular edge and a deep shadow side.',
        'Liquid spikes with mirror gloss.',
        'Centered spiky form.',
        'Alien, tense, sleek and strange.',
        'Glossy macro photograph with razor-sharp spike tips, liquid reflections and a clean black or white backdrop.',
        'ferrofluid spikes; glossy black',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "Glossy black spikes rise into a beast's crest above a hidden magnet, sharp cones reflecting a softbox. No readable text or logo.",
        "On a mirror plate a crown of glossy black magnetic liquid stands up in sharp reflective cones. No readable text or logo.",
        "On a white dish a hedgehog curls up, its back a field of glossy black magnetic spikes shimmering under studio light. No readable text or logo.",
      ],
    },
    'SP10-017': {
      dna: style(
        'Acrylic pour: cells and lacing from poured acrylic layers forming the subject.',
        'the subject emerges from poured acrylic cells and lacing.',
        'Saturated poured colors with white lacing.',
        'Glossy flat light.',
        'Cells, lacing and glossy pour.',
        'Flowing pour across the frame.',
        'Playful, vivid, organic and flowing.',
        'Glossy finish.',
        'acrylic cells; lacing; glossy pour',
      ),
      avoid: AVOID,
      briefs: [
        "A phoenix spreads wings of poured cells and lacing in crimson, gold and white, the layers splitting into round craters. No readable text or logo.",
        "A mountain range at dusk is poured in violet, pink and white layers that break into cells along the ridgelines. No readable text or logo.",
        "A whale breaches in poured blue and white cells, lacing trails splashing off its body like spray. No readable text or logo.",
      ],
    },
    'SP10-018': {
      dna: style(
        'Reaction-diffusion: labyrinthine Turing patterns of spots and stripes forming the subject.',
        'the subject is filled and shaped by Turing-pattern spots and maze stripes.',
        'Two-tone contrast.',
        'Flat.',
        'Maze-like stripes and spots.',
        'Pattern fill following contours.',
        'Organic, mathematical, alien and precise.',
        'Crisp finish.',
        'Turing patterns; maze stripes; spots',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "A leopard's spots grow into labyrinthine stripes across its body, black and amber mazes on cream. No readable text or logo.",
        "An egg is covered in labyrinthine spots and stripes in teal and cream, the maze tightening toward the tip. No readable text or logo.",
        "A coral reef's branches are grown from self-organizing maze stripes in coral pink and deep blue. No readable text or logo.",
      ],
    },
    'SP10-019': {
      dna: style(
        'Cymatics: sand or liquid patterns formed by sound vibration — concentric nodal geometry.',
        'the subject is built from cymatic nodal patterns of sand or liquid.',
        'Sand on dark plate or liquid ripples.',
        'Raking light on ridges.',
        'Nodal sand lines and ripples.',
        'Radial symmetric pattern.',
        'Mystical, harmonic, precise and resonant.',
        'Crisp finish.',
        'cymatic nodal pattern; radial symmetry',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "Sand dancing on a vibrating black plate settles into a heraldic crest of concentric nodal rings and petals. No readable text or logo.",
        "A rose window pattern appears in sand on a humming plate, twelve radiating petals of nodal geometry. No readable text or logo.",
        "A vibrating dish of water forms an eye of rippling concentric rings, light glinting on the standing waves. No readable text or logo.",
      ],
    },
    'SP10-020': {
      dna: style(
        'Nebula cloud: the subject formed of glowing interstellar gas, dust lanes and stars.',
        'the subject is shaped from glowing nebula gas and dark dust lanes.',
        'Magenta, teal and gold gas with stars.',
        'Self-luminous glow.',
        'Gas filaments, dust and starfields.',
        'Cosmic scale framing.',
        'Awe-filled, cosmic, silent and vast.',
        'Deep-space finish.',
        'glowing nebula gas; dust lanes; stars',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "A colossal horse and rider form from glowing magenta and teal interstellar gas, dark dust lanes shaping the mane. No readable text or logo.",
        "A crowned skull glows in violet gas and dark dust lanes, blue star clusters sparkling in its eye sockets. No readable text or logo.",
        "A vast whale swims through space in teal gas and dust lanes, stars shining through its fins. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Floating Ink Marbling',
      domain: 'marbled paper pattern',
      tags: ['marbling', 'paper', 'fluid'],
      dna: style(
        'Paper marbling: combed and swirled floating paints transferred to paper in feathered and peacock patterns.',
        'the subject is formed by combed marbling swirls and feathered pattern.',
        'Indigo, ochre, oxblood and cream.',
        'Flat printed paper.',
        'Combed swirls and feathered edges.',
        'Pattern flowing along the subject.',
        'Elegant, antique, fluid and intricate.',
        'Crisp printed finish.',
        'combed marbling; feathered swirls; antique paper',
      ),
      avoid: AVOID,
      briefs: [
        "A sea serpent's body is combed indigo and ochre, feathered patterns running along its coils and peacock swirls in its eye. No readable text or logo.",
        "A peacock's tail blooms in teal, gold and rust peacock-pattern swirls, combed feathering along its body. No readable text or logo.",
        "A full moon hangs over rolling waves, swirled indigo for the sea and a pale feathered disc above. No readable text or logo.",
      ],
    },
    {
      name: 'Resin Geode Pour',
      domain: 'resin geode art',
      tags: ['resin', 'geode', 'fluid'],
      dna: style(
        'Resin geode: poured resin rings with crystal centers and gold edges.',
        'the subject is built from concentric resin rings with crystal centers and gold veins.',
        'Deep blue, amethyst, white and gold.',
        'Glossy reflective light.',
        'Glossy resin rings, crystals and gold leaf.',
        'Concentric rings following the subject.',
        'Luxurious, glossy, mineral and vivid.',
        'Glossy finish.',
        'resin rings; crystal centers; gold veins',
      ),
      avoid: AVOID,
      briefs: [
        "A human eye is poured in concentric amethyst and teal rings with gold edge veins, a crystal cluster for the pupil. No readable text or logo.",
        "An egg of poured concentric rings in deep green and white opens to a sparkling crystal center rimmed in gold leaf. No readable text or logo.",
        "A round tabletop holds poured ocean-blue rings, crystal clusters at its center and gold veins along the edge. No readable text or logo.",
      ],
    },
    {
      name: 'Lava Lamp Blobs',
      domain: 'lava lamp blobs',
      tags: ['lava-lamp', 'blobs', 'fluid'],
      dna: style(
        'Lava lamp: soft rising wax blobs merging and splitting in glowing liquid.',
        'the subject is formed by soft glowing wax blobs.',
        'Warm orange, magenta and purple glow.',
        'Backlit glow.',
        'Soft wax blobs and warm liquid.',
        'Vertical flowing blobs.',
        'Retro, dreamy, slow and warm.',
        'Soft glowing finish.',
        'glowing wax blobs; merging; retro glow',
      ),
      avoid: AVOID,
      briefs: [
        "A phoenix rises from glowing orange wax blobs merging and splitting in red liquid, lit from below. No readable text or logo.",
        "A slow-dancing couple are two soft glowing blobs drifting together and merging into one inside warm purple liquid, lit from below like a nightclub. No readable text or logo.",
        "A jellyfish of rising green blobs stretches its tentacles through glowing yellow liquid until they split. No readable text or logo.",
      ],
    },
    {
      name: 'Dendritic Ink Growth',
      domain: 'dendritic branching ink',
      tags: ['dendrite', 'ink', 'fluid'],
      dna: style(
        'Dendritic growth: branching fern-like ink or mineral dendrites forming the subject.',
        'the subject is traced by branching dendritic ink growth.',
        'Black or iron-brown dendrites on pale ground.',
        'Flat.',
        'Fine branching dendrites.',
        'Branching outward from centers.',
        'Organic, fractal, delicate and eerie.',
        'Fine finish.',
        'dendritic branching; fern-like growth',
      ),
      avoid: AVOID,
      briefs: [
        "A tree-shaped figure spreads across white paper in branching black fern-like tendrils with fine fractal edges. No readable text or logo.",
        "On a slate tile a crown of branching mineral tendrils grows in fern-like black and rust. No readable text or logo.",
        "A lightning strike over a sleeping harbor branches out as black tendrils creeping through wet paper, each fork splitting into finer fern-like threads. No readable text or logo.",
      ],
    },
    {
      name: 'Salt-Bloom Watercolor',
      domain: 'salt-textured watercolor',
      tags: ['watercolor', 'salt', 'fluid'],
      dna: style(
        'Salt-bloom watercolor: wet washes with salt crystals creating starry blooms.',
        'the subject is painted in wet washes with salt blooms scattered through.',
        'Deep blues, violets and greens.',
        'Soft paper light.',
        'Salt starbursts, blooms and granulation.',
        'Loose wash composition.',
        'Magical, soft, starry and fluid.',
        'Wet paper finish.',
        'salt starbursts; wet washes',
      ),
      avoid: AVOID,
      briefs: [
        "A hilltop monastery at night sits under a deep indigo wash scattered with starry crystal blooms. No readable text or logo.",
        "An owl on a snowy branch is washed in grey-blue, crystals leaving starry textures across its feathers. No readable text or logo.",
        "A sea serpent rises in a green wave, crystal blooms bursting across the water like foam and stars. No readable text or logo.",
      ],
    },
    {
      name: 'Coffee Stain Bloom',
      domain: 'coffee and tea stain painting',
      tags: ['coffee', 'stain', 'fluid'],
      dna: style(
        'Coffee stain painting: brown coffee washes with dark tide rings and blooms.',
        'the subject is painted in coffee washes with darker drying rings.',
        'Sepia and brown tones.',
        'Soft paper light.',
        'Stain rings, blooms and drips.',
        'Loose composition.',
        'Warm, nostalgic, humble and intimate.',
        'Paper finish.',
        'coffee washes; tide rings',
      ),
      avoid: AVOID,
      briefs: [
        "A monk reading by a window is painted in brown washes, dark tide rings forming the shadows of his robe. No readable text or logo.",
        "A fox sleeps in tall grass in warm brown washes, dark rings marking where each pool dried. No readable text or logo.",
        "A steam train crosses a viaduct in layered brown washes, tide rings and blooms swirling through its smoke. No readable text or logo.",
      ],
    },
    {
      name: 'Hydro-Dip Swirl',
      domain: 'hydro-dip swirl pattern',
      tags: ['hydro-dip', 'swirl', 'fluid'],
      dna: style(
        'Hydro-dip: the subject coated by dipping through swirled paint film.',
        "the subject's surfaces are coated in swirled hydro-dip paint.",
        'Neon or pastel swirls.',
        'Studio light.',
        'Swirled paint film.',
        'Object-centered.',
        'Playful, vivid, crafty and bold.',
        'Glossy finish.',
        'hydro-dip swirls; coated surfaces',
      ),
      avoid: AVOID,
      briefs: [
        "A fencing mask has been dipped through neon swirls of pink, cyan and black, the film wrapping every curve with drips at the base. No readable text or logo.",
        "A skull is coated in a swirling marbled film of gold and black, the pattern stretched tight over its cheekbones. No readable text or logo.",
        "An electric guitar is dipped in psychedelic orange and violet swirls that flow around its body and neck. No readable text or logo.",
      ],
    },
    {
      name: 'Magnetic Iron Filings',
      domain: 'iron filing field patterns',
      tags: ['iron-filings', 'magnetic', 'fluid'],
      dna: style(
        'Iron filings: field lines of iron filings tracing the subject.',
        'the subject is traced by iron filings aligned in field lines.',
        'Dark grey filings on white.',
        'Flat.',
        'Aligned filings.',
        'Field lines around forms.',
        'Scientific, invisible-made-visible and precise.',
        'Crisp finish.',
        'aligned iron filings; field lines',
      ),
      avoid: AVOID,
      briefs: [
        "A coiled serpent is traced by field lines of iron filings on white paper, dense black clusters marking the hidden poles. No readable text or logo.",
        "A crown is traced by radiating field lines, filings bristling at its points above hidden magnets. No readable text or logo.",
        "A hummingbird is traced by curving field lines on cream paper, filings clustering densely at the wings. No readable text or logo.",
      ],
    },
    {
      name: 'Frost Fern Crystals',
      domain: 'frost fern crystal growth',
      tags: ['frost', 'crystal', 'fluid'],
      dna: style(
        'Frost ferns: window-frost crystal feathers growing into the subject.',
        'the subject is drawn by growing frost fern crystals.',
        'White frost on dark glass.',
        'Backlight.',
        'Feathery ice crystals.',
        'Growth patterns.',
        'Cold, delicate, magical and quiet.',
        'Crisp finish.',
        'frost fern crystals; window glass',
      ),
      avoid: AVOID,
      briefs: [
        "A stag is traced across a dark pane by feathery ice crystals, ferns of frost forming its antlers. No readable text or logo.",
        "A sailing ship grows across a winter window, crystal feathers forming its sails and rigging against the night. No readable text or logo.",
        "A dancer grows in ice crystals on a window, feathery ferns forming her skirt and outstretched arms. No readable text or logo.",
      ],
    },
    {
      name: 'Liquid Light Show',
      domain: 'oil projection light show',
      tags: ['light-show', 'projection', 'fluid'],
      dna: style(
        'Liquid light show: overhead-projected oil and dye blobs pulsing in saturated color.',
        'the subject is formed by projected pulsing oil and dye blobs.',
        'Saturated magenta, green, orange.',
        'Projected light.',
        'Oil and dye blobs.',
        'Full-frame projection.',
        'Psychedelic, pulsing, warm and hypnotic.',
        'Projected finish.',
        'projected oil blobs; saturated dye',
      ),
      avoid: AVOID,
      briefs: [
        "A wizard's face forms out of projected blobs of dye and oil, saturated magenta and yellow pulsing across a dark wall. No readable text or logo.",
        "A rock band on stage is bathed in projected blobs, saturated colors pulsing over their silhouettes. No readable text or logo.",
        "An eye opens inside bubbling projected blobs, deep blue and orange pulsing across a dark screen. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
