import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Toys and miniatures: each preset names the toy line, maker or hobby tradition whose sculpting,
// material and packaging it rebuilds. The requested subject becomes that kind of toy; cards stage
// original characters, never licensed ones or real branded packaging.
const T = ['toy-miniature'];
const shot = 'Clean toy product photography with honest plastic, paint and material detail.';

const spec: Spec = {
  pack: 'pack_28',
  category: '2. Toys & Miniatures',
  newCategory: { id: 'toys-miniatures' },
  updates: {},
  creates: [
    cr('Nendoroid - Chibi Articulated Figure', 'toy figure', [...T, 'nendoroid'], {
      look: 'Good Smile Nendoroid look: super-deformed chibi PVC figures with huge heads, tiny bodies, swappable face plates, little accessories and clear stands.',
      subject:
        'turn the subject into a chibi PVC figure with a huge head, tiny body and swappable face plate.',
      color: 'Bright clean PVC color with glossy eyes.',
      light: 'Soft even product light.',
      texture: 'Smooth PVC with printed eyes.',
      camera: 'Eye-level product view on a clear stand.',
      mood: 'cute playful charm',
      render: shot,
      key: 'Nendoroid chibi; huge head; swappable faces',
      avoid: ['licensed anime characters'],
      briefs: [
        'Balancing on a clear stand, a chibi PVC figure of an original ramen chef with a huge head holds tiny chopsticks over a miniature steaming bowl while two spare face plates, one crying and one laughing, lie beside her. No readable text or logo.',
        'Posed mid-jump on a clear stand, a chibi mountain climber with an oversized head clutches a tiny pickaxe while a spare panicked face plate waits on the table. No readable text or logo.',
        'Beside a tiny sofa accessory, a sleepy chibi office worker with a huge head hugs a miniature pillow. A little coffee cup accessory lies tipped over. No readable text or logo.',
      ],
    }),
    cr('Sofubi - Japanese Soft Vinyl Kaiju Toy', 'toy figure', [...T, 'sofubi'], {
      look: 'Japanese sofubi look: hand-sprayed soft vinyl kaiju and monster toys, chunky simplified sculpts, glossy sprayed gradients, sparkle vinyl and small-batch artisan runs.',
      subject: 'turn the subject into a chunky hand-sprayed soft vinyl monster toy.',
      color: 'Sprayed gradients of neon, sparkle and translucent vinyl.',
      light: 'Soft product light with glossy highlights.',
      texture: 'Glossy hollow soft vinyl with hand-sprayed paint.',
      camera: 'Frontal product view.',
      mood: 'quirky retro monster charm',
      render: shot,
      key: 'Sofubi soft vinyl; sprayed kaiju; chunky sculpt',
      avoid: ['licensed kaiju'],
      briefs: [
        'Standing on a wooden shelf, a chunky soft vinyl kaiju shaped like a grumpy teapot with stubby legs glows in hand-sprayed neon orange fading into sparkle purple, its glossy spout roaring. No readable text or logo.',
        'Molded in translucent green vinyl with sprayed red eyes, a squat swamp monster with three horns grins on a collector shelf. A tiny sprayed fish dangles from its mouth. No readable text or logo.',
        'Lined up on a shop counter, three small sofubi yokai in sparkle vinyl each carry a sprayed lantern. Their glossy tongues are painted bubblegum pink. No readable text or logo.',
      ],
    }),
    cr('Designer Vinyl Art Toy - Blank Platform Figure', 'toy figure', [...T, 'designer-vinyl'], {
      look: 'Designer vinyl art toy look: simple rounded platform figures customized by artists, bold graphic surface designs, matte vinyl and gallery shelf display.',
      subject:
        'turn the subject into a simple rounded vinyl platform figure with bold artist surface graphics.',
      color: 'Bold graphic surface color on matte vinyl.',
      light: 'Clean gallery shelf light.',
      texture: 'Matte vinyl with printed graphics.',
      camera: 'Frontal gallery display view.',
      mood: 'playful urban art cool',
      render: shot,
      key: 'Designer vinyl platform; artist graphics; gallery shelf',
      avoid: ['Kidrobot Dunny ears', 'bear-shaped block toys'],
      briefs: [
        'On a white gallery shelf, a simple rounded vinyl platform figure of an original sleepy whale is covered in bold hand-drawn graphics of city skylines and hot air balloons in matte blue and orange. No readable text or logo.',
        'Covered in black-and-white checker graphics, a rounded vinyl figure of a penguin in sneakers stands beside two blank versions awaiting customization. No readable text or logo.',
        'Wrapped in bright tropical fruit patterns, a matte vinyl figure of a stubby dinosaur poses on a gallery plinth. A tiny paint marker rests beside it. No readable text or logo.',
      ],
    }),
    cr('Blind Box Art Toy - Pastel Collectible Series', 'toy figure', [...T, 'blind-box'], {
      look: 'Asian blind box art toy look: small pastel matte vinyl characters with round faces and big eyes, seasonal themed series, foil packets and open-box display trays.',
      subject:
        'turn the subject into a small pastel matte blind box character with a round face and big eyes.',
      color: 'Soft pastel pink, mint and cream.',
      light: 'Soft dreamy product light.',
      texture: 'Matte pastel vinyl.',
      camera: 'Close product view with foil packets.',
      mood: 'sweet collectible delight',
      render: shot,
      key: 'Blind box pastel; round face; themed series',
      avoid: ['Pop Mart Molly or Labubu designs'],
      briefs: [
        'Beside a torn foil packet on a pastel desk, a small matte vinyl blind box figure of an original girl in a strawberry-bread costume sits with big glossy eyes, part of a bakery-themed series displayed in a tray behind her. No readable text or logo.',
        'Lined up in a clear display tray, six pastel blind box astronauts each hold a different planet, one gleaming as the rare chase variant. No readable text or logo.',
        'Half-hidden in shredded paper, a tiny mint-green figure in a raincoat peeks out of its opened capsule box. A matching umbrella accessory lies beside it. No readable text or logo.',
      ],
    }),
    cr(
      'Eighties Carded Action Figure - Blister Pack Hero',
      'toy figure',
      [...T, 'eighties-carded'],
      {
        look: 'Eighties action figure look: five-inch muscular plastic heroes with simple articulation, bold painted colors, chunky weapon accessories and sealed blister-card packaging with painted card art.',
        subject:
          'turn the subject into a five-inch muscular eighties plastic action figure sealed on a painted blister card.',
        color: 'Bold primary plastic colors and painted card art.',
        light: 'Flat product light on glossy blister plastic.',
        texture: 'Hard plastic figure in a clear blister bubble.',
        camera: 'Frontal carded packaging view.',
        mood: 'nostalgic Saturday-morning heroics',
        render: shot,
        key: 'Eighties carded figure; blister pack; painted card art',
        avoid: ['Masters of the Universe or other licensed lines', 'real toy logos'],
        briefs: [
          'Sealed in a clear blister bubble on a painted card of a volcano battle, a five-inch muscular plastic figure of an original barbarian librarian holds a chunky axe and a tiny book accessory. No readable text or logo.',
          'Inside a slightly dented blister card, a plastic hero with a snap-on jetpack waits beside a spare laser pistol accessory. The painted card shows a canyon chase. No readable text or logo.',
          'Hanging on a toy store peg, a carded villain figure with a skull shoulder pad grins beneath sun-faded card art. His tiny cape is real fabric. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Warhammer Painted Miniature - Tabletop Wargame Mini',
      'miniature',
      [...T, 'warhammer-mini'],
      {
        look: 'Tabletop wargame miniature look: 28mm plastic figures painted by hobbyists with layered highlights, edge highlighting, washes, textured bases with tufts and gothic grimdark detail.',
        subject:
          'turn the subject into a 28mm painted wargame miniature with edge highlights and a textured tufted base.',
        color: 'Layered hobby paint with bright edge highlights.',
        light: 'Macro hobby photography light.',
        texture: 'Painted plastic with washes and textured base.',
        camera: 'Macro close-up on a hobby desk.',
        mood: 'gritty hobbyist devotion',
        render: 'Macro miniature painting photograph.',
        key: 'Painted 28mm mini; edge highlights; tufted base',
        avoid: ['Space Marines or licensed Warhammer designs'],
        briefs: [
          'In a macro close-up on a hobby desk, a 28mm painted miniature of an original plague-doctor inquisitor with a lantern shows crisp edge highlights and a textured base of skulls and grass tufts, a brush resting beside it. No readable text or logo.',
          'Lined up on a cutting mat, a squad of five painted miniature monks in red robes glow with layered highlights. One is still grey primer. No readable text or logo.',
          'Under a magnifier lamp, a half-painted miniature ogre cook holds a cleaver over a tiny cauldron. Paint pots crowd the desk. No readable text or logo.',
        ],
      },
    ),
    cr('D&D Painted Mini - Fantasy Role-Playing Miniature', 'miniature', [...T, 'dnd-mini'], {
      look: 'Fantasy role-playing miniature look: painted pewter or resin adventurer minis on round bases, standing on grid battle maps with dice and character sheets around them.',
      subject:
        'turn the subject into a painted fantasy adventurer miniature standing on a grid battle map.',
      color: 'Warm hobby paint colors on a battle map.',
      light: 'Warm game-night table light.',
      texture: 'Painted pewter and grid mat.',
      camera: 'Low table-level view among dice.',
      mood: 'cozy game-night adventure',
      render: 'Warm tabletop game-night photograph.',
      key: 'RPG miniature; grid battle map; dice',
      briefs: [
        'On a grid battle map among polyhedral dice and a spilled bowl of popcorn, a painted pewter miniature of an original halfling cartographer faces a towering painted troll mini at game night. No readable text or logo.',
        'Standing in a paper dungeon of folded walls, four painted adventurer minis crowd a doorway while a dice tower looms behind them. No readable text or logo.',
        'Knocked over beside a natural-one die, a tiny painted wizard miniature lies on its side on a stone-texture map. Someone’s pencil rests nearby. No readable text or logo.',
      ],
    }),
    cr('Gashapon Capsule Toy - Vending Mini Figure', 'toy figure', [...T, 'gashapon'], {
      look: 'Japanese gashapon capsule toy look: tiny detailed figures in clear plastic capsules, quirky everyday themes, colorful vending machines and small assembly parts.',
      subject: 'turn the subject into a tiny detailed capsule toy beside its open plastic capsule.',
      color: 'Bright capsule colors and tiny painted detail.',
      light: 'Bright shop light.',
      texture: 'Small PVC parts and clear capsule plastic.',
      camera: 'Macro close-up with an open capsule.',
      mood: 'quirky tiny delight',
      render: shot,
      key: 'Gashapon capsule; tiny figure; quirky theme',
      briefs: [
        'Beside a half-open clear plastic capsule, a tiny detailed gashapon figure of a cat sleeping inside a miniature convenience-store rice ball sits on a vending machine ledge. No readable text or logo.',
        'Clustered in a palm, three tiny capsule toys of office chairs with different animals spinning on them await assembly. No readable text or logo.',
        'Rows of colorful capsules fill a vending machine window in a quiet arcade. One capsule has rolled to the front. No readable text or logo.',
      ],
    }),
    cr('Tin Wind-Up Toy - Vintage Lithographed Tin', 'toy', [...T, 'tin-toy'], {
      look: 'Vintage tin wind-up toy look: lithographed printed tin, folded tabs, visible wind-up keys, chipped paint, simple mechanical motion and mid-century graphic charm.',
      subject: 'turn the subject into a lithographed tin wind-up toy with a key and folded tabs.',
      color: 'Faded lithograph red, yellow and blue.',
      light: 'Warm antique shop light.',
      texture: 'Printed tin with chips and folded tabs.',
      camera: 'Close antique shelf view.',
      mood: 'nostalgic mechanical charm',
      render: shot,
      key: 'Tin wind-up; lithograph; wind-up key',
      briefs: [
        'On an antique shop shelf, a lithographed tin wind-up toy of an original drumming penguin shows folded tabs, chipped red paint and a brass wind-up key in its back. No readable text or logo.',
        'Rolling across a wooden floor, a tin wind-up tram with printed passengers in the windows trails a tiny spark. Its key is still turning. No readable text or logo.',
        'Waiting in a glass case, a tin robot with printed dials on its chest has one arm raised mid-wave. Rust spots freckle its feet. No readable text or logo.',
      ],
    }),
    cr('Plush Toy - Stitched Fabric Character', 'toy', [...T, 'plush'], {
      look: 'Plush toy look: soft stitched fabric characters, embroidered eyes, fuzzy minky fabric, visible seams and cozy bedroom or shop display.',
      subject:
        'turn the subject into a soft plush toy with embroidered features and visible seams.',
      color: 'Soft pastel and warm fabric colors.',
      light: 'Soft window light.',
      texture: 'Fuzzy minky fabric and embroidery.',
      camera: 'Close cozy product view.',
      mood: 'cuddly comforting warmth',
      render: shot,
      key: 'Plush toy; embroidery; minky fabric; seams',
      briefs: [
        'Slumped on a bedroom windowsill, a soft plush toy of an original grumpy storm cloud with embroidered eyebrows and felt raindrops hangs from its seams, its minky fabric catching the morning light. No readable text or logo.',
        'Packed into a claw machine, a pile of plush vegetables with embroidered smiles waits under neon light. One carrot is dangling from the claw. No readable text or logo.',
        'Tucked into a bed beside a sleeping child, a patched plush dragon has one button eye replaced. The stitches are uneven and loving. No readable text or logo.',
      ],
    }),
    cr('Die-Cast Car - Scale Model Collectible', 'toy', [...T, 'die-cast'], {
      look: 'Die-cast collectible car look: heavy metal scale models with glossy paint, rubber tires, chrome details, opening doors and display cases or blister packs.',
      subject: 'turn the subject into a heavy glossy die-cast scale model with chrome details.',
      color: 'Glossy car paint and chrome.',
      light: 'Studio product light with reflections.',
      texture: 'Die-cast metal, glossy paint, rubber.',
      camera: 'Low three-quarter macro product view.',
      mood: 'precise collector pride',
      render: shot,
      key: 'Die-cast model; glossy paint; chrome; scale',
      avoid: ['real car brand logos'],
      briefs: [
        'In a low macro product shot, a heavy die-cast scale model of an original ice-cream van with opening doors and chrome bumpers gleams on a mirrored display base. No readable text or logo.',
        'Parked in rows inside a glass display case, tiny die-cast delivery trucks each carry a different painted cargo. One has a door open. No readable text or logo.',
        'Racing across a playroom carpet, a die-cast rally car leaves a trail of dust from a toy track. Its rubber tires are worn smooth. No readable text or logo.',
      ],
    }),
    cr('Model Railway - HO Scale Layout Figure', 'miniature', [...T, 'model-railway'], {
      look: 'Model railway layout look: HO scale miniature towns with trains, painted tiny figures, static grass, lichen trees and warm layout lighting.',
      subject:
        'turn the subject into tiny painted HO scale figures and buildings on a model railway layout.',
      color: 'Static grass green, brick red and painted details.',
      light: 'Warm layout lighting.',
      texture: 'Static grass, lichen trees and tiny painted plastic.',
      camera: 'Low miniature eye-level view.',
      mood: 'cozy miniature world',
      render: 'Miniature model railway photograph.',
      key: 'HO scale layout; static grass; tiny figures',
      briefs: [
        'At eye level on a model railway layout, tiny painted HO scale figures wait at a rural station platform as a little steam engine rounds a bend past lichen trees and static grass. No readable text or logo.',
        'On a tiny market square, painted figures browse stalls while a model tram passes the church. A giant hand places a new bench. No readable text or logo.',
        'A miniature tunnel mouth glows as a tiny train emerges into a snowy scale village. A plastic dog chases it. No readable text or logo.',
      ],
    }),
    cr('Brick-Built Minifigure - Toy Brick Character', 'toy figure', [...T, 'brick-minifig'], {
      look: 'Toy brick minifigure look: small blocky interlocking-brick figures with C-shaped hands, printed faces, snap-on accessories and studded baseplates.',
      subject:
        'turn the subject into a small blocky toy-brick minifigure with printed face and snap-on accessories.',
      color: 'Bright primary brick colors.',
      light: 'Bright even toy light.',
      texture: 'Glossy ABS plastic and studs.',
      camera: 'Macro view on a studded baseplate.',
      mood: 'playful building fun',
      render: shot,
      key: 'Brick minifigure; printed face; studs',
      avoid: ['real LEGO logos', 'licensed minifigures'],
      briefs: [
        'On a studded green baseplate, a blocky toy-brick minifigure of an original beekeeper with a printed smile holds a snap-on honey jar while tiny brick bees sit on transparent stalks around her. No readable text or logo.',
        'Crowded around a brick-built campfire, four minifigures toast snap-on marshmallows on a studded plate. One has lost his hair piece. No readable text or logo.',
        'A single minifigure hangs from a brick-built crane over a half-finished tower. His printed face looks worried. No readable text or logo.',
      ],
    }),
    cr('Wooden Toy - Montessori Painted Wood', 'toy', [...T, 'wooden-toy'], {
      look: 'Wooden toy look: smooth sanded beech with non-toxic pastel paint, simple peg figures, stacking shapes and Scandinavian nursery styling.',
      subject: 'turn the subject into a simple sanded wooden peg toy with soft pastel paint.',
      color: 'Pastel paint on natural beech.',
      light: 'Soft nursery window light.',
      texture: 'Smooth sanded wood grain.',
      camera: 'Clean top view on a play mat.',
      mood: 'calm gentle simplicity',
      render: shot,
      key: 'Wooden peg toy; pastel paint; beech',
      briefs: [
        'On a soft linen play mat, simple sanded wooden peg figures of an original fire crew with pastel painted helmets stand beside a stacking-block fire truck in natural beech. No readable text or logo.',
        'Stacked into a wobbly tower, pastel wooden rings form a smiling caterpillar. One ring has rolled away. No readable text or logo.',
        'Seated around a round beech table set with painted cups, a family of pastel peg figures shares a pretend supper. The baby peg is tucked into a tiny crib nearby. No readable text or logo.',
      ],
    }),
    cr('Plastic Army Men - Green Toy Soldiers', 'toy', [...T, 'army-men'], {
      look: 'Green plastic toy soldier look: cheap molded olive plastic figures in frozen poses with flat bases and mold seams, staged in backyard or kitchen-table battles.',
      subject:
        'turn the subject into cheap olive plastic toy figures with flat bases and mold seams.',
      color: 'Olive green plastic and backyard earth.',
      light: 'Bright sun or kitchen light.',
      texture: 'Cheap molded plastic with seams.',
      camera: 'Low macro ground-level view.',
      mood: 'playful mock heroism',
      render: shot,
      key: 'Green army men; molded plastic; mock battle',
      briefs: [
        'At ground level in a backyard garden, cheap olive plastic figures of original gardeners in frozen poses defend a strawberry plant from a giant snail, mold seams visible on their flat bases. No readable text or logo.',
        'A kitchen table becomes a battlefield as plastic figures storm a fortress of cereal boxes. A spoon bridge spans a milk moat. No readable text or logo.',
        'Half-buried in a sandbox at dusk, one olive soldier figure lies on his side with a mold seam across his helmet. A toy dump truck waits beside him. No readable text or logo.',
      ],
    }),
    cr('Scale Model Diorama - Weathered Hobby Scene', 'miniature', [...T, 'scale-diorama'], {
      look: 'Hobby scale model diorama look: realistic weathered miniature scenes with pigments, rust, mud and water effects on a wooden plinth, photographed as if full size.',
      subject:
        'turn the subject into a weathered realistic scale model diorama on a wooden plinth.',
      color: 'Realistic weathered earth, rust and water.',
      light: 'Natural-looking diorama light.',
      texture: 'Pigment weathering, rust and resin water.',
      camera: 'Low forced-realism view.',
      mood: 'quiet realistic miniature',
      render: 'Hobby diorama photograph.',
      key: 'Scale diorama; weathering pigments; resin water',
      briefs: [
        'On a wooden plinth, a weathered scale model diorama shows an original rusted fishing boat pulled onto a muddy riverbank with resin water, pigment rust streaks and a tiny painted fisherman mending nets. No readable text or logo.',
        'A miniature abandoned gas station diorama gathers dust and pigment rust under a painted sky backdrop. A tiny cat sits on the pump. No readable text or logo.',
        'A frozen resin waterfall pours over miniature rocks into a moss-covered pool. A tiny deer drinks at the edge. No readable text or logo.',
      ],
    }),
    cr('Anime Figma - Articulated Action Figure', 'toy figure', [...T, 'figma'], {
      look: 'Max Factory figma look: small highly articulated anime action figures with visible joints, swappable hands, effect parts and posing stands.',
      subject:
        'turn the subject into a small highly articulated anime action figure with visible joints.',
      color: 'Clean anime PVC color.',
      light: 'Bright product light.',
      texture: 'PVC with visible ball joints.',
      camera: 'Dynamic posed product view.',
      mood: 'dynamic playful action',
      render: shot,
      key: 'figma articulated; visible joints; effect parts',
      avoid: ['licensed anime characters'],
      briefs: [
        'Posed mid-kick on a flexible stand, a small highly articulated anime figure of an original courier with visible ball joints swings a messenger bag while translucent speed-line effect parts trail behind her. No readable text or logo.',
        'Laid out in a tray, swappable hands, a tiny umbrella and a sword accessory wait beside an articulated figure mid-pose. No readable text or logo.',
        'An articulated figure sits cross-legged on a desk reading a tiny book, its joints bent naturally. A stand arm hovers unused. No readable text or logo.',
      ],
    }),
    cr('Retro Robot Toy - Space Age Battery Operated', 'toy', [...T, 'space-age-robot'], {
      look: 'Fifties and sixties space-age battery toy look: chunky tin and plastic robots with dome heads, antennas, lit-up chests, walking mechanisms and colorful boxes.',
      subject:
        'turn the subject into a chunky space-age battery toy robot with a dome head and lit chest.',
      color: 'Candy red, silver and space blue.',
      light: 'Warm retro product light with lit-up chest glow.',
      texture: 'Tin, chrome and clear plastic domes.',
      camera: 'Frontal product view.',
      mood: 'optimistic space-age fun',
      render: shot,
      key: 'Space-age robot toy; dome head; lit chest',
      briefs: [
        'Marching across a checkered linoleum floor, a chunky battery-operated space-age toy robot shaped like an original milkman with a dome head and blinking chest lights carries tin milk bottles. No readable text or logo.',
        'A tin rocket toy with sparking exhaust rolls across a carpet toward a cardboard moon. A cat watches warily. No readable text or logo.',
        'A dome-headed robot toy stands next to its faded original box on a shelf. Its antenna is slightly bent. No readable text or logo.',
      ],
    }),
    cr('Handmade Clay Miniature - Tiny Food Craft', 'miniature', [...T, 'clay-miniature'], {
      look: 'Handmade polymer clay miniature look: tiny realistic food and objects sculpted at doll scale, glossy resin glazes, placed next to a fingertip or coin for scale.',
      subject:
        'turn the subject into a tiny polymer clay miniature shown next to a fingertip for scale.',
      color: 'Realistic appetizing colors at tiny scale.',
      light: 'Soft macro light.',
      texture: 'Polymer clay with glossy resin glaze.',
      camera: 'Macro view with a fingertip for scale.',
      mood: 'delightful tiny craftsmanship',
      render: 'Macro craft photograph.',
      key: 'Polymer clay miniature; fingertip scale; resin glaze',
      briefs: [
        'Balanced on a fingertip in macro focus, a tiny polymer clay miniature of an original bakery display with glossy resin-glazed croissants, a slice of layered cake and a pie smaller than a pea glows in soft light. No readable text or logo.',
        'A thimble-sized clay bowl of ramen with resin broth and a tiny egg sits beside a coin. Steam is made of cotton wisp. No readable text or logo.',
        'A tiny clay breakfast tray with toast, jam and a fried egg rests on a fingertip. The toast has a bite taken out. No readable text or logo.',
      ],
    }),
    cr('Kinetic Articulated Wooden Mannequin - Artist Toy', 'toy', [...T, 'wooden-mannequin'], {
      look: 'Artist wooden mannequin look: jointed beech drawing mannequins with ball joints, faceless heads and natural grain, posed in expressive human gestures.',
      subject:
        'turn the subject into a faceless jointed wooden artist mannequin in an expressive pose.',
      color: 'Natural pale beech.',
      light: 'Soft studio light.',
      texture: 'Smooth wood with ball joints.',
      camera: 'Clean still-life view.',
      mood: 'quiet expressive gesture',
      render: shot,
      key: 'Wooden mannequin; ball joints; faceless pose',
      briefs: [
        'On a sunny desk, a faceless jointed wooden artist mannequin is posed kneeling to propose to a smaller mannequin, offering a ring made from a paperclip while a sketchbook lies open nearby. No readable text or logo.',
        'Two wooden mannequins dance a tango on a stack of art books, their ball joints bent mid-step. No readable text or logo.',
        'A single mannequin slumps over a laptop keyboard as if asleep. A tiny coffee cup sits beside its hand. No readable text or logo.',
      ],
    }),
  ],
};

export default spec;
