import type { Create, Spec } from '../tools/apply';
import { ANIME_AVOID as AVOID, anime } from './_anime';

// Slice of life, school and music (part A): each preset is a light-and-mood look, not a venue.
// The venue in each brief is only one test of the look; any everyday prompt can use it.
const spec: Spec = {
  pack: 'pack_13',
  category: '2. Slice Of Life, School And Music',
  updates: {
    'SP13-003': {
      dna: anime(
        'Soft shojo spring anime: airy pastel frames with fine elegant lines, sparkling eyes and drifting petals.',
        'fine thin contours, tall slender figures, large glossy eyes with many highlights, petals and light sparkles drifting through the frame.',
        'Pastel pink, mint, cream and pale sky blue.',
        'Soft diffused spring daylight with gentle bloom.',
        'Light cel with soft painted gradients and screentone-like sparkle.',
        'Intimate close and mid shots with lots of air.',
        'Tender, hopeful, shy and dreamy.',
        'fine lines; sparkling eyes; drifting petals; pastel bloom',
      ),
      avoid: AVOID,
      briefs: [
        'Soft shojo anime frame of a shy apprentice knight handing a pressed flower to a young healer under a blossoming tree in a castle garden, petals drifting, sparkling eyes, fine elegant lines and pastel bloom. No readable text or logo.',
        'Shojo anime close-up of a girl reading a letter by an open window as petals blow in, her cheeks flushed, a cat asleep on the sill. No readable text or logo.',
        'Shojo anime frame of two friends sharing an umbrella under a spring shower of petals on a stone bridge, soft bloom and sparkles in the air. No readable text or logo.',
      ],
    },
    'SP13-005': {
      dna: anime(
        'Rainy slice of life anime: quiet everyday frames with rain on glass, muted color and small gestures.',
        'restrained expressions, small hand gestures, detailed rain drops on glass and puddles, simple clean lines.',
        'Muted blue-grey with warm interior amber.',
        'Overcast daylight or warm indoor lamps against rain.',
        'Painted rain streaks, droplets and wet reflections.',
        'Framed through windows and doorways.',
        'Calm, reflective, lonely and cozy.',
        'rain on glass; muted palette; small gestures; warm interiors',
      ),
      avoid: AVOID,
      briefs: [
        'Rainy slice of life anime frame of a young innkeeper drying cups behind the counter of an empty tavern while rain streams down the diamond-paned window, a traveler cloak dripping on a hook, warm lamp light. No readable text or logo.',
        'Anime frame of a boy waiting at a village bus stop in heavy rain, a small forest spirit sharing the shelter, puddles reflecting the lamp. No readable text or logo.',
        'Anime frame of a girl pressing her forehead to a rainy train window, raindrops racing sideways, town lights blurred beyond. No readable text or logo.',
      ],
    },
    'SP13-013': {
      name: 'Backstage Nerves Anime',
      dna: anime(
        'Backstage nerves anime: the look of the minutes before a performance, dim wings, mirror bulbs and a slice of stage light.',
        'tight faces and hands, small nervous gestures, costumes half-done, the stage glimpsed as a bright strip.',
        'Dim backstage browns with mirror-bulb warm white and stage-light color spill.',
        'Mirror bulbs and stage light leaking through curtains.',
        'Cel with soft glow and dust in light.',
        'Close framing among curtains, cables and mirrors.',
        'Nervous, private, hopeful and tense.',
        'mirror bulbs; stage light strip; nervous hands',
      ),
      avoid: AVOID,
      briefs: [
        'Anime frame backstage before a performance: a young bard in a patched costume tuning a lute in front of a bulb-ringed mirror, hands trembling, a strip of bright stage light through the curtain gap and rain drumming on the theatre roof. No readable text or logo.',
        'Anime close-up of a dancer lacing her shoes in the dark wings, stage light falling across her face, dust floating. No readable text or logo.',
        'Anime frame of a band of young musicians huddled in a cramped backstage room, one breathing into a paper bag, another grinning. No readable text or logo.',
      ],
    },
    'SP13-015': {
      dna: anime(
        'Dessert cafe comedy anime: warm, sugary comedic frames with glossy desserts and big reaction faces.',
        'rounded friendly designs, exaggerated reaction faces, chibi moments, glossy dessert close-ups.',
        'Cream, strawberry pink, caramel and mint.',
        'Warm cozy cafe light.',
        'Soft cel with glossy dessert highlights.',
        'Table-level framing with desserts in the foreground.',
        'Sweet, silly, cozy and cheerful.',
        'glossy desserts; reaction faces; warm light',
      ),
      avoid: AVOID,
      briefs: [
        'Dessert cafe comedy anime frame of a stern armored knight trying a strawberry parfait for the first time, face melting into a blissful chibi expression while her squire gasps, glossy cream and warm light. No readable text or logo.',
        'Dessert cafe comedy anime frame of a tiny dragon waiter carrying a towering layered cake across a crowded cafe, the cake starting to tilt, customers frozen mid-gasp with big reaction faces, glossy frosting highlights. No readable text or logo.',
        'Dessert cafe comedy anime frame of three friends lunging for the last macaron on a pastel plate, faces exaggerated into fierce chibi expressions, crumbs and sparkles flying, warm cafe light. No readable text or logo.',
      ],
    },
    'SP13-018': {
      dna: anime(
        'Festival lantern summer anime: warm summer-night frames with rows of lanterns, yukata-like robes and firefly glow.',
        'soft lines, flowing robes and sleeves, faces lit warmly from lanterns, fireworks drawn as soft bursts.',
        'Lantern orange, deep indigo night and firework colors.',
        'Lantern and firework light on faces.',
        'Cel with bokeh lantern glows.',
        'Crowd-level frames with lanterns receding.',
        'Nostalgic, warm, romantic and fleeting.',
        'lantern rows; fireworks; warm faces; summer night',
      ),
      avoid: AVOID,
      briefs: [
        'Festival lantern anime frame of a young witch and a werewolf boy in festival robes walking under rows of paper lanterns on a summer night, holding candied apples, faces lit warm orange and fireflies around. No readable text or logo.',
        "Festival anime frame of friends sitting on the stone steps of a hill shrine watching fireworks bloom over a lantern-lit town, faces flashing pink and gold, one reaching to hold another's hand. No readable text or logo.",
        "Festival anime frame of a goldfish-scooping stall at night where a tiny river spirit in the water tub keeps dodging a child's paper scoop, lantern bokeh and warm orange faces. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Concert Spotlight Anime',
      domain: 'live performance anime',
      tags: ['concert', 'stage-light', 'anime'],
      dna: anime(
        'Concert spotlight anime: live-performance frames with blazing spotlights, lens flares, sweat and silhouetted crowds.',
        'dynamic performing poses, flying sweat and hair, instruments drawn precisely, crowd as silhouettes with raised hands.',
        'Saturated stage colors: magenta, blue and gold against black.',
        'Spotlights, backlight and lens flares.',
        'Cel with glow, haze and flare overlays.',
        'Low angle from the crowd or wide from behind the band.',
        'Euphoric, loud, sweaty and alive.',
        'spotlights; lens flares; sweat; crowd silhouettes',
      ),
      avoid: AVOID,
      briefs: [
        'Concert spotlight anime frame of a young bard band performing in a packed torchlit tavern hall, the singer mid-scream with sweat flying, a violinist and a drummer behind, magenta and gold spotlights cutting smoke, raised hands in silhouette. No readable text or logo.',
        'Concert anime frame from behind a drummer looking out at a sea of raised hands and blinding blue spotlights, sticks blurred mid-hit, sweat droplets glowing in the backlight. No readable text or logo.',
        'Concert anime frame of a harpist alone on a dark stage under a single white spotlight, eyes closed, sweat glinting on her temple, the audience a quiet dark ocean. No readable text or logo.',
      ],
    },
    {
      name: 'Afterschool Golden Hour Anime',
      domain: 'late afternoon light anime',
      tags: ['golden-hour', 'nostalgia', 'anime'],
      dna: anime(
        'Afterschool golden hour anime: long orange light through windows, dust motes and long shadows at the end of the day.',
        'simple quiet poses, long cast shadows, window frames and silhouettes against the light.',
        'Deep orange and amber with violet shadows.',
        'Low sun through windows with bright shafts.',
        'Cel with painted light shafts and floating dust.',
        'Wide still frames with strong window geometry.',
        'Nostalgic, bittersweet, quiet and warm.',
        'orange shafts; long shadows; dust motes',
      ),
      avoid: AVOID,
      briefs: [
        'Afterschool golden hour anime frame of an apprentice mage alone in a tower classroom, sweeping spilled chalk while long orange light pours through tall arched windows, dust motes floating and long violet shadows of desks. No readable text or logo.',
        'Afterschool golden hour anime frame of two students sitting on a stone riverbank below a castle bridge, bags beside them, their long shadows stretching across the water, orange light and violet shade. No readable text or logo.',
        'Golden hour anime frame of an empty school corridor with tall windows, orange light shafts falling across the floor in stripes, a single forgotten umbrella leaning against a locker. No readable text or logo.',
      ],
    },
    {
      name: 'Winter Breath Quiet Anime',
      domain: 'winter slice of life anime',
      tags: ['winter', 'quiet', 'anime'],
      dna: anime(
        'Winter breath anime: hushed snowy frames with visible breath, red noses, scarves and pale blue light.',
        'soft lines, bundled clothes, visible breath clouds, rosy cheeks and falling snow.',
        'Pale blue, white and a warm red accent.',
        'Soft overcast snow light.',
        'Cel with painted snow and soft glow.',
        'Quiet mid shots with snow falling.',
        'Hushed, tender, cold and cozy.',
        'visible breath; scarves; falling snow',
      ),
      avoid: AVOID,
      briefs: [
        'Winter breath anime frame of a young blacksmith and a snow fairy sharing a hot drink outside the forge as heavy snow falls, both breathing clouds, red scarves and rosy cheeks, pale blue light. No readable text or logo.',
        'Winter anime frame of a girl in a red scarf waiting at a snowy crossroads under a lamp, breath clouds rising, footprints behind her filling with snow, pale blue evening light. No readable text or logo.',
        'Winter anime frame of village children building a lopsided snow dragon with stick wings and pinecone eyes, rosy cheeks and breath clouds, snow falling softly. No readable text or logo.',
      ],
    },
    {
      name: 'Night Study Lamp Anime',
      domain: 'late-night study anime',
      tags: ['night', 'lamp', 'anime'],
      dna: anime(
        'Night study lamp anime: small pools of warm desk light in dark rooms, tired eyes and late-night focus.',
        'tired soft faces, messy hair, hands with pens, cluttered desks drawn in detail.',
        'Warm lamp yellow in deep blue darkness.',
        'Single desk lamp pool of light.',
        'Cel with soft glow.',
        'Close desk framing.',
        'Quiet, tired, focused and intimate.',
        'lamp pool; darkness; tired focus',
      ),
      avoid: AVOID,
      briefs: [
        'Night study anime frame of a young alchemy student asleep on open books under a small brass lamp, a half-finished potion glowing faintly, a cat curled on her notes, deep blue darkness around. No readable text or logo.',
        'Night study anime frame of a boy writing a long letter by the light of a small oil lamp in an attic room, ink-stained fingers, crumpled drafts around him, moonlight on the window. No readable text or logo.',
        'Night study anime frame of a young illustrator drawing at 3 a.m., desk lamp pooling on sketches of dragons, empty tea cups, a cat watching from the shelf in darkness. No readable text or logo.',
      ],
    },
    {
      name: 'Nineties School Cel Nostalgia',
      domain: '90s cel anime look',
      tags: ['90s', 'cel', 'anime'],
      dna: anime(
        '90s cel anime: hand-painted cel look with muted palette, slightly soft film grain and classic character proportions.',
        'classic 90s proportions, thin lines, hard two-tone cel shadows and slightly soft film transfer.',
        'Muted pastels with film warmth.',
        'Soft film light.',
        'Film grain and cel paint.',
        'Classic TV framing.',
        'Nostalgic, warm, simple and sincere.',
        'film grain; muted cel; 90s proportions',
      ),
      avoid: AVOID,
      briefs: [
        '90s cel anime frame of three friends in old-fashioned uniforms walking home along a seaside road beside a castle ruin, film grain, muted pastel palette and hard two-tone shadows. No readable text or logo.',
        '90s cel anime frame of a girl lying on a school rooftop with headphones and a cassette player, clouds drifting, film grain and muted pastel sky, hard two-tone shadow under her arm. No readable text or logo.',
        '90s cel anime frame of a classroom at dusk with chairs on desks, one student left staring out the window at a flying ship passing, soft film grain. No readable text or logo.',
      ],
    },
    {
      name: 'Garage Band Grit Anime',
      domain: 'rough rock band anime',
      tags: ['garage-band', 'rock', 'anime'],
      dna: anime(
        'Garage band anime: raw, energetic frames with rough lines, amp glow, sweat and cramped rehearsal spaces.',
        'rough energetic lines, loose expressive faces, instruments slightly distorted by motion.',
        'Grimy greys with amp red and bulb yellow.',
        'Bare bulb and amp glow.',
        'Rough cel with grain.',
        'Cramped low angles.',
        'Raw, loud, messy and passionate.',
        'rough lines; amp glow; sweat',
      ),
      avoid: AVOID,
      briefs: [
        'Garage band anime frame of four young musicians rehearsing in a cramped castle cellar, the singer yelling into a horn-shaped microphone, amp glow red, a bare bulb swinging, rough energetic lines. No readable text or logo.',
        'Garage band anime frame of a guitarist snapping a string mid-solo, the string whipping, sweat flying, the drummer laughing, amp glowing red in a cramped room. No readable text or logo.',
        'Garage band anime frame of a young band loading battered gear into a rusty van at night under a streetlamp, one carrying a drum kit on her head, rough lines. No readable text or logo.',
      ],
    },
    {
      name: 'Classical Recital Hush Anime',
      domain: 'classical music anime',
      tags: ['recital', 'classical', 'anime'],
      dna: anime(
        'Classical recital anime: hushed concert-hall frames, polished instruments, soft spotlight and suspended breath.',
        'elegant restrained lines, precise hands on instruments, formal clothing.',
        'Deep wood browns, black, cream and gold.',
        'Soft spotlight in a dark hall.',
        'Cel with polished reflections.',
        'Stage framing.',
        'Hushed, elegant, intense and emotional.',
        'polished instruments; spotlight; hush',
      ),
      avoid: AVOID,
      briefs: [
        'Classical recital anime frame of a young pianist in a black dress at a grand piano under a single soft spotlight in a dark candlelit hall, her reflection in the polished lid, the audience silhouettes holding breath. No readable text or logo.',
        'Classical recital anime frame of a cellist playing with eyes closed under a soft spotlight, bow mid-stroke, reflections on the polished wood, dust in the light beam. No readable text or logo.',
        'Classical recital anime frame of two violinists in a duet facing each other on a candlelit stage, bows crossing in rhythm, hushed audience silhouettes. No readable text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
