import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas indexed raster language: hand-placed pixel craft techniques as drawing rules,
// independent of any console or game. Four originals get card briefs; sixteen new studies add
// hue-shifted ramps, hand anti-aliasing, ordered Bayer dither, selective outlines, duotone pixels,
// palette-swap twins, seamless tilesets, low-count portraits, pixel bloom, pillow-shading kitsch,
// clustered foliage, four-ink scenes, high-density pixel painting, pixel water reflections,
// rim-lit silhouettes and palette-shifted night scenes.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'indexed-pixel', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'blurry upscaled pixels', 'interface or HUD', 'existing game sprites', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original characters';

const spec: Spec = {
  pack: 'pack_23',
  category: '7. Indexed Raster Language',
  updates: {
    'SP23-030': { briefs: [
      'Hauling a wicker trap from a river eddy, a fisher pulls up a sleeping river spirit curled inside like a cat, its body built from intentional clusters with dither that follows every curve. No readable text or logo.',
      'Posing proudly beside a pumpkin the size of a cart, a farmer receives a prize ribbon from a very small judge standing on a ladder, all in hard-edged indexed clusters. No readable text or logo.',
      'Deep in a forest of volume-following dither, a stone statue of a deer stands in a clearing, and fresh hoofprints lead away from its empty pedestal. No readable text or logo.',
    ] },
    'SP23-031': { briefs: [
      'Lifting from a dark reed bank, a heron pulls a glowing golden fish from the water, the bird a crisp hard silhouette against deep green with only the fish carrying bright color. No readable text or logo.',
      'Against deep support values, a proud little knight holds up a sword that is only three bright pixels long, and he is completely satisfied with it. No readable text or logo.',
      'On a black ground, a lone lantern-bearer climbs a spiral stair, the lantern the only bright cluster and the stair behind her disappearing step by step. No readable text or logo.',
    ] },
    'SP23-032': { briefs: [
      "Carrying a whole monastery on its shell, a colossal armored tortoise crosses a painted valley at dusk, dither appearing only where the light turns to shadow on its plates. No readable text or logo.",
      'Painted in compressed matte values with visible dither, a bakery at dawn has a loaf of bread that has risen so far it is now leaving through the chimney. No readable text or logo.',
      "Drifting across a still lake at twilight, a small boat heads toward a fog bank, and the visible dither in the fog forms the faint outline of a huge face. No readable text or logo.",
    ] },
    'SP23-033': { briefs: [
      'At a hillside practice range, an archer lowers her bow after her arrow has split the target and kept flying toward a surprised dragon on the horizon, all in compact readable clusters. No readable text or logo.',
      "Standing beside the enormous pile of its own wool, a freshly shorn round sheep looks very cold and embarrassed, reduced to a few compact readable color clusters. No readable text or logo.",
      'In a few simple color clusters, a well stands in a village square, and a single rope hangs down into it, pulled taut from below. No readable text or logo.',
    ] },
  },
  creates: [
    study('Hue-Shifted Color Ramps', 'pixel ramps that shift hue', 'hue-shift', {
      aesthetic: 'Hue-shifted color ramps: pixel art where every shading ramp shifts hue as it darkens and lightens, warm highlights into cool violet shadows, giving vivid painterly life.',
      subject_treatment: `${keep}; shade the subject with ramps that move warm in light and cool in shadow.`,
      color_and_tone: 'Yellow-warm highlights, saturated midtones, violet and teal shadows.',
      lighting_and_shadow: "Clear key light with hue-shifted shadow ramps, kept consistent across the whole image.",
      texture_and_material: 'Hand-placed pixels in short ramps of four or five steps.',
      camera_and_composition: "Readable central subject with clear silhouette, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with vivid painterly glow.',
      rendering_and_quality: "Clean ramps without banding or noise, kept consistent across the whole image.",
      key_features: 'hue-shifted ramps; warm light; violet shadows; hand-placed pixels',
    }, [], [
      'Rising out of a sunset marsh, a moss-covered bog giant glows gold on its shoulders and sinks into violet and teal in the shadows below its knees. No readable text or logo.',
      'Standing in golden light, a very proud rooster has feathers shading from warm orange to deep purple, and he is certain everyone is looking at him. No readable text or logo.',
      'Warm light falls on a small cottage while its long shadow in the snow shifts from blue into deep violet, and something small is sitting in that shadow. No readable text or logo.',
    ]),
    study('Hand Anti-Aliased Pixel Line', 'manual pixel anti-aliasing', 'hand-aa', {
      aesthetic: 'Hand anti-aliased pixel line: pixel art where curves and diagonals are smoothed by carefully placed intermediate-color pixels, clean lines that look smooth at a distance and deliberate up close.',
      subject_treatment: `${keep}; draw the subject with smooth curves made of hand-placed intermediate pixels.`,
      color_and_tone: 'Clean palette with intermediate tones only along edges.',
      lighting_and_shadow: "Soft shading with neat ramps, kept consistent across the whole image.",
      texture_and_material: "Crisp pixels with smoothing steps on curves, kept consistent across the whole image.",
      camera_and_composition: 'Large curving shapes that show off the line quality.',
      atmosphere_and_mood: 'Keep the requested mood with polished crafted calm.',
      rendering_and_quality: "Precise elegant lines without jaggies, kept consistent across the whole image.",
      key_features: 'smooth pixel curves; intermediate edge pixels; crisp; deliberate',
    }, [], [
      'Curling across the whole card in one smooth pixel line, a sea serpent coils around a tiny lighthouse island, every curve softened by hand-placed edge pixels. No readable text or logo.',
      'Drawn with perfectly smoothed curves, a round cat has squeezed itself into a round bowl that is clearly two sizes too small. No readable text or logo.',
      'A crescent moon with a perfectly smooth curved edge hangs over a lake, and one pixel on its edge is the wrong color, like a small open door. No readable text or logo.',
    ]),
    study('Ordered Bayer Dither Field', 'regular matrix dithering', 'bayer-dither', {
      aesthetic: 'Ordered Bayer dither field: gradients built from a regular crosshatch matrix of pixels, mechanical and even, turning skies, fog and glow into precise patterned fields.',
      subject_treatment: `${keep}; build gradients and atmosphere around the subject from even ordered dither.`,
      color_and_tone: 'A few flat colors mixed through regular dither patterns.',
      lighting_and_shadow: "Soft light represented by dither density, kept consistent across the whole image.",
      texture_and_material: 'Regular matrix patterns, crisp pixels and flat areas.',
      camera_and_composition: 'Large gradient areas where the dither can show.',
      atmosphere_and_mood: 'Keep the requested mood with cool mechanical beauty.',
      rendering_and_quality: "Precise regular dithering without random noise, kept consistent across the whole image.",
      key_features: 'ordered dither matrix; gradient fields; few colors; crisp pixels',
    }, ['random noise dither'], [
      'Across a sky dithered in precise ordered patterns from night blue to dawn pink, a fleet of flying ships rises out of the clouds toward a dithered sun. No readable text or logo.',
      'In a field of regular dither fog, a lost goat stands on a hill wearing a small bell, confident it is not lost at all. No readable text or logo.',
      'A soft glow of ordered dither surrounds a single window in a dark tower, and the pattern becomes denser in the shape of a figure standing inside. No readable text or logo.',
    ]),
    study('Selective Colored Outline', 'colored sel-out pixel outlines', 'sel-out', {
      aesthetic: 'Selective colored outline: pixel art where outlines change color with the light, dark on the shadow side, light or colored on the lit side, blending sprites into their scene.',
      subject_treatment: `${keep}; outline the subject with colored lines that lighten on its lit side.`,
      color_and_tone: "Outline colors drawn from neighboring fills, kept consistent across the whole image.",
      lighting_and_shadow: "Directional light reflected in outline color, kept consistent across the whole image.",
      texture_and_material: "One-pixel colored outlines and clean fills, kept consistent across the whole image.",
      camera_and_composition: "Clear sprite silhouette within a scene, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with soft integrated charm.',
      rendering_and_quality: "Refined outlines that read cleanly, kept consistent across the whole image.",
      key_features: 'colored outlines; lit-side light line; dark shadow line; integrated sprite',
    }, [], [
      'Lit by a burning village behind it, a giant troll\'s outline glows orange on one side and fades to deep brown on the other as it steps over the rooftops. No readable text or logo.',
      'Standing in a sunbeam, a small mushroom creature has an outline that turns pale yellow where the light hits, and it is posing as if on stage. No readable text or logo.',
      'Half in moonlight, a hooded figure has a silver outline on one side and no outline at all on the other, as if part of it is not really there. No readable text or logo.',
    ]),
    study('Two-Tone Duotone Pixel', 'two-color pixel art', 'duotone-pixel', {
      aesthetic: 'Two-tone duotone pixel: pixel art using only two colors, a light and a dark, with pattern and silhouette doing all the work.',
      subject_treatment: `${keep}; render the subject using just two colors with patterned mid-values.`,
      color_and_tone: 'Exactly two colors, such as cream and deep plum.',
      lighting_and_shadow: 'Light and shadow made from patterns of the two colors.',
      texture_and_material: "Crisp pixels, checker and line patterns, kept consistent across the whole image.",
      camera_and_composition: "Strong silhouette-driven composition, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with stark graphic mystery.',
      rendering_and_quality: "Clear readable image with only two colors, kept consistent across the whole image.",
      key_features: 'two colors only; patterned mid-values; strong silhouette; crisp pixels',
    }, ['a third color'], [
      'In only cream and deep plum, a whale rises out of a patterned sea beneath a sky full of patterned birds, both colors doing all the work. No readable text or logo.',
      'Using just two colors, a goblin proudly shows off his new hat, which is only a slightly different pattern than his head. No readable text or logo.',
      'In two colors of mint and black, a corridor of doors stretches away, and one door in the middle is patterned differently from all the rest. No readable text or logo.',
    ]),
    study('Palette-Swap Twin Sprites', 'same sprite different palettes', 'palette-swap', {
      aesthetic: 'Palette-swap twin sprites: the same pixel sprite repeated side by side in different color palettes, a classic way to make new characters and rivals from one drawing.',
      subject_treatment: `${keep}; repeat the subject as identical sprites in different color palettes.`,
      color_and_tone: "Several distinct palettes on identical shapes, kept consistent across the whole image.",
      lighting_and_shadow: "Same shading structure in every palette, kept consistent across the whole image.",
      texture_and_material: "Identical pixel sprites with swapped colors, kept consistent across the whole image.",
      camera_and_composition: "Sprites lined up or facing each other, kept consistent across the whole image.",
      atmosphere_and_mood: "Keep the requested mood with playful rivalry, kept consistent across the whole image.",
      rendering_and_quality: "Pixel-identical sprites with clean palettes, kept consistent across the whole image.",
      key_features: 'identical sprites; swapped palettes; side by side; rivalry',
    }, [], [
      'Facing off across a bridge, a hero and his palette-swapped evil twin in black and red raise identical swords, both absolutely sure they are the real one. No readable text or logo.',
      'Seven identical slimes in seven different colors sit in a row, and the plain green one looks very insecure about it. No readable text or logo.',
      'In a hall of mirrors, one sprite is repeated in five palettes, and in the last mirror the palette is completely grey and the sprite is smiling. No readable text or logo.',
    ]),
    study('Seamless Pixel Tileset Sheet', 'tiling pixel environment tiles', 'tileset-sheet', {
      aesthetic: 'Seamless pixel tileset sheet: an environment assembled from repeating square pixel tiles of grass, stone, water and walls that fit together seamlessly into a scene.',
      subject_treatment: `${keep}; build the subject\'s environment from clearly repeating seamless tiles.`,
      color_and_tone: "Cohesive limited palette shared across tiles, kept consistent across the whole image.",
      lighting_and_shadow: "Consistent top-left light on every tile, kept consistent across the whole image.",
      texture_and_material: 'Repeating stone, grass and water tiles with seamless edges.',
      camera_and_composition: 'Top-down or side view showing the tile rhythm.',
      atmosphere_and_mood: 'Keep the requested mood with orderly handcrafted worlds.',
      rendering_and_quality: "Clean tiling with subtle variation tiles, kept consistent across the whole image.",
      key_features: 'seamless tiles; repeating rhythm; shared palette; variation tiles',
    }, [], [
      'Built from repeating stone and moss tiles, a ruined fortress sprawls across the card, and one tile in the wall is a hidden door that does not quite match. No readable text or logo.',
      "Planting crops in a perfect grid of repeating grass tiles, a farmer has not yet noticed that one tile holds a single carrot the size of a house. No readable text or logo.",
      'Made of repeating water tiles, a dark lake stretches out, and in one tile the ripple pattern goes in the opposite direction. No readable text or logo.',
    ]),
    study('Low-Count Pixel Portrait', 'tiny pixel character portrait', 'low-count-portrait', {
      aesthetic: 'Low-count pixel portrait: a character portrait in a tiny canvas such as thirty-two pixels square, where every single pixel carries an eye, a brow or a mood.',
      subject_treatment: `${keep}; reduce the subject to a tiny portrait where each pixel matters.`,
      color_and_tone: "Small bold palette with strong contrast, kept consistent across the whole image.",
      lighting_and_shadow: "One or two shading steps only, kept consistent across the whole image.",
      texture_and_material: "Very large visible pixels with no smoothing, kept consistent across the whole image.",
      camera_and_composition: 'Tight head portrait filling a tiny square canvas.',
      atmosphere_and_mood: 'Keep the requested mood with strong expression from minimal means.',
      rendering_and_quality: "Every pixel intentional and readable, kept consistent across the whole image.",
      key_features: 'tiny canvas; huge pixels; minimal expression; tight portrait',
    }, [], [
      'In a portrait only thirty-two pixels wide, an ancient dragon king is shown with one glowing eye that takes up exactly two pixels and still feels terrifying. No readable text or logo.',
      'A tiny pixel portrait of a grumpy innkeeper manages a very clear expression of disapproval using just four dark pixels. No readable text or logo.',
      'A tiny portrait shows a pale face with two black pixels for eyes, and one of the pixels is slightly lower than the other. No readable text or logo.',
    ]),
    study('Pixel Light Bloom Halo', 'stepped pixel glow', 'pixel-bloom', {
      aesthetic: 'Pixel light bloom halo: light sources surrounded by concentric stepped rings of pixel glow, lanterns, spells and crystals blooming into the dark in hard-edged bands.',
      subject_treatment: `${keep}; make the subject or its light source bloom in stepped rings of pixel glow.`,
      color_and_tone: "Dark scenes with bright stepped glow rings, kept consistent across the whole image.",
      lighting_and_shadow: "Radial stepped glow from light sources, kept consistent across the whole image.",
      texture_and_material: "Hard-edged glow bands and crisp pixels, kept consistent across the whole image.",
      camera_and_composition: "Light source central with darkness around, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with warm magical glow.',
      rendering_and_quality: "Clean ring steps without soft blur, kept consistent across the whole image.",
      key_features: 'stepped glow rings; dark scene; light source; hard bands',
    }, ['soft photographic bloom'], [
      'Deep underground, a miner holds up a crystal that blooms in stepped rings of blue light, revealing an entire sleeping cave dragon around her. No readable text or logo.',
      'A firefly lands on a sleeping frog\'s nose and glows in stepped pixel rings, lighting up its very annoyed expression. No readable text or logo.',
      'In a dark forest, a single lantern blooms in stepped orange rings, and at the edge of the last ring stands a figure the light does not quite reach. No readable text or logo.',
    ]),
    study('Pillow-Shaded Pixel Kitsch', 'naive pillow-shaded pixels', 'pillow-shading', {
      aesthetic: 'Pillow-shaded pixel kitsch: pixel art shaded inward from every outline like a pillow, ignoring any real light, a naive beginner look embraced for comedy and charm.',
      subject_treatment: `${keep}; shade the subject from its edges inward like a puffy pillow.`,
      color_and_tone: 'Bright colors getting lighter toward the center of each shape.',
      lighting_and_shadow: "No real light source; shading follows outlines, kept consistent across the whole image.",
      texture_and_material: "Puffy inward ramps and thick outlines, kept consistent across the whole image.",
      camera_and_composition: "Simple centered subject, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with lovable amateur charm.',
      rendering_and_quality: "Deliberately naive but clean pixels, kept consistent across the whole image.",
      key_features: 'pillow shading; inward ramps; no light source; puffy forms',
    }, [], [
      'Towering over a burning town, a terrifying demon lord is pillow-shaded so puffy that he looks like an inflatable toy, which he finds deeply insulting. No readable text or logo.',
      'A knight, a horse and a tree are all shaded like soft pillows, and the knight is trying to sit on the tree. No readable text or logo.',
      "Floating down an empty hallway, a ghost shaded puffy from every edge like a cushion seems sad that it is far too cute to frighten anyone. No readable text or logo.",
    ]),
    study('Clustered Pixel Foliage Canopy', 'pixel leaf cluster technique', 'pixel-foliage', {
      aesthetic: 'Clustered pixel foliage canopy: trees and bushes built from repeated hand-shaped leaf clusters in three or four greens, lit from above with dark gaps showing depth.',
      subject_treatment: `${keep}; surround the subject with dense canopies of repeating leaf clusters.`,
      color_and_tone: 'Three or four greens from lime highlight to deep teal shadow.',
      lighting_and_shadow: 'Top light on cluster tops, dark gaps between.',
      texture_and_material: "Hand-shaped leaf clusters, trunks and dappled ground, kept consistent across the whole image.",
      camera_and_composition: "Deep forest framing with light patches, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with lush green depth.',
      rendering_and_quality: "Consistent cluster shapes with readable layers, kept consistent across the whole image.",
      key_features: 'leaf clusters; layered greens; dark gaps; dappled light',
    }, [], [
      'Beneath a vast canopy of hand-shaped leaf clusters, a lost caravan has discovered that the forest is walking with them, the trees stepping forward in the dark gaps. No readable text or logo.',
      'Hidden in dense pixel foliage, a very round bird thinks it is invisible, although its bright red belly is the only red pixel for miles. No readable text or logo.',
      'Deep in layered green leaf clusters, a single patch of dappled light falls on a mossy stone where someone has left a small pair of shoes. No readable text or logo.',
    ]),
    study('Four-Ink Palette Scene', 'four-color constrained scene', 'four-ink', {
      aesthetic: 'Four-ink palette scene: a whole scene built from exactly four colors chosen as a mood, like ink, rust, bone and sea, where limits create strong atmosphere.',
      subject_treatment: `${keep}; render the subject and its world with exactly four chosen colors.`,
      color_and_tone: 'Exactly four harmonious colors covering dark to light.',
      lighting_and_shadow: "Light values mapped onto the four colors, kept consistent across the whole image.",
      texture_and_material: "Crisp pixels with minimal dither between colors, kept consistent across the whole image.",
      camera_and_composition: "Atmospheric scene with clear depth layers, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with strong unified atmosphere.',
      rendering_and_quality: "Disciplined palette with strong design, kept consistent across the whole image.",
      key_features: 'exactly four colors; unified mood; depth layers; crisp pixels',
    }, ['extra colors'], [
      'In only ink black, rust, bone and sea green, a ship of bones sails across a rust-colored ocean toward a sea green moon. No readable text or logo.',
      "At a village festival in full swing, only one thing appears in the palette's brightest color: the goose that has just stolen the pie. No readable text or logo.",
      "Descending into a flooded crypt rendered with just four muted colors, a stair ends at water that is the only thing in the lightest tone. No readable text or logo.",
    ]),
    study('High-Density Pixel Painting', 'large-canvas detailed pixel art', 'hd-pixel', {
      aesthetic: 'High-density pixel painting: modern large-canvas pixel art with painterly detail, many colors and atmospheric depth while every pixel is still hand-placed and crisp.',
      subject_treatment: `${keep}; render the subject with rich painterly detail using crisp hand-placed pixels.`,
      color_and_tone: "Rich atmospheric palette with many hues, kept consistent across the whole image.",
      lighting_and_shadow: "Painterly light, volumetric beams and depth haze, kept consistent across the whole image.",
      texture_and_material: "Detailed pixel textures, stone, cloth and foliage, kept consistent across the whole image.",
      camera_and_composition: "Cinematic wide composition with deep layers, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with cinematic painterly depth.',
      rendering_and_quality: "Crisp pixels at high detail, never blurred, kept consistent across the whole image.",
      key_features: 'large canvas; painterly pixels; atmospheric depth; crisp detail',
    }, [], [
      'In a vast painterly pixel canyon, beams of light fall on a colossal ruined statue whose broken hand holds a whole village in its palm. No readable text or logo.',
      'Painted in dense detailed pixels, a busy dragon laundry hangs giant scales out to dry while tiny workers run beneath them with baskets. No readable text or logo.',
      'In rich atmospheric pixels, a lighthouse stands on a rock in a sea of mist, and its beam lights up a second lighthouse that should not exist. No readable text or logo.',
    ]),
    study('Pixel Water Reflection', 'pixel water with broken reflections', 'pixel-water', {
      aesthetic: 'Pixel water reflection: water scenes where reflections are broken into horizontal pixel strips and highlight dashes, shimmering in stepped lines.',
      subject_treatment: `${keep}; place the subject above water that reflects it in broken pixel strips.`,
      color_and_tone: "Deep water blues with bright reflected colors, kept consistent across the whole image.",
      lighting_and_shadow: "Reflected light broken into horizontal dashes, kept consistent across the whole image.",
      texture_and_material: "Horizontal pixel strips, highlight dashes and ripples, kept consistent across the whole image.",
      camera_and_composition: "Horizon with subject above and reflection below, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with calm shimmering reflection.',
      rendering_and_quality: "Clean stepped reflections with readable shapes, kept consistent across the whole image.",
      key_features: 'broken reflection strips; highlight dashes; horizon; ripples',
    }, [], [
      'Above a still lake, a floating castle hangs in the sky, and its reflection in the pixel water below is broken into shimmering strips that show it upside down and on fire. No readable text or logo.',
      'A fisherman sits on a pier over water that reflects him in broken strips, and his reflection has caught a much bigger fish. No readable text or logo.',
      'At night, a small boat crosses a pixel lake, and in the rippling reflection there are two figures in the boat instead of one. No readable text or logo.',
    ]),
    study('Rim-Lit Pixel Silhouette', 'dark sprites with bright edge light', 'rim-lit-pixel', {
      aesthetic: 'Rim-lit pixel silhouette: dark near-black sprites outlined by a thin line of bright pixels where light from behind catches their edges.',
      subject_treatment: `${keep}; render the subject as a dark silhouette with a thin bright pixel rim.`,
      color_and_tone: 'Near-black figures with bright gold or cyan edge pixels.',
      lighting_and_shadow: "Strong backlight creating one-pixel rims, kept consistent across the whole image.",
      texture_and_material: "Dark flat fills and crisp bright edges, kept consistent across the whole image.",
      camera_and_composition: 'Figures against a bright sky or glowing source.',
      atmosphere_and_mood: 'Keep the requested mood with dramatic backlit mystery.',
      rendering_and_quality: "Clean rims and strong silhouettes, kept consistent across the whole image.",
      key_features: 'dark silhouettes; one-pixel rim light; backlight; strong shapes',
    }, [], [
      'Against an enormous rising sun, a line of knights on horseback is reduced to black silhouettes, each rider traced by a single line of gold pixels. No readable text or logo.',
      'Backlit by a glowing campfire, a small raccoon is only a dark shape with bright edges, holding up a stolen sausage like a trophy. No readable text or logo.',
      'In front of a glowing doorway, a tall figure stands as a black silhouette, and the thin rim of light around it has a gap where its face should be. No readable text or logo.',
    ]),
    study('Palette-Shifted Night Scene', 'day scene shifted to night palette', 'night-palette', {
      aesthetic: 'Palette-shifted night scene: a pixel scene whose whole palette has been shifted to night, blues and purples replacing daylight colors, with a few warm lights left burning.',
      subject_treatment: `${keep}; set the subject in a scene whose palette is shifted to cool night.`,
      color_and_tone: 'Indigo, violet and teal with a few warm window lights.',
      lighting_and_shadow: "Moonlight tint everywhere, warm pools around lights, kept consistent across the whole image.",
      texture_and_material: "Same crisp pixels with cool shifted colors, kept consistent across the whole image.",
      camera_and_composition: 'Village or landscape with a few glowing points.',
      atmosphere_and_mood: 'Keep the requested mood with hushed nocturnal quiet.',
      rendering_and_quality: "Consistent night palette with readable detail, kept consistent across the whole image.",
      key_features: 'night palette shift; indigo tones; warm window lights; moonlight',
    }, [], [
      'In a village shifted to indigo night, the townsfolk sleep while a giant owl the size of the bell tower perches on the church and watches the only lit window. No readable text or logo.',
      'Under a violet night palette, a baker is already awake, and the warm glow from the oven is lighting up three cats waiting outside the door. No readable text or logo.',
      'In a cool night palette, every window in the street is dark except one warm window at the end, which was boarded up yesterday. No readable text or logo.',
    ]),
  ],
};

export default spec;
