import type { Create, Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Material surface textures (pack_10) are decorative surface patterns — the visible figure, grain
// or finish pattern — as opposed to pack_09's physical material behavior.
const AVOID = [...MATERIAL_AVOID, 'plain untextured surface'];
const s = (a: string, b: string, c: string, l: string, t: string, m: string, k: string) =>
  material(
    a,
    `${b} The decorative surface pattern is the point: make its figure, veining or motif the first read.`,
    c,
    l,
    t,
    m,
    `${k}; decorative surface pattern`,
  );

const spec: Spec = {
  pack: 'pack_10',
  category: '6. Material Surface Textures',
  updates: {
    'SP10-048': {
      dna: s(
        'Terrazzo: polished composite with scattered stone and glass chips in a cement matrix.',
        'the surface shows scattered colored chips set in a smooth matrix.',
        'Cream matrix with terracotta, green and black chips.',
        'Soft even light on polished surface.',
        'Polished chips flush in matrix.',
        'Playful, modern, crafted and bright.',
        'scattered chips; polished matrix',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a knight statue finished in polished terrazzo with terracotta and green chips. No text or logo.',
        'Photograph of a terrazzo dragon egg. No text or logo.',
        'Photograph of a terrazzo throne. No text or logo.',
      ],
    },
    'SP10-054': {
      dna: s(
        'Marble veining texture: dramatic flowing veins across polished stone.',
        "bold flowing veins sweep across the target's surfaces.",
        'White, black or green marble with gold or grey veins.',
        'Polished reflections.',
        'Flowing veins and polish.',
        'Luxurious, dramatic, cool and grand.',
        'dramatic flowing veins',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a black marble dragon with dramatic gold veins sweeping along its body. No text or logo.',
        'Photograph of a green marble knight. No text or logo.',
        'Photograph of a veined marble crown. No text or logo.',
      ],
    },
    'SP10-055': {
      dna: s(
        'Wood grain texture: bold flowing grain lines and knots across the surface.',
        'strong grain lines flow around knots over the surfaces.',
        'Warm wood tones with dark grain.',
        'Warm side light.',
        'Flowing grain and knots.',
        'Warm, organic, handcrafted and natural.',
        'flowing grain lines; knots',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a wooden owl whose grain lines flow around its eyes like feathers. No text or logo.',
        'Photograph of a wood-grained knight. No text or logo.',
        'Photograph of a wood-grained violin-shaped shield. No text or logo.',
      ],
    },
    'SP10-056': {
      dna: s(
        'Carbon fiber weave: glossy twill pattern of black fibers.',
        'a glossy 2x2 twill carbon weave covers the surfaces.',
        'Black and graphite with gloss.',
        'Strip light across the weave.',
        'Twill weave under clear coat.',
        'High-tech, sleek, sporty and modern.',
        'twill carbon weave; glossy',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a carbon-fiber twill knight's helmet under strip light. No text or logo.",
        'Photograph of a carbon-fiber dragon. No text or logo.',
        'Photograph of a carbon-fiber violin. No text or logo.',
      ],
    },
    'SP10-059': {
      dna: s(
        'Leather texture: pebbled or embossed leather grain with stitching.',
        'embossed leather grain and saddle stitching cover the surfaces.',
        'Cognac, black, oxblood.',
        'Soft side light.',
        'Grain, stitching and edge paint.',
        'Crafted, warm, rugged and classic.',
        'leather grain; saddle stitching',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a leather-textured dragon egg with saddle stitching. No text or logo.',
        'Photograph of a tooled leather knight. No text or logo.',
        'Photograph of a leather-covered book-shaped chest. No text or logo.',
      ],
    },
    'SP10-060': {
      dna: s(
        'Glitter texture: dense sparkling glitter coating.',
        'dense multicolor glitter coats the surfaces.',
        'Gold, silver or rainbow glitter.',
        'Point lights for sparkle.',
        'Glitter flakes.',
        'Festive, playful, sparkly and kitsch.',
        'dense glitter sparkle',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a gold-glitter-coated skull on velvet. No text or logo.',
        'Photograph of a glitter dragon. No text or logo.',
        'Photograph of a glitter knight. No text or logo.',
      ],
    },
    'SP10-061': {
      dna: s(
        'Rust texture: decorative rust blooms and streaks as surface pattern.',
        'orange rust blooms and streaks pattern the surface.',
        'Orange and brown on grey.',
        'Warm light.',
        'Rust blooms and streaks.',
        'Aged, industrial, raw and warm.',
        'rust blooms and streaks',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a rust-patterned dragon sculpture. No text or logo.',
        'Photograph of a rust-patterned throne. No text or logo.',
        'Photograph of a rust-patterned bell. No text or logo.',
      ],
    },
    'SP10-062': {
      dna: s(
        'Holographic foil: rainbow diffraction foil that shifts color with angle.',
        'holographic diffraction foil covers the surfaces with shifting rainbows.',
        'Rainbow diffraction over silver.',
        'Point lights for diffraction.',
        'Foil with diffraction pattern.',
        'Futuristic, playful, shiny and pop.',
        'holographic diffraction foil',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a holographic-foil knight's armor shifting rainbows. No text or logo.",
        'Photograph of a holographic dragon. No text or logo.',
        'Photograph of a holographic crown. No text or logo.',
      ],
    },
    'SP10-063': {
      dna: s(
        'Chainmail texture: ring pattern as a decorative surface.',
        'fine interlocking ring pattern covers the surfaces.',
        'Steel, silver, bronze.',
        'Sparkling light on rings.',
        'Interlocking rings.',
        'Armored, ancient, elegant and heavy.',
        'interlocking ring pattern',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a chainmail-textured swan sculpture. No text or logo.',
        'Photograph of a chainmail-textured teapot. No text or logo.',
        'Photograph of a chainmail-textured mask. No text or logo.',
      ],
    },
    'SP10-064': {
      dna: s(
        'Snake skin texture: scale pattern with bold markings as decorative surface.',
        'patterned snake scales cover the surfaces with bold markings.',
        'Python browns or emerald.',
        'Soft sheen.',
        'Overlapping scales and markings.',
        'Exotic, sleek, dangerous and luxe.',
        'snake scale markings',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a python-patterned knight's gauntlet. No text or logo.",
        'Photograph of a snakeskin throne. No text or logo.',
        'Photograph of a snakeskin violin. No text or logo.',
      ],
    },
    'SP10-071': {
      dna: s(
        'Kintsugi: broken ceramic repaired with gold-filled seams.',
        'the surfaces show cracks repaired with bright gold seams.',
        'Ceramic base with gold seams.',
        'Soft light catching gold.',
        'Gold-lacquer seams across cracks.',
        'Resilient, poetic, precious and calm.',
        'gold-repaired cracks',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's helmet repaired with kintsugi gold seams. No text or logo.",
        'Photograph of a kintsugi dragon mask. No text or logo.',
        'Photograph of a kintsugi skull. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Raku Crackle Glaze',
      domain: 'raku crackle glaze',
      tags: ['raku', 'crackle', 'surface'],
      dna: s(
        'Raku glaze: crackled white glaze with smoky black craze lines and metallic flashes.',
        'crackled glaze with smoky black lines and copper flashes covers the surfaces.',
        'White crackle with black lines and copper flashes.',
        'Soft light.',
        'Crazed glaze and smoky carbon.',
        'Earthy, fiery, random and beautiful.',
        'raku crackle; smoky lines; copper flash',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a raku-glazed dragon skull with smoky black crackle and copper flashes. No text or logo.',
        'Raku knight helmet. No text or logo.',
        'Raku owl. No text or logo.',
      ],
    },
    {
      name: 'Damascus Steel',
      domain: 'damascus pattern-welded steel',
      tags: ['damascus', 'steel', 'surface'],
      dna: s(
        'Damascus steel: flowing layered wave patterns in etched steel.',
        'flowing etched Damascus layers pattern the metal surfaces.',
        'Dark and light grey steel waves.',
        'Raking light.',
        'Etched layered wave pattern.',
        'Crafted, deadly, elegant and ancient.',
        'Damascus wave pattern',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a Damascus-steel crown with flowing etched waves. No text or logo.',
        'Damascus steel gauntlet. No text or logo.',
        'Damascus steel dragon. No text or logo.',
      ],
    },
    {
      name: 'Burl Wood Figure',
      domain: 'burl wood figure',
      tags: ['burl', 'wood', 'surface'],
      dna: s(
        'Burl wood: swirling chaotic grain with eyes and clusters.',
        'swirling burl figure with tiny eyes covers the surfaces.',
        'Amber, honey and dark swirls.',
        'Warm glossy light.',
        'Chaotic swirls and eyes.',
        'Rich, organic, warm and rare.',
        'swirling burl figure; eyes',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a burl-wood dragon egg with swirling figure. No text or logo.',
        'Burl wood throne. No text or logo.',
        'Burl wood violin. No text or logo.',
      ],
    },
    {
      name: 'Mokume-gane',
      domain: 'mokume-gane layered metal',
      tags: ['mokume-gane', 'metal', 'surface'],
      dna: s(
        'Mokume-gane: layered mixed metals forming wood-grain-like patterns.',
        'wood-grain patterns of layered copper, silver and gold cover the surfaces.',
        'Copper, silver and gold bands.',
        'Soft metallic light.',
        'Layered metal grain.',
        'Refined, crafted, precious and warm.',
        'layered metal grain',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a mokume-gane knight's helmet with copper-silver grain. No text or logo.",
        'Mokume-gane ring on velvet. No text or logo.',
        'Mokume-gane dragon. No text or logo.',
      ],
    },
    {
      name: 'Tadelakt Plaster',
      domain: 'tadelakt polished plaster',
      tags: ['tadelakt', 'plaster', 'surface'],
      dna: s(
        'Tadelakt: burnished lime plaster with soft sheen and subtle cloudy variation.',
        'soft burnished plaster with cloudy tone variation covers the surfaces.',
        'Terracotta, sand, sage.',
        'Soft warm light.',
        'Burnished plaster sheen.',
        'Calm, earthy, warm and soft.',
        'burnished plaster; cloudy sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a tadelakt-plastered knight statue in terracotta. No text or logo.',
        'Tadelakt dragon. No text or logo.',
        'Tadelakt throne. No text or logo.',
      ],
    },
    {
      name: 'Cloisonné Enamel',
      domain: 'cloisonne enamel',
      tags: ['cloisonne', 'enamel', 'surface'],
      dna: s(
        'Cloisonné: glossy colored enamel fields separated by fine gold wire cells.',
        'glossy enamel fields in gold wire cells cover the surfaces.',
        'Turquoise, cobalt, coral, gold.',
        'Glossy light.',
        'Enamel and gold wire.',
        'Ornate, precious, bright and refined.',
        'enamel in gold wire cells',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a cloisonné dragon with turquoise enamel cells. No text or logo.',
        'Cloisonné helmet. No text or logo.',
        'Cloisonné egg. No text or logo.',
      ],
    },
    {
      name: 'Guilloché Engraving',
      domain: 'guilloche engine turning',
      tags: ['guilloche', 'engraving', 'surface'],
      dna: s(
        'Guilloché: machine-engraved repeating wave and sunburst patterns under enamel.',
        'fine engine-turned wave and sunburst patterns cover the surfaces.',
        'Silver or gold with translucent enamel.',
        'Light rippling in grooves.',
        'Engine-turned grooves.',
        'Precise, luxurious, hypnotic and refined.',
        'engine-turned grooves; sunburst',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a guilloché-engraved shield with sunburst grooves. No text or logo.',
        'Guilloché crown. No text or logo.',
        'Guilloché dragon egg. No text or logo.',
      ],
    },
    {
      name: 'Urushi Lacquer',
      domain: 'urushi lacquer finish',
      tags: ['urushi', 'lacquer', 'surface'],
      dna: s(
        'Urushi lacquer: deep glossy lacquer in black and vermilion with maki-e gold sprinkles.',
        'deep glossy lacquer with gold sprinkle motifs covers the surfaces.',
        'Black and vermilion with gold.',
        'Deep glossy reflections.',
        'Layered lacquer and gold dust.',
        'Refined, deep, precious and calm.',
        'deep lacquer; maki-e gold',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a black urushi-lacquered samurai helmet with gold maki-e cranes. No text or logo.',
        'Urushi dragon box. No text or logo.',
        'Urushi knight shield. No text or logo.',
      ],
    },
    {
      name: 'Hammered Metal',
      domain: 'hammered metal texture',
      tags: ['hammered', 'metal', 'surface'],
      dna: s(
        'Hammered metal: dimpled facets from hand hammering catching light.',
        'hand-hammered dimples facet the metal surfaces.',
        'Copper, brass or pewter.',
        'Point lights sparkling on dimples.',
        'Hammered facets.',
        'Handmade, warm, rustic and crafted.',
        'hammered dimples',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a hammered-copper dragon with dimpled facets glinting. No text or logo.',
        'Hammered brass crown. No text or logo.',
        "Hammered pewter goblet with a knight's crest. No text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
