import type { Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Man-made materials: the finish, not the source product (rubber, not a tire; brick bond, not a
// whole wall). Assembly-profile materials keep their construction pattern.
const AVOID = [...MATERIAL_AVOID, 'replacing the target with the source product'];

const spec: Spec = {
  pack: 'pack_09',
  category: '2. Man-Made Materials',
  updates: {
    'SP09-017': {
      dna: material(
        'Brushed aluminum: satin metal with fine parallel brush lines and soft anisotropic highlights.',
        'the target is made of brushed aluminum with fine directional grain and machined edges.',
        'Cool silver-grey with soft white highlights.',
        'Strip light producing stretched anisotropic highlights.',
        'Satin aluminum with fine parallel brush lines and chamfered edges.',
        'Precise, modern, cool and engineered.',
        'brushed satin aluminum; parallel brush lines; anisotropic highlight; machined edges',
      ),
      avoid: AVOID,
      briefs: [
        "In a stone hall stands a full suit of armor machined from brushed aluminum, chamfered edges catching soft stretched highlights. No readable text or logo.",
        "On a dark plinth a beast's skull machined from brushed aluminum shows fine parallel brush lines running along the jaw. No readable text or logo.",
        "In a white gallery a rocking horse of brushed aluminum rocks gently, one long satin highlight sliding across its flank. No readable text or logo.",
      ],
    },
    'SP09-019': {
      dna: material(
        'Gold leaf: thin beaten gold applied over the target with visible leaf seams, crackle and burnish.',
        'the target is gilded with gold leaf showing leaf seams, crackle and burnished highlights.',
        'Warm yellow gold with red bole showing through cracks.',
        'Warm raking light for burnish and leaf edges.',
        'Gold leaf squares with seams, crackle and burnish.',
        'Sacred, precious, opulent and still.',
        'gold leaf seams; crackle over red bole; burnished highlights',
      ),
      avoid: AVOID,
      briefs: [
        "On black velvet lies a wolf skull covered in thin beaten gold, square leaf seams and fine crackle across the burnished brow. No readable text or logo.",
        "A small rowboat wrapped entirely in gold leaf drifts on a dark lake at night, reflecting the moon in broken gilded plates. No readable text or logo.",
        "Leaning against a weathered church wall, an old bicycle covered in cracked gold leaf shines on its frame and dulls on its spokes. No readable text or logo.",
      ],
    },
    'SP09-020': {
      dna: material(
        'Copper patina: aged copper with verdigris green bloom over bronze-brown metal.',
        'the target is made of copper with verdigris patina in recesses and bright copper on worn edges.',
        'Verdigris green, teal and warm copper orange.',
        'Soft overcast light.',
        'Copper sheet with oxidized verdigris crust and worn bright edges.',
        'Aged, weathered, noble and calm.',
        'verdigris patina; bright worn copper edges; teal and orange',
      ),
      avoid: AVOID,
      briefs: [
        "On a town square in the rain a copper statue of a soldier weeps streaks of green verdigris from his helmet over the bronze-brown metal. No readable text or logo.",
        "Inside a Victorian greenhouse a piano sheathed in aged copper blooms with verdigris in the corners as ferns lean over the lid. No readable text or logo.",
        "On a slate rooftop at dusk a copper owl pools green verdigris in its feather grooves while real pigeons keep their distance. No readable text or logo.",
      ],
    },
    'SP09-021': {
      dna: material(
        'Forged carbon fiber: marbled chopped-fiber composite under a glossy clear coat.',
        'the target is molded from forged carbon with marbled black-grey fiber pattern under gloss.',
        'Black and graphite marbling with glossy highlights.',
        'Hard studio light for clear-coat reflections.',
        'Forged carbon composite with marbled chopped fibers and clear coat.',
        'High-tech, sleek, strong and aggressive.',
        'marbled forged carbon; glossy clear coat; graphite and black',
      ),
      avoid: AVOID,
      briefs: [
        "On a dark plinth a helmet of forged carbon fiber swirls with marbled chopped fibers beneath a deep glossy clear coat. No readable text or logo.",
        "A cello made of forged carbon fiber rests on grey felt, the marbled texture flowing across its body like dark smoke. No readable text or logo.",
        "In a bare concrete room a throne of forged carbon fiber reflects a single bulb in its mirror clear coat. No readable text or logo.",
      ],
    },
    'SP09-022': {
      dna: material(
        'Raw concrete: board-formed or cast concrete with tie holes, air voids and grey mineral texture.',
        'the target is cast in raw concrete with formwork marks and air voids.',
        'Cool grey concrete with darker water stains.',
        'Flat overcast light that reads texture.',
        'Cast concrete with board marks, tie holes and pits.',
        'Brutal, heavy, austere and monumental.',
        'board-formed concrete; tie holes; air voids; cool grey',
      ),
      avoid: AVOID,
      briefs: [
        "In a wild meadow lies a sleeping beast cast in raw concrete, board-form wood grain imprinted on its flanks and tie holes along its spine. No readable text or logo.",
        "Inside a brutalist church a pipe organ cast in board-formed concrete is lit by a single shaft of light through the air voids. No readable text or logo.",
        "By a tall window a cast-concrete armchair wears a soft wool blanket over one arm, air voids speckling its seat. No readable text or logo.",
      ],
    },
    'SP09-023': {
      dna: material(
        'Aged brick: fired clay bricks in a running or Flemish bond, with worn edges and lime mortar.',
        'the target is built from aged brick in a visible bond pattern with lime mortar joints.',
        'Red, rust, brown and soot-darkened brick with pale mortar.',
        'Warm late sun on the brick face.',
        'Fired clay bricks with chipped edges, efflorescence and mortar.',
        'Industrial, sturdy, historic and warm.',
        'aged brick bond; lime mortar joints; chipped edges; efflorescence',
      ),
      avoid: AVOID,
      briefs: [
        "In an empty factory yard stands a giant horse built from aged red bricks in Flemish bond, lime mortar crumbling from its knees. No readable text or logo.",
        "In a ruined hall a throne of old fired bricks shows worn corners and a sapling growing out of the mortar. No readable text or logo.",
        "Floating impossibly on a still city canal, a rowboat built from aged bricks mirrors its orange hull in the water. No readable text or logo.",
      ],
    },
    'SP09-024': {
      dna: material(
        'Wet asphalt: dark aggregate surface slick with water and mirror reflections.',
        'the target is coated in dark asphalt aggregate made glossy and reflective by water.',
        'Near-black with grey aggregate and reflected lights.',
        'Night light with reflections of lamps.',
        'Asphalt aggregate with wet sheen and puddle reflections.',
        'Urban, moody, nocturnal and slick.',
        'wet asphalt aggregate; mirror reflections; night sheen',
      ),
      avoid: AVOID,
      briefs: [
        "On a city corner at night a statue coated in wet black asphalt shines with street lamps and red taillights. No readable text or logo.",
        "A grand staircase surfaced in wet asphalt glistens in heavy rain, puddles on each step mirroring neon light from across the street. No readable text or logo.",
        "Headlights sweep across a wolf sculpture surfaced in wet asphalt, rain pooling in the grit along its back. No readable text or logo.",
      ],
    },
    'SP09-026': {
      dna: material(
        'Injection-molded plastic: smooth toy-like plastic with slight gloss, parting lines and rounded edges.',
        'the target is molded from colored plastic with parting lines, sprue marks and rounded edges.',
        'Saturated primary or pastel plastic colors.',
        'Bright soft studio light.',
        'Smooth molded plastic with parting lines and slight gloss.',
        'Playful, toy-like, clean and artificial.',
        'molded plastic; parting lines; rounded edges; saturated color',
      ),
      avoid: AVOID,
      briefs: [
        "A life-size guardsman in red molded plastic armor stands at a palace gate, parting lines running down the middle of his face. No readable text or logo.",
        "Lying on a suburban lawn, a glossy yellow plastic dinosaur the size of a car shows parting lines along its spine and rounded toy edges. No readable text or logo.",
        "Set into an ancient stone wall, a cathedral door molded in pastel blue plastic has parting lines running through its carved saints. No readable text or logo.",
      ],
    },
    'SP09-027': {
      dna: material(
        'Vulcanized rubber: matte black rubber with molded tread-like ridges and slight wear.',
        'the target is made of matte black rubber with molded ridges and scuffs, without becoming a tire.',
        'Matte black and charcoal grey.',
        'Soft light showing matte texture.',
        'Vulcanized rubber with molded ridges, scuffs and mold lines.',
        'Industrial, tough, flexible and heavy.',
        'matte vulcanized rubber; molded ridges; scuffs',
      ),
      avoid: [...AVOID, 'tire object'],
      briefs: [
        "On a steel workshop table sits a vintage typewriter molded entirely from matte black rubber, tread ridges across the carriage. No readable text or logo.",
        "In an empty warehouse a horse molded from vulcanized rubber shows tread-like ridges along its mane and smooth worn knees. No readable text or logo.",
        "In a concrete room a throne molded from black tire rubber has deep tread ridges on the back and a worn smooth seat. No readable text or logo.",
      ],
    },
    'SP09-028': {
      dna: material(
        'Shattered glass: glass surfaces crazed with radial cracks and missing shards, held in place.',
        'the target is made of glass that is cracked in radial spiderweb patterns, still holding its shape.',
        'Clear glass with green edges and white fracture lines.',
        'Backlight catching the cracks.',
        'Glass with radial fractures, spiderweb cracks and chipped edges.',
        'Fragile, tense, dramatic and dangerous.',
        'radial spiderweb cracks; chipped glass edges; backlit fractures',
      ),
      avoid: AVOID,
      briefs: [
        "Goldfish swim calmly past a web of radial cracks spreading from one impact point across a tall aquarium that somehow still holds its water. No readable text or logo.",
        "On a velvet cushion a clear glass crown is crazed with fine cracks, one point missing its tip under a spotlight. No readable text or logo.",
        "Floating on a still lake at dawn, a swan of clear crazed glass is missing shards from one wing, cracks spreading from its neck. No readable text or logo.",
      ],
    },
    'SP09-031': {
      dna: material(
        'Shiny latex: stretched glossy rubber film with sharp specular streaks.',
        'the target is skinned in glossy stretched latex with tight specular streaks.',
        'Black, red or colored latex with white highlights.',
        'Strip lights drawing highlights along curves.',
        'Glossy latex skin with stretch and tight reflections.',
        'Sleek, provocative, strange and polished.',
        'glossy latex skin; specular streaks; stretched surface',
      ),
      avoid: [...AVOID, 'explicit fetish content'],
      briefs: [
        "Coiled on a black floor, a sea serpent skinned in stretched glossy red latex carries sharp white specular streaks along its spine. No readable text or logo.",
        "In a white room an armchair wrapped in taut black latex shows long sharp highlights following every curve. No readable text or logo.",
        "Draped over a white plinth, an octopus skinned in shiny black latex slides specular streaks along each tentacle. No readable text or logo.",
      ],
    },
    'SP09-032': {
      dna: material(
        'Cardboard: corrugated brown cardboard with exposed flutes, tape and crushed edges.',
        'the target is built from corrugated cardboard with exposed flutes, tape joints and creases.',
        'Kraft brown, beige and grey tape.',
        'Soft daylight.',
        'Corrugated cardboard with flutes, creases and packing tape.',
        'Handmade, playful, humble and improvised.',
        'corrugated cardboard; exposed flutes; tape joints; creases',
      ),
      avoid: AVOID,
      briefs: [
        "Parked on a rainy street, a full-size cardboard tuk-tuk sags at the joints, parcel tape peeling and flutes exposed at every edge. No readable text or logo.",
        "Folded around the sofa with its snout crushed against the ceiling, a corrugated dragon made of taped boxes fills an entire living room. No readable text or logo.",
        "In a garage a cardboard cathedral rises to the rafters, pointed arches cut from boxes and a rose window of exposed flutes. No readable text or logo.",
      ],
    },
    'SP09-042': {
      dna: material(
        'Bubble wrap: clear plastic sheet with rows of air cells wrapped over the target.',
        'the target is wrapped in or made of clear bubble wrap with visible air cells.',
        'Clear with bright highlights on each bubble.',
        'Bright light making bubbles glint.',
        'Bubble wrap with air cells, creases and tape.',
        'Playful, protective, absurd and light.',
        'bubble wrap cells; glinting highlights; wrapped folds',
      ),
      avoid: AVOID,
      briefs: [
        "In a dim museum storeroom a stuffed polar bear waits wrapped in clear bubble wrap, rows of air cells catching the fluorescent light. No readable text or logo.",
        "In a bare white room a throne wrapped in bubble wrap bulges over its carved armrests, a few cells already popped. No readable text or logo.",
        "In a shipping warehouse a vintage motorcycle is wrapped in layers of bubble wrap, its chrome blurred beneath the air cells. No readable text or logo.",
      ],
    },
    'SP09-046': {
      dna: material(
        'Sequins: overlapping sequins or paillettes covering the target and scattering light.',
        'the target is covered edge to edge in overlapping sequins.',
        'Gold, silver, ruby or iridescent sequins.',
        'Point lights producing sparkle.',
        'Overlapping sequins with individual reflections.',
        'Glamorous, festive, dazzling and loud.',
        'overlapping sequins; scattered sparkle; point-light glitter',
      ),
      avoid: AVOID,
      briefs: [
        "On a dark stage a flamingo covered in overlapping pink and coral sequins stands on one leg, each paillette catching the spotlight. No readable text or logo.",
        "In a candlelit hall a throne covered in gold sequins shimmers, a few loose paillettes scattered across the stone. No readable text or logo.",
        "A life-size horse covered in silver sequins grazes in a green field at golden hour, sequins rippling across its muscles. No readable text or logo.",
      ],
    },
    'SP09-048': {
      dna: material(
        'Cork: granulated cork board with speckled texture and soft pinholes.',
        'the target is made of granulated cork with speckled texture.',
        'Warm tan, brown and dark speckles.',
        'Soft warm light.',
        'Granular cork with pinholes and compressed grains.',
        'Warm, light, natural and homely.',
        'granulated cork; speckled texture; pinholes',
      ),
      avoid: AVOID,
      briefs: [
        "On a wooden desk an old globe made of granulated cork shows soft pinholes where a traveler marked every trip. No readable text or logo.",
        "Perched on a mossy branch, an owl carved from cork has speckled granules and soft pinholes across its chest. No readable text or logo.",
        "In a sunlit reading room an armchair upholstered in cork board still has a few pushpins stuck in the seat. No readable text or logo.",
      ],
    },
    'SP09-049': {
      name: 'Hook-and-Loop Fastener',
      dna: material(
        'Hook-and-loop fastener: dense nylon hooks and loops covering the target in fuzzy and bristly zones.',
        'the target is covered in hook-and-loop fabric panels, bristly hooks and fuzzy loops.',
        'Black, grey or bright nylon colors.',
        'Soft raking light for micro-texture.',
        'Nylon hooks and loops with fuzzy and bristly zones.',
        'Tactile, odd, practical and playful.',
        'hook-and-loop panels; bristly hooks; fuzzy loops',
      ),
      avoid: AVOID,
      briefs: [
        "On a mountain trail a hiking backpack and boots are covered in black hook-and-loop panels, burrs and leaves stuck all over them. No readable text or logo.",
        "On a windowsill sits a cat statue covered in grey hook-and-loop fastener, fuzzy loops on the body and bristly hooks on the ears. No readable text or logo.",
        "An indoor climbing wall covered in hook-and-loop fastener holds an adult climber stuck to it in a fuzzy jumpsuit, arms spread. No readable text or logo.",
      ],
    },
    'SP09-060': {
      dna: material(
        'Liquid mercury: mirror liquid metal that pools, beads and ripples over the target.',
        'the target is made of liquid mirror metal that holds its form while rippling and beading.',
        'Chrome silver reflecting surroundings.',
        'Environment reflections and hard highlights.',
        'Liquid metal with ripples, beads and mirror reflection.',
        'Uncanny, fluid, futuristic and cold.',
        'liquid mirror metal; ripples and beads; environment reflections',
      ),
      avoid: AVOID,
      briefs: [
        "A heron rises from a pool of liquid mercury in a stone courtyard, mirror metal streaming from its wings in heavy beads. No readable text or logo.",
        "A horse of liquid mercury gallops along a wet beach, splashing into silver beads with every stride. No readable text or logo.",
        "On a velvet cushion a crown of liquid mercury slowly sags and pools, perfect reflections trembling on its surface. No readable text or logo.",
      ],
    },
    'SP09-070': {
      name: 'Expanded Polystyrene Foam',
      dna: material(
        'Polystyrene foam: white expanded foam with visible beads, carved edges and crumbs.',
        'the target is carved from white expanded polystyrene with bead texture and hot-wire cuts.',
        'Bright white with soft grey shadows.',
        'Soft even light.',
        'Expanded foam beads, hot-wire cut faces and crumbs.',
        'Light, cheap, clean and temporary.',
        'white expanded foam; bead texture; hot-wire cuts',
      ),
      avoid: AVOID,
      briefs: [
        "On a film-set floor a white polystyrene giant tortoise shows hot-wire carved shell plates and a scatter of foam crumbs. No readable text or logo.",
        "In a prop workshop a white foam mammoth skull with crisp hot-wire cuts looms over a sleeping carpenter. No readable text or logo.",
        "On a workshop table a large polystyrene cathedral model sheds white beads beside the hot-wire cutter that made it. No readable text or logo.",
      ],
    },
    'SP09-071': {
      dna: material(
        'Plywood: laminated veneer sheets with visible ply edges and wood grain faces.',
        'the target is built from plywood sheets with exposed layered edges.',
        'Birch cream, tan and darker glue lines.',
        'Soft daylight.',
        'Plywood with layered edges, grain faces and screws.',
        'Constructive, modern, honest and handmade.',
        'plywood layered edges; birch faces; screw joints',
      ),
      avoid: AVOID,
      briefs: [
        "In a woodworking shop a plywood giraffe shows exposed layered edges along its neck, sawdust piled at its hooves. No readable text or logo.",
        "A canoe of bent plywood rests on two sawhorses, its ply edges striped along the gunwales and brass screws gleaming. No readable text or logo.",
        "In a white gallery a spiral staircase of stacked plywood sheets forms striped treads and a layered handrail. No readable text or logo.",
      ],
    },
    'SP09-072': {
      dna: material(
        'Oriented strand board: pressed wood flakes in a chaotic mosaic of strands.',
        'the target is made of OSB with visible pressed wood strands.',
        'Golden tan and brown flakes.',
        'Flat light for the strand pattern.',
        'Pressed wood strands with resin and rough edges.',
        'Raw, industrial, rough and practical.',
        'pressed wood strands; OSB mosaic; rough edges',
      ),
      avoid: AVOID,
      briefs: [
        "In an old barn stands a full-size elephant built from oriented strand board, a chaotic mosaic of pressed flakes across its hide. No readable text or logo.",
        "On an empty beach a lifeguard tower of oriented strand board shows its pressed flake mosaic bleaching in the sun. No readable text or logo.",
        "Set in a stone portal, a tall arched door made of strand board is fitted with old iron hinges. No readable text or logo.",
      ],
    },
    'SP09-073': {
      dna: material(
        'Linoleum: smooth resilient sheet with marbled color flecks and slight sheen.',
        'the target is surfaced with marbled linoleum with seams.',
        'Marbled beige, mint, rust or grey.',
        'Flat institutional light.',
        'Smooth linoleum with marbled flecks and seams.',
        'Institutional, retro, clean and quiet.',
        'marbled linoleum; seams; soft sheen',
      ),
      avoid: AVOID,
      briefs: [
        "In a small diner a jukebox surfaced with mint green marbled linoleum shows color flecks under a soft sheen. No readable text or logo.",
        "In a long school hallway a rhinoceros statue clad in marbled red linoleum stands guard outside the principal's office. No readable text or logo.",
        "In a quiet clinic a row of waiting-room chairs surfaced in marbled blue linoleum hold one patient reading a magazine. No readable text or logo.",
      ],
    },
    'SP09-076': {
      dna: material(
        "Chain link: woven steel wire diamond mesh forming the target's surfaces.",
        'the target is formed from galvanized chain-link diamond mesh, keeping the woven pattern.',
        'Galvanized silver-grey.',
        'Backlight making the mesh graphic.',
        'Woven galvanized wire in diamond mesh.',
        'Urban, restrictive, industrial and hard.',
        'chain-link diamond mesh; galvanized wire; backlit pattern',
      ),
      avoid: AVOID,
      briefs: [
        "On a coastal hill a whale sculpture of galvanized chain-link mesh glows at sunset, the diamond weave outlined against the sky. No readable text or logo.",
        "In a misty field a life-size stag of chain-link mesh lets the sky show through its body, rust at the joints. No readable text or logo.",
        "In an abandoned factory a wedding dress woven from chain-link mesh stands on a mannequin, its long train dragging over the concrete. No readable text or logo.",
      ],
    },
    'SP09-077': {
      dna: material(
        "Barbed wire: twisted wire with barbs wound into the target's shape.",
        'the target is formed from coiled twisted barbed wire.',
        'Rusty grey and brown steel.',
        'Low hard light with thin shadows.',
        'Twisted steel wire with barbs and rust.',
        'Harsh, threatening, painful and stark.',
        'twisted barbed wire; barbs; rust',
      ),
      avoid: AVOID,
      briefs: [
        "Resting on a flat grey stone, a crown of coiled barbed wire catches cold light on its sharp barbs and rusted points. No readable text or logo.",
        "On a windy prairie hill at dusk a bison wound from rusted barbed wire forms heavy shoulders from twisted strands. No readable text or logo.",
        "In a graveyard at dusk an angel wound from barbed wire spreads looping wings as the last orange light catches the barbs. No readable text or logo.",
      ],
    },
    'SP09-078': {
      dna: material(
        'Solar panel: photovoltaic cells with blue-black grid lines and glass surface.',
        'the target is surfaced with solar cells in a grid under glass.',
        'Deep blue-black cells with silver busbars.',
        'Sunlight reflecting on the glass.',
        'Photovoltaic cells, busbars and glass.',
        'Technological, clean, efficient and modern.',
        'solar cell grid; silver busbars; blue-black glass',
      ),
      avoid: AVOID,
      briefs: [
        "Basking on a rock in full sun, a giant beetle's wing cases are photovoltaic panels, blue-black cells gleaming under glass. No readable text or logo.",
        "In a sunny meadow a caravan wagon's curved roof is surfaced with blue-black solar cells, a cat sleeping on the warm glass. No readable text or logo.",
        "An old stone chapel's steep roof is clad in photovoltaic panels, gravestones below reflected in the dark cells. No readable text or logo.",
      ],
    },
  },
};

export default spec;
