import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas classic RPG visual studies: the picture languages of 1980s-2000s role-playing
// games, as descriptors only (no game, studio or character names). Four originals get card briefs;
// sixteen new studies add first-person dungeon frames, overworld maps, side-view battles, airbrushed
// box art, dialogue portraits, painted backdrops, sprite towns, cutscene stills, cloth maps, vector
// adventure pictures, party lines, digitized actors, palette-cycling spells, one-bit adventures,
// arcade marquees and bestiary sprite plates.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'classic-rpg', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'interface text, health bars or menus', 'existing game characters or logos', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original characters';

const spec: Spec = {
  pack: 'pack_23',
  category: '6. Classic RPG Visual Studies',
  updates: {
    'SP23-026': { briefs: [
      'Opening the shutter of a cliffside beacon at dusk, a signal keeper sees the sea below rising into the shape of an enormous hand, built from purposeful pixel clusters and subdued color masses. No readable text or logo.',
      'In broad low-resolution color masses, an innkeeper tries to evict a slime that has paid for its room in advance and refuses to leave the bathtub. No readable text or logo.',
      'Drawn in short tonal ramps and hand-shaped hatching, a lone adventurer reaches the end of a long corridor and finds a door with her own name carved into it, the carving unreadable. No readable text or logo.',
    ] },
    'SP23-027': { briefs: [
      'Guiding three goats across a fallen log over a stream, a goatherd discovers the log is the back of a sleeping river beast, every scale and horn a compact consistent pixel cluster. No readable text or logo.',
      "Proudly showing off his newest blade, a blacksmith has made a sword so heavy that it has sunk halfway through the floor of his forge, all in tight consistent pixel clusters. No readable text or logo.",
      'In tight small pixel clusters, a sleeping village is seen at midnight, and one house has its door open with warm light and a shadow waiting inside. No readable text or logo.',
    ] },
    'SP23-028': { briefs: [
      'Painted in quantized gouache ramps, a crew of adventurers opens a treasure chest in a flooded crypt and finds a very small, very angry mermaid inside. No readable text or logo.',
      'In softly drawn stepped contours, a tavern cook stirs a stew while a skeleton at the counter holds out its bowl for the fourth time. No readable text or logo.',
      'Through short raster ramps of torchlight, a narrow dungeon stair descends into shadow, and the torch at the bottom is being held by something just out of view. No readable text or logo.',
    ] },
    'SP23-029': { briefs: [
      'On a rocky ridge, a tracker studies a hoofprint the size of a cart while a six-legged cliff-runner crests the rise behind her, rendered in compact digital-paint forms and selective patina. No readable text or logo.',
      'In controlled material texture, an armored adventurer sits in the mud after losing a fight with a chicken, which stands proudly on his helmet. No readable text or logo.',
      "At an abandoned campsite, a warm fire is still burning and a stew is bubbling, but every bedroll is empty, rendered in compact planar forms with restrained wear. No readable text or logo.",
    ] },
  },
  creates: [
    study('First-Person Dungeon Crawl Frame', 'grid dungeon first-person view', 'dungeon-crawl-view', {
      aesthetic: 'First-person dungeon crawl frame: a static first-person view down a stone grid corridor with symmetrical walls stepping back into darkness and a monster filling the center square.',
      subject_treatment: `${keep}; show the subject face-on in the center of a symmetrical stepped corridor view.`,
      color_and_tone: 'Limited palette of stone greys, torch orange and deep black.',
      lighting_and_shadow: 'Distance darkness in discrete steps, torchlit near walls.',
      texture_and_material: 'Pixelated brick walls, flat floor tiles and dithered darkness.',
      camera_and_composition: "Perfectly symmetrical one-point perspective corridor, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with claustrophobic step-by-step dread.',
      rendering_and_quality: "Crisp pixel walls with discrete depth steps, kept consistent across the whole image.",
      key_features: 'symmetrical corridor; stepped depth; center monster; torch light',
    }, [], [
      'At the end of a symmetrical stone corridor, a gelatinous cube fills the center square, and inside it floats the previous party\'s entire set of equipment. No readable text or logo.',
      'Straight ahead in a stepped grid corridor, a monster blocks the way, but it is only a very nervous goblin holding up a lost-and-found box. No readable text or logo.',
      'Down a stepped dark corridor, the next square is completely empty, but on the wall beside it a torch has just been blown out. No readable text or logo.',
    ]),
    study('Eight-Direction Overworld Map', 'top-down tile overworld', 'overworld-map', {
      aesthetic: 'Eight-direction overworld map: a top-down tile world of tiny forests, mountains, towns and rivers with a small hero sprite walking across a much larger land.',
      subject_treatment: `${keep}; show the subject as a tiny sprite or landmark on a top-down tile overworld.`,
      color_and_tone: 'Bright grass greens, ocean blues, sand and mountain browns.',
      lighting_and_shadow: "Flat lighting with small tile shadows, kept consistent across the whole image.",
      texture_and_material: 'Repeating tiles, pixel trees and tiny town icons.',
      camera_and_composition: 'Top-down view with the sprite small in a large map.',
      atmosphere_and_mood: 'Keep the requested mood with open adventurous freedom.',
      rendering_and_quality: "Clean readable tile map without interface, kept consistent across the whole image.",
      key_features: 'top-down tiles; tiny hero sprite; forests and towns; map scale',
    }, [], [
      'On a top-down tile map, a tiny hero sprite walks toward a mountain range, unaware that the mountains form the sleeping face of a giant as big as the continent. No readable text or logo.',
      'Across a pixel overworld, a tiny hero has been followed by forty chickens from the first village, lined up behind him in a long stubborn trail. No readable text or logo.',
      'On a small tile map, every town is lit except one at the edge of the sea, where the tiles around it have turned grey. No readable text or logo.',
    ]),
    study('Side-View Battle Tableau', 'side-view turn battle scene', 'side-battle', {
      aesthetic: 'Side-view battle tableau: a turn-based battle frozen mid-action, a row of small hero sprites on the right facing a huge painted enemy on the left across a backdrop.',
      subject_treatment: `${keep}; arrange the subject as small sprites facing a huge enemy across a battle backdrop.`,
      color_and_tone: 'Bright sprite colors against a painted dusky backdrop.',
      lighting_and_shadow: 'Flat sprites with spell flashes lighting the scene.',
      texture_and_material: 'Pixel sprites, painted enemy art and effect sparkles.',
      camera_and_composition: 'Heroes in a staggered row on the right, enemy on the left.',
      atmosphere_and_mood: 'Keep the requested mood with dramatic turn-based tension.',
      rendering_and_quality: 'Clear sprite readability with a large detailed enemy.',
      key_features: 'hero row; huge painted enemy; spell flash; battle backdrop',
    }, [], [
      'In a frozen turn-based moment, four small heroes face a giant moth queen whose wings fill the sky, a spell of ice halfway between them. No readable text or logo.',
      "Lined up for a turn-based fight, a mighty party of heroes faces its enemy across the field, and the enemy is one extremely small and very confident rabbit. No readable text or logo.",
      'In a dim battle backdrop, three heroes stand ready, and the enemy on the left is just an empty space where something is clearly still loading in. No readable text or logo.',
    ]),
    study('Airbrushed Game Box Epic', 'painted fantasy game box cover', 'box-art', {
      aesthetic: 'Airbrushed game box epic: eighties and nineties fantasy game box paintings with airbrushed skies, heroic figures in dynamic poses, glowing weapons and dramatic diagonal composition.',
      subject_treatment: `${keep}; pose the subject heroically in a dramatic diagonal fantasy painting.`,
      color_and_tone: 'Saturated sunset orange, violet sky and glowing weapon cyan.',
      lighting_and_shadow: "Strong rim light and airbrushed glow, kept consistent across the whole image.",
      texture_and_material: "Smooth airbrush gradients with crisp painted highlights, kept consistent across the whole image.",
      camera_and_composition: 'Low heroic angle with strong diagonal and space for a title at top.',
      atmosphere_and_mood: 'Keep the requested mood with bombastic fantasy grandeur.',
      rendering_and_quality: "Polished commercial painting, no logo or title, kept consistent across the whole image.",
      key_features: 'airbrushed sky; heroic diagonal; glowing weapon; rim light',
    }, ['title logo'], [
      'Leaping from a crumbling bridge with a glowing sword, a barbarian queen faces a skeletal serpent rising from lava under a violet airbrushed sky. No readable text or logo.',
      'In a heroic airbrushed pose on a mountain peak, a warrior raises his glowing weapon, which on closer look is a very bright frying pan. No readable text or logo.',
      "Standing on a cliff beneath a glowing storm, a robed sorceress raises her staff, and the lightning behind her is shaped exactly like a giant reaching hand. No readable text or logo.",
    ]),
    study('Dialogue Portrait Bust', 'character dialogue portrait', 'dialogue-portrait', {
      aesthetic: 'Dialogue portrait bust: a framed head-and-shoulders character portrait of the kind that appears beside dialogue in classic RPGs, expressive face, painterly pixel detail and a plain backdrop.',
      subject_treatment: `${keep}; show the subject as a head-and-shoulders portrait with one clear expression.`,
      color_and_tone: 'Rich skin and costume colors on a plain dark backdrop.',
      lighting_and_shadow: "Soft key light with pixel-level shading, kept consistent across the whole image.",
      texture_and_material: 'Careful pixel painting, hair clusters and cloth folds.',
      camera_and_composition: "Square framed bust facing slightly sideways, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with strong personal character.',
      rendering_and_quality: "Expressive detailed portrait with no dialogue box, kept consistent across the whole image.",
      key_features: 'framed bust; single expression; painterly pixels; plain backdrop',
    }, ['dialogue box text'], [
      'In a framed pixel portrait, a villainous court wizard smiles far too widely, and a tiny second face is visible in the pupil of his left eye. No readable text or logo.',
      'A framed portrait shows a shopkeeper goblin with an expression of absolute betrayal because the hero has tried to sell him his own item back. No readable text or logo.',
      'In a square pixel portrait, an old sailor stares out with wet eyes, a single silver tear catching the light as if he has just told the saddest story. No readable text or logo.',
    ]),
    study('Pre-Rendered Painted Backdrop', 'pre-rendered isometric backdrop', 'painted-backdrop', {
      aesthetic: 'Pre-rendered painted backdrop: late-nineties computer RPG backgrounds, richly detailed isometric-angle scenes pre-rendered and painted over, with small figures moving through them.',
      subject_treatment: `${keep}; place small figures inside a richly detailed angled pre-rendered environment.`,
      color_and_tone: 'Warm lamplit browns, deep greens and moody blues.',
      lighting_and_shadow: 'Baked warm lighting and soft shadows in every corner.',
      texture_and_material: "Painterly detailed textures, stone, wood and foliage, kept consistent across the whole image.",
      camera_and_composition: "Fixed elevated three-quarter angle with small figures, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with lived-in explorable depth.',
      rendering_and_quality: "Dense environmental detail with readable figures, kept consistent across the whole image.",
      key_features: 'elevated fixed angle; painted detail; baked light; small figures',
    }, [], [
      'From an elevated fixed angle, a small party explores a swamp temple where the huge carved stone face in the wall is slowly turning its eyes to follow them. No readable text or logo.',
      'In a richly detailed tavern backdrop, a tiny adventurer tries to have a quiet drink while every patron in the room is clearly a disguised monster. No readable text or logo.',
      'Seen from a fixed angle, a candlelit library is empty except for one chair that has been pulled out, and a book lies open on the floor. No readable text or logo.',
    ]),
    study('Sprite Town Bustle', 'pixel village crowd scene', 'sprite-town', {
      aesthetic: 'Sprite town bustle: a top-down or three-quarter pixel village crowded with townsfolk sprites, market stalls, animals and small daily dramas all happening at once.',
      subject_treatment: `${keep}; set the subject among many small busy townsfolk sprites in a pixel village.`,
      color_and_tone: "Warm village colors, cobbles, awnings and greenery, kept consistent across the whole image.",
      lighting_and_shadow: "Bright daylight with small sprite shadows, kept consistent across the whole image.",
      texture_and_material: 'Pixel cobbles, tile roofs, crates and signs without words.',
      camera_and_composition: "Three-quarter overhead view full of activity, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with lively everyday charm.',
      rendering_and_quality: "Busy but readable scene with clear sprites, kept consistent across the whole image.",
      key_features: 'townsfolk sprites; market stalls; small dramas; overhead view',
    }, ['readable shop signs'], [
      'In a bustling pixel market, a hero walks through town while a dragon in a disguise of one tiny hat is buying vegetables at a stall. No readable text or logo.',
      'Across a crowded sprite village, every single townsperson is chasing the same escaped pig, which is standing on the fountain looking pleased. No readable text or logo.',
      'In a busy pixel town, all the townsfolk have stopped walking and turned to face the same empty house at the end of the street. No readable text or logo.',
    ]),
    study('CD-Era Anime Cutscene Still', 'nineties cd game anime cutscene', 'cd-cutscene', {
      aesthetic: 'CD-era anime cutscene still: a frame from a nineties CD-ROM game animated cutscene, hand-painted cels, slightly compressed video softness and dramatic character close-ups.',
      subject_treatment: `${keep}; show the subject as a dramatic hand-painted anime cel frame.`,
      color_and_tone: 'Painted cel colors with a slightly washed video palette.',
      lighting_and_shadow: "Two-tone cel shadows and dramatic backlight, kept consistent across the whole image.",
      texture_and_material: 'Painted backgrounds, cel lines, mild video compression softness.',
      camera_and_composition: 'Cinematic close-up or wide shot with letterbox feeling.',
      atmosphere_and_mood: 'Keep the requested mood with melodramatic story weight.',
      rendering_and_quality: 'Authentic cel animation look with soft video grain.',
      key_features: 'painted anime cels; video softness; dramatic close-up; backlight',
    }, ['subtitles'], [
      'In a cinematic cel close-up, a young swordswoman turns as the airship explodes behind her, her hair lit by the blast in two-tone cel shading. No readable text or logo.',
      'In a painted cutscene frame, a stern knight delivers a heroic speech while a small dog in the background eats his lunch. No readable text or logo.',
      'In a soft video-grain cel frame, a girl stands alone on a train platform in the snow while the train leaves with her reflection still on board. No readable text or logo.',
    ]),
    study('Hand-Drawn Cloth Map Insert', 'printed cloth game map', 'cloth-map', {
      aesthetic: 'Hand-drawn cloth map insert: the printed cloth or paper maps packed inside old fantasy game boxes, pen-drawn mountains, forests and ruins in sepia on creased fabric.',
      subject_treatment: `${keep}; draw the subject as a pen-drawn landmark or figure on a creased cloth map.`,
      color_and_tone: 'Sepia and dark brown ink on beige cloth.',
      lighting_and_shadow: "Soft light on creases and folds, kept consistent across the whole image.",
      texture_and_material: 'Woven cloth, creases, pen hatching and fraying edges.',
      camera_and_composition: 'Top-down map filling the card with folds visible.',
      atmosphere_and_mood: "Keep the requested mood with nostalgic exploration, kept consistent across the whole image.",
      rendering_and_quality: "Clear cartographic drawing with believable cloth, kept consistent across the whole image.",
      key_features: 'creased cloth; sepia pen map; mountains and ruins; fraying edges',
    }, ['readable place names'], [
      'On a creased sepia cloth map, the pen-drawn sea monster in the corner has been circled many times by a previous player, with small tally marks beside it. No readable text or logo.',
      'On a frayed game map, the tiny drawn hero figure is standing at the exact spot where a coffee ring has made a brand-new lake. No readable text or logo.',
      'On an old folded cloth map, one area has been carefully cut out, leaving a hole the shape of a castle. No readable text or logo.',
    ]),
    study('Vector Line Adventure Picture', 'early vector-drawn adventure image', 'vector-adventure', {
      aesthetic: 'Vector line adventure picture: early home-computer adventure game pictures drawn with thin vector lines and simple flood fills, a few bright colors on black.',
      subject_treatment: `${keep}; draw the subject with thin straight vector lines and flat flood-fill color.`,
      color_and_tone: 'Black ground with a handful of bright flat colors.',
      lighting_and_shadow: "No lighting; flood fills only, kept consistent across the whole image.",
      texture_and_material: 'Thin jagged lines, flat fills and fill leaks.',
      camera_and_composition: 'Simple scene in a rectangular picture above empty space.',
      atmosphere_and_mood: 'Keep the requested mood with primitive imaginative charm.',
      rendering_and_quality: "Crude charming vector drawing with visible steps, kept consistent across the whole image.",
      key_features: 'thin vector lines; flood fills; black ground; few colors',
    }, ['text parser prompt'], [
      'Drawn in thin vector lines and flat magenta and cyan fills, a troll guards a bridge while the fill color of the river has leaked into his beard. No readable text or logo.',
      'In a crude vector adventure picture, a wizard has turned a prince into a frog but the frog has been drawn slightly larger than the prince was. No readable text or logo.',
      "Alone on a black screen, a dark cave entrance drawn in thin straight lines waits in silence, and two small white dots inside it have just appeared. No readable text or logo.",
    ]),
    study('Party Conga Sprite Line', 'rpg party following in a line', 'party-line', {
      aesthetic: 'Party conga sprite line: a row of small RPG party sprites following each other in single file through a landscape, each step identical, like a tiny parade.',
      subject_treatment: `${keep}; line the subject up as a single-file party of small sprites.`,
      color_and_tone: "Bright sprite colors on a soft landscape, kept consistent across the whole image.",
      lighting_and_shadow: "Flat light with small oval sprite shadows, kept consistent across the whole image.",
      texture_and_material: "Pixel sprites, tile grass and path stones, kept consistent across the whole image.",
      camera_and_composition: 'Top-down or three-quarter path with sprites in a line.',
      atmosphere_and_mood: "Keep the requested mood with cozy companionship, kept consistent across the whole image.",
      rendering_and_quality: "Clean consistent sprites with identical steps, kept consistent across the whole image.",
      key_features: 'single-file sprites; identical steps; path; small shadows',
    }, [], [
      'Walking single file through a forest path, a party of four heroes is followed by a fifth sprite no one recruited, a small ghost copying every step. No readable text or logo.',
      'In a perfect single-file line, a hero party marches across the map with a cow, a knight, a mage and a chicken all taking identical steps. No readable text or logo.',
      'Along a narrow snowy path, a line of party sprites walks toward a cave, and the last sprite in line has stopped and turned to look back. No readable text or logo.',
    ]),
    study('Digitized Actor Sprite', 'photo-digitized game sprite', 'digitized-actor', {
      aesthetic: 'Digitized actor sprite: early-nineties game sprites made from photographed costumed actors, low-resolution photo pixels with harsh cutout edges and limited colors.',
      subject_treatment: `${keep}; show the subject as a digitized costumed photo cut out into a low-res sprite.`,
      color_and_tone: "Photographic colors reduced to a limited palette, kept consistent across the whole image.",
      lighting_and_shadow: 'Flat studio lighting from the original photo shoot.',
      texture_and_material: 'Photo pixels, jagged cutout edges and costume fabric.',
      camera_and_composition: "Full-body figure on a painted fantasy backdrop, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with earnest low-budget spectacle.',
      rendering_and_quality: "Authentic low-res digitized look with jagged edges, kept consistent across the whole image.",
      key_features: 'photographed actor; jagged cutout; limited palette; painted backdrop',
    }, [], [
      'On a painted temple backdrop, a digitized actor in a rubber monster suit roars with great commitment while the zipper on his back is clearly visible. No readable text or logo.',
      'In jagged photo pixels, a digitized warrior strikes a heroic pose with a cardboard sword that is bending slightly at the tip. No readable text or logo.',
      'On a dark painted backdrop, a digitized actress in a pale gown stands perfectly still, her photographed eyes following the player. No readable text or logo.',
    ]),
    study('Palette-Cycling Spell Glow', 'animated palette cycling effect', 'palette-cycling', {
      aesthetic: 'Palette-cycling spell glow: old pixel effects where color bands rotate through a palette to make water, fire and magic shimmer, captured as bands of cycling color.',
      subject_treatment: `${keep}; wrap the subject in shimmering bands of cycling palette color.`,
      color_and_tone: 'Rotating color bands from deep blue to cyan to white.',
      lighting_and_shadow: "Glow implied through bright band steps, kept consistent across the whole image.",
      texture_and_material: 'Pixel bands, stepped gradients and still background art.',
      camera_and_composition: 'Central glowing effect over a still pixel scene.',
      atmosphere_and_mood: 'Keep the requested mood with hypnotic magical shimmer.',
      rendering_and_quality: "Precise stepped bands with clean pixels, kept consistent across the whole image.",
      key_features: 'cycling color bands; stepped glow; still pixel scene; shimmer',
    }, [], [
      'In a pixel throne room, a sorcerer\'s spell of cycling color bands swirls toward a knight, rippling from indigo to cyan to white in stepped rings. No readable text or logo.',
      'Around a pixel fountain, the water shimmers in cycling bands of color, and a very small frog in the middle is enjoying the light show. No readable text or logo.',
      'Deep in a still pixel cave, a waterfall of cycling colors pours from nowhere, and the bands on one side are flowing upward. No readable text or logo.',
    ]),
    study('One-Bit Desktop Adventure', 'monochrome early computer game art', 'one-bit-adventure', {
      aesthetic: 'One-bit desktop adventure: early black-and-white desktop computer games with crisp one-bit pixels, fine patterned fills and elegant tiny drawings in a window.',
      subject_treatment: `${keep}; draw the subject in pure black and white pixels with patterned fills.`,
      color_and_tone: "Pure black and white only, kept consistent across the whole image.",
      lighting_and_shadow: "Pattern fills stand in for shadow, kept consistent across the whole image.",
      texture_and_material: 'Checker, dot and line pattern fills and crisp pixels.',
      camera_and_composition: "Small framed scene with clean negative space, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with quiet crafted mystery.',
      rendering_and_quality: "Crisp one-bit clarity with neat patterns, kept consistent across the whole image.",
      key_features: 'one-bit pixels; pattern fills; black and white; framed scene',
    }, ['window chrome text', 'gray tones'], [
      'In crisp one-bit pixels, a knight stands before a castle gate filled with a checker pattern, and the pattern is starting to form the shape of a face. No readable text or logo.',
      'Drawn in black and white patterned fills, a small mouse detective inspects a giant cheese that has been perfectly cut into a keyhole shape. No readable text or logo.',
      'In a one-bit scene, a lighthouse on a dotted sea shines a white beam, and at the far end of the beam there is a black shape in the water. No readable text or logo.',
    ]),
    study('Arcade Cabinet Fantasy Marquee', 'backlit arcade side art', 'arcade-marquee', {
      aesthetic: 'Arcade cabinet fantasy marquee: backlit arcade header and side art with bold ink outlines, saturated flat color, airbrushed flames and heroic fantasy figures glowing through plastic.',
      subject_treatment: `${keep}; render the subject as bold outlined cabinet art glowing from behind.`,
      color_and_tone: 'Hot red, yellow and blue flats with black outlines.',
      lighting_and_shadow: "Backlit glow through translucent plastic, kept consistent across the whole image.",
      texture_and_material: 'Screen-printed plastic, bold ink, airbrush flames and scratches.',
      camera_and_composition: "Wide horizontal marquee or tall side panel, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with loud coin-op excitement.',
      rendering_and_quality: "Punchy commercial art with no logo, kept consistent across the whole image.",
      key_features: 'backlit plastic; bold outlines; airbrush flames; saturated flats',
    }, ['game title logo'], [
      'Glowing on a backlit arcade marquee, a warrior and a dwarf leap toward a flaming skull the size of a mountain, bold black outlines over hot red and yellow. No readable text or logo.',
      'On scratched cabinet side art, a heroic barbarian flexes beside a treasure chest that is quietly sprouting legs and teeth. No readable text or logo.',
      'On a dim backlit marquee in an empty arcade, the painted villain\'s eyes are the only part of the art still lit. No readable text or logo.',
    ]),
    study('Bestiary Sprite Plate', 'monster compendium sprite sheet art', 'bestiary-sprites', {
      aesthetic: 'Bestiary sprite plate: a neat compendium of monster sprites arranged in rows like a collector\'s plate, each creature on its own tile with a tiny shadow.',
      subject_treatment: `${keep}; present the subject as one of many monster sprites arranged in neat rows.`,
      color_and_tone: 'Varied bright creature colors on a dark or parchment ground.',
      lighting_and_shadow: "Consistent top-left light and small shadows, kept consistent across the whole image.",
      texture_and_material: 'Clean pixel sprites, tile borders and small shadows.',
      camera_and_composition: "Grid of creatures with one featured larger, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with the delight of a completed collection.',
      rendering_and_quality: "Consistent sprite style across the plate, kept consistent across the whole image.",
      key_features: 'monster grid; consistent sprites; tile borders; featured creature',
    }, ['readable monster names or numbers'], [
      'In a neat grid of monster sprites, one tile is larger than the others and holds a mimic that has disguised itself as the tile border. No readable text or logo.',
      "Among rows of fierce monster sprites, every creature snarls at the viewer except the last one, a slime with tiny glasses quietly reading a book. No readable text or logo.",
      'In a compendium grid of creatures, one tile is completely black, and a single pair of pixel eyes has appeared in it. No readable text or logo.',
    ]),
  ],
};

export default spec;
