import type { Create, Spec } from '../tools/apply';
import { WARDROBE_AVOID, wear } from './_wardrobe';

// Historical costume: the preset supplies period garments with specific provenance. The era of the
// surroundings changes only when the prompt asks for it.
const AVOID = [...WARDROBE_AVOID, 'costume-shop synthetic fabric', 'mixed-up period details'];
const H = (period: string) =>
  `the ${period} garment system below, with period-accurate cut, closures, layering and accessories; the surrounding setting stays as the prompt describes`;

const spec: Spec = {
  pack: 'pack_08',
  category: '3. Historical & Fantasy',
  updates: {
    'SP08-011': {
      dna: wear(
        '1950s domestic-pop fashion: fitted bodices, full circle skirts over petticoats, cardigans, pearls, gloves and neat set hair, or boxy suits with fedoras.',
        `${H('1950s')} — fitted-waist dress with full skirt and petticoat, twinset cardigan and pearls, gloves and kitten heels, or a boxy suit with skinny tie and fedora.`,
        'Technicolor pastels — mint, cherry, butter yellow, powder blue — with crisp white.',
        'Bright, even, cheerful light like a vintage advertisement.',
        'Cotton poplin, taffeta petticoats, wool twinsets, pearls and patent leather.',
        'Posed full figure with the skirt silhouette visible.',
        'Optimistic, polished, wholesome and slightly uncanny.',
        'Saturated, glossy vintage print finish.',
        'full circle skirt and petticoat; twinset and pearls; gloves; technicolor pastels; advertising polish',
      ),
      avoid: AVOID,
      briefs: [
        'Technicolor photograph of an adult woman witch in a mint 1950s full-skirted dress with petticoat, pearls and white gloves, smiling as she pours a bubbling green potion in a pastel kitchen. No text or logo.',
        'Technicolor photograph of an adult man knight in a boxy 1950s grey suit, skinny tie and fedora, holding his helmet at a suburban barbecue. No text or logo.',
        'Technicolor photograph of an elderly adult woman in a cherry-red 1950s dress and twinset feeding a small dragon in a picket-fenced garden. No text or logo.',
      ],
    },
    'SP08-012': {
      dna: wear(
        'Sixteenth-century Renaissance court regalia: stiffened bodices, slashed and puffed sleeves, brocade, ruffs or square necklines and jeweled girdles.',
        `${H('16th-century European court')} — stiff brocade bodice or doublet, slashed puffed sleeves showing contrasting lining, ruff or square neckline, jeweled girdle and hose or full skirts.`,
        'Crimson, gold, deep green, ivory and black velvet.',
        'Soft window light like a court portrait.',
        'Silk brocade, velvet, lace ruffs, pearls and gold embroidery.',
        'Formal portrait framing, three-quarter or full figure.',
        'Regal, rich, formal and self-assured.',
        'Painterly-rich photographic finish.',
        'slashed puffed sleeves; stiff brocade bodice or doublet; ruff; jeweled girdle; court portrait light',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in 16th-century court regalia — crimson brocade bodice, slashed puffed sleeves, lace ruff and jeweled girdle — holding a leashed snow leopard in a stone gallery. No text or logo.',
        'Photograph of an adult man in a black velvet slashed doublet with gold embroidery and a small ruff playing chess against a skeleton. Window light. No text or logo.',
        'Photograph of an elderly adult queen in green brocade and pearls seated on a carved throne in a ruined hall overgrown with ivy. No text or logo.',
      ],
    },
    'SP08-031': {
      dna: wear(
        '1920s flapper eveningwear: dropped-waist beaded dresses, fringe, long pearls, cloche or headband and T-strap heels; men in slick tuxedos.',
        `${H('1920s jazz-age')} — dropped-waist beaded or fringed shift, long pearl ropes, feathered headband or cloche, T-strap heels, or a slim tuxedo with slicked hair.`,
        'Champagne gold, black, silver and deep emerald.',
        'Warm speakeasy lamplight with sparkle.',
        'Glass beading, silk fringe, feathers, pearls and satin.',
        'Dancing or leaning full figure with motion in the fringe.',
        'Decadent, rebellious, glittering and jazzy.',
        'Warm, sparkling vintage finish.',
        'dropped-waist beaded shift; swinging fringe; long pearls; feathered headband; speakeasy glow',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman ghost in a champagne-gold beaded flapper dress, feathered headband and long pearls dancing the Charleston in a candlelit abandoned ballroom. No text or logo.',
        'Photograph of an adult man vampire in a slim 1920s tuxedo with slicked hair lighting a cigarette in a speakeasy cellar. No text or logo.',
        'Photograph of an elderly adult woman in a black fringed flapper dress and cloche at a roulette table run by goblins. No text or logo.',
      ],
    },
    'SP08-032': {
      dna: wear(
        'Victorian mourning dress: head-to-toe black crape, high collars, bustles, veils and jet jewelry — grief made into strict ceremony.',
        `${H('Victorian mourning')} — high-collared black bodice, bustled skirt, long veil or crape bonnet, black gloves and faceted jet jewelry; men in black frock coats with armbands.`,
        'Matte and glossy blacks only, with jet and pale skin.',
        'Cold grey window light or candlelight.',
        'Silk crape, bombazine, lace veils, jet beads and black kid leather.',
        'Formal, still, full-figure framing.',
        'Solemn, ritual, grief-stricken and severe.',
        'Deep black, detailed, somber finish.',
        'high-collared black crape; bustle and veil; jet jewelry; matte blacks; still solemnity',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in full Victorian mourning — high-collared black crape, bustle, long veil and jet jewelry — standing beside a coffin holding a sleeping dragon egg. Cold window light. No text or logo.',
        'Photograph of an elderly adult man in a black frock coat and mourning armband feeding crows in a foggy churchyard. No text or logo.',
        'Photograph of three adult sisters in matching Victorian mourning veils seated for a portrait with a ghostly fourth chair. No text or logo.',
      ],
    },
    'SP08-033': {
      dna: wear(
        'Ancient Egyptian regalia: pleated white linen, broad beaded collars, gold armbands, kohl-lined eyes and ceremonial wigs or headdresses.',
        `${H('ancient Egyptian')} — finely pleated white linen kalasiris or shendyt, broad beaded usekh collar, gold arm and wrist cuffs, kohl eyeliner and a braided wig or headdress.`,
        'White linen, gold, lapis blue, carnelian red and turquoise.',
        'Strong desert sun with hard shadows.',
        'Pleated linen, faience beads, hammered gold and lapis.',
        'Frontal, hieratic full figure framing.',
        'Divine, ceremonial, poised and timeless.',
        'Sharp, sunlit, high-detail finish.',
        'pleated white linen; broad beaded usekh collar; gold cuffs; kohl eyes; hieratic pose',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in ancient Egyptian regalia — pleated white linen, broad lapis-and-gold usekh collar, gold cuffs and kohl eyes — standing in a modern subway station. Hard light. No text or logo.',
        'Photograph of an adult man in a pleated shendyt, beaded collar and braided wig steering a reed boat through papyrus. No text or logo.',
        'Photograph of an elderly adult woman in Egyptian linen and turquoise jewelry feeding a sacred ibis. No text or logo.',
      ],
    },
    'SP08-034': {
      dna: wear(
        'Roman ceremonial regalia: draped togas with colored borders, stolas and pallas, laurel wreaths, fibulae and military cuirasses with red cloaks.',
        `${H('Roman ceremonial')} — draped wool toga or stola with palla, purple or red border stripes, bronze fibula, laurel wreath, or a muscled cuirass with a red paludamentum cloak.`,
        'Undyed wool white, imperial purple, crimson and bronze.',
        'Bright Mediterranean daylight with marble bounce.',
        'Heavy wool drapery, bronze, leather straps and gilded laurel.',
        'Statuesque full figure with drapery clearly readable.',
        'Imperial, dignified, commanding and austere.',
        'Crisp, classical finish.',
        'draped toga or stola; purple border; laurel wreath; bronze fibula; statuesque drapery',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman senator in a draped white stola and palla with a purple border and laurel wreath addressing a crowd of goblins in a marble forum. No text or logo.',
        'Photograph of an adult man general in a bronze muscled cuirass and red cloak standing on a snowy Alpine pass. No text or logo.',
        'Photograph of an elderly adult man in a heavy wool toga reading scrolls in a modern glass library. No readable text or logo.',
      ],
    },
    'SP08-035': {
      dna: wear(
        'Ceremonial samurai armor: lacquered lamellar plates laced with silk cords, flared shoulder guards, a crested kabuto helmet and a menpō face mask.',
        `${H('Japanese ceremonial armor')} — lacquered lamellar ō-yoroi or dō-maru plates laced with colored silk, flared sode shoulder guards, crested kabuto and menpō mask, over hakama.`,
        'Black and vermilion lacquer, indigo or crimson lacing and gold crest.',
        'Soft overcast or low torchlight glinting on lacquer.',
        'Lacquered plates, silk lacing, iron, leather and gilded crests.',
        'Imposing full figure or three-quarter framing.',
        'Stoic, fearsome, disciplined and ceremonial.',
        'Rich, detailed lacquer finish.',
        'lacquered lamellar plates; silk lacing; crested kabuto; menpō mask; stoic presence',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in black-and-vermilion ceremonial samurai armor with crimson silk lacing and a crested kabuto kneeling in a field of red spider lilies at dusk. No text or logo.',
        'Photograph of an elderly adult man in indigo-laced lamellar armor and menpō mask fishing from a wooden pier in fog. No text or logo.',
        'Photograph of an adult samurai in gold-crested armor standing guard at a neon-lit night market. No readable text or logo.',
      ],
    },
    'SP08-036': {
      dna: wear(
        'Norse seafaring dress: layered wool tunics and apron dresses with oval brooches, fur-trimmed cloaks, woven bands and leg wraps.',
        `${H('Viking-age Norse')} — wool tunic or apron dress held with oval tortoise brooches and bead strings, tablet-woven bands, fur-trimmed cloak with ring pin, leg wraps and turnshoes.`,
        'Madder red, woad blue, undyed wool grey, bronze and fur brown.',
        'Cold, grey northern light.',
        'Coarse wool, fur, tablet-woven bands, bronze brooches and glass beads.',
        'Weathered full figure in cold outdoor framing.',
        'Hardy, proud, seafaring and wind-beaten.',
        'Textured, cold-toned finish.',
        'apron dress with oval brooches; fur-trimmed cloak; tablet-woven bands; leg wraps; cold northern light',
      ),
      avoid: [...AVOID, 'horned helmets'],
      briefs: [
        'Photograph of an adult woman in a madder-red Norse apron dress with oval bronze brooches, bead strings and a fur-trimmed cloak standing at a ship prow in a storm. No text or logo.',
        'Photograph of an elderly adult man in a woad-blue wool tunic, leg wraps and ring-pinned cloak carving runes-free wood by a longhouse fire. No text or logo.',
        'Photograph of two adult sisters in Norse dress hauling nets on a black pebble beach. Cold grey light. No text or logo.',
      ],
    },
    'SP08-037': {
      dna: wear(
        'Frontier workwear: nineteenth-century American frontier clothing — canvas trousers, suspenders, flannel shirts, calico dresses, dusters and worn boots.',
        `${H('19th-century frontier')} — canvas or wool trousers with suspenders, collarless flannel shirt, vest, long duster or calico dress with bonnet, and worn leather boots and hat.`,
        'Dust brown, faded indigo, rust, bone and weathered black.',
        'Harsh prairie sun or low dusty sunset.',
        'Duck canvas, wool, calico, cracked leather and brass buttons.',
        'Wide full figure in open land.',
        'Weathered, stubborn, lonely and hardworking.',
        'Dusty, film-like finish.',
        'canvas trousers and suspenders; long duster; calico and bonnet; worn leather boots; dusty light',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in a faded calico dress, bonnet and long duster walking beside a huge armored beetle pulling her wagon across the prairie. Dusty sunset. No text or logo.',
        'Photograph of an elderly adult man in suspenders, collarless flannel and a battered hat forging horseshoes outside a sod house. No text or logo.',
        'Photograph of an adult man in a canvas duster and vest standing in a futuristic desert city at dawn. No text or logo.',
      ],
    },
    'SP08-038': {
      dna: wear(
        '1970s disco fashion: slinky jersey wrap dresses, halter jumpsuits, sequined tops, wide-lapel shirts and flared trousers made to catch the mirror ball.',
        `${H('1970s disco')} — halter jumpsuit or jersey wrap dress, sequined or lamé top, wide-lapel open shirt, high-waisted flares and platform shoes, big hair.`,
        'Metallic gold, silver, hot pink, electric blue and white.',
        'Mirror-ball sparkle, colored spotlights and haze.',
        'Lamé, sequins, silk jersey, satin and patent platforms.',
        'Dancing full figure with dynamic pose.',
        'Glamorous, euphoric, sensual and flashy.',
        'Glossy, sparkling finish.',
        'halter jumpsuit and flares; sequins and lamé; wide lapels; platforms; mirror-ball sparkle',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman dragon-tamer in a gold lamé halter jumpsuit and platforms dancing under a mirror ball in a torchlit cavern, a small dragon spinning beside her. No text or logo.',
        'Photograph of an adult man knight in a wide-lapel satin shirt and electric-blue flares under his breastplate striking a disco pose. No text or logo.',
        'Photograph of an elderly adult woman in a silver sequined wrap dress with big hair roller-skating in a castle hall. No text or logo.',
      ],
    },
    'SP08-039': {
      dna: wear(
        'Late eighteenth-century French court: rococo excess and revolutionary change — panniered silk gowns, powdered wigs, embroidered coats, or tricolor sashes and simple sans-culottes.',
        `${H('late 18th-century French')} — panniered silk robe à la française with lace engageantes and powdered pouf, embroidered justaucorps coat and breeches, or revolutionary striped trousers, carmagnole jacket and cockade.`,
        'Pastel silks, powder white, gold embroidery, or tricolor blue, white and red.',
        'Soft candlelight or chandelier glow.',
        'Silk taffeta, embroidery, lace, powdered hair and brass buttons.',
        'Full figure with the silhouette of panniers or coat clearly visible.',
        'Decadent, fragile, dramatic and on the edge of upheaval.',
        'Rich, detailed, painterly photographic finish.',
        'panniered silk gown; powdered pouf; embroidered coat and breeches; lace engageantes; chandelier glow',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in a powder-pink panniered silk gown and towering powdered pouf with a tiny ship in it, standing in a flooded palace ballroom. No text or logo.',
        'Photograph of an adult man in an embroidered gold justaucorps and breeches dueling a skeleton by candlelight. No text or logo.',
        'Photograph of an adult woman in revolutionary striped trousers, carmagnole jacket and cockade raising a lantern on a barricade of furniture. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Byzantine Court',
      domain: 'Byzantine imperial dress',
      tags: ['byzantine', 'court-dress', 'fashion'],
      dna: wear(
        'Byzantine court dress: stiff, jewel-encrusted silk dalmatics and loros sashes, pearl pendilia crowns and gold-embroidered cloaks.',
        `${H('Byzantine imperial')} — long silk dalmatic, jeweled loros sash wrapped over the body, chlamys cloak with a gold tablion panel, and a crown with hanging pearl pendilia.`,
        'Imperial purple, gold, deep red, emerald and pearl.',
        'Warm mosaic-gold glow with soft shadows.',
        'Heavy silk samite, gold thread, pearls, cabochon gems and enamel.',
        'Frontal, iconic full figure.',
        'Sacred, imperial, rigid and resplendent.',
        'Rich, glowing, detailed finish.',
        'jeweled loros sash; silk dalmatic; pearl pendilia crown; gold tablion; frontal icon pose',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult empress in Byzantine court dress — purple silk dalmatic, jeweled loros and pearl-hung crown — standing frontally before a collapsed mosaic wall. No text or logo.',
        'Photograph of an adult man in a gold-embroidered Byzantine chlamys riding a white horse through snow. No text or logo.',
        'Photograph of an elderly adult woman in emerald Byzantine silk and pearls reading at a desert monastery window. No text or logo.',
      ],
    },
    {
      name: 'Heian Court Layers',
      domain: 'Heian court layered robes',
      tags: ['heian', 'court-dress', 'fashion'],
      dna: wear(
        'Heian court dress: many layered unlined silk robes whose sleeve edges show graded seasonal color combinations, with very long loose hair.',
        `${H('Heian Japanese court')} — a jūnihitoe of many layered silk robes with visible graded color edges at sleeves and collar, a trailing mo, a hiōgi fan and floor-length loose hair; men in sokutai with tall kanmuri.`,
        'Seasonal color gradations such as plum-blossom pinks, autumn maple reds or iris purples and greens.',
        'Soft, diffused screen-filtered light.',
        'Figured silk, gauze, lacquered fan and long straight hair.',
        'Seated or kneeling figure with layers spread around.',
        'Refined, poetic, contemplative and aristocratic.',
        'Delicate, soft, luminous finish.',
        'many layered silk robes; graded color edges; floor-length loose hair; hiōgi fan; kneeling spread',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in Heian court layers in autumn maple colors, floor-length hair spread around her, kneeling on a moss garden while a fox spirit watches. Soft light. No text or logo.',
        'Photograph of an adult man in a black sokutai and tall kanmuri playing a flute on a wooden veranda in rain. No text or logo.',
        'Photograph of an elderly adult woman in plum-blossom layered silks holding a fan inside a modern concrete gallery. No text or logo.',
      ],
    },
    {
      name: 'Regency Empire Line',
      domain: 'Regency era dress',
      tags: ['regency', 'empire-waist', 'fashion'],
      dna: wear(
        'Regency dress: high-waisted empire-line muslin gowns, spencer jackets, bonnets and long gloves; men in tailcoats, cravats, waistcoats and tall boots.',
        `${H('Regency')} — high-waisted white or pastel muslin gown with short puffed sleeves, spencer jacket, bonnet and long gloves, or a tailcoat, high-collared shirt with cravat, waistcoat and Hessian boots.`,
        'White muslin, pale pastels, bottle green and navy wool.',
        'Soft English daylight through tall windows.',
        'Sheer muslin, wool broadcloth, silk ribbon and polished leather.',
        'Graceful full-figure framing.',
        'Genteel, romantic, restrained and witty.',
        'Soft, fresh, detailed finish.',
        'empire-waist muslin gown; spencer and bonnet; tailcoat and cravat; Hessian boots; soft window light',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in a white Regency empire-line gown, spencer jacket and bonnet walking a griffin on a lead through a formal garden. Soft daylight. No text or logo.',
        'Photograph of an adult man in a bottle-green tailcoat, cravat and Hessian boots rowing across a misty lake at dawn. No text or logo.',
        'Photograph of two elderly adult sisters in pastel Regency gowns playing cards with a ghost. No text or logo.',
      ],
    },
    {
      name: 'Ottoman Court Kaftan',
      domain: 'Ottoman court dress',
      tags: ['ottoman', 'kaftan', 'fashion'],
      dna: wear(
        'Ottoman court dress: layered silk and velvet kaftans with large tulip, carnation and çintemani patterns, sashes, and tall headdresses or turbans.',
        `${H('16th–17th-century Ottoman court')} — layered long kaftans of patterned silk or velvet with long hanging sleeves, a wide sash, şalvar trousers, and a turban or tall headdress.`,
        'Crimson, gold, turquoise, deep green and ivory.',
        'Warm lamplight or bright courtyard light.',
        'Silk lampas, velvet, gold brocade and embroidered çintemani and tulip motifs.',
        'Stately full figure showing the layered kaftans.',
        'Majestic, ornate, dignified and worldly.',
        'Rich, patterned, detailed finish.',
        'layered patterned kaftans; tulip and çintemani motifs; hanging sleeves; wide sash; turban',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in a layered crimson-and-gold Ottoman kaftan with tulip patterns and a tall headdress feeding peacocks in a tiled courtyard. No text or logo.',
        'Photograph of an adult man in a turquoise velvet kaftan with hanging sleeves and a turban reading star charts on a rooftop. No readable text or logo.',
        'Photograph of an elderly adult man in an ivory çintemani kaftan riding a camel through a snowstorm. No text or logo.',
      ],
    },
    {
      name: 'Medieval Peasant Workwear',
      domain: 'medieval working dress',
      tags: ['medieval', 'peasant', 'fashion'],
      dna: wear(
        'Medieval working dress: homespun wool tunics and kirtles, linen coifs and hoods, belted aprons, patched hose and turnshoes — clothes made to last.',
        `${H('medieval European working')} — undyed or plant-dyed wool tunic or kirtle, linen coif or hood with liripipe, belted apron, patched hose and simple leather turnshoes.`,
        'Undyed wool, madder rust, weld yellow, woad blue and earth brown.',
        'Soft overcast or smoky hearth light.',
        'Coarse wool, linen, patched seams, leather and wooden toggles.',
        'Honest working full figure.',
        'Humble, hardworking, earthy and resilient.',
        'Textured, natural finish.',
        'homespun wool tunic or kirtle; linen coif; hood with liripipe; patched hose; plant-dyed palette',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in a woad-blue wool kirtle, linen coif and belted apron wrestling a runaway pig through a flooded village lane. No text or logo.',
        'Photograph of an elderly adult man in a hooded tunic with a long liripipe and patched hose working at a modern espresso machine. No text or logo.',
        'Photograph of an adult man in a madder-rust tunic scything wheat under a sky with two moons. No text or logo.',
      ],
    },
    {
      name: '1940s Wartime Utility',
      domain: '1940s utility clothing',
      tags: ['forties', 'utility', 'fashion'],
      dna: wear(
        '1940s wartime utility clothing: austere tailored suits with padded shoulders, knee-length A-line skirts, headscarves, overalls, and make-do-and-mend details.',
        `${H('1940s wartime')} — padded-shoulder utility suit or shirtwaist dress, knee-length skirt, headscarf or victory rolls, practical shoes, or work overalls and a knitted pullover.`,
        'Muted khaki, navy, brick red, bottle green and cream.',
        'Hard, clean daylight or factory light.',
        'Wool gabardine, rayon, cotton drill and hand-knitted wool.',
        'Determined full figure.',
        'Resolute, practical, thrifty and brave.',
        'Crisp, slightly faded vintage finish.',
        'padded-shoulder utility suit; headscarf and victory rolls; work overalls; make-do-and-mend; muted palette',
      ),
      avoid: [...AVOID, 'military insignia'],
      briefs: [
        "Photograph of an adult woman in 1940s work overalls, a red headscarf and victory rolls riveting a giant dragon's iron armor in a hangar. No text or logo.",
        'Photograph of an adult woman in a navy padded-shoulder utility suit waiting on a platform for a steam train as fog rolls in. No text or logo.',
        'Photograph of an elderly adult man in a knitted pullover and patched trousers tending a rooftop victory garden. No text or logo.',
      ],
    },
    {
      name: 'Belle Époque',
      domain: 'Belle Époque fashion',
      tags: ['belle-epoque', 'edwardian', 'fashion'],
      dna: wear(
        'Belle Époque fashion: S-bend corseted silhouettes, lace high collars, trumpet skirts, enormous plumed hats and parasols; men in frock coats and top hats.',
        `${H('c. 1900 Belle Époque')} — S-bend lace blouse and trumpet skirt or tea gown, huge feathered hat, parasol and gloves, or a frock coat, waistcoat and top hat with cane.`,
        'Ivory lace, dove grey, lavender, champagne and black.',
        'Soft, hazy summer daylight.',
        'Lace, silk chiffon, ostrich plumes, tulle and kid leather.',
        'Elegant full figure with the S-bend silhouette visible.',
        'Elegant, leisurely, romantic and refined.',
        'Soft, luminous, vintage finish.',
        'S-bend silhouette; lace high collar; enormous plumed hat; parasol; hazy summer light',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in an ivory lace Belle Époque gown and enormous plumed hat with a parasol, strolling a promenade beside a sea monster in the bay. Hazy light. No text or logo.',
        'Photograph of an adult man in a frock coat and top hat holding a birdcage with a tiny dragon at a railway café. No text or logo.',
        'Photograph of an elderly adult woman in a lavender tea gown on a bicycle in a lavender field. No text or logo.',
      ],
    },
    {
      name: 'Tang Dynasty Hanfu',
      domain: 'Tang dynasty dress',
      tags: ['tang', 'hanfu', 'fashion'],
      dna: wear(
        'Tang dynasty dress: high-waisted flowing skirts tied above the chest, short jackets with wide sleeves, long pibo shawls and elaborate high hairstyles with ornaments.',
        `${H('Tang Chinese')} — high-waisted ruqun skirt tied above the chest, short wide-sleeved top, long gauze pibo shawl, and a high chignon with gold hairpins; men in round-collar robes and futou caps.`,
        'Pomegranate red, peony pink, emerald, gold and apricot.',
        'Warm, glowing court light.',
        'Silk gauze, damask, gold hairpins and painted flower motifs.',
        'Flowing full figure with shawl in motion.',
        'Opulent, graceful, lively and cosmopolitan.',
        'Luminous, colorful finish.',
        'high-waisted ruqun skirt; long gauze pibo shawl; wide sleeves; high chignon with gold pins; opulent color',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult woman in Tang dynasty hanfu — pomegranate-red high-waisted skirt, gauze pibo shawl flying and gold hairpins — dancing on a bridge over a misty gorge. No text or logo.',
        'Photograph of an adult man in a round-collar Tang robe and futou cap playing polo on horseback. No text or logo.',
        'Photograph of an elderly adult woman in peony-pink Tang silks feeding koi in a snowy garden. No text or logo.',
      ],
    },
    {
      name: 'Mughal Court Jama',
      domain: 'Mughal court dress',
      tags: ['mughal', 'jama', 'fashion'],
      dna: wear(
        'Mughal court dress: flared jama robes tied at the side, patka sashes, fitted pyjamas, jeweled turbans and fine muslin veils with gold borders.',
        `${H('Mughal court')} — flared knee-length jama tied at the side, embroidered patka sash, fitted churidar trousers, jeweled turban with sarpech and pearls, or peshwaz and fine muslin odhni.`,
        'Saffron, pale muslin white, emerald, gold and ruby.',
        'Soft, golden palace light through jali screens.',
        'Fine muslin, zari gold thread, pearls, emeralds and embroidered silk.',
        'Elegant three-quarter or full figure.',
        'Refined, regal, poetic and sumptuous.',
        'Luminous, finely detailed finish.',
        'flared jama; embroidered patka sash; jeweled turban with sarpech; fine gold-bordered muslin; jali light',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an adult man in a saffron Mughal jama, patka sash and jeweled turban with sarpech releasing a falcon from a marble balcony. Jali light. No text or logo.',
        'Photograph of an adult woman in a peshwaz and gold-bordered muslin odhni playing a veena beside a moonlit pool. No text or logo.',
        'Photograph of an elderly adult man in white muslin jama and pearls riding an elephant through a rain-soaked bazaar. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
