import type { Spec } from '../tools/apply';
import { dna } from './_strict';
import { au } from './_authors';

// Anime style spectrum, author pass: each preset names its original creator and describes the
// concrete marks of that style (line, faces, color, staging) so the result reads as that author.
// Briefs stay original; reference-guard avoid rules keep characters, logos and scenes out.
const spec: Spec = {
  pack: 'pack_13',
  category: '5. Anime Style Spectrum',
  updates: {
    'SP05-339': {
      name: 'Naoki Urasawa - Adult Suspense Microgesture',
      dna: dna({
        aesthetic:
          'Naoki Urasawa manga style, as in his long psychological suspense series: grounded realist seinen drawing where ordinary adult faces carry individual wrinkles, heavy eyelids, imperfect noses and ears, and suspense lives in one silent held reaction.',
        subject_treatment:
          'Preserve the requested identity, count, pose, action and any requested clothing; draw people with realistic adult proportions, small eyes, individualized features, believable hair and everyday clothing folds, never generic big-eyed anime faces. Wardrobe details apply only when the prompt leaves clothing open.',
        color_and_tone:
          'Black-and-white manga page: black ink, grey screentone and paper white, with at most one pale wash of color on a single object.',
        lighting_and_shadow:
          'Flat naturalistic light shaped by screentone gradients and solid black shadow shapes that grow heavier as the tension rises.',
        texture_and_material:
          'Clean confident G-pen contour with slight weight variation, sparse economical hatching, dot screentone, white paper showing through; drawn line art, not painting or photo.',
        camera_and_composition:
          'Cinematic manga panel staging: tight close-ups on a face reacting in silence, steady mid shots in ordinary streets, offices and apartment hallways.',
        atmosphere_and_mood:
          'Keep the requested mood with quiet creeping dread under everyday human warmth.',
        rendering_and_quality:
          'Precise realist manga illustration, every face distinct and every gesture observed from life, no glossy digital polish.',
        key_features:
          'Naoki Urasawa realism; individualized adult faces; held silent reaction; screentone and hatching; ordinary settings',
      }),
      briefs: [
        'Two spies smile at each other across a restaurant table, and only one finger tightening on a wine glass betrays who already knows. No readable text or logo.',
        "At the reading of her husband's will, a composed widow lets the corner of her mouth twitch for exactly one instant. No readable text or logo.",
        "A poker player's calm face is flawless except for a single bead of sweat halfway down his temple. No readable text or logo.",
      ],
    },
    ...Object.fromEntries([
      au('SP05-321', 'Yoshitaka Amano - Ether-Wisp Gothic Ornament', {
        look: 'Yoshitaka Amano illustration look: ethereal wispy ink lines, elongated pale figures dissolving into ornamental swirls, gothic decadence and watercolor washes of gold and violet.',
        subject:
          'draw people with Amano elegance, elongated pale faces, flowing wispy hair and ornate gothic garments that dissolve into line.',
        color: 'Pale watercolor washes of gold, violet, rose and ink black on ivory paper.',
        light: 'Ethereal glowing light suggested by blank paper.',
        texture: 'Wispy fine ink line, watercolor bleed and ornamental swirls.',
        camera: 'Tall vertical ornamental compositions.',
        mood: 'ethereal gothic decadence',
        render: 'Ethereal ink-and-watercolor illustration.',
        key: 'Yoshitaka Amano wisps; elongated figures; gothic ornament; watercolor',
      }),
      au('SP05-322', 'CLAMP - Celestial Vertical Ornament', {
        look: 'CLAMP manga look as in X and Tsubasa: extremely elongated elegant figures, flowing robes and hair, celestial ornament, feathers and dramatic vertical page layouts.',
        subject:
          'draw people with CLAMP proportions, very long limbs, narrow faces, flowing robes and hair falling in long vertical lines.',
        color: 'Black ink with delicate tone, and pale gold and silver in color art.',
        light: 'Celestial glow and soft starlight.',
        texture: 'Fine elegant ink line, feathers and ornament.',
        camera: 'Tall vertical compositions spanning the page.',
        mood: 'celestial elegant destiny',
        render: 'Elegant ornamental manga illustration.',
        key: 'CLAMP elongation; celestial ornament; feathers; vertical layout',
      }),
      au('SP05-323', 'Naoko Takeuchi - Prism-Glamour Transformation Polish', {
        look: 'Naoko Takeuchi manga art: fashion-illustration magical girls with very long legs, watercolor color pages, jewels, crescent moons, prism light and glamorous transformation.',
        subject:
          'draw people with Takeuchi designs, very long legs, slender bodies, big jeweled eyes and glamorous fashion-inspired costumes.',
        color: 'Watercolor pastel pinks, lavender, silver and prism rainbows.',
        light: 'Prism light and sparkling jewel glints.',
        texture: 'Watercolor washes and fine fashion-illustration line.',
        camera: 'Fashion-plate full-body compositions.',
        mood: 'glamorous prism transformation',
        render: 'Glamorous watercolor manga illustration.',
        key: 'Naoko Takeuchi fashion; long legs; watercolor; prism glamour',
        avoid: ['blonde twin buns with a crescent moon tiara', 'existing franchise characters'],
      }),
      au('SP05-324', 'Rumiko Takahashi - Elastic Rom-Com Slapstick Timing', {
        look: 'Rumiko Takahashi manga look as in Ranma 1/2: round clean faces, elastic slapstick bodies, martial-arts comedy, quick panel timing and cheerful romantic chaos.',
        subject:
          'draw people with Takahashi designs, round faces, big simple eyes and springy energetic bodies.',
        color: 'Black ink with light tone, and bright flat color in color pages.',
        light: 'Flat bright comic light.',
        texture: 'Clean round brush-pen line and light tone.',
        camera: 'Quick comic panels and slapstick action.',
        mood: 'bouncy romantic slapstick',
        render: 'Clean lively comedy manga illustration.',
        key: 'Rumiko Takahashi roundness; slapstick; rom-com; martial comedy',
        avoid: [
          'a pigtailed martial artist in a red Chinese shirt',
          'existing franchise characters',
        ],
      }),
      au('SP05-325', 'Taiyo Matsumoto - Scratchy Concrete-Poetry Drift', {
        look: 'Taiyo Matsumoto manga look as in Tekkonkinkreet and Sunny: wobbly scratchy pen lines, distorted perspective, lopsided figures and poetic urban melancholy.',
        subject:
          'draw people with Matsumoto designs, lopsided heads, lanky limbs and scruffy clothes.',
        color: 'Black ink with scratchy tone and faded watercolor.',
        light: 'Hazy poetic city light.',
        texture: 'Scratchy wobbly pen lines and hatching.',
        camera: 'Distorted fisheye urban compositions.',
        mood: 'poetic urban melancholy',
        render: 'Idiosyncratic scratchy manga illustration.',
        key: 'Taiyo Matsumoto wobbly line; distorted perspective; urban poetry',
      }),
      au('SP05-326', 'Masaaki Yuasa - Rubber Reality Sprint', {
        look: 'Masaaki Yuasa animation look: rubbery elastic bodies, reality bending with emotion, flat bold colors and exhilarating long sprints.',
        subject: 'draw people with Yuasa elasticity, stretchy limbs and simplified faces.',
        color: 'Flat bold colors and sudden psychedelic shifts.',
        light: 'Flat graphic light.',
        texture: 'Loose lines and flat color.',
        camera: 'Warping sprint compositions.',
        mood: 'exhilarating rubbery freedom',
        render: 'Elastic expressive animation frame.',
        key: 'Masaaki Yuasa elasticity; warping reality; sprints',
      }),
      au('SP05-327', 'Osamu Dezaki - Postcard Memory Freeze', {
        look: 'Osamu Dezaki direction look as in Ashita no Joe 2 and Aim for the Ace: painted pastel postcard freeze frames, triple-take zooms, split screens and harmonica-light melancholy.',
        subject:
          'draw people with seventies-eighties realistic designs, strong faces and sporting clothes.',
        color: 'Pastel chalk postcard colors over dramatic darks.',
        light: 'Dramatic backlight and hazy glow.',
        texture: 'Painted pastel-chalk freeze frames over cel.',
        camera: 'Triple-take zooms and split screens.',
        mood: 'melancholy frozen memory',
        render: 'Painterly postcard freeze-frame illustration.',
        key: 'Dezaki postcard freeze; triple takes; split screens',
      }),
      au('SP05-328', 'Leiji Matsumoto - Retrofuture Distance Melancholy', {
        look: 'Leiji Matsumoto manga look: gaunt romantic figures, tall elegant women with long lashes, stubby comic men, mechanical gauges and melancholy starry retrofuture.',
        subject:
          'draw people with Leiji contrast, tall elegant long-lashed figures and short stubby men in coats.',
        color: 'Black ink with starry tone and deep blue in color.',
        light: 'Starlight and gauge glow.',
        texture: 'Dense mechanical gauges and fine ink.',
        camera: 'Lonely distant compositions.',
        mood: 'lonely retrofuture melancholy',
        render: 'Romantic retrofuture manga illustration.',
        key: 'Leiji Matsumoto gauges; tall elegant women; stubby men; stars',
      }),
      au('SP05-329', 'Kazuo Umezz - Spiral Panic Engraving', {
        look: 'Kazuo Umezz horror manga look: wide screaming faces with hands on cheeks, dense engraving-like hatching, spiraling dread and sixties-seventies horror energy.',
        subject:
          'draw people with Umezz designs, huge terrified eyes, screaming mouths and hands pressed to faces.',
        color: 'Black ink with dense hatching.',
        light: 'Harsh horror shadows.',
        texture: 'Engraving-like hatching and spiral lines.',
        camera: 'Screaming close-ups and spiraling layouts.',
        mood: 'screaming spiral panic',
        render: 'Classic horror manga illustration.',
        key: 'Kazuo Umezz screams; hatching; spiral dread',
      }),
      au('SP05-330', 'Shigeru Mizuki - Folkloric Deadpan Ink Catalog', {
        look: 'Shigeru Mizuki yokai manga look: cartoony simple characters against extremely detailed stippled realistic backgrounds, catalog-like yokai portraits and deadpan folklore.',
        subject: 'draw people cartoony and simple, and spirits as odd deadpan yokai.',
        color: 'Black ink with dense stipple and hatching.',
        light: 'Dim eerie light via stippling.',
        texture: 'Dense stippled backgrounds and simple cartoon figures.',
        camera: 'Catalog-like portraits and detailed scenes.',
        mood: 'deadpan folkloric eeriness',
        render: 'Classic yokai manga illustration.',
        key: 'Shigeru Mizuki stipple; cartoon figures; yokai catalog',
      }),
      au('SP05-331', 'Yusuke Murata - Chrome Impact Hero Frame', {
        look: 'Yusuke Murata manga art as in One-Punch Man: hyper-detailed dynamic action, chrome reflections, impossible perspective and virtuoso destruction.',
        subject: 'draw people with Murata detail, athletic heroes and hyper-detailed armor.',
        color: 'Black ink with chrome tones and cyan-magenta glints in color.',
        light: 'Chrome glints and impact flashes.',
        texture: 'Hyper-detailed ink and debris.',
        camera: 'Impossible dynamic perspective.',
        mood: 'virtuoso heroic impact',
        render: 'Virtuoso action manga illustration.',
        key: 'Yusuke Murata detail; chrome; dynamic perspective; destruction',
      }),
      au('SP05-332', 'Kunihiko Ikuhara - Ritual Allegory Icon System', {
        look: 'Kunihiko Ikuhara direction look as in Mawaru Penguindrum and Yurikuma: flat pictogram icons, repeated symbolic stock shots, theatrical allegory and bold graphic signage.',
        subject: 'draw people with stylized elegant designs and pictogram-like symbolic figures.',
        color: 'Bold flat pink, red, black and white.',
        light: 'Theatrical flat lighting.',
        texture: 'Flat graphic pictograms and clean cel.',
        camera: 'Symmetrical symbolic compositions.',
        mood: 'ritual allegorical theater',
        render: 'Graphic allegorical animation frame.',
        key: 'Ikuhara pictograms; allegory; symbolic repetition',
      }),
      au('SP05-333', 'Hiroyuki Okiura - Quiet Human Naturalism', {
        look: 'Hiroyuki Okiura animation look as in A Letter to Momo: meticulous realistic acting, accurate anatomy, quiet everyday gestures and warm natural light.',
        subject: 'draw people with Okiura realism, accurate anatomy and natural gestures.',
        color: 'Warm natural everyday tones.',
        light: 'Soft natural morning light.',
        texture: 'Precise realistic cel.',
        camera: 'Quiet observational compositions.',
        mood: 'quiet human warmth',
        render: 'Meticulous naturalist animation frame.',
        key: 'Okiura naturalism; precise acting; everyday gestures',
      }),
      au('SP05-334', 'Hideaki Anno - Emergency Storyboard Tension', {
        look: 'Hideaki Anno storyboard and layout look: rough graphite storyboards, bureaucratic emergency staging, telephoto compositions and tense quick cutting.',
        subject: 'draw people as rough graphite figures in tense emergency scenes.',
        color: 'Graphite grey and warning orange.',
        light: 'Harsh emergency light.',
        texture: 'Rough graphite storyboard lines.',
        camera: 'Telephoto staging and quick cuts.',
        mood: 'tense emergency urgency',
        render: 'Rough storyboard illustration.',
        key: 'Anno storyboards; graphite; emergency staging',
      }),
      au('SP05-335', 'Haruko Ichikawa - Mineral Void Serenity', {
        look: 'Haruko Ichikawa manga look as in Land of the Lustrous: delicate sparse lines, vast white voids, translucent mineral bodies and serene minimal compositions.',
        subject: 'draw figures as translucent mineral beings with delicate sparse lines.',
        color: 'Pale mineral tints and vast white.',
        light: 'Bright white void light.',
        texture: 'Delicate sparse ink line.',
        camera: 'Minimal compositions with vast empty space.',
        mood: 'serene mineral solitude',
        render: 'Minimal delicate manga illustration.',
        key: 'Haruko Ichikawa voids; mineral bodies; sparse line',
      }),
      au('SP05-336', 'Takeshi Koike - Razorline Velocity Poster', {
        look: 'Takeshi Koike illustration look as in his Lupin films: razor-thin sharp lines, huge black shadow shapes, long angular figures and cool poster compositions.',
        subject: 'draw people with Koike stylization, long angular bodies and hard black shadows.',
        color: 'Saturated flat color with massive blacks.',
        light: 'Hard graphic light with black shadow shapes.',
        texture: 'Razor-thin line and flat color.',
        camera: 'Cool poster-like compositions.',
        mood: 'cool razor velocity',
        render: 'Stylish graphic poster illustration.',
        key: 'Takeshi Koike razor line; black shadows; poster cool',
      }),
      au('SP05-337', 'Yoh Yoshinari - Technomagic Draftsmanship Burst', {
        look: 'Yoh Yoshinari animation look as in Little Witch Academia: bouncy elastic magic, firework effects, blueprint-like technical magic and bright joyful draftsmanship.',
        subject: 'draw people with Yoshinari designs, bouncy shapes and expressive faces.',
        color: 'Bright magic colors and blueprint cyan.',
        light: 'Firework magic light.',
        texture: 'Clean energetic line and effects.',
        camera: 'Dynamic magic bursts.',
        mood: 'joyful technomagic energy',
        render: 'Energetic Trigger-style animation frame.',
        key: 'Yoh Yoshinari magic; fireworks; blueprint arcs',
      }),
      au('SP05-338', 'Atsushi Ohkubo - Angular Combustion Iconography', {
        look: 'Atsushi Ohkubo manga look as in Fire Force: angular graphic designs, triangle grins, bold ember effects and stylish street-level combustion.',
        subject:
          'draw people with Ohkubo designs, triangular grins, angular bodies and stylish uniforms.',
        color: 'Ember orange, soot black and white.',
        light: 'Flame light and ember glow.',
        texture: 'Bold angular ink and ember effects.',
        camera: 'Angular dynamic compositions.',
        mood: 'blazing angular bravado',
        render: 'Bold graphic action manga illustration.',
        key: 'Ohkubo angular grins; embers; combustion',
      }),
      au('SP05-340', 'Akio Sugino - Velvet Lash Refined Tension', {
        look: 'Akio Sugino animation design look as in Rose of Versailles and Cat’s Eye: elegant long-lashed faces, refined eighties glamour and tense restrained drama.',
        subject:
          'draw people with Sugino elegance, long lashes, refined faces and elegant clothes.',
        color: 'Velvet red, candle gold and deep shadow.',
        light: 'Candlelight and soft glamour glow.',
        texture: 'Refined hand-drawn cel line.',
        camera: 'Elegant dramatic close-ups.',
        mood: 'refined tense elegance',
        render: 'Elegant eighties animation frame.',
        key: 'Akio Sugino lashes; refined glamour; tension',
      }),
      au('SP05-341', 'Hiromu Arakawa - Mechanical Warmth Ensemble', {
        look: 'Hiromu Arakawa manga look as in Fullmetal Alchemist and Silver Spoon: sturdy warm characters, clear expressive faces, detailed mechanical limbs and ensemble camaraderie.',
        subject:
          'draw people with Arakawa designs, sturdy bodies, expressive faces and practical clothes.',
        color: 'Black ink with warm tones in color pages.',
        light: 'Warm campfire and daylight.',
        texture: 'Clean confident ink line and mechanical detail.',
        camera: 'Ensemble compositions.',
        mood: 'warm mechanical camaraderie',
        render: 'Warm clear manga illustration.',
        key: 'Hiromu Arakawa warmth; mechanical limbs; ensemble',
      }),
      au('SP05-342', 'Satoshi Kon - Reality-Slip Reflection Continuity', {
        look: 'Satoshi Kon manga and film look: grounded realistic adults, mirrors and reflections, seamless match-cuts where reality slips into illusion.',
        subject: 'draw people with Kon realism, grounded adult faces and ordinary clothes.',
        color: 'Muted realistic tones with uncanny accents.',
        light: 'Ordinary light with uncanny reflections.',
        texture: 'Precise realist line.',
        camera: 'Mirror compositions and match-cut continuity.',
        mood: 'uncanny reality slip',
        render: 'Precise uncanny realist illustration.',
        key: 'Satoshi Kon mirrors; reality slips; match cuts',
      }),
      au('SP05-101', 'Koji Yamamura - Abstract Fluid Painterly Anime', {
        look: 'Koji Yamamura independent animation look as in Mt. Head: hand-drawn fluid pencil and watercolor, abstract flowing forms and painterly metamorphosis.',
        subject:
          'draw figures with fluid hand-drawn lines that melt into abstract painterly forms.',
        color: 'Watercolor blues, sepia and soft washes.',
        light: 'Soft painterly light.',
        texture: 'Pencil and watercolor texture.',
        camera: 'Flowing metamorphic compositions.',
        mood: 'fluid dreamy metamorphosis',
        render: 'Painterly independent animation frame.',
        key: 'Koji Yamamura fluidity; watercolor; metamorphosis',
      }),
      au('SP05-102', 'Minoru Furuya - Gritty Realist Seinen', {
        look: 'Minoru Furuya manga look as in Himizu: gritty realism, awkward ordinary faces, grimy settings and bleak dark humor.',
        subject: 'draw people with Furuya realism, awkward faces and worn clothes.',
        color: 'Black ink with grimy tone.',
        light: 'Dim gritty light.',
        texture: 'Gritty realistic line and tone.',
        camera: 'Bleak realistic compositions.',
        mood: 'gritty bleak realism',
        render: 'Gritty realist seinen illustration.',
        key: 'Minoru Furuya grit; awkward faces; bleak humor',
      }),
      au('SP05-103', 'Mika Pikazo - Neon Hyperpop Anime', {
        look: 'Mika Pikazo illustration look: hyper-saturated neon pop, rainbow gradients, graphic stickers, bold character designs and explosive color.',
        subject:
          'draw people with Pikazo designs, bold hair colors, graphic outfits and energetic poses.',
        color: 'Hyper-saturated rainbow neon.',
        light: 'Neon glow and RGB splits.',
        texture: 'Glossy digital paint and graphic shapes.',
        camera: 'Energetic poster compositions.',
        mood: 'explosive neon pop',
        render: 'Hyper-saturated digital illustration.',
        key: 'Mika Pikazo neon; rainbow gradients; hyperpop',
      }),
      au('SP05-104', 'Seiichi Hayashi - Minimalist Indie Quiet', {
        look: 'Seiichi Hayashi manga look as in Red Colored Elegy: minimalist alternative gekiga, sparse lines, large empty spaces and quiet poetic emotion.',
        subject: 'draw people with sparse minimal lines and simple forms.',
        color: 'Sparse black ink and a single red accent.',
        light: 'Quiet flat light.',
        texture: 'Sparse minimal brush line.',
        camera: 'Minimal compositions with much empty space.',
        mood: 'quiet poetic minimalism',
        render: 'Minimal alternative manga illustration.',
        key: 'Seiichi Hayashi minimalism; empty space; poetry',
      }),
      au('SP05-105', 'Takashi Nakamura - Textured Hand-Drawn Rough', {
        look: 'Takashi Nakamura animation look as in A Tree of Palme: textured rough hand-drawn lines, visible pencil energy and whimsical organic fantasy.',
        subject: 'draw people with Nakamura designs and rough textured lines.',
        color: 'Earthy muted fantasy tones.',
        light: 'Soft warm workshop light.',
        texture: 'Rough visible pencil texture.',
        camera: 'Whimsical cluttered compositions.',
        mood: 'whimsical handmade warmth',
        render: 'Rough textured hand-drawn frame.',
        key: 'Takashi Nakamura rough texture; pencil energy; whimsy',
      }),
      au('SP05-106', 'The Big O Sunrise - Deco-Inspired Geometric Anime', {
        look: 'Sunrise The Big O look (1999) by Keiichi Sato: art deco retro city, geometric architecture, noir gentlemen and giant retro robots.',
        subject: 'draw people with Sato designs, noir suits and elegant retro dresses.',
        color: 'Deco gold, black and muted sepia.',
        light: 'Noir city light.',
        texture: 'Analog cel with geometric deco architecture.',
        camera: 'Geometric noir compositions.',
        mood: 'noir art deco elegance',
        render: 'Retro deco television frame.',
        key: 'The Big O art deco; geometric city; noir',
      }),
      au('SP05-107', 'Gou Tanabe - Visceral Guro Horror', {
        look: 'Gou Tanabe manga look as in his Lovecraft adaptations: dense organic crosshatching, cosmic horror, grotesque bodies and heavy black atmosphere.',
        subject: 'draw people with Tanabe realism, dense hatching and grotesque organic forms.',
        color: 'Black ink with dense hatching.',
        light: 'Candle and eldritch glow.',
        texture: 'Dense organic crosshatching.',
        camera: 'Oppressive horror compositions.',
        mood: 'visceral cosmic horror',
        render: 'Dense cosmic horror manga illustration.',
        key: 'Gou Tanabe hatching; cosmic horror; grotesque',
      }),
      au('SP05-108', 'Kazuo Oga - Fairy-Tale Storybook Soft', {
        look: 'Kazuo Oga background painting look as in Totoro: lush soft gouache forests, dappled light, gentle storybook atmosphere and painterly nature.',
        subject: 'draw figures small and simple within lush painted nature.',
        color: 'Lush gouache greens and soft warm light.',
        light: 'Dappled forest light.',
        texture: 'Painterly gouache brushwork.',
        camera: 'Lush storybook landscapes.',
        mood: 'soft storybook wonder',
        render: 'Painterly gouache background illustration.',
        key: 'Kazuo Oga gouache; lush forests; storybook',
      }),
      au('SP05-109', 'Masashi Kishimoto - Kinetic Impact-Line Choreography', {
        look: 'Masashi Kishimoto manga look: dynamic ninja action choreography, radial impact lines, afterimages and sharp detailed panels.',
        subject: 'draw people with Kishimoto designs, sharp eyes and dynamic action poses.',
        color: 'Black ink with dynamic tone.',
        light: 'Impact flashes.',
        texture: 'Sharp ink and radial lines.',
        camera: 'Dynamic action choreography.',
        mood: 'kinetic martial energy',
        render: 'Dynamic action manga illustration.',
        key: 'Kishimoto choreography; impact lines; afterimages',
        avoid: [
          'an orange jumpsuit ninja with whisker marks',
          'a leaf headband emblem',
          'existing franchise characters',
        ],
      }),
      au('SP05-110', 'Keiichi Tanaami - Surreal Dream Logic', {
        look: 'Keiichi Tanaami psychedelic pop art look: surreal collage, vivid flat colors, repeating motifs, dream logic and pop explosions.',
        subject: 'draw figures as flat pop shapes within surreal collage worlds.',
        color: 'Vivid psychedelic pop colors.',
        light: 'Flat pop light.',
        texture: 'Flat collage shapes.',
        camera: 'Surreal collage compositions.',
        mood: 'surreal dream logic',
        render: 'Psychedelic pop illustration.',
        key: 'Tanaami psychedelia; collage; dream logic',
      }),
      au('SP05-111', 'Miss Hokusai Production I.G - Ukiyo-e Woodblock Anime', {
        look: 'Production I.G Miss Hokusai look (2015) by Keiichi Hara: Edo woodblock world, graded indigo skies, painters’ studios and ukiyo-e staging.',
        subject: 'draw people with Edo-period designs and kimono in ukiyo-e staging.',
        color: 'Graded indigo, vermilion and paper beige.',
        light: 'Graded woodblock sky light.',
        texture: 'Woodblock-inspired flat color and line.',
        camera: 'Ukiyo-e compositions.',
        mood: 'Edo artistic wonder',
        render: 'Woodblock-inspired feature frame.',
        key: 'Miss Hokusai Edo; woodblock gradients; ukiyo-e',
      }),
      au('SP05-112', 'Dead Leaves Imaishi - Spray-Drip Wildstyle Anime', {
        look: 'Hiroyuki Imaishi Dead Leaves look (2004): punk graffiti energy, spray drips, crude wild shapes and hyperactive color.',
        subject: 'draw people with crude punk designs and wild poses.',
        color: 'Hyperactive spray colors.',
        light: 'Flat punk light.',
        texture: 'Spray drips and crude lines.',
        camera: 'Chaotic graffiti compositions.',
        mood: 'wild punk chaos',
        render: 'Crude punk graffiti animation frame.',
        key: 'Dead Leaves punk; spray drips; wildstyle',
      }),
      au('SP05-113', 'Madoka Magica SHAFT - Leaded Jewel-Light Segmentation', {
        look: 'SHAFT Puella Magi Madoka Magica look (2011): stained-glass segmentation, cute Ume Aoki designs, jewel light and ominous symbolism.',
        subject:
          'draw people with Ume Aoki designs, big round eyes and costumes segmented like stained glass.',
        color: 'Jewel pink, violet, gold and dark glass lead lines.',
        light: 'Stained-glass jewel light.',
        texture: 'Leaded stained-glass segmentation.',
        camera: 'Symmetrical stained-glass compositions.',
        mood: 'ominous jeweled beauty',
        render: 'Stained-glass animation frame.',
        key: 'Madoka stained glass; jewel light; symbolism',
        avoid: [
          'a pink-haired magical girl with twin bows',
          'a white cat-like creature with red eyes',
          'existing franchise characters',
        ],
      }),
      au('SP05-114', 'Gankutsuou Gonzo - Threadbare Textile Patchwork', {
        look: 'Gonzo Gankutsuou look (2004) by Mahiro Maeda: characters filled with static textile patterns, ornate fabric textures and baroque sci-fi opulence.',
        subject:
          'draw people with Maeda designs whose clothes and hair are filled with flat static textile patterns.',
        color: 'Ornate jewel textile colors.',
        light: 'Opulent theatrical light.',
        texture: 'Static textile patterns inside shapes.',
        camera: 'Baroque opulent compositions.',
        mood: 'opulent patterned intrigue',
        render: 'Patterned textile animation frame.',
        key: 'Gankutsuou textiles; static patterns; baroque',
      }),
      au('SP05-115', 'Studio Orange CG - Ice-Crystal Refractive', {
        look: 'Studio Orange cel-shaded CG crystal rendering as in its gemstone work: translucent refractive surfaces, prismatic splits and crisp faceted light.',
        subject: 'draw people as cel-shaded CG figures with crystalline refractive details.',
        color: 'Icy prismatic blues and white.',
        light: 'Prismatic refractive light.',
        texture: 'Faceted translucent CG surfaces.',
        camera: 'Crisp faceted compositions.',
        mood: 'crystalline icy clarity',
        render: 'Crystalline cel-shaded CG frame.',
        key: 'Studio Orange crystal; refraction; faceted light',
      }),
      au('SP05-116', 'Sawaki Takeyasu - Sumi-e Impact Brushstroke', {
        look: 'Sawaki Takeyasu sumi-e illustration look as in Okami: bold ink brushstrokes, celestial brush art, ukiyo-e inspired forms and sweeping impact strokes.',
        subject: 'draw people with bold brush strokes and ukiyo-e inspired forms.',
        color: 'Ink black, paper white and red accents.',
        light: 'Paper-white glow.',
        texture: 'Bold sumi-e brush and paper grain.',
        camera: 'Sweeping brush compositions.',
        mood: 'bold brush impact',
        render: 'Sumi-e brush illustration.',
        key: 'Sawaki Takeyasu sumi-e; brush strokes; ukiyo-e',
        avoid: ['a white wolf with red markings', 'existing franchise characters'],
      }),
      au('SP05-117', 'Patlabor 2 Oshii - Phosphor Sensor-Vision Grain', {
        look: 'Mamoru Oshii Patlabor 2 film look (1993): sensor screens, night-vision green, military surveillance and cold tactical stillness.',
        subject: 'draw people with realistic sober designs and military gear.',
        color: 'Phosphor green monochrome.',
        light: 'Night-vision glow.',
        texture: 'Sensor grain and scanlines.',
        camera: 'Surveillance sensor compositions.',
        mood: 'cold tactical stillness',
        render: 'Grainy sensor-view film frame.',
        key: 'Patlabor 2 sensors; night vision; surveillance',
      }),
      au('SP05-118', 'Hiroshi Nagai - Backlit Contour Longing', {
        look: 'Hiroshi Nagai city pop illustration look: flat clean color, glowing sunsets, pools and palm trees, crisp backlit contours and nostalgic longing.',
        subject: 'draw people as small clean flat figures with glowing backlit contours.',
        color: 'Sunset orange, pool blue and palm green.',
        light: 'Strong backlit sunset glow.',
        texture: 'Flat clean acrylic color.',
        camera: 'Clean wide city pop compositions.',
        mood: 'nostalgic backlit longing',
        render: 'Clean city pop illustration.',
        key: 'Hiroshi Nagai city pop; backlit sunsets; flat color',
      }),
      au('SP05-119', 'Yusei Matsui - Chalk-Dust Slate Sketch', {
        look: 'Yusei Matsui manga look as in Assassination Classroom: chalkboard classrooms, simple round comedic faces and sketchy chalk gags.',
        subject: 'draw people with Matsui designs, simple faces and classroom clothes.',
        color: 'Slate green and chalk white.',
        light: 'Classroom light.',
        texture: 'Chalk-dust strokes on slate.',
        camera: 'Classroom compositions.',
        mood: 'playful chalky comedy',
        render: 'Chalk-sketch comedy illustration.',
        key: 'Yusei Matsui chalkboards; round faces; chalk gags',
        avoid: ['a yellow octopus teacher with a graduation cap', 'existing franchise characters'],
      }),
      au('SP05-120', 'Ghost in the Shell SAC_2045 - Thermal-Heat-Signature Vision', {
        look: 'Production I.G and Sola Ghost in the Shell SAC_2045 look (2020): cel-shaded CG, tactical thermal views, heat signatures and cold cyber operations.',
        subject: 'draw figures as cel-shaded CG operatives seen through thermal vision.',
        color: 'Thermal white, red, amber and cold blue.',
        light: 'Heat-signature glow.',
        texture: 'Cel-shaded CG with thermal gradients.',
        camera: 'Tactical thermal compositions.',
        mood: 'cold tactical scan',
        render: 'Cel-shaded thermal CG frame.',
        key: 'SAC_2045 thermal; heat signatures; tactical',
        avoid: ['a purple-haired cyborg major', 'existing franchise characters'],
      }),
    ]),
  },
};

export default spec;
