import type { Create, Dna, Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Weathering is a surface treatment with an explicit intensity. The target keeps its structure;
// collapse, ruins or abandonment scenes are not added unless the prompt asks for them.
const AVOID = [...MATERIAL_AVOID, 'structural collapse', 'unrequested ruins or abandonment scene'];
const w = (a: string, b: string, c: string, l: string, t: string, m: string, k: string): Dna =>
  material(
    a,
    `${b} Default intensity is moderate; follow the prompt if it asks for light or heavy wear.`,
    c,
    l,
    t,
    m,
    `${k}; surface-level damage; structure intact`,
    'surfaces of the target named in the prompt',
  );

const spec: Spec = {
  pack: 'pack_09',
  category: '3. Weathering And Decay',
  updates: {
    'SP09-018': {
      dna: w(
        'Rusty iron: iron or steel surfaces oxidized into orange-brown rust with flaking scale and streaks.',
        'rust blooms from edges, bolts and seams, with flaking scale and run-off streaks.',
        'Orange, umber and dark brown rust over grey steel.',
        'Low warm light that shows flaking relief.',
        'Oxide scale, pitting, flakes and streaks.',
        'Neglected, industrial, harsh and timeworn.',
        'orange rust blooms; flaking scale; run-off streaks; pitting',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's full armor rusted orange-brown with flaking scale and streaks, still standing proud on a stand. No text or logo.",
        'Photograph of a rusted iron dragon sculpture rising from a field of red poppies, orange-brown rust with flaking scale along the wings, dark streaks running down from every rivet onto the grass. No text or logo.',
        'Photograph of a rusty iron birdcage hanging in a sunny kitchen window with a live yellow canary inside, flaking orange scale on the bars and rust streaks on the white sill below. No text or logo.',
      ],
    },
    'SP09-025': {
      dna: w(
        'Cracked porcelain: glazed ceramic surfaces crazed with hairline cracks and a few chips.',
        'fine crazing across the glaze with a few deeper cracks and chipped edges, the object still whole.',
        'Glazed white, celadon or blue-and-white with dark crack lines.',
        'Soft light with glaze highlights.',
        'Crazed glaze network, chips and exposed bisque.',
        'Fragile, precious, aged and delicate.',
        'crazed glaze network; hairline cracks; chipped edges',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a porcelain knight's helmet glazed white and cobalt resting on a velvet cushion, crazed with fine hairline cracks across the visor, one chipped edge showing raw bisque beneath. No text or logo.",
        'Photograph of a blue-and-white porcelain dragon on a dim cabinet shelf, a web of hairline crazing through the glaze, a small chip missing from one claw and soft window light. No text or logo.',
        'Photograph of a celadon porcelain horse on a lacquered table, its pale green glaze crazed with fine dark cracks, a chipped ear and gentle reflections along its back. No text or logo.',
      ],
    },
    'SP09-030': {
      dna: w(
        'Burlap decay: coarse sackcloth surfaces frayed, stained and patched.',
        "the target's fabric surfaces fray at seams and edges, with stains and rough patches.",
        'Sack brown with darker stains and pale frayed threads.',
        'Dim natural light.',
        'Coarse weave, loose threads, stains and patches.',
        'Poor, worn, rustic and humble.',
        'frayed burlap; stains; patched weave',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a scarecrow knight whose burlap tabard is frayed and stained in a windy field. No text or logo.',
        'Photograph of a throne draped in a frayed, stained burlap cover in a cold stone hall, coarse sackcloth weave torn at the hem, patched with mismatched squares and damp stains spreading up the sides. No text or logo.',
        'Photograph of a small burlap doll slumped on a dusty windowsill, frayed edges, coffee-colored stains, a crude patch sewn over one arm and afternoon light through the coarse weave. No text or logo.',
      ],
    },
    'SP09-033': {
      dna: w(
        'Peeling paint: layered paint coats curling, cracking and flaking off to reveal older colors beneath.',
        'paint layers curl and flake from the target, revealing older coats and bare material.',
        'Layered pastel and faded colors over bare wood or metal.',
        'Soft raking light on curling flakes.',
        'Curling paint flakes, cracked layers and exposed substrate.',
        'Nostalgic, faded, neglected and layered.',
        'curling paint flakes; layered old colors; exposed substrate',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an old carousel horse with thick layered paint peeling in curls, pink over mint over red, flakes lifting from the mane and bare wood showing at the knees, soft fairground light. No text or logo.',
        'Photograph of a knight statue in a town square with peeling blue paint cracking and curling off to reveal the bronze beneath, flakes scattered on the plinth and pigeons nearby. No text or logo.',
        'Photograph of a wooden rowboat pulled onto a pebble beach with layers of white, red and green paint peeling in long curls from the hull, bare grey wood and rust stains at the oarlocks. No text or logo.',
      ],
    },
    'SP09-034': {
      dna: w(
        'Mold and mildew: fuzzy spotted mold colonies spreading over damp surfaces.',
        "patchy mold colonies and mildew spots spread over the target's damp surfaces.",
        'Black, grey-green and white mold spots.',
        'Dim damp light.',
        'Fuzzy mold colonies, spots and damp stains.',
        'Unsettling, damp, neglected and organic.',
        'fuzzy mold colonies; mildew spots; damp stains',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a velvet throne spotted with fuzzy grey-green mold colonies in a damp crypt, patches spreading over the armrests, white mildew bloom on the gilded frame and water dripping from the vault. No text or logo.',
        'Photograph of an ornate wedding portrait frame hanging in an abandoned hallway, black mildew spots spreading across the gilded edges and fuzzy mold blooming over the faded photograph. No text or logo.',
        'Photograph of a crown made of bread left on a kitchen table for weeks, fuzzy blue and white mold colonies growing over its points, spores dusting the tablecloth. No text or logo.',
      ],
    },
    'SP09-035': {
      dna: w(
        'Charred wood (shou sugi ban): wood surfaces deliberately charred into black alligator-skin char.',
        'the wooden surfaces are charred into black crackled alligator texture, brushed to reveal grain on edges.',
        'Deep charcoal black with silvery sheen and brown grain.',
        'Low side light on the crackled char.',
        'Crackled char, silvery sheen and exposed grain.',
        'Dark, elegant, protective and primal.',
        'alligator char crackle; silvery sheen; brushed grain',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a horse sculpture made of charred shou-sugi-ban timber standing in fresh snow, deep black alligator-skin char across its body, silver sheen on the cracked ridges against white ground. No text or logo.',
        'Photograph of a knight statue carved from charred timber in a stone courtyard, black alligator-skin char on the armor, brushed ridges revealing brown grain beneath and rain beading on the surface. No text or logo.',
        'Photograph of a wooden throne deliberately charred into cracked black shou-sugi-ban texture standing in a bright white gallery, the sheen on the char catching skylight. No text or logo.',
      ],
    },
    'SP09-036': {
      dna: w(
        'Water damage: tide lines, swelling, staining and bloom where water soaked the target.',
        'tide-line stains, swelling, warping and mineral bloom where water soaked the surfaces.',
        'Brown tide lines, grey bloom and darkened wet zones.',
        'Soft window light.',
        'Warped swollen surfaces, tide lines and bloom.',
        'Melancholic, neglected, damp and quiet.',
        'tide-line stains; swelling; mineral bloom',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a grand piano with tide-line stains and swelling after a flood, in an otherwise tidy room. No text or logo.',
        'Photograph of a painted wooden icon of a saint on a chapel wall after a flood, brown tide lines across the gold background, swollen warped panel and paint blooming white at the edges. No text or logo.',
        'Photograph of a wooden rocking horse in a nursery after water damage, tide-line stains on the legs, swollen joints split open and paint bloom where the water sat. No text or logo.',
      ],
    },
    'SP09-037': {
      dna: w(
        'Scratched metal: bright scratches and scuffs cutting through a metal finish.',
        'bright scratches, scuffs and nicks cut through the metal surface along worn areas.',
        'Metal grey with bright silver scratch lines.',
        'Hard light catching scratch lines.',
        'Scratches, scuffs, nicks and dulled patches.',
        'Used, battle-worn, tough and honest.',
        'bright scratch lines; scuffs and nicks; dulled wear',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a diner's stainless steel counter and stools covered in bright scratches and scuffs under hard raking light, decades of cutlery gouges cutting through the brushed finish, a dent where a stool was kicked. No text or logo.",
        'Photograph of a violin made of polished steel covered in fine bright scratches and scuffs, a deep gouge across the body where it was dropped, studio light catching every mark. No text or logo.',
        'Photograph of a steel horse sculpture in a city plaza, its flanks covered in bright scratches from skateboards and keys, scuffs on the hooves and hard midday light. No text or logo.',
      ],
    },
    'SP09-038': {
      dna: w(
        'Dusty surface: a soft layer of settled dust dulling the target, thicker on top surfaces.',
        'a fine layer of settled dust dulls the target, thicker on upward faces, with finger swipes.',
        'Grey-beige dust over the object color.',
        'Shafts of light revealing floating motes.',
        'Fine dust layer, finger swipes and motes.',
        'Forgotten, quiet, still and timeless.',
        'settled dust layer; thicker on top faces; finger swipes',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a crown on a cushion under a fine layer of settled dust with a finger swipe. No text or logo.',
        'Photograph of a golden harp in an abandoned music room under a soft layer of settled dust, thicker on the top of the frame, a single shaft of window light showing dust motes in the air. No text or logo.',
        'Photograph of a suit of armor standing in a forgotten castle corridor, dulled by a thick layer of grey dust on the shoulders and helmet, a clean handprint on the breastplate. No text or logo.',
      ],
    },
    'SP09-040': {
      dna: w(
        'Oil stains: dark glossy oil and grease stains soaking into the target.',
        'dark glossy oil and grease stains soak into the surfaces with iridescent edges.',
        'Black-brown stains with iridescent sheen.',
        'Hard light for glossy spots.',
        'Oil stains, grease smears and iridescent film.',
        'Mechanical, gritty, working and dirty.',
        'oil stains; grease smears; iridescent film',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a white wedding dress on a mannequin in a garage, dark glossy oil stains soaking into the satin skirt, grease handprints on the bodice and a wrench on the concrete floor. No text or logo.',
        "Photograph of a mechanic's canvas apron hanging on a hook in a motorcycle workshop, dark glossy oil and grease stains soaking into the fabric, handprint smears on the pocket and a rag tucked in the strap. No text or logo.",
        'Photograph of a white marble statue of a dancer in a museum with dark oil stains spreading from the base into the stone, a glossy pool on the plinth and a guard staring at it. No text or logo.',
      ],
    },
    'SP09-041': {
      dna: w(
        'Sandpaper abrasion: surfaces covered in grit or scuffed by sanding into a matte scratched finish.',
        'the surface is gritty or sanded matte with swirl marks and exposed layers.',
        'Muted, dusty tones with pale sanding marks.',
        'Soft light showing matte grit.',
        'Abrasive grit, sanding swirls and dust.',
        'Rough, workshop-worn and matte.',
        'abrasive grit; sanding swirls; matte scuffed finish',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a wooden rocking chair in a workshop half sanded, swirl marks from an orbital sander across the seat, a matte scratched finish on one side, old varnish on the other and pale dust everywhere. No text or logo.',
        'Photograph of a dragon egg covered in coarse sandpaper grit resting on a velvet cushion, angular abrasive grains glittering across its shell, a scuffed matte patch where it was rubbed. No text or logo.',
        'Photograph of an unfinished guitar body on a workbench, sanded to a matte scratched finish with visible swirl marks, a sanding block and fine dust piled beside it. No text or logo.',
      ],
    },
    'SP09-064': {
      dna: w(
        'Cracked mud: dried mud coating the target and splitting into polygon cracks.',
        'dried mud coats the target and splits into polygon cracks, curling at edges.',
        'Clay brown and ochre with dark crack lines.',
        'Harsh sun with crisp shadows in cracks.',
        'Dried mud plates, polygon cracks and curls.',
        'Parched, rough, earthy and harsh.',
        'dried mud polygon cracks; curled edges; parched clay',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a rally jeep coated in dried cracked mud parked in a desert village, the mud splitting into polygon cracks across the doors and bonnet, flakes falling from the wheel arches. No text or logo.',
        'Photograph of a rhinoceros statue in a dry riverbed caked in cracked grey mud, polygon plates curling at the edges, a few green shoots growing from the cracks along its back. No text or logo.',
        'Photograph of an ornate throne left in a drained lake bed, coated in grey mud dried into curling polygon cracks, a crow standing on the armrest. No text or logo.',
      ],
    },
    'SP09-065': {
      dna: w(
        'Tar coating: thick black tar coating the target, glossy, dripping and sticky.',
        'thick black tar coats the target with glossy drips and stringy strands.',
        'Glossy black with brown translucency at thin edges.',
        'Hard light for glossy highlights.',
        'Viscous tar, drips, strands and bubbles.',
        'Heavy, sticky, ominous and industrial.',
        'glossy black tar; drips and strands; viscous coating',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a white swan statue dripping with thick glossy black tar on a white plinth, long sticky strands stretching from the wings and pooling on the stone. No text or logo.',
        'Photograph of a seabird statue coated in thick black tar on a rocky shoreline, glossy drips hanging from its beak and wing tips, straw and sand stuck to the sticky surface. No text or logo.',
        'Photograph of a gold crown half dipped in black tar resting on a stone slab, glossy sticky coating ending in a drip line, the bare gold still shining above it. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Salt Crust',
      domain: 'salt crust efflorescence',
      tags: ['salt', 'crust', 'weathering'],
      dna: w(
        'Salt crust: white crystalline salt deposits crusting over the target, as if dried by sea spray.',
        'white salt crystals crust on edges and recesses with efflorescence blooms.',
        'White salt over darker base colors.',
        'Bright coastal light sparkling on crystals.',
        'Crystalline salt crust, blooms and granules.',
        'Coastal, dry, bleached and ancient.',
        'white salt crystal crust; efflorescence blooms',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a ship's brass bell and anchor chain left on a windswept pier, crusted with white crystalline salt deposits from years of spray, thick crystals on every upturned surface. No text or logo.",
        'Photograph of a violin left on a seaside windowsill crusted with white salt crystals, crystalline growths along the strings and f-holes, the varnish dulled beneath. No text or logo.',
        'Photograph of a wooden rowboat stranded on a dry salt lake, its hull crusted with thick white salt crystals, cracked hexagonal salt flats stretching to the horizon. No text or logo.',
      ],
    },
    {
      name: 'Sun-Bleached Fade',
      domain: 'sun-bleached fading',
      tags: ['sun-bleached', 'fade', 'weathering'],
      dna: w(
        'Sun-bleached fade: colors washed out by years of sun, pale on exposed faces and richer in shadowed folds.',
        'exposed faces fade to pale washed tones while protected folds keep deeper color.',
        'Pastel-faded versions of the original colors.',
        'Harsh overhead sun.',
        'Chalky faded pigment and dried surfaces.',
        'Nostalgic, dry, quiet and timeworn.',
        'sun-faded exposed faces; deeper colors in folds; chalky pigment',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an old roadside diner and a parked convertible in the desert, paint sun-bleached to pale pastels on the exposed side while the shaded side keeps rich red and teal, cracked lacquer and sand drifts. No text or logo.',
        'Photograph of a red velvet throne on a beach faded to pale pink on its sunlit back and armrests, richer crimson in the shaded folds, sand drifting against its legs. No text or logo.',
        'Photograph of a row of striped deck chairs on a seaside terrace sun-bleached from deep blue to pale grey on the seats while the folds keep their color, a forgotten towel on one chair. No text or logo.',
      ],
    },
    {
      name: 'Soot Staining',
      domain: 'soot and smoke staining',
      tags: ['soot', 'smoke-stain', 'weathering'],
      dna: w(
        'Soot staining: black smoke deposits blackening the target from below, as after a fire, without burning it away.',
        'black soot stains rise from lower edges and gather in crevices, surfaces intact.',
        'Black soot gradients over original colors.',
        'Dim light with smoky warmth.',
        'Soft soot deposits, smudges and fingerprints.',
        'Ominous, grim, aftermath and heavy.',
        'soot gradients from below; smudges; intact surfaces',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a white marble angel in a burned chapel, black soot staining it from below, thickest at the feet and fading upward, the stone unburned and the face still clean. No text or logo.',
        'Photograph of a tall white wedding cake on a banquet table after a kitchen fire, black soot staining the lower tiers, the top tier still white, smoke haze in the room. No text or logo.',
        'Photograph of a white porcelain teapot on a kitchen shelf blackened with soot from below after a stove fire, the lid still bright, soot fingerprints on the handle and a smoky window behind. No text or logo.',
      ],
    },
    {
      name: 'Woodworm Rot',
      domain: 'woodworm and dry rot',
      tags: ['woodworm', 'rot', 'weathering'],
      dna: w(
        'Woodworm rot: wood riddled with tiny boreholes and soft dry-rot cracking.',
        'the wooden target is riddled with small boreholes and cubic dry-rot cracks.',
        'Grey-brown wood with dark holes and pale dust.',
        'Soft side light showing holes.',
        'Boreholes, frass dust and cubic rot cracks.',
        'Decrepit, old, fragile and eerie.',
        'woodworm boreholes; cubic dry rot; frass dust',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a carved wooden saint in a chapel niche riddled with tiny woodworm boreholes, soft dry-rot cracks across the robe, fine powdery frass on the ledge beneath. No text or logo.',
        'Photograph of an antique wooden chess set riddled with woodworm holes, crumbling pawns, a rook split open by dry rot and fine powdery frass scattered across the squares. No text or logo.',
        'Photograph of a woodworm-riddled rocking chair on a farmhouse porch, tiny boreholes all over the spindles, soft dry-rot cracks in the seat and evening light. No text or logo.',
      ],
    },
    {
      name: 'Acid Etching',
      domain: 'acid-etched surfaces',
      tags: ['acid', 'etching', 'weathering'],
      dna: w(
        'Acid etching: surfaces eaten by acid into pitted, frosted and bubbled zones with bright residue edges.',
        'acid pits, frosted zones and bubbled corrosion eat into the surfaces in splash patterns.',
        'Frosted pale zones and yellow-green residue.',
        'Cold light on pitted surfaces.',
        'Pitted, frosted and bubbled corrosion.',
        'Toxic, alarming, chemical and harsh.',
        'acid pits; frosted zones; splash patterns; residue edges',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a silver tea tray eaten by acid in splash-shaped zones, pitted and frosted metal with bubbled edges and bright residue rims, the untouched silver mirror-polished around them. No text or logo.',
        'Photograph of a glass crown etched by acid, frosted pitted patches across the points, bubbled edges and clear untouched glass between, backlit on a dark cloth. No text or logo.',
        'Photograph of a bronze gazelle statue with acid-etched pitted streaks running down its flanks, frosted bubbled zones and bright green residue edges on a park plinth. No text or logo.',
      ],
    },
    {
      name: 'Lichen Crust',
      domain: 'lichen crust growth',
      tags: ['lichen', 'crust', 'weathering'],
      dna: w(
        'Lichen crust: flat crusty lichen rosettes in orange, yellow and grey growing over the target.',
        'flat lichen rosettes and crusts spread over exposed surfaces in circular patches.',
        'Orange, chartreuse and grey-green lichen.',
        'Soft overcast light.',
        'Crusty lichen rosettes and powdery patches.',
        'Ancient, slow, quiet and alive.',
        'lichen rosettes; circular crust patches; orange and chartreuse',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a stone sundial in an overgrown garden dotted with flat crusty lichen rosettes in orange, chartreuse and grey, thickest on the gnomon and upper rim, soft overcast light. No text or logo.',
        'Photograph of an old rotary telephone left on a garden wall for decades, crusted with orange and grey lichen rosettes, the dial half covered. No text or logo.',
        'Photograph of a bronze bell hanging in a ruined tower, its surface crusted with yellow and grey lichen rosettes, a rope still hanging from the clapper. No text or logo.',
      ],
    },
    {
      name: 'Ash Fall Coating',
      domain: 'volcanic ash coating',
      tags: ['ash', 'coating', 'weathering'],
      dna: w(
        'Ash fall coating: fine grey volcanic ash settled over the target, softening edges.',
        'fine grey ash settles on every upward face, softening edges and filling crevices.',
        'Monochrome grey ash over faint original colors.',
        'Diffuse hazy light.',
        'Fine powdery ash drifts and settled layers.',
        'Silent, eerie, suspended and bleak.',
        'grey ash drifts; softened edges; monochrome',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a banquet table fully set with plates, goblets and candelabras, everything coated in fine grey volcanic ash, soft rounded edges, footprints in the ash on the floor. No text or logo.',
        "Photograph of a deserted children's playground frozen under a coat of fine grey volcanic ash, the swings and slide softened, ash still falling from a dim orange sky. No text or logo.",
        'Photograph of a golden harp in an empty square covered in grey volcanic ash, strings dusted, ash drifting in the air. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
