import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, sea monsters and water spirits: culture-rooted visual languages for leviathans,
// river spirits, sea goddesses and drowned kingdoms. Eleven originals stay; eleven new looks add
// Nordic cartography, Central and West African popular painting, Japanese, Slavic, Chinese,
// Babylonian, Indian, Filipino, Scottish and Amazonian traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} water-spirit art`,
  tags: [tag, culture.toLowerCase().replace(/\s+/g, '-'), 'mythic-waters', 'portable-style-study'],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Sea Monsters & Water Spirits',
  updates: {},
  creates: [
    s(
      'Carta Marina Monster Chart',
      'carta-marina',
      'Nordic cartographic',
      'Carta marina monster chart: sixteenth-century northern sea charts crowded with hand-colored sea monsters, whales mistaken for islands, serpents and sinking ships.',
      'place the subject as a hand-colored monster on an old engraved sea chart.',
      'Faded sea green, ochre coasts and red accents.',
      'Flat chart color without light, kept consistent across the whole image.',
      'Engraved lines, hand color and aged paper, kept consistent across the whole image.',
      'Chart with coasts and monster-filled sea, kept consistent across the whole image.',
      'wondrous seafaring fear',
      'Detailed engraved chart without readable labels, kept consistent across the whole image.',
      'sea chart; hand-colored monsters; whale island; engraved waves',
      [
        'Coiling across a hand-colored northern sea chart, a colossal sea serpent wraps a merchant ship while sailors on a nearby whale think they have landed on an island. No readable text or logo.',
        'On an old sea chart, a monstrous whale spouts so proudly that it has soaked the compass rose. No readable text or logo.',
        'At the far edge of an engraved chart, the waves stop drawing, and a single eye watches from the blank sea. No readable text or logo.',
      ],
    ),
    s(
      'Mami Wata Popular Painting',
      'mami-wata',
      'West and Central African',
      'Mami Wata popular painting: vivid West and Central African popular paintings of the glamorous water spirit with a serpent around her shoulders, mirrors, combs and river light.',
      'paint the subject as a vivid popular painting of a glamorous water spirit.',
      'Turquoise water, gold, bright red and green, kept consistent across the whole image.',
      'Bright glossy light on water, kept consistent across the whole image.',
      'Enamel paint on board, bold outlines and shine.',
      'Frontal portrait standing at the edge of a glowing river.',
      'alluring mysterious power',
      'Vivid popular painting, kept consistent across the whole image.',
      'water spirit; serpent; mirror and comb; river light',
      [
        'Rising from a turquoise river with a great python draped across her shoulders, the glamorous water spirit holds up a golden mirror that reflects a city beneath the waves. No readable text or logo.',
        'At the riverbank, a water spirit has left her mirror behind, and a fisherman is very carefully deciding whether to touch it. No readable text or logo.',
        'On a still river at dusk, a comb floats on the surface, and the water around it is perfectly calm. No readable text or logo.',
      ],
    ),
    s(
      'Dragon Palace Undersea Screen',
      'dragon-palace',
      'Japanese',
      "Dragon palace undersea screen: Japanese folding screen painting of the sea king's palace beneath the waves, coral halls, fish attendants and a jeweled dragon king on gold.",
      'paint the subject in an undersea palace of coral and gold on a folding screen.',
      'Gold leaf, sea green, coral red and pearl white.',
      'Glowing gold and undersea light, kept consistent across the whole image.',
      'Gold leaf screen, mineral pigment and fine line.',
      'Palace scene across screen panels, kept consistent across the whole image.',
      'enchanted undersea splendor',
      'Rich decorative screen painting, kept consistent across the whole image.',
      'undersea palace; coral halls; fish attendants; gold screen',
      [
        "Across a gold folding screen, a fisherman rides a giant turtle into the dragon king's coral palace as fish attendants in court robes line the pearl steps. No readable text or logo.",
        'In the undersea palace, a fisherman is enjoying the banquet so much that he has not noticed three hundred years have passed. No readable text or logo.',
        'On a gold screen, a lacquer box from the dragon palace sits on a beach, and a thin white smoke is escaping its lid. No readable text or logo.',
      ],
    ),
    s(
      'Rusalka Moonlit Lake Illustration',
      'rusalka',
      'Slavic',
      'Rusalka moonlit lake illustration: Slavic folk-tale illustration of water maidens with long green hair among birches and moonlit lakes, ornate folk borders.',
      'show the subject in a moonlit lake scene with water maidens and folk borders.',
      'Moon silver, birch white, deep green and blue.',
      'Moonlight on still water, kept consistent across the whole image.',
      'Watercolor, ink outline and ornamental borders, kept consistent across the whole image.',
      'Lake scene framed by folk ornament, kept consistent across the whole image.',
      'haunting lakeside allure',
      'Elegant folk illustration, kept consistent across the whole image.',
      'water maidens; birches; moonlit lake; folk border',
      [
        'Sitting in the branches of a birch over a moonlit lake, water maidens with long green hair comb their tresses and call softly to a fisherman rowing too close. No readable text or logo.',
        'At a moonlit lake, the water maidens try to enchant a traveler who is completely distracted by his fishing line. No readable text or logo.',
        'On a still lake at night, a wreath of flowers floats on the water, and a pale hand is holding it from below. No readable text or logo.',
      ],
    ),
    s(
      'Mazu Sea Goddess Mural',
      'mazu',
      'Chinese',
      'Mazu sea goddess mural: Chinese coastal temple mural of the goddess of the sea calming storms, her two demon generals with keen eyes and ears, and ships guided home.',
      'paint the subject in a coastal temple mural of the sea goddess calming a storm.',
      'Vermilion, gold, sea green and storm grey, kept consistent across the whole image.',
      'Radiant halo over dark waves, kept consistent across the whole image.',
      'Temple plaster, gold leaf and fine line, kept consistent across the whole image.',
      'Storm seascape with a radiant figure, kept consistent across the whole image.',
      'protective serene grace',
      'Reverent vivid mural, kept consistent across the whole image.',
      'sea goddess; calming storm; guardian generals; ships',
      [
        'Standing on the clouds above a black storm, the sea goddess raises her hand and the waves fall still as fishing junks turn toward her light and two guardian generals watch the horizon. No readable text or logo.',
        "In a temple mural, the goddess's far-seeing guardian has spotted a lost boat, and her far-hearing guardian is covering his ears from the thunder. No readable text or logo.",
        'On a stormy temple mural, one small boat in the waves has a lantern that glows brighter than the paint around it. No readable text or logo.',
      ],
    ),
    s(
      'Tiamat Glazed Brick Serpent',
      'glazed-brick',
      'Babylonian',
      'Tiamat glazed brick serpent: Babylonian glazed brick reliefs in deep blue and gold with striding dragons and bulls, reimagined as the primordial sea serpent of chaos.',
      'render the subject in raised glazed bricks of deep blue and gold.',
      'Deep lapis blue glaze with gold and white.',
      'Glossy light on glazed brick, kept consistent across the whole image.',
      'Glazed brick relief, mortar lines and chips, kept consistent across the whole image.',
      'Wall panel with a striding creature, kept consistent across the whole image.',
      'primordial majestic chaos',
      'Crisp glazed relief, kept consistent across the whole image.',
      'glazed brick; lapis blue; striding dragon; relief',
      [
        'Rising from a wall of deep blue glazed bricks, the primordial sea serpent of chaos coils through golden waves as a young storm god draws his bow against her. No readable text or logo.',
        'On a glazed brick wall, a striding dragon has been assembled with one brick upside down, giving it a startled expression. No readable text or logo.',
        'On a blue glazed wall in moonlight, one golden serpent brick glistens wet, as if something has just risen from the sea. No readable text or logo.',
      ],
    ),
    s(
      'Makara Temple Gateway Carving',
      'makara',
      'Indian',
      'Makara temple gateway carving: Indian stone gateway arches with makara sea creatures, part crocodile, fish and elephant, spewing foliage and pearls.',
      'carve the subject as makara sea creatures on an ornate stone gateway.',
      'Warm sandstone with moss green, kept consistent across the whole image.',
      'Dappled light on carved stone, kept consistent across the whole image.',
      'Dense stone carving, foliate scrolls and moss, kept consistent across the whole image.',
      'Arched gateway composition, kept consistent across the whole image.',
      'lush guardian wonder',
      'Intricate stone carving, kept consistent across the whole image.',
      'makara creature; gateway arch; foliage; pearls',
      [
        'Arching over a temple gateway, two sea creatures with crocodile jaws, fish tails and elephant trunks spew garlands of lotus and pearls into a sacred tank below. No readable text or logo.',
        'On a carved temple gate, a sea creature with a curling trunk seems to be trying to sneeze out a pearl. No readable text or logo.',
        "On an old temple gateway at dusk, the carved sea creature's mouth drips with water although the air is dry. No readable text or logo.",
      ],
    ),
    s(
      'Bakunawa Moon-Eater Painting',
      'bakunawa',
      'Filipino',
      'Bakunawa moon-eater painting: Philippine folklore painting of the great sea serpent rising from the ocean to swallow the moon while villagers bang pots to scare it.',
      'paint the subject as a great sea serpent rising to swallow the moon.',
      'Deep ocean blue, moon silver and red, kept consistent across the whole image.',
      'Moonlight and serpent glow, kept consistent across the whole image.',
      'Painterly waves, scales and night sky, kept consistent across the whole image.',
      'Serpent rising toward a huge moon, kept consistent across the whole image.',
      'cosmic folk drama',
      'Bold dramatic painting, kept consistent across the whole image.',
      'sea serpent; moon; ocean; villagers with pots',
      [
        'Rising from the dark ocean with gills like wings, a colossal sea serpent opens its jaws around the moon as villagers on the shore bang pots and gongs to drive it away. No readable text or logo.',
        'Having swallowed the moon, a great sea serpent is now very uncomfortable because it glows through its belly. No readable text or logo.',
        'On a calm sea at night, a crescent moon hangs low, and a long dark shape circles beneath its reflection. No readable text or logo.',
      ],
    ),
    s(
      'Kelpie River Horse Etching',
      'kelpie',
      'Scottish',
      'Kelpie river horse etching: Scottish etchings of shape-shifting water horses with dripping manes of weed, rearing from dark lochs and rivers.',
      'etch the subject as a dripping water horse rearing from a dark loch.',
      'Dark loch greys with silver highlights, kept consistent across the whole image.',
      'Moonlight and spray, kept consistent across the whole image.',
      'Etched line, aquatint water and paper, kept consistent across the whole image.',
      'Horse rearing from water, kept consistent across the whole image.',
      'wild treacherous beauty',
      'Dramatic etched finish, kept consistent across the whole image.',
      'water horse; weed mane; dark loch; spray',
      [
        'Rearing out of a dark loch in a burst of silver spray, a water horse with a mane of dripping weed shakes off the shape of a fine black stallion. No readable text or logo.',
        'Beside a Highland river, a water horse tries very hard to look like an ordinary pony and fails because of the seaweed. No readable text or logo.',
        'On a loch shore at dawn, a set of hoofprints leads into the water, and a bridle lies on the stones. No readable text or logo.',
      ],
    ),
    s(
      'Amazon Iara River Painting',
      'iara',
      'Amazonian Brazilian',
      'Amazon iara river painting: lush Brazilian folklore painting of the river siren among giant lilies, flooded forest, pink dolphins and golden light.',
      'paint the subject in a lush flooded forest with giant lilies and river light.',
      'Emerald green, river gold and pink dolphin tones.',
      'Golden light through the canopy, kept consistent across the whole image.',
      'Lush painterly foliage and water reflections, kept consistent across the whole image.',
      'River scene among giant lilies, kept consistent across the whole image.',
      'lush enchanted danger',
      'Rich tropical painting, kept consistent across the whole image.',
      'river siren; giant lilies; flooded forest; pink dolphins',
      [
        'Singing from a giant lily pad in the flooded forest, the river siren draws a canoe toward her as pink river dolphins circle and the canopy glows gold. No readable text or logo.',
        'In the flooded forest, a pink river dolphin has disguised itself as a charming stranger for a village dance and forgot to take off its hat. No readable text or logo.',
        'In a still flooded forest, a canoe drifts empty among the giant lilies, its paddle floating beside it. No readable text or logo.',
      ],
    ),
    s(
      'Umibozu Storm Woodblock',
      'umibozu',
      'Japanese',
      'Umibozu storm woodblock: Japanese woodblock prints of the vast sea monk spirit rising from night storms beside fishing boats, huge dark head and glowing eyes.',
      'print the subject as a vast dark sea spirit rising beside small boats in a storm.',
      'Prussian blue, black and wave white, kept consistent across the whole image.',
      'Storm light and glowing eyes, kept consistent across the whole image.',
      'Woodblock lines, bokashi and paper grain, kept consistent across the whole image.',
      'Towering figure beside small boats, kept consistent across the whole image.',
      'overwhelming oceanic dread',
      'Bold dramatic woodblock, kept consistent across the whole image.',
      'sea monk spirit; night storm; fishing boats; glowing eyes',
      [
        'Rising from a night storm taller than any mast, a vast dark sea spirit with glowing eyes looms over a fishing boat as the crew hands it a bottomless ladle. No readable text or logo.',
        'Asked by a sea spirit for a ladle, clever fishermen hand over one with no bottom, and the spirit is very confused. No readable text or logo.',
        "On a calm night sea, the fishermen's lanterns reflect in the water, and one reflection is a pair of enormous eyes. No readable text or logo.",
      ],
    ),
  ],
};

export default spec;
