import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, witches, oracles and shamans: culture-rooted visual languages for seers, healers,
// exorcists, sorcerers and fortune tellers. Six originals stay (two re-briefed toward the theme);
// fifteen new looks add Ottoman, Baroque, Chinese, Sri Lankan, Ethiopian, Pennsylvania German,
// stage-magic, Ghanaian, Japanese, Mesopotamian, Maithil, Egyptian, Arabic, Mexican and Guna traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} magic and divination art`,
  tags: [tag, culture.toLowerCase().replace(/\s+/g, '-'), 'mythic-magic', 'portable-style-study'],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Witches, Oracles & Shamans',
  updates: {
    'SP14-198': {
      briefs: [
        'Woven into a faded narrow band, a seeress in a dark cloak rides a wagon at the head of a procession, her staff raised as ravens, horses and shielded warriors wait for her prophecy. No readable text or logo.',
        'In a fragile woven band, a whole procession has stopped to hear a prophecy, and the seeress has clearly forgotten what she was going to say. No readable text or logo.',
        'At the frayed edge of an old tapestry, an empty high seat stands alone, and a single raven sits on its back. No readable text or logo.',
      ],
    },
    'SP14-179': {
      briefs: [
        'Beneath a full moon over a snowy shrine, a shrine maiden with a bell wand dances in the lantern glow while her shadow on the snow has grown nine fox tails. No readable text or logo.',
        'On a snowy night street, a fox wearing a borrowed human face buys lantern oil and forgets to hide its tail. No readable text or logo.',
        'On a moonlit bridge, a woman with an umbrella crosses the snow, and she leaves only small fox prints behind her. No readable text or logo.',
      ],
    },
  },
  creates: [
    s(
      'Falname Omen Painting',
      'falname',
      'Ottoman',
      'Falname omen painting: large-format Ottoman and Safavid books of omens, grand painted pages of prophets, angels, demons and wonders consulted by fortune tellers, bold figures on gold and flat jewel color.',
      'paint the subject as a large bold figure in a grand omen page of jewel color and gold.',
      'Gold ground, lapis, vermilion, emerald and flame orange.',
      'Flat shadowless light with gold glowing from within.',
      'Opaque watercolor, burnished gold, flame haloes and fine line.',
      'Single large page filled by one dramatic omen scene.',
      'fateful wondrous omen',
      'Bold large-scale manuscript painting, kept consistent across the whole image.',
      'omen page; flame haloes; angels and demons; gold ground',
      [
        'Opening a giant book of omens for a nervous traveler, a fortune teller reveals a painted page where an angel with flaming wings wrestles a many-eyed demon over a burning city of gold. No readable text or logo.',
        "At a fortune teller's table, the book of omens has opened to a page so terrible that the painted demon on it is also covering its eyes. No readable text or logo.",
        'On a low table under a lamp, a huge book of omens lies open to a single gold page with one small bird. No readable text or logo.',
      ],
    ),
    s(
      'Tenebrist Sorceress Oil',
      'tenebrist-sorceress',
      'Baroque European',
      'Tenebrist sorceress oil: seventeenth-century candlelit oil paintings of enchantresses and sibyls, a single flame carving faces and hands out of deep black, magic circles, skulls and smoking bowls.',
      'paint the subject lit by a single flame in deep black, hands and face carved out of darkness.',
      'Deep black, candle amber, blood red velvet and bone white.',
      'Single candle source with hard falloff into total black.',
      'Oil glaze, visible brush, varnish sheen and dark canvas grain.',
      'Close half-figure with the flame in frame and deep empty darkness.',
      'hushed forbidden power',
      'Masterful dark oil painting with glowing flesh tones.',
      'single candle; deep black; magic circle; smoking bowl',
      [
        "Leaning over a chalk circle by the light of one candle, an enchantress pours silver into a smoking bowl, and the smoke rises into the faint shape of a stranger's face. No readable text or logo.",
        'By the light of one candle, a sorceress checks her spell book twice and then looks suspiciously at the cat. No readable text or logo.',
        'On a dark table, a candle has just gone out, and its smoke curls into a perfect circle. No readable text or logo.',
      ],
    ),
    s(
      'Nuo Exorcism Mask Theater',
      'nuo-mask',
      'Chinese',
      'Nuo exorcism mask theater: rural Chinese Nuo ritual theater with carved and painted wooden masks of exorcist gods, bulging eyes, horns and fangs, performed in smoke and torchlight to drive plague spirits away.',
      'show the subject wearing a carved painted wooden exorcist mask in smoky torchlit ritual theater.',
      'Cinnabar red, gold, black, green and white, kept consistent across the whole image.',
      'Torchlight and incense smoke, faces flickering, kept consistent across the whole image.',
      'Carved painted wood masks, cloth robes, smoke and ash.',
      'Low close angle on masked performers mid-gesture in a village square.',
      'fierce protective ritual',
      'Vivid dramatic performance depiction, kept consistent across the whole image.',
      'carved wood masks; exorcist gods; torch smoke; village square',
      [
        'Leaping through torch smoke in a village square, masked exorcist gods with golden fangs and horns drive a crowd of shadowy plague spirits out through the gate. No readable text or logo.',
        'Waiting backstage at a village ritual, a performer in a terrifying carved mask is gently sipping tea. No readable text or logo.',
        'Hung on a dark wall after the ritual, a row of carved masks stares into the smoke. No readable text or logo.',
      ],
    ),
    s(
      'Sanni Healing Masks',
      'sanni-masks',
      'Sri Lankan',
      'Sanni healing masks: Sri Lankan carved masks of the eighteen illness spirits with wild eyes and snakes, used in all-night healing dances of drums, fire and palm-leaf arches.',
      'show the subject in an all-night healing dance of carved illness spirit masks, drums and fire.',
      'Red, yellow, green, black and palm cream, kept consistent across the whole image.',
      'Torch and firelight in deep tropical night, kept consistent across the whole image.',
      'Carved kaduru wood masks, lacquer paint, palm leaf and cloth.',
      'Performance space under a palm-leaf arch with dancers circling.',
      'feverish night healing',
      'Vibrant performance depiction with mask detail, kept consistent across the whole image.',
      'illness spirit masks; drummers; palm-leaf arch; fire',
      [
        'Under a woven palm-leaf arch at midnight, masked illness spirits with cobra crowns and bulging eyes dance around a patient as drummers call them out one by one to leave. No readable text or logo.',
        'At an all-night healing, the spirit of fever arrives very late and finds that everyone has already recovered. No readable text or logo.',
        'At dawn after the ceremony, a carved spirit mask rests on a palm mat beside a cold drum. No readable text or logo.',
      ],
    ),
    s(
      'Ethiopian Protective Scroll',
      'ethiopian-scroll',
      'Ethiopian',
      'Ethiopian protective scroll: tall narrow parchment scrolls drawn for healing, with staring angel faces, eyes in geometric nets, crosses and interlaced stars in red, yellow and black ink.',
      'draw the subject in a tall narrow parchment panel with staring eyes and interlaced geometric nets.',
      'Red ink, ochre yellow, black and parchment cream.',
      'Flat parchment light with no cast shadow, kept consistent across the whole image.',
      'Ink and pigment on parchment, uneven edges and fine line.',
      'Tall narrow vertical strip with a central face and geometric net.',
      'watchful protective magic',
      'Precise graphic parchment drawing, kept consistent across the whole image.',
      'staring eyes; geometric nets; angel faces; parchment strip',
      [
        'Drawn on a tall strip of parchment, an angel with enormous eyes spreads its wings inside a net of interlaced stars, and a small demon trying to cross the net is caught in its knots. No readable text or logo.',
        'In a protective scroll, a hundred painted eyes stare out at once, and a very small fly has decided to leave. No readable text or logo.',
        'Rolled half open on a wooden table, a narrow parchment shows only a single watching eye in a red star. No readable text or logo.',
      ],
    ),
    s(
      'Hex Sign Barn Painting',
      'hex-sign',
      'Pennsylvania German',
      'Hex sign barn painting: Pennsylvania German folk barn stars and rosettes painted on big red barns, distelfink birds, tulips and compass stars in bright flat circles.',
      'paint the subject as a bright circular folk emblem of stars, birds and tulips on a barn wall.',
      'Barn red, sunflower yellow, sky blue, white and black.',
      'Bright farm daylight with crisp barn-plank shadows, kept consistent across the whole image.',
      'Flat house paint on weathered barn planks, crisp compass geometry.',
      'Frontal barn wall with one or more large circular emblems.',
      'cheerful folk protection',
      'Crisp flat folk graphic painting, kept consistent across the whole image.',
      'compass stars; distelfink birds; tulips; barn wall',
      [
        'Painted across a red barn wall, a huge circle of stars and tulips holds two yellow birds guarding the harvest, while a real storm curves politely around the barn. No readable text or logo.',
        'On a red barn, a painted good-luck bird has been guarding the harvest so long that real birds come to it for advice. No readable text or logo.',
        'On a faded red barn at dusk, a single painted star has almost vanished, except for one bright point. No readable text or logo.',
      ],
    ),
    s(
      'Stage Illusionist Poster',
      'illusionist-poster',
      'Edwardian stage-magic',
      "Stage illusionist poster: turn-of-the-century lithograph posters for touring stage magicians, with imps whispering in the magician's ear, levitating assistants, skulls and devils in saturated stone-litho color.",
      'present the subject as the star of a bold stone-lithograph magic show poster with whispering imps.',
      'Crimson, black, saffron yellow, stage green and cream.',
      'Dramatic stage limelight on a dark backdrop, kept consistent across the whole image.',
      'Stone lithograph, flat color separations and poster paper.',
      'Vertical poster with the performer large and wonders around them.',
      'thrilling theatrical magic',
      'Bold vintage poster art without readable lettering, kept consistent across the whole image.',
      'stage magician; whispering imps; levitation; lithograph color',
      [
        'In a blazing lithograph poster, a stage magician in evening dress levitates a sleeping assistant above a red curtain as tiny devils whisper secrets into both of his ears. No readable text or logo.',
        "On a vintage magic poster, the whispering imps on the magician's shoulders are clearly telling him two completely different tricks. No readable text or logo.",
        'On an empty stage, a single top hat sits under a spotlight, and a small red hand is reaching out of it. No readable text or logo.',
      ],
    ),
    s(
      'Ghana Hand-Painted Witch Poster',
      'ghana-poster',
      'Ghanaian',
      'Ghana hand-painted witch poster: lurid hand-painted film posters from Ghana, oil on stitched flour sacks, with wild witches, flying heads, snakes and fire exaggerated far beyond any real film.',
      'paint the subject as a wild exaggerated scene on a hand-painted flour-sack film poster.',
      'Hot orange, poison green, blood red, black and sky blue.',
      'Melodramatic glow and fire light, kept consistent across the whole image.',
      'Oil paint on stitched flour sacks, visible seams and bold brush.',
      'Crowded vertical poster with a huge central figure and multiple wonders.',
      'wild sensational thrill',
      'Exuberant naive painting with fearless exaggeration, kept consistent across the whole image.',
      'flour-sack canvas; flying heads; snakes and fire; lurid color',
      [
        'Painted on stitched flour sacks, a towering witch with glowing eyes rides a giant snake over a burning village while flying heads and a crocodile in a suit chase a terrified taxi. No readable text or logo.',
        'On a hand-painted poster, the witch is so huge that the painter ran out of sack and had to stitch on more for her hat. No readable text or logo.',
        'On a wall at night, a peeling hand-painted poster shows only two green eyes glowing from the dark. No readable text or logo.',
      ],
    ),
    s(
      'Iwami Kagura Serpent Dance',
      'iwami-kagura',
      'Japanese',
      'Iwami kagura serpent dance: Japanese shrine theater where a hero battles giant serpents made of paper and cloth that coil around the stage, with gold brocade costumes, masks and smoke.',
      'show the subject in shrine theater with brocade costume and coiling paper-cloth serpents.',
      'Gold brocade, serpent green, fire red, smoke white and black.',
      'Stage lanterns and fireworks glow through smoke, kept consistent across the whole image.',
      'Gold brocade, paper-cloth serpent bodies, carved masks and smoke.',
      'Wide stage view with serpents coiling around a central performer.',
      'exuberant theatrical myth',
      'Rich spectacular performance depiction, kept consistent across the whole image.',
      'giant paper serpents; brocade hero; masks; stage smoke',
      [
        'On a smoky shrine stage, eight giant serpents made of paper and cloth coil around a hero in blazing gold brocade as sparks burst from their painted jaws. No readable text or logo.',
        'During a shrine performance, one of the eight giant serpents has become tangled with another and both are trying to be very scary. No readable text or logo.',
        'After the festival, a giant paper serpent lies coiled and quiet at the back of an empty stage. No readable text or logo.',
      ],
    ),
    s(
      'Lamashtu Exorcism Plaque',
      'exorcism-plaque',
      'Mesopotamian',
      'Lamashtu exorcism plaque: Mesopotamian bronze exorcism plaques with a protective demon peering over the top, and registers of healers in fish cloaks, symbols and a monster driven away on a boat.',
      'cast the subject into a small bronze plaque with registers of healers and a protective demon peering over.',
      'Bronze brown, verdigris green, dull gold and shadow black.',
      'Low raking light on cast relief, kept consistent across the whole image.',
      'Cast bronze relief, patina and worn edges, kept consistent across the whole image.',
      'Small rectangular plaque in horizontal registers, kept consistent across the whole image.',
      'ancient protective dread',
      'Crisp small-scale relief detail, kept consistent across the whole image.',
      'bronze plaque; registers; fish-cloaked healers; protective demon',
      [
        'Cast into a small bronze plaque, healers in fish-skin cloaks chant over a sick adult while a monstrous goddess is sent away on a boat, and a protective demon peers down from the top edge. No readable text or logo.',
        'On an ancient healing plaque, the protective demon peering over the top looks like it is supervising very closely. No readable text or logo.',
        'In a museum case at night, a small bronze plaque glows faintly, and the carved boat on it seems to drift. No readable text or logo.',
      ],
    ),
    s(
      'Mithila Wall Painting Seer',
      'mithila-seer',
      'Maithil',
      'Mithila wall painting seer: Bihar folk paintings with double-line outlines, filled with fine hatching, fish, suns, serpents and wide-eyed figures, every space dense with pattern.',
      'paint the subject with double-line outlines and fine hatching among fish, suns and serpents.',
      'Turmeric yellow, vermilion, indigo, leaf green and black on cream.',
      'Flat bright color with no cast shadow, kept consistent across the whole image.',
      'Natural pigment on handmade paper or mud wall, fine nib line and hatching.',
      'Frontal composition with every space filled by pattern.',
      'joyous dense enchantment',
      'Crisp patterned folk painting, kept consistent across the whole image.',
      'double-line outlines; fine hatching; fish and suns; dense pattern',
      [
        'Seated beneath a hatched sun and moon, a wide-eyed seer reads the future in a bowl of water while fish, serpents and birds swirl from it to fill every inch of the wall. No readable text or logo.',
        'In a densely patterned painting, a village seer tries to see the future, but every inch of her view is already filled with fish. No readable text or logo.',
        'On a cream wall, a single painted fish swims inside a double-line circle, facing the door. No readable text or logo.',
      ],
    ),
    s(
      'Egyptian Faience Amulet Magic',
      'faience-amulet',
      'Egyptian',
      'Egyptian faience amulet magic: glazed turquoise faience amulets of protective gods, eyes, dwarf guardians and scarabs, strung on cords or set on dark stone, luminous blue-green glaze.',
      'shape the subject as a small glazed turquoise faience amulet or scene of glowing protective charms.',
      'Turquoise glaze, lapis, gold, black and sand, kept consistent across the whole image.',
      'Soft spot light making glaze glow and shimmer.',
      'Glazed faience, crackle, worn edges and polished beads.',
      'Close macro still life of charms on dark stone or cloth.',
      'mysterious protective glow',
      'Precise macro still life with luminous glaze, kept consistent across the whole image.',
      'turquoise faience; protective eyes; scarabs; dwarf guardian',
      [
        "Laid out on dark stone in a magician's chest, dozens of turquoise faience amulets glow, protective eyes, scarabs and a grinning dwarf guardian, as one begins to move by itself. No readable text or logo.",
        "In a magician's case, a tiny grinning guardian amulet has pushed all the other charms aside to get the best spot. No readable text or logo.",
        'On black cloth in a sealed tomb chamber, a single turquoise eye amulet catches a thin sliver of lamplight from the opening door. No readable text or logo.',
      ],
    ),
    s(
      'Book of Wonders Astrologer',
      'book-wonders',
      'Arabic',
      'Book of wonders astrologer: medieval Arabic manuscripts of cosmic wonders with astrologers, angels of the spheres, star creatures and marvels on plain paper with gold and bright mineral color.',
      'paint the subject as a small bright figure among angels and star creatures in a wonders manuscript.',
      'Lapis, vermilion, gold, green and buff paper, kept consistent across the whole image.',
      'Flat even light with gold highlights, kept consistent across the whole image.',
      'Mineral color, gold leaf, fine ink line and buff paper.',
      'Figure with instruments beneath stacked celestial creatures, kept consistent across the whole image.',
      'curious cosmic wonder',
      'Delicate manuscript painting, kept consistent across the whole image.',
      'astrologer; angels of the spheres; star creatures; gold',
      [
        'Kneeling on a rooftop with a brass instrument, an astrologer watches the angels of the seven spheres pass overhead, each riding a creature made of stars. No readable text or logo.',
        'An astrologer carefully measures the sky with a brass instrument while a star creature right above him waves. No readable text or logo.',
        'On a quiet manuscript page, a single brass instrument rests on a rooftop under one bright star. No readable text or logo.',
      ],
    ),
    s(
      'Curandera Tin Ex-Voto',
      'ex-voto',
      'Mexican',
      'Curandera tin ex-voto: Mexican painted tin votive panels telling small miracle stories, a healer or saint appearing in a corner cloud, simple naive figures in flat color on dented tin.',
      'paint the subject as a small naive miracle scene on dented tin with a glowing helper in a cloud.',
      'Pink, sky blue, ochre, green and tin silver.',
      'Naive glowing light from a heavenly cloud, kept consistent across the whole image.',
      'Oil on dented tin, scratches and nail holes.',
      'Small horizontal scene with a room and a cloud in one corner.',
      'humble grateful wonder',
      'Naive heartfelt painting, kept consistent across the whole image.',
      'painted tin; naive figures; miracle cloud; dented metal',
      [
        'On a dented tin panel, a village healer with a bundle of herbs cures a farmer bitten by a scorpion as a glowing figure appears in a pink cloud in the corner. No readable text or logo.',
        'On a painted tin panel, a healer saves a very sick goat, and the goat looks unmistakably grateful. No readable text or logo.',
        'Nailed to a chapel wall, a small tin panel shows only an empty bed and a glowing cloud. No readable text or logo.',
      ],
    ),
    s(
      'Mola Spirit Panel',
      'mola-panel',
      'Guna',
      'Mola spirit panel: Guna reverse-appliqué textile panels from Panama with layered cut fabric in maze-like channels, bold red, black and orange, spirit creatures and healers.',
      'cut and stitch the subject as a layered reverse-appliqué panel of maze-like channels.',
      'Red, black, orange, blue and green, kept consistent across the whole image.',
      'Flat bright textile color, kept consistent across the whole image.',
      'Layered cotton, cut channels, hand stitching, kept consistent across the whole image.',
      'Rectangular panel filled with a central figure and maze lines.',
      'vivid spirit play',
      'Bold graphic textile craft, kept consistent across the whole image.',
      'reverse appliqué; maze channels; spirit creatures; bold colors',
      [
        'Cut into layered red and black cloth, a healer holds carved spirit figures as maze-like channels spiral into sea turtles, birds and lightning around them. No readable text or logo.',
        'In a layered textile panel, a spirit bird has been cut with so many maze lines that it is lost inside itself. No readable text or logo.',
        'On a bright red textile panel, a single orange lightning bolt runs through winding black maze channels toward a tiny stitched turtle. No readable text or logo.',
      ],
    ),
  ],
};

export default spec;
