import type { Spec } from '../tools/apply';
import { ga, keep } from './_authors';

// Video game pass, arcane temples and mythic realms: each preset names its game, studio and year
// and states the real render technique and camera. Briefs that restaged a signature creature
// (the celestial wolf, the one-eyed guardian machine, the three bog crones) are replaced.
const spec: Spec = {
  pack: 'pack_12',
  category: '2. Arcane Temples & Mythic Realms',
  updates: Object.fromEntries([
    ga('SP12-006', 'Bloodstained 2019 - ArtPlay 2.5D Gothic Castle', {
      look: 'ArtPlay Bloodstained: Ritual of the Night (2019) look: 2.5D side-scrolling gothic castle in the Koji Igarashi Castlevania tradition, stylized 3D models on a flat plane, ornate libraries and giant demon bosses.',
      subject:
        'render people as stylized 3D gothic anime figures with ornate clothing, moving on a flat side-scrolling plane.',
      color: 'Gothic crimson, library gold, deep violet and cold moon blue.',
      light: 'Candelabra glow, stained-glass beams and bright spell flashes.',
      texture: 'Stylized painted 3D surfaces of carved wood, stone and velvet.',
      camera: '2.5D side-scrolling view with parallax gothic depth.',
      mood: 'ornate gothic exploration',
      render: 'Authentic modern 2.5D metroidvania screen.',
      key: 'Bloodstained 2.5D; gothic castle; Igarashi metroidvania; demon bosses',
      avoid: ['a pale heroine with crystal shards on her back'],
    }),
    ga('SP12-013', 'Journey 2012 - thatgamecompany Sand Pilgrimage', {
      look: 'thatgamecompany Journey (2012) look: vast shimmering sand dunes rendered with glittering sand shaders, tiny cloaked figures with glowing scarves, flying cloth creatures and a distant beam-topped mountain.',
      subject:
        'render people as tiny faceless cloaked figures with long glowing scarves, small against vast landscapes.',
      color: 'Glittering gold sand, sunset rose, deep red cloth and cool blue shadow.',
      light: 'Low sun turning sand to glittering gold with soft long shadows.',
      texture: 'Shimmering sand shader, soft cloth and weathered stone ruins.',
      camera: 'Wide third-person view dwarfing the small traveler.',
      mood: 'wordless shared awe',
      render: 'Authentic early-2010s art-game screen.',
      key: 'Journey glittering sand; tiny cloaked pilgrim; glowing scarf',
      avoid: ['a red-robed traveler with a gold-embroidered scarf'],
    }),
    ga('SP12-015', 'Axiom Verge 2015 - Thomas Happ Glitch Pixel Ruin', {
      look: 'Thomas Happ Axiom Verge (2015) look: 16-bit style pixel metroidvania in a biomechanical alien ruin, H.R. Giger-inspired organic machinery, glitch-gun corruption and scrambled pixels.',
      subject:
        'render people as small detailed pixel sprites in biomechanical ruins, with glitch effects scrambling nearby pixels.',
      color: 'Toxic purple, flesh pink, alien teal and corrupted neon.',
      light: 'Dark ruin interiors lit by glowing organic machinery.',
      texture: 'Dense 16-bit pixel art with biomechanical detail and glitch noise.',
      camera: 'Side-view metroidvania room view.',
      mood: 'eerie alien discovery',
      render: 'Authentic modern pixel metroidvania screen.',
      key: 'Axiom Verge pixels; biomechanical ruin; glitch corruption',
    }),
    ga('SP12-020', 'Sunless Skies 2019 - Failbetter Gaslamp Void Trade', {
      look: 'Failbetter Games Sunless Skies (2019) look: top-down painted gaslamp void, flying locomotives with lantern prows, Victorian space ports and gothic celestial horrors.',
      subject:
        'render people and vessels as small painted steam locomotives and Victorian figures seen from above in a dark void.',
      color: 'Deep void black, lantern amber, cosmic teal and brass.',
      light: 'Lantern prow cones cutting through dark starry void.',
      texture: 'Hand-painted illustrative surfaces with gothic detail.',
      camera: 'Top-down view of the locomotive in the void.',
      mood: 'gothic cosmic wanderlust',
      render: 'Authentic painted top-down exploration screen.',
      key: 'Sunless Skies void; flying locomotives; lantern prows',
    }),
    ga('SP12-028', 'Sekiro 2019 - FromSoftware Shinobi Deflect', {
      look: 'FromSoftware Sekiro: Shadows Die Twice (2019) look: third-person shinobi action in Sengoku Japan, temple rooftops, falling snow and autumn leaves, deflection sparks and grappling lines.',
      subject:
        'render people as grounded realistic Sengoku warriors, monks and shinobi in weathered armor and robes.',
      color: 'Autumn red, temple ash grey, snow white and spark orange.',
      light: 'Diffuse overcast mountain light with bright deflection sparks.',
      texture: 'Realistic weathered wood, stone, cloth and armor.',
      camera: 'Third-person lock-on duel view on rooftops.',
      mood: 'tense deadly duel',
      render: 'Authentic modern third-person action screen.',
      key: 'Sekiro deflection sparks; temple rooftops; shinobi duel',
      avoid: ['a one-armed shinobi with a prosthetic arm'],
    }),
    ga('SP12-044', 'Persona 5 2016 - Atlus Red-Black Phantom Heist', {
      look: 'Atlus Persona 5 (2016) look: stylized anime cel 3D with a bold red, black and white graphic identity, torn paper shapes, halftone and theatrical palaces for heists.',
      subject:
        'render people as stylish cel-shaded anime characters with masks and dynamic heist poses.',
      color: 'Bold red, black and white only.',
      light: 'Dramatic theatrical light with sharp black shadows.',
      texture: 'Cel shading with halftone, torn paper and graphic shapes.',
      camera: 'Dynamic tilted angles through palace interiors.',
      mood: 'stylish rebellious heist',
      render: 'Authentic stylized anime JRPG screen.',
      key: 'Persona 5 red and black; masked thieves; graphic flair',
      avoid: [
        'a black-haired thief in a long black coat and white mask',
        'a cat with a yellow scarf',
      ],
    }),
    ga('SP12-053', 'The Witcher 3 2015 - CD Projekt Bog Hunt', {
      look: 'CD Projekt Red The Witcher 3: Wild Hunt (2015) look: realistic dark Slavic fantasy, misty bogs and wet villages, monster contracts, muddy browns and eerie folklore.',
      subject:
        'render people as grounded Slavic peasants, hunters and folklore creatures in worn clothing and armor.',
      color: 'Bog green, muddy brown, grey fog and pale folklore light.',
      light: 'Diffuse misty light with lantern glow and eerie hues.',
      texture: 'Realistic mud, wet wood, leather and moss.',
      camera: 'Third-person over-the-shoulder view in wet landscapes.',
      mood: 'eerie folkloric dread',
      render: 'Authentic mid-2010s open-world RPG screen.',
      key: 'Witcher 3 Slavic bog; monster contracts; misty folklore',
      avoid: ['a white-haired hunter with two swords and cat eyes', 'three crones of a bog'],
      briefs: [
        'Wading through a misty bog at the edge of a wet village, an original monster hunter with a lantern pole faces a drowned miller who has risen from the millpond as a shape of reeds, water and grinding stones. No readable text or logo.',
        keep('SP12-053')[1],
        keep('SP12-053')[2],
      ],
    }),
    ga('SP12-055', 'The Witness 2016 - Thekla Saturated Puzzle Island', {
      look: 'Thekla The Witness (2016) look: first-person puzzle island in saturated painterly color, simplified shapes, glowing line puzzle panels and silent monumental nature.',
      subject:
        'render every subject in clean simplified painterly shapes, seen from first person on a silent island.',
      color: 'Saturated orchid pink, grass green, sky blue and warm stone.',
      light: 'Bright clean sunlight with soft painterly shading.',
      texture: 'Simplified smooth shapes without grime.',
      camera: 'First-person view facing puzzle panels.',
      mood: 'quiet contemplative insight',
      render: 'Authentic painterly first-person puzzle screen.',
      key: 'The Witness saturated island; line puzzles; simplified shapes',
    }),
    ga('SP12-061', 'Okami 2006 - Clover Sumi-e Celestial Brush', {
      look: 'Clover Studio Okami (2006) look: cel-shaded sumi-e ink painting in motion, rice paper filter, bold brush outlines, Japanese folklore and celestial brush strokes across the sky.',
      subject:
        'render people and creatures as sumi-e ink figures with bold brush outlines and flowing painted forms.',
      color: 'Rice paper cream, jade green, cherry pink and ink black.',
      light: 'Soft painted daylight with glowing celestial strokes.',
      texture: 'Sumi-e brush outlines on rice paper texture.',
      camera: 'Third-person view across painted landscapes.',
      mood: 'divine folkloric wonder',
      render: 'Authentic PS2 ink-painted action screen.',
      key: 'Okami sumi-e; rice paper; celestial brush strokes',
      avoid: ['a white wolf with red markings and a disc on its back'],
      briefs: [
        'Painting a stroke across the sky with a celestial brush, an original white hare spirit makes the sun rise over a jade volcano shrine, ink-wash petals bursting from every step it takes. No readable text or logo.',
        'In an ink-wash painted village, a divine fox spirit tries to restore a withered tree with a brush stroke and accidentally paints a moustache on the moon. No readable text or logo.',
        keep('SP12-061')[2],
      ],
    }),
    ga('SP12-070', 'Breath of the Wild 2017 - Nintendo Painterly Open Air', {
      look: 'Nintendo The Legend of Zelda: Breath of the Wild (2017) look: soft painterly cel-shaded open air, watercolor-like grass, wind-blown plains, ancient shrines and gliding over vast landscapes.',
      subject:
        'render people as soft cel-shaded adventurers with simple shapes and painterly shading.',
      color: 'Soft grass green, sky blue, sunset gold and stone grey.',
      light: 'Soft open-air light with painterly haze.',
      texture: 'Painterly cel shading with watercolor-like grass.',
      camera: 'Third-person view across a vast open landscape.',
      mood: 'free open-air adventure',
      render: 'Authentic Switch painterly open-world screen.',
      key: 'BotW painterly cel; open plains; ancient shrines',
      avoid: ['a green-tunic elf hero', 'one-eyed spider guardian machines', 'blue Sheikah glyphs'],
      briefs: [
        'Drawing a bow in slow motion while leaping off a cliff shrine, an original ranger lines up a shot at a giant stone boar whose moss-covered back is lined with glowing runes, all in soft painterly cel light. No readable text or logo.',
        keep('SP12-070')[1],
        'On a quiet open plain at dusk, an ancient stone turtle the size of a hill lies overgrown with grass, and a small shrine door on its shell glows once as the player passes. No readable text or logo.',
      ],
    }),
    ga('SP12-109', 'Genshin Impact 2020 - miHoYo Anime Sky Isles', {
      look: 'miHoYo Genshin Impact (2020) look: bright anime cel-shaded open world, floating islands with waterfalls, gliding with wings, elemental particle effects and clean saturated skies.',
      subject:
        'render people as bright anime cel-shaded adventurers with detailed outfits and glowing elemental effects.',
      color: 'Saturated sky blue, grass green, gold and elemental colors.',
      light: 'Bright clean anime daylight with soft rim light.',
      texture: 'Clean anime cel shading on stylized 3D.',
      camera: 'Third-person gliding view over islands.',
      mood: 'bright heroic wonder',
      render: 'Authentic modern anime open-world screen.',
      key: 'Genshin anime cel; floating isles; gliding; elements',
      avoid: ['existing Genshin characters', 'a floating fairy companion in white'],
    }),
    ga('SP12-110', 'The Talos Principle 2014 - Croteam Ruin Puzzle', {
      look: 'Croteam The Talos Principle (2014) look: first-person philosophical puzzle ruins, photoreal ancient stone, beams of light and laser connectors, sealed doors and quiet sunlit decay.',
      subject:
        'render every subject as part of a first-person puzzle space of beams, pedestals and sealed stone doors.',
      color: 'Warm sunlit stone, cool shadow and colored beam light.',
      light: 'Sunlit ruins with clean colored light beams.',
      texture: 'Photoreal weathered stone and brushed metal devices.',
      camera: 'First-person view facing puzzle devices.',
      mood: 'serene philosophical puzzling',
      render: 'Authentic first-person puzzle screen.',
      key: 'Talos Principle ruins; light beams; sealed doors',
    }),
    ga('SP12-111', 'Final Fantasy X 2001 - Square Aeon Summon', {
      look: 'Square Final Fantasy X (2001) look: PS2 JRPG summoning cutscenes, glowing glyph circles, huge aeon beasts rising in bursts of light, detailed anime-realist characters and pyreflies.',
      subject:
        'render people as detailed anime-realist PS2 JRPG characters in ornate summoner robes.',
      color: 'Mystic blue, summon gold and pyrefly green.',
      light: 'Bursting summon light and glowing glyphs.',
      texture: 'PS2 CG-cutscene polish with glowing particles.',
      camera: 'Low cinematic cutscene view of rising beasts.',
      mood: 'sacred grand spectacle',
      render: 'Authentic PS2 JRPG cutscene screen.',
      key: 'FFX summon cutscene; glyph circle; rising aeon',
      avoid: ['existing Final Fantasy summons'],
    }),
    ga('SP12-112', 'Spelunky 2012 - Mossmouth Pixel Temple', {
      look: 'Mossmouth Spelunky (2012) look: cartoon side-view cave-diving roguelike, chunky hand-drawn sprites, golden idols, boulder traps, spikes and dark jungle temples.',
      subject: 'render people as chunky cartoon explorers with round noses and pith helmets.',
      color: 'Temple ochre, jungle green, gold and dark earth.',
      light: 'Dark caves lit by torches and glowing gold.',
      texture: 'Chunky hand-drawn cartoon tiles.',
      camera: 'Side-view roguelike cave view.',
      mood: 'greedy perilous fun',
      render: 'Authentic cartoon roguelike screen.',
      key: 'Spelunky idol; boulder traps; cartoon caves',
    }),
    ga('SP12-113', 'Soul Reaver 1999 - Crystal Dynamics Realm Shift', {
      look: 'Crystal Dynamics Legacy of Kain: Soul Reaver (1999) look: gothic PS1-era 3D where the material realm twists into a warped blue-green spectral realm, bending architecture and ghostly creatures.',
      subject:
        'render people as gaunt gothic figures shifting between a solid world and a warped spectral version.',
      color: 'Material earth tones against spectral blue-green.',
      light: 'Dim gothic light shifting into sickly spectral glow.',
      texture: 'Low-poly gothic stone with warped spectral geometry.',
      camera: 'Third-person view mid realm shift.',
      mood: 'gothic spectral unease',
      render: 'Authentic late-nineties gothic 3D screen.',
      key: 'Soul Reaver realm shift; warped geometry; spectral blue',
      avoid: ['a blue-skinned wraith with a tattered cape and claws'],
    }),
    ga('SP12-114', 'Abzu 2016 - Giant Squid Luminous Dive', {
      look: 'Giant Squid Abzu (2016) look: vivid underwater exploration with luminous schools of fish, clean stylized shapes, sunlit god rays, coral and ancient sunken temples.',
      subject: 'render people as small stylized divers moving among vast shoals of fish.',
      color: 'Luminous turquoise, coral orange and deep blue.',
      light: 'Sunlit god rays through clear water.',
      texture: 'Smooth stylized shapes without grime.',
      camera: 'Third-person swimming view.',
      mood: 'meditative oceanic awe',
      render: 'Authentic stylized underwater screen.',
      key: 'Abzu luminous shoals; god rays; sunken temples',
    }),
    ga('SP12-115', 'Sky Children of the Light 2019 - thatgamecompany Cape Glide', {
      look: 'thatgamecompany Sky: Children of the Light (2019) look: soft glowing cloud kingdoms, children in capes gliding on wind, candle light, luminous spirits and floating temples.',
      subject: 'render people as small soft figures in glowing capes gliding on the wind.',
      color: 'Soft peach, cloud white, dusk lilac and candle gold.',
      light: 'Soft glowing haze with warm candle light.',
      texture: 'Soft stylized shapes with glow and haze.',
      camera: 'Wide third-person view over clouds.',
      mood: 'gentle luminous wonder',
      render: 'Authentic soft stylized mobile screen.',
      key: 'Sky capes; cloud kingdoms; candle glow',
    }),
    ga('SP12-116', 'Ori and the Blind Forest 2015 - Moon Studios Luminous Painted', {
      look: 'Moon Studios Ori and the Blind Forest (2015) look: side-view platformer with lush hand-painted layered backgrounds, luminous glowing creatures, bioluminescent flora and dense parallax depth.',
      subject: 'render people and creatures as small glowing figures against lush painted scenery.',
      color: 'Deep teal, glowing cyan and warm amber.',
      light: 'Luminous glow against deep shadows.',
      texture: 'Hand-painted layered backgrounds.',
      camera: 'Side-view platformer with parallax.',
      mood: 'luminous tender wonder',
      render: 'Authentic painted platformer screen.',
      key: 'Ori painted layers; luminous glow; parallax',
      avoid: ['a small white glowing spirit creature with long ears'],
    }),
    ga('SP12-117', 'Ratchet & Clank Rift Apart 2021 - Insomniac Rift Portals', {
      look: 'Insomniac Games Ratchet & Clank: Rift Apart (2021) look: animated-film-quality stylized 3D, glowing purple dimensional rifts tearing open, dense detailed environments and cartoon characters.',
      subject: 'render people as animated-film cartoon characters with expressive faces.',
      color: 'Rift purple, cyan and warm gold.',
      light: 'Glowing rift light with cinematic bounce.',
      texture: 'Animated-film-quality stylized surfaces.',
      camera: 'Third-person action view near a rift.',
      mood: 'zippy dimensional adventure',
      render: 'Authentic PS5 animated-film action screen.',
      key: 'Rift Apart portals; animated-film 3D; purple rifts',
      avoid: ['a furry lombax with a small robot on his back'],
    }),
    ga('SP12-118', 'Gris 2018 - Nomada Watercolor Platforms', {
      look: 'Nomada Studio Gris (2018) look: side-view watercolor platformer with Conrad Roset art, washes of color, elegant thin figures, geometric ruins and flowing dress shapes.',
      subject: 'render people as elegant thin watercolor figures with flowing shapes.',
      color: 'Watercolor washes of silver, blue and rose.',
      light: 'Soft washed light with moon glow.',
      texture: 'Watercolor washes and ink lines.',
      camera: 'Side-view platformer composition.',
      mood: 'quiet grieving beauty',
      render: 'Authentic watercolor platformer screen.',
      key: 'Gris watercolor; Conrad Roset; geometric ruins',
      avoid: ['a blue-haired girl in a flowing dress'],
    }),
  ]),
};

export default spec;
