import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Horror cinema of the 1990s: each preset names its film and director and rebuilds that film's
// production look. Cards stage original adult horror moments.
const T = ['horror-90s', 'horror-cinema'];
const film90 = 'Nineties 35mm film grain, crisp contrast and slightly desaturated print color.';

const spec: Spec = {
  pack: 'pack_27',
  category: '3. Horror Cinema 90s',
  newCategory: { id: 'horror-cinema-90s' },
  updates: {},
  creates: [
    cr('Scream 1996 - Suburban Meta Slasher', 'nineties horror cinema', [...T, 'scream'], {
      look: 'Wes Craven Scream (1996) look: bright suburban houses at night, cordless phones, teen-horror gloss, self-aware staging and sudden violent chaos.',
      subject:
        'stage the subject in glossy suburban homes at night with self-aware slasher staging.',
      color: 'Glossy suburban warm interiors against blue night windows.',
      light: 'Warm kitchen light and cold blue night outside.',
      texture: film90,
      camera: 'Glossy suspense framing with windows and phones.',
      mood: 'self-aware slasher suspense',
      render: 'Glossy nineties teen slasher frame.',
      key: 'Scream suburbia; cordless phones; meta suspense',
      avoid: ['a ghost-face mask with a black hooded robe'],
      briefs: [
        'In a glossy suburban kitchen at night, a film critic in her forties answers a ringing cordless phone while making popcorn, and every window behind her shows the same dark garden with one garden gnome missing. The popcorn keeps popping. No readable text or logo.',
        'A video store clerk shelves horror tapes while explaining the rules of survival to an empty store. The bell on the door rings once. No readable text or logo.',
        'A cordless phone lies on a porch swing ringing in the blue night. Nobody is home. No readable text or logo.',
      ],
    }),
    cr('Ringu 1998 - Cursed Tape Well Dread', 'nineties Japanese horror cinema', [...T, 'ringu'], {
      look: 'Hideo Nakata Ringu (1998) look: cold desaturated Japanese apartments, cursed VHS static, grainy black-and-white tape imagery, rain and slow creeping dread.',
      subject: 'stage the subject in cold desaturated rooms lit by flickering VHS static.',
      color: 'Cold desaturated blue-green and static grey.',
      light: 'Flickering television static and grey rainy light.',
      texture: film90,
      camera: 'Slow still framing and grainy tape inserts.',
      mood: 'cold creeping dread',
      render: 'Cold nineties J-horror frame.',
      key: 'Ringu static; cursed tape; cold desaturation',
      avoid: ['a long-haired girl in white crawling from a well or TV'],
      briefs: [
        'In a cold desaturated apartment, a journalist watches a grainy cursed videotape showing a quiet seaside cliff, and the phone beside her rings at the exact moment the tape ends. Rain streaks the window. No readable text or logo.',
        'An old stone well sits in a misty forest clearing, its lid slightly moved. A single moth rests on the edge. No readable text or logo.',
        'A VHS tape lies on a tatami floor in flickering static light. Its label has been scratched out. No readable text or logo.',
      ],
    }),
    cr(
      'Se7en 1995 - Rain-Soaked Grime Procedural',
      'nineties crime horror cinema',
      [...T, 'se7en'],
      {
        look: 'David Fincher Se7en (1995) look: endless rain, bleach-bypass desaturation, grimy decaying city apartments, flashlight beams and oppressive procedural dread.',
        subject: 'stage the subject in grimy rain-soaked rooms searched by flashlight beams.',
        color: 'Bleach-bypass desaturated greens, browns and sickly yellow.',
        light: 'Flashlight beams through gloom and grey rain light.',
        texture: 'Bleach-bypass silver retention grain and grime.',
        camera: 'Oppressive procedural compositions in cramped rooms.',
        mood: 'oppressive grim dread',
        render: 'Grimy bleach-bypass nineties thriller frame.',
        key: 'Fincher bleach bypass; rain; grime; flashlights',
        briefs: [
          'In a grimy rain-soaked apartment, two tired detectives sweep flashlight beams across walls covered in thousands of neatly pinned dry-cleaning tickets. The rain never stops outside. No readable text or logo.',
          'A detective sits in his car in endless rain eating a cold sandwich while watching an apartment window. The light inside turns on and off. No readable text or logo.',
          'A single sealed cardboard box sits in a desert field under a hard sky. Everyone is looking at it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Silence of the Lambs 1991 - Direct-Gaze Interrogation',
      'nineties thriller cinema',
      [...T, 'silence-lambs'],
      {
        look: 'Jonathan Demme The Silence of the Lambs (1991) look: characters staring directly into the lens, stone basement cells, cold institutional corridors and intense psychological duels.',
        subject:
          'stage the subject in direct-to-camera close-ups inside cold institutional spaces.',
        color: 'Cold institutional greys and dim amber.',
        light: 'Harsh institutional light and deep shadow.',
        texture: film90,
        camera: 'Direct gaze into the lens and tight close-ups.',
        mood: 'intense psychological duel',
        render: 'Intense nineties psychological thriller frame.',
        key: 'Demme direct gaze; institutional cells; psychological duel',
        avoid: ['a man in a restraint face mask'],
        briefs: [
          'In a stone basement cell block, a calm prison librarian stares directly into the lens as she slides a book through the glass slot to someone unseen. The corridor lights hum behind her. No readable text or logo.',
          'A trainee investigator jogs through a misty forest training course at dawn. She stops when a phone rings in the trees. No readable text or logo.',
          'A single moth rests on a cold glass partition in a dim corridor. The chair behind it is empty. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Cure 1997 - Kurosawa Clinical Stillness',
      'nineties Japanese horror cinema',
      [...T, 'cure'],
      {
        look: 'Kiyoshi Kurosawa Cure (1997) look: long static wide takes, empty institutional rooms, washed-out daylight, flickering fluorescents and quiet hypnotic menace.',
        subject: 'stage the subject in long static wide takes of empty washed-out rooms.',
        color: 'Washed-out grey-green and pale daylight.',
        light: 'Flickering fluorescents and flat daylight.',
        texture: film90,
        camera: 'Long static wide takes with distant figures.',
        mood: 'quiet hypnotic menace',
        render: 'Minimal nineties Japanese horror frame.',
        key: 'Kurosawa long takes; empty rooms; hypnotic menace',
        briefs: [
          'In a long static wide shot of an empty laundromat, a detective watches a stranger slowly flick a lighter while every washing machine stops spinning at once. The fluorescent tube above flickers. No readable text or logo.',
          'An empty hospital corridor stretches under flickering light as a man in a raincoat walks away without sound. Water drips from his coat. No readable text or logo.',
          'A glass of water sits on a table, its surface trembling in a perfect spiral. No one is in the room. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Audition 1999 - Miike Quiet-to-Cruel',
      'nineties Japanese horror cinema',
      [...T, 'audition'],
      {
        look: 'Takashi Miike Audition (1999) look: quiet muted romance slowly turning cruel, empty sparse apartments, a single sack in the corner and sudden shocking stillness.',
        subject: 'stage the subject in quiet sparse rooms with an unsettling stillness.',
        color: 'Muted beige, pale grey and one dark accent.',
        light: 'Soft flat daylight in empty rooms.',
        texture: film90,
        camera: 'Quiet static compositions with a single odd object.',
        mood: 'quiet mounting cruelty',
        render: 'Quiet unsettling nineties Japanese horror frame.',
        key: 'Miike quiet cruelty; sparse rooms; single sack',
        briefs: [
          'In a sparse empty apartment, a shy widower sits across from a quiet woman at a low table while a large canvas sack in the corner slowly shifts on its own. The phone on the floor is ringing. No readable text or logo.',
          'In a rented casting room, one empty chair faces a long table of nervous producers holding résumés. The chair is still warm, and nobody saw anyone leave. No readable text or logo.',
          'A single piano wire rests coiled on a clean white table. The window light is soft. No readable text or logo.',
        ],
      },
    ),
    cr('Candyman 1992 - Urban Legend Hive', 'nineties horror cinema', [...T, 'candyman'], {
      look: 'Bernard Rose Candyman (1992) look: Chicago housing projects, graffiti murals of giant faces, honey and bees, gothic Philip Glass choral grandeur and urban legend.',
      subject: 'stage the subject in graffiti-covered urban spaces with bees and honey-gold light.',
      color: 'Honey gold, graffiti colors and concrete grey.',
      light: 'Golden shafts of light through broken walls.',
      texture: film90,
      camera: 'Gothic compositions with giant murals.',
      mood: 'haunting urban legend',
      render: 'Gothic nineties urban horror frame.',
      key: 'Candyman murals; bees and honey; urban legend',
      avoid: ['a tall man in a fur-collared coat with a hook hand'],
      briefs: [
        'A folklore student photographs a giant graffiti mural of a gaping face in an abandoned apartment block while honey-gold light and a slow cloud of bees drift through the broken wall. Her camera flash reveals a doorway inside the painted mouth. No readable text or logo.',
        'A bathroom mirror glows in golden light as a woman whispers into it. A single bee lands on the glass. No readable text or logo.',
        'Honey drips slowly from a cracked ceiling in an empty concrete stairwell, pooling on the steps in golden light. The walls around it are humming softly. No readable text or logo.',
      ],
    }),
    cr(
      'In the Mouth of Madness 1994 - Lovecraftian Small Town',
      'nineties horror cinema',
      [...T, 'mouth-madness'],
      {
        look: 'John Carpenter In the Mouth of Madness (1994) look: Lovecraftian New England small town, pulp horror novel covers, cosmic creatures in shadows and reality unraveling.',
        subject: 'stage the subject in an eerie New England small town where reality unravels.',
        color: 'Autumn New England tones and cosmic blue.',
        light: 'Eerie overcast and cosmic glows.',
        texture: film90,
        camera: 'Anamorphic unraveling-reality compositions.',
        mood: 'cosmic unraveling dread',
        render: 'Anamorphic nineties cosmic horror frame.',
        key: 'Mouth of Madness Lovecraftian town; unraveling reality',
        briefs: [
          'In an eerie New England town, an insurance investigator stops his car on a covered bridge as the road behind him folds up like a page of a pulp novel. The painted church steeple leans toward him. No readable text or logo.',
          'A bookstore window displays a novel whose cover changes each time a customer blinks. The shopkeeper is smiling. No readable text or logo.',
          'An old church door breathes in and out in a quiet New England square at dusk. Crows line every rooftop, all facing the same way. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Event Horizon 1997 - Gothic Starship Hell',
      'nineties science fiction horror cinema',
      [...T, 'event-horizon'],
      {
        look: 'Paul W. S. Anderson Event Horizon (1997) look: gothic cathedral-like starship interiors, spinning gravity drive rings, blue-black space and hellish red flashes.',
        subject: 'stage the subject in gothic cathedral starship interiors with spinning rings.',
        color: 'Blue-black steel with hellish red flashes.',
        light: 'Cold blue emergency light and red flashes.',
        texture: film90,
        camera: 'Gothic vertical starship compositions.',
        mood: 'gothic cosmic hell',
        render: 'Gothic nineties sci-fi horror frame.',
        key: 'Gothic starship; spinning rings; hellish red',
        briefs: [
          'Inside a gothic cathedral-like starship corridor lined with spikes, a rescue engineer floats toward a spinning ring of glowing machinery as red flashes reveal words scratched into her helmet from inside. The ring whispers. No readable text or logo.',
          'A captain watches a flooded medical bay where the water floats upward in blue light. His reflection is not blinking. No readable text or logo.',
          'A spinning gravity ring glows in the dark heart of a derelict ship. Nothing is powering it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Jacob’s Ladder 1990 - Hallucinatory Subway Dread',
      'nineties psychological horror cinema',
      [...T, 'jacobs-ladder'],
      {
        look: 'Adrian Lyne Jacob’s Ladder (1990) look: gritty New York subways, grainy desaturated film, vibrating headshake faces and hallucinatory hospital corridors.',
        subject:
          'stage the subject in gritty subways and hospital corridors with vibrating blurred faces.',
        color: 'Desaturated grimy greens and grey.',
        light: 'Flickering subway and hospital light.',
        texture: 'Grainy desaturated film and motion blur.',
        camera: 'Hallucinatory close-ups with vibrating blur.',
        mood: 'hallucinatory paranoid dread',
        render: 'Grainy nineties psychological horror frame.',
        key: 'Jacob’s Ladder vibrating faces; subways; hallucination',
        briefs: [
          'On a gritty late-night subway, a postal worker sits across from a sleeping passenger whose head suddenly vibrates into a blur while the lights flicker between stations. The train never stops. No readable text or logo.',
          'A hospital gurney rolls down a corridor of flickering lights past rooms full of strange shapes. The floor is wet. No readable text or logo.',
          'A single subway car idles in an empty tunnel with its doors open. Something breathes inside. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Sixth Sense 1999 - Cold Breath Red Accent',
      'nineties supernatural cinema',
      [...T, 'sixth-sense'],
      {
        look: 'M. Night Shyamalan The Sixth Sense (1999) look: muted Philadelphia autumn, visible cold breath, deliberate slow framing and single red objects marking the supernatural.',
        subject:
          'stage the subject in muted autumn rooms with cold breath and a single red object.',
        color: 'Muted autumn browns and greys with one red accent.',
        light: 'Soft muted daylight and cold interiors.',
        texture: film90,
        camera: 'Slow deliberate compositions.',
        mood: 'melancholy supernatural quiet',
        render: 'Muted nineties supernatural drama frame.',
        key: 'Sixth Sense red accent; cold breath; muted autumn',
        avoid: ['a boy whispering in a hospital bed'],
        briefs: [
          'In a muted autumn kitchen, a psychologist’s breath suddenly turns visible as every cupboard door stands open at once, and a single red doorknob glows among the grey. Her tea is still steaming. No readable text or logo.',
          'A church in muted light is empty except for a red balloon tied to a pew. The candles flicker in a cold draft. No readable text or logo.',
          'A single red door stands at the end of a grey basement. Frost creeps from under it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Sleepy Hollow 1999 - Burton Monochrome Gothic',
      'nineties gothic horror cinema',
      [...T, 'sleepy-hollow'],
      {
        look: 'Tim Burton Sleepy Hollow (1999) look: near-monochrome desaturated gothic village, twisted trees, misty forests, blood-red accents and storybook horror.',
        subject: 'stage the subject in near-monochrome misty gothic villages with twisted trees.',
        color: 'Near-monochrome grey-blue with vivid red accents.',
        light: 'Misty diffused light and lanterns.',
        texture: film90,
        camera: 'Storybook gothic compositions.',
        mood: 'storybook gothic dread',
        render: 'Desaturated nineties gothic horror frame.',
        key: 'Burton desaturated gothic; twisted trees; red accents',
        avoid: ['a headless horseman on a black horse'],
        briefs: [
          'In a near-monochrome misty village, a nervous town clerk rides a mule past a gnarled twisted tree whose roots hold a glowing red lantern. The fog closes behind him. No readable text or logo.',
          'A covered bridge glows in grey mist as hooves echo from nowhere and the hanging lanterns sway. The toll keeper hides behind his little window. No readable text or logo.',
          'A single red apple lies on a misty gothic path. The fog is creeping toward it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Cronos 1993 - Del Toro Clockwork Amber',
      'nineties Mexican horror cinema',
      [...T, 'cronos'],
      {
        look: 'Guillermo del Toro Cronos (1993) look: warm amber antique shops, golden clockwork insect devices, gothic Catholic imagery and tender horror.',
        subject: 'stage the subject in amber antique shops with golden clockwork devices.',
        color: 'Warm amber, gold and deep shadow.',
        light: 'Warm amber lamplight through dust.',
        texture: film90,
        camera: 'Intimate antique shop compositions.',
        mood: 'tender gothic horror',
        render: 'Warm amber nineties gothic horror frame.',
        key: 'Del Toro amber; clockwork devices; antiques',
        briefs: [
          'In a warm amber antique shop, an elderly clockmaker opens a statue of an angel and finds a golden clockwork beetle ticking inside, its legs slowly unfolding toward his hand. Dust drifts in the lamplight. No readable text or logo.',
          'A grandmother polishes silver in an antique shop as the clocks all stop at once. Her granddaughter watches. No readable text or logo.',
          'A tiny golden clockwork device ticks on a velvet cloth. The wood beneath it is warm. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Cemetery Man 1994 - Romantic Gothic Absurdity',
      'nineties Italian horror cinema',
      [...T, 'cemetery-man'],
      {
        look: 'Michele Soavi Cemetery Man (Dellamorte Dellamore, 1994) look: romantic misty Italian cemetery, ossuaries, absurd dark comedy and dreamy gothic beauty.',
        subject: 'stage the subject in romantic misty cemeteries with absurd dark comedy.',
        color: 'Misty blue, candle gold and bone white.',
        light: 'Misty moonlight and candles.',
        texture: film90,
        camera: 'Romantic gothic compositions.',
        mood: 'romantic absurd gothic',
        render: 'Dreamy nineties Italian gothic frame.',
        key: 'Cemetery Man romance; ossuary; absurd gothic',
        briefs: [
          'In a romantic misty Italian cemetery, a lonely caretaker eats his dinner on a tomb while bored skeletons in the ossuary behind him play cards by candlelight. A widow in black walks toward him through the fog. No readable text or logo.',
          'A caretaker digs a grave while a talking skull gives advice on love. The moon is huge. No readable text or logo.',
          'A single rose lies on a mossy tomb in blue mist. The candles never go out. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Braindead 1992 - Splatstick Suburban Excess',
      'nineties horror comedy cinema',
      [...T, 'braindead'],
      {
        look: 'Peter Jackson Braindead (1992) look: fifties New Zealand suburban house, absurd splatstick comedy, practical effects excess and garish domestic chaos.',
        subject: 'stage the subject in fifties suburban houses overrun by absurd splatstick chaos.',
        color: 'Garish fifties pastels and splatter red.',
        light: 'Bright domestic light.',
        texture: film90,
        camera: 'Wide-angle comedic compositions.',
        mood: 'gleeful absurd excess',
        render: 'Garish nineties splatstick frame.',
        key: 'Braindead splatstick; fifties suburbia; absurd excess',
        briefs: [
          'In a garish fifties suburban dining room, a meek son serves custard to his strict mother’s bridge club while the custard slowly crawls off the plates toward the guests. The wallpaper is very floral. No readable text or logo.',
          'A priest performs kung fu in a suburban graveyard at night. The neighbors watch from their windows. No readable text or logo.',
          'A lawnmower sits in a pastel garden shed, its blades gleaming. The garden is suspiciously quiet. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Bram Stoker’s Dracula 1992 - In-Camera Opulent Gothic',
      'nineties gothic cinema',
      [...T, 'coppola-dracula'],
      {
        look: 'Francis Ford Coppola Bram Stoker’s Dracula (1992) look: in-camera practical effects, shadows moving independently, Eiko Ishioka’s opulent costumes, red and gold excess and theatrical gothic romance.',
        subject:
          'stage the subject in opulent gothic rooms with theatrical costumes and independent shadows.',
        color: 'Deep crimson, gold and black.',
        light: 'Theatrical candlelight with shadows moving independently.',
        texture: 'In-camera double exposures and film grain.',
        camera: 'Theatrical in-camera compositions.',
        mood: 'opulent gothic romance',
        render: 'Opulent nineties gothic romance frame.',
        key: 'Coppola in-camera effects; Ishioka costumes; red and gold',
        avoid: ['an armored red count with a long wig', 'existing film characters'],
        briefs: [
          'In an opulent castle hall lit by candles, a real estate clerk shakes hands with an elegant host in a sweeping gold-embroidered robe while their shadows on the wall do something completely different. The dinner table is set for one. No readable text or logo.',
          'A woman in a crimson gown dances with an invisible partner in a ballroom. Her reflection dances faster. No readable text or logo.',
          'A single black candle burns inside a circle of chalk on an old wooden floor. Its wax drips upward toward the ceiling in slow glossy threads. No readable text or logo.',
        ],
      },
    ),
    cr('The Craft 1996 - Nineties Teen Witchcraft', 'nineties horror cinema', [...T, 'the-craft'], {
      look: 'Andrew Fleming The Craft (1996) look: nineties grunge-goth fashion, candlelit bedroom rituals, beach invocations and teen witch glamour.',
      subject: 'stage the subject in grunge-goth candlelit rituals and beach invocations.',
      color: 'Goth black, candle gold and ocean grey.',
      light: 'Candlelight and stormy beach light.',
      texture: film90,
      camera: 'Stylish ritual circle compositions.',
      mood: 'stylish dark witchcraft',
      render: 'Stylish nineties witchcraft frame.',
      key: 'Grunge goth; candlelit rituals; beach invocation',
      briefs: [
        'Four grunge-goth adult women in plaid and black lace sit in a candlelit circle on a bedroom floor as their joined hands make the candle flames rise into a spiral. Rain lashes the window. No readable text or logo.',
        'A group of witches stands on a stormy beach as the tide suddenly withdraws. Fish flop on the sand. No readable text or logo.',
        'A single black candle burns in a circle of chalk on a wooden floor. The wax drips upward. No readable text or logo.',
      ],
    }),
    cr(
      'The Blair Witch Project 1999 - Lost Woods Footage',
      'nineties found footage horror',
      [...T, 'blair-witch'],
      {
        look: 'The Blair Witch Project (1999) look: shaky Hi8 video and 16mm black-and-white, night forest flashlight, stick figures in trees and panicked documentary realism.',
        subject: 'stage the subject in shaky handheld night forest footage lit by one flashlight.',
        color: 'Hi8 video color and grainy black and white.',
        light: 'Single flashlight beam in pitch-black woods.',
        texture: 'Hi8 video noise and 16mm grain.',
        camera: 'Shaky handheld documentary framing.',
        mood: 'panicked lost dread',
        render: 'Raw found-footage frame.',
        key: 'Blair Witch Hi8; flashlight woods; stick figures',
        avoid: ['a person standing in a corner facing the wall'],
        briefs: [
          'In shaky Hi8 night footage, a birdwatching club leader shines her flashlight on dozens of little bundles of twigs hanging from the trees around her tent. Her companions’ voices are getting farther away. No readable text or logo.',
          'Grainy black-and-white footage shows a map blowing away into the dark forest. Someone is laughing nervously. No readable text or logo.',
          'A flashlight lies on the forest floor pointing at a pile of stones. The camera is still recording. No readable text or logo.',
        ],
      },
    ),
    cr('Nadja 1994 - Pixelvision Vampire Noir', 'nineties art horror cinema', [...T, 'nadja'], {
      look: 'Michael Almereyda Nadja (1994) look: black-and-white New York vampire noir intercut with blurry toy Pixelvision camera footage, cool indie art-house mood.',
      subject: 'stage the subject in black-and-white New York noir with blurry toy-camera inserts.',
      color: 'Black and white with blurry Pixelvision grey.',
      light: 'Noir night light.',
      texture: 'Grainy black and white and blocky toy-camera blur.',
      camera: 'Cool indie noir framing.',
      mood: 'cool indie vampire noir',
      render: 'Black-and-white indie vampire frame.',
      key: 'Nadja Pixelvision; black-and-white noir; indie vampires',
      briefs: [
        'In black-and-white New York at night, a pale elegant woman in sunglasses smokes on a fire escape while a blurry toy-camera insert shows her reflection missing from the window. A subway rumbles below. No readable text or logo.',
        'A vampire hunter buys coffee at an all-night diner in grainy black and white. The waitress stares at his garlic necklace. No readable text or logo.',
        'A single typewriter sits alone on a desk by a snowy farmhouse window. One blank sheet waits in it while the snow piles against the glass. No readable text or logo.',
      ],
    }),
    cr(
      'Misery 1990 - Snowbound Farmhouse Captivity',
      'nineties thriller cinema',
      [...T, 'misery'],
      {
        look: 'Rob Reiner Misery (1990) look: snowbound isolated farmhouse, cozy country kitsch, low-angle looming caretaker and claustrophobic captivity.',
        subject: 'stage the subject in cozy snowbound farmhouses with looming low-angle menace.',
        color: 'Cozy country kitsch tones and snow white.',
        light: 'Soft winter light and warm lamps.',
        texture: film90,
        camera: 'Low looming angles and cozy interiors.',
        mood: 'cozy claustrophobic menace',
        render: 'Tense nineties captivity thriller frame.',
        key: 'Misery snowbound farmhouse; country kitsch; looming menace',
        avoid: ['a sledgehammer beside a bed'],
        briefs: [
          'In a cozy snowbound farmhouse full of ceramic pigs, a bedridden novelist looks up from his typewriter as his cheerful nurse looms over him from a low angle holding a tray of soup. The snow keeps falling. No readable text or logo.',
          'A pet pig wanders through a kitsch farmhouse kitchen while a radio plays country music. The phone line has been cut. No readable text or logo.',
          'A typewriter sits alone on a desk by a snowy window. A single sheet of paper waits in it. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
