import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Comic covers: cover traditions named after their artists, publishers and eras. Cards invent
// original series and heroes with exact titles and issue numbers.
const T = ['comic-cover'];
const P = { requestedText: true } as const;

const spec: Spec = {
  pack: 'pack_26',
  category: '5. Comic Covers',
  newCategory: { id: 'comic-covers' },
  updates: {},
  creates: [
    cr('Golden Age Superhero Comic Cover', 'forties comic cover', [...T, 'golden-age'], {
      ...P,
      look: 'Golden Age comic cover look of the forties: bold flat primary colors, heroic poses punching villains, dramatic diagonal action, masthead logo, price box and cheap newsprint.',
      subject:
        'draw the subject as a bold heroic figure in dramatic diagonal action with flat primary colors.',
      color: 'Flat primary red, yellow and blue with black line.',
      light: 'Flat printed comic light.',
      texture: 'Cheap yellowed newsprint with Ben-Day dots and misregistration.',
      camera: 'Dramatic diagonal action below a big masthead.',
      mood: 'bold wartime heroics',
      render: 'Vintage Golden Age comic cover.',
      key: 'Golden Age flat primaries; heroic diagonals; newsprint; masthead',
      avoid: ['existing superhero emblems'],
      briefs: [
        'A caped librarian hero punches a mechanical gorilla off a speeding train in bold flat primary colors on yellowed newsprint, cover of the invented comic "THE LIBRARIAN" issue 1 with masthead and price box set exact.',
        'A masked milkman hero leaps between rooftops hurling glass bottles at a gang of goons, forties comic titled "MIDNIGHT MILK" issue 7 with a bold masthead.',
        'A single giant fist bursts through a brick wall on a faded newsprint cover titled "POW PATROL" issue 3 with a ten-cent price box.',
      ],
    }),
    cr('Jack Kirby - Cosmic Kirby Crackle Cover', 'comic cover art', [...T, 'kirby'], {
      ...P,
      look: 'Jack Kirby cover look: blocky monumental heroes, cosmic energy drawn as black Kirby crackle dots, colossal machinery, foreshortened fists and explosive cosmic scale.',
      subject:
        'draw the subject with blocky monumental anatomy, crackling cosmic energy and colossal machinery.',
      color: 'Bold cosmic reds, blues and yellows with black crackle.',
      light: 'Crackling cosmic energy light.',
      texture: 'Bold ink with Kirby dots and flat color.',
      camera: 'Foreshortened explosive cosmic compositions.',
      mood: 'titanic cosmic awe',
      render: 'Monumental cosmic comic cover.',
      key: 'Kirby crackle; blocky heroes; cosmic machinery; foreshortening',
      avoid: ['existing cosmic heroes'],
      briefs: [
        'A blocky cosmic grandmother in armored robes lifts a planet-sized teapot as black Kirby crackle erupts around colossal machinery, cover of the invented comic "THE ETERNAL KETTLE" issue 1 set exact.',
        'A monumental space mechanic punches through a galaxy of crackling gears on the cover of the invented comic "COSMIC WRENCH" issue 4.',
        'A single giant cosmic helmet floats in crackling black dots over a burning star, cover titled "THE WATCHER’S HAT" issue 12.',
      ],
    }),
    cr('Graham Ingels - EC Horror Comic Cover', 'fifties horror comic cover', [...T, 'ec-horror'], {
      ...P,
      look: 'Graham Ingels EC horror comic cover look of the fifties: dripping rotting ghouls, dense wiggly ink lines, a grinning horror host, lurid colors and moralistic macabre humor.',
      subject: 'draw the subject with dripping wiggly ink horror and lurid color.',
      color: 'Lurid green, purple and yellow with deep black.',
      light: 'Lurid moonlit horror light.',
      texture: 'Dense wiggly ink and newsprint.',
      camera: 'Shocking horror scene below a masthead with a host figure.',
      mood: 'macabre ironic horror',
      render: 'Fifties horror comic cover.',
      key: 'EC horror; dripping ghouls; wiggly ink; lurid color',
      briefs: [
        'A dripping ghoul in a butcher’s apron serves a smiling family a suspicious stew while a grinning horror host peeks from the corner, fifties cover of the invented comic "TALES FROM THE LARDER" issue 22 set exact.',
        'A rotting mail carrier delivers a letter to his own grave on a lurid cover titled "RETURN TO SENDER" issue 9.',
        'A single dripping hand rises from a swamp under a purple moon, cover titled "SWAMP STORIES" issue 5 set exact.',
      ],
    }),
    cr('Silver Age Romance Comic Cover', 'sixties romance comic cover', [...T, 'romance-comic'], {
      ...P,
      look: 'Silver Age romance comic cover look: tearful women with glossy hair, dramatic thought balloons, Ben-Day dots and melodramatic sixties heartbreak.',
      subject: 'draw the subject as a tearful romantic melodrama with Ben-Day dots.',
      color: 'Pastel pink, teal and glossy black hair highlights.',
      light: 'Flat printed pop light.',
      texture: 'Ben-Day dots and clean ink.',
      camera: 'Close tearful faces with speech balloons.',
      mood: 'tearful melodramatic heartbreak',
      render: 'Sixties romance comic cover.',
      key: 'Romance comics; tears; Ben-Day dots; melodrama',
      briefs: [
        'A tearful woman clutches a wilting houseplant while her boyfriend walks away with a cactus, thought balloon reading "HE CHOSE THE CACTUS!" on the cover of the invented comic "HEARTBREAK GARDEN" issue 17 set exact.',
        'A lighthouse keeper weeps into her telescope as a ship sails away on the cover of "TEARS AT SEA" issue 4.',
        'A single broken record lies on a pink floor under a tear-shaped balloon, cover titled "OUR SONG" issue 8.',
      ],
    }),
    cr('Frank Miller - Noir Silhouette Cover', 'noir comic cover', [...T, 'frank-miller'], {
      ...P,
      look: 'Frank Miller noir cover look: stark black and white silhouettes, rain drawn as white slashes, heavy solid blacks, one splash of spot color and hard-boiled attitude.',
      subject: 'render the subject as stark black and white silhouettes with heavy solid blacks.',
      color: 'Black and white with a single spot color.',
      light: 'Stark silhouette light with white rain slashes.',
      texture: 'Heavy brush ink and white negative space.',
      camera: 'Stark noir compositions with tall silhouettes.',
      mood: 'hard-boiled brutal noir',
      render: 'Stark black-and-white noir comic cover.',
      key: 'Frank Miller silhouettes; heavy blacks; spot color; rain slashes',
      avoid: ['existing noir characters'],
      briefs: [
        'A tall silhouette of a retired boxer stands in white slashing rain holding a single spot-color red umbrella in a pure black alley, noir comic cover titled "RED UMBRELLA" issue 1 set exact.',
        'A cab driver’s silhouette leans on her taxi under a single yellow streetlight in stark black and white, cover titled "NIGHT FARE" issue 3.',
        'A single spot-color blue eye stares from a black silhouette, noir cover titled "WITNESS" issue 2.',
      ],
    }),
    cr('Mike Mignola - Blocky Shadow Cover', 'comic cover art', [...T, 'mignola'], {
      ...P,
      look: 'Mike Mignola cover look: blocky angular shapes, massive flat black shadows, limited muted color, gothic folklore monsters and stark graphic simplicity.',
      subject: 'build the subject from blocky angular shapes with massive flat black shadows.',
      color: 'Limited muted reds, ochres and teals with deep black.',
      light: 'Stark light carving blocky shapes out of black.',
      texture: 'Flat ink shapes and flat color.',
      camera: 'Stark graphic compositions with lots of black.',
      mood: 'stark gothic folklore',
      render: 'Stark blocky gothic comic cover.',
      key: 'Mignola black shadows; blocky shapes; muted color; folklore',
      avoid: ['a red demon with a stone right hand'],
      briefs: [
        'A blocky folklore witch made of angular black shadows stands in a ruined chapel with a lantern of muted teal fire, comic cover titled "THE WIDOW OF THE MARSH" issue 1 set exact.',
        'A monstrous frog priest crouches on a gothic altar in massive flat shadows, cover titled "FROG CHAPEL" issue 3.',
        'A single blocky skull glows ochre in a sea of black, comic cover titled "RELIC" issue 6.',
      ],
    }),
    cr('Alex Ross - Painted Photoreal Hero Cover', 'painted comic cover', [...T, 'alex-ross'], {
      ...P,
      look: 'Alex Ross painted cover look: gouache photorealism, heroic figures painted like classical portraits, dramatic sky light and monumental dignity.',
      subject: 'paint the subject as a dignified photoreal heroic figure in gouache.',
      color: 'Rich naturalistic gouache with heroic skies.',
      light: 'Dramatic sky light and warm highlights.',
      texture: 'Gouache painting with photographic realism.',
      camera: 'Monumental heroic portrait composition.',
      mood: 'monumental heroic dignity',
      render: 'Photoreal painted comic cover.',
      key: 'Alex Ross gouache realism; heroic dignity; sky light',
      avoid: ['existing superheroes', 'real person likeness'],
      briefs: [
        'An aging retired superhero in a faded homemade costume sits on a park bench feeding pigeons, painted with photoreal gouache dignity under a golden evening sky, cover titled "GOLDEN YEARS" issue 1 set exact.',
        'A firefighter hero stands on a burning rooftop in painted realism, cover titled "EMBER" issue 2.',
        'A single faded cape hangs on a coat rack in warm gouache light, cover titled "RETIRED" issue 5.',
      ],
    }),
    cr(
      'Bill Sienkiewicz - Mixed-Media Expressionist Cover',
      'comic cover art',
      [...T, 'sienkiewicz'],
      {
        ...P,
        look: 'Bill Sienkiewicz cover look: expressionist mixed media, collage, splattered paint, distorted figures and chaotic psychological intensity.',
        subject: 'render the subject with expressionist mixed media, collage and splattered paint.',
        color: 'Wild expressive colors and splatters.',
        light: 'Chaotic expressive light.',
        texture: 'Collage, splatter, pencil and paint.',
        camera: 'Chaotic expressionist compositions.',
        mood: 'feverish psychological intensity',
        render: 'Expressionist mixed-media comic cover.',
        key: 'Sienkiewicz mixed media; splatter; distortion; intensity',
        briefs: [
          'A psychic accountant’s distorted face explodes into collaged tax forms, splattered paint and scribbled numbers, expressionist comic cover titled "AUDIT" issue 1 set exact.',
          'A jazz pianist dissolves into splattered keys and torn photos on a cover titled "BLUE NOTES" issue 3.',
          'A single collaged eye stares through a storm of paint splatter, cover titled "INSIDE" issue 7.',
        ],
      },
    ),
    cr('Philippe Druillet - Métal Hurlant Cover', 'French sci-fi comic cover', [...T, 'druillet'], {
      ...P,
      look: 'Philippe Druillet and Métal Hurlant cover look: monumental psychedelic science fiction architecture, cosmic cathedrals, ornate baroque machines and vivid seventies color.',
      subject: 'render the subject amid monumental psychedelic cosmic architecture.',
      color: 'Vivid psychedelic cosmic colors.',
      light: 'Cosmic radiant light.',
      texture: 'Dense ornate ink and vivid color.',
      camera: 'Monumental vertical cosmic compositions.',
      mood: 'psychedelic cosmic grandeur',
      render: 'Monumental psychedelic sci-fi cover.',
      key: 'Druillet cosmic cathedrals; baroque machines; psychedelia',
      briefs: [
        'A tiny wanderer stands before a colossal cosmic cathedral built from ornate baroque machinery and glowing stained-glass planets, psychedelic cover of the invented magazine "COSMOS HURLANT" issue 12 set exact.',
        'A baroque starship shaped like an organ pipe cathedral drifts through a vivid nebula on a cover titled "ORGAN OF STARS".',
        'A single ornate cosmic door carved with baroque machinery swings open onto a swirling psychedelic void full of tiny planets, science fiction magazine cover titled "PORTAIL" set exact.',
      ],
    }),
    cr('2000 AD British Sci-Fi Comic Cover', 'British sci-fi comic cover', [...T, '2000ad'], {
      ...P,
      look: '2000 AD British comic cover look: gritty dystopian science fiction, heavy armored lawmen and mutants, sharp detailed ink, punk satire and bold masthead.',
      subject: 'draw the subject with gritty dystopian detail, armor and punk satire.',
      color: 'Gritty dystopian colors with bold accents.',
      light: 'Harsh dystopian light.',
      texture: 'Sharp detailed ink and gritty color.',
      camera: 'Low-angle armored menace compositions.',
      mood: 'gritty satirical dystopia',
      render: 'Gritty British sci-fi comic cover.',
      key: '2000 AD dystopia; armored lawmen; punk satire',
      avoid: ['a helmeted street judge with an eagle shoulder pad'],
      briefs: [
        'A heavily armored dystopian traffic warden issues a parking ticket to a giant mutant snail in a megacity, gritty British sci-fi cover titled "WARDEN" prog 1 with masthead set exact.',
        'A punk mutant grandma rides a hoverbike through a dystopian ruin on a cover titled "MUTANT GRAN".',
        'A single cracked armored visor lies on a grimy megacity street reflecting burning neon towers and a flock of mutant pigeons, British comic cover titled "LAWLESS" set exact.',
      ],
    }),
    cr('Nineties Image Extreme Foil Cover', 'nineties comic cover', [...T, 'nineties-image'], {
      ...P,
      look: 'Nineties Image-era extreme comic cover look: hyper-muscular grimacing heroes, giant guns and pouches, foil and chromium variant finishes, speed lines and excess.',
      subject: 'draw the subject with hyper-muscular excess, pouches, giant guns and grimaces.',
      color: 'Saturated purple, teal and chrome foil.',
      light: 'Explosive rim light and foil shine.',
      texture: 'Chromium foil and heavy ink.',
      camera: 'Extreme low-angle excess compositions.',
      mood: 'extreme nineties excess',
      render: 'Extreme nineties foil variant cover.',
      key: 'Nineties extreme; pouches; giant guns; chrome foil',
      avoid: ['existing nineties heroes'],
      briefs: [
        'A hyper-muscular grimacing grandmother with forty pouches and a giant water gun leaps from an explosion on a chromium foil variant cover titled "GRANDMA PRIME" issue 1 set exact.',
        'A cybernetic mercenary florist aims two giant flower guns on a foil cover titled "BLOOMSHOT" issue 1.',
        'A single gigantic utility pouch glints on a chromium foil variant cover surrounded by explosive speed lines and lens flares, extreme comic titled "POUCH" issue 0 set exact.',
      ],
    }),
    cr(
      'André Franquin - Franco-Belgian Humor Album Cover',
      'bande dessinée album cover',
      [...T, 'franquin'],
      {
        ...P,
        look: 'André Franquin Franco-Belgian humor album look: rubbery lively cartoon line, chaotic comic scenes, expressive animals and clean bright album color.',
        subject: 'draw the subject with rubbery lively cartoon line in chaotic comic action.',
        color: 'Clean bright album colors.',
        light: 'Flat bright comic light.',
        texture: 'Lively ink line and flat color.',
        camera: 'Chaotic comic scene album cover.',
        mood: 'chaotic cheerful comedy',
        render: 'Franco-Belgian humor album cover.',
        key: 'Franquin rubbery line; chaotic comedy; bright album color',
        avoid: ['a spotted long-tailed jungle creature', 'a bellhop reporter'],
        briefs: [
          'A clumsy office clerk’s homemade invention floods the whole office with foam while a gleeful cat surfs on a filing cabinet, Franco-Belgian humor album titled "GASTON’S NEIGHBOR" set exact.',
          'A mailman chases a runaway letter that has sprouted wings across rooftops on an album titled "COURRIER VOLANT".',
          'A single exploding coffee machine sits in a chaotic office on an album titled "PAUSE CAFÉ".',
        ],
      },
    ),
    cr('Dylan Dog Bonelli Fumetti Cover', 'Italian fumetti cover', [...T, 'bonelli'], {
      ...P,
      look: 'Sergio Bonelli Editore fumetti cover look as in Dylan Dog: elegant painted horror covers, detailed realistic ink, eerie gothic scenes and consistent series masthead.',
      subject: 'paint the subject in elegant realistic gothic horror.',
      color: 'Muted gothic colors with eerie accents.',
      light: 'Eerie moody light.',
      texture: 'Detailed realistic ink and painted color.',
      camera: 'Elegant eerie horror compositions.',
      mood: 'elegant gothic horror',
      render: 'Italian fumetti horror cover.',
      key: 'Bonelli fumetti; elegant horror; realistic ink',
      avoid: ['a nightmare investigator in a red shirt and black jacket'],
      briefs: [
        'An elegant nightmare detective in a grey coat stands in a fog-bound London cemetery as a hand of ivy rises behind him, Italian fumetti cover titled "INCUBI DI NEBBIA" number 1 with masthead set exact.',
        'A clockwork doll plays a harpsichord in a candlelit mansion on a fumetti cover titled "LA BAMBOLA".',
        'A single raven perches on a cracked tombstone at dusk while fog creeps through an Italian cemetery, elegant fumetti cover titled "IL CORVO" number 3 with masthead set exact.',
      ],
    }),
    cr('Robert Crumb - Underground Comix Cover', 'underground comix cover', [...T, 'crumb'], {
      ...P,
      look: 'Robert Crumb underground comix look: dense crosshatched cartoon line, rubbery bulbous figures, satirical countercultural humor and hand-lettered covers.',
      subject: 'draw the subject with dense crosshatched rubbery cartoon line and satirical humor.',
      color: 'Limited print color with dense black hatching.',
      light: 'Flat printed light.',
      texture: 'Dense crosshatching and hand lettering.',
      camera: 'Crowded satirical cover scene.',
      mood: 'satirical countercultural humor',
      render: 'Underground comix cover.',
      key: 'Crumb crosshatching; rubbery figures; satire',
      briefs: [
        'A bulbous crosshatched office manager in a tiny tie dances wildly on his desk as coworkers stare in horror, underground comix cover titled "BIG BOSS BLUES" number 1 hand-lettered exactly.',
        'A crosshatched hippie grandmother rides a giant turnip down a highway on a comix cover titled "TURNIP TRIP".',
        'A single crosshatched shoe with rubbery toes keeps on truckin’ down an empty desert road toward a bulbous sunset, underground comix cover titled "WALKIN’" hand-lettered exactly.',
      ],
    }),
    cr(
      'Chris Ware - Architectural Graphic Novel Cover',
      'graphic novel cover design',
      [...T, 'chris-ware'],
      {
        ...P,
        look: 'Chris Ware cover look: precise architectural diagrams, tiny clean figures, flat muted palettes, intricate information design and melancholy everyday life.',
        subject:
          'draw the subject as tiny clean figures inside precise architectural diagram compositions.',
        color: 'Flat muted palettes with soft accents.',
        light: 'Flat diagrammatic light.',
        texture: 'Precise clean line and flat color.',
        camera: 'Intricate diagrammatic layouts.',
        mood: 'quiet melancholy precision',
        render: 'Precise architectural graphic novel cover.',
        key: 'Chris Ware diagrams; tiny figures; muted palettes',
        briefs: [
          'A cutaway apartment building shows each tenant alone in a tiny precise room at 3 a.m., one woman on the top floor watering a single plant, graphic novel cover titled "BUILDING STORIES OF MARGARET" set exact in intricate lettering.',
          'A diagram of a lonely man’s daily routine forms the shape of a clock on a cover titled "EVERY DAY".',
          'A single tiny figure stands on a vast muted diagram of a city, cover titled "SMALL".',
        ],
      },
    ),
    cr('Dave McKean - Collage Mythic Cover', 'comic cover art', [...T, 'mckean'], {
      ...P,
      look: 'Dave McKean cover look: dreamlike mixed-media collage, photography, found objects, paint and typography layered into mythic eerie compositions.',
      subject: 'build the subject from layered dreamlike collage of photos, objects and paint.',
      color: 'Muted dreamlike tones with rich accents.',
      light: 'Mysterious layered light.',
      texture: 'Collage of photos, objects, paint and texture.',
      camera: 'Layered dreamlike compositions.',
      mood: 'dreamlike mythic eeriness',
      render: 'Mythic mixed-media collage cover.',
      key: 'McKean collage; found objects; dreamlike; mythic',
      avoid: ['a pale lord of dreams in black'],
      briefs: [
        'A collaged face made of old keys, moths, clock parts and a painted eye stares from a dreamlike box of found objects, mythic comic cover titled "THE KEEPER OF LOCKS" issue 1 set exact.',
        'A collage of feathers and old maps forms a sleeping giant on a cover titled "ATLAS DREAMS".',
        'A single rusted key floats in layered painted fog among torn photographs of doors and moth wings, mythic collage comic cover titled "UNLOCK" issue 2 set exact.',
      ],
    }),
    cr('Jim Steranko - Op-Art Spy Cover', 'sixties comic cover', [...T, 'steranko'], {
      ...P,
      look: 'Jim Steranko spy comic cover look: op-art psychedelic patterns, sleek secret agents, bold graphic design, dynamic spirals and sixties cool.',
      subject: 'draw the subject as a sleek secret agent within op-art psychedelic patterns.',
      color: 'Psychedelic op-art black, white, red and yellow.',
      light: 'Graphic flat light.',
      texture: 'Op-art patterns and bold ink.',
      camera: 'Dynamic spiral compositions.',
      mood: 'psychedelic spy cool',
      render: 'Op-art sixties spy comic cover.',
      key: 'Steranko op-art; spirals; sleek agents',
      briefs: [
        'A sleek secret agent grandmother in a tuxedo falls through an op-art spiral of black and white stripes while firing a grappling hook, sixties spy cover titled "AGENT GRANNY" issue 1 set exact.',
        'Two sleek spies in tuxedos duel with umbrellas on a dizzying psychedelic checkerboard floor that curves into a spiral, sixties spy comic cover titled "CHECKMATE" issue 4 set exact.',
        'A single spinning black and white op-art spiral swallows a dropped briefcase and a bowler hat, sixties spy comic cover titled "VORTEX" issue 6 set exact.',
      ],
    }),
    cr('Bernie Wrightson - Bronze Age Horror Cover', 'horror comic cover', [...T, 'wrightson'], {
      ...P,
      look: 'Bernie Wrightson horror cover look: lush gothic ink, detailed crosshatched monsters, swamps and castles, and romantic macabre atmosphere.',
      subject: 'draw the subject with lush detailed gothic ink and crosshatched monsters.',
      color: 'Muted swamp greens and gothic browns.',
      light: 'Moonlit gothic light.',
      texture: 'Lush detailed crosshatched ink.',
      camera: 'Gothic swamp and castle compositions.',
      mood: 'romantic macabre gloom',
      render: 'Lush gothic horror comic cover.',
      key: 'Wrightson lush ink; gothic monsters; swamps',
      avoid: ['a swamp monster made of plants', 'the stitched creature of a famous novel'],
      briefs: [
        'A lonely moss-covered scarecrow monster carries a lantern through a moonlit swamp toward a ruined castle in lush crosshatched ink, bronze age horror cover titled "THE BOG GARDENER" issue 1 set exact.',
        'A gothic mad scientist’s assistant tends a garden of glowing jars on a cover titled "LAB GARDEN".',
        'A single cracked lantern hangs from a dead tree in a crosshatched swamp, cover titled "WILL-O".',
      ],
    }),
    cr('Darwyn Cooke - Retro Modern Hero Cover', 'comic cover art', [...T, 'darwyn-cooke'], {
      ...P,
      look: 'Darwyn Cooke cover look: retro mid-century modern design, clean animated line, bold graphic shapes, limited palettes and optimistic sixties cool.',
      subject: 'draw the subject with clean retro animated line and bold mid-century shapes.',
      color: 'Limited retro palettes with warm accents.',
      light: 'Flat retro light.',
      texture: 'Clean line and flat color.',
      camera: 'Bold graphic mid-century compositions.',
      mood: 'optimistic retro cool',
      render: 'Retro modern comic cover.',
      key: 'Darwyn Cooke retro modern; clean line; limited palette',
      avoid: ['existing superheroes'],
      briefs: [
        'A retro test pilot in a clean mid-century flight suit waves from a rocket launching over a desert under a limited teal and orange palette, comic cover titled "NEW FRONTIER GIRL" issue 1 set exact.',
        'A cool jazz detective in a narrow tie strolls past a mid-century diner under a flat teal sky, retro modern comic cover titled "COOL CAT" issue 2 set exact.',
        'A single retro rocket stands on a launch pad under a flat orange sky, cover titled "LIFTOFF".',
      ],
    }),
    cr('Mexican Historieta Pulp Cover', 'Mexican comic cover', [...T, 'historieta'], {
      ...P,
      look: 'Mexican historieta pulp cover look: painted luchadores, masked heroes, lurid melodrama, bold colors and cheap weekly newsstand printing.',
      subject: 'paint the subject as lurid pulp melodrama with masked heroes.',
      color: 'Bold lurid pulp colors.',
      light: 'Dramatic pulp lighting.',
      texture: 'Cheap newsstand print with painted art.',
      camera: 'Dramatic pulp action compositions.',
      mood: 'lurid pulp melodrama',
      render: 'Mexican historieta pulp cover.',
      key: 'Historieta pulp; luchadores; lurid color',
      avoid: ['a real silver-masked wrestler'],
      briefs: [
        'A masked luchador grandmother body-slams a vampire on top of a speeding bus in lurid painted pulp color, historieta cover titled "LA ABUELA ENMASCARADA" number 1 set exact.',
        'A masked hero battles a giant scorpion in the desert on a historieta titled "EL ESCORPIÓN".',
        'A single lucha mask rests on a ring post under a spotlight, historieta titled "LA MÁSCARA".',
      ],
    }),
  ],
};

export default spec;
