import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas retro 3D visual studies: the rendering limits of early real-time and CG 3D as
// deliberate looks, never a specific game. Three originals get card briefs; seventeen new studies
// add clay-scanned CGI creatures, Gouraud primitives, billboard sprites, raycast corridors,
// draw-distance fog, vertex colors, filtered textures, chrome-on-checkerboard, voxel heightmaps,
// character-select poses, bright early-2000s console 3D, grey-box levels, scrolling water,
// particle sprites, sphere-mapped metal, nearest-neighbor close-ups and low-res skyboxes.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'retro-3d', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'modern high-poly rendering', 'interface or HUD', 'existing game characters or logos', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original characters';

const spec: Spec = {
  pack: 'pack_23',
  category: '8. Retro 3D Visual Studies',
  updates: {
    'SP23-034': { briefs: [
      'Pausing at a hillside spring, a wayfarer watches a boulder-shelled newt climb out of the pool, and the newt keeps growing until its shell is a hill, built from a few clear lit polygon planes. No readable text or logo.',
      'Built from restrained polygonal planes, a very blocky cow stands proudly in a field, clearly convinced it is the most realistic cow ever made. No readable text or logo.',
      'Made of a few sharp lit facets, a lone stone tower stands on a hill at dusk, and its single window is a flat black polygon with nothing behind it. No readable text or logo.',
    ] },
    'SP23-035': { briefs: [
      'Hoisting a timber beam with a rope winch, two bridge builders look up as a giant river serpent lifts the other end for them, all angular geometry and painterly raster textures. No readable text or logo.',
      "Serving a stew so low-poly that every carrot is a perfect cube, a proud innkeeper waits for praise, the whole tavern built from angular geometry and hand-painted textures. No readable text or logo.",
      "Standing between hills of hand-painted grass, an empty chapel has its door ajar, and inside is only a flat painted texture of darkness. No readable text or logo.",
    ] },
    'SP23-036': { briefs: [
      'Balancing on a stone stair cut into a mountain, a wayfarer reaches a landing where a sleeping giant\'s faceted face forms the cliff wall, painted textures carrying every crease. No readable text or logo.',
      'With visible facets and small painted textures, a knight\'s horse refuses to cross a bridge because the bridge texture is clearly painted on and it does not trust it. No readable text or logo.',
      "Sitting in an abandoned courtyard of painted facets, an old well holds a painted water texture that is slowly scrolling upward. No readable text or logo.",
    ] },
  },
  creates: [
    study('Clay-Scanned Early CGI Creature', 'digitized clay model cgi', 'clay-scan-cgi', {
      aesthetic: 'Clay-scanned early CGI creature: early nineties computer creatures scanned from sculpted clay maquettes, glossy plasticky shading, low polygon smoothing and simple ray-traced shadows.',
      subject_treatment: `${keep}; render the subject as an early CGI model built from a scanned clay sculpture.`,
      color_and_tone: "Saturated plasticky colors with glossy white highlights, kept consistent across the whole image.",
      lighting_and_shadow: "Hard ray-traced shadows and simple point lights, kept consistent across the whole image.",
      texture_and_material: 'Smooth faceted surfaces, visible polygon edges and plastic sheen.',
      camera_and_composition: 'Creature posed on a flat plane or simple background.',
      atmosphere_and_mood: 'Keep the requested mood with proud early digital wonder.',
      rendering_and_quality: "Authentic early CGI look with slight faceting, kept consistent across the whole image.",
      key_features: 'scanned clay creature; plastic sheen; hard shadows; faceted smoothing',
    }, [], [
      'Rearing up on a flat grey plane, a glossy early-CGI wyvern roars with visible polygon edges on its jaw and a perfectly hard black shadow beneath it. No readable text or logo.',
      'Posed proudly on a flat plane, an early CGI snail has been rendered with such shiny plastic that it reflects the entire empty studio. No readable text or logo.',
      'Standing alone in a flat grey void, a glossy early CGI child\'s toy blinks, and its hard shadow on the floor does not blink. No readable text or logo.',
    ]),
    study('Gouraud-Shaded Primitives', 'smooth vertex-shaded simple shapes', 'gouraud', {
      aesthetic: 'Gouraud-shaded primitives: early 3D built from simple spheres, cones and cylinders with smooth vertex-interpolated shading and telltale soft polygon edges.',
      subject_treatment: `${keep}; build the subject from simple smooth-shaded primitive shapes.`,
      color_and_tone: "Flat saturated colors with smooth gradient shading, kept consistent across the whole image.",
      lighting_and_shadow: "Single light with smooth interpolated gradients, kept consistent across the whole image.",
      texture_and_material: "Untextured surfaces and slightly jagged silhouettes, kept consistent across the whole image.",
      camera_and_composition: "Simple arrangement on a flat ground plane, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with naive geometric charm.',
      rendering_and_quality: 'Clean early 3D with visible faceted silhouette edges.',
      key_features: 'primitive shapes; smooth vertex shading; untextured; faceted edges',
    }, [], [
      "Towering over a village made of cubes, a giant golem of spheres, cones and cylinders stomps forward, its smooth-shaded club a single long cone. No readable text or logo.",
      'Assembled from smooth-shaded spheres, a snowman has been given a cone for a nose that is clearly much too long for his face. No readable text or logo.',
      'On an empty flat plane, a single smooth-shaded sphere sits alone, and its shadow is shaped like a person. No readable text or logo.',
    ]),
    study('Billboard Sprite 3D Space', 'flat sprites in 3d world', 'billboard-sprite', {
      aesthetic: 'Billboard sprite 3D space: flat two-dimensional sprites of trees, monsters and items that always face the camera, standing in a simple textured 3D world.',
      subject_treatment: `${keep}; render the subject as a flat sprite that faces the camera inside a 3D space.`,
      color_and_tone: 'Pixelated sprites over darker textured walls and floors.',
      lighting_and_shadow: 'Sector lighting; sprites not lit by the scene.',
      texture_and_material: 'Flat pixel sprites, tiled wall textures and floor grids.',
      camera_and_composition: 'First-person or low view with sprites facing the camera.',
      atmosphere_and_mood: 'Keep the requested mood with uncanny flat presence.',
      rendering_and_quality: "Authentic sprite-in-3D look, kept consistent across the whole image.",
      key_features: 'camera-facing sprites; textured 3D rooms; pixel monsters; flat trees',
    }, [], [
      'Charging down a stone hall, a demon made of a flat pixel sprite fills the view, always facing the camera no matter where the player moves. No readable text or logo.',
      'Standing in a textured courtyard, every tree is a flat sprite, and a very confused deer is trying to walk behind one. No readable text or logo.',
      'At the end of a dim textured corridor, a flat sprite of a smiling figure always turns to face you, even when you walk around it. No readable text or logo.',
    ]),
    study('Raycast Corridor Render', 'early raycast maze graphics', 'raycast', {
      aesthetic: 'Raycast corridor render: early first-person maze graphics where walls are vertical textured slices, floors and ceilings are flat colors and every room is a right-angle grid.',
      subject_treatment: `${keep}; place the subject in a right-angle maze of vertical textured wall slices.`,
      color_and_tone: 'Flat grey floor and ceiling, textured walls in muted colors.',
      lighting_and_shadow: 'Alternating wall brightness for faces of the grid.',
      texture_and_material: 'Stretched pixel wall textures and flat untextured floors.',
      camera_and_composition: "Eye-level first-person corridor on a grid, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with tense maze claustrophobia.',
      rendering_and_quality: "Authentic early raycast look without modern effects, kept consistent across the whole image.",
      key_features: 'vertical wall slices; flat floors; right-angle maze; eye level',
    }, [], [
      'Deep in a right-angle stone maze, a cyclops guard steps around a corner with a lantern, the walls behind him made of stretched blue brick textures. No readable text or logo.',
      'Wandering a flat-colored maze, a lost knight finds a single potted plant in a corridor and treats it like the greatest treasure in the world. No readable text or logo.',
      'Down a long corridor of repeating brick textures, a wall that was solid a moment ago now has a doorway. No readable text or logo.',
    ]),
    study('Draw-Distance Fog World', 'fog hiding short draw distance', 'draw-fog', {
      aesthetic: 'Draw-distance fog world: early 3D worlds wrapped in thick colored fog that hides how little could be drawn, objects popping out of the haze a few steps away.',
      subject_treatment: `${keep}; surround the subject with thick flat fog that swallows everything beyond a short distance.`,
      color_and_tone: 'Flat fog color such as grey-green, purple or orange.',
      lighting_and_shadow: "Flat ambient light fading into fog color, kept consistent across the whole image.",
      texture_and_material: "Low-res textures fading into solid fog, kept consistent across the whole image.",
      camera_and_composition: 'Near objects clear, distance a flat wall of fog.',
      atmosphere_and_mood: 'Keep the requested mood with lonely unseen menace.',
      rendering_and_quality: 'Hard fog falloff with objects popping into view.',
      key_features: 'thick flat fog; short view distance; popping objects; low-res textures',
    }, [], [
      "Crossing a plain swallowed by thick purple fog, a pilgrim sees the leg of a giant appear out of the haze a few steps away, the rest of it still hidden. No readable text or logo.",
      'In thick grey-green fog, a farmer walks his cow and keeps being surprised by trees that pop into existence right in front of his face. No readable text or logo.',
      'On a road that vanishes into flat orange fog, a signpost stands at the edge of visibility, and just beyond it, something tall is waiting. No readable text or logo.',
    ]),
    study('Vertex-Colored Low Poly', 'untextured vertex color models', 'vertex-color', {
      aesthetic: 'Vertex-colored low poly: early 3D models with no textures at all, color painted directly on vertices so gradients blend across big simple polygons.',
      subject_treatment: `${keep}; render the subject with simple polygons colored only by blended vertex colors.`,
      color_and_tone: "Soft blended gradients across large polygons, kept consistent across the whole image.",
      lighting_and_shadow: "Baked vertex shading with no real shadows, kept consistent across the whole image.",
      texture_and_material: 'No textures, visible polygon edges and color blends.',
      camera_and_composition: "Clean composition of simple models, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with soft minimal dream.',
      rendering_and_quality: "Clean low poly with smooth color gradients, kept consistent across the whole image.",
      key_features: 'vertex colors; no textures; blended gradients; low poly',
    }, ['textures'], [
      'Circling a floating island of blended vertex colors, a low-poly whale drifts through a sunset sky, its belly fading from pink to gold with no textures anywhere. No readable text or logo.',
      'With no textures at all, a low-poly frog prince sits on a lily pad, his crown just three yellow triangles blending into orange. No readable text or logo.',
      'In a soft vertex-colored cave, a low-poly lantern glows, and its light gradient ends abruptly at the edge of one dark polygon. No readable text or logo.',
    ]),
    study('Filtered Blurry Texture 3D', 'bilinear smeared texture console 3d', 'blurry-texture', {
      aesthetic: 'Filtered blurry texture 3D: late-nineties console 3D with small textures stretched and smoothed into soft smeared blurs, round cartoon forms and bright colors.',
      subject_treatment: `${keep}; render the subject with soft smeared low-res textures on rounded low-poly forms.`,
      color_and_tone: "Bright saturated colors softened by blur, kept consistent across the whole image.",
      lighting_and_shadow: "Simple lighting and round blob shadows, kept consistent across the whole image.",
      texture_and_material: 'Smeared blurry textures, rounded polygons and soft edges.',
      camera_and_composition: "Third-person camera behind or beside the character, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with bright nostalgic playfulness.',
      rendering_and_quality: "Authentic soft filtered look, kept consistent across the whole image.",
      key_features: 'smeared textures; bright colors; blob shadows; rounded low poly',
    }, [], [
      'Racing across a bright grassy field with blurry smeared textures, a small hero on a giant chicken leaps over a castle moat toward a round drawbridge. No readable text or logo.',
      'With smeared soft textures, a smiling round king waves from a castle balcony, his face texture so blurry he looks slightly melted. No readable text or logo.',
      "In a bright blurry world, a painting in the throne room is so smeared that its subject seems to have left the frame. No readable text or logo.",
    ]),
    study('Chrome Spheres on Checkerboard', 'classic ray-traced demo scene', 'chrome-checker', {
      aesthetic: 'Chrome spheres on checkerboard: the classic early ray-tracing demo scene, perfect mirrored spheres floating over an infinite checkerboard under a gradient sky.',
      subject_treatment: `${keep}; place the subject among perfect chrome reflections on an infinite checkerboard.`,
      color_and_tone: 'Red and white or black and white checkers, blue gradient sky.',
      lighting_and_shadow: "Sharp ray-traced shadows and perfect reflections, kept consistent across the whole image.",
      texture_and_material: 'Mirror chrome, glass spheres and a crisp tile plane.',
      camera_and_composition: 'Low camera over an infinite checkerboard to the horizon.',
      atmosphere_and_mood: 'Keep the requested mood with early digital wonder.',
      rendering_and_quality: "Crisp perfect reflections with aliased edges, kept consistent across the whole image.",
      key_features: 'chrome spheres; infinite checkerboard; gradient sky; sharp shadows',
    }, [], [
      "Above an infinite red and white checkerboard, a chrome unicorn gallops, reflecting the whole gradient sky and a dragon that is not visible anywhere else. No readable text or logo.",
      'On an infinite checkerboard, three perfect chrome spheres sit in a row, and a chrome duck is trying to hatch them. No readable text or logo.',
      'Floating over an endless checkerboard, a mirrored sphere reflects the scene perfectly, except that the reflection shows a figure standing right behind the viewer. No readable text or logo.',
    ]),
    study('Voxel Heightmap Landscape', 'early voxel terrain renderer', 'voxel-heightmap', {
      aesthetic: 'Voxel heightmap landscape: early terrain engines that drew hills from columns of colored pixels, rolling blocky landscapes stretching to a fogged horizon.',
      subject_treatment: `${keep}; set the subject over rolling terrain built from pixel columns.`,
      color_and_tone: 'Earthy greens, browns and a hazy blue horizon.',
      lighting_and_shadow: "Baked slope shading and haze, kept consistent across the whole image.",
      texture_and_material: "Pixel-column terrain, jagged ridges and flat sky, kept consistent across the whole image.",
      camera_and_composition: 'Low flying view over hills to the horizon.',
      atmosphere_and_mood: 'Keep the requested mood with vast early freedom.',
      rendering_and_quality: "Authentic column terrain with blocky ridges, kept consistent across the whole image.",
      key_features: 'pixel column terrain; rolling hills; hazy horizon; low flight',
    }, [], [
      'Flying low over rolling hills built from pixel columns, a flock of dragons chases a lone airship toward a blocky mountain range fading into blue haze. No readable text or logo.',
      "Trying to count his flock on the blocky hills, a shepherd realizes all his sheep look like identical small white columns on the slopes. No readable text or logo.",
      "Winding through endless column-built valleys at dusk, a single path of lanterns leads toward a hill that has no shading at all. No readable text or logo.",
    ]),
    study('Character-Select Model Pose', 'turntable character select screen', 'char-select', {
      aesthetic: 'Character-select model pose: a low-poly hero model standing on a small pedestal in an idle pose, lit dramatically against a dark gradient as if waiting to be chosen.',
      subject_treatment: `${keep}; pose the subject as a low-poly character on a pedestal in an idle stance.`,
      color_and_tone: 'Dark gradient background with a bright spot on the model.',
      lighting_and_shadow: 'Strong key light and rim light on the model.',
      texture_and_material: 'Low-poly model, painted textures and a glowing pedestal.',
      camera_and_composition: "Full-body centered, slightly low angle, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with anticipation and pride.',
      rendering_and_quality: "Clean low-poly model with dramatic lighting, kept consistent across the whole image.",
      key_features: 'pedestal; idle pose; dark gradient; dramatic spotlight',
    }, ['character names or stats'], [
      'Waiting on a glowing pedestal, a low-poly barbarian queen rests her huge axe on her shoulder, lit from below as if daring you to pick anyone else. No readable text or logo.',
      "Standing in a heroic idle pose on the selection pedestal, a low-poly chicken is fully convinced it is the strongest fighter in the roster. No readable text or logo.",
      'Alone on a pedestal in a dark gradient, a low-poly figure in a plain grey default texture waits, although no one remembers adding it. No readable text or logo.',
    ]),
    study('Bright Early-2000s Console 3D', 'saturated sunny console 3d', 'bright-console', {
      aesthetic: 'Bright early-2000s console 3D: sunny saturated worlds with blue skies, clean textures, plain even brightness and cheerful chunky characters in smooth low-poly.',
      subject_treatment: `${keep}; render the subject as a chunky cheerful model in a sunny saturated world.`,
      color_and_tone: 'Sky blue, grass green, sunny yellow and bright white.',
      lighting_and_shadow: "Bright sun, simple soft shadows, kept consistent across the whole image.",
      texture_and_material: "Clean medium-res textures and smooth low-poly shapes, kept consistent across the whole image.",
      camera_and_composition: "Dynamic third-person or wide sunny vista, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with bright optimistic energy.',
      rendering_and_quality: "Clean crisp early-2000s look, kept consistent across the whole image.",
      key_features: 'sunny blue sky; saturated color; chunky characters; clean textures',
    }, [], [
      'Grinding down a castle rampart on a skateboard under a bright blue sky, a young wizard dodges catapult stones in a sunny saturated world. No readable text or logo.',
      "Chasing a crab across a sunny seaside island, a cheerful chunky warrior wants back the helmet the crab has stolen and is now wearing proudly. No readable text or logo.",
      'Under a perfect blue sky in a bright world, a sunny village square is completely empty and every door is locked. No readable text or logo.',
    ]),
    study('Untextured Grey-Box Level', 'level blockout greybox render', 'greybox', {
      aesthetic: 'Untextured grey-box level: a game level in its blockout stage, plain grey boxes and ramps standing in for castles, trees and stairs, with a single placeholder figure.',
      subject_treatment: `${keep}; render the subject as simple grey placeholder shapes in a blockout level.`,
      color_and_tone: "Flat light greys with occasional orange placeholder, kept consistent across the whole image.",
      lighting_and_shadow: "Plain default lighting and soft ambient occlusion, kept consistent across the whole image.",
      texture_and_material: "Untextured grey surfaces and simple grid lines, kept consistent across the whole image.",
      camera_and_composition: "Wide view of a blockout level, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with unfinished eerie emptiness.',
      rendering_and_quality: "Clean untextured blockout look, kept consistent across the whole image.",
      key_features: 'grey boxes; placeholder figure; grid lines; unfinished level',
    }, [], [
      "Surrounded by a level made entirely of grey boxes and ramps, a placeholder hero stands before a grey cube fortress while a grey cylinder dragon towers overhead. No readable text or logo.",
      'On a grey-box level, a placeholder capsule has been standing in for the hero for years, and today it finally has a small hat. No readable text or logo.',
      "At the end of a plain grey corridor, simple boxes lead to a single room where one object has somehow already been fully textured. No readable text or logo.",
    ]),
    study('Scrolling-Texture Water World', 'early 3d scrolling water surfaces', 'scrolling-water', {
      aesthetic: 'Scrolling-texture water world: early 3D seas, rivers and waterfalls made of a single looping texture sliding across flat polygons, glossy and hypnotic.',
      subject_treatment: `${keep}; surround the subject with flat water surfaces covered in a looping scrolling texture.`,
      color_and_tone: 'Saturated turquoise and blue with white foam patterns.',
      lighting_and_shadow: "Flat bright water with simple highlights, kept consistent across the whole image.",
      texture_and_material: 'Repeating wave textures, flat water planes and pixel foam.',
      camera_and_composition: "Wide view of sea, rivers or waterfalls, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with hypnotic looping calm.',
      rendering_and_quality: "Clean repeating water with visible tiling, kept consistent across the whole image.",
      key_features: 'looping water texture; flat planes; waterfall strips; visible tiling',
    }, [], [
      'Sailing across a flat sea of repeating wave textures, a pirate ship approaches a waterfall at the edge of the world that is only a single sliding texture strip. No readable text or logo.',
      'Standing in a river of scrolling blue texture, a bear tries to catch a fish that keeps sliding past with the water pattern. No readable text or logo.',
      'Across a calm looping sea, the texture of the water repeats perfectly, and in each repeated tile the same shadow of something below moves a little closer. No readable text or logo.',
    ]),
    study('Sprite-Particle Magic Burst', 'early 3d particle sprite effects', 'particle-sprites', {
      aesthetic: 'Sprite-particle magic burst: early 3D spell and fire effects made from many small flat glowing sprites, stars and rings bursting outward with additive glow.',
      subject_treatment: `${keep}; surround the subject with bursts of flat glowing sprite particles.`,
      color_and_tone: 'Bright additive magenta, cyan and gold sprites on dark.',
      lighting_and_shadow: "Glow from particles with flat surroundings, kept consistent across the whole image.",
      texture_and_material: 'Flat star sprites, rings and sparkles with hard edges.',
      camera_and_composition: "Dramatic burst centered on the subject, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with flashy magical spectacle.',
      rendering_and_quality: "Crisp flat sprites layered into glowing bursts, kept consistent across the whole image.",
      key_features: 'flat sprite particles; additive glow; star bursts; rings',
    }, [], [
      "Casting a huge spell on a rope bridge over a chasm, a sorceress throws out a burst of hundreds of flat star sprites and rings that light up a charging ogre. No readable text or logo.",
      'A small wizard tries to cast a fire spell, and a single tiny star sprite floats out of his wand and politely fizzles. No readable text or logo.',
      'In a dark crypt, a burst of glowing sprite particles rises from a coffin, and the sparkles are slowly forming the shape of a hand. No readable text or logo.',
    ]),
    study('Sphere-Mapped Metal Shine', 'fake environment mapped chrome', 'sphere-map', {
      aesthetic: 'Sphere-mapped metal shine: early 3D shiny metal faked with a single swirling reflection texture wrapped over models, liquid and dreamlike rather than accurate.',
      subject_treatment: `${keep}; wrap the subject in a swirling fake reflection texture like liquid chrome.`,
      color_and_tone: "Swirling silver, blue and gold reflections, kept consistent across the whole image.",
      lighting_and_shadow: "Reflections independent of the scene lighting, kept consistent across the whole image.",
      texture_and_material: "Swirling environment texture on low-poly metal, kept consistent across the whole image.",
      camera_and_composition: 'Close view of the shiny model on a simple ground.',
      atmosphere_and_mood: 'Keep the requested mood with slick dreamy strangeness.',
      rendering_and_quality: "Authentic sphere-mapped look, not physically accurate, kept consistent across the whole image.",
      key_features: 'swirling reflection texture; liquid chrome; low poly; fake shine',
    }, [], [
      "Rising from a lake of mercury, a silver mermaid glistens with a swirling reflection texture that shows a sky and a sunset that exist nowhere in the scene. No readable text or logo.",
      'A proud low-poly chrome duck swims in a pond, its shiny swirl texture reflecting a disco ball that is not there. No readable text or logo.',
      'A liquid silver figure stands in a dark hall, and its swirling reflection shows a sunny meadow full of people waving. No readable text or logo.',
    ]),
    study('Nearest-Neighbor Texture Close-Up', 'unfiltered pixelated 3d textures', 'nearest-neighbor', {
      aesthetic: 'Nearest-neighbor texture close-up: 3D surfaces seen up close with unfiltered low-res textures, every texel a crisp square block of color on walls, faces and floors.',
      subject_treatment: `${keep}; bring the camera close so the subject\'s textures break into crisp square texels.`,
      color_and_tone: "Muted texture colors as sharp square blocks, kept consistent across the whole image.",
      lighting_and_shadow: "Simple lighting over crisp texel blocks, kept consistent across the whole image.",
      texture_and_material: "Hard-edged square texels on flat polygons, kept consistent across the whole image.",
      camera_and_composition: "Extreme close-up where texels become large, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with crunchy tactile nostalgia.',
      rendering_and_quality: "Crisp unfiltered texels, no smoothing, kept consistent across the whole image.",
      key_features: 'square texels; unfiltered textures; close-up; flat polygons',
    }, [], [
      "Leaning in close to a dungeon wall, a thief discovers that each brick is only four crisp texels wide, and one brick is a secret door drawn in slightly different pixels. No readable text or logo.",
      "Seen up close, a heroic king's face is just a grid of crisp square texels, including a moustache that is exactly two pixels tall. No readable text or logo.",
      'Very close to a painted portrait in a 3D hall, the texels of its eyes are blocky and square, and they are not the same color they were a moment ago. No readable text or logo.',
    ]),
    study('Low-Res Skybox Panorama', 'early 3d sky cube', 'skybox', {
      aesthetic: 'Low-res skybox panorama: early 3D skies painted on a cube around the world, low-resolution clouds and mountains with faint seams at the corners.',
      subject_treatment: `${keep}; set the subject under a low-resolution painted sky cube with visible corner seams.`,
      color_and_tone: 'Painted sunset or night gradients with low-res clouds.',
      lighting_and_shadow: "Sky light not matching the scene exactly, kept consistent across the whole image.",
      texture_and_material: "Stretched low-res sky textures and visible seams, kept consistent across the whole image.",
      camera_and_composition: 'Wide view with lots of sky and a small ground.',
      atmosphere_and_mood: 'Keep the requested mood with lonely vast nostalgia.',
      rendering_and_quality: "Authentic stretched skybox with seams, kept consistent across the whole image.",
      key_features: 'painted sky cube; low-res clouds; corner seams; small ground',
    }, [], [
      'Beneath a vast low-res painted sky of purple storm clouds, a lone rider crosses a plain while a painted dragon on the skybox never gets any closer. No readable text or logo.',
      "Under a stretched sunset skybox, a shepherd tries to walk to the painted mountains in the distance and keeps bumping into the edge of the world. No readable text or logo.",
      'Standing on a small floating ground, a figure looks up at a painted night sky, and in one corner of the skybox the seam has opened a little. No readable text or logo.',
    ]),
  ],
};

export default spec;
