import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Album covers for jazz, soul, funk, world and hip-hop: each preset names the designer, label or
// scene whose cover grammar it rebuilds. Cards invent original artists and album titles with
// exact text, never a real record's artwork.
const T = ['album-cover', 'album-cover-soul'];
const P = { requestedText: true } as const;
const sleeve = 'Printed record sleeve on board with slight ring wear and soft paper grain.';

const spec: Spec = {
  pack: 'pack_26',
  category: '6. Album Covers - Jazz, Soul & Hip-Hop',
  newCategory: { id: 'album-covers-jazz-soul-hiphop' },
  updates: {},
  creates: [
    cr(
      'Alex Steinweiss - Forties Illustrated Album Cover',
      'album cover design',
      [...T, 'steinweiss'],
      {
        ...P,
        look: 'Alex Steinweiss Columbia album cover look of the 1940s: the first illustrated record covers, flat graphic shapes of instruments, curly hand-lettered titles and bright poster color.',
        subject:
          'turn the subject into a flat graphic poster motif built from simple instrument-like shapes.',
        color: 'Bright poster red, mustard, teal and cream.',
        light: 'Flat printed poster light.',
        texture: sleeve,
        camera: 'Flat frontal square sleeve with a bold central motif.',
        mood: 'jaunty early optimism',
        render: 'Faithful forties illustrated album cover design.',
        key: 'Steinweiss flat shapes; curly hand lettering; poster color',
        briefs: [
          'A flat graphic square sleeve shows a giant stylized clarinet curling around a tiny city skyline in mustard and teal, hand-lettered title "MIDNIGHT FERRY SUITE" and artist "THE HARBOR QUARTET" set exact in curly script.',
          'Stylized piano keys ripple like ocean waves beneath a red moon on a square poster cover, title "KEYS TO THE SEA" set exact in curly hand lettering.',
          'A single bold violin shape made of overlapping red and cream planes fills a square cover, title "STRING THEORY FOR BEGINNERS" set exact below it.',
        ],
      },
    ),
    cr(
      'Reid Miles - Blue Note Type-Driven Jazz Cover',
      'album cover design',
      [...T, 'reid-miles'],
      {
        ...P,
        look: 'Reid Miles Blue Note Records cover look of the 1950s and 1960s: bold modernist typography as image, cropped Francis Wolff black-and-white photographs, one strong tint color and asymmetric grids.',
        subject:
          'render the subject as a cropped high-contrast black-and-white photograph under bold modernist type.',
        color: 'Black-and-white photo with one bold tint of blue, orange or green.',
        light: 'Moody smoky studio photo light.',
        texture: sleeve,
        camera: 'Asymmetric modernist grid with extreme crops.',
        mood: 'cool modernist swing',
        render: 'Faithful Blue Note era jazz cover design.',
        key: 'Reid Miles bold type; cropped photo; one tint color',
        avoid: ['the real Blue Note label logo'],
        briefs: [
          'A tightly cropped black-and-white photo of a trumpeter’s hands on the valves sits under a bold orange tint, with giant modernist type "SLOW BURN AVENUE" and artist "OTIS REYNE SEXTET" set exact running off the edge.',
          'Huge stacked letters fill a green cover with a tiny cropped photo of a drummer’s cymbal, title "SIDE STEP" set exact.',
          'A smoky photo of an empty bandstand sits beneath a deep blue tint, title "AFTER HOURS AT THE LANTERN" set exact in heavy sans serif.',
        ],
      },
    ),
    cr(
      'David Stone Martin - Verve Ink Line Jazz Cover',
      'album cover design',
      [...T, 'david-stone-martin'],
      {
        ...P,
        look: 'David Stone Martin Clef and Verve cover look of the 1950s: nervous single-weight ink line drawings of musicians, big areas of white, a single watercolor wash and elegant hand lettering.',
        subject:
          'draw the subject in nervous single-weight ink lines with one flat watercolor wash.',
        color: 'Black ink line on white with one wash of red or ochre.',
        light: 'Flat paper light.',
        texture: sleeve,
        camera: 'Airy composition with lots of white space.',
        mood: 'elegant improvised ease',
        render: 'Faithful fifties ink-drawn jazz cover design.',
        key: 'David Stone Martin ink line; white space; single wash',
        briefs: [
          'A nervous ink line drawing of a bassist leaning into his instrument floats in white space with a single red watercolor wash behind his head, title "THE LONG WALK HOME" and artist "EZRA BLUE TRIO" set exact in elegant hand lettering.',
          'A saxophonist drawn in trembling ink lines plays to a single ochre wash moon, title "NIGHT SCHOOL" set exact.',
          'An ink drawing of an empty chair and a hat on a piano sits under an ochre wash, title "INTERMISSION" set exact.',
        ],
      },
    ),
    cr('Jim Flora - Cartoon Modernist Jazz Cover', 'album cover design', [...T, 'jim-flora'], {
      ...P,
      look: 'Jim Flora RCA Victor and Columbia cover look of the 1940s and 1950s: zany mid-century cartoon modernism, angular elongated musicians, floating eyes, crazy perspective and wild playful color.',
      subject:
        'draw the subject as zany angular mid-century cartoon figures with crazy perspective.',
      color: 'Wild mid-century orange, turquoise, magenta and black.',
      light: 'Flat printed light.',
      texture: sleeve,
      camera: 'Crazy tilted mid-century perspective.',
      mood: 'zany exuberant swing',
      render: 'Faithful mid-century cartoon jazz cover design.',
      key: 'Jim Flora zany modernism; angular musicians; wild color',
      briefs: [
        'Zany angular cartoon musicians with floating eyeballs and noodle arms play tubas on a tilted rooftop under a turquoise sky, title "BOP GOES THE WEASEL" and artist "THE LOONEY LOOPS" set exact in wobbly letters.',
        'A cartoon drummer with six arms plays a kit made of cooking pots in crazy perspective, title "KITCHEN CRASH" set exact.',
        'A cartoon piano with legs dances down a zigzag street at night, title "THE UPTOWN SHUFFLE" set exact.',
      ],
    }),
    cr('Motown Sixties - Studio Portrait Soul Cover', 'album cover design', [...T, 'motown'], {
      ...P,
      look: 'Motown and sixties soul cover look: bright studio portrait photographs of groups in matching outfits, saturated color backdrops, clean sans-serif titles and optimistic polish.',
      subject:
        'stage the subject as a bright polished studio portrait of a group in matching outfits.',
      color: 'Saturated backdrop red, yellow or turquoise with matching outfits.',
      light: 'Bright polished studio flash.',
      texture: sleeve,
      camera: 'Frontal group portrait with clean type band.',
      mood: 'bright optimistic soul',
      render: 'Faithful sixties soul label cover design.',
      key: 'Motown group portrait; matching outfits; bright backdrop',
      avoid: ['real Motown artists', 'the real Motown label logo'],
      briefs: [
        'Four original singers in matching mint-green suits pose shoulder to shoulder against a bright yellow studio backdrop, clean title "HEARTBEAT ON MAIN STREET" and group name "THE VELVET STEPS" set exact above them.',
        'Three singers in matching red sequin dresses laugh mid-step against a turquoise backdrop, title "SATURDAY SWEET" set exact.',
        'A lone crooner in a white tuxedo holds a vintage microphone against a red backdrop, title "SAY IT TWICE" set exact.',
      ],
    }),
    cr('Stax Memphis - Gritty Southern Soul Cover', 'album cover design', [...T, 'stax'], {
      ...P,
      look: 'Stax and Memphis soul cover look of the late sixties: gritty candid photographs, bold chunky typography, warm earthy palettes and raw southern street energy.',
      subject:
        'stage the subject in a gritty candid southern street photograph with bold chunky type.',
      color: 'Warm earthy brown, mustard and red.',
      light: 'Hot southern daylight.',
      texture: sleeve,
      camera: 'Candid photo framing with chunky title band.',
      mood: 'raw soulful grit',
      render: 'Faithful late-sixties southern soul cover design.',
      key: 'Stax gritty photo; chunky type; earthy palette',
      avoid: ['the real Stax snapping-finger logo'],
      briefs: [
        'A candid photo of an organ player sweating outside a Memphis barbershop on a hot afternoon sits under chunky mustard type "GREASE AND GOSPEL" and artist "LITTLE RAY PARKER" set exact.',
        'A horn section rehearses on a porch in the summer heat, title "SWAMP HEAT" set exact in bold brown letters.',
        'A pair of worn dancing shoes rests on a wooden stage, title "MEMPHIS AT MIDNIGHT" set exact.',
      ],
    }),
    cr('Pedro Bell - Funk Cartoon Cosmos Cover', 'album cover design', [...T, 'pedro-bell'], {
      ...P,
      look: 'Pedro Bell Funkadelic-era cover look of the 1970s: dense felt-tip cartoon cosmos, grotesque funky space creatures, crowded all-over chaos and psychedelic Afrofuturist satire.',
      subject:
        'draw the subject as dense funky felt-tip cartoon creatures in a crowded cosmic city.',
      color: 'Psychedelic felt-tip magenta, green, orange and purple.',
      light: 'Flat marker color.',
      texture: sleeve,
      camera: 'Crowded all-over cartoon composition.',
      mood: 'wild cosmic funk satire',
      render: 'Faithful seventies funk cartoon cover design.',
      key: 'Pedro Bell felt-tip cosmos; funky creatures; crowded',
      briefs: [
        'A dense felt-tip cartoon cosmos packed with funky space creatures in platform boots dancing on a flying disco saucer over a neon city, title "GALACTIC GREASE" and band "THE MOTHERSHIP JANITORS" set exact in bubble letters.',
        'A crowded cartoon city of funky alien musicians crams every inch of a square cover, title "UPTOWN ORBIT" set exact.',
        'A cartoon spaceship made of a giant platform shoe blasts off, title "STEP INTO SPACE" set exact.',
      ],
    }),
    cr('Mati Klarwein - Visionary Painted Cover', 'album cover design', [...T, 'mati-klarwein'], {
      ...P,
      look: 'Mati Klarwein visionary cover painting look of around 1970: hyper-detailed surreal oil painting, mirrored symmetric bodies and landscapes, African and cosmic imagery and lush saturated color.',
      subject: 'paint the subject as hyper-detailed surreal symmetric visionary oil imagery.',
      color: 'Lush saturated jungle green, sky blue and flesh gold.',
      light: 'Glowing visionary painted light.',
      texture: sleeve,
      camera: 'Symmetric wraparound painted composition.',
      mood: 'lush visionary spirituality',
      render: 'Faithful visionary painted album cover.',
      key: 'Klarwein visionary oil; symmetry; lush surreal',
      briefs: [
        'A hyper-detailed symmetric oil painting shows twin musicians mirrored across a river under a cosmic sky full of flowers and fish, title "RIVER OF TWO MOONS" and artist "SOLANGE AKANDE" set exact in small elegant letters.',
        'A visionary painted landscape blooms out of a mirrored hand drum under twin suns, title "ROOTS AND ORBITS" set exact in small gold letters across the lower edge.',
        'A symmetric painted tree grows eyes instead of fruit under a golden sky, title "THE WATCHING GARDEN" set exact.',
      ],
    }),
    cr(
      'Lemi Ghariokwu - Afrobeat Political Painting Cover',
      'album cover design',
      [...T, 'lemi-ghariokwu'],
      {
        ...P,
        look: 'Lemi Ghariokwu Afrobeat cover look of the 1970s Lagos scene: bold flat painted satire, crowded political caricature, bright primary color, thick outlines and hand-painted titles.',
        subject: 'paint the subject as bold flat satirical caricature with thick outlines.',
        color: 'Bright primary red, yellow, green and black.',
        light: 'Flat painted light.',
        texture: sleeve,
        camera: 'Crowded poster-like narrative composition.',
        mood: 'defiant satirical energy',
        render: 'Faithful seventies Afrobeat cover painting.',
        key: 'Lemi Ghariokwu flat satire; thick outlines; primary color',
        avoid: ['real politicians or musicians'],
        briefs: [
          'A bold flat painting shows a giant bureaucrat made of stacked paperwork towering over a joyful street band playing in a crowded Lagos market, title "PAPER GIANT" and band "THE SHRINE COLLECTIVE" set exact in hand-painted letters.',
          'A crowd of dancers pushes a broken traffic light down a busy street, title "NO MORE WAITING" set exact.',
          'A hand-painted saxophone grows into a palm tree over a sunny street, title "SHADE FOR EVERYBODY" set exact.',
        ],
      },
    ),
    cr(
      'Tropicalia 1968 - Brazilian Psychedelic Collage Cover',
      'album cover design',
      [...T, 'tropicalia'],
      {
        ...P,
        look: 'Brazilian Tropicália cover look of 1968: collage of tropical kitsch, bananas and parrots, group portraits in odd costumes, psychedelic lettering and ironic sunny color.',
        subject:
          'stage the subject as a tropical kitsch collage portrait with psychedelic lettering.',
        color: 'Sunny banana yellow, parrot green and hot pink.',
        light: 'Bright tropical daylight.',
        texture: sleeve,
        camera: 'Collage group portrait composition.',
        mood: 'ironic tropical exuberance',
        render: 'Faithful Tropicália collage cover design.',
        key: 'Tropicália collage; tropical kitsch; psychedelic lettering',
        briefs: [
          'A tropical kitsch collage shows an original band in odd costumes holding bananas, a parrot and a toy airplane in front of a painted beach, psychedelic lettering "BANANA SATELLITE" and band "OS PAPAGAIOS" set exact.',
          'A collage of palm trees and television sets frames a singer in a sequin cape, title "SOL DE PLÁSTICO" set exact.',
          'A single pineapple wearing round sunglasses sits on a velvet chair in a tropical kitsch collage of parrots and palms, title "FRUTA PROIBIDA" set exact.',
        ],
      },
    ),
    cr(
      'Blaxploitation 1973 - Painted Funk Soundtrack Cover',
      'album cover design',
      [...T, 'blaxploitation'],
      {
        ...P,
        look: 'Seventies blaxploitation soundtrack cover look: painted action montage, heroic figures in leather coats and afros, city skylines, fiery orange and purple and bold funky type.',
        subject: 'paint the subject as a heroic seventies action montage with funky type.',
        color: 'Fiery orange, purple and gold.',
        light: 'Dramatic painted sunset light.',
        texture: sleeve,
        camera: 'Painted montage with a heroic central figure.',
        mood: 'cool heroic funk',
        render: 'Faithful seventies soundtrack cover painting.',
        key: 'Blaxploitation painted montage; afros; funky type',
        avoid: ['real actors from seventies films'],
        briefs: [
          'A painted action montage shows an original private eye in a long leather coat and afro striding past a burning purple city skyline, bold funky title "HARLEM HEAT WAVE" and composer credit "MUSIC BY DEX HOLLOWAY" set exact.',
          'A painted car chase races through city streets under a fiery orange sky with a helicopter overhead, title "UPTOWN GETAWAY" set exact in bold funky letters.',
          'A lone saxophone glows gold in a painted rain-soaked alley, title "COOL IN THE STORM" set exact.',
        ],
      },
    ),
    cr(
      'CTI Records - Pete Turner Saturated Photo Cover',
      'album cover design',
      [...T, 'cti-records'],
      {
        ...P,
        look: 'CTI Records gatefold look of the 1970s: Pete Turner hyper-saturated color photographs of surreal landscapes and objects, minimal clean type and luxurious laminated finish.',
        subject: 'render the subject as a hyper-saturated surreal color photograph.',
        color: 'Hyper-saturated sunset orange, electric blue and magenta.',
        light: 'Intense saturated photographic light.',
        texture: 'Glossy laminated gatefold sleeve.',
        camera: 'Bold graphic photo with minimal type.',
        mood: 'smooth luxurious cool',
        render: 'Faithful seventies CTI gatefold design.',
        key: 'CTI Pete Turner saturated photo; minimal type',
        avoid: ['the real CTI logo'],
        briefs: [
          'A hyper-saturated photograph of a single red umbrella standing in an electric blue desert under a magenta sky fills a glossy gatefold, minimal title "DESERT RAIN" and artist "MILO FONTAINE" set exact.',
          'A giraffe silhouette crosses a blazing orange sun in saturated photographic color, title "LONG NECK BLUES" set exact.',
          'A saturated photo of a glass of water on a hot highway shimmers, title "MIRAGE" set exact.',
        ],
      },
    ),
    cr('ECM Records - Minimal Atmospheric Photo Cover', 'album cover design', [...T, 'ecm'], {
      ...P,
      look: 'ECM Records cover look from the 1970s onward: minimal atmospheric landscape photographs, fog, water and emptiness, small refined sans-serif type and quiet Nordic restraint.',
      subject:
        'reduce the subject to a small presence in a minimal foggy atmospheric landscape photograph.',
      color: 'Muted greys, cold blues and pale white.',
      light: 'Soft fog and diffuse northern light.',
      texture: sleeve,
      camera: 'Wide empty landscape with small refined type.',
      mood: 'quiet contemplative space',
      render: 'Faithful ECM-style minimal cover design.',
      key: 'ECM minimal fog photo; small type; restraint',
      avoid: ['the real ECM logo'],
      briefs: [
        'A minimal foggy photograph of a lone wooden pier vanishing into grey water fills the cover, with small refined type "NORTHERN SILENCE" and artist "INGRID HALVORSEN" set exact in the corner.',
        'A blurred photo of snow falling on a dark lake, title "WINTER LIGHT" set exact in small grey letters.',
        'A single leafless tree stands on a white foggy horizon above a frozen field, title "HORIZON STUDIES" set exact in small refined grey letters in the corner.',
      ],
    }),
    cr(
      'Def Jam 1986 - Black-and-White Hip-Hop Photo Cover',
      'album cover design',
      [...T, 'def-jam-86'],
      {
        ...P,
        look: 'Mid-eighties hip-hop cover look: stark black-and-white street photography, crews in tracksuits and gold chains, boomboxes, big bold sans-serif and raw minimal design.',
        subject:
          'stage the subject in stark black-and-white eighties street photography with bold type.',
        color: 'Stark black and white with one red accent.',
        light: 'Hard flash and street daylight.',
        texture: sleeve,
        camera: 'Low street portrait with bold type.',
        mood: 'raw confident swagger',
        render: 'Faithful mid-eighties hip-hop cover design.',
        key: 'Eighties hip-hop black-and-white; tracksuits; boombox',
        avoid: ['real rappers', 'the real Def Jam logo'],
        briefs: [
          'A stark black-and-white street photo shows an original crew in tracksuits leaning on a boombox outside a Queens bodega, bold red title "BLOCK PARTY BUSINESS" and crew name "THE CORNER KINGS" set exact.',
          'A turntable on a milk crate in a black-and-white alley, title "SCRATCH AND SNIFF" set exact.',
          'A pair of fat-laced sneakers dangles from a power line, title "HIGH TOPS" set exact in bold white.',
        ],
      },
    ),
    cr(
      'Golden Age Hip-Hop 1994 - Gritty Street Portrait Cover',
      'album cover design',
      [...T, 'hiphop-94'],
      {
        ...P,
        look: 'Mid-nineties East Coast hip-hop cover look: gritty grainy color street photography, project courtyards, fisheye angles, baggy denim and muted urban tones.',
        subject:
          'stage the subject in gritty grainy nineties street photography with fisheye angles.',
        color: 'Muted urban brown, grey and faded denim.',
        light: 'Overcast street daylight.',
        texture: sleeve,
        camera: 'Fisheye low angles in project courtyards.',
        mood: 'gritty reflective hunger',
        render: 'Faithful mid-nineties hip-hop cover design.',
        key: 'Nineties hip-hop gritty photo; fisheye; projects',
        avoid: ['real rappers', 'a child photo superimposed over a skyline'],
        briefs: [
          'A grainy fisheye photograph of an original MC in a baggy denim jacket crouched on a project courtyard bench under grey skies, title "CONCRETE LULLABIES" and artist "YOUNG SAGE" set exact in small gritty type.',
          'A fisheye shot looks up at water towers on tenement roofs, title "HIGH RISE THOUGHTS" set exact.',
          'A worn notebook full of rhymes rests on an empty subway seat in grainy color light, title "THE LONG COMMUTE" set exact in small gritty type.',
        ],
      },
    ),
    cr('Pen & Pixel 1998 - Chrome Bling Rap Cover', 'album cover design', [...T, 'pen-and-pixel'], {
      ...P,
      look: 'Pen & Pixel Graphics Southern rap cover look of the late 1990s: over-the-top digital collage, chrome and gold 3D lettering, mansions, cars, flames, diamonds and maximal bling.',
      subject: 'stage the subject in over-the-top digital bling collage with chrome and gold.',
      color: 'Gold, chrome, fire orange and purple.',
      light: 'Glowing digital highlights and lens flares.',
      texture: 'Glossy late-nineties digital collage.',
      camera: 'Maximal crowded collage.',
      mood: 'over-the-top bling bravado',
      render: 'Faithful late-nineties Southern rap cover design.',
      key: 'Pen & Pixel chrome letters; bling collage; flames',
      avoid: ['real rappers', 'real label logos'],
      briefs: [
        'An over-the-top digital collage shows an original rapper in a gold suit on a mountain of diamonds before a flaming mansion and helicopters, chrome 3D title "BAYOU BILLIONAIRE" and name "LIL GUMBO" set exact.',
        'A golden tank with rims sits in front of a pyramid of money, title "RICH HISTORY" set exact in chrome.',
        'A diamond-encrusted crawfish glows in a lens flare above a gold swimming pool of champagne, title "SEAFOOD PLATINUM" set exact in chrome letters.',
      ],
    }),
    cr('Neo-Soul 2000 - Warm Film Intimacy Cover', 'album cover design', [...T, 'neo-soul'], {
      ...P,
      look: 'Late-nineties and 2000s neo-soul cover look: warm grainy film portraits, earth tones, head wraps and natural hair, soft window light and understated handwritten type.',
      subject: 'stage the subject as a warm intimate grainy film portrait in earth tones.',
      color: 'Warm earth brown, ochre and olive.',
      light: 'Soft warm window light.',
      texture: sleeve,
      camera: 'Intimate close portrait with handwritten type.',
      mood: 'warm intimate groove',
      render: 'Faithful neo-soul cover design.',
      key: 'Neo-soul warm film; earth tones; handwritten type',
      avoid: ['real singers'],
      briefs: [
        'A warm grainy film portrait of an original singer in a mustard head wrap sipping tea by a sunlit window, understated handwritten title "SUNDAY KITCHEN" and name "AMARA JOY" set exact.',
        'A close crop of hands holding a vinyl record in warm light, title "SLOW SPIN" set exact in handwriting.',
        'A potted fern and a Rhodes piano glow in afternoon sun, title "LIVING ROOM SESSIONS" set exact.',
      ],
    }),
    cr('Madlib Beat Tape - Lo-Fi Crate Collage Cover', 'album cover design', [...T, 'beat-tape'], {
      ...P,
      look: 'Underground beat tape cover look of the 2000s: lo-fi photocopied collage of found records, VHS stills, rubber stamps, cut-out type and dusty crate-digging texture.',
      subject: 'render the subject as a lo-fi photocopied collage of found images and stamps.',
      color: 'Faded photocopy grey, dusty ochre and one stamp red.',
      light: 'Flat photocopier light.',
      texture: 'Photocopy grain, torn tape and dusty paper.',
      camera: 'Layered collage composition.',
      mood: 'dusty crate-digging mystery',
      render: 'Faithful lo-fi beat tape cover design.',
      key: 'Beat tape collage; photocopy; found records',
      avoid: ['a stoned cartoon quasimoto character'],
      briefs: [
        'A lo-fi photocopied collage of a found kung fu movie still, a torn record label and a rubber stamp of a cassette, cut-out title "DUSTY FINGERS VOL. 3" and producer "BEAT LIBRARIAN" set exact.',
        'A VHS still of a weather map sits under a red stamp, title "SAMPLE WEATHER" set exact in cut-out letters.',
        'A photocopied crate of dusty records overflows the frame beside torn tape and a coffee stain, title "CRATE EXPECTATIONS" set exact in cut-out letters.',
      ],
    }),
    cr(
      'Bollywood Soundtrack 1975 - Painted Filmi LP Cover',
      'album cover design',
      [...T, 'bollywood-lp'],
      {
        ...P,
        look: 'Seventies Bollywood soundtrack LP look: hand-painted filmi montage of heroes and heroines, lush color, dramatic poses, decorative borders and ornate titles.',
        subject: 'paint the subject as a lush dramatic filmi montage with ornate borders.',
        color: 'Lush magenta, saffron, emerald and gold.',
        light: 'Dramatic painted spotlight glow.',
        texture: sleeve,
        camera: 'Montage of dramatic faces and scenes.',
        mood: 'lush melodramatic romance',
        render: 'Faithful seventies filmi soundtrack cover.',
        key: 'Bollywood painted montage; ornate border; filmi drama',
        avoid: ['real film stars'],
        briefs: [
          'A lush hand-painted filmi montage shows an original hero on a motorcycle and a heroine in a saffron sari against a painted mountain sunset, ornate title "DIL KI TRAIN" and composer credit "MUSIC: R. KAPOOR" set exact.',
          'A painted dance number fills a palace hall with twirling dancers, title "PALACE OF SONGS" set exact.',
          'A painted rose lies on a railway track at dawn as a steam train approaches through mist, title "FAREWELL PLATFORM" set exact in ornate filmi lettering.',
        ],
      },
    ),
    cr('Trojan Reggae 1970 - Roots Sound System Cover', 'album cover design', [...T, 'reggae-70'], {
      ...P,
      look: 'Seventies roots reggae and dub cover look: red, gold and green palettes, sound system speakers, hand-lettered titles, Jamaican street photos and dub-wise surreal illustration.',
      subject:
        'stage the subject with roots reggae color, sound system speakers and hand lettering.',
      color: 'Red, gold and green with deep black.',
      light: 'Sunny Kingston daylight.',
      texture: sleeve,
      camera: 'Poster-like frontal composition.',
      mood: 'warm rootsy groove',
      render: 'Faithful seventies roots reggae cover design.',
      key: 'Roots reggae colors; sound system; hand lettering',
      avoid: ['real reggae artists', 'the real Trojan label logo'],
      briefs: [
        'A towering hand-painted sound system of speaker boxes stands on a sunny Kingston street as children dance around it, hand-lettered red gold and green title "BASS FOR THE PEOPLE" and name "SELECTOR MAMA JOY" set exact.',
        'A dub-wise illustration shows a calm lion floating inside rings of echo over a green hillside, title "ECHO CHAMBER" set exact in red gold and green letters.',
        'A single speaker cone glows on a quiet beach at dusk while waves roll in slowly, title "SUNSET RIDDIM" set exact in hand-lettered red gold and green.',
      ],
    }),
  ],
};

export default spec;
