import type { Spec } from '../tools/apply';
import { ga, keep } from './_authors';

// Video game pass, sci-fi frontiers and mech zones: each preset names its game, studio and year
// and states the real render technique and camera. The drowned hall moves to SOMA because the
// art-deco undersea city already lives in the 2000s decade category.
const spec: Spec = {
  pack: 'pack_12',
  category: '3. Sci-Fi Frontiers & Mech Zones',
  updates: Object.fromEntries([
    ga('SP12-003', 'Deserts of Kharak 2016 - Blackbird Desert Carrier RTS', {
      look: 'Blackbird Interactive Homeworld: Deserts of Kharak (2016) look: real-time strategy across vast desert dunes, colossal land carriers, tracked vehicles leaving dust trails and buried alien wrecks.',
      subject:
        'render vehicles and people as small detailed military sci-fi units seen from a high strategy camera.',
      color: 'Desert ochre, dusty tan, steel grey and signal orange.',
      light: 'Harsh desert sun with long dune shadows and dust haze.',
      texture: 'Weathered industrial metal, sand drifts and dust trails.',
      camera: 'High tilted RTS camera over the dunes.',
      mood: 'vast lonely desert warfare',
      render: 'Authentic mid-2010s desert RTS screen.',
      key: 'Kharak land carriers; desert dunes; dust trails; RTS camera',
    }),
    ga('SP12-005', 'Alien Isolation 2014 - Creative Assembly Lo-Fi Dread', {
      look: 'Creative Assembly Alien: Isolation (2014) look: first-person survival horror on a 1979 lo-fi retro-futurist station, chunky CRT monitors, analog motion tracker, flickering corridors and film-grain dread.',
      subject:
        'render people as ordinary engineers and crew in worn seventies work clothes, seen from first person.',
      color: 'Sickly green CRT, emergency red, beige plastic and deep shadow.',
      light: 'Flickering fluorescents, emergency strobes and dark vents.',
      texture: 'Chunky beige plastic, grimy metal, film grain and VHS noise.',
      camera: 'First-person view holding an analog motion tracker.',
      mood: 'suffocating hunted dread',
      render: 'Authentic mid-2010s retro-futurist horror screen.',
      key: 'Alien Isolation lo-fi; motion tracker; CRT green; film grain',
      avoid: ['a black biomechanical alien with an elongated head'],
    }),
    ga('SP12-011', 'SOMA 2015 - Frictional Abyssal Station', {
      look: 'Frictional Games SOMA (2015) look: first-person horror inside a deep-sea research station, flooded industrial corridors, flickering lights, leaking bulkheads and dark abyssal ocean beyond thick windows.',
      subject:
        'render people and machines as uncanny figures in diving suits and cabled machinery, seen from first person.',
      color: 'Abyssal blue-black, sodium orange, rust and cold teal.',
      light: 'Flickering station lights and flashlight beams in dark water.',
      texture: 'Wet rusty metal, cables, algae and fogged glass.',
      camera: 'First-person view through flooded corridors.',
      mood: 'crushing existential dread',
      render: 'Authentic mid-2010s undersea horror screen.',
      key: 'SOMA undersea station; flooded corridors; abyss windows',
      briefs: [
        'Wading through a flooded pressure hall of an abyssal research station in first person, an original diver raises a flashlight as a hulking machine wearing an empty human diving suit stomps through the leaking bulkhead. No readable text or logo.',
        'In an undersea research station lobby, a proud founder bronze bust stands on its pedestal while a small octopus has settled comfortably on its head. No readable text or logo.',
        keep('SP12-011')[2],
      ],
    }),
    ga('SP12-018', 'Defense Grid 2008 - Hidden Path Tower Defense', {
      look: 'Hidden Path Entertainment Defense Grid: The Awakening (2008) look: elevated 3D tower defense on sci-fi citadels, glowing turret beams, alien walkers on winding paths and a glowing power core.',
      subject:
        'render every subject as tower-defense units, turrets and alien walkers seen from above.',
      color: 'Storm blue, turret orange, core cyan and steel grey.',
      light: 'Stormy dark sky with bright turret beams.',
      texture: 'Clean sci-fi metal and glowing energy.',
      camera: 'Elevated tower-defense camera over paths.',
      mood: 'tense strategic defense',
      render: 'Authentic late-2000s tower-defense screen.',
      key: 'Defense Grid turrets; alien walkers; glowing core',
    }),
    ga('SP12-023', 'Surviving Mars 2018 - Haemimont Retro-Future Colony', {
      look: 'Haemimont Games Surviving Mars (2018) look: retro-futurist colony builder on red Mars, glass domes linked by tubes, drones, rovers and optimistic fifties space-age design.',
      subject:
        'render people and machines as tiny colonists, drones and rovers among retro-futurist domes.',
      color: 'Mars red, dome glass teal and space-age white.',
      light: 'Dusty Mars daylight and dust storms.',
      texture: 'Clean retro-futurist panels and red dust.',
      camera: 'Overhead colony builder view.',
      mood: 'optimistic frontier building',
      render: 'Authentic colony builder screen.',
      key: 'Surviving Mars domes; retro-futurism; drones; red dust',
    }),
    ga('SP12-033', 'Plants vs Zombies 2009 - PopCap Cartoon Lawn', {
      look: 'PopCap Plants vs. Zombies (2009) look: bright cartoon lawn defense with grid rows, googly-eyed fighting plants, shambling goofy enemies and a suburban house at the left.',
      subject:
        'render every subject as a goofy cartoon plant or shambling cartoon enemy with big eyes.',
      color: 'Lawn green, sunny yellow and dusk purple.',
      light: 'Bright cartoon daylight or moonlight.',
      texture: 'Flat cartoon vectors with soft shading.',
      camera: 'Side-on lawn grid view.',
      mood: 'goofy spooky fun',
      render: 'Authentic casual cartoon defense screen.',
      key: 'PvZ lawn grid; goofy plants; cartoon defense',
      avoid: ['a green pea-shooting plant', 'existing zombie designs'],
    }),
    ga('SP12-042', 'Control 2019 - Remedy Brutalist Bureau', {
      look: 'Remedy Entertainment Control (2019) look: third-person paranormal action in a shifting brutalist government building, raw concrete, red astral corruption, telekinesis and floating debris.',
      subject: 'render people as calm bureau agents in plain office clothes wielding telekinesis.',
      color: 'Raw concrete grey, corruption red and fluorescent white.',
      light: 'Clean office light with red glowing corruption.',
      texture: 'Raw concrete, office clutter and particle debris.',
      camera: 'Third-person view in brutalist halls.',
      mood: 'uncanny bureaucratic dread',
      render: 'Authentic modern ray-traced action screen.',
      key: 'Control brutalism; telekinesis; red corruption; floating debris',
      avoid: ['a woman with a shape-shifting service weapon'],
    }),
    ga('SP12-045', 'Generation Zero 2019 - Avalanche Eighties Machine Hunt', {
      look: 'Avalanche Studios Generation Zero (2019) look: first-person survival in 1980s rural Sweden, pine forests, red wooden houses and retrofuturist hunting machines with searchlights.',
      subject:
        'render people as eighties Swedish survivors in windbreakers and denim, and machines as retrofuturist hunters.',
      color: 'Pine green, Swedish red cottage, grey sky and searchlight white.',
      light: 'Overcast Nordic light or dusk with machine searchlights.',
      texture: 'Realistic pine forest and rusted machine panels.',
      camera: 'First-person view hiding among trees.',
      mood: 'eerie rural invasion',
      render: 'Authentic open-world survival shooter screen.',
      key: 'Generation Zero machines; Swedish pines; eighties rural',
    }),
    ga('SP12-046', 'Sable 2021 - Shedworks Moebius Desert', {
      look: 'Shedworks Sable (2021) look: open desert rendered in clean Moebius-style line art with flat color, hoverbikes, ancient beast skeletons, mask culture and huge ruins.',
      subject: 'render people as clean-lined flat-color figures in masks and robes.',
      color: 'Pale sand, sky blue, sunset orange and flat pastel.',
      light: 'Flat shading with clean line art.',
      texture: 'Clean Moebius-style line and flat fills.',
      camera: 'Wide third-person desert view.',
      mood: 'serene coming-of-age wander',
      render: 'Authentic line-art open-world screen.',
      key: 'Sable Moebius lines; flat color; hoverbike desert',
    }),
    ga('SP12-068', 'Panzer Dragoon 1995 - Team Andromeda Saturn Rail Flight', {
      look: 'Team Andromeda Panzer Dragoon (1995) look: Sega Saturn on-rails flight in low-poly 3D with dithered textures, Moebius-inspired alien architecture, biomechanical creature design and hazy golden palettes.',
      subject:
        'render people and creatures as angular low-poly Saturn-era figures with Moebius costume lines and biomechanical shapes.',
      color: 'Canyon gold, ruin teal and hazy sky.',
      light: 'Hazy Saturn-era light and glowing lock-ons.',
      texture: 'Low-poly Saturn textures with dithering.',
      camera: 'On-rails flight view from behind and above the subject, with lock-on reticles.',
      mood: 'ancient mythic flight',
      render: 'Authentic Sega Saturn rail shooter screen.',
      key: 'Panzer Dragoon rails; low-poly Saturn; Moebius ruins',
      avoid: ['a blue armored dragon with a lone rider'],
    }),
    ga('SP12-119', 'Titanfall 2 2016 - Respawn Titan Cockpit', {
      look: 'Respawn Entertainment Titanfall 2 (2016) look: first-person view from inside a giant titan mech cockpit, canopy framing, HUD brackets, rain on the glass and industrial frontier cities.',
      subject:
        'render people as pilots inside mech cockpits and machines as colossal industrial walkers.',
      color: 'Industrial grey, cockpit amber and rain blue.',
      light: 'Cockpit instrument glow and rain light.',
      texture: 'Rain streaks, glass and worn industrial metal.',
      camera: 'First-person cockpit canopy view.',
      mood: 'heavy mechanical power',
      render: 'Authentic mid-2010s mech shooter screen.',
      key: 'Titanfall cockpit; mech canopy; rain glass',
      avoid: ['a titan with a single round blue eye'],
    }),
    ga('SP12-120', 'Prey 2017 - Arkane Talos Zero-G', {
      look: 'Arkane Studios Prey (2017) look: neo-deco space station interiors, zero-gravity drifting, shadowy shape-shifting aliens, wrenches and gloo, and Earth through large windows.',
      subject: 'render people as station crew in jumpsuits floating in zero gravity.',
      color: 'Neo-deco gold, walnut wood and space black.',
      light: 'Warm station light with cold space glow.',
      texture: 'Polished deco panels, walnut and brushed metal.',
      camera: 'First-person drifting view.',
      mood: 'paranoid weightless unease',
      render: 'Authentic immersive-sim screen.',
      key: 'Prey neo-deco station; zero gravity; alien shadows',
      avoid: ['black shadow mimic aliens'],
    }),
    ga('SP12-121', 'Stellaris 2016 - Paradox Orbital Planet View', {
      look: 'Paradox Development Studio Stellaris (2016) look: grand strategy planet view from orbit, glowing colony lights, sleek UI rings and route lines, deep space nebulae.',
      subject: 'render every subject as planets, colonies and fleets seen from orbit.',
      color: 'Deep space blue, colony gold and nebula violet.',
      light: 'Starlight rim on planets with glowing cities.',
      texture: 'Clean planet textures and soft nebulae.',
      camera: 'Orbital planet overview.',
      mood: 'vast galactic ambition',
      render: 'Authentic grand strategy planet screen.',
      key: 'Stellaris orbit; colony lights; route lines',
    }),
    ga('SP12-122', 'Everspace 2 2023 - Rockfish Asteroid Dogfight', {
      look: 'Rockfish Games Everspace 2 (2023) look: vivid space shooter among colorful nebulae and asteroid fields, chase camera behind small ships, flak bursts and salvage wrecks.',
      subject: 'render pilots and ships as small agile craft seen from a chase camera.',
      color: 'Vivid nebula magenta, amber flak and rock grey.',
      light: 'Nebula glow and bright weapon flashes.',
      texture: 'Detailed ship hulls and rocky asteroids.',
      camera: 'Chase camera between asteroids.',
      mood: 'daring space action',
      render: 'Authentic modern space shooter screen.',
      key: 'Everspace nebulae; asteroid dogfight; chase camera',
    }),
    ga('SP12-123', "No Man's Sky 2016 - Hello Games Pulp Planets", {
      look: "Hello Games No Man's Sky (2016) look: procedural alien planets in pulp sci-fi book cover colors, strange floating fauna, rovers, twin suns and saturated skies.",
      subject: 'render explorers and rovers as small figures under saturated alien skies.',
      color: 'Pulp magenta, lime and cyan skies.',
      light: 'Saturated alien sun with colored fog.',
      texture: 'Procedural stylized alien terrain.',
      camera: 'Wide photo-mode view.',
      mood: 'wondrous pulp exploration',
      render: 'Authentic procedural exploration screen.',
      key: "No Man's Sky pulp colors; alien fauna; rovers",
    }),
    ga('SP12-124', 'Armored Core VI 2023 - FromSoftware Mech Garage', {
      look: 'FromSoftware Armored Core VI: Fires of Rubicon (2023) look: heavy industrial mecha assembly, gantries, part swaps, sparks, grimy hangars and weathered paint.',
      subject: 'render mechs as heavy customizable industrial machines with modular parts.',
      color: 'Industrial grey, hazard yellow and spark orange.',
      light: 'Hangar floodlights with spark showers.',
      texture: 'Weathered paint, bolts and industrial metal.',
      camera: 'Low garage view up at a mech.',
      mood: 'heavy mechanical pride',
      render: 'Authentic modern mecha screen.',
      key: 'Armored Core garage; modular mech; industrial',
    }),
    ga('SP12-125', 'Starfield 2023 - Bethesda NASA-Punk Scanner', {
      look: 'Bethesda Game Studios Starfield (2023) look: NASA-punk space exploration, scanner visor overlay outlining alien flora and fauna, grounded spacesuits and alien planets.',
      subject: 'render people as explorers in grounded NASA-punk spacesuits scanning alien life.',
      color: 'Scanner cyan outlines over natural alien palettes.',
      light: 'Natural alien sunlight with scan glow.',
      texture: 'Realistic alien terrain and suits.',
      camera: 'First-person scanner visor view.',
      mood: 'curious scientific discovery',
      render: 'Authentic modern space RPG screen.',
      key: 'Starfield scanner; NASA-punk; alien flora',
    }),
    ga('SP12-126', 'Oxygen Not Included 2019 - Klei Colony Cutaway', {
      look: 'Klei Entertainment Oxygen Not Included (2019) look: side-view cartoon colony cutaway, tiny round-headed duplicants, pipes and gas overlays, cramped rooms and jaunty hand-drawn style.',
      subject: 'render people as tiny round-headed cartoon colonists with big eyes.',
      color: 'Muted earth, pipe teal and cartoon highlights.',
      light: 'Flat cartoon light in cutaway rooms.',
      texture: 'Hand-drawn Klei cartoon lines.',
      camera: 'Side-view colony cutaway.',
      mood: 'busy desperate charm',
      render: 'Authentic cartoon colony sim screen.',
      key: 'ONI cutaway; tiny colonists; pipes and rooms',
    }),
    ga('SP12-127', 'Lost Planet 2006 - Capcom Frozen Frontier', {
      look: 'Capcom Lost Planet: Extreme Condition (2006) look: third-person snowy alien planet, blizzards, thermal energy, giant bug creatures under the ice and heavy mech suits.',
      subject: 'render people as bundled survivors in heavy parkas and mech suits.',
      color: 'Ice white, orange thermal and steel grey.',
      light: 'Blizzard haze with orange thermal glow.',
      texture: 'Snow particles, ice and metal.',
      camera: 'Third-person view in snowstorms.',
      mood: 'frozen alien peril',
      render: 'Authentic late-2000s sci-fi shooter screen.',
      key: 'Lost Planet snow; giant bugs; thermal energy',
    }),
    ga('SP12-128', 'Gravity Rush 2012 - Project Siren Comic Gravity', {
      look: 'Project Siren Gravity Rush (2012) look: cel-shaded comic book gravity shifting, characters falling sideways, floating European town, comic panels and ink crosshatching.',
      subject:
        'render people as cel-shaded comic figures with flowing hair and clothing affected by shifting gravity.',
      color: 'Warm Euro-town ochre, sky blue and ink black.',
      light: 'Soft comic light with ink shadows.',
      texture: 'Cel shading with ink crosshatching.',
      camera: 'Tilted sideways gravity view.',
      mood: 'dreamy vertiginous freedom',
      render: 'Authentic comic cel-shaded screen.',
      key: 'Gravity Rush sideways gravity; comic cel; floating town',
      avoid: ['a blonde gravity shifter with a black cat'],
    }),
  ]),
};

export default spec;
