import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas print and engraving: fifteenth- and early sixteenth-century printmaking as
// drawing languages. Six originals get card briefs; fourteen new studies add criblé metalcuts,
// blockbooks, stencil-colored woodcuts, chronicle city views, dances of death, wonder broadsheets,
// card decks, niello, goldsmith ornament prints, armor etching, visionary woodcuts, lift-flap
// anatomies, printer's devices and paper volvelles.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'early-print', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'readable type or lettering', 'modern screen printing look', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original figures';

const spec: Spec = {
  pack: 'pack_23',
  category: '2. Print & Engraving',
  updates: {
    'SP23-007': { briefs: [
      'Carrying a woven hive through an orchard at night, a beekeeper realizes the swarm following her has formed the shape of a giant bear, cut in broad black relief masses and open gouged channels. No readable text or logo.',
      'Cut in bold blockprint shapes, a village baker proudly presents a loaf so large that it takes six people and a donkey to carry it out of the oven. No readable text or logo.',
      'In a relief print of heavy black and bare paper, a lone ferryman poles across a flooded field where the church steeple is the only thing still above the water. No readable text or logo.',
    ] },
    'SP23-008': { briefs: [
      'Settling onto a falconer\'s glove, a hawk carries back not a rabbit but a small screaming dragon, every feather and scale turned in fine controlled burin cross-hatching. No readable text or logo.',
      'Engraved in precise woven hatching, a very dignified hound sits for his portrait wearing the falconer\'s hat, while the falconer holds the dog\'s bone. No readable text or logo.',
      'In fine engraved lines that follow every fold, a knight kneels in a dark forest before a stag whose antlers hold a lit lantern between them. No readable text or logo.',
    ] },
    'SP23-009': { briefs: [
      'Beside a turning waterwheel, a miller lifts the sluice and a giant pike comes through with the flood, sketched in loose nervous etched lines that thicken into the churning water. No readable text or logo.',
      'Drawn in loose etched networks, a crowd of villagers argues over a single goose, which has quietly walked away through the middle of them. No readable text or logo.',
      "At night beside a dry riverbed, an abandoned mill creaks and its waterwheel keeps turning although there has been no water for years, drawn in restless nervous lines. No readable text or logo.",
    ] },
    'SP23-010': { briefs: [
      'Guiding his flock across a narrow footbridge, a shepherd does not notice that the last sheep is a wolf wearing a fleece, carved from dark masses opened by fine white lines. No readable text or logo.',
      'Opened out of deep black by fine white cuts, a proud rooster crows at the moon because he has mistaken it for the sun and is deeply confused why no one wakes. No readable text or logo.',
      'In a dark riverbank wood carved with thin light lines, a single lantern floats downstream on the water with no boat and no hand holding it. No readable text or logo.',
    ] },
    'SP23-011': { briefs: [
      'Over a crisp black relief print of a dragon attacking a town, a few hand-brushed tints of red and yellow have been added only to the flames, the rest left bare ink and paper. No readable text or logo.',
      'On a black relief print of a baker sliding loaves from a brick oven, loose hand tinting in ochre and rose has spilled a little outside the lines onto a surprised cat. No readable text or logo.',
      'In a woodcut of a night forest, only the eyes of the hidden creatures have been tinted by hand in pale green, dozens of them in the dark relief lines. No readable text or logo.',
    ] },
    'SP23-012': { briefs: [
      'In a black and white print of a battlefield after the fight, the only color is one warm red banner still standing upright in the center of the silent field. No readable text or logo.',
      'Among a grey crowd of identical sheep, one sheep has a single warm red scarf, and it looks extremely pleased with itself about it. No readable text or logo.',
      'In a dark ink drawing of an empty hallway, one door at the far end is marked with a single warm red handprint, the rest left in black and paper white. No readable text or logo.',
    ] },
  },
  creates: [
    study('Criblé Dotted Metalcut', 'dotted relief metal print', 'crible', {
      aesthetic: 'Criblé dotted metalcut: fifteenth-century relief prints cut in metal, dark grounds punched with thousands of tiny white dots and stars that sparkle around the figures.',
      subject_treatment: `${keep}; set the subject against a black ground punched with dense white dots.`,
      color_and_tone: 'Black ink and white paper, sometimes with a pale hand tint.',
      lighting_and_shadow: 'Sparkling dotted grounds that glow around dark-lined figures.',
      texture_and_material: 'Punched dots, star shapes, fine white lines and metal-cut edges.',
      camera_and_composition: 'Figures in the center with dotted grounds filling every space.',
      atmosphere_and_mood: 'Keep the requested mood with starry glittering mystery.',
      rendering_and_quality: 'Dense even dot patterns with clear figure silhouettes.',
      key_features: 'punched white dots; black ground; star punches; metal relief',
    }, [], [
      'Against a night ground punched with thousands of white dots, a giant moth-winged queen descends on a village while its tiny people run with candles. No readable text or logo.',
      'Surrounded by a sparkle of punched dots, a hedgehog proudly shows off his spines, which he believes are just as beautiful as the stars. No readable text or logo.',
      'In a black ground full of tiny white stars, a lone figure fishes from the edge of the world and has hooked one of the stars. No readable text or logo.',
    ]),
    study('Blockbook Picture Print', 'single-block picture book page', 'blockbook', {
      aesthetic: 'Blockbook picture print: pages cut entirely from a single woodblock, simple thick-lined figures and scenes in compartments with pale hand tints of green, red and yellow.',
      subject_treatment: `${keep}; draw the subject in simple thick outline shapes arranged in framed compartments.`,
      color_and_tone: 'Brown-black ink outlines with pale transparent hand tints.',
      lighting_and_shadow: "No shading, only outlines and flat tint, kept consistent across the whole image.",
      texture_and_material: 'Rubbed brown ink, soft paper, uneven tint washes.',
      camera_and_composition: 'Two or three framed picture compartments on a page.',
      atmosphere_and_mood: "Keep the requested mood with naive storytelling, kept consistent across the whole image.",
      rendering_and_quality: "Simple bold outline with clear readable action, kept consistent across the whole image.",
      key_features: 'thick outlines; framed compartments; pale tints; rubbed brown ink',
    }, [], [
      'In three framed compartments, a man swallows a fish, the fish swallows the man back, and in the last panel they sit together looking embarrassed. No readable text or logo.',
      'Across a woodblock page, a king orders a tower built to the moon, and in the final compartment the moon peers down into the unfinished top. No readable text or logo.',
      'In simple thick outline, a figure lies in bed while a smaller dark figure sits on his chest, and in the next compartment the bed is empty. No readable text or logo.',
    ]),
    study('Stencil-Colored Early Woodcut', 'stenciled color on woodcut', 'stencil-woodcut', {
      aesthetic: 'Stencil-colored early woodcut: simple fifteenth-century woodcut lines with color added through stencils in flat patches that slip out of register.',
      subject_treatment: `${keep}; give the subject simple woodcut lines with stenciled color blocks slightly off the lines.`,
      color_and_tone: 'Flat stenciled red, green, yellow and brown over black lines.',
      lighting_and_shadow: 'No shading; flat color blocks carry the design.',
      texture_and_material: "Rough paper, stencil edges and ink squeeze, kept consistent across the whole image.",
      camera_and_composition: 'Single central figure or scene with a simple frame line.',
      atmosphere_and_mood: 'Keep the requested mood with folk devotion and vigor.',
      rendering_and_quality: "Crude charming lines with misaligned color patches, kept consistent across the whole image.",
      key_features: 'stenciled color; slipped register; black woodcut lines; rough paper',
    }, [], [
      'In simple woodcut lines, a knight wrestles a giant crab on a beach while the red stencil color of his cloak has slipped onto the crab. No readable text or logo.',
      "Teaching a whole village how to dance, a bear in a green and yellow stenciled coat leads the circle while its colors land slightly beside its body like a shadow of paint. No readable text or logo.",
      'A pale sleeping figure lies in an early woodcut with a single stenciled patch of black-red color over the doorway behind them. No readable text or logo.',
    ]),
    study('Chronicle City Woodcut', 'woodcut panoramic city views', 'chronicle-city', {
      aesthetic: 'Chronicle city woodcut: crowded panoramic views of walled towns with spires, towers, bridges and rivers cut in lively lines for illustrated world chronicles.',
      subject_treatment: `${keep}; set the subject within or above a panoramic walled city of spires and towers.`,
      color_and_tone: 'Black ink lines with optional light hand coloring.',
      lighting_and_shadow: 'Parallel hatching on one side of buildings, open sky.',
      texture_and_material: 'Fine woodcut lines, crowded rooftops and wavy river lines.',
      camera_and_composition: "Wide elevated panorama of a walled town, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with busy civic pride.',
      rendering_and_quality: "Dense architectural detail with clear skyline, kept consistent across the whole image.",
      key_features: 'walled town panorama; spires; river bridge; woodcut hatching',
    }, ['readable banners'], [
      'Above a crowded walled city of spires, a comet with a long flaming tail hangs so low that the townspeople are climbing the towers to touch it. No readable text or logo.',
      'In a busy panoramic city of towers, one house has sprouted chicken legs and is trying to leave through the main gate. No readable text or logo.',
      'Seen from a hill, a walled town of spires sits silent at dawn with every door open and not a single person anywhere in its streets. No readable text or logo.',
    ]),
    study('Dance of Death Woodcut', 'macabre danse macabre print', 'dance-of-death', {
      aesthetic: 'Dance of death woodcut: grinning skeletons leading people of every station into a dance, lively macabre woodcut lines with dark humor.',
      subject_treatment: `${keep}; pair the subject with a dancing grinning skeleton in a lively woodcut scene.`,
      color_and_tone: 'Black ink on cream paper with deep blacks.',
      lighting_and_shadow: "Hatched shadows and stark silhouettes, kept consistent across the whole image.",
      texture_and_material: 'Fine woodcut lines, bone detail and rustling drapery.',
      camera_and_composition: 'Small framed scene of skeleton and victim in motion.',
      atmosphere_and_mood: 'Keep the requested mood with grim darkly comic inevitability.',
      rendering_and_quality: "Clear expressive figures with bony humor, kept consistent across the whole image.",
      key_features: 'dancing skeletons; framed scenes; macabre humor; woodcut hatching',
    }, ['gore'], [
      'In a tiny framed woodcut, a grinning skeleton politely takes a rich merchant by the hand, while another skeleton is already counting his coins. No readable text or logo.',
      'A skeleton plays the bagpipes at a village wedding, and the guests are dancing so happily they have not noticed the musician has no face. No readable text or logo.',
      'Walking beside a young painter, a patient skeleton holds up an hourglass and waits as she finishes one last brush stroke. No readable text or logo.',
    ]),
    study('Wonder Broadsheet Woodcut', 'sensational monster news prints', 'wonder-broadsheet', {
      aesthetic: 'Wonder broadsheet woodcut: sensational single-sheet prints reporting marvels, comets, monstrous fish and strange births, drawn in bold woodcut with awed crowds.',
      subject_treatment: `${keep}; present the subject as a shocking marvel witnessed by amazed onlookers.`,
      color_and_tone: 'Black ink with occasional bright hand-colored red and yellow.',
      lighting_and_shadow: 'Hatched shading and radiating lines around the marvel.',
      texture_and_material: 'Coarse woodcut lines, rough paper and ink smudges.',
      camera_and_composition: 'Large marvel in the center with small witnesses below.',
      atmosphere_and_mood: 'Keep the requested mood with breathless sensational wonder.',
      rendering_and_quality: "Bold readable marvel with naive exaggeration, kept consistent across the whole image.",
      key_features: 'central marvel; tiny witnesses; radiating lines; coarse woodcut',
    }, ['readable headlines'], [
      'Washed up on a beach, a monstrous fish wearing what looks like a bishop\'s hat is surrounded by awed fishermen, drawn in bold woodcut with radiating lines. No readable text or logo.',
      'Above a market square, a flying cow with angel wings has appeared, and the villagers are holding up buckets hoping for milk from the sky. No readable text or logo.',
      'Over a sleeping town, three suns rise at once, and only a single small child at a window has noticed. No readable text or logo.',
    ]),
    study('Hand-Stenciled Card Deck Print', 'early printed playing cards', 'early-cards', {
      aesthetic: 'Hand-stenciled card deck print: early woodcut playing cards with stiff court figures and pip patterns, colored through stencils in red, yellow and green.',
      subject_treatment: `${keep}; render the subject as a stiff court figure or pip design on an early playing card.`,
      color_and_tone: 'Black outlines with stenciled red, yellow, green and flesh tones.',
      lighting_and_shadow: "Flat with no shading, kept consistent across the whole image.",
      texture_and_material: 'Worn card stock, stencil edges and rubbed corners.',
      camera_and_composition: 'Single upright figure filling a narrow rounded card.',
      atmosphere_and_mood: 'Keep the requested mood with gamblers\' tavern charm.',
      rendering_and_quality: "Simple bold figure with stenciled patches, kept consistent across the whole image.",
      key_features: 'court figure; stenciled color; narrow card; pip patterns',
    }, ['modern card indices', 'readable letters'], [
      'On a worn early playing card, a stiff court king holds a sword in one hand and a very frightened chicken in the other, both stenciled in red and yellow. No readable text or logo.',
      'On a narrow card with rubbed corners, a queen of acorns stares seriously while a small squirrel steals the acorn pips from the edges. No readable text or logo.',
      'On a single faded card, a knave stands with his back turned, and his stenciled shadow on the card has a different, darker face. No readable text or logo.',
    ]),
    study('Niello Silver Plate', 'black-filled engraved silver', 'niello', {
      aesthetic: 'Niello silver plate: engraved silver with lines filled with black metal alloy, crisp black drawing sparkling against polished silver like a goldsmith\'s picture.',
      subject_treatment: `${keep}; engrave the subject in fine black-filled lines on a polished silver plate.`,
      color_and_tone: "Polished silver with deep black filled lines, kept consistent across the whole image.",
      lighting_and_shadow: 'Metallic reflections across silver with black line drawing.',
      texture_and_material: 'Engraved grooves, black niello fill and polished metal.',
      camera_and_composition: "Small plate or roundel filling the card, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with precious miniature intensity.',
      rendering_and_quality: "Crisp detailed engraving with bright silver, kept consistent across the whole image.",
      key_features: 'polished silver; black filled lines; small roundel; goldsmith detail',
    }, [], [
      'On a small silver roundel, a hunter blows a horn while a giant boar made of black-filled lines charges out of the metal toward him. No readable text or logo.',
      'Engraved in black on polished silver, a fox in a friar\'s robe preaches to a crowd of very attentive geese. No readable text or logo.',
      'On a tarnished silver plate, a black-lined woman looks into a hand mirror, and the silver shows only darkness where her reflection should be. No readable text or logo.',
    ]),
    study('Goldsmith Ornament Engraving', 'ornament print for craftsmen', 'ornament-engraving', {
      aesthetic: 'Goldsmith ornament engraving: model prints of curling foliage, thistle leaves and grotesque creatures engraved in fine lines for craftsmen to copy.',
      subject_treatment: `${keep}; weave the subject into curling engraved foliage and ornament.`,
      color_and_tone: "Black engraved lines on white paper, kept consistent across the whole image.",
      lighting_and_shadow: "Fine hatching models each curling leaf, kept consistent across the whole image.",
      texture_and_material: 'Burin lines, curling thistle foliage and paper white.',
      camera_and_composition: 'Vertical or horizontal ornament band with subject nested inside.',
      atmosphere_and_mood: 'Keep the requested mood with virtuoso decorative play.',
      rendering_and_quality: "Precise elegant curls with crisp modeling, kept consistent across the whole image.",
      key_features: 'curling thistle foliage; engraved lines; nested creatures; ornament band',
    }, [], [
      'Tangled in curling engraved thistle leaves, a wild man wrestles a lion whose tail has turned into foliage wrapping around them both. No readable text or logo.',
      'Hidden in an ornament of spiraling leaves, a small monkey sits on the tip of a curl eating a fruit that grows from the same engraved vine. No readable text or logo.',
      'In fine engraved foliage, a curling leaf opens into a face that is slowly closing its eyes as the vine winds around its mouth. No readable text or logo.',
    ]),
    study('Armor-Etcher Iron Plate', 'early etching on iron', 'iron-etching', {
      aesthetic: 'Armor-etcher iron plate: early etching bitten into iron plates, thick rough lines, corroded dark tone and uneven biting from armorers who made the first etched prints.',
      subject_treatment: `${keep}; bite the subject into iron with thick etched lines and rough corrosion.`,
      color_and_tone: 'Dark iron-black ink with grey corroded plate tone.',
      lighting_and_shadow: "Strong hatching with rough foul-biting in shadows, kept consistent across the whole image.",
      texture_and_material: 'Thick etched lines, pitted corrosion and irregular ink.',
      camera_and_composition: "Bold central figures with rough surrounding landscape, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with rugged martial intensity.',
      rendering_and_quality: "Coarse powerful lines with visible plate flaws, kept consistent across the whole image.",
      key_features: 'thick iron-etched lines; pitted corrosion; foul biting; martial detail',
    }, [], [
      'Bitten roughly into an iron plate, three mercenaries share one tiny cooking pot while their towering armored shadows loom behind them on the wall. No readable text or logo.',
      'In thick corroded etched lines, a peasant woman confidently leads a fully armored knight home by his ear. No readable text or logo.',
      'In a pitted etched landscape, a rusty suit of armor sits alone under a tree, and a bird flies in and out of the empty visor. No readable text or logo.',
    ]),
    study('Visionary Apocalypse Woodcut', 'dense visionary woodcut', 'visionary-woodcut', {
      aesthetic: 'Visionary apocalypse woodcut: dense dramatic late-medieval woodcuts full of swirling clouds, radiant beings, rushing riders and tiny figures below.',
      subject_treatment: `${keep}; set the subject in a dense turbulent woodcut vision of sky and earth.`,
      color_and_tone: 'Black ink and white paper with dense tonal hatching.',
      lighting_and_shadow: "Radiating light lines against dark swirling clouds, kept consistent across the whole image.",
      texture_and_material: 'Dense woodcut hatching, curling clouds and fine cuts.',
      camera_and_composition: 'Grand vertical composition with heavens above and small earth below.',
      atmosphere_and_mood: 'Keep the requested mood with overwhelming cosmic drama.',
      rendering_and_quality: "Virtuoso dense cutting with readable focal figures, kept consistent across the whole image.",
      key_features: 'swirling clouds; radiating light; rushing riders; tiny earth below',
    }, ['religious text'], [
      'From swirling woodcut clouds, four riders on huge beasts storm down toward a tiny town, one of the riders carrying an enormous pair of scales. No readable text or logo.',
      'Out of radiating clouds, a giant hand reaches down and very carefully picks up a tiny farmer who was only trying to finish plowing his field. No readable text or logo.',
      'In a vast sky of curling cut clouds, a door opens in the heavens and a staircase of light descends to a single sleeping shepherd. No readable text or logo.',
    ]),
    study('Lift-Flap Anatomy Sheet', 'layered paper anatomy print', 'flap-anatomy', {
      aesthetic: 'Lift-flap anatomy sheet: early printed anatomical sheets with paper flaps that lift to reveal organs and skeleton beneath, woodcut figures standing calmly.',
      subject_treatment: `${keep}; show the subject as a calm standing figure with lifting paper flaps revealing layers.`,
      color_and_tone: 'Black woodcut lines with pale hand tints on cream paper.',
      lighting_and_shadow: 'Flat woodcut with small cast shadows from raised flaps.',
      texture_and_material: 'Layered paper flaps, woodcut lines and hinged edges.',
      camera_and_composition: 'Single standing figure with flaps lifted partly open.',
      atmosphere_and_mood: 'Keep the requested mood with curious scientific wonder.',
      rendering_and_quality: "Clear diagrammatic figure, no graphic gore, kept consistent across the whole image.",
      key_features: 'lifting flaps; standing figure; revealed layers; woodcut lines',
    }, ['gore', 'readable labels'], [
      'Standing calmly on a woodcut sheet, a knight has his paper chest flap lifted to reveal that inside him is a small room where a tiny knight is steering. No readable text or logo.',
      'On an anatomy sheet with lifting flaps, a cat\'s belly flap opens to show it is entirely full of stolen fish. No readable text or logo.',
      'A calm woodcut figure stands with a paper flap lifted over her heart, revealing only a small closed door. No readable text or logo.',
    ]),
    study('Printer\'s Device Emblem', 'early printer mark emblem', 'printers-device', {
      aesthetic: 'Printer\'s device emblem: small symbolic woodcut marks used by early printers, anchors with dolphins, orbs with crosses, shields hung from trees, framed and compact.',
      subject_treatment: `${keep}; turn the subject into a compact symbolic emblem with a frame and simple charge.`,
      color_and_tone: 'Black woodcut on white, or white lines on black ground.',
      lighting_and_shadow: "Flat with small areas of hatching, kept consistent across the whole image.",
      texture_and_material: 'Crisp woodcut lines, black grounds and neat frames.',
      camera_and_composition: 'Centered emblem in a square or shield frame.',
      atmosphere_and_mood: 'Keep the requested mood with proud craftsman identity.',
      rendering_and_quality: "Clean compact symbol with confident cutting, kept consistent across the whole image.",
      key_features: 'compact emblem; black ground; symbolic charge; neat frame',
    }, ['initials or letters'], [
      'In a small woodcut emblem on black, a dolphin wraps around an anchor while a crab tries to pull the anchor away in the other direction. No readable text or logo.',
      'A compact emblem shows a shield hanging from a tree, and a very determined beaver is chewing through the trunk below it. No readable text or logo.',
      'In a square black emblem, a single hand holds out a candle toward a dark shape that is leaning closer to blow it out. No readable text or logo.',
    ]),
    study('Astronomical Volvelle Print', 'rotating paper disks print', 'volvelle', {
      aesthetic: 'Astronomical volvelle print: stacked rotating paper disks with pointers, moon faces, sun rays and zodiac creatures, printed and hand-colored for calculating the heavens.',
      subject_treatment: `${keep}; place the subject on or around layered rotating paper disks with pointers.`,
      color_and_tone: 'Black lines with hand-colored gold, blue and red disks.',
      lighting_and_shadow: "Small shadows between stacked paper disks, kept consistent across the whole image.",
      texture_and_material: 'Layered paper disks, thread pivots and printed rings.',
      camera_and_composition: "Circular disks filling the card from above, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with clever cosmic machinery.',
      rendering_and_quality: "Precise concentric rings with clear pointers, kept consistent across the whole image.",
      key_features: 'rotating disks; pointers; moon faces; concentric rings',
    }, ['readable numbers or letters'], [
      'On a stack of rotating paper disks, a tiny astronomer rides the pointer like a horse, chasing the moon face around the outer ring. No readable text or logo.',
      'On a hand-colored volvelle, the printed sun has grown tired of turning and is lying down across the disk to take a nap. No readable text or logo.',
      'On layered paper disks threaded through the center, the pointer has stopped at an unmarked black ring and the moon face is looking away in fear. No readable text or logo.',
    ]),
  ],
};

export default spec;
