import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID as AVOID, style } from './_style';

const spec: Spec = {
  pack: 'pack_10',
  category: '1. Geometric Abstraction',
  updates: {
    'SP10-001': {
      dna: style(
        'Analytic-synthetic Cubism: forms broken into faceted planes seen from several viewpoints at once.',
        'the subject is fractured into overlapping angular planes showing front and profile simultaneously, reassembled into a shallow space.',
        'Muted ochre, grey, olive and brown with occasional collage-like color blocks.',
        'Light is flattened into tonal facets rather than a single source.',
        'Faceted planes, overlapping outlines and paint-like brushwork.',
        'Shallow, compressed picture plane with interlocking facets.',
        'Intellectual, restless, fragmented and dense.',
        'Painterly Cubist finish with clear facet edges.',
        'multiple viewpoints; faceted planes; shallow space; muted ochre-grey',
      ),
      avoid: AVOID,
      briefs: [
        'Cubist painting of a knight and his warhorse seen from front, side and above at once, faceted into ochre and grey planes, a broken lance cutting across. No text or logo.',
        'Cubist painting of an old alchemist at his table, bottles and face fractured into overlapping planes. No text or logo.',
        'Cubist painting of a dragon coiled around a tower, scales and stones merging into facets. No text or logo.',
      ],
    },
    'SP10-002': {
      dna: style(
        'Bauhaus design: primary shapes, clean grids, sans-serif-era modernism reduced to circle, square and triangle.',
        'the subject is simplified into circles, squares, triangles and bold bars arranged on a clean grid.',
        'Red, yellow, blue, black and off-white.',
        'Flat, shadowless color.',
        'Flat printed color with crisp geometric edges.',
        'Balanced asymmetric grid composition.',
        'Rational, bold, modern and clear.',
        'Crisp poster-like finish.',
        'circle square triangle; primary colors; clean grid; flat shapes',
      ),
      avoid: AVOID,
      briefs: [
        'Bauhaus composition of a knight on horseback reduced to circles, triangles and red, yellow and blue bars on off-white. No text or logo.',
        'Bauhaus composition of a castle and moon as squares and a yellow circle on a grid. No text or logo.',
        'Bauhaus composition of a raven made of black triangles and a red circle eye. No text or logo.',
      ],
    },
    'SP10-003': {
      dna: style(
        'Constructivism: dynamic diagonals, bold wedges and photomontage-free graphic propaganda energy.',
        'the subject is built from strong diagonal wedges, bars and circles pushing across the frame.',
        'Red, black and cream.',
        'Flat graphic contrast.',
        'Flat printed shapes with crisp edges.',
        'Steep diagonals and radiating wedges.',
        'Urgent, heroic, industrial and forceful.',
        'Bold print-like finish.',
        'dynamic diagonals; red wedges; black bars; cream ground',
      ),
      avoid: AVOID,
      briefs: [
        'Constructivist composition of a giant red wedge splitting a black castle, a tiny rider charging on a diagonal. No text or logo.',
        "Constructivist composition of a blacksmith's hammer and anvil as bold diagonals. No text or logo.",
        'Constructivist composition of a dragon as black bars and a red circle. No text or logo.',
      ],
    },
    'SP10-004': {
      dna: style(
        'Op Art: optical illusions of vibrating stripes, warped grids and moiré that make flat patterns seem to move.',
        'the subject is formed by bending black-and-white stripes or grids so it bulges or recedes optically.',
        'Black and white, sometimes one vibrating color pair.',
        'No light; illusion comes from pattern density.',
        'Precise stripes, checks and warped grids.',
        'Pattern fills the frame with the subject as distortion.',
        'Dizzying, hypnotic, precise and kinetic.',
        'Hard-edged precise finish.',
        'warped stripes; bulging grid illusion; black and white; vibration',
      ),
      avoid: AVOID,
      briefs: [
        "Op art composition where a knight's helmet appears only as a bulge in warped black-and-white stripes. No text or logo.",
        'Op art composition of a spiral staircase formed by bending concentric stripes. No text or logo.',
        'Op art composition of a snake made of vibrating checkerboard. No text or logo.',
      ],
    },
    'SP10-005': {
      name: 'De Stijl Grid',
      dna: style(
        'De Stijl grid: black orthogonal lines dividing white fields with a few primary color blocks.',
        'the subject is abstracted into an asymmetric grid of rectangles, with color blocks placed at its key parts.',
        'White fields, black lines, red, yellow and blue blocks.',
        'Flat, no shadows.',
        'Flat paint with crisp lines.',
        'Asymmetric orthogonal balance.',
        'Calm, pure, ordered and spiritual.',
        'Crisp flat finish.',
        'black orthogonal grid; primary blocks; white fields',
      ),
      avoid: AVOID,
      briefs: [
        'De Stijl grid composition of a castle gate: black lines and a red block for the door, a yellow block for the torch. No text or logo.',
        "De Stijl grid composition of a knight's shield and banner. No text or logo.",
        'De Stijl grid composition of a stained-glass window made of primary rectangles. No text or logo.',
      ],
    },
    'SP10-006': {
      dna: style(
        'Fractal geometry: self-similar recursive forms repeating at every scale.',
        'the subject is built from recursive self-similar branches, spirals or tiles repeating inward.',
        'Deep gradients of blue, violet, gold or fire tones.',
        'Glowing edges on recursive forms.',
        'Infinitely detailed recursive branching.',
        'Central spiral or branching recursion.',
        'Infinite, mesmerizing, mathematical and cosmic.',
        'Crisp high-detail digital finish.',
        'self-similar recursion; infinite branching; glowing gradients',
      ),
      avoid: AVOID,
      briefs: [
        'Fractal image of a dragon whose wings split recursively into smaller dragons, spiraling inward in gold and violet. No text or logo.',
        'Fractal image of a tree whose branches become castles repeating at every scale. No text or logo.',
        'Fractal image of a nautilus spiral of crowns. No text or logo.',
      ],
    },
    'SP10-007': {
      dna: style(
        'Low-poly abstraction: subjects built from flat-shaded triangles with visible facets.',
        'the subject is triangulated into flat-shaded polygons with no smoothing.',
        'Gradient-sampled flat colors across facets.',
        'Facet shading from one soft light.',
        'Flat triangular facets with crisp edges.',
        'Clean centered subject on a simple faceted ground.',
        'Modern, crystalline, clean and graphic.',
        'Crisp flat-shaded finish.',
        'flat-shaded triangles; visible facets; gradient colors',
      ),
      avoid: AVOID,
      briefs: [
        'Low-poly faceted image of a wolf howling on a triangulated rock under a faceted moon. No text or logo.',
        "Low-poly image of a knight's helmet in amber triangles. No text or logo.",
        'Low-poly image of a volcano castle at sunset. No text or logo.',
      ],
    },
    'SP10-008': {
      dna: style(
        'Suprematism: floating pure geometric shapes on a white void, weightless and non-objective.',
        'the subject is reduced to a few floating rectangles, circles and crosses drifting on white.',
        'Black, red, yellow, blue on white.',
        'Flat, no light.',
        'Flat painted shapes.',
        'Shapes floating diagonally in empty space.',
        'Spiritual, weightless, pure and radical.',
        'Clean painted finish.',
        'floating geometric shapes; white void; diagonal drift',
      ),
      avoid: AVOID,
      briefs: [
        'Suprematist composition of a castle reduced to a few floating black rectangles and a red circle on white. No text or logo.',
        'Suprematist composition of a falling knight as tilted bars. No text or logo.',
        'Suprematist composition of a ship as floating crosses. No text or logo.',
      ],
    },
    'SP10-009': {
      dna: style(
        'Islamic geometric pattern: star-and-polygon tessellations built from compass and straightedge.',
        'the subject is filled or outlined with interlaced star-and-polygon tessellation.',
        'Lapis blue, turquoise, gold, white and terracotta.',
        'Flat or tile-glaze sheen.',
        'Interlaced strapwork, stars and rosettes.',
        'Radial symmetric tessellation.',
        'Harmonious, infinite, sacred and precise.',
        'Precise, crisp geometric finish.',
        'star-and-polygon tessellation; interlaced strapwork; radial symmetry',
      ),
      avoid: [...AVOID, 'religious text'],
      briefs: [
        'Geometric pattern image of a falcon whose feathers are interlaced star tessellations in lapis and gold. No text or logo.',
        'Geometric pattern image of a dome interior built from rosettes. No text or logo.',
        'Geometric pattern image of a horse silhouette filled with turquoise star patterns. No text or logo.',
      ],
    },
    'SP10-010': {
      dna: style(
        'Voronoi: space divided into irregular cells around seed points, like cracked earth or cells.',
        'the subject is divided into Voronoi cells that follow its form, with thicker cell walls at contours.',
        'Organic gradient colors per cell.',
        'Soft shading inside each cell.',
        'Irregular cells with clean borders.',
        'Cellular fill across subject and ground.',
        'Organic, cellular, scientific and modern.',
        'Clean generative finish.',
        'Voronoi cells; seed points; cellular borders',
      ),
      avoid: AVOID,
      briefs: [
        'Voronoi image of a dragon skull built from irregular cells with thick borders along its contours. No text or logo.',
        'Voronoi image of a castle cracked into cells. No text or logo.',
        'Voronoi image of a turtle shell as cells. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Orphism Color Discs',
      domain: 'orphist color disc abstraction',
      tags: ['orphism', 'color-discs', 'geometric'],
      dna: style(
        'Orphism: rhythmic concentric color discs and arcs that pulse with simultaneous contrast.',
        'the subject emerges from overlapping concentric color discs and arcs.',
        'Saturated contrasting color rings.',
        'Light is color contrast itself.',
        'Painted concentric rings and arcs.',
        'Circular rhythms around the subject.',
        'Joyful, rhythmic, luminous and musical.',
        'Painterly flat finish.',
        'concentric color discs; simultaneous contrast; rhythmic arcs',
      ),
      avoid: AVOID,
      briefs: [
        'Orphist painting of a carousel with knights on horses dissolving into concentric color discs. No text or logo.',
        'Orphist painting of a sun rising over a castle as color rings. No text or logo.',
        'Orphist painting of a dancer made of arcs. No text or logo.',
      ],
    },
    {
      name: 'Futurist Force Lines',
      domain: 'futurist dynamism',
      tags: ['futurism', 'force-lines', 'geometric'],
      dna: style(
        'Futurist dynamism: repeated overlapping forms and force lines expressing speed and motion.',
        'the subject is repeated in successive overlapping positions with sharp force lines.',
        'Bright reds, blues and metallic greys.',
        'Dynamic light fragments.',
        'Repeated contours, force lines and fragmented planes.',
        'Diagonal motion across the frame.',
        'Fast, violent, mechanical and exhilarating.',
        'Energetic painted finish.',
        'repeated motion contours; force lines; diagonal speed',
      ),
      avoid: AVOID,
      briefs: [
        'Futurist painting of a charging knight on horseback repeated in overlapping positions with sharp force lines. No text or logo.',
        'Futurist painting of a dragon diving. No text or logo.',
        'Futurist painting of a sword swing. No text or logo.',
      ],
    },
    {
      name: 'Hard-Edge Painting',
      domain: 'hard-edge color field',
      tags: ['hard-edge', 'color-field', 'geometric'],
      dna: style(
        'Hard-edge painting: large flat color areas meeting at razor-sharp edges.',
        'the subject is simplified into a few large flat color shapes with crisp edges.',
        'Bold flat complementary colors.',
        'No shading.',
        'Flat opaque paint with razor edges.',
        'Large simple shapes filling the frame.',
        'Bold, calm, confident and modern.',
        'Clean flat finish.',
        'razor-sharp edges; flat color areas; bold simplicity',
      ),
      avoid: AVOID,
      briefs: [
        "Hard-edge painting of a knight's silhouette as one orange shape against a teal field and a white moon. No text or logo.",
        'Hard-edge painting of a tower and sun. No text or logo.',
        'Hard-edge painting of a crow on a branch. No text or logo.',
      ],
    },
    {
      name: 'Precisionism',
      domain: 'precisionist industrial geometry',
      tags: ['precisionism', 'industrial', 'geometric'],
      dna: style(
        'Precisionism: clean, sharp-edged geometric rendering of structures with smooth planes and crisp shadows.',
        'the subject is rendered as clean geometric volumes with smooth planes and precise shadows.',
        'Cool greys, soft blues and cream with sharp shadow shapes.',
        'Crisp directional sun with geometric shadows.',
        'Smooth painted planes without texture.',
        'Frontal or low-angle structural view.',
        'Calm, orderly, monumental and quiet.',
        'Precise smooth finish.',
        'smooth geometric planes; crisp shadows; industrial order',
      ),
      avoid: AVOID,
      briefs: [
        'Precisionist painting of a castle keep rendered as smooth geometric volumes with crisp shadows. No text or logo.',
        'Precisionist painting of a windmill and silos. No text or logo.',
        'Precisionist painting of a cathedral buttress. No text or logo.',
      ],
    },
    {
      name: 'Vorticism',
      domain: 'vorticist angular abstraction',
      tags: ['vorticism', 'angular', 'geometric'],
      dna: style(
        'Vorticism: hard angular machine-like forms spiraling into a vortex center.',
        'the subject is broken into hard angular shards converging into a vortex.',
        'Strong blacks, reds and ochres.',
        'Harsh contrast.',
        'Sharp angular shards.',
        'Vortex converging to a point.',
        'Aggressive, mechanical, energetic and harsh.',
        'Bold graphic finish.',
        'angular shards; vortex center; machine energy',
      ),
      avoid: AVOID,
      briefs: [
        'Vorticist painting of a battle of knights compressed into angular shards spiraling into a vortex. No text or logo.',
        'Vorticist painting of a lighthouse beam. No text or logo.',
        "Vorticist painting of a dragon's jaw. No text or logo.",
      ],
    },
    {
      name: 'Truchet Tile Weave',
      domain: 'truchet tile patterns',
      tags: ['truchet', 'tiling', 'geometric'],
      dna: style(
        'Truchet tiling: square tiles with quarter-circle or diagonal motifs that combine into flowing mazes.',
        'the subject emerges from a field of rotated Truchet tiles whose curves form its outline.',
        'Two- or three-color schemes.',
        'Flat, no shading.',
        'Tiled quarter-circle arcs.',
        'Grid of tiles filling the frame.',
        'Playful, maze-like, rhythmic and clever.',
        'Crisp graphic finish.',
        'Truchet quarter-circle tiles; emergent curves; grid',
      ),
      avoid: AVOID,
      briefs: [
        "Truchet tile image where a serpent's body emerges from rotated quarter-circle tiles. No text or logo.",
        'Truchet tile image of a castle outline. No text or logo.',
        "Truchet tile image of a knight's face. No text or logo.",
      ],
    },
    {
      name: 'Penrose Aperiodic Tiling',
      domain: 'aperiodic tiling',
      tags: ['penrose', 'aperiodic', 'geometric'],
      dna: style(
        'Penrose tiling: aperiodic kite-and-dart or rhombus tiling with five-fold symmetry.',
        'the subject is filled and outlined with aperiodic rhombus tiles.',
        'Two-tone or jewel palette per tile type.',
        'Flat or subtle tile sheen.',
        'Rhombus tiles with fine grout lines.',
        'Five-fold radial tiling.',
        'Mathematical, mysterious, ordered and unusual.',
        'Crisp precise finish.',
        'aperiodic rhombus tiling; five-fold symmetry',
      ),
      avoid: AVOID,
      briefs: [
        'Penrose tiling image of a star-shaped rose window. No text or logo.',
        'Penrose tiling image of a dragon egg. No text or logo.',
        "Penrose tiling image of a knight's shield. No text or logo.",
      ],
    },
    {
      name: 'Swiss Grid Composition',
      domain: 'Swiss grid design',
      tags: ['swiss-grid', 'modernism', 'geometric'],
      dna: style(
        'Swiss grid composition: strict modular grid, asymmetric layout, bold geometric image blocks without type.',
        'the subject is placed in a strict modular grid of image blocks and color fields.',
        'Red, black, white and one accent.',
        'Flat or photographic within blocks.',
        'Clean blocks with precise alignment.',
        'Asymmetric modular grid.',
        'Rational, clean, confident and modern.',
        'Crisp print finish.',
        'modular grid; asymmetric blocks; no type',
      ),
      avoid: AVOID,
      briefs: [
        'Swiss grid composition of a knight in cropped blocks — helmet, gauntlet and spur — on a strict red and white grid. No text or logo.',
        'Swiss grid composition of a castle. No text or logo.',
        'Swiss grid composition of a dragon eye. No text or logo.',
      ],
    },
    {
      name: 'String Art Geometry',
      domain: 'string art line geometry',
      tags: ['string-art', 'line-geometry', 'geometric'],
      dna: style(
        'String art: taut straight threads between pins forming curves by envelope.',
        'the subject is drawn by taut threads stretched between pins, curves emerging from straight lines.',
        'Bright thread colors on dark board.',
        'Soft light on threads.',
        'Taut threads, pins and board.',
        'Pinned outline with thread envelopes.',
        'Precise, handmade, delicate and mathematical.',
        'Crisp thread finish.',
        'taut threads; pin outlines; curve envelopes',
      ),
      avoid: AVOID,
      briefs: [
        'String art of a dragon made of gold threads stretched between pins on a black board. No text or logo.',
        'String art of a castle. No text or logo.',
        'String art of a moon and wolf. No text or logo.',
      ],
    },
    {
      name: 'Neo-Geo Minimalism',
      domain: 'neo-geo minimal geometry',
      tags: ['neo-geo', 'minimal', 'geometric'],
      dna: style(
        'Neo-geo minimalism: cool, slick geometric forms with fluorescent accents and industrial surfaces.',
        'the subject is reduced to slick geometric cells, bars and conduits.',
        'Fluorescent accents on grey and white.',
        'Clean flat light.',
        'Smooth industrial surfaces.',
        'Grid-based cells.',
        'Cool, detached, slick and ironic.',
        'Clean finish.',
        'geometric cells; fluorescent accents; industrial slick',
      ),
      avoid: AVOID,
      briefs: [
        'Neo-geo image of a castle reduced to grey cells connected by fluorescent orange conduits. No text or logo.',
        'Neo-geo image of a sword. No text or logo.',
        'Neo-geo image of a throne. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
