import type { Create, Dna, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';

// Sensor and technical imaging: each preset is one real instrument's output. The prompt subject keeps
// its geometry and pose; only the appearance becomes what that sensor records. Mechanics were checked
// against existing sensor presets (thermal, ironbow, night vision, lidar, SAR, sonar, MRI slice,
// ultrasound, Hubble, UV, Schlieren, camera trap, weather radar) so these add new instruments.
const AVOID = [...STYLE_AVOID, 'readable UI text', 'fake HUD clutter', 'medical gore'];

const words = (t: string) => t.split(/\s+/).filter(Boolean).length;
const pad = (t: string, min: number, tail: string) =>
  words(t) < min ? `${t.replace(/\.$/, '')}, ${tail}` : t;

function sensor(
  aesthetic: string,
  records: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  key: string,
): Dna {
  return {
    aesthetic,
    subject_treatment: `Keep the prompt subject's geometry, pose and setting; replace only its appearance with what this instrument records: ${records}`,
    color_and_tone: pad(color, 9, 'exactly as the instrument maps its signal.'),
    lighting_and_shadow: pad(light, 9, 'because the image shows signal, not ordinary light.'),
    texture_and_material: pad(texture, 9, 'as real instrument artifacts rather than decoration.'),
    camera_and_composition: pad(camera, 9, 'matching how this instrument actually frames data.'),
    atmosphere_and_mood: pad(mood, 8, 'coming from seeing what eyes cannot.'),
    rendering_and_quality:
      'Believable instrument output with correct signal logic, artifacts and resolution for that sensor.',
    key_features: key,
  };
}

const spec: Spec = {
  pack: 'pack_11',
  category: '6. Sensor And Technical Imaging',
  updates: {
    'SP11-034': {
      name: 'Dual-Energy Baggage X-Ray',
      dna: sensor(
        'Security baggage X-ray: dual-energy scan where organic materials read orange, metals blue and mixed materials green.',
        'a flat top-down transmission scan: dense metal in dark blue-black, organics in orange, mixed materials in green, overlapping objects adding density.',
        'Orange, green and blue-black on a pale background.',
        'No light; brightness is material density.',
        'Overlapping translucent layers with crisp metal edges and slight scan noise.',
        'Top-down scan of a case or container with contents packed together.',
        'Clinical, suspicious, revealing and tense.',
        'dual-energy colors; orange organics; blue metal; overlapping contents',
      ),
      avoid: AVOID,
      briefs: [
        "An old leather chest on a security belt reveals a coiled chain and a dagger in dark blue, a skull and candles in soft orange organic tones. No readable text or logo.",
        "A traveling trunk slides through the scanner showing folded armor plates in blue-black, a lute, a loaf of bread and one wrapped sword. No readable text or logo.",
        "A witch's satchel on the airport belt reveals a cat curled asleep in orange, glass vials in green and iron keys in deep blue. No readable text or logo.",
      ],
    },
    'SP11-035': {
      name: 'White-Hot Thermal Imager',
      dna: sensor(
        'White-hot thermal imager: greyscale heat image where warm bodies glow white through smoke and darkness, hottest spots flagged red.',
        'shown as heat: warm bodies bright white, cool surfaces dark grey, the hottest points tinted red, smoke and darkness ignored.',
        'Greyscale white-hot with a single red hot-spot overlay.',
        'Heat glows; no visible light or shadows.',
        'Soft thermal blur, low resolution and slight sensor noise.',
        'Handheld imager view with a centered crosshair.',
        'Urgent, tactical, eerie and tense.',
        'white-hot greyscale; red hottest spots; smoke transparency',
      ),
      avoid: AVOID,
      briefs: [
        "Through thick smoke in a burning hall, a rescuer carrying a wounded squire glows white while the walls stay cold grey. No readable text or logo.",
        "A dark forest at night reveals a hulking warm beast hiding behind the trees, its breath glowing white in the cold air. No readable text or logo.",
        "In a cold crypt one coffin lid glows faintly warm from something inside, while the skeletons around it stay black. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Neutron Radiography',
      domain: 'neutron imaging',
      tags: ['neutron', 'radiography', 'sensor'],
      dna: sensor(
        'Neutron radiography: an X-ray-like image with reversed logic, where metal turns see-through and organic or wet materials show dark.',
        'a greyscale transmission image in which metal casings fade to pale ghosts and wood, wax, water, leather and bone read dark and sharp.',
        'Greyscale with inverted material contrast.',
        'No light; density to hydrogen-rich materials.',
        'Fine grain and soft edges on metal.',
        'Frontal transmission view of a sealed object.',
        'Revealing, mysterious, scientific and quiet.',
        'metal transparent; organics dark; sealed contents',
      ),
      avoid: AVOID,
      briefs: [
        "A sealed iron reliquary turns almost transparent, revealing a dark mummified hand and a wax seal inside in reversed contrast. No readable text or logo.",
        "A steel helmet on a stand fades into a pale ghost while its leather straps and padding turn dark and dense. No readable text or logo.",
        "A locked iron treasure chest becomes faint and ghostly, water-swollen books and a wax candle standing out dark within. No readable text or logo.",
      ],
    },
    {
      name: 'Terahertz Package Scan',
      domain: 'terahertz imaging',
      tags: ['terahertz', 'scan', 'sensor'],
      dna: sensor(
        'Terahertz scan: a soft, blurry, low-resolution image that sees through paper, cloth and plastic but not metal or water.',
        'a soft false-color intensity map where cloth, paper and wood fade away and metal and wet objects show as bright solid shapes.',
        'Blue-to-yellow false-color intensity.',
        'No light; intensity is reflected terahertz signal.',
        'Blurry pixels, speckle and soft edges.',
        'Frontal scan of a person or package.',
        'Clinical, eerie, intrusive and quiet.',
        'sees through cloth; bright metal; soft blur',
      ),
      avoid: AVOID,
      briefs: [
        "A hooded pilgrim stands still while the robe dissolves into soft blur, revealing a hidden dagger, a chain of keys and a flask. No readable text or logo.",
        "A sealed envelope held up to the scanner turns nearly invisible, a silver ring glowing softly inside. No readable text or logo.",
        "A wooden marionette case fades away to reveal bright metal hinges, a coiled spring and a hidden coin in low-resolution blur. No readable text or logo.",
      ],
    },
    {
      name: 'Event Camera Sparse Pixels',
      domain: 'neuromorphic event sensor',
      tags: ['event-camera', 'motion', 'sensor'],
      dna: sensor(
        'Event camera: only changing pixels appear, as scattered colored dots along moving edges on a black or grey field.',
        'reduced to scattered brightness-change events along moving edges: red for darker, blue or green for brighter, still areas empty.',
        'Red and blue events on black or mid grey.',
        'No light; only change is recorded.',
        'Sparse dots, motion trails and noise speckles.',
        'Fixed sensor view of a moving scene.',
        'Ghostly, kinetic, abstract and technical.',
        'sparse events; moving edges only; red and blue dots',
      ),
      avoid: AVOID,
      briefs: [
        "A swordsman spins a blade in the dark and only its moving edges appear, as scattered red and blue dots on black. No readable text or logo.",
        "Hundreds of bats burst from a cave mouth at dusk, each flapping wing edge a flicker of red and blue points. No readable text or logo.",
        "A galloping horse and armored rider are traced in dense red and blue dots along their legs and cloak, dust kicking up as sparse specks. No readable text or logo.",
      ],
    },
    {
      name: 'Audio Spectrogram Imaging',
      domain: 'sound spectrogram',
      tags: ['spectrogram', 'sound', 'sensor'],
      dna: sensor(
        'Audio spectrogram: time runs left to right and frequency bottom to top, with sound energy as glowing color.',
        'drawn as sound energy in a spectrogram: harmonics as stacked lines, noise as clouds, silence dark.',
        'Magma or viridis color ramps on black.',
        'No light; brightness is sound energy.',
        'Harmonic stripes, noise clouds and pixel blocks.',
        'Wide horizontal time-frequency plot with no axis labels.',
        'Hidden, eerie, musical and precise.',
        'harmonic stripes; time-frequency; energy colors',
      ),
      avoid: AVOID,
      briefs: [
        "The harmonics of a tolling bell and a scream form the silhouette of a screaming skull in bright magma bands across time. No readable text or logo.",
        "A beast's roar appears as a low rumble band at the bottom and rising harmonic curves spreading upward like wings. No readable text or logo.",
        "A monastery choir's evenly stacked harmonics rise and fall like the arches and spires of a cathedral. No readable text or logo.",
      ],
    },
    {
      name: 'Infrared Reflectography',
      domain: 'art conservation imaging',
      tags: ['reflectography', 'conservation', 'sensor'],
      dna: sensor(
        'Infrared reflectography: a grey image of a painting that shows the hidden underdrawing and changed mind beneath the paint.',
        'the visible paint fades to grey, revealing the artist underdrawing: sketch lines, grid squares and corrections.',
        'Neutral greys with dark carbon lines.',
        'Even flat lighting.',
        'Faded paint, sketch lines and craquelure.',
        'Frontal view of a painting panel.',
        'Secretive, scholarly, quiet and revealing.',
        'underdrawing; corrections; grey paint layer',
      ),
      avoid: AVOID,
      briefs: [
        "An old painting of a saint fades to grey under infrared, revealing sketched underdrawing of a second figure the painter hid. No readable text or logo.",
        "A portrait of a noblewoman fades to soft grey, revealing a skull sketched in carbon beneath her smiling face. No readable text or logo.",
        "A gentle pastoral landscape of sheep and meadows fades to grey, revealing a sketched fortress and a gallows hidden beneath the painted grass. No readable text or logo.",
      ],
    },
    {
      name: 'Multispectral Palimpsest Imaging',
      domain: 'manuscript recovery imaging',
      tags: ['palimpsest', 'multispectral', 'sensor'],
      dna: sensor(
        'Multispectral palimpsest: false-color processed manuscript where scraped-off earlier writing and drawings show in red over the later text.',
        'shown as a recovered layer on parchment: the hidden older image in red or magenta, later marks in grey.',
        'Pale grey parchment with recovered red.',
        'Even flat lighting.',
        'Parchment fibers, erased ink and holes.',
        'Flat page view.',
        'Scholarly, secret, ancient and haunting.',
        'recovered red layer; grey later text; parchment',
      ),
      avoid: AVOID,
      briefs: [
        "A parchment page reveals an erased drawing of a beast devouring the sun reappearing in red beneath later brown ink. No readable text or logo.",
        "A scraped-away drawing of a walled city returns in magenta beneath the grey of the later page. No readable text or logo.",
        "A faint erased portrait of a crowned queen returns in red, her eyes crossing through the later marks. No readable text or logo.",
      ],
    },
    {
      name: 'Acoustic Camera Overlay',
      domain: 'sound source localization',
      tags: ['acoustic-camera', 'overlay', 'sensor'],
      dna: sensor(
        'Acoustic camera: an ordinary photo overlaid with colored sound hotspots showing where noise comes from.',
        'a normal photo with translucent sound-intensity blobs over the loud sources, red at the center fading to blue.',
        'Normal photo with red to blue overlay.',
        'Ordinary light plus overlay.',
        'Soft overlay blobs.',
        'Fixed camera view.',
        'Technical, revealing, strange and diagnostic.',
        'sound hotspots; photo overlay',
      ),
      avoid: AVOID,
      briefs: [
        "A dark stone hall shows a red sound hotspot glowing at a sealed wall where something inside is scratching. No readable text or logo.",
        "A blacksmith's forge is overlaid with red-hot sound hotspots on the hammer and anvil and softer blue at the bellows. No readable text or logo.",
        "An empty candlelit corridor shows a red sound hotspot hanging in mid-air at head height, where weeping comes from nowhere. No readable text or logo.",
      ],
    },
    {
      name: 'MR Tractography',
      domain: 'diffusion MRI fiber tracking',
      tags: ['tractography', 'mri', 'sensor'],
      dna: sensor(
        'Tractography: bundles of fiber pathways color-coded by direction, glowing like silk threads.',
        'traced as bundles of streamlines color-coded by direction: red left-right, green front-back, blue up-down.',
        'Red, green and blue streamlines on black.',
        'Glow of streamlines.',
        'Fine silk-like strands.',
        'Isolated 3D subject on black.',
        'Intricate, beautiful, clinical and luminous.',
        'direction-coded streamlines; fiber bundles',
      ),
      avoid: AVOID,
      briefs: [
        "Glowing fiber streamlines trace the body and wings of a sleeping serpent, color-coded red, green and blue by direction. No readable text or logo.",
        "A crowned human head in profile glows with fiber streamlines through the brain in red, green and blue. No readable text or logo.",
        "A war horse in motion is rendered as muscle fiber streamlines along its neck and legs, colored by direction like silk. No readable text or logo.",
      ],
    },
    {
      name: 'EBSD Crystal Map',
      domain: 'crystal orientation mapping',
      tags: ['ebsd', 'microscopy', 'sensor'],
      dna: sensor(
        'EBSD map: metal grains shown as a mosaic of flat colored patches by crystal orientation.',
        'broken into grains colored by crystal orientation: flat rainbow patches with sharp grain boundaries.',
        'Pastel rainbow orientation colors.',
        'No light.',
        'Grain boundaries and flat patches.',
        'Flat map view.',
        'Precise, scientific, colorful and strange.',
        'grain mosaic; orientation colors',
      ),
      avoid: AVOID,
      briefs: [
        "A sword blade cross-section becomes a rainbow mosaic of flat crystal grains, the forge-folded layers visible as bands. No readable text or logo.",
        "A cross-section of an old gold crown shows its grains as a mosaic of flat rainbow patches, a jewel socket at the edge. No readable text or logo.",
        "A polished slice of iron meteorite reveals large interlocking crystal bands in pastel orientation colors, each grain a flat patch of its own hue. No readable text or logo.",
      ],
    },
    {
      name: 'Atomic Force Microscope Topography',
      domain: 'nanoscale surface topography',
      tags: ['afm', 'nanoscale', 'sensor'],
      dna: sensor(
        'AFM topography: a nanoscale surface shown as a 3D height map with a gold-brown color ramp.',
        'rendered as a height map: hills and pits from nanoscale scanning, with scan lines.',
        'Gold-brown height ramp.',
        'Virtual side light on height map.',
        'Scan lines and artifacts.',
        'Oblique 3D height view.',
        'Precise, alien, tiny and strange.',
        'height map; scan lines; gold ramp',
      ),
      avoid: AVOID,
      briefs: [
        "At nanoscale, molecules on a surface form a castle on a hill, rendered as a gold-brown height map at an oblique angle. No readable text or logo.",
        "A strand of DNA coils across a surface like a serpent, its height rising in a gold-brown ramp. No readable text or logo.",
        "A crystal surface rises in stepped terraces like a ruined amphitheater on a gold-brown height map. No readable text or logo.",
      ],
    },
    {
      name: 'Fluoroscopy',
      domain: 'live X-ray video',
      tags: ['fluoroscopy', 'x-ray', 'sensor'],
      dna: sensor(
        'Fluoroscopy: live X-ray video frame, grainy greyscale with dark bones and a circular field.',
        'shown as a grainy live X-ray frame: bones and dense objects dark, soft tissue faint, motion blur.',
        'Greyscale inverted.',
        'No light.',
        'Grain and blur.',
        'Circular field.',
        'Clinical, live, eerie and intimate.',
        'circular field; grainy live X-ray',
      ),
      avoid: AVOID,
      briefs: [
        "An armored hand grips a sword hilt, dark bones visible inside a faint metal gauntlet in a grainy circular field. No readable text or logo.",
        "A cat mid-leap shows its spine and legs dark and crisp, fur a faint haze, motion blur in the grainy circle. No readable text or logo.",
        "A swallowed iron key sits dark and sharp inside a faint stomach outline, ribs and spine soft grey around it. No readable text or logo.",
      ],
    },
    {
      name: 'Water Vapor Satellite Imagery',
      domain: 'meteorological satellite',
      tags: ['water-vapor', 'satellite', 'sensor'],
      dna: sensor(
        'Water vapor satellite image: swirling moisture in the upper atmosphere shown in grey or blue-orange false color.',
        'seen from orbit as water vapor: moist swirls bright, dry slots dark, jet streams and storms.',
        'Grey or blue-orange false color.',
        'No light.',
        'Swirls, filaments and coastlines.',
        'Top-down satellite view.',
        'Vast, turbulent, moody and planetary.',
        'vapor swirls; dry slots; storms',
      ),
      avoid: AVOID,
      briefs: [
        "A vast storm swirl coils over a continent in the shape of a sea serpent, bright moist swirls against dark dry slots. No readable text or logo.",
        "A hurricane with a clear eye spins its spiral bands in bright moisture against dark dry air. No readable text or logo.",
        "Seen from orbit, jet stream ribbons wrap around a continent like serpents, bright moisture filaments glowing against deep dark slots of dry air. No readable text or logo.",
      ],
    },
    {
      name: 'Mass Spectrometry Imaging',
      domain: 'molecular distribution map',
      tags: ['mass-spec', 'imaging', 'sensor'],
      dna: sensor(
        'Mass spectrometry imaging: pixelated maps of where molecules sit in a tissue slice, hot colors on black.',
        'mapped as molecular distribution: pixelated hot-colored patches on black.',
        'Hot colormap on black.',
        'No light.',
        'Pixelated maps.',
        'Flat slice.',
        'Scientific, abstract, precise and hidden.',
        'pixelated molecule map; hot colors',
      ),
      avoid: AVOID,
      briefs: [
        "A plant slice shows one molecule distributed in the shape of a crowned serpent in pixelated hot colors. No readable text or logo.",
        "A mushroom slice glows with molecules mapped in pixelated hot colors, gills yellow and cap cool blue. No readable text or logo.",
        "One molecule gathers along a leaf's veins in hot orange pixels, forming a tree shape on dark ground. No readable text or logo.",
      ],
    },
    {
      name: 'Streak Camera Image',
      domain: 'ultrafast streak imaging',
      tags: ['streak-camera', 'ultrafast', 'sensor'],
      dna: sensor(
        'Streak camera: one line of space smeared across time into a glowing streak pattern.',
        'turned into streaks: a single line of space stretched over time.',
        'Glowing green or false color on black.',
        'Streak glow.',
        'Smeared streaks.',
        'Horizontal streak.',
        'Fast, abstract, scientific and eerie.',
        'space-time streak',
      ),
      avoid: AVOID,
      briefs: [
        "A lightning strike on a tower is smeared across time into a glowing green streak on black. No readable text or logo.",
        "An explosion in a powder room is caught through a single slit and smeared into fanning green time streaks. No readable text or logo.",
        "A laser pulse passes through a crystal, a thin bright streak splitting into colored lines across black. No readable text or logo.",
      ],
    },
    {
      name: 'Endoscopy Capsule View',
      domain: 'capsule camera',
      tags: ['endoscopy', 'capsule', 'sensor'],
      dna: sensor(
        'Capsule endoscopy: a fisheye camera view with ring light inside a wet tunnel, pink and glossy.',
        'seen from a tiny capsule camera: fisheye tunnel, ring light, wet glossy walls.',
        'Pinks and reds with glossy highlights.',
        'Ring light.',
        'Wet glossy walls.',
        'Fisheye tunnel.',
        'Claustrophobic, intimate, strange and alien.',
        'fisheye; ring light; wet tunnel',
      ),
      avoid: AVOID,
      briefs: [
        "A fisheye view inside a wet stone tunnel beneath a castle glints with ring light on glossy walls, a tiny lantern ahead. No readable text or logo.",
        "A fisheye view looks down the throat of a sleeping dragon, ring light glinting on glossy red walls and ridged scales. No readable text or logo.",
        "A fisheye view inside an old copper pipe shows green corrosion and water drops glinting in the ring light. No readable text or logo.",
      ],
    },
    {
      name: 'Radio Telescope Intensity Map',
      domain: 'radio astronomy',
      tags: ['radio-telescope', 'astronomy', 'sensor'],
      dna: sensor(
        'Radio telescope map: blurry false-color radio emission with lobes and jets.',
        'mapped as radio emission: blobs, lobes, jets and contour lines.',
        'False-color on black.',
        'No light.',
        'Blurry emission and contours.',
        'Sky map.',
        'Cosmic, mysterious, scientific and vast.',
        'radio lobes; jets; contours',
      ),
      avoid: AVOID,
      briefs: [
        "Spreading like the wings of a great bird, the twin lobes of a distant galaxy glow in blurry false-color emission wrapped in contour lines. No readable text or logo.",
        "A pulsar and its wind nebula glow like a lighthouse beam in false-color emission and contour rings. No readable text or logo.",
        "A nebula's false-color emission blobs form a hooded figure bowing its head, soft contour lines around it. No readable text or logo.",
      ],
    },
    {
      name: 'Solar H-Alpha Telescope',
      domain: 'solar telescope',
      tags: ['h-alpha', 'sun', 'sensor'],
      dna: sensor(
        'H-alpha solar telescope: the sun in deep red-orange with prominences and filaments.',
        'shown in H-alpha: red-orange disk, prominences, filaments and granular texture.',
        'Red-orange on black.',
        'Solar glow.',
        'Granulation and filaments.',
        'Sun disk or limb.',
        'Fiery, vast, cosmic and dramatic.',
        'prominences; filaments; red disk',
      ),
      avoid: AVOID,
      briefs: [
        "At the sun's limb a huge prominence rears up in deep red-orange like a beast about to strike. No readable text or logo.",
        "A large sunspot with a dark umbra and fibrous penumbra stares out like an eye from red-orange granulation. No readable text or logo.",
        "Dark filaments snake across the full red solar disk, bright plage around them and prominences flickering on the limb. No readable text or logo.",
      ],
    },
    {
      name: 'All-Sky Meteor Camera',
      domain: 'fisheye night sky camera',
      tags: ['all-sky', 'meteor', 'sensor'],
      dna: sensor(
        'All-sky camera: a circular fisheye night sky with meteor streaks, horizon ring and trees.',
        'seen from an all-sky camera: circular fisheye, horizon at the rim, meteors and stars.',
        'Dark blue night with white streaks.',
        'Starlight.',
        'Noise, star trails.',
        'Circular fisheye.',
        'Vast, quiet, cosmic and watchful.',
        'circular fisheye; meteor streaks',
      ),
      avoid: AVOID,
      briefs: [
        "A circular fisheye night sky is ringed by dark pines and a stone tower at the rim, a bright fireball crossing the center. No readable text or logo.",
        "Green and violet aurora curtains fill the fisheye circle above pine silhouettes and a stone watchtower. No readable text or logo.",
        "A long exposure shows dozens of meteor streaks radiating from one point inside a circular horizon of mountains. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
