import type { Spec } from '../tools/apply';
import { design } from './_design';

// Game UI, HUDs & screen graphics (part A): R-HUD-01..10. Readouts stay exact; the style changes how they are built.
const H = (
  source: string,
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof design>[4],
  avoid: string[],
  briefs: [string, string, string],
  kind: 'style' | 'modifier' | 'profile' = 'style',
) => design(name, domain, tag, 'hud', fields, avoid, briefs, { text: true, source, kind });

const spec: Spec = {
  pack: 'pack_25',
  category: '5. Game UI, HUDs & Screen Graphics',
  newCategory: { id: 'game-ui-huds-and-screen-graphics' },
  updates: {},
  creates: [
    H('R-HUD-01', 'Microfiche Telemetry', 'optical archive readout HUD', 'microfiche-telemetry', {
      aesthetic: 'Microfiche Telemetry: readouts shown through optical reading windows and stacked film registers, with slight offsets that give the data a physical body.',
      subject_treatment: "Arrange the prompt's readouts in optical reading windows and stacked registers, keeping every active value, unit and label perfectly sharp and exact.",
      color_and_tone: 'Sober dark or light ground with one single tone for the active reading.',
      lighting_and_shadow: 'Soft backlit glow of the film support, with letters and marks kept crisp.',
      texture_and_material: 'Light optical grain and small offsets on secondary registers only, active text clean.',
      camera_and_composition: 'One dominant reading window, secondary indexes and subordinate archive zones.',
      atmosphere_and_mood: 'Tangible archive instrumentation with an old optical feel, calm and focused.',
      rendering_and_quality: 'Film defects never touch values, units or data relationships.',
      key_features: 'optical reading windows; stacked registers; film grain on support; sharp values',
    }, ['noise over numbers', 'decorative reticles', 'illegible micro text'], [
      'The HUD of a deep-time archaeologist robot digging through a buried city: "POWER 68%", "DEPTH 042 M" and "RELIC FOUND" in amber optical windows over charcoal film.',
      'An old ship\'s microfiche screen that only reports bad news, "RATIONS 12%", "MORALE LOW" and "CAPTAIN ASLEEP", stacked registers, pale blue on dark, very calm about it.',
      'A quiet explorer HUD with "RESERVE 42%" and "ROUTE C" in two optical windows of different size, a pale light ground and faint film edges.',
    ]),
    H('R-HUD-02', 'Capillary Diagnostics', 'branching flow channel HUD', 'capillary-diagnostics', {
      aesthetic: 'Capillary Diagnostics: branching channels and status reservoirs show connection and flow, their thickness following hierarchy.',
      subject_treatment: "Show the prompt's connected systems as branching channels feeding status reservoirs, thickness by hierarchy and only the links supplied; keep labels exact.",
      color_and_tone: 'Active, idle and reservoir states separated by shape and value as well as color.',
      lighting_and_shadow: 'Light contained inside the channels, each branch glowing on its own.',
      texture_and_material: 'Smooth surfaces and ducts of consistent thickness, graphic rather than anatomical.',
      camera_and_composition: 'Root, branches and destinations follow the given topology, labels clear of crossings.',
      atmosphere_and_mood: 'Controlled organic flow and a sense of interdependence, calm and legible.',
      rendering_and_quality: 'Every branch corresponds to one real link in the supplied data.',
      key_features: 'branching channels; status reservoirs; hierarchy by thickness; exact links',
    }, ['invented branches', 'reservoirs with no function', 'look of a real medical diagnosis'], [
      'The life-support HUD of a colony ship: one reservoir at 70% feeding "FARM", "LABS" and "SLEEP"; FARM and LABS active, SLEEP stopped, pale green channels on charcoal.',
      'A greenhouse game HUD where the main tank at 55% feeds two thirsty "TOMATOES" channels and one very dramatic "CACTUS" valve, closed, labels exact.',
      'A ship HUD with no ship shown: one core branching to "LIGHT", "AUDIO" and "MAP", MAP on standby, sober ducts and one coral accent.',
    ]),
    H('R-HUD-03', 'Mechanical Index Displays', 'discrete mechanical selector HUD', 'mechanical-index', {
      aesthetic: 'Mechanical Index Displays: index bands that click into discrete positions behind a stable reading window, like a mechanical selector.',
      subject_treatment: "Show the prompt's selection as bands locked into discrete positions with one stable reading window; keep every option name exact.",
      color_and_tone: 'Light values for the selection, neutrals for available positions and one alert accent.',
      lighting_and_shadow: 'Flat light with a tiny seating shadow where each band settles.',
      texture_and_material: 'Clean index surfaces, visible slots and well-defined position edges.',
      camera_and_composition: 'Selected reading centered in its window, neighbors clearly subordinate.',
      atmosphere_and_mood: 'Precise mechanical change and a firm pause, satisfying and exact.',
      rendering_and_quality: 'The active position has exactly one reading and never sits between two values.',
      key_features: 'index bands; discrete positions; reading window; firm selection',
    }, ['bands with no function', 'value between positions', 'excess decorative screws'], [
      'The spell-selector HUD of a battle mage: bands for "FIRE", "ICE", "STORM" and "HEAL" clicking into a reading window, STORM selected, black and bone with an orange alert.',
      'A mood selector on a robot butler\'s chest display: "POLITE", "SARCASTIC" and "PASSIVE AGGRESSIVE", with SARCASTIC locked in place, grey bands, deadpan.',
      'A route index for a hiking game with steps "01", "02" and "03", step 02 active and status "READY", pale grey bands.',
    ]),
    H('R-HUD-04', 'Etched Glass Instruments', 'etched glass instrument HUD', 'etched-glass', {
      aesthetic: 'Etched Glass Instruments: permanent scales etched into glass plates, with the active reading lit separately in front.',
      subject_treatment: "Etch the prompt's permanent scales into glass plates and show the active reading as a separate bright layer; keep every value and label exact.",
      color_and_tone: 'Low-contrast etched scales and higher-value active data in one light color.',
      lighting_and_shadow: 'Soft side light catching the glass edge, the front reading kept crisp.',
      texture_and_material: 'Sober glass with visible edge thickness and fine etching, clean and clear.',
      camera_and_composition: 'Frontal or near-frontal plates with aligned scales and undistorted data.',
      atmosphere_and_mood: 'Transparent precision and instrumental lightness, grounded and physical.',
      rendering_and_quality: 'Etching and live data never read as the same state.',
      key_features: 'etched scales; separate active reading; glass edge light; frontal plates',
    }, ['reflections over text', 'glass that warps values', 'ornamental scales'], [
      'The cockpit instrument of a glass airship: an etched 0 to 100 energy scale with the live reading "68" glowing in front, a soft edge light, storm clouds implied only by color.',
      'An etched-glass "PATIENCE" gauge on a dragon trainer\'s helmet, scale 0 to 10, current reading "2", very honest.',
      'A heading plate etched from 000 to 090 with the reading "042°" and the label "HEADING", charcoal ground and a soft glass edge.',
    ]),
    H('R-HUD-05', 'Woven Signal Panels', 'interwoven signal channel HUD', 'woven-signal', {
      aesthetic: 'Woven Signal Panels: parallel signal channels weave over and under each other with every crossing clearly resolved.',
      subject_treatment: "Route the prompt's signals in parallel channels that weave with resolved crossings, each traceable from source to destination; keep labels exact.",
      color_and_tone: 'Color per signal only when declared, weight and continuity carrying identity.',
      lighting_and_shadow: 'A discreet glow confined to the active channel only.',
      texture_and_material: 'Smooth strokes of related weight with visible crossing bridges.',
      camera_and_composition: 'Spaced crossings, supplied connectivity and a reading zone free of tangles.',
      atmosphere_and_mood: 'Ordered complexity with a textile cadence, rhythmic and clear.',
      rendering_and_quality: 'Every signal can be followed from origin to destination without doubt.',
      key_features: 'woven channels; resolved crossings; traceable signals; one active glow',
    }, ['invented links', 'unresolved crossings', 'textures that replace data'], [
      'The comms HUD of a rebel radio tower: signals "NORTH→A", "SOUTH→B" and "SEA→C" weaving over and under without touching, one coral channel active, pale ink on dark.',
      'A HUD for a DJ robot mixing "BIRDS" and "THUNDER" into "CHAOS", two channels weaving into one output, crossings clean and smug.',
      'A file route display with three independent paths P, Q and R woven to X, Y and Z, light ground, dark ink and generous gaps.',
    ]),
    H('R-HUD-06', 'Pressure-Chamber Readouts', 'connected chamber level HUD', 'pressure-chamber', {
      aesthetic: 'Pressure-Chamber Readouts: connected geometric chambers show levels through a clearly drawn fill surface and apparent volume.',
      subject_treatment: "Show the prompt's levels as connected chambers of simple geometry with a crisp fill line matching each supplied value; keep labels exact.",
      color_and_tone: 'Full, empty and limit separated by value and edge, solid and readable.',
      lighting_and_shadow: 'One soft common light on the volumes, marks and reading kept frontal.',
      texture_and_material: 'Smooth chambers of consistent wall thickness with minimal ducts.',
      camera_and_composition: 'Main and auxiliary chambers sized by the data, never by decoration.',
      atmosphere_and_mood: 'Contained pressure and stability, steady, legible and reassuring.',
      rendering_and_quality: 'Levels match the stated values and never change with perspective.',
      key_features: 'connected chambers; exact fill lines; geometric volumes; steady levels',
    }, ['misleading volume', 'decorative tanks', 'levels that differ from the data'], [
      'The survival HUD of a submarine sinking toward a trench: chambers "AIR 70%", "BALLAST 40%" and "HOPE 20%", amber and charcoal, fill lines exact.',
      'A bunker game HUD with "WATER 60%" and "SNACKS 35%" in separate chambers and a warning chamber labeled "BOREDOM 99%", clean and tongue-in-cheek.',
      'A calm mechanism HUD with a central tank at 50% and two helpers at 25%, one scale per chamber, pale green.',
    ]),
    H('R-HUD-07', 'Optical Ghost Registers', 'optical afterimage HUD modifier', 'optical-ghost', {
      aesthetic: 'Optical Ghost Registers: a modifier that adds faint afterimages behind the current readout, like an old optical display remembering itself.',
      subject_treatment: "Add a faint, slightly offset afterimage behind the prompt's existing readouts, keeping the current values locked, dominant and exact.",
      color_and_tone: 'Echoes lower in value and saturation than the active data.',
      lighting_and_shadow: 'Soft glow on the echo with the current reading kept crisp and clear.',
      texture_and_material: 'Light optical persistence with a small bounded offset and clean active letter edges.',
      camera_and_composition: 'Composition and data of the input kept exactly, no new positions.',
      atmosphere_and_mood: 'Subtle visual memory of an old optical system, calm and eerie.',
      rendering_and_quality: 'The current reading is identified before the echo is noticed.',
      key_features: 'faint afterimage; locked current values; small offset; old optics',
    }, ['double reading', 'ghosting over digits', 'invented historical data'], [
      'Optical ghosts added to the HUD of a starship that has been drifting for a century: "POWER 68%" sharp in front, a faint afterimage trailing behind it like a memory.',
      'A haunted arcade cabinet screen showing "HIGH SCORE" with a ghostly afterimage of someone else\'s name fading behind it, current text perfectly crisp.',
      'A calm reading "RESERVE 42%" on a light ground with a soft grey echo behind it, black text untouched.',
    ], 'modifier'),
    H('R-HUD-08', 'Porcelain Dial Console', 'pale porcelain dial HUD', 'porcelain-dial', {
      aesthetic: 'Porcelain Dial Console: pale enamel plates with fine-stroke dials and precise slots make a calm instrument with a few highlighted controls.',
      subject_treatment: "Arrange the prompt's readouts as fine-stroke dials and slots on pale plates, each linked to its label and value; keep every label and value exact.",
      color_and_tone: 'Bone or pale grey base, dark strokes and one accent for the active indicator.',
      lighting_and_shadow: 'Soft light across the plates with clean reflection-free reading areas.',
      texture_and_material: 'Sober glazed surface, rounded edges and precise slots.',
      camera_and_composition: 'Each dial tied to its label and value, with resting space between groups.',
      atmosphere_and_mood: 'Instrumental calm and clean tactility, gentle and precise.',
      rendering_and_quality: 'Only the graduations and units the brief defines appear on the dials.',
      key_features: 'pale enamel plates; fine dials; precise slots; one accent',
    }, ['decorative porcelain', 'dials with no function', 'reflections hiding scales'], [
      'The console of an elegant steam train racing a storm across a bridge: "SPEED 090", "STEAM 68%" and mode "HOLD" on porcelain dials, one coral indicator.',
      'A tea-ceremony robot\'s console with "STEEP 3 MIN", "POLITENESS 100%" and "SPILL RISK LOW", pale porcelain plates, absurdly serene.',
      'A quiet farming game HUD with "DAY 03", "ROUTE A" and "ENERGY 55%" on small pale plates, wide gaps and no frame.',
    ]),
    H('R-HUD-09', 'Inkbound Status Panels', 'bold ink mass status HUD', 'inkbound-status', {
      aesthetic: 'Inkbound Status Panels: heavy ink masses and generous voids form meters and markers, graphic and decisive without ornamental frames.',
      subject_treatment: "Build the prompt's meters and markers from bold ink masses and wide voids, with clean functional edges; keep every value and label exact.",
      color_and_tone: 'Black and bone with one small accent, states readable without color.',
      lighting_and_shadow: 'Flat ink contrast that sets hierarchy and grouping.',
      texture_and_material: 'Very contained print texture, kept away from numbers and meter limits.',
      camera_and_composition: 'Compact panels with clear silhouettes and unframed data.',
      atmosphere_and_mood: 'Graphic weight and forceful reading, bold and uncluttered.',
      rendering_and_quality: 'The voids that encode state are never eroded by texture.',
      key_features: 'ink mass meters; wide voids; black and bone; small accent',
    }, ['excess frames', 'ink over numbers', 'decorative state with no scale'], [
      'The HUD of a samurai-ronin game in a burning village: "VIGOR 68%", "ARROWS 4/8" and "PATH B" as bold ink meters, black and bone with one red accent.',
      'An ink-heavy HUD for a very stressed wizard accountant: "MANA 12%", "RECEIPTS 400" and "DEADLINE TODAY", dramatic and exact.',
      'A navigation game panel with "LINK STABLE", "HEADING 042°" and "ENERGY 55%", ink masses on a light ground and generous voids.',
    ]),
    H('R-HUD-10', 'Perforated Card Readouts', 'punched card status HUD', 'perforated-card', {
      aesthetic: 'Perforated Card Readouts: rows of punched holes and clear headers encode states like stacked punch cards, with a readable legend.',
      subject_treatment: "Encode the prompt's states as rows of punched holes under clear headers with an explicit legend; keep every code, header and label exact.",
      color_and_tone: 'Filled and empty told apart by shape and value, color optional.',
      lighting_and_shadow: 'Flat light with a minimal hole shadow that keeps the reading easy.',
      texture_and_material: 'Smooth card stock and holes of uniform size with clean edges.',
      camera_and_composition: 'Aligned rows with spacing between records and a dominant header.',
      atmosphere_and_mood: 'Register order and mechanical memory, tidy and clear.',
      rendering_and_quality: 'Every hole matches a declared value or position.',
      key_features: 'punched rows; clear headers; explicit legend; stacked cards',
    }, ['invented code', 'filler holes', 'illegible headers'], [
      'The ship computer of a 1960s-style moon rocket: modules A, B and C punched as 1100, 1010 and 0011 with the legend "punched = 1", carbon ink on cream cards.',
      'A punch-card HUD tracking a cat\'s daily crimes, rows "SOFA", "CURTAIN" and "PLANT", holes for each offense, legend exact, very bureaucratic.',
      'A four-step process card reading 1,1,0,0 under the header "PROCESS", stacked cards and carbon ink.',
    ]),
  ],
};

export default spec;
