import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID, style } from './_style';

// Fluid & Organic: the fluid process is how the image is made. It does not add smoke, liquid or
// bubbles as props to a scene unless the prompt asks for them.
const AVOID = [...STYLE_AVOID, 'adding literal liquid or smoke props to the scene'];

const spec: Spec = {
  pack: 'pack_10',
  category: '2. Fluid & Organic',
  updates: {
    'SP10-011': {
      dna: style(
        'Alcohol ink: vivid translucent inks spreading and pushing each other into cells with dark edge rings.',
        'the subject is painted in flowing alcohol ink whose pooled edges define its contours.',
        'Saturated translucent teal, magenta, gold and violet.',
        'Glowing translucency on white yupo.',
        'Ink cells, dark edge rings and metallic veins.',
        'Flowing organic fields shaping the subject.',
        'Vivid, fluid, spontaneous and luminous.',
        'Wet translucent finish.',
        'alcohol ink cells; dark edge rings; metallic veins',
      ),
      avoid: AVOID,
      briefs: [
        'Alcohol ink painting of a dragon whose body is formed by flowing teal and gold ink cells with dark edge rings. No text or logo.',
        "Alcohol ink painting of a knight's silhouette in magenta and violet pools. No text or logo.",
        'Alcohol ink painting of a castle on a cliff in flowing ink. No text or logo.',
      ],
    },
    'SP10-012': {
      dna: style(
        'Smoke photography style: the subject drawn as thin wisps of backlit smoke on black.',
        "the subject's outline is traced by curling smoke filaments on black.",
        'White or tinted smoke on pure black.',
        'Hard side backlight on smoke.',
        'Thin curling smoke filaments.',
        'Subject centered against black.',
        'Ethereal, delicate, mysterious and fleeting.',
        'Crisp high-contrast finish.',
        'smoke filaments tracing form; black ground',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        'Smoke-art image of a horse and rider traced entirely by curling white smoke on black. No text or logo.',
        'Smoke-art image of a dragon head. No text or logo.',
        "Smoke-art image of a woman's profile. No text or logo.",
      ],
    },
    'SP10-013': {
      dna: style(
        'Oil slick: iridescent thin-film color swirls forming the subject.',
        'the subject is formed from swirling rainbow thin-film color on dark ground.',
        'Iridescent rainbow over black.',
        'Soft sheen with interference colors.',
        'Thin-film swirls and marbling.',
        'Swirling field shaping the subject.',
        'Hypnotic, toxic, beautiful and fluid.',
        'Glossy finish.',
        'iridescent thin-film swirls; dark ground',
      ),
      avoid: AVOID,
      briefs: [
        'Oil-slick image of a serpent coiling in iridescent thin-film swirls on black. No text or logo.',
        "Oil-slick image of a knight's helmet. No text or logo.",
        'Oil-slick image of a moth. No text or logo.',
      ],
    },
    'SP10-014': {
      dna: style(
        'Macro bubble: the subject seen inside or reflected on a giant soap-bubble surface.',
        'the subject is reflected and wrapped on the curved surface of a huge bubble with thin-film swirls.',
        'Iridescent swirls with dark background.',
        'Soft backlight.',
        'Thin-film surface with swirling interference.',
        'Spherical framing.',
        'Dreamy, fragile, cosmic and delicate.',
        'Crisp macro finish.',
        'giant bubble surface; iridescent swirls; spherical framing',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        'Macro image of a castle reflected and warped on the surface of a giant iridescent bubble. No text or logo.',
        "Macro bubble image of a knight's face. No text or logo.",
        'Macro bubble image of a dragon. No text or logo.',
      ],
    },
    'SP10-015': {
      dna: style(
        'Mycelium network: the subject built from branching white fungal threads and nodes.',
        'the subject is woven from branching mycelial threads and glowing nodes.',
        'White threads on dark soil or glowing blue-green.',
        'Soft glow at nodes.',
        'Fine branching hyphae and nodes.',
        'Network fill across the frame.',
        'Organic, interconnected, eerie and alive.',
        'Fine detailed finish.',
        'branching hyphae; glowing nodes; network',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        'Mycelium-network image of a stag whose body and antlers are woven from glowing white fungal threads on dark soil. No text or logo.',
        'Mycelium image of a skull. No text or logo.',
        'Mycelium image of a tree of knights. No text or logo.',
      ],
    },
    'SP10-016': {
      dna: style(
        'Ferrofluid: black magnetic liquid spiking into sharp cones.',
        'the subject is sculpted from glossy black ferrofluid spikes.',
        'Glossy black with reflected highlights.',
        'Hard studio light on spikes.',
        'Liquid spikes with mirror gloss.',
        'Centered spiky form.',
        'Alien, tense, sleek and strange.',
        'Glossy macro finish.',
        'ferrofluid spikes; glossy black',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "Ferrofluid sculpture of a dragon's crest rising in glossy black spikes. No text or logo.",
        'Ferrofluid crown. No text or logo.',
        'Ferrofluid hedgehog. No text or logo.',
      ],
    },
    'SP10-017': {
      dna: style(
        'Acrylic pour: cells and lacing from poured acrylic layers forming the subject.',
        'the subject emerges from poured acrylic cells and lacing.',
        'Saturated poured colors with white lacing.',
        'Glossy flat light.',
        'Cells, lacing and glossy pour.',
        'Flowing pour across the frame.',
        'Playful, vivid, organic and flowing.',
        'Glossy finish.',
        'acrylic cells; lacing; glossy pour',
      ),
      avoid: AVOID,
      briefs: [
        'Acrylic-pour painting of a phoenix whose wings are made of poured cells and lacing. No text or logo.',
        'Acrylic pour of a castle. No text or logo.',
        'Acrylic pour of a whale. No text or logo.',
      ],
    },
    'SP10-018': {
      dna: style(
        'Reaction-diffusion: labyrinthine Turing patterns of spots and stripes forming the subject.',
        'the subject is filled and shaped by Turing-pattern spots and maze stripes.',
        'Two-tone contrast.',
        'Flat.',
        'Maze-like stripes and spots.',
        'Pattern fill following contours.',
        'Organic, mathematical, alien and precise.',
        'Crisp finish.',
        'Turing patterns; maze stripes; spots',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        'Reaction-diffusion image of a leopard knight whose armor is maze stripes. No text or logo.',
        'Reaction-diffusion image of a dragon egg. No text or logo.',
        'Reaction-diffusion image of a coral castle. No text or logo.',
      ],
    },
    'SP10-019': {
      dna: style(
        'Cymatics: sand or liquid patterns formed by sound vibration — concentric nodal geometry.',
        'the subject is built from cymatic nodal patterns of sand or liquid.',
        'Sand on dark plate or liquid ripples.',
        'Raking light on ridges.',
        'Nodal sand lines and ripples.',
        'Radial symmetric pattern.',
        'Mystical, harmonic, precise and resonant.',
        'Crisp finish.',
        'cymatic nodal pattern; radial symmetry',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        "Cymatics image where sand on a vibrating plate forms a knight's shield crest. No text or logo.",
        'Cymatics image of a rose window. No text or logo.',
        'Cymatics image of a dragon eye. No text or logo.',
      ],
    },
    'SP10-020': {
      dna: style(
        'Nebula cloud: the subject formed of glowing interstellar gas, dust lanes and stars.',
        'the subject is shaped from glowing nebula gas and dark dust lanes.',
        'Magenta, teal and gold gas with stars.',
        'Self-luminous glow.',
        'Gas filaments, dust and starfields.',
        'Cosmic scale framing.',
        'Awe-filled, cosmic, silent and vast.',
        'Deep-space finish.',
        'glowing nebula gas; dust lanes; stars',
      ),
      avoid: STYLE_AVOID,
      briefs: [
        'Nebula image of a colossal horse and rider formed from glowing magenta and teal gas. No text or logo.',
        'Nebula image of a crowned skull. No text or logo.',
        'Nebula image of a whale. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Paper Marbling',
      domain: 'marbled paper pattern',
      tags: ['marbling', 'paper', 'fluid'],
      dna: style(
        'Paper marbling: combed and swirled floating paints transferred to paper in feathered and peacock patterns.',
        'the subject is formed by combed marbling swirls and feathered pattern.',
        'Indigo, ochre, oxblood and cream.',
        'Flat printed paper.',
        'Combed swirls and feathered edges.',
        'Pattern flowing along the subject.',
        'Elegant, antique, fluid and intricate.',
        'Crisp printed finish.',
        'combed marbling; feathered swirls; antique paper',
      ),
      avoid: AVOID,
      briefs: [
        'Marbled-paper image of a dragon whose body is combed indigo and ochre marbling. No text or logo.',
        'Marbled paper knight. No text or logo.',
        'Marbled paper moon over waves. No text or logo.',
      ],
    },
    {
      name: 'Resin Geode Pour',
      domain: 'resin geode art',
      tags: ['resin', 'geode', 'fluid'],
      dna: style(
        'Resin geode: poured resin rings with crystal centers and gold edges.',
        'the subject is built from concentric resin rings with crystal centers and gold veins.',
        'Deep blue, amethyst, white and gold.',
        'Glossy reflective light.',
        'Glossy resin rings, crystals and gold leaf.',
        'Concentric rings following the subject.',
        'Luxurious, glossy, mineral and vivid.',
        'Glossy finish.',
        'resin rings; crystal centers; gold veins',
      ),
      avoid: AVOID,
      briefs: [
        'Resin-geode art of an eye with concentric amethyst rings and gold veins. No text or logo.',
        'Resin geode dragon egg. No text or logo.',
        'Resin geode shield. No text or logo.',
      ],
    },
    {
      name: 'Lava Lamp Blobs',
      domain: 'lava lamp blobs',
      tags: ['lava-lamp', 'blobs', 'fluid'],
      dna: style(
        'Lava lamp: soft rising wax blobs merging and splitting in glowing liquid.',
        'the subject is formed by soft glowing wax blobs.',
        'Warm orange, magenta and purple glow.',
        'Backlit glow.',
        'Soft wax blobs and warm liquid.',
        'Vertical flowing blobs.',
        'Retro, dreamy, slow and warm.',
        'Soft glowing finish.',
        'glowing wax blobs; merging; retro glow',
      ),
      avoid: AVOID,
      briefs: [
        'Lava-lamp image of a rising dragon made of glowing orange wax blobs. No text or logo.',
        'Lava lamp knight. No text or logo.',
        'Lava lamp jellyfish. No text or logo.',
      ],
    },
    {
      name: 'Dendritic Ink Growth',
      domain: 'dendritic branching ink',
      tags: ['dendrite', 'ink', 'fluid'],
      dna: style(
        'Dendritic growth: branching fern-like ink or mineral dendrites forming the subject.',
        'the subject is traced by branching dendritic ink growth.',
        'Black or iron-brown dendrites on pale ground.',
        'Flat.',
        'Fine branching dendrites.',
        'Branching outward from centers.',
        'Organic, fractal, delicate and eerie.',
        'Fine finish.',
        'dendritic branching; fern-like growth',
      ),
      avoid: AVOID,
      briefs: [
        'Dendritic-ink image of a tree-shaped dragon made of branching black dendrites. No text or logo.',
        'Dendritic ink crown. No text or logo.',
        'Dendritic ink lightning over a castle. No text or logo.',
      ],
    },
    {
      name: 'Salt-Bloom Watercolor',
      domain: 'salt-textured watercolor',
      tags: ['watercolor', 'salt', 'fluid'],
      dna: style(
        'Salt-bloom watercolor: wet washes with salt crystals creating starry blooms.',
        'the subject is painted in wet washes with salt blooms scattered through.',
        'Deep blues, violets and greens.',
        'Soft paper light.',
        'Salt starbursts, blooms and granulation.',
        'Loose wash composition.',
        'Magical, soft, starry and fluid.',
        'Wet paper finish.',
        'salt starbursts; wet washes',
      ),
      avoid: AVOID,
      briefs: [
        'Salt-bloom watercolor of a night castle with starry salt blooms in the sky. No text or logo.',
        'Salt watercolor owl. No text or logo.',
        'Salt watercolor sea serpent. No text or logo.',
      ],
    },
    {
      name: 'Coffee Stain Bloom',
      domain: 'coffee and tea stain painting',
      tags: ['coffee', 'stain', 'fluid'],
      dna: style(
        'Coffee stain painting: brown coffee washes with dark tide rings and blooms.',
        'the subject is painted in coffee washes with darker drying rings.',
        'Sepia and brown tones.',
        'Soft paper light.',
        'Stain rings, blooms and drips.',
        'Loose composition.',
        'Warm, nostalgic, humble and intimate.',
        'Paper finish.',
        'coffee washes; tide rings',
      ),
      avoid: AVOID,
      briefs: [
        'Coffee-stain painting of a monk reading, with dark tide rings as shadows. No text or logo.',
        'Coffee stain dragon. No text or logo.',
        'Coffee stain castle. No text or logo.',
      ],
    },
    {
      name: 'Hydro-Dip Swirl',
      domain: 'hydro-dip swirl pattern',
      tags: ['hydro-dip', 'swirl', 'fluid'],
      dna: style(
        'Hydro-dip: the subject coated by dipping through swirled paint film.',
        "the subject's surfaces are coated in swirled hydro-dip paint.",
        'Neon or pastel swirls.',
        'Studio light.',
        'Swirled paint film.',
        'Object-centered.',
        'Playful, vivid, crafty and bold.',
        'Glossy finish.',
        'hydro-dip swirls; coated surfaces',
      ),
      avoid: AVOID,
      briefs: [
        "Hydro-dipped knight's helmet coated in neon swirls. No text or logo.",
        'Hydro-dip skull. No text or logo.',
        'Hydro-dip violin. No text or logo.',
      ],
    },
    {
      name: 'Magnetic Iron Filings',
      domain: 'iron filing field patterns',
      tags: ['iron-filings', 'magnetic', 'fluid'],
      dna: style(
        'Iron filings: field lines of iron filings tracing the subject.',
        'the subject is traced by iron filings aligned in field lines.',
        'Dark grey filings on white.',
        'Flat.',
        'Aligned filings.',
        'Field lines around forms.',
        'Scientific, invisible-made-visible and precise.',
        'Crisp finish.',
        'aligned iron filings; field lines',
      ),
      avoid: AVOID,
      briefs: [
        'Iron-filings image of a dragon traced by field lines on white paper. No text or logo.',
        'Iron filings crown. No text or logo.',
        'Iron filings knight. No text or logo.',
      ],
    },
    {
      name: 'Frost Fern Crystals',
      domain: 'frost fern crystal growth',
      tags: ['frost', 'crystal', 'fluid'],
      dna: style(
        'Frost ferns: window-frost crystal feathers growing into the subject.',
        'the subject is drawn by growing frost fern crystals.',
        'White frost on dark glass.',
        'Backlight.',
        'Feathery ice crystals.',
        'Growth patterns.',
        'Cold, delicate, magical and quiet.',
        'Crisp finish.',
        'frost fern crystals; window glass',
      ),
      avoid: AVOID,
      briefs: [
        'Frost-fern image of a stag traced by window frost crystals. No text or logo.',
        'Frost fern castle. No text or logo.',
        'Frost fern knight. No text or logo.',
      ],
    },
    {
      name: 'Liquid Light Show',
      domain: 'oil projection light show',
      tags: ['light-show', 'projection', 'fluid'],
      dna: style(
        'Liquid light show: overhead-projected oil and dye blobs pulsing in saturated color.',
        'the subject is formed by projected pulsing oil and dye blobs.',
        'Saturated magenta, green, orange.',
        'Projected light.',
        'Oil and dye blobs.',
        'Full-frame projection.',
        'Psychedelic, pulsing, warm and hypnotic.',
        'Projected finish.',
        'projected oil blobs; saturated dye',
      ),
      avoid: AVOID,
      briefs: [
        "Liquid light show image of a wizard's face formed from projected oil and dye blobs. No text or logo.",
        'Liquid light show dragon. No text or logo.',
        'Liquid light show castle. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
