import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Character design: very different design languages, each named after the designer, studio or
// tradition that defined it. Every card invents an original character in that language.
const T = ['character-design'];

const spec: Spec = {
  pack: 'pack_26',
  category: '1. Character Design',
  newCategory: { id: 'character-design' },
  updates: {},
  creates: [
    cr('Tetsuya Nomura - Zipper-Belt Hero Design', 'JRPG character design', [...T, 'nomura'], {
      look: 'Tetsuya Nomura character design look: slender stylish heroes with spiky layered hair, belts, zippers, buckles and asymmetric straps, oversized boots and melancholy fashion-model faces.',
      subject:
        'design characters with lean elegant bodies, spiky layered hair, pale moody faces and outfits crossed with belts, zippers, chains and buckles.',
      color: 'Black leather, silver hardware, one saturated accent color and pale skin.',
      light: 'Clean promotional render light with soft rim highlights on leather and metal.',
      texture: 'Crisp digital painting with leather sheen, metal buckles and fabric folds.',
      camera: 'Full-body heroic character art on a pale background, slight three-quarter pose.',
      mood: 'brooding stylish melancholy',
      render: 'Polished JRPG promotional character illustration.',
      key: 'Nomura belts and zippers; spiky hair; oversized boots; asymmetric straps',
      avoid: ['a spiky blond soldier with a giant buster sword', 'a keyblade weapon'],
      briefs: [
        'Designed as the brooding hero of an invented role-playing game, a retired lighthouse keeper in his sixties wears a leather greatcoat crossed with nine buckled belts, one zipper running pointlessly across his chest, holding a lantern like a weapon. No readable text or logo.',
        'A melancholy florist is reimagined as a JRPG party member, her apron covered in silver buckles and dangling chains, clutching pruning shears as if they were a legendary blade. No readable text or logo.',
        'On a pale backdrop, a single oversized boot covered in eleven buckles stands alone like a character reveal teaser. No readable text or logo.',
      ],
    }),
    cr(
      'Tim Burton - Spindly Gothic Character Sketch',
      'gothic character design',
      [...T, 'burton'],
      {
        look: 'Tim Burton character design look: spindly limbs, hollow dark-ringed eyes, stripes, stitches, crooked postures and whimsical gothic melancholy drawn with scratchy pen.',
        subject:
          'design characters with impossibly thin limbs, huge sunken eyes, pale faces, stitched details and striped clothing.',
        color: 'Black ink, bone white, faded purple and sickly green with stripes.',
        light: 'Moonlit gothic light and deep shadows around the eyes.',
        texture: 'Scratchy pen lines, crosshatching and watercolor stains on paper.',
        camera: 'Single character standing in a crooked pose against a pale or moonlit ground.',
        mood: 'whimsical gothic melancholy',
        render: 'Scratchy gothic character sketch with watercolor.',
        key: 'Burton spindly limbs; hollow eyes; stripes and stitches; crooked poses',
        avoid: ['a stitched ragdoll woman', 'a skeleton pumpkin king'],
        briefs: [
          'Drawn with spindly scratchy pen lines, a shy undertaker with arms as thin as umbrella ribs and enormous hollow eyes holds a tiny wilted flower out to nobody in particular. No readable text or logo.',
          'A striped-stockinged bicycle messenger with a neck three times too long delivers letters to a haunted apartment block, her hat stitched shut. No readable text or logo.',
          'On yellowed sketch paper, a lone crooked chair with stitched upholstery and spindly legs seems to be waiting for its character. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Genndy Tartakovsky - Angular Silhouette Action Design',
      'animation character design',
      [...T, 'tartakovsky'],
      {
        look: 'Genndy Tartakovsky character design look: bold angular silhouettes, huge shapes contrasted with tiny details, flat color, minimal line and powerful action poses.',
        subject:
          'design characters as strong geometric silhouettes with exaggerated shape contrast, tiny heads on huge bodies or the reverse.',
        color: 'Flat bold color blocks with deep shadow shapes.',
        light: 'Graphic flat lighting with hard shadow shapes.',
        texture: 'Minimal clean lines and flat color.',
        camera: 'Wide cinematic silhouettes with strong negative space.',
        mood: 'bold stoic action',
        render: 'Graphic animation character design with bold silhouettes.',
        key: 'Tartakovsky silhouettes; shape contrast; flat color; minimal line',
        avoid: ['a samurai in a white gi with a topknot', 'a small boy genius in a lab coat'],
        briefs: [
          'Built from a giant rectangular torso and tiny triangular head, a stoic grandmother bodyguard stands in a desert silhouette, one small umbrella held like a sword. No readable text or logo.',
          'A tiny round chef with enormous angular forearms carries a whole roast ox on one shoulder, drawn as bold flat shapes. No readable text or logo.',
          'Against a huge red sun, a lone triangular silhouette on a cliff waits, its scarf the only thing moving. No readable text or logo.',
        ],
      },
    ),
    cr('Bruce Timm - Streamlined Hero Model Sheet', 'animation model sheet', [...T, 'bruce-timm'], {
      look: 'Bruce Timm model sheet look: streamlined art deco hero anatomy, broad chests and tiny waists, square jaws, simple black shadow shapes and minimal clean lines.',
      subject:
        'design characters with streamlined geometric anatomy, square jaws, simple facial features and bold black shadow shapes.',
      color: 'Limited flat palette with solid black shadows.',
      light: 'Noir-inspired flat lighting with black shadow masses.',
      texture: 'Clean minimal line and flat fills.',
      camera: 'Front, side and back turnaround model-sheet layout.',
      mood: 'streamlined heroic noir',
      render: 'Clean animation model sheet illustration.',
      key: 'Bruce Timm streamlined anatomy; black shadows; model sheet; deco',
      avoid: ['a bat-eared caped vigilante', 'an S-shield emblem'],
      briefs: [
        'Shown in a clean front, side and back turnaround, an original night-shift pharmacist turned masked hero has a square jaw, a streamlined cape and one bold black shadow shape across her mask. No readable text or logo.',
        'A broad-chested retired mail carrier becomes a streamlined noir detective on a model sheet, his coat drawn as three simple geometric shapes. No readable text or logo.',
        'A model sheet shows only a hero’s gloved fist from five angles, each one a perfect simple shape. No readable text or logo.',
      ],
    }),
    cr(
      'Jamie Hewlett - Punk Cartoon Band Portrait',
      'punk cartoon character design',
      [...T, 'hewlett'],
      {
        look: 'Jamie Hewlett character design look: scrappy punk cartoon characters with lanky bodies, scratchy ink, messy hair, bad teeth, graphic flat color and urban grime.',
        subject:
          'design characters with lanky scruffy bodies, messy hair, bags under the eyes, crooked teeth and layered street clothes.',
        color: 'Grimy flat color with punchy acid accents.',
        light: 'Flat graphic light with scratchy shadows.',
        texture: 'Scratchy ink line and flat color.',
        camera: 'Band-portrait group lineup with attitude.',
        mood: 'scrappy punk attitude',
        render: 'Scrappy punk cartoon illustration.',
        key: 'Hewlett scratchy ink; lanky punks; urban grime; attitude',
        avoid: ['a virtual band of four cartoon musicians', 'a tank girl with a shaved head'],
        briefs: [
          'Posing like an album cover, an invented band of four retired dentists slouches against a graffiti wall, lanky and scruffy with crooked grins, one holding a drill like a guitar. No readable text or logo.',
          'A scrappy punk grandmother with a mohawk of curlers kicks a vending machine in a grimy launderette. No readable text or logo.',
          'Alone in a puddle-filled back alley behind a punk venue, a beat-up amplifier covered in stickers hums quietly while cartoon flies buzz around its cracked speaker. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Kim Jung Gi - Freehand Crowd Ink Character',
      'freehand ink drawing',
      [...T, 'kim-jung-gi'],
      {
        look: 'Kim Jung Gi drawing look: virtuoso freehand brush-pen ink with no pencils, dense crowds of characters, impossible perspective, vehicles and animals flowing together.',
        subject:
          'design characters as confident freehand ink figures crowded together at many scales and angles.',
        color: 'Black brush-pen ink on white paper.',
        light: 'Light implied by ink density and white paper.',
        texture: 'Confident brush-pen strokes and loose hatching.',
        camera: 'Wide-angle dense compositions of many figures.',
        mood: 'virtuoso bustling energy',
        render: 'Virtuoso freehand ink drawing.',
        key: 'Kim Jung Gi freehand; dense crowds; wide-angle; brush pen',
        briefs: [
          'Drawn freehand in one continuous brush-pen session, a whole market of invented characters spills across the page, fishmongers, cyclists, a sleeping tiger and an old woman juggling melons, all at wildly different angles. No readable text or logo.',
          'A crowded ferry deck is packed with characters drawn from above, every face different, a goat stealing someone’s hat. No readable text or logo.',
          'A single motorbike rider leans into a curve, drawn in a few confident brush strokes on white paper. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Carter Goodrich - Rounded Feature Film Character Maquette',
      'feature animation character design',
      [...T, 'carter-goodrich'],
      {
        look: 'Carter Goodrich feature animation character design look: appealing rounded shape language, strong silhouettes, expressive caricature and soft painted maquette-like volume.',
        subject:
          'design characters with appealing caricatured proportions, strong simple silhouettes and warm expressive faces.',
        color: 'Warm appealing colors with soft painted shading.',
        light: 'Soft studio light on rounded forms.',
        texture: 'Soft painted gouache and pencil like a character study.',
        camera: 'Character study poses with expression variations.',
        mood: 'warm appealing charm',
        render: 'Appealing feature animation character study.',
        key: 'Carter Goodrich rounded shapes; caricature; appeal; maquette volume',
        briefs: [
          'Drawn as an appealing character study with three expressions, a round grumpy baker with a tiny hat and huge floury hands tries very hard not to smile at a stray kitten. No readable text or logo.',
          'A tall lanky museum guard with a pear-shaped body tiptoes after a runaway painting, shown in a warm character sketch. No readable text or logo.',
          'On a warm character sketch page, a single rounded teapot with a caricatured grumpy face waits beside three expression studies, clearly offended by the cup next to it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Shigenori Soejima - Stylish Persona Cast Portrait',
      'JRPG character design',
      [...T, 'soejima'],
      {
        look: 'Shigenori Soejima character design look: stylish modern students and adults, sharp graphic color accents, confident fashion poses and bold red, yellow or blue themed palettes.',
        subject:
          'design characters with sleek modern designs, sharp eyes, stylish contemporary fashion and confident poses.',
        color: 'One bold theme color with black and white graphic accents.',
        light: 'Clean graphic lighting with sharp highlights.',
        texture: 'Crisp digital line and flat cel shading.',
        camera: 'Dynamic full-body portraits with graphic backgrounds.',
        mood: 'stylish confident cool',
        render: 'Stylish JRPG character portrait.',
        key: 'Soejima stylish fashion; bold theme colors; confident poses',
        avoid: ['a masked phantom thief in a black coat', 'existing franchise characters'],
        briefs: [
          'Posed against a bold red graphic splash, an invented cast member, a stylish night-bus driver in her fifties, flips her driving gloves like a gambler flips cards. No readable text or logo.',
          'A cool pharmacist character in a sharp yellow coat stands confidently, one hand in a pocket full of pill bottles. No readable text or logo.',
          'A pair of glasses rests on a bold blue graphic background, the only clue to the next character. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Yusuke Kozaki - Graphic Flat-Color Hero Roster',
      'game character design',
      [...T, 'kozaki'],
      {
        look: 'Yusuke Kozaki character design look: clean graphic line, flat vivid color, sharp stylish silhouettes and roster-ready heroes with clear readable shapes.',
        subject:
          'design characters with clean graphic silhouettes, flat vivid color and stylish fantasy or modern outfits.',
        color: 'Flat vivid color with crisp contrast.',
        light: 'Flat graphic lighting.',
        texture: 'Clean graphic line and flat fills.',
        camera: 'Roster-style full-body character lineup.',
        mood: 'crisp heroic style',
        render: 'Clean graphic character roster illustration.',
        key: 'Kozaki flat color; graphic silhouettes; roster heroes',
        briefs: [
          'Lined up like a game roster, five original heroes, a baker, a crossing guard, a beekeeper, a violinist and a plumber, stand in clean flat-color armor that hints at their day jobs. No readable text or logo.',
          'A stylish assassin who is secretly a librarian holds a bookmark like a blade, drawn in crisp flat color. No readable text or logo.',
          'Between two finished hero designs on a clean character roster sheet, an empty glowing slot waits to be filled, a single pencil resting in front of it. No readable text or logo.',
        ],
      },
    ),
    cr('Kazuma Kaneko - Occult Demon Compendium', 'demon design', [...T, 'kaneko'], {
      look: 'Kazuma Kaneko demon design look: occult demons and deities drawn with elegant fashion-illustration line, flat color, strange anatomy and compendium-like poses.',
      subject:
        'design creatures as elegant occult beings with strange anatomy, ornaments and fashion-illustration flair.',
      color: 'Flat muted color with occult accents.',
      light: 'Flat illustration light.',
      texture: 'Elegant clean line and flat color.',
      camera: 'Single full-body compendium portrait on white.',
      mood: 'elegant occult strangeness',
      render: 'Elegant occult compendium illustration.',
      key: 'Kaneko occult demons; fashion line; compendium pose',
      avoid: ['a blue snowman demon with a hat', 'existing franchise characters'],
      briefs: [
        'Presented like a compendium entry on white, an original demon of lost umbrellas stands elegantly with six folded umbrella wings and a face like a porcelain mask. No readable text or logo.',
        'A demon of overdue library books wears a gown of stacked pages and holds a stamp as a scepter. No readable text or logo.',
        'On a clean white compendium page, an ornate horned crown floats alone above a neat shadow, its jewels arranged like a strange watching face. No readable text or logo.',
      ],
    }),
    cr(
      'Moebius - Desert Wanderer Character Studies',
      'bande dessinée character design',
      [...T, 'moebius'],
      {
        look: 'Moebius (Jean Giraud) character design look: clean ligne claire contours, fine hatching, flowing robes, strange helmets and serene wanderers in vast desert worlds.',
        subject:
          'design characters with clean contours, flowing robes, odd helmets and calm faces.',
        color: 'Soft pastel desert colors, pale blue and sand.',
        light: 'Bright serene desert light.',
        texture: 'Clean line with fine hatching and flat pastel color.',
        camera: 'Character studies with small landscapes around them.',
        mood: 'serene cosmic wandering',
        render: 'Ligne claire character studies.',
        key: 'Moebius clean line; flowing robes; odd helmets; desert serenity',
        briefs: [
          'On a sheet of character studies, an invented desert courier in flowing robes and a headpiece shaped like a seashell rides a long-legged bird across pale sand, calm as a monk. No readable text or logo.',
          'A cosmic mechanic with a transparent helmet full of floating fish repairs a hovering bicycle in the dunes. No readable text or logo.',
          'Under a huge pale pastel sky, a lone odd seashell-shaped headpiece lies half buried in the desert sand, a tiny lizard sunning itself on top. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Lorelay Bové - Soft Gouache Princess Visdev',
      'visual development character design',
      [...T, 'lorelay-bove'],
      {
        look: 'Lorelay Bové visual development look: soft gouache character paintings, gentle rounded faces, flowing dresses, warm storybook palettes and elegant graceful poses.',
        subject:
          'design characters with gentle rounded faces, flowing clothing and graceful storybook poses.',
        color: 'Warm soft gouache palettes, rose, sage and gold.',
        light: 'Soft warm storybook light.',
        texture: 'Soft gouache brushwork on paper.',
        camera: 'Graceful single-character visdev paintings.',
        mood: 'gentle storybook grace',
        render: 'Soft gouache visual development painting.',
        key: 'Lorelay Bové gouache; graceful poses; storybook palettes',
        briefs: [
          'Painted in soft gouache, an original elderly queen who rules a kingdom of bees twirls in a honeycomb gown, a crown of wax flowers melting slightly in the warm light. No readable text or logo.',
          'A gentle ferrywoman with a dress made of river water leans on her oar in a warm storybook painting. No readable text or logo.',
          'On a sunlit garden step painted in soft gouache, a single slipper made of rose petals waits beside a trail of tiny glowing footprints. No readable text or logo.',
        ],
      },
    ),
    cr('Tohl Narita - Kaiju Suit Design Sheet', 'kaiju design', [...T, 'narita'], {
      look: 'Tohl Narita kaiju and alien design look from sixties tokusatsu: abstract modernist creature shapes, sculptural suits built for actors, bold patterns and strange elegant silhouettes.',
      subject:
        'design giant creatures as wearable suit designs with modernist abstract shapes and bold patterns.',
      color: 'Bold modernist colors on paper with watercolor washes.',
      light: 'Flat design-sheet light.',
      texture: 'Watercolor and pencil design sketches.',
      camera: 'Front and side suit-design views on paper.',
      mood: 'strange modernist wonder',
      render: 'Sixties kaiju design sketch.',
      key: 'Tohl Narita modernist kaiju; suit design; abstract shapes',
      avoid: ['a red and silver giant hero with a color timer', 'existing franchise characters'],
      briefs: [
        'On a watercolor design sheet, an original kaiju shaped like a walking cathedral bell has spiral patterns on its hide and small human-sized feet for the suit actor. No readable text or logo.',
        'A space alien designed as an abstract lamp with a single ring-shaped eye appears in front and side views. No readable text or logo.',
        'Across a watercolor design page, a single kaiju tail curls in a long spiral, spotted with bold modernist rings and marked with suit seam notes drawn as lines. No readable text or logo.',
      ],
    }),
    cr(
      'Laika - Stop-Motion Puppet Character Design',
      'stop-motion character design',
      [...T, 'laika'],
      {
        look: 'Laika studio stop-motion character look as in Coraline and Kubo: handcrafted puppets with sculpted faces, real fabric costumes, tiny stitched details and eerie handmade charm.',
        subject:
          'design characters as handcrafted stop-motion puppets with sculpted faces, fabric clothes and visible handmade details.',
        color: 'Rich muted handmade colors and tactile fabrics.',
        light: 'Miniature set lighting with soft shadows.',
        texture: 'Sculpted resin faces, woven fabric and knitted details.',
        camera: 'Macro puppet photography on miniature sets.',
        mood: 'eerie handmade charm',
        render: 'Photographed stop-motion puppet character.',
        key: 'Laika puppets; handmade fabrics; sculpted faces; miniature sets',
        avoid: [
          'a blue-haired girl in a yellow raincoat',
          'button eyes',
          'existing franchise characters',
        ],
        briefs: [
          'Photographed on a miniature set, an original puppet of a grumpy lighthouse keeper with a hand-knitted sweater and a sculpted face full of wrinkles holds a tiny working lantern. No readable text or logo.',
          'A stop-motion puppet of a nervous tailor with pins stuck all over her apron measures a paper moon. No readable text or logo.',
          'On an empty stop-motion puppet set, a tiny hand-knitted scarf hangs from a miniature coat hook beside a teacup no bigger than a fingernail. No readable text or logo.',
        ],
      },
    ),
    cr('Sanrio Minimal Mascot Silhouette', 'mascot character design', [...T, 'sanrio'], {
      look: 'Sanrio mascot design language: ultra-simple rounded silhouettes, dot eyes, no mouth or tiny mouth, a single accessory, pastel flat color and instant cuteness.',
      subject:
        'design characters as ultra-simple round mascots with dot eyes and one signature accessory.',
      color: 'Pastel flat colors with white.',
      light: 'Flat cute light.',
      texture: 'Clean thick outlines and flat fills.',
      camera: 'Centered mascot portrait on a pastel background.',
      mood: 'instant sweet cuteness',
      render: 'Clean kawaii mascot design.',
      key: 'Sanrio simplicity; dot eyes; one accessory; pastel',
      avoid: ['a white cat with a red bow', 'existing franchise characters'],
      briefs: [
        'Centered on a pastel background, an original mascot shaped like a sleepy rice ball with dot eyes wears a tiny construction helmet as its only accessory. No readable text or logo.',
        'Centered on a soft pink background, an original round cloud mascot with dot eyes smiles shyly, holding one tiny striped umbrella as its only accessory. No readable text or logo.',
        'On a plain pastel mint background, a tiny floating ribbon and two small dot footprints suggest a mascot that just hopped out of the picture. No readable text or logo.',
      ],
    }),
    cr('Yuru-Chara Regional Mascot Costume', 'regional mascot design', [...T, 'yuru-chara'], {
      look: 'Japanese yuru-chara regional mascot look: lovably clumsy costumes built around local products, oversized heads, stubby limbs and awkward handmade charm.',
      subject:
        'design mascots as clumsy costumes combining a local product with a friendly face and stubby limbs.',
      color: 'Bright friendly colors of local produce.',
      light: 'Outdoor festival daylight.',
      texture: 'Foam costume, felt and fabric seams.',
      camera: 'Full-body photos at local festivals.',
      mood: 'lovable clumsy charm',
      render: 'Photographed mascot costume design.',
      key: 'Yuru-chara clumsy costumes; local products; oversized heads',
      avoid: ['a black bear mascot with red cheeks', 'existing franchise characters'],
      briefs: [
        'At a small-town festival, an original regional mascot shaped like a giant pickled radish with a samurai helmet waves stubby arms while a toddler stares in total disbelief. No readable text or logo.',
        'A foam mascot of a local oyster with tiny legs tries to climb stage stairs at a seaside fair. No readable text or logo.',
        'Backstage at a small-town festival, an enormous foam mascot head rests on a folding chair, its wide painted smile beaming at an empty dressing room. No readable text or logo.',
      ],
    }),
    cr(
      'Keita Amemiya - Armored Tokusatsu Monster Design',
      'creature and armor design',
      [...T, 'amemiya'],
      {
        look: 'Keita Amemiya creature and armor design look: ornate organic armor, baroque demon knights, sculptural textures and dark tokusatsu elegance.',
        subject:
          'design characters as ornate armored beings with organic sculptural textures and baroque silhouettes.',
        color: 'Dark metal, bone, gold and deep red.',
        light: 'Dramatic sculptural lighting.',
        texture: 'Ornate sculpted armor detail.',
        camera: 'Full-body heroic design paintings.',
        mood: 'dark ornate menace',
        render: 'Ornate armor design illustration.',
        key: 'Amemiya organic armor; baroque demons; sculptural detail',
        avoid: ['a golden wolf armor knight', 'existing franchise characters'],
        briefs: [
          'In a dramatic design painting, an original knight of a forgotten orchard wears ornate armor grown from twisted apple wood and bone, with a helmet shaped like a closed flower bud. No readable text or logo.',
          'A demon clockmaker in baroque armor with gears growing like coral stands in a dark workshop. No readable text or logo.',
          'Under a single spotlight in a dark studio, an ornate armored gauntlet grown from bone and gold filigree lies on a folded velvet cloth. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Ilya Kuvshinov - Glossy Digital Portrait Character',
      'digital portrait character design',
      [...T, 'kuvshinov'],
      {
        look: 'Ilya Kuvshinov digital portrait look: glossy anime-realist faces, big reflective eyes, soft painted skin, flat graphic backgrounds and cool contemporary fashion.',
        subject:
          'design characters as glossy portraits with big reflective eyes, soft skin and contemporary fashion.',
        color: 'Soft pastel skin tones against flat bold backgrounds.',
        light: 'Soft glossy highlights on eyes and lips.',
        texture: 'Smooth digital paint with glossy highlights.',
        camera: 'Close portrait framing with flat background.',
        mood: 'cool glossy calm',
        render: 'Glossy digital portrait illustration.',
        key: 'Kuvshinov glossy eyes; soft skin; flat backgrounds',
        briefs: [
          'In a glossy portrait against a flat mint background, an original character, a tattooed marine biologist in her forties, gazes calmly while a tiny jellyfish floats near her reflective eyes. No readable text or logo.',
          'A cool motorcycle courier with glossy eyes and a scuffed helmet under her arm stares straight at the viewer. No readable text or logo.',
          'Against a flat tangerine background, a pair of glossy oversized sunglasses reflects a tiny city skyline and the silhouette of whoever is wearing them. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Shinkiro - Fighting Game Select Portrait',
      'fighting game character art',
      [...T, 'shinkiro'],
      {
        look: 'Shinkiro fighting game art look: painterly muscular fighters, dramatic airbrushed portraits, intense stares and nineties arcade select-screen bravado.',
        subject:
          'design fighters with muscular painterly anatomy, intense faces and bold costumes.',
        color: 'Rich airbrushed color with dramatic contrast.',
        light: 'Dramatic rim light and arcade glow.',
        texture: 'Painterly airbrush and gouache.',
        camera: 'Bust-up select portraits with dramatic angles.',
        mood: 'intense arcade bravado',
        render: 'Painterly nineties fighting game portrait.',
        key: 'Shinkiro airbrush; muscular fighters; select portraits',
        avoid: ['existing fighting game characters'],
        briefs: [
          'In a painterly arcade select portrait, an original fighter, a sixty-year-old sumo-trained sushi chef, cracks his knuckles as steam rises from his headband. No readable text or logo.',
          'In a painterly arcade select portrait, a fierce librarian fighter in a cardigan and fingerless gloves glares at the next opponent while books orbit her fists. No readable text or logo.',
          'On a glowing arcade select screen, an empty portrait frame burns with dramatic rim light while a scuffed pair of fighting gloves waits beneath it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Ashley Wood - Grunge Mecha Pilot Sketch',
      'grunge character design',
      [...T, 'ashley-wood'],
      {
        look: 'Ashley Wood art look: grungy loose painterly sketches, battered mecha and pilots, drips, scratches and moody muted color.',
        subject:
          'design characters as loose painterly pilots and battered robots with grungy textures.',
        color: 'Muted greys, olive and rust with one accent.',
        light: 'Moody diffuse light.',
        texture: 'Grungy paint drips, scratches and loose marks.',
        camera: 'Loose character sketches on grungy grounds.',
        mood: 'grungy moody cool',
        render: 'Loose grungy painterly character sketch.',
        key: 'Ashley Wood grunge; battered mecha; drips and scratches',
        briefs: [
          'Sketched with grungy drips and scratches, an original pilot, a chain-smoking grandmother in a flight jacket, leans on her battered squat robot that has flowers growing from its exhaust pipe. No readable text or logo.',
          'A tired robot soldier sits on a crate reading a newspaper in a loose painterly sketch. No readable text or logo.',
          'In a loose painterly sketch, a dented robot cockpit hatch sits on a wooden stool, grey paint dripping down it onto a pile of spent shell casings. No readable text or logo.',
        ],
      },
    ),
    cr('Gacha Splash Art Character', 'mobile game character art', [...T, 'gacha'], {
      look: 'Modern gacha game splash art look as in miHoYo and Cygames releases: ornate fantasy outfits, dynamic flowing fabric, glowing elemental effects and polished anime-realist rendering.',
      subject:
        'design characters with ornate layered outfits, flowing ribbons, glowing accessories and dynamic poses.',
      color: 'Rich jewel tones with glowing elemental accents.',
      light: 'Glowing elemental light and soft bloom.',
      texture: 'Polished digital painting with ornate detail.',
      camera: 'Dynamic splash compositions with flowing fabric.',
      mood: 'dazzling heroic spectacle',
      render: 'Polished gacha splash illustration.',
      key: 'Gacha splash; ornate outfits; elemental glow; flowing fabric',
      avoid: ['existing gacha characters'],
      briefs: [
        'In a dazzling splash pose, an original five-star character, a retired train conductor in ornate gold and navy robes, summons a spectral steam locomotive from her pocket watch. No readable text or logo.',
        'A plant-element healer with ribbons of ivy flowing from her sleeves leaps across a glowing greenhouse. No readable text or logo.',
        'On an ornate marble pedestal in a glowing summoning hall, a single crystal hovers and spins while pink sparkles swirl around it like a coming reveal. No readable text or logo.',
      ],
    }),
    cr(
      'Jorge R. Gutiérrez - Mexican Folk Cartoon Characters',
      'folk animation character design',
      [...T, 'gutierrez'],
      {
        look: 'Jorge R. Gutiérrez character design look: Mexican folk art shapes, wooden-toy bodies, skull motifs, marigolds, bold patterns and festive exaggerated silhouettes.',
        subject:
          'design characters like painted wooden folk toys with bold patterns, skull motifs and exaggerated silhouettes.',
        color: 'Festive marigold orange, turquoise, magenta and black.',
        light: 'Warm candlelit festival light.',
        texture: 'Painted wood grain and folk patterns.',
        camera: 'Festive character lineups.',
        mood: 'festive folkloric joy',
        render: 'Folk-art animation character design.',
        key: 'Gutiérrez folk toys; skull motifs; marigolds; bold patterns',
        avoid: ['existing franchise characters'],
        briefs: [
          'Carved and painted like a wooden folk toy, an original mariachi grandmother skeleton with a guitar made of marigolds dances on a festive tile floor. No readable text or logo.',
          'A luchador baker with a mask patterned like a sugar skull kneads bread in a festive kitchen. No readable text or logo.',
          'On a festival floor covered in marigold petals, a single painted wooden sombrero spins slowly while candles flicker around it in a perfect circle. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
