import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, underworlds and realms of the dead: culture-rooted visual languages for journeys
// through death realms, ferrymen, judges and ghost cities. Ten originals stay; twelve new looks add
// Chinese, Japanese, Norse, Mesopotamian, Italian literary, Bengali, Etruscan, Chinese folk,
// Celtic, Persian, Korean and Greek traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} underworld art`,
  tags: [
    tag,
    culture.toLowerCase().replace(/\s+/g, '-'),
    'mythic-underworlds',
    'portable-style-study',
  ],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Underworlds & Realms of the Dead',
  updates: {},
  creates: [
    s(
      'Diyu Ten Courts Scroll',
      'diyu',
      'Chinese',
      'Diyu ten courts scroll: Chinese hanging-scroll paintings of the ten courts of the underworld, stern judges in official robes, ox-headed and horse-faced guards and bridges over dark rivers.',
      'paint the subject as a scene from the courts of the underworld with judges and guardians.',
      'Vermilion, ink black, jade green and gold, kept consistent across the whole image.',
      'Flat painted light with lamp glow, kept consistent across the whole image.',
      'Silk scroll, fine brushwork and mounted borders, kept consistent across the whole image.',
      'Vertical scroll with a judge above and souls below.',
      'solemn bureaucratic dread',
      'Detailed scroll painting without readable script, kept consistent across the whole image.',
      'underworld court; stern judge; ox-head guard; scroll',
      [
        'Seated behind a great desk of black lacquer, an underworld judge in vermilion robes reviews a line of souls as an ox-headed guard and a horse-faced guard drag in a trembling tax collector. No readable text or logo.',
        'At the courts of the underworld, a soul argues with the judge for so long that the ox-headed guard has fallen asleep standing up. No readable text or logo.',
        'At the bridge of forgetting, an old woman ladles soup for the dead, and one soul has walked past without taking a bowl. No readable text or logo.',
      ],
    ),
    s(
      'Jigoku-zoshi Hell Scroll',
      'jigoku',
      'Japanese',
      'Jigoku-zoshi hell scroll: Japanese medieval handscrolls of the hell realms, red flames, blue and red oni wardens, and small pale souls in swirling ink and color.',
      'paint the subject in a handscroll of flaming hell realms with oni wardens.',
      'Flame red, oni blue, ink black and pale skin.',
      'Fire glow on scroll paper, kept consistent across the whole image.',
      'Handscroll paper, swirling flames and fine ink, kept consistent across the whole image.',
      'Long horizontal scroll scene, kept consistent across the whole image.',
      'fiery moral dread',
      'Expressive handscroll painting, kept consistent across the whole image.',
      'hell scroll; flames; oni wardens; handscroll',
      [
        'Unrolling across a long scroll, a river of fire winds past iron mountains as blue and red oni wardens herd pale souls toward a gate guarded by a giant rooster of flame. No readable text or logo.',
        'In a hell scroll, a busy oni warden is taking a tea break on a hot rock and fanning himself with a tiny fan. No readable text or logo.',
        'On an old hell scroll, a single soul climbs a spider thread out of the flames, and the thread above him is fraying. No readable text or logo.',
      ],
    ),
    s(
      'Helheim Frost Painting',
      'helheim',
      'Norse',
      'Helheim frost painting: painterly frozen underworld of the Norse dead, a half-living half-dead queen, ice halls, bone gates and grey rivers of cold mist.',
      'place the subject in a painterly frozen underworld of ice halls and grey mist.',
      'Ice blue, bone white and deep grey, kept consistent across the whole image.',
      'Cold diffuse glow through mist, kept consistent across the whole image.',
      'Frost crystals, bone, ice and painterly mist, kept consistent across the whole image.',
      'Wide hall or gate with a small figure.',
      'cold mournful grandeur',
      'Atmospheric painterly finish, kept consistent across the whole image.',
      'frozen underworld; bone gate; ice hall; mist',
      [
        'Riding a hound across a bridge roofed with gold over a roaring grey river, a messenger approaches the frozen hall where the queen of the dead waits, half her face living and half bone. No readable text or logo.',
        'In the icy hall of the dead, a newly arrived warrior is very disappointed to learn there is no feast, only cold porridge. No readable text or logo.',
        'At the frozen bone gate of the underworld, a single set of warm footprints leads in, melting the frost. No readable text or logo.',
      ],
    ),
    s(
      'Inanna Descent Cylinder Seal',
      'cylinder-seal',
      'Mesopotamian',
      'Inanna descent cylinder seal: Mesopotamian cylinder seal impressions rolled into clay, repeating frieze scenes of the goddess passing through seven gates of the underworld.',
      'render the subject as a repeating frieze rolled from a carved cylinder seal into clay.',
      'Clay brown with dark recesses, kept consistent across the whole image.',
      'Raking light across rolled relief, kept consistent across the whole image.',
      'Rolled clay impression and carved stone seal, kept consistent across the whole image.',
      'Long horizontal repeating frieze, kept consistent across the whole image.',
      'ancient mythic descent',
      'Crisp miniature relief, kept consistent across the whole image.',
      'cylinder seal; rolled clay; seven gates; frieze',
      [
        'Rolled across wet clay, a cylinder seal repeats the goddess of love passing through the seven gates of the underworld, surrendering a crown, a necklace and her robes at each. No readable text or logo.',
        'On a rolled seal impression, a gatekeeper of the underworld keeps asking the goddess for one more item and looks rather embarrassed about it. No readable text or logo.',
        'On a clay tablet rolled with a seal, the procession passes through seven gates, and the last gate is open with no one inside. No readable text or logo.',
      ],
    ),
    s(
      'Inferno Circle Engraving',
      'inferno',
      'Italian literary',
      'Inferno circle engraving: nineteenth-century wood engravings of the circles of the literary inferno, vast dark chasms, dramatic light and crowds of souls in sweeping tone.',
      'engrave the subject in vast dark chasms with dramatic light and sweeping crowds.',
      'Black and silver engraved tones, kept consistent across the whole image.',
      'Dramatic beams of light into darkness, kept consistent across the whole image.',
      'Fine wood-engraved tone and hatching, kept consistent across the whole image.',
      'Vast descending landscape with two small travelers, kept consistent across the whole image.',
      'epic sublime dread',
      'Virtuoso engraved tone, kept consistent across the whole image.',
      'infernal circles; chasms; dramatic light; crowds of souls',
      [
        'Standing on a cliff above a spiral chasm of souls, two poets watch a colossal winged figure frozen in a lake of ice at the very bottom of the pit. No readable text or logo.',
        'In a vast infernal engraving, a demon ferryman is trying to fit far too many souls into one small boat. No readable text or logo.',
        'At the rim of a dark chasm, a narrow path leads down, and a single lantern halfway down is climbing up. No readable text or logo.',
      ],
    ),
    s(
      'Yama Pata Scroll Painting',
      'yama-pata',
      'Bengali',
      'Yama pata scroll painting: Bengali patachitra narrative scrolls with bold outlines and bright colors showing the lord of death on his buffalo and the fates of souls.',
      'paint the subject in bold bright scroll panels of a narrative painting.',
      'Bright yellow, red, green and black, kept consistent across the whole image.',
      'Flat color without shadow, kept consistent across the whole image.',
      'Painted cloth scroll, bold outlines and panels, kept consistent across the whole image.',
      'Vertical panels of a storytelling scroll, kept consistent across the whole image.',
      'vivid moral storytelling',
      'Bold narrative folk painting, kept consistent across the whole image.',
      'narrative scroll; lord of death; buffalo; bright panels',
      [
        "Riding a great black buffalo across a bright scroll panel, the lord of death holds a noose as a devoted wife follows him, arguing for her husband's life. No readable text or logo.",
        "In a bright painted scroll, the lord of death is so impressed by a clever wife's arguments that he has given up and sits down. No readable text or logo.",
        'At the bottom of a painted scroll, the buffalo of death stands alone, waiting for its rider. No readable text or logo.',
      ],
    ),
    s(
      'Etruscan Tomb Fresco',
      'etruscan',
      'Etruscan',
      'Etruscan tomb fresco: lively painted tomb walls with banqueting couples, dancers, blue-skinned underworld demons with hammers and winged guides of the dead.',
      'paint the subject as a lively tomb fresco with banquets and underworld guides.',
      'Red ochre, black, blue-green and cream, kept consistent across the whole image.',
      'Flat fresco light, kept consistent across the whole image.',
      'Tomb plaster, fresco pigment and cracks, kept consistent across the whole image.',
      'Frieze on a tomb wall, kept consistent across the whole image.',
      'festive otherworld mystery',
      'Lively ancient fresco, kept consistent across the whole image.',
      'tomb fresco; banquet; underworld demon; winged guide',
      [
        'Painted on a tomb wall, a banqueting couple reclines on a couch as a blue-skinned demon with a hammer and a winged woman with a torch arrive to guide them onward. No readable text or logo.',
        'On an ancient tomb fresco, a dancer at the afterlife banquet is dancing so enthusiastically that the flute player has stopped to watch. No readable text or logo.',
        'On a painted tomb wall, a door is painted closed, and a painted hand is resting on its edge. No readable text or logo.',
      ],
    ),
    s(
      'Joss Paper Afterlife Mansion',
      'joss-paper',
      'Chinese folk',
      'Joss paper afterlife mansion: paper offerings of houses, cars, servants and banknotes crafted for the dead, glowing as they burn into the afterlife.',
      'build the subject from delicate paper offerings glowing and curling in flame.',
      'Gold foil, red paper and ember orange, kept consistent across the whole image.',
      'Glow of burning paper and embers, kept consistent across the whole image.',
      'Folded paper, gold foil and ash, kept consistent across the whole image.',
      'Paper model in the moment of burning, kept consistent across the whole image.',
      'tender devotional wonder',
      'Delicate paper craft with glow, kept consistent across the whole image.',
      'paper offerings; gold foil; burning; afterlife',
      [
        'Burning in a courtyard brazier, a paper mansion with a garden and a paper car rises as ash and reassembles itself in a glowing city of the dead above. No readable text or logo.',
        'In the afterlife, an ancestor who received a paper smartphone is very confused about how to use it. No readable text or logo.',
        'In a burnt-out brazier, one paper figure has not burned at all and is standing upright among the ashes. No readable text or logo.',
      ],
    ),
    s(
      'Celtic Otherworld Mound Illumination',
      'celtic-otherworld',
      'Celtic',
      'Celtic otherworld mound illumination: illuminated knotwork frames around scenes of the fairy mound, a door into the hill, silver apple trees and endless twilight.',
      'frame the subject in Celtic knotwork around a scene of the otherworld beneath the hill.',
      'Twilight violet, silver, green and gold, kept consistent across the whole image.',
      'Soft twilight glow from within the hill, kept consistent across the whole image.',
      'Vellum, knotwork borders and gold, kept consistent across the whole image.',
      'Illuminated page with a central scene, kept consistent across the whole image.',
      'timeless enchanted longing',
      'Refined illumination without script, kept consistent across the whole image.',
      'fairy mound; knotwork frame; silver apples; twilight',
      [
        'Framed in gold knotwork, a door opens in a green hill at twilight, revealing a hall of silver apple trees where a hundred years pass in a single dance. No readable text or logo.',
        'At the door of a fairy mound, a traveler politely refuses food and drink while a fairy offers him increasingly tempting cakes. No readable text or logo.',
        'On a green hill at dusk, a small door is open, and a fiddle tune drifts out though no one is inside. No readable text or logo.',
      ],
    ),
    s(
      'Chinvat Bridge Miniature',
      'chinvat',
      'Persian',
      'Chinvat bridge miniature: Persian miniature painting of the bridge of judgment over the abyss, widening for the righteous and narrowing to a blade, with guiding maidens and dogs.',
      'paint the subject crossing a bridge over an abyss in jewel-toned miniature style.',
      'Lapis, gold, crimson and spring green, kept consistent across the whole image.',
      'Radiant light from the far shore, kept consistent across the whole image.',
      'Fine pigment, gold leaf and patterned sky, kept consistent across the whole image.',
      'Bridge spanning a deep chasm, kept consistent across the whole image.',
      'luminous moral suspense',
      'Exquisite miniature detail, kept consistent across the whole image.',
      'bridge of judgment; abyss; guiding maiden; dogs',
      [
        'Crossing a bridge that widens into a golden road, a soul is led by a radiant maiden and two white dogs as the abyss below churns with smoke. No readable text or logo.',
        'On the bridge of judgment, a soul keeps stopping to admire the view, and the guiding dogs keep nudging him along. No readable text or logo.',
        'Over a dark abyss, the bridge has narrowed to a thin gleaming edge, and one footprint glows on it. No readable text or logo.',
      ],
    ),
    s(
      'Korean Jeoseung Messenger Painting',
      'jeoseung',
      'Korean',
      'Korean jeoseung messenger painting: Korean painting of the afterlife messengers in black robes and wide hats, the kings of the underworld and lantern-lit paths to the other world.',
      'paint the subject with black-robed afterlife messengers on a lantern-lit path.',
      'Black, muted red, gold and pale ivory, kept consistent across the whole image.',
      'Lantern light on a dark path, kept consistent across the whole image.',
      'Hanji paper, ink and mineral color, kept consistent across the whole image.',
      'Path receding into mist, kept consistent across the whole image.',
      'quiet solemn fate',
      'Refined ink-and-color painting, kept consistent across the whole image.',
      'afterlife messengers; black robes; wide hats; lantern path',
      [
        'Walking a lantern-lit path into mist, three black-robed messengers in wide hats escort a newly departed soul toward a palace of the ten kings. No readable text or logo.',
        'At a village door, an afterlife messenger in a wide black hat has come for an old man who insists on finishing his card game first. No readable text or logo.',
        'On a misty path at night, a wide black hat lies on the ground, and the lantern beside it is still lit. No readable text or logo.',
      ],
    ),
    s(
      'Styx Ferryman Black-Glaze',
      'styx',
      'Greek',
      'Styx ferryman black-glaze: Greek black-glaze pottery painted with the ferryman of the dead poling his boat across the black river, winged guides and shades.',
      'paint the subject in fine red line on glossy black pottery of the river of the dead.',
      'Lustrous black glaze with fine red and white line.',
      'Glossy highlights on glaze, kept consistent across the whole image.',
      'Black glaze, incised lines and clay, kept consistent across the whole image.',
      'Scene around a curved vessel, kept consistent across the whole image.',
      'hushed crossing dread',
      'Elegant glaze painting, kept consistent across the whole image.',
      'ferryman; river of the dead; black glaze; shades',
      [
        'Poling a narrow boat across a river as black as the glaze itself, the ferryman of the dead reaches out for a coin as pale shades wait on the far shore. No readable text or logo.',
        'At the river of the dead, a shade without a coin tries to pay the ferryman with a very nice olive instead. No readable text or logo.',
        'On a black-glazed vase, the boat of the dead crosses empty, and the ferryman is looking back over his shoulder. No readable text or logo.',
      ],
    ),
  ],
};

export default spec;
