import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID as AVOID, style } from './_style';

const spec: Spec = {
  pack: 'pack_10',
  category: '1. Geometric Abstraction',
  updates: {
    'SP10-001': {
      dna: style(
        'Analytic-synthetic Cubism: forms broken into faceted planes seen from several viewpoints at once.',
        'the subject is fractured into overlapping angular planes showing front and profile simultaneously, reassembled into a shallow space.',
        'Muted ochre, grey, olive and brown with occasional collage-like color blocks.',
        'Light is flattened into tonal facets rather than a single source.',
        'Faceted planes, overlapping outlines and paint-like brushwork.',
        'Shallow, compressed picture plane with interlocking facets.',
        'Intellectual, restless, fragmented and dense.',
        'Painterly Cubist finish with clear facet edges.',
        'multiple viewpoints; faceted planes; shallow space; muted ochre-grey',
      ),
      avoid: AVOID,
      briefs: [
        'Cubist painting of a knight and his warhorse seen from front, side and above at once, faceted into ochre and grey planes, a broken lance cutting across. No text or logo.',
        'Cubist painting of an old alchemist at his table, bottles and face fractured into overlapping planes. No text or logo.',
        'Cubist painting of a street musician playing an accordion in a cafe, the instrument, hands and chairs fractured into overlapping ochre and grey planes seen from several angles at once, a wine glass split into facets. No text or logo.',
      ],
    },
    'SP10-002': {
      dna: style(
        'Bauhaus design: primary shapes, clean grids, sans-serif-era modernism reduced to circle, square and triangle.',
        'the subject is simplified into circles, squares, triangles and bold bars arranged on a clean grid.',
        'Red, yellow, blue, black and off-white.',
        'Flat, shadowless color.',
        'Flat printed color with crisp geometric edges.',
        'Balanced asymmetric grid composition.',
        'Rational, bold, modern and clear.',
        'Crisp poster-like finish.',
        'circle square triangle; primary colors; clean grid; flat shapes',
      ),
      avoid: AVOID,
      briefs: [
        'Bauhaus composition of a knight on horseback reduced to circles, triangles and red, yellow and blue bars on off-white. No text or logo.',
        'Bauhaus composition of a castle and moon as squares and a yellow circle on a grid. No text or logo.',
        'Bauhaus composition of a raven built from black triangles with a single red circle eye, perched on a yellow bar across a strict grid on off-white paper, one blue square as the moon. No text or logo.',
      ],
    },
    'SP10-003': {
      dna: style(
        'Constructivism: dynamic diagonals, bold wedges and graphic propaganda energy without photomontage.',
        'the subject is built from strong diagonal wedges, bars and circles pushing across the frame.',
        'Red, black and cream.',
        'Flat graphic contrast.',
        'Flat printed shapes with crisp edges.',
        'Steep diagonals and radiating wedges.',
        'Urgent, heroic, industrial and forceful.',
        'Bold print-like finish.',
        'dynamic diagonals; red wedges; black bars; cream ground',
      ),
      avoid: AVOID,
      briefs: [
        'Constructivist composition of a giant red wedge splitting a black castle, a tiny rider charging on a diagonal. No text or logo.',
        "Constructivist composition of a blacksmith's hammer striking an anvil, both reduced to bold black and red diagonal wedges slicing across the frame, sparks as small red triangles and heavy dynamic tilt. No text or logo.",
        'Constructivist composition of a lighthouse beam cutting the night, the tower a steep black wedge, the beam a long red diagonal bar and the waves stacked grey trapezoids. No text or logo.',
      ],
    },
    'SP10-004': {
      dna: style(
        'Op Art: optical illusions of vibrating stripes, warped grids and moiré that make flat patterns seem to move.',
        'the subject is formed by bending black-and-white stripes or grids so it bulges or recedes optically.',
        'Black and white, sometimes one vibrating color pair.',
        'No light; illusion comes from pattern density.',
        'Precise stripes, checks and warped grids.',
        'Pattern fills the frame with the subject as distortion.',
        'Dizzying, hypnotic, precise and kinetic.',
        'Hard-edged precise finish.',
        'warped stripes; bulging grid illusion; black and white; vibration',
      ),
      avoid: AVOID,
      briefs: [
        "Op art composition where a knight's helmet appears only as a bulge in warped black-and-white stripes. No text or logo.",
        'Op art composition of a spiral staircase seen from above formed by concentric black and white stripes that bend and tighten toward the center, the pattern seeming to rotate. No text or logo.',
        'Op art composition of a coiled snake made from a warped checkerboard that swells and pinches along its body, vibrating black and white squares against a moiré background. No text or logo.',
      ],
    },
    'SP10-005': {
      name: 'De Stijl Grid',
      dna: style(
        'De Stijl grid: black orthogonal lines dividing white fields with a few primary color blocks.',
        'the subject is abstracted into an asymmetric grid of rectangles, with color blocks placed at its key parts.',
        'White fields, black lines, red, yellow and blue blocks.',
        'Flat, no shadows.',
        'Flat paint with crisp lines.',
        'Asymmetric orthogonal balance.',
        'Calm, pure, ordered and spiritual.',
        'Crisp flat finish.',
        'black orthogonal grid; primary blocks; white fields',
      ),
      avoid: AVOID,
      briefs: [
        'De Stijl grid composition of a castle gate: black lines and a red block for the door, a yellow block for the torch. No text or logo.',
        'De Stijl grid composition of a sailboat, black orthogonal lines dividing white fields, a red rectangle for the hull, a yellow square sail and a small blue block of sea. No text or logo.',
        'De Stijl grid composition of a tall stained-glass window, black lead-like orthogonal lines dividing white panes with a few red, yellow and blue rectangles placed off-center. No text or logo.',
      ],
    },
    'SP10-006': {
      dna: style(
        'Fractal geometry: self-similar recursive forms repeating at every scale.',
        'the subject is built from recursive self-similar branches, spirals or tiles repeating inward.',
        'Deep gradients of blue, violet, gold or fire tones.',
        'Glowing edges on recursive forms.',
        'Infinitely detailed recursive branching.',
        'Central spiral or branching recursion.',
        'Infinite, mesmerizing, mathematical and cosmic.',
        'Crisp high-detail digital finish.',
        'self-similar recursion; infinite branching; glowing gradients',
      ),
      avoid: AVOID,
      briefs: [
        'Fractal image of a dragon whose wings split recursively into smaller dragons, spiraling inward in gold and violet. No text or logo.',
        'Fractal image of a tree whose branches split into smaller trees again and again, each fork repeating the whole, deep green at the trunk fading to glowing gold at the tips. No text or logo.',
        'Fractal image of a nautilus shell spiral where each chamber contains a smaller nautilus, self-similar curves repeating inward in pearl and rust tones. No text or logo.',
      ],
    },
    'SP10-007': {
      dna: style(
        'Low-poly abstraction: subjects built from flat-shaded triangles with visible facets.',
        'the subject is triangulated into flat-shaded polygons with no smoothing.',
        'Gradient-sampled flat colors across facets.',
        'Facet shading from one soft light.',
        'Flat triangular facets with crisp edges.',
        'Clean centered subject on a simple faceted ground.',
        'Modern, crystalline, clean and graphic.',
        'Crisp flat-shaded finish.',
        'flat-shaded triangles; visible facets; gradient colors',
      ),
      avoid: AVOID,
      briefs: [
        'Low-poly faceted image of a wolf howling on a triangulated rock under a faceted pale moon, every surface a flat-shaded triangle in cold blues and greys, crisp visible facet edges. No text or logo.',
        'Low-poly faceted image of a hummingbird hovering at a flower, amber, emerald and violet flat-shaded triangles, the wings a spray of sharp facets. No text or logo.',
        'Low-poly faceted image of an erupting volcano at sunset, triangular lava facets in orange and red, a faceted smoke column and a flat-shaded sea. No text or logo.',
      ],
    },
    'SP10-008': {
      dna: style(
        'Suprematism: floating pure geometric shapes on a white void, weightless and non-objective.',
        'the subject is reduced to a few floating rectangles, circles and crosses drifting on white.',
        'Black, red, yellow, blue on white.',
        'Flat, no light.',
        'Flat painted shapes.',
        'Shapes floating diagonally in empty space.',
        'Spiritual, weightless, pure and radical.',
        'Clean painted finish.',
        'floating geometric shapes; white void; diagonal drift',
      ),
      avoid: AVOID,
      briefs: [
        'Suprematist composition of a lighthouse reduced to a few floating black rectangles and a red circle on a white void, the forms tilted and weightless as if drifting apart. No text or logo.',
        'Suprematist composition of a falling acrobat as three tilted bars and a small black square, floating on a white void with one thin red line. No text or logo.',
        'Suprematist composition of a sailing ship as floating crosses and trapezoids in black, red and ochre, drifting across a white void. No text or logo.',
      ],
    },
    'SP10-009': {
      dna: style(
        'Islamic geometric pattern: star-and-polygon tessellations built from compass and straightedge.',
        'the subject is filled or outlined with interlaced star-and-polygon tessellation.',
        'Lapis blue, turquoise, gold, white and terracotta.',
        'Flat or tile-glaze sheen.',
        'Interlaced strapwork, stars and rosettes.',
        'Radial symmetric tessellation.',
        'Harmonious, infinite, sacred and precise.',
        'Precise, crisp geometric finish.',
        'star-and-polygon tessellation; interlaced strapwork; radial symmetry',
      ),
      avoid: [...AVOID, 'religious text'],
      briefs: [
        'Geometric pattern image of a falcon whose feathers are interlaced star tessellations in lapis and gold. No text or logo.',
        'Islamic geometric pattern of a dome interior seen from below, star-and-polygon rosettes radiating from a central twelve-point star, turquoise, cobalt and gold tessellation. No text or logo.',
        'Islamic geometric pattern filling the silhouette of an Arabian horse, turquoise and white interlaced stars inside, the background a deep blue field of smaller polygons. No text or logo.',
      ],
    },
    'SP10-010': {
      dna: style(
        'Voronoi: space divided into irregular cells around seed points, like cracked earth or cells.',
        'the subject is divided into Voronoi cells that follow its form, with thicker cell walls at contours.',
        'Organic gradient colors per cell.',
        'Soft shading inside each cell.',
        'Irregular cells with clean borders.',
        'Cellular fill across subject and ground.',
        'Organic, cellular, scientific and modern.',
        'Clean generative finish.',
        'Voronoi cells; seed points; cellular borders',
      ),
      avoid: AVOID,
      briefs: [
        'Voronoi image of a dragon skull built from irregular cells with thick borders along its contours. No text or logo.',
        'Voronoi image of a desert landscape of cracked earth, irregular cells around seed points in terracotta and ochre, a lone figure walking across the pattern. No text or logo.',
        'Voronoi image of a turtle shell where each scute is a cell around a seed point, deep green borders and amber cell interiors on dark sand. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Orphism Color Discs',
      domain: 'orphist color disc abstraction',
      tags: ['orphism', 'color-discs', 'geometric'],
      dna: style(
        'Orphism: rhythmic concentric color discs and arcs that pulse with simultaneous contrast.',
        'the subject emerges from overlapping concentric color discs and arcs.',
        'Saturated contrasting color rings.',
        'Light is color contrast itself.',
        'Painted concentric rings and arcs.',
        'Circular rhythms around the subject.',
        'Joyful, rhythmic, luminous and musical.',
        'Painterly flat finish.',
        'concentric color discs; simultaneous contrast; rhythmic arcs',
      ),
      avoid: AVOID,
      briefs: [
        'Orphist painting of a carousel with riders and horses dissolving into rhythmic concentric color discs, orange against blue and green against red pulsing with simultaneous contrast. No text or logo.',
        'Orphist painting of a sun rising over a harbor rendered as overlapping color rings and arcs, simultaneous contrast making the orange and violet bands vibrate. No text or logo.',
        'Orphist painting of a dancer spinning, her body built from interlocking arcs and color discs in yellow, magenta and cobalt, the rhythm echoing outward. No text or logo.',
      ],
    },
    {
      name: 'Futurist Force Lines',
      domain: 'futurist dynamism',
      tags: ['futurism', 'force-lines', 'geometric'],
      dna: style(
        'Futurist dynamism: repeated overlapping forms and force lines expressing speed and motion.',
        'the subject is repeated in successive overlapping positions with sharp force lines.',
        'Bright reds, blues and metallic greys.',
        'Dynamic light fragments.',
        'Repeated contours, force lines and fragmented planes.',
        'Diagonal motion across the frame.',
        'Fast, violent, mechanical and exhilarating.',
        'Energetic painted finish.',
        'repeated motion contours; force lines; diagonal speed',
      ),
      avoid: AVOID,
      briefs: [
        'Futurist painting of a galloping cavalry charge repeated in overlapping positions, sharp force lines radiating forward, horses and riders fused into a single wave of motion. No text or logo.',
        'Futurist painting of a steam train bursting across a bridge, the locomotive repeated in overlapping positions, smoke and rails fractured by angular force lines. No text or logo.',
        "Futurist painting of a fencer's lunge, arm and blade repeated in overlapping positions, force lines slicing the space into sharp planes of red and grey. No text or logo.",
      ],
    },
    {
      name: 'Hard-Edge Painting',
      domain: 'hard-edge color field',
      tags: ['hard-edge', 'color-field', 'geometric'],
      dna: style(
        'Hard-edge painting: large flat color areas meeting at razor-sharp edges.',
        'the subject is simplified into a few large flat color shapes with crisp edges.',
        'Bold flat complementary colors.',
        'No shading.',
        'Flat opaque paint with razor edges.',
        'Large simple shapes filling the frame.',
        'Bold, calm, confident and modern.',
        'Clean flat finish.',
        'razor-sharp edges; flat color areas; bold simplicity',
      ),
      avoid: AVOID,
      briefs: [
        "Hard-edge painting of a lone rider's silhouette as one flat orange shape against a teal field and a white disc moon, razor-sharp edges and no gradients. No text or logo.",
        'Hard-edge painting of a lighthouse tower and a setting sun as flat red, cream and navy areas meeting at razor-sharp edges, a single white band of sea. No text or logo.',
        'Hard-edge painting of a crow on a bare branch, flat black shape against a pale mint field, a lemon-yellow sun, every edge razor sharp. No text or logo.',
      ],
    },
    {
      name: 'Precisionism',
      domain: 'precisionist industrial geometry',
      tags: ['precisionism', 'industrial', 'geometric'],
      dna: style(
        'Precisionism: clean, sharp-edged geometric rendering of structures with smooth planes and crisp shadows.',
        'the subject is rendered as clean geometric volumes with smooth planes and precise shadows.',
        'Cool greys, soft blues and cream with sharp shadow shapes.',
        'Crisp directional sun with geometric shadows.',
        'Smooth painted planes without texture.',
        'Frontal or low-angle structural view.',
        'Calm, orderly, monumental and quiet.',
        'Precise smooth finish.',
        'smooth geometric planes; crisp shadows; industrial order',
      ),
      avoid: AVOID,
      briefs: [
        'Precisionist painting of a river mill and its water tower rendered as smooth geometric volumes with crisp shadows, clean planes of cream, rust and sky blue under hard light. No text or logo.',
        'Precisionist painting of a windmill and grain silos rendered as smooth cylinders and cones, crisp cast shadows and a cloudless pale sky. No text or logo.',
        'Precisionist painting of a cathedral flying buttress rendered as clean smooth planes with crisp shadows, grey stone reduced to geometric volumes. No text or logo.',
      ],
    },
    {
      name: 'Vorticism',
      domain: 'vorticist angular abstraction',
      tags: ['vorticism', 'angular', 'geometric'],
      dna: style(
        'Vorticism: hard angular machine-like forms spiraling into a vortex center.',
        'the subject is broken into hard angular shards converging into a vortex.',
        'Strong blacks, reds and ochres.',
        'Harsh contrast.',
        'Sharp angular shards.',
        'Vortex converging to a point.',
        'Aggressive, mechanical, energetic and harsh.',
        'Bold graphic finish.',
        'angular shards; vortex center; machine energy',
      ),
      avoid: AVOID,
      briefs: [
        'Vorticist painting of a ship caught in a storm compressed into hard angular shards spiraling into a vortex center, machine-like forms in black, ochre and electric blue. No text or logo.',
        'Vorticist painting of a lighthouse beam spiraling into angular shards around a vortex center, hard machine-like planes in black, white and acid yellow. No text or logo.',
        'Vorticist painting of a crowd at a factory gate compressed into jagged spiraling planes, angular figures pulled toward the vortex. No text or logo.',
      ],
    },
    {
      name: 'Truchet Tile Weave',
      domain: 'truchet tile patterns',
      tags: ['truchet', 'tiling', 'geometric'],
      dna: style(
        'Truchet tiling: square tiles with quarter-circle or diagonal motifs that combine into flowing mazes.',
        'the subject emerges from a field of rotated Truchet tiles whose curves form its outline.',
        'Two- or three-color schemes.',
        'Flat, no shading.',
        'Tiled quarter-circle arcs.',
        'Grid of tiles filling the frame.',
        'Playful, maze-like, rhythmic and clever.',
        'Crisp graphic finish.',
        'Truchet quarter-circle tiles; emergent curves; grid',
      ),
      avoid: AVOID,
      briefs: [
        "Truchet tile image where a serpent's body emerges from rotated quarter-circle tiles, the flowing maze of arcs in black and cream forming its coils, scales implied by tile rotation. No text or logo.",
        'Truchet tile image of an owl whose outline appears from rotated quarter-circle tiles, black and gold arcs flowing into its eyes and wings. No text or logo.',
        'Truchet tile image of an ocean wave built from diagonal and quarter-circle tiles, navy and white arcs flowing into a curling crest. No text or logo.',
      ],
    },
    {
      name: 'Penrose Aperiodic Tiling',
      domain: 'aperiodic tiling',
      tags: ['penrose', 'aperiodic', 'geometric'],
      dna: style(
        'Penrose tiling: aperiodic kite-and-dart or rhombus tiling with five-fold symmetry.',
        'the subject is filled and outlined with aperiodic rhombus tiles.',
        'Two-tone or jewel palette per tile type.',
        'Flat or subtle tile sheen.',
        'Rhombus tiles with fine grout lines.',
        'Five-fold radial tiling.',
        'Mathematical, mysterious, ordered and unusual.',
        'Crisp precise finish.',
        'aperiodic rhombus tiling; five-fold symmetry',
      ),
      avoid: AVOID,
      briefs: [
        'Penrose tiling image of a star-shaped rose window, kite-and-dart tiles radiating with five-fold symmetry in ruby, amber and cobalt glass tones. No text or logo.',
        'Penrose tiling image of an egg shape filled with aperiodic rhombus tiles in pale blue and gold, five-fold stars appearing across its curve. No text or logo.',
        'Penrose tiling image of a courtyard floor seen from above with a fountain at its center, aperiodic kite-and-dart tiles in terracotta and cream. No text or logo.',
      ],
    },
    {
      name: 'Swiss Grid Composition',
      domain: 'Swiss grid design',
      tags: ['swiss-grid', 'modernism', 'geometric'],
      dna: style(
        'Swiss grid composition: strict modular grid, asymmetric layout, bold geometric image blocks without type.',
        'the subject is placed in a strict modular grid of image blocks and color fields.',
        'Red, black, white and one accent.',
        'Flat or photographic within blocks.',
        'Clean blocks with precise alignment.',
        'Asymmetric modular grid.',
        'Rational, clean, confident and modern.',
        'Crisp print finish.',
        'modular grid; asymmetric blocks; no type',
      ),
      avoid: AVOID,
      briefs: [
        'Swiss grid composition of a cyclist in cropped image blocks — wheel, hand and shoe — arranged on a strict red and white modular grid with asymmetric layout. No text or logo.',
        'Swiss grid composition of a mountain railway in cropped photographic blocks — tunnel, bridge and peak — on a strict black and white modular grid. No text or logo.',
        'Swiss grid composition of a single human eye cropped into three blocks of different scales, strict grid, one red rectangle as the only color. No text or logo.',
      ],
    },
    {
      name: 'String Art Geometry',
      domain: 'string art line geometry',
      tags: ['string-art', 'line-geometry', 'geometric'],
      dna: style(
        'String art: taut straight threads between pins forming curves by envelope.',
        'the subject is drawn by taut threads stretched between pins, curves emerging from straight lines.',
        'Bright thread colors on dark board.',
        'Soft light on threads.',
        'Taut threads, pins and board.',
        'Pinned outline with thread envelopes.',
        'Precise, handmade, delicate and mathematical.',
        'Crisp thread finish.',
        'taut threads; pin outlines; curve envelopes',
      ),
      avoid: AVOID,
      briefs: [
        'String art of a coiled dragon made of gold threads stretched between brass pins on a black board, curves formed by straight thread envelopes. No text or logo.',
        'String art of a sailing ship made of white threads between pins on a navy board, the sails formed by fanned straight lines. No text or logo.',
        'String art of a howling wolf under a full circle, silver threads forming curves by envelope on a charcoal board. No text or logo.',
      ],
    },
    {
      name: 'Neo-Geo Minimalism',
      domain: 'neo-geo minimal geometry',
      tags: ['neo-geo', 'minimal', 'geometric'],
      dna: style(
        'Neo-geo minimalism: cool, slick geometric forms with fluorescent accents and industrial surfaces.',
        'the subject is reduced to slick geometric cells, bars and conduits.',
        'Fluorescent accents on grey and white.',
        'Clean flat light.',
        'Smooth industrial surfaces.',
        'Grid-based cells.',
        'Cool, detached, slick and ironic.',
        'Clean finish.',
        'geometric cells; fluorescent accents; industrial slick',
      ),
      avoid: AVOID,
      briefs: [
        'Neo-geo image of a city block reduced to grey cells connected by fluorescent orange conduits, slick industrial surfaces and cool geometric order. No text or logo.',
        'Neo-geo image of a transit network of cells and conduits in grey and fluorescent pink, slick industrial surface. No text or logo.',
        'Neo-geo image of a stack of cool grey boxes with fluorescent yellow edges like shipping containers, slick industrial finish. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
