import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Medieval atlas regional manuscript traditions: specific painting traditions from the period
// roughly 600-1600 across Afro-Eurasia and Mesoamerica, each scoped to one named corpus as a
// technique study, never a generic "ethnic" look. Four originals get card briefs; sixteen new
// studies add Middle Byzantine, Timurid Herat, Maqamat, Andalusian romance, Coptic, Nara ehon,
// Song album leaves, western Indian, Pala palm-leaf, Mixtec screenfolds, Icelandic saga drawings,
// Bohemian court painting, Majorcan portolans, Deccani, Vaspurakan and Jalayirid painting.
const study = (
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof dna>[0],
  avoid: string[],
  briefs: [string, string, string],
): Create => ({
  name,
  domain,
  tags: [tag, 'regional-manuscript', 'portable-style-study'],
  dna: dna(fields),
  avoid: [...avoid, 'cultural stereotypes or costume caricature', 'readable script', 'mixing unrelated traditions', ...STYLE_AVOID],
  briefs,
});

const keep = 'Preserve the requested identity, count, pose and action with original figures';

const spec: Spec = {
  pack: 'pack_23',
  category: '4. Regional Manuscript Traditions',
  updates: {
    'SP23-018': { briefs: [
      'Crossing a rope bridge above a gorge, a wayfarer realizes the bridge is the long braided tail of a sleeping mountain beast, drawn in fine disciplined contours and compact jewel-bright color fields. No readable text or logo.',
      'In compact jewel-colored fields, a very proud peacock has spread its tail so wide that it has knocked over the entire garden table beside it. No readable text or logo.',
      'Under a small arch of disciplined geometric ornament, a lone traveler stands at a closed gate, and a thin line of gold light leaks from beneath it onto his feet. No readable text or logo.',
    ] },
    'SP23-019': { briefs: [
      'At a mountain spring, a hero wrestles a winged beast with reed-like scales while layered hills, twisted trees and a startled horse rise behind them in bounded pigment spaces. No readable text or logo.',
      'Overlapping layers of rocks and trees frame a camp where a whole royal hunting party has gathered to watch one very stubborn donkey refuse to move. No readable text or logo.',
      'Deep in layered painted mountains, a traveler has fallen asleep beside his horse, and the rocks behind them are shaped like the faces of watching giants. No readable text or logo.',
    ] },
    'SP23-020': { briefs: [
      'Through crisp geometric planes of red, yellow and green, a high stone aqueduct crosses a ravine as a great eagle carries a traveler\'s whole pack mule into the sky. No readable text or logo.',
      'Framed in compact geometric bands, a lion and a goat sit across a game board, and the goat is clearly winning. No readable text or logo.',
      'In flat opaque geometry, a small traveler stands at the bottom of a staircase cut into a cliff, and the staircase disappears into a band of pure dark color. No readable text or logo.',
    ] },
    'SP23-021': { briefs: [
      'Rushing along a rhythmic brush-drawn river, a burning ox cart races across a bridge while a crowd of tiny figures runs in every direction in flowing contained washes. No readable text or logo.',
      'In lively brush contours, a frog and a hare hold a wrestling match while a monkey referee has completely lost control of the audience. No readable text or logo.',
      'Along a misty brush-drawn road at night, a procession of old household objects with little legs, umbrellas, pots and lanterns, parades past a sleeping house. No readable text or logo.',
    ] },
  },
  creates: [
    study('Middle Byzantine Book Miniature', 'middle byzantine illuminated miniature', 'byzantine-miniature', {
      aesthetic: 'Middle Byzantine book miniature: tenth- to twelfth-century Constantinopolitan book painting with elegant elongated figures, gold grounds, soft green-shadowed flesh and classical drapery.',
      subject_treatment: `${keep}; give figures graceful elongated proportions and classical drapery against gold.`,
      color_and_tone: 'Burnished gold ground, lapis blue, rose, olive-green flesh shadows.',
      lighting_and_shadow: 'Soft modeling with fine white highlight lines on drapery.',
      texture_and_material: 'Gold leaf, flaking pigment on parchment and fine brushwork.',
      camera_and_composition: 'Few figures on a narrow ground strip against gold, framed by a thin border.',
      atmosphere_and_mood: 'Keep the requested mood with calm courtly elegance.',
      rendering_and_quality: "Refined miniature detail with luminous gold, kept consistent across the whole image.",
      key_features: 'gold ground; elongated figures; green-shadowed flesh; white highlight lines',
    }, [], [
      'Against burnished gold, an emperor\'s astronomer holds up a painted sphere and discovers a small extra star that is moving on its own. No readable text or logo.',
      'On a narrow ground strip before gold, two elegant court musicians play for a bear who is enjoying the concert more than anyone else. No readable text or logo.',
      'In a gold-ground miniature, a tall figure walks away from a sleeping city, and every window behind her closes one by one. No readable text or logo.',
    ]),
    study('Herat Timurid Garden Miniature', 'fifteenth-century herat painting', 'timurid-herat', {
      aesthetic: 'Herat Timurid garden miniature: fifteenth-century Persian book painting from Herat, jewel-toned gardens, tiled pavilions, slender figures and high horizons full of flowering trees.',
      subject_treatment: `${keep}; place slender figures in a high-horizon garden with tiled pavilions and flowering trees.`,
      color_and_tone: 'Lapis, turquoise, apricot, leaf green and gold sky.',
      lighting_and_shadow: "Even jewel-like light with no cast shadows, kept consistent across the whole image.",
      texture_and_material: 'Fine opaque pigment, gold, tiny patterned tiles and carpets.',
      camera_and_composition: 'High viewpoint with stacked space rising to a gold sky.',
      atmosphere_and_mood: 'Keep the requested mood with poetic courtly beauty.',
      rendering_and_quality: "Exquisite small detail with patterned surfaces, kept consistent across the whole image.",
      key_features: 'tiled pavilion; flowering garden; high horizon; jewel tones',
    }, [], [
      'In a jeweled garden with a tiled pavilion, a prince has invited a giant simurgh-like bird to dinner and it is eating the entire banquet. No readable text or logo.',
      'Beneath a flowering almond tree, a poet reads to a crowd of cats who are all pretending to listen while watching a bird. No readable text or logo.',
      'In a high-horizon garden under a gold sky, a woman at a pavilion window watches a single rider arriving, but the rider has no shadow. No readable text or logo.',
    ]),
    study('Maqamat Tavern Miniature', 'thirteenth-century baghdad maqamat painting', 'maqamat', {
      aesthetic: 'Maqamat tavern miniature: thirteenth-century Baghdad illustrations of lively everyday stories, expressive figures in striped robes, camels, ships, taverns and libraries on plain grounds.',
      subject_treatment: `${keep}; show expressive everyday figures in a lively story scene with lively gestures.`,
      color_and_tone: 'Warm reds, blues, ochres and gold on a pale plain ground.',
      lighting_and_shadow: "Flat with light modeling in robes, kept consistent across the whole image.",
      texture_and_material: 'Opaque pigment on paper, striped patterned textiles, simple settings.',
      camera_and_composition: 'Figures arranged in a row or around a central action.',
      atmosphere_and_mood: 'Keep the requested mood with witty worldly humor.',
      rendering_and_quality: "Expressive faces and gestures with clear storytelling, kept consistent across the whole image.",
      key_features: 'expressive figures; striped robes; plain ground; everyday story',
    }, [], [
      'At a busy caravan stop, a clever trickster has convinced a row of camels that he is their leader, and they are all following him into a library. No readable text or logo.',
      'Aboard a small ship with a patterned sail, travelers argue loudly about the route while a fish leaps out and points the way. No readable text or logo.',
      'In a quiet library of stacked books, a scholar reaches for one volume and discovers a hand reaching from the other side of the shelf. No readable text or logo.',
    ]),
    study('Andalusian Garden Romance Miniature', 'andalusian romance manuscript painting', 'andalusian-romance', {
      aesthetic: 'Andalusian garden romance miniature: thirteenth-century western Islamic painting of lovers\' stories, gardens with water wheels, palaces with horseshoe arches and stylized trees beside a river.',
      subject_treatment: `${keep}; set the figures beside a river garden with horseshoe arches and a water wheel.`,
      color_and_tone: 'Warm reds, soft greens, blue water and cream grounds.',
      lighting_and_shadow: "Flat with gentle robe modeling, kept consistent across the whole image.",
      texture_and_material: "Opaque pigment, stylized trees and patterned architecture, kept consistent across the whole image.",
      camera_and_composition: 'Figures on a river bank with palace and water wheel behind.',
      atmosphere_and_mood: "Keep the requested mood with lyrical longing, kept consistent across the whole image.",
      rendering_and_quality: "Clear graceful figures with stylized garden elements, kept consistent across the whole image.",
      key_features: 'horseshoe arches; water wheel; river garden; stylized trees',
    }, [], [
      'By a river under horseshoe arches, a lovesick young man plays the oud so sadly that the water wheel has stopped turning to listen. No readable text or logo.',
      'In a riverside garden, a group of noble ladies laugh at a very proud peacock who has fallen into the fountain. No readable text or logo.',
      'Beneath a palace window with a horseshoe arch, a figure waits by the river at night, and in the water her reflection is holding someone else\'s hand. No readable text or logo.',
    ]),
    study('Coptic Interlace Frontispiece', 'coptic egyptian manuscript ornament', 'coptic', {
      aesthetic: 'Coptic interlace frontispiece: Egyptian Christian book painting with bold interlace crosses and frames, birds and simple frontal figures in red, yellow and green on parchment.',
      subject_treatment: `${keep}; render simple frontal figures or birds framed by bold ribbon interlace.`,
      color_and_tone: 'Red, yellow ochre, green and black on warm parchment.',
      lighting_and_shadow: "Flat with no modeling, kept consistent across the whole image.",
      texture_and_material: "Thick outlines, ribbon interlace and aged parchment, kept consistent across the whole image.",
      camera_and_composition: 'Centered framed motif with birds or figures at the corners.',
      atmosphere_and_mood: 'Keep the requested mood with humble earnest devotion.',
      rendering_and_quality: "Bold simple shapes with clear interlace, kept consistent across the whole image.",
      key_features: 'ribbon interlace frame; frontal figures; birds; warm parchment',
    }, [], [
      'Inside a bold ribbon interlace frame, two large-eyed birds guard a small sleeping figure, their wings spread over her like a roof. No readable text or logo.',
      'Framed by red and yellow interlace, a frontal camel with a very serious face stands exactly in the center, having refused to move out of the frame. No readable text or logo.',
      'At the heart of a knotted green interlace, a single frontal figure holds an oil lamp, and the ribbons tighten slowly around its flame. No readable text or logo.',
    ]),
    study('Nara Picture Book', 'japanese nara ehon painting', 'nara-ehon', {
      aesthetic: 'Nara picture book: Japanese Muromachi and early Edo illustrated storybooks with naive bright figures, gold cloud bands, simple architecture and tales of foxes, demons and heroes.',
      subject_treatment: `${keep}; draw simple charming figures in a story scene divided by gold cloud bands.`,
      color_and_tone: 'Bright mineral green, red, blue and gold clouds on paper.',
      lighting_and_shadow: "Flat with no shadow, kept consistent across the whole image.",
      texture_and_material: 'Opaque mineral pigment, gold flake clouds and simple ink lines.',
      camera_and_composition: 'Elevated view with roofless rooms and cloud bands.',
      atmosphere_and_mood: 'Keep the requested mood with naive folk wonder.',
      rendering_and_quality: "Simple charming figures with bright clean color, kept consistent across the whole image.",
      key_features: 'gold cloud bands; roofless rooms; naive figures; mineral green',
    }, [], [
      'Between gold cloud bands, a young hero sails into a harbor of ogres, who are all very surprised because they were in the middle of a birthday party. No readable text or logo.',
      'In a roofless room seen from above, a fox bride at her wedding forgets herself and her tail slips out from beneath her robe as the guests stare. No readable text or logo.',
      'Seen through gold clouds, an old woman opens a gift box on her porch and a curl of smoke rises that turns into her own younger face. No readable text or logo.',
    ]),
    study('Song Court Album Leaf', 'song dynasty small album painting', 'song-album', {
      aesthetic: 'Song court album leaf: small Chinese court paintings on silk fans and album leaves, one corner composition, misty distances, precise birds and branches, vast empty space.',
      subject_treatment: `${keep}; place the subject in one corner with precise detail and vast misty space.`,
      color_and_tone: 'Soft silk browns, pale mineral greens and ink grey.',
      lighting_and_shadow: "Soft atmospheric mist and graded ink wash, kept consistent across the whole image.",
      texture_and_material: 'Aged silk weave, fine ink lines and light color washes.',
      camera_and_composition: 'Asymmetric one-corner composition on a round or square leaf.',
      atmosphere_and_mood: 'Keep the requested mood with poetic contemplative stillness.',
      rendering_and_quality: "Precise brush detail balanced with empty space, kept consistent across the whole image.",
      key_features: 'one-corner composition; misty space; aged silk; precise birds',
    }, [], [
      'In one misty corner of a round silk leaf, a scholar on a cliff watches a colossal dragon-like cloud rise from the valley, the rest of the leaf empty silk. No readable text or logo.',
      'On a small album leaf, a very round sparrow sits on a plum branch that is bending far too low under its weight. No readable text or logo.',
      'In the corner of a pale silk leaf, a boat drifts in mist with its fisherman asleep, and a thin line in the water shows something following it. No readable text or logo.',
    ]),
    study('Western Indian Red-Ground Manuscript', 'western indian manuscript painting', 'western-indian', {
      aesthetic: 'Western Indian red-ground manuscript: fourteenth- to sixteenth-century Gujarati painting with brilliant red grounds, gold, angular figures in profile with the far eye projecting.',
      subject_treatment: `${keep}; draw angular profile figures with the projecting far eye against a red ground.`,
      color_and_tone: 'Brilliant vermilion ground with gold, ultramarine and white.',
      lighting_and_shadow: "Flat with no shading, kept consistent across the whole image.",
      texture_and_material: 'Opaque pigment, gold, crisp outlines on paper or palm leaf.',
      camera_and_composition: 'Horizontal panel with figures in rows and patterned borders.',
      atmosphere_and_mood: 'Keep the requested mood with bright festive intensity.',
      rendering_and_quality: "Crisp angular line with intense flat color, kept consistent across the whole image.",
      key_features: 'red ground; projecting far eye; angular profiles; gold detail',
    }, [], [
      'On a brilliant red ground, a royal elephant carrying a whole musical band on its back has stopped because a tiny mouse is standing in the road. No readable text or logo.',
      'In a horizontal red panel, two merchants in angular profile haggle so fiercely over a single mango that both of their turbans have fallen off. No readable text or logo.',
      'Against a red ground edged in gold, a lone figure in profile walks through a forest where every tree has an eye looking back at her. No readable text or logo.',
    ]),
    study('Palm-Leaf Manuscript Painting', 'long narrow palm-leaf illustration', 'palm-leaf', {
      aesthetic: 'Palm-leaf manuscript painting: tiny bright paintings on long narrow palm leaves from eastern India, figures in small panels between rows, with string holes and worn leaf edges.',
      subject_treatment: `${keep}; paint the subject tiny inside a small panel on a long narrow palm leaf.`,
      color_and_tone: 'Red, yellow, green, blue and white on golden-brown leaf.',
      lighting_and_shadow: "Flat with soft modeling on figures, kept consistent across the whole image.",
      texture_and_material: 'Palm-leaf fibers, string holes, worn edges and tiny brushwork.',
      camera_and_composition: 'Very wide narrow strip with a central painted panel.',
      atmosphere_and_mood: 'Keep the requested mood with intimate precious calm.',
      rendering_and_quality: "Tiny delicate figures with believable leaf wear, kept consistent across the whole image.",
      key_features: 'long narrow leaf; small panels; string holes; tiny brushwork',
    }, ['readable script'], [
      'In a tiny panel on a long palm leaf, a monkey army builds a bridge across the sea by holding tails, and one monkey in the middle is clearly regretting it. No readable text or logo.',
      'Painted on a worn palm leaf, a small figure feeds a peacock that has decided to sit in her lap like a very large cat. No readable text or logo.',
      'In a panel beside a string hole, a figure meditates under a tree while a king cobra spreads its hood above her like a quiet umbrella in the rain. No readable text or logo.',
    ]),
    study('Mixtec Screenfold Codex', 'painted deerskin screenfold history', 'mixtec-codex', {
      aesthetic: 'Mixtec screenfold codex: pre-Columbian painted deerskin histories from Oaxaca, flat brilliantly colored profile figures with bold outlines, place signs and meander guide lines.',
      subject_treatment: `${keep}; draw the subject as flat bold-outlined profile figures moving along a meander line.`,
      color_and_tone: 'Red, yellow, turquoise, black and white on cream gesso.',
      lighting_and_shadow: "Flat with no shading, kept consistent across the whole image.",
      texture_and_material: 'Gesso-coated deerskin, bold black outlines and fold creases.',
      camera_and_composition: 'Figures travel along red guide lines across folded panels.',
      atmosphere_and_mood: 'Keep the requested mood with ceremonial historical grandeur.',
      rendering_and_quality: "Crisp flat color with strong consistent outline, kept consistent across the whole image.",
      key_features: 'flat profile figures; bold outlines; meander guide lines; fold creases',
    }, ['readable glyphs as text', 'generic tribal pattern'], [
      'Walking along a red meander line across folded panels, a ruler in a jaguar helmet leads a long procession toward a mountain that is opening its mouth. No readable text or logo.',
      'In flat bold color on cream gesso, a hero and a very large turkey face each other in profile, both certain they are the more important figure. No readable text or logo.',
      'Along a folded screenfold, a figure descends a staircase into a cave where the guide line simply stops in a field of black. No readable text or logo.',
    ]),
    study('Icelandic Saga Margin Drawing', 'icelandic manuscript pen drawing', 'icelandic-saga', {
      aesthetic: 'Icelandic saga margin drawing: rough lively pen drawings from Icelandic manuscripts, vigorous gods, heroes and sea monsters drawn in brown ink with simple washes.',
      subject_treatment: `${keep}; draw the subject in vigorous brown-ink lines with rough energetic gestures.`,
      color_and_tone: 'Brown ink with faded red and green washes on yellowed vellum.',
      lighting_and_shadow: "No modeling beyond hatched strokes, kept consistent across the whole image.",
      texture_and_material: 'Rough pen lines, worn vellum, stains and holes.',
      camera_and_composition: 'Single figure or struggle filling a margin or page.',
      atmosphere_and_mood: 'Keep the requested mood with rugged northern vigor.',
      rendering_and_quality: "Energetic rough drawing with strong character, kept consistent across the whole image.",
      key_features: 'brown ink; rough vigorous line; worn vellum; sea monsters',
    }, [], [
      'Drawn in rough brown ink, a giant fisherman hauls up a sea serpent so big that his boat is cracking and his foot has gone straight through the hull. No readable text or logo.',
      'In a vigorous margin drawing, a bearded hero tries to lift a sleeping cat that is secretly as heavy as a mountain. No readable text or logo.',
      'On worn yellowed vellum, a lone rider on an eight-legged horse gallops toward a distant hall where every window is dark. No readable text or logo.',
    ]),
    study('Bohemian Court Miniature', 'late fourteenth-century prague court painting', 'bohemian-court', {
      aesthetic: 'Bohemian court miniature: late fourteenth-century Prague court book painting with soft rounded figures, playful marginal bath attendants, wild men and knotted ribbons among acanthus.',
      subject_treatment: `${keep}; give soft rounded figures and playful marginal characters tangled in ribbons.`,
      color_and_tone: 'Soft rose, blue, green and burnished gold on vellum.',
      lighting_and_shadow: "Gentle soft modeling on rounded forms, kept consistent across the whole image.",
      texture_and_material: 'Fine pigment, acanthus scrolls, knotted ribbons and gold.',
      camera_and_composition: 'Central scene framed by margin characters and scrolls.',
      atmosphere_and_mood: 'Keep the requested mood with playful courtly sweetness.',
      rendering_and_quality: "Soft refined miniature with lively margins, kept consistent across the whole image.",
      key_features: 'soft rounded figures; knotted ribbons; acanthus scrolls; margin characters',
    }, [], [
      'Tangled in a knotted blue ribbon among acanthus scrolls, a king has been tied up by a pair of cheerful bath attendants who are giving him a bath he did not ask for. No readable text or logo.',
      'In a soft court miniature, a hairy wild man in the margin offers a bouquet to a lady, who is politely pretending not to notice. No readable text or logo.',
      'Among gold acanthus, a small knotted ribbon forms a noose around a sleeping kingfisher, and a tiny hand from the margin is reaching to untie it. No readable text or logo.',
    ]),
    study('Majorcan Portolan Chart', 'painted medieval sea chart', 'portolan', {
      aesthetic: 'Majorcan portolan chart: fourteenth-century painted sea charts with webs of rhumb lines radiating from compass roses, coastlines, flags, kings in tents and camel caravans.',
      subject_treatment: `${keep}; place the subject on a painted sea chart among rhumb lines and compass roses.`,
      color_and_tone: 'Vellum cream, gold, red, green and blue lines.',
      lighting_and_shadow: "Flat chart painting without light, kept consistent across the whole image.",
      texture_and_material: 'Vellum, fine ruled rhumb lines, tiny painted figures.',
      camera_and_composition: 'Top-down chart with radiating lines and small vignettes.',
      atmosphere_and_mood: 'Keep the requested mood with adventurous trade and discovery.',
      rendering_and_quality: "Crisp line networks with miniature vignettes, kept consistent across the whole image.",
      key_features: 'rhumb line web; compass rose; coastlines; small vignettes',
    }, ['readable place names'], [
      'On a painted sea chart webbed with rhumb lines, a tiny ship follows one golden line straight into the open mouth of a painted whale. No readable text or logo.',
      'Among radiating compass lines, a small king sits in his tent on the coast and angrily points at a camel caravan that has walked onto the sea. No readable text or logo.',
      'On a vellum sea chart, every rhumb line meets at a compass rose except one, which leads off the edge of the chart into darkness. No readable text or logo.',
    ]),
    study('Deccani Twilight Painting', 'deccan sultanate painting', 'deccani', {
      aesthetic: 'Deccani twilight painting: sixteenth- and seventeenth-century painting from the Deccan sultanates, dreamy gold skies, lavender and green palettes and lyrical figures in fantastical landscapes.',
      subject_treatment: `${keep}; set lyrical figures in a dreamy twilight landscape under glowing gold skies.`,
      color_and_tone: 'Lavender, soft green, rose and glowing gold skies.',
      lighting_and_shadow: "Soft glowing twilight with no harsh shadow, kept consistent across the whole image.",
      texture_and_material: "Fine opaque pigment, gold and delicate foliage, kept consistent across the whole image.",
      camera_and_composition: 'Figure in a lush fantastical landscape with high horizon.',
      atmosphere_and_mood: 'Keep the requested mood with dreamy poetic melancholy.',
      rendering_and_quality: "Refined lyrical detail with soft glowing color, kept consistent across the whole image.",
      key_features: 'gold sky; lavender palette; fantastical landscape; lyrical figures',
    }, [], [
      'Under a glowing gold twilight sky, a lone musician plays for a flock of cranes who have landed in a perfect circle to listen, the trees around them lavender and rose. No readable text or logo.',
      'In a dreamy lavender landscape, a noble on a horse has stopped to argue with a very philosophical goat standing on a rock. No readable text or logo.',
      'Beneath a gold sky fading to violet, a woman waits under a flowering tree and the flowers are falling upward into the dusk. No readable text or logo.',
    ]),
    study('Vaspurakan Folk Miniature', 'armenian vaspurakan painting', 'vaspurakan', {
      aesthetic: 'Vaspurakan folk miniature: thirteenth- to fifteenth-century Armenian manuscript painting from the Lake Van region, bold simplified figures, huge eyes, bright flat colors and plain grounds.',
      subject_treatment: `${keep}; simplify the subject into bold flat shapes with huge eyes on a plain ground.`,
      color_and_tone: 'Bright red, yellow, green and blue on plain parchment.',
      lighting_and_shadow: "Flat with no modeling, kept consistent across the whole image.",
      texture_and_material: "Thick outlines, flat opaque color, worn parchment, kept consistent across the whole image.",
      camera_and_composition: "Frontal or profile figures isolated on parchment, kept consistent across the whole image.",
      atmosphere_and_mood: 'Keep the requested mood with strong naive directness.',
      rendering_and_quality: "Bold simple forms with striking expressions, kept consistent across the whole image.",
      key_features: 'huge eyes; bold flat shapes; plain ground; bright colors',
    }, [], [
      'On plain parchment, a huge-eyed fisherman lifts a fish as big as himself from a lake, and the fish looks just as surprised as he does. No readable text or logo.',
      'In bold flat colors, a proud rooster with enormous eyes wakes up a whole village by standing directly on the roof of the loudest sleeper. No readable text or logo.',
      'A single huge-eyed figure stands alone on bare parchment holding a lamp, looking at something just outside the edge of the page. No readable text or logo.',
    ]),
    study('Jalayirid Dream Landscape', 'fourteenth-century jalayirid painting', 'jalayirid', {
      aesthetic: 'Jalayirid dream landscape: late fourteenth-century Baghdad and Tabriz painting with small figures in towering spongy rock formations, flowering meadows and delicate lyrical detail.',
      subject_treatment: `${keep}; place small figures within towering spongy rocks and flowering meadows.`,
      color_and_tone: 'Soft lilac rocks, gold sky, spring green and floral dots.',
      lighting_and_shadow: 'Soft even light with gentle color gradation in rocks.',
      texture_and_material: "Fine pigment, sponge-like rocks and dotted flowers, kept consistent across the whole image.",
      camera_and_composition: 'Tall vertical landscape with figures small at the base.',
      atmosphere_and_mood: 'Keep the requested mood with enchanted dreamlike calm.',
      rendering_and_quality: "Delicate lyrical detail across the whole landscape, kept consistent across the whole image.",
      key_features: 'spongy towering rocks; flowering meadow; small figures; gold sky',
    }, [], [
      'Among towering lilac rocks, a tiny prince has found a sleeping giant whose body forms half of the mountain, a flowering meadow growing on its chest. No readable text or logo.',
      'In a meadow of dotted flowers below spongy rocks, a picnic of courtiers is interrupted by a family of rabbits who have come to share. No readable text or logo.',
      'At the foot of tall dreamlike rocks, a lone figure notices that one of the stones has the calm, closed-eyed face of someone sleeping. No readable text or logo.',
    ]),
  ],
};

export default spec;
