import type { Create, Dna, Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Weathering is a surface treatment with an explicit intensity. The target keeps its structure;
// collapse, ruins or abandonment scenes are not added unless the prompt asks for them.
const AVOID = [...MATERIAL_AVOID, 'structural collapse', 'unrequested ruins or abandonment scene'];
const w = (a: string, b: string, c: string, l: string, t: string, m: string, k: string): Dna =>
  material(
    a,
    `${b} Default intensity is moderate; follow the prompt if it asks for light or heavy wear.`,
    c,
    l,
    t,
    m,
    `${k}; surface-level damage; structure intact`,
    'surfaces of the target named in the prompt',
  );

const spec: Spec = {
  pack: 'pack_09',
  category: '3. Weathering And Decay',
  updates: {
    'SP09-018': {
      dna: w(
        'Rusty iron: iron or steel surfaces oxidized into orange-brown rust with flaking scale and streaks.',
        'rust blooms from edges, bolts and seams, with flaking scale and run-off streaks.',
        'Orange, umber and dark brown rust over grey steel.',
        'Low warm light that shows flaking relief.',
        'Oxide scale, pitting, flakes and streaks.',
        'Neglected, industrial, harsh and timeworn.',
        'orange rust blooms; flaking scale; run-off streaks; pitting',
      ),
      avoid: AVOID,
      briefs: [
        "Still standing proud on its stand in a leaking barn, a suit of armor has rusted orange-brown, flaking scale piled at its feet. No readable text or logo.",
        "Rising from a field of red poppies, an iron serpent sculpture bleeds orange-brown rust streaks down its flaking wings. No readable text or logo.",
        "In a sunny kitchen window hangs an iron birdcage flaking orange scale, a live yellow canary singing inside. No readable text or logo.",
      ],
    },
    'SP09-025': {
      dna: w(
        'Cracked porcelain: glazed ceramic surfaces crazed with hairline cracks and a few chips.',
        'fine crazing across the glaze with a few deeper cracks and chipped edges, the object still whole.',
        'Glazed white, celadon or blue-and-white with dark crack lines.',
        'Soft light with glaze highlights.',
        'Crazed glaze network, chips and exposed bisque.',
        'Fragile, precious, aged and delicate.',
        'crazed glaze network; hairline cracks; chipped edges',
      ),
      avoid: AVOID,
      briefs: [
        "On a velvet cushion a white-and-cobalt glazed helmet is crazed with hairline cracks across the visor, one small chip at the crest. No readable text or logo.",
        "A blue-and-white ceramic dragon on a dim cabinet shelf is webbed with fine crazing, a chip missing from one claw. No readable text or logo.",
        "On a lacquered table a celadon horse shows fine dark cracks through its pale green glaze and a chipped ear. No readable text or logo.",
      ],
    },
    'SP09-030': {
      dna: w(
        'Burlap decay: coarse sackcloth surfaces frayed, stained and patched.',
        "the target's fabric surfaces fray at seams and edges, with stains and rough patches.",
        'Sack brown with darker stains and pale frayed threads.',
        'Dim natural light.',
        'Coarse weave, loose threads, stains and patches.',
        'Poor, worn, rustic and humble.',
        'frayed burlap; stains; patched weave',
      ),
      avoid: AVOID,
      briefs: [
        "In a windy field a scarecrow sentinel's sackcloth tabard hangs frayed and stained, a crow tugging loose threads from the hem. No readable text or logo.",
        "In a cold stone hall a throne hides under a frayed, stained sackcloth cover, torn at the hem and patched with mismatched squares. No readable text or logo.",
        "Slumped on a dusty windowsill, a small sackcloth doll shows coffee-colored stains and a crude patch sewn over one arm. No readable text or logo.",
      ],
    },
    'SP09-033': {
      dna: w(
        'Peeling paint: layered paint coats curling, cracking and flaking off to reveal older colors beneath.',
        'paint layers curl and flake from the target, revealing older coats and bare material.',
        'Layered pastel and faded colors over bare wood or metal.',
        'Soft raking light on curling flakes.',
        'Curling paint flakes, cracked layers and exposed substrate.',
        'Nostalgic, faded, neglected and layered.',
        'curling paint flakes; layered old colors; exposed substrate',
      ),
      avoid: AVOID,
      briefs: [
        "An old carousel horse sheds thick layered paint in curls, pink over mint over red, bare wood showing at the nose. No readable text or logo.",
        "In a town square a bronze general sheds a coat of blue paint that cracks and curls away, flakes scattered around the plinth. No readable text or logo.",
        "Pulled onto a pebble beach, a wooden rowboat lets white, red and green coats of paint curl off its hull in long strips. No readable text or logo.",
      ],
    },
    'SP09-034': {
      dna: w(
        'Mold and mildew: fuzzy spotted mold colonies spreading over damp surfaces.',
        "patchy mold colonies and mildew spots spread over the target's damp surfaces.",
        'Black, grey-green and white mold spots.',
        'Dim damp light.',
        'Fuzzy mold colonies, spots and damp stains.',
        'Unsettling, damp, neglected and organic.',
        'fuzzy mold colonies; mildew spots; damp stains',
      ),
      avoid: AVOID,
      briefs: [
        "In a damp crypt a velvet throne is spotted with fuzzy grey-green colonies spreading over the armrests. No readable text or logo.",
        "In an abandoned hallway an ornate wedding portrait frame is spotted with black mildew creeping across the gilding. No readable text or logo.",
        "Left on a kitchen table for weeks, a crown baked from bread sprouts fuzzy blue and white colonies over its points. No readable text or logo.",
      ],
    },
    'SP09-035': {
      dna: w(
        'Charred wood (shou sugi ban): wood surfaces deliberately charred into black alligator-skin char.',
        'the wooden surfaces are charred into black crackled alligator texture, brushed to reveal grain on edges.',
        'Deep charcoal black with silvery sheen and brown grain.',
        'Low side light on the crackled char.',
        'Crackled char, silvery sheen and exposed grain.',
        'Dark, elegant, protective and primal.',
        'alligator char crackle; silvery sheen; brushed grain',
      ),
      avoid: AVOID,
      briefs: [
        "Standing in fresh snow, a horse sculpture of deliberately charred timber shows deep black alligator-skin char across its body. No readable text or logo.",
        "In a stone courtyard a warrior carved from charred timber shows brushed ridges where brown grain breaks through the black. No readable text or logo.",
        "In a bright white gallery a wooden throne charred into cracked black scales glints with a faint silver sheen. No readable text or logo.",
      ],
    },
    'SP09-036': {
      dna: w(
        'Water damage: tide lines, swelling, staining and bloom where water soaked the target.',
        'tide-line stains, swelling, warping and mineral bloom where water soaked the surfaces.',
        'Brown tide lines, grey bloom and darkened wet zones.',
        'Soft window light.',
        'Warped swollen surfaces, tide lines and bloom.',
        'Melancholic, neglected, damp and quiet.',
        'tide-line stains; swelling; mineral bloom',
      ),
      avoid: AVOID,
      briefs: [
        "In an otherwise tidy parlor a piano stands swollen after a flood, brown tide lines ringing its legs at the height the water reached. No readable text or logo.",
        "On a chapel wall a painted wooden saint bears brown tide lines across its gold background, the panel warped and split. No readable text or logo.",
        "In a nursery after the flood a wooden rocking horse has swollen joints split open and pale paint bloom on its legs. No readable text or logo.",
      ],
    },
    'SP09-037': {
      dna: w(
        'Scratched metal: bright scratches and scuffs cutting through a metal finish.',
        'bright scratches, scuffs and nicks cut through the metal surface along worn areas.',
        'Metal grey with bright silver scratch lines.',
        'Hard light catching scratch lines.',
        'Scratches, scuffs, nicks and dulled patches.',
        'Used, battle-worn, tough and honest.',
        'bright scratch lines; scuffs and nicks; dulled wear',
      ),
      avoid: AVOID,
      briefs: [
        "Under hard raking light a diner's stainless steel counter and stools are covered in decades of bright scratches and cutlery gouges. No readable text or logo.",
        "A trumpet of polished steel lies on a workbench covered in fine bright scratches and one deep gouge where it was dropped. No readable text or logo.",
        "In a city plaza a steel horse sculpture is covered in bright scratches from skateboards and keys, scuffed bare at the hooves. No readable text or logo.",
      ],
    },
    'SP09-038': {
      dna: w(
        'Dusty surface: a soft layer of settled dust dulling the target, thicker on top surfaces.',
        'a fine layer of settled dust dulls the target, thicker on upward faces, with finger swipes.',
        'Grey-beige dust over the object color.',
        'Shafts of light revealing floating motes.',
        'Fine dust layer, finger swipes and motes.',
        'Forgotten, quiet, still and timeless.',
        'settled dust layer; thicker on top faces; finger swipes',
      ),
      avoid: AVOID,
      briefs: [
        "On a cushion in a locked vault a crown sits under fine settled grey powder, one clean finger swipe across its brow. No readable text or logo.",
        "In an abandoned music room a golden harp dulls under settled grey, thicker along the top of the frame, a shaft of window light crossing it. No readable text or logo.",
        "In a forgotten corridor a suit of armor wears a thick grey layer on its shoulders and helmet, a moth-shaped clean patch on the visor. No readable text or logo.",
      ],
    },
    'SP09-040': {
      dna: w(
        'Oil stains: dark glossy oil and grease stains soaking into the target.',
        'dark glossy oil and grease stains soak into the surfaces with iridescent edges.',
        'Black-brown stains with iridescent sheen.',
        'Hard light for glossy spots.',
        'Oil stains, grease smears and iridescent film.',
        'Mechanical, gritty, working and dirty.',
        'oil stains; grease smears; iridescent film',
      ),
      avoid: AVOID,
      briefs: [
        "In a garage a white wedding dress on a mannequin soaks up dark glossy stains across the satin skirt, grease handprints on the bodice. No readable text or logo.",
        "Hanging on a hook in a motorcycle workshop, a mechanic's canvas apron is soaked dark with glossy grease stains. No readable text or logo.",
        "In a museum a white marble dancer has dark glossy stains spreading up from a pool on its plinth. No readable text or logo.",
      ],
    },
    'SP09-041': {
      dna: w(
        'Sandpaper abrasion: surfaces covered in grit or scuffed by sanding into a matte scratched finish.',
        'the surface is gritty or sanded matte with swirl marks and exposed layers.',
        'Muted, dusty tones with pale sanding marks.',
        'Soft light showing matte grit.',
        'Abrasive grit, sanding swirls and dust.',
        'Rough, workshop-worn and matte.',
        'abrasive grit; sanding swirls; matte scuffed finish',
      ),
      avoid: AVOID,
      briefs: [
        "Half sanded in a workshop, a wooden rocking chair shows orbital swirl marks across the seat and matte scratches on one arm. No readable text or logo.",
        "Resting on a velvet cushion, an enormous egg covered in coarse abrasive grit glitters with angular grains across its shell. No readable text or logo.",
        "On a workbench an unfinished guitar body is sanded to a matte scratched finish, fine dust drifting from the block. No readable text or logo.",
      ],
    },
    'SP09-064': {
      dna: w(
        'Cracked mud: dried mud coating the target and splitting into polygon cracks.',
        'dried mud coats the target and splits into polygon cracks, curling at edges.',
        'Clay brown and ochre with dark crack lines.',
        'Harsh sun with crisp shadows in cracks.',
        'Dried mud plates, polygon cracks and curls.',
        'Parched, rough, earthy and harsh.',
        'dried mud polygon cracks; curled edges; parched clay',
      ),
      avoid: AVOID,
      briefs: [
        "Parked in a desert village, a rally jeep is caked in dried grey clay split into polygon cracks across its doors. No readable text or logo.",
        "In a dry riverbed a rhinoceros statue is caked in cracked grey clay plates, green shoots growing from the gaps. No readable text or logo.",
        "Left in a drained lake bed, an ornate throne is coated in dried clay curling into polygons, a crow perched on the armrest. No readable text or logo.",
      ],
    },
    'SP09-065': {
      dna: w(
        'Tar coating: thick black tar coating the target, glossy, dripping and sticky.',
        'thick black tar coats the target with glossy drips and stringy strands.',
        'Glossy black with brown translucency at thin edges.',
        'Hard light for glossy highlights.',
        'Viscous tar, drips, strands and bubbles.',
        'Heavy, sticky, ominous and industrial.',
        'glossy black tar; drips and strands; viscous coating',
      ),
      avoid: AVOID,
      briefs: [
        "On a white plinth a swan statue drips thick glossy black coating, long sticky strands stretching from its wings. No readable text or logo.",
        "On a rocky shoreline a seabird statue is smothered in glossy black pitch, drips hanging from its beak and sand stuck to its sides. No readable text or logo.",
        "Half dipped in black pitch, a gold crown rests on a stone slab, the drip line gleaming against the bare gold above. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Salt Crust',
      domain: 'salt crust efflorescence',
      tags: ['salt', 'crust', 'weathering'],
      dna: w(
        'Salt crust: white crystalline salt deposits crusting over the target, as if dried by sea spray.',
        'white salt crystals crust on edges and recesses with efflorescence blooms.',
        'White salt over darker base colors.',
        'Bright coastal light sparkling on crystals.',
        'Crystalline salt crust, blooms and granules.',
        'Coastal, dry, bleached and ancient.',
        'white salt crystal crust; efflorescence blooms',
      ),
      avoid: AVOID,
      briefs: [
        "On a windswept pier a ship's brass bell and anchor chain are crusted with white crystals from years of sea spray. No readable text or logo.",
        "Left on a seaside windowsill, a guitar grows white crystal crust along its strings and sound hole. No readable text or logo.",
        "Stranded on a dry lake bed, a wooden rowboat is crusted with thick white crystals, hexagonal flats stretching to the horizon. No readable text or logo.",
      ],
    },
    {
      name: 'Sun-Bleached Fade',
      domain: 'sun-bleached fading',
      tags: ['sun-bleached', 'fade', 'weathering'],
      dna: w(
        'Sun-bleached fade: colors washed out by years of sun, pale on exposed faces and richer in shadowed folds.',
        'exposed faces fade to pale washed tones while protected folds keep deeper color.',
        'Pastel-faded versions of the original colors.',
        'Harsh overhead sun.',
        'Chalky faded pigment and dried surfaces.',
        'Nostalgic, dry, quiet and timeworn.',
        'sun-faded exposed faces; deeper colors in folds; chalky pigment',
      ),
      avoid: AVOID,
      briefs: [
        "In the desert an old roadside diner and parked convertible have faded to pale pastels on their sunny sides, rich color surviving in the shade. No readable text or logo.",
        "On a beach a red velvet throne has faded to pale pink on its sunlit back, crimson still hiding in the folds. No readable text or logo.",
        "On a seaside terrace striped deck chairs have washed from deep blue to pale grey on the seats while the folds keep their color. No readable text or logo.",
      ],
    },
    {
      name: 'Soot Staining',
      domain: 'soot and smoke staining',
      tags: ['soot', 'smoke-stain', 'weathering'],
      dna: w(
        'Soot staining: black smoke deposits blackening the target from below, as after a fire, without burning it away.',
        'black soot stains rise from lower edges and gather in crevices, surfaces intact.',
        'Black soot gradients over original colors.',
        'Dim light with smoky warmth.',
        'Soft soot deposits, smudges and fingerprints.',
        'Ominous, grim, aftermath and heavy.',
        'soot gradients from below; smudges; intact surfaces',
      ),
      avoid: AVOID,
      briefs: [
        "In a burned chapel a white marble angel is blackened from the feet upward, the stone itself unharmed. No readable text or logo.",
        "After a kitchen fire a tall white wedding cake is blackened on its lower tiers while the top tier stays pristine. No readable text or logo.",
        "On a kitchen shelf a white porcelain teapot is blackened from below after a stove fire, smoky fingerprints on the handle. No readable text or logo.",
      ],
    },
    {
      name: 'Woodworm Rot',
      domain: 'woodworm and dry rot',
      tags: ['woodworm', 'rot', 'weathering'],
      dna: w(
        'Woodworm rot: wood riddled with tiny boreholes and soft dry-rot cracking.',
        'the wooden target is riddled with small boreholes and cubic dry-rot cracks.',
        'Grey-brown wood with dark holes and pale dust.',
        'Soft side light showing holes.',
        'Boreholes, frass dust and cubic rot cracks.',
        'Decrepit, old, fragile and eerie.',
        'woodworm boreholes; cubic dry rot; frass dust',
      ),
      avoid: AVOID,
      briefs: [
        "In a chapel niche a carved wooden saint is riddled with tiny boreholes, fine powdery frass collecting at its feet. No readable text or logo.",
        "An antique wooden chess set has crumbled into boreholes, one rook split open by dry rot and pawns reduced to powder. No readable text or logo.",
        "On a farmhouse porch a rocking chair riddled with boreholes still rocks in the wind, frass sifting from its spindles. No readable text or logo.",
      ],
    },
    {
      name: 'Acid Etching',
      domain: 'acid-etched surfaces',
      tags: ['acid', 'etching', 'weathering'],
      dna: w(
        'Acid etching: surfaces eaten by acid into pitted, frosted and bubbled zones with bright residue edges.',
        'acid pits, frosted zones and bubbled corrosion eat into the surfaces in splash patterns.',
        'Frosted pale zones and yellow-green residue.',
        'Cold light on pitted surfaces.',
        'Pitted, frosted and bubbled corrosion.',
        'Toxic, alarming, chemical and harsh.',
        'acid pits; frosted zones; splash patterns; residue edges',
      ),
      avoid: AVOID,
      briefs: [
        "A silver tea tray has been eaten in splash-shaped zones, pitted frosted metal with bright residue rims beside untouched mirror silver. No readable text or logo.",
        "Backlit on a black cloth, a glass crown shows frosted pitted patches across its points with clear glass between. No readable text or logo.",
        "Running down the flanks of a bronze gazelle, pitted frosted streaks end in bright green residue edges. No readable text or logo.",
      ],
    },
    {
      name: 'Lichen Crust',
      domain: 'lichen crust growth',
      tags: ['lichen', 'crust', 'weathering'],
      dna: w(
        'Lichen crust: flat crusty lichen rosettes in orange, yellow and grey growing over the target.',
        'flat lichen rosettes and crusts spread over exposed surfaces in circular patches.',
        'Orange, chartreuse and grey-green lichen.',
        'Soft overcast light.',
        'Crusty lichen rosettes and powdery patches.',
        'Ancient, slow, quiet and alive.',
        'lichen rosettes; circular crust patches; orange and chartreuse',
      ),
      avoid: AVOID,
      briefs: [
        "In an overgrown garden a stone sundial is dotted with flat rosettes in orange, chartreuse and grey, thickest on the gnomon. No readable text or logo.",
        "Left on a garden wall for decades, an old rotary telephone is crusted with orange and grey rosettes, the dial half covered. No readable text or logo.",
        "In a ruined tower a bronze bell wears yellow and grey rosettes, its frayed rope still hanging from the clapper. No readable text or logo.",
      ],
    },
    {
      name: 'Ash Fall Coating',
      domain: 'volcanic ash coating',
      tags: ['ash', 'coating', 'weathering'],
      dna: w(
        'Ash fall coating: fine grey volcanic ash settled over the target, softening edges.',
        'fine grey ash settles on every upward face, softening edges and filling crevices.',
        'Monochrome grey ash over faint original colors.',
        'Diffuse hazy light.',
        'Fine powdery ash drifts and settled layers.',
        'Silent, eerie, suspended and bleak.',
        'grey ash drifts; softened edges; monochrome',
      ),
      avoid: AVOID,
      briefs: [
        "A banquet table fully set with plates, goblets and candelabras lies under fine grey volcanic dust, every edge softened. No readable text or logo.",
        "An empty playground is frozen under a coat of fine grey volcanic dust, swings and slide softened as more drifts down. No readable text or logo.",
        "In an empty town square a golden harp stands under a coat of volcanic grey, its strings dusted and the air still hazy. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
