import type { Spec } from '../tools/apply';
import { MATERIAL_AVOID as AVOID, material } from './_material';

const spec: Spec = {
  pack: 'pack_09',
  category: '1. Natural Materials',
  updates: {
    'SP09-001': {
      dna: material(
        'Raw oak wood: unfinished quarter-sawn oak with open grain, ray flecks and dry, matte fibers.',
        'the target becomes carved or built from raw oak, with grain following its form and tool marks at edges.',
        'Pale honey to mid brown with darker grain lines.',
        'Warm side light raking across the open grain.',
        'Open-pore oak grain, medullary ray flecks, splits and adze marks.',
        'Solid, honest, warm and old.',
        'raw open oak grain; ray flecks; tool marks; matte dry fibers',
      ),
      avoid: AVOID,
      briefs: [
        "A life-size warhorse carved from raw oak stands in a misty meadow, grain flowing along its muscles and adze marks still rough in the mane. No readable text or logo.",
        "Deep in a forest clearing a man stands in full armor built from raw oak planks and wooden pegs, a woodpecker testing his shoulder. No readable text or logo.",
        "Rising through an empty stone tower, a raw oak spiral staircase shows open grain and ray flecks climbing every dry, matte step. No readable text or logo.",
      ],
    },
    'SP09-002': {
      dna: material(
        'Polished mahogany: deep red-brown hardwood with a mirror-like French polish and flowing figure.',
        'the target is made of polished mahogany with a deep lacquered finish and figure that follows its curves.',
        'Deep red-brown to near-black with amber highlights.',
        'Warm lamp light producing glossy reflections.',
        'French-polished mahogany with ribbon figure, deep gloss and inlay lines.',
        'Rich, formal, warm and antique.',
        'polished mahogany gloss; ribbon figure; amber highlights; deep red-brown',
      ),
      avoid: AVOID,
      briefs: [
        "A full-size dragon skeleton of mirror-polished mahogany with brass joints reflects every candle in a long museum hall. No readable text or logo.",
        "Tucked in a library corner, a suit of armor made of French-polished mahogany shows flowing flame figure across its breastplate. No readable text or logo.",
        "A slender racing shell of polished mahogany glides across a black lake at dawn, the deep red-brown grain glowing through a mirror finish. No readable text or logo.",
      ],
    },
    'SP09-003': {
      dna: material(
        'Birch bark: papery white bark with dark horizontal lenticels, curling peels and chalky texture.',
        'the target is wrapped or built from birch bark sheets with peeling curls and dark lenticel dashes.',
        'Chalk white, cream and charcoal marks with peach inner bark.',
        'Soft cool daylight.',
        'Papery peeling bark layers with black lenticels and curls.',
        'Northern, quiet, delicate and wild.',
        'papery white bark; dark lenticels; curling peels; peach inner layer',
      ),
      avoid: AVOID,
      briefs: [
        "In a snowy forest a tall hooded figure wears a cloak of peeling birch bark layers, blending into the white trunks around it. No readable text or logo.",
        "Resting on green moss, a fiddle made from curled sheets of birch bark shows dark lenticels running across its papery body. No readable text or logo.",
        "Clad entirely in overlapping birch bark, a tiny wayside chapel glows at dusk with one candle, curled peels lifting at every corner. No readable text or logo.",
      ],
    },
    'SP09-004': {
      dna: material(
        'Polished granite: speckled crystalline stone polished to a hard reflective surface.',
        'the target is carved from granite and polished, with mineral speckles visible across its surfaces.',
        'Grey, black and pink speckle or black granite with mica sparkle.',
        'Crisp light producing sharp reflections.',
        'Polished granite with feldspar, quartz and mica grains.',
        'Hard, permanent, cold and monumental.',
        'polished speckled granite; mica sparkle; hard reflections; crystalline grain',
      ),
      avoid: AVOID,
      briefs: [
        "A colossal black granite bull stands in a rain-soaked plaza, the whole city sliding in reflections across its polished flanks. No readable text or logo.",
        "Carved from polished pink granite, a grand piano sits in an empty concert hall with speckled feldspar crystals under a mirror-hard finish. No readable text or logo.",
        "On a windswept sea cliff a throne cut from polished grey granite beads with rain, black mica speckles catching the storm light. No readable text or logo.",
      ],
    },
    'SP09-005': {
      dna: material(
        'Rough sandstone: layered sedimentary stone with granular surface and warm bands.',
        'the target is carved from rough sandstone with visible bedding layers and eroded edges.',
        'Ochre, rust, cream and red banding.',
        'Low warm sun that emphasizes grain.',
        'Granular sandstone with bedding layers and wind erosion.',
        'Ancient, eroded, warm and desert-like.',
        'rough granular sandstone; bedding bands; wind erosion; warm ochre',
      ),
      avoid: AVOID,
      briefs: [
        "Half-eroded by desert wind, a giant kneeling warrior of rough sandstone shows bands of red and ochre across his shoulders. No readable text or logo.",
        "A steam locomotive carved from rough red sandstone waits on rusted desert rails, grit trickling from its wind-rounded boiler. No readable text or logo.",
        "In a quiet cloister courtyard a tall harp carved from layered sandstone sheds a thin ring of crumbled grit at its base. No readable text or logo.",
      ],
    },
    'SP09-006': {
      dna: material(
        'Carrara marble: white marble with soft grey veining, polished or finely carved.',
        'the target is carved from white Carrara marble with grey veins following its form.',
        'Warm white with soft grey veining.',
        'Soft diffused light showing subsurface glow.',
        'Fine crystalline marble with translucent edges and polished or chiselled finish.',
        'Classical, serene, pure and timeless.',
        'white Carrara marble; grey veining; translucent glow; carved detail',
      ),
      avoid: AVOID,
      briefs: [
        "A veiled mourner carved from Carrara marble kneels in a ruined chapel, the veil so thin at its edges that light passes through the stone. No readable text or logo.",
        "Coiling down a grand staircase, a serpent carved in white stone shows soft grey veins flowing along its polished scales. No readable text or logo.",
        "Leaning against an old wall in a narrow street, a life-size bicycle carved from Carrara marble has thin grey veins running across its spokes. No readable text or logo.",
      ],
    },
    'SP09-007': {
      dna: material(
        'Split slate: dark layered stone that cleaves into thin sheets with sharp, stepped edges.',
        'the target is built from split slate sheets or carved slate showing layered cleavage.',
        'Blue-grey, charcoal and green-grey with rust stains.',
        'Overcast light showing the stepped layers.',
        'Cleaved slate sheets with sharp edges and rough riven faces.',
        'Austere, cold, rugged and old.',
        'split slate sheets; stepped cleavage; riven faces; blue-grey',
      ),
      avoid: AVOID,
      briefs: [
        "Perched on a quarry ledge, a winged beast built from overlapping split slate sheets shows sharp stepped edges along every plate. No readable text or logo.",
        "Beside a quarry in the rain, a sentinel wears armor of riven slate scales, each dark plate cleaved into thin wet layers. No readable text or logo.",
        "A rowing boat shingled in split slate tiles drifts on a still grey loch, rainwater pooling in the stepped hull. No readable text or logo.",
      ],
    },
    'SP09-008': {
      dna: material(
        'Mossy rock: weathered stone covered in cushions of green moss and lichen.',
        'the target turns into weathered stone covered with thick moss cushions and lichen patches.',
        'Vivid moss green, lichen yellow and grey stone.',
        'Soft, damp forest light.',
        'Velvety moss cushions, crusty lichen and damp stone.',
        'Ancient, quiet, overgrown and living.',
        'moss cushions; lichen patches; damp weathered stone; forest green',
      ),
      avoid: AVOID,
      briefs: [
        "A sleeping giant made of mossy boulders lies across a misty glen, sheep grazing the cushions of moss on its shoulders. No readable text or logo.",
        "On a forest floor a stone helmet has been swallowed by bright green moss, orange lichen crusting the rim like rust. No readable text or logo.",
        "Deep in a rainforest an old stone telephone kiosk wears a roof of thick moss, lichen patterns creeping across its panels. No readable text or logo.",
      ],
    },
    'SP09-009': {
      dna: material(
        'River stones: smooth, rounded pebbles fitted together like a mosaic.',
        'the target is assembled from smooth rounded river stones fitted tightly together.',
        'Grey, ochre, slate and white pebbles.',
        'Soft light, with some stones wet and glossy.',
        'Water-polished stones with rounded edges.',
        'Calm, patient, natural and grounded.',
        'fitted rounded pebbles; water-polished; wet gloss; mosaic packing',
      ),
      avoid: AVOID,
      briefs: [
        "Standing in a shallow clear stream, a life-size bear built from smooth river stones catches the current around its fitted pebble legs. No readable text or logo.",
        "On a windy shingle beach a long cloak of fitted river pebbles drapes over a standing figure, wet and gleaming at the hem. No readable text or logo.",
        "In a sunlit whitewashed room an armchair assembled from smooth river stones holds a sleeping cat that clearly finds it comfortable. No readable text or logo.",
      ],
    },
    'SP09-010': {
      dna: material(
        'Obsidian: black volcanic glass with conchoidal fractures, razor edges and glassy sheen.',
        'the target is knapped from obsidian, with shell-like fracture scars and sharp edges.',
        'Glossy black with smoky brown and rainbow sheen.',
        'Hard rim light showing the glassy edges.',
        'Volcanic glass with conchoidal ripples and translucent edges.',
        'Dangerous, sleek, dark and primordial.',
        'black volcanic glass; conchoidal fractures; razor edges; rainbow sheen',
      ),
      avoid: AVOID,
      briefs: [
        "On a deep red velvet cushion rests a crown knapped from black obsidian, conchoidal ripples across every point and razor edges glowing brown. No readable text or logo.",
        "Striding across a lava field, a warrior wears armor of knapped obsidian plates that flash with rainbow sheen. No readable text or logo.",
        "A wolf knapped from black volcanic glass stands on a snowy ridge at sunset, razor edges along its fur catching pink light. No readable text or logo.",
      ],
    },
    'SP09-011': {
      dna: material(
        'Wolf fur: dense grey-brown guard hairs over a soft underfur, with directional flow.',
        'the target is covered in dense wolf-like fur with directional flow following its form.',
        'Grey, silver, tan and black tipped fur.',
        'Backlight halo on the fur edges.',
        'Guard hairs and soft underfur with natural direction.',
        'Wild, warm, primal and alert.',
        'dense grey fur; guard hairs; directional flow; backlit halo',
      ),
      avoid: AVOID,
      briefs: [
        "In a snowbound log cabin a tall grandfather clock is covered in dense grey-brown wolf fur, guard hairs flowing down its case. No readable text or logo.",
        "A frozen battlefield wind combs through a warlord's cape and helmet crest of thick silver wolf fur. No readable text or logo.",
        "Beside a crackling hearth sits an armchair upholstered in wolf fur, the underfur showing where the guard hairs part on the arms. No readable text or logo.",
      ],
    },
    'SP09-012': {
      dna: material(
        'Snake scales: overlapping keeled or smooth scales with iridescent sheen and patterned bands.',
        'the target is covered in overlapping snake scales with patterned bands following its form.',
        'Olive, emerald, black and gold banding with iridescence.',
        'Raking light that shows each scale edge.',
        'Overlapping keeled scales with glossy iridescent sheen.',
        'Sleek, dangerous, hypnotic and exotic.',
        'overlapping snake scales; patterned bands; iridescent sheen; scale edges',
      ),
      avoid: AVOID,
      briefs: [
        "A cello covered in overlapping emerald-and-gold keeled scales lies on black cloth, a banded pattern spiraling down its neck. No readable text or logo.",
        "In a desert ruin a woman's gown of iridescent snake scales shifts from copper to green as she turns. No readable text or logo.",
        "A horse-drawn carriage covered in iridescent snake scales waits on a rainy cobbled street, shifting violet under the gas lamps. No readable text or logo.",
      ],
    },
    'SP09-013': {
      dna: material(
        'Bird feathers: overlapping contour feathers with barbs, shafts and iridescent sheen.',
        'the target is covered in overlapping feathers laid in rows like plumage.',
        'Brown, cream, black and iridescent blue-green.',
        'Soft backlight showing feather barbs.',
        'Overlapping feathers with visible barbs and shafts.',
        'Light, graceful, alive and soft.',
        'overlapping feathers; barbs and shafts; plumage rows; iridescent sheen',
      ),
      avoid: AVOID,
      briefs: [
        "On a dusk battlefield rests a helmet covered in overlapping glossy raven feathers, blue-violet iridescence rippling along every barb. No readable text or logo.",
        "In an old manor a sweeping banister is covered in soft barred owl feathers, overlapping downward like a folded wing. No readable text or logo.",
        "A small rowboat covered in white swan feathers floats on a still pond at dawn, feathers lifting slightly in the breeze. No readable text or logo.",
      ],
    },
    'SP09-014': {
      dna: material(
        'Coral reef: branching and brain corals growing over the target in bright calcareous forms.',
        'the target is overgrown or formed from living coral structures, branching and brain coral.',
        'Coral pink, orange, purple, cream and turquoise.',
        'Underwater-like caustic light.',
        'Calcareous coral with polyps, ridges and porous texture.',
        'Vibrant, alive, oceanic and intricate.',
        'branching and brain coral; polyps; porous calcareous texture; caustic light',
      ),
      avoid: AVOID,
      briefs: [
        "On the sea bed a sunken diving bell is overgrown with pink and orange branching coral while parrotfish graze its rim. No readable text or logo.",
        "A chandelier grown from branching coral hangs in a dark sunken ballroom, fish swimming between its arms. No readable text or logo.",
        "In a sea cave a throne formed from brain and staghorn coral hosts a moray eel peering out from the armrest. No readable text or logo.",
      ],
    },
    'SP09-015': {
      dna: material(
        'Honeycomb wax: hexagonal beeswax comb with golden translucent cells and honey drips.',
        'the target is built from hexagonal honeycomb with some cells filled and dripping.',
        'Amber, gold and pale yellow wax.',
        'Backlight making wax cells glow.',
        'Hexagonal wax cells, honey drips and waxy sheen.',
        'Warm, sweet, organic and industrious.',
        'hexagonal wax cells; honey drips; glowing amber; waxy sheen',
      ),
      avoid: AVOID,
      briefs: [
        "On a stone altar a crown of golden beeswax honeycomb glows in a sunbeam as honey drips slowly down its points. No readable text or logo.",
        "A beekeeper's smoker and veiled hat left on a garden bench have been grown over by golden honeycomb, cells glowing in the late sun. No readable text or logo.",
        "Hanging in a dark barn, a lantern of honeycomb wax makes every hexagonal cell glow amber around its candle. No readable text or logo.",
      ],
    },
    'SP09-016': {
      dna: material(
        'Glacier ice: dense blue ice with trapped bubbles, fracture planes and melt-smoothed surfaces.',
        'the target is made of glacier ice with blue depths and trapped bubbles.',
        'Deep cyan-blue with white frosted edges.',
        'Backlight showing blue translucency.',
        'Dense ice with bubbles, fractures and melt ridges.',
        'Cold, ancient, pure and silent.',
        'deep blue glacier ice; trapped bubbles; fracture planes; translucent depth',
      ),
      avoid: AVOID,
      briefs: [
        "A life-size bison carved from dense blue glacier ice stands on a frozen plain, trapped bubbles drifting inside its hump. No readable text or logo.",
        "In a dark stone hall a piano carved from glacier ice glows in a single spotlight, meltwater dripping steadily from its keys. No readable text or logo.",
        "A great door of blue glacier ice stands in a snowstorm, fracture planes deep inside and melt-smoothed edges around its handle. No readable text or logo.",
      ],
    },
    'SP09-044': {
      dna: material(
        'Sea sponge: porous organic sponge with irregular holes and soft tan fibers.',
        'the target is made of porous natural sea sponge with irregular holes.',
        'Tan, sand, ochre and pale yellow.',
        'Soft side light showing pores.',
        'Porous spongy fibers with irregular holes.',
        'Soft, strange, organic and absorbent.',
        'porous sea sponge; irregular holes; soft tan fibers',
      ),
      avoid: AVOID,
      briefs: [
        "On a wet beach at dusk sits an old diving helmet grown from porous tan sea sponge, tiny crabs sheltering in its holes. No readable text or logo.",
        "In a white-walled room an armchair made entirely of sea sponge casts dotted shadows through its irregular pores. No readable text or logo.",
        "On a museum plinth a bust of a queen made of sea sponge wears a crown of porous tan fibers. No readable text or logo.",
      ],
    },
    'SP09-055': {
      dna: material(
        'Crystal and gemstone: faceted translucent crystal with internal refractions and color zones.',
        'the target is carved from gem crystal with facets and inner refractions.',
        'Amethyst purple, emerald, sapphire or clear quartz.',
        'Point lights producing refraction and fire.',
        'Faceted crystal with inclusions and internal reflections.',
        'Precious, magical, cold and brilliant.',
        'faceted gem crystal; internal refraction; inclusions; spectral fire',
      ),
      avoid: AVOID,
      briefs: [
        "In a candlelit cave a beast's skull of faceted amethyst throws violet refractions across the rock walls. No readable text or logo.",
        "A hummingbird carved from faceted blue sapphire perches on a real flower stem, color zoning deepening through its wings. No readable text or logo.",
        "In a sunlit nursery a rocking horse of clear quartz spills rainbow refractions across the floorboards. No readable text or logo.",
      ],
    },
    'SP09-063': {
      dna: material(
        'Cobweb: dense dusty spider silk draped in layers over the target.',
        'the target is draped in thick layers of dusty cobweb strands and sheets.',
        'Grey-white strands with dust and dark gaps.',
        'Backlight catching the strands.',
        'Silk strands, sagging sheets and dust.',
        'Abandoned, eerie, still and forgotten.',
        'dusty cobweb layers; backlit strands; sagging sheets',
      ),
      avoid: AVOID,
      briefs: [
        "In an abandoned workshop an old printing press is draped in thick dusty cobwebs, silk strands sagging between rollers and levers. No readable text or logo.",
        "A grand piano in a derelict ballroom is shrouded under layers of cobweb that hang from the lid like curtains. No readable text or logo.",
        "On a long banquet table in a derelict manor, a tiered wedding cake lies shrouded in grey cobwebs, spiders still at work. No readable text or logo.",
      ],
    },
    'SP09-066': {
      dna: material(
        'Beach sand: fine packed sand sculpted into the target, with grain texture and crumbling edges.',
        'the target is sculpted from packed beach sand with crumbling edges and fine grain.',
        'Warm beige, golden and wet darker sand.',
        'Low sun raking the grains.',
        'Packed fine sand grains with crumbling edges and shell fragments.',
        'Fleeting, playful, warm and fragile.',
        'packed sand sculpture; crumbling edges; fine grains; wet and dry tones',
      ),
      avoid: AVOID,
      briefs: [
        "A huge sleeping serpent sculpted from packed beach sand stretches along the shore, its tail already crumbling into the tide. No readable text or logo.",
        "Crawling toward the waves, a sea turtle sculpted from packed beach sand slowly loses its flippers to the wind. No readable text or logo.",
        "At sunset a cathedral facade carved from packed sand glows orange on the beach, one tower slowly slumping. No readable text or logo.",
      ],
    },
    'SP09-068': {
      dna: material(
        'Cooled lava rock: porous black-red basalt scoria with vesicles and ropy flow texture.',
        'the target is made of cooled lava rock with vesicles and ropy flow texture.',
        'Charcoal black, rust red and ash grey.',
        'Hard side light revealing pores.',
        'Vesicular basalt, scoria and ropy pahoehoe flow.',
        'Harsh, volcanic, primal and rough.',
        'porous lava rock; vesicles; ropy flow; charcoal and rust',
      ),
      avoid: AVOID,
      briefs: [
        "On a black sand beach a golem of porous black-red lava rock kneels while steam rises from the cracks in its shoulders. No readable text or logo.",
        "Inside a volcanic cave a throne of ropy cooled lava rock glows faintly orange from a fissure beneath it. No readable text or logo.",
        "A teapot of porous black lava rock steams on a rough wooden table, a ropy flow ridge running along its spout. No readable text or logo.",
      ],
    },
    'SP09-079': {
      dna: material(
        'Mother of pearl: iridescent nacre with shimmering color shifts and layered sheen.',
        'the target is inlaid or carved from mother-of-pearl nacre with color-shifting sheen.',
        'Pearl white with pink, blue and green iridescence.',
        'Soft light producing shifting iridescence.',
        'Layered nacre with shimmer and inlay seams.',
        'Precious, delicate, oceanic and luminous.',
        'iridescent nacre; color-shifting sheen; inlay seams',
      ),
      avoid: AVOID,
      briefs: [
        "An old music box sheathed in mother of pearl lies open on a dark pebble shore at twilight, its nacre shifting pink to green to silver. No readable text or logo.",
        "A mandolin inlaid entirely with mother of pearl rests on black silk, shimmering plates shifting color along its curves. No readable text or logo.",
        "In a moonlit palace courtyard a ceremonial carriage covered in nacre inlay shimmers blue and pink while the horses wait in shadow. No readable text or logo.",
      ],
    },
    'SP09-080': {
      dna: material(
        'Dragon scale: large armored overlapping scales with ridges, metallic sheen and battle scratches.',
        'the target is covered in large overlapping dragon scales with ridges and metallic sheen.',
        'Bronze, crimson, emerald or obsidian with metallic highlights.',
        'Hard raking light showing ridges.',
        'Thick overlapping scales with ridges, scratches and metallic sheen.',
        'Powerful, armored, mythic and fierce.',
        'large overlapping dragon scales; ridges; metallic sheen; battle scratches',
      ),
      avoid: AVOID,
      briefs: [
        "Leaning against a burnt tree, a round shield covered in huge crimson scales shows deep battle scratches across its metallic sheen. No readable text or logo.",
        "A woman in a coat of bronze armored scales stands in a storm, lightning flashing along every ridged plate. No readable text or logo.",
        "Set in a fortress wall, a heavy door covered in bronze-green scales bears old claw scratches beside a burning torch. No readable text or logo.",
      ],
    },
  },
};

export default spec;
