import type { Create, Dna, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';

// Diagram and technical drawing: each preset is one drafting convention. The prompt subject is the
// thing documented; labels stay as unreadable marks. Checked against existing blueprint, patent,
// cutaway, exploded, section, isometric, wiring and knotwork presets so these add new conventions.
const AVOID = [...STYLE_AVOID, 'readable labels or numbers', 'fake data claims'];

const words = (t: string) => t.split(/\s+/).filter(Boolean).length;
const pad = (t: string, min: number, tail: string) =>
  words(t) < min ? `${t.replace(/\.$/, '')}, ${tail}` : t;

function diagram(
  aesthetic: string,
  convention: string,
  color: string,
  surface: string,
  layout: string,
  mood: string,
  key: string,
): Dna {
  return {
    aesthetic,
    subject_treatment: `Treat the prompt's subject as the thing being documented, keeping it recognizable; all labels, numbers and notes are unreadable marks: ${convention}`,
    color_and_tone: pad(color, 9, 'following the conventions of this drawing type.'),
    lighting_and_shadow:
      'No scene lighting; depth and emphasis come only from line weight, hatching and flat tone.',
    texture_and_material: pad(surface, 9, 'with the drafting tools visible in the line quality.'),
    camera_and_composition: pad(layout, 9, 'laid out as a real sheet of this drawing type.'),
    atmosphere_and_mood: pad(mood, 8, 'from careful, purposeful drafting.'),
    rendering_and_quality:
      'Precise technical drafting with consistent line weights and believable conventions.',
    key_features: key,
  };
}

const spec: Spec = {
  pack: 'pack_11',
  category: '7. Diagram And Technical Drawing',
  updates: {
    'SP11-033': {
      name: 'Faded Workshop Blueprint',
      dna: diagram(
        'Faded workshop blueprint: a real, used blueprint sheet photographed on a workbench, sun-faded, creased and marked up.',
        'drawn as white lines on a faded, creased blueprint that has been used for years: pencil marks, pin holes, stains and torn corners.',
        'Sun-faded cyan and grey-blue with white lines and brown stains.',
        'Diazo paper, creases, coffee rings, pencil smudges and tape.',
        'Sheet pinned or weighted on a workbench with tools at the edges.',
        'Worn, practical, nostalgic and hands-on.',
        'faded diazo sheet; creases; stains; pencil markups; workbench',
      ),
      avoid: AVOID,
      briefs: [
        "Pinned to a workshop bench, a sun-faded and creased sheet shows plans for a clockwork dragon in white lines on blue, oily thumbprints at the corners. No readable text or logo.",
        "Spread across a tavern table, an old folded plan of a siege tower is held flat by a dagger, torn fold lines and wax drips across the blue. No readable text or logo.",
        "Taped to a salt-stained wall, the plan of a lighthouse lantern mechanism curls at the corners, rust bleeding from the pins. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Hachure Relief Map',
      domain: 'hachured terrain map',
      tags: ['hachure', 'map', 'diagram'],
      dna: diagram(
        'Hachure relief map: terrain drawn with thousands of short strokes that follow the slopes, dense on steep ground.',
        'mapped as terrain seen from above, with slope strokes, rivers, roads and settlements; figures become landforms.',
        'Brown or black ink on cream paper with blue water.',
        'Engraved ink strokes on laid paper.',
        'Map sheet with neatline border and compass rose.',
        'Old, careful, geographic and patient.',
        'hachure strokes; slopes; rivers; compass rose',
      ),
      avoid: AVOID,
      briefs: [
        "A volcanic island shaped like a sleeping beast is drawn in thousands of short brown slope strokes, dense on its ridged spine. No readable text or logo.",
        "A narrow mountain pass guarded by a fortress on a spur is drawn in dense black strokes down the cliffs, a thin river in the gorge. No readable text or logo.",
        "A round crater lake is ringed by tree symbols and a ruined abbey on its shore, soft slope strokes on the gentle banks. No readable text or logo.",
      ],
    },
    {
      name: 'Naval Lines Plan',
      domain: 'ship hull lines drawing',
      tags: ['naval', 'lines-plan', 'diagram'],
      dna: diagram(
        "Naval lines plan: a ship's hull drawn as profile, half-breadth and body plan, with flowing waterlines and station curves.",
        'drawn as a hull lines plan: sheer profile, waterlines, buttock lines and station curves in three linked views.',
        'Fine black or sepia ink on off-white paper.',
        'Ink on drafting linen with ship curves.',
        'Three linked views aligned on one long sheet.',
        'Elegant, precise, maritime and classic.',
        'profile; half-breadth; body plan; waterlines',
      ),
      avoid: AVOID,
      briefs: [
        "A serpent-prowed longship is drawn in sheer profile, half-breadth waterlines and a neat body plan of flowing sections. No readable text or logo.",
        "A tall-sterned galleon with a carved gallery flows through half-breadth waterlines and stacked body sections in fine ink. No readable text or logo.",
        "A whale-shaped submersible with fin rudders and a riveted conning hump is drawn in profile, half-breadth and body plan. No readable text or logo.",
      ],
    },
    {
      name: 'Isometric Piping Drawing',
      domain: 'piping isometric',
      tags: ['piping', 'isometric', 'diagram'],
      dna: diagram(
        'Piping isometric: single-line pipe runs drawn on a 30-degree grid with valves, flanges and elbows as symbols.',
        'rebuilt as pipe runs on an isometric grid: single lines, valve and flange symbols, flow arrows and elbows.',
        'Black line work on white, with one accent color.',
        'Clean CAD-like lines on paper.',
        'Isometric sheet with a flow arrow and title block left blank.',
        'Industrial, systematic, precise and clean.',
        'isometric grid; single-line pipes; valve symbols',
      ),
      avoid: AVOID,
      briefs: [
        "An alchemist's laboratory still is drawn as single-line pipes on a 30-degree grid running between a cauldron, condenser and flasks. No readable text or logo.",
        "Inside a faint outline of a great beast, fuel bladders, pumps and check valves are piped in single lines toward its jaws. No readable text or logo.",
        "A fortress water system runs in single lines from a deep well through a cistern, pumps and valves to a courtyard fountain. No readable text or logo.",
      ],
    },
    {
      name: 'Star-Fort Fortification Plan',
      domain: 'bastion fort plan',
      tags: ['star-fort', 'fortification', 'diagram'],
      dna: diagram(
        'Star-fort plan: angular bastion fortifications seen from above, with moats, ravelins and lines of fire.',
        'laid out as a bastioned fortification plan: star-shaped walls, moats, outworks and dashed lines of fire.',
        'Ink with watercolor washes: moat blue, earth ochre, walls red.',
        'Engraved line and wash on old paper.',
        'Top-down plan centered on the sheet.',
        'Military, geometric, severe and elegant.',
        'bastions; ravelins; moat; lines of fire',
      ),
      avoid: AVOID,
      briefs: [
        "A city of angular bastions and a blue moat surrounds a sleeping beast coiled at its center, ravelins pointing outward. No readable text or logo.",
        "Angular bastions and a blue moat sit under siege as zigzag approach trenches and artillery batteries creep closer. No readable text or logo.",
        "A fortress on a floating rock island has bastions following the jagged cliff edge, chains anchoring it to the ground far below. No readable text or logo.",
      ],
    },
    {
      name: 'Clockwork Escapement Drawing',
      domain: 'horological drawing',
      tags: ['clockwork', 'escapement', 'diagram'],
      dna: diagram(
        'Horological drawing: precise views of escapements, wheels and springs with fine ink and brass wash.',
        'drawn as a mechanism: escapement, wheel train, springs and pivots in front and side views.',
        'Black ink with brass and steel-blue washes.',
        'Fine pen on smooth paper.',
        'Front and side views with detail circles.',
        'Precise, intricate, patient and elegant.',
        'escapement; wheel train; detail circles',
      ),
      avoid: AVOID,
      briefs: [
        "Inside a mechanical owl, the ticking heart is drawn in front and side views, escapement, wheel train and mainspring rendered in fine ink with blue wash. No readable text or logo.",
        "The arm mechanism of a warrior automaton is drawn with cam stack, levers, springs and a sword-grip linkage in steel-blue wash. No readable text or logo.",
        "A tower clock escapement with a long pendulum, anchor pallets and great wheel is drawn in steel-blue and brass washes. No readable text or logo.",
      ],
    },
    {
      name: 'Renaissance Invention Notebook',
      domain: 'inventor notebook page',
      tags: ['renaissance', 'notebook', 'diagram'],
      dna: diagram(
        'Renaissance invention notebook: sepia pen sketches of machines and studies scattered across a page with dense mirror-script marks.',
        'sketched as inventions and studies on a notebook page: pen and wash views, details, and unreadable script marks.',
        'Sepia and red chalk on aged paper.',
        'Iron-gall ink, red chalk and foxing.',
        'Several sketches arranged loosely on one page.',
        'Curious, brilliant, restless and old.',
        'sepia sketches; script marks; red chalk; aged page',
      ),
      avoid: AVOID,
      briefs: [
        "A sepia notebook page holds sketches of a flying machine with bat wings, a gear study and a hand gripping a lever. No readable text or logo.",
        "Anatomy and motion studies for a walking automaton fill a sepia page, a leg drawn at four stages of a stride. No readable text or logo.",
        "War machine designs crowd a sepia page, a giant siege crossbow, a scythed chariot and a covered battering ram. No readable text or logo.",
      ],
    },
    {
      name: 'Axonometric Architectural Drawing',
      domain: 'axonometric drawing',
      tags: ['axonometric', 'architecture', 'diagram'],
      dna: diagram(
        'Axonometric drawing: a building shown in a parallel projection from above with crisp lines and flat color.',
        'drawn in parallel axonometric projection, often exploded or cut open, with flat color fills.',
        'Flat pastel fills with black lines.',
        'Clean lines on white.',
        'Axonometric view floating on white.',
        'Clear, modern, analytic and elegant.',
        'axonometric projection; flat fills; cut-away',
      ),
      avoid: AVOID,
      briefs: [
        "A witch's tower is shown from above with its roof lifted away, floors of bedrooms, a library and an attic full of bats. No readable text or logo.",
        "A mountain monastery is drawn in parallel projection with the cloister roof removed to show scriptorium, refectory and cells. No readable text or logo.",
        "A crossroads tavern explodes upward in parallel projection, roof lifted, upper rooms, a busy common room and a cellar of barrels. No readable text or logo.",
      ],
    },
    {
      name: 'Urban Figure-Ground Plan',
      domain: 'figure-ground map',
      tags: ['figure-ground', 'urbanism', 'diagram'],
      dna: diagram(
        'Figure-ground plan: buildings as solid black shapes, streets and open space as white.',
        'reduced to solid black buildings and white open space, so the subject shape emerges from streets and squares.',
        'Pure black and white.',
        'Flat print.',
        'Top-down plan.',
        'Stark, graphic, analytic and bold.',
        'black buildings; white streets',
      ),
      avoid: AVOID,
      briefs: [
        "In a medieval city plan the white streets and squares together form the silhouette of a leaping stag between solid black blocks. No readable text or logo.",
        "A walled medieval city appears as solid black building blocks around a white cathedral square and white winding lanes. No readable text or logo.",
        "In a canal city plan the white waterways and squares wind like a serpent between dense black buildings. No readable text or logo.",
      ],
    },
    {
      name: 'Stage Lighting Plot',
      domain: 'theatre lighting plan',
      tags: ['lighting-plot', 'theatre', 'diagram'],
      dna: diagram(
        'Lighting plot: a theatre stage plan with instrument symbols on pipes and beam zones.',
        'shown as a stage plan: set outline, lighting instrument symbols on battens and colored beam zones.',
        'Black lines with colored beam zones.',
        'CAD-like plan.',
        'Stage plan top-down.',
        'Theatrical, technical, organized and precise.',
        'instrument symbols; battens; beam zones',
      ),
      avoid: AVOID,
      briefs: [
        "A theatre plan for a storm at sea shows the outline of a ship deck, instrument symbols on battens and green beam zones sweeping over it. No readable text or logo.",
        "A theatre plan for a ghost scene outlines a graveyard set, instruments on three battens and one pale blue beam at center. No readable text or logo.",
        "A theatre plan for a haunted ballroom places a chandelier outline at center, instruments on battens and side booms. No readable text or logo.",
      ],
    },
    {
      name: 'Origami Crease Pattern',
      domain: 'origami crease diagram',
      tags: ['origami', 'crease-pattern', 'diagram'],
      dna: diagram(
        'Crease pattern: a square sheet covered in mountain and valley fold lines that fold into the subject.',
        'shown as a crease pattern: geometric mountain and valley lines on a square, the subject hinted by flaps.',
        'Red and blue lines on white.',
        'Paper.',
        'Square sheet.',
        'Geometric, clever, precise and calm.',
        'mountain and valley lines; square',
      ),
      avoid: AVOID,
      briefs: [
        "A square sheet is covered in red mountain and blue valley lines forming a dense geometric web that will fold into a scorpion. No readable text or logo.",
        "Pinned to a workshop wall, radial red and blue fold lines on a square sheet promise a bird with flapping wings. No readable text or logo.",
        "Clean radial red and blue lines on a square sheet map a crane with an extra-long tail, the folded bird resting beside it. No readable text or logo.",
      ],
    },
    {
      name: 'Knot Tying Diagram',
      domain: 'knot instruction diagram',
      tags: ['knot', 'rope', 'diagram'],
      dna: diagram(
        'Knot tying diagram: a clear step-by-step sequence of rope drawings with arrows showing each pass, tuck and pull.',
        'shown as a numbered-feeling sequence of panels (without readable numbers) where rope wraps, crosses and tightens around or through the subject, with direction arrows.',
        'Two contrasting rope colors on white or pale cream.',
        'Clean vector rope with simple twist texture and soft flat shading.',
        'Four to six step panels in a grid, each with arrows.',
        'Practical, calm, clear and handy.',
        'step panels; rope twist; direction arrows; tightening sequence',
      ),
      avoid: AVOID,
      briefs: [
        "Six step panels show how a sailor lashes a bone harpoon head to its shaft, red and cream rope with arrows at each pass. No readable text or logo.",
        "Four panels show how to tie a rope bridge plank to its hand lines over a chasm, arrows and cross-sections at every turn. No readable text or logo.",
        "Step panels show a fishing net mesh knot in blue and white rope, arrows looping around a netting needle. No readable text or logo.",
      ],
    },
    {
      name: 'Dance Step Diagram',
      domain: 'dance footprint diagram',
      tags: ['dance', 'footprints', 'diagram'],
      dna: diagram(
        'Dance step diagram: old instruction-book footprints on a floor plan, with curved arrows and dotted paths showing the steps.',
        'translated into a floor diagram of footprints, turning arrows, dotted paths and partner positions, the subject implied by the pattern and small silhouette markers.',
        'Black footprints and red arrows on cream paper.',
        'Printed ink on old book paper with slight dot gain.',
        'Top-down floor view with the path spiraling or zigzagging.',
        'Playful, rhythmic, nostalgic and clear.',
        'footprints; turning arrows; dotted paths; partner markers',
      ),
      avoid: AVOID,
      briefs: [
        "Pairs of bony footprints spiral across a ballroom floor plan for a skeleton waltz, red curved arrows marking every turn. No readable text or logo.",
        "A medieval court dance in two facing lines steps forward and back in footprints, arrows marking bows and turns. No readable text or logo.",
        "Footprints loop in a ring around a bonfire symbol for a witches' circle dance, dotted paths crossing through the middle. No readable text or logo.",
      ],
    },
    {
      name: 'Weaving Draft Grid',
      domain: 'weaving draft',
      tags: ['weaving', 'draft', 'diagram'],
      dna: diagram(
        "Weaving draft: a weaver's grid with threading, tie-up and treadling blocks around a drawdown that reveals the woven pattern.",
        'encoded as a weaving draft whose drawdown pattern of filled squares forms the subject, with threading, tie-up and treadling grids around it.',
        'Black filled squares on graph paper, sometimes one accent color.',
        'Pencil or ink squares on printed graph paper.',
        'Classic four-block draft layout with the drawdown largest.',
        'Methodical, patient, crafty and precise.',
        'threading; tie-up; treadling; drawdown pattern',
      ),
      avoid: AVOID,
      briefs: [
        "On graph paper a large drawdown of black filled squares forms a leaping deer, threading grid and tie-up blocks framing it. No readable text or logo.",
        "A drawdown reveals a repeating fortress-and-tree border in deep red squares, neat grids around it and a wooden shuttle resting nearby. No readable text or logo.",
        "A drawdown forms a field of small skulls and diamonds in black squares on aged graph paper, eraser smudges at the edges. No readable text or logo.",
      ],
    },
    {
      name: 'Survey Plat Map',
      domain: 'land survey plat',
      tags: ['survey', 'plat', 'diagram'],
      dna: diagram(
        'Survey plat: a legal land map of lots, boundaries, bearings and monuments drawn with ruler-straight lines.',
        'mapped as surveyed parcels: straight boundary lines, lot blocks, corner monuments, easements and a north arrow, with the subject shaping the land.',
        'Black ink with faint colored lot washes.',
        'Ink on linen with a slightly yellowed surface.',
        'Plan view with a north arrow and blank title block.',
        'Dry, official, precise and quietly eerie.',
        'lot lines; corner monuments; north arrow; easements',
      ),
      avoid: AVOID,
      briefs: [
        "A haunted village is divided into lots, one parcel shaded black around an abandoned chapel, corner monuments at every angle. No readable text or logo.",
        "An old graveyard is laid out in neat ruler-straight lots along a crooked path, one lot outlined twice in red. No readable text or logo.",
        "A manor estate is surveyed with straight boundaries around keep, orchards, mill and village lots beside a meandering river. No readable text or logo.",
      ],
    },
    {
      name: 'Gear Train Drawing',
      domain: 'gear train engineering drawing',
      tags: ['gears', 'mechanism', 'diagram'],
      dna: diagram(
        'Gear train drawing: interlocking gears drawn as pitch circles and tooth outlines, with shafts and rotation arrows.',
        'drawn as a gear train: pitch circles, tooth profiles, shafts, bearings and curved rotation arrows, the subject shaped by the mechanism.',
        'Black ink with light grey pitch circles.',
        'Pen and compass lines on smooth drafting paper.',
        'Front view of meshing gears with a side section.',
        'Mechanical, precise, clever and calm.',
        'pitch circles; tooth profiles; shafts; rotation arrows',
      ),
      avoid: AVOID,
      briefs: [
        "The wing mechanism of a clockwork bat is drawn as meshing gears in pitch circles, a crank and linkage reaching the wings. No readable text or logo.",
        "A water mill's mechanism is sectioned from the side, waterwheel shaft, pit wheel, crown gear and millstone spindle. No readable text or logo.",
        "An astronomical clock's nested planetary gears drive a moon-phase disk and a plain star dial in pitch circles. No readable text or logo.",
      ],
    },
    {
      name: 'Ship Rigging Diagram',
      domain: 'sail and rigging plan',
      tags: ['rigging', 'ship', 'diagram'],
      dna: diagram(
        'Rigging diagram: a sailing ship profile with every mast, yard, stay and line drawn as a fine web.',
        'drawn in profile with masts, yards, sails outlined, and standing and running rigging as fine straight lines.',
        'Black ink with pale sail washes.',
        'Fine pen on cream paper.',
        'Side profile filling the sheet.',
        'Maritime, intricate, elegant and patient.',
        'masts; yards; stays; running rigging',
      ),
      avoid: AVOID,
      briefs: [
        "A ghost galleon in profile shows tattered sails in pale washes, every stay, shroud and halyard drawn as a fine line. No readable text or logo.",
        "A three-masted war galleon with a spritsail is drawn in fine pen lines and pale sail washes, every line of rigging accounted for. No readable text or logo.",
        "A smuggler's sloop with one tall mast, a long bowsprit and furled sails shows every halyard and sheet in fine ink. No readable text or logo.",
      ],
    },
    {
      name: 'Architectural Elevation Drawing',
      domain: 'building elevation',
      tags: ['elevation', 'architecture', 'diagram'],
      dna: diagram(
        'Architectural elevation: a flat frontal facade drawing with precise lines, cast-shadow washes and entourage figures.',
        'drawn as a flat frontal elevation of a facade or front: windows, ornament and material patterns, with soft wash shadows and tiny scale figures.',
        'Ink with grey and sepia washes.',
        'Ink and wash on heavy paper.',
        'Frontal elevation with ground line.',
        'Grand, orderly, classical and calm.',
        'frontal facade; wash shadows; scale figures',
      ),
      avoid: AVOID,
      briefs: [
        "A gothic cathedral's west front stands flat and frontal, rose window, pointed portals and gargoyles in grey and sepia wash. No readable text or logo.",
        "A wizard's tower with spiral balconies stands in flat ink and wash, a cat sitting on the ground line for scale. No readable text or logo.",
        "A fortified city gate with twin towers, a raised portcullis and hanging banners is drawn flat with sepia wash shadows. No readable text or logo.",
      ],
    },
    {
      name: 'Garden Contour Plan',
      domain: 'landscape design plan',
      tags: ['garden', 'contour', 'diagram'],
      dna: diagram(
        'Landscape plan: garden design seen from above with contour lines, tree canopies as circles, paths and planting beds.',
        'laid out as a landscape plan: contour lines, canopy circles with shadows, hedges, paths and water.',
        'Soft greens and earth tones over black ink.',
        'Colored pencil and ink on paper.',
        'Top-down plan with north arrow.',
        'Calm, verdant, ordered and inviting.',
        'contours; canopy circles; hedges; paths',
      ),
      avoid: AVOID,
      briefs: [
        "Seen from above, a hedge maze wraps around a sunken garden with a black obelisk at its center, contour lines and canopy circles. No readable text or logo.",
        "Four herb beds surround a central well inside a monastery cloister seen from above, canopy circles marking the fruit trees along its walks. No readable text or logo.",
        "A sacred grove climbs a hill around a stone circle, contour lines rising to the summit and oak canopies as shaded circles. No readable text or logo.",
      ],
    },
    {
      name: 'Masonry Stereotomy Drawing',
      domain: 'stone cutting geometry',
      tags: ['stereotomy', 'masonry', 'diagram'],
      dna: diagram(
        'Stereotomy: the geometry of cutting stones for arches and vaults, drawn with projections, voussoirs and construction lines.',
        'drawn as stone-cutting geometry: projected views, voussoir blocks and fine construction lines.',
        'Black ink with sandstone washes.',
        'Fine lines on old paper.',
        'Projected plan and elevation.',
        'Geometric, ancient, precise and austere.',
        'voussoirs; projections; construction lines',
      ),
      avoid: AVOID,
      briefs: [
        "A skewed pointed arch over a crypt entrance is projected block by block, every voussoir traced with fine construction lines. No readable text or logo.",
        "A ribbed gothic vault unfolds each rib stone into flat templates beside its projection in fine lines. No readable text or logo.",
        "A spiral staircase inside a round tower is projected step by step in plan and elevation, fine construction lines everywhere. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
