import type { Create, Spec } from '../tools/apply';
import { ANIME_AVOID as AVOID, anime } from './_anime';

// Core anime: each preset is one genre look (line, cel, palette, light). Scene names stay as
// identities but the DNA describes how any prompt is drawn; scenes live in the three card briefs.
const spec: Spec = {
  pack: 'pack_13',
  category: '1. Core Anime',
  updates: {
    'SP13-001': {
      dna: anime(
        'Heroic dawn cel anime: bold adventure-series key art with strong silhouettes, two-step cel shading and warm sunrise light.',
        'confident thick outer contours, thinner inner lines, two-step cel shadows, heroic low-angle poses with windblown hair and cloth.',
        'Warm gold, peach and orange against cool blue shadow.',
        'Low sunrise backlight with a bright rim on hair and armor.',
        'Flat cel fills with softly painted sky gradients.',
        'Low heroic angle with the sky behind.',
        'Brave, hopeful, determined and bright.',
        'thick contours; two-step cel; sunrise rim light; heroic pose',
      ),
      avoid: AVOID,
      briefs: [
        "A swordswoman stands on a cliff above a ruined kingdom at sunrise, and the first ray catches her raised blade and lights every broken tower below. No readable text or logo.",
        "A hero strikes a triumphant pose at dawn on her homecoming, not noticing that a rooster has claimed the top of her helmet. No readable text or logo.",
        "At dawn a young hero reaches the legendary sword in the stone and finds it already pulled, an old farmer using it to dig potatoes nearby. No readable text or logo.",
      ],
    },
    'SP13-002': {
      dna: anime(
        'Neon city vigil anime: rain-soaked cyber-city night frames with sharp lines, wet reflections and lonely figures.',
        'crisp thin lines, hard cel shadows, faces lit by colored signs, rain streaks drawn as straight white lines.',
        'Magenta, cyan and violet neon on deep navy black.',
        'Neon signs as key light with wet reflections.',
        'Flat cel with glossy painted reflections and rain streaks.',
        'Street-level wide shots and tight lonely close-ups.',
        'Lonely, cool, watchful and melancholic.',
        'neon key light; wet reflections; rain lines; lonely figure',
      ),
      avoid: AVOID,
      briefs: [
        "A hooded courier with a glowing prosthetic arm waits in a rain-soaked alley, the rain hissing into steam wherever it touches her arm. No readable text or logo.",
        "An android sits alone on a rooftop in the rain, holding her umbrella over a potted sunflower instead of herself. No readable text or logo.",
        "A lonely vending-machine robot keeps vigil in a flooded neon alley, dimming and brightening its face to guide lost pedestrians home. No readable text or logo.",
      ],
    },
    'SP13-004': {
      dna: anime(
        'Mecha hangar anime: giant robots drawn with precise mechanical line work, panel lines and industrial lighting.',
        'hard-edged mechanical line work with panel lines, bolts and vents, humans tiny beside machines, sparks and steam as cel effects.',
        'Gunmetal, hazard orange, off-white and teal accents.',
        'Industrial floodlights, sparks and visor glow.',
        'Crisp cel metal with sharp highlight blocks.',
        'Low angle up at the machine with tiny figures for scale.',
        'Tense, powerful, mechanical and awe-struck.',
        'panel lines; floodlights; sparks; scale contrast',
      ),
      avoid: AVOID,
      briefs: [
        "Its visor igniting teal, a knight-shaped giant robot boots up in a cathedral-sized hangar as the steam from its shoulders gathers into clouds under the roof. No readable text or logo.",
        "Panicked technicians scramble as a giant robot wakes up early and politely tries to help sweep the hangar floor. No readable text or logo.",
        "In a dark abandoned hangar a mecha that has not moved in fifty years slowly turns its head toward the scavenger holding a flashlight. No readable text or logo.",
      ],
    },
    'SP13-006': {
      dna: anime(
        'Spirit shrine twilight anime: quiet supernatural frames with soft glowing spirits, lanterns and painted dusk skies.',
        'soft thin lines, gentle cel shading, spirits drawn translucent with glowing edges, richly painted backgrounds.',
        'Dusky violet, lantern orange and spirit teal.',
        'Twilight sky with lantern and spirit glow.',
        'Painted backgrounds with soft cel characters and glowing particles.',
        'Calm wide frames with small figures.',
        'Mysterious, gentle, sacred and wistful.',
        'translucent spirits; lanterns; painted dusk; soft glow',
      ),
      avoid: AVOID,
      briefs: [
        "A woman in a winter coat leaves a rice offering at a mossy roadside shrine as a tall translucent deer spirit bows to eat from her hand. No readable text or logo.",
        "A tiny shrine spirit scolds a passing office worker because the offerings have been nothing but convenience-store pudding for a week. No readable text or logo.",
        "At twilight a line of glowing lanterns floats up the stairs of a mountain shrine where no one has prayed in a hundred years. No readable text or logo.",
      ],
    },
    'SP13-007': {
      dna: anime(
        'Sports climax anime: explosive match-point frames with speed lines, sweat, impact frames and extreme perspective.',
        'extreme foreshortening, speed lines, impact flashes, sweat drops and gritted faces at the peak of motion.',
        'Bright team colors with white impact flashes.',
        'Arena lights and hard rim light.',
        'Cel with speed-line overlays and motion smears.',
        'Extreme angles close to the action.',
        'Intense, triumphant, sweaty and electric.',
        'speed lines; foreshortening; impact flash; sweat',
      ),
      avoid: AVOID,
      briefs: [
        "A goalkeeper dives at match point in extreme perspective, the ball filling half the frame as sweat and torn grass explode around her. No readable text or logo.",
        "The rope snaps at the climax of a championship tug-of-war between two villages, both teams flying backwards in bursting speed lines. No readable text or logo.",
        "At the instant two sumo wrestlers collide, the shockwave blows every cushion off the front row of the arena. No readable text or logo.",
      ],
    },
    'SP13-008': {
      dna: anime(
        'Gothic vampire anime: elegant dark frames with long thin lines, pale faces, crimson accents and moonlit shadows.',
        'long elegant lines, sharp eyes and chins, flowing capes and lace, large solid black shadow shapes.',
        'Black, crimson, bone white and moon blue.',
        'Moonlight and candlelight with deep shadows.',
        'Cel with fine lace and velvet detail.',
        'Tall vertical frames and dramatic angles.',
        'Elegant, dangerous, romantic and cold.',
        'long lines; pale faces; crimson accents; moonlight',
      ),
      avoid: AVOID,
      briefs: [
        "A pale aristocrat in a crimson-lined cape stands on a manor balcony under a huge moon as a thousand bats pour out of the chimney behind him. No readable text or logo.",
        "An ancient vampire lady tries to apply lipstick with no reflection while her butler holds up a painted portrait of her as a guide. No readable text or logo.",
        "In a silent moonlit ballroom every guest is a vampire standing perfectly still, waiting for the one living musician to stop playing. No readable text or logo.",
      ],
    },
    'SP13-009': {
      dna: anime(
        'Magical girl prism anime: transformation-sequence sparkle, ribbons, stars and rainbow prism light.',
        'big shining eyes, flowing ribbons, star and heart sparkles, spinning transformation poses with bursts of light.',
        'Pastel pinks, lilac, gold and rainbow prisms.',
        'Radiant backlight and prism flares.',
        'Glossy cel with sparkle overlays.',
        'Centered spinning pose on a starry background.',
        'Magical, joyful, radiant and brave.',
        'ribbons; prism flares; sparkles; transformation pose',
      ),
      avoid: AVOID,
      briefs: [
        "Spinning on a rooftop in a thunderstorm, a grown-up witch in her thirties transforms as ribbons of light wrap into armored skirts, and the prism flare from her wand splits the storm clouds into rainbow shards. No readable text or logo.",
        "Two retired magical heroines in sparkling transformed costumes argue over a parking space outside the supermarket, rainbow sparkles flying with every gesture. No readable text or logo.",
        "On a quiet windowsill at dawn, a small crystal brooch catches the sunrise and throws a tiny rainbow across a sleeping cat. No readable text or logo.",
      ],
    },
    'SP13-010': {
      dna: anime(
        'Isekai caravan anime: bright fantasy-adventure frames of travelers, carts, odd beasts and lush landscapes.',
        'friendly character designs, clean lines, soft cel shading, rich painted fantasy backgrounds.',
        'Lush greens, sky blue and warm earth.',
        'Sunny daylight through leaves.',
        'Painted backgrounds with clean cel characters.',
        'Wide travel frames.',
        'Adventurous, cozy, curious and bright.',
        'caravan; lush painted backgrounds; clean cel; odd beasts',
      ),
      avoid: AVOID,
      briefs: [
        "A caravan of adventurers crosses a forest of glowing mushrooms while the giant lizard pulling their wagon snacks on the luminous caps. No readable text or logo.",
        "An office worker reborn as a fantasy innkeeper serves stew to a scaled merchant who will not stop complaining about the royal taxes. No readable text or logo.",
        "At night the caravan camps inside the hollow skull of a colossal beast, their campfire glowing out through its eye sockets. No readable text or logo.",
      ],
    },
    'SP13-011': {
      dna: anime(
        'Dungeon glow anime: torchlit labyrinth frames with glowing magic circles, dark stone and stylized monsters.',
        'clean lines, strong cel shadow, magic drawn as glowing shapes, monsters stylized with readable silhouettes.',
        'Deep blue stone with torch orange and magic teal.',
        'Torch and magic glow in darkness.',
        'Cel with glowing effect overlays.',
        'Corridor and chamber frames with depth.',
        'Tense, adventurous, eerie and exciting.',
        'torchlight; magic glow; dark stone; stylized monsters',
      ),
      avoid: AVOID,
      briefs: [
        "An adventuring party descends a spiral stair into a glowing labyrinth, and the teal magic circle far below them is slowly opening like an eye. No readable text or logo.",
        "A battered adventuring party kicks open the final boss door and finds a cozy tavern run by a retired lich in an apron. No readable text or logo.",
        "A lone adventurer's torch sputters in a labyrinth whose stone walls quietly rearrange themselves each time she blinks. No readable text or logo.",
      ],
    },
    'SP13-012': {
      dna: anime(
        'Retro mecha VHS anime: 80s-90s cel look with VHS grain, color bleed and hand-painted highlight streaks.',
        'thick line art, cel shading with hand-painted highlight streaks and gradient shadows, then VHS tracking noise over everything.',
        'Faded saturated colors with red and cyan bleed.',
        'Dramatic backlight and explosions.',
        'VHS grain, scanlines, cel and paint streaks.',
        'Dynamic mecha shots and tight cockpit close-ups.',
        'Nostalgic, dramatic, gritty and bold.',
        'VHS grain; painted highlight streaks; retro cel',
      ),
      avoid: AVOID,
      briefs: [
        "Drawing a glowing beam sword over a burning space colony, an olive-green mecha with hand-painted highlight streaks sliding down its armor turns toward a squadron of rivals as VHS grain softens the flames. No readable text or logo.",
        "In a quiet hangar during a lull in the battle, a mechanic in grease-stained overalls repaints a dent on a mech’s shoulder while a radio crackles beside her. No readable text or logo.",
        "In orbit above a blue planet, a single drifting mech helmet catches the sunlight, its cracked visor softened by grainy analog color. No readable text or logo.",
      ],
    },
    'SP13-014': {
      dna: anime(
        'Ronin duel anime: period samurai frames with long stillness, ink-brush accents and sudden white slash arcs.',
        'sharp restrained lines, faces half in shadow, slashes drawn as white arcs, ink-brush accents in the backgrounds.',
        'Muted indigo, grey and blood red.',
        'Moonlight or lantern light.',
        'Cel with ink-wash backgrounds.',
        'Wide standoff frames and extreme close-ups of eyes and hilts.',
        'Tense, still, lethal and poetic.',
        'standoff; white slash arcs; ink wash; half-shadow faces',
      ),
      avoid: AVOID,
      briefs: [
        "Hands on their hilts in a rainy night alley, two swordsmen face each other, the swinging lantern between them the only clock. No readable text or logo.",
        "Postponing their fight, two exhausted swordsmen sit side by side on an alley step sharing one skewer of sweet dumplings. No readable text or logo.",
        "A single white slash arc cuts across a dark alley, and only the parted rain shows where the blade has passed. No readable text or logo.",
      ],
    },
    'SP13-016': {
      dna: anime(
        'Battle mage anime: spell-combat frames with storm magic, layered glowing circles and dynamic casting poses.',
        'dynamic casting poses, flowing robes, layered glowing circles and jagged lightning drawn as bright cel shapes.',
        'Storm blue, violet and electric white.',
        'Magic glow lighting faces from below.',
        'Cel with bright effect layers and debris.',
        'Dynamic low and high angles.',
        'Powerful, dramatic, electric and fierce.',
        'lightning cel shapes; layered circles; casting poses',
      ),
      avoid: AVOID,
      briefs: [
        "A mage on a fortress wall calls down lightning onto a siege army, three glowing circles stacked above her staff like a spinning tower. No readable text or logo.",
        "At a drought festival a storm spell summons exactly one tiny raincloud, which follows the mayor everywhere he goes. No readable text or logo.",
        "Alone in a crater of fused glass, a sorceress watches her storm circles slowly fade overhead after the siege. No readable text or logo.",
      ],
    },
    'SP13-017': {
      dna: anime(
        'Ink noir detective anime: black-ink shadows, stark white highlights and a single accent color in hard-boiled mystery frames.',
        'heavy solid black shadows, sharp white highlights, lean angular faces, smoke and rain drawn in ink.',
        'Black and white with one accent color, usually red.',
        'Hard single-source light through blinds or a streetlamp.',
        'Ink fills with light screentone.',
        'Canted angles and deep shadow frames.',
        'Moody, suspicious, weary and cool.',
        'solid black shadows; single accent color; hard light',
      ),
      avoid: AVOID,
      briefs: [
        "A weary detective sits in his office at night while the blinds throw bars of light over a client whose shadow is holding a knife she is not. No readable text or logo.",
        "A hard-boiled detective interrogates a nervous parrot, the only witness to the crime, under a single swinging bulb. No readable text or logo.",
        "In a black-ink city a single red umbrella moves through the crowd while the detective tails it for a third rainy night. No readable text or logo.",
      ],
    },
    'SP13-019': {
      dna: anime(
        'Forest courier anime: gentle hand-drawn frames of young couriers flying or cycling through lush countryside and small towns.',
        'soft thin lines, rounded friendly faces, careful everyday motion, wind in clothes and grass.',
        'Leaf greens, sky blue, warm cream and red accents.',
        'Clear summer daylight with cloud shadows.',
        'Richly painted watercolor-like backgrounds with soft cel characters.',
        'Wide sky-and-land frames.',
        'Gentle, free, hopeful and warm.',
        'wind in grass; painted skies; soft lines; delivery journey',
      ),
      avoid: AVOID,
      briefs: [
        "A courier on a rattling bicycle coasts down a hillside path into a seaside village, a tiny forest spirit in her basket guarding a warm pie. No readable text or logo.",
        "A courier delivers a parcel to a giant sleeping tree, and a hand of branches slowly reaches down to accept it. No readable text or logo.",
        "Caught in a summer storm, a courier shelters under a giant leaf beside a family of moss spirits, all dripping and pretending not to be annoyed. No readable text or logo.",
      ],
    },
    'SP13-020': {
      dna: anime(
        'Final episode anime: the soft, emotional look of a series finale, golden light, tears and wide quiet farewells.',
        'gentle expressive faces, glistening eyes, soft lines, lingering held poses.',
        'Warm gold and rose with soft blue.',
        'Golden hour light and lens bloom.',
        'Soft painted light and particles.',
        'Wide farewells and intimate close-ups.',
        'Tender, bittersweet, grateful and final.',
        'golden hour; tears; farewell framing',
      ),
      avoid: AVOID,
      briefs: [
        "A party of adventurers parts at a crossroads at sunset, and each road they take bursts into a different color of wildflowers. No readable text or logo.",
        "The reformed villain turns up at the heroes' farewell feast carrying a lopsided homemade cake, awkwardly hoping to be invited in. No readable text or logo.",
        "A lone traveler lays her sword on a grave overlooking the sea as a last golden light washes over the ruins they saved. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Sky Pirate Airship Anime',
      domain: 'airship adventure anime',
      tags: ['sky-pirates', 'airship', 'anime'],
      dna: anime(
        'Sky pirate anime: swashbuckling airship adventure with wind, clouds, ropes and bright wood-and-brass ships.',
        'lively poses with ropes and cutlasses, clothes snapping in the wind, detailed ships with patched sails.',
        'Sky blue, cloud white, brass gold and red sails.',
        'Bright sun above clouds.',
        'Cel with painted clouds.',
        'Wide sky shots with ships and falling figures.',
        'Adventurous, free, cheeky and bright.',
        'airships; clouds; ropes; cutlasses',
      ),
      avoid: AVOID,
      briefs: [
        "A pirate captain swings on a rope between two wooden airships above a sea of clouds, her patched red coat snapping as the cannons fire. No readable text or logo.",
        "Sky pirates board a flying merchant ship and discover it is crewed entirely by very organized penguins. No readable text or logo.",
        "A lone lookout sits in the crow's nest of a drifting airship at night while a colossal cloud whale glides beneath the hull. No readable text or logo.",
      ],
    },
    {
      name: 'Cursed Blade Dark Fantasy Anime',
      domain: 'grim sword anime',
      tags: ['dark-fantasy', 'seinen', 'anime'],
      dna: anime(
        'Cursed blade dark fantasy anime: grim seinen frames with heavy hatching, black ink shadows and blood-red accents.',
        'heavy hatching on faces and armor, scarred bodies, massive weapons, grim expressions and ink-black shadows.',
        'Desaturated grey, rust brown and blood red.',
        'Grim overcast or firelight.',
        'Cel with hatching and grit.',
        'Low menacing angles.',
        'Grim, desperate, brutal and defiant.',
        'heavy hatching; massive blades; blood-red accents',
      ),
      avoid: [...AVOID, 'gore'],
      briefs: [
        "A mercenary stands in the rain over a field of fallen demon knights while the cursed blade in his hand whispers in his ear. No readable text or logo.",
        "Refusing to be sheathed, a haunted sword drags its exhausted wielder through a tavern door in search of another fight. No readable text or logo.",
        "A black-armored woman stands at the gate of a plague castle, the cracks in her gauntlet glowing red with each heartbeat. No readable text or logo.",
      ],
    },
    {
      name: 'Monster Tamer Adventure Anime',
      domain: 'creature companion anime',
      tags: ['monster-tamer', 'creatures', 'anime'],
      dna: anime(
        'Monster tamer anime: bright creature-companion adventures with round readable creature designs and energetic kids.',
        'round readable creatures with simple markings, energetic young tamers, clear action effects.',
        'Bright primaries and fresh greens.',
        'Sunny daylight.',
        'Clean cel.',
        'Dynamic mid shots with creature and tamer.',
        'Energetic, friendly, brave and fun.',
        'creature companions; round designs; bright action',
      ),
      avoid: AVOID,
      briefs: [
        "In a sunlit forest clearing, a grown-up tamer in a worn cap sends her moss-covered armadillo rolling like a boulder at a lumbering clay golem while fireflies scatter around them. No readable text or logo.",
        "On a sunny farmhouse porch, a retired tamer naps in a rocking chair while his giant tortoise creature carries a tiny vegetable garden on its shell. No readable text or logo.",
        "At dusk at the end of a quiet pier, a small creature made of paper lanterns waits patiently for its tamer to come home from the sea. No readable text or logo.",
      ],
    },
    {
      name: 'Mythic Beast-Rider Anime',
      domain: 'epic mount anime',
      tags: ['beast-rider', 'epic', 'anime'],
      dna: anime(
        'Beast-rider anime: epic sky and battle frames of riders on dragons, griffins and giant wolves.',
        'sweeping poses, flowing manes and wings, riders in light armor, huge creature scale.',
        'Sky blues, dragon scale colors and gold.',
        'Dramatic sunset or storm light.',
        'Cel with painted skies.',
        'Wide aerial and low heroic angles.',
        'Epic, free, fierce and noble.',
        'riders; wings; epic scale',
      ),
      avoid: AVOID,
      briefs: [
        "A rider on a silver dragon dives through a storm over a burning fleet, lance leveled, lightning reflected in every scale. No readable text or logo.",
        "A griffin rider tries to land gracefully in the town square, but the griffin spots the fish market and bolts. No readable text or logo.",
        "A giant wolf and its rider rest on a snowy peak at dawn, the rider asleep against the wolf's chest as its breath steams in the cold. No readable text or logo.",
      ],
    },
    {
      name: 'Midnight Mountain Racing Anime',
      domain: 'street racing anime',
      tags: ['racing', 'night', 'anime'],
      dna: anime(
        'Midnight mountain racing anime: late-night downhill racing with drifting cars, headlights and speed lines.',
        'precise car line work, drift smoke, speed lines, driver close-ups with focused eyes.',
        'Night blue with headlight white and taillight red.',
        'Headlights and streetlamps.',
        'Cel with speed-line overlays.',
        'Low angles on mountain roads.',
        'Fast, tense, cool and electric.',
        'drift smoke; headlights; speed lines',
      ),
      avoid: [...AVOID, 'real car brand'],
      briefs: [
        "Drifting through a hairpin on a misty mountain road at 2 a.m., a battered old station wagon full of rice sacks cuts its headlights through the fog as a sleek rival sports car struggles to keep up. No readable text or logo.",
        "A retired racer delivering vegetables in a tiny kei truck overtakes a pack of sports cars downhill, carrots bouncing in the back. No readable text or logo.",
        "On a deserted mountain pass at night a single red taillight glows in the fog where no car has been seen for years. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
