import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Dark and medieval fantasy masters: each preset names the painter or illustrator whose hand,
// palette and composition it rebuilds. Cards stage original characters and scenes, never the
// artist's own published images or licensed game and book characters.
const T = ['dark-fantasy-master', 'fantasy-illustrator'];

const spec: Spec = {
  pack: 'pack_17',
  category: '11. Dark Fantasy Masters',
  newCategory: { id: 'dark-fantasy-masters' },
  updates: {},
  creates: [
    cr('Gerald Brom - Gothic Pale Dark Fantasy', 'dark fantasy painting', [...T, 'brom'], {
      look: 'Gerald Brom dark fantasy painting: pale gaunt figures with hollow dark eyes, thorny gothic costume, desaturated umber backgrounds, a single blood-red accent and eerie beautiful menace.',
      subject:
        'paint people as pale gaunt gothic figures with hollow eyes, thorny costume and elegant menace.',
      color: 'Desaturated umber and bone with one blood-red accent.',
      light: 'Soft grey fog light with pale skin glowing.',
      texture: 'Smooth oil painting with soft blended edges.',
      camera: 'Vertical full-figure book-cover framing.',
      mood: 'eerie beautiful menace',
      render: 'Polished dark fantasy oil painting.',
      key: 'Brom pale gaunt figures; thorny gothic; blood-red accent',
      briefs: [
        'In a fog-drowned orchard of dead apple trees, a pale gaunt beekeeper with hollow dark eyes stands in a thorny black veil, one blood-red apple glowing in her gloved hand while the hives hum behind her. No readable text or logo.',
        'Beside a frozen canal, a gaunt boy in a patched velvet coat feeds ravens from a lantern of thorns. His hollow eyes reflect no light at all. No readable text or logo.',
        'Hanging from a leafless tree in the fog, a single crimson ribbon twists slowly in the wind. The bark beneath it is carved with tiny faces. No readable text or logo.',
      ],
    }),
    cr('John Blanche - Gothic Grotesque Sketch-Paint', 'dark fantasy painting', [...T, 'blanche'], {
      look: 'John Blanche grimdark look: scratchy loose gothic sketch-painting, spindly towering figures with elongated limbs, rust-brown and verdigris palettes, punk-baroque ornament and grotesque decay.',
      subject:
        'paint people as spindly elongated gothic figures in scratchy loose sketch-paint with baroque punk ornament.',
      color: 'Rust brown, verdigris and sickly ochre.',
      light: 'Murky gothic light with scratched highlights.',
      texture: 'Scratchy ink lines under loose washes.',
      camera: 'Tall vertical gothic composition.',
      mood: 'grotesque gothic decay',
      render: 'Loose scratchy gothic sketch-painting.',
      key: 'Blanche spindly figures; scratchy sketch-paint; rust and verdigris',
      avoid: ['Warhammer 40,000 insignia and Space Marines'],
      briefs: [
        'Towering over a rusted cathedral gate, a spindly elongated pilgrim with a birdcage for a head carries a crooked banner of stitched receipts, drawn in scratchy ink under rust-brown and verdigris washes. No readable text or logo.',
        'A procession of long-limbed monks drags a bell on wheels through a sewer of candles. Their robes trail into scratchy shadows. No readable text or logo.',
        'A tall crooked lamp post leans over a gothic alley, its bulb a caged glowing skull. Verdigris drips down its iron. No readable text or logo.',
      ],
    }),
    cr(
      'Ian Miller - Obsessive Pen Gothic Architecture',
      'dark fantasy illustration',
      [...T, 'ian-miller'],
      {
        look: 'Ian Miller illustration: obsessive technical-pen gothic architecture, warped towers and machinery, dense cross-hatching, twisted perspective and nightmarish ornamental detail.',
        subject:
          'draw the subject within obsessive warped gothic architecture in dense technical-pen hatching.',
        color: 'Black ink with sepia and muted washes.',
        light: 'Hatched darkness with stark white gaps.',
        texture: 'Dense technical pen cross-hatching.',
        camera: 'Twisted warped perspective.',
        mood: 'obsessive nightmare intricacy',
        render: 'Obsessive technical-pen gothic drawing.',
        key: 'Ian Miller technical pen; warped towers; dense hatching',
        briefs: [
          'Rising out of a swamp in obsessive technical-pen hatching, a warped gothic lighthouse made of stacked pipe organs leans in twisted perspective while tiny figures climb its ornamented stairs. No readable text or logo.',
          'A crooked city of chimneys and cogs curls around a single sleeping moon, every brick cross-hatched. A small ferry crosses the black river below. No readable text or logo.',
          'A tangled iron tree grows windows and doors among its branches. Tiny lanterns hang from every twisted limb. No readable text or logo.',
        ],
      },
    ),
    cr('Alan Lee - Misty Watercolor Legend', 'fantasy illustration', [...T, 'alan-lee'], {
      look: 'Alan Lee fantasy watercolor: soft misty pencil and watercolor landscapes, towering ancient trees and ruins, pale greens and greys and reverent Northern myth atmosphere.',
      subject:
        'paint the subject small within soft misty pencil-and-watercolor landscapes of ancient trees and ruins.',
      color: 'Pale moss green, mist grey and faded gold.',
      light: 'Soft diffuse mist light.',
      texture: 'Pencil lines under soft watercolor washes.',
      camera: 'Tall landscape dwarfing figures.',
      mood: 'reverent ancient stillness',
      render: 'Delicate pencil and watercolor fantasy illustration.',
      key: 'Alan Lee misty watercolor; ancient trees; ruins',
      avoid: ['Middle-earth characters and places'],
      briefs: [
        'Beneath towering ancient beech trees swallowed by mist, a small traveling bookbinder leads a pony laden with manuscripts past a moss-covered ruin, all in soft pencil and pale watercolor washes. No readable text or logo.',
        'A broken stone bridge fades into a misty river valley where herons stand in the shallows. Faint pencil lines show carved faces in the arches. No readable text or logo.',
        'A single standing stone waits on a pale moor at dawn. Mist pools around its base like water. No readable text or logo.',
      ],
    }),
    cr('John Howe - Epic Mountain Fantasy Painting', 'fantasy painting', [...T, 'john-howe'], {
      look: 'John Howe epic fantasy painting: dramatic mountain and fortress landscapes, towering dragons and armored hosts, dynamic diagonal compositions, cool blue-grey atmosphere and historical armor accuracy.',
      subject:
        'paint the subject in dramatic mountain landscapes with historically accurate armor and dynamic diagonals.',
      color: 'Cool blue-grey stone, storm sky and ember orange.',
      light: 'Stormy dramatic light breaking through clouds.',
      texture: 'Confident gouache and watercolor brushwork.',
      camera: 'Dynamic diagonal wide composition.',
      mood: 'epic sweeping grandeur',
      render: 'Epic fantasy gouache painting.',
      key: 'John Howe mountains; historical armor; dynamic diagonals',
      avoid: ['Middle-earth characters and places'],
      briefs: [
        'Along a narrow mountain pass under a breaking storm, a column of historically armored salt merchants drives laden mules past a colossal sleeping dragon coiled around a ruined watchtower, drawn on a dynamic diagonal. No readable text or logo.',
        'A fortress carved into a cliff glows with watch fires as ravens circle a snowstorm. A single rider climbs the switchback road. No readable text or logo.',
        'A dragon skull the size of a barn lies half-buried in snow on a high pass. Travelers shelter inside its jaws. No readable text or logo.',
      ],
    }),
    cr('Paul Bonner - Painterly Goblin Crowd Scenes', 'fantasy painting', [...T, 'paul-bonner'], {
      look: 'Paul Bonner fantasy painting: detailed painterly crowd scenes of goblins, trolls and dwarves in muddy forests and war camps, humorous grubby characters and rich earthy watercolor.',
      subject:
        'paint people and creatures as grubby humorous goblins, trolls and dwarves in crowded earthy scenes.',
      color: 'Rich earthy browns, moss green and rusty red.',
      light: 'Warm campfire and forest light.',
      texture: 'Detailed painterly watercolor and gouache.',
      camera: 'Crowded eye-level scene.',
      mood: 'grubby humorous warmth',
      render: 'Detailed painterly fantasy crowd scene.',
      key: 'Paul Bonner goblin crowds; grubby humor; earthy paint',
      briefs: [
        'In a muddy forest war camp, a crowd of grubby goblins argues over a stolen cookbook while a huge troll cook stirs a cauldron of mystery soup and a tiny goblin tastes it with great suspicion. No readable text or logo.',
        'A dwarf caravan wades through a flooded bog with barrels on their heads. One dwarf floats serenely on his back. No readable text or logo.',
        'A troll sleeps against a mossy boulder while goblins tie his toes together. Birds nest in his beard. No readable text or logo.',
      ],
    }),
    cr('Karl Kopinski - Painterly Grimdark Portrait', 'dark fantasy painting', [...T, 'kopinski'], {
      look: 'Karl Kopinski painterly grimdark look: gritty realistic portraits and battle scenes with loose expressive brushwork, muted earth palettes, heavy armor and weathered faces.',
      subject:
        'paint people as gritty weathered warriors with loose expressive brushwork and heavy armor.',
      color: 'Muted earth, steel grey and dried blood brown.',
      light: 'Overcast battlefield light.',
      texture: 'Loose expressive oil brushwork.',
      camera: 'Close gritty portrait framing.',
      mood: 'grim weathered resolve',
      render: 'Loose painterly grimdark portrait.',
      key: 'Kopinski loose brushwork; weathered faces; heavy armor',
      avoid: ['Warhammer 40,000 insignia'],
      briefs: [
        'In loose expressive brushwork, a weathered siege cook in dented plate armor stares out from a smoking trench, a ladle tucked in his belt and rain streaking the grime on his tired face. No readable text or logo.',
        'An old standard-bearer rests against a broken wall, his torn banner furled. His eyes are still watching the horizon. No readable text or logo.',
        'A helmet rests on a muddy pike above a quiet battlefield at dusk. Crows wait politely on the fence nearby. No readable text or logo.',
      ],
    }),
    cr(
      'Adrian Smith - Hyper-Detailed Grim Warrior',
      'dark fantasy illustration',
      [...T, 'adrian-smith'],
      {
        look: 'Adrian Smith grim illustration: hyper-detailed monochrome and muted color warriors with massive spiked armor, dense texture, dynamic brutal poses and dark heroic scale.',
        subject:
          'draw people as massively armored hyper-detailed grim warriors in dynamic brutal poses.',
        color: 'Near-monochrome grey with muted rust accents.',
        light: 'High-contrast dramatic light.',
        texture: 'Hyper-detailed rendered pencil and paint texture.',
        camera: 'Low heroic angle.',
        mood: 'brutal heroic grimness',
        render: 'Hyper-detailed grim warrior illustration.',
        key: 'Adrian Smith spiked armor; hyper-detail; brutal poses',
        avoid: ['Warhammer insignia'],
        briefs: [
          'From a low heroic angle, a hyper-detailed grim warrior in massive spiked armor built from old cooking pots swings a giant ladle against a charging boar, every rivet and dent rendered in near-monochrome grey. No readable text or logo.',
          'A hulking armored gatekeeper sits on a throne of shields. His spiked gauntlets cradle a tiny sleeping kitten. No readable text or logo.',
          'A single spiked helmet lies on a bed of broken arrows. Rust creeps across every edge. No readable text or logo.',
        ],
      },
    ),
    cr('Wayne Barlowe - Infernal Architecture Vision', 'dark fantasy painting', [...T, 'barlowe'], {
      look: 'Wayne Barlowe infernal painting: vast hellscape architecture of flesh and bone, towering bizarre demon silhouettes, hazy amber atmosphere and naturalist creature invention.',
      subject:
        'paint the subject within vast infernal architecture of flesh and bone under hazy amber skies.',
      color: 'Hazy amber, bone white and deep red.',
      light: 'Dim infernal haze light.',
      texture: 'Smooth naturalist oil painting.',
      camera: 'Vast wide vista dwarfing figures.',
      mood: 'vast infernal awe',
      render: 'Naturalist infernal landscape painting.',
      key: 'Barlowe infernal architecture; bone cities; amber haze',
      briefs: [
        'Across a hazy amber hellscape, a towering cathedral built of vertebrae and stretched skin rises from a lake of ash as a small procession of lantern-carrying clerks crosses a bridge of ribs toward it. No readable text or logo.',
        'A colossal bizarre demon silhouette strides through the haze with a city on its back. Tiny lights glow in its windows. No readable text or logo.',
        'A throne of bone stands alone on an ash plain under a red sky. Its occupant has left a cup of tea. No readable text or logo.',
      ],
    }),
    cr(
      'Zdzislaw Beksinski - Dystopian Surreal Decay',
      'dark fantasy painting',
      [...T, 'beksinski'],
      {
        look: 'Zdzisław Beksiński fantastic realism: dystopian surreal landscapes of decaying organic architecture, skeletal figures, burnt orange and ochre skies and silent apocalyptic dread.',
        subject:
          'paint the subject in silent dystopian landscapes of decaying organic forms and skeletal structures.',
        color: 'Burnt orange, ochre and ashen brown.',
        light: 'Glowing apocalyptic sky light.',
        texture: 'Smooth fine-grained oil on hardboard.',
        camera: 'Centered monumental composition.',
        mood: 'silent apocalyptic dread',
        render: 'Fantastic realism oil painting.',
        key: 'Beksiński decay; skeletal forms; ochre skies',
        briefs: [
          'Under a glowing burnt-orange sky, a colossal cathedral of fused ribs and lace-like decay stands in a silent desert while a tiny figure in a hooded shroud rows a boat across the sand toward its door. No readable text or logo.',
          'A skeletal violinist plays to a crowd of draped figures on a crumbling hill. No sound reaches the ochre clouds. No readable text or logo.',
          'A single decaying armchair sits in an endless desert under a dim sun. Roots grow from its legs. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Keith Parkinson - Luminous Epic Fantasy Painting',
      'fantasy painting',
      [...T, 'parkinson'],
      {
        look: 'Keith Parkinson epic fantasy painting: luminous glowing skies, gleaming armored heroes, sweeping castles and dragons, rich saturated color and classic eighties and nineties fantasy cover polish.',
        subject:
          'paint people as gleaming heroic figures under luminous glowing skies in sweeping fantasy scenes.',
        color: 'Luminous gold, sapphire and emerald.',
        light: 'Glowing radiant sky light.',
        texture: 'Polished luminous oil painting.',
        camera: 'Sweeping heroic composition.',
        mood: 'radiant heroic wonder',
        render: 'Polished epic fantasy cover painting.',
        key: 'Parkinson luminous skies; gleaming heroes; castles',
        avoid: ['EverQuest or licensed game characters'],
        briefs: [
          'Under a luminous golden sky, a gleaming armored ferry captain steers a crystal barge across a mountain lake toward a sweeping castle while a sapphire dragon glides alongside like an escort. No readable text or logo.',
          'A radiant mage stands on a cliff with a staff of light as dawn floods the valley. Her cloak glows emerald. No readable text or logo.',
          'A castle on a floating island shines gold at sunset. Waterfalls fall from its roots into clouds. No readable text or logo.',
        ],
      },
    ),
    cr('Larry Elmore - Classic Adventure RPG Painting', 'fantasy painting', [...T, 'elmore'], {
      look: 'Larry Elmore classic role-playing painting: warm heroic adventurers in natural poses, detailed practical armor, dragons, lush outdoor light and friendly eighties tabletop fantasy.',
      subject:
        'paint people as warm heroic adventurers in natural poses with practical detailed armor.',
      color: 'Warm natural greens, gold and sky blue.',
      light: 'Warm natural daylight.',
      texture: 'Smooth classic oil painting.',
      camera: 'Classic heroic adventure framing.',
      mood: 'warm adventurous optimism',
      render: 'Classic eighties tabletop fantasy painting.',
      key: 'Elmore warm adventurers; practical armor; dragons',
      avoid: ['Dragonlance characters'],
      briefs: [
        'On a sunny hillside, a warm-hearted party of adventurers, a halfling cartographer, a dwarf cook and a lanky ranger, share a picnic while a friendly bronze dragon naps curled around the boulder behind them. No readable text or logo.',
        'A young squire polishes an oversized helmet by a campfire. Her horse steals an apple from the saddlebag. No readable text or logo.',
        'A sword rests against a mossy stone beside a map and a half-eaten pie. Sunlight filters through the trees. No readable text or logo.',
      ],
    }),
    cr('Jeff Easley - Moody Dramatic RPG Cover', 'fantasy painting', [...T, 'easley'], {
      look: 'Jeff Easley role-playing cover painting: moody dramatic lighting, looming dragons and undead, dark blues and fiery accents, heavy atmosphere and bold iconic compositions.',
      subject:
        'paint the subject with moody dramatic light, looming menace and bold iconic composition.',
      color: 'Dark blues, black and fiery orange accents.',
      light: 'Moody backlight and fire glow.',
      texture: 'Rich oil painting.',
      camera: 'Bold iconic low angle.',
      mood: 'moody looming menace',
      render: 'Dramatic eighties RPG cover painting.',
      key: 'Easley moody drama; looming dragons; fire accents',
      avoid: ['Dungeons & Dragons logos'],
      briefs: [
        'From a bold low angle, a looming black dragon unfurls its wings over a lone night-watch baker holding a flaming torch in a snowy village square, fiery orange glow against deep midnight blue. No readable text or logo.',
        'An undead king rises from a flooded crypt as lightning splits the sky. A frog watches from a skull. No readable text or logo.',
        'Deep in a stormy forest, a single tower window glows red against the midnight blue sky. Something huge circles the roof, blotting out the moon. No readable text or logo.',
      ],
    }),
    cr('Clyde Caldwell - Glamorous Gothic RPG Painting', 'fantasy painting', [...T, 'caldwell'], {
      look: 'Clyde Caldwell gothic role-playing painting: glamorous vampires and sorceresses, rich jewel-tone color, candlelit gothic interiors and theatrical sensual menace.',
      subject:
        'paint people as glamorous gothic figures in jewel tones within candlelit interiors.',
      color: 'Jewel ruby, sapphire and gold.',
      light: 'Theatrical candlelight.',
      texture: 'Glossy rich oil painting.',
      camera: 'Theatrical portrait framing.',
      mood: 'theatrical gothic glamour',
      render: 'Glamorous gothic RPG painting.',
      key: 'Caldwell gothic glamour; jewel tones; candlelight',
      avoid: ['Ravenloft characters'],
      briefs: [
        'In a candlelit gothic library, a glamorous vampire archivist in ruby velvet leans on a ladder of ancient books while a sapphire moth lands on her jeweled glove. No readable text or logo.',
        'A sorceress in gold brocade conducts a floating orchestra of candles in a ballroom. Mirrors show nobody. No readable text or logo.',
        'A goblet of wine glows on a black piano in a candlelit hall. A rose lies beside it. No readable text or logo.',
      ],
    }),
    cr(
      'Rodney Matthews - Curving Prog Fantasy Line',
      'fantasy illustration',
      [...T, 'rodney-matthews'],
      {
        look: 'Rodney Matthews fantasy illustration: sweeping curving organic lines, spiky twisted trees, whimsical sinister creatures, bright gouache color and seventies prog-rock fantasy.',
        subject:
          'draw the subject with sweeping curving lines, spiky twisted forms and bright gouache color.',
        color: 'Bright gouache violet, green and orange.',
        light: 'Flat bright gouache light.',
        texture: 'Smooth gouache with crisp line.',
        camera: 'Swirling whimsical composition.',
        mood: 'whimsical sinister wonder',
        render: 'Crisp gouache prog fantasy illustration.',
        key: 'Rodney Matthews curving lines; spiky trees; gouache',
        briefs: [
          'Along a swirling curving road through spiky twisted violet trees, a whimsical caravan of beetle-drawn carts carries sleepy gnomes toward a spiral castle under a bright orange sky. No readable text or logo.',
          'A spiky airship with curling sails glides over a green lake. Tiny creatures wave from its rigging. No readable text or logo.',
          'A crooked spiral tree grows one glowing orange fruit at the top of a violet hill. A wary spiky lizard guards it with its tail curled around the trunk. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Angus McBride - Historical Warrior Illustration',
      'historical fantasy illustration',
      [...T, 'mcbride'],
      {
        look: 'Angus McBride historical illustration: vivid painted scenes of ancient and medieval warriors with accurate costume, bright gouache, lively crowd action and dusty battlefields.',
        subject: 'paint people as historically costumed warriors in lively gouache action scenes.',
        color: 'Bright gouache reds, blues and dusty ochre.',
        light: 'Bright natural daylight.',
        texture: 'Crisp gouache with fine detail.',
        camera: 'Lively crowd action composition.',
        mood: 'vivid historical energy',
        render: 'Vivid historical gouache illustration.',
        key: 'McBride historical warriors; accurate costume; gouache',
        briefs: [
          'In bright gouache, a lively crowd of historically costumed Celtic villagers races a herd of runaway pigs through a dusty market while warriors on the palisade laugh and bet on the winner. No readable text or logo.',
          'A Byzantine cook argues with a Norse mercenary over a spilled pot of stew. Soldiers crowd around to watch. No readable text or logo.',
          'A shield wall rests in a sunny meadow at lunchtime. Helmets are stacked beside a basket of bread. No readable text or logo.',
        ],
      },
    ),
    cr('Justin Sweet - Muted Painterly Fantasy Mood', 'fantasy painting', [...T, 'justin-sweet'], {
      look: 'Justin Sweet painterly fantasy: muted desaturated palettes, soft atmospheric edges, lone contemplative figures, heavy mist and classical painterly restraint.',
      subject:
        'paint people as lone contemplative figures in muted misty atmosphere with soft edges.',
      color: 'Muted grey-green, ochre and soft brown.',
      light: 'Soft misty diffuse light.',
      texture: 'Soft painterly oil with lost edges.',
      camera: 'Quiet contemplative framing.',
      mood: 'quiet melancholic contemplation',
      render: 'Restrained painterly fantasy oil.',
      key: 'Justin Sweet muted mist; lone figures; soft edges',
      briefs: [
        'In muted grey-green mist, a lone contemplative knight-errant sits on a fallen log beside her grazing horse, sharpening a pencil instead of a sword while she sketches the ruined abbey ahead. No readable text or logo.',
        'A cloaked archer waits alone in a silent grey birch forest at dusk. Snow falls softly on her bowstring and gathers on her hood. No readable text or logo.',
        'A lonely lantern hangs on a post at a crossroads in the fog. Its light barely reaches the ground. No readable text or logo.',
      ],
    }),
    cr('Michael Whelan - Luminous Surreal Cover Painting', 'fantasy painting', [...T, 'whelan'], {
      look: 'Michael Whelan fantasy painting: luminous surreal color, glowing albino heroes, precise realism, dreamlike cosmic skies and elegant sword-and-sorcery melancholy.',
      subject: 'paint people with precise luminous realism against dreamlike glowing skies.',
      color: 'Luminous violet, cyan and pale gold.',
      light: 'Glowing surreal light.',
      texture: 'Precise smooth acrylic realism.',
      camera: 'Elegant vertical cover composition.',
      mood: 'dreamlike melancholy grandeur',
      render: 'Luminous surreal fantasy painting.',
      key: 'Whelan luminous surreal; glowing skies; precise realism',
      avoid: ['Elric of Melniboné', 'Dark Tower characters'],
      briefs: [
        'Beneath a luminous violet sky full of drifting moons, a pale albino astronomer in flowing silver robes stands on a crystal balcony holding a glowing brass telescope. No readable text or logo.',
        'A black sword lies on a glowing white altar in a cosmic temple. Stars reflect in its blade. No readable text or logo.',
        'A tower of glass rises out of a cyan sea at dusk. Birds of light circle it. No readable text or logo.',
      ],
    }),
    cr('Chris Achilleos - Airbrushed Heroic Fantasy', 'fantasy painting', [...T, 'achilleos'], {
      look: 'Chris Achilleos fantasy art: glossy airbrushed heroic figures, precise ornate armor and costume detail, bright vignetted backgrounds and seventies and eighties fantasy glamour.',
      subject:
        'paint people as glossy airbrushed heroic figures with ornate armor and costume detail.',
      color: 'Glossy saturated skin tones, gold and bright vignette color.',
      light: 'Glossy airbrushed highlights.',
      texture: 'Smooth airbrush and precise detail.',
      camera: 'Vignetted heroic figure framing.',
      mood: 'glamorous heroic bravado',
      render: 'Glossy airbrushed fantasy illustration.',
      key: 'Achilleos airbrush; ornate armor; vignette',
      briefs: [
        'Against a bright vignetted sunset, a glossy airbrushed heroic falconer in ornate bronze armor raises her arm as a golden eagle lands, every filigree detail precise. No readable text or logo.',
        'A warrior in jeweled armor rides a white tiger through a vignetted desert. Her cape billows in gold. No readable text or logo.',
        'An ornate helmet with a dragon crest floats in a glossy vignette. Its eyes glow red. No readable text or logo.',
      ],
    }),
    cr('Brian Froud - Faerie Goblin Watercolor', 'fantasy illustration', [...T, 'froud'], {
      look: 'Brian Froud faerie art: mossy earthy watercolor and pencil, knobbly goblins and faeries with expressive faces, tangled roots, lichen and mischievous woodland magic.',
      subject:
        'paint people and creatures as knobbly earthy faeries and goblins among tangled roots and lichen.',
      color: 'Moss green, earth brown and lichen ochre.',
      light: 'Soft dappled woodland light.',
      texture: 'Pencil and earthy watercolor.',
      camera: 'Close woodland vignette.',
      mood: 'mischievous woodland magic',
      render: 'Earthy faerie watercolor illustration.',
      key: 'Froud faeries; knobbly goblins; roots and lichen',
      avoid: ['Labyrinth or Dark Crystal characters'],
      briefs: [
        'Among tangled mossy roots, a knobbly goblin postmaster with lichen eyebrows sorts acorn-cap letters for a queue of mischievous faeries, painted in earthy pencil and watercolor. No readable text or logo.',
        'A faerie with bark skin naps in a teacup of dew. A snail carries her tiny shoes. No readable text or logo.',
        'A gnarled tree trunk shows a hidden face in its bark. A mushroom door opens at its root. No readable text or logo.',
      ],
    }),
  ],
};

export default spec;
