import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID } from './_style';
import { dna } from './_strict';

// Mythic vault, demons, yokai and night spirits: culture-rooted visual languages from many
// traditions used to paint fantastic demons, ghosts and night spirits. Four Japanese originals
// stay; eighteen new looks add Korean, Chinese, Filipino, Indian, Persian, Arab, Mesopotamian,
// medieval European, Victorian, Balinese, Thai, Czech, Slavic, Irish, Mexica, Javanese and
// Brazilian traditions.
const s = (
  name: string,
  tag: string,
  culture: string,
  aesthetic: string,
  subject: string,
  color: string,
  light: string,
  texture: string,
  camera: string,
  mood: string,
  render: string,
  key: string,
  briefs: [string, string, string],
): Create => ({
  name,
  domain: `${culture} night-spirit art`,
  tags: [tag, culture.toLowerCase().replace(/\s+/g, '-'), 'mythic-demons', 'portable-style-study'],
  dna: dna({
    aesthetic,
    subject_treatment: `Preserve the requested identity, count, pose and action; ${subject}`,
    color_and_tone: color,
    lighting_and_shadow: light,
    texture_and_material: texture,
    camera_and_composition: camera,
    atmosphere_and_mood: `Keep the requested mood with ${mood}.`,
    rendering_and_quality: render,
    key_features: key,
  }),
  avoid: ['cultural stereotypes or caricature', 'readable text or script', 'gore', ...STYLE_AVOID],
  briefs,
});

const spec: Spec = {
  pack: 'pack_14',
  category: 'Demons, Yokai & Night Spirits',
  updates: {},
  creates: [
    s(
      'Korean Dokkaebi Minhwa',
      'dokkaebi',
      'Korean',
      'Korean dokkaebi minhwa: Joseon folk painting with bold outlines and cheerful flat color, showing horned goblins with magic clubs, tigers and magpies in playful mischief.',
      'paint the subject as a bold cheerful folk-painting goblin scene with flat color.',
      'Cheerful red, green, yellow and indigo on mulberry paper.',
      'Flat color without shadows, kept consistent across the whole image.',
      'Hanji paper, bold ink outlines and flat washes.',
      'Lively folk composition with a big goblin, kept consistent across the whole image.',
      'mischievous folk delight',
      'Bold charming folk painting, kept consistent across the whole image.',
      'dokkaebi goblin; magic club; flat color; folk painting',
      [
        'Swinging a magic club that rains gold coins, a one-horned goblin dances with a grinning tiger in a moonlit pine forest painted in bold folk colors. No readable text or logo.',
        'Challenged to a wrestling match, a mischievous goblin keeps losing to an old woodcutter and demands a rematch every single night. No readable text or logo.',
        'Deep in a pine forest at night, a pile of gold coins glows beside a dropped wooden club, and the goblin who owns it is nowhere to be seen. No readable text or logo.',
      ],
    ),
    s(
      'Peking Opera Demon Mask',
      'opera-demon',
      'Chinese',
      'Peking opera demon mask: painted opera face makeup of demons and generals with symbolic colors, bold lines, flared eyebrows, and dazzling stage costume.',
      'render the subject with bold painted opera face patterns and stage costume.',
      'Symbolic red, black, blue, gold and white face paint.',
      'Stage spotlight with dark wings, kept consistent across the whole image.',
      'Painted greasepaint, silk embroidery and pheasant plumes, kept consistent across the whole image.',
      'Close dramatic stage portrait, kept consistent across the whole image.',
      'theatrical fierce spectacle',
      'Crisp vivid stage portrait, kept consistent across the whole image.',
      'opera face paint; symbolic colors; plumes; stage light',
      [
        'Leaping onto a dark stage with pheasant plumes whipping, a blue-faced demon king in gold armor spreads his sleeves as paper lightning falls from the rafters. No readable text or logo.',
        'Backstage, a fearsome opera demon with a fully painted face is carefully sipping tea through a straw so as not to smudge it. No readable text or logo.',
        'On an empty stage after the show, a painted demon face stares back from the dressing mirror, though the actor has already left. No readable text or logo.',
      ],
    ),
    s(
      'Hungry Ghost Lantern Festival',
      'hungry-ghost',
      'Chinese',
      'Hungry ghost lantern festival: glowing river lanterns, paper offerings and drifting ghosts with long thin necks under the seventh-month moon.',
      'place the subject among floating lanterns and drifting pale ghosts on a night river.',
      'Lantern red and gold on deep blue-black water.',
      'Warm lantern glow reflected on water, kept consistent across the whole image.',
      'Paper lanterns, incense smoke and translucent spirits, kept consistent across the whole image.',
      'River scene at night with drifting lights, kept consistent across the whole image.',
      'tender eerie remembrance',
      'Luminous atmospheric painting, kept consistent across the whole image.',
      'river lanterns; drifting ghosts; incense; night moon',
      [
        'Drifting down a dark river among thousands of glowing paper lanterns, a crowd of long-necked hungry ghosts reaches toward the offerings on the bank. No readable text or logo.',
        'At a night festival of floating lanterns, a hungry ghost has found the dumpling stall and is trying to pay with a paper coin. No readable text or logo.',
        'On a black river under the ghost moon, one paper lantern floats upstream, and the ghost following it has no face. No readable text or logo.',
      ],
    ),
    s(
      'Aswang Night Woodcut',
      'aswang',
      'Filipino',
      'Aswang night woodcut: stark Philippine folklore prints of shape-shifting night creatures over nipa huts and banana groves, cut in bold black with moonlit whites.',
      'cut the subject as a stark night woodcut of village folklore creatures.',
      'Black ink with moon white and a touch of red.',
      'Moonlight rims and deep black shadows, kept consistent across the whole image.',
      'Carved wood grain, gouge marks and rice paper.',
      'Night village with a creature above the roofs.',
      'tropical folk dread',
      'Bold carved contrast, kept consistent across the whole image.',
      'night woodcut; nipa huts; banana groves; flying creature',
      [
        'Flying over a village of nipa huts under a full moon, a winged night creature with its long hair streaming leaves its lower half standing in the banana grove. No readable text or logo.',
        'In a village night woodcut, a family has hung so much garlic around their hut that the flying creature is holding its nose. No readable text or logo.',
        'Beneath a stilted house in moonlight, a pair of eyes glows between the posts, and the family dog refuses to look away. No readable text or logo.',
      ],
    ),
    s(
      'Kerala Rakshasa Temple Mural',
      'kerala-mural',
      'Indian',
      'Kerala rakshasa temple mural: South Indian temple mural painting in ochre, green and red with ornate crowns, many arms, fierce demon kings and dense decorative fills.',
      'paint the subject in dense Kerala mural style with ornate crowns and fierce expressions.',
      'Ochre yellow, deep green, red and black, kept consistent across the whole image.',
      'Flat mural color with subtle shading, kept consistent across the whole image.',
      'Natural pigments on plaster, fine decorative lines, kept consistent across the whole image.',
      'Dense frontal mural composition, kept consistent across the whole image.',
      'fierce epic grandeur',
      'Rich ornate mural painting, kept consistent across the whole image.',
      'temple mural; ornate crowns; many arms; ochre and green',
      [
        'Towering across a temple wall in ochre and green, a ten-headed demon king lifts a mountain as tiny sages and monkeys scatter in the ornate borders. No readable text or logo.',
        'In a dense temple mural, a fearsome demon with many arms is using every hand to hold a different snack. No readable text or logo.',
        "On an old temple mural, one of the painted demon's many eyes has been left unpainted, a pale circle watching the corridor. No readable text or logo.",
      ],
    ),
    s(
      'Persian Div Miniature',
      'div-miniature',
      'Persian',
      'Persian div miniature: Shahnama-style miniature painting of spotted horned divs battling heroes among spongy rocks, gold skies and jewel-colored landscapes.',
      'paint the subject as a jewel-toned miniature with spotted horned demons among fantastic rocks.',
      'Lapis, gold sky, vermilion and spring green, kept consistent across the whole image.',
      'Even jewel-like light, kept consistent across the whole image.',
      'Fine pigment, gold leaf and patterned surfaces, kept consistent across the whole image.',
      'High-horizon composition with layered rocks, kept consistent across the whole image.',
      'heroic fantastic wonder',
      'Exquisite miniature detail, kept consistent across the whole image.',
      'spotted divs; gold sky; spongy rocks; hero battle',
      [
        'Among coral-colored rocks under a gold sky, a hero in a tiger-skin cloak wrestles a spotted white div with antelope horns as his horse rears beside a cave. No readable text or logo.',
        "In a jeweled miniature, a spotted div is trying to carry off a sleeping hero and has not noticed the hero's horse biting its tail. No readable text or logo.",
        'In a painted cave mouth on a gold-sky miniature, only a pair of spotted horns rises from the darkness. No readable text or logo.',
      ],
    ),
    s(
      'Jinn Smoke Illumination',
      'jinn-illumination',
      'Arabian',
      'Jinn smoke illumination: illuminated manuscript pages of the wonders tradition, jinn rising from smoke and lamps in gold, lapis and vermilion with arabesque margins.',
      'paint the subject as a jinn scene rising in smoke inside an illuminated page.',
      'Gold, lapis blue, vermilion and ivory, kept consistent across the whole image.',
      'Glowing smoke and gold highlights, kept consistent across the whole image.',
      'Illuminated paper, gold leaf and arabesque borders, kept consistent across the whole image.',
      'Central figure framed by arabesque margins, kept consistent across the whole image.',
      'smoky wondrous mystery',
      'Refined illumination without readable script, kept consistent across the whole image.',
      'jinn in smoke; brass lamp; arabesques; gold',
      [
        'Rising in a spiral of blue smoke from a brass lamp, a vast jinn with flame-colored eyes bows over a fisherman on the shore of a moonlit sea. No readable text or logo.',
        'Freed from a bottle after a thousand years, a jinn first insists on stretching every one of his enormous limbs. No readable text or logo.',
        'On an illuminated page, a brass lamp sits alone in a gold arabesque frame, and a thin thread of smoke rises from its spout. No readable text or logo.',
      ],
    ),
    s(
      'Mesopotamian Demon Bronze',
      'mesopotamian-bronze',
      'Mesopotamian',
      'Mesopotamian demon bronze: ancient cast bronze figures and amulets of winged, taloned wind demons with snarling faces and four wings, dark green patina.',
      'cast the subject as a winged taloned bronze demon figure with patina.',
      'Dark bronze with green patina, kept consistent across the whole image.',
      'Low dramatic light on metal, kept consistent across the whole image.',
      'Cast bronze, feather incisions and corrosion, kept consistent across the whole image.',
      'Single figure against dark ground, kept consistent across the whole image.',
      'ancient wind-borne menace',
      'Crisp ancient casting, kept consistent across the whole image.',
      'winged demon; bronze; talons; patina',
      [
        'Standing on taloned feet atop a desert ziggurat, a four-winged wind demon of dark bronze spreads its wings as a sandstorm roars toward the city. No readable text or logo.',
        'A tiny bronze wind demon amulet hanging over a doorway seems very proud of scaring away one small mosquito. No readable text or logo.',
        'On a museum pedestal, a small bronze demon faces the wall, and its shadow on the wall has its wings open. No readable text or logo.',
      ],
    ),
    s(
      'Medieval Hell-Mouth Illumination',
      'hell-mouth',
      'Medieval European',
      'Medieval hell-mouth illumination: manuscript miniatures of a gaping monstrous jaw swallowing the damned, grotesque blue and red devils, gold grounds and flames.',
      'paint the subject in a gothic miniature with a gaping monstrous mouth and grotesque devils.',
      'Gold ground, flame red, devil blue and green.',
      'Flame glow and flat gold, kept consistent across the whole image.',
      'Vellum, gold leaf and fine brushwork, kept consistent across the whole image.',
      'Framed miniature with a gaping maw, kept consistent across the whole image.',
      'grotesque medieval dread and humor',
      'Detailed illumination without script, kept consistent across the whole image.',
      'hell mouth; grotesque devils; gold ground; flames',
      [
        'Gaping open on a gold-ground page, a colossal beast mouth breathes flames as grotesque blue devils with bat wings herd a crowd of kings and bishops inside. No readable text or logo.',
        'At the gate of a monstrous jaw, a devil with a pitchfork checks a long list of arrivals and is visibly overwhelmed. No readable text or logo.',
        'On an illuminated page, the great monstrous jaw has closed, and a single hand is waving from between its teeth. No readable text or logo.',
      ],
    ),
    s(
      'Victorian Spirit Photograph',
      'spirit-photo',
      'Victorian',
      'Victorian spirit photograph: nineteenth-century double-exposure portraits where translucent ghosts float behind stiff sitters, sepia tones and faded edges.',
      'photograph the subject as a stiff sitter with a translucent ghost double exposure.',
      'Sepia browns, cream highlights and faded edges, kept consistent across the whole image.',
      'Soft studio light with ghostly glow, kept consistent across the whole image.',
      'Albumen print, double exposure and scratches, kept consistent across the whole image.',
      'Formal seated portrait with a floating figure, kept consistent across the whole image.',
      'uncanny parlor mystery',
      'Convincing antique photograph, kept consistent across the whole image.',
      'double exposure; translucent ghost; sepia; stiff pose',
      [
        'Seated stiffly for a sepia portrait, a widow in black lace holds a teacup while a translucent figure in uniform stands behind her with a hand on her shoulder. No readable text or logo.',
        'In a double-exposure spirit portrait, the ghost has clearly moved during the exposure and is now blurry and slightly embarrassed. No readable text or logo.',
        'In an antique portrait of an empty chair, a faint handprint appears on the backrest, glowing whiter than the rest. No readable text or logo.',
      ],
    ),
    s(
      'Balinese Rangda Mask Dance',
      'rangda',
      'Balinese',
      'Balinese rangda mask dance: temple dance of the witch queen with bulging eyes, long tongue and wild hair against the lion-like barong, in gold, red and white.',
      'show the subject in a temple dance of fierce painted masks, gold costume and wild hair.',
      'Gold, crimson, white and black, kept consistent across the whole image.',
      'Torchlight and temple night, kept consistent across the whole image.',
      'Carved painted masks, gold leaf costume and white hair.',
      'Dancers facing each other in a courtyard, kept consistent across the whole image.',
      'ritual dramatic intensity',
      'Vivid performance depiction, kept consistent across the whole image.',
      'rangda mask; barong; gold costume; torchlight',
      [
        'Facing each other in a torchlit temple courtyard, the bulging-eyed witch queen with a flame-long tongue confronts the golden lion-like guardian as dancers fall into trance. No readable text or logo.',
        'During a temple dance, the lion-like guardian costume has two dancers inside, and the back half is clearly going the wrong way. No readable text or logo.',
        "In a temple courtyard after the dance, the witch queen's mask rests on a cushion, and its long tongue has moved. No readable text or logo.",
      ],
    ),
    s(
      'Thai Phi Temple Mural',
      'thai-mural',
      'Thai',
      'Thai phi temple mural: Buddhist temple murals with gold leaf, red grounds and graceful figures, showing forest spirits, giants and ghosts of the Thai tradition.',
      'paint the subject in graceful Thai mural style with gold leaf on a red ground.',
      'Deep red ground, gold leaf, green and white.',
      'Flat mural color with gold shimmer, kept consistent across the whole image.',
      'Mural pigment, gold leaf and fine lines, kept consistent across the whole image.',
      'Continuous mural with small figures, kept consistent across the whole image.',
      'graceful eerie devotion',
      'Refined mural painting, kept consistent across the whole image.',
      'temple mural; red ground; gold leaf; forest spirits',
      [
        'Across a red and gold temple mural, a towering giant guardian with a green face watches over a forest where tree spirits in white drift between the trunks. No readable text or logo.',
        "In a temple mural, a small forest spirit has climbed into a monk's alms bowl and is refusing to leave. No readable text or logo.",
        'In a dim temple, a painted tree spirit on the mural stands among the trunks, and its long hair seems to move in a breeze. No readable text or logo.',
      ],
    ),
    s(
      'Czech Devil Marionette',
      'czech-marionette',
      'Czech',
      'Czech devil marionette: hand-carved wooden string puppets of devils, witches and knights from Bohemian puppet theater, painted faces, horns and cloth costumes.',
      'render the subject as a hand-carved painted string puppet on a small stage.',
      'Red, black and painted wood tones, kept consistent across the whole image.',
      'Warm stage footlights, kept consistent across the whole image.',
      'Carved wood, painted faces, strings and cloth, kept consistent across the whole image.',
      'Puppet stage with visible strings, kept consistent across the whole image.',
      'playful theatrical mischief',
      'Charming handcrafted puppetry, kept consistent across the whole image.',
      'string puppet; carved devil; painted face; stage',
      [
        'Dancing on a candlelit puppet stage, a red carved devil marionette with a curling tail lures a wooden miller toward a painted hell-mouth backdrop. No readable text or logo.',
        'On a small puppet stage, a carved devil has tangled his strings around the angel puppet and both are now stuck together. No readable text or logo.',
        'In a dark puppet workshop, a carved devil marionette hangs on its hook, and one of its strings has been cut. No readable text or logo.',
      ],
    ),
    s(
      'Slavic Nightmare Lubok',
      'lubok',
      'Slavic',
      'Slavic nightmare lubok: Russian popular woodblock prints with bold outlines and bright hand coloring, showing house spirits, forest spirits and night hags.',
      'print the subject as a bold hand-colored folk woodblock with Slavic spirits.',
      'Bright red, yellow, green and blue hand color.',
      'Flat color without shadows, kept consistent across the whole image.',
      'Woodblock lines, hand coloring and rough paper, kept consistent across the whole image.',
      'Framed folk scene, kept consistent across the whole image.',
      'folk dread and humor',
      'Bold naive folk print, kept consistent across the whole image.',
      'lubok print; house spirit; forest spirit; hand-colored',
      [
        'In a bright folk print, a moss-bearded forest spirit taller than the birches leads a lost peasant in circles while wolves dance behind him. No readable text or logo.',
        "In a hand-colored folk print, a grumpy little house spirit is hiding the family's spoons because nobody left him porridge. No readable text or logo.",
        'In a folk print of a sleeping peasant, a small hag sits on his chest, and his cat is the only one who has noticed. No readable text or logo.',
      ],
    ),
    s(
      'Banshee Mist Etching',
      'banshee',
      'Irish',
      'Banshee mist etching: Celtic-revival etchings of keening spirits over moors and ruined towers, fine lines dissolving into mist and moonlight.',
      'etch the subject as a spirit dissolving into mist over a moor or ruin.',
      'Silvery grey and deep black with pale moon.',
      'Moonlight through mist, kept consistent across the whole image.',
      'Fine etched lines, aquatint mist and paper, kept consistent across the whole image.',
      'Moorland with a ruined tower, kept consistent across the whole image.',
      'mournful haunting beauty',
      'Delicate etched atmosphere, kept consistent across the whole image.',
      'keening spirit; mist; ruined tower; moonlight',
      [
        'Rising from the mist over a ruined tower, a keening spirit with hair like drifting smoke combs her long silver locks as a candle flickers in the only window. No readable text or logo.',
        'Wailing grandly on a misty moor at midnight, a keening spirit is interrupted mid-note by a very confused sheep that has wandered up to stare at her. No readable text or logo.',
        'On a moonlit moor, a silver comb lies in the heather, and the mist around it has not moved all night. No readable text or logo.',
      ],
    ),
    s(
      'Tzitzimimeh Star Demon Codex',
      'star-demons',
      'Mexica',
      'Tzitzimimeh star demon codex: codex-style star demons of the night sky descending on eclipse, skeletal bodies with star eyes and bold outlined flat color.',
      'draw the subject as bold outlined star demons descending from a starry codex sky.',
      'Black night, bone white, star yellow and red.',
      'Flat codex color with glowing stars, kept consistent across the whole image.',
      'Gesso ground, bold outlines and fold creases, kept consistent across the whole image.',
      'Sky filled with descending figures, kept consistent across the whole image.',
      'cosmic eclipse dread',
      'Crisp codex drawing without readable glyphs, kept consistent across the whole image.',
      'star demons; eclipse; bold outlines; codex',
      [
        'During a total eclipse, skeletal star demons with glittering eyes descend on ropes of starlight toward a city whose people bang drums to drive them back. No readable text or logo.',
        'Waiting for an eclipse that keeps being delayed, a group of star demons sits on the edge of the sky looking bored. No readable text or logo.',
        'In a codex sky full of stars, one star has two eyes and is looking down. No readable text or logo.',
      ],
    ),
    s(
      'Javanese Wayang Demon Puppet',
      'wayang',
      'Javanese',
      'Javanese wayang demon puppet: intricately perforated painted leather shadow puppets of giants and demons, gilded and cast as shadows on a white screen by oil lamp.',
      'render the subject as a perforated leather shadow puppet and its shadow on a lit screen.',
      'Gold, red and black leather with warm screen glow.',
      'Oil lamp light casting sharp shadows, kept consistent across the whole image.',
      'Perforated buffalo hide, horn rods and gilt paint.',
      'Puppet and shadow on a white screen, kept consistent across the whole image.',
      'mythic theatrical enchantment',
      'Intricate perforated detail, kept consistent across the whole image.',
      'shadow puppet; perforated leather; oil lamp; screen',
      [
        'Cast huge on a glowing screen by an oil lamp, the shadow of a fanged giant puppet reaches for a slender prince puppet whose shadow raises a tiny bow. No readable text or logo.',
        'Behind the shadow screen, the giant demon puppet has been bent so dramatically that the puppeteer is now stuck in the rods. No readable text or logo.',
        'On a white screen at the end of a show, one shadow remains after all the puppets have been put away. No readable text or logo.',
      ],
    ),
    s(
      'Cordel Devil Woodcut',
      'cordel',
      'Brazilian',
      'Cordel devil woodcut: Brazilian northeastern cordel pamphlet woodcuts with bold black carving of devils, cangaceiros and saints in rustic comic drama.',
      'cut the subject as a bold rustic black woodcut in cordel style.',
      'Black ink on cream or colored pamphlet paper.',
      'Flat carved contrast, kept consistent across the whole image.',
      'Rough wood gouges and cheap paper, kept consistent across the whole image.',
      'Single bold scene in a rectangle, kept consistent across the whole image.',
      'rustic comic menace',
      'Bold carved charm, kept consistent across the whole image.',
      'cordel woodcut; devil; cangaceiro; rough gouges',
      [
        'Carved in bold black, a horned devil arrives at a backlands dance and challenges the fiddler to a duel while the dancers freeze mid-step. No readable text or logo.',
        'In a rustic woodcut, a crafty backlands cowboy has sold his hat to the devil, and the devil is trying it on very proudly. No readable text or logo.',
        'In a rough woodcut of a dusty crossroads, a pair of cloven hoofprints stops in the middle of the road. No readable text or logo.',
      ],
    ),
  ],
};

export default spec;
