import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Video games of the 1990s: each preset names its game, studio and hardware and rebuilds that
// game's real on-screen look. Cards stage original characters and places in that look.
const T = ['games-90s', 'video-game-era'];
const lowpoly =
  'Low-polygon models with affine texture warping, blurry low-resolution textures and visible vertex jitter.';

const spec: Spec = {
  pack: 'pack_27',
  category: '5. Video Games 90s',
  newCategory: { id: 'video-games-90s' },
  updates: {},
  creates: [
    cr('Doom 1993 - id Software Sprite Shooter', 'nineties PC game', [...T, 'doom'], {
      look: 'id Software Doom (1993) look: first-person 2.5D corridors, low-resolution brown and red textures, flat sprite monsters, a weapon sprite at screen bottom and a status bar with a face.',
      subject:
        'render the subject in first-person 2.5D corridors with flat billboard sprites and gritty textures.',
      color: 'Hellish brown, blood red, techbase grey and toxic green.',
      light: 'Sector-based flat lighting with flickering rooms.',
      texture: 'Chunky 320x200 pixels, low-resolution textures and flat sprites.',
      camera: 'First-person view with a weapon sprite and status bar.',
      mood: 'frantic hellish action',
      render: 'Authentic 1993 PC first-person screen capture.',
      key: 'Doom 2.5D; flat sprite monsters; brown and red; status bar',
      avoid: ['a green-armored space marine face', 'horned red demons'],
      briefs: [
        'In a first-person 2.5D techbase corridor of brown and grey textures, a flat sprite of a furious office printer spits paper at the player, whose screen-bottom weapon is a chunky pixel stapler. The status bar face looks worried. No readable text or logo.',
        'A flickering hell-red chamber is full of flat sprite demons made of kitchen appliances. A toaster fires fireballs. No readable text or logo.',
        'An empty pixel corridor ends at a glowing blue keycard door. Toxic green sludge flows below. No readable text or logo.',
      ],
    }),
    cr('Myst 1993 - Cyan Pre-Rendered Island', 'nineties adventure game', [...T, 'myst'], {
      look: 'Cyan Myst (1993) look: still pre-rendered 3D island scenes, early CGI surfaces, strange mechanical puzzles, libraries and quiet surreal emptiness.',
      subject:
        'render the subject as a still pre-rendered early CGI scene of a quiet surreal island.',
      color: 'Early CGI greens, stone grey and brass.',
      light: 'Soft early CGI lighting with ray-traced gloss.',
      texture: 'Early nineties pre-rendered CGI with dithered 256 colors.',
      camera: 'Still first-person node views.',
      mood: 'quiet surreal mystery',
      render: 'Pre-rendered early nineties CGI still.',
      key: 'Myst pre-rendered; still nodes; mechanical puzzles; island',
      briefs: [
        'In a still pre-rendered early CGI view, a lonely island dock leads to a brass telescope tower beside a giant gear half-sunk in the water, dithered clouds hanging motionless above. Nobody is anywhere. No readable text or logo.',
        'A pre-rendered library holds two strange books on pedestals and a glowing map table. The fireplace is cold. No readable text or logo.',
        'A single brass lever stands on a mossy rock in a still CGI forest. A clock tower hums in the distance. No readable text or logo.',
      ],
    }),
    cr(
      'Final Fantasy VII 1997 - Pre-Rendered Backdrop Polygons',
      'nineties console role-playing game',
      [...T, 'ff7'],
      {
        look: 'Square Final Fantasy VII (1997) look: detailed pre-rendered CGI backdrops with blocky low-poly chibi characters walking in front, industrial steampunk cities and Tetsuya Nomura designs.',
        subject:
          'render the subject as blocky low-poly chibi figures standing in front of a detailed pre-rendered backdrop.',
        color: 'Mako green glow, rusty industrial browns and night blue.',
        light: 'Pre-rendered glowing lights and flat polygon shading.',
        texture: 'Blocky low-poly figures over detailed pre-rendered art.',
        camera: 'Fixed cinematic angle of a pre-rendered scene.',
        mood: 'melancholy steampunk adventure',
        render: 'Authentic late-nineties PlayStation JRPG screen.',
        key: 'FF7 pre-rendered backdrops; chibi polygons; mako green',
        avoid: ['a spiky blond soldier with a buster sword', 'existing franchise characters'],
        briefs: [
          'In front of a detailed pre-rendered steampunk train station glowing green, a blocky low-poly chibi flower seller and a low-poly retired mechanic argue over a broken ticket machine. Their polygon hands are mittens. No readable text or logo.',
          'A low-poly chibi party stands on a pre-rendered rusty bridge above glowing green pipes. A small round cat balloon mascot floats above them, reading a fortune off a tiny scroll. No readable text or logo.',
          'A pre-rendered empty church glows with a patch of flowers under a broken roof. Light falls on them. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Resident Evil 1996 - Fixed-Camera Mansion Dread',
      'nineties survival horror game',
      [...T, 're-96'],
      {
        look: 'Capcom Resident Evil (1996) look: fixed cinematic camera angles over pre-rendered mansion rooms, low-poly characters, tank-control dread and door-opening transitions.',
        subject:
          'render the subject as low-poly figures in fixed-camera pre-rendered mansion rooms.',
        color: 'Dim mansion browns, dusty reds and dim green.',
        light: 'Dim pre-rendered lamplight and shadows.',
        texture: lowpoly,
        camera: 'Fixed high-angle security-camera shots.',
        mood: 'claustrophobic survival dread',
        render: 'Authentic PlayStation survival horror screen.',
        key: 'Fixed cameras; pre-rendered mansion; low-poly; survival dread',
        avoid: ['S.T.A.R.S. uniforms', 'zombie dogs through windows'],
        briefs: [
          'From a fixed high-angle camera, a low-poly insurance adjuster in a trench coat stands frozen in a pre-rendered mansion dining hall as a slow shuffling shape appears in the far doorway. A typewriter sits on a side table. No readable text or logo.',
          'A low-poly chef backs away from a pre-rendered kitchen where the refrigerator door hangs open. Something is dripping. No readable text or logo.',
          'A pre-rendered mansion door creaks open in a slow first-person transition. Darkness waits beyond it, and a single flickering candle shows the wet footprints on the carpet. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Chrono Trigger 1995 - Toriyama Sixteen-Bit Time Travel',
      'nineties console role-playing game',
      [...T, 'chrono-trigger'],
      {
        look: 'Square Chrono Trigger (1995) SNES look: vibrant 16-bit sprites with Akira Toriyama designs, lush tile maps, time eras from prehistory to future and fairground warmth.',
        subject: 'render the subject as vibrant 16-bit sprites in lush tile-based era maps.',
        color: 'Vibrant SNES greens, blues and warm fairground colors.',
        light: 'Bright 16-bit palette with color gradients.',
        texture: 'Crisp 16-bit sprites and tiles.',
        camera: 'Top-down three-quarter view of tile maps.',
        mood: 'joyful time-traveling adventure',
        render: 'Authentic SNES JRPG screen.',
        key: 'Chrono Trigger 16-bit; Toriyama sprites; time eras',
        avoid: ['a red spiky-haired boy with a katana', 'a frog knight'],
        briefs: [
          'On a lush 16-bit tile map of a medieval fairground, a sprite of a retired clockmaker and his robot assistant step into a glowing time portal while balloons and a dancing crowd wave. The colors are warm and bright. No readable text or logo.',
          'A 16-bit sprite caveman grills fish beside a prehistoric lake while dinosaurs watch. The palms sway. No readable text or logo.',
          'A 16-bit ruined future dome glows under a grey sky. A single flower grows in the rubble. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Donkey Kong Country 1994 - Rare Pre-Rendered Sprites',
      'nineties console platformer',
      [...T, 'dkc'],
      {
        look: 'Rare Donkey Kong Country (1994) SNES look: pre-rendered 3D models turned into glossy sprites, lush jungles, mine carts, banana hoards and atmospheric parallax.',
        subject: 'render the subject as glossy pre-rendered 3D sprites in lush jungle stages.',
        color: 'Jungle green, banana yellow and sunset orange.',
        light: 'Pre-rendered glossy lighting and atmospheric haze.',
        texture: 'Glossy pre-rendered sprites with SNES palette limits.',
        camera: 'Side-scrolling jungle platform view.',
        mood: 'lush jungle adventure',
        render: 'Authentic SNES pre-rendered platformer screen.',
        key: 'DKC pre-rendered sprites; jungle; mine carts; glossy',
        avoid: ['a gorilla with a red tie', 'a monkey with a red cap'],
        briefs: [
          'In a glossy pre-rendered jungle stage, a sprite of a round-bellied tapir in a construction helmet rides a mine cart through a canyon full of glowing crystals as a parrot flaps ahead. The parallax trees sway. No readable text or logo.',
          'A glossy pre-rendered sloth swings across a misty jungle lagoon on long vines. Snapping crocodiles bob below and fireflies drift through the parallax haze. No readable text or logo.',
          'A pre-rendered treasure hoard of coconuts glows in a jungle cave. A barrel cannon waits beside it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Sonic the Hedgehog 1991 - Sega Loop Zone Speed',
      'nineties console platformer',
      [...T, 'sonic-91'],
      {
        look: 'Sega Sonic the Hedgehog (1991) Mega Drive look: checkerboard hills, loop-de-loops, palm trees, bright saturated blue skies and speed.',
        subject: 'render the subject as a fast sprite racing through checkerboard hills and loops.',
        color: 'Saturated sky blue, grass green and checkerboard brown.',
        light: 'Bright Mega Drive light.',
        texture: 'Crisp Mega Drive sprites and tiles.',
        camera: 'Side-scrolling speed view.',
        mood: 'bright blazing speed',
        render: 'Authentic Mega Drive platformer screen.',
        key: 'Sonic checkerboard hills; loops; palm trees; speed',
        avoid: ['a blue hedgehog with red shoes', 'gold rings'],
        briefs: [
          'Across checkerboard hills and a giant loop-de-loop under a saturated blue sky, a sprite of a speedy armadillo in roller skates blasts past palm trees collecting shiny acorns. The water sparkles below. No readable text or logo.',
          'A sprite badger surfs a waterfall at top speed through a bright zone. Robot bees chase him. No readable text or logo.',
          'An empty checkerboard hill with a single loop sits under a bright sky. A spring waits at the bottom. No readable text or logo.',
        ],
      },
    ),
    cr('Street Fighter II 1991 - Capcom Sprite Versus', 'nineties fighting game', [...T, 'sf2'], {
      look: 'Capcom Street Fighter II (1991) look: large detailed fighting sprites, world stage backgrounds with cheering crowds, health bars and chunky special-move effects.',
      subject: 'render the subject as large detailed fighting sprites on a lively world stage.',
      color: 'Bright arcade colors with detailed stage backdrops.',
      light: 'Flat arcade light.',
      texture: 'Large detailed arcade sprites.',
      camera: 'Side versus view with health bars.',
      mood: 'competitive arcade intensity',
      render: 'Authentic early-nineties fighting game screen.',
      key: 'SF2 large sprites; world stages; versus layout',
      avoid: ['existing fighting game characters'],
      briefs: [
        'On a detailed fighting stage in a crowded fish market, two large sprites face off, a retired sushi chef and a baker in a flour-dusted apron, as the crowd of cheering fishmongers waves from the background. Health bars glow at the top. No readable text or logo.',
        'A sprite librarian fighter blocks a flying kick in a quiet reading room stage. The patrons keep reading. No readable text or logo.',
        'An empty fighting stage waits in a moonlit temple courtyard with stone lanterns. Cherry petals drift across the flagstones while monks watch quietly from the balcony. No readable text or logo.',
      ],
    }),
    cr(
      'Metal Slug 1996 - Nazca SNK Pixel War',
      'nineties arcade action game',
      [...T, 'metal-slug'],
      {
        look: 'Nazca and SNK Metal Slug (1996) look: incredibly detailed hand-drawn pixel art, comedic soldiers, chunky tanks and explosions animated frame by frame.',
        subject:
          'render the subject as highly detailed comedic pixel art with chunky vehicles and explosions.',
        color: 'Desert tan, military green and explosion orange.',
        light: 'Bright pixel explosion light.',
        texture: 'Dense hand-drawn pixel art.',
        camera: 'Side-scrolling war view.',
        mood: 'comedic explosive chaos',
        render: 'Authentic Neo Geo pixel art screen.',
        key: 'Metal Slug detailed pixels; comedic war; chunky tanks',
        avoid: ['a tiny green tank with a cannon'],
        briefs: [
          'In densely detailed pixel art, a comedic grandmother soldier drives a chunky ice cream truck tank through a desert town as enemy soldiers panic and drop their lunches. Pixel explosions bloom everywhere. No readable text or logo.',
          'A pixel camel with a machine gun on its back charges across the dunes. The enemy flees. No readable text or logo.',
          'A detailed pixel prisoner waits tied to a post with a gift box. He is smiling. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Secret of Monkey Island 1990 - LucasArts Painted Adventure',
      'nineties adventure game',
      [...T, 'monkey-island'],
      {
        look: 'LucasArts The Secret of Monkey Island (1990) look: moody painted pixel backgrounds, Caribbean pirate towns at night, small characters and witty verb interface.',
        subject: 'render the subject as small pixel characters in moody painted Caribbean scenes.',
        color: 'Moody Caribbean night blue, tavern orange and sea teal.',
        light: 'Moonlit night and warm tavern windows.',
        texture: 'Painted VGA pixel art.',
        camera: 'Side-view scenes with a verb interface.',
        mood: 'witty piratical adventure',
        render: 'Authentic VGA adventure screen.',
        key: 'Monkey Island moody pixels; pirate towns; verb interface',
        avoid: ['a blond wannabe pirate in a white shirt', 'a ghost pirate'],
        briefs: [
          'On a moonlit painted pixel dock in a Caribbean pirate town, a small pixel accountant tries to buy a ship with a rubber chicken while a parrot heckles from a lamppost. The tavern glows orange. No readable text or logo.',
          'Three important-looking pixel pirates sit around a candlelit tavern table scheming about a map. One of them is fast asleep, snoring into his grog mug. No readable text or logo.',
          'A pixel treasure map glows on a desk under a single candle. A monkey sits on the chair. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Diablo 1996 - Blizzard Gothic Isometric',
      'nineties PC action role-playing game',
      [...T, 'diablo-96'],
      {
        look: 'Blizzard North Diablo (1996) look: dark gothic isometric pre-rendered sprites, blood-red and brown dungeons, candlelit cathedral town of Tristram and grim atmosphere.',
        subject:
          'render the subject as a small isometric sprite in dark gothic pre-rendered dungeons.',
        color: 'Dark brown, blood red and candle gold.',
        light: 'Light radius around the character in darkness.',
        texture: 'Pre-rendered sprites with 256-color gloom.',
        camera: 'Isometric view with a light radius.',
        mood: 'grim gothic dread',
        render: 'Authentic mid-nineties isometric ARPG screen.',
        key: 'Diablo isometric; light radius; gothic dungeon',
        avoid: ['a horned red demon lord'],
        briefs: [
          'In a dark isometric cathedral dungeon, a small pre-rendered sprite of a village blacksmith holds a lantern whose light radius reveals a crowd of shambling bone shapes just at its edge. The floor is stained. No readable text or logo.',
          'A pre-rendered isometric village square glows with a single campfire at night. A cow stands nearby. No readable text or logo.',
          'An isometric treasure chest glows faintly in a dark stone crypt. The light radius of the approaching hero barely reaches it, and something shifts in the shadows. No readable text or logo.',
        ],
      },
    ),
    cr('StarCraft 1998 - Blizzard Sci-Fi RTS', 'nineties strategy game', [...T, 'starcraft'], {
      look: 'Blizzard StarCraft (1998) look: isometric pre-rendered sci-fi units, alien creep, industrial space bases, dark space platforms and RTS interface.',
      subject: 'render the subject as tiny pre-rendered isometric units on dark sci-fi terrain.',
      color: 'Dark space blue, alien purple and industrial grey.',
      light: 'Pre-rendered unit lighting and dark terrain.',
      texture: 'Pre-rendered isometric sprites.',
      camera: 'Isometric RTS view with interface.',
      mood: 'tense sci-fi warfare',
      render: 'Authentic late-nineties RTS screen.',
      key: 'StarCraft isometric units; alien creep; RTS interface',
      avoid: ['existing faction units'],
      briefs: [
        'On a dark isometric space platform, a squad of tiny pre-rendered delivery robots builds a noodle stand while a purple alien carpet slowly creeps toward it from the edge of the map. The minimap blinks. No readable text or logo.',
        'Tiny pre-rendered mining drones harvest glowing crystals on a snowy moon outpost. A hungry creature watches from the ridge while the supply counter ticks upward. No readable text or logo.',
        'An isometric sci-fi base stands empty under a purple alien sky. Its alarms blink red, its turrets turn slowly, and the creep spreads toward the gate. No readable text or logo.',
      ],
    }),
    cr(
      'Crash Bandicoot 1996 - Naughty Dog Cartoon 3D',
      'nineties console platformer',
      [...T, 'crash'],
      {
        look: 'Naughty Dog Crash Bandicoot (1996) look: cartoon 3D corridors into the screen, lush tropical islands, wooden crates, running-toward-camera chases and vibrant PS1 colors.',
        subject:
          'render the subject as a cartoon 3D character running down lush tropical corridors.',
        color: 'Vibrant tropical green, crate brown and ocean blue.',
        light: 'Bright tropical PS1 lighting.',
        texture: lowpoly,
        camera: 'Behind-the-character corridor view.',
        mood: 'zany tropical fun',
        render: 'Authentic PS1 cartoon platformer screen.',
        key: 'Crash corridors; crates; tropical islands; cartoon 3D',
        avoid: ['an orange bandicoot in jeans'],
        briefs: [
          'Down a lush cartoon 3D jungle corridor, a zany low-poly iguana in sneakers smashes wooden crates of mangoes while a giant boulder rolls toward the camera behind him. The PS1 textures wobble. No readable text or logo.',
          'A cartoon 3D penguin surfs a river of lava on a crate lid. The volcano rumbles. No readable text or logo.',
          'A single wooden crate sits on a tropical beach under a low-poly palm tree. It is ticking. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Super Mario 64 1996 - N64 Blurry Texture Worlds',
      'nineties console platformer',
      [...T, 'mario-64'],
      {
        look: 'Nintendo Super Mario 64 (1996) look: bright blocky 3D worlds with blurry filtered textures, painting portals, floating islands, fog at the draw distance and cheerful primary colors.',
        subject: 'render the subject in bright blocky 3D worlds with blurry filtered N64 textures.',
        color: 'Cheerful primary colors and grass green.',
        light: 'Bright flat N64 lighting with distance fog.',
        texture: 'Blurry bilinear-filtered N64 textures and simple polygons.',
        camera: 'Third-person chase camera.',
        mood: 'cheerful playful exploration',
        render: 'Authentic N64 3D platformer screen.',
        key: 'N64 blurry textures; blocky worlds; painting portals; fog',
        avoid: ['a mustached plumber in red and blue', 'a princess castle with star doors'],
        briefs: [
          'In a bright blocky N64 world with blurry grass textures, a low-poly beaver in overalls dives into a framed painting on a castle wall and emerges into a floating island level. Fog softens the distant hills. No readable text or logo.',
          'A low-poly turtle rides a long slide of ice down a snowy N64 mountain. A crowd of round penguins cheers from blurry snowbanks as it spins past. No readable text or logo.',
          'A blurry N64 painting hangs on a castle wall, rippling like water. A coin floats beside it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'GoldenEye 007 1997 - Rare N64 Fog Shooter',
      'nineties console shooter',
      [...T, 'goldeneye'],
      {
        look: 'Rare GoldenEye 007 (1997) N64 look: first-person corridors with blurry textures, heavy fog, low frame rate, stiff low-poly guards and Cold War facilities.',
        subject:
          'render the subject in first-person foggy N64 corridors with stiff low-poly figures.',
        color: 'Military grey, snow white and fog.',
        light: 'Flat N64 light and heavy fog.',
        texture: 'Blurry N64 textures and stiff low polygons.',
        camera: 'First-person view with a weapon model.',
        mood: 'tense spy infiltration',
        render: 'Authentic N64 first-person screen.',
        key: 'GoldenEye fog; blurry textures; stiff guards; facilities',
        avoid: ['a tuxedoed spy', 'a gun barrel logo'],
        briefs: [
          'In first-person through heavy N64 fog, a low-poly night janitor holding a mop like a weapon creeps through a Cold War dam facility as stiff low-poly guards patrol the snowy catwalk. Everything is slightly blurry. No readable text or logo.',
          'A low-poly security guard stands frozen in a tiled bathroom stall, staring straight ahead. His hat is two polygons and his mustache is a flat blurry texture. No readable text or logo.',
          'An empty foggy N64 corridor stretches toward a locked vault door. A red alarm light spins. No readable text or logo.',
        ],
      },
    ),
    cr('PaRappa the Rapper 1996 - Paper-Flat Rhythm', 'nineties rhythm game', [...T, 'parappa'], {
      look: 'NanaOn-Sha PaRappa the Rapper (1996) look: paper-flat 2D characters by Rodney Greenblat in 3D worlds, bright pop colors and rhythm game energy.',
      subject: 'render the subject as paper-flat cartoon cutouts in bright pop 3D worlds.',
      color: 'Bright pop pink, yellow, blue and green.',
      light: 'Flat cheerful light.',
      texture: 'Flat paper cutout characters in simple 3D sets.',
      camera: 'Stage-like rhythm scenes.',
      mood: 'cheerful rhythmic optimism',
      render: 'Authentic PS1 rhythm game screen.',
      key: 'PaRappa paper-flat; Greenblat designs; pop colors',
      avoid: ['a rapping dog in a knit hat', 'an onion martial arts master'],
      briefs: [
        'In a bright pop 3D kitchen, a paper-flat cartoon cutout of a giraffe baker raps instructions to a paper-flat frog apprentice who keeps flipping pancakes onto the ceiling. The whole set bounces to the beat. No readable text or logo.',
        'A paper-flat cat driving instructor raps behind the wheel of a toy car. The road wobbles. No readable text or logo.',
        'A paper-flat microphone stands alone on a bright pink stage with a paper-flat curtain. The spotlight bounces to the beat and a paper audience waves its flat hands. No readable text or logo.',
      ],
    }),
    cr('Half-Life 1998 - Valve Black Mesa Facility', 'nineties PC shooter', [...T, 'half-life'], {
      look: 'Valve Half-Life (1998) look: first-person science facility corridors, orange and beige lab textures, flickering fluorescents, scientists in lab coats and resonance cascade chaos.',
      subject:
        'render the subject in first-person science facility corridors with lab coats and flickering lights.',
      color: 'Facility beige, hazard orange and industrial grey.',
      light: 'Flickering fluorescent lab lighting.',
      texture: 'Low-resolution facility textures and simple polygons.',
      camera: 'First-person corridor view.',
      mood: 'unraveling facility dread',
      render: 'Authentic late-nineties PC shooter screen.',
      key: 'Half-Life facility; lab coats; flickering fluorescents',
      avoid: ['an orange hazard suit with a crowbar', 'a man in a blue suit with a briefcase'],
      briefs: [
        'In a first-person science facility corridor, a panicked low-poly cafeteria worker in a paper hat runs past flickering fluorescents as a portal of green light opens beside the vending machines. Alarms echo down the beige halls. No readable text or logo.',
        'Two low-poly scientists argue beside a test chamber as sparks fly. Neither notices the ceiling vent open. No readable text or logo.',
        'An empty tram rolls slowly into a silent facility station deep underground. The monorail lights flicker and a security guard waves from behind the glass. No readable text or logo.',
      ],
    }),
    cr(
      'Grim Fandango 1998 - LucasArts Calavera Noir',
      'nineties adventure game',
      [...T, 'grim-fandango'],
      {
        look: 'LucasArts Grim Fandango (1998) look: Day of the Dead calavera characters, art deco film noir, pre-rendered backgrounds with low-poly skeletons and smoky atmosphere.',
        subject:
          'render the subject as low-poly calavera skeletons in art deco noir pre-rendered scenes.',
        color: 'Noir amber, marigold orange and deep teal.',
        light: 'Smoky noir lighting and neon.',
        texture: 'Pre-rendered deco backgrounds with low-poly figures.',
        camera: 'Cinematic noir fixed angles.',
        mood: 'smoky deco noir',
        render: 'Authentic late-nineties noir adventure screen.',
        key: 'Grim Fandango calaveras; art deco noir; low-poly skeletons',
        avoid: ['a skeleton travel agent in a suit and a demon mechanic'],
        briefs: [
          'In a smoky art deco nightclub of the afterlife, a low-poly calavera skeleton jazz singer in a sequin gown performs under neon marigold lights while skeleton patrons sip glowing drinks. Everything is noir amber. No readable text or logo.',
          'A skeleton detective stands on a rainy deco street holding a paper umbrella. His cigarette glows. No readable text or logo.',
          'A single marigold rests on a deco desk under a noir lamp. A skeleton hand reaches for it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'EarthBound 1994 - Ape Suburban Psychedelia',
      'nineties console role-playing game',
      [...T, 'earthbound'],
      {
        look: 'Ape and HAL EarthBound (1994) SNES look: small suburban sprite towns, oblique perspective, quirky everyday enemies and psychedelic swirling battle backgrounds.',
        subject:
          'render the subject as small quirky sprites in suburban towns with psychedelic battle backdrops.',
        color: 'Pastel suburban colors and psychedelic battle swirls.',
        light: 'Flat SNES light.',
        texture: 'Crisp SNES sprites and animated psychedelic patterns.',
        camera: 'Oblique top-down town view or battle screen.',
        mood: 'quirky suburban surrealism',
        render: 'Authentic SNES quirky RPG screen.',
        key: 'EarthBound suburban sprites; psychedelic battles; quirky enemies',
        avoid: ['a boy in a red cap with a baseball bat'],
        briefs: [
          'On a psychedelic swirling battle background, a quirky enemy made of a grumpy office stapler faces a tiny sprite party of a retired mailman, a dog and a librarian. The swirls pulse in pastel colors. No readable text or logo.',
          'A small sprite town at dusk holds a burger shop, a drugstore and a suspicious crashed meteor. A cop stands guard. No readable text or logo.',
          'A single sprite telephone rings in an empty suburban living room at night. Beside it the swirling psychedelic battle background is already leaking through the wallpaper. No readable text or logo.',
        ],
      },
    ),
    cr('Ecco the Dolphin 1992 - Sega Alien Ocean', 'nineties console game', [...T, 'ecco'], {
      look: 'Sega Ecco the Dolphin (1992) look: detailed underwater pixel art, eerie deep blue oceans, glyph crystals, alien architecture and lonely atmosphere.',
      subject:
        'render the subject swimming through eerie detailed pixel oceans with alien crystals.',
      color: 'Deep ocean blue, crystal cyan and alien purple.',
      light: 'Filtered underwater light and crystal glow.',
      texture: 'Detailed Mega Drive pixel art.',
      camera: 'Side-view underwater exploration.',
      mood: 'lonely alien ocean',
      render: 'Authentic Mega Drive underwater screen.',
      key: 'Ecco underwater pixels; glyph crystals; alien ocean',
      avoid: ['a bottlenose dolphin with star markings'],
      briefs: [
        'In detailed pixel art of an eerie deep ocean, a lonely sea turtle swims past glowing glyph crystals and the sunken remains of an alien spiral tower. Shafts of light fall from far above. No readable text or logo.',
        'A pixel humpback whale sings to a glowing crystal buried in the sand of a deep reef. Schools of tiny fish gather in rings around the sound. No readable text or logo.',
        'A single glowing crystal floats in a dark pixel ocean trench. Something enormous passes behind it. No readable text or logo.',
      ],
    }),
  ],
};

export default spec;
