import type { Spec } from '../tools/apply';
import { ga } from './_authors';

// Video game pass, gothic and dungeon gameplay: each preset names its game, studio and year and
// states the real render technique and camera. The cave descent moves to Noita because the idol
// and boulder platformer already names Spelunky in the arcane category.
// Intentional-v1 presets (SP12-081 to SP12-098) keep their own policy and stay out of this pass.
const spec: Spec = {
  pack: 'pack_12',
  category: '9. Gothic & Dungeon Gameplay',
  updates: Object.fromEntries([
    ga('SP12-179', 'Children of Morta 2019 - Dead Mage Painterly Pixel', {
      look: 'Dead Mage Children of Morta (2019) look: top-down action roguelite in detailed painterly pixel art, family of heroes, crypts and caves with glowing spell effects.',
      subject: 'render people as detailed painterly pixel heroes seen from above.',
      color: 'Warm torch amber, crypt teal and spell glow.',
      light: 'Pixel torchlight and spell glow.',
      texture: 'Painterly pixel art.',
      camera: 'Top-down roguelite view.',
      mood: 'warm heroic struggle',
      render: 'Authentic pixel roguelite screen.',
      key: 'Children of Morta pixels; crypts; spell glow',
    }),
    ga('SP12-180', 'Salt and Sanctuary 2016 - Ska Studios Grim Hand-Drawn', {
      look: 'Ska Studios Salt and Sanctuary (2016) look: side-view hand-drawn grim fantasy, thick-lined gothic characters, towering bosses and moody castle halls.',
      subject: 'render people as thick-lined hand-drawn grim warriors.',
      color: 'Moonlit grey, rust and blood red.',
      light: 'Stained moonlight and shadows.',
      texture: 'Hand-drawn inked textures.',
      camera: 'Side-view castle view.',
      mood: 'grim gothic dread',
      render: 'Authentic hand-drawn action screen.',
      key: 'Salt and Sanctuary hand-drawn; side-view; bosses',
    }),
    ga('SP12-181', 'Legend of Grimrock 2012 - Almost Human Grid Dungeon', {
      look: 'Almost Human Legend of Grimrock (2012) look: first-person grid dungeon crawler with stone corridors, torches, pressure plates and real-time monsters.',
      subject: 'render people and monsters in stone corridors seen from first person.',
      color: 'Torch amber, stone grey and moss green.',
      light: 'Torchlight in stone corridors.',
      texture: 'Detailed stone and iron.',
      camera: 'First-person grid view.',
      mood: 'claustrophobic dungeon tension',
      render: 'Authentic dungeon crawler screen.',
      key: 'Grimrock grid dungeon; torches; stone corridors',
    }),
    ga('SP12-182', 'Elden Ring 2022 - FromSoftware Lands Between', {
      look: 'FromSoftware Elden Ring (2022) look: third-person open-world dark fantasy, golden Erdtree light, colossal bosses, ruined arenas and lock-on duels.',
      subject: 'render people as weathered Tarnished warriors in mixed armor.',
      color: 'Golden light, ash grey and flame orange.',
      light: 'Golden tree glow and fire.',
      texture: 'Weathered stone and armor.',
      camera: 'Third-person lock-on view.',
      mood: 'epic desperate duel',
      render: 'Authentic modern dark fantasy screen.',
      key: 'Elden Ring bosses; golden light; lock-on',
      avoid: ['existing Elden Ring bosses', 'a giant golden tree'],
    }),
    ga('SP12-183', 'Enter the Gungeon 2016 - Dodge Roll Pixel Bullet Hell', {
      look: 'Dodge Roll Enter the Gungeon (2016) look: top-down pixel bullet hell dungeon, gun puns, bullet-shaped enemies, spirals of glowing projectiles and dodge rolls.',
      subject: 'render people as small pixel gunslingers seen from above.',
      color: 'Dungeon grey and neon bullet colors.',
      light: 'Pixel light with bullet glow.',
      texture: 'Detailed pixel art.',
      camera: 'Top-down dungeon view.',
      mood: 'frantic bullet chaos',
      render: 'Authentic pixel bullet-hell screen.',
      key: 'Gungeon pixel bullets; top-down; bosses',
      avoid: ['bullet-shaped enemies with guns'],
    }),
    ga('SP12-184', 'Gauntlet 2014 - Arrowhead Co-op Dungeon', {
      look: 'Arrowhead Game Studios Gauntlet (2014) look: isometric co-op dungeon brawler, four color-coded heroes, endless goblin swarms, spawners and treasure.',
      subject: 'render people as four color-coded dungeon heroes.',
      color: 'Hero red, blue, green and gold.',
      light: 'Dungeon torchlight.',
      texture: 'Stylized stone and gear.',
      camera: 'Isometric co-op view.',
      mood: 'chaotic co-op fun',
      render: 'Authentic co-op dungeon screen.',
      key: 'Gauntlet co-op; four heroes; swarms',
      avoid: ['existing Gauntlet heroes'],
    }),
    ga('SP12-185', 'Alone in the Dark 1992 - Infogrames Polygon Manor', {
      look: 'Infogrames Alone in the Dark (1992) look: flat-shaded polygon characters over hand-drawn manor backgrounds, fixed camera angles and 1920s Lovecraftian dread.',
      subject: 'render people as flat-shaded blocky polygon figures.',
      color: 'Muted manor browns and gloom.',
      light: 'Painted gloom light.',
      texture: 'Flat polygons over painted art.',
      camera: 'Fixed high angle.',
      mood: 'Lovecraftian manor dread',
      render: 'Authentic early-nineties 3D horror screen.',
      key: 'Alone in the Dark polygons; painted manor',
    }),
    ga('SP12-186', 'Thief The Dark Project 1998 - Looking Glass Shadow Stealth', {
      look: 'Looking Glass Studios Thief: The Dark Project (1998) look: first-person stealth in a gothic steampunk city, deep shadows, lanterns and low-poly guards.',
      subject: 'render people as low-poly guards and thieves.',
      color: 'Deep shadow and lantern amber.',
      light: 'Light gem darkness.',
      texture: 'Low-resolution stone and wood.',
      camera: 'First-person shadow view.',
      mood: 'tense sneaky patience',
      render: 'Authentic late-nineties stealth screen.',
      key: 'Thief shadows; lanterns; gothic city',
    }),
    ga('SP12-187', 'Hunt Showdown 2019 - Crytek Bayou Hunt', {
      look: 'Crytek Hunt: Showdown (2019) look: 1895 Louisiana bayou hunting of monsters, fog villages, gritty period weapons and realistic lighting.',
      subject: 'render people as gritty 1895 bounty hunters.',
      color: 'Fog grey, swamp green and lamplight.',
      light: 'Foggy dusk.',
      texture: 'Realistic wood and mud.',
      camera: 'First-person hunting view.',
      mood: 'gritty monster hunt',
      render: 'Authentic hunt shooter screen.',
      key: 'Hunt Showdown bayou; fog; monsters',
    }),
    ga('SP12-188', 'Dungeon Keeper 1997 - Bullfrog Imp Dungeon', {
      look: 'Bullfrog Productions Dungeon Keeper (1997) look: top-down dungeon building, imps digging rock, lava rivers, trap rooms and heroes invading.',
      subject: 'render people as small cartoonish imps and heroes from above.',
      color: 'Lava orange and earth brown.',
      light: 'Lava glow in dungeon dark.',
      texture: 'Chunky late-nineties textures.',
      camera: 'Top-down dungeon view.',
      mood: 'devilishly mischievous building',
      render: 'Authentic late-nineties strategy screen.',
      key: 'Dungeon Keeper imps; lava; traps',
    }),
    ga('SP12-189', 'Grim Dawn 2016 - Crate Gritty Isometric', {
      look: 'Crate Entertainment Grim Dawn (2016) look: gritty Victorian dark fantasy isometric ARPG, necromancers, graveyards, grim ruins and heavy particle effects.',
      subject: 'render people as gritty Victorian dark fantasy heroes.',
      color: 'Muted grey-brown with spell glows.',
      light: 'Grim overcast.',
      texture: 'Gritty isometric detail.',
      camera: 'Isometric ARPG view.',
      mood: 'grim desperate war',
      render: 'Authentic isometric ARPG screen.',
      key: 'Grim Dawn gritty; necromancer; isometric',
    }),
    ga('SP12-190', 'Noita 2020 - Nolla Games Falling-Pixel Physics', {
      look: 'Nolla Games Noita (2020) look: side-view roguelite where every pixel is simulated, burning, flowing and falling, caves of liquid, fire and chaotic spells.',
      subject: 'render people as tiny robed pixel wizards.',
      color: 'Deep cave dark with fire and toxic liquids.',
      light: 'Fire and spell glow.',
      texture: 'Simulated pixel particles.',
      camera: 'Side-view cave view.',
      mood: 'chaotic alchemical danger',
      render: 'Authentic falling-pixel roguelite screen.',
      key: 'Noita pixel physics; fire; liquids',
    }),
    ga('SP12-191', 'Pillars of Eternity II 2018 - Obsidian Painted Deadfire', {
      look: 'Obsidian Entertainment Pillars of Eternity II: Deadfire (2018) look: painted isometric RPG of an archipelago, ship boarding, pirates, ghosts and rich painted scenes.',
      subject: 'render people as small painted isometric pirates and ghosts.',
      color: 'Fog grey, ghost green and sea teal.',
      light: 'Painted fog light.',
      texture: 'Painted isometric scenes.',
      camera: 'Isometric deck view.',
      mood: 'eerie piratical adventure',
      render: 'Authentic painted isometric RPG screen.',
      key: 'Deadfire painted isometric; pirates; ghosts',
    }),
    ga('SP12-192', "Don't Starve 2013 - Klei Gothic Paper Cartoon", {
      look: "Klei Entertainment Don't Starve (2013) look: gothic Tim Burton-like paper cartoon survival, scratchy ink lines, campfire circles, shadow creatures and twisted forests.",
      subject: 'render people as scratchy gothic paper cartoon survivors.',
      color: 'Muted sepia and firelight.',
      light: 'Campfire circle in darkness.',
      texture: 'Scratchy ink and paper.',
      camera: 'Three-quarter overhead view.',
      mood: 'eerie gothic survival',
      render: 'Authentic gothic survival screen.',
      key: "Don't Starve paper; campfire; shadows",
      avoid: ['a gentleman scientist with spiky hair'],
    }),
  ]),
};

export default spec;
