import type { Create, Spec } from '../tools/apply';
import { STYLE_AVOID as AVOID, style } from './_style';

const spec: Spec = {
  pack: 'pack_10',
  category: '1. Geometric Abstraction',
  updates: {
    'SP10-001': {
      dna: style(
        'Analytic-synthetic Cubism: forms broken into faceted planes seen from several viewpoints at once.',
        'the subject is fractured into overlapping angular planes showing front and profile simultaneously, reassembled into a shallow space.',
        'Muted ochre, grey, olive and brown with occasional collage-like color blocks.',
        'Light is flattened into tonal facets rather than a single source.',
        'Faceted planes, overlapping outlines and paint-like brushwork.',
        'Shallow, compressed picture plane with interlocking facets.',
        'Intellectual, restless, fragmented and dense.',
        'Painterly Cubist finish with clear facet edges.',
        'multiple viewpoints; faceted planes; shallow space; muted ochre-grey',
      ),
      avoid: AVOID,
      briefs: [
        "A knight and his warhorse seen from the front, side and above at once shatter into ochre and grey planes as a broken lance cuts across the canvas. No readable text or logo.",
        "An old alchemist's face splinters into the same angular planes as the bottles on his table, so it is hard to tell which one is watching you. No readable text or logo.",
        "A street musician's accordion unfolds across the whole cafe, its bellows, his hands and the chairs sharing the same fractured viewpoints. No readable text or logo.",
      ],
    },
    'SP10-002': {
      dna: style(
        'Bauhaus design: primary shapes, clean grids, sans-serif-era modernism reduced to circle, square and triangle.',
        'the subject is simplified into circles, squares, triangles and bold bars arranged on a clean grid.',
        'Red, yellow, blue, black and off-white.',
        'Flat, shadowless color.',
        'Flat printed color with crisp geometric edges.',
        'Balanced asymmetric grid composition.',
        'Rational, bold, modern and clear.',
        'Crisp poster-like finish.',
        'circle square triangle; primary colors; clean grid; flat shapes',
      ),
      avoid: AVOID,
      briefs: [
        "A mounted knight is reduced to a red circle, a blue triangle and two yellow bars charging across a strict grid on off-white paper. No readable text or logo.",
        "A raven built from black triangles perches on a yellow bar with one red circle for an eye, staring down a lone blue square. No readable text or logo.",
        "A whole seaside village is assembled from a handful of primary squares and one yellow sun, the tide a single long blue bar. No readable text or logo.",
      ],
    },
    'SP10-003': {
      dna: style(
        'Constructivism: dynamic diagonals, bold wedges and graphic propaganda energy without photomontage.',
        'the subject is built from strong diagonal wedges, bars and circles pushing across the frame.',
        'Red, black and cream.',
        'Flat graphic contrast.',
        'Flat printed shapes with crisp edges.',
        'Steep diagonals and radiating wedges.',
        'Urgent, heroic, industrial and forceful.',
        'Bold print-like finish.',
        'dynamic diagonals; red wedges; black bars; cream ground',
      ),
      avoid: AVOID,
      briefs: [
        "A giant red wedge splits a black fortress in two while a tiny rider charges up the diagonal it leaves behind. No readable text or logo.",
        "A blacksmith's hammer and anvil collide as bold black and red wedges slicing across the frame, sparks reduced to small red squares. No readable text or logo.",
        "A lighthouse beam slashes the night as one long red bar, the tower a steep black wedge and the waves stacked grey trapezoids. No readable text or logo.",
      ],
    },
    'SP10-004': {
      dna: style(
        'Op Art: optical illusions of vibrating stripes, warped grids and moiré that make flat patterns seem to move.',
        'the subject is formed by bending black-and-white stripes or grids so it bulges or recedes optically.',
        'Black and white, sometimes one vibrating color pair.',
        'No light; illusion comes from pattern density.',
        'Precise stripes, checks and warped grids.',
        'Pattern fills the frame with the subject as distortion.',
        'Dizzying, hypnotic, precise and kinetic.',
        'Hard-edged precise finish.',
        'warped stripes; bulging grid illusion; black and white; vibration',
      ),
      avoid: AVOID,
      briefs: [
        "A helmet exists only as a bulge swelling out of warped black-and-white stripes, invisible until the eye stops moving. No readable text or logo.",
        "A spiral staircase seen from above becomes concentric stripes that tighten toward the center until the whole image seems to rotate. No readable text or logo.",
        "A coiled snake made from a warped checkerboard swells and pinches along its body, vibrating against a moire background. No readable text or logo.",
      ],
    },
    'SP10-005': {
      name: 'De Stijl Grid',
      dna: style(
        'De Stijl grid: black orthogonal lines dividing white fields with a few primary color blocks.',
        'the subject is abstracted into an asymmetric grid of rectangles, with color blocks placed at its key parts.',
        'White fields, black lines, red, yellow and blue blocks.',
        'Flat, no shadows.',
        'Flat paint with crisp lines.',
        'Asymmetric orthogonal balance.',
        'Calm, pure, ordered and spiritual.',
        'Crisp flat finish.',
        'black orthogonal grid; primary blocks; white fields',
      ),
      avoid: AVOID,
      briefs: [
        "A fortress gate is reduced to black orthogonal lines, a red block for the door and a small yellow block for the guard's torch. No readable text or logo.",
        "A sailboat on open sea becomes white fields divided by black lines, a red hull rectangle and one yellow square sail. No readable text or logo.",
        "A tall chapel window is rebuilt as black lines dividing white panes, with red, yellow and blue rectangles placed off center. No readable text or logo.",
      ],
    },
    'SP10-006': {
      dna: style(
        'Fractal geometry: self-similar recursive forms repeating at every scale.',
        'the subject is built from recursive self-similar branches, spirals or tiles repeating inward.',
        'Deep gradients of blue, violet, gold or fire tones.',
        'Glowing edges on recursive forms.',
        'Infinitely detailed recursive branching.',
        'Central spiral or branching recursion.',
        'Infinite, mesmerizing, mathematical and cosmic.',
        'Crisp high-detail digital finish.',
        'self-similar recursion; infinite branching; glowing gradients',
      ),
      avoid: AVOID,
      briefs: [
        "A winged beast's wings split recursively into smaller winged beasts, spiraling inward in gold and violet forever. No readable text or logo.",
        "A tree's branches split into smaller trees again and again, deep green at the trunk fading to glowing gold at the endless tips. No readable text or logo.",
        "Each chamber of a nautilus spiral holds a smaller nautilus, self-similar curves repeating inward in pearl and rust. No readable text or logo.",
      ],
    },
    'SP10-007': {
      dna: style(
        'Low-poly abstraction: subjects built from flat-shaded triangles with visible facets.',
        'the subject is triangulated into flat-shaded polygons with no smoothing.',
        'Gradient-sampled flat colors across facets.',
        'Facet shading from one soft light.',
        'Flat triangular facets with crisp edges.',
        'Clean centered subject on a simple faceted ground.',
        'Modern, crystalline, clean and graphic.',
        'Crisp flat-shaded finish.',
        'flat-shaded triangles; visible facets; gradient colors',
      ),
      avoid: AVOID,
      briefs: [
        "A wolf howls on a triangulated rock under a faceted pale moon, every surface a flat-shaded triangle in cold blues. No readable text or logo.",
        "A hummingbird hovers at a flower in amber, emerald and violet triangles, its wings a spray of sharp facets. No readable text or logo.",
        "A volcano erupts at sunset in triangular lava facets of orange and red above a flat-shaded sea. No readable text or logo.",
      ],
    },
    'SP10-008': {
      dna: style(
        'Suprematism: floating pure geometric shapes on a white void, weightless and non-objective.',
        'the subject is reduced to a few floating rectangles, circles and crosses drifting on white.',
        'Black, red, yellow, blue on white.',
        'Flat, no light.',
        'Flat painted shapes.',
        'Shapes floating diagonally in empty space.',
        'Spiritual, weightless, pure and radical.',
        'Clean painted finish.',
        'floating geometric shapes; white void; diagonal drift',
      ),
      avoid: AVOID,
      briefs: [
        "A lighthouse drifts apart into a few floating black rectangles and a red circle, weightless on a white void. No readable text or logo.",
        "A falling acrobat becomes three tilted bars and one small black square tumbling through white space along a thin red line. No readable text or logo.",
        "A sailing ship dissolves into floating crosses and trapezoids of black, red and ochre drifting across emptiness. No readable text or logo.",
      ],
    },
    'SP10-009': {
      dna: style(
        'Islamic geometric pattern: star-and-polygon tessellations built from compass and straightedge.',
        'the subject is filled or outlined with interlaced star-and-polygon tessellation.',
        'Lapis blue, turquoise, gold, white and terracotta.',
        'Flat or tile-glaze sheen.',
        'Interlaced strapwork, stars and rosettes.',
        'Radial symmetric tessellation.',
        'Harmonious, infinite, sacred and precise.',
        'Precise, crisp geometric finish.',
        'star-and-polygon tessellation; interlaced strapwork; radial symmetry',
      ),
      avoid: [...AVOID, 'religious text'],
      briefs: [
        "A falcon's feathers are interlaced star tessellations in lapis and gold, its eye a single twelve-point rosette. No readable text or logo.",
        "Seen from below, a dome interior radiates star-and-polygon rosettes from one central star in turquoise, cobalt and gold. No readable text or logo.",
        "The silhouette of a horse is filled with turquoise and white interlaced stars against a deep blue field of smaller polygons. No readable text or logo.",
      ],
    },
    'SP10-010': {
      dna: style(
        'Voronoi: space divided into irregular cells around seed points, like cracked earth or cells.',
        'the subject is divided into Voronoi cells that follow its form, with thicker cell walls at contours.',
        'Organic gradient colors per cell.',
        'Soft shading inside each cell.',
        'Irregular cells with clean borders.',
        'Cellular fill across subject and ground.',
        'Organic, cellular, scientific and modern.',
        'Clean generative finish.',
        'Voronoi cells; seed points; cellular borders',
      ),
      avoid: AVOID,
      briefs: [
        "A beast's skull is built from irregular cells whose thickened borders trace every ridge and socket. No readable text or logo.",
        "A lone traveler walks across a desert of cracked earth divided into irregular terracotta cells around unseen seeds. No readable text or logo.",
        "Each scute of a turtle's shell is a cell around its own seed point, deep green borders around amber interiors on dark sand. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Orphism Color Discs',
      domain: 'orphist color disc abstraction',
      tags: ['orphism', 'color-discs', 'geometric'],
      dna: style(
        'Orphism: rhythmic concentric color discs and arcs that pulse with simultaneous contrast.',
        'the subject emerges from overlapping concentric color discs and arcs.',
        'Saturated contrasting color rings.',
        'Light is color contrast itself.',
        'Painted concentric rings and arcs.',
        'Circular rhythms around the subject.',
        'Joyful, rhythmic, luminous and musical.',
        'Painterly flat finish.',
        'concentric color discs; simultaneous contrast; rhythmic arcs',
      ),
      avoid: AVOID,
      briefs: [
        "Riders and horses on a carousel dissolve into rhythmic concentric discs, orange against blue pulsing with simultaneous contrast. No readable text or logo.",
        "A sun rising over a harbor becomes overlapping rings and arcs, the orange and violet bands vibrating against each other. No readable text or logo.",
        "A spinning dancer's body is built from interlocking arcs of yellow, magenta and cobalt that echo outward across the canvas. No readable text or logo.",
      ],
    },
    {
      name: 'Futurist Force Lines',
      domain: 'futurist dynamism',
      tags: ['futurism', 'force-lines', 'geometric'],
      dna: style(
        'Futurist dynamism: repeated overlapping forms and force lines expressing speed and motion.',
        'the subject is repeated in successive overlapping positions with sharp force lines.',
        'Bright reds, blues and metallic greys.',
        'Dynamic light fragments.',
        'Repeated contours, force lines and fragmented planes.',
        'Diagonal motion across the frame.',
        'Fast, violent, mechanical and exhilarating.',
        'Energetic painted finish.',
        'repeated motion contours; force lines; diagonal speed',
      ),
      avoid: AVOID,
      briefs: [
        "A cavalry charge repeats in overlapping positions as sharp lines of force fuse horses and riders into one onrushing wave. No readable text or logo.",
        "A steam train bursts across a bridge in overlapping positions, smoke and rails fractured by angular lines of speed. No readable text or logo.",
        "A fencer's lunge repeats arm and blade in overlapping positions, force lines slicing the space into red and grey planes. No readable text or logo.",
      ],
    },
    {
      name: 'Hard-Edge Painting',
      domain: 'hard-edge color field',
      tags: ['hard-edge', 'color-field', 'geometric'],
      dna: style(
        'Hard-edge painting: large flat color areas meeting at razor-sharp edges.',
        'the subject is simplified into a few large flat color shapes with crisp edges.',
        'Bold flat complementary colors.',
        'No shading.',
        'Flat opaque paint with razor edges.',
        'Large simple shapes filling the frame.',
        'Bold, calm, confident and modern.',
        'Clean flat finish.',
        'razor-sharp edges; flat color areas; bold simplicity',
      ),
      avoid: AVOID,
      briefs: [
        "A lone rider is one flat orange shape against a teal field under a white disc moon, every edge razor sharp. No readable text or logo.",
        "A lighthouse and setting sun become flat red, cream and navy areas meeting at razor edges above one white band of sea. No readable text or logo.",
        "A crow on a bare branch is a single flat black shape against pale mint, with a lemon-yellow sun and no gradients anywhere. No readable text or logo.",
      ],
    },
    {
      name: 'Precisionism',
      domain: 'precisionist industrial geometry',
      tags: ['precisionism', 'industrial', 'geometric'],
      dna: style(
        'Precisionism: clean, sharp-edged geometric rendering of structures with smooth planes and crisp shadows.',
        'the subject is rendered as clean geometric volumes with smooth planes and precise shadows.',
        'Cool greys, soft blues and cream with sharp shadow shapes.',
        'Crisp directional sun with geometric shadows.',
        'Smooth painted planes without texture.',
        'Frontal or low-angle structural view.',
        'Calm, orderly, monumental and quiet.',
        'Precise smooth finish.',
        'smooth geometric planes; crisp shadows; industrial order',
      ),
      avoid: AVOID,
      briefs: [
        "A river mill and its water tower become smooth geometric volumes with crisp shadows under a hard noon sun. No readable text or logo.",
        "A windmill and grain silos stand as clean cylinders and cones casting crisp shadows across a cloudless pale sky. No readable text or logo.",
        "A cathedral's flying buttresses are reduced to clean smooth planes of grey stone with knife-sharp shadows. No readable text or logo.",
      ],
    },
    {
      name: 'Vorticism',
      domain: 'vorticist angular abstraction',
      tags: ['vorticism', 'angular', 'geometric'],
      dna: style(
        'Vorticism: hard angular machine-like forms spiraling into a vortex center.',
        'the subject is broken into hard angular shards converging into a vortex.',
        'Strong blacks, reds and ochres.',
        'Harsh contrast.',
        'Sharp angular shards.',
        'Vortex converging to a point.',
        'Aggressive, mechanical, energetic and harsh.',
        'Bold graphic finish.',
        'angular shards; vortex center; machine energy',
      ),
      avoid: AVOID,
      briefs: [
        "A ship caught in a storm is compressed into hard angular shards spiraling toward a vortex center in black, ochre and electric blue. No readable text or logo.",
        "A lighthouse beam spirals into angular shards around a vortex, machine-like planes in black, white and acid yellow. No readable text or logo.",
        "A crowd at a factory gate is pulled into jagged spiraling planes, angular figures sucked toward the vortex. No readable text or logo.",
      ],
    },
    {
      name: 'Truchet Tile Weave',
      domain: 'truchet tile patterns',
      tags: ['truchet', 'tiling', 'geometric'],
      dna: style(
        'Truchet tiling: square tiles with quarter-circle or diagonal motifs that combine into flowing mazes.',
        'the subject emerges from a field of rotated Truchet tiles whose curves form its outline.',
        'Two- or three-color schemes.',
        'Flat, no shading.',
        'Tiled quarter-circle arcs.',
        'Grid of tiles filling the frame.',
        'Playful, maze-like, rhythmic and clever.',
        'Crisp graphic finish.',
        'Truchet quarter-circle tiles; emergent curves; grid',
      ),
      avoid: AVOID,
      briefs: [
        "A serpent's body emerges from rotated quarter-circle tiles, a flowing maze of black and cream arcs forming its coils. No readable text or logo.",
        "An owl's outline appears out of rotated tiles, black and gold arcs flowing into its eyes and folded wings. No readable text or logo.",
        "An ocean wave is built from diagonal and quarter-circle tiles, navy and white arcs flowing into a curling crest. No readable text or logo.",
      ],
    },
    {
      name: 'Penrose Aperiodic Tiling',
      domain: 'aperiodic tiling',
      tags: ['penrose', 'aperiodic', 'geometric'],
      dna: style(
        'Penrose tiling: aperiodic kite-and-dart or rhombus tiling with five-fold symmetry.',
        'the subject is filled and outlined with aperiodic rhombus tiles.',
        'Two-tone or jewel palette per tile type.',
        'Flat or subtle tile sheen.',
        'Rhombus tiles with fine grout lines.',
        'Five-fold radial tiling.',
        'Mathematical, mysterious, ordered and unusual.',
        'Crisp precise finish.',
        'aperiodic rhombus tiling; five-fold symmetry',
      ),
      avoid: AVOID,
      briefs: [
        "A star-shaped rose window radiates kite-and-dart tiles with five-fold symmetry in ruby, amber and cobalt glass tones. No readable text or logo.",
        "An egg shape is filled with aperiodic rhombus tiles in pale blue and gold, five-fold stars appearing across its curve. No readable text or logo.",
        "A courtyard floor seen from above never quite repeats, kite-and-dart tiles in terracotta and cream circling a fountain. No readable text or logo.",
      ],
    },
    {
      name: 'Swiss Grid Composition',
      domain: 'Swiss grid design',
      tags: ['swiss-grid', 'modernism', 'geometric'],
      dna: style(
        'Swiss grid composition: strict modular grid, asymmetric layout, bold geometric image blocks without type.',
        'the subject is placed in a strict modular grid of image blocks and color fields.',
        'Red, black, white and one accent.',
        'Flat or photographic within blocks.',
        'Clean blocks with precise alignment.',
        'Asymmetric modular grid.',
        'Rational, clean, confident and modern.',
        'Crisp print finish.',
        'modular grid; asymmetric blocks; no type',
      ),
      avoid: AVOID,
      briefs: [
        "A cyclist is cropped into image blocks of wheel, hand and shoe arranged asymmetrically on a strict red and white modular grid. No readable text or logo.",
        "A mountain railway becomes cropped blocks of tunnel, bridge and peak on a strict black and white grid. No readable text or logo.",
        "A single human eye is cropped into three blocks of different scales, with one red rectangle as the only color. No readable text or logo.",
      ],
    },
    {
      name: 'String Art Geometry',
      domain: 'string art line geometry',
      tags: ['string-art', 'line-geometry', 'geometric'],
      dna: style(
        'String art: taut straight threads between pins forming curves by envelope.',
        'the subject is drawn by taut threads stretched between pins, curves emerging from straight lines.',
        'Bright thread colors on dark board.',
        'Soft light on threads.',
        'Taut threads, pins and board.',
        'Pinned outline with thread envelopes.',
        'Precise, handmade, delicate and mathematical.',
        'Crisp thread finish.',
        'taut threads; pin outlines; curve envelopes',
      ),
      avoid: AVOID,
      briefs: [
        "A coiled dragon is drawn by gold threads stretched between brass pins on a black board, curves formed by straight envelopes. No readable text or logo.",
        "A tall sailing ship crossing a navy board has sails made of fanned straight white threads, every curve built from taut lines between brass pins. No readable text or logo.",
        "A howling wolf beneath a full moon is strung in silver threads whose straight lines bend into curves on a charcoal board. No readable text or logo.",
      ],
    },
    {
      name: 'Neo-Geo Minimalism',
      domain: 'neo-geo minimal geometry',
      tags: ['neo-geo', 'minimal', 'geometric'],
      dna: style(
        'Neo-geo minimalism: cool, slick geometric forms with fluorescent accents and industrial surfaces.',
        'the subject is reduced to slick geometric cells, bars and conduits.',
        'Fluorescent accents on grey and white.',
        'Clean flat light.',
        'Smooth industrial surfaces.',
        'Grid-based cells.',
        'Cool, detached, slick and ironic.',
        'Clean finish.',
        'geometric cells; fluorescent accents; industrial slick',
      ),
      avoid: AVOID,
      briefs: [
        "A city block is reduced to grey cells connected by fluorescent orange conduits, slick industrial surfaces in cool order. No readable text or logo.",
        "A transit network becomes grey cells and conduits with one fluorescent pink line pulsing through the grid. No readable text or logo.",
        "A stack of cool grey boxes with fluorescent yellow edges rises like shipping containers on a slick industrial surface. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
