import type { Create, Spec } from '../tools/apply';
import { CRAFT_AVOID as AVOID, craft } from './_craft';

// Toys & crafts: each preset is one construction method. Brand names are replaced by generic
// descriptions; collectible proportion changes are stated in the preset that uses them.
const spec: Spec = {
  pack: 'pack_11',
  category: '1. Toys And Crafts',
  updates: {
    'SP11-001': {
      name: 'Interlocking Brick Build',
      dna: craft(
        'Interlocking brick build: the subject assembled from studded plastic building bricks.',
        'built from studded interlocking plastic bricks with visible studs, stepped curves and right-angle blocks.',
        'Primary brick colors: red, yellow, blue, grey, black.',
        'Bright studio light with plastic highlights.',
        'Glossy ABS bricks with studs and seams.',
        'Playful, constructive, nostalgic and bright.',
        'studded bricks; stepped curves; plastic gloss',
      ),
      avoid: AVOID,
      briefs: [
        'Tabletop photograph of a brick-built dragon coiled around a brick castle tower, studs and stepped curves visible. No logos or text.',
        'Brick-built knight on horseback. No logos or text.',
        'Brick-built pirate ship in a storm of blue bricks. No logos or text.',
      ],
    },
    'SP11-002': {
      name: 'Big-Head Vinyl Collectible',
      dna: craft(
        'Big-head vinyl collectible: stylized figure with oversized square head, small body and blank black eyes.',
        'a vinyl figure with a huge head, tiny body and simplified features — a deliberate proportion change.',
        'Flat matte vinyl colors.',
        'Soft studio light.',
        'Matte vinyl with seam lines.',
        'Cute, collectible, simple and playful.',
        'oversized head; small body; blank eyes; matte vinyl',
      ),
      avoid: AVOID,
      briefs: [
        'Studio photograph of a big-head vinyl collectible of an original plague doctor with blank black eyes, on a shelf. No logos or text.',
        'Big-head vinyl dragon knight. No logos or text.',
        'Big-head vinyl witch with a cat. No logos or text.',
      ],
    },
    'SP11-003': {
      name: 'Modeling Dough Clay',
      dna: craft(
        'Modeling dough: soft bright dough rolled and pinched with fingerprints and cracks.',
        'hand-rolled soft modeling dough with fingerprints, pinched edges and small drying cracks.',
        'Bright dough colors.',
        'Soft diffuse light.',
        'Soft dough with fingerprints and cracks.',
        'Playful, childlike, soft and handmade.',
        'soft dough; fingerprints; drying cracks',
      ),
      avoid: AVOID,
      briefs: [
        'Tabletop photograph of a modeling-dough dragon with fingerprints and pinched wings. No logos or text.',
        'Modeling-dough knight. No logos or text.',
        'Modeling-dough castle. No logos or text.',
      ],
    },
    'SP11-004': {
      dna: craft(
        'Papercraft low poly: folded paper model with flat faceted panels and glue tabs.',
        'folded paper facets with crisp creases and visible glue tabs.',
        'Printed flat paper colors.',
        'Soft side light showing facets.',
        'Paper facets, creases and tabs.',
        'Crafted, geometric, charming and light.',
        'folded paper facets; glue tabs',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a low-poly papercraft wolf with visible folds and glue tabs on a desk. No text or logo.',
        'Papercraft knight. No text or logo.',
        'Papercraft castle. No text or logo.',
      ],
    },
    'SP11-005': {
      dna: craft(
        'Amigurumi crochet: small crocheted stuffed figures with single-crochet stitches and safety eyes.',
        'crocheted in tight spiral stitches, stuffed, with safety eyes and sewn-on parts.',
        'Soft yarn colors.',
        'Soft natural light.',
        'Crochet stitches and yarn fuzz.',
        'Cute, cozy, handmade and gentle.',
        'crochet stitches; safety eyes; stuffed',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an amigurumi crocheted dragon with safety eyes sitting on a teacup. No text or logo.',
        'Amigurumi knight. No text or logo.',
        'Amigurumi witch. No text or logo.',
      ],
    },
    'SP11-016': {
      dna: craft(
        'Plushie: soft stuffed toy with fleece or minky fabric, seams and embroidered features.',
        'sewn from soft minky fabric panels, stuffed, with embroidered eyes and visible seams.',
        'Soft pastel or bright fabric.',
        'Soft light.',
        'Minky fleece, seams and embroidery.',
        'Cuddly, comforting, sweet and soft.',
        'minky fabric; seams; embroidered eyes',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a plush dragon with embroidered eyes and floppy wings on a bed. No text or logo.',
        'Plush knight. No text or logo.',
        'Plush grim reaper holding a felt scythe. No text or logo.',
      ],
    },
    'SP11-017': {
      dna: craft(
        '90s action figure: hard plastic figure with visible joints, sculpted muscles and painted details.',
        'molded plastic with swivel joints at shoulders, hips and knees, sculpted detail and simple paint.',
        'Bold toy colors.',
        'Studio light with plastic sheen.',
        'Molded plastic, joints and paint apps.',
        'Heroic, nostalgic, toyetic and bold.',
        'swivel joints; sculpted plastic; paint apps',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a 90s-style action figure of an original barbarian with visible swivel joints on a rock diorama. No logos or text.',
        'Action figure dragon rider. No logos or text.',
        'Action figure skeleton king. No logos or text.',
      ],
    },
    'SP11-018': {
      dna: craft(
        'Balloon art: the subject twisted from long modeling balloons.',
        'twisted from inflated modeling balloons with visible twists and knots.',
        'Glossy balloon colors.',
        'Bright light with glossy highlights.',
        'Latex balloons with twists.',
        'Playful, festive, silly and bright.',
        'twisted balloons; glossy latex',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a balloon-art dragon with twisted wings. No text or logo.',
        'Balloon-art knight on horse. No text or logo.',
        'Balloon-art castle. No text or logo.',
      ],
    },
    'SP11-020': {
      dna: craft(
        'Wooden toy: turned and carved wood toy with rounded shapes and simple paint.',
        'turned and carved wood parts, dowels and pegs, with simple painted details.',
        'Natural wood with primary paint.',
        'Warm soft light.',
        'Wood grain, dowels and paint.',
        'Wholesome, classic, warm and simple.',
        'turned wood; dowels; simple paint',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a wooden pull-along dragon toy with painted wheels. No text or logo.',
        'Wooden knight toy. No text or logo.',
        'Wooden castle toy. No text or logo.',
      ],
    },
    'SP11-021': {
      dna: craft(
        'Sticker art: die-cut vinyl sticker with thick white border and glossy print.',
        'printed as a die-cut vinyl sticker with a thick white border.',
        'Bold flat colors with white border.',
        'Glossy light on vinyl.',
        'Glossy vinyl and white border.',
        'Playful, bold, graphic and collectible.',
        'die-cut sticker; white border; glossy',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a glossy die-cut sticker of a grumpy dragon stuck on a wooden desk. No text or logo.',
        'Sticker of a knight. No text or logo.',
        'Sticker of a witch cat. No text or logo.',
      ],
    },
    'SP11-022': {
      dna: craft(
        'Clay stop-motion comedy: plasticine characters with big grins and fingerprinted surfaces on a miniature set.',
        'plasticine puppets with wide mouths, bulging eyes and fingerprints on a miniature set.',
        'Saturated plasticine colors.',
        'Warm miniature-set lighting.',
        'Plasticine with fingerprints.',
        'Comic, warm, silly and handmade.',
        'plasticine puppets; wide grins; fingerprints',
      ),
      avoid: AVOID,
      briefs: [
        'Stop-motion still of an original plasticine knight grinning nervously at a tiny dragon on a miniature set. No logos or text.',
        'Plasticine witch. No logos or text.',
        'Plasticine castle feast. No logos or text.',
      ],
    },
    'SP11-023': {
      dna: craft(
        'Tin toy: lithographed tin-plate toy with wind-up key and tabs.',
        'lithographed tin plate folded with tabs, with a wind-up key.',
        'Bright printed lithograph colors.',
        'Studio light on metal.',
        'Tin plate, tabs and printed detail.',
        'Vintage, charming, mechanical and nostalgic.',
        'lithographed tin; tabs; wind-up key',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a wind-up tin toy dragon with lithographed scales and a key. No text or logo.',
        'Tin toy knight. No text or logo.',
        'Tin toy castle carousel. No text or logo.',
      ],
    },
    'SP11-024': {
      dna: craft(
        'Diorama box: a miniature scene built inside an open box with layered depth.',
        'built as a miniature scene inside a shadow box with layered cut-outs and props.',
        'Warm crafted colors.',
        'Soft light from above.',
        'Paper, wood and miniature props.',
        'Intimate, charming, crafted and deep.',
        'shadow box; layered miniature scene',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a shadow-box diorama of a dragon sleeping on treasure inside a wooden box. No text or logo.',
        'Diorama knight camp. No text or logo.',
        'Diorama witch cottage. No text or logo.',
      ],
    },
    'SP11-025': {
      dna: craft(
        'Button-eye doll: stitched cloth doll with button eyes and yarn hair.',
        'sewn cloth doll with button eyes, yarn hair and visible stitches.',
        'Muted fabric colors.',
        'Soft window light.',
        'Cloth, buttons and stitches.',
        'Eerie, handmade, sweet and uncanny.',
        'button eyes; stitched cloth; yarn hair',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a button-eyed cloth doll of an original witch sitting on a windowsill. No text or logo.',
        'Button-eye knight doll. No text or logo.',
        'Button-eye dragon doll. No text or logo.',
      ],
    },
    'SP11-027': {
      dna: craft(
        'Craft mosaic tile: small ceramic craft tiles glued onto a form.',
        'covered in small hand-cut ceramic tiles with grout.',
        'Bright glazed tile colors.',
        'Soft light.',
        'Glazed tiles and grout.',
        'Crafty, cheerful, handmade and bright.',
        'craft mosaic tiles; grout',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a mosaic-tiled garden dragon sculpture. No text or logo.',
        'Mosaic-tiled knight statue. No text or logo.',
        'Mosaic-tiled birdbath. No text or logo.',
      ],
    },
    'SP11-029': {
      dna: craft(
        'Embroidery: the subject stitched in thread on fabric in a hoop.',
        'embroidered with satin, stem and French-knot stitches on linen in a hoop.',
        'Thread colors on linen.',
        'Soft light.',
        'Satin stitches, knots and linen weave.',
        'Delicate, handmade, patient and cozy.',
        'embroidery stitches; hoop; linen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an embroidery hoop with a stitched dragon and castle in satin and stem stitches. No text or logo.',
        'Embroidered knight. No text or logo.',
        'Embroidered moth. No text or logo.',
      ],
    },
    'SP11-030': {
      dna: craft(
        'Sand art: colored sand layered in a glass bottle into patterns and scenes.',
        'layered colored sand forming the subject inside a glass bottle or frame.',
        'Layered colored sands.',
        'Backlit glass.',
        'Sand grains and glass.',
        'Patient, fragile, colorful and calm.',
        'layered colored sand; glass',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a glass bottle with layered colored sand forming a desert dragon. No text or logo.',
        'Sand art knight. No text or logo.',
        'Sand art castle sunset. No text or logo.',
      ],
    },
    'SP11-031': {
      dna: craft(
        'Ice carving: the subject carved from clear ice with chisel marks.',
        'carved from a clear ice block with chisel marks and frosty edges.',
        'Clear ice with blue tints.',
        'Colored backlight through ice.',
        'Clear ice, chisel marks and frost.',
        'Cold, elegant, fleeting and luminous.',
        'carved clear ice; chisel marks',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an ice-carved dragon at a winter festival lit blue from below. No text or logo.',
        'Ice-carved knight. No text or logo.',
        'Ice-carved swan. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Paper Theater Puppets',
      domain: 'toy paper theater',
      tags: ['paper-theater', 'puppets', 'craft'],
      dna: craft(
        'Paper theater: flat printed cardboard figures on sticks in a miniature stage with layered wings.',
        'flat printed cardboard cut-outs on sticks set in a toy stage with layered scenery.',
        'Victorian printed colors.',
        'Warm footlight glow.',
        'Printed card, cut edges and sticks.',
        'Theatrical, nostalgic, charming and quaint.',
        'flat card cut-outs; toy stage; layered wings',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a toy paper theater staging a knight fighting a dragon with flat printed cardboard cut-outs on sticks. No text or logo.',
        'Paper theater witch scene. No text or logo.',
        'Paper theater ship. No text or logo.',
      ],
    },
    {
      name: 'Resin Garage Kit',
      domain: 'hand-painted resin kit',
      tags: ['resin-kit', 'model', 'craft'],
      dna: craft(
        'Resin garage kit: hand-painted resin model on a sculpted base with fine brushwork.',
        'a cast resin model assembled and hand-painted with washes and drybrush on a sculpted base.',
        'Hand-painted model colors with washes.',
        'Studio light.',
        'Resin with brushwork, washes and base.',
        'Crafted, detailed, collectible and dramatic.',
        'hand-painted resin; washes; sculpted base',
      ),
      avoid: AVOID,
      briefs: [
        'Studio photograph of a hand-painted resin model of an original dragon knight on a sculpted rocky base. No text or logo.',
        'Resin kit witch. No text or logo.',
        'Resin kit sea monster. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
