import type { Spec } from '../tools/apply';
import { ga, keep } from './_authors';

// Video game pass, sieges, warfronts and last stands: each preset names its game, studio and
// year and states the real render technique and camera. Briefs that restaged a game's own
// heroes or units (the four colored knights, the horned giants, the lane armies) are replaced.
const spec: Spec = {
  pack: 'pack_12',
  category: '4. Sieges, Warfronts & Last Stands',
  updates: Object.fromEntries([
    ga('SP12-007', 'The Banner Saga 2014 - Stoic Hand-Painted Saga', {
      look: 'Stoic The Banner Saga (2014) look: hand-animated 2D in the Eyvind Earle and Sleeping Beauty tradition, flat painted Norse landscapes, caravans on snow and turn-based tactical grids.',
      subject:
        'render people as hand-animated Norse figures with clean flat shapes, fur, braids and weathered armor.',
      color: 'Muted snow blue, birch white, ochre and deep red banners.',
      light: 'Soft flat painted light with pale winter skies.',
      texture: 'Hand-painted flat backgrounds and clean hand-drawn animation lines.',
      camera: 'Side tactical grid view or wide caravan landscape.',
      mood: 'weary stoic endurance',
      render: 'Authentic hand-animated tactical RPG screen.',
      key: 'Banner Saga Eyvind Earle painting; caravans; tactical grid',
      avoid: ['horned giant warriors', 'stone-armored invaders of the source game'],
      briefs: [
        'Holding a frozen bridge on a hand-painted tactical grid, an original band of towering bearded shieldbearers and archers faces a column of bark-armored raiders marching out of a snowstorm. No readable text or logo.',
        'On a painted snowy battlefield, a towering bearded warrior waits for his turn while a tiny archer spends forever deciding where to move. No readable text or logo.',
        keep('SP12-007')[2],
      ],
    }),
    ga('SP12-009', 'Castle Crashers 2008 - The Behemoth Cartoon Brawl', {
      look: 'The Behemoth Castle Crashers (2008) look: Dan Paladin thick-outline 2D cartoon, round-headed characters with simple faces, bright flat colors and side-scrolling co-op brawling.',
      subject:
        'render people as round-headed thick-outline cartoon figures with tiny dot eyes and chunky gear.',
      color: 'Bright flat grass green, sky blue and primary colors.',
      light: 'Flat cartoon light with no gradients.',
      texture: 'Thick outlines and flat vector fills.',
      camera: 'Side-scrolling brawler view.',
      mood: 'silly co-op mayhem',
      render: 'Authentic cartoon brawler screen.',
      key: 'Castle Crashers thick outlines; round heads; co-op brawl',
      avoid: ['four knights in red, green, blue and orange armor', 'animal orb companions'],
      briefs: [
        'Storming a cartoon castle in thick outlines, four original rescuers, a baker, a beekeeper, a lumberjack and a nun, bash through a gate as a giant barbarian chief throws a battering ram at them. No readable text or logo.',
        'In a thick-outlined cartoon siege, a beekeeper triumphantly rescues a princess, who immediately rescues his pet owl from a tree. No readable text or logo.',
        keep('SP12-009')[2],
      ],
    }),
    ga('SP12-026', 'Tactics Ogre 1995 - Quest Isometric Sprite Tactics', {
      look: 'Quest Tactics Ogre: Let Us Cling Together (1995) look: isometric tactical RPG with Akihiko Yoshida character designs as small detailed sprites on tiered tile maps of ruins and highlands.',
      subject: 'render people as small detailed isometric sprites with Yoshida-style proportions.',
      color: 'Muted earth, vine green and faded medieval blue.',
      light: 'Soft even 16-bit light on tiered tiles.',
      texture: 'Detailed 16-bit sprites and textured tiles.',
      camera: 'Isometric view over tiered tile maps.',
      mood: 'grave political war',
      render: 'Authentic 16-bit isometric tactics screen.',
      key: 'Tactics Ogre isometric; Yoshida sprites; tiered ruins',
    }),
    ga('SP12-035', 'Monster Train 2020 - Shiny Shoe Infernal Floors', {
      look: 'Shiny Shoe Monster Train (2020) look: roguelike deckbuilder on a hellish train with three stacked floors plus the burning pyre, cartoon demon units and flame-orange card effects.',
      subject:
        'render every subject as cartoon demon units and cards battling on stacked train floors.',
      color: 'Infernal orange, ember red and deep purple.',
      light: 'Pyre fire glow and card flashes.',
      texture: 'Clean stylized cartoon 3D and card frames.',
      camera: 'Side view of stacked train floors.',
      mood: 'fiery strategic chaos',
      render: 'Authentic deckbuilder screen.',
      key: 'Monster Train stacked floors; pyre; demon cards',
    }),
    ga('SP12-038', 'World of Warships 2015 - Wargaming Naval Broadside', {
      look: 'Wargaming World of Warships (2015) look: realistic naval combat with detailed WWII-style battleships, shell tracers arcing across open ocean, smoke screens and third-person ship camera.',
      subject: 'render vessels as detailed realistic warships seen from a third-person camera.',
      color: 'Steel grey, ocean blue and tracer orange.',
      light: 'Stormy daylight with muzzle flashes.',
      texture: 'Realistic hulls, water spray and smoke.',
      camera: 'Third-person naval camera.',
      mood: 'thunderous naval clash',
      render: 'Authentic naval combat screen.',
      key: 'World of Warships broadside; tracers; naval camera',
    }),
    ga('SP12-052', 'Overwatch 2016 - Blizzard Hero Payload', {
      look: 'Blizzard Overwatch (2016) look: bright animated-film stylized 3D, chunky readable hero silhouettes, colorful near-future maps and payload escort objectives.',
      subject:
        'render people as colorful animated-film heroes with exaggerated readable silhouettes.',
      color: 'Bright optimistic orange, teal and sunny whites.',
      light: 'Warm clean daylight with soft bounce.',
      texture: 'Stylized painted PBR surfaces.',
      camera: 'First-person view with a stylized weapon.',
      mood: 'hopeful team heroics',
      render: 'Authentic hero shooter screen.',
      key: 'Overwatch animated-film heroes; payload; bright maps',
      avoid: ['existing Overwatch heroes'],
    }),
    ga('SP12-060', 'Blasphemous 2019 - The Game Kitchen Pixel Penance', {
      look: 'The Game Kitchen Blasphemous (2019) look: dark detailed pixel art metroidvania steeped in Andalusian Holy Week imagery, baroque basilicas, grotesque religious enemies and penitent suffering.',
      subject:
        'render people as detailed dark pixel sprites in religious robes, thorns and baroque armor.',
      color: 'Bone white, dried blood red, candle gold and black stone.',
      light: 'Candle halos and stained-glass shafts in deep shadow.',
      texture: 'Dense detailed pixel art with baroque ornament.',
      camera: 'Side-view metroidvania frame.',
      mood: 'penitent grotesque solemnity',
      render: 'Authentic dark pixel metroidvania screen.',
      key: 'Blasphemous pixels; Holy Week; baroque grotesque',
      avoid: ['a penitent in a tall spiked capirote helm'],
    }),
    ga('SP12-064', 'They Are Billions 2019 - Numantian Steampunk Horde', {
      look: 'Numantian Games They Are Billions (2019) look: isometric steampunk colony defense with painted 2D units, wooden walls, turrets and hordes of thousands pouring out of the fog.',
      subject:
        'render people as tiny painted steampunk soldiers and colonists facing massive hordes.',
      color: 'Steampunk brass, fog grey and night blue.',
      light: 'Night fog with turret flashes.',
      texture: 'Detailed painted isometric 2D.',
      camera: 'Isometric strategy view.',
      mood: 'desperate horde defense',
      render: 'Authentic isometric RTS screen.',
      key: 'They Are Billions hordes; steampunk walls; isometric',
    }),
    ga('SP12-076', 'Northgard 2018 - Shiro Norse Isometric Clans', {
      look: 'Shiro Games Northgard (2018) look: stylized isometric Norse settlement strategy, cartoonish chunky villagers, snowy tiles, aurora skies and mythical creatures.',
      subject: 'render people as chunky stylized Norse villagers and warriors.',
      color: 'Snow white, aurora green and warm hearth orange.',
      light: 'Soft winter light and aurora glow.',
      texture: 'Stylized painted low-poly surfaces.',
      camera: 'Isometric strategy view.',
      mood: 'hardy clan survival',
      render: 'Authentic stylized strategy screen.',
      key: 'Northgard isometric; Norse clans; aurora',
    }),
    ga('SP12-079', 'Helldivers 2 2024 - Arrowhead Orbital Drop', {
      look: 'Arrowhead Game Studios Helldivers 2 (2024) look: third-person co-op shooter with satirical military propaganda tone, orbital drops, strategems beams, alien bug swarms and fiery skies.',
      subject: 'render people as armored troopers in heavy helmets and capes.',
      color: 'Fire orange, alien acid and military yellow.',
      light: 'Burning skies and bright orbital strikes.',
      texture: 'Gritty armor, dust and explosions.',
      camera: 'Third-person over-the-shoulder view.',
      mood: 'chaotic satirical heroism',
      render: 'Authentic modern co-op shooter screen.',
      key: 'Helldivers orbital drop; bug swarm; beacons',
      avoid: ['existing Helldiver armor and insignia'],
    }),
    ga('SP12-129', 'Orcs Must Die 2011 - Robot Entertainment Trap Defense', {
      look: 'Robot Entertainment Orcs Must Die! (2011) look: comic stylized third-person trap defense, cartoon orc and goblin hordes, fortress corridors, traps and exaggerated effects.',
      subject: 'render people as comic stylized cartoon defenders facing cartoon hordes.',
      color: 'Warm torch orange, stone grey and goblin green.',
      light: 'Torch light and trap flashes.',
      texture: 'Stylized painted 3D surfaces.',
      camera: 'Third-person view behind the defender.',
      mood: 'gleeful horde defense',
      render: 'Authentic stylized trap-defense screen.',
      key: 'Orcs Must Die hordes; trap defense; comic stylized',
    }),
    ga('SP12-130', 'Battlefield 1 2016 - DICE Great War Trenches', {
      look: 'DICE Battlefield 1 (2016) look: first-person Great War trenches, mud, barbed wire, early tanks, smoke, sepia-tinted skies and cinematic Frostbite lighting.',
      subject: 'render people as Great War soldiers in wool uniforms, helmets and gas masks.',
      color: 'Mud brown, smoke grey and sepia sky.',
      light: 'Cinematic haze and flare glow.',
      texture: 'Mud, wire, wood and wool.',
      camera: 'First-person view over a trench lip.',
      mood: 'harrowing wartime dread',
      render: 'Authentic Frostbite first-person war screen.',
      key: 'Battlefield 1 trenches; mud; smoke; war machines',
    }),
    ga('SP12-131', 'Chivalry 2 2021 - Torn Banner Siege Crew', {
      look: 'Torn Banner Studios Chivalry 2 (2021) look: chaotic medieval siege battles, catapults and trebuchets, burning castles, shouting crews and bright banners.',
      subject: 'render people as grubby medieval soldiers and siege crews in padded jackets.',
      color: 'Banner red, siege fire orange and stone grey.',
      light: 'Bright day with fire glow.',
      texture: 'Mud, wood, leather and smoke.',
      camera: 'First-person view behind siege engines.',
      mood: 'rowdy medieval chaos',
      render: 'Authentic medieval melee screen.',
      key: 'Chivalry 2 siege; catapults; burning castles',
    }),
    ga('SP12-132', 'Battle for Wesnoth 2005 - Wesnoth Painted Hex', {
      look: 'Battle for Wesnoth (2005) look: turn-based fantasy strategy on painted hex maps, small painted unit sprites, rivers, castles and mountain hexes.',
      subject: 'render people as small painted fantasy unit sprites standing on hexes.',
      color: 'Painted greens, river blue and parchment.',
      light: 'Even top light on painted terrain.',
      texture: 'Painted hex tiles and sprite detail.',
      camera: 'Top-down hex map view.',
      mood: 'thoughtful tactical campaign',
      render: 'Authentic painted hex strategy screen.',
      key: 'Wesnoth painted hexes; unit sprites; fantasy map',
    }),
    ga('SP12-133', 'Resident Evil 7 2017 - Capcom Louisiana Farmhouse', {
      look: 'Capcom Resident Evil 7: Biohazard (2017) look: first-person horror in a rotting Louisiana farmhouse, photoreal decay, VHS found-footage grain, flashlight beams and humid dread.',
      subject:
        'render people as ordinary survivors in dirty everyday clothes, seen from first person.',
      color: 'Rotting brown, humid green and flashlight white.',
      light: 'Flashlight beam in heavy darkness.',
      texture: 'Photoreal rot, mold and wood.',
      camera: 'First-person view at boarded windows.',
      mood: 'humid claustrophobic terror',
      render: 'Authentic modern first-person horror screen.',
      key: 'RE7 farmhouse; photoreal rot; flashlight',
      avoid: ['existing Baker family members'],
    }),
    ga('SP12-134', 'Halo Reach 2010 - Bungie Last Stand', {
      look: 'Bungie Halo: Reach (2010) look: doomed planet last stand, burning skies, armored super-soldiers, alien war-beasts, spaceports and evacuation transports.',
      subject: 'render people as chunky armored soldiers under a burning alien sky.',
      color: 'Burning orange sky, steel grey and plasma blue.',
      light: 'Fire glow with plasma flashes.',
      texture: 'Chunky armor and scorched metal.',
      camera: 'First-person view at a landing pad.',
      mood: 'doomed heroic sacrifice',
      render: 'Authentic Xbox 360 shooter screen.',
      key: 'Halo Reach last stand; burning sky; evacuation',
      avoid: ['green armored super-soldier with gold visor', 'existing Covenant species'],
    }),
    ga('SP12-135', 'Clash Royale 2016 - Supercell Cartoon Arena', {
      look: 'Supercell Clash Royale (2016) look: bright chunky cartoon mobile arena, two towers per side, lanes across a river bridge and tiny exaggerated units.',
      subject: 'render every subject as a tiny chunky exaggerated cartoon unit.',
      color: 'Bright grass green, blue and red teams.',
      light: 'Bright flat cartoon daylight.',
      texture: 'Glossy chunky cartoon 3D.',
      camera: 'Top-down arena view.',
      mood: 'cheeky competitive chaos',
      render: 'Authentic mobile cartoon arena screen.',
      key: 'Clash Royale arena; chunky cartoon; lanes',
      avoid: ['existing Clash units'],
      briefs: [
        'Marching along the lanes between two towers, an original army of blue gnome engineers clashes with red mushroom warriors as a giant catapult-turtle lumbers across the middle bridge. No readable text or logo.',
        keep('SP12-135')[1],
        keep('SP12-135')[2],
      ],
    }),
    ga('SP12-136', 'Stronghold 2001 - Firefly Castle Sim', {
      look: 'Firefly Studios Stronghold (2001) look: isometric 2D castle-building simulation, tiny busy peasants, farms, walls and sieges on a medieval landscape.',
      subject: 'render people as tiny busy medieval peasants and soldiers from above.',
      color: 'Pastoral green, stone grey and thatch gold.',
      light: 'Soft daylight on isometric terrain.',
      texture: 'Pre-rendered isometric sprites.',
      camera: 'Isometric castle overview.',
      mood: 'industrious medieval siege',
      render: 'Authentic early-2000s castle sim screen.',
      key: 'Stronghold isometric; tiny peasants; castle walls',
    }),
    ga('SP12-137', 'Mount & Blade II Bannerlord 2020 - TaleWorlds Cavalry', {
      look: 'TaleWorlds Mount & Blade II: Bannerlord (2020) look: massive medieval field battles with hundreds of horsemen, dust, pike lines and sunset plains.',
      subject: 'render people as medieval riders and infantry in mail and cloth.',
      color: 'Sunset gold, dust brown and banner colors.',
      light: 'Low sun through dust.',
      texture: 'Realistic mail, cloth and dust.',
      camera: 'Low third-person battle view.',
      mood: 'thunderous medieval clash',
      render: 'Authentic medieval battle screen.',
      key: 'Bannerlord cavalry; massed battle; dust',
    }),
    ga('SP12-138', 'Valkyria Chronicles 2008 - Sega Canvas Watercolor War', {
      look: 'Sega Valkyria Chronicles (2008) look: CANVAS engine watercolor war, pencil hatching lines on 3D, paper texture, WWII-inspired European battlefields and giant iron land fortresses.',
      subject: 'render people as anime soldiers with sketchy watercolor shading.',
      color: 'Soft watercolor snow, olive and sepia.',
      light: 'Watercolor wash light with paper grain.',
      texture: 'Pencil hatching over watercolor paper.',
      camera: 'Third-person tactical view.',
      mood: 'bittersweet wartime tactics',
      render: 'Authentic watercolor strategy screen.',
      key: 'Valkyria CANVAS watercolor; hatching; iron fortresses',
      avoid: ['a blue-haired Valkyria with a lance and shield'],
    }),
  ]),
};

export default spec;
