import type { Create, Spec } from '../tools/apply';
import { WARDROBE_AVOID as AVOID, wear } from './_wardrobe';

// Subculture wardrobes: clothing rules only. Venue, props and social narrative stay with the prompt.
const spec: Spec = {
  pack: 'pack_08',
  category: '2. Subcultures',
  updates: {
    'SP08-002': {
      dna: wear(
        'Streetwear hype styling: oversized drop-shoulder layers, heavyweight hoodies, statement pieces without printed graphics and coveted sneakers stacked with attitude.',
        'oversized heavyweight hoodie or boxy jacket, baggy cargo or track pants, chunky statement sneakers, crossbody bag and a beanie or cap worn low.',
        'Washed black, bone, olive and one loud accent such as safety orange or electric blue.',
        'Hard urban daylight or flash with strong contrast.',
        'Heavyweight fleece, nylon shells, ripstop cargo and suede-and-mesh sneakers.',
        'Low-angle full figure emphasizing sneakers and oversized silhouette.',
        'Confident, cool, collectible and street-proud.',
        'Crisp, high-contrast street editorial finish.',
        'oversized drop-shoulder layers; chunky statement sneakers; crossbody bag; washed black with loud accent; low-angle framing',
      ),
      avoid: [...AVOID, 'sneaker brand marks'],
      briefs: [
        "Shot from low, an orc warrior leans on a castle portcullis in an oversized washed-black hoodie, baggy olive cargos and chunky statement sneakers, a crossbody bag slung over his axe. No readable text or logo.",
        "An elderly woman in a boxy safety-orange nylon jacket and track pants skateboards down a cobbled medieval street, chunky sneakers kicking up sparks. No readable text or logo.",
        "A wizard in an oversized bone hoodie, cargo pants and a low beanie pulled over his long beard sits on a stone bridge rail, guarding a queue of apprentices. No readable text or logo.",
      ],
    },
    'SP08-004': {
      dna: wear(
        'Boho festival style: sun-faded layers of flowing prints, fringe, crochet and handmade jewelry worn loose for dancing outdoors.',
        'flowing printed maxi dress or wide trousers, crochet or fringed layer, suede boots or sandals, stacked beaded and silver jewelry, and a flower or feather accent.',
        'Sun-bleached terracotta, mustard, sage, cream and turquoise.',
        'Low golden-hour backlight with dust and lens glow.',
        'Crochet, suede fringe, cotton voile, embroidery, beads and hammered silver.',
        'Loose, joyful full figure in open air.',
        'Free, sunny, romantic and wandering.',
        'Warm, hazy, film-like finish.',
        'flowing printed layers; fringe and crochet; stacked beaded jewelry; sun-bleached palette; golden backlight',
      ),
      avoid: AVOID,
      briefs: [
        "A druid in a flowing terracotta maxi dress, fringed suede vest and crochet shawl dances barefoot inside a stone circle at golden hour, silver jewelry flashing. No readable text or logo.",
        "In a hazy sunflower field a minstrel in wide sage trousers and an embroidered cotton tunic plays a lute while bees orbit his beaded necklaces. No readable text or logo.",
        "An elderly woman in a crochet cardigan, mustard printed skirt and turquoise rings drives a painted horse-drawn caravan down a dusty lane. No readable text or logo.",
      ],
    },
    'SP08-007': {
      dna: wear(
        'Traditional goth darkwave: black-on-black romantic layers — lace, velvet, fishnet and silver — with pale skin and dramatic dark makeup.',
        'layered black lace and velvet, a long coat or corseted top, fishnet or striped hosiery, heavy boots, silver crosses or moons and dark lipstick and eyeliner.',
        'Black on black with pale skin, blood red and cold silver accents.',
        'Low cold light, candles or moonlight with deep shadow.',
        'Crushed velvet, lace, fishnet, patent leather and oxidized silver.',
        'Moody full or three-quarter figure in dim settings.',
        'Melancholic, romantic, nocturnal and dramatic.',
        'Rich, low-key finish with deep blacks.',
        'black lace and velvet layers; silver moons and crosses; dark lipstick; heavy boots; candlelit low key',
      ),
      avoid: AVOID,
      briefs: [
        "A lighthouse keeper in layered black velvet and lace, silver moon pendants and dark eyeliner lights candles in a storm-battered lantern room. No readable text or logo.",
        "A woman in a crushed velvet coat, fishnet sleeves and blood-red lipstick walks through a misty cemetery, a black cat trailing her hem. No readable text or logo.",
        "An elderly woman in a black lace high-collar dress and silver rings reads tarot at a candlelit table, and the cards are reading her back. No readable text or logo.",
      ],
    },
    'SP08-008': {
      dna: wear(
        '1970s punk: DIY insurrection clothing — ripped and safety-pinned tees, studded leather, tartan bondage trousers and spiked hair.',
        'a ripped or hand-painted shirt held with safety pins, studded leather jacket, tartan or bondage trousers, heavy boots, chains and spiked or dyed hair.',
        'Black, red tartan, bleach white and one shock color in the hair.',
        'Harsh flash or grimy club light.',
        'Worn leather, studs, safety pins, ripped cotton, tartan wool and metal chains.',
        'Aggressive, close or full figure with energy.',
        'Rebellious, raw, loud and anti-establishment.',
        'Gritty, contrasty finish.',
        'safety pins and rips; studded leather; tartan bondage trousers; spiked dyed hair; harsh flash',
      ),
      avoid: [...AVOID, 'readable slogans'],
      briefs: [
        "Under harsh flash, a court jester reborn as a 1970s punk sneers from a throne in a studded leather jacket, ripped safety-pinned tee, red tartan bondage trousers and spiked green hair. No readable text or logo.",
        "An elderly woman in a studded leather jacket, chains and tartan trousers, her white hair spiked high, feeds pigeons in a castle square. No readable text or logo.",
        "A knight whose surcoat is ripped and safety-pinned leans on a broken lance, a studded collar at his throat and a bright red mohawk rising from his helmet. No readable text or logo.",
      ],
    },
    'SP08-014': {
      dna: wear(
        'Field utility textile styling: workwear and military-surplus pieces worn as fashion — multi-pocket jackets, canvas, webbing belts and sturdy boots.',
        'a multi-pocket field or chore jacket, canvas or ripstop trousers, webbing belt, sturdy lace-up boots and a utility pouch or canvas bag.',
        'Olive drab, khaki, brown duck canvas, faded navy and rust.',
        'Overcast field daylight with honest shadow.',
        'Waxed cotton, duck canvas, ripstop, webbing, brass snaps and leather.',
        'Practical full figure in working or outdoor settings.',
        'Capable, rugged, practical and quietly stylish.',
        'Matte, textured finish with visible wear.',
        'multi-pocket field jacket; duck canvas; webbing belt; lace-up boots; olive and khaki palette',
      ),
      avoid: [...AVOID, 'military insignia'],
      briefs: [
        "Crouched over huge claw prints in the mud, a dragon tracker wears a waxed olive field jacket with a dozen pockets, canvas trousers, webbing belt and lace-up boots. No readable text or logo.",
        "An elderly man in a rust duck-canvas chore jacket and khaki trousers repairs a creaking waterwheel under an overcast sky. No readable text or logo.",
        "A cartographer in a multi-pocket ripstop jacket and utility pouches stands at the edge of a glacier, measuring the crevasse with a knotted rope. No readable text or logo.",
      ],
    },
    'SP08-021': {
      dna: wear(
        'Pastel goth: creepy-cute fusion of goth silhouettes in candy pastels — platform shoes, spiked chokers, bat and skull motifs in lilac and mint.',
        'pastel-colored goth pieces — babydoll or pleated dress, pastel faux-fur or cardigan, platform creepers, spiked choker, bat or skull accessories and pastel hair.',
        'Lilac, mint, baby pink and baby blue with black accents.',
        'Soft, bright, slightly dreamy light.',
        'Faux fur, vinyl, lace, spikes, plastic charms and glitter.',
        'Playful full figure with cute-creepy props.',
        'Cute, spooky, ironic and whimsical.',
        'Soft, clean, pastel finish.',
        'goth silhouettes in pastels; platform creepers; spiked choker; bat and skull charms; pastel hair',
      ),
      avoid: AVOID,
      briefs: [
        "A necromancer in a lilac babydoll dress, mint faux-fur coat, spiked choker and platform creepers walks a cute skeleton cat on a leash through a pastel graveyard. No readable text or logo.",
        "A vampire in a baby-pink cape, black lace collar and pastel platform boots fixes his bat-shaped hair clips in a mirror that shows only the clips. No readable text or logo.",
        "An elderly witch with baby-blue hair, a pastel pleated dress and skull charms stirs a cauldron bubbling with candy-colored smoke. No readable text or logo.",
      ],
    },
    'SP08-022': {
      dna: wear(
        '90s grunge: slouchy thrift-store layers — oversized flannel, ripped jeans, faded band-less tees, knit beanies and scuffed boots — worn uncared-for.',
        'an oversized flannel shirt over a faded tee or thermal, ripped loose jeans or a slip dress, knit beanie and scuffed combat boots or worn sneakers.',
        'Faded plaid reds and greens, washed black, olive and denim blue.',
        'Dim, grainy available light or overcast day.',
        'Brushed flannel, thermal waffle knit, worn denim and scuffed leather.',
        'Slouching, candid full or three-quarter figure.',
        'Apathetic, melancholic, raw and lo-fi.',
        'Grainy, washed-out film finish.',
        'oversized flannel; ripped jeans; knit beanie; scuffed boots; faded plaid palette',
      ),
      avoid: [...AVOID, 'band names'],
      briefs: [
        "Grainy and damp, a troll musician slumps on a mossy log in a rainy forest in an oversized faded red flannel, ripped jeans and knit beanie. No readable text or logo.",
        "A woman in a slip dress over a thermal top and scuffed combat boots sits on the steps of a ruined abbey, staring at the overcast sky. No readable text or logo.",
        "Taking a break outside the castle kitchen, a knight wears a worn flannel shirt over his chainmail and ripped trousers, sipping from a chipped mug. No readable text or logo.",
      ],
    },
    'SP08-023': {
      dna: wear(
        'Lolita fashion: doll-like Victorian-Rococo silhouettes — bell-shaped petticoated skirts, lace, bows, blouses with high collars and bonnets.',
        'a bell-shaped knee-length dress over petticoats, high-collared lace blouse, bonnet or bow headdress, frilled socks and round-toe strap shoes.',
        'Sweet pastels, classic burgundy and navy, or gothic black and white.',
        'Soft, even, romantic light.',
        'Cotton lace, chiffon ruffles, satin ribbons, jacquard and pearls.',
        'Full figure with the bell silhouette clearly visible.',
        'Elegant, doll-like, whimsical and composed.',
        'Delicate, detailed finish.',
        'bell-shaped petticoat skirt; lace and bows; bonnet; frilled socks; doll-like elegance',
      ),
      avoid: AVOID,
      briefs: [
        "A woman in a gothic black-and-white bell-skirted dress, bonnet and lace parasol stands in an overgrown greenhouse full of carnivorous plants, one of them nibbling her ribbons. No readable text or logo.",
        "Two sisters in classic burgundy petticoated dresses take tea with a large owl in a stone castle garden, the owl in a tiny bonnet. No readable text or logo.",
        "Frilled socks swinging, a woman in pastel sweet ruffles rides a carousel horse in an abandoned fairground at dusk. No readable text or logo.",
      ],
    },
    'SP08-024': {
      dna: wear(
        '1950s rockabilly: hot-rod Americana wardrobe — cuffed selvedge jeans, bowling shirts, swing dresses, leather jackets and pompadours or victory rolls.',
        'cuffed dark jeans with a rolled tee or bowling shirt and leather jacket, or a polka-dot swing dress with petticoat; pompadour or victory-roll hair and saddle shoes or creepers.',
        'Cherry red, black, cream, turquoise and polka-dot white.',
        'Warm diner neon or sunny chrome glare.',
        'Selvedge denim, leather, rayon, polka-dot cotton and chrome.',
        'Confident full figure, often leaning or mid-dance.',
        'Swaggering, flirtatious, retro and fun.',
        'Saturated, glossy retro finish.',
        'cuffed jeans and leather jacket; polka-dot swing dress; pompadour and victory rolls; cherry red and turquoise',
      ),
      avoid: [...AVOID, 'car brand marks'],
      briefs: [
        "A blacksmith with a greased pompadour leans on his anvil at a medieval forge in cuffed jeans, a rolled white tee and a leather jacket. No readable text or logo.",
        "A woman with victory rolls and a cherry-red polka-dot swing dress dances with a skeleton at a moonlit village fair. No readable text or logo.",
        "An elderly man in a turquoise bowling shirt and creepers polishes a horse-drawn carriage as if it were a hot rod. No readable text or logo.",
      ],
    },
    'SP08-025': {
      dna: wear(
        '1960s hippie: flower-power clothing — bell-bottoms, peasant blouses, tie-dye, fringe, headbands and handmade beads.',
        'bell-bottom jeans or a flowing peasant dress, tie-dye or embroidered top, fringed vest, headband with flowers and handmade bead necklaces.',
        'Psychedelic tie-dye swirls, earthy browns, sunflower yellow and sky blue.',
        'Warm summer daylight with flare.',
        'Tie-dyed cotton, suede fringe, embroidery, beads and crochet.',
        'Relaxed, happy full figure outdoors.',
        'Peaceful, joyful, idealistic and free.',
        'Warm, saturated vintage film finish.',
        'bell-bottoms; tie-dye; flower headband; fringed vest; handmade beads',
      ),
      avoid: AVOID,
      briefs: [
        "An elf in bell-bottoms, a tie-dye tunic, fringed vest and flower headband plays a flute on top of a painted wagon in a summer flare. No readable text or logo.",
        "A woman in a peasant dress and bead necklaces slips daisies into the visor of a sleeping knight's helmet. No readable text or logo.",
        "An elderly man with long grey hair, tie-dye and a headband tends his bees in a meadow, the bees wearing tiny flower crowns. No readable text or logo.",
      ],
    },
    'SP08-026': {
      dna: wear(
        'Road-worn biker leather: heavy motorcycle leathers with patina — thick jackets, vests, chaps, engineer boots and chains, dusty from the road.',
        'a heavy leather motorcycle jacket or vest, denim or leather chaps, engineer boots, a wallet chain and fingerless gloves, all visibly worn.',
        'Aged black and brown leather, faded denim and chrome.',
        'Hard sun or low sunset light with dust.',
        'Heavy cowhide with creases and scuffs, chrome buckles, denim and road dust.',
        'Low, heroic full figure on an open road or roadside.',
        'Tough, weathered, free and loyal.',
        'Gritty, warm finish.',
        'heavy worn leather; chaps and engineer boots; chrome chains; road dust; low heroic framing',
      ),
      avoid: [...AVOID, 'club patches with text'],
      briefs: [
        "Shot from low at sunset, a dragon rider in a road-worn black leather jacket, chaps and engineer boots stands beside her dusty dragon at a desert crossroads. No readable text or logo.",
        "An elderly man with a white braid, scuffed brown leather vest and wallet chain sits outside a roadside tavern, boots up on a barrel. No readable text or logo.",
        "Beside his warhorse in a muddy field, a knight wears a heavy creased motorcycle jacket over his mail and fingerless gloves on his sword hand. No readable text or logo.",
      ],
    },
    'SP08-027': {
      dna: wear(
        'Skater style: loose, durable clothes built around the board — baggy jeans or cords, oversized tees, hoodies, flannel, beanies and scuffed vulcanized shoes.',
        'baggy jeans or corduroys, oversized tee or hoodie, open flannel, beanie or cap, and scuffed flat vulcanized skate shoes.',
        'Faded black, grey, mustard, forest green and washed denim.',
        'Bright afternoon sun or golden-hour glare.',
        'Heavy cotton, corduroy, canvas, suede and grip-worn rubber.',
        'Low fisheye or wide full figure mid-trick or sitting on a board.',
        'Laid-back, playful, rebellious and free.',
        'Candid, zine-like finish.',
        'baggy jeans and oversized tee; vulcanized skate shoes; beanie; low wide angle; candid energy',
      ),
      avoid: [...AVOID, 'skate brand graphics'],
      briefs: [
        "Captured with a wide lens, a goblin in baggy corduroys, an oversized mustard tee and scuffed skate shoes ollies down the steps of a crumbling castle. No readable text or logo.",
        "A woman in baggy jeans, an open flannel and a beanie sits on her board at the edge of a drained moat at golden hour. No readable text or logo.",
        "An elderly man in an oversized hoodie and skate shoes carves through a stone courtyard while the palace guards pretend not to watch. No readable text or logo.",
      ],
    },
    'SP08-028': {
      name: 'Cottagecore Wardrobe',
      dna: wear(
        'Cottagecore: romantic rural wardrobe — puff-sleeve prairie dresses, aprons, knitted cardigans, straw hats and embroidered florals.',
        'a puff-sleeve prairie or smocked dress, linen apron or knitted cardigan, straw hat or headscarf, and simple leather boots or clogs.',
        'Cream, sage, faded rose, butter yellow and small calico florals.',
        'Soft morning sunlight through leaves.',
        'Linen, cotton calico, hand-knit wool, straw and embroidery.',
        'Gentle full figure in garden, meadow or kitchen.',
        'Tender, nostalgic, pastoral and calm.',
        'Soft, dreamy, warm finish.',
        'puff-sleeve prairie dress; linen apron; straw hat; calico florals; soft morning light',
      ),
      avoid: AVOID,
      briefs: [
        "A witch in a sage puff-sleeve prairie dress, linen apron and straw hat gathers mushrooms beside a mossy cottage in soft morning light. No readable text or logo.",
        "A baker in a cream knitted cardigan and calico shirt carries an armful of loaves through a wildflower meadow, followed by hopeful rabbits. No readable text or logo.",
        "At her garden gate an elderly woman in a butter-yellow smocked dress feeds a fawn from her palm while bluebirds perch along her straw hat brim. No readable text or logo.",
      ],
    },
    'SP08-029': {
      name: 'Dark Academia Wardrobe',
      dna: wear(
        'Dark academia: scholarly tailoring in autumnal darks — tweed blazers, turtlenecks, pleated trousers, long wool coats, oxfords and wire glasses.',
        'a tweed blazer or long wool coat, turtleneck or collared shirt with sweater vest, pleated trousers or skirt, oxford shoes and round wire glasses.',
        'Chocolate brown, charcoal, burgundy, forest green and ivory.',
        'Dim library lamplight or grey autumn light.',
        'Tweed, wool, corduroy, leather and aged paper tones.',
        'Contemplative three-quarter or full figure among books or old architecture.',
        'Brooding, intellectual, melancholic and romantic.',
        'Moody, warm-shadowed finish.',
        'tweed blazer and turtleneck; long wool coat; oxfords; wire glasses; autumnal dark palette',
      ),
      avoid: AVOID,
      briefs: [
        "A necromancer scholar in a tweed blazer, burgundy turtleneck and round wire glasses reads beside a skull in a candlelit library. No readable text or logo.",
        "A woman in a long charcoal wool coat, sweater vest and oxfords walks through a foggy cloister with an armful of old books. No readable text or logo.",
        "An elderly professor in corduroy and a forest-green cardigan feeds ravens on a college tower ledge at dusk. No readable text or logo.",
      ],
    },
    'SP08-030': {
      dna: wear(
        '90s raver: club-kid ravewear — fluorescent colors, oversized cargos, crop tops, fuzzy accessories, visors, kandi bracelets and platform sneakers.',
        'oversized fluorescent cargo pants or phat pants, crop top or mesh tee, fuzzy leg warmers or backpack, kandi bracelets, visor or bucket hat and platform sneakers.',
        'Fluorescent pink, lime, cyan and orange under black light.',
        'UV black light, strobes and laser beams in haze.',
        'Nylon, mesh, faux fur, PVC and plastic beads.',
        'Dancing full figure with motion blur and lasers.',
        'Euphoric, colorful, communal and wild.',
        'Glowing, UV-saturated finish.',
        'fluorescent phat pants; kandi bracelets; fuzzy accessories; platform sneakers; UV and lasers',
      ),
      avoid: AVOID,
      briefs: [
        "A troll in fluorescent pink phat pants, a lime mesh tee, kandi bracelets and platform sneakers dances under UV lasers deep in a cavern. No readable text or logo.",
        "A woman in a cyan crop top, fuzzy leg warmers and visor glows under black light at a rave inside a ruined cathedral. No readable text or logo.",
        "An elderly man in fluorescent orange cargos and a bucket hat dances among laser beams in a stone hall, glow sticks in both fists. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Emo Scene',
      domain: '2000s emo scene wardrobe',
      tags: ['emo', 'scene', 'fashion'],
      dna: wear(
        '2000s emo and scene style: skinny black jeans, graphic tees with invented motifs, studded belts, checkered accessories and side-swept dyed fringe.',
        'skinny black jeans, fitted dark tee or striped long sleeve, studded belt, checkered wristbands or scarf, worn canvas sneakers and side-swept black or dyed fringe with heavy eyeliner.',
        'Black with hot pink, electric blue or checkered black-and-white accents.',
        'Webcam-like flash or moody bedroom light.',
        'Stretch denim, cotton jersey, studs, canvas and plastic jewelry.',
        'Close three-quarter framing, often from a high angle.',
        'Emotional, dramatic, self-conscious and nostalgic.',
        'Slightly grainy, flash-lit finish.',
        'skinny black jeans; studded belt; checkered accessories; side-swept dyed fringe; heavy eyeliner',
      ),
      avoid: [...AVOID, 'band names'],
      briefs: [
        "Caught in a high-angle flash, a vampire with a side-swept black-and-pink fringe, heavy eyeliner, skinny black jeans and a studded belt poses in a candlelit crypt. No readable text or logo.",
        "A knight with a side-swept electric-blue fringe and a checkered scarf over his armor sulks on a spiral tower stair. No readable text or logo.",
        "A ghost in a striped long sleeve, skinny jeans and worn canvas sneakers sits on her own gravestone, headphones on. No readable text or logo.",
      ],
    },
    {
      name: 'Visual Kei',
      domain: 'visual kei stage fashion',
      tags: ['visual-kei', 'japanese-subculture', 'fashion'],
      dna: wear(
        'Visual kei: theatrical rock fashion with dramatic hair, heavy makeup and ornate layered costumes mixing gothic, aristocratic and punk elements.',
        'an ornate layered costume — brocade or leather coat, lace, buckles, chains, asymmetric cuts — with sculpted teased hair and bold stage makeup.',
        'Black, deep purple, blood red, silver and white with metallic accents.',
        'Dramatic stage lighting with colored rim light.',
        'Brocade, leather, PVC, lace, feathers and metal hardware.',
        'Dramatic three-quarter or full figure pose.',
        'Theatrical, androgynous, dark and glamorous.',
        'Glossy, high-contrast stage finish.',
        'ornate layered costume; teased sculpted hair; heavy stage makeup; brocade and buckles; colored rim light',
      ),
      avoid: [...AVOID, 'real musician likeness'],
      briefs: [
        "A demon prince in a purple brocade coat, lace cravat, buckles, teased silver hair and heavy eye makeup lounges on a ruined throne in dramatic rim light. No readable text or logo.",
        "A woman in black PVC and feather layers with sculpted red hair plays violin on the roof of a moonlit clock tower. No readable text or logo.",
        "Two performers in asymmetric white-and-silver costumes pose back to back in a flooded cathedral, their reflections wearing black. No readable text or logo.",
      ],
    },
    {
      name: 'Sixties Mod',
      domain: '1960s mod wardrobe',
      tags: ['mod', 'sixties', 'fashion'],
      dna: wear(
        '1960s mod style: sharp slim tailoring and graphic geometric dresses — two-button suits, fishtail parkas, shift dresses, go-go boots and bold op-art patterns.',
        'a slim two-button suit with narrow tie and Chelsea boots or a fishtail parka, or a geometric shift dress with go-go boots and a bob haircut.',
        'Black and white op-art, primary red, mustard and target-motif blues.',
        'Crisp, bright studio or city daylight.',
        'Mohair suiting, PVC, wool crepe and patent leather.',
        'Graphic, centered full figure with clean background.',
        'Sharp, cool, youthful and optimistic.',
        'Crisp, graphic finish.',
        'slim two-button suit; geometric shift dress; go-go boots; op-art patterns; bob haircut',
      ),
      avoid: [...AVOID, 'target logos with text'],
      briefs: [
        "A sorceress in a black-and-white op-art shift dress, white go-go boots and a sharp bob poses inside a spiral stone stairwell that echoes her pattern. No readable text or logo.",
        "A knight in a slim two-button mohair suit and narrow tie rides a scooter through a medieval market, his lance strapped to the back. No readable text or logo.",
        "An elderly woman in a mustard shift dress and patent boots stands on a ballroom's black-and-white checkered floor like the queen piece in a giant game. No readable text or logo.",
      ],
    },
    {
      name: 'Decora Harajuku',
      domain: 'decora street fashion',
      tags: ['decora', 'harajuku', 'fashion'],
      dna: wear(
        'Decora street fashion: layered, hyper-accessorized kawaii style — dozens of hair clips, bright layered clothes, stickers, toys and bags worn all at once.',
        'bright layered tutus, tees and hoodies, leggings and socks in different colors, dozens of plastic hair clips, bracelets, toy charms, face stickers and a character backpack.',
        'Every bright candy color at once: pink, yellow, sky blue, mint and purple.',
        'Bright, flat, playful daylight.',
        'Plastic clips, tulle, fleece, vinyl stickers and plush toys.',
        'Full figure packed with accessories, playful pose.',
        'Joyful, excessive, childlike and fearless.',
        'Crisp, saturated, detailed finish.',
        'dozens of hair clips; layered candy colors; toy charms; face stickers; hyper-accessorized',
      ),
      avoid: [...AVOID, 'licensed character toys'],
      briefs: [
        "A witch covered in decora layers, dozens of pastel hair clips, a tutu over leggings and toy charms, rides her broom over a grey medieval town. No readable text or logo.",
        "A dwarf in decora, layered candy hoodies, plush toy necklaces and rainbow hair clips, mines gems by the light of his glowing accessories. No readable text or logo.",
        "An elderly woman in decora layers with a plush dragon backpack feeds ducks at a village pond, the ducks pecking at her hair clips. No readable text or logo.",
      ],
    },
    {
      name: 'Metalhead Battle Vest',
      domain: 'heavy metal fan wardrobe',
      tags: ['metal', 'battle-vest', 'fashion'],
      dna: wear(
        'Heavy metal fan style: denim or leather battle vest covered in sewn patches and studs, black tees, bullet belts, long hair and high-top sneakers or boots.',
        'a sleeveless denim or leather battle vest covered in wordless patches, pins and studs, a black tee, bullet or studded belt, tight jeans and high-tops or boots, with long hair.',
        'Black, faded denim, silver studs and colorful patch artwork.',
        'Concert stage light, fire glow or harsh flash.',
        'Faded denim, leather, embroidered patches, studs and metal spikes.',
        'Headbanging or powerful full figure framing.',
        'Loud, loyal, fierce and exuberant.',
        'Gritty, high-contrast finish.',
        'patch-covered battle vest; studded bullet belt; black tee; long hair; concert glow',
      ),
      avoid: [...AVOID, 'band names', 'readable patch text'],
      briefs: [
        "Under concert light a long-haired barbarian in a patch-covered denim battle vest, bullet belt and high-tops headbangs on a battlefield of burning banners. No readable text or logo.",
        "An elderly woman in a studded leather battle vest covered in wordless dragon patches knits calmly in a rocking chair. No readable text or logo.",
        "A monk in a denim battle vest over his robes throws the horns in a candlelit cloister. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
