import type { Create, Spec } from '../tools/apply';
import { MATERIAL_AVOID as AVOID, material } from './_material';

// Tactile surfaces: each preset names its own hand-feel mechanism (pile, loops, compression,
// powder, frost...). Mechanisms are not shared across presets.
const t = material;

const spec: Spec = {
  pack: 'pack_09',
  category: '4. Tactile Surfaces',
  updates: {
    'SP09-029': {
      dna: t(
        'Velvet: short dense pile that darkens and brightens as it bends, showing finger-brushed trails.',
        'the target is upholstered in velvet whose pile reverses where touched, leaving darker brushed trails.',
        'Jewel velvet colors shifting light to dark with pile direction.',
        'Low raking light to show pile direction.',
        'Dense short pile with brushed trails and crush marks.',
        'Soft, rich, inviting and intimate.',
        'directional velvet pile; brushed dark trails; crush marks',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's helmet upholstered in emerald velvet with finger-brushed dark trails across the pile. No text or logo.",
        'Photograph of a velvet-covered dragon egg with crushed pile on a stone altar. No text or logo.',
        'Photograph of a velvet-upholstered rowboat on a still lake. No text or logo.',
      ],
    },
    'SP09-039': {
      dna: t(
        "Frosted: a crust of feathery hoarfrost crystals growing over the target's surfaces.",
        'hoarfrost crystals grow in feathery spikes over the target, thicker on edges.',
        'White and pale blue frost over darker surfaces.',
        'Cold backlight sparkling on crystals.',
        'Feathery hoarfrost needles and rime crust.',
        'Cold, crisp, silent and delicate.',
        'feathery hoarfrost needles; rime crust; cold sparkle',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's gauntlet covered in feathery hoarfrost crystals on a dark table. No text or logo.",
        'Photograph of a frosted spider web on a castle gate. No text or logo.',
        'Photograph of a frost-covered bicycle at dawn. No text or logo.',
      ],
    },
    'SP09-045': {
      dna: t(
        'Felt: dense matted wool with fuzzy surface and soft rounded edges, like needle-felted craft.',
        'the target is formed from dense needle-felted wool with soft rounded edges.',
        'Soft saturated wool colors.',
        'Soft diffuse light showing fuzz.',
        'Matted wool fibers with fuzzy halo and needle pits.',
        'Cozy, handmade, soft and gentle.',
        'needle-felted wool; fuzzy halo; rounded edges',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a needle-felted dragon with fuzzy wool scales curled on a wooden shelf. No text or logo.',
        "Photograph of a felt knight's helmet. No text or logo.",
        'Photograph of a felt crown on a pillow. No text or logo.',
      ],
    },
    'SP09-047': {
      dna: t(
        'Synthetic fur: long glossy faux-fur pile, uniformly colored and shaggy.',
        'the target is covered in long glossy synthetic fur that sways with volume.',
        'Bright or dyed faux-fur colors.',
        'Soft light with glossy fiber sheen.',
        'Long synthetic fibers with glossy sheen and clumps.',
        'Playful, plush, bold and cuddly.',
        'long glossy faux fur; shaggy volume; dyed color',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's full armor covered in shaggy pink synthetic fur in a snowy field. No text or logo.",
        'Photograph of a faux-fur covered throne. No text or logo.',
        'Photograph of a shaggy-fur covered piano. No text or logo.',
      ],
    },
    'SP09-050': {
      dna: t(
        'Dry chalk: powdery matte chalk surfaces that smudge and leave dust.',
        'the target is made of or coated in dry chalk, powdery, smudged and dusty at edges.',
        'Chalky pastels or white with dust.',
        'Soft light for matte powder.',
        'Powdery chalk with smudges, dust and fingerprints.',
        'Fragile, dusty, soft and ephemeral.',
        'powdery matte chalk; smudges; dust fall',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a chalk-carved knight statue smudged by fingerprints with dust on the floor. No text or logo.',
        'Photograph of a chalk dragon skull. No text or logo.',
        'Photograph of a chalk-coated violin. No text or logo.',
      ],
    },
    'SP09-069': {
      dna: t(
        'Fiberglass insulation: pink or yellow fluffy glass-fiber batts with an itchy loose texture.',
        'the target is formed from fluffy fiberglass batts with loose fibers.',
        'Pink or yellow insulation with pale fibers.',
        'Soft light showing fluffy fibers.',
        'Loose glass-fiber batts with torn edges.',
        'Industrial, odd, soft-looking and prickly.',
        'fluffy fiberglass batts; loose fibers; pink or yellow',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a fiberglass-insulation dragon in an attic. No text or logo.',
        'Photograph of a knight statue made of pink fiberglass batts. No text or logo.',
        'Photograph of a fiberglass armchair. No text or logo.',
      ],
    },
    'SP09-074': {
      dna: t(
        'Shag carpet: long looped or cut shag pile covering the target like a rug.',
        'the target is covered in long shag carpet pile.',
        'Retro orange, avocado, mustard or cream shag.',
        'Warm indoor light.',
        'Long shag strands with deep pile.',
        'Retro, cozy, kitsch and soft.',
        'long shag pile; retro colors; deep strands',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's horse covered in orange shag carpet pile. No text or logo.",
        'Photograph of a shag-carpet dragon. No text or logo.',
        'Photograph of a shag-carpet cathedral pew. No text or logo.',
      ],
    },
    'SP09-075': {
      dna: t(
        'Artificial turf: synthetic grass blades in dense uniform rows over the target.',
        'the target is covered in synthetic turf blades with a rubber-crumb base.',
        'Bright artificial green with black rubber crumb.',
        'Bright daylight.',
        'Uniform plastic blades and rubber crumb infill.',
        'Artificial, playful, suburban and odd.',
        'plastic turf blades; rubber crumb; uniform green',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a knight statue covered in artificial turf. No text or logo.',
        'Photograph of a turf-covered grand piano on a rooftop. No text or logo.',
        'Photograph of a turf-covered dragon. No text or logo.',
      ],
    },
  },
  creates: [
    {
      name: 'Terrycloth Loops',
      domain: 'terrycloth loop pile',
      tags: ['terrycloth', 'loops', 'tactile'],
      dna: t(
        'Terrycloth: soft uncut cotton loops like a bath towel, absorbent and plush.',
        'the target is covered in uncut cotton terry loops.',
        'Soft white, pastel or striped terry.',
        'Soft daylight showing loop texture.',
        'Uncut cotton loops, absorbent and plush.',
        'Soft, domestic, fresh and comfortable.',
        'uncut terry loops; plush cotton; towel texture',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's armor made of white terrycloth towel loops standing in a bathhouse. No text or logo.",
        'Photograph of a terrycloth dragon. No text or logo.',
        'Photograph of a terrycloth throne. No text or logo.',
      ],
    },
    {
      name: 'Brushed Suede',
      domain: 'brushed suede nap',
      tags: ['suede', 'nap', 'tactile'],
      dna: t(
        'Brushed suede: velvety leather nap that shows light and dark finger marks.',
        'the target is covered in soft brushed suede with napped fingerprint marks.',
        'Tan, camel, olive or dusty rose suede.',
        'Soft side light for nap direction.',
        'Napped suede with finger marks and matte softness.',
        'Warm, soft, rich and tactile.',
        'brushed suede nap; finger marks; matte softness',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a suede-covered knight's helmet with finger marks in the nap. No text or logo.",
        'Photograph of a suede dragon. No text or logo.',
        'Photograph of a suede violin. No text or logo.',
      ],
    },
    {
      name: 'Quilted Padding',
      domain: 'quilted padded surfaces',
      tags: ['quilted', 'padding', 'tactile'],
      dna: t(
        'Quilted padding: puffy stitched quilting in diamond or channel patterns.',
        'the target is covered in puffy quilted padding with stitched diamond or channel lines.',
        'Glossy or matte fabric colors with stitch shadows.',
        'Soft light casting shadows in each quilt pocket.',
        'Stitched quilting with puffy pockets.',
        'Protective, cozy, plush and cushioned.',
        'puffy quilted pockets; stitched diamonds; soft shadows',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's full armor rendered as puffy quilted padding in a snowy field. No text or logo.",
        'Photograph of a quilted dragon. No text or logo.',
        'Photograph of a quilted chapel door. No text or logo.',
      ],
    },
    {
      name: 'Corduroy Ridges',
      domain: 'corduroy wale ridges',
      tags: ['corduroy', 'ridges', 'tactile'],
      dna: t(
        'Corduroy: parallel velvet wales with soft ridged texture.',
        'the target is covered in corduroy with parallel wales following its form.',
        'Rust, mustard, brown or bottle green cord.',
        'Raking light over the ridges.',
        'Parallel velvet wales and grooves.',
        'Retro, warm, scholarly and cozy.',
        'parallel corduroy wales; ridged pile; warm colors',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a corduroy-covered horse statue in a meadow. No text or logo.',
        "Photograph of a corduroy knight's helmet. No text or logo.",
        'Photograph of a corduroy armchair. No text or logo.',
      ],
    },
    {
      name: 'Memory Foam Imprint',
      domain: 'memory foam compression',
      tags: ['memory-foam', 'compression', 'tactile'],
      dna: t(
        'Memory foam: slow-rebound foam holding fresh imprints of hands and objects.',
        'the target is made of dense memory foam with fresh handprint and pressure imprints slowly recovering.',
        'Pale grey, blue or white foam.',
        'Soft light showing imprint depth.',
        'Open-cell foam with deep slow-rebound imprints.',
        'Soft, quiet, strange and yielding.',
        'memory foam; handprint imprints; slow rebound',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a memory-foam knight statue with fresh handprints pressed into it. No text or logo.',
        'Photograph of a memory-foam throne with the imprint of its last occupant. No text or logo.',
        'Photograph of a memory-foam dragon egg. No text or logo.',
      ],
    },
    {
      name: 'Shearling Fleece',
      domain: 'shearling fleece curls',
      tags: ['shearling', 'fleece', 'tactile'],
      dna: t(
        'Shearling: curly sheepskin fleece with dense crimped wool.',
        'the target is covered in curly sheepskin shearling.',
        'Cream, oatmeal or caramel fleece.',
        'Warm soft light.',
        'Dense crimped wool curls.',
        'Warm, cozy, rustic and soft.',
        'curly shearling fleece; crimped wool; cream tones',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a shearling-covered knight's helmet by a fire. No text or logo.",
        'Photograph of a shearling dragon curled in snow. No text or logo.',
        'Photograph of a shearling throne. No text or logo.',
      ],
    },
    {
      name: 'Soft-Touch Silicone',
      domain: 'soft silicone surfaces',
      tags: ['silicone', 'soft-touch', 'tactile'],
      dna: t(
        'Soft-touch silicone: matte squishy silicone that looks rubbery and slightly translucent.',
        'the target is molded in soft matte silicone, slightly translucent at thin edges.',
        'Pastel or clear silicone colors.',
        'Soft diffuse light with subsurface glow.',
        'Matte silicone with slight translucency and softness.',
        'Soft, squishy, modern and friendly.',
        'soft matte silicone; translucent edges; squishy',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a silicone knight's helmet in pastel mint. No text or logo.",
        'Photograph of a squishy silicone dragon. No text or logo.',
        'Photograph of a silicone throne. No text or logo.',
      ],
    },
    {
      name: 'Neoprene',
      domain: 'neoprene wetsuit material',
      tags: ['neoprene', 'wetsuit', 'tactile'],
      dna: t(
        'Neoprene: thick spongy wetsuit rubber with jersey facing and glued seams.',
        'the target is made of neoprene with jersey faces and flat-glued seams.',
        'Black, navy or bright wetsuit colors.',
        'Soft light showing texture.',
        'Spongy neoprene with jersey faces and seams.',
        'Sporty, protective, modern and snug.',
        'neoprene; jersey face; glued seams',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a knight in armor made of black neoprene panels on a stormy beach. No text or logo.',
        'Photograph of a neoprene dragon. No text or logo.',
        'Photograph of a neoprene crown. No text or logo.',
      ],
    },
    {
      name: 'Pumice Stone',
      domain: 'pumice porous stone',
      tags: ['pumice', 'porous', 'tactile'],
      dna: t(
        'Pumice: light frothy volcanic stone full of tiny pores, rough to the touch.',
        'the target is carved from pale porous pumice.',
        'Pale grey, cream or tan.',
        'Soft light showing pores.',
        'Frothy porous stone with rough texture.',
        'Light, rough, abrasive and airy.',
        'pale porous pumice; frothy vesicles; rough',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a pumice knight statue floating in water. No text or logo.',
        'Photograph of a pumice dragon skull. No text or logo.',
        'Photograph of a pumice harp. No text or logo.',
      ],
    },
    {
      name: 'Flocked Coating',
      domain: 'flocked fuzzy coating',
      tags: ['flocking', 'coating', 'tactile'],
      dna: t(
        'Flocking: short fibers sprayed onto a surface, giving a uniform velvety matte coat.',
        'the target is flocked with a uniform velvety fiber coat.',
        'Uniform flat colors — black, red, cream.',
        'Soft light, no reflections.',
        'Short uniform fibers, matte and velvety.',
        'Soft, uniform, toy-like and plush.',
        'flocked matte coat; uniform short fibers',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a black flocked knight statue in a white gallery. No text or logo.',
        'Photograph of a red flocked dragon. No text or logo.',
        'Photograph of a flocked crown. No text or logo.',
      ],
    },
    {
      name: 'Kneaded Putty',
      domain: 'kneaded putty surfaces',
      tags: ['putty', 'kneaded', 'tactile'],
      dna: t(
        'Kneaded putty: soft malleable putty with fingerprints, folds and pulled strands.',
        'the target is modeled in soft putty with fingerprints and pulled strands.',
        'Grey, beige or pastel putty.',
        'Soft light showing fingerprints.',
        'Malleable putty with folds, strands and prints.',
        'Handmade, soft, malleable and odd.',
        'kneaded putty; fingerprints; pulled strands',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a putty-modeled knight with fingerprints all over. No text or logo.',
        'Photograph of a putty dragon. No text or logo.',
        'Photograph of a putty throne. No text or logo.',
      ],
    },
    {
      name: 'Pebbled Leather Grain',
      domain: 'pebbled leather grain',
      tags: ['pebbled-leather', 'grain', 'tactile'],
      dna: t(
        'Pebbled leather: full-grain leather with raised pebble texture and soft sheen.',
        'the target is covered in pebble-grain leather with stitched seams.',
        'Black, cognac, oxblood or navy leather.',
        'Soft side light showing pebble grain.',
        'Raised pebble grain with soft sheen.',
        'Luxurious, durable, tactile and classic.',
        'pebble-grain leather; stitched seams; soft sheen',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's helmet covered in cognac pebbled leather. No text or logo.",
        'Photograph of a pebbled leather dragon. No text or logo.',
        'Photograph of a pebbled leather throne. No text or logo.',
      ],
    },
  ] satisfies Create[],
};

export default spec;
