import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Science fiction cinema of the 1990s: each preset names its film and director and rebuilds that
// film's production look (sets, color grade, effects era, film stock). Cards stage original
// moments, never the film's own characters, machines or scenes. Event Horizon lives in Horror 90s.
const T = ['scifi-90s', 'scifi-cinema'];
const film90 = 'Nineties 35mm film grain with punchy print contrast and early digital compositing.';

const spec: Spec = {
  pack: 'pack_27',
  category: '9. Sci-Fi Cinema 90s',
  newCategory: { id: 'scifi-cinema-90s' },
  updates: {},
  creates: [
    cr(
      'Total Recall 1990 - Verhoeven Red Mars Colony',
      'nineties science fiction cinema',
      [...T, 'total-recall'],
      {
        look: 'Paul Verhoeven Total Recall (1990) look: red Martian colony of concrete domes and mining tunnels, practical mutant makeup, x-ray security scanners and loud action satire.',
        subject:
          'stage the subject in red-lit Martian colony domes, mining tunnels and concrete corridors.',
        color: 'Mars red, concrete grey and neon blue signage.',
        light: 'Red Martian daylight through domes and harsh tunnel light.',
        texture: film90,
        camera: 'Wide dome vistas and low action angles.',
        mood: 'loud paranoid adventure',
        render: 'Authentic nineties Verhoeven science fiction frame.',
        key: 'Total Recall red Mars; domes; x-ray scanners',
        avoid: [
          'a three-breasted woman',
          'a mutant growing from a man’s stomach',
          'a robot taxi driver',
        ],
        briefs: [
          'Inside a red-lit Martian colony dome, a retired geology teacher runs a tiny souvenir kiosk selling snow globes of Earth to miners in dusty jumpsuits. The red sky glows beyond the curved glass. No readable text or logo.',
          'At a colony security checkpoint, commuters walk behind a glowing x-ray wall showing their skeletons carrying lunchboxes. One skeleton is holding a cat. No readable text or logo.',
          'A long mining tunnel on Mars glows with red dust and a single abandoned drill. A lunchbox sits on its seat. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Terminator 2 1991 - Cameron Steel Blue Future War',
      'nineties science fiction cinema',
      [...T, 'terminator-2'],
      {
        look: 'James Cameron Terminator 2: Judgment Day (1991) look: steel-blue grade, Los Angeles storm drains and steel mills, liquid-metal effects and a burning skull-strewn future war.',
        subject: 'stage the subject in steel-blue urban industry and liquid-metal reflections.',
        color: 'Steel blue, molten orange and chrome.',
        light: 'Cold blue night and molten steel glow.',
        texture: film90,
        camera: 'Low anamorphic action frames.',
        mood: 'relentless steel dread',
        render: 'Authentic early-nineties Cameron action frame.',
        key: 'T2 steel blue; liquid metal; steel mill glow',
        avoid: [
          'a chrome endoskeleton with red eyes',
          'a leather-jacketed man on a motorcycle with a shotgun',
        ],
        briefs: [
          'In a steel mill glowing with molten orange light under a steel-blue night, a night-shift welder watches a puddle of liquid chrome on the floor slowly reassemble itself into a perfect teapot. No readable text or logo.',
          'A dry concrete storm drain at night echoes with an eighteen-wheeler horn. A kid on a dirt bike looks back over his shoulder. No readable text or logo.',
          'A playground under a steel-blue sky shimmers with heat. The swings are moving on their own. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Delicatessen 1991 - Jeunet Caro Sepia Absurd',
      'nineties science fiction cinema',
      [...T, 'delicatessen'],
      {
        look: 'Jeunet and Caro Delicatessen (1991) look: post-apocalyptic French apartment block in amber and sepia, wide-angle grotesque faces, creaking pipes, rhythmic comedy and absurd domestic desperation.',
        subject:
          'stage the subject in amber sepia apartment interiors with wide-angle grotesque close-ups.',
        color: 'Amber, sepia, olive and nicotine yellow.',
        light: 'Warm amber lamps through fog.',
        texture: film90,
        camera: 'Wide-angle close-ups and rhythmic cross-cutting.',
        mood: 'absurd desperate comedy',
        render: 'Authentic nineties Jeunet Caro frame.',
        key: 'Delicatessen amber; wide-angle faces; creaking pipes',
        briefs: [
          'In an amber-lit apartment block, every tenant squeaks in rhythm as a musician saws his cello, a woman beats a rug and a couple bounces on a creaking mattress all at once. Pipes rattle along the walls. No readable text or logo.',
          'A clown in a sepia raincoat slips a note under the door of a butcher shop in thick fog. A single pig is painted on the window. No readable text or logo.',
          'A flooded bathroom in amber light has a man sitting calmly in the full bathtub with a snorkel. Water pours from the ceiling. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Stargate 1994 - Emmerich Desert Pharaoh Sci-Fi',
      'nineties science fiction cinema',
      [...T, 'stargate-94'],
      {
        look: 'Roland Emmerich Stargate (1994) look: golden desert planets, pyramid spaceships, Egyptian-futurist costumes, a glowing ring portal and blockbuster adventure scale.',
        subject: 'stage the subject in golden desert planets with Egyptian-futurist architecture.',
        color: 'Desert gold, lapis blue and glowing ring light.',
        light: 'Hard desert sun and shimmering portal glow.',
        texture: film90,
        camera: 'Wide desert epics and low temple angles.',
        mood: 'epic desert wonder',
        render: 'Authentic mid-nineties blockbuster frame.',
        key: 'Stargate desert; Egyptian futurism; ring portal',
        avoid: ['a stone ring portal with chevrons', 'a jackal-headed guard helmet'],
        briefs: [
          'On a golden desert planet, an Egyptologist in a sweater vest haggles with a nomad over a woolly desert beast while a pyramid-shaped ship lands silently behind the dunes. No readable text or logo.',
          'Inside a torchlit desert temple, bearded scholars copy glowing glyphs onto graph paper by lamplight. The carved wall hums faintly and dust trickles from the ceiling. No readable text or logo.',
          'Three moons rise over a desert mining camp. A child holds a candy bar up to the stars. No readable text or logo.',
        ],
      },
    ),
    cr(
      '12 Monkeys 1995 - Gilliam Underground Time Loop',
      'nineties science fiction cinema',
      [...T, '12-monkeys'],
      {
        look: 'Terry Gilliam 12 Monkeys (1995) look: grimy underground future bunkers, fish-eye lenses, dangling cages of tubes, abandoned snowy Philadelphia and feverish time-loop paranoia.',
        subject:
          'stage the subject in grimy underground bunkers or empty snowy cities, shot fish-eye and tilted.',
        color: 'Grimy teal, rust brown and snowy white.',
        light: 'Dingy bunker light and cold winter daylight.',
        texture: film90,
        camera: 'Fish-eye close-ups and dutch tilts.',
        mood: 'feverish loop paranoia',
        render: 'Authentic nineties Gilliam frame.',
        key: '12 Monkeys fish-eye; bunkers; snowy empty city',
        briefs: [
          'In a snowy abandoned city, a volunteer in a clear plastic hazmat suit collects insect samples from a department store window while a bear walks down the empty avenue behind him. No readable text or logo.',
          'Scientists interrogate a man seated on a chair lifted high up a wall, their faces distorted by a bulging fish-eye screen. Wires hang everywhere. No readable text or logo.',
          'An airport concourse is frozen mid-moment. A little boy stares at a man in a trench coat running past. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Johnny Mnemonic 1995 - Longo Cyberspace Neon',
      'nineties science fiction cinema',
      [...T, 'johnny-mnemonic'],
      {
        look: 'Robert Longo Johnny Mnemonic (1995) look: mid-nineties cyberpunk of VR gloves and wireframe cyberspace, neon slums built from junk, data couriers and Gibson grit.',
        subject:
          'stage the subject in neon junk slums or glowing mid-nineties wireframe cyberspace.',
        color: 'Neon green and magenta over grimy steel.',
        light: 'Neon signs and glowing cyberspace grids.',
        texture: film90,
        camera: 'Tilted cyberpunk frames and virtual reality inserts.',
        mood: 'jittery cyberpunk hustle',
        render: 'Authentic mid-nineties cyberpunk frame.',
        key: 'Johnny Mnemonic cyberspace; neon slums; VR gloves',
        avoid: ['a cybernetic dolphin in a tank'],
        briefs: [
          'In a neon slum built from stacked junk under a bridge, a data courier in a crisp suit adjusts VR gloves and plunges into a wireframe city of glowing pyramids. No readable text or logo.',
          'A street doctor installs a memory chip behind the ear of a nervous accountant in a neon-lit back room. The monitor shows static. No readable text or logo.',
          'A wireframe city of glowing cubes stretches forever in green light. One cube is flashing red. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Strange Days 1995 - Bigelow Millennium POV Noir',
      'nineties science fiction cinema',
      [...T, 'strange-days'],
      {
        look: 'Kathryn Bigelow Strange Days (1995) look: millennium-eve Los Angeles, handheld point-of-view recordings, riot-lit streets, rave crowds and edgy tech-noir intensity.',
        subject:
          'stage the subject in riot-lit millennium streets and first-person handheld recordings.',
        color: 'Sodium orange, riot blue and neon.',
        light: 'Streetlight, fire and strobe.',
        texture: film90,
        camera: 'Handheld first-person point-of-view frames.',
        mood: 'feverish millennium tension',
        render: 'Authentic mid-nineties tech-noir frame.',
        key: 'Strange Days POV; millennium streets; tech noir',
        briefs: [
          'Seen through a handheld first-person recording, a delivery cyclist weaves through a millennium-eve street party of costumed crowds as fireworks burst over riot police lines. No readable text or logo.',
          'A dealer in a silk shirt slides a tiny disc across a bar in a smoky club. A headset rig waits on the stool. No readable text or logo.',
          'A rooftop at midnight on December 31st holds one abandoned headset. Confetti falls over the city below. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The City of Lost Children 1995 - Jeunet Caro Harbor Dream',
      'nineties science fiction cinema',
      [...T, 'city-lost-children'],
      {
        look: 'Jeunet and Caro The City of Lost Children (1995) look: green and amber rusty harbor city, Jean-Paul Gaultier costumes, clones, dream-stealing machines and grotesque fairy-tale science fiction.',
        subject:
          'stage the subject in a rusty green-amber harbor fairy tale with grotesque inventive costume.',
        color: 'Sea green, amber and rust.',
        light: 'Foggy harbor light and warm lamps.',
        texture: film90,
        camera: 'Wide-angle close-ups and fog-bound harbor vistas.',
        mood: 'grotesque fairy-tale wonder',
        render: 'Authentic nineties Jeunet Caro fantasy frame.',
        key: 'City of Lost Children harbor; green amber; dream machine',
        avoid: ['a cyclops cult with mechanical eyes', 'a brain in a tank'],
        briefs: [
          'In a rusty green-amber harbor city, a strongman in a striped shirt carries a tiny orphan on his shoulders across a flooded pier as fog rolls in and a lighthouse turns overhead. No readable text or logo.',
          'An old inventor on an oil rig plugs a sleeping child into a brass dream machine. Nothing appears on the screen. No readable text or logo.',
          'A single tear drifts across a foggy harbor, reflected in every window. A flea jumps from a dog. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Waterworld 1995 - Reynolds Drowned Planet',
      'nineties science fiction cinema',
      [...T, 'waterworld'],
      {
        look: 'Kevin Reynolds Waterworld (1995) look: sun-bleached endless ocean, floating rust atolls built of scrap, trimarans, jet-ski raiders and salvaged post-apocalyptic survival.',
        subject:
          'stage the subject on sun-bleached floating scrap atolls surrounded by endless ocean.',
        color: 'Sun-bleached rust, turquoise ocean and sky white.',
        light: 'Harsh ocean sun and glare.',
        texture: film90,
        camera: 'Wide ocean vistas and low deck angles.',
        mood: 'sun-bleached scrappy survival',
        render: 'Authentic mid-nineties ocean epic frame.',
        key: 'Waterworld atolls; scrap; endless ocean',
        avoid: ['a gilled mariner on a trimaran', 'a smoker gang on jet skis'],
        briefs: [
          'On a floating atoll built from rusted car parts and shipping containers, a grandmother grows tomatoes in a salvaged bathtub garden while children dive for bottle caps in the turquoise sea. No readable text or logo.',
          'A trader rows a raft stacked with jars of fresh water across a glassy sea. Everyone on the atoll wall is watching. No readable text or logo.',
          'A rusted lighthouse top pokes out of an endless calm turquoise ocean under a white sky. A single seagull guards it, puffed up against the wind. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Independence Day 1996 - Emmerich City-Size Shadows',
      'nineties science fiction cinema',
      [...T, 'independence-day'],
      {
        look: 'Roland Emmerich Independence Day (1996) look: colossal alien ships casting shadows over city skylines, burning clouds, miniature destruction and flag-waving blockbuster spectacle.',
        subject:
          'stage the subject under colossal ships shadowing entire cities in blockbuster scale.',
        color: 'Burning orange clouds and hazy city blue.',
        light: 'Shadows of giant ships and burning skies.',
        texture: film90,
        camera: 'Low wide angles up at colossal ships.',
        mood: 'epic blockbuster panic',
        render: 'Authentic mid-nineties disaster blockbuster frame.',
        key: 'Independence Day city-size ships; burning clouds',
        avoid: ['a disc ship firing a blue beam down on a white government building'],
        briefs: [
          'A colossal ship slides silently over a small-town Fourth of July parade, its shadow swallowing the marching band while a retired crop-duster pilot in the crowd lowers his hot dog. No readable text or logo.',
          'Clouds roll backward and burn orange over a desert highway. Every car has stopped to look up. No readable text or logo.',
          'A desert trailer park at dawn sits in total shadow under something vast overhead. A single porch light flickers on and a dog starts howling. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Mars Attacks 1996 - Burton Pulp Trading Card Mayhem',
      'nineties science fiction cinema',
      [...T, 'mars-attacks'],
      {
        look: 'Tim Burton Mars Attacks! (1996) look: candy-colored pulp satire, fifties-style flying saucers over Las Vegas, big-brained Martians with ray guns and campy blockbuster chaos.',
        subject: 'stage the subject in candy-colored camp chaos with fifties-style flying saucers.',
        color: 'Candy green, Vegas neon and saucer chrome.',
        light: 'Neon Vegas glow and ray-gun flashes.',
        texture: film90,
        camera: 'Wide camp compositions.',
        mood: 'gleeful camp mayhem',
        render: 'Authentic mid-nineties Burton satire frame.',
        key: 'Mars Attacks candy colors; fifties saucers; camp',
        avoid: ['a big-brained Martian in a glass helmet'],
        briefs: [
          'Over a neon Las Vegas strip, a fleet of chrome fifties-style saucers hovers while a lounge singer in a sequin jacket keeps crooning to an audience that is running for the exits. No readable text or logo.',
          'A grandmother’s record player in a trailer blasts yodeling music while tiny saucers wobble and crash in the yard. No readable text or logo.',
          'A single chrome saucer is parked on a suburban lawn next to a flamingo. The garden hose is still running. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Fifth Element 1997 - Besson Flying Traffic Pop',
      'nineties science fiction cinema',
      [...T, 'fifth-element'],
      {
        look: 'Luc Besson The Fifth Element (1997) look: candy-colored future New York with stacked flying traffic, Gaultier costumes, blue opera divas, luxury cruisers and Moebius-Mézières design.',
        subject:
          'stage the subject in candy-colored future cities with stacked flying traffic and bold costume.',
        color: 'Candy orange, cyan and chrome.',
        light: 'Bright future-city daylight.',
        texture: film90,
        camera: 'Vertiginous vertical city shots.',
        mood: 'exuberant pop future',
        render: 'Authentic late-nineties Besson frame.',
        key: 'Fifth Element flying traffic; Gaultier; pop future',
        avoid: ['a woman in white bandage straps with orange hair', 'a blue alien opera diva'],
        briefs: [
          'In a candy-colored future city, a retired sushi chef pilots his floating junk boat restaurant between stacked lanes of flying traffic, handing rolls through the windows of passing cabs. No readable text or logo.',
          'A tiny apartment shelves everything into the walls with a single button. A cat pops out of a drawer. No readable text or logo.',
          'A luxury space cruiser drifts past a blue planet with every porthole lit. Music leaks into space. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Gattaca 1997 - Niccol Retro-Modern Genetics',
      'nineties science fiction cinema',
      [...T, 'gattaca'],
      {
        look: 'Andrew Niccol Gattaca (1997) look: sleek retro-modern architecture, golden-green grade, identical suits, clean corridors, genetic testing and quiet aspiration.',
        subject:
          'stage the subject in sleek retro-modern concrete architecture with a golden-green grade.',
        color: 'Golden-green, slate grey and amber.',
        light: 'Warm clean sun through modernist glass.',
        texture: film90,
        camera: 'Symmetrical modernist framing.',
        mood: 'quiet restrained aspiration',
        render: 'Authentic late-nineties retro-modern frame.',
        key: 'Gattaca golden grade; retro modernism; identical suits',
        briefs: [
          'In a golden-lit modernist atrium, rows of workers in identical suits type at glass desks while a janitor with a perfect posture quietly polishes the floor and watches the rockets launch outside. No readable text or logo.',
          'A swimmer races her brother in a dark ocean at night. Both are far from shore. No readable text or logo.',
          "A single fallen eyelash lies on a spotless glass keyboard in a golden modernist office. A janitor's vacuum hose waits quietly nearby, pointed at it. No readable text or logo.",
        ],
      },
    ),
    cr(
      'Starship Troopers 1997 - Verhoeven Propaganda Satire',
      'nineties science fiction cinema',
      [...T, 'starship-troopers'],
      {
        look: 'Paul Verhoeven Starship Troopers (1997) look: bright satirical propaganda aesthetics, glossy recruitment reels, desert bug planets, grey armored troopers and cheerful militarism.',
        subject:
          'stage the subject in glossy satirical propaganda reels and dusty desert battle planets.',
        color: 'Recruitment-ad sunshine and dusty bug-planet ochre.',
        light: 'Bright commercial light and harsh desert sun.',
        texture: film90,
        camera: 'Propaganda newsreel inserts and wide battle vistas.',
        mood: 'cheerful satirical militarism',
        render: 'Authentic late-nineties Verhoeven satire frame.',
        key: 'Starship Troopers propaganda; bug planet; satire',
        avoid: ['giant arachnid bugs', 'grey trooper armor with a round helmet'],
        briefs: [
          'In a glossy recruitment reel, a smiling dental hygienist in a pressed uniform salutes the camera while cheerful children hand her apples in front of a spotless starship. No readable text or logo.',
          'A dusty desert outpost on a distant planet holds a lone radio operator eating cereal. The ground beneath her trembles. No readable text or logo.',
          'A spotless mess hall of a starship waits for dinner. Every tray is laid out and none is taken. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Contact 1997 - Zemeckis Radio Telescope Wonder',
      'nineties science fiction cinema',
      [...T, 'contact'],
      {
        look: 'Robert Zemeckis Contact (1997) look: vast radio telescope arrays in the New Mexico desert, headphones and static, a gyroscopic machine and luminous cosmic journeys.',
        subject:
          'stage the subject among vast desert radio telescope arrays and luminous cosmic light.',
        color: 'Desert dusk orange, dish white and cosmic blue.',
        light: 'Golden desert dusk and glowing cosmos.',
        texture: film90,
        camera: 'Wide array vistas and intimate headphone close-ups.',
        mood: 'luminous cosmic longing',
        render: 'Authentic late-nineties Zemeckis frame.',
        key: 'Contact radio telescopes; static; cosmic light',
        briefs: [
          'At dusk among dozens of white radio dishes in the desert, a retired ham radio operator in a folding chair wears headphones and suddenly sits up straight as the dishes all turn toward the same star. No readable text or logo.',
          'A young girl at a kitchen table calls into a ham radio at night. Static answers. No readable text or logo.',
          'A gigantic spinning ring of rings hums inside a hangar. A single chair hangs in the middle. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Cube 1997 - Natali Colored Cell Maze',
      'nineties science fiction cinema',
      [...T, 'cube-97'],
      {
        look: 'Vincenzo Natali Cube (1997) look: identical cubic rooms lit in single colors, hatches in every wall, strangers in prison jumpsuits and deadly geometric traps.',
        subject: 'stage the subject in identical cubic rooms lit in a single saturated color.',
        color: 'Single-color rooms of red, blue, green or amber.',
        light: 'Glowing grid-patterned walls.',
        texture: film90,
        camera: 'Tight symmetric cube framing through hatches.',
        mood: 'claustrophobic geometric dread',
        render: 'Authentic late-nineties Canadian science fiction frame.',
        key: 'Cube colored rooms; hatches; geometric traps',
        briefs: [
          'In an amber-lit cubic room with a hatch in every wall, a tax accountant in an orange jumpsuit calculates prime numbers on the floor with a lipstick while four strangers argue behind him. No readable text or logo.',
          'A hatch opens between a blue room and a green room. A boot dangles through it. No readable text or logo.',
          'A red cubic room is empty except for a folded paper crane. The walls hum faintly. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Dark City 1998 - Proyas Eternal Night Noir',
      'nineties science fiction cinema',
      [...T, 'dark-city'],
      {
        look: 'Alex Proyas Dark City (1998) look: perpetual night city of shifting noir architecture, buildings growing at midnight, pale men in black coats and amber streetlight.',
        subject: 'stage the subject in an eternal-night noir city whose buildings shift and grow.',
        color: 'Amber streetlight, deep night blue and black coats.',
        light: 'Amber streetlamps in endless night.',
        texture: film90,
        camera: 'Low noir angles on shifting architecture.',
        mood: 'uncanny eternal night',
        render: 'Authentic late-nineties Proyas frame.',
        key: 'Dark City eternal night; shifting buildings; noir',
        avoid: ['pale bald men in black coats and hats'],
        briefs: [
          'At midnight in an eternal-night city, a milkman on his round stops his cart as every person on the street falls asleep standing up and the apartment building beside him quietly grows three floors. No readable text or logo.',
          'An automat restaurant glows amber in the dark. A detective eats a sandwich and stares at a map of spirals. No readable text or logo.',
          'A pier ends at a brick wall painted with a sunny beach. The sea beyond it is black. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Truman Show 1998 - Weir Pastel Studio Town',
      'nineties science fiction cinema',
      [...T, 'truman-show'],
      {
        look: 'Peter Weir The Truman Show (1998) look: pastel perfect seaside studio town, hidden-camera vignettes, product placements, a painted sky wall and cheerful uncanny control.',
        subject:
          'stage the subject in a too-perfect pastel seaside town seen through hidden cameras.',
        color: 'Pastel suburban pink, mint and sky blue.',
        light: 'Too-perfect studio daylight.',
        texture: film90,
        camera: 'Hidden-camera vignettes and wide pastel streets.',
        mood: 'cheerful uncanny control',
        render: 'Authentic late-nineties Weir frame.',
        key: 'Truman Show pastel town; hidden cameras; sky wall',
        briefs: [
          'In a pastel seaside town seen through a hidden button camera, a retired insurance salesman waves good morning to neighbors who all smile a little too long while a studio light falls from the clear sky. No readable text or logo.',
          'A sailboat bumps into a painted sky wall on a calm sea. A door in the clouds is ajar. No readable text or logo.',
          'An empty pastel street at night has every porch light switch on at once. A dog barks once. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Pi 1998 - Aronofsky High-Contrast Mathematical Paranoia',
      'nineties science fiction cinema',
      [...T, 'pi-98'],
      {
        look: 'Darren Aronofsky Pi (1998) look: grainy high-contrast black-and-white reversal film, cramped apartment of computers, spirals, snorri-cam close-ups and migraine paranoia.',
        subject:
          'stage the subject in grainy high-contrast black and white with cramped computer clutter.',
        color: 'Harsh black and white with blown highlights.',
        light: 'Blown-out window light and harsh bulbs.',
        texture: 'Grainy high-contrast black-and-white reversal film.',
        camera: 'Body-mounted close-ups and jittery cuts.',
        mood: 'feverish mathematical paranoia',
        render: 'Authentic late-nineties indie frame.',
        key: 'Pi high contrast; spirals; cramped computers',
        briefs: [
          'In a cramped Chinatown apartment choked with computer cables, a chess-playing mathematician stares at a snail shell under a magnifier while the circuits behind him blow out in harsh white light. No readable text or logo.',
          'A subway platform in harsh black and white holds a man counting the tiles. The train never arrives. No readable text or logo.',
          'A spiral drawn in coffee on a diner napkin fills the frame. Sugar grains orbit it. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Matrix 1999 - Wachowski Green Code Bullet Time',
      'nineties science fiction cinema',
      [...T, 'matrix-99'],
      {
        look: 'The Wachowskis The Matrix (1999) look: sickly green-tinted simulated city, black leather and sunglasses, bullet-time frozen action and falling digital code.',
        subject:
          'stage the subject in a green-tinted simulated city with bullet-time frozen motion.',
        color: 'Sickly digital green and black.',
        light: 'Cold green fluorescent tint.',
        texture: film90,
        camera: 'Frozen bullet-time rotations.',
        mood: 'cool simulated revelation',
        render: 'Authentic late-nineties Wachowski frame.',
        key: 'Matrix green tint; bullet time; digital code',
        avoid: [
          'a man in a black trench coat and small sunglasses',
          'falling green code characters',
          'agents in black suits with earpieces',
        ],
        briefs: [
          'Frozen in bullet time on a green-tinted office rooftop, a pastry chef in a white apron leans impossibly backward as a flock of pigeons hangs motionless around her. No readable text or logo.',
          'A cat walks past a doorway in a green-tinted hallway, then walks past again the exact same way. No readable text or logo.',
          'A teaspoon on a green-tinted kitchen table slowly bends in the cold fluorescent light. Nobody is touching it, and the cereal beside it has stopped mid-pour. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
