import type { Create, Spec } from '../tools/apply';
import { MATERIAL_AVOID, material } from './_material';

// Material surface textures (pack_10) are decorative surface patterns — the visible figure, grain
// or finish pattern — as opposed to pack_09's physical material behavior.
const AVOID = [...MATERIAL_AVOID, 'plain untextured surface'];
const s = (a: string, b: string, c: string, l: string, t: string, m: string, k: string) =>
  material(
    a,
    `${b} The decorative surface pattern is the point: make its figure, veining or motif the first read.`,
    c,
    l,
    t,
    m,
    `${k}; decorative surface pattern`,
  );

const spec: Spec = {
  pack: 'pack_10',
  category: '6. Material Surface Textures',
  updates: {
    'SP10-048': {
      dna: s(
        'Terrazzo: polished composite with scattered stone and glass chips in a cement matrix.',
        'the surface shows scattered colored chips set in a smooth matrix.',
        'Cream matrix with terracotta, green and black chips.',
        'Soft even light on polished surface.',
        'Polished chips flush in matrix.',
        'Playful, modern, crafted and bright.',
        'scattered chips; polished matrix',
      ),
      avoid: AVOID,
      briefs: [
        "At a busy cafe the counter and bar stools are finished in polished speckled stone, terracotta, green and white chips scattered through the cement. No readable text or logo.",
        "On a museum plinth a giant egg of polished composite stone flecks marble, glass and brass chips across its curve. No readable text or logo.",
        "In a park a public drinking fountain cast in speckled polished stone glints with blue and white glass chips as water splashes. No readable text or logo.",
      ],
    },
    'SP10-054': {
      dna: s(
        'Marble veining texture: dramatic flowing veins across polished stone.',
        "bold flowing veins sweep across the target's surfaces.",
        'White, black or green marble with gold or grey veins.',
        'Polished reflections.',
        'Flowing veins and polish.',
        'Luxurious, dramatic, cool and grand.',
        'dramatic flowing veins',
      ),
      avoid: AVOID,
      briefs: [
        "A black stone panther sculpture is polished to a mirror, dramatic gold veins sweeping along its body like lightning. No readable text or logo.",
        "In an old spa a green stone bathtub shows white veins flowing across its curves as steam rises from the water. No readable text or logo.",
        "In a grand hotel lobby a pink stone staircase curves upward, flowing grey veins running across every polished step. No readable text or logo.",
      ],
    },
    'SP10-055': {
      dna: s(
        'Wood grain texture: bold flowing grain lines and knots across the surface.',
        'strong grain lines flow around knots over the surfaces.',
        'Warm wood tones with dark grain.',
        'Warm side light.',
        'Flowing grain and knots.',
        'Warm, organic, handcrafted and natural.',
        'flowing grain lines; knots',
      ),
      avoid: AVOID,
      briefs: [
        "A carved owl's bold grain lines flow around its eyes like feathers, a dark knot forming one pupil. No readable text or logo.",
        "On a lakeside dock at sunset a freshly oiled canoe shows bold flowing grain and knots along its hull. No readable text or logo.",
        "In a quiet attic an old toy chest shows swirling honey-toned grain on its lid, two knots staring up like eyes. No readable text or logo.",
      ],
    },
    'SP10-056': {
      name: 'Carbon Fiber Twill Surface',
      dna: s(
        'Carbon fiber weave: glossy twill pattern of black fibers.',
        'a glossy 2x2 twill carbon weave covers the surfaces.',
        'Black and graphite with gloss.',
        'Strip light across the weave.',
        'Twill weave under clear coat.',
        'High-tech, sleek, sporty and modern.',
        'twill carbon weave; glossy',
      ),
      avoid: AVOID,
      briefs: [
        "Under strip lights a racing bicycle frame shows glossy black twill weave shifting as the light slides along the tubes. No readable text or logo.",
        "On a marble desk a briefcase in glossy black woven fiber catches a single desk lamp in its twill. No readable text or logo.",
        "In a dark studio a cello of glossy black woven fiber shows the twill following every curve. No readable text or logo.",
      ],
    },
    'SP10-059': {
      dna: s(
        'Leather texture: pebbled or embossed leather grain with stitching.',
        'embossed leather grain and saddle stitching cover the surfaces.',
        'Cognac, black, oxblood.',
        'Soft side light.',
        'Grain, stitching and edge paint.',
        'Crafted, warm, rugged and classic.',
        'leather grain; saddle stitching',
      ),
      avoid: AVOID,
      briefs: [
        "On a travel desk a vintage camera case in pebbled black hide shows saddle stitching and worn corners. No readable text or logo.",
        "On a fence rail a tooled saddle shows embossed floral patterns and stitching along the skirt in warm ranch light. No readable text or logo.",
        "On a train platform a traveling trunk with brass corners shows pebbled grain and neat hand stitching. No readable text or logo.",
      ],
    },
    'SP10-060': {
      dna: s(
        'Glitter texture: dense sparkling glitter coating.',
        'dense multicolor glitter coats the surfaces.',
        'Gold, silver or rainbow glitter.',
        'Point lights for sparkle.',
        'Glitter flakes.',
        'Festive, playful, sparkly and kitsch.',
        'dense glitter sparkle',
      ),
      avoid: AVOID,
      briefs: [
        "On black velvet a skull coated in dense gold sparkle shines under a spotlight, loose flecks scattered around it. No readable text or logo.",
        "On a rink floor a roller skate coated in dense silver sparkle scatters light under colored bulbs. No readable text or logo.",
        "On a stage stool a trumpet coated in violet sparkle catches the spotlight in a thousand points. No readable text or logo.",
      ],
    },
    'SP10-061': {
      dna: s(
        'Rust texture: decorative rust blooms and streaks as surface pattern.',
        'orange rust blooms and streaks pattern the surface.',
        'Orange and brown on grey.',
        'Warm light.',
        'Rust blooms and streaks.',
        'Aged, industrial, raw and warm.',
        'rust blooms and streaks',
      ),
      avoid: AVOID,
      briefs: [
        "A garden gate is patterned with decorative orange blooms of oxidation streaking down from each scroll. No readable text or logo.",
        "Autumn leaves settle on a steel park bench whose slats are patterned with decorative orange oxidation blooms and long dripping streaks like a painted map. No readable text or logo.",
        "In a tower hangs a large bell patterned with orange oxidation blooms running down its lip. No readable text or logo.",
      ],
    },
    'SP10-062': {
      dna: s(
        'Holographic foil: rainbow diffraction foil that shifts color with angle.',
        'holographic diffraction foil covers the surfaces with shifting rainbows.',
        'Rainbow diffraction over silver.',
        'Point lights for diffraction.',
        'Foil with diffraction pattern.',
        'Futuristic, playful, shiny and pop.',
        'holographic diffraction foil',
      ),
      avoid: AVOID,
      briefs: [
        "In a pit lane a racing suit wrapped in rainbow diffraction foil shifts from magenta to green as the driver turns. No readable text or logo.",
        "A whale-shaped balloon covered in rainbow diffraction foil floats over a festival, colors rippling across its body. No readable text or logo.",
        "On a white table a gift box wrapped in rainbow foil shifts color across every face. No readable text or logo.",
      ],
    },
    'SP10-063': {
      name: 'Chainmail Ring Pattern',
      dna: s(
        'Chainmail texture: ring pattern as a decorative surface.',
        'fine interlocking ring pattern covers the surfaces.',
        'Steel, silver, bronze.',
        'Sparkling light on rings.',
        'Interlocking rings.',
        'Armored, ancient, elegant and heavy.',
        'interlocking ring pattern',
      ),
      avoid: AVOID,
      briefs: [
        "On a lake shore a swan sculpture covered in tiny interlocking metal rings shimmers like wet feathers. No readable text or logo.",
        "On a kitchen table a teapot surfaced in interlocking metal rings catches window light as steam rises. No readable text or logo.",
        "On a velvet stand a carnival mask of fine interlocking rings forms brows and nose from linked metal. No readable text or logo.",
      ],
    },
    'SP10-064': {
      dna: s(
        'Snake skin texture: scale pattern with bold markings as decorative surface.',
        'patterned snake scales cover the surfaces with bold markings.',
        'Python browns or emerald.',
        'Soft sheen.',
        'Overlapping scales and markings.',
        'Exotic, sleek, dangerous and luxe.',
        'snake scale markings',
      ),
      avoid: AVOID,
      briefs: [
        "On a porch a pair of cowboy boots in python-patterned hide shows bold scale markings and a soft sheen. No readable text or logo.",
        "In a jazz lounge an armchair patterned in bold reptile diamonds curves around a sleeping bass player. No readable text or logo.",
        "In a smoky club an electric guitar with a black and gold reptile finish leans against an amplifier. No readable text or logo.",
      ],
    },
    'SP10-071': {
      dna: s(
        'Kintsugi: broken ceramic repaired with gold-filled seams.',
        'the surfaces show cracks repaired with bright gold seams.',
        'Ceramic base with gold seams.',
        'Soft light catching gold.',
        'Gold-lacquer seams across cracks.',
        'Resilient, poetic, precious and calm.',
        'gold-repaired cracks',
      ),
      avoid: AVOID,
      briefs: [
        "On a tatami mat a broken tea bowl is repaired with gold-filled seams branching like rivers across its glaze. No readable text or logo.",
        "A ceramic fox mask that once shattered on a festival night is mended with bright gold seams running across its snout, cheeks and narrow eyes. No readable text or logo.",
        "Beside a single candle in a dark study, a cracked porcelain skull glows along branching golden repair seams that trace every old fracture. No readable text or logo.",
      ],
    },
  },
  creates: [
    {
      name: 'Raku Crackle Glaze',
      domain: 'raku crackle glaze',
      tags: ['raku', 'crackle', 'surface'],
      dna: s(
        'Raku glaze: crackled white glaze with smoky black craze lines and metallic flashes.',
        'crackled glaze with smoky black lines and copper flashes covers the surfaces.',
        'White crackle with black lines and copper flashes.',
        'Soft light.',
        'Crazed glaze and smoky carbon.',
        'Earthy, fiery, random and beautiful.',
        'raku crackle; smoky lines; copper flash',
      ),
      avoid: AVOID,
      briefs: [
        "On a rough stone plinth a vase shows crackled white glaze, smoky black craze lines and copper metallic flashes. No readable text or logo.",
        "On a gallery pedestal a horse head sculpture shows white glaze split by a dense web of smoky black lines. No readable text or logo.",
        "On a mossy garden wall at dusk a fired owl sits with heavy carbon smoke staining its lower half black. No readable text or logo.",
      ],
    },
    {
      name: 'Damascus Steel',
      domain: 'damascus pattern-welded steel',
      tags: ['damascus', 'steel', 'surface'],
      dna: s(
        'Damascus steel: flowing layered wave patterns in etched steel.',
        'flowing etched Damascus layers pattern the metal surfaces.',
        'Dark and light grey steel waves.',
        'Raking light.',
        'Etched layered wave pattern.',
        'Crafted, deadly, elegant and ancient.',
        'Damascus wave pattern',
      ),
      avoid: AVOID,
      briefs: [
        "On a cutting board a chef's knife shows flowing etched wave patterns along its blade beside fresh herbs. No readable text or logo.",
        "Open on a velvet cloth, a pocket watch case of layered steel shows flowing etched waves. No readable text or logo.",
        "On a mossy river stone rest two wedding rings of layered steel, etched swirls in grey and silver. No readable text or logo.",
      ],
    },
    {
      name: 'Burl Wood Figure',
      domain: 'burl wood figure',
      tags: ['burl', 'wood', 'surface'],
      dna: s(
        'Burl wood: swirling chaotic grain with eyes and clusters.',
        'swirling burl figure with tiny eyes covers the surfaces.',
        'Amber, honey and dark swirls.',
        'Warm glossy light.',
        'Chaotic swirls and eyes.',
        'Rich, organic, warm and rare.',
        'swirling burl figure; eyes',
      ),
      avoid: AVOID,
      briefs: [
        "On a workbench a turned bowl shows swirling chaotic grain and clusters of eyes under a glossy oil finish. No readable text or logo.",
        "Inside a vintage car the dashboard shows swirling figured wood and eye clusters under glossy lacquer. No readable text or logo.",
        "Under stage lights a guitar body glows with swirling figured wood and dark eye clusters deep beneath its glossy honey finish. No readable text or logo.",
      ],
    },
    {
      name: 'Mokume-gane',
      domain: 'mokume-gane layered metal',
      tags: ['mokume-gane', 'metal', 'surface'],
      dna: s(
        'Mokume-gane: layered mixed metals forming wood-grain-like patterns.',
        'wood-grain patterns of layered copper, silver and gold cover the surfaces.',
        'Copper, silver and gold bands.',
        'Soft metallic light.',
        'Layered metal grain.',
        'Refined, crafted, precious and warm.',
        'layered metal grain',
      ),
      avoid: AVOID,
      briefs: [
        "On slate rests a pendant of layered copper, silver and gold forming wood-grain patterns in metal. No readable text or logo.",
        "On velvet a ring of layered mixed metals swirls like wood grain in pink and grey. No readable text or logo.",
        "On dark cloth a sword guard of layered copper and silver shows a grain pattern like polished driftwood. No readable text or logo.",
      ],
    },
    {
      name: 'Tadelakt Plaster',
      domain: 'tadelakt polished plaster',
      tags: ['tadelakt', 'plaster', 'surface'],
      dna: s(
        'Tadelakt: burnished lime plaster with soft sheen and subtle cloudy variation.',
        'soft burnished plaster with cloudy tone variation covers the surfaces.',
        'Terracotta, sand, sage.',
        'Soft warm light.',
        'Burnished plaster sheen.',
        'Calm, earthy, warm and soft.',
        'burnished plaster; cloudy sheen',
      ),
      avoid: AVOID,
      briefs: [
        "A bathroom's walls and sunken tub are finished in burnished terracotta plaster with a soft cloudy sheen. No readable text or logo.",
        "A sink and niche in pale sand plaster glow with a soft burnished sheen and subtle cloudy variation. No readable text or logo.",
        "In a courtyard a curved bench of burnished ochre plaster shows soft cloudy variation in the late sun. No readable text or logo.",
      ],
    },
    {
      name: 'Cloisonné Enamel',
      domain: 'cloisonne enamel',
      tags: ['cloisonne', 'enamel', 'surface'],
      dna: s(
        'Cloisonné: glossy colored enamel fields separated by fine gold wire cells.',
        'glossy enamel fields in gold wire cells cover the surfaces.',
        'Turquoise, cobalt, coral, gold.',
        'Glossy light.',
        'Enamel and gold wire.',
        'Ornate, precious, bright and refined.',
        'enamel in gold wire cells',
      ),
      avoid: AVOID,
      briefs: [
        "A koi fish vase glows in turquoise and coral enamel fields separated by fine gold wire cells. No readable text or logo.",
        "On a gold stand an egg shows glossy cobalt and white enamel fields divided by gold wire. No readable text or logo.",
        "An incense burner glows in glossy green and red enamel cells outlined by fine gold wire. No readable text or logo.",
      ],
    },
    {
      name: 'Guilloché Engraving',
      domain: 'guilloche engine turning',
      tags: ['guilloche', 'engraving', 'surface'],
      dna: s(
        'Guilloché: machine-engraved repeating wave and sunburst patterns under enamel.',
        'fine engine-turned wave and sunburst patterns cover the surfaces.',
        'Silver or gold with translucent enamel.',
        'Light rippling in grooves.',
        'Engine-turned grooves.',
        'Precise, luxurious, hypnotic and refined.',
        'engine-turned grooves; sunburst',
      ),
      avoid: AVOID,
      briefs: [
        "Held open in a jeweler's palm, a pocket watch dial shows engine-turned sunburst grooves glowing beneath translucent blue enamel as it tilts. No readable text or logo.",
        "On a mirrored vanity a compact case shows repeating machine-engraved waves shimmering beneath a thin layer of translucent pink enamel. No readable text or logo.",
        "On an old leather desk blotter a fountain pen shows machine-cut waves glowing along its barrel. No readable text or logo.",
      ],
    },
    {
      name: 'Urushi Lacquer',
      domain: 'urushi lacquer finish',
      tags: ['urushi', 'lacquer', 'surface'],
      dna: s(
        'Urushi lacquer: deep glossy lacquer in black and vermilion with maki-e gold sprinkles.',
        'deep glossy lacquer with gold sprinkle motifs covers the surfaces.',
        'Black and vermilion with gold.',
        'Deep glossy reflections.',
        'Layered lacquer and gold dust.',
        'Refined, deep, precious and calm.',
        'deep lacquer; maki-e gold',
      ),
      avoid: AVOID,
      briefs: [
        "A black lacquered helmet decorated with gold cranes reflects a paper lantern in its deep glossy surface. No readable text or logo.",
        "On a low table a vermilion lacquered writing box lies open, gold maple leaves drifting across its lid. No readable text or logo.",
        "On a tatami mat a black lacquered tiered food box is scattered with fine gold flecks like stars. No readable text or logo.",
      ],
    },
    {
      name: 'Hammered Metal',
      domain: 'hammered metal texture',
      tags: ['hammered', 'metal', 'surface'],
      dna: s(
        'Hammered metal: dimpled facets from hand hammering catching light.',
        'hand-hammered dimples facet the metal surfaces.',
        'Copper, brass or pewter.',
        'Point lights sparkling on dimples.',
        'Hammered facets.',
        'Handmade, warm, rustic and crafted.',
        'hammered dimples',
      ),
      avoid: AVOID,
      briefs: [
        "On an old iron stove a copper kettle's hundreds of dimpled facets glint orange and pink in the flame. No readable text or logo.",
        "Under a window of herbs a brass farmhouse sink scatters morning light from its hand-dimpled facets. No readable text or logo.",
        "On a long oak tavern table a pewter goblet glows softly in candlelight, its dimpled facets catching a spilled drop. No readable text or logo.",
      ],
    },
  ] satisfies Create[],
};

export default spec;
