import type { Spec } from '../tools/apply';
import { design } from './_design';

// UI & app design (part B): R-UI-11..15 styles, R-UI-16 layer modifier, R-UI-17..19 workspace profiles,
// R-UI-20 five-state specimen recipe as a sheet profile.
const U = (
  source: string,
  name: string,
  domain: string,
  tag: string,
  fields: Parameters<typeof design>[4],
  avoid: string[],
  briefs: [string, string, string],
  kind: 'style' | 'modifier' | 'profile' = 'style',
) => design(name, domain, tag, 'ui', fields, avoid, briefs, { text: true, source, kind });

const spec: Spec = {
  pack: 'pack_25',
  category: '4. UI & App Design',
  updates: {},
  creates: [
    U('R-UI-11', 'Monospace Archive Interface', 'monospaced archive app layout', 'monospace-archive', {
      aesthetic: 'Monospace Archive Interface: monospaced text, index codes and constant column widths build a calm, trustworthy technical library.',
      subject_treatment: "Organize the prompt's records in monospaced text and index columns of stable width, keeping every requested code, name and date exact.",
      color_and_tone: 'Neutrals plus one navigation accent, codes set apart from titles by value and weight.',
      lighting_and_shadow: 'Crisp flat text with a clean screen and sharp characters.',
      texture_and_material: 'Sober surfaces and discreet separators on a clean, quiet ground.',
      camera_and_composition: 'Columns of predictable width with explicit truncation only where allowed.',
      atmosphere_and_mood: 'A reliable technical archive, orderly and quietly confident.',
      rendering_and_quality: 'Codes, dates and long names keep their reading and alignment.',
      key_features: 'monospaced columns; index codes; stable widths; one accent',
    }, ['decorative terminal', 'fake characters', 'codes invented to fill space'], [
      'The archive of a secret society of cartographers who map places that do not exist: codes "MAP-01", "MAP-02" and "MAP-03", long place names in monospace, charcoal with a soft amber accent.',
      'A monospaced archive of every excuse a teenager has ever given, columns "Code", "Excuse" and "Believed?", neat and deadpan, one green accent.',
      'A sound preset library in calm monospace columns, id, name and version for three presets and a simple inspector, pale background.',
    ]),
    U('R-UI-12', 'Split-Weight Navigation', 'light nav and dense work area layout', 'split-weight', {
      aesthetic: 'Split-Weight Navigation: very light navigation contrasts with a dense working surface and bold primary actions.',
      subject_treatment: "Give the prompt's app a light narrow navigation and a denser main work area with one bold primary action; keep requested labels exact.",
      color_and_tone: 'Low-weight navigation, well-contrasted content and one accent for the main action.',
      lighting_and_shadow: 'Discreet depth only between navigation and the active zone.',
      texture_and_material: 'Neutral surfaces, clear icons and controls of different weights.',
      camera_and_composition: 'Narrow but legible navigation, with the width reserved for the real task.',
      atmosphere_and_mood: 'Easy access and deep concentration while working, in one unified space.',
      rendering_and_quality: 'Navigation stays visible and the dense zone feels like the same app.',
      key_features: 'light navigation; dense work area; bold primary action; one accent',
    }, ['navigation too faint', 'giant buttons for no reason', 'different aesthetics between views'], [
      'A sprite editor for a video game about giant moths: whisper-light navigation on the left, a dense pixel editor in the center and a bold "Export" button, dark neutral background.',
      'A wedding-planning app for a couple who hate each other\'s families, thin navigation and a dense seating chart in the center, bold "Separate Them" action, pale background.',
      'A recordings library with discreet categories on the left and dense metadata editing in the main area, one clear "Save" button, single accent.',
    ]),
    U('R-UI-13', 'Graphic Stamp Interface', 'solid status stamp layout', 'graphic-stamp', {
      aesthetic: 'Graphic Stamp Interface: solid geometric markers placed on flat surfaces show real states, each with its own distinct shape.',
      subject_treatment: "Mark the states in the prompt's screen with solid geometric markers of distinct shapes next to the content they describe; keep state names exact.",
      color_and_tone: 'One main ink and a functional accent, states told apart by shape too.',
      lighting_and_shadow: 'Flat clean graphic stamps with no physical relief.',
      texture_and_material: 'Firm edges and minimal texture, crisp as fresh print.',
      camera_and_composition: 'Markers close to their content and smaller than the main reading.',
      atmosphere_and_mood: 'Direct editorial character and decisiveness, friendly and firm.',
      rendering_and_quality: 'Every stamp marks a real state and reads without color.',
      key_features: 'geometric state stamps; distinct shapes; flat surfaces; near content',
    }, ['decorative stamps', 'invented states', 'content covered by markers'], [
      'A review board for a museum of cursed objects, each item marked "Safe", "Watch" or "Sealed" by a different solid geometric stamp, pale background, black ink and one coral accent.',
      'A dating app for vampires where profiles get stamped "Bitten", "Maybe" and "Garlic Eater" with distinct shapes, flat and graphic, deeply judgmental.',
      'A text archive with compact solid markers for "Draft", "Published" and "Archived", clear type hierarchy and nothing else competing.',
    ]),
    U('R-UI-14', 'Rounded Instrument Panels', 'soft grouped instrument panel layout', 'rounded-instrument', {
      aesthetic: 'Rounded Instrument Panels: compact groups of controls in soft-edged panels, each with its own scale and a direct reading.',
      subject_treatment: "Group the prompt's controls into soft panels sized by task, each with a directly linked scale or reading; keep requested labels and values exact.",
      color_and_tone: 'Neutral base and an accent concentrated on the selection, with clear reading values.',
      lighting_and_shadow: 'Very soft edge light where it helps separate one panel from another.',
      texture_and_material: 'Semi-matte surfaces, soft contours and precise graphic scales.',
      camera_and_composition: 'Panels sized by task with aligned controls and readings within easy reach.',
      atmosphere_and_mood: 'Friendly instruments with operational clarity, approachable and exact.',
      rendering_and_quality: 'Every scale shows a range or unit when the brief supplies one.',
      key_features: 'soft grouped panels; linked scales; task-sized groups; one accent',
    }, ['identical panels for different tasks', 'decorative knobs', 'meaningless scales'], [
      'The control deck of a music box that summons spirits: soft panels for "Melody", "Tempo" and "Summoning", each with its own scale, charcoal with a coral accent.',
      'A smart-bath app with rounded panels for "Bubbles", "Temperature" and "Rubber Duck Count", each with a tidy scale, pale and cheerful.',
      'A stage lighting app with three soft panels, "Intensity", "Color" and "Fade", clear scales and one strong main action, calm grey surfaces.',
    ]),
    U('R-UI-15', 'High-Contrast Quiet UI', 'quiet high-contrast app layout', 'quiet-contrast', {
      aesthetic: 'High-Contrast Quiet UI: strong contrast reserved for text, focus and actions while large areas of the screen stay silent.',
      subject_treatment: "Reserve strong contrast in the prompt's screen for reading, focus and actions, leaving wide calm areas around them; keep requested labels exact.",
      color_and_tone: 'White and charcoal with one optional accent, every grey still readable.',
      lighting_and_shadow: 'Separation through value and space on an even, quiet surface.',
      texture_and_material: 'Uniform surfaces, minimal borders and precise states with clear control edges.',
      camera_and_composition: 'Few attention zones, one clear main column and grouped secondary controls.',
      atmosphere_and_mood: 'Visual silence and decisiveness, energy focused on the current task.',
      rendering_and_quality: 'Focus stands out without the whole interface sharing one contrast level.',
      key_features: 'silent areas; reserved contrast; one main column; clear focus',
    }, ['minimalism that hides functions', 'uniform contrast', 'labels too faint'], [
      'The writing app of a novelist trapped in a lighthouse during a storm: one high-contrast column of text, a visible "Save" and an "Offline" state, almost nothing else.',
      'A breakup-text drafting app with one stark text box, a huge "Don\'t Send" button and wide silent space around it, black on white.',
      'An audio export panel with format, name and destination fields, a dominant "Export" action and generous empty space, white and charcoal.',
    ]),
    U('R-UI-16', 'Translucent Work Layers', 'translucent interface layer modifier', 'translucent-layers', {
      aesthetic: 'Translucent Work Layers: an interface modifier that separates stacked panels with soft transparency and background blur while foreground content stays sharp.',
      subject_treatment: "Change only the optical separation between the prompt's interface layers with transparency and blur, keeping content, layout and every label unchanged.",
      color_and_tone: 'Source colors kept, with an opaque enough backing behind critical text.',
      lighting_and_shadow: 'Depth separated by blur alone, calm and even across layers.',
      texture_and_material: 'Discreet translucent surfaces with readable edges, closer to frosted film than glossy glass.',
      camera_and_composition: 'Positions, sizes and stacking order of the input kept exactly.',
      atmosphere_and_mood: 'Calm depth with visible context, never competing with reading.',
      rendering_and_quality: 'Foreground text and controls stay crisp over complex backgrounds.',
      key_features: 'frosted layers; background blur; sharp foreground; unchanged layout',
    }, ['translucent text', 'contrast that depends on the background', 'layout changed by a finish'], [
      'Translucent layers applied to a spaceship navigation overlay floating above a nebula: panels frosted, every label exact and sharp, positions unchanged.',
      'A menu for a very fancy fish-tank app becomes frosted glass over the swimming fish, labels "Feed" and "Lights" still perfectly crisp.',
      'A floating inspector over a light and a dark canvas, same content and order, only transparency and blur changed, text always legible.',
    ], 'modifier'),
    U('R-UI-17', 'Timeline-Centered Workspace', 'timeline editor workspace profile', 'timeline-workspace', {
      aesthetic: 'Timeline-Centered Workspace: a workspace organized around one timeline where selection, events, properties and transport stay synchronized.',
      subject_treatment: "Build the prompt's workspace around a dominant timeline with a synchronized inspector and a stable transport; keep every requested time and label exact.",
      color_and_tone: 'Color by role or track with redundant cues, selection distinct from playback.',
      lighting_and_shadow: 'Flat design or minimal functional depth across the time scale.',
      texture_and_material: 'Clean time rulers, consistent marks and readable content blocks.',
      camera_and_composition: 'Dominant timeline, synchronized inspector and transport in a fixed place.',
      atmosphere_and_mood: 'Task continuity and temporal orientation in one connected workspace.',
      rendering_and_quality: 'One time position matches the selection, marker and properties.',
      key_features: 'dominant timeline; synced inspector; fixed transport; exact times',
    }, ['desynchronized events', 'ambiguous scale', 'invented clips'], [
      'A timeline workspace for choreographing a fireworks show over a castle: events at 0, 4 and 8 seconds, the 4-second rocket selected in the inspector, dark workspace.',
      'A timeline editor for planning a toddler\'s birthday party minute by minute, blocks for "Cake", "Chaos" and "Nap", one marker and an inspector, bright and exact.',
      'A 12-second animation editor with three four-second blocks, a shared marker and a properties panel, calm grey interface.',
    ], 'profile'),
    U('R-UI-18', 'Map-and-Inspector Workspace', 'map with linked inspector profile', 'map-inspector', {
      aesthetic: 'Map-and-Inspector Workspace: a spatial plan and a coordinated inspector keep context visible while one selected item is edited.',
      subject_treatment: "Link the prompt's spatial plan and a side inspector by a stable identity, keeping every requested coordinate, route and label exact.",
      color_and_tone: 'Map lower in contrast than the selection and its properties, states backed by shape.',
      lighting_and_shadow: 'Flat plan rendering that keeps the topology and every element visible.',
      texture_and_material: 'Clean map surfaces and lines with a crisp text inspector.',
      camera_and_composition: 'Wide central plan and a side inspector, the selection visible in both.',
      atmosphere_and_mood: 'Spatial orientation and local editing without losing the context.',
      rendering_and_quality: 'Selecting an item never moves it or creates a duplicate.',
      key_features: 'central plan; linked inspector; visible selection; exact coordinates',
    }, ['invented coordinates', 'inconsistent selection', 'panel that covers the edited object'], [
      'A map workspace for a zombie-proof city: nodes A, B and C linked by two routes, B selected with its properties in the inspector, nothing moved, pale plan.',
      'A seating-plan editor for a very tense family reunion, three tables on a plan and the selected table\'s guests in the inspector, clean and tactful.',
      'A small museum floor plan with rooms A, B and C connected, the chosen room\'s text in a side panel and a discreet search box.',
    ], 'profile'),
    U('R-UI-19', 'Single-Task Progressive UI', 'step-by-step flow screens profile', 'progressive-flow', {
      aesthetic: 'Single-Task Progressive UI: a flow that reveals controls step by step while keeping earlier choices, progress and the way back visible.',
      subject_treatment: "Show the prompt's flow as three steps, one primary task per step with a persistent summary and visible back path; keep requested labels exact.",
      color_and_tone: 'One accent for the current action, completed steps lighter and labeled.',
      lighting_and_shadow: 'Flat separation by hierarchy with every earlier step still in view.',
      texture_and_material: 'Sober surfaces and consistent controls, the same selection and error style.',
      camera_and_composition: 'One primary task per state, a persistent summary and a visible return path.',
      atmosphere_and_mood: 'Calm, reversible progress that never adds false urgency or pressure.',
      rendering_and_quality: 'Going back keeps decisions, and the summary matches the visible data.',
      key_features: 'three steps; persistent summary; back path; one task per step',
    }, ['wizard that loses data', 'hidden controls with no explanation', 'decorative steps'], [
      'A three-step flow for adopting a baby dragon: choose egg, sign fire waiver, confirm pickup, with a persistent summary and exact "Back" and "Continue" buttons.',
      'A three-step flow for returning a gift you secretly hated, "Choose Gift", "Invent Excuse" and "Confirm", each step keeping your earlier choices, polite and clear.',
      'A three-step export flow, format, size and destination, with the file name "studio-01.png" kept exact in the summary.',
    ], 'profile'),
    U('R-UI-20', 'Five-State UI Specimen', 'five-screen UI consistency sheet', 'five-state-specimen', {
      aesthetic: 'Five-State UI Specimen: one interface language shown across library, editor, search, settings and error screens with the same data.',
      subject_treatment: "Show the prompt's app in five screens, library, editor, empty search, settings and error, with the same names, selection and values in each.",
      color_and_tone: 'Identical color roles across all five screens, with one shared accent.',
      lighting_and_shadow: 'One depth model shared by every view, flat and consistent.',
      texture_and_material: 'The same borders, type and densities by role in every screen.',
      camera_and_composition: 'Five screens in a row with global controls and back paths in the same places.',
      atmosphere_and_mood: 'Product unity and a clear flow, one app rather than five pictures.',
      rendering_and_quality: 'Every view uses the same names, selection and test values.',
      key_features: 'five screens; same data; identical roles; fixed global controls',
    }, ['changed data between screens', 'missing states', 'a style that only works on one screen'], [
      'A five-screen specimen for a haunted-house booking app: library of houses, booking editor, empty search "No ghosts found", settings and a payment error, same selected house throughout.',
      'Five screens of a plant-watering app for forgetful people, library, editor, empty search, settings and the error "Your fern is disappointed", same data everywhere.',
      'A five-screen specimen of a small notes app, the same selected note in library, editor, search, settings and a save error, calm and consistent.',
    ], 'profile'),
  ],
};

export default spec;
