import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Science fiction cinema of the 1970s and 1980s: each preset names its film and director and
// rebuilds that film's production look (miniatures, sets, lighting, film stock). Cards stage
// original moments, never the film's own characters, vehicles or scenes. Alien lives in Horror 70s.
const T = ['scifi-70s-80s', 'scifi-cinema'];
const film70 = 'Seventies 35mm film grain with muted print color, soft lenses and halation.';
const film80 =
  'Eighties 35mm film grain with diffusion glow on highlights and rich saturated print color.';

const spec: Spec = {
  pack: 'pack_27',
  category: '8. Sci-Fi Cinema 70s & 80s',
  newCategory: { id: 'scifi-cinema-70s-80s' },
  updates: {},
  creates: [
    cr(
      'Solaris 1972 - Tarkovsky Ocean of Memory',
      'seventies science fiction cinema',
      [...T, 'solaris-72'],
      {
        look: 'Andrei Tarkovsky Solaris (1972) look: slow contemplative science fiction, a cluttered decaying space station, rain inside dachas, long takes and a living ocean of swirling mist.',
        subject:
          'stage the subject in long contemplative takes among decaying station rooms, rain and swirling ocean mist.',
        color: 'Muted greens, rain grey and occasional sepia monochrome.',
        light: 'Soft grey daylight and dim station lamps.',
        texture: film70,
        camera: 'Slow long takes and still contemplative framing.',
        mood: 'melancholy metaphysical longing',
        render: 'Authentic seventies Soviet art cinema frame.',
        key: 'Tarkovsky Solaris; long takes; station decay; living ocean',
        briefs: [
          'Inside a cluttered space station library with dust on the chandeliers, a retired psychologist in a wool cardigan waters a houseplant while rain falls gently from nowhere across the bookshelves. The ocean churns beyond the porthole. No readable text or logo.',
          'A wooden country house stands on a tiny island in a swirling misty ocean. A man stands at its door in the rain. No readable text or logo.',
          'A station corridor is strewn with paper streamers blowing from an air vent. Nobody has walked here in weeks. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Silent Running 1972 - Trumbull Space Greenhouse',
      'seventies science fiction cinema',
      [...T, 'silent-running'],
      {
        look: 'Douglas Trumbull Silent Running (1972) look: geodesic greenhouse domes on a freighter in deep space, lush forests under artificial light, small shuffling drones and gentle ecological melancholy.',
        subject: 'stage the subject in geodesic greenhouse domes of forest drifting in deep space.',
        color: 'Forest green under dome glass, freighter grey and space black.',
        light: 'Artificial growing light and distant starlight.',
        texture: film70,
        camera: 'Wide miniature shots of domes against space and intimate forest frames.',
        mood: 'gentle ecological melancholy',
        render: 'Authentic seventies ecological science fiction frame.',
        key: 'Silent Running domes; space forest; drones; ecology',
        avoid: ['small boxy walking drones with manipulator arms'],
        briefs: [
          'Beneath a geodesic dome drifting past Saturn, an old botanist in a monk-like robe teaches a rabbit to eat from her hand while the forest hums under growing lamps. No readable text or logo.',
          'A space freighter trails a line of glowing forest domes like lanterns. One dome is dark. No readable text or logo.',
          'Inside a glass dome, a single watering can rests beside a sapling. The stars wheel slowly overhead. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Westworld 1973 - Crichton Robot Resort',
      'seventies science fiction cinema',
      [...T, 'westworld-73'],
      {
        look: 'Michael Crichton Westworld (1973) look: sunlit seventies resort theme parks, dusty western towns, fluorescent control rooms full of technicians, pixelated robot point-of-view and cold malfunction.',
        subject:
          'stage the subject in sunlit theme-park towns or fluorescent seventies control rooms.',
        color: 'Dusty western gold and fluorescent control-room white.',
        light: 'Hot desert sun and flat fluorescent light.',
        texture: film70,
        camera: 'Wide western frames and control-room monitor walls.',
        mood: 'cold resort malfunction',
        render: 'Authentic seventies resort science fiction frame.',
        key: 'Westworld resort; western town; control room; malfunction',
        avoid: ['a bald gunslinger in black with silver eyes'],
        briefs: [
          'In a sunlit resort saloon, a vacationing dentist in a brand-new cowboy hat notices that the robot piano player keeps playing the same eight bars while staring straight at him. No readable text or logo.',
          'In a fluorescent control room, technicians in short-sleeved shirts watch a wall of monitors where every robot has stopped moving at once. Coffee cups tremble. No readable text or logo.',
          'A robot repair bay at night holds rows of faceless figures under white sheets. One sheet is lying on the floor. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Zardoz 1974 - Boorman Psychedelic Future Myth',
      'seventies science fiction cinema',
      [...T, 'zardoz'],
      {
        look: 'John Boorman Zardoz (1974) look: surreal seventies future myth, a giant floating stone head, Irish green countryside, crystal chambers, flowing robes and hallucinatory prism effects.',
        subject:
          'stage the subject in green Irish countryside with surreal floating monuments and crystal chambers.',
        color: 'Irish green, flesh red and crystal prism colors.',
        light: 'Soft overcast light and prism refractions.',
        texture: film70,
        camera: 'Wide landscape frames and prism-reflected interiors.',
        mood: 'surreal mythic strangeness',
        render: 'Authentic seventies psychedelic science fiction frame.',
        key: 'Zardoz floating head; Irish green; crystal prisms',
        avoid: ['a giant floating stone head', 'a man in a red bandolier and ponytail'],
        briefs: [
          'Over a green Irish valley, a giant floating stone teapot drifts silently above a crowd of farmers in flowing robes who raise their pitchforks and baskets toward it. No readable text or logo.',
          'Inside a crystal chamber, an ageless librarian in a white robe watches a thousand reflections of herself reading the same book. Each reflection is a little older. No readable text or logo.',
          'A stone stairway in a misty meadow leads up to nothing. A single sheep stands on the top step. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Dark Star 1974 - Carpenter Slacker Starship',
      'seventies science fiction cinema',
      [...T, 'dark-star'],
      {
        look: 'John Carpenter and Dan O’Bannon Dark Star (1974) look: shabby low-budget starship, cramped cockpit with blinking lights, bored bearded crew, talking bombs and deadpan cosmic comedy.',
        subject:
          'stage the subject in cramped shabby low-budget starship interiors with blinking lights.',
        color: 'Dingy cockpit orange, blinking red and space black.',
        light: 'Blinking panel lights and dim cabin glow.',
        texture: film70,
        camera: 'Cramped close cockpit framing.',
        mood: 'deadpan cosmic boredom',
        render: 'Authentic seventies low-budget science fiction frame.',
        key: 'Dark Star shabby ship; blinking panels; deadpan crew',
        avoid: ['a beach-ball alien with clawed feet'],
        briefs: [
          'In a shabby starship cockpit full of blinking buttons, a bearded astronaut in a stained T-shirt argues philosophy with the ship’s talking toaster while the rest of the crew plays cards. No readable text or logo.',
          'A cramped starship galley is piled with unwashed trays. One astronaut surfs a floating sheet of metal outside the window. No readable text or logo.',
          'A starship corridor lit by one flickering bulb holds a door covered in handwritten warnings. Something behind it squeaks. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Logans Run 1976 - Anderson Domed Mall Utopia',
      'seventies science fiction cinema',
      [...T, 'logans-run'],
      {
        look: 'Michael Anderson Logan’s Run (1976) look: seventies domed-city utopia shot in shopping malls, pastel tunics, glowing palm crystals, miniature domes and a wild overgrown Washington outside.',
        subject: 'stage the subject in seventies domed shopping-mall utopias with pastel tunics.',
        color: 'Pastel tunics, mall chrome and overgrown green.',
        light: 'Glowing mall light and domed skylight.',
        texture: film70,
        camera: 'Wide mall-atrium frames and miniature dome exteriors.',
        mood: 'pastel utopian unease',
        render: 'Authentic seventies utopia science fiction frame.',
        key: "Logan's Run domes; pastel tunics; mall utopia",
        avoid: ['a glowing red crystal in a palm', 'a silver chrome robot in an ice cave'],
        briefs: [
          'In a domed mall utopia, a pastel-tunic florist arranges bouquets under a skylight while every customer glances nervously at the glowing crystal in their palm. A fountain splashes in the atrium. No readable text or logo.',
          'Two escapees in pastel tunics step out of a dome into an overgrown city of vines. A deer stands on the steps of a ruined monument. No readable text or logo.',
          'A carousel of glowing figures rises toward the dome ceiling in a crowded arena. Nobody in the crowd looks away. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Close Encounters 1977 - Spielberg Suburban Awe',
      'seventies science fiction cinema',
      [...T, 'close-encounters'],
      {
        look: 'Steven Spielberg Close Encounters of the Third Kind (1977) look: seventies suburban Indiana, blinding lights through windows, glowing mothership chandeliers, mashed-potato obsession and awe.',
        subject:
          'stage the subject in seventies suburban homes and roads bathed in blinding lights from above.',
        color: 'Suburban brown, blazing white and warm orange.',
        light: 'Blinding light pouring through doors and windows.',
        texture: film70,
        camera: 'Low awe-struck angles into blazing light.',
        mood: 'wondrous suburban awe',
        render: 'Authentic seventies Spielberg science fiction frame.',
        key: 'Close Encounters blinding light; suburban awe; lights above',
        avoid: ['a colossal chandelier mothership over a butte', 'slender grey aliens'],
        briefs: [
          'In a seventies suburban kitchen at midnight, every appliance switches on at once and a retired mail carrier in pajamas stands at the open back door, bathed in blinding white light pouring from the sky. No readable text or logo.',
          'A line of cars stops on a dark country road as a cluster of colored lights hovers over the power lines. A child claps. No readable text or logo.',
          'A dining table holds a strange mountain sculpted from mashed potatoes. The family sits around it in silence. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Stalker 1979 - Tarkovsky Zone Sepia',
      'seventies science fiction cinema',
      [...T, 'stalker'],
      {
        look: 'Andrei Tarkovsky Stalker (1979) look: sepia-toned industrial wasteland and lush green Zone, flooded rooms, rusted machinery, dripping water and slow meditative tracking shots.',
        subject:
          'stage the subject in flooded ruins, rusted machinery and overgrown green wasteland.',
        color: 'Sepia monochrome and lush mossy green.',
        light: 'Soft overcast light through ruins.',
        texture: film70,
        camera: 'Slow meditative tracking shots.',
        mood: 'spiritual weary wonder',
        render: 'Authentic seventies Soviet art cinema frame.',
        key: 'Stalker Zone; flooded ruins; sepia; slow tracking',
        briefs: [
          'Through a flooded room of the Zone where syringes and coins glint under shallow water, an old guide in a padded coat throws a nut tied to a rag ahead of him to find the safe path. Moss covers the rusted machines. No readable text or logo.',
          'Three travelers rest in a dune of sand inside a vast ruined hall. Birds fly in slow circles overhead. No readable text or logo.',
          'A rusted handcar stands on overgrown rails leading into the mist of the Zone. A patient black dog waits beside it, ears raised toward something unseen. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Mad Max 1979 - Miller Outback Road Fury',
      'seventies action science fiction cinema',
      [...T, 'mad-max-79'],
      {
        look: 'George Miller Mad Max (1979) look: sun-bleached Australian outback roads, leather-clad highway patrol, souped-up muscle cars, wide-angle speed and near-future lawlessness.',
        subject:
          'stage the subject on sun-bleached outback highways with souped-up cars and wide-angle speed.',
        color: 'Bleached outback gold, asphalt grey and black leather.',
        light: 'Harsh Australian sun and heat haze.',
        texture: film70,
        camera: 'Low wide-angle speed shots on the road.',
        mood: 'dusty lawless fury',
        render: 'Authentic seventies Australian road film frame.',
        key: 'Mad Max outback; muscle cars; leather; speed',
        avoid: [
          'a black supercharged police interceptor',
          'a man in black leather with a leg brace',
        ],
        briefs: [
          'On a sun-bleached outback highway, a retired schoolteacher in a floral dress races her souped-up mustard-yellow station wagon past a biker gang, her knitting still on the passenger seat. Heat haze melts the horizon. No readable text or logo.',
          'A roadside diner in the outback has every window boarded but one. Engines rumble somewhere beyond the ridge. No readable text or logo.',
          'A single boot lies on a straight empty highway. Tire marks spiral around it into the dust. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Black Hole 1979 - Disney Gothic Starship',
      'seventies science fiction cinema',
      [...T, 'black-hole-79'],
      {
        look: 'Gary Nelson The Black Hole (1979) look: Disney gothic space opera, a cathedral-like starship lit like a glowing lattice, a swirling black hole vortex and sinister red robots.',
        subject:
          'stage the subject aboard a vast gothic lattice starship beside a swirling vortex.',
        color: 'Vortex red and orange, lattice gold and space black.',
        light: 'Glowing lattice light and swirling vortex glow.',
        texture: film70,
        camera: 'Wide matte-painted starship exteriors.',
        mood: 'gothic cosmic doom',
        render: 'Authentic seventies Disney space opera frame.',
        key: 'Black Hole gothic starship; lattice glow; vortex',
        avoid: ['a red robot with spinning blades', 'a small floating robot with round eyes'],
        briefs: [
          'Aboard a cathedral-like starship glowing like a golden lattice beside a swirling red vortex, a lost botanist wanders a vast observation deck while hooded crew figures glide past without a word. No readable text or logo.',
          'A tiny scout ship approaches a giant lit starship in total silence. Every window is lit and nobody answers. No readable text or logo.',
          'A swirling red and orange vortex fills the whole sky beyond the observation glass. A single broken antenna drifts slowly toward its glowing center. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Escape from New York 1981 - Carpenter Prison City',
      'eighties science fiction cinema',
      [...T, 'escape-ny'],
      {
        look: 'John Carpenter Escape from New York (1981) look: night-time Manhattan turned prison island, burning barrels, dark streets, green wireframe glider displays and synth dread.',
        subject: 'stage the subject in dark burning ruined city streets at night.',
        color: 'Night blue-black, barrel fire orange and wireframe green.',
        light: 'Burning barrels and harsh searchlights.',
        texture: film80,
        camera: 'Low anamorphic night frames.',
        mood: 'grim nocturnal survival',
        render: 'Authentic eighties Carpenter frame.',
        key: 'Escape from NY prison city; burning barrels; wireframe',
        avoid: ['an eyepatched mercenary in a snakeskin jacket'],
        briefs: [
          'In a burning-barrel-lit prison city, a retired cab driver in a flat cap still runs his battered yellow taxi through the ruined avenues, a chandelier strapped to its roof. No readable text or logo.',
          'A glider lands on a dark skyscraper rooftop with a green wireframe display glowing in its cockpit. The city below is black. No readable text or logo.',
          'An empty theater in the ruined city stages a show for a crowd of prisoners. The performer on stage is a nervous accountant. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Blade Runner 1982 - Scott Neon Rain Noir',
      'eighties science fiction cinema',
      [...T, 'blade-runner-82'],
      {
        look: 'Ridley Scott Blade Runner (1982) look: rain-soaked neon Los Angeles 2019, towering pyramids, smoky shafts of light through blinds, crowded markets and Syd Mead future noir.',
        subject: 'stage the subject in rainy neon future streets with smoky light shafts.',
        color: 'Neon amber, cyan and deep night blue.',
        light: 'Smoky shafts through blinds and neon rain.',
        texture: film80,
        camera: 'Low anamorphic future noir framing.',
        mood: 'melancholy neon noir',
        render: 'Authentic eighties future noir frame.',
        key: 'Blade Runner neon rain; smoky shafts; future noir',
        avoid: [
          'a flying police spinner car',
          'an origami unicorn',
          'a trench-coated detective with a heavy blaster',
        ],
        briefs: [
          'In a rain-soaked neon night market, an elderly noodle cook in a clear plastic poncho serves steaming bowls from under a glowing umbrella while giant billboards flicker above the crowd. No readable text or logo.',
          'Smoky shafts of light fall through the blinds of a cluttered apartment. A lone toymaker repairs a mechanical bird at a desk. No readable text or logo.',
          'A rooftop at dawn drips with rain beside a huge glowing pyramid. A single white dove flies away. No readable text or logo.',
        ],
      },
    ),
    cr('Tron 1982 - Lisberger Glowing Grid', 'eighties science fiction cinema', [...T, 'tron-82'], {
      look: 'Steven Lisberger Tron (1982) look: backlit glowing circuit-line costumes on black, early computer-generated grids, light cycles leaving walls and neon digital landscapes.',
      subject: 'stage the subject with glowing circuit lines on black inside a neon digital grid.',
      color: 'Black void with glowing cyan, orange and red lines.',
      light: 'Backlit glowing lines on black.',
      texture: 'Early-eighties backlit animation composited over black-and-white film.',
      camera: 'Wide grid vistas and low speed shots.',
      mood: 'luminous digital adventure',
      render: 'Authentic early-eighties digital world frame.',
      key: 'Tron glowing circuits; digital grid; light trails',
      avoid: ['a light cycle', 'a glowing identity disc', 'a red-lined master control face'],
      briefs: [
        'On a glowing neon grid, a retired librarian program with cyan circuit lines on her cardigan sorts glowing data books onto a shelf that stretches to the horizon. No readable text or logo.',
        'Two programs share a glowing picnic on a floating platform above the grid. Their lunch is a cube of light. No readable text or logo.',
        'A glowing orange wall of light cuts across an empty grid plain. It is slowly curling. No readable text or logo.',
      ],
    }),
    cr(
      'Liquid Sky 1982 - Tsukerman New Wave Neon',
      'eighties science fiction cinema',
      [...T, 'liquid-sky'],
      {
        look: 'Slava Tsukerman Liquid Sky (1982) look: New York new wave club culture, fluorescent face paint, angular shoulder pads, thermal-vision alien point of view and cheap psychedelic effects.',
        subject:
          'stage the subject in new wave club fashion with fluorescent face paint and angular silhouettes.',
        color: 'Fluorescent pink, electric blue and thermal rainbow.',
        light: 'Club spotlights and black light.',
        texture: film80,
        camera: 'Stagey frames and thermal-vision inserts.',
        mood: 'cold new wave alienation',
        render: 'Authentic early-eighties underground science fiction frame.',
        key: 'Liquid Sky new wave; fluorescent paint; thermal view',
        briefs: [
          'On a Manhattan penthouse rooftop at night, a new wave model with fluorescent geometric face paint and angular shoulder pads stares at a tiny flying saucer hovering over a flower pot. No readable text or logo.',
          'A club crowd in neon makeup dances under black light while the scene flickers into rainbow thermal vision. No readable text or logo.',
          'An empty loft holds a mirror covered in fluorescent lipstick shapes. A tiny glowing dot hovers near the window. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Dune 1984 - Lynch Baroque Desert Empire',
      'eighties science fiction cinema',
      [...T, 'dune-84'],
      {
        look: 'David Lynch Dune (1984) look: baroque science fiction, ornate imperial halls, steam and brass, desert planets under orange skies, strange guild navigators and heavy ornate costume.',
        subject:
          'stage the subject in baroque imperial halls of brass and steam or orange desert plains.',
        color: 'Desert orange, brass gold and imperial black.',
        light: 'Heavy stage light, desert sun and steam haze.',
        texture: film80,
        camera: 'Formal baroque framing and wide desert matte shots.',
        mood: 'heavy baroque strangeness',
        render: 'Authentic eighties baroque science fiction frame.',
        key: 'Lynch Dune baroque; brass halls; orange desert',
        avoid: [
          'giant sandworms',
          'a stillsuit with a nose tube',
          'a bloated floating guild navigator',
        ],
        briefs: [
          'In an ornate brass throne hall filled with steam, a court tailor on a ladder measures a towering nobleman for a coat of black armor plates while courtiers in veils whisper along the walls. No readable text or logo.',
          'On an orange desert plain, a caravan of cloaked traders walks in an irregular rhythm across the dunes. A distant rumble shakes the sand. No readable text or logo.',
          'A brass water reservoir hidden in a desert cave glows under lamps. Every drop is counted. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Brazil 1985 - Gilliam Retro Bureaucracy',
      'eighties science fiction cinema',
      [...T, 'brazil'],
      {
        look: 'Terry Gilliam Brazil (1985) look: retro-futurist bureaucratic dystopia, ducts everywhere, tiny monitors on huge desks, forties fashion, wide-angle lenses and absurd dream flights.',
        subject:
          'stage the subject in cluttered retro bureaucratic offices wrapped in ducts, shot wide-angle.',
        color: 'Grey bureaucratic tones, rust and faded forties color.',
        light: 'Cold fluorescent office light and haze.',
        texture: film80,
        camera: 'Distorting wide-angle lenses and dutch tilts.',
        mood: 'absurd bureaucratic dread',
        render: 'Authentic eighties Gilliam dystopia frame.',
        key: 'Brazil ducts; tiny monitors; wide-angle absurdity',
        avoid: ['a winged armored knight in the sky'],
        briefs: [
          'In a vast grey records office, a clerk in a forties suit squints at a tiny magnified monitor on a giant desk while ducts snake over every wall and a colleague steals his desk through the partition. No readable text or logo.',
          'A plumber repairs a burst duct in a family apartment while paper forms spill out of it like snow. The family keeps eating dinner. No readable text or logo.',
          'A long grey corridor of identical doors disappears into haze. A single forgotten form flutters on the floor. No readable text or logo.',
        ],
      },
    ),
    cr(
      'Back to the Future 1985 - Zemeckis Suburban Time Warp',
      'eighties science fiction cinema',
      [...T, 'back-to-the-future'],
      {
        look: 'Robert Zemeckis Back to the Future (1985) look: sunny eighties and fifties American small-town squares, a courthouse clock tower, garage workshops full of gadgets and electric blue time sparks.',
        subject:
          'stage the subject in sunny small-town squares and cluttered garage workshops with electric sparks.',
        color: 'Sunny Americana, fifties pastel and electric blue.',
        light: 'Bright suburban daylight and electric flashes.',
        texture: film80,
        camera: 'Classic Hollywood coverage with low heroic angles.',
        mood: 'zippy nostalgic adventure',
        render: 'Authentic eighties Amblin frame.',
        key: 'Back to the Future town square; garage gadgets; time sparks',
        avoid: [
          'a stainless steel gull-wing sports car',
          'a wild-haired scientist in a radiation suit',
        ],
        briefs: [
          'In a cluttered suburban garage full of clocks and wires, a grandmother in a bowling shirt tests a homemade time device on a toaster that vanishes in a crackle of electric blue sparks. No readable text or logo.',
          'A fifties town square fills with electric sparks as a lightning bolt strikes the clock tower. A soda jerk stares from the diner. No readable text or logo.',
          'Two burning tire tracks run straight across an empty parking lot. A small dog sits between them. No readable text or logo.',
        ],
      },
    ),
    cr(
      'RoboCop 1987 - Verhoeven Corporate Satire',
      'eighties science fiction cinema',
      [...T, 'robocop-87'],
      {
        look: 'Paul Verhoeven RoboCop (1987) look: gritty eighties Detroit, corporate glass towers, satirical television ads, steel-grey armor, practical gore effects and cynical satire.',
        subject:
          'stage the subject in gritty urban decay and sleek corporate boardrooms with satirical edge.',
        color: 'Steel grey, corporate blue and grimy brown.',
        light: 'Hard urban light and boardroom fluorescents.',
        texture: film80,
        camera: 'Low wide-angle action and TV-screen inserts.',
        mood: 'cynical violent satire',
        render: 'Authentic eighties Verhoeven frame.',
        key: 'RoboCop Detroit; corporate satire; steel armor',
        avoid: [
          'a steel-grey armored police cyborg with a visor',
          'a two-legged enforcement droid',
        ],
        briefs: [
          'In a glass corporate boardroom, executives applaud a presentation of a new cybernetic mail carrier who immediately delivers every letter to the wrong floor at great speed. No readable text or logo.',
          'A cheerful TV ad plays in a grimy bar showing a family board game about urban warfare. Nobody watches. No readable text or logo.',
          'A rain-soaked abandoned steel mill holds a single glowing vending machine among the rusted furnaces. It still takes coins and still thanks every customer. No readable text or logo.',
        ],
      },
    ),
    cr(
      'They Live 1988 - Carpenter Black-and-White Truth',
      'eighties science fiction cinema',
      [...T, 'they-live'],
      {
        look: 'John Carpenter They Live (1988) look: grubby eighties Los Angeles in color, switching to stark black-and-white through special sunglasses revealing hidden commands and skull-faced elites.',
        subject:
          'stage the subject in grubby eighties streets split between color reality and stark black-and-white truth.',
        color: 'Grubby eighties color against stark black-and-white.',
        light: 'Flat daylight and harsh contrast.',
        texture: film80,
        camera: 'Point-of-view reveals through lenses.',
        mood: 'paranoid satirical awakening',
        render: 'Authentic eighties Carpenter satire frame.',
        key: 'They Live sunglasses reveal; black-and-white truth',
        avoid: ['skull-faced people in suits', 'a man in a flannel shirt with a shotgun'],
        briefs: [
          'On a busy eighties shopping street, a construction worker lifts a pair of plain sunglasses and half the frame turns stark black and white, revealing the pigeons are all wearing tiny ties. No readable text or logo.',
          'A shantytown under a freeway gathers around a TV that flickers into black and white. Nobody else notices. No readable text or logo.',
          'A pair of cheap sunglasses rests on a trash can lid in an alley. One lens shows a different world. No readable text or logo.',
        ],
      },
    ),
    cr(
      'The Abyss 1989 - Cameron Deep Sea Glow',
      'eighties science fiction cinema',
      [...T, 'the-abyss'],
      {
        look: 'James Cameron The Abyss (1989) look: claustrophobic underwater drilling rig, flooded corridors, diving helmets with lights, deep trench blackness and glowing translucent aliens.',
        subject:
          'stage the subject in claustrophobic undersea rigs and deep black trenches lit by helmet lamps.',
        color: 'Deep trench black, helmet white and glowing cyan.',
        light: 'Helmet lamps and bioluminescent glow.',
        texture: film80,
        camera: 'Underwater diver framing and cramped rig corridors.',
        mood: 'claustrophobic deep wonder',
        render: 'Authentic late-eighties deep sea science fiction frame.',
        key: 'The Abyss undersea rig; helmet lamps; glowing aliens',
        avoid: ['a water tentacle with a face', 'a glowing translucent angelic alien'],
        briefs: [
          'In a flooded corridor of an undersea drilling rig, a cook in a diving helmet carries a birthday cake through waist-deep water while strange cyan lights drift past the porthole. No readable text or logo.',
          'A diver descends into a black trench with a single helmet lamp. Far below, a faint glowing city answers. No readable text or logo.',
          'A rig mess hall at night has every porthole glowing blue. The crew’s coffee cups are all trembling. No readable text or logo.',
        ],
      },
    ),
  ],
};

export default spec;
