import type { Spec } from '../tools/apply';
import { ga, keep } from './_authors';

// Video game pass, psychological and tactical gameplay: each preset names its game, studio and
// year and states the real render technique and camera. Presets that duplicated a neighbor
// (the second jungle stealth, the second cargo trek) move to other games with the same genre.
// Intentional-v1 presets (SP12-081 to SP12-098) keep their own policy and stay out of this pass.
const spec: Spec = {
  pack: 'pack_12',
  category: '11. Psychological & Tactical Gameplay',
  updates: Object.fromEntries([
    ga('SP12-207', 'Silent Hill 1999 - Team Silent PS1 Fog', {
      look: 'Team Silent Silent Hill (1999) look: PS1 horror with fog hiding a tiny draw distance, crackling radio, low-poly town streets, darkness and grainy flashlight.',
      subject: 'render people as low-poly PS1 figures in the fog.',
      color: 'White fog and rust.',
      light: 'Fog and flashlight cone.',
      texture: 'Low-poly PS1 textures.',
      camera: 'Third-person fog view.',
      mood: 'unknowable foggy dread',
      render: 'Authentic PS1 horror screen.',
      key: 'Silent Hill 1999 fog; low-poly; radio',
      avoid: ['a pyramid-helmeted executioner'],
      briefs: [
        'Walking down a street swallowed by white fog, an original man clutches a crackling radio as a towering silhouette on stilt-like legs drags a squeaking hospital gurney just out of sight. No readable text or logo.',
        keep('SP12-207')[1],
        keep('SP12-207')[2],
      ],
    }),
    ga('SP12-208', 'Silent Hill Homecoming 2008 - Double Helix Peeling Otherworld', {
      look: 'Double Helix Silent Hill: Homecoming (2008) look: walls peeling away like burning paper into a rusted otherworld of grates and chain link, sirens and industrial rot.',
      subject: 'render people as survivors caught between normal rooms and rust.',
      color: 'Rust red, ash and dirty metal.',
      light: 'Siren-lit darkness.',
      texture: 'Peeling paper, rust and grates.',
      camera: 'Third-person transition view.',
      mood: 'screaming nightmare shift',
      render: 'Authentic horror transition screen.',
      key: 'Homecoming peeling walls; rust otherworld; sirens',
    }),
    ga('SP12-209', 'P.T. 2014 - Kojima Productions Looping Hallway', {
      look: 'Kojima Productions P.T. (2014) look: photoreal first-person L-shaped suburban hallway that repeats endlessly, a radio, family photos and flickering light.',
      subject: 'render people as unseen first-person visitors in a domestic hallway.',
      color: 'Dim beige, sickly green and shadow.',
      light: 'Flickering hallway bulb.',
      texture: 'Photoreal domestic surfaces.',
      camera: 'First-person hallway view.',
      mood: 'looping domestic terror',
      render: 'Authentic photoreal horror screen.',
      key: 'P.T. looping hallway; photoreal; dread',
    }),
    ga('SP12-210', 'Crysis 2007 - Crytek Jungle Stealth', {
      look: 'Crytek Crysis (2007) look: first-person tropical island jungle in lush CryEngine detail, dense foliage, cloaking stealth, patrols and god rays.',
      subject: 'render people as soldiers in face paint and jungle gear.',
      color: 'Lush jungle green and sun gold.',
      light: 'God rays through foliage.',
      texture: 'Dense photoreal foliage.',
      camera: 'First-person jungle view.',
      mood: 'tense predatory stealth',
      render: 'Authentic CryEngine jungle screen.',
      key: 'Crysis jungle; foliage; stealth',
      avoid: ['a ribbed nanosuit'],
    }),
    ga('SP12-211', 'Metal Gear Solid 1998 - Konami Shadow Base', {
      look: 'Konami Metal Gear Solid (1998) look: PS1 low-poly stealth at a snowy Alaskan base, overhead camera, searchlights, crates, guards and a giant walking tank.',
      subject: 'render people as low-poly PS1 soldiers and guards.',
      color: 'Snow white, steel grey and night blue.',
      light: 'Searchlights at night.',
      texture: 'Low-poly PS1 textures.',
      camera: 'Overhead stealth camera.',
      mood: 'tense cold infiltration',
      render: 'Authentic PS1 stealth screen.',
      key: 'MGS1 base; searchlights; walking tank',
      avoid: ['a soldier in a sneaking suit with a bandana', 'existing Metal Gear walkers'],
    }),
    ga('SP12-212', "Jusant 2023 - Don't Nod Climbing Pilgrimage", {
      look: "Don't Nod Jusant (2023) look: stylized painterly climbing up a huge tower in a drought world, a small climber with a pack, ropes, moss and whale-like creatures drifting in the air.",
      subject: 'render people as small stylized climbers with big packs.',
      color: 'Soft stone, moss green and sky blue.',
      light: 'Soft painterly light.',
      texture: 'Painterly stone and cloth.',
      camera: 'Wide climbing view.',
      mood: 'quiet meditative ascent',
      render: 'Authentic painterly climbing screen.',
      key: 'Jusant climbing; drought world; floating whales',
    }),
    ga('SP12-213', 'Layers of Fear 2016 - Bloober Team Shifting Rooms', {
      look: 'Bloober Team Layers of Fear (2016) look: first-person Victorian house that shifts behind you, a painter descending into madness, warped rooms and dripping paint.',
      subject: 'render people as haunted artists seen from first person.',
      color: 'Victorian brown, oil paint and shadow.',
      light: 'Candle and warped light.',
      texture: 'Oil paint, wood and plaster.',
      camera: 'First-person warped view.',
      mood: 'unraveling artistic madness',
      render: 'Authentic psychological horror screen.',
      key: 'Layers of Fear shifting rooms; paint; madness',
    }),
    ga('SP12-214', 'Condemned 2005 - Monolith Derelict First-Person', {
      look: 'Monolith Productions Condemned: Criminal Origins (2005) look: first-person grimy derelict buildings, forensic flashlight, melee pipes and gaunt figures in darkness.',
      subject: 'render people as gaunt figures in a grimy derelict interior.',
      color: 'Grimy green, flashlight white and rust.',
      light: 'Flashlight in darkness.',
      texture: 'Grimy decay textures.',
      camera: 'First-person flashlight view.',
      mood: 'grimy lurking dread',
      render: 'Authentic mid-2000s horror screen.',
      key: 'Condemned grime; flashlight; derelict',
    }),
    ga('SP12-215', 'Splinter Cell Chaos Theory 2005 - Ubisoft Montreal Night Stealth', {
      look: 'Ubisoft Montreal Splinter Cell: Chaos Theory (2005) look: third-person stealth in rain and darkness, light meters, green night-vision goggles and guards with flashlights.',
      subject: 'render people as stealth operatives in dark gear.',
      color: 'Night black, goggle green and rain blue.',
      light: 'Darkness with flashlight sweeps.',
      texture: 'Wet gear and rain.',
      camera: 'Third-person stealth view.',
      mood: 'tense silent infiltration',
      render: 'Authentic stealth screen.',
      key: 'Splinter Cell darkness; goggles; rain',
      avoid: ['three green night-vision lenses'],
    }),
    ga('SP12-216', 'LSD Dream Emulator 1998 - Asmik Ace PS1 Dreams', {
      look: 'Asmik Ace LSD: Dream Emulator (1998) look: surreal PS1 dream exploration, low-poly pastel worlds, impossible links between places and uncanny textures.',
      subject: 'render people as low-poly dream figures.',
      color: 'Pastel pink, sky blue and surreal colors.',
      light: 'Flat dream light.',
      texture: 'Warped PS1 textures.',
      camera: 'First-person dream view.',
      mood: 'uncanny dreamy drift',
      render: 'Authentic PS1 dream screen.',
      key: 'LSD Dream Emulator; pastel; surreal PS1',
    }),
    ga('SP12-217', 'Dear Esther 2012 - The Chinese Room Island', {
      look: 'The Chinese Room Dear Esther (2012) look: first-person walk across a lonely Hebridean island, lighthouses, storms, caves and melancholic narration.',
      subject: 'render people as lonely wanderers seen from first person.',
      color: 'Storm grey, sea teal and lamp gold.',
      light: 'Stormy light with lamp beams.',
      texture: 'Realistic rock and sea spray.',
      camera: 'First-person lamp room view.',
      mood: 'melancholic windswept isolation',
      render: 'Authentic walking-sim screen.',
      key: 'Dear Esther island; lighthouse; storm',
    }),
    ga('SP12-218', 'Deathloop 2021 - Arkane Lyon Retro Loop', {
      look: 'Arkane Lyon Deathloop (2021) look: sixties retro-futurist island party in a time loop, mod colors, masked partygoers and stylized painterly art.',
      subject: 'render people as masked sixties partygoers.',
      color: 'Mod orange, teal and gold.',
      light: 'Party lights at midnight.',
      texture: 'Stylized painterly surfaces.',
      camera: 'First-person party view.',
      mood: 'stylish looping intrigue',
      render: 'Authentic stylized loop screen.',
      key: 'Deathloop sixties; masks; time loop',
    }),
    ga('SP12-219', 'STALKER Shadow of Chernobyl 2007 - GSC Zone Forest', {
      look: 'GSC Game World S.T.A.L.K.E.R.: Shadow of Chernobyl (2007) look: first-person survival in the Zone, misty forests, anomalies, rusted Soviet ruins and snipers.',
      subject: 'render people as stalkers in hoods and gas masks.',
      color: 'Grey-green mist and rust.',
      light: 'Overcast mist.',
      texture: 'Grimy late-2000s textures.',
      camera: 'First-person scope view.',
      mood: 'paranoid patient survival',
      render: 'Authentic late-2000s survival screen.',
      key: 'STALKER Zone; mist; anomalies',
    }),
    ga('SP12-220', 'Yomawari Night Alone 2015 - Nippon Ichi Night Walk', {
      look: 'Nippon Ichi Software Yomawari: Night Alone (2015) look: a small chibi girl with a flashlight walking a dark Japanese suburb at night, cute art and creeping spirits.',
      subject: 'render people as small chibi figures with flashlights.',
      color: 'Night blue with flashlight yellow.',
      light: 'Flashlight cone in darkness.',
      texture: 'Soft hand-drawn art.',
      camera: 'Top-down night walk view.',
      mood: 'cute creeping dread',
      render: 'Authentic chibi horror screen.',
      key: 'Yomawari night walk; chibi; spirits',
    }),
  ]),
};

export default spec;
