import type { Spec } from '../tools/apply';
import { cr } from './_authors';

// Movie posters: poster traditions named after the designers, studios and national schools that
// defined them. Cards invent original films; requested titles and credits stay exact when asked.
const T = ['movie-poster'];
const P = { requestedText: true } as const;

const spec: Spec = {
  pack: 'pack_26',
  category: '2. Movie Posters',
  newCategory: { id: 'movie-posters' },
  updates: {},
  creates: [
    cr('Saul Bass - Cut-Paper Title Poster', 'film poster design', [...T, 'saul-bass'], {
      ...P,
      look: 'Saul Bass film poster look: bold cut-paper shapes, fragmented silhouettes, two or three flat colors, jagged hand-cut edges and one powerful symbolic image.',
      subject:
        'reduce the subject to a bold cut-paper silhouette or symbol with jagged hand-cut edges.',
      color: 'Two or three flat colors, often orange, black and white.',
      light: 'No modeled light, only flat cut shapes.',
      texture: 'Cut paper with slightly rough hand-cut edges.',
      camera: 'One central symbolic image with strong negative space and a title band.',
      mood: 'tense graphic intrigue',
      render: 'Bold minimal cut-paper poster design.',
      key: 'Saul Bass cut paper; symbolic silhouette; flat color; jagged edges',
      briefs: [
        'A single cut-paper ear built from jagged black piano keys floats on a blazing orange field, the poster of a thriller about a piano tuner who hears a murder through the wall, title "THE TUNER" set exact in hand-cut letters.',
        'A cut-paper hand made of broken keys reaches into a white spiral staircase on a flat red background, poster of a heist caper titled "SEVEN LOCKS", every edge ragged and hand-cut.',
        'One tall black cut-paper lighthouse casts a single orange beam across an empty white field while a small bird is cut from the beam itself, poster of a quiet drama titled "KEEPER".',
      ],
    }),
    cr('Drew Struzan - Airbrushed Blockbuster Montage', 'film poster painting', [...T, 'struzan'], {
      ...P,
      look: 'Drew Struzan poster look: airbrushed and colored-pencil montage of heroic faces, glowing edges, action vignettes and warm cinematic nostalgia.',
      subject:
        'paint the subject as heroic airbrushed portraits and vignettes collaged in a glowing montage.',
      color: 'Warm amber, sunset orange and deep blue with glowing white edges.',
      light: 'Glowing backlit rim light around every figure.',
      texture: 'Airbrush gradients with colored-pencil highlights on toned board.',
      camera: 'Stacked montage of large faces and small action scenes.',
      mood: 'nostalgic blockbuster adventure',
      render: 'Airbrushed blockbuster montage poster painting.',
      key: 'Struzan airbrush montage; glowing edges; heroic faces; vignettes',
      avoid: ['existing movie heroes'],
      briefs: [
        'A retired librarian’s airbrushed face glows above a montage of a collapsing temple, a biplane and a giant bookworm, all rimmed in warm light, blockbuster poster for "THE LAST ENCYCLOPEDIA" with its title set exact.',
        'A weathered cook and her robot mule gaze heroically out of an airbrushed montage of desert moons and train robberies, space-western poster titled "DUST OF SATURN" in glowing letters.',
        'A glowing airbrushed kite drifts over a montage of rooftops, grandparents and sunset faces, family film poster titled "HIGH WIND" with every edge shimmering white.',
      ],
    }),
    cr('Bob Peak - Seventies Painted Epic Poster', 'film poster painting', [...T, 'bob-peak'], {
      ...P,
      look: 'Bob Peak poster look: expressive seventies painted epics with vivid streaked color, dramatic silhouettes, dissolving brushwork and mythic scale.',
      subject:
        'paint the subject in bold expressive silhouettes that dissolve into streaks of vivid color.',
      color: 'Vivid sunset orange, magenta, violet and black silhouettes.',
      light: 'Burning skies and dramatic backlight.',
      texture: 'Loose expressive brushwork and color streaks.',
      camera: 'Epic silhouettes over huge painted skies.',
      mood: 'mythic dramatic grandeur',
      render: 'Expressive seventies painted epic poster.',
      key: 'Bob Peak streaked color; silhouettes; burning skies; epic scale',
      briefs: [
        'A boatman’s silhouette stands tall against a burning magenta and orange sky as brushstrokes dissolve him into streaks of color over the jungle river, epic poster titled "UPRIVER" painted across the sky.',
        'A trapeze artist’s silhouette swings across a violet sky that bursts into expressive streaks of red and gold, circus drama poster titled "THE LONG FALL" in painterly letters.',
        'A single soldier’s helmet silhouette sinks into a painted orange sunset streaked with smoke and color, war film poster titled "LAST LIGHT" floating above the horizon.',
      ],
    }),
    cr(
      'Polish Poster School - Surreal Film Poster',
      'film poster design',
      [...T, 'polish-school'],
      {
        ...P,
        look: 'Polish Poster School look (Jan Lenica, Franciszek Starowieyski, Waldemar Świerzy): surreal painted metaphors, hand-lettering, grotesque symbolic imagery and expressive painterly craft.',
        subject:
          'transform the subject into a surreal painted visual metaphor with strange anatomy.',
        color: 'Bold unexpected colors with painterly shading.',
        light: 'Painterly flat light and eerie glows.',
        texture: 'Gouache painting and hand-drawn line.',
        camera: 'Single central surreal metaphor image.',
        mood: 'surreal unsettling wit',
        render: 'Surreal painted film poster.',
        key: 'Polish school surrealism; visual metaphor; hand craft',
        briefs: [
          'A jealous husband’s head opens like a birdcage and a dozen painted eyes fly out on moth wings across a pale yellow ground, Polish comedy poster titled "ZAZDROŚĆ" hand-lettered exactly.',
          'A grandfather clock with a human ear instead of a face drips painted time onto a black floor, horror poster titled "GODZINA" in crooked hand lettering above it.',
          'A single wooden chair grows roots into a red painted floor while its shadow takes the shape of a sleeping woman, drama poster titled "CZEKANIE" lettered by hand.',
        ],
      },
    ),
    cr('Japanese Chirashi Showa Film Flyer', 'Japanese film flyer', [...T, 'chirashi'], {
      ...P,
      look: 'Japanese chirashi film flyer look from the Showa era: dense collage of stills and painted art, dramatic diagonal layouts, bold vertical title blocks and printed halftone.',
      subject: 'collage the subject from painted art and photo stills in a dense diagonal layout.',
      color: 'Punchy printed reds, yellows and black with halftone.',
      light: 'Printed flat light with dramatic contrast.',
      texture: 'Halftone print, slight misregistration and paper grain.',
      camera: 'Dense diagonal collage layout with vertical title areas.',
      mood: 'punchy promotional energy',
      render: 'Showa-era film flyer print.',
      key: 'Chirashi collage; diagonals; halftone; vertical title blocks',
      briefs: [
        'A giant snail crushes a bullet train while screaming commuters and a heroic noodle chef tilt across bold diagonal bands, Showa monster flyer with the vertical title "巨大カタツムリ" set exact.',
        'Painted faces and halftone stills of a rainy gambling den tilt across a dense flyer for a yakuza drama titled "雨の賭場", red and yellow bands slicing the layout.',
        'A couple shares one umbrella inside diagonal bands of printed red and yellow halftone, romance flyer titled "雨宿り" in a bold vertical block.',
      ],
    }),
    cr(
      'Bollywood Hand-Painted Billboard Poster',
      'Indian film poster painting',
      [...T, 'bollywood'],
      {
        ...P,
        look: 'Bollywood hand-painted film billboard look: saturated oil paint, giant heroic faces, dramatic emotional expressions, flying action scenes and dense colorful composition.',
        subject:
          'paint the subject as giant heroic faces and dramatic action vignettes in saturated oil paint.',
        color: 'Saturated magenta, turquoise, gold and flame orange.',
        light: 'Dramatic glowing highlights on faces.',
        texture: 'Thick hand-painted oil on billboard panels.',
        camera: 'Huge faces dominating with small action scenes around.',
        mood: 'melodramatic heroic spectacle',
        render: 'Hand-painted Bollywood billboard.',
        key: 'Bollywood hand-painted; giant faces; melodrama; saturated oil',
        briefs: [
          'A grieving mustached postman’s giant tearful face towers above a motorcycle leaping over a wedding procession in blazing magenta and gold, hand-painted billboard for "DAAK BABU" with the title set exact.',
          'Two lovers’ giant glowing faces float above a dance on the roof of a moving train, saturated oil billboard for the musical "RAIL ROMANCE" painted in huge letters.',
          'A single giant painted eye with a glistening tear dominates a turquoise billboard above a busy street, melodrama titled "AANSOO" painted along the bottom.',
        ],
      },
    ),
    cr(
      'Tom Chantrell - Hammer Horror Painted Poster',
      'horror film poster painting',
      [...T, 'hammer'],
      {
        ...P,
        look: 'Tom Chantrell and Hammer Films poster look: lurid painted gothic horror, screaming heroines, looming monsters, castles and blood-red sixties color.',
        subject: 'paint the subject in lurid gothic melodrama with looming menace.',
        color: 'Blood red, sickly green, black and pale flesh tones.',
        light: 'Lurid moonlight and candle glow.',
        texture: 'Painted gouache and oil with bold outlines.',
        camera: 'Looming menace over screaming figures and castles.',
        mood: 'lurid gothic thrill',
        render: 'Painted sixties horror poster.',
        key: 'Hammer lurid paint; gothic castles; looming monsters; blood red',
        briefs: [
          'A looming cardinal with glowing green eyes towers over a screaming governess as a castle burns behind them in lurid red paint, Hammer-style poster titled "THE CARDINAL’S CURSE" set exact.',
          'A village baker screams as a giant clawed shadow falls across her bread ovens under a full moon, werewolf poster titled "THE BAKER’S MOON" in dripping letters.',
          'A single candelabra glows on a gothic staircase painted in blood red and sickly green, horror poster titled "THE WAITING STAIR" above a closed door.',
        ],
      },
    ),
    cr('Renato Casaro - Italian Painted Action Poster', 'film poster painting', [...T, 'casaro'], {
      ...P,
      look: 'Renato Casaro poster look: hyper-detailed Italian painted action and adventure posters, muscular heroes, explosions, dramatic sunsets and glossy realism.',
      subject:
        'paint the subject as a glossy heroic figure amid explosions and dramatic landscapes.',
      color: 'Sunset orange, sky blue and glossy skin tones.',
      light: 'Dramatic sunset backlight and explosion glow.',
      texture: 'Glossy detailed painting.',
      camera: 'Heroic central figure over action vignettes.',
      mood: 'bold heroic action',
      render: 'Glossy Italian painted action poster.',
      key: 'Casaro glossy realism; heroes; explosions; sunsets',
      briefs: [
        'A muscular retired lifeguard stands heroically on a jet ski as a volcano erupts behind her and a pirate ship explodes in glossy painted detail, action poster titled "LAVA COAST" set exact.',
        'A sword-wielding shepherd rides a giant goat across a burning sunset toward a crumbling fortress, barbarian epic poster titled "HORNS OF FURY" in bold chrome letters.',
        'A single painted dagger stuck in desert sand glows orange against a dramatic sunset, adventure poster titled "SAND KING" stretched across the sky.',
      ],
    }),
    cr('Mondo Screenprint Alternative Poster', 'screenprint film poster', [...T, 'mondo'], {
      ...P,
      look: 'Mondo alternative movie poster look (Olly Moss, Tyler Stout, Martin Ansin): limited-color screenprints, clever negative space, dense character collages or minimal symbolic wit.',
      subject:
        'reinterpret the subject as a limited-color screenprint with clever negative space or dense collage.',
      color: 'Three to five flat screenprint inks.',
      light: 'Flat printed light.',
      texture: 'Screenprint ink layers and paper texture.',
      camera: 'Clever negative-space composition or dense collage.',
      mood: 'clever collector cool',
      render: 'Limited-edition screenprint poster.',
      key: 'Mondo screenprint; negative space; limited inks',
      briefs: [
        'A monster’s face hides in the negative space between two astronauts’ helmets while stars are printed in pale cream ink, five-color screenprint for the space horror "VACANCY" with its title set exact.',
        'Every character and horse of an invented western fills the silhouette of a cowboy hat in a dense screenprint collage, poster titled "LONG RIDE HOME" in the hat band.',
        'A single screenprinted key casts a shadow shaped like a house in three inks, minimal poster titled "TENANT" printed small at the bottom.',
      ],
    }),
    cr(
      'Stenberg Brothers - Soviet Constructivist Film Poster',
      'constructivist film poster',
      [...T, 'stenberg'],
      {
        ...P,
        look: 'Stenberg Brothers Soviet film poster look: constructivist diagonals, photomontage faces, dynamic geometry, bold red and black and kinetic cinematic energy.',
        subject: 'build the subject from photomontage fragments and bold constructivist geometry.',
        color: 'Red, black, cream and one accent.',
        light: 'Flat graphic light.',
        texture: 'Lithograph print and photomontage.',
        camera: 'Dynamic diagonals and spirals.',
        mood: 'kinetic revolutionary energy',
        render: 'Constructivist lithograph poster.',
        key: 'Stenberg constructivism; diagonals; photomontage; red and black',
        briefs: [
          'A determined train driver’s photomontage face spins inside a giant red wheel while tracks shoot diagonally across a cream field, constructivist poster for the silent film "ЛОКОМОТИВ" with its title set exact.',
          'A spiral of photographed hands and gears whirls around a dancing welder, factory drama poster titled "ИСКРА" in bold diagonal constructivist letters.',
          'A single red diagonal slices a black field with a small photographed eye at its tip, avant-garde poster titled "ГЛАЗ" along the diagonal.',
        ],
      },
    ),
    cr('Nineties Floating-Heads Photo Poster', 'film poster design', [...T, 'floating-heads'], {
      ...P,
      look: 'Nineties Hollywood floating-heads photo poster look: stacked celebrity-style headshots floating over a sky, teal-orange grading, action vignette below and glossy photo retouching.',
      subject:
        'arrange the subject as stacked floating photographic heads above a small action scene.',
      color: 'Teal and orange grading with glossy highlights.',
      light: 'Glossy studio headshot light.',
      texture: 'Retouched photo compositing.',
      camera: 'Stacked heads above a small action vignette.',
      mood: 'glossy blockbuster hype',
      render: 'Glossy nineties photo poster composite.',
      key: 'Floating heads; teal-orange; stacked headshots',
      avoid: ['real celebrity likeness'],
      briefs: [
        'The giant floating heads of a grumpy veterinarian and a cheerful parrot stack over a teal and orange sky above a tiny car chase through a pet shop, buddy-cop poster titled "BEAK & BADGE" set exact.',
        'Six worried floating faces hover above a tiny flooding shopping mall, nineties disaster poster titled "HIGH WATER" in chrome letters.',
        'The floating head of a startled goldfish glares out of a glossy teal and orange sky, comedy poster titled "FISH OUT" in bold letters.',
      ],
    }),
    cr('A24 Minimal Photo Poster', 'indie film poster design', [...T, 'a24'], {
      ...P,
      look: 'A24-era indie film poster look: minimal art-directed photography, strange quiet imagery, lots of negative space, muted or single-tone color and small elegant typography areas.',
      subject:
        'present the subject in a single strange quiet photographic moment with lots of empty space.',
      color: 'Muted single-tone color or soft pastel grading.',
      light: 'Natural soft light with eerie calm.',
      texture: 'Fine grain photographic print.',
      camera: 'Minimal centered or offset composition with negative space.',
      mood: 'quiet uncanny indie',
      render: 'Minimal art-directed photo poster.',
      key: 'A24 minimal; negative space; uncanny calm; muted tones',
      briefs: [
        'A woman in a pale blue dress stands in a vast field with a goat balanced on her shoulders, both staring calmly under a flat white sky, folk drama poster titled "THE GIFT" set small and exact.',
        'A birthday cake sits on an empty lawn at dusk with every candle burning sideways, family horror poster titled "WISH" in small elegant letters.',
        'A single chair floats a few inches above a pale pink floor in an empty room, psychological drama poster titled "STILL" tucked into a corner.',
      ],
    }),
    cr(
      'Blaxploitation Painted Poster',
      'seventies film poster painting',
      [...T, 'blaxploitation'],
      {
        ...P,
        look: 'Seventies blaxploitation poster look: bold painted heroes in afros and leather, funky action collages, neon urban nights and swaggering color.',
        subject: 'paint the subject as a swaggering hero surrounded by action collage.',
        color: 'Funky orange, purple, gold and black.',
        light: 'Neon night glow and dramatic highlights.',
        texture: 'Painted illustration with bold outlines.',
        camera: 'Central hero with action vignettes around.',
        mood: 'funky swaggering cool',
        render: 'Painted seventies action poster.',
        key: 'Blaxploitation swagger; funky collage; neon nights',
        briefs: [
          'A swaggering librarian in a leather coat and huge afro holds overdue books while car chases and roller discos swirl around her, seventies action poster titled "OVERDUE" set exact in funky letters.',
          'A cool private eye in a purple suit leans on a gold car under neon lights, detective poster titled "GOLD ROLLER" in chunky seventies lettering.',
          'A single platform boot kicks through a painted neon sign in a burst of orange, action poster titled "KICKBACK" exploding from the glass.',
        ],
      },
    ),
    cr('Shaw Brothers Kung Fu Poster', 'Hong Kong film poster', [...T, 'shaw-brothers'], {
      ...P,
      look: 'Shaw Brothers kung fu poster look: dynamic painted fighters mid-kick, collaged action stills, bold red and yellow and dramatic seventies Hong Kong energy.',
      subject: 'paint the subject as dynamic fighters mid-kick among collaged action scenes.',
      color: 'Bold red, yellow and black.',
      light: 'Dramatic flat printed light.',
      texture: 'Painted art and halftone stills.',
      camera: 'Dynamic diagonal fight compositions.',
      mood: 'explosive martial energy',
      render: 'Seventies Hong Kong kung fu poster.',
      key: 'Shaw Brothers kicks; collaged stills; red and yellow',
      briefs: [
        'An elderly noodle master leaps mid-kick over bandits while flying bowls and chopstick duels explode around her in red and yellow, kung fu poster titled "NOODLE FIST" with its title set exact.',
        'Two monks clash on a bamboo bridge in painted diagonal action above a misty gorge, temple epic poster titled "BRIDGE OF TEN MONKS" in brush letters.',
        'A single flying bamboo staff spins across a bold red background trailing motion lines, martial poster titled "THE STAFF" in bold yellow brush strokes.',
      ],
    }),
    cr('Czech Surrealist Film Poster', 'Czech film poster', [...T, 'czech-poster'], {
      ...P,
      look: 'Sixties Czechoslovak film poster look: surrealist photo collage, playful graphic shapes, odd juxtapositions and handmade print textures.',
      subject:
        'collage the subject with playful surreal juxtapositions of photo and graphic shapes.',
      color: 'Muted print colors with one bright accent.',
      light: 'Flat collage light.',
      texture: 'Photo collage, print grain and cut edges.',
      camera: 'Playful surreal collage composition.',
      mood: 'playful surreal wit',
      render: 'Sixties surrealist collage poster.',
      key: 'Czech surreal collage; odd juxtapositions; print grain',
      briefs: [
        'A man in a bowler hat with a teapot instead of a head pours tea into the hands of a smiling woman cut from an old photograph, Czech comedy poster titled "ČAJ" set exact.',
        'Two cut-out lovers sit inside a giant pear floating over a rooftop city, surreal romance poster titled "HRUŠKA" in playful collage letters.',
        'A photographed hand holds a cut-paper moon on a string over a dark collage town, dreamy poster titled "MĚSÍC" glued in cut letters.',
      ],
    }),
    cr('Cuban ICAIC Silkscreen Film Poster', 'Cuban film poster', [...T, 'icaic'], {
      ...P,
      look: 'Cuban ICAIC film poster look: hand-pulled silkscreen, bold flat psychedelic color, graphic symbolism and inventive minimal imagery.',
      subject: 'reduce the subject to bold flat silkscreen shapes with graphic symbolism.',
      color: 'Bold flat psychedelic colors.',
      light: 'Flat screenprint light.',
      texture: 'Hand-pulled silkscreen ink layers.',
      camera: 'Bold symbolic central image.',
      mood: 'bold inventive energy',
      render: 'Hand-pulled Cuban silkscreen poster.',
      key: 'ICAIC silkscreen; flat color; graphic symbolism',
      briefs: [
        'A fisherman’s silhouette is built from overlapping psychedelic waves of magenta, orange and green silkscreen ink with a fish for an eye, Cuban film poster titled "EL PESCADOR" set exact.',
        'A trumpet bursts into flat colored silkscreen petals that spiral into a dancing couple, musical poster titled "SON" in bold flat letters across the bell.',
        'A single flat green palm leaf casts a shadow shaped like a guitar on a bright orange field, drama poster titled "LA PALMA" pulled in two inks.',
      ],
    }),
    cr('Richard Amsel - Painted Portrait Collage Poster', 'film poster painting', [...T, 'amsel'], {
      ...P,
      look: 'Richard Amsel poster look: elegant painted portraits blended into collage, nostalgic glamour, soft pencil and paint and art-deco-tinged sophistication.',
      subject: 'paint the subject as elegant portraits blended into nostalgic collage.',
      color: 'Soft nostalgic sepia, rose and gold.',
      light: 'Soft glamorous light.',
      texture: 'Pencil and paint blending on board.',
      camera: 'Elegant portrait collage composition.',
      mood: 'nostalgic glamorous elegance',
      render: 'Elegant painted portrait collage poster.',
      key: 'Amsel portraits; nostalgic glamour; collage',
      briefs: [
        'An aging film projectionist’s elegant painted portrait dissolves into old theater marquees, dancers and a rainy train platform in soft sepia and rose, nostalgia poster titled "THE LAST REEL" set exact.',
        'A jazz singer’s painted portrait blends into a glittering nightclub scene full of dancers and smoke, mystery poster titled "MIDNIGHT AT THE ORCHID" in art deco letters.',
        'A single vintage movie ticket floats in soft painted gold light above a velvet seat, nostalgic poster titled "ADMIT ONE" in elegant script.',
      ],
    }),
    cr(
      'Reynold Brown - Fifties Sci-Fi B-Movie Poster',
      'fifties film poster painting',
      [...T, 'reynold-brown'],
      {
        ...P,
        look: 'Reynold Brown fifties B-movie poster look: giant monsters and alien menaces towering over screaming crowds, painted realism and lurid atomic-age color.',
        subject:
          'paint the subject as a giant atomic-age menace towering over tiny fleeing crowds.',
        color: 'Lurid atomic green, red and yellow.',
        light: 'Dramatic menace lighting from below.',
        texture: 'Painted realism on board.',
        camera: 'Towering low-angle menace over crowds.',
        mood: 'lurid atomic thrill',
        render: 'Painted fifties sci-fi poster.',
        key: 'Reynold Brown giant menace; atomic color; screaming crowds',
        briefs: [
          'A colossal housecat with glowing green eyes towers over a small desert town as residents flee past a diner in lurid painted realism, atomic-age poster titled "THE CAT THAT ATE PHOENIX" set exact.',
          'A giant jellyfish floats over a drive-in theater full of screaming couples in convertibles, invasion poster titled "IT DRIFTED FROM SPACE" in dripping atomic letters.',
          'A single giant footprint glows radioactive green in a painted cornfield at night, sci-fi poster titled "STEP ONE" in bold fifties lettering.',
        ],
      },
    ),
    cr('Tadanori Yokoo - Japanese Pop Theater Poster', 'Japanese pop poster', [...T, 'yokoo'], {
      ...P,
      look: 'Tadanori Yokoo poster look: Japanese pop art collage, rising-sun rays, psychedelic color, Mount Fuji, trains and dense symbolic pop imagery.',
      subject: 'collage the subject with rising-sun rays and dense pop symbolism.',
      color: 'Psychedelic pop red, pink, blue and gold.',
      light: 'Flat pop light with radiant rays.',
      texture: 'Silkscreen collage texture.',
      camera: 'Dense symmetrical pop compositions.',
      mood: 'psychedelic pop mysticism',
      render: 'Japanese pop art poster.',
      key: 'Yokoo rising-sun rays; pop collage; psychedelic',
      briefs: [
        'A sumo wrestler with angel wings rises between radiant rising-sun rays flanked by bullet trains, waves and a pink Mount Fuji, underground theater poster titled "天使の相撲" set exact.',
        'A guitarist floats inside a giant lotus surrounded by radiant pop rays and tiny steam trains, music film poster titled "蓮" in bold pop letters.',
        'A single steam locomotive bursts through a sunburst of pink and gold rays over a stylized sea, travel film poster titled "夜行列車" in the sky.',
      ],
    }),
    cr(
      'Enzo Sciotti - Italian Giallo Poster',
      'Italian horror poster painting',
      [...T, 'sciotti'],
      {
        ...P,
        look: 'Enzo Sciotti Italian horror and giallo poster look: lurid painted terror, black-gloved killers, glinting knives, screaming faces and saturated red.',
        subject: 'paint the subject with lurid giallo terror and glinting menace.',
        color: 'Saturated red, black and lurid purple.',
        light: 'Lurid colored lighting.',
        texture: 'Painted realism with lurid color.',
        camera: 'Terrifying close-up compositions.',
        mood: 'lurid stylish terror',
        render: 'Painted Italian giallo poster.',
        key: 'Sciotti giallo; black gloves; glinting knives; saturated red',
        briefs: [
          'A black-gloved hand holds a glinting sewing needle above a fashion model’s terrified eye reflected in a shattered mirror, all bathed in lurid red, giallo poster titled "L’AGO" set exact.',
          'A screaming opera singer’s face splits into shards of stained glass under purple light, horror mystery poster titled "LA VOCE" in sharp letters.',
          'A single black leather glove rests on a red velvet chair under lurid purple light, thriller poster titled "IL GUANTO" in elegant red letters.',
        ],
      },
    ),
    cr('Hong Kong Nineties Action Poster', 'Hong Kong film poster', [...T, 'hk-nineties'], {
      ...P,
      look: 'Nineties Hong Kong action poster look: dual-pistol heroes, doves, slow-motion explosions, cool sunglasses, glossy photo montage and neon city nights.',
      subject: 'compose the subject as glossy photo montage with heroic slow-motion action.',
      color: 'Neon blue, fire orange and glossy black.',
      light: 'Explosion glow and neon light.',
      texture: 'Glossy photo montage.',
      camera: 'Heroic montage with doves and explosions.',
      mood: 'heroic bloodshed cool',
      render: 'Glossy Hong Kong action poster montage.',
      key: 'HK nineties montage; doves; explosions; sunglasses',
      avoid: ['real celebrity likeness'],
      briefs: [
        'A cool dim sum chef in sunglasses leaps sideways through a restaurant in slow motion as white doves and bamboo baskets explode in glossy neon montage, Hong Kong action poster titled "DUMPLING HEAT" set exact.',
        'Two rival tailors face off across a rain-slick neon street with measuring tapes drawn like pistols, triad drama poster titled "THE CUT" in bold chrome letters.',
        'A single white dove flies through a burst of orange explosion light over a harbor, action poster titled "HARBOUR FIRE" in glossy letters.',
      ],
    }),
    cr(
      'Criterion Collection Art-Directed Cover',
      'art house film cover design',
      [...T, 'criterion'],
      {
        ...P,
        look: 'Criterion Collection cover art look: commissioned illustrations and restrained art direction, clever conceptual imagery, limited palettes and elegant art house design.',
        subject:
          'reinterpret the subject as a clever conceptual illustration with restrained art direction.',
        color: 'Limited elegant palettes.',
        light: 'Soft flat illustration light.',
        texture: 'Refined illustration or print texture.',
        camera: 'Elegant conceptual composition.',
        mood: 'thoughtful art house elegance',
        render: 'Refined art-directed cover illustration.',
        key: 'Criterion conceptual art; restraint; limited palette',
        briefs: [
          'A lonely ferryman’s small boat is drawn as a single brushstroke on a vast grey sea with a paper boat floating in its reflection, art-house cover titled "FERJAN" set exact in restrained type.',
          'Three teacups on a table cast shadows shaped like three generations of one family, cover for a Japanese family drama titled "TEA AT FOUR" in quiet letters.',
          'A single red thread crosses an otherwise empty cream cover with one tiny knot at the center, film cover titled "THE KNOT" set small.',
        ],
      },
    ),
  ],
};

export default spec;
