import type { Spec } from '../tools/apply';
import { MATERIAL_AVOID as AVOID, material } from './_material';

const spec: Spec = {
  pack: 'pack_09',
  category: '1. Natural Materials',
  updates: {
    'SP09-001': {
      dna: material(
        'Raw oak wood: unfinished quarter-sawn oak with open grain, ray flecks and dry, matte fibers.',
        'the target becomes carved or built from raw oak, with grain following its form and tool marks at edges.',
        'Pale honey to mid brown with darker grain lines.',
        'Warm side light raking across the open grain.',
        'Open-pore oak grain, medullary ray flecks, splits and adze marks.',
        'Solid, honest, warm and old.',
        'raw open oak grain; ray flecks; tool marks; matte dry fibers',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a life-size warhorse carved entirely from raw oak, grain flowing along its muscles and adze marks on the mane, standing in a misty meadow. No text or logo.',
        "Photograph of a knight's full armor made of raw unfinished oak planks and pegs, worn by an adult man in a forest clearing. No text or logo.",
        'Photograph of a raw oak spiral staircase rising through an empty stone tower, grain lines flowing up each step. No text or logo.',
      ],
    },
    'SP09-002': {
      dna: material(
        'Polished mahogany: deep red-brown hardwood with a mirror-like French polish and flowing figure.',
        'the target is made of polished mahogany with a deep lacquered finish and figure that follows its curves.',
        'Deep red-brown to near-black with amber highlights.',
        'Warm lamp light producing glossy reflections.',
        'French-polished mahogany with ribbon figure, deep gloss and inlay lines.',
        'Rich, formal, warm and antique.',
        'polished mahogany gloss; ribbon figure; amber highlights; deep red-brown',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a full-size dragon skeleton made of polished mahogany with brass joints displayed in a candlelit hall. No text or logo.',
        'Photograph of a polished mahogany suit of armor with inlaid lines standing in a library corner. No text or logo.',
        'Photograph of a rowboat made of mirror-polished mahogany gliding on a black lake. No text or logo.',
      ],
    },
    'SP09-003': {
      dna: material(
        'Birch bark: papery white bark with dark horizontal lenticels, curling peels and chalky texture.',
        'the target is wrapped or built from birch bark sheets with peeling curls and dark lenticel dashes.',
        'Chalk white, cream and charcoal marks with peach inner bark.',
        'Soft cool daylight.',
        'Papery peeling bark layers with black lenticels and curls.',
        'Northern, quiet, delicate and wild.',
        'papery white bark; dark lenticels; curling peels; peach inner layer',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a tall hooded figure whose cloak is layers of peeling birch bark standing in a snowy forest. No text or logo.',
        'Photograph of a violin made from curled birch bark resting on moss. No text or logo.',
        'Photograph of a small chapel clad entirely in birch bark sheets at dusk. No text or logo.',
      ],
    },
    'SP09-004': {
      dna: material(
        'Polished granite: speckled crystalline stone polished to a hard reflective surface.',
        'the target is carved from granite and polished, with mineral speckles visible across its surfaces.',
        'Grey, black and pink speckle or black granite with mica sparkle.',
        'Crisp light producing sharp reflections.',
        'Polished granite with feldspar, quartz and mica grains.',
        'Hard, permanent, cold and monumental.',
        'polished speckled granite; mica sparkle; hard reflections; crystalline grain',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a colossal polished black granite bull standing in a rain-soaked plaza, reflections sliding on its flanks. No text or logo.',
        'Photograph of a grand piano carved from polished pink granite in an empty hall. No text or logo.',
        'Photograph of a polished grey granite throne on a windy cliff. No text or logo.',
      ],
    },
    'SP09-005': {
      dna: material(
        'Rough sandstone: layered sedimentary stone with granular surface and warm bands.',
        'the target is carved from rough sandstone with visible bedding layers and eroded edges.',
        'Ochre, rust, cream and red banding.',
        'Low warm sun that emphasizes grain.',
        'Granular sandstone with bedding layers and wind erosion.',
        'Ancient, eroded, warm and desert-like.',
        'rough granular sandstone; bedding bands; wind erosion; warm ochre',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a giant sandstone statue of a kneeling knight half-eroded by wind, bands of red and ochre across the armor. No text or logo.',
        'Photograph of a sandstone locomotive with eroded edges standing on rails. No text or logo.',
        'Photograph of a sandstone harp in a quiet courtyard. No text or logo.',
      ],
    },
    'SP09-006': {
      dna: material(
        'Carrara marble: white marble with soft grey veining, polished or finely carved.',
        'the target is carved from white Carrara marble with grey veins following its form.',
        'Warm white with soft grey veining.',
        'Soft diffused light showing subsurface glow.',
        'Fine crystalline marble with translucent edges and polished or chiselled finish.',
        'Classical, serene, pure and timeless.',
        'white Carrara marble; grey veining; translucent glow; carved detail',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a veiled mourner carved from Carrara marble, the veil translucent at the edges, in a ruined chapel. No text or logo.',
        'Photograph of a marble dragon coiled on a staircase, grey veins along its scales. No text or logo.',
        'Photograph of a marble bicycle leaning on a stone wall. No text or logo.',
      ],
    },
    'SP09-007': {
      dna: material(
        'Split slate: dark layered stone that cleaves into thin sheets with sharp, stepped edges.',
        'the target is built from split slate sheets or carved slate showing layered cleavage.',
        'Blue-grey, charcoal and green-grey with rust stains.',
        'Overcast light showing the stepped layers.',
        'Cleaved slate sheets with sharp edges and rough riven faces.',
        'Austere, cold, rugged and old.',
        'split slate sheets; stepped cleavage; riven faces; blue-grey',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a slate-plated dragon made of overlapping split slate sheets perched on a quarry ledge. No text or logo.',
        'Photograph of an adult knight in armor made of riven slate scales in the rain. No text or logo.',
        'Photograph of a slate-shingled rowing boat on a grey loch. No text or logo.',
      ],
    },
    'SP09-008': {
      dna: material(
        'Mossy rock: weathered stone covered in cushions of green moss and lichen.',
        'the target turns into weathered stone covered with thick moss cushions and lichen patches.',
        'Vivid moss green, lichen yellow and grey stone.',
        'Soft, damp forest light.',
        'Velvety moss cushions, crusty lichen and damp stone.',
        'Ancient, quiet, overgrown and living.',
        'moss cushions; lichen patches; damp weathered stone; forest green',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a sleeping giant made of mossy rock, moss cushions on its shoulders, in a misty glen. No text or logo.',
        "Photograph of a knight's helmet turned to mossy stone resting on a forest floor. No text or logo.",
        'Photograph of a mossy stone telephone booth in a forest. No text or logo.',
      ],
    },
    'SP09-009': {
      dna: material(
        'River stones: smooth, rounded pebbles fitted together like a mosaic.',
        'the target is assembled from smooth rounded river stones fitted tightly together.',
        'Grey, ochre, slate and white pebbles.',
        'Soft light, with some stones wet and glossy.',
        'Water-polished stones with rounded edges.',
        'Calm, patient, natural and grounded.',
        'fitted rounded pebbles; water-polished; wet gloss; mosaic packing',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a life-size bear built from fitted river stones standing in a shallow stream. No text or logo.',
        'Photograph of a cloak of river pebbles draped on a standing figure on a beach. No text or logo.',
        'Photograph of a river-stone armchair in a sunlit room. No text or logo.',
      ],
    },
    'SP09-010': {
      dna: material(
        'Obsidian: black volcanic glass with conchoidal fractures, razor edges and glassy sheen.',
        'the target is knapped from obsidian, with shell-like fracture scars and sharp edges.',
        'Glossy black with smoky brown and rainbow sheen.',
        'Hard rim light showing the glassy edges.',
        'Volcanic glass with conchoidal ripples and translucent edges.',
        'Dangerous, sleek, dark and primordial.',
        'black volcanic glass; conchoidal fractures; razor edges; rainbow sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an obsidian crown with knapped ripple facets on a black velvet cushion. No text or logo.',
        'Photograph of an adult woman in armor of knapped obsidian plates with rainbow sheen on a lava field. No text or logo.',
        'Photograph of an obsidian wolf sculpture on a snowy ridge. No text or logo.',
      ],
    },
    'SP09-011': {
      dna: material(
        'Wolf fur: dense grey-brown guard hairs over a soft underfur, with directional flow.',
        'the target is covered in dense wolf-like fur with directional flow following its form.',
        'Grey, silver, tan and black tipped fur.',
        'Backlight halo on the fur edges.',
        'Guard hairs and soft underfur with natural direction.',
        'Wild, warm, primal and alert.',
        'dense grey fur; guard hairs; directional flow; backlit halo',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a grandfather clock covered in dense wolf fur standing in a snowbound cabin. No text or logo.',
        "Photograph of a knight's cape and helmet crest made of wolf fur on a frozen battlefield. No text or logo.",
        'Photograph of an armchair covered in silver wolf fur by a fire. No text or logo.',
      ],
    },
    'SP09-012': {
      dna: material(
        'Snake scales: overlapping keeled or smooth scales with iridescent sheen and patterned bands.',
        'the target is covered in overlapping snake scales with patterned bands following its form.',
        'Olive, emerald, black and gold banding with iridescence.',
        'Raking light that shows each scale edge.',
        'Overlapping keeled scales with glossy iridescent sheen.',
        'Sleek, dangerous, hypnotic and exotic.',
        'overlapping snake scales; patterned bands; iridescent sheen; scale edges',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a violin covered in emerald-and-gold snake scales on a black cloth. No text or logo.',
        'Photograph of an adult woman in a gown of iridescent snake scales in a desert ruin. No text or logo.',
        'Photograph of a snake-scaled carriage in a rainy street. No text or logo.',
      ],
    },
    'SP09-013': {
      dna: material(
        'Bird feathers: overlapping contour feathers with barbs, shafts and iridescent sheen.',
        'the target is covered in overlapping feathers laid in rows like plumage.',
        'Brown, cream, black and iridescent blue-green.',
        'Soft backlight showing feather barbs.',
        'Overlapping feathers with visible barbs and shafts.',
        'Light, graceful, alive and soft.',
        'overlapping feathers; barbs and shafts; plumage rows; iridescent sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a feathered armored helmet with overlapping raven feathers on a battlefield at dusk. No text or logo.',
        'Photograph of a grand staircase banister covered in owl feathers. No text or logo.',
        'Photograph of a feathered rowboat on a still pond. No text or logo.',
      ],
    },
    'SP09-014': {
      dna: material(
        'Coral reef: branching and brain corals growing over the target in bright calcareous forms.',
        'the target is overgrown or formed from living coral structures, branching and brain coral.',
        'Coral pink, orange, purple, cream and turquoise.',
        'Underwater-like caustic light.',
        'Calcareous coral with polyps, ridges and porous texture.',
        'Vibrant, alive, oceanic and intricate.',
        'branching and brain coral; polyps; porous calcareous texture; caustic light',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a sunken knight's armor overgrown with pink and orange coral standing on a sea bed. No text or logo.",
        'Photograph of a coral chandelier in a dark ballroom. No text or logo.',
        'Photograph of a coral-formed throne in a sea cave. No text or logo.',
      ],
    },
    'SP09-015': {
      dna: material(
        'Honeycomb wax: hexagonal beeswax comb with golden translucent cells and honey drips.',
        'the target is built from hexagonal honeycomb with some cells filled and dripping.',
        'Amber, gold and pale yellow wax.',
        'Backlight making wax cells glow.',
        'Hexagonal wax cells, honey drips and waxy sheen.',
        'Warm, sweet, organic and industrious.',
        'hexagonal wax cells; honey drips; glowing amber; waxy sheen',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a honeycomb crown dripping honey on a stone altar. No text or logo.',
        'Photograph of a honeycomb suit of armor glowing amber in sunlight. No text or logo.',
        'Photograph of a honeycomb lantern in a dark barn. No text or logo.',
      ],
    },
    'SP09-016': {
      dna: material(
        'Glacier ice: dense blue ice with trapped bubbles, fracture planes and melt-smoothed surfaces.',
        'the target is made of glacier ice with blue depths and trapped bubbles.',
        'Deep cyan-blue with white frosted edges.',
        'Backlight showing blue translucency.',
        'Dense ice with bubbles, fractures and melt ridges.',
        'Cold, ancient, pure and silent.',
        'deep blue glacier ice; trapped bubbles; fracture planes; translucent depth',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a glacier-ice warhorse with a knight rider, blue depths and trapped bubbles, on a frozen plain. No text or logo.',
        'Photograph of a grand piano carved from glacier ice in a dark hall. No text or logo.',
        'Photograph of a glacier-ice cathedral door. No text or logo.',
      ],
    },
    'SP09-044': {
      dna: material(
        'Sea sponge: porous organic sponge with irregular holes and soft tan fibers.',
        'the target is made of porous natural sea sponge with irregular holes.',
        'Tan, sand, ochre and pale yellow.',
        'Soft side light showing pores.',
        'Porous spongy fibers with irregular holes.',
        'Soft, strange, organic and absorbent.',
        'porous sea sponge; irregular holes; soft tan fibers',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a sea-sponge knight's helmet on a beach at dusk. No text or logo.",
        'Photograph of an armchair made of porous sea sponge in a white room. No text or logo.',
        'Photograph of a sponge-textured bust of a queen on a plinth. No text or logo.',
      ],
    },
    'SP09-055': {
      dna: material(
        'Crystal and gemstone: faceted translucent crystal with internal refractions and color zones.',
        'the target is carved from gem crystal with facets and inner refractions.',
        'Amethyst purple, emerald, sapphire or clear quartz.',
        'Point lights producing refraction and fire.',
        'Faceted crystal with inclusions and internal reflections.',
        'Precious, magical, cold and brilliant.',
        'faceted gem crystal; internal refraction; inclusions; spectral fire',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of an amethyst-crystal dragon skull catching candlelight in a cave. No text or logo.',
        "Photograph of a sapphire-crystal knight's gauntlet on a velvet cloth. No text or logo.",
        'Photograph of a clear quartz rocking horse in a nursery. No text or logo.',
      ],
    },
    'SP09-063': {
      dna: material(
        'Cobweb: dense dusty spider silk draped in layers over the target.',
        'the target is draped in thick layers of dusty cobweb strands and sheets.',
        'Grey-white strands with dust and dark gaps.',
        'Backlight catching the strands.',
        'Silk strands, sagging sheets and dust.',
        'Abandoned, eerie, still and forgotten.',
        'dusty cobweb layers; backlit strands; sagging sheets',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a knight's armor on a stand draped in thick dusty cobwebs in an abandoned hall. No text or logo.",
        'Photograph of a grand piano under layers of cobweb. No text or logo.',
        'Photograph of a wedding cake shrouded in cobwebs on a long table. No text or logo.',
      ],
    },
    'SP09-066': {
      dna: material(
        'Beach sand: fine packed sand sculpted into the target, with grain texture and crumbling edges.',
        'the target is sculpted from packed beach sand with crumbling edges and fine grain.',
        'Warm beige, golden and wet darker sand.',
        'Low sun raking the grains.',
        'Packed fine sand grains with crumbling edges and shell fragments.',
        'Fleeting, playful, warm and fragile.',
        'packed sand sculpture; crumbling edges; fine grains; wet and dry tones',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a sand-sculpted sleeping dragon on a beach with the tide approaching. No text or logo.',
        'Photograph of a sand knight on a sand horse, crumbling at the edges. No text or logo.',
        'Photograph of a sand-sculpted cathedral facade at sunset. No text or logo.',
      ],
    },
    'SP09-068': {
      dna: material(
        'Cooled lava rock: porous black-red basalt scoria with vesicles and ropy flow texture.',
        'the target is made of cooled lava rock with vesicles and ropy flow texture.',
        'Charcoal black, rust red and ash grey.',
        'Hard side light revealing pores.',
        'Vesicular basalt, scoria and ropy pahoehoe flow.',
        'Harsh, volcanic, primal and rough.',
        'porous lava rock; vesicles; ropy flow; charcoal and rust',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a lava-rock golem kneeling on black sand. No text or logo.',
        'Photograph of a throne of ropy lava rock in a volcanic cave. No text or logo.',
        'Photograph of a lava-rock teapot on a table. No text or logo.',
      ],
    },
    'SP09-079': {
      dna: material(
        'Mother of pearl: iridescent nacre with shimmering color shifts and layered sheen.',
        'the target is inlaid or carved from mother-of-pearl nacre with color-shifting sheen.',
        'Pearl white with pink, blue and green iridescence.',
        'Soft light producing shifting iridescence.',
        'Layered nacre with shimmer and inlay seams.',
        'Precious, delicate, oceanic and luminous.',
        'iridescent nacre; color-shifting sheen; inlay seams',
      ),
      avoid: AVOID,
      briefs: [
        "Photograph of a mother-of-pearl knight's helmet shimmering on a dark shore. No text or logo.",
        'Photograph of a mother-of-pearl violin. No text or logo.',
        'Photograph of a nacre-inlaid carriage in a moonlit courtyard. No text or logo.',
      ],
    },
    'SP09-080': {
      dna: material(
        'Dragon scale: large armored overlapping scales with ridges, metallic sheen and battle scratches.',
        'the target is covered in large overlapping dragon scales with ridges and metallic sheen.',
        'Bronze, crimson, emerald or obsidian with metallic highlights.',
        'Hard raking light showing ridges.',
        'Thick overlapping scales with ridges, scratches and metallic sheen.',
        'Powerful, armored, mythic and fierce.',
        'large overlapping dragon scales; ridges; metallic sheen; battle scratches',
      ),
      avoid: AVOID,
      briefs: [
        'Photograph of a shield covered in crimson dragon scales leaning on a burnt tree. No text or logo.',
        'Photograph of an adult woman in a dragon-scale coat with metallic bronze sheen in a storm. No text or logo.',
        'Photograph of a dragon-scaled door in a castle wall. No text or logo.',
      ],
    },
  },
};

export default spec;
